### ISSUE TITLE
Query hints

### ISSUE THREAD

**Issue by AlekSi** [VictoriaMetrics/VictoriaMetrics#10]
FAQ [says](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/FAQ#why-victoriametrics-doesnt-support-prometheus-remote-read-api) this about Prometheus Remote Read API:

> Remote read API requires transferring all the raw data for all the metrics in the query over the given time range. For instance, if a query covers 1000 metrics with 10K values each, then the remote read API had to return 1000*10K=10M metric values to Prometheus.

That ignores the fact that Prometheus supports [query hints](https://github.com/prometheus/prometheus/issues/2580).

**Comment by valyala** [comment]
The linked issue contains the reason - query hints are experimental and it is unclear how to use them properly:
> This is unstructured and experimental as we don't know yet what if any of this will prove useful for things like downsampling optimisations on the other end.
> At some point (likely after the rest of remote read is considered non-experimental), this should be changed to proper structured data when we have a good idea from multiple implementations what information is needed.

**Comment by valyala** [comment]
Closing this question as resolved.
