### ISSUE TITLE
Remote write for Prometheus not working 

### ISSUE THREAD

**Issue by NikolayShama** [VictoriaMetrics/VictoriaMetrics#100]
I try to send metrics to remote storage VictoriaMetrics cluster but get errors that:
Jul 00 00:00:00 servename prometheus[19637]: level=error ts=2019-07-16T13:50:05.313Z caller=queue_manager.go:699 component=remote queue=0:http://localhost:8480/api/v1/write msg="non-recoverable error" count=10000 err="server returned HTTP status 400 Bad Request: unsupported path requested: \"/api/v1/write\""
My config in prometheus.yml
remote_write:
  - url: http://localhost:8480/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      max_shards: 100

netstat -tnlp | grep prod
tcp        0      0 0.0.0.0:8400            0.0.0.0:*               LISTEN      9414/vmstorage-prod
tcp        0      0 0.0.0.0:8401            0.0.0.0:*               LISTEN      9414/vmstorage-prod
tcp        0      0 0.0.0.0:8480            0.0.0.0:*               LISTEN      9415/vminsert-prod
tcp        0      0 0.0.0.0:8481            0.0.0.0:*               LISTEN      9407/vmselect-prod
tcp        0      0 0.0.0.0:8482            0.0.0.0:*               LISTEN      9414/vmstorage-prod

**Comment by NikolayShama** [comment]
already resolved

**Comment by tenmozes** [comment]
close an issue, feel free to reopen if any help is needed

**Comment by krakazyabra** [comment]
@NikolayShama how did you resolve it?  
I also have cluster version in kubernetes, but `:8480/api/v1/write` is for single-version.  
in prometheus.yaml i wrote  
```    remote_write:
      - url: https://victoriametrics-stage.wedos.org/insert
        queue_config:
          max_samples_per_send: 10000
          max_shards: 100
```  
in ingress  
```      - path: /insert*
        backend:
          serviceName: victoria-metrics-vminsert
          servicePort: 8480
```  
in service  
```  ports:
    - name: http
      port: 8480
      protocol: TCP
      targetPort: http
  selector:
    app: vminsert
```  
but still have errors like  
```level=error ts=2019-07-17T11:05:13.913Z caller=queue_manager.go:699 component=remote queue=0:https://victoriametrics-stage.domain.org/insert msg="non-recoverable error" count=213 err="server returned HTTP status 404 Not Found: <html>"```

**Comment by valyala** [comment]
Just for the reference - cluster version of VictoriaMetrics has different url paths comparing to single-node version. See [details here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#url-format).
