### ISSUE TITLE
Difference between data stored and query_range results for data with inconsistent intervals

### ISSUE THREAD

**Issue by Fusl** [VictoriaMetrics/VictoriaMetrics#1003]
I'm having a very similar, if not the same, issue as #977 and #996. My application writes a lot of data at very different intervals and I was kinda expecting VM to interpolate the data inside a single step interval but not outside of a step interval, but instead it does pretty much what the InfluxDB's `fill(previous)` option does: When a certain step is missing datapoints, unconditionally copy the last step.

The VM version used is `victoria-metrics-20201227-122315-tags-v1.51.0-0-g70df5f497` with `--storageDataPath=/storage --httpListenAddr=:8428 --retentionPeriod=10y --search.disableCache=true` as arguments.

An export from a test set in VM shows this data:
```
{
    "metric": {
        "__name__": "test_value"
    },
    "values": [
        100,
        4654,
        17474
    ],
    "timestamps": [
        1610146601116,
        1610146663412,
        1610146698891
    ]
}
```
query_range (`query=test_value&start=1610146590&end=1610146770&step=15`) however returns the following data:
```
{
    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "__name__": "test_value"
                },
                "values": [
                    [
                        1610146605,
                        "100"
                    ],
                    [
                        1610146620,
                        "100"
                    ],
                    [
                        1610146635,
                        "100"
                    ],
                    [
                        1610146650,
                        "100"
                    ],
                    [
                        1610146665,
                        "4654"
                    ],
                    [
                        1610146680,
                        "4654"
                    ],
                    [
                        1610146695,
                        "4654"
                    ],
                    [
                        1610146710,
                        "17474"
                    ],
                    [
                        1610146725,
                        "17474"
                    ],
                    [
                        1610146740,
                        "17474"
                    ]
                ]
            }
        ]
    }
}
```
This behavior is especially annoying when the application I have logs all HTTP requests into VM and Grafana is expected to show a `count()` of non-successful requests inside a single step but instead keeps copying the results from the previous step over to the next step, essentially showing incorrect data.

The described behavior causes graphs like these from InfluxDB
![image](https://user-images.githubusercontent.com/2349496/104074496-35c12b00-5208-11eb-9701-8d51f619e6cd.png)
![image](https://user-images.githubusercontent.com/2349496/104074656-92244a80-5208-11eb-91ff-f90c2cf2064d.png)

to show up like these from VM
![image](https://user-images.githubusercontent.com/2349496/104074593-699c5080-5208-11eb-8c1f-149674ddcf41.png)
![image](https://user-images.githubusercontent.com/2349496/104074687-a6684780-5208-11eb-9da3-9a51aea4203d.png)

The graphs from VM suggest that the application is failing when, in fact, the application is healthy and the data is just incorrectly interpolated.

Edit: I was able to work around the issue of VM duplicating metric data (similar to #996) by setting `search.maxStalenessInterval` to `1s` but now query_range is missing a lot of datapoints (that InfluxDB would otherwise return with a similar count query), probably ones that are not perfectly aligned with the step interval within a few seconds barrier of it (similar to #977).

**Comment by valyala** [comment]
If you push a single data point to VictoriaMetrics per each request, then try using `count_over_time(metric)` or `sum_over_time(metric)` functions from PromQL - see https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time .

While VictoriaMetrics accepts data points for a single time series with irregular intervals between them, such data doesn't align well with PromQL and MetricsQL data models. VictoriaMetrics also can provide not so good data compression for time series with data points at irregular intervals. So it is recommended converting the scheme above with `a data point push per each request` to a scheme with `a counter increment per each request with counter push at regular intervals`. Then either [increase()](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) or [rate()](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) functions could be used for building graphs shown in the initial message. See more details about counter type in Prometheus (and VictoriaMetrics) - https://prometheus.io/docs/concepts/metric_types/#counter .

**Comment by Fusl** [comment]
`*_over_time` queries are exactly what I was looking for in my usecase. Unfortunately I don't know much about PromQL yet so I didn't exactly find that query function at first.

I'll additionally look into aggregating the data before pushing it off to VM in pre-defined intervals, however, right now VM performs REALLY well compared to InfluxDB, even with the exact same dataset exported from InfluxDB.

Thanks a lot!

**Comment by paragor** [comment]
tip: if you push Statsd's metrics in VM via an intermediate Prometheus like this 
![image](https://user-images.githubusercontent.com/31911894/107314425-4f43e400-6ae0-11eb-872e-68386057bdfa.png)

`sum_over_time` and `count_over_time` will show wrong result (multiple of 2 or 3 of real). To fix that you should push statsd's metrics directly into VM like this

![image](https://user-images.githubusercontent.com/31911894/107314544-8ca87180-6ae0-11eb-846e-1b17d80d340b.png)
