### ISSUE TITLE
MetricsQL function ignore_step() required

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#1004]
When one wants to visualize counter values within grafana, grafana allows the user to specify the query (via *Metrics* field), whether to use the `/api/v1/query_range` or `/api/v1/query` prefix (via *Instant* button) and that's basically it. When it queries the datasource (e.g. VM), for an `Instant` query it adds `&time=A` and otherwise `&start=B&end=C&step=W`. Not sure yet how A gets determined, however, B and C are the beginning and end of the selected `local browser time` as unix epoch timestamp in seconds, W is basically the time in seconds represented by 2 adjacent datapoints (or pixels), i.e. W = (C-B)/(panel|chart width in px). Often a chart is ~1000px wide, so VM returns usually ~ m * 1000 timestamp+value pairs (m is the number of metrics matched by the query).

If one wants to visualize a chart, that's fine. However, if one just wants to show the delta or difference of the value at C and B, there seems to be no efficient way to get this value calculated, because *rate* does not accept expressions like `end()-start()` or `C-B`. Even if it would allow such expressions, VM would still apply/execute ~ m * 1000 calculations wrt. matched metrics instead of m - so very inefficent.

Therefore we need something like a `ignore_step(q)` function, which just resets the evaluation window passed via step parameter to the result of the `end-start` parameter (same way, what it does, if one does not pass a step parameter) of the request. This way it can be used in all range query requests, and e.g. in case of *delta()* it would just need to do something like `foreach m return {C, m.getVal(C) - m.getVal(B)}`.

Use cases for such queries are e.g. power consumption counters: when one just wants to display the power consumption within the selected `local browser time` period as a single value.

**Comment by jelmd** [comment]
The following quick & dirty modification does, what is needed: https://github.com/jelmd/VictoriaMetrics/commit/2cb77955e9894866f7f3a1667327d2bafa1cbf24

"Modifies" the http request, only - but this is sufficient wrt. grafana oddities ...

**Comment by valyala** [comment]
The desired behaviour is already supported via a request to `/api/v1/query` (aka instant query in Grafana). For example, the following request will return counter counter increase over one hour (1h) on a time range ending at the given `time=C`: `/api/v1/query?query=increase(m[1h])&time=C`. Grafana provides useful variable - `$__range` - which is automatically substituted by the selected time range on Grafana dashboard. See more details about this variable at https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__range . This variable can be used inside instant queries as `increase(m[$__range])` .

**Comment by jelmd** [comment]
The problem with `/api/v1/query` is, that grafana does not align the `time` parameter with the *local browser time* period. The other problem is, that `$__range` is simply not available, neither for the `relative time` nor the `Query` setting. If you use it, e.g. Query Inspector takes forever and the dashboard never updates the charts. At least 7.3.6 seems to allow '$__interval` and `$_interval_rate`, only - both useless.

**Comment by jelmd** [comment]
OK, I've thrown away the old and  setup+tested with a new grafana instance: this works. Auto completion still does not show `$__range`, but who cares - it works ;-). Using `increase()` now, because it seems to be the better choice and not much slower. Thanx again!
