### ISSUE TITLE
vmselect performance

### ISSUE THREAD

**Issue by Guoyuechuan** [VictoriaMetrics/VictoriaMetrics#1008]
I am using cluster version and doing a load testing on vmselect. It keeps sending requests via

`http://<vmselect>:8481/select/<accountID>/prometheus/api/v1/query_range`

as fast as possible. While the CPU usage is low(0.3) and the QPS is low(100).

What is the problem? Is there benchmark on vmselect?

**Comment by valyala** [comment]
Try sending multiple requests in parallel during the benchmark. Note also that a single request can saturate all the CPU cores on `vmselect` if it needs to fetch big number of time series and/or big number of data points. For example, the heaviest request - `{__name__!=''}` - needs to select all the data points for all time series in the database on the given `start ... end` time range, so it can require big amounts of CPU time, RAM, disk IO and network bandwidth.

**Comment by Guoyuechuan** [comment]
Thanks for the reply.
I am using the load testing tool https://github.com/tsenart/vegeta to send two requests in parallel. This tool sends the request 'infinitely' during one second by setting parameters. These two query requests are just aggreagation without filtering lablels. One will hit 1432(time series) * 4320(datapoints), the other will hit 48(time series) * 4320(datapoints).
The result is strange. Sometimes it can handle this load testing but with low CPU and QPS, sometimes it gives logs that informs max concurrency request number is reached and rejects all other requests, with even lower CPU and QPS.
I will arrange more different requests and see the results. If there is more information or explanation about the performance of the vmselect, that will be great!

**Comment by valyala** [comment]
I think you need to tune `-rate` and `-connections` command-line flags for `vegeta`. By default it tries sending 50 requests per second over up to 10K connections. This may explain low rps with low CPU usage on VictoriaMetrics side. This also may explain `max concurrency limit reached` error on vmselect side, since by default it limit the number of concurrent requests to the number of available CPU cores for vmselect. This means that you must run `vegeta` with `-connection=NumCPU` config, where `NumCPU` is the summary number of CPU cores available on all the `vmselect` nodes in the cluster.

**Comment by Guoyuechuan** [comment]
Thanks a lot! I just follow the direction below the `vegeta` project and it does not tune `-connection`. I will adjust these parameter and report the result later.

Thanks for the very helpful and very fast reply.

**Comment by Guoyuechuan** [comment]
Consequently, the vmselect uses 1 CPU core per pod and has about 160 RPS. This is in accord with the result in [https://valyala.medium.com/measuring-vertical-scalability-for-time-series-databases-in-google-cloud-92550d78d8ae](url)

There is another problem is that I limit the CPU number of vmselect pod to 4 while it cannot use these CPUs fully. If so, the RPS will be higher. I will try to figure out the this problem. This TSDB has the potential to show greater performance.

**Comment by Guoyuechuan** [comment]
I am figuring out the process of searching, which involves `vmselect` and `vmstorage`. As far as I understand, the `vmselect` uses channel to enable concurrent queries in `vmselect/netstorage.go - execOnConn()` but the `vmstorage` does not deal with the searching request in parallel as `vmstorage/transport/server.go - processVMSelectConn()` shows. While `vmstorage` uses channel and goroutines to deal with insert request.

Does the above description right? What is the reason of not using concurrency in select process? Will this way affect the speed of selecting?

**Comment by valyala** [comment]
`vmselect` sends requests for fetching raw data in parallel to all the `-storageNode` `vmstorage` nodes. `vmstorage` can process simultaneously many concurrent requests from `vmselect` nodes. There is no bottleneck there. By default `vmstorage` compresses responses before sending them to `vmselect`. This can take additional time and CPU resources on both `vmstorage` and `vmselect` sides. The compression is needed for saving network bandwidth between `vmstorage` and `vmselect` nodes. The compression can be disabled by passing `-rpc.disableCompression` command-line flag at `vmstorage` nodes.

Another bottleneck could be in the network latency - e.g. the time needed for sending requests from `vmselect` to `vmstorage` nodes and the time needed for sending responses from `vmstorage` to `vmselect` nodes. Try increasing `-search.maxConcurrentRequests` command-line flag value at `vmselect` nodes and increasing `-connections` arg at Vegeta side.

**Comment by valyala** [comment]
Closing this question as answered.
