### ISSUE TITLE
Remote_read from Prometheus via 'vmselect'

### ISSUE THREAD

**Issue by NikolayShama** [VictoriaMetrics/VictoriaMetrics#101]
When I try to make remote_read from Prometheus via 'vmselect' I get error:
 error        app/vmselect/main.go:233        error in "/select/01/prometheus/api/v1/query": missing `query` arg

cannot obtain connection from a pool: cannot perform "vmselect" handshake with server "server:8400": cannot read success response after sending hello: cannot read message with size 2: EOF

I use cluster version.
tcp        0      0 0.0.0.0:8480            0.0.0.0:*               LISTEN      20750/vminsert-prod
tcp        0      0 0.0.0.0:8481            0.0.0.0:*               LISTEN      20764/vmselect-prod

prometheus.yml:

remote_read:
  - url: http://localhost:8481/select/01/prometheus/api/v1/query

**Comment by tenmozes** [comment]
VM doesn't not support remote read protocol because of its limitation, please check https://github.com/VictoriaMetrics/VictoriaMetrics/issues/96

**Comment by valyala** [comment]
> When I try to make remote_read from Prometheus via 'vmselect' I get error

VictoriaMetrics doesn't support Prometheus remote read API as @tenmozes already said. More information on the reasons behind it is available [here](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/FAQ#why-victoriametrics-doesnt-support-prometheus-remote-read-api).

Prometheus is required only for replicating scraped metric into VictoriaMetrics by remote write API. Prometheus isn't needed for querying VictoriaMetrics, because it must be queried directly via [Prometheus query API](https://prometheus.io/docs/prometheus/latest/querying/api/). VictoriaMetrics may be used as drop-in replacement for Prometheus in Grafana and other Prometheus clients. See [how to configure Grafana to work with VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#grafana-setup). Cluster version of VictoriaMetrics has slightly different [url paths](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#url-format) for Grafana config.

**Comment by NikolayShama** [comment]
@valyala Thanks a lot. Got it and already set up. But I have one more questions about balancing method between three Insert and Select agents. What methods should I choose?

**Comment by valyala** [comment]
> But I have one more questions about balancing method between three Insert and Select agents. What methods should I choose?

Any load balancing methods should work. Round-robin or least-loaded balancing methods are the best.

**Comment by valyala** [comment]
Closing the issue as resolved. Feel free re-opening it if you have additional questions related to the original question

**Comment by xkfen** [comment]
i'm using vm cluster:
my vmselect args:
`-storageNode=vmstorage-svc:8482`
my link in browser:
`http://10.10.13.29:32001/select/1/prometheus/api/v1/series/count`
my vmstorage svc:
`vmstorage-svc           NodePort   10.41.232.80    <none>        8482:32002/TCP,8481:30003/TCP,8480:31639/TCP`
 i got this err:
`{"status":"error","errorType":"422","error":"cannot obtain series count: error occured during fetching series count: cannot get series count from vmstorage vmstorage-svc:8482: cannot obtain connection from a pool: cannot perform \"vmselect\" handshake with server \"vmstorage-svc:8482\": cannot read success response after sending hello: cannot read message with size 2: read tcp4 10.40.104.1:46798->10.41.232.80:8482: i/o timeout; read only 0 bytes"}`

any help? please. thanks

**Comment by valyala** [comment]
@xkfen , it looks like the issue has been already resolved [in Slack](https://victoriametrics.slack.com/archives/CGZF1H6L9/p1580816382160800). Could you post details on how the issue has been resolved here, so other users could find this info?

**Comment by xkfen** [comment]
> @xkfen , it looks like the issue has been already resolved [in Slack](https://victoriametrics.slack.com/archives/CGZF1H6L9/p1580816382160800). Could you post details on how the issue has been resolved here, so other users could find this info?

thanks @valyala replied my question in slack.
i am new in k8s and i made a mistake in vmstorage-statefulset.yaml, the incorrect container yaml:
`      containers:
        - name: vmstorage
          image: victoriametrics/vmstorage:v1.32.8-cluster
          imagePullPolicy: IfNotPresent
          args:
            - "-retentionPeriod=1"
            - "-storageDataPath=/data/vmstorage"
            - "-httpListenAddr=0.0.0.0:8482"
            - "-vminsertAddr=0.0.0.0:8480"
            - "-vmselectAddr=0.0.0.0:8481"
          ports:
            - name: http
              containerPort: 8482`
i didn't expose the vminsertAddr  and vmselectAddr in containers.ports part.
the correct content should be the following:
`      containers:
        - name: vmstorage
          image: victoriametrics/vmstorage:v1.32.8-cluster
          imagePullPolicy: IfNotPresent
          args:
            - "-retentionPeriod=1"
            - "-storageDataPath=/data/vmstorage"
            - "-httpListenAddr=0.0.0.0:8482"
            - "-vminsertAddr=0.0.0.0:8480"
            - "-vmselectAddr=0.0.0.0:8481"
          ports:
            - name: http
              containerPort: 8482
            - name: vminsert
              containerPort: 8480
            - name: vmselect
              containerPort: 8481`

**Comment by valyala** [comment]
Thanks!

**Comment by lav-kush** [comment]
> you may just use vmselect url in Grafana as DataSource url

@tenmozes What vmselect url can we use in Grafana?
I tried http://localhost:8481/select/01/prometheus/api/v1/query and http://localhost:8481, but i am getting Http Bad source for vmselect data source.
Can you please help? Thanks in advance.

**Comment by denisgolius** [comment]
> > you may just use vmselect url in Grafana as DataSource url
> 
> @tenmozes What vmselect url can we use in Grafana? I tried http://localhost:8481/select/01/prometheus/api/v1/query and http://localhost:8481, but i am getting Http Bad source for vmselect data source. Can you please help? Thanks in advance.

Hi @lav-kush !
Please see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/provisioning/datasources/datasource.yml#L13 and https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format
