### ISSUE TITLE
I have remove some metrics scrape But vmmetrics is stilling srape that

### ISSUE THREAD

**Issue by yangvipguang** [VictoriaMetrics/VictoriaMetrics#1016]
I have  remove the node 192.168.0.151. But the vmmetrics still scrape the node metrics。And which will result  vmagent  pod crashoff,including some other metrics like vmservicesrape .But  there is no such issues with prometheus 。Does  this relate to  cache?
![image](https://user-images.githubusercontent.com/11416887/104484863-bdda7280-5604-11eb-8b78-37d3f382ca09.png)

**Comment by f41gh7** [comment]
Hello, can you post crash-off reason? Is it a panic?
 
 `kubernetes_sd_config` is eventually updated. By default, it`s 30 seconds, according to the value of flag`-promscrape.kubernetesSDCheckInterval`. So you may see some scrapping error messages until this update happens. Prometheus doesn't print error log messages in this case. The same behavior can be enabled for vmagent with flag `-promscrape.suppressScrapeErrors=true`.

**Comment by yangvipguang** [comment]
@f41gh7  I have configured the crashoff .It's wrong with oom.   thx.

**Comment by f41gh7** [comment]
Great!
