### ISSUE TITLE
search.maxPointsPerTimeseries ignored for query requests with range vector set.

### ISSUE THREAD

**Issue by slavitch** [VictoriaMetrics/VictoriaMetrics#1020]
Using query to get a set of raw metrics:

`curl -gsG 'http://localhost:8481/select/0/prometheus/api/v1/query?query={__name__=~"networking_bytes_(in|out)",interface="en5"}[2w]%20offset%201w' |   python -m json.tool | grep '\['  | wc
`

Returns millions of metrics per time series, exceeding the value set in   - '--search.maxPointsPerTimeseries=1000000'

Expected result: search.maxPointsPerTimeseries respected.

**Comment by f41gh7** [comment]
Consulted with @valyala  and this behavior is correct according to prometheus data model. It must return raw datapoints at `/query` endpoint for given interval `[2w]` in your case. 

 Flag ` search.maxPointsPerTimeseries` is used only for `/query_range` api and it limits number of points to return at given interval and calculates as `end-start/step`. It useful for graph drawing.

**Comment by valyala** [comment]
Updated docs for `-search.maxPointsPerTimeseries` in the commit c164a8d231945261306b8604adb0d288d023161f .

As @f41gh7 already said, `/api/v1/query` returns all the raw samples on the given time window `[w]` if no more outer functions are applied to the series selector. See https://medium.com/@valyala/analyzing-prometheus-data-with-external-tools-5f3e5e147639 for details.

If you need exporting raw samples and limiting the number of samples returned per line, then it is recommended to use `/api/v1/export` instead and passing `max_rows_per_line` or `reduce_mem_usage` options to this handler. See https://victoriametrics.github.io/#how-to-export-data-in-json-line-format .

If you need only a single point from `/api/v1/query`, then wrap the metrics selector into `last_over_time` function: `last_over_time({__name__=~"networking_bytes_(in|out)",interface="en5"}[2w] offset 1w)`

**Comment by valyala** [comment]
Closing this issue as answered.
