### ISSUE TITLE
filtered datasource in grafana?

### ISSUE THREAD

**Issue by yonimoses** [VictoriaMetrics/VictoriaMetrics#1021]
Quick question on the datasource definition in grafana while using drop in Prometheus replacement .
Can i define a datasource with some pre-defined query in it to help isolating the results ?

My main goal is to provide an isolation for users so that user A can't query user B data. (different business metrics in prometheus and we need an isolation of the data) 
this cannot be achieved in prometheus due to it's nature but there's projects like https://github.com/hoffie/prometheus-filter-proxy which can help .
I'm familiar I can configure such for victoria as well but i was hoping you have some built-in support for such.

**Comment by f41gh7** [comment]
Hello, this is possible at enterprise version.  @kreedom knows more.

**Comment by valyala** [comment]
The isolation is performed via `extra_label` query arg, which is accepted by all the [Prometheus querying API](https://prometheus.io/docs/prometheus/latest/querying/api/) handlers in enterprise version. For example, `/api/v1/query_range?query=q&extra_label=tenant_id=123` would add `{tenant_id="123"}` label filter to all metric expressions inside `q`. This ensures that the query `q` processes only time series with the label `{tenant_id="123"}`.

**Comment by yonimoses** [comment]
@valyala is that an enterprise feature? Or the oss supports that?

**Comment by valyala** [comment]
@yonimoses , support for `extra_label` query arg has been added to [Prometheus querying API](https://victoriametrics.github.io/#prometheus-querying-api-usage) in the following OSS commits:

* Single-node version: b43b498fd8c18d0475ebd9e979023e283139ac70 
* Cluster version: 7d23f3ff3a6909a63160e30e2fe5bc2b32577ce1

These commits will be included in the next release of VictoriaMetrics.

It is expected that a special service is responsible for authorizing incoming `select` requests, adding the needed `extra_label` query args for the authorized tenants and proxying these requests to VictoriaMetrics. Such a service is available as a part of [enterprise subscription](https://victoriametrics.com/enterprise.html).

**Comment by valyala** [comment]
VictoriaMetrics accepts `extra_label` query arg at Prometheus querying API handlers starting from [v1.53.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Comment by shayfisher** [comment]
Is it possible to enrich this parameter and have it support also regex expressions?
Such that if I would enter for the previous example:
extra_label=tenant_id=~12.*
That would made the query add the filter {tenant_id=~"12.*"}.
Hope this is clear.
Thanks!

**Comment by valyala** [comment]
Regex filters aren't supported in extra_label. @shayfisher , could you open a new feature request for regexp handling in `extra_labels`?
