### ISSUE TITLE
Add Azure Blob to vmbackup

### ISSUE THREAD

**Issue by Cytram** [VictoriaMetrics/VictoriaMetrics#1029]
**Describe the solution you'd like**
Support Azure Blob storage for vmbackup and vmrestore

**Comment by Xtigyro** [comment]
Hmm, almost amazed that this was requested just 8 days ago for the first time!

**Comment by Cytram** [comment]
Started looking into creating adding azures [azure-storage-blob-go](https://github.com/Azure/azure-storage-blob-go) into vmbackup and it looks fairly simple

**Comment by valyala** [comment]
vmbackup and vmrestore gain ability to save and restore backups to / from Azure Blob storage starting from the commit 262ce77e2d8fba0d4c7187654b7fbd255e7e9e3d . Example commands:

* Save backup to Azure blob storage: `./vmbackup -storageDataPath=... -dst=azblob://bucket/path/to/backup`
* Restore from backup at Azure blob storage: `./vmrestore -src=azblob://bucket/path/to/backup -storageDataPath=...`

This commit will be included in the next release. In the meantime it is possible to test saving / loading VictoriaMetrics backups to / from Azure blob storage by building `vmbackup` and `vmrestore` tools from this commit according to the following docs:

* [How to build vmbackup from sources](https://docs.victoriametrics.com/vmbackup.html#how-to-build-from-sources)
* [How to build vmrestore from sources](https://docs.victoriametrics.com/vmrestore.html#how-to-build-from-sources)

**Comment by valyala** [comment]
`vmbackup` and `vmrestore` gain support for [Azure blob storage](https://azure.microsoft.com/en-us/products/storage/blobs/) starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1029#issuecomment-1269021124) for details on how to create and restore backups at Azure blob storage.

Closing the feature request as done.
