### ISSUE TITLE
CLI tools for VM

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#103]
Create general CLI tool for migrations, data manipulation and other ops thing
need to support:
- re-balance data between nodes
- migrate data from one account id to another 
- remove/add node from cluster

**Comment by tenmozes** [comment]
I'm going to use https://github.com/VictoriaMetrics/vmctl repo this issue,
the open questions:
- do we need to use any CLI framework
- if yes which one
- we need to have basic design and pattern for all command

**Comment by valyala** [comment]
> do we need to use any CLI framework

I'd start with standard library. CLI framework such as [readline](https://github.com/chzyer/readline) can be used later for implementing interactive command-line utility.

> we need to have basic design and pattern for all command

Something like `vmctl <command> <args>` looks good, since it is common practice for CLI tools at the moment.

**Comment by valyala** [comment]
Small context for further readers - the https://github.com/VictoriaMetrics/vmctl contains `vmctl` tool for VictoriaMetrics. This tool can migrate data from Prometheus, Thanos and InfluxDB to VictoriaMetrics.

**Comment by rachelratte** [comment]
@valyala Hi there! You've mentioned this issue in other issues concerning the ask for rebalancing nodes (#188 for example), and I was wondering if rebalancing was still on the roadmap? Reading the readme for vmctl it looks like it primarily deals with migration _into_ VM, not rebalancing among nodes _within_ VM. Let me know if I'm missing something there. 
Thank you!

**Comment by radinv** [comment]
@valyala Hi! I am also interested in the question from @rachelratte. Thank you!

**Comment by valyala** [comment]
Rebalancing and replication factor recovery features are in the roadmap for `vmctl` tool. ETA is third quarter of 2021. Note that these features will be available as a part of [enterprise subscription](https://victoriametrics.com/enterprise.html).
