### ISSUE TITLE
Add ability to pass multiple targets.yaml files

### ISSUE THREAD

**Issue by Oloremo** [VictoriaMetrics/VictoriaMetrics#1031]
It'd be really great if it will be possible to pass multiple targets.yaml files to vmagent. 

It's very convenient to keep different scraping targets separately in terms of configuration management software, for example, server-side scrape targets like VM services and client-side targets, like exporters, etc.

Currently, we use a lot of conditions inside targets.yaml template and it starting to become unreadable.

**Comment by hagen1778** [comment]
Hello @Oloremo! Have you tried to use file-based service discovery?
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config

**Comment by Oloremo** [comment]
This seems like a perfect solution, thanks!
