### ISSUE TITLE
Readiness endpoint in clustered components  

### ISSUE THREAD

**Issue by syepes** [VictoriaMetrics/VictoriaMetrics#1034]
It would be great to have the same [Readiness http endpoints](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) that exits in the single mode version also in the clustered components (Insert, Select..)

Exists in standalone version:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vminsert/main.go#L170

Nonexistent in clustered version:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vminsert/main.go#L222

**Comment by f41gh7** [comment]
Note, cluster vesion vminsert doesn't scrape targets, so there is no much sense for `/ready` endpoint with the same meaning, as vmsingle and vmagent have. 

 But it can be added for consistency to all components.

**Comment by syepes** [comment]
Yes, it's more to be able to correctly monitor and check the health under a K8s deployment. Right noew we are using the standard TCP check and it generated unnecessary errors:
`cannot decompress request with length 0: snappy: corrupt input`

**Comment by f41gh7** [comment]
Btw, all components have `/health` endpoint.  https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/httpserver/httpserver.go#L212

**Comment by syepes** [comment]
I missed that one!
