### ISSUE TITLE
VMAgent rate limiting

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1035]
It'd be good to have option to limit write from vmagent to storage

The case:

-  Database or one of the storage nodes goes offline 

- A number of pending datapoints grow in agent 

- Database goes online 

- Agent tries to refill all datapoints from buffer into db.

- DB goes offline because of DDoS from agent

**Comment by valyala** [comment]
The commit 419ad7426928ea2935e27c400e0719f5c07c9044 adds `-remoteWrite.rateLimit` command-line flag for limiting per-second rate for data sent by `vmagent` to each configured `-remoteWrite.url`. This feature will be included in the next release. In the mean time it can be tested and evaluated by building `vmagent` from the latest commit in `master` branch according to [these docs](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment]
The `-remoteWrite.rateLimit` command-line flag is available in `vmagent` starting from [v1.53.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
