### ISSUE TITLE
Windows support for VMAgent

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1036]
Could you please add support of VMAgent for Windows OS

The usecase:
- setup windows machine with exporter and agent which pushes data to centralize storage 

Related issues: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/70

**Comment by valyala** [comment]
Windows build for `vmagent` is available starting from the commit f3a03c416408bf7d81dee438a10566428962c5ee . `vmagent` build for Windows can be created with the following command, which should be executed from the repository root:

`CGO_ENABLED=0 GOOS=windows go build ./app/vmagent`

**Comment by valyala** [comment]
Windows build for `vmagent` is supported starting from [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as done.
