### ISSUE TITLE
Add VMagent build for Mac OS to releases

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1042]
As AWS provided osx machine it would be good to have build for VMAgent for this system in releases

**Comment by vasylenko** [comment]
+1 for this! I would really love to use that build on my project with macOS!

**Comment by valyala** [comment]
A temporary solution is to build `vmagent` for MacOS from source code. Run the following command from the root directory of VictoriaMetrics repository:
```
CGO_ENABLED=0 GOOS=darwin go build -mod=vendor ./app/vmagent/
```
It will build `vmagent` binary and put it into the root directory of VictoriaMetrics repository.
The minimal supported Go version for the build is v1.13 .

**Comment by valyala** [comment]
VictoriaMetrics ships release builds for MacOS (both amd64 and arm64 architectures) at the [releases page](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest) starting from the [v1.73.0](https://docs.victoriametrics.com/CHANGELOG.html). See the corresponding commit 75e84144c72e290f6f3e7b4c0cf92b32d9d573eb and the related issues - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1896 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1851 .

Closing this issue as resolved.
