### ISSUE TITLE
PromQL compliance testing

### ISSUE THREAD

**Issue by sagor999** [VictoriaMetrics/VictoriaMetrics#1045]
Hi,

I came across this PromQL compliance testing that is done across different vendors, including Victoria Metrics, and Victoria did not score very well on those.
https://promlabs.com/promql-compliance-tests/

I was wondering if authors are aware of this compliance test?
And if there is an intention to try to pass that compliance test or get close to it? Or is this known and not fixable due to victoria's architecture\design decisions? 

Thank you!

**Comment by hagen1778** [comment]
Hi @sagor999! Yes, these are well-written tests and VM team is aware of it. Pls see the comments here https://promlabs.com/blog/2020/11/26/an-update-on-promql-compatibility-across-vendors#comment-1

**Comment by valyala** [comment]
See also [MetricsQL documentation](https://victoriametrics.github.io/MetricsQL.html), which explains why MetricsQL diverges from PromQL in some cases.

**Comment by valyala** [comment]
MetricsQL isn't going to be 100% compatible with PromQL because of reasons explained in [MetricsQL docs](https://victoriametrics.github.io/MetricsQL.html). See also https://medium.com/@romanhavronenko/victoriametrics-promql-compliance-d4318203f51e 

Closing this issue as won't implement.
