### ISSUE TITLE
kubernetes_sd watch api

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1057]
**Is your feature request related to a problem? Please describe.**

 currently kubernetes services discovery  takes 50-60 seconds to fetch all pod entities and append labels to it at big clusters. It leads to race conditions during updates, when pod ip can be reused.  

**Describe the solution you'd like**
 Add watch api and cache kubernetes entities changes at local cache.

**Comment by valyala** [comment]
`vmagent` and single-node VictoriaMetrics uses Kuberntes watch API for targets discovery starting from [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
