### ISSUE TITLE
vmagent/MetricsQL: value capping bounds

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#1059]
Currently having the problem, that buggy source emits invalid values. Since there is a lot of firmware, which answers request with "out of range" alias non-sense values it would be nice, if one could instruct vmagent to ignore a sample, if its value is above an upper or below a lower boundary. Similar, if one wants to collect even those invalid samples, it would be nice, if one could exclude all data points which are out-of-bounds, e.g. like `skip(q, val_upper_bound, val_lower_bound)` and thus do not "destroy" grafana charts.

**Comment by valyala** [comment]
The following query should remove undesired values in Grafana `q < val_upper_bound > val_lower_bound`
