### ISSUE TITLE
Support regex in the extra_label parameter

### ISSUE THREAD

**Issue by shayfisher** [VictoriaMetrics/VictoriaMetrics#1060]
Enable support for regex in the extra_label parameter so that one could state for instance the following (working on the example provided in the docs):
extra_label=user_id=\~12.* 
This would translate to the following query parameter - 
{user_id=~"12.*"}
We need some query parameters to be regex based in order to be more elastic with our queries and do less configuration.
Thanks!

**Comment by valyala** [comment]
This has been already implemented in [v1.71.0](https://docs.victoriametrics.com/CHANGELOG.html). See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1863 and [these docs](https://docs.victoriametrics.com/#prometheus-querying-api-enhancements).

Closing the feature request as done.
