### ISSUE TITLE
vmselect consumes more 100% Memory 

### ISSUE THREAD

**Issue by nikhilavrio** [VictoriaMetrics/VictoriaMetrics#1067]
**Description**
We have a timeseries where 16 samples are stored every second for more than 2 months.

If we visualize the timeseries in grafana, everything works well for 10day duration. But if someone selects 30day duration / more than 30day, vmselect consumes 100% RAM (4GB) and stops responding.

Is there any way to limit the query duration in vmselect ?

FYI - using -memory.allowedPercent and   -memory.allowedBytes doesn't have any effect on this behavior.

**Comment by valyala** [comment]
VictoriaMetrics (and vmselect) processes a series at a time per each CPU core. It fetches all the data for a time series on the requested time range, unpacks it in memory and then starts processing it. If each of your time series have 16 samples per second, then vmselect needs to unpack `16*3600*24*30=41472000` data points in memory per series. Each data point occupies 16 bytes after unpacking - 8 bytes for timestamp and 8 bytes for value. This means that each CPU core needs `41472000*16=660MB` of memory for processing such time series. If `vmselect` runs on a host with more than a single CPU core, then RAM requirements must be multiplied by the number of CPU cores (the number of CPU cores visible to vmselect can be tuned with [GOMAXPROCS environment variable](https://golang.org/pkg/runtime/#GOMAXPROCS)). Additionally, Go runtime may use up to 100% of extra memory according to default value of [GOGC=100](https://golang.org/pkg/runtime/#hdr-Environment_Variables).

Probably, VictoriaMetrics should be optimized for the case when each time series contains big number of datapoints on the selected time range.

**Comment by nikhilavrio** [comment]
Thanks for the reply @valyala 

Can we configure query limit on time range in vmselect ?

If suppose 4GB is max RAM of server, if somebody queries for 90d data of 4 such timeseries, server will crash as it will run out of memory. (660MB x 3 x 4 ~= 8GB)

DB should be such that so single query can crash whole server.

**Comment by valyala** [comment]
Agreed - the issue needs to be addressed in the future.

**Comment by valyala** [comment]
The commit 5830ce270651265e45509710a6a6b8cf51c3e00b adds `-search.maxSamplesPerSeries` command-line flag to `vmselect`, which can be used for limiting the maximum number of samples a single query can process per each time series, and, consequently, the maximum memory usage when querying time series with big number of samples per each series.

**Comment by valyala** [comment]
The `-search.maxSamplesPerSeries` command-line flag has been added in [VictoriaMetrics v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
