### ISSUE TITLE
Debian packages?

### ISSUE THREAD

**Issue by kmansoft** [VictoriaMetrics/VictoriaMetrics#107]
I know it's a single executable and so is super-easy to install,  but ...

... think it would still be cool to have OS format packages, for Debian / Ubuntu (.dpkg) and CentOS / Fedora (.rpm). These could include systemd units for a truly single step install.

I don't know what your build environment is, but .dpkg's are easy to create using standard Linux command line tools like tar etc. without any Debian specific tools. In other words, a .dpkg can be created on any OS (linux distro).

Please see this for how that's done (someone else's project):

https://github.com/DeaDBeeF-Player/deadbeef/blob/master/tools/packages/debian.sh

This approach is also currently working for me in my own project, just fine.

**Comment by valyala** [comment]
@kmansoft , thanks for raising this question. It would be great to publish regular VictoriaMetrics packages for various Linux distros. Unfortunately we have little experience with packaging systems for Linux distros, so it would be better if someone with better experience could help us with this. See [unofficial yum repo for VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#third-party-contributions) as an example.

**Comment by kmansoft** [comment]
I'll try to package for debian and submit a pull request next week.

**Comment by valyala** [comment]
This would be awesome!

**Comment by kmansoft** [comment]
I just pushed some initial work into

https://github.com/kmansoft/VictoriaMetrics

on the master branch.

This will create a .deb file:

```
$ ./package/package_deb.sh  amd64
```
And this will too:

```
make victoria-metrics-package-deb
```

The "code" (scripts) are in package_deb.sh.

I still have more work to do on systemd integration (enable the unit, restart if it was / is enabled) but in the meantime, some questions:

- Right now the script is called from the makefile, not the other way around, which is same as your existing arm targets are set up (in the makefile).

This is of course fine but makes it difficult to create packaging scripts from building and packaging more than one architecture "flavor". In other words, you can't run a single command and get .debs for amd64, arm64, ...

- Related to the first item, should I create `make` targets to package arm flavors?

Something like: `victoria-metrics-arm-package-deb` and `victoria-metrics-arm64-package-deb`???

- Should there be a boiletplate /etc/...conf file with at least some comments on what the options are and their default values? A lot of software does this, making it easier for users to learn about settings and/or tweak them.

**Comment by kmansoft** [comment]
By the way is there a PID file? I can't find one under /var/run

What is the default storage directory? I believe it's standard for data to be stored under /var/lib/<app name> is there a config file option to set it (already seen the command line switch).

**Comment by kmansoft** [comment]
Should the executable be running under root - or should the install script create a separate user and run the executable as that user?

BTW dropping from root to a non-privileged user would ideally go into the software itself, not into its run scripts. I can try to take a look at that and maybe submit some code if there is interest.

**Comment by valyala** [comment]
> This is of course fine but makes it difficult to create packaging scripts from building and packaging more than one architecture "flavor". In other words, you can't run a single command and get .debs for amd64, arm64, ...

This is quite easy to do with the following Makefile rule:

```Makefile
victoria-metrics-package-deb-all: \
        victoria-metrics-package-deb \
        victoria-metrics-package-deb-arm \
        victoria-metrics-package-deb-arm64 \
        ...
```

> Should there be a boiletplate /etc/...conf file with at least some comments on what the options are and their default values? A lot of software does this, making it easier for users to learn about settings and/or tweak them.

`victoria-metrics-prod -help` lists all the config options with descriptions and default values. I'm unsure if additional `/etc/...conf` file is necessary. Probably such a file must contain instructions on how to run `victoria-metrics-prod -help` in order to see available config options.
Pull requests with improved descriptions or better default values for config options are welcome.

> By the way is there a PID file? I can't find one under /var/run

`victoria-metrics-prod` doesn't create `pid` file, so it must be created by wrapper scripts.

> What is the default storage directory?

The default storage directory is `victoria-metrics-data` relative to the current working directory where `victoria-metrics-prod` runs. See default value for `-storageDataPath` option. It is expected that the OS-specific package should set `-storageDataPath` option to more standard directory like `/var/lib/victoria-metrics-data`.

**Comment by valyala** [comment]
See also [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/43) for example instructions on how to set up VictoriaMetrics service under CentOS.

**Comment by kmansoft** [comment]
@valyala I incorporated all your feedback:

- Data directory under /var/lib
- Packaging for arm64
- "package all" target which builds and packages amd64 and arm64

... except one item: the PID file.

I'm reluctant to add wrapper scripts inside the systemd unit file.

And systemd will not create the PID file: https://serverfault.com/a/817560

This leaves the victoria-metrics process as "the" only actor that can create the PID.

What do you think if I add a new command line option to create a PID file? The default will be blank, i.e. do not create, therefore no change for people running victoria using their own scripts right now.

**Comment by valyala** [comment]
> What do you think if I add a new command line option to create a PID file? The default will be blank, i.e. do not create, therefore no change for people running victoria using their own scripts right now.

`-pidfile` command line option may be added to VictoriaMetrics, but it is unclear the purpose of this option for VictoriaMetrics. The [linked answer](https://serverfault.com/a/817560) says the following about `PIDFile` option in systemd:
```
this option tells systemd where to find an existing PID file (if any). In most cases it's not required at all, as systemd will keep services in their own cgroups and does not need a PID file to keep track of them
```
and
```
Use of this option is recommended for services where Type= is set to forking
```
VictoriaMetrics process doesn't call `fork()`, so the `PIDFile` option looks redundant for it.

**Comment by kmansoft** [comment]
> -pidfile command line option may be added to VictoriaMetrics, but it is unclear the purpose of this option for VictoriaMetrics. 

Clear purpose: operating system integration.

> tells systemd where to find an existing PID file (if any). In most cases it's not required at all, 

First it's "traditional" to have a pid file.

Even skipping that, the systemd unit needs a PID in order to gracefully terminate the process:

https://github.com/kmansoft/VictoriaMetrics/blob/master/package/victoria-metrics.service

SystemD docs are pretty vague about $MAINPID - I'm not sure how exactly it's set for "simple" unit type, the docs only mention forking type units. It's also unclear if $MAINPID would be read by systemd from thge pid file if it's provided by the unit.

**Comment by kmansoft** [comment]
OK I did some testing - `systemctl stop` while watching `journalctl` from Victoria.

```
Jul 22 10:56:11 xandra systemd[1]: Stopping VictoriaMetrics is a fast, cost-effective and scalable time series database....
Jul 22 10:56:11 xandra victoria-metrics[13771]: 2019-07-22T07:56:11.288+0000        info        /home/kman/Android/src/VictoriaMetrics-fork/app/victoria-metrics/main.go:33        received signal terminated
Jul 22 10:56:11 xandra victoria-metrics[13771]: 2019-07-22T07:56:11.288+0000        info        /home/kman/Android/src/VictoriaMetrics-fork/app/victoria-metrics/main.go:35        gracefully shutting down webservice at ":8428"
Jul 22 10:56:11 xandra victoria-metrics[13771]: 2019-07-22T07:56:11.288+0000        info        /home/kman/Android/src/VictoriaMetrics-fork/app/victoria-metrics/main.go:41        successfully shut down the webservice in 29.884µs
Jul 22 10:56:11 xandra victoria-metrics[13771]: 2019-07-22T07:56:11.288+0000        info        /home/kman/Android/src/VictoriaMetrics-fork/app/vmstorage/main.go:125        gracefully closing the storage at /var/lib/victoria-metrics
```

I believe this means that the process is shut down *gracefully* and does receive the intended signal - as opposed to systemd killing the process using -KILL or some other way that's "external" and "ungraceful".

I believe this means that I am ready to submit my PR. @valyala  please let me know if there is anything else you think needs to be done.

**Comment by oOHenry** [comment]
Is it also planed to package the cluster version?

**Comment by kmansoft** [comment]
> Is it also planed to package the cluster version?

As far as I can tell, the cluster version is a separate branch (as opposed to a build target within the same code base)....

Let's wait for the developers to merge my changes so far - and if they decide to also cherrypick them into the cluster branch. If they do and if they then require more assistance from me - I'll be happy to help.

I suppose at the very least, the names of package files will need to be changed...

**Comment by kmansoft** [comment]
Created a draft PR: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/116

**Comment by zonk1** [comment]
Created PR for vmagent and vmalert deb packages: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/690

**Comment by guillemj** [comment]
Hi!

BTW I had already packaged VictoriaMetrics from scratch for work, and submitted it to Debian. It is currently only available in unstable, but I expect to appear in testing in a week or less, and thus the eventually next Debian stable release.

  https://tracker.debian.org/victoriametrics

I've got a couple of patches for its build-dependencies which I'll submit in the coming week. And it seems I'll need to also fix the test suite problems on non-x86 architectures:

  https://buildd.debian.org/status/package.php?p=victoriametrics

**Comment by valyala** [comment]
@guillemj , thanks for great news!

**Comment by valyala** [comment]
@guillemj , note that it is better creating e.g. `pure  Go` builds for non-amd64 architectures - this removes dependency on gozstd and, subsequently, on libzstd. See [these docs](https://victoriametrics.github.io/#pure-go-build-cgo_enabled0) for details.

**Comment by guillemj** [comment]
@valyala Ah thanks for the hint! The gozstd support should be almost fine now I think, after the PR I sent (except for the tests on armhf due to too much required memory and the system being under provisioned I think, the rest pass now). The problem I'm having which I need to sit down and fix seems to be (from a quick cursory look) in the VictoriaMetrics test suite, as it tries to do floating point comparisons w/o using any epsilon. I'll try to cover that one during next week or so, if no one beats me to it. :)

**Comment by guillemj** [comment]
The packages migrated to Debian testing (bullseye) and will be part of the next stable release once that happens. While we have been using these packages at work for a while now, I'd appreciate anyone interested in the packaged versions to test them now so that we can fix stuff before the hard-freeze.

**Comment by grinapo** [comment]
>  I'd appreciate anyone interested in the packaged versions to test them now so that we can fix stuff before the hard-freeze.

I am using them from the start (in fact that was the way I have found VictoriaMetrics!) and it works well. (I am *not* using systemd so I use them under runit so maybe that makes me not that good testing point after all.)

**Comment by jakobdalsgaard** [comment]
I tried finding an arm package for my Raspberry Pi, but ended up modifying the package_deb.sh script in release 1.52.0 because I could not find one; it looks like the current work is focusing on making one debian package for the victoria-metrics binary and possibly additional packages the remaining binaries. Is there any particular reason for that? I did my Debian package such that it would install vmagent and victoriametrics, with each their /etc/default/ file - and each their unit file.

I'll be doing a fork if anyone has interest in this work.

**Comment by guillemj** [comment]
@grinapo the Debian packages support both sysvinit and systemd. I've not looked into what what would entail adding runit support though. But testing whether the daemon works from what is packaged, is already a good start, thanks!

@jakobdalsgaard the packages I'm talking about are from Debian itself, I didn't use the packaging in the upstream git repo, see https://packages.debian.org/bullseye/victoria-metrics (https://tracker.debian.org/pkg/victoriametrics), but I'm not sure the arm versions there are compatible with the Rraspberry Pi. Still a rebuild of those might be just enough, or they might end up appearing in one of the downstreams targetting Raspberry Pi eventually.

**Comment by windware-ono** [comment]
I think this needs attention as VictoriaMetrics gains more popularity.

While a single binary is easy to deploy, it's bad for maintenance.
By packaging, I can do security updates if there ever will be in a reasonable timeframe automatically with `unattended-upgrades` if such an update is provided without having have to check release notes every now and then and by having a systemd unit file, it will be easy to start the process on boot, when I have to write a custom unit file now by moving the binary to some permanent folder.

This also goes with `vmagent` which I'm trying to deploy to dozens of hosts but need to manually distribute the binary to all the machines with manual updating and start it up with a custom systemd unit file.

**Comment by windware-ono** [comment]
Sorry, I just figured it was already available, including vmagent...
https://packages.ubuntu.com/jammy/victoria-metrics

**Comment by denisgolius** [comment]
> Sorry, I just figured it was already available, including vmagent... https://packages.ubuntu.com/jammy/victoria-metrics
> 
> But it would be nice to include a systemd unit file for vmagent too.

See https://github.com/VictoriaMetrics/victoriametrics-lts-rpm

**Comment by valyala** [comment]
Closing this issue as done, since it looks like Debian package for VictoriaMetrics already exists -https://packages.debian.org/source/sid/victoriametrics .

It is better to work with the package maintainers at Debian side in order to regularly update VictoriaMetrics package to the latest versions.
