### ISSUE TITLE
How to safely delete overlapping data?

### ISSUE THREAD

**Issue by johnseekins** [VictoriaMetrics/VictoriaMetrics#1071]
I have found some weirdly overlapping stats, and I'm not sure how to safely delete only the bad ones:
```
{"metric":{"__name__":"zfs_zil_itx_metaslab_slog_count","dc":"ca-east-1","host":"cae1-syncstation-4","group":"syncstation","rack":"r","row":"14"},...
{"metric":{"__name__":"zfs_zil_itx_metaslab_slog_count","dc":"ca-east-1","host":"cae1-syncstation-4","group":"syncstation","pools":"rtpool-276712","rack":"r","row":"14"},...
```

We can see that the only difference is one additional tag. When I try to `/export` this data (because that uses the same _basic_ API as the deletion endpoint), I receive both series. This implies (to me) that the delete command (which _also_ uses `match[]`) will delete both series.

Is there a safe way to delete _only_ the first series?

These bad stats appeared around when some storage nodes crashed from being OOMed, so this isn't the only example.

**Comment by f41gh7** [comment]
Hello, if you can identify these series with `match[]` filter expression for export request, you can delete it with the same filter.
  For example, if all bad series has additional label `pools`, execute request: `curl -g 'localhost:8428/api/v1/export' -d 'match[]={pools!=""}'` and delete it with `curl -g 'localhost:8428/api/v1/admin/tsdb/delete_series' -d 'match[]={pools!=""}'`

**Comment by johnseekins** [comment]
The problem is the "bad" data has _fewer_ labels than the "good" data. So if I use a `match[]` query, it will match both series.

**Comment by f41gh7** [comment]
Match filter `match[]={pools="",rack!=""}` should help in this case. But its no so useful for broken series with different label names and you have to change it.

**Comment by johnseekins** [comment]
But in the case of a series where a tag doesn't exist when it should, setting `pools=""` should work. Cool. I can actually clear out these bad series then. Thanks!
