### ISSUE TITLE
pass additional HTTP headers with vmagent

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#1073]
**Is your feature request related to a problem? Please describe.**
We gradually move to token based authentication and in order to access our VictoriaMetrics we need to pass an additional HTTP headers, like `Authorization: Beader <token>`, with each HTTP request in VM tools such as `vmagent`. So far I was unable to find how I can specify this with `wmagent`.

**Describe the solution you'd like**
I foresee that `wmagent` should provide additional http.Header option, e.g.
```
./vmagent -http.Header "Authorization: Bearer <token> ... "
```
I think this option should be added to all VM tools which require access of remote VM server via token based authentication. Please note, that it would be convenient to allow multiple `-http.Header` options to generalize this use case further.

**Describe alternatives you've considered**
So far I don't see any alternative solutions to resolve this issue.

**Additional context**
This request is mostly viewed for use-case when `vmagent` should send metrics to VictoriaMetrics server which is protected via token based authentication. But I think the addition of HTTP headers to VM tools can be useful for other use-cases.

**Comment by f41gh7** [comment]
Hello, `vmagent` has flag `--remoteWrite.bearerToken=somevalue` per each remoteWrite url. It will produce http header:
```Authorization: Bearer somevalue`.

**Comment by vkuznet** [comment]
That's great, sorry it is totally my mistake that I missed this option. I'm closing the ticket.

**Comment by f41gh7** [comment]
No worries!
