### ISSUE TITLE
EC2 discovery is missing AWS API auth types

### ISSUE THREAD

**Issue by hatemosphere** [VictoriaMetrics/VictoriaMetrics#1080]
**Is your feature request related to a problem? Please describe.**
Looking at the **[code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/discovery/ec2/api.go)** it seems like EC2 discovery AWS API mechanisms are missing, compared to vanilla AWS SDK credentials chain. As an example, WebIdentityToken auth is missing, so it's impossible to use IAM Roles for Service Accounts (IRSA) available in EKS out of the box. This forces us to use some alternative deprecated or not officially recommended methods to inject AWS credentials into pods when running VM stack in Kubernetes.

**Describe the solution you'd like**
More AWS API auth types are added to the EC2 discovery credentials chain, at least the WebIdentityToken one, to be able to use native IRSA auth in Kubernetes.

**Comment by valyala** [comment]
@hatemosphere , could build `vmagent` from the commit 22b1941cfc8216bef7dcdba72c385f7f4c949806 according to [these instructions](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources) and verify whether it works properly with WebIdentityToken auth?

**Comment by hatemosphere** [comment]
@valyala sure thing, we will test this commit today-tomorrow and i will post results here

**Comment by alexandrst88** [comment]
Tested from commit above and got:

```
-03-02T16:37:19.375Z	error	VictoriaMetrics/lib/promscrape/config.go:650	skipping ec2_sd_config targets for job_name "victoriametrics-node-exporter" because of error: error when fetching instances data from EC2: cannot obtain instances: cannot obtain fresh credentials for EC2 API: unexpected status code for "https://sts.us-east-1.amazonaws.com/?Action=AssumeRoleWithWebIdentity&Version=2011-06-15&RoleArn=arn:aws:iam::xxxxxxxxxxxxxx:role/VmagentProdOIDC&RoleSessionName=vmagent-ec2-discovery"; got 403; want 200; response body: "<ErrorResponse xmlns=\"https://sts.amazonaws.com/doc/2011-06-15/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>AccessDenied</Code>\n    <Message>Not authorized to perform sts:AssumeRoleWithWebIdentity</Message>\n  </Error>\n  <RequestId>xxxxxxxxxxxxxx</RequestId>\n</ErrorResponse>\n"
```

**Comment by alexandrst88** [comment]
+1 it works.

**Comment by hatemosphere** [comment]
fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1099

**Comment by valyala** [comment]
The WebIdentityToken authorization for AWS service discovery (aka ec2_sd_config) is supported in `vmagent` starting from [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
