### ISSUE TITLE
vmagent "1:secret-url" error

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#1081]
**Describe the bug**
I'm trying to setup pipeline to feed data to our VM instance via vmagent. For authentication we rely on tokens. I can reach our VM instance as following:
```
curl -kv -H "Authorization: Bearer `cat /tmp/$USER/token`" https://xxxx.cern.ch/victoria-metrics/api/v1/targets
...
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Mon, 22 Feb 2021 19:51:09 GMT
< Response-Proto: HTTP/1.1
< Response-Status: 200 OK
< Response-Status-Code: 200
< Response-Time: 10.589411ms
< Response-Time-Seconds: 0.010590411
< Set-Cookie: gosessionid=AQDpMYp-Jtzh7Qosg7sp_jdRDfpsyX4IqZeWjo7CxG8%3D; Path=/; Max-Age=3600; HttpOnly
< X-Content-Type-Options: bla
< Content-Length: 68
<
* Connection #0 to host xxxx.cern.ch left intact
{"status":"success","data":{"activeTargets":[],"droppedTargets":[]}}
```
but when I try it through vmagent I get the following:
```
./vmagent-prod --remoteWrite.bearerToken="`cat /tmp/$USER/token`" -promscrape.config=./prometheus.yml -remoteWrite.url=https://xxx.cern.ch/victoria-metrics/api/v1/write -remoteWrite.tlsCAFile /path/certificates/CERN-GridCA.pem,/path/certificates/CERN-Root-2.pem
....
2021-02-22T19:52:54.771Z	error	VictoriaMetrics/app/vmagent/remotewrite/client.go:242	couldn't send a block with size 1274 bytes to "1:secret-url": Post "https://xxxxx.cern.ch/victoria-metrics/api/v1/write": EOF; re-sending the block in 4.000 seconds
```
At this point I'm not sure where the issue. Is it possible to add debug output somehow to see if request arrive to VM? From our auth proxy logs I can see it but I don't know what `"1:secret-url"` refers to?

**To Reproduce**
run vmagent with token based access to VM.

**Expected behavior**
should publish the data

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./vmagent-prod -version
vmagent-20210218-171604-tags-v1.54.1-0-g5e341ccb5
```

**Comment by f41gh7** [comment]
Hello, you can add flag `remoteWrite.showURL` for vmagent to display URL.  Also, `-remoteWrite.tlsCAFile /path/certificates/CERN-GridCA.pem,/path/certificates/CERN-Root-2.pem` wouldn't work, vmagent will pick only first file `/path/certificates/CERN-GridCA.pem`,  you have to set path for single bundle file, if needed. 

 There are metrics at VictoriaMetrics server for debugging tcp connections: `vm_tcplistener_accepts_total` and `vm_tcplistener_errors_total`.

**Comment by vkuznet** [comment]
Nikolay, could you please clarify usage of remoteWrite options since it is unclear how routing via proxy server is done. For example, if I have VM behind my proxy server which redirects request from `/victoria-metrics` to `host:8248`, how I should use vmagent in this case. I see two possibilities here:
```
# specify remoteWrite.url as my proxy server
vmagent -remoteWrite.url=https://proxy-server/victoria-metrics/api/v1/write

# or if I understand correctly, I can specify remoteWrite.tlsServerName
vmagent -remoteWrite.tlsServerName=https://proxy-server -remoteWrite.url=http://host:8248/api/v1/write
```

**Comment by f41gh7** [comment]
Ah, i thought, that is reverse proxy.  In your case,you can set `-remoteWrite.proxyURL=https://proxy-server remoteWrite.url=http://host:8248/api/v1/write` flags combination, it must work.

**Comment by vkuznet** [comment]
Hi, I resolved the underlying issue with our proxy server and now everything works smoothly. The final configuration is the following:
```
# in case of reverse proxy which we use in front of VM I need to pass the following command
vmagent-prod --remoteWrite.bearerToken="`cat /tmp/$USER/token`" -promscrape.config=./prometheus.yml -remoteWrite.url=https://xxx.cern.ch/victoria-metrics/api/v1/write -remoteWrite.tlsCAFile /etc/grid-security/certificates/CERN-GridCA.pem
```

Thanks for all your help!
