### ISSUE TITLE
please provide release binary executable for darwin and other architectures

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#1083]
**Is your feature request related to a problem? Please describe.**
Could you please provide in release binary executable for darwin architecture?

**Describe the solution you'd like**
I often test different workflows directly on macOS, and it would be very convenient to have binaries in release area for darwin architecture.

In general, I want to see binaries for all supported architectures, arm64, ppc64le, etc. I hope you can include proper `GOOS` into your Makefiles and build them all together for every release.

**Comment by valyala** [comment]
This should be definitely done in the long run. In the mean time it is possible to build VictoriaMetrics binaries for supported architectures with the following command which must be executed from the root folder of VictoriaMetrics repository:

```
CGO_ENABLED=0 GOOS=... GOARCH=... go build -mod=vendor ./app/<app_name>
```

For example, `VictoriaMetrics` for MacOS can be built with the following command:

```
CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -mod=vendor ./app/victoria-metrics
```

**Comment by valyala** [comment]
Related feature request - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1042

**Comment by valyala** [comment]
Closing this issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1896 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1851 .
