### ISSUE TITLE
Can't query cluster's data when one of vmstorage down

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1086]
**Describe the bug**
I deployed vmcluster on k8s using helm chart with 2 vminsert, 2 vmselect, 2 vmstorage.
When one of vmstorage was failed due to Node failed, I can't query data of cluster from grafana.

![Screenshot from 2021-02-24 16-45-19](https://user-images.githubusercontent.com/1458400/108982677-a214c280-76c0-11eb-8faf-aa56262fddcc.png)
![Screenshot from 2021-02-24 16-46-39](https://user-images.githubusercontent.com/1458400/108982672-a0e39580-76c0-11eb-8a33-e724eb0b3934.png)

Could someone help me to check it?

**Comment by valyala** [comment]
The `cannot fetch query results from vmstorage nodes` error can occur if `-search.denyPartialResponse` command-line flag is passed to `vmselect` and `vmselect` cannot obtain response from all the `vmstorage` nodes listed in `-storageNode` command-line flag. Remove the `-search.denyPartialResponse` command-line flag from `vmselect` if you want receiving partial responses when a part of `vmstorage` nodes are temporarily unavailable.

**Comment by vuxuanlai** [comment]
Hi,
This is args which passed to vmselect pod:
![Screenshot from 2021-03-01 16-18-21](https://user-images.githubusercontent.com/1458400/109476770-da921300-7aa9-11eb-87b6-e283c18f738b.png)

There are no flag `-search.denyPartialResponse` in here.

**Comment by f41gh7** [comment]
It seems like, that all storage nodes were unavailable during request. In this case only first error returned. Probably, when 1 nodes went down, the second one was overloaded by incoming requests.

**Comment by sharninder-se** [comment]
This is still an open issue. vmselect gives the tcp lookup error when even a single vmstorage node is down and replicationFactor is not specified.
