### ISSUE TITLE
Support for extra_label from vmalert datasource and remoteRead

### ISSUE THREAD

**Issue by pmitra43** [VictoriaMetrics/VictoriaMetrics#1087]
**What is the pain point**
I am trying to use `extra_label` as a filter for vmalert's queries. This is currently not supported.

**Summary**
VMAlert has `datasource.url` and `remoteRead.url` properties, which can be any datasource.
In case of datasource being victoria-metrics, the value is required to be `vmselect_url/select/0/prometheus`, which is the prefix. vmalert then appends the required [handler](https://victoriametrics.github.io/#prometheus-querying-api-usage) to it before sending the request.
Due to this, when using victoriametrics as a datasource, it is not possible to use the `extra_label` query feature which was introduced in [v1.53.0](https://victoriametrics.github.io/#prometheus-querying-api-enhancements), because `extra_label` is expected to be a query param.

**Describe the solution you'd like**
Given if the datasource type is victoria-metrics, vmalert can accept an extra_label param, either as part of the url, or as a config `datasource.extra_label` & `remoteRead.extra_label`, which can be appended to the query being sent to vmselect.

**Comment by f41gh7** [comment]
Its need to be fixed only for remoteWrite. read and datasource already supported it. 

cc @hagen1778

**Comment by valyala** [comment]
@pmitra43 , could you build `vmalert` from the commit 317b0cbed25002f915f64fe51b2d3d3173288bb6 and verify whether it works as expected when `extra_label` query arg is passed to `-datasource.url` and `-remoteRead.url` command-line args?

**Comment by valyala** [comment]
`vmalert` should support passing query args to `-datasource.url` and `-remoteRead.url` starting from [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
