### ISSUE TITLE
What balancing method to use for Insert and Select?

### ISSUE THREAD

**Issue by NikolayShama** [VictoriaMetrics/VictoriaMetrics#109]
I have created a cluster from three nodes and on each of them installed Select, Insert and Storage. What balancing method to use for Insert and Select?

**Comment by tenmozes** [comment]
hello @NikolayShama , vmselect and vminsert are stateless (vmselect has a cache, but it can be erased and restored, this is just a matter of performance). Simple load-balancer with round-robin strategy, k8s service perfectly solves that task

**Comment by NikolayShama** [comment]
@tenmozes tnx a lot for your answer. I will try to configure in the nearest future.

**Comment by tenmozes** [comment]
@NikolayShama i close an issue, please re-open if you need any help
