### ISSUE TITLE
Add multitenancy support to vmagent

### ISSUE THREAD

**Issue by JGShaw** [VictoriaMetrics/VictoriaMetrics#1098]
**Is your feature request related to a problem? Please describe.**
I am looking at setting up a Victoria Metrics cluster, and having multiple clusters spread across availability zones as suggested by the documentation to give high availability. I would need to ensure that all writes are written to both clusters. The documentation suggests using vmagent to send all of the data to all clusters. 

This is fine, unless you want to make use of multitenancy in the clustered version to segregate the data, as the remote write URL in vmagent has to be hard coded to a specific tenant ID. The only solution I can see around this right now is to run an instance of vmagent per tenant ID, which does not scale and allow dynamic adding of new tenants.

**Describe the solution you'd like**
I would like to see some way of specifying which tenant the data should be written to. This could be done using a subset of URLs similar to those in vminsert and vmstorage, or perhaps some headers which could be passed though and used to build the remote write URL. Both of these solutions would not work for non-HTTP write protocols though, so something different would have to be done for them. 

**Describe alternatives you've considered**
I have thought about going against the documentation and running a single cluster across availability zones while accepting the risk of higher latency and error rates, and then enabling replication to ensure all data is written to the other site. But if there is more than one storage node in an availability zone, it would not guarantee the data was written to a different availability zone as the replication does not have any options for rack awareness.

**Comment by tenmozes** [comment]
@valyala @f41gh7 should we close this as far we support multitenancy in vmagent https://docs.victoriametrics.com/vmagent.html#multitenancy?

**Comment by JGShaw** [comment]
Closing as I agree with @tenmozes, looks like this would be supported now as shown in the docs.
