### ISSUE TITLE
Graphite parser error for ending semicolumn

### ISSUE THREAD

**Issue by Karsonito** [VictoriaMetrics/VictoriaMetrics#1100]
The incoming record is skipped by graphite parser if metric name contains ending semicolumn ";"
Records are not saved and an error occurs
`2021-03-01T13:33:23.397Z        error   VictoriaMetrics/lib/protoparser/graphite/parser.go:154  cannot unmarshal Graphite line "test; 1 1614605603": cannot umarshal tags: missing tag value for ""`

To reproduce: `$ echo "test; 1 $(date +%s)" | nc 127.0.0.1 2003`

Version: victoria-metrics-20190730-121249-heads-single-node-0-g671d9e55

Such problem happens with new version of bioyino 0.7+ ONLY with option `destination="tag"`
`2021-03-01T13:25:11.325Z        error   VictoriaMetrics/lib/protoparser/graphite/parser.go:154  cannot unmarshal Graphite line "resources.monitoring.bioyino.egress; 8 1614605111": cannot umarshal tags: missing tag value for ""`

It's not very urgent - I will use `destination="smart"` for a while )

**Comment by valyala** [comment]
The issue must be fixed in the following commits:
* For single-node VictoriaMetrics - 019d8e88d82d0de14d7c0bdad8e092dba42778d5
* For cluster version of VictoriaMetrics - f4969a624dca5430a75976e3d157fee8c09878fb

These commits will be included in the next release.

**Comment by Karsonito** [comment]
Thanks for incredible quick fix! )

**Comment by valyala** [comment]
The bugfix has been included in [v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
