### ISSUE TITLE
Prometheus frequent resharding after upgrade to 1.54.1

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#1102]
**Describe the bug**
A few hours after upgrading from 1.52.0 to 1.54.1 the Prometheus servers doing remote writes to VictoriaMetrics started to reshard frequently. The ingestion rate on VictoriaMetrics would drop to 0 and then increase to catch up. vmagent did not have this issue and VictoriaMetrics kept a steady ingestion rate for metrics from vmagent even after the upgrade.

I have not tried yet a rollback to 1.52.0.

**Expected behavior**
Steady ingestion rate

**Screenshots**
<img width="1388" alt="Screen Shot 2021-03-02 at 10 19 09 AM" src="https://user-images.githubusercontent.com/37348934/109626687-204dea80-7b41-11eb-86ec-4c0a55bac102.png">

**Version**
1.54.1

**Used command-line flags**
```
version | false
-- | --
tls | false
storageDataPath | /storage
smallMergeConcurrency | 0
selfScrapeJob | victoria-metrics
selfScrapeInterval | 10s
selfScrapeInstance | self
search.treatDotsAsIsInRegexps | false
search.queryStats.minQueryDuration | 0s
search.queryStats.lastQueriesCount | 20000
search.minStalenessInterval | 0s
search.maxUniqueTimeseries | 300000
search.maxTagValues | 100000
search.maxTagValueSuffixesPerSearch | 100000
search.maxStepForPointsAdjustment | 1m0s
search.maxStalenessInterval | 0s
search.maxQueueDuration | 10s
search.maxQueryLen | 16384
search.maxQueryDuration | 30s
search.maxPointsPerTimeseries | 30000
search.maxLookback | 0s
search.maxExportDuration | 720h0m0s
search.maxConcurrentRequests | 16
search.logSlowQueryDuration | 5s
search.latencyOffset | 30s
search.disableCache | false
search.cacheTimestampOffset | 5m0s
retentionPeriod | 12
promscrape.suppressScrapeErrors | false
promscrape.suppressDuplicateScrapeTargetErrors | false
promscrape.streamParse | false
promscrape.openstackSDCheckInterval | 30s
promscrape.maxScrapeSize | 16777216
promscrape.maxDroppedTargets | 1000
promscrape.kubernetesSDCheckInterval | 30s
promscrape.gceSDCheckInterval | 1m0s
promscrape.fileSDCheckInterval | 30s
promscrape.eurekaSDCheckInterval | 30s
promscrape.ec2SDCheckInterval | 1m0s
promscrape.dropOriginalLabels | false
promscrape.dockerswarmSDCheckInterval | 30s
promscrape.dnsSDCheckInterval | 30s
promscrape.discovery.concurrentWaitTime | 1m0s
promscrape.discovery.concurrency | 100
promscrape.disableKeepAlive | false
promscrape.disableCompression | false
promscrape.consulSDCheckInterval | 30s
promscrape.configCheckInterval | 0s
promscrape.config.strictParse | false
promscrape.config.dryRun | false
precisionBits | 64
opentsdbhttpTrimTimestamp | 1ms
opentsdbhttp.maxInsertRequestSize | 33554432
opentsdbTrimTimestamp | 1s
memory.allowedPercent | 60
memory.allowedBytes | 0
maxLabelsPerTimeseries | 30
maxInsertRequestSize | 33554432
maxConcurrentInserts | 128
loggerWarnsPerSecondLimit | 0
loggerTimezone | UTC
loggerOutput | stderr
loggerLevel | INFO
loggerFormat | default
loggerErrorsPerSecondLimit | 0
loggerDisableTimestamps | false
insert.maxQueueDuration | 1m0s
influxTrimTimestamp | 1ms
influxSkipSingleField | false
influxSkipMeasurement | false
influxMeasurementFieldSeparator | _
influx.maxLineSize | 262144
import.maxLineLen | 104857600
httpListenAddr | :8428
http.shutdownDelay | 0s
http.maxGracefulShutdownDuration | 7s
http.idleConnTimeout | 1m0s
http.disableResponseCompression | false
http.connTimeout | 2m0s
graphiteTrimTimestamp | 1s
fs.disableMmap | false
finalMergeDelay | 0s
envflag.enable | false
enableTCP6 | false
dryRun | false
denyQueriesOutsideRetention | false
dedup.minScrapeInterval | 0s
csvTrimTimestamp | 1ms
bigMergeConcurrency | 0
```

**Comment by alexandv** [comment]
I did not find anything interesting in the VictoriaMetrics logs or Prometheus logs other than the resharding.

**Comment by alexandv** [comment]
Noticing some new error messages that were not there before the upgrade:
`2021-03-02T11:50:11.054Z	error	VictoriaMetrics/lib/storage/index_db.go:2950	missing metricName by metricID 1605707651334438419; this could be the case after unclean shutdown; deleting the metricID, so it could be re-created next time`

I don't know if this has anything to do with the above issue.

**Comment by valyala** [comment]
@alexandv , could you share `churn rate` graph from the [official dashboard for VictoriaMetrics](https://victoriametrics.github.io/#monitoring) on the same time range as the `ingestion rate` graph above?

**Comment by valyala** [comment]
Try also tuning `queue_config` section in Prometheus `remote_write` configs according to the docs https://victoriametrics.github.io/#prometheus-setup .

**Comment by valyala** [comment]
Note that the file `<-storageDataPath>/metadata/minTimestampForCompositeIndex` must be deleted when downgrading to version below v1.54. If the file isn't deleted, then VictoriaMetrics could return incomplete query results after the later upgrade to version v1.54 or above.

**Comment by alexandv** [comment]
@valyala here is the churn rate:
<img width="1403" alt="Screen Shot 2021-03-02 at 7 48 43 PM" src="https://user-images.githubusercontent.com/37348934/109786468-78eab980-7c0d-11eb-877a-60ebd68a19db.png">

IO utilization was much higher than before the migration and often close to 100%. Slow inserts was also much higher than before.

I also notice that `sum(vm_concurrent_addrows_capacity)` was at 32 with 1.54. It was at 25 with 1.52.

We use an HDD and will try to migrate the data to an SSD.

Rolling back to 1.52.0 seems to have solved the issue for now.

**Comment by valyala** [comment]
VictoriaMetrics 1.54.0 and all the newer releases creates composite index for faster time series lookups by label filters. Composite index entries are created when the first sample for new time series is ingested into VictoriaMetrics. The churn rate graph above shows that you have quite high time series churn rate, e.g. old time series are constantly substituted by new time series. Such workload can result in increased disk IO utilization after the upgrade to 1.54.0 or newer release because VictoriaMetrics needs to save an an additional composite index per each new time series. I'd suggest switching from HDD to SSD for your workload.

It is also recommended investigating the source of high churn rate in your workload and try to eliminate it. This should reduce overall resource usage (disk IO, RAM, CPU).

**Comment by valyala** [comment]
FYI, VictoriaMetrics [v1.59.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) improves data ingestion speed when big number of new time series are registered in the system (e.g. under high churn rate). See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1244) for details. This should reduce the probability of re-routing in cluster version of VictoriaMetrics.

**Comment by valyala** [comment]
FYI, re-routing is disabled by default in VictoriaMetrics cluster starting from [v1.66.0](https://docs.victoriametrics.com/CHANGELOG.html#v1660). It can be enabled by passing `-disableRerouting=true` command-line flag to `vminsert` nodes.

**Comment by hagen1778** [comment]
Closing as inactive.
