### ISSUE TITLE
vmauth: unable to handle source path /api/v1/label/{name}/values in url_map

### ISSUE THREAD

**Issue by damnever** [VictoriaMetrics/VictoriaMetrics#1112]
**Is your feature request related to a problem? Please describe.**
It is not possible if we use a single user for both vminsert and vmselect because vmauth can not handle variable parameter in `src_paths`.

**Describe the solution you'd like**
Make `src_paths` using regex pattern or something else.

**Comment by valyala** [comment]
The commit 47ac2051bb8c8c403966c403f0642916b8dfc2b0 adds possibility to use regexps inside `url_map` paths. @damnever , could you build `vmauth` from this commit according to [these build instructions](https://victoriametrics.github.io/vmauth.html#how-to-build-from-sources) and verify whether it works as expected? The regexps must match full path. I.e. if you want routing urls with `/some/prefix/` prefix to a particular target, then `/some/prefix/.+` regexp must be used.

**Comment by damnever** [comment]
I haven't set up the VictoriaMetrics, but I tested it with an existed prometheus server, which seems to be fixed.

**Comment by damnever** [comment]
I have tested it in the VictoriaMetrics cluster, is there a release date for this?

**Comment by valyala** [comment]
`vmauth` release with this feature included should be published on the next week. I'll send a notification here when the release will be published.

**Comment by valyala** [comment]
Regexps can be used in `url_map` paths starting from [v1.56.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See https://victoriametrics.github.io/vmauth.html#auth-config for details. Closing this issue as done.
