### ISSUE TITLE
Query with range and offset has unpredictable results

### ISSUE THREAD

**Issue by slavitch** [VictoriaMetrics/VictoriaMetrics#1122]
I would expect this to return an empty set, but it does not, assuming the database is less than 3 years old:
curl -sS -XPOST  "http://localhost:8481/select/0/prometheus/api/v1/query?query=kafka_consumer_Confidence_24[1000d]" -d "offset 1000d"

Instead it returns a range with a value matching the most recently successful offset fetch, which in my case is:

curl -sS -XPOST  "http://localhost:8481/select/0/prometheus/api/v1/query?query=kafka_consumer_Confidence_24[1000d]" -d "offset 1d"

**Comment by valyala** [comment]
The `offset` part must be included in the query itself:

```
curl http://localhost:8481/select/0/prometheus/api/v1/query -d "query=kafka_consumer_Confidence_24[1000d] offset 1000d"
```

Note the MetricsQL query must be properly [urlencoded](https://en.wikipedia.org/wiki/Percent-encoding).

**Comment by slavitch** [comment]
Thanks that works.
