### ISSUE TITLE
Заглушка для influxdb со списком БД

### ISSUE THREAD

**Issue by proffust** [VictoriaMetrics/VictoriaMetrics#1124]
**Is your feature request related to a problem? Please describe.**
Некоторый софт при попытке писать по infux протоколу проверяет наличие БД(например Fluent), и если её не находит пытается создать или не запускается. Таким образом нет возможности писать некоторым софтом с VM по протоколу Influx

**Describe the solution you'd like**
Сделать заглушку для /query?q=SHOW+DATABASES который будет выдавать валидный ответ с заранее заданным списком баз, список можно передавать через параметры запуска

**Describe alternatives you've considered**
Альтернатива - nginx с двумя locations, но это выглядит как костыль
```
server{
	listen 8428;
	server_name _;
	location /query {
		return 200 '{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["juniper-nti"]]}]}]}';
	}

	location / {
		proxy_pass http://victoriametrics:8428;
	}
}
```

**Comment by proffust** [comment]
примеры, где столкнулся с этой проблемой
https://github.com/fangli/fluent-plugin-influxdb
https://github.com/Juniper/open-nti
https://github.com/Juniper/jtimon

**Comment by valyala** [comment]
@proffust , could you build VictoriaMetrics from the commit 7c37e9aea938c9c4c9b0b1d3510165e71be1ce3b according to [these docs](https://victoriametrics.github.io/#how-to-build-from-sources) and pass `-influx.databaseNames=_internal,juniper-nti` command-line flag to it? This flag instructs VictoriaMetrics returning the following response at `/query` handler:

```
{"results":[{"name":"databases","columns":["name"],"series":[{"values":[["_internal"],["juniper-nti"]]}]}]}
```

**Comment by denisgolius** [comment]
@proffust 
The docker image for test `victoriametrics/victoria-metrics:heads-master-0-g031d25681 `

**Comment by proffust** [comment]
Hello!
it works, thanks

**Comment by valyala** [comment]
The `-influx.databaseNames` command-line flag is available starting from [v1.56.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
