### ISSUE TITLE
How to query VictoriaMetric in go/rust

### ISSUE THREAD

**Issue by OutOfBoundCats** [VictoriaMetrics/VictoriaMetrics#1129]
Hi All

This is the stupiediest question in universe.
But can anyone help me in understanding how can i get data in and out of VictoriaMetric using programing language like go.

Thanks
Raj

**Comment by f41gh7** [comment]
Hello, VictoriaMetrics supports prometheus http api https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries.

 So you only need any http client, go has built-in `net/http`, for rust i can suggest reqwest https://github.com/seanmonstar/reqwest

**Comment by OutOfBoundCats** [comment]
Thanks for help @f41gh7

**Comment by OutOfBoundCats** [comment]
@f41gh7  just one more questioon does it support MetricsQl over http as well?

**Comment by valyala** [comment]
> just one more questioon does it support MetricsQl over http as well?

Yes - [MetricsQL](https://victoriametrics.github.io/MetricsQL.html) queries can be sent to `/api/v1/query` and `/api/v1/query_range` http endpoints - see https://victoriametrics.github.io/#prometheus-querying-api-usage .
