### ISSUE TITLE
Please fully support IPv6

### ISSUE THREAD

**Issue by grinapo** [VictoriaMetrics/VictoriaMetrics#1131]
**Is your feature request related to a problem? Please describe.**
Some functions doesn't support ipv6: none of the UDP listeners (influx, graphite) is able to bind to ipv6.
My machine does not have ipv4 address and now I have tried to send influx line protocol into it and realised that I cannot.

**Describe the solution you'd like**
A global switch enabling ipv6 which would enable it everywhere: tcp, udp, and whatever future protocols you support. :-)

**Describe alternatives you've considered**
No much options: packets are ipv6, bindind is ipv6. I could probably install some v6-to-v4 local proxy but it would be really ugly.

**Comment by valyala** [comment]
The commit 6378205415cf6f6a0682f024101fe581fa21d292 should enabe IPv6 UDP listening if `-enableTCP` command-line flag is passed to VictoriaMetrics.

**Comment by valyala** [comment]
VictoriaMetrics listens for IPv6 UDP if `-enableTCP` command-line flag is passed to it starting from [v1.56.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as done.

**Comment by flokli** [comment]
I think VM should use the defaults of the go stdlib by default, and not use custom dialers. I think this broke https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2573.
