### ISSUE TITLE
Add presision for select queries

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1133]
**Is your feature request related to a problem? Please describe.**
The response may be not deterministic when the result contains many digits after point
eg,
sum(irate(....)) -> 213.1333333333335 or 213.1333333333333

**Describe the solution you'd like**
I want to have option to add precision for select 

**Describe alternatives you've considered**
use `round` function

**Comment by f41gh7** [comment]
Added at commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/2dae0a2c47a116c0020ae7965b43d88f0c6f0c11

 Will be included to the next release.

**Comment by valyala** [comment]
[VictoriaMetrics v1.56.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) accepts `round_digits` query arg at `/api/v1/query` and `/api/v1/query_range` API handlers. For example, `/api/v1/query?query=avg(m)&round_digits=2` would return the average value for time series with name `m` rounded to two digits after the decimal point.

Closing the feature request as done.
