### ISSUE TITLE
Docker image does not start (lastest version 2021-03-16), asking for a license

### ISSUE THREAD

**Issue by niko2** [VictoriaMetrics/VictoriaMetrics#1135]
**Describe the bug**
Docker image victoriametrics/victoria-metrics:latest does not start

**To Reproduce**
Using docker-compose.yml

**Expected behavior**
Container should start

**Screenshots**
Logs seen :
```
 Copyright 2018-2021 VictoriaMetrics, Inc - All Rights Reserved.
 For any questions please contact info@victoriametrics.com
 
 Pass -eula command-line flag if you have an enterprise license for running this software
 See https://victoriametrics.com/assets/VM_EULA.pdf for details
```

**Version**
```
# docker run victoriametrics/victoria-metrics:latest --version
Copyright 2018-2021 VictoriaMetrics, Inc - All Rights Reserved.
For any questions please contact info@victoriametrics.com

Pass -eula command-line flag if you have an enterprise license for running this software
See https://victoriametrics.com/assets/VM_EULA.pdf for details
```

**Used command-line flags**
Those from docker-compose.yml

**Comment by valyala** [comment]
Enterprise version build accidentally overwritten `latest` tag. This should be fixed now.

**Comment by valyala** [comment]
@niko2 , could you verify that the `latest` tag points to public version of VictoriaMetrics and doesn't require passing `-eula` command-line flag?

**Comment by niko2** [comment]
It's working again.
Thank you @valyala
