### ISSUE TITLE
failed to remove directory  due to NFS lock

### ISSUE THREAD

**Issue by yangvipguang** [VictoriaMetrics/VictoriaMetrics#1142]
Version:
![image](https://user-images.githubusercontent.com/11416887/112105148-06a33e80-8be7-11eb-9f2f-5f63e8988af5.png)

bug:
![image](https://user-images.githubusercontent.com/11416887/112105117-fdb26d00-8be6-11eb-9165-0ed8e7bfd9f7.png)

**Comment by denisgolius** [comment]
This is a known warning as VictoriaMetrics tries to delete the out of retention directory before closing all files in it. Conventional posix-compatible file systems support such deletion but NFS does'n. It should disappear in next release.

**Comment by vuxuanlai** [comment]
Hi @denisgolius ,
This issue is still existing on version 1.58.0.

**Comment by valyala** [comment]
@vuxuanlai , @yangvipguang , could you try building `vmstorage` from the commit ab8008d6d7f66d714c5b13bf4f3aab1314a24526 and verify whether it fixes the issue?

**Comment by valyala** [comment]
See build instructions for cluster components at [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by valyala** [comment]
The bugfix with proper deletion of NFS directories has been included in [v1.59.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

@yangvipguang , @vuxuanlai , could you verify whether it works as expected now?

**Comment by faceair** [comment]
I also had this problem and I verified that this [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/bbebdf9ba1013560c152daa2d2e98e37a0de0745) has solved it.

**Comment by valyala** [comment]
Thanks for the update, @faceair ! Then closing the issue as fixed.
