### ISSUE TITLE
count_over_time cause victoria-metrics-arm crash

### ISSUE THREAD

**Issue by haerk** [VictoriaMetrics/VictoriaMetrics#1147]
**Describe the bug**
count_over_time cause victoria-metrics-arm crash

**To Reproduce**
wget --post-data='start=2020-01-01T00:00:00.000Z&end=2021-01-01T00:00:00.000Z&step=1d&query=count_over_time({__name__="his_metrics",spid="10/14"})' http://10.11.22.189:8428/api/v1/query_range

**Screenshots**
2021-03-25T04:31:51.549Z        info    /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/querystats/querystats.go:69 enabled query stats tracking at `/api/v1/status/top_queries` with -search.queryStats.lastQueriesCount=20000, -search.queryStats.minQueryDuration=0s
unexpected fault address 0x0
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x0 pc=0x5891a0]

goroutine 29 [running]:
runtime.throw(0x6b7c12, 0x5)
        /opt/go/src/runtime/panic.go:1116 +0x5c fp=0x1cab58c sp=0x1cab578 pc=0x454ec
runtime.sigpanic()
        /opt/go/src/runtime/signal_unix.go:692 +0x378 fp=0x1cab5a4 sp=0x1cab58c pc=0x5d3a0
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.removeNaNs(0x1b900b0, 0x1, 0x2, 0xa6bc2d00, 0xa6bc2d58, 0x19fd54)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/promql/exec.go:138 +0x6c fp=0x1cab600 sp=0x1cab5a8 pc=0x5891a0
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.timeseriesToResult(0x1b900b0, 0x1, 0x2, 0x1b90001, 0x1, 0x2, 0x0, 0x0, 0x1c820df)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/promql/exec.go:106 +0x30 fp=0x1cab6d8 sp=0x1cab600 pc=0x588b7c
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/promql.Exec(0x1c82070, 0x1b80640, 0x36, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/promql/exec.go:72 +0x2b8 fp=0x1cab7c8 sp=0x1cab6d8 pc=0x5885f4
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.queryRangeHandler(0xa7ee8f1, 0xc00f226f, 0x86404212, 0x2, 0xbf43b0, 0x7dc638, 0x1ad1a00, 0x1b80640, 0x36, 0x5e66e800, ...)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/prometheus/prometheus.go:1133 +0x308 fp=0x1cab91c sp=0x1cab7c8 pc=0x5c0420
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/prometheus.QueryRangeHandler(0xa7ee8f1, 0xc00f226f, 0x86404212, 0x2, 0xbf43b0, 0x7dc638, 0x1ad1a00, 0x11e4200, 0x13, 0x1098844)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/prometheus/prometheus.go:1093 +0x294 fp=0x1cab9f8 sp=0x1cab91c pc=0x5bfef8
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect.RequestHandler(0x7dc638, 0x1ad1a00, 0x11e4200, 0x1b700)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/vmselect/main.go:169 +0x1c5c fp=0x1cabc08 sp=0x1cab9f8 pc=0x5c6f8c
main.requestHandler(0x7dc638, 0x1ad1a00, 0x11e4200, 0x1)
        /mnt/data/build/VictoriaMetrics-1.56.0/app/victoria-metrics/main.go:103 +0x78 fp=0x1cabca4 sp=0x1cabc08 pc=0x5cac38
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0x177bf00, 0x7dc638, 0x1ad1a00, 0x11e4200, 0x6ffdac)
        /mnt/data/build/VictoriaMetrics-1.56.0/lib/httpserver/httpserver.go:268 +0x324 fp=0x1cabd38 sp=0x1cabca4 pc=0x3e75ac
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1(0x7dc638, 0x1ad1a00, 0x11e4200)
        /mnt/data/build/VictoriaMetrics-1.56.0/lib/httpserver/httpserver.go:186 +0x70 fp=0x1cabd74 sp=0x1cabd38 pc=0x3ea54c
net/http.HandlerFunc.ServeHTTP(0x177bf10, 0x7dc918, 0x10a8120, 0x11e4200)
        /opt/go/src/net/http/server.go:2012 +0x34 fp=0x1cabd84 sp=0x1cabd74 pc=0x28d990
net/http.serverHandler.ServeHTTP(0x1c84120, 0x7dc918, 0x10a8120, 0x11e4200)
        /opt/go/src/net/http/server.go:2807 +0x88 fp=0x1cabda0 sp=0x1cabd84 pc=0x2902d4
net/http.(*conn).serve(0x112c120, 0x7dd3d8, 0x100aca0)
        /opt/go/src/net/http/server.go:1895 +0x7d4 fp=0x1cabfdc sp=0x1cabda0 pc=0x28c89c
runtime.goexit()
        /opt/go/src/runtime/asm_arm.s:857 +0x4 fp=0x1cabfdc sp=0x1cabfdc pc=0x77a64
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2933 +0x2d0

goroutine 1 [chan receive]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/procutil.WaitForSigterm(0x1, 0x6b6ef5)
        /mnt/data/build/VictoriaMetrics-1.56.0/lib/procutil/signal.go:23 +0xb0
main.main()
        /mnt/data/build/VictoriaMetrics-1.56.0/app/victoria-metrics/main.go:66 +0x3a0

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
-20210325-044302--dirty-da39a3ee
```

**Used command-line flags**
./victoria-metrics-arm -opentsdbListenAddr=:4242 -storageDataPath=/mnt/data/victoria-metrics -retentionPeriod=300d

**Comment by valyala** [comment]
@haerk , could you share more information about the ARM machine used ?

Could you try the official ARM build from https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.56.0/victoria-metrics-arm64-v1.56.0.tar.gz ? There was arm-releated big in previous builds - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1074 .

**Comment by haerk** [comment]
My machine is 32 bit, so I compile from the source code.
Here is the kernel & golang version.
# uname -a
# Linux haerk 3.4.39-s5p4418 #1 SMP PREEMPT Mon Feb 10 12:18:40 CST 2020 armv7l armv7l armv7l GNU/Linux
# go version
# go version go1.14.3 linux/arm

**Comment by haerk** [comment]
My machine is 32 bit, so I compile from the source code.
Here is the kernel & golang version.
-uname -a
-Linux haerk 3.4.39-s5p4418 #1 SMP PREEMPT Mon Feb 10 12:18:40 CST 2020 armv7l armv7l armv7l GNU/Linux
-go version
-go version go1.14.3 linux/arm

**Comment by denisgolius** [comment]
@haerk 
Did you run officially builds from [Release 1.56](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.56.0) ?

**Comment by denisgolius** [comment]
@haerk 
Could you try to install the [latest go-lang](https://golang.org/dl/) version and try to build and run it again?

**Comment by f41gh7** [comment]
I suggest you to try compile `victoria-metrics` with command
`package-victoria-metrics-arm`, build it at any machine with docker and try to run at our OS. It must produce binary at `bin/victoria-metrics-arm-prod`

 For me at works good w/o any crashes:

```uname -a 
Linux osmc 4.9.29-12-osmc #1 PREEMPT Mon Oct 9 04:15:35 UTC 2017 armv6l GNU/Linux
./victoria-metrics-arm-prod --version
victoria-metrics-20210329-173533-tags-v1.56.0-0-g20ac89c4e
curl 'http://localhost:8428/api/v1/query_range?start=-20m' -g -d 'query=count_over_time(vm_log_messages_total)'
```


Btw, i wasn't able to compile it with go version `1.14`, coz it doesn't have url.Url Redacted method, which was added at go 1.15.

**Comment by valyala** [comment]
@haerk , try the following binary - [victoria-metrics-arm-heads-public-single-node-0-g65c60cf41.tar.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6224427/victoria-metrics-arm-heads-public-single-node-0-g65c60cf41.tar.gz).

FYI, the next release will contain the official binaries for `arm` architecture - see 75991277fa154404c4e870494abc4258e2c5cc22 and 65c60cf41347e01242b8e2dbc9f4c9951eb048c9 .

**Comment by valyala** [comment]
@haerk , try official binaries for `arm` architecture from the [release v1.57.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by haerk** [comment]
> @haerk , try official binaries for `arm` architecture from the [release v1.57.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Thank you very much. This version solves this problem
