### ISSUE TITLE
[Consult][vmagent] Do we have a retry-limit option

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#1149]
Hi VictoriaMetrics Community,
Here is a consulting issue, thanks for your repies.
# Background
We deploy a vmagent instance, which scraping metrics from k8s pods and remote_write to prometheus. We noticed that, in starting hours, vmagent sent sampls successfully, but it's blocked in few minutes after one hour. The panel screenshot is here
![image](https://user-images.githubusercontent.com/8848479/112572604-71da5400-8e25-11eb-8f03-1ff5febf67bd.png)

## Parameters
Our deployment parameters are
- vmagent(v1.56.0) 16c/40G `-remoteWrite.maxDiskUsagePerURL=4GiB -remoteWrite.queues=15`
- prom(v2.25.0) 64c/100G/1000G enable remote_write_receive feature, other options keep default

## What we have tried
1. we deploy a Prometheus for scraping and remote write the same receiving prometheus, there are no writing errors
![image](https://user-images.githubusercontent.com/8848479/112573045-74897900-8e26-11eb-8fdc-685482b8fc81.png)

## Help we need
According to above information, we are wondering that vmagent and prometheus cooperate unproperly. We want to make it clear that does vmagent write too fast and exceeds promtheus's receiving capacity. So do we have an option about remote_write samples limiting for vmagent?

Thanks!

**Comment by xiaozongyang** [comment]
ping @valyala 
cc @faceair

**Comment by f41gh7** [comment]
Any error logs at prometheus? As far as i remember, it doesn't accept out of order metrics and must log `Out of order sample from remote write` error. In this case `-remoteWrite.queues=1` should help.  Also, vmagents has metric with response codes from remote_write.

   Prometheus returns `Bad Request` - 400  https://github.com/prometheus/prometheus/blob/main/storage/remote/write_handler.go#L54
 While Thanos returns `Conflict` - 409 https://github.com/thanos-io/thanos/blob/d173bcb9a920eb4c96f98eb029d5d85a3cc0be99/pkg/receive/handler.go#L334

**Comment by xiaozongyang** [comment]
@f41gh7 
Thanks for your kindness!
I can find `Bad request, out of order` error messages in my Prometheus log, detail logs are
```
level=error ts=2021-03-26T06:42:29.993Z caller=write_handler.go:53 component=web msg="Out of order sample f
rom remote write" err="out of bounds"
level=error ts=2021-03-26T06:42:44.626Z caller=write_handler.go:53 component=web msg="Out of order sample f
rom remote write" err="out of order sample"
level=error ts=2021-03-26T06:42:46.115Z caller=write_handler.go:53 component=web msg="Out of order sample f
rom remote write" err="out of order sample"
level=error ts=2021-03-26T06:42:46.910Z caller=write_handler.go:53 component=web msg="Out of order sample f
rom remote write" err="out of order sample"
level=error ts=2021-03-26T06:42:48.343Z caller=write_handler.go:53 component=web msg="Out of order sample f
rom remote write" err="out of order sample"
```
I'll try to change the option `-remoteWrite.queues` to `1`, and check its behavior again.

---

Furthermore, When I use Prometheus remote write to Prometheus, I find out that Prometheus use 2 shards(showing at following picture) during this process. So do we have any sharding strategy according to `number of queues?` e.g sharding time series to exact queue.

![image](https://user-images.githubusercontent.com/8848479/112593324-4b76e180-8e42-11eb-86d8-5d23a902e10c.png)


Thanks!

**Comment by xiaozongyang** [comment]
And, does vmagent have any policy for evicting sampling that failing too many times or due to unrecoverable errors? e.g. `Bad Request` error because of `Out of order samples` or `Duplicate samples`

**Comment by xiaozongyang** [comment]
Hi @f41gh7,
I change the option `-remoteWrite.queues=1`, and the persistent queue size is shown in following picture. It seems that samples got lagged even only one queue.
![image](https://user-images.githubusercontent.com/8848479/112595653-acec7f80-8e45-11eb-8e85-ac53fe635972.png)

And when the persistent queue is full, vmagent stop sending samples.
![image](https://user-images.githubusercontent.com/8848479/112595832-f046ee00-8e45-11eb-848d-74701fad6a6a.png)

By the way, I'm trying to tuning this option, and find out that relation between `number of queues` and `persistent queue size`, here is the result

| number of queues | Time of no persistent queue lag(min) | Time of incrementally lag to full(min) |
|--------|-----------|-----------------|
| 1      |    0       |   18         |
| 4      |    8      |    9         |
| 8      |   12      |    9         |

And I check the log of vmagent, it shows that retrying of first `out of order samples` is executed periodically and seems never drop it. So when `out of order samples` error requests keep occurring, it will run out the space of persistent queue and make remote_write unavailable. 

This symptom is likely to some kind of leak. If I resolve the `out of order samples` error, it should never lag anymore!  Do I understand this behavior correctly?

**Comment by xiaozongyang** [comment]
ping @valyala @f41gh7 
Why don't we drop samples after some times failure retry or evict old blocks and keep remote_write works for new data? 

What I meet is when there are `400 Bad Request` errors caused by `out of order samples`, finally the vmagent will stop sending sampling to Prometheus and recent will lost, shown in following picture.

- vmagent's persisten queue is increasing until full
![image](https://user-images.githubusercontent.com/8848479/112621007-3612af00-8e64-11eb-9453-3b0c9121cad5.png)
![image](https://user-images.githubusercontent.com/8848479/112621300-8be75700-8e64-11eb-8f7f-e8eb8098fcdb.png)

- once the persistent queue is full, the sending blocks/samples metric is reduced to 0
![image](https://user-images.githubusercontent.com/8848479/112621389-a4577180-8e64-11eb-893b-ccbeaac6089d.png)

- 200 requests are 0 and all are 400 requests
![image](https://user-images.githubusercontent.com/8848479/112621463-be914f80-8e64-11eb-86cb-f93adfa65fd3.png)

**Comment by f41gh7** [comment]
We decided to drop such blocks, can you build `vmagent` from master branch and verify, that it works for you? 

 how to build from sources https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-build-from-sources

 or just run from root of repo `make package-vmagent`

**Comment by valyala** [comment]
> If I resolve the out of order samples error, it should never lag anymore! Do I understand this behavior correctly?

In this case Prometheus will store only a part of incoming data. Other data will be dropped by `vmagent` when it sees 400 response error from Prometheus. `vmagent` sends data to remote storage in blocks. Each block may contain many samples. Only a part of samples may be out of order, but `vmagent` will drop the whole block on 400 response error from Prometheus.

> do we have any sharding strategy according to number of queues? e.g sharding time series to exact queue.

All the blocks for a particular `-remoteWrite.url` are put in a shared buffer. Then `-remoteWrite.queues` concurrent workers fetch blocks one-by-one from this shared buffer and send them to remote storage over a dedicated connection. This means that data for the same time series can be split among connections (queues). This also means that blocks with newer samples can reach the remote storage faster than blocks with older samples for the same time series.

`vmagent` doesn't shard time series among queues, since this may result in uneven ingestion speed among queues, which may slow down the overall ingestion speed.

**Comment by xiaozongyang** [comment]
@f41gh7 @valyala 
Thank you, guys!

ping @f41gh7 
I will try to build `vmagent` from the master branch which git hash is `78188dec`, and scrape targets with this binary. Future feedback will be provided soon.

---

ping @valyala 
> `vmagent` doesn't shard time series among queues, since this may result in uneven ingestion speed among queues, which may slow down the overall ingestion speed.

According to this, it's reasonable that the `out of order samples` error will occur early or later, right? It's inevitable.

> vmagent sends data to remote storage in blocks. Each block may contain many samples from many time series. Only a part of samples may be out of order, but vmagent will drop the whole block on 400 response error from Prometheus, since it doesn't know exact samples, which leads to `out of order samples` error.

So, samples of some time series will be lost and never be appended to Prometheus. Can I make a conclusion simply that we should make `vm` work with `vmagent` instead of Prometheus? Since there is no `out of order samples` error raised by `vm`.

**Comment by xiaozongyang** [comment]
Hi @f41gh7 

When I try to build the binary on my mac by `GOOS=linux make vmagent`, I got an error with the following message
```
APP_NAME=vmagent /Library/Developer/CommandLineTools/usr/bin/make app-local
CGO_ENABLED=1 GO111MODULE=on go build  -mod=vendor -ldflags "-X 'github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=vmagent-20210328-092527-remotes-origin-HEAD-0-g78188dec'" -o bin/vmagent github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent
# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
make[1]: *** [app-local] Error 2
make: *** [vmagent] Error 2
```

When I search `implicit declaration of function 'setresgid' is invalid in C99` in Google, no explicit working solutions. Further help is needed.

**Comment by xiaozongyang** [comment]
ping @f41gh7 @valyala 

Here is feedback! When I set the option `-remoteWrite.queues=1`, the `out of order samples` error disappears from the log stream. But after few minutes, `out of bound` errors occur. And pending bytes are increasing, showing in the following picture.
![image](https://user-images.githubusercontent.com/8848479/112785017-9df41000-9085-11eb-8559-302e915d0a50.png)

It seems that only one queue is not enough for sending two many samples, more and more samples enter the queue and wait for being sent, finally `out of bound` error arose since there is a time range limit about appending samples to Prometheus. So the persistent queue gots lagged. Are there any problems about this deduction?

Thank you, guys! :)

**Comment by f41gh7** [comment]
> ping @f41gh7 @valyala
> 
> Here is feedback! When I set the option `-remoteWrite.queues=1`, the `out of order samples` error disappears from the log stream. But after few minutes, `out of bound` errors occur. And pending bytes are increasing, showing in the following picture.
> ![image](https://user-images.githubusercontent.com/8848479/112785017-9df41000-9085-11eb-8559-302e915d0a50.png)
> 
> It seems that only one queue is not enough for sending two many samples, more and more samples enter the queue and wait for being sent, finally `out of bound` error arose since there is a time range limit about appending samples to Prometheus. So the persistent queue gots lagged. Are there any problems about this deduction?
> 
> Thank you, guys! :)

 Trying to  increase queues size in this case. Also watch for metric at vmagent side `vmagent_remotewrite_packets_dropped_total`, it shows count of blocks being dropped by out of order error and other bad request error at remote write side.

**Comment by xiaozongyang** [comment]
@f41gh7 
Thanks for your suggestions. It seems that the problem is not solved but delayed, but it doesn't matter, it just a survey and experiment. 

This issue will be closed, thank you for the kindness and help.  Also thank you @valyala!

**Comment by valyala** [comment]
>> vmagent doesn't shard time series among queues, since this may result in uneven ingestion speed among queues, which may slow down the overall ingestion speed.

> According to this, it's reasonable that the out of order samples error will occur early or later, right?

Yes

> Can I make a conclusion simply that we should make vm work with vmagent instead of Prometheus? Since there is no out of order samples error raised by vm.

Yes

**Comment by valyala** [comment]
FYI, vmagent [v1.57.0 and newer versions](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) should drop the outgoing batch of samples if remote storage replies with `400 Bad Request` http status code.

**Comment by 123BLiN** [comment]
Sorry about necroposting, but what about such scheme:
vmagent -> vmagent -> thanos
in that case if thanos was down for some period of time - the pipeline never goes up, I see some 
```
sending a block with size 15472 bytes to \"1:secret-url\" was rejected (skipping the block): status code 409; response body: 4 errors: store locally for endpoint thanos-tenants-receive-2.thanos-tenants-receive-headless.monitoring.svc.us-east-1.k8s:10901: conflict; forwarding request to endpoint thanos-tenants-receive-0.thanos-tenants-receive-headless.monitoring.svc.us-east-1.k8s:10901: rpc error: code = AlreadyExists
```
but no recent metrics coming
