### ISSUE TITLE
/api/v1/labels/.../values not narrowed down by match[]

### ISSUE THREAD

**Issue by kmansoft** [VictoriaMetrics/VictoriaMetrics#115]
Not sure if this is a bug, I'm new to Victoria and have no prior experience with Prometheus, but..

Let's say there are two or more series that have same-named tags (labels).

I'm querying the list of label values, and only interested in those for a particular set of series, applying a filter:

```
curl -G 'http://localhost:8428/api/v1/label/sub/values' --data-urlencode 'match[]=disk_value' |  python -m json.tool
```
The result I receive is this:

```
{
    "data": [
        "aborted_clients",
        "aborted_connects",
        "access",
        "bytes",
        "bytes_received",
        "bytes_sent",
        "com_delete",
        "com_insert",
        "com_select",
        "com_update",
        "combined_read_bytes",
        "combined_read_count",
        "combined_write_bytes",
        "combined_write_count",
        "connections",
        "cpu",
        "disksize",
        "diskused",
        "free_bytes",
        "free_inodes",
        "instance_count",
        "io_read",
        "io_write",
        "load_avg",
        "max_used_connections",
        "qcache_hits",
        "qcache_inserts",
        "qcache_lowmem_prunes",
        "qcache_not_cached",
        "qcache_queries_in_cache",
        "read_count",
        "real_buffers",
        "real_cache",
        "real_free",
        "real_used",
        "realmemsize",
        "realmemused",
        "rss",
        "rx",
        "rx_4",
        "rx_6",
        "slow_queries",
        "swap_free",
        "swap_used",
        "swapsize",
        "swapused",
        "system",
        "total_bytes",
        "total_inodes",
        "tx",
        "tx_4",
        "tx_6",
        "user",
        "wait",
        "workers_reading",
        "workers_waiting",
        "workers_writing",
        "write_count"
    ],
    "status": "success"
}
```
This result includes the values of "sub" label from all the data that's there in the database.

I was expecting to see the list of values *only* for data where the series is `disk_value` as specified in the match.

This is not a show-stopper for me and I'm not even sure if this might be intended behavior, but it does seem a little strange.

**Comment by valyala** [comment]
The [/api/v1/label/.../values](https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values) handler doesn't accept additional filters according to Prometheus querying API. As I know, Grafana selects all the matching series from `/api/v1/series?match[]=...` handler and then manually extracts unique values for the given label. I'd recommend following this path.
