### ISSUE TITLE
add topologySpreadConstraints to clusters

### ISSUE THREAD

**Issue by eilonmonday** [VictoriaMetrics/VictoriaMetrics#1157]
Hey there, we face a problem that all vminsert pods are spread only on 2 nodes, when it has 8 available nodes to spread on.
It causes us overuse of node resources, and restarts to the nodes

I would like to have topologySpreadConstraints in the Victoria Metrics clusters.
Unlike clusters, victoria metrics operator contains topologySpreadConstraints

Thanks,
Eilon

**Comment by f41gh7** [comment]
Hello,

  `topologySpreadConstraints` will be supported by operator at the next release https://github.com/VictoriaMetrics/operator/issues/191

 helm chart doesn't support it atm. If you would be able to create pull request, it helps a lot.

**Comment by valyala** [comment]
`topologySpreadConstraints` is supported in the [latest helm charts for VictoriaMetrics](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-cluster#parameters). Closing the feature request as done.
