### ISSUE TITLE
vmagent support for AMQP

### ISSUE THREAD

**Issue by matejsp** [VictoriaMetrics/VictoriaMetrics#1159]
**Is your feature request related to a problem? Please describe.**
We would like to replace graphite with victoriametrics but to retain the functionality of fetching data from message queue (AMQP).

**Describe the solution you'd like**
In ideal scenario vmagent should fetch data from AMQP directly.

**Describe alternatives you've considered**
Reason for such setup is to not loose any metrics. For example when upgrading different parts of victorametrics. Message queue can buffer all non consumed metrics and after the system is back online they are processed.

**Additional context**
https://graphite.readthedocs.io/en/latest/feeding-carbon.html
https://github.com/grafana/carbon-relay-ng/blob/master/input/amqp.go
https://github.com/graphite-project/carbon/blob/master/lib/carbon/amqp_listener.py

**Comment by valyala** [comment]
FYI, [vmagent](https://docs.victoriametrics.com/vmagent/) already supports reading and writing data from the following message queues:

- [Google PubSub](https://docs.victoriametrics.com/vmagent/#google-pubsub-integration)
- [Kafka](https://docs.victoriametrics.com/vmagent/#kafka-integration)

**Comment by matejsp** [comment]
Yes Kafka is now supported. When I was working on this solution in 2021 we were using RabbitMQ as message broker not Kafka. We were looking for feature parity with graphite that supports AMQP. 

I understand you cannot support all the protocols (AMQP is standard https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol).

Today we would go with Vector for metrics shipping to vm: https://vector.dev/docs/reference/configuration/sources/amqp/
