### ISSUE TITLE
Victoria Metrics and Prometheus Inconsistency among data

### ISSUE THREAD

**Issue by gr8Adakron** [VictoriaMetrics/VictoriaMetrics#1166]
I have Multiple Prometheus push data to Victoria Metric VM for persistent storage then passing it on Promxy.

Version v1.56.0
The zone level information:

Prometheus   &nbsp;&nbsp;&nbsp;&nbsp;-->   Victoria Metric  &nbsp;&nbsp;&nbsp;-->     Promxy
(Australlia zone)      &nbsp;&nbsp;&nbsp;&nbsp;  (SouthEast Asia)   &nbsp;&nbsp;&nbsp; &nbsp;         (SouthEast Asia)

The issue is as I am trying to get the same query on Prometheus and Promxy(Indirectly Victoria Metric) and I cant see consistency among data:

### The Prometheus dashboard:
![image](https://user-images.githubusercontent.com/16715364/113105174-ebf04b80-921e-11eb-916c-63093a46b19c.png)

### The Promxy dashboard:
![image](https://user-images.githubusercontent.com/16715364/113105237-00344880-921f-11eb-93aa-aad181df6dd0.png)

**

> The queries are going in UTC

** 

The other weird thing is the Prometheus dashboard has all data while Promxy (Indirect Victoria Metric) dashboard only shows data if we timestamp filter of **>= 1hours** Which is Bizzare to me!

For example as you can see, no data for 30minute graph - which is present on Prometheus dashboard, ideally it should be present here as well.

![image](https://user-images.githubusercontent.com/16715364/113105514-4a1d2e80-921f-11eb-934e-8e2892c774e8.png)

any help will be appreciated!

**Comment by gr8Adakron** [comment]
@valyala - sorry for tagging but if could provide some help will be very kind.

**Comment by denisgolius** [comment]
@gr8Adakron, could you share screenshot from **VM**  but without **promxy**  and the result for query that **VM** will return?
Also, check, that the time on those instances is the same, because different time may be the reason of this issue.

**Comment by gr8Adakron** [comment]
WIth out Promxy, Victoria Metric actually matching(consistent) and am not getting the issue of metric available only for >= 1hour. 

So thank you @denisgolius that narrows down the problem to Promxy now.  Which is also some strange behavior because promxy doesnt store anything on its end. If I query Promxy, Promxy also send the request to Victoria Metric.

**Comment by valyala** [comment]
@gr8Adakron , thanks for the update! Closing this issue for now.
