### ISSUE TITLE
Add label filter to /status/tsdb

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#1168]
**Is your feature request related to a problem? Please describe.**
I want to have statistic by specific label, It can be useful when every team has own label. 

**Describe the solution you'd like**
Query parameters for `/api/v1/status/tsdb`

**Comment by valyala** [comment]
VictoriaMetrics accepts `match[]=<series_selector>` query args to `/api/v1/status/tsdb` starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/#tsdb-stats) for details. Closing the issue as done.
