### ISSUE TITLE
Release checksums files drop "GOARCH" variable from filename

### ISSUE THREAD

**Issue by Skunnyk** [VictoriaMetrics/VictoriaMetrics#1171]
**Describe the bug**
The generated `_checksums.txt` for releases does not contains the correct name of the VictoriaMetrics artifact, it drop the `GOARCH` variable on https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/Makefile#L114 : `sed s/-$(GOARCH)//`

**To Reproduce**
Download latest release for amd64 (1.57.1 atm)
Content of victoria-metrics-amd64-v1.57.1_checksums.txt:
```
26e0c869ce318bf8b950ef6c06205bdbaed154603cee401141c8677893f20a05  victoria-metrics-v1.57.1.tar.gz
8f8d818c639d9bb10ed1c9bb41ce7e03008f98b88b23ab15726ec48e1e576982  victoria-metrics-prod
```

```
$ sha256sum -c victoria-metrics-amd64-v1.57.1_checksums.txt
sha256sum: victoria-metrics-v1.57.1.tar.gz: No such file or directory
```

**Expected behavior**
The name inside the checksum file should be the same as the artifact, for example `victoria-metrics-amd64-v1.57.1.tar.gz`

**Comment by valyala** [comment]
@Skunnyk , the bug should be fixed in the commit 9d237408c655470cd75e0940dd9a389500279fab . Try running `make release-victoria-metrics` from this commit and verify whether it properly generates checksum file in `bin` directory.

**Comment by Skunnyk** [comment]
Thank you, it works :)

**Comment by valyala** [comment]
Checksum files should be properly generated starting from [v1.58.0 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
