### ISSUE TITLE
Add flag for /-/reload

### ISSUE THREAD

**Issue by hdost** [VictoriaMetrics/VictoriaMetrics#1172]
**Is your feature request related to a problem? Please describe.**
/-/reload is exposed by default which means that it and other admin functions could be spammed by accident or nefarious intent

**Describe the solution you'd like**
Add a flag similar to in prometheus which by default is disabled. (Could at least at the beginning be enabled by default, but allowed to be set false)

**Describe alternatives you've considered**
Working on authentication proxy to block such issues.

**Additional context**
https://prometheus.io/docs/prometheus/latest/management_api/

**Comment by valyala** [comment]
All the VictoriaMetrics components, which provide `/-/reload` handler - [vmagent](https://docs.victoriametrics.com/vmagent/#configuration-update), [vmalert](https://docs.victoriametrics.com/vmalert/#hot-config-reload), [vmauth](https://docs.victoriametrics.com/vmauth/#quick-start) and [single-node VictoriaMetrics](https://docs.victoriametrics.com/vmauth/) - support the `-reloadAuthKey` command-line flag, which can be used for protecting the access to `/-/reload` handler with `authKey` query arg.

For example, `./vmauth -reloadAuthKey=my_password` protects `/-/reload` endpoint at `vmauth` with `authKey=my_password`, so it can be requests only via `/-/reload?authKey=my_password`.

See the description for `-reloadAuthKey` command-line flag below:
```
   -reloadAuthKey value
     Auth key for /-/reload http endpoint. It must be passed as authKey=...
     Flag value can be read from the given file when using -reloadAuthKey=file:///abs/path/to/file
     or -reloadAuthKey=file://./relative/path/to/file . Flag value can be read from the given http/https url
     when using -reloadAuthKey=http://host/path or -reloadAuthKey=https://host/path
```

Closing the feature request as done.
