### ISSUE TITLE
Remove misleading description

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#1173]
**Is your feature request related to a problem? Please describe.**
This comment can be misleading by using Grafana for VictoriaMetrics https://github.com/VictoriaMetrics/VictoriaMetrics/blob/dc9eafcd023d569b2283f9c77bfdecbbf79639f8/dashboards/victoriametrics.json#L2657 

**Describe the solution you'd like**
Remove this description with links.

**Comment by valyala** [comment]
@denisgolius , could you give more details on why this description is misleading?

**Comment by hagen1778** [comment]
@denisgolius @valyala see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1185/commits/ad562fe34eb9abd387caac3af1c3cac763f186f6#diff-61af54205c2e1cfb2f5b49e95b0e42298a29d1ff8c04f62cc83c4befd3748c9aR2665

**Comment by denisgolius** [comment]
> @denisgolius @valyala see [ad562fe#diff-61af54205c2e1cfb2f5b49e95b0e42298a29d1ff8c04f62cc83c4befd3748c9aR2665](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ad562fe34eb9abd387caac3af1c3cac763f186f6#diff-61af54205c2e1cfb2f5b49e95b0e42298a29d1ff8c04f62cc83c4befd3748c9aR2665)

It looks pretty good.

**Comment by hagen1778** [comment]
@denisgolius dashboards were updated at https://grafana.com/orgs/victoriametrics

**Comment by denisgolius** [comment]
@hagen1778 Thank you a lot!
