### ISSUE TITLE
socks v5 as option for proxy_url for vmagent

### ISSUE THREAD

**Issue by rizwankh** [VictoriaMetrics/VictoriaMetrics#1177]
**Is your feature request related to a problem? Please describe.**
I need to scrape metrics out of a machine with only the ssh port open. I need to tunnel the http(metrics) over ssh.

**Describe the solution you'd like**
Socks v5 proxy would do the job for me.

**Describe alternatives you've considered**
There are no other alternatives as http/https proxy requires another port on the machine, which I cannot have.

**Comment by valyala** [comment]
@rizwankh , thanks for the feature request!

The workaround is to run [vmagent](https://victoriametrics.github.io/vmagent.html) on the host, so it could collect all the metrics locally and then push them to a central VictoriaMetrics instance. This approach is used by PMM - see https://www.percona.com/blog/2020/12/01/foiled-by-the-firewall-a-tale-of-transition-from-prometheus-to-victoriametrics/

**Comment by rizwankh** [comment]
@valyala Thanks for the tip. 

Checked, the machine has a very strict fw and not even able to access anything that I could use for VM.

**Comment by rizwankh** [comment]
@valyala I know its asking for too much, is there a way I can know when this Feature Request will be taken care of? Any sort of  
time frame so that I can plan on my end, if I need a workaround for a certain amount of time. :)

**Comment by valyala** [comment]
@f41gh7 , what do you think?

**Comment by f41gh7** [comment]
I think, its possible to add, more over prometheus supports it.

**Comment by f41gh7** [comment]
Funny fact, its already supported with flag `--promscrape.streamParse`. 

 This pr must add support for default client https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1178

**Comment by rizwankh** [comment]
awesome! Thanks a lot :)

**Comment by valyala** [comment]
@rizwankh , could you build `vmagent` from the commit a4c6a3b3e191e70e7e8d8d43cc98e0fcfa2b32a5 and verify whether it properly supports socks5 proxy? Build instructions:

```
git clone https://github.com/VictoriaMetrics/VictoriaMetrics
cd VictoriaMetrics
git checkout a4c6a3b3e191e70e7e8d8d43cc98e0fcfa2b32a5
make vmagent-prod
```

The resulting binary will be available in `bin` folder. See [these build instructions](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources) for more details.

**Comment by rizwankh** [comment]
Checked and its working fine. Thanks a lot for such a quick response. Really appreciated. VM is awesome and you guys are even better!

**Comment by valyala** [comment]
FYI, `vmagent` supports `socks5` for `proxy_url` starting from [v1.58.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
