### ISSUE TITLE
Why retentionPeriod default set to 0?

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1181]
Hi there,
I'm using VM which deployed on k8s. In values file of helm, I set `retentionPeriod=10d`. When I restart vmsingle pod, the `retentionPeriod`  was set to 0 which as below. I don't know why. 
![vm](https://user-images.githubusercontent.com/1458400/113511299-5ee42400-9589-11eb-9fe3-78667a32f381.PNG)

I would like to know what is `retentionPeriod=0`? and How will it affect my storage?
Thanks.

**Comment by f41gh7** [comment]
Hello, seems like you need to upgrade helm chart version.

 Related issue at https://github.com/VictoriaMetrics/helm-charts/issues/88

**Comment by vuxuanlai** [comment]
Thanks, issue closed
