### ISSUE TITLE
Ignore `/query_exemplars` requests from Grafana to VM datasource

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1186]
Prometheus datasource in Grafana now performs extra HTTP GET request  `api/v1/query_exemplars`. See https://github.com/grafana/grafana/commit/b649bfc270a08ba54f96326ddf5be337a6030cfb#diff-a4c7450a7fbfcf23283bf451fef14397c9b007c8fdba59ffe497fb55b2813e6bR665. Since VM does not support such path it logs an error `unsupported path requested: "/select/0/prometheus/api/v1/query_exemplars"` and increments corresponding errors metrics. This may have negative impact on user's experience while using VM as datasource in Grafana and produce false-positive errors for those who relies on metrics for logs/errors.

**Describe the solution you'd like**
Support `/query_exemplars` path but respond with empty response.

**Comment by valyala** [comment]
This has been addressed in the following commits:

* single-node VictoriaMetrics - 7d23598b33dfd127ab06b21bc03c89943aeaa3e9
* cluster VictoriaMetrics - 7fce4e9fb4031b4fe31b008015ce9fef1f20268d

**Comment by hagen1778** [comment]
Much appreciated!

**Comment by valyala** [comment]
VictoriaMetrics returns an empty stub for request to `/api/v1/query_exemplars` starting from [v1.58.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
