### ISSUE TITLE
Add ability to have tenant relabel configs in vminsert.

### ISSUE THREAD

**Issue by arramos84** [VictoriaMetrics/VictoriaMetrics#1188]
While vmagent is great, there might not be a need to use it, and therefore it would be really useful if tenant specific relabeling could be done at the vminsert. This reduces complexity in architectures that don't need a vmagent. 

Our specific use case is managing a multi-tenant VictoriaMetrics cluster where tenants can update their own relabel configurations, vminsert would pick up the changes with a configmap reload (this should be easily done with a configMap reload sidecar), and changes would only affect that specific tenant. Right now vminsert has a global relabel configuration, but this isn't realistically useful on a tenant by tenant basis.

If you'd like more info on this request, please let me know. Would greatly appreciate this feature!

**Comment by valyala** [comment]
This feature is likely to be implemented in an [enterprise package](https://victoriametrics.com/enterprise.html) for VictoriaMetrics. Feel free contacting us at info@victoriametrics.com in order to discuss feature details and prioritizing it.

**Comment by arramos84** [comment]
> This feature is likely to be implemented in an [enterprise package](https://victoriametrics.com/enterprise.html) for VictoriaMetrics. Feel free contacting us at [info@victoriametrics.com](mailto:info@victoriametrics.com) in order to discuss feature details and prioritizing it.

Sounds good, will be reaching out shortly!

**Comment by hagen1778** [comment]
@valyala can this be achieved via https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy-via-labels ?

**Comment by leoskyrocker** [comment]
> vminsert would pick up the changes with a configmap reload (this should be easily done with a configMap reload sidecar), and changes would only affect that specific tenant.

That is saying in your architecture, you have one vminsert per tenant?
(In our multitenancy design, we have many vmagents in different tenants, and they all end up in one VMCluster.)

**Comment by arramos84** [comment]
We have actually implemented all our relabeling at the vmagent since I wrote this up a while back. It works well and is more practical for controlling blast radius as well as other features vmagent has. Amazing how things evolve! 

Thanks for all the work, feel free to close this ticket.
