### ISSUE TITLE
multiple use of topk_max returns inconsistent results

### ISSUE THREAD

**Issue by shenxingbo** [VictoriaMetrics/VictoriaMetrics#1189]
use topk_max(100, filter) and topk_max(50, filter), found that the first 50 results of the two requests have different parts.

**Comment by valyala** [comment]
The issue must be fixed in the commit 1177dca3da7122935d5f60685907d203e0096cbf . @shenxingbo , could you build VictoriaMetrics from this commit and verify whether it fixes the issue? See [build instructions](https://victoriametrics.github.io/#how-to-build-from-sources).

**Comment by valyala** [comment]
VictoriaMetrics should return series in consistent order from `topk*` and `bottomk*` functions starting from [v1.58.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed.
