### ISSUE TITLE
Wrong vmalert:1.58.0 image

### ISSUE THREAD

**Issue by lujiajing1126** [VictoriaMetrics/VictoriaMetrics#1193]
**Describe the bug**

vmalert:1.58.0 image contains vmagent-prod binary

**To reproduce**

```shell
$ dive victoriametrics/vmalert:v1.58.0
```

**Screenshots**

![image](https://user-images.githubusercontent.com/2568208/113993957-8b4cb880-9887-11eb-8b0a-0fcafb54b7a8.png)

**Comment by valyala** [comment]
Re-uploaded docker image for vmalert:1.58.0

**Comment by valyala** [comment]
@lujiajing1126 , could you verify whether the newly uploaded docker image for vmalert:1.58.0 contains the expected `vmalert-prod` binary?

**Comment by lujiajing1126** [comment]
> @lujiajing1126 , could you verify whether the newly uploaded docker image for vmalert:1.58.0 contains the expected `vmalert-prod` binary?

Thanks. It is fine now. But I have to delete the local image cache on the node,

```shell
$ sudo docker rmi victoriametrics/vmalert:v1.58.0
```

**Comment by valyala** [comment]
It looks like the Docker builder used for building VictoriaMetrics images - `moby/buildkit:buildx-stable-1` - had some issues, which resulted in building `vmalert` image with `vmagent-prod` binary. Still investigating this issue.

**Comment by valyala** [comment]
Closing this issue for now. Let's re-open it if it will appear in future releases.
