### ISSUE TITLE
support for dynamic changes in the vmauth auth configuration file

### ISSUE THREAD

**Issue by t0p4** [VictoriaMetrics/VictoriaMetrics#1194]
**Is your feature request related to a problem? Please describe.**
Add the ability to apply changes to the auth configuration file without manually sending the SIGHUP signal.  
I always get frustrated when I have to restart vmauth after adding credentials.

**Describe the solution you'd like**
Everything should be automatic, in real-time (no restarts, no connection interruptions), the fully dynamic configuration.
Configuration can be changed and easily applied without interrupting the request or losing the connection.

**Describe alternatives you've considered**
Add the watch option to allow vmauth to automatically watch for file changes.

**Comment by valyala** [comment]
It may be hard automatically determining when the config is ready to be read after the update. Otherwise the config can be read in the middle of update, which can result in broken config.

**Comment by t0p4** [comment]
@valyala Maybe create a check on the config object before applying it?

**Comment by valyala** [comment]
@t0p4 , could you share more details on why reloading `vmauth` config via SIGHUP doesn't work for your case?

**Comment by t0p4** [comment]
@valyala I'm starting service in a Docker container, in order to apply the service configuration, I need to send a SIGHUP to the docker container.

**Comment by jtyr** [comment]
What about to equip `vmauth` with an API and expose `/_/reload` endpoint which would allow to reload the config? That would also open the possibility to manage it via VictoriaMetrics Operator.

**Comment by valyala** [comment]
@f41gh7 , is it possible to send `SIGHUP` signal to `vmauth` pod via [VictoriaMetrics Operator](https://github.com/VictoriaMetrics/operator)?

**Comment by f41gh7** [comment]
VictoriaMetrics Operator doesn't support it yet. Need to think, how to implement it better. Any use cases or suggestion are welcome.

 For now, reload-config container can be added to the `vmauth` helm chart with extraContainers: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-auth/values.yaml#L70

**Comment by jtyr** [comment]
@valyala It's not only about reloading it. `vmauth` deserves to have it's own Custom Resource for managing individual users. Then, instead of editing the same `ConfigMap`, you just keep adding/removing/modifying CR for individual users and VictoriMetrics Operator will take care of composing the final `ConfigMap` and reloading the `vmauth` processes.

**Comment by f41gh7** [comment]
> @valyala It's not only about reloading it. `vmauth` deserves to have it's own Custom Resource for managing individual users. Then, instead of editing the same `ConfigMap`, you just keep adding/removing/modifying CR for individual users and VictoriMetrics Operator will take care of composing the final `ConfigMap` and reloading the `vmauth` processes.

 I've created linked issue for CRD https://github.com/VictoriaMetrics/operator/issues/245

 Any ideas are welcome.

**Comment by valyala** [comment]
FYI, `vmauth` supports config reload via `/-/reload` http endpoint starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). The endpoint is protected by auth key if `-reloadAuthKey` command-line flag is set.

**Comment by jesusheredia-consensys** [comment]
If you are using helm charts,  you can annotate vmauth secret with https://github.com/stakater/Reloader/blob/master/docs/How-it-works.md , so it gets reloaded on changes

**Comment by valyala** [comment]
See [how to re-load vmauth config without restart](https://docs.victoriametrics.com/vmauth/#quick-start).

Closing this feature request as addressed.

**Comment by valyala** [comment]
Note that `vmauth` supports the ability to automatically reload `-auth.config` on the given interval when `-configCheckInterval` command-line flag is set to the duration bigger than 0, starting from [v1.90.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3990).
