### ISSUE TITLE
Native export format is not documented

### ISSUE THREAD

**Issue by rbtcollins** [VictoriaMetrics/VictoriaMetrics#1203]
**Describe the bug**
The native export format is not documented.

The native export format seems to be the fastest way to get metrics out of VM, but it requires reverse engineering via the source code. At least - I couldn't find any docs on the format, nor any Rust/Python/Go libraries for parsing such exports.

**To Reproduce**
Export some metrics and go to analyse them using your favourite language. Realise you can't parse the files.

**Expected behavior**
The format would be documented - and ideally language bindings maintained and available.

**Screenshots**

**Version**
Applies to all versions at time of filing

**Used command-line flags**
Not relevant

**Comment by valyala** [comment]
The native export format isn't documented intentionally, since it may change in incompatible way over time. It may be documented later when we'll see it is stabilized and isn't going to be modified.

**Comment by rbtcollins** [comment]
Fair enough. The docs however don't say that one cannot depend upon exporting from VictoriaMetrics version X and importing into VictoriaMetrics version Y. So perhaps updating the docs to say that this format is unstable and version-specific would be useful.

**Comment by valyala** [comment]
@rbtcollins , docs have been updated according to the suggestion in the commit e9898e1772acd727845aa19e6362200da1d90983

**Comment by rbtcollins** [comment]
@valyala cool, thanks. Up to you whether you keep the bug open for long term documentation of the format, or close as an obvious thing to do when you stabilise the format...

**Comment by valyala** [comment]
Let's close the issue for now and will re-open new one when the native export format is stabilized.
