### ISSUE TITLE
JSON export format is not valid JSON

### ISSUE THREAD

**Issue by rbtcollins** [VictoriaMetrics/VictoriaMetrics#1205]
**Describe the bug**

The JSON export format generates a series of JSON documents separated by `\n` characters. This isn't valid JSON: https://www.crockford.com/mckeeman.html defines valid JSON.

One easy way to convert it to valid JSON would be to wrap the export in a list: prepend `[`, add `,` to the separator between metrics, elide that for the last metric, and conclude with `]`.

**To Reproduce**
Export in JSON format.

**Expected behavior**
The JSON exported contents should be parsable by a JSON parser.

**Screenshots**
```
Python 3.9.1 (default, Jan  7 2021, 11:37:59) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> f = open('metrics.json', 'rt').read()
>>> json.loads(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robertc/.pyenv/versions/3.9.1/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/robertc/.pyenv/versions/3.9.1/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 146369)
>>> 
```

**Version**
Applies to all versions at time of filing

**Comment by rbtcollins** [comment]
Also the JSON schema isn't documented, which would be a nice thing to do, but I presume its the same story as the native one vis-a-vis backwards compat and changes.

**Comment by f41gh7** [comment]
Its json line protocol, which allows you to consume result with stream parser. 

 Minimal working example:

```python
import requests as re
import json
import io

url = 'http://localhost:8428/api/v1/export?match[]={__name__!=""}&start=-1d'

with re.get(url,stream=True) as resp:
   if resp.status_code != 200:
     print("unexpected status code: %d, reason: %s"%(resp.status_code,resp.text))
     exit(1)
   stream = io.StringIO(resp.text)
   for line in stream.readlines():
     print(json.loads(line))
```

  Its documented here https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-export-data-in-json-line-format

**Comment by rbtcollins** [comment]
I see; thank you. I missed the wiki link.
