### ISSUE TITLE
unit in "Labels limit exceeded" panel 

### ISSUE THREAD

**Issue by datamuc** [VictoriaMetrics/VictoriaMetrics#1206]
Hi,

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/251747e2535b19c9cb1cfc19832d759555ab5bc2/dashboards/victoriametrics.json#L3031

I think percent doesn't make sense here. A simple "short" is good enough.

**Comment by valyala** [comment]
@hagen1778 , could you look at this issue?

**Comment by valyala** [comment]
The issue has been addressed in the commit b955fe003876bf822aa87faa35e53deb13f3e4b9 . The commit will be included in the next release of the official dashboard for VictoriaMetrics. Closing the issue as fixed.
