### ISSUE TITLE
is not recommand enable vmselect replicationfactor in cluster with data

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#1207]
According to the doc https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/docs/Cluster-VictoriaMetrics.md#replication-and-data-safety

> When the replication is enabled, -replicationFactor=N and -dedup.minScrapeInterval=1ms command-line flag must be passed to vmselect nodes. 

but for a cluster with data exist, partial responses will be return sometimes after RF enable in `vmselect`

![vm rf=2 issue (2)](https://user-images.githubusercontent.com/3345153/114576437-b97a3000-9cad-11eb-8c85-bd251b546d66.png)

Assuming that we enable `replicationFactor` in `vminsert` and `vmselect` at `t`.

the query like `query_range?query=q&start=t-n&end=t+n` may be return partial data.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/72c41323fa0301f29167948a9bba01b468bc4585/app/vmselect/netstorage/netstorage.go#L1373

eg. `node2` and `node3` hit, and `node1` will be ignore in some reason( but `node1` still alive, it's just slower then `node2` and `node3`). so the result data of `series1` which before `t` will be disappear.

so if you has running victoriametrics for a while, is not recommand enable replicationfactor in `vmselect`.

**Comment by valyala** [comment]
Mentioned about this case in the commit 574b80f274eb4b7d95c5571617c18228fd5a9203

**Comment by valyala** [comment]
FYI, the next release of VictoriaMetrics will change the behavior for `-replicationFactor` command-line flag at `vmselect` - now it will wait for responses from all the `vmstorage` nodes before returning the response. If less than `-replicationFactor` vmstorage nodes are unavailable during the query, then the response is considered full. This should reduce the probability of returning incomplete response when `-replicationFactor` is set to values bigger than 1 at `vmselect`. See [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/711#issuecomment-1627802973) for details.

**Comment by valyala** [comment]
FYI, the behaviour documented [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1207#issuecomment-1627803864) is implemented in VictoriaMetrics since [v1.91.3](https://docs.victoriametrics.com/CHANGELOG.html).
