### ISSUE TITLE
Over time functions returns wrong last value in query range 

### ISSUE THREAD

**Issue by paoloach** [VictoriaMetrics/VictoriaMetrics#1221]
**Describe the bug**
Given a timeseries with data from `t1` to `t2`,  given a step `s1` and a time `tstart` such that `t1  < tStart < t2` and  a time `tEnd  < t2 + step`, a  query range like

```
query=sum_over_time(metric{label="aacc959a-17bd-4c05-8e8d-b07c90a389d4"}[step])&start=tStart&endtEnd&step=step&nocache=1	
```

return a set of `(timestamp, samples)` whose last value is the same of the second to last.

**To Reproduce**
Steps to reproduce the behavior.

Add this timeseries:

```
,l1=res1 metric1=10 1618390799000000000
,l1=res1 metric1=20 1618412399000000000
,l1=res1 metric1=30 1618433999000000000
,l1=res1 metric1=40 1618448399000000000
,l1=res1 metric1=50 1618462799000000000
,l1=res1 metric1=60 1618484399000000000
```

Executed this query:

```
query=sum_over_time(metric1{l1="res1"}[86400s])&start=2021-04-14T00:00:00Z&end=2021-04-16T00:00:00Z&step=86400s&nocache=1
```
the result is:
```
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "l1": "res1"
                },
                "values": [
                    [
                        1618444800,
                        "60"
                    ],
                    [
                        1618531200,
                        "60"
                    ]
                ]
            }
        ]
    }
}
```

**Expected behavior**
The value for the `timesteps 1618531200` shuld be:

```
60+50+40 = 150
```

**Version**
v1.51.0-cluster

**Comment by f41gh7** [comment]
Hello, can you try to upgrade for the latest version - `v1.58.0` ? There were few fixes for this functions since v1.51.0

**Comment by paoloach** [comment]
Thanks Nikolay, it works.

**Comment by paoloach** [comment]
@f41gh7 do you know if there is a specific issue related to my problems ? You know, to adding as reference in the my application issue

**Comment by valyala** [comment]
It is likely the issue has been fixed in the commit 8749c2dd9257044cc14eca069228e0d73cba608c , which has been included in v1.53.0 and newer releases.

**Comment by paoloach** [comment]
Thanks.
Unfortunately I had to  downgrade again to the 1.51 version because the 1.58 version produced a noticeable slowdown (about 10 times !). I think I will open a new issues defining better the problem.

**Comment by valyala** [comment]
Closing this issue as fixed according to [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1221#issuecomment-820941567).
