### ISSUE TITLE
UI for vmalert

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1223]
**Is your feature request related to a problem? Please describe.**
To improve user's experience vmalert needs a UI to display groups, rules, active alerts, apply simple filtering etc. 
Vmalert already exposes such an information, so we should consider to keep it as is in case if someone needs to use it for integrations. The graphical UI can use existing API but display it in a fancy manner.

**Comment by valyala** [comment]
The initial version of UI for vmalert has been included in [v1.66.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) . Closing the feature request as done.
