### ISSUE TITLE
Can VictoriaMetrics store many time-series data into ceph cluster?

### ISSUE THREAD

**Issue by btdan** [VictoriaMetrics/VictoriaMetrics#1230]
Hello, I am new to VictoriaMetrics  and want to use my ceph cluster to store the time-series data collected by Prometheus.
I have already collected data from Prometheus and stored it into local disk.
However, I want to know whether VictoriaMetrics can store data into ceph cluster instead of local disk?And where can I find the method?
Thanks very much.

**Comment by denisgolius** [comment]
@btdan 
You can mount ceph cluster to your local machine as a file system or in any way you want to use this storage. We know that some users use VictoriaMetrics on Ceph clusters without any problems.

This link could help https://docs.ceph.com/en/nautilus/cephfs/#using-cephfs .

**Comment by valyala** [comment]
[Ceph Block storage](https://ceph.io/ceph-storage/block-storage/) can be used for storing VictoriaMetrics data as well.

**Comment by valyala** [comment]
Closing the question as answered.
