### ISSUE TITLE
vmtctl does't write any information into log about the last imported timestamp if this process was interrupted by the user.

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#1236]
**Is your feature request related to a problem? Please describe.**
**vmtctl** doesn't write any information into log about the last imported timestamp if this process was interrupted by the user. For example, if you start **vmtctl** without using a screen and interrupt or kill the import process - nothing will be written to the log. If the information was imported over a long period that contains a huge amount of data  then you will have to do the import from the very beginning even if you will use **deduplication** and you will have to wait a long time again.

**Describe the solution you'd like**
It is necessary to add the functionality for logging the last imported timestamp by vmtctl for any completion scenario: both user and import errors.

**Describe alternatives you've considered**
Perhaps it is worth adding the functionality of continuing the import from the place of the last imported timestamp, or implementing other functionality that will allow do not to run import from the very beginning when it need to import a huge amount of data.

**Comment by hagen1778** [comment]
Hey @denisgolius! Do you mind to try if https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2006 works for you?

**Comment by denisgolius** [comment]
> Hey @denisgolius! Do you mind to try if #2006 works for you?

I will try it and give a feedback. Thanks!

**Comment by valyala** [comment]
`vmctl` should write the information about the last imported sample when it is interrupted because of error or because of user action, starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as done.
