### ISSUE TITLE
Different directory for storageDataPath for service

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/VictoriaMetrics#124]
Different directory for storageDataPath for service
A few days ago was add service.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/package/victoria-metrics.service#L10
```
storageDataPath /var/lib/victoria-metrics
```

Many people used https://github.com/patsevanton/victoriametrics-rpm and used
```
-storageDataPath=/var/lib/victoria-metrics-data
```

Nobody used https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/package/victoria-metrics.service.
I propose change 
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/package/victoria-metrics.service#L10
```
-storageDataPath /var/lib/victoria-metrics
```
to
```
-storageDataPath=/var/lib/victoria-metrics-data
```

**Comment by valyala** [comment]
Agreed.

@kmansoft , could you update the `-storageDataPath` in `package/victoria-metrics.service` accordingly?

**Comment by patsevanton** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/125
