### ISSUE TITLE
vmagent: show endpoint overview

### ISSUE THREAD

**Issue by MorphBonehunter** [VictoriaMetrics/VictoriaMetrics#1251]
For easy overview of useful endpoint `vmagent` should list this endpoints on "/" on the http listen port.
This would be analogous to `victoriametrics` and `vmalert` which show things like "/metrics" and "/targets" for example.
The endpoints are nearly the same as in `victoriametrics`:
* /targets
* /api/v1/targets
* /metrics

**Comment by valyala** [comment]
The list of user-visible endpoints for `vmagent` has been added in the commit 6fa5981e68006a77311c1a74bbfa6fddf6bf3ad0 . This commit will be included in the next release.

**Comment by valyala** [comment]
The list of user-visible endpoints for `vmagent` has been added in the commit 6fa5981e68006a77311c1a74bbfa6fddf6bf3ad0 . This commit will be included in the next release.

**Comment by MorphBonehunter** [comment]
Great! Thanks.

**Comment by valyala** [comment]
`vmagent` shows the list of exposed endpoints at `http://vmagent:8429/` starting from [v1.59.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
