### ISSUE TITLE
vmselect doesn't use cache folder

### ISSUE THREAD

**Issue by sagor999** [VictoriaMetrics/VictoriaMetrics#1254]
**Describe the bug**
It seems like vmselect doesn't use or cannot use cache folder that is allocated to it.
We are using cluster helm chart, with cache mount path set to: `cacheMountPath: /cache`
and persistent volume allocated for it with the size of 4GB.
But running `du -h` in `/cache` folder always shows zero usage:
```
/cache # du -h
4.0K	./tmp/searchResults
8.0K	./tmp
16.0K	./lost+found
72.0K	./rollupResult
100.0K	.
```
What makes me think that maybe it cannot use cache for some reason, is that we are getting this error on running long query:
```
Error executing query: 422: error when executing query="sum(node_scrape_collector_duration_seconds{job=\"nodes\"})" on the time range (start=1617206489947, end=1619625689947, step=9676000): cannot execute query: error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage central-vmstorage-2.central-vmstorage.monitoring.svc.cluster.local:8401: cannot execute rpcName="search_v4" on vmstorage "240.1.34.26:8401" with timeout 30.000 seconds (elapsed 10.224 seconds); the timeout can be adjusted with `-search.maxQueryDuration` command-line flag: cannot process MetricBlock #327: cannot write MetricBlock to temporary blocks file: cannot write block to "/cache/tmp/searchResults/779926288": write /cache/tmp/searchResults/779926288: no space left on device
```
for some reason it is getting `no space left on device` even though it has 4GB of free storage? or does it attempt to write more than 4GB file at once?
Here is an actual error from vmselect log:
```
{"ts":"2021-04-28T15:53:50.671Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:490","msg":"error in \"/select/0/prometheus/api/v1/query_range?nocache=1\": error when executing query=\"sum(node_scrape_collector_duration_seconds{job=\\\"nodes\\\"})\" on the time range (start=1614786812809, end=1619625212809, step=19353000): cannot execute query: error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage central-vmstorage-1.central-vmstorage.monitoring.svc.cluster.local:8401: cannot execute rpcName=\"search_v4\" on vmstorage \"240.1.32.27:8401\" with timeout 30.000 seconds (elapsed 18.113 seconds); the timeout can be adjusted with `-search.maxQueryDuration` command-line flag: cannot process MetricBlock #122: cannot write MetricBlock to temporary blocks file: cannot write block to \"/cache/tmp/searchResults/048604339\": write /cache/tmp/searchResults/048604339: no space left on device"}
```

**To Reproduce**
Install victoria-metrics-cluster version with vmselect using persistent volume. and try to run very large or long query that would aggregate lots of results.

**Expected behavior**
Query should complete and cache should be used to speed up subsequent queries

**Version**
Using victoria-metrics-cluster helm chart version: 0.8.24
victoria metrics version: 1.58.0-cluster

**Used command-line flags**
```
- args:                                                                                  
  - --cacheDataPath=/cache                                                               
  - --storageNode=central-vmstorage-0.central-vmstorage.monitoring.svc.cluster.local:8401
  - --storageNode=central-vmstorage-1.central-vmstorage.monitoring.svc.cluster.local:8401
  - --storageNode=central-vmstorage-2.central-vmstorage.monitoring.svc.cluster.local:8401
  - --selectNode=central-vmselect-0.central-vmselect.monitoring.svc.cluster.local:8481   
  - --selectNode=central-vmselect-1.central-vmselect.monitoring.svc.cluster.local:8481   
  - --selectNode=central-vmselect-2.central-vmselect.monitoring.svc.cluster.local:8481   
  - --envflag.enable=true                                                                
  - --envflag.prefix=VM_                                                                 
  - --loggerFormat=json                                                                  
```

**Comment by sagor999** [comment]
Update:
I increased cache folder size to 32GB and that error went away. So it was indeed hitting size limit (and query timeout limit at the same time). 
Though I noticed that it would dump cache query into cache folder, but then it would immediately delete it. 
I was under impression that it can use that cache folder to speed up subsequent requests (since it does attempt to load data from cache folder at start up). Is that intentional that cache gets cleaned up right away?

**Comment by f41gh7** [comment]
Hello, vmselect uses `/cache` dir for:
1) saving in-memory cache at service shutdown, to be able to load it after restart.
2) saving response from vmstorage for query processing. When vmselect requests data from vmstorage and saves response to the disk if needed. Usually it happens, when response to big and cannot be processed in-memory. After that, vmselect applies all needed query functions (sum, group, etc) and saves result of query at in-memory cache. When its done, vmselect removes cached data for query from disk.

**Comment by sagor999** [comment]
Thank you for explanation! Closing this issue now.
