### ISSUE TITLE
How to set legend of max avg and min value of rollup_rate return seperately in Grafana?

### ISSUE THREAD

**Issue by tongorz** [VictoriaMetrics/VictoriaMetrics#1255]
How to set legend of max avg and min value of rollup_rate return seperately in Grafana.

I have read this article about rollup_rate function of VictoriaMetrics.
[](https://valyala.medium.com/why-irate-from-prometheus-doesnt-capture-spikes-45f9896d7832)

rate function is ok:
`rate(ifmib_ifOutOctets{ip="$ip",ifName=~"$ifName"}[$__rate_interval])*8`

rollup_rate funciton is ok, but min max avg value has same legend.
`rate(ifmib_ifOutOctets{ip="$ip",ifName=~"$ifName"}[$__rate_interval])*8`

rollup_rate with/without/by cannot work. Maybe I misunderstanding something.
`rollup_rate with (rollup="max") (ifmib_ifOutOctets{ip="$ip",ifName=~"$ifName"}[$__rate_interval])*8`
`rollup_rate without (rollup="max") (ifmib_ifOutOctets{ip="$ip",ifName=~"$ifName"}[$__rate_interval])*8`
`rollup_rate by (rollup="max") (ifmib_ifOutOctets{ip="$ip",ifName=~"$ifName"}[$__rate_interval])*8`

**Comment by valyala** [comment]
All the `rollup_*` functions including `rollup_rate` return three time series per each input series. Each such time series has an additional `rollup` label with `min`, `max` and `avg` labels. If you need selecting only a single series (for example, `max`) per each input series, then this can be done with `label_match` function available in [MetricsQL](https://victoriametrics.github.io/MetricsQL.html): `label_match(rollup_rate(...), "rollup", "max")`

If you need selecting the maximum rate value among all the input series, then use `max without (rollup) (label_match(rollup_rate(...), "rollup", "max"))`

**Comment by valyala** [comment]
Update: all the `rollup_*` functions now support optional second argument, which can be used for returning only the specified `min`, `max` or `avg` value. For example, `rollup_rate(process_cpu_seconds_total[5m], "max")` returns only `max` value. See [rollup_rate](https://docs.victoriametrics.com/metricsql/#rollup_rate) docs for more details.

This feature has been appeared in VictoriaMetrics starting from [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). See the commit dac21d874b555a80166561376059961d861cbc76 for details.

Closing the question as answered.
