### ISSUE TITLE
Failed to send metrics from vmagent to vmsingle

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1256]
Hi there,
I'm using VM version 1.58.0 on both vmagent and vmsingle
My vmagent fire the error log as below:
```
{"ts":"2021-04-29T04:41:49.431Z","level":"error","caller":"VictoriaMetrics/app/vmagent/remotewrite/client.go:242","msg":"couldn't send a block with size 112965 bytes to \"1:secret-url\": Post \"http://<vmsingle-ip>:8428/api/v1/write\": EOF; re-sending the block in 2.000 seconds"}
```
and in that time, vmsingle was miss data
![Screenshot from 2021-04-29 11-48-18](https://user-images.githubusercontent.com/1458400/116503691-ebf86f80-a8e0-11eb-8e95-0e7cba694fdd.png)

The resource consumption:
![Screenshot from 2021-04-29 11-49-51](https://user-images.githubusercontent.com/1458400/116503815-2a8e2a00-a8e1-11eb-9cfa-25339091628c.png)

The total datapoint and active series:
![Screenshot from 2021-04-29 11-51-25](https://user-images.githubusercontent.com/1458400/116503857-44c80800-a8e1-11eb-9016-c5fd81939601.png)

Could you someone help me to clear why vmagent got error and vmagent consume high memory?
Thanks.

**Comment by f41gh7** [comment]
Hello, can you check metrics from official dashboard for
1) persistent queue size and persistent queue drop rate, any drops?
2) `panel` Remote Write - graph Request rate. Is there any 4XX responses?
 
 I can suggest you to add following setting for vmagent and check memory consumption:
1) increase queues count `vmagent.spec.remoteWriteSettings.queues: 20` 
2) enable streamParse mode, `vmagent.spec.extraArgs.promscrape.streamParse: "true"`

**Comment by vuxuanlai** [comment]
Hi,
1. Persistent queue size and drops
![Screenshot from 2021-04-29 13-24-29](https://user-images.githubusercontent.com/1458400/116509942-56fc7300-a8ee-11eb-9d14-06811539051a.png)
![Screenshot from 2021-04-29 13-24-43](https://user-images.githubusercontent.com/1458400/116509939-55cb4600-a8ee-11eb-8fb2-7aa046eabcd0.png)
2. Request rate
![Screenshot from 2021-04-29 13-26-29](https://user-images.githubusercontent.com/1458400/116510080-89a66b80-a8ee-11eb-8620-4ee269ef307b.png)


I'm using extra flags as below:
![Screenshot from 2021-04-29 13-27-43](https://user-images.githubusercontent.com/1458400/116510188-b6f31980-a8ee-11eb-8439-14e879884f74.png)


So what the problem here?

**Comment by vuxuanlai** [comment]
I used the extra flags as you recommend and issue is resolved. 
Thank you.

**Comment by valyala** [comment]
The related issues - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1235
