### ISSUE TITLE
Add cumulative sum aggregation function

### ISSUE THREAD

**Issue by luhhujbb** [VictoriaMetrics/VictoriaMetrics#1264]
**Is your feature request related to a problem? Please describe.**
We are switching from influxdb to victoriaMetrics, and we need the cumulative sum function (https://docs.influxdata.com/influxdb/v1.8/query_language/functions/#cumulative_sum).

NB: Maybe it can already be done but I've not found something easy to do.

**Describe the solution you'd like**
Add an aggregation function like this:
```go
func aggrFuncCumSum(tss []*timeseries) []*timeseries {
	dst := tss[0]
	for i := range dst.Values {
		sum := float64(0)
		count := 0
		for _, ts := range tss {
			v := ts.Values[i]
			if math.IsNaN(v) {
				continue
			}
			sum += v
			count++
		}
		if count == 0 {
			sum = 0
		}
		if i != 0 {
			dst.Values[i] = dst.Values[i-1] + sum
		} else {
			dst.Values[i] = sum	
		}
	}
	return tss[:1]
}
```

**Describe alternatives you've considered**
For now we manage to do this kind of aggregation on client side

Many thanks !

**Comment by valyala** [comment]
It looks like you need `running_sum()` function from [MetricsQL](https://victoriametrics.github.io/MetricsQL.html).

**Comment by valyala** [comment]
Try combining `running_sum` with `sum` and `sum_over_time` functions:
* `running_sum(sum(q))` would return cumulative sum over all the series returned by `q` (`q` may contain arbitrary MetricsQL query). Not that `q` returns calculated series, which may contain different values compared to raw values for these series stored in the database. See https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness for details.
* `running_sum(sum(sum_over_time(metric{label_filters}))` would return cumulative sum for raw samples for all the time series with the given `metric` name and the given `label_filters` (see https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors for details on `metric{label_filters}` syntax).

**Comment by luhhujbb** [comment]
Ok many thanks ! Sorry for the duplicate !

**Comment by luhhujbb** [comment]
I personally think that cumulative_sum semantic is more easy to understand than running_sum and the possibility to directly aggregate with `cumulative_sum by (my_label) q` is nice.
However it is clear that `running_sum(sum by (my_label) q)` is the exact same function.
So I've close all the PR related to this issue/feature request  since it is already implemented. 
Many thanks !
