### ISSUE TITLE
High availability

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1268]
**Is your feature request related to a problem? Please describe.**
HTTP load balancer must stop routing requests to unavailable vminsert and vmselect nodes. 
When a vmselect fails，Do I need to manually modify the configuration of NGINX？
thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by denisgolius** [comment]
@WuJingLearn 
Opensource Nginx use https://www.nginx.com/resources/glossary/round-robin-load-balancing/ by default. To solve your issue you need to configure Nginx up to your needs and change its default configuration, see [this article](https://www.dnsstuff.com/what-is-server-load-balancing) it must help.
Note that Opensource Nginx do not contains health checks (see this https://docs.nginx.com/nginx/admin-guide/load-balancer/http-health-check) as it have HAProxy, Traefik, Envoy. etc.

**Comment by WuJingLearn** [comment]
resolve
