### ISSUE TITLE
allow suffixes on memory.allowedBytes

### ISSUE THREAD

**Issue by MorphBonehunter** [VictoriaMetrics/VictoriaMetrics#1269]
For better Ressource control i would like to see that the `memory.allowedBytes` could expressed with suffixes like K,M,G...

One use case for this is if vm or vmalert runs under an container orchestration tool like nomad.
Nomad exposes the memory limit per task as variable (`NOMAD_MEMORY_LIMIT`) which could be uses for example in arguments for the application.
Problem is in this case...the [value is in MB](https://www.nomadproject.io/docs/runtime/interpolation#interpreted_env_vars).
So the approach `-memory.allowedBytes=${NOMAD_MEMORY_LIMIT}` isn't suitable. (i can fill up zeros, but that's semi optimal).

I'm not familiar with kubernetes, but the memory limits could also be [expresses with suffixes](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory) and so i guess that would also be an enhancement for k8s.

As an side notice, my "problem" arises because of vm could not honor the memory constraints in my docker container because in my environment cgroup v2 is used (and this isn't supported atm [if i read the code right](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/cgroup/mem.go)) and i'm not sure if this is easily fixable so i thought this would be an more "generic" way to solve that :)

**Comment by valyala** [comment]
`-memory.allowedBytes` already supports suffixes. See `-help` output for this command-line flag:

```
  -memory.allowedBytes size
        Allowed size of system memory VictoriaMetrics caches may occupy. This option overrides -memory.allowedPercent if set to a non-zero value. Too low a value may increase the cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from OS page cache resulting in higher disk IO usage
        Supports the following optional suffixes for size values: KB, MB, GB, KiB, MiB, GiB (default 0)
```

As for the missing cgroup v2 support - we'll look into this and try to add the missing support.

**Comment by MorphBonehunter** [comment]
@valyala Sorry, my fault...for whatever reason i didn't catch that 🤷
Close...

**Comment by valyala** [comment]
There is no need in closing this issue - we need to investigate cgroup v2 support :)

**Comment by f41gh7** [comment]
Can you try to build victoria-metrics from branch https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cgroupv2-support
 and check, are allowed memory and cpu recognized correctly? 

 It can be done with 
` make package-victoria-metrics` 
https://github.com/VictoriaMetrics/VictoriaMetrics#production-build

**Comment by MorphBonehunter** [comment]
Hi @f41gh7,
i've testet this a few moments ago with version `victoria-metrics-20210512-145505-heads-cgroupv2-support-0-gbd83dac4`.
The cgroup is limited to 2GB and i got the following:
```
2021-05-12T14:59:37.559Z	info	VictoriaMetrics/lib/memory/memory.go:37	limiting caches to 1288490188 bytes, leaving 858993460 bytes to the OS according to -memory.allowedPercent=60
```
This works :)

I'm unsure how i can see the CPU stuff atm.

**Comment by MorphBonehunter** [comment]
Ahh...OK, i figured this out...(have to read the code to get this)
it's the `vm_available_cpu_cores` which changes 😃 

So yes, this also works...my cpu count drops from 4 to 1 after playing with the settings.
After this was merged i close the issue.

Thanks!

**Comment by valyala** [comment]
FYI, all the VictoriaMetrics components automatically detect cgroups v2 limits for memory and cpu starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
