### ISSUE TITLE
First write to InfluxDB endpoint results in error message

### ISSUE THREAD

**Issue by kmansoft** [VictoriaMetrics/VictoriaMetrics#127]
My computer boots up

Victoria starts from systemd unit

I start my software (manually)

The first Write via InfluxDB API results in this error:

Write error: error in "/write": cannot unmarshal influx line protocol data with size 3888: missing field value for "ERROR:"

After this everything is good.

Victoria version: git head as of right now.

**Comment by valyala** [comment]
The latest commit contains improved error logging. Could you build VictoriaMetrics from it and try catching this error again? It will contain the whole Influx line which couldn't be parsed.

**Comment by kmansoft** [comment]
Looks like it's a bug in my client??? Trying to send a NaN value?

> Write error: error in "/write": cannot unmarshal influx line protocol data with size 3861: cannot unmarshal Influx line "# ERROR: NaN is an unsupported value for field value process_list": missing field value for "ERROR:"

**Comment by kmansoft** [comment]
Yep found it. Thanks for the help and sorry for the distraction.

**Comment by valyala** [comment]
Thanks for the issue - it helped improving error messaging, which will save users' time in the future :)
