### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1272]
**Is your feature request related to a problem? Please describe.**

docker run --name vmstorage -d  -p 8400:8400 -p 8401:8401 -p 8482:8482 victoriametrics/vmstorage --storageDataPath=/storage

docker run --name vmselect -d -p 8481:8481 victoriametrics/vmselect --storageNode=localhost:8401

docker run --name vminsert -d -p 8480:8480 victoriametrics/vmselect --storageNode=localhost:8400

connection refused,can not connect to vmstorage
thanks
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by denisgolius** [comment]
@WuJingLearn  you need configure different directories path for `vmstorages` . Try to reconfigure it properly and give a feedback.

**Comment by valyala** [comment]
It is likely you need to pass `--network` arg to `docker run` and pass proper hostnames to `-storageNode`, which match the container image name defined in the `--name` query arg - see [these docs](https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks) for details.

Another solution is to pass `--net=host` command-line flag to `docker run` - see [these docs](https://docs.docker.com/network/host/) for details.

**Comment by WuJingLearn** [comment]
I didn't see the detailed introduction of cluster building on the official website. Is there any relevant document introduction? Thank you

**Comment by valyala** [comment]
The recommended ways to build the VictoriaMetrics cluster on top of Docker images are:
* via [helm chart](https://github.com/VictoriaMetrics/helm-charts)
* via [victoriametrics-operator](https://github.com/VictoriaMetrics/operator)

There is also a docker-compose example of VictoriaMetrics cluster - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/docker-compose.yml .

**Comment by WuJingLearn** [comment]
resolve
