### ISSUE TITLE
Warning from Grafana when query metrics

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1274]
Hi there,
I used VictoriaMetrics as datasource in Grafana, when I query metrics on grafana, I got the warning as below:

![image](https://user-images.githubusercontent.com/1458400/117410792-14194b80-af3d-11eb-8af6-7b7f1edabd26.png)

This is issue? and this warning is how affect to performance in query?

Thanks.

**Comment by valyala** [comment]
This warning says that VictoriaMetrics contains time series with more than 10K of unique names. You can verify this by querying `/api/v1/label/__name__/values` endpoint - see https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values for more details. Grafana disables auto-suggestions in this case.
