### ISSUE TITLE
time range modifier

### ISSUE THREAD

**Issue by gmwiku** [VictoriaMetrics/VictoriaMetrics#1276]
**Is your feature request related to a problem? Please describe.**
I use TSDBs (mostly InfluxDB) for storing network devices metrics gathered by SNMP, eg. InOctets and OutOctets labeled by deviceName, ifName, ifAlias, ifOperStatus, ifAdminStatus etc. The usage of the interfaces sometimes can be changed and ifAlias not always reflect the change (or even is not supported by device). So lets assume the client X was connected to device xxx interface 0/0/1 and then (01.04.2021) reconnected to device yyy interface 1-0. I would like to offer to the client grafana dashboard presenting  client's traffic.
InOctets{device="xxx",ifName="0/0/1"} before 01.04.2021
InOctets{device="yyy",ifName="1-0"} after 01.04.2021
after 01.04.2021 to device xxx interface 0/0/1 is connected client Y and I have to limit access to client Y traffic stats.

**Describe the solution you'd like**
I'd be happy with 2 different solutions:

1. Some kind of perspective in victoriametrics database, so I can query
InOctets{client="X"}
and this query returns union of InOctets{device="xxx",ifName="0/0/1"} before 01.04.2021 and InOctets{device="yyy",ifName="1-0"} after 01.04.2021

2. Grafana independent time range modifier, eg
InOctets{device="xxx",ifName="0/0/1", time < 1617235200}
InOctets{device="yyy",ifName="1-0", time >= 1617235200}

Is there now available any solution by which I can achieve described above functionality?

and sorry for my poor English :(

**Comment by valyala** [comment]
If `InOctets` metric has `client` label, then `sum(InOctets{client="X"})` would return a single time series for that client.

[MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) also supports datetime-related functions such as [time()](https://prometheus.io/docs/prometheus/latest/querying/functions/#time), which can be used for filtering series samples based on time. Something like the following should work: `InOctets{device="xxx",ifName="0/0/1"} if time() < 1617235200`

**Comment by valyala** [comment]
If `InOctets` is a [counter](https://prometheus.io/docs/concepts/metric_types/#counter), then the query must look like `sum(rate(InOctets{client="X"}))`. See [this article](https://www.robustperception.io/rate-then-sum-never-sum-then-rate) for details.

**Comment by gmwiku** [comment]
> If `InOctets` metric has `client` label, then `sum(InOctets{client="X"})` would return a single time series for that client.

It has not. Is it possible to add/modify labels to past data?

> (...) Something like the following should work: `InOctets{device="xxx",ifName="0/0/1"} if time() < 1617235200`

It works like a charm, that's what I was looking for!! Thank you very much!!!

**Comment by valyala** [comment]
>  Is it possible to add/modify labels to past data?

It is possible to add/modify/delete labels during data ingestion with relabeling - see [these docs](https://docs.victoriametrics.com/#relabeling). It is possible to change labels during querying - see `label_*` functions at [MetricsQL page](https://docs.victoriametrics.com/MetricsQL.html).

**Comment by gmwiku** [comment]
> If `InOctets` is a [counter](https://prometheus.io/docs/concepts/metric_types/#counter), then the query must look like `sum(rate(InOctets{client="X"}))`. See [this article](https://www.robustperception.io/rate-then-sum-never-sum-then-rate) for details.

In fact it is, but for SNMP polling I use Toni Moreno's SNMPcollector (https://github.com/toni-moreno/snmpcollector - BTW great tool I can recommend) and this tool does the job and converts counter to rate.

**Comment by gmwiku** [comment]
> > Is it possible to add/modify labels to past data?
> 
> It is possible to add/modify/delete labels during data ingestion with relabeling - see [these docs](https://docs.victoriametrics.com/#relabeling). It is possible to change labels during querying - see `label_*` functions at [MetricsQL page](https://docs.victoriametrics.com/MetricsQL.html).

relabeling at ingestion stage can be solution of my second problem ( #1277) by creating additional label which is concatenation of device and ifName :) Nevetheless string manipulation functions would be also very welcome :)

**Comment by tredondo** [comment]
> > (...) Something like the following should work: `InOctets{device="xxx",ifName="0/0/1"} if time() < 1617235200`
> 
> It works like a charm, that's what I was looking for!! Thank you very much!!!

Filtering for `time()` to be less than a timestamp, returns an empty vector for me, while plenty of data does exist around that timestamp.

Screenshot below, based on the same data as from bug #2414:

![image](https://user-images.githubusercontent.com/10043369/162141338-a1a92a90-a460-43e2-8f8a-3f616cf5eb7c.png)

1649268000 is 2022-04-06T18:00:00Z, and the time at the execution of the query was about 2022-04-07T07:10:00Z.
