### ISSUE TITLE
Metrics is lacked when query in grafana

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#1281]
Hi there,
When I query metrics which relating to CPU, RAM, I saw that metrics being lacked in some time. 
![Screenshot from 2021-05-10 10-39-01](https://user-images.githubusercontent.com/1458400/117603041-4e246080-b17c-11eb-9a5a-27a951ec2d35.png)

And some metrics is also get same status.
![Screenshot from 2021-05-11 10-06-32](https://user-images.githubusercontent.com/1458400/117752274-ae7cd600-b240-11eb-9347-55749301d5d6.png)

I confirm that, metrics which fired from k8s pod is continous.

VictoriaMetrics version:
- vmsingle: v1.58.0
- vmagent: v1.58.0
 @valyala plz help me to trace this issue.
Thanks.

**Comment by valyala** [comment]
Related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1250

**Comment by vuxuanlai** [comment]
@valyala 
I dont think so. I have checked targets of vmagent and got some info as below
![Screenshot from 2021-05-11 15-39-02](https://user-images.githubusercontent.com/1458400/117785856-28c44f00-b26f-11eb-9412-691e9e07b82a.png)

I also workaround and find the issue on [this](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1017)
I'll try upgrade VM to version 1.59.0

**Comment by vuxuanlai** [comment]
@valyala , I have some updates:
- Upgrade vmagent to v1.59.0
- Set scrape_timeout to 40s
As result there are no positive changes. Some data was still lost.
and on vmagent targets portal, I still got the error:
![Screenshot from 2021-05-12 09-24-25](https://user-images.githubusercontent.com/1458400/117909118-dc771e80-b303-11eb-98bd-af4a5e88a650.png)

Notice that, I just use one vmagent and one vmsingle.

**Comment by valyala** [comment]
Try querying the given target manually and measure the response time. The `/targets` page should contain full url it uses for the querying (it is named `endpoint`). Probably the target responds too slow. In this case just increase `scrape_timeout` for this target.

**Comment by valyala** [comment]
Note that single-node VictoriaMetrics supports service discovery and metrics scraping on its own - see [these docs](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) for details.

**Comment by vuxuanlai** [comment]
It takes about 3s for get response from targets

**Comment by valyala** [comment]
As I know, Prometheus automatically adjusts `scrape_timeout` to `scrape_interval` if the given `scrape_timeout` exceeds `scrape_interval`. Probably the target usually responds within 3 seconds most of the time, but sometimes it responds much slowly. Prometheus re-scrapes the target after `scrape_interval` in this case. So it may miss only a single sample, while VictoriaMetrics may wait for much longer periods of time compared to the configured `scrape_interval` if `scrape_timeout` isn't configured or configured to value exceeding `scrape_interval`. Try setting `scrape_timeout` to the same value as `scrape_interval` (or to slightly smaller value) and see whether this removes gaps on the graph?

**Comment by valyala** [comment]
Both `vmagent` and single-node VictoriaMetrics should limit `scrape_timeout` by `scrape_interval` like Prometheus does starting from the commit fc3519fa26487a9b9fb49e388beacb25833cf61a . This can be verified by building `vmagent` from this commit according to [these docs](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources) and checking whether this removes gaps on graphs for time series collected from scrape targets, which may respond slowly sometimes.

**Comment by vuxuanlai** [comment]
@valyala you're right. The issue is resolved when I inscrease `scrape_timeout` to 1m (same to `scrape_interval`)
Thanks so much.

**Comment by valyala** [comment]
FYI, `vmagent` limits `scrape_timeout` by `scrape_interval` in the same way as Prometheus does starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by raags** [comment]
This is breaking an exporter I have that needs to take `scrape_interval` time to calculate the metric. I'm fixing that now to reduce the interval. I think there should be a check in vmagent to fail / warn if the scrape_timeout > scrape_interval. It's implicit right now, and it'll be hard to debug.
