### ISSUE TITLE
vmalert errors

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#1285]
**Describe the bug**
We start seeing the following set of vmalert errors:
```
2021-05-11T14:48:11.293Z        error   VictoriaMetrics/app/vmalert/remotewrite/remotewrite.go:213      attempt 1 to send request failed: error while sending request to http://cms-host:30428/api/v1/write: Post "http://cms-host:30428/api/v1/write": read tcp 10.100.2.51:50868->188.185.126.220:30428: read: connection reset by peer; Data len 21790(21790)
...
2021-05-11T17:29:11.298Z        error   VictoriaMetrics/app/vmalert/remotewrite/remotewrite.go:213      attempt 1 to send request failed: error while sending request to http://cms-host:30428/api/v1/write: Post "http://cms-host:30428/api/v1/write": EOF; Data len 21663(21663)

```
It is unclear from these errors if they are transient or should we pay attention to them. The communication between vmalert and VM is done on k8s infrastructure (each deployed on different clusters). On the VM sides we do not see any log entries corresponding to the above timestamps. The question is critical for us as we do not want to loose any data.

**To Reproduce**
We run vmalert on one k8s cluster and it writes aggregated to VM which is deployed on another k8s clsuter.

**Expected behavior**
If error occur we need more description about its cause. If the error is transient, we should get confirmation that it is resolved under further attempts.

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./vmalert-prod -version
vmalert-20210501-071339-tags-v1.59.0-0-gfb097ff77

$ ./victoria-metrics-prod -version
victoria-metrics-20210315-171150-heads-perf-tune-0-geaf7965ee
```

The vmalert is deployed with the following set of options:
```
          -datasource.url=http://cms-host:30082
          -remoteWrite.url=http://cms-host:30428
          -rule=/etc/vmalert/rucio-agg-1h.rules
          -notifier.url=http://cms-host:9093
```
while VM is deployed as following:
```
          -opentsdbHTTPListenAddr=:4242
          -retentionPeriod=12
          -storageDataPath=/tsdb
          -search.maxConcurrentRequests=32
```

**Comment by f41gh7** [comment]
Hello,
  `vmalert` performs 5 attempts to write data to the remote storage. Log message : `all 5 attempts to send request failed - dropping 1 timeseries` indicates, that data was lost.
 
 For now it seems like, there are some errors at proxy host, that forwards requests to the victoria metrics.

**Comment by vkuznet** [comment]
ok, now we know the pattern and can watch it in our logs. From the technical point of view there is no proxy involved in communication between two services. As I wrote they reside within two different k8s clusters and routing is done within k8s. We use NodePorts on internal network and there is no ingress controller involved. Therefore, I would assume that packet drops is caused by VM for whatever reason.

**Comment by hagen1778** [comment]
> ok, now we know the pattern and can watch it in our logs.

you also can track it via `vmalert` metrics:
```
	droppedRows  = metrics.NewCounter(`vmalert_remotewrite_dropped_rows_total`)
	droppedBytes = metrics.NewCounter(`vmalert_remotewrite_dropped_bytes_total`)
```

**Comment by vkuznet** [comment]
ok, thank you for the information. Closing the ticket.
