### ISSUE TITLE
vmbackupmanager support backup creation before version update

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1288]
**Is your feature request related to a problem? Please describe.**

 As kubernetes victoria-metrics user, i want to perform cluster backup before version upgrade.  For now, it requires to run additional scripts and connect to each node with mounted volume.

**Describe the solution you'd like**
 Add API to [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html), which accepts: backup name (folder name to store backup), dst storage. It should perform backup to given folder with actual state. Return error, if backup in progress. 

**Describe alternatives you've considered**
 Run  bash scripts with fragile custom logic.

**Comment by valyala** [comment]
@f41gh7 , is this feature request still relevant? If yes, then could you discuss how to implement it with @zekker6 ?

**Comment by f41gh7** [comment]
closing as irrelevant
