### ISSUE TITLE
Unexpected RAM usage increase until VM runs out of memory during historical ingestion

### ISSUE THREAD

**Issue by jorge-pessoa-j** [VictoriaMetrics/VictoriaMetrics#1295]
When running the Billy benchmark on VictoriaMetrics everything works as intended and performance matches our current setup. However, we've adapted the billy benchmark to load data from historical files and suddenly our vmstorage deployment constantly increases RAM usage to unexpected levels. As an example we've experienced billy with 500k time series consuming around 700mb to 1Gb of RAM used. In contrast, our benchmark with 2000 timeseries quickly rises to 32Gb of RAM and kills the DB before we can ingest the full data of the benchmark. 

The only relevant change in our billy benchmark compared to https://github.com/VictoriaMetrics/billy is that a single request will contain a whole day for one specific metric. Some metrics contain a few datapoints per day, and some up to around 200 000 points per day at maximum. Most of the changes made apart from reading data are in the method writeSeriesVMImport:

```
func writeSeriesVMImport(bw *bufio.Writer, sd *seriesData) {
	fmt.Fprintf(bw, `{"metric":{"__name__": "%s"},"values":[`, sd.metric)

	if len(sd.datapoints) == 0 {
		return
	}

	rowsCount := sd.length
	var buf []byte

	t := sd.datapoints[0]
	for i := 0; i < rowsCount-1; i++ {
		buf = strconv.AppendFloat(buf[:0], t, 'f', *digits, 64)
		buf = append(buf, ',')
		bw.Write(buf)
		t = sd.datapoints[i+1]
	}
	fmt.Fprintf(bw, `%.*f],"timestamps":[`, *digits, t)

	timestamp := sd.timestamps[0]
	for i := 0; i < rowsCount-1; i++ {
		buf = strconv.AppendInt(buf[:0], timestamp, 10)
		buf = append(buf, ',')
		bw.Write(buf)
		timestamp = sd.timestamps[i+1]
	}
	fmt.Fprintf(bw, "%d]}\n", timestamp)
}
```

**To Reproduce**
Unfortunately the full dataset used cannot be shared since it contains proprietary data. However I can provide some samples:

Metric 1

| value  | timestamp |
| ------------- | ------------- |
| -606.192261  |  2021-04-13 00:00:00.385   |
| -548.321777   | 2021-04-13 00:00:00.869   |
| -493.344849  | 2021-04-13 00:00:01.359   |
| -458.622803   | 2021-04-13 00:00:01.841   |
| -399.305420  | 2021-04-13 00:00:02.330   |

Metric 2

| value  | timestamp |
| ------------- | ------------- |
| 42.678810  |  2021-04-12 00:00:00.401   |
| 42.377483   | 2021-04-12 00:00:00.893   |
| 42.165565   | 2021-04-12 00:00:01.375   |
| 42.039738   | 2021-04-12 00:00:01.878   |
| 42.307949  | 2021-04-12 00:00:02.359   |

The dataset is highly irregular in periodicity. We have verified the constructed requests and they are identical to the ones generated by Billy except the number of points per request.
To reproduce the issue we simply run VictoriaMetrics with the arguments provided below on this dataset and behaviour is consistently the same. 

**Expected behavior**
We would expect the RAM used by VictoriaMetrics to be proportional to the active time series, or at least be relatively low and remain stable during the benchmark.

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20210501-071031-tags-v1.59.0-0-gfb097ff77
```

**Used command-line flags**

```
retentionPeriod=128
storageDataPath=/var/lib/victoria/data
memory_allowedPercent=60
selfScrapeInterval=5s
```

**Additional context**

The memory profile when the system was showing around 30Gb reserved for VictoriaMetrics, a few seconds before crashing:
[mem.pprof.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6474121/mem.pprof.gz)

Screenshots of the VictoriaMetrics dashboard for the Billy benchmark:
![image](https://user-images.githubusercontent.com/84147163/118164442-0b33e880-b41b-11eb-9895-27abfd6a8efb.png)
![image](https://user-images.githubusercontent.com/84147163/118164465-0ec76f80-b41b-11eb-9502-ad90fe0b9c46.png)
![image](https://user-images.githubusercontent.com/84147163/118164472-1129c980-b41b-11eb-8007-300f78d40565.png)
![image](https://user-images.githubusercontent.com/84147163/118164479-12f38d00-b41b-11eb-9df9-3edb61f656f5.png)
![image](https://user-images.githubusercontent.com/84147163/118164496-15ee7d80-b41b-11eb-8362-a4c4e156e42b.png)
![image](https://user-images.githubusercontent.com/84147163/118164508-18e96e00-b41b-11eb-8350-7a523c5a7865.png)
![image](https://user-images.githubusercontent.com/84147163/118164518-1ab33180-b41b-11eb-8a12-d864c0464811.png)
![image](https://user-images.githubusercontent.com/84147163/118164531-1d158b80-b41b-11eb-890e-1c070765adc3.png)

And screenshots of the dashboard for our custom benchmark:
![image](https://user-images.githubusercontent.com/84147163/118164563-256dc680-b41b-11eb-8ae8-af3d3353b72a.png)
![image](https://user-images.githubusercontent.com/84147163/118164570-2868b700-b41b-11eb-88cb-67e5d071d473.png)
![image](https://user-images.githubusercontent.com/84147163/118164579-2acb1100-b41b-11eb-8dfe-38d9b3ffc4c0.png)
![image](https://user-images.githubusercontent.com/84147163/118164584-2c94d480-b41b-11eb-8f54-95087f4d4232.png)
![image](https://user-images.githubusercontent.com/84147163/118164592-2e5e9800-b41b-11eb-9636-da9c3c851160.png)
![image](https://user-images.githubusercontent.com/84147163/118164600-30285b80-b41b-11eb-9720-d1f34a3df281.png)
![image](https://user-images.githubusercontent.com/84147163/118164605-328ab580-b41b-11eb-8e2f-0aaf56bd0d59.png)
![image](https://user-images.githubusercontent.com/84147163/118164612-33bbe280-b41b-11eb-8307-0a94aee87003.png)
![image](https://user-images.githubusercontent.com/84147163/118164620-3585a600-b41b-11eb-8628-09eb78e72464.png)

**Comment by valyala** [comment]
The provided memory profile shows that the majority of memory (more than 76%) is occupied by json parser. VictoriaMetrics parses the input JSON lines one-by-one. It reads each line into memory, then parses it into a datastructure located in memory, then ingests the parsed samples into storage. If JSON lines are too long (e.g. if they contain millions of samples per line), then VictoriaMetrics could need big amounts of memory. The solution is to split too long JSON lines into smaller chunks before passing them to [/api/v1/import](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format). It is OK if samples for a single time series are spread among multiple JSON lines.

So the solution for the issue is to limit the number of samples per each `writeSeriesVMImport` call by 10K. This should significantly reduce memory usage when importing data to VictoriaMetrics via `/api/v1/import`.

**Comment by jorge-pessoa-j** [comment]
We have divided the import of longer files in different chunks and it has indeed solved the problem. The mention in documentation should be useful in case anyone faces the same problem. Thank you

**Comment by valyala** [comment]
Mentioned this issue in the docs - see [the corresponding commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/e6ec442e9671f7fb13aba1020d6f187074589931) and [the updated docs](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format).
