### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1296]
There are too many boot parameters. Can I put the boot parameters into the configuration file? How?

thank you

**Comment by denisgolius** [comment]
@WuJingLearn 
You can create .env file with parameters and run `source .env && ./victoria-metrics`

**Comment by WuJingLearn** [comment]
Got it

**Comment by valyala** [comment]
See more details on how to pass configs via environment variables at https://docs.victoriametrics.com/#environment-variables .
