### ISSUE TITLE
Re-read bearer_token_file

### ISSUE THREAD

**Issue by deemon87** [VictoriaMetrics/VictoriaMetrics#1297]
**Is your feature request related to a problem? Please describe.**
When bearer_token_file is changed vmagent don't know anything about it. It can happend when vault-agent is managing this file for example. Only restart is solved this problem

**Describe the solution you'd like**
Sometimes re-read this files or subscribe on changing this files

**Comment by valyala** [comment]
@deemon87 , could you try `vmagent` built from the commit 733706e6c62a2024759c548d5beffe904886150b ? It should automatically refresh auth tokens loaded from files.

**Comment by deemon87** [comment]
@valyala I just have checked this commit. My problem was resolved. Everything is very well. Thank you i will wait for release

**Comment by valyala** [comment]
FYI, `vmagent` automatically re-reads `bearer_token_file`, `credentials_file`, `password_file` and `client_secret_file` files starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
