### ISSUE TITLE
vmstorage  Data De duplication

### ISSUE THREAD

**Issue by zhangy-in** [VictoriaMetrics/VictoriaMetrics#1298]
hi , When Victoria metrics is used with Prometheus (two Prometheus nodes), the data volume of Victoria metrics dashboard is doubled (vmselect and vmstorage are configured with -dedup.Minscrapeinterval = 40s)
At present, it is observed that two Prometheus nodes write two copies of data at the same time, which leads to the duplication of data in grafana view. Is there any solution?

exporter*N -> prometheus*2 -> vminsert*2 -> vmstorage*2 -> vmselect*2 -> grafana

Victoria metrics dashboard:
![vm](https://user-images.githubusercontent.com/74394796/118258003-e9516900-b4e1-11eb-9b40-ca7e30bc1477.png)

Prometheus dashboard:
![prom](https://user-images.githubusercontent.com/74394796/118258007-ea829600-b4e1-11eb-92f9-35ca79d5acdc.png)

**Comment by valyala** [comment]
Make sure that Prometheus instances have identical configs, so they scrape the same set of targets and write the data to the same set of time series.

The most likely cause for the issue shown on the graphs above is that Prometheus instances have a distinct set of `external_labels` in `global` section - see https://prometheus.io/docs/prometheus/latest/configuration/configuration/ . If this is the case, then each Prometheus will write metrics to VictoriaMetrics with a distinct set of labels, so these metrics are written to a distinct time series (a time series is uniquely identified by its name plus all its labels - for example, `foo{datacenter="A"}` and `foo{datacenter="B"}` are two different time series). VictoriaMetrics can de-duplicate samples only if they are located in a single time series - see https://docs.victoriametrics.com/#deduplication .

There is yet another common reason for the issue shown above - if `-dedup.minScrapeInterval` is set to a value smaller than the real scrape interval configured at Prometheus instance, which write data to VictoriaMetrics. The `-dedup.minScrapeInterval` should be equal or bigger than the maximum `scrape_interval` configured at Prometheus or [vmagent](https://docs.victoriametrics.com/vmagent.html).

If these suggestions don't help, then it would be grate if you could share a query used for building the graph above.

**Comment by zhangy-in** [comment]
OK, I will check whether the configuration is the same again. If there is any problem, I hope to communicate again. Thank you very much!
