### ISSUE TITLE
vmauth not reusing existing outgoing connections

### ISSUE THREAD

**Issue by aval13** [VictoriaMetrics/VictoriaMetrics#1300]
**Describe the bug**
When vmauth receives upto 2 parallel connections, it will keep open 1 or 2 established connections to the targets specified in the configuration files.
When there are at least 3 incoming connections, vmauth behaves erratically by closing the existing established connections and opening and closing alot of connections to the targets based on the number of new connections it receives.
We traced this issue to the Go http.Transport object, namely the MaxIdleConnsPerHost which is not explicitly defined so it takes the value of DefaultMaxIdleConnsPerHost which has the value 2.

**To Reproduce**
Connect 2 clients each with 1 connection to vmauth, you will see 2 stable established connections to the targets.
Add one more client, you will see the 2 existing connections closed and alot of new short-lived connections to the target (a lot of SYNs on the wire)

**Expected behavior**
vmauth should just scale and increase the number of stable established connections when more clients connect to it.

**Version**
vmauth-20210303-095340-tags-v1.55.1-0-g3a68b9448
(we checked the sources of the last vmauth, same issue)

**Used command-line flags**
/usr/sbin/vmauth-prod -auth.config=/etc/vmauth/vmauth.yml

**Additional context**
In https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmauth/main.go
reverseProxy object does not set the MaxIdleConnsPerHost in the http.Transport component.
Setting it with a higher value and recompiling vmauth resolved the issue for us.
Something similar is already implemented in vmagent.

**Comment by valyala** [comment]
Thanks for spotting this issue! It must be resolved in the commit 10a47af631bcdb77f78e3d65dc8e3330b700d4c9 .

**Comment by aval13** [comment]
Hello,

We tested and confirm everything works as expected with vmauth on the new code, no more tsunami of new ephemereal outgoing connections.

Thank you for the fast fix.

**Comment by valyala** [comment]
FYI, the bugfix is available starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
It has been appeared that the `-maxIdleConnsPerBackend` command-line flag was hardcoded to 100 and couldn't be changed. This should be fixed in the commit e5d4c7f4a7fd9bb9957dddd58a5776bc525e15b2 .

**Comment by valyala** [comment]
FYI, `vmauth` should properly take into account `-maxIdleConnsPerBackend` command-line option starting from [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
