### ISSUE TITLE
vm-insert http api error

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#1304]
**Describe the bug**
We used the cluster version of the VM to transfer data through the http api provided by vm-insert, and found some errors in the log, resulting in occasional data loss, However, no error logs were found on the VM-insert machine.

What's the probable cause?

thx

**Screenshots**
![image](https://user-images.githubusercontent.com/2275120/118622353-ced90180-b7f9-11eb-852c-821fee296505.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
/usr/local/bin/vminsert-prod --version
vminsert-20201228-002924-tags-v1.51.0-cluster-0-g66a19e007

/usr/local/bin/vmstorage-prod --version
vmstorage-20201228-002929-tags-v1.51.0-cluster-0-g66a19e007
```

**Comment by valyala** [comment]
It looks like there are exceeded timeouts on connections between the data source and `vminsert`.  These timeouts may be specified either in the proxy sitting between the data source and `vminsert` or in the `vminsert` itself. The `vminsert` provides the following timeouts:

* The timeout for idle connection. It can be configured with `-http.idleConnTimeout` command-line flag. The default value for it is one minute (`1m`).
* The timeout for non-idle connection. It can be configured with `-http.connTimeout` command-line flag. By default it is set to two minutes (`2m`).

Try also reducing the packet sizes sent to `vminsert` by the data source (e.g. the maximum number of samples per `remote_write` block). This usually helps avoiding timeouts shown in the provided error log.

**Comment by mindw** [comment]
@valyala although this is an old issue - I'm seeing a similar problem with VM running behind kubernetes ingress-nginx.
The setup is Telegraf workloads sending data to VM via remote write protocol (`/api/v1/write`) exposed via ingress-nginx.
Nginx by default open long lived connection to the configured backend (EA VM). 
By default, telegraf report a write failure (despite retires) every ~2min or so. The stored metrics show corresponding gaps.
Question/request  - can the `--http.connTimeout`  be disabled? the code doesn't seem to support this - only setting it to a very high number.
IMHO this mechanism should be disabled by default - it is very surprising behaviour when VM is deployed behind any LB or reverse proxy I know of.

**Comment by valyala** [comment]
@mindw , thanks for highlighting the issue with `-http.connTimeout` - it should be resolved in the commit d8c1db7953d2265c9cd3a2913f12aac07a99a45c . Now VictoriaMetrics servers won't close client connections every 2 minutes. This commit will be included in the next release.

As for the issue with Telegraf. It is known issue that Telegraf can close connections to the output server in the middle of data transfer, and re-send the same data to the output server. This may lead to duplicate data in VictoriaMetrics. [This comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1190#issuecomment-1934576746) describes a workaround for this issue. Basically increase timeout and decrease batch size at Telegraf side.

**Comment by valyala** [comment]
FYI, `-http.connTimeout` is disabled by default in all the VictoriaMetrics components starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing this issue as addressed.

**Comment by valyala** [comment]
It has been appeared that some VictoriaMetrics users rely on TCP-level proxies such as [haproxy](https://www.haproxy.org/) for spreading client connections among a cluster of VictoriaMetrics components. In this case disabling periodic closing of incoming connections may result in uneven distribution of connections among a cluster of VictoriaMetrics components if the following conditions are met simultaneously:
  - a small number of clients establish a small number of long-living [HTTP keep-alive connections](https://en.wikipedia.org/wiki/HTTP_persistent_connection) to a cluster of VictoriaMetrics components via TCP-level proxy;
  - a big number of requests are sent over the established connections;
  - some of VictoriaMetrics components in the cluster are restarted.
  The TCP-level proxy re-establishes connections to the remaining available VictoriaMetrics components during the restart of some components, so they receive more connections comparing to the restarted components. The solution is to forcibly close periodically the persistent HTTP keep-alive connections at the VictoriaMetrics component side, so TCP-level proxy could re-establish them evenly among all the VictoriaMetrics backends.

So it has been decided returning back the periodic closing of incoming connections to `-httpListenAddr` every 2 minutes by default. The periodic closing of incoming connections can be disabled by passing `-http.connTimeout=0s` to VictoriaMetrics components.

**Comment by valyala** [comment]
FYI, the default value for `-http.connTimeout` command-line flag is returned back to `2m` in [v1.97.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.3).

**Comment by valyala** [comment]
FYI, the default value for `-http.connTimeout` command-line flag is returned back to `2m` in [v1.99.0 release](https://docs.victoriametrics.com/changelog/).
