### ISSUE TITLE
Support for Timezones when doing queries

### ISSUE THREAD

**Issue by AlexGrs** [VictoriaMetrics/VictoriaMetrics#1306]
**Describe the solution you'd like**
Using both InfluxDB and Postgresql we have a lot of use cases where we are doing analytics based on the timezone of our users. For instance we want to generate for each days in GMT+4 the average value of temperature sensors across a city. At the moment in PromQL or MetricsQL this is not supported. It means that when doing a group by day it will always take the days in UTC. 

**Describe alternatives you've considered**
A frontend making the query could be created and then do a query per day but we would loose the simplicity of MetricsQL and would end up doing a lot of queries.

**Additional context**
There is a related question here for PromQL https://github.com/prometheus/prometheus/issues/4160 but it seems Prometheus developper will not work on it as it is out of scope of the prometheus solution.

**Comment by valyala** [comment]
The next release of VictoriaMetrics will support `timezone_offset()` function, which returns the offset in seconds for the given timezone. For example `timezone_offset("Europe/Lisbon")` usually returns 3600. See the full list of supported timezones at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones .

The `timezone_offset()` function can be combined with `time()` and date-related functions such as [day_of_week](https://prometheus.io/docs/prometheus/latest/querying/functions/#day_of_week). For example, `day_of_week(time() + timezone_offset("Europe/Kiev"))` would align the weekdays to `Europe/Kiev` timezone.

**Comment by valyala** [comment]
The `timezone_offset()` function is available starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html) for details.

**Comment by AlexGrs** [comment]
Amazing news. I will try this asap. Any ideas how to make a group by day / weeks or month with this function ?

**Comment by gmwiku** [comment]
`timezone_offset` function works properly only for zones, where [daylight saving time](https://en.wikipedia.org/wiki/Daylight_saving_time) is **NOT** observed; is it possible to fix it? I suppose it would require adding time as extra argument.

**Comment by gmwiku** [comment]
> Amazing news. I will try this asap. Any ideas how to make a group by day / weeks or month with this function ?

I am struggling with the same problem and no idea how to solve it. It would be great to use something like:
`label_set(foo,"month",month(time()+timezone_offset("Europe/Warsaw")))`
but

1. `timezone_offset` function needs some improvements for DST
2. `month(...)` returns number and label value needs to be string

Please write a comment if you find solution.

**Comment by isodude** [comment]
```
q='WITH (
 query = metric{},
 tz = "Europe/Stockholm",
 off = timezone_offset(tz),
 month(q) = month(timestamp(q)),
 with_month(q) = q * ignoring(month) group_left(month) count_values without() ("month", months(q) ) )
) with_month(query)'
```
Here off will be 7200 for me. I want to add the value of timestamp(q) with 7200, and then everything will work flawless.
The trick here anyhow is to use count_values such that values is converted to label.

**Comment by isodude** [comment]
@valyala could we have support for numeric sort? like `sort -g`. Maybe add the above as a function? Then it could be generic for all time modifiers.

**Comment by valyala** [comment]
> timezone_offset function works properly only for zones, where [daylight saving time](https://en.wikipedia.org/wiki/Daylight_saving_time) is NOT observed; is it possible to fix it? I suppose it would require adding time as extra argument.

The [timezone_offset](https://docs.victoriametrics.com/metricsql/#timezone_offset) function works properly with DST in [the latest release](https://docs.victoriametrics.com/CHANGELOG.html) - see, for example, [this graph](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?#/?g0.expr=timezone_offset%28%22Europe%2FKiev%22%29&g0.range_input=1y&g0.end_input=2024-02-08T19%3A39%3A01&g0.tab=0&g0.relative_time=last_1_year).

Make sure you set up proper timezone at your web browser, so it matches the time zone passed to `timezone_offset()` function.

> Any ideas how to make a group by day / weeks or month with this function ?

You can use `q if (day_of_month(timezone_offset("TZ")+time()) == N)` idiom for obtaining `q` results only for the day `N` under the given timezone `TZ`. See [day_of_month](https://docs.victoriametrics.com/metricsql/#day_of_month) docs.

This can be combined into something like the following for obtaining `q` results for multiple days:

```metricsql
with (
  tz = "Europe/Kiev",
  series_for_day(q, day, dayName) = label_set(
    q if (day_of_month(timezone_offset(tz)+time()) == day),
    "day", dayName,
  ),
)
(
  series_for_day(up, 1, "1"),
  series_for_day(up, 2, "2"),
  ...
  series_for_day(up, 31, "31"),
)
```

**Comment by isodude** [comment]
> MetricsQL already supports numeric sort - see sort_by_label_numeric. This function has been added in v1.82.0 release. See this feature request.

Nice, I'll update my query to reflect that!

**Comment by valyala** [comment]
Closing this feature request as complete then, since [timezone_offset](https://docs.victoriametrics.com/metricsql/#timezone_offset) function has been added to MetricsQL.

[MetricsQL](https://docs.victoriametrics.com/metricsql) still misses easy-to-use functionality for grouping by day / week / month. I don't know good solution yet :( If you have an idea on the functions, which can be added in MetricsQL for simplifying grouping by day / week / month, and make this grouping timezone-aware, then feel free creating a new feature request.
