### ISSUE TITLE
Question: How to ignore duplicates in aggregation methods (sum_over_time...)

### ISSUE THREAD

**Issue by rbariou** [VictoriaMetrics/VictoriaMetrics#1308]
What is the best way in VM to completely ignore incoming duplicates within a time serie ?

I need aggregation methods such as sum_over_time not to accumulate values set at the same timestamp.

I figured -dedup.minScrapeInterval seems to work for me, but not sure if this is the optimal way. Which datapoint VM will decide to keep (last/first ?), doc says "arbitrary".

Could you please shine some light on this ?

Thank you

**Comment by f41gh7** [comment]
With -dedup.minScrapeInterval VictoriaMetrics will use first datapoint at given interval.

**Comment by valyala** [comment]
> Which datapoint VM will decide to keep (last/first ?), doc says "arbitrary".

If `-dedup.minScrapeInterval=<interval>` command-line flag is passed to VictoriaMetrics, then it leaves the datapoint with the smallest timestamp on every `<interval>`. If there are multiple datapoints with identical timestamps exist in a single time series, then VictoriaMetrics leaves an arbitrary datapoint. See more details at https://docs.victoriametrics.com/#deduplication .
