### ISSUE TITLE
Question: query_range vs export

### ISSUE THREAD

**Issue by rbariou** [VictoriaMetrics/VictoriaMetrics#1309]
Most of my metrics have irregular scrap intervals, and I simply want to plot my timeseries exactly how they were generated.

Is there a way to use query_range to do just that (without any "step" defined"), or should I fallback on export instead (with start param). 
What is the behavior of query_range if no step is defined ?
Now that I'm using dedup.minScrapInterval, it seems that query_range is often filling gaps where I don't want to.

Performance wise, would export be equivalent than query_range ?

Thank you for your support

**Comment by f41gh7** [comment]
Hello, it seems like in your case it's better to use exporter api. If step omitted for `query_range`, it uses default step  5 minutes.
 
  For performance tips, it should be faster to use exporter api.

 @valyala can you also suggest something?

**Comment by valyala** [comment]
The `/api/v1/query_range` always returns datapoints on the requested time range `[start ... end]` with the requested interval `step` as documented at https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries . It automatically adds missing points and/or removes superfluous points as described at https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness (aka Prometheus data model). If `step` arg is missing, then the default value - `5m` (5 minutes) is used as @f41gh7 already noted.

If you need raw points stored in the database, then use any of the supported export methods - see https://docs.victoriametrics.com/#how-to-export-time-series .

**Comment by rbariou** [comment]
Thank you for the answer !
I'll go the export way for raw data then.
