### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1311]
QA environment 80W time series data per second, two ·vmstorage nodes, ' memory 8G, direct OOM.

What is the minimum memory NE required for a node to support 50W of sequential data

**Comment by valyala** [comment]
Could you clarify what does `W` suffix mean? Probably you mean `thousands` or `millions`?

**Comment by WuJingLearn** [comment]
haha，sorry， So there's 800,000 time series data

**Comment by valyala** [comment]
VictoriaMetrics memory usage mostly depends on the number of active time series. This number can be monitored with the official Grafana dashboard for VictoriaMetrics as described [here](https://docs.victoriametrics.com/#monitoring). See also [these docs](https://docs.victoriametrics.com/FAQ.html#how-to-set-a-memory-limit-for-victoriametrics-components).

**Comment by WuJingLearn** [comment]
11

**Comment by valyala** [comment]
Try also VictoriaMetrics [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - it should use lower amounts of memory on data ingestion path.
