### ISSUE TITLE
Unable to connect grafana to vmselect

### ISSUE THREAD

**Issue by vinicius-maia** [VictoriaMetrics/VictoriaMetrics#1314]
**Describe the bug**
I'm following the cluster documentation of Victoria Metrics at: (https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster). My setup is 2 virtual machines running vminsert-prod, vmselect-prod and vmstorage-prod. I didn't identify any issue in the logs of vminsert-prod and vmstorage-prod, so I believe those binaries are OK. My vmselect setup is:
```
/usr/local/bin/vmselect-prod -dedup.minScrapeInterval 1ms -selectNode=<IP VM-01>:8481,<IP VM-02>:8481 -storageNode=<IP VM-01>:8401,<IP VM-02>:8401
```
I have a load balancer in front of both virtual machines with the HTTP port 8481 openned for grafana connections and it sends all traffic to the HTTP 8481 port of VM-01 and VM-02 running vmselect-prod.
When I try to connect my grafana using prometheus datasource, I use the URL: http://<IP OF LB>:8481. The rest of the datasource is default.

The error that I receive in the Grafana datasource setup is: HTTP Error Bad Request

The error in the vmselect log is:
```
May 21 09:39:02 vinvic501esf vmselect-prod: 2021-05-21T12:39:02.912Z#011warn#011VictoriaMetrics/app/vmselect/main.go:195#011remoteAddr: "10.0.4.43:60082", X-Forwarded-For: "10.244.4.1, 10.244.4.17, 10.244.4.17"; auth error: cannot parse accountID from "v1": strconv.Atoi: parsing "v1": invalid syntax
```
If I try the same setup but straight from my grafana server to one single vmselect binary, I receive the same errors messages.
I just can't understand where I had a mistake.

**To Reproduce**
Run vmselect-prod binary with:
```
/usr/local/bin/vmselect-prod -dedup.minScrapeInterval 1ms -selectNode=<IP VM-01>:8481,<IP VM-02>:8481 -storageNode=<IP VM-01>:8401,<IP VM-02>:8401
```
Point Grafana to vmselect-prod with: http://IP-vmselect:8481

**Expected behavior**
The expected behavior is a successful connection between grafana and vmselect-prod

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
# /usr/local/bin/vmstorage-prod --version
vmstorage-20210501-072056-tags-v1.59.0-cluster-0-g9aa44a276
```

**Comment by denisgolius** [comment]
@vinicius-maia 
Here is nginx example:

```
upstream vmselects {
    server 192.168.1.2:8481/select/0/prometheus
    server 192.1681.3:8481/select/0/prometheus
}
```

and the Grafana data source should be pointed to nginx balancer url http://vmselects

**Comment by denisgolius** [comment]
Also you could try to test VictoriaMetrics cluster from [docker-compose ](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster/deployment/docker) but you should specify `vmstorag`-es for `vminsert` and `vmselect` like this:

```
    command:
      - '--storageNode=192.168.1.1:8401,192.168.2.2:8401,192.168.2.3:8401'
```

**Comment by valyala** [comment]
As @denisgolius already mentioned, cluster version of VictoriaMetrics has slightly different urls compared to single-node version, since it needs to take into account url-based routing (e.g. select queries must be routed to vmselect nodes, while insert queries must be routed to vminsert nodes) and [multitenancy](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy). The url format for cluster components of VictoriaMetrics is described at https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format .

**Comment by vinicius-maia** [comment]
Finally I found what was wrong here.
The correct setup of vmselect is:
```
./vmselect-prod -selectNode=server-01:8481,server-02:8481,server-N:8481 -storageNode=server-01:8401,server-02:8401,server-N:8401
```
It was correct since the begining.

I got confused in the documentation about how to connect Grafana to vmselect. 
```
URLs for Prometheus querying API: http://<vmselect>:8481/select/<accountID>/prometheus/<suffix>, where:

<accountID> is an arbitrary number identifying data namespace for the query (aka tenant)
<suffix> may have the following values:
api/v1/query - performs PromQL instant query.
```
Reading that, I understood that I just must provide http://<IP of vmselect>:8481 in Grafana and the "/select/<accountID>/prometheus/<suffix>" part must be set in vmselect.

The trick here is that in Grafana I need to set:
```
http://vinvic501esf:8481/select/0/prometheus
```
And the "api/v1/query - performs PromQL instant query." part Grafana do in the background.

Now it is working smoothly.
