### ISSUE TITLE
Feature: Deduplication determinism & using latest data available

### ISSUE THREAD

**Issue by matejsp** [VictoriaMetrics/VictoriaMetrics#1320]
We have two victoria db with different retentions. First one feeds the data in realtime (1 week retentions). Then every minute we do rollup_candlestick[1m] and write to another instance. However there is sometimes a delay feeding data because there is a congestion in message queue. This mean that we do candlestick that is still not completely populated. We would like to update data in another instance based on the latest data. dedup.minScrapeInterval=60s in second instance help us with the problem but according to the docs:
> The earliest data point will be kept. In the case of equal timestamps, an arbitrary data point will be kept.

We would like for Victoria to always keep latest data and not earliest. But what is more crucial in our case is that in case of equal timestamps that latest point should always be used.

**Comment by hagen1778** [comment]
Hi @matejsp! Unfortunately, due to architecture reasons changing behaviour could be extremely difficult. Please let me know if you are interested in details.

As a workaround, you can try to add artificial delay for recording rules calculations. The delay must be equal or bigger than retention period in your message queue systems. In two words, make the delay big enough to cover the possible lag in message queue. Doing so recording rule will always be calculated on fully written data.
If you're using vmalert, take a look at `datasource.lookback` flag to add artificial delay for calculations.

**Comment by matejsp** [comment]
Yes, I am interested in the details, so I would know how it works internally.

Artificial delay is really bad because you would get really bad latency. Point is to have as realtime data as possible. And message queue lag is not predicable (like when upgrading message queue or when something bad happens). Alternative would be to calculate rollup_candlestick for latest granulation only in memory and write only after you get newer data (outside granulation). This only works if queue consuming is sequential (no out of order messages). But this would complicate logic quite a bit since you must join victoria query with in memory data.

We are currently using influxdb with continues queries. And we are in process of replacing it with victoria because influxdb is painfully slow (100x times slower than victoria based on our metrics).

**Comment by hagen1778** [comment]
> Yes, I am interested in the details, so I would know how it works internally.

VictoriaMetrics uses LSM-like data structure for storing data. Every time something is pushed to VM, it creates a `part` - structure with all data points ordered by time and time series ID. Such parts are immutable, they can't be changed or updated. 
So when a new data point arrives and VM (based on its indices) identifies it as a duplicate there two ways: discard it or keep it.
Deduplication now means data point will be discarded, so only data point which arrived first will be kept. 
But if we want to keep it for `keep latest data`, there is no way to "delete" the "earliest" data point which arrived before - parts are immutable. 
Of course, there are ways how `keep latest data` can be achieved. But this is a sort of thing which could become very pricey in  terms of performance. VM relies on immutability of data parts, and it makes VM incredibly fast for writes. Changing it could make usage experience worse.
If you're interested in more techincal details please see https://valyala.medium.com/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282

> Artificial delay is really bad because you would get really bad latency.

Is there any way you can detect the lag before doing the aggregation? For example, if you can expose the latest written timestamp by message queue, then you can use that as a threshold for aggregating service. For example, before every aggregation check the lag and if it exceeds `1m` skip the round. On next attempt, if lag is over - do lag / evaluation_interval iterations one-by-one.

**Comment by matejsp** [comment]
I understand. 

I tried detecting lag. For example after microservice startup I tried to get latest written timestamp for each metric. But it seems getting latest timestamp is really really expensive operation.

We are tracking around 15k of metrics/s from message queue. 

I tried calling: tlast_over_time(assetPrices) over last 7 days. But it seems to get latest timestamp for each metric is taking really long and consuming > 400 MB of RAM and taking couple of gigs of disk space. Is there any less expensive function to get last timestamp for each metric (in last week)? Isn't that supposed to be an O(1) operation for each metric?

I have also tried tlast_over_time(assetPrices[1h]).

**Comment by hagen1778** [comment]
I see. I meant to detect the lag of your message queue system. For example, Kafka exports the lag offset via metrics, and it is quite easy to track how far consumption fall behind. Having this info system which does aggregations may decide whether to continue doing them or take a pause until lag will resolved.

**Comment by hagen1778** [comment]
VictoriaMetrics leaves a single raw sample with the biggest timestamp per each -dedup.minScrapeInterval discrete interval if -dedup.minScrapeInterval is set to positive duration. For example, -dedup.minScrapeInterval=60s would leave a single raw sample with the biggest timestamp per each discrete 60s interval. This aligns with the [staleness rules in Prometheus](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness).

If multiple raw samples have the same biggest timestamp on the given -dedup.minScrapeInterval discrete interval, then the sample with the biggest value is left.

See https://docs.victoriametrics.com/#deduplication
