### ISSUE TITLE
Solaris/SmartOS Support

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#1322]
Right now `make victoria-metrics` on SmartOS alias Solaris fails with:
```
# github.com/VictoriaMetrics/VictoriaMetrics/lib/memory
lib/memory/memory.go:34:9: undefined: sysTotalMemory
# github.com/VictoriaMetrics/fastcache
vendor/github.com/VictoriaMetrics/fastcache/malloc_mmap.go:24:16: undefined: syscall.Mmap
# github.com/valyala/gozstd
Undefined			first referenced
 symbol  			    in file
ZSTD_createDCtx                     $WORK/b076/_x003.o
ZSTD_createCCtx                     $WORK/b076/_x003.o
ZSTD_createDDict                    $WORK/b076/_x002.o
ZSTD_createCDict                    $WORK/b076/_x002.o
ZSTD_endStream                      $WORK/b076/_x005.o
ZSTD_getFrameContentSize            $WORK/b076/_x003.o
ZSTD_initCStream                    $WORK/b076/_x005.o
ZSTD_freeCStream                    $WORK/b076/_x005.o
ZSTD_freeDDict                      $WORK/b076/_x002.o
ZSTD_freeCDict                      $WORK/b076/_x002.o
ZSTD_compressStream                 $WORK/b076/_x005.o
ZSTD_freeDStream                    $WORK/b076/_x004.o
ZSTD_CStreamOutSize                 $WORK/b076/_x005.o
ZSTD_DStreamOutSize                 $WORK/b076/_x004.o
ZSTD_compress_usingCDict            $WORK/b076/_x003.o
ZSTD_getErrorString                 $WORK/b076/_x003.o
ZSTD_CCtx_setParameter              $WORK/b076/_x005.o
ZSTD_decompressStream               $WORK/b076/_x004.o
ZSTD_createDStream                  $WORK/b076/_x004.o
ZSTD_freeDCtx                       $WORK/b076/_x003.o
ZSTD_freeCCtx                       $WORK/b076/_x003.o
ZSTD_compressBound                  $WORK/b076/_x003.o
ZSTD_createCStream                  $WORK/b076/_x005.o
ZSTD_flushStream                    $WORK/b076/_x005.o
ZSTD_decompressDCtx                 $WORK/b076/_x003.o
ZSTD_compressCCtx                   $WORK/b076/_x003.o
ZDICT_trainFromBuffer               $WORK/b076/_x002.o
ZSTD_initDStream_usingDDict         $WORK/b076/_x004.o
ZSTD_initCStream_usingCDict         $WORK/b076/_x005.o
ZSTD_CStreamInSize                  $WORK/b076/_x005.o
ZSTD_decompress_usingDDict          $WORK/b076/_x003.o
ZSTD_DStreamInSize                  $WORK/b076/_x004.o
ZSTD_getErrorCode                   $WORK/b076/_x003.o
ZDICT_isError                       $WORK/b076/_x002.o
ld: fatal: symbol referencing errors. No output written to $WORK/b076/_cgo_.o
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:131: app-local] Error 2
make[1]: Leaving directory '/home/admin/work/VictoriaMetrics'
make: *** [app/victoria-metrics/Makefile:4: victoria-metrics] Error 2
```

Would be nice to get it work on this platform, too.

**Comment by f41gh7** [comment]
Hello, can you try to build `Victoria-Metrics` from branch https://github.com/VictoriaMetrics/VictoriaMetrics/tree/solaris-build

 with command 
`GOOS=solaris make app-local-pure APP_NAME=victoria-metrics`

 If make isn't supported, use command:
`GOOS=solaris CGO_ENABLED=0 GO111MODULE=on go build  -mod=vendor -ldflags "-X 'github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=victoria-metrics-20210526-052554-heads-master-0-g8666ad912'" -o bin/victoria-metrics-pure github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics`

**Comment by jelmd** [comment]
Great - this works! Finally used `make {victoria-metrics|vmagent}-pure`. All others (vmalert, vmauth, vmbackup, vmctl, vmrestore) can be build with `make $target`, i.e. with CGO_ENABLED=1.

My primary interest here is vmagent: to be able to collect data from the local zones on the bare metal box and push them to the vmdb.

Wrt. golang 1.16: right now 1.14 is available, only. Used the attached Q&D patch to get it compiled
[go15.patch.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6549133/go15.patch.txt)

Again, thanx a lot!!! :-)

**Comment by jelmd** [comment]
BTW: Compiled it on SmartOS, which has flock(), but Solaris 11.3 doesn't. So I used the attached patch to get it work for Solaris 11.3 as well.
[victoria-metrics-solaris11.patch.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6550646/victoria-metrics-solaris11.patch.txt)

**Comment by f41gh7** [comment]
Thanks! 

  This changes will be adopted and included into the next release of VictoriaMetrics.

**Comment by valyala** [comment]
VictoriaMetrics components can be built for Solaris starting from the commit ddc80227024c486bc55b93352f25f1d0823d7265 with the following commands:

```
GOOS=solaris make <component-name>-pure
```

For example, `vmagent` for Solaris can be built with `GOOS=solaris make vmagent-pure`, while single-node VictoriaMetrics can be built with `GOOS=solaris make victoria-metrics-pure` .

**Comment by valyala** [comment]
The ability to build VictoriaMetrics components for Solaris / SmartOS is available starting from the [release v1.61.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.

**Comment by jelmd** [comment]
FWIW: Building vmctl 1.77.1 with `make vmctl-pure`  fails with:
```
APP_NAME=vmctl make app-local-pure
make[1]: Entering directory '/home/admin/work/VictoriaMetrics'
CGO_ENABLED=0 GO111MODULE=on go build  -trimpath -ldflags "-X 'github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=vmctl-v1.77.1 (v1.77.1)'" -o bin/vmctl-pure github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl
# github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl
github.com/cheggaaa/pb/v3/termutil.lockEcho: relocation target syscall.Syscall6 not defined
github.com/cheggaaa/pb/v3/termutil.unlockEcho: relocation target syscall.Syscall6 not defined
make[1]: *** [Makefile:263: app-local-pure] Error 2
make[1]: Leaving directory '/home/admin/work/VictoriaMetrics'
make: *** [app/vmctl/Makefile:82: vmctl-pure] Error 2
```

It can't be build with CGO_ENABLED=1 anymore, too - leads to the same undefined symbols problem as shown above.

**Comment by f41gh7** [comment]
It seems to be, that we are using outdated version from this PR https://github.com/cheggaaa/pb/pull/188/files

 https://github.com/cheggaaa/pb/blob/90c02fa07ea4ee9edb93588b7bd22e8e96b10aad/v3/termutil/term_x.go

The master branch version, uses correct syscall 

https://github.com/cheggaaa/pb/blob/master/v3/termutil/term_x.go#L39

 That's weird.

**Comment by jelmd** [comment]
Hmmm, not sure, why one needs a progress bar. Just printing some dots is usually sufficient (KISS) ;-)

**Comment by dmitryk-dk** [comment]
I think this issue is related to 
https://github.com/golang/go/issues/24357

as workaround we can scrip this library call for solaris

**Comment by valyala** [comment]
FYI, [vmctl](https://docs.victoriametrics.com/vmctl.html) should re-gain the ability to be built for Solaris / SmartOS starting from [v1.77.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by dmitryk-dk** [comment]
@jelmd can we close the issue?

**Comment by jelmd** [comment]
Yes, thanx a lot!!!
