### ISSUE TITLE
Vmagent

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1323]
Does Vmagent support auto-discovery

**Comment by f41gh7** [comment]
Yes, VictoriaMetrics single and vmagent supports many service discovery providers as prometheus does. Check these docs 
https://docs.victoriametrics.com/vmagent.html#how-to-collect-metrics-in-prometheus-format
https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter
