### ISSUE TITLE
Vmstorage

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1325]
How does Prometheus import historical data into vmstorage

**Comment by denisgolius** [comment]
@WuJingLearn 
**You can use:**
- remote_write see [this](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#prometheus-setup) 
- vmctl [Migrating data from Prometheus](https://docs.victoriametrics.com/vmctl.html#migrating-data-from-prometheus)
- [backup](https://docs.victoriametrics.com/vmbackup.html)/[restore](https://docs.victoriametrics.com/vmrestore.html)

**Comment by valyala** [comment]
See also [these docs](https://docs.victoriametrics.com/#backfilling).

Closing the question as answered.
