### ISSUE TITLE
group_left/group_right isn't  working when add a new labels or modify labels

### ISSUE THREAD

**Issue by wangqiongkaka** [VictoriaMetrics/VictoriaMetrics#1327]
When I add a new labels or modify labels, using left group prompts a duplicate time series on the right side

how can i do it ?

**Comment by f41gh7** [comment]
Hello, usually it means, that it's not enough labels to create distinct group result.

 Can you provide query example and error message, that you receive?

**Comment by pathcl** [comment]
is there any workaround for this? Im facing the same problem. If I have two jobs with the same targets but different labels I will get
```duplicate time series on the right side of `* ```
