### ISSUE TITLE
Data Corruption after power outage

### ISSUE THREAD

**Issue by fortindavid** [VictoriaMetrics/VictoriaMetrics#1328]
"ts":"2021-05-24T14:53:08.881Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1555","msg":"opened part \"/storage/data/small/2021_04/32272068_109699_20210430134951.639_20210430165518.602_167A839C0356176B\" in 0.013 seconds"}
{"ts":"2021-05-24T14:53:08.894Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1555","msg":"opened part \"/storage/data/small/2021_04/48326_48326_20210430170359.123_20210430170420.210_167A839C035617DA\" in 0.013 seconds"}
{"ts":"2021-05-24T14:53:08.894Z","level":"panic","caller":"VictoriaMetrics/lib/fs/reader_at.go:92","msg":"FATAL: cannot open file \"/storage/data/small/2021_04/59982365_148793_20210420170501.273_20210421133918.638_1677C0647D95F8D0/timestamps.bin\" for reading: open /storage/data/small/2021_04/59982365_148793_20210420170501.273_20210421133918.638_1677C0647D95F8D0/timestamps.bin: no such file or directory"}

We got the previous error by using VictoriaMetrics with docker release v1.58.0

Each night, our k8s pods (including victoria-metrics) are restarted

**Comment by f41gh7** [comment]
What kind of filesystem do you use for storage?

**Comment by f41gh7** [comment]
Can you also try to upgrade to 1.60 version?

**Comment by fortindavid** [comment]
Since I have installed the release 1.60.0 it has fixed the issue

**Comment by fortindavid** [comment]
The problem is fixed byuising teh release 1.60.0
