### ISSUE TITLE
[Question] Drop in replacement for influxdb

### ISSUE THREAD

**Issue by vipinvkmenon** [VictoriaMetrics/VictoriaMetrics#1332]
The performance metrics and the clustering option in victoria metrics seem rather impressive to try out. Wanted to understand a couple of aspects to see if this can be used as a drop-in replacement for influxdb.

1) Can this be used to ingest data through influxdb clients (NOT influx-Line)
2) O saw the metricsQL which has backward compatibility with PromQL...Does it have support for  InfluxQL? (not flux)...Any possibility of running influxQL on top of it through adapters etc?

**Comment by denisgolius** [comment]
@vipinvkmenon 

1. You can send data by http or by TCP/UDP when specified `-influxListenAddr=:8189` flag . To get more information see this 
[link](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf) .
2. You may write data into VictoriaMetrics on [different ways](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#prominent-features) but it has not `backward compatibility` for InfluxQL or any (known for us) adapters. You should run queries with PromQL/MetricsQL syntax.

**Comment by valyala** [comment]
The following article can be useful to read if you aren't familiar with PromQL/[MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) yet - https://medium.com/@valyala/promql-tutorial-for-beginners-9ab455142085

**Comment by valyala** [comment]
If you are migrating from InfluxDB to VictoriaMetrics, then [this guide](https://docs.victoriametrics.com/guides/migrate-from-influx/) can be useful.

Closing the question as answered.
