### ISSUE TITLE
PromQL sort_desc is not enable

### ISSUE THREAD

**Issue by coreyho** [VictoriaMetrics/VictoriaMetrics#1334]
**Describe the bug**
PromQL sort_desc is not enable.

When we used VictoriaMetrics as remote storage of prometheus, metrics containing  ‘sort_desc’ were not sorted, meanwhile prometheus returned sorted results.

`sort_desc(topk(20,transaction_average_time{instance="$instance",consumer_application_name="ALL",content_path!="ALL",provider_application_name="ALL"})) > 0`

**Comment by valyala** [comment]
Try a workaround by putting `>0` inside `sort_desc()`:

```
sort_desc(topk(20,transaction_average_time{instance="$instance",consumer_application_name="ALL",content_path!="ALL",provider_application_name="ALL"}) > 0)
```

**Comment by coreyho** [comment]
> Try a workaround by putting `>0` inside `sort_desc()`:
> 
> ```
> sort_desc(topk(20,transaction_average_time{instance="$instance",consumer_application_name="ALL",content_path!="ALL",provider_application_name="ALL"}) > 0)
> ```
It works well.

**Comment by valyala** [comment]
Closing the issue as resolved then.
