### ISSUE TITLE
how should I set vmselect address in prometheus client_golang

### ISSUE THREAD

**Issue by Cosrider** [VictoriaMetrics/VictoriaMetrics#1339]
I used to use prometheus client_golang to query prometheus data;
I use function api.NewClient to generate a client, the cfg.Address may set as
`https://192.168.0.3:6443/api/v1/namespaces/prometheus-namespace/services/prometheus:9090/proxy/`
'192.168.0.3 ' is the k8s cluster address;  'prometheus-namespace'  is the ns where prometheus installed;

and now i installed victoriaMetrics cluster verison;
the vmselect service is `vmselect-vmcluster-persistent`
in grafana , datasource is set to 'http://vmselect-vmcluster-persistent:8481/select/0/prometheus' , i can get metrics correctly.

therefore, i want to use prometheus client_golang to query vm data;

when i set address to `https://192.168.0.3:6443/api/v1/namespaces/vm-namespace/services/vmselect-vmcluster-persistent:8481/proxy/`
'vm-namespace' is the ns where vm cluster installed.

it returned error
```
error:bad_response: readObjectStart: expect { or n, but found
r, error found in #1 byte of ...|remoteAddr:|..., bigger context ...|remoteAddr: 
```

however, when i set address to `https://192.168.0.3:6443/api/v1/namespaces/vm-namespace/services/vmselect-vmcluster-persistent:8481/select/0/prometheus/proxy`

it returned error
```
client_error: client error: 404
````

how should i set the address, or is there another package like prometheus client_go which can be used to query data from vm?

**Comment by f41gh7** [comment]
Can you try this one:

`https://192.168.0.3:6443/api/v1/namespaces/vm-namespace/services/vmselect-vmcluster-persistent:8481/proxy/select/0/prometheus`

**Comment by Cosrider** [comment]
> Can you try this one:
> 
> `https://192.168.0.3:6443/api/v1/namespaces/vm-namespace/services/vmselect-vmcluster-persistent:8481/proxy/select/0/prometheus`

It works, thanks
