### ISSUE TITLE
Possible documentation improvement

### ISSUE THREAD

**Issue by chhetripradeep** [VictoriaMetrics/VictoriaMetrics#1341]
Thank you so much for the awesome software. 

I was looking for ways in which we can improve victoriametrics documentation recently and came across Doks Theme of Hugo.

I tried it with one page of the existing documentation and hosted it over here: https://victoriametrics.netlify.app/. One advantage is we can host blog along with documentation (personally i am not a big fan of medium blog)

Let me know what you think. I can help  with migration in case you're interested.

**Comment by denisgolius** [comment]
@chhetripradeep 
Thanks for your great work!
We have already choose Hugo too and soon it will be applied in action.
