### ISSUE TITLE
VictoriaMetrics how to  statistics  big label 

### ISSUE THREAD

**Issue by jiangxinlingdu** [VictoriaMetrics/VictoriaMetrics#1346]
in prometheus use like promql:
topk(10, count by (__name__)({__name__=~".+"}))

but do this in vm error, i want to collection big label ,what should I do

**Comment by hagen1778** [comment]
Hi @jiangxinlingdu!

> topk(10, count by (name)({name=~".+"}))

It doesn't look like a correct query. It should be `topk(10, count by (name) ({__name__=~".+"}))`. 
Btw, what exact error you got from VM?

The following docs could also help you find the heaviest seres - https://docs.victoriametrics.com/?highlight=status#tsdb-stats.

**Comment by jiangxinlingdu** [comment]
> 嗨@jiangxinlingdu！
> 
> > topk(10, count by (name)({name=~".+"}))
> 
> 它看起来不像一个正确的查询。应该是`topk(10, count by (name) ({__name__=~".+"}))`。
> 顺便说一句，你从 VM 得到了什么确切的错误？
> 
> 以下文档也可以帮助您找到最重的序列 - https://docs.victoriametrics.com/?highlight=status#tsdb-stats。

![image](https://user-images.githubusercontent.com/6373972/120255937-a8b66580-c2bf-11eb-90ba-e6c43116510e.png)

**Comment by jiangxinlingdu** [comment]
> Hi @jiangxinlingdu!
> 
> > topk(10, count by (name)({name=~".+"}))
> 
> It doesn't look like a correct query. It should be `topk(10, count by (name) ({__name__=~".+"}))`.
> Btw, what exact error you got from VM?
> 
> The following docs could also help you find the heaviest seres - https://docs.victoriametrics.com/?highlight=status#tsdb-stats.

![image](https://user-images.githubusercontent.com/6373972/120255981-be2b8f80-c2bf-11eb-8399-63bf85f60b61.png)

**Comment by hagen1778** [comment]
The screenshot does not contain the full error description. Could you pls copy it all?

Have you tried to use `/status` page I mentioned above? For example, it could look like this `http://<victoriametrics-addr>:8428/api/v1/status/tsdb?topN=10&date=2021-05-30`

**Comment by jiangxinlingdu** [comment]
> The screenshot does not contain the full error description. Could you pls copy it all?
> 
> Have you tried to use `/status` page I mentioned above? For example, it could look like this `http://<victoriametrics-addr>:8428/api/v1/status/tsdb?topN=10&date=2021-05-30`

ok  ,i try

**Comment by jiangxinlingdu** [comment]
3q, ok,  For example, it could look like this http://<victoriametrics-addr>:8428/api/v1/status/tsdb?topN=10&date=2021-05-30
