### ISSUE TITLE
A small part of the time series is missing

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#1347]
**Describe the bug**
We used the cluster version of the VM to transfer data through the http api provided by vm-insert.

We found that some of the same metric name have only one label and different time series. After storage in vmstorage, only one time series can be queried

for example:
We insert the following two time series data by vminsert

`cpu.idle{dc="lq", endpoint="1.1.1.1", ip="1.1.1.1", ipv6="1.1.1.1", psm="iaas.tosmix.compute", vdc="lq"}`

`cpu.idle{dc="lq", endpoint="1.1.1.1", ip="1.1.1.1", ipv6="1.1.1.1", psm="tos.mosaic.tos", vdc="lq"}`

It can be seen that only the psm label is different.

There is only one time series when query

![image](https://user-images.githubusercontent.com/2275120/120330095-104fcd80-c31f-11eb-942f-696b3db3a119.png)

So based on the 1.60.0-cluster version, we added debug logs on insert, storage, and select components respectively

***vminsert***
![image](https://user-images.githubusercontent.com/2275120/120334003-d5e82f80-c322-11eb-831c-74a26b9e89f1.png)
It can be seen that we insert two time series, and the value of the psm tag is different

***vmstorage***
![image](https://user-images.githubusercontent.com/2275120/120335280-eea51500-c323-11eb-85c1-69770315b8f1.png)
We caught the data on the third and thirteenth storage nodes

***vmselect***
![image](https://user-images.githubusercontent.com/2275120/120335705-43e12680-c324-11eb-8852-027249e14035.png)
In the query node, only one time series is queried

So, what is the cause of this problem? We now suspect that there is a problem when the storage merges?
Thanks

**Comment by f41gh7** [comment]
Hello, 

 1) can you try to export metrics, with `/api/v1/export` api call, something like `curl http://vmselect:8481/select/tenant_id/prometheus/api/v1/export -d 'match={__name__="cpu.idle"}' ` ?

2) Ensure, that `vmselect` was configured with all exist `vmstorage` nodes passed via `-storageNode` flag.

**Comment by jinlongwang** [comment]
1.  try to  export metrics, with /api/v1/export api call, still only one series 
![image](https://user-images.githubusercontent.com/2275120/120583513-f5857200-c460-11eb-8977-9ace662df1ec.png)

2. Confirm that all selected storage nodes are configured. That's what I suspected first, so we double check it.

**Comment by jinlongwang** [comment]
Can there be any clues to investigate? Or how should we investigate
thx

**Comment by f41gh7** [comment]
What else you can try: 
 - run designated vmselect node, that has only one storage node configured (third vmstorage node, where metric with label `psm="tos.mosaic.tos"` was written).
 - execute query with this select node (export and query).

 Check, was it able to find metric or not?

 Btw, how many vmstorage nodes you have?
 Was replicationFactor enabled for vminsert and vmselect?

**Comment by jinlongwang** [comment]
hi @f41gh7 
we run designated vmselect node, that has only third vmstorage node configure, the series still lost
![image](https://user-images.githubusercontent.com/2275120/121119472-44ab1880-c84e-11eb-87f7-16653bc418c4.png)

![image](https://user-images.githubusercontent.com/2275120/121119496-4ecd1700-c84e-11eb-8d98-37f9d6d9477a.png)

and we have 15 vmstorage nodes， replicationFactor is not enabled

thx

**Comment by tangqipengleoo** [comment]
hi @f41gh7 
We find the lost metric's TSID appears in both DeletedMetricIDsSet and tsidCache, here is the debug log
In lib/storage/metric.go `func mergeBlockStreamsInternal(ph *partHeader, bsw *blockStreamWriter, bsm *blockStreamMerger, stopCh <-chan struct{},
	dmis *uint64set.Set, retentionDeadline int64, rowsMerged, rowsDeleted *uint64) error`,line 55
![delete](https://user-images.githubusercontent.com/83160619/121520640-ba1d1180-ca25-11eb-9d38-58c78b5e0aa1.png)
In lib/storage/storage.go `func (s *Storage) add(rows []rawRow, dstMrs []*MetricRow, mrs []MetricRow, precisionBits uint8) error`,line 1662
![tsidfromcache](https://user-images.githubusercontent.com/83160619/121520654-be492f00-ca25-11eb-83b6-e47c2d0823bd.png)
We suspect after calling the delete method (func `(db *indexDB) deleteMetricIDs(metricIDs []uint64) error),` the service was unexpectedly interrupted and exited, resulting in Storage.tsidCache not being emptied. After the server restarted again, the tsidCache before deletion was loaded, but the metric that was deleted before TSID has been marked for deletion(`nsPrefixDeletedMetricID = 4`), resulting in data inconsistency
thx

**Comment by jinlongwang** [comment]
> hi @f41gh7
> We find the lost metric's TSID appears in both DeletedMetricIDsSet and tsidCache, here is the debug log
> In lib/storage/metric.go `func mergeBlockStreamsInternal(ph *partHeader, bsw *blockStreamWriter, bsm *blockStreamMerger, stopCh <-chan struct{}, dmis *uint64set.Set, retentionDeadline int64, rowsMerged, rowsDeleted *uint64) error`,line 55
> ![delete](https://user-images.githubusercontent.com/83160619/121520640-ba1d1180-ca25-11eb-9d38-58c78b5e0aa1.png)
> In lib/storage/storage.go `func (s *Storage) add(rows []rawRow, dstMrs []*MetricRow, mrs []MetricRow, precisionBits uint8) error`,line 1662
> ![tsidfromcache](https://user-images.githubusercontent.com/83160619/121520654-be492f00-ca25-11eb-83b6-e47c2d0823bd.png)
> We suspect after calling the delete method (func `(db *indexDB) deleteMetricIDs(metricIDs []uint64) error),` the service was unexpectedly interrupted and exited, resulting in Storage.tsidCache not being emptied. After the server restarted again, the tsidCache before deletion was loaded, but the metric that was deleted before TSID has been marked for deletion(`nsPrefixDeletedMetricID = 4`), resulting in data inconsistency
> thx

@f41gh7 @valyala Please help us confirm whether it is a bug

**Comment by tangqipengleoo** [comment]
hi @f41gh7 
We find more information that might be useful. We try to create a new TSID for the lost metric, in the func(`func (is *indexSearch) getTSIDByMetricName(dst *TSID, metricName []byte) error`,lib/storage/index_db.go,line 1798),the metricID has been found in the external storage,and it has been marked as deleted by the `dmis`. But at a certain moment,the `dmis` will be reset, which lead to `getTSIDByMetricName` return a deleted metricID. Here is the debug log 
![generate](https://user-images.githubusercontent.com/83160619/121628837-9bae2900-caac-11eb-9ffc-d2d92d74b092.png)

Because of the  return error of `getTSIDByMetricName` is not `io.EOF`, vmstroage will not `generateUniqueMetricID()` for the lost metric. We think is the usage of `indeDB.deletedMetricIDs(*uint64set.set)` leads this result. Please help us confirm 
this opinion,thx.

**Comment by f41gh7** [comment]
Thanks a lot for detail investigation, its a bug. Workaround for now - is cleaning vmstorage cache:
1) stop vmstorage
2) remove cache folder `vmstorage-data/cache`
3) start vmstorage.

 Later we will introduce fix for it. At metrics delete request, vmstorage will load deleted metricsID into cache first, then  cleanup metrics cache and mark metricID as deleted at table.

**Comment by tangqipengleoo** [comment]
hi @f41gh7 We found another information that might be useful.
When we try to trace the the generation process of the lost metric(after reset the tsidCache), we find the lost metric's TSID can be found in the external storage, and this TSID is marked for deletion in current DeletedMetricIDsSet, which leads the 
 phenomenon of data cannot be written(new arrival metric use the deleted TSID,insead of creating a new one).Here is the debug log.
![generate](https://user-images.githubusercontent.com/83160619/121660653-0a53ac80-cad6-11eb-893d-376e97c0f0b4.png)
So far we do not know why there is a piece of data marked as deleted in current storage but not marked deleted in the external storage. But we think if check the TSID which is found in the external storage using current storage's DeletedMetricIDsSet, we can get the lost mertric.

**Comment by valyala** [comment]
The bugfix for this issue has been implemented in [v1.61.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Upgrading to `v1.61.1` or newer release should prevent from this bug in the future. Unfortunately the ongoing issue won't be automatically fixed after the upgrade. You need to manually remove the cache as @f41gh7 mentioned in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1347#issuecomment-859447441). After that newly ingested data should become visible. The old data will remain invisible, since it is inserted under the deleted `metricID`.

**Comment by jinlongwang** [comment]
Great, we will verify it in the test environment, thank you

**Comment by tangqipengleoo** [comment]
@f41gh7 Thanks a lot for such a quick bug fix. In our issue, the TSID which should be marked deleted in both current and external storage is only marked in the current storage because of unclean shutdown. We think after using `func (db *indexDB) getTSIDByNameNoCreate(dst *TSID, metricName []byte) error` by external storage, we can check the search result with current storage's `deletedMetricIDs`. If the TSID searched from external storage is marked deleted in the current `deletedMetricIDs`,we should delete it in the external storage and create a new MetricId for the metric.
Here is our PR [link.](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1383)
Thx.

**Comment by valyala** [comment]
> We think after using `func (db *indexDB) getTSIDByNameNoCreate(dst *TSID, metricName []byte) error` by external storage, we can check the search result with current storage's deletedMetricIDs. If the TSID searched from external storage is marked deleted in the current `deletedMetricIDs`, we should delete it in the external storage and create a new `MetricID` for the metric.

Thanks for the investigation and the [pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1383)! The commit b133de1 took the idea from the PR and made it more generic by moving the deletedMetricIDs set from indexDB to Storage. Now the set is consistently shared across both the current indexDB and the previous indexDB (aka extDB).

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b133de1e37969689869167f7b71e71af733f66b4 in included in VictoriaMetrics [v1.62.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @jinlongwang , @tangqipengleoo , could you verify whether the upgrade to v1.62.0 fixes the issue with missing samples for some time series? It is recommended deleting the `<-storageDataPath>/cache` directory after stopping the previous version of VictoriaMetrics and starting v1.62.0 .

**Comment by jinlongwang** [comment]
> The commit [b133de1](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b133de1e37969689869167f7b71e71af733f66b4) in included in VictoriaMetrics [v1.62.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @jinlongwang , @tangqipengleoo , could you verify whether the upgrade to v1.62.0 fixes the issue with missing samples for some time series? It is recommended deleting the `<-storageDataPath>/cache` directory after stopping the previous version of VictoriaMetrics and starting v1.62.0 .

ok, we will try it. 
thx

**Comment by valyala** [comment]
@liangyuanpeng , I suppose the bug is fixed since v1.62.0 as pointed [above](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1347#issuecomment-868453780), so closing this issue. If this isn't the case, then feel free re-opening the issue or creating new one and linking to this one.
