### ISSUE TITLE
Can't start VictoriaMetrics use docker-compose and volume mapping on Windows

### ISSUE THREAD

**Issue by ReyStar** [VictoriaMetrics/VictoriaMetrics#135]
I've wrote simple [docker-compose.yml](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3443071/docker-compose.txt) file with mapping image directory with data to my OS directory, I started it and saw next error: ![VictoriaMetrics_Error](https://user-images.githubusercontent.com/20856751/62062365-8a99fd00-b231-11e9-8430-d86c31a3cab7.png)
Directory with VictoryaMetrics files was created in file system: 
![VictoriaMetrics_Error_2](https://user-images.githubusercontent.com/20856751/62062577-ee242a80-b231-11e9-97c7-bfc93706bfd8.png)
I need help I haven't idea what wrong (((

**Comment by valyala** [comment]
This looks like an issue in Docker for Windows - see https://github.com/docker/for-win/issues/445 . Basically it fails calling fsync on windows directories.

**Comment by ReyStar** [comment]
Yep. It's really look like this case. Thank you very much!!!!!

**Comment by valyala** [comment]
It is possible adding workaround for the issue in VictoriaMetrics like ignoring errors on directory sync. But this would break data durability for `Docker under Windows` setup.

**Comment by ReyStar** [comment]
Not sure "ignoring errors" is true way. This very interesting problem, but not critical in this moment, need more research and add task to tech-backlog.
