### ISSUE TITLE
vmauth random panics

### ISSUE THREAD

**Issue by aval13** [VictoriaMetrics/VictoriaMetrics#1353]
**Describe the bug**
On Jun 2nd we upgraded VMC components from 1.55.1 to 1.60.0.
Since then, apparently randomly, but usually every few hours, vmauth panics.
So far 34 panics in 48 hours. Last 3 panics were immediately after service restart (we manage it with systemd unitfile with max 3 restarts on failure).

**To Reproduce**
Unknown yet.

**Expected behavior**
Not panic? Just work like 1.55.1 did with 0 panics.

**Logs**
On every panic the stacktrace seems to me to be the same (except of course the addresses).

First panic after around 4 hours in (last 1.55.1 start, first 1.60.0 start, first panic):
May 28 07:20:13 [server_name] vmauth-prod[8918]: 2021-05-28T07:20:13.026Z        info        VictoriaMetrics/lib/logger/flag.go:12        build version: vmauth-20210303-095340-tags-v1.55.1-0-g3a68b9448
[...]
Jun 02 10:55:55 [server_name] vmauth-prod[8083]: 2021-06-02T10:55:55.813Z        info        VictoriaMetrics/lib/logger/flag.go:12        build version: vmauth-20210524-130632-tags-v1.60.0-0-g08234aa7a
...
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: panic: net/http: abort Handler
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: goroutine 10154478 [running]:
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:221 +0xbd
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: panic(0x741fc0, 0xc00001eab0)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         runtime/panic.go:965 +0x1b9
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: net/http/httputil.(*ReverseProxy).ServeHTTP(0xa2bf40, 0x878340, 0xc0003fe380, 0xc000087200)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         net/http/httputil/reverseproxy.go:338 +0x165d
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: main.requestHandler(0x878340, 0xc0003fe380, 0xc000087200, 0x1)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmauth/main.go:84 +0x32c
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc0000eaa80, 0x878340, 0xc0003fe380, 0xc000087200, 0x8224e0)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:297 +0x491
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1(0x878340, 0xc0003fe380, 0xc000087200)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:189 +0xb4
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: net/http.HandlerFunc.ServeHTTP(0xc00000c168, 0x878340, 0xc0003fe380, 0xc000087200)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         net/http/server.go:2069 +0x44
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: net/http.serverHandler.ServeHTTP(0xc0000f4000, 0x878340, 0xc0003fe380, 0xc000087200)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         net/http/server.go:2887 +0xa3
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: net/http.(*conn).serve(0xc00067bea0, 0x878b60, 0xc00047b4c0)
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         net/http/server.go:1952 +0x8cd
Jun 02 15:21:59 [server_name] vmauth-prod[8083]: created by net/http.(*Server).Serve
Jun 02 15:21:59 [server_name] vmauth-prod[8083]:         net/http/server.go:3013 +0x39b

Last panic (like the 2 before it) after 0-2 seconds:
Jun 04 16:30:28 [servername] vmauth-prod[7742]: 2021-06-04T16:30:28.549Z        info        VictoriaMetrics/lib/logger/flag.go:12        build version: vmauth-20210524-130632-tags-v1.60.0-0-g08234aa7a
...
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: panic: net/http: abort Handler
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: goroutine 530 [running]:
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:221 +0xbd
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: panic(0x741fc0, 0xc00008aa90)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         runtime/panic.go:965 +0x1b9
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: net/http/httputil.(*ReverseProxy).ServeHTTP(0xa2bf40, 0x878160, 0xc0002bf6e0, 0xc0002bab00)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         net/http/httputil/reverseproxy.go:338 +0x165d
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: main.requestHandler(0x878160, 0xc0002bf6e0, 0xc0002bab00, 0x1)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         github.com/VictoriaMetrics/VictoriaMetrics/app/vmauth/main.go:84 +0x32c
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc0001c5700, 0x878160, 0xc0002bf6e0, 0xc0002bab00, 0x8224e0)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:297 +0x491
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1(0x878340, 0xc000286700, 0xc0002bab00)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:189 +0xb4
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: net/http.HandlerFunc.ServeHTTP(0xc00009a210, 0x878340, 0xc000286700, 0xc0002bab00)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         net/http/server.go:2069 +0x44
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: net/http.serverHandler.ServeHTTP(0xc000228000, 0x878340, 0xc000286700, 0xc0002bab00)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         net/http/server.go:2887 +0xa3
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: net/http.(*conn).serve(0xc000068a00, 0x878b60, 0xc000184a40)
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         net/http/server.go:1952 +0x8cd
Jun 04 16:30:29 [server_name] vmauth-prod[7742]: created by net/http.(*Server).Serve
Jun 04 16:30:29 [server_name] vmauth-prod[7742]:         net/http/server.go:3013 +0x39b

Last start logs (human intervention after 3 failed after 2 seconds restarts):
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.609Z        info        VictoriaMetrics/lib/logger/flag.go:12        build version: vmauth-20210524-130632-tags-v1.60.0-0-g08234aa7a
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.611Z        info        VictoriaMetrics/lib/logger/flag.go:13        command line flags
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.611Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "auth.config" = "/etc/vmauth/vmauth.yml"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.611Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "enableTCP6" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.611Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "envflag.enable" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "envflag.prefix" = ""
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "fs.disableMmap" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "http.connTimeout" = "2m0s"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "http.disableResponseCompression" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "http.idleConnTimeout" = "1m0s"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "http.maxGracefulShutdownDuration" = "7s"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "http.pathPrefix" = ""
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "http.shutdownDelay" = "0s"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "httpAuth.password" = "secret"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.612Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "httpAuth.username" = ""
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "httpListenAddr" = ":8427"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerDisableTimestamps" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerErrorsPerSecondLimit" = "0"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerFormat" = "default"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerLevel" = "INFO"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerOutput" = "stderr"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerTimezone" = "UTC"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "loggerWarnsPerSecondLimit" = "0"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "maxIdleConnsPerBackend" = "100"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.613Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "memory.allowedBytes" = "0"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "memory.allowedPercent" = "60"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "metricsAuthKey" = "secret"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "pprofAuthKey" = "secret"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "reloadAuthKey" = "secret"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "tls" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "tlsCertFile" = ""
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "tlsKeyFile" = "secret"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "version" = "false"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.614Z        info        VictoriaMetrics/app/vmauth/main.go:33        starting vmauth at ":8427"...
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.619Z        info        VictoriaMetrics/app/vmauth/auth_config.go:168        Loaded information about 273 users from "/etc/vmauth/vmauth.yml"
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.622Z        info        VictoriaMetrics/app/vmauth/main.go:37        started vmauth in 0.007 seconds
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.622Z        info        VictoriaMetrics/lib/httpserver/httpserver.go:82        starting http server at http://:8427/
Jun 04 18:41:29 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:29.622Z        info        VictoriaMetrics/lib/httpserver/httpserver.go:83        pprof handlers are exposed at http://:8427/debug/pprof/
Jun 04 18:41:44 [server_name] vmauth-prod[32728]: 2021-06-04T18:41:44.441Z        info        VictoriaMetrics/lib/memory/memory.go:37        limiting caches to 2481423974 bytes, leaving 1654282650 bytes to the OS according to -memory.allowedPercent=60

**Version**
\# vmauth-prod --version
vmauth-20210524-130632-tags-v1.60.0-0-g08234aa7a

**Used command-line flags**
/usr/sbin/vmauth-prod -auth.config=/etc/vmauth/vmauth.yml

Config file has only entries of sets of username+password+urlprefix.
Same config file, last config change was on 2021-05-28 07:20:01 UTC (when 1.55.1 was last restarted before 1.60.0 upgrade)

Further logs available on request if needed.

**Comment by f41gh7** [comment]
It's because of new panic handler at lib/httpserver. Its ok for golang reverse_proxy to panic https://github.com/golang/go/issues/28239

 Need to handle this error.

**Comment by f41gh7** [comment]
This PR must fix it https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1355

**Comment by aval13** [comment]
@f41gh7 Thank you for the quick response.

Based on your estimation of the next release ETA, would you advise we downgrade for the moment or wait for it?
(if 1.60.1/1.61.0 is expected this week, it would be ok for us to wait)

Thank you for your time.

**Comment by aval13** [comment]
Hello @valyala , can you please share a thought about the previous comment?

Thank you.

**Comment by valyala** [comment]
@aval13 , the pull request has been merged in the commit 6b29b955c0951fc69f53a38c6e74f5dbe3ac3741 . This commit will be available in the release v1.61.0 , which is scheduled to be published in the next 24 hours.
