### ISSUE TITLE
problem with count(), large step size, and grafana

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#1354]
**Describe the bug**

When a large step size is set in Grafana for a `count()` query with multiple series, the stacked graphed output is strange (stuttering values).  (E.g. `resolution=1/10` for 2 day range, which is step size 3000.)

The symptom disappears by decreasing step size, or by setting 2x step size in `Min step` query option.  However neither of these workarounds is satisfactory.  (Decreasing step size means a slower query, and manually setting `Min step` makes assumptions about the query range.)

**Screenshots**

query:  `count by (version) (info)`, resolution=1/10

![Screen Shot 2021-06-07 at 10 06 20 AM](https://user-images.githubusercontent.com/1708631/120946630-0ba07480-c778-11eb-88af-07f12695817f.png)

query:  `count by (version) (info)`, resolution=1/4

![Screen Shot 2021-06-07 at 10 08 41 AM](https://user-images.githubusercontent.com/1708631/120946707-5b7f3b80-c778-11eb-9893-7cfb244580fc.png)

**Version**
VictoriaMetrics 1.59.0
Grafana 7.5.2

**Comment by valyala** [comment]
Did you set `-search.maxStalenessInterval` or `-search.maxLookback` command-line options when running VictoriaMetrics? Or probably you set up `max_lookback` query arg for the Grafana datasource used for querying VictoriaMetrics? These options limit the lookbehind window for searching the previous datapoint for every returned timestamp. By default it is set to the `step` query arg Grafana sends to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) unless it is overridden by one of the options mentioned above. In this case some samples can become missing in the output result if they are located outside the adjusted (smaller) lookbehind window.

The following workarounds exist:
* To remove (or adjust) config options mentioned above, so they cover the maximum possible `step` query arg.
* To wrap the [series selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors) into `last_over_time()` function. For example:

```metricsql
count by (version) (last_over_time(info))
```

This also may be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/748

**Comment by belm0** [comment]
Thank you.

I confirmed we do not set `-search.maxStalenessInterval`, `-search.maxLookback`, or `max_lookback` query arg.

I tried `last_over_time(info[d])` for various `d`, and it did not help.

>  [or] adjust config options mentioned above so they cover the maximum possible step query arg

Do you expect this should be necessary?  I'm not sure about the consequences to performance, query accuracy, etc.

**Comment by valyala** [comment]
> I tried `last_over_time(info[d])` for various d, and it did not help.

Do not set `[d]` - just use `last_over_time(info)` - in this case VictoriaMetrics must automatically set the lookbehind window to `step` value, which Grafana sends to [/api/v1/query_range](https://docs.victoriametrics.com/keyconcepts/#range-query). See [these docs](https://docs.victoriametrics.com/metricsql/#implicit-query-conversions) for details.

> Do you expect this should be necessary? I'm not sure about the consequences to performance, query accuracy, etc.

Ideally all the mentioned configs mustn't be set explicitly, since they may result in various unexpected issues.

Could you also follow https://docs.victoriametrics.com/troubleshooting/index.html#unexpected-query-results ?

**Comment by belm0** [comment]
I can't explain exactly, but switching such panels from Grafana "Timeseries (old)" to "Timeseries" seemed to resolve these problems.  I know the new panel implementation handles step sizes much differently.

**Comment by hagen1778** [comment]
Closing issue as inactive, and it looks like for @belm0 the problem is solved.
