### ISSUE TITLE
Memory Usage of vmagent is almost doubled after upgrade to v1.61.0

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#1368]
**Describe the bug**
I upgrade vmagent container's image from `v1.58.0` to `v1.61.0`, and it's OOM-Killed. When I increase the memory limit, **the memory usage of vmagent is almost doubled.** The pprof file of two deployments will be attached .

[vmagent-dump.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6636265/vmagent-dump.zip)

**Comment by xiaozongyang** [comment]
ping @valyala

**Comment by WuJingLearn** [comment]
老哥你好，请问你一个问题，Vmagent是不是真能拉取80w左右的指标啊·，80w左右内存需要2g多，当指标超过90w左右时，内存直接飙到10几个g，直接oom.

**Comment by xiaozongyang** [comment]
@WuJingLearn  你打开 streamParse  试试，能够大幅度降低内存用量 `-promscrape.streamParse`，官方文档在这里[stream-parsing-mode](https://docs.victoriametrics.com/vmagent.html#stream-parsing-mode)

**Comment by xiaozongyang** [comment]
@WuJingLearn 另外你说的 80w 是指写入指标的 QPS 还是活跃的 Time Series 数量，我们目前是 13G 内存写入指标 QPS 260W

**Comment by WuJingLearn** [comment]
是写入qps,通过vmagent去拉取pod的metric，我在做压力测试，当metric超过80万之后，内存迅速飙升

**Comment by WuJingLearn** [comment]
另外我使用的vmagent是单节点的

**Comment by f41gh7** [comment]
Hello, can you check that 1.58 and 1.61 version scrapes the same number of targets? There were few bug fixes for kubernetes service discovery process.
 In addition, 1.58 and 1.59 version could discover lower count of scrape target labels https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1240

 You can verify it by comparing two jsons, from vmagents api:
```
# at 1.58
curl localhost:8429/api/v1/targets > 1.58_targets.json
# at 1.61
curl localhost:8429/api/v1/targets > 1.61_targets.json
```

**Comment by xiaozongyang** [comment]
@f41gh7 

It seems that it's not a same problem of [#1240](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1240). We have 14 target discovered by k8s endpoints, number of targets didn't change after the upgrading operation, showing in this picture. We only scrape endpoints which has annotation `prometheus.io/scrape: true`, so most endpoints are not scraped.

![image](https://user-images.githubusercontent.com/8848479/121673011-067a5700-cae3-11eb-9db3-9ef5feae4fdd.png)

**Comment by xiaozongyang** [comment]
![image](https://user-images.githubusercontent.com/8848479/121673442-7557b000-cae3-11eb-89f7-2a7b867de233.png)
And total number of targets scraped by this vmagent instance wasn't double yet. Since there are many app pods deploying, this number are slightly changed, but it doesn't matter.

**Comment by xiaozongyang** [comment]
@WuJingLearn 
我上面给你发的数据也是单个 vmagent 的

**Comment by valyala** [comment]
@xiaozongyang , could you check how many CPU cores `vmagent` actually uses and then pass `GOMAXPROCS=N` environment variable when starting `vmagent` where `N` is slightly bigger value than the number of actually used CPU cores? For example, if `vmagent` uses 2.5 CPU cores, then pass `GOMAXPROCS=3` or `GOMAXPROCS=4`. This should reduce memory usage if `vmagent` runs on a host with much bigger number of CPU cores, since it allocates additional memory per each available CPU core. The `GOMAXPROCS` environment variable limits the number of available CPU cores. See https://golang.org/pkg/runtime/#hdr-Environment_Variables .

While this suggestion doesn't solve the original issue (e.g. the increased memory usage), it may help reducing the memory usage in general case. We are still investigating the source of increased memory usage.

**Comment by xiaozongyang** [comment]
@valyala 
Thanks for your suggestions!

We deploy vmagent in k8s and the cpu limit is 32, we don't change this value in this upgrade operation. And I check the value from `cpu.cfs_quota_us` and `cpu.cgs_period_us`, it doesn't conflict the value of limit.

**Comment by zhiyin009** [comment]
i have the same problem as well

**Comment by valyala** [comment]
@xiaozongyang , @zhiyin009 , could you try upgrading to the latest available version of `vmagent` - [v1.73.0 now](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and check whether the issue with increased memory usage still persists there?

**Comment by xiaozongyang** [comment]
@valyala I'm glad to, but sorry, I have been resigned from previous company and can't try that now. 🙁

**Comment by hagen1778** [comment]
Closing as inactive.
