### ISSUE TITLE
Incorrect calculation record rules

### ISSUE THREAD

**Issue by deemon87** [VictoriaMetrics/VictoriaMetrics#1369]
After update stack on 1.61.0 i have problem with calculation record rules. Each record each rule have the same value close to 0.
When I rollback vmalert to version 1.60.0 the problem is solved.
I don't have any special logs but if need i'll collect them

![image](https://user-images.githubusercontent.com/28749431/121644698-01de8000-ca9c-11eb-9d2c-bb5fffe8793e.png)

**Comment by deemon87** [comment]
Thanks

**Comment by hagen1778** [comment]
@deemon87 the fix has been released in https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.61.1
