### ISSUE TITLE
Vmagent question

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1371]
For 1000 thousand time series, Vmagent requires 8 gigabytes of memory. When I turned on stream parsing mode, it only required 300 megabytes of memory. What is the principle of stream parsing mode?

**Comment by hagen1778** [comment]
Hi @WuJingLearn! Have you checked the following page https://docs.victoriametrics.com/vmagent.html#stream-parsing-mode?
