### ISSUE TITLE
Scrape statistics page could show number of metrics scraped

### ISSUE THREAD

**Issue by lapo-luchini** [VictoriaMetrics/VictoriaMetrics#1377]
**Is your feature request related to a problem? Please describe.**
When I add a new metrics to scrape I check on the `/targets` page to check if it works fine; sometimes it works but but has zero content, and I can only know that by visiting it directly, but since the metrics endpoint is usually filtered to only allow my VM-host's IP address, that's not so easy to do.

**Describe the solution you'd like**
I'd like the `/targets` page to also report the number of series found in last scrape.

Columns right now:  `Last Scrape | Scrape Duration | Error`
Columns I'd like:  `Last Scrape | Scrape Duration | Samples scraped | Error`

**Describe alternatives you've considered**
I can always connect to the VM-host and check the metrics endpoint from the command line (i.e. with httpie or similar tool).

**Comment by valyala** [comment]
`vmagent` generates the following metrics with each scrape in the same way as [Prometheus does](https://prometheus.io/docs/concepts/jobs_instances/#automatically-generated-labels-and-time-series):

* up
* scrape_duration_seconds
* scrape_samples_scraped
* scrape_samples_post_metric_relabeling
* scrape_series_added

So the following query can be used for determining the number of samples scraped per each target at any given time: `scrape_samples_scraped`.

**Comment by valyala** [comment]
The commit 36d55bff6638795466a2c4f716754b7b355f5b58 adds the `Samples scraped` column at `/targets` and `/api/v1/targets` pages. @lapo-luchini , could you build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether it works as expected?

**Comment by lapo-luchini** [comment]
Yes… nice!
![image](https://user-images.githubusercontent.com/420454/122168694-e3ea9400-ce7c-11eb-8b75-612844e409a9.png)

**Comment by valyala** [comment]
FYI, vmagent and single-node VictoriaMetrics shows the `Samples scraped` column at `/targets` and `/api/v1/targets` pages starting from [v1.62.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
