### ISSUE TITLE
retentionPeriod default, would need another restore

### ISSUE THREAD

**Issue by stakeconomy** [VictoriaMetrics/VictoriaMetrics#1382]
We have restored data from a hosted version of victoriametrics into a single node victoriametrics machine.
All good until we figured out the default data retentionPeriod is only 30 days.

We moved retentionperiod to 90 days.

Can we do another restore? or are we going to end up getting double data points in the database?

**Version**
victoria-metrics-20210524-130543-tags-v1.60.0-0-g08234aa7a

**Comment by hagen1778** [comment]
Hi @stakeconomy! Restore procedure replaces all existing data with the given backup, so no duplicates will appear.

**Comment by stakeconomy** [comment]
Will it also overwrite the new data?
for example, I want to restore everything from 3 month ago to 1 month ago. 
Do I need to specify a date range?

**Comment by valyala** [comment]
If you need more fine grained data restoration, then take a look at [vmctl](https://victoriametrics.github.io/vmctl.html) tool. It allows migrating the data on the given time range, which matches the given label filters.

**Comment by stakeconomy** [comment]
Thanks. Too bad

I was really looking to keep the new data generated after the last backup and include the history from before 30 days.

Willl take a look at vmctl tool.

Op 15 jun. 2021 om 16:51 heeft Aliaksandr Valialkin ***@***.***> het volgende geschreven:

﻿

If you need more fine grained data restoration, then take a look at vmctl<https://victoriametrics.github.io/vmctl.html> tool. It allows migrating the data on the given time range, which matches the given label filters.

**Comment by valyala** [comment]
> I was really looking to keep the new data generated after the last backup and include the history from before 30 days.

We periodically receive this feature request from different users. E.g. to combine the locally stored data with the data from the backup. So it would be great implementing it in the future. Unfortunately this is non-trivial task, so it can take some time :(
