### ISSUE TITLE
sum_over_time function is not returning name of the metric

### ISSUE THREAD

**Issue by rjtokenring** [VictoriaMetrics/VictoriaMetrics#1384]
**Describe the bug**
Functions like avg_over_time of min_over_time are returning __name__ tag into metric section. This is not happening in sum_over_time function

`
POST {/select/1/prometheus/api/v1/query_range
Content-Type: application/x-www-form-urlencoded

query=avg_over_time(EVENTS{tagid="xyz"}[3600s])&step=3600m&start=1623113999&end=1623718798

Results:
    ....
    "result": [
      {
        "metric": {
          "__name__": "EVENTS",
          "tagid": "xyz",
         .....
`

while call on sum is returning

`
POST {/select/1/prometheus/api/v1/query_range
Content-Type: application/x-www-form-urlencoded

query=sum_over_time(EVENTS{tagid="xyz"}[3600s])&step=3600m&start=1623113999&end=1623718798

Results:
    ....
    "result": [
      {
        "metric": {
          "tagid": "xyz",
         .....
`

No "__name__": "EVENTS" is returned.

**Expected behavior**
sum_over_time function should work as avg/min/max/quantile functions

**Version**
reproduced with 1.51 and 1.61.1 cluster version

**Comment by valyala** [comment]
The metric name can be returned back with `alias()` function from [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html):

`alias(sum_over_time(EVENTS{tagid="xyz"}[3600s]), "EVENTS")`

**Comment by rjtokenring** [comment]
Thanks, got the point
