### ISSUE TITLE
yandex cloud service discovery

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1386]
**Describe the solution you'd like**
 Add yandex_sd to the configuration file. It should export metadata with IPv4 and IPv6 ips.

 Related APIs

 https://cloud.yandex.ru/docs/compute/api-ref/Instance/list 
 https://cloud.yandex.ru/docs/compute/api-ref/authentication

**Comment by valyala** [comment]
The service discovery for [Yandex cloud](https://cloud.yandex.com/en/) has been added into vmagent and VictoriaMetrics. See [these docs](https://docs.victoriametrics.com/sd_configs.html#yandexcloud_sd_configs). This change will be available in the next release. In the mean time it can be tested by building `vmagent` from the latest commit in [master](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master) branch according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment]
`vmagent` supports `yandexcloud_sd_configs` according to [these docs](https://docs.victoriametrics.com/sd_configs.html#yandexcloud_sd_configs) starting from [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
