### ISSUE TITLE
 Promxy No ARM version available

### ISSUE THREAD

**Issue by caizhiyong88** [VictoriaMetrics/VictoriaMetrics#1388]
Has Promxy been used in an ARM environment

**Comment by denisgolius** [comment]
@ caizhiyong88
It looks like you got the wrong repository for this issue. VictoriaMetrics don't provide promxy builds.

**Comment by tenmozes** [comment]
You can open issue about promxy here https://github.com/jacksontj/promxy/issues

**Comment by caizhiyong88** [comment]
Access to the ProMXY ARM version appears:
Error opening React index.html: open static/react/index.html: no such file or directory

**Comment by caizhiyong88** [comment]
Thank you very much if you can compile the ARM version of promxy

**Comment by denisgolius** [comment]
@caizhiyong88 

>Access to the ProMXY ARM version appears:
>Error opening React index.html: open static/react/index.html: no such file or directory

> Thank you very much if you can compile the ARM version of promxy

As I wrote before - VictoriaMetrics do not provide [promxy](https://github.com/jacksontj/promxy) builds. We provide ARM build only for VictoriaMetrics that you can find [here](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
You have already create issue https://github.com/jacksontj/promxy/issues/437 on **promxy** repository so you need to wait when their maintainers will answer.
