### ISSUE TITLE
Add HTTP sd to the service discovery

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1392]
**Describe the solution you'd like**

 Add `http_sd_configs`  as prometheus does https://github.com/prometheus/prometheus/pull/8839/files

**Comment by valyala** [comment]
HTTP-based service discovery has been added to vmagent in the commit ac54f34f9e1075dfd5bd25918ce52fa7631c9ddd . This commit will be included in the next release of VictoriaMetrics. In the mean time it is possible to build vmagent from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether the `http_sd_configs` works as expected in vmagent.

**Comment by valyala** [comment]
`http_sd_config` service discovery has been added in [v1.62.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
