### ISSUE TITLE
High CPU, RAM and disk IO usage once per the configured -retentionPeriod

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#1401]
**Describe the bug**

There is a regular spike in CPU, RAM and disk IO usage once per the configured `-retentionPeriod`. For example, if VictoriaMetrics runs with `-retentionPeriod=7d`, then the [default dashboard for Grafana](https://docs.victoriametrics.com/#monitoring) shows spikes for CPU usage, RAM usage and disk IO usage once per 7 days.

**To Reproduce**

1. Pass `-retentionPeriod=7d` to a single-node VictoriaMetrics or to `vmstorage` component from [VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html)
2. Ingest big number of time series (e.g. more than 10 millions) to it for more than 7 days.
3. Observe a spike in CPU usage, RAM usage and disk IO usage once per 7 days. If VictoriaMetrics runs on a resource-constrained system (e.g. with CPU and memory limits), then the resource usage spike can lead to OOM (out of memory) crash.

**Expected behavior**

Resource usage shouldn't change significantly during data ingestion.

**Version**

All the versions prior to and including v1.61.1 .

**Additional details**

Resource usage spike once per `-retentionPeriod` is related to how VictoriaMetrics rotates e.g. `indexdb` - an inverted index used for fast time series lookups by label filters. The rotation of `indexdb` is performed once per `-retentionPeriod`. It works in the following way:

* Old `indexdb` is removed.
* The current `indexdb` becomes old. The old `indexdb` is used for looking up historical time series, which still fit the configured `-retentionPeriod`.
* New `indexdb` is created.

After that the newly created indexdb is populated on demand. E.g. new entries are created for all the ingested time series. The registration of time series in the inverted index takes additional CPU, RAM and disk IO resources. If the number of ingested time series (aka active time series) is big, then the process of indexdb population can take an extended period of time. VictoriaMetrics performance can become slower than usual during this period of time.

**Possible solution**

To start populating new indexdb in advance, so it becomes populated at the rotation time.

**Comment by johnseekins** [comment]
I see this regular spike once a week with a 1 year long retention period. I provided some additional context in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1441#issuecomment-886717592, but here's additional interesting stuff that makes me think it's a weekly rollover of the indexdb:

```
root@storagehost3:~# ls -larth /var/lib/victoriametrics/storage/prod_cluster_1/indexdb/168915F9B8364F72/
total 72K
-rw-r--r--  1 victoria victoria    2 Jun 16 14:21 converted-to-v1.28.0
drwxr-xr-x  5 victoria victoria 4.0K Jun 16 14:21 ..
drwxr-xr-x  2 victoria victoria 4.0K Jul  3 01:22 393535837_773863_168DBBAA7F67E77B
-rw-r--r--  1 victoria victoria    0 Jul 22 18:05 flock.lock
drwxr-xr-x  2 victoria victoria 4.0K Jul 23 07:49 271456777_496895_16942F10D8D26D59
drwxr-xr-x  2 victoria victoria 4.0K Jul 31 19:28 98795464_172984_16942F10D8D9CFAC
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 00:08 15935216_28173_16942F10D8DADC48
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 05:11 5759860_10144_16942F10D8DAFD7C
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 11:05 2847666_5206_16942F10D8DB3527
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 12:25 908275_1551_16942F10D8DB4231
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:05 441943_734_16942F10D8DB4868
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:20 210867_356_16942F10D8DB4AD0
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:23 61035_83_16942F10D8DB4B4D
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:23 12_1_16942F10D8DB4B4E
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:24 11856_14_16942F10D8DB4B6A
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:24 3817_5_16942F10D8DB4B6D
drwxr-xr-x 17 victoria victoria 4.0K Aug  2 13:24 .
drwxr-xr-x  3 victoria victoria 4.0K Aug  2 13:24 tmp
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:24 txn
root@storagehost3:~# ls -larth /var/lib/victoriametrics/storage/prod_cluster_1/indexdb/168915F9B8364F72/15935216_28173_16942F10D8DADC48/
total 412M
-rw-r--r--  1 victoria victoria  42K Aug  2 00:08 metaindex.bin
-rw-r--r--  1 victoria victoria 4.3M Aug  2 00:08 index.bin
-rw-r--r--  1 victoria victoria 399M Aug  2 00:08 items.bin
-rw-r--r--  1 victoria victoria 9.6M Aug  2 00:08 lens.bin
-rw-r--r--  1 victoria victoria 1.2K Aug  2 00:08 metadata.json
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 00:08 .
drwxr-xr-x 17 victoria victoria 4.0K Aug  2 13:35 ..
```

We can see an entire chunk of index data is written at midnight on this host. Looking at another host:

```
root@use1-victoria-store-21:~# ls -larth /var/lib/victoriametrics/storage/prod_cluster_1/indexdb/1688E46289282AAD/
total 64K
-rw-r--r--  1 victoria victoria    2 Jun 15 23:12 converted-to-v1.28.0
drwxr-xr-x  5 victoria victoria 4.0K Jun 15 23:12 ..
-rw-r--r--  1 victoria victoria    0 Jul 15 14:53 flock.lock
drwxr-xr-x  2 victoria victoria 4.0K Jul 26 02:16 689871649_1311768_1691FE878A90C6D1
drwxr-xr-x  2 victoria victoria 4.0K Aug  1 13:59 76405850_132317_1691FE878A9677EA
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 00:11 9612877_18050_1691FE878A96D80B
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 10:31 5630517_10293_1691FE878A972AB8
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 12:14 1043272_1801_1691FE878A973B20
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:12 625123_1021_1691FE878A974439
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:40 336220_552_1691FE878A974891
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:41 230_1_1691FE878A9748AC
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:41 504_1_1691FE878A9748B9
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:41 24492_33_1691FE878A9748BC
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:41 107_1_1691FE878A9748C2
drwxr-xr-x  3 victoria victoria 4.0K Aug  2 13:41 tmp
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 13:41 txn
drwxr-xr-x 15 victoria victoria 4.0K Aug  2 13:41 .
root@use1-victoria-store-21:~# ls -larth /var/lib/victoriametrics/storage/prod_cluster_1/indexdb/1688E46289282AAD/9612877_18050_1691FE878A96D80B/
total 249M
-rw-r--r--  1 victoria victoria  24K Aug  2 00:10 metaindex.bin
-rw-r--r--  1 victoria victoria 2.6M Aug  2 00:10 index.bin
-rw-r--r--  1 victoria victoria 240M Aug  2 00:10 items.bin
-rw-r--r--  1 victoria victoria 6.3M Aug  2 00:10 lens.bin
-rw-r--r--  1 victoria victoria 1.1K Aug  2 00:10 metadata.json
drwxr-xr-x  2 victoria victoria 4.0K Aug  2 00:11 .
drwxr-xr-x 17 victoria victoria 4.0K Aug  2 13:41 ..
```

Another midnight write. But notice none of the other folders are created at the same time.

To me, this smells like something synchronizing once a week unintentionally and causing significant churn in the cluster.

**Comment by dima-vm** [comment]
Another solution idea: de-popupate index gradually.
E.g. evict series one-by-one during a period of 1 day.


Another idea is to keep a bloom filter of recently used series, and don't evict those (it's ok to have some small percentage of series not evicted).

**Comment by valyala** [comment]
The severity of this issue can be lowered by increasing the amounts of free CPU and disk IO resources at single-node VictoriaMetrics or at `vmstorage` nodes if [cluster version](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) is used.  See [capacity planning docs for single-node version](https://docs.victoriametrics.com/#capacity-planning) and [capacity planning docs for cluster version](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning). This will increase the performance of index population just after the index rotation, which, in turn, should decrease the duration of index population.

It is also recommended upgrading VictoriaMetrics to [the latest available](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since it contains improvements since v1.61.1, which should lower the severity of the issue.

**Comment by valyala** [comment]
The issue with the increased CPU and disk IO usage during indexdb rotation should be fixed starting from [VictoriaMetrics v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2177) for technical details.

Closing the issue as fixed.

**Comment by oronsh** [comment]
@valyala I know it may be naive and stupid but if this is actually happening because entries from previous index are not in the new rotated index, would it make sense to somehow copy the entries for the same day daily index into the new daily index before rotation? 
or the problem that entries are not found in global index after rotation?
I'm not very familiar with the index format, but maybe somehow something like this could be cheaply done:
before rotation:
1. copy all entries for the new day daily index (00:00 to 04:00) into the new rotated index with the per day prefix.
2. copy those entries but change the prefix to the global index also.

this way, almost all permutations would be found in the new rotated index.
if data in index is sorted, taking some byte range of the current per day index from previous db and copy it to the new one could be cheap?
but even if this sounds, I'm not sure how expensive it would be to add those entries to the new global index.
If I remember correctly from the code, the storage actually looks in the global index before inserting new data.

but again, maybe those spikes has nothing to do with it and I just got it all wrong :)

**Comment by valyala** [comment]
@oronsh , indeed, the problem with the increased CPU and disk IO usage just after the indexdb rotation wasn't completely fixed in the commit cf1a8bce6bfe725f3f363c8ad78d422b18141369 , so re-opening the issue again.

The proposed solution with copying the data for the last day from the previous indexdb to the newly created indexdb looks good. But it still may lead to CPU usage spike and disk IO spike needed for copying the data just after the indexdb rotation, even if taking the advantage of sorted data.

I think the way to go is to gradually pre-populate the new indexdb with the needed data in one hour just before indexdb rotation, so it will contain all the needed data at rotation time. cc'ing @f41gh7  , who proposed this solution.

**Comment by valyala** [comment]
FYI, the commit 544fba6826dff910b6e4ab6c5f696277c546f2b7 implements gradual population of the next indexdb when less than one hour remains to the next indexdb rotation. This should prevent from data ingestion slowdown just after the indexdb rotation. This also should remove spikes for CPU and disk IO during indexdb rotation. This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
The improvement mentioned at [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401#issuecomment-1646683409) has been included in [VictoriaMetrics v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). This should resolve the issue with CPU and RAM usage spikes during `indexdb` rotation.

Closing the issue as fixed. Feel free leaving comments and re-opening the issue if it still persists in v1.92.0 or newer releases.

**Comment by mmkkoo** [comment]
Sorry, I raised a new question in a closed question！
We have a primary and backup cluster in production, and the retention time of the backup cluster is 7 days; When we upgraded the version from 1.91 to 1.97, we found that the standby cluster had an hour of slow storage write when rolling the indexdb
The following are the performance indicators of vmstorage index preheating！！！
<img width="1400" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42405491/f9d64639-5cd5-4997-8c41-ade1c4a97670">
<img width="1389" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42405491/1f55118f-86cc-422d-bcc7-6fc9b7e80729">

The vmagent pending starts appearing at 11 o'clock and disappears at exactly 12 o'clock！！！
<img width="1409" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42405491/5a05d99c-505d-4302-823b-20a8c26f8ff4">

The send_duration of vminsert increased at 11 o'clock and decreased to normal water level at exactly 12 o'clock！！！
<img width="1411" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42405491/2d3b8187-6421-4517-bf09-0ded9ba62141">
How to avoid such problems？

**Comment by f41gh7** [comment]
It could be related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5959
