### ISSUE TITLE
support trace slow query

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#1403]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/3659110/123225121-fad85880-d504-11eb-987e-099b300462b7.png)

**Comment by valyala** [comment]
VictoriaMetrics supports query tracing at `/api/v1/query` and `/api/v1/query_range` endpoints starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - see [these docs](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#query-tracing). Closing the feature request as done.

**Comment by valyala** [comment]
FYI, the upcoming release will contain an UI for query tracing feature - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2703
