### ISSUE TITLE
How can a client connect multiple vmselect and multiple inserts

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/VictoriaMetrics#1406]
I use docker compose to install the clustered version of Victoria metrics. I use Victoria metrics through Prometheus. How to connect Prometheus and grafana when there are multiple vmselect and vminsert in the Victoria metrics cluster.

Here's how I can think of a connection

1. Use HTTP proxy such as nginx to proxy multiple vmselect or vminsert?

2. Prometheus and grafana fill in multiple vmselect or vminsert addresses?

**Comment by valyala** [comment]
@f41gh7 , @hagen1778 , could you help with these questions?

**Comment by hagen1778** [comment]
Hi @ktpktr0! The first option is preferable - put a proxy to balance connections for vminsert and vmselect components. Use balancer address for Prometheus remote_write config and for Grafana datasource config. The similar approach is described here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview.

What is the expected amount of metrics you're going to ingest into VM? How many Prometheis do you have? Could it be simpler to use single node installation?

**Comment by ktpktr0** [comment]
OK, thank you, then I can use haproxy + kept + VIP to achieve high availability, but the best solution is to use k8s deployment. Single node deployment is not very reliable in production environment

**Comment by xiaozongyang** [comment]
Hi @ktpktr0,
If you deploy vmselect in a single node deployment, did you considerate that deploy two single-node deployments for vmselect and define a k8s service for these two deployments? These two deployments provide same data but have different names, then you access the service for vmselect through ingress. In this case, every time one vmselect instance serves and there are high available.
