### ISSUE TITLE
Working of victoria metrics?

### ISSUE THREAD

**Issue by Roshmik236** [VictoriaMetrics/VictoriaMetrics#1407]
PLease explain the working of victoria metrics.

**Comment by valyala** [comment]
@Roshmik236 , could you add more details to the question?

**Comment by Roshmik236** [comment]
I want to integrate the kafka consuker with victoria metric using a spring boot application. Can u give me some idea of how to do it?

**Comment by valyala** [comment]
There are the following options exist:

* To use Telegraf for accepting data from Kafka and then sending to to VictoriaMetrics via [InfluxDB line protocol](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf). See [docs for Kafka consumer in Telegraf](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kafka_consumer)

* To write a custom Kafka consumer, which would read Kafka topics, transform and send the data in [one of the supported data ingestion protocols for VictoriaMetrics](https://docs.victoriametrics.com/#how-to-import-time-series-data).

* To use [vector.dev kafka consumer](https://vector.dev/docs/reference/configuration/sources/kafka/) for collecting the data from Kafka and then sending it to VictoriaMetrics via [Prometheus remote_write protocol](https://vector.dev/docs/reference/configuration/sinks/prometheus_remote_write/).

**Comment by valyala** [comment]
FYI, [vmagent](https://docs.victoriametrics.com/vmagent.html) gains the ability to read data from Kafka and to write data to Kafka starting from [v1.67.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [these docs](https://docs.victoriametrics.com/vmagent/#kafka-integration) for details.

Closing the issue as answered.
