### ISSUE TITLE
statsd parser exception

### ISSUE THREAD

**Issue by projekt01** [VictoriaMetrics/VictoriaMetrics#1409]
The statsd graphite parser is wrong. The parser needs a space between the metric key and value but the "StatsD Metrics Export Specification" description doesn't define a space. See: 
https://github.com/b/statsd_spec#counters
https://github.com/statsd/statsd/blob/master/docs/metric_types.md#multi-metric-packets
https://github.com/mojodna/metricsd#counters

The log says:
 cannot unmarshal Graphite line "stats.login.count:1.0|c": cannot find whitespace between metric and value in "stats.login.count:1.0|c"

The parser is located at:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6bc52fe41a7cf389606cb8e742f27d7b08f7a6c1/lib/protoparser/graphite/parser.go

The version is:
victoria-metrics-20210408-064138-tags-v1.58.0-0-gedd1590ac

Regards
Roger

**Comment by guidao** [comment]
You should aggregate the statsd format metrics into graphite format

**Comment by valyala** [comment]
VictoriaMetrics doesn't support incoming data in statsd format yet. There are plans to implement it soon - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/206 .

In the mean time it is recommended sending data to [statsd server](https://github.com/statsd/statsd), so it could push the data to VictoriaMetrics with Graphite protocol. See [these docs](https://docs.victoriametrics.com/#how-to-send-data-from-graphite-compatible-agents-such-as-statsd) for details.

Another solution is to push data to [statsd_exporter](https://github.com/prometheus/statsd_exporter) and then set up a single-node VictoriaMetrics or vmagent for scraping the `statsd_exporter`. See [these docs](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) for details on how to set up metrics scraping.

**Comment by valyala** [comment]
Closing the issue as answered.
