### ISSUE TITLE
на дашборде Cluster нет метрики bytes per point

### ISSUE THREAD

**Issue by proffust** [VictoriaMetrics/VictoriaMetrics#1412]
**Describe the bug**
в стандартном дашборде кластера https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/dashboards/victoriametrics.json на панели Datapoints нет метрики bytes-per-datapoint

**Expected behavior**
метрика есть на дашборде

**Screenshots**
![image](https://user-images.githubusercontent.com/33157540/123702223-8b979700-d86b-11eb-8282-74213fb62948.png)

**Comment by hagen1778** [comment]
Hi @proffust! It is missing there because panels shows cumulative value for multiple vmstorage instances. Cumulative form of display makes second Y axis less readable. Is it ok for you to use `Bytes per point` panel from the top of the dashboard instead?

**Comment by proffust** [comment]
ok
