### ISSUE TITLE
Include vmui component into single and vmselect binaries.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1413]
**Is your feature request related to a problem? Please describe.**
 It would be nice to have some ui for metrics visualization included into binary.

**Describe the solution you'd like**
Use go 1.16 embed feature https://golang.org/pkg/embed/ and include pre-built files into binaries. It should be exposed at `/ui` api.
  Pre-built files can be downloaded from github-releases page of vmui.
 Example code with embedded ui https://github.com/VictoriaMetrics/vmui/blob/master/packages/victoria-metrics-ui/web/main.go#L10

**Additional context**

There is no pre-built ui files. Need to add it into `vmui` repo first. Add zip step there https://github.com/VictoriaMetrics/vmui/blob/master/Makefile#L23

**Comment by TinySong** [comment]
is it in progress？ I would like finish this feature.

**Comment by f41gh7** [comment]
> is it in progress？ I would like finish this feature.

 Not, its not, help is welcome!

 I've added fresh static files archive to the releases page of vmui 
https://github.com/VictoriaMetrics/vmui/releases/download/v0.1.0/static.zip

  Need to create dir at `app/vmselect/ui`, extract content of static.zip to it

 And write something like:

```
diff --git a/app/vmselect/main.go b/app/vmselect/main.go
index c2d620421..0de4e0c40 100644
--- a/app/vmselect/main.go
+++ b/app/vmselect/main.go
@@ -1,6 +1,7 @@
 package vmselect
 
 import (
+       "embed"
        "errors"
        "flag"
        "fmt"
@@ -77,6 +78,12 @@ var (
        })
 )
 
+// static content
+//go:embed ui
+var files embed.FS
+
 // RequestHandler handles remote read API requests for Prometheus
 func RequestHandler(w http.ResponseWriter, r *http.Request) bool {
        startTime := time.Now()
@@ -135,6 +142,12 @@ func RequestHandler(w http.ResponseWriter, r *http.Request) bool {
                return true
        }
 
+       // ui access.
+       if strings.HasPrefix(path, "/ui") {
+               http.FileServer(http.FS(files)).ServeHTTP(w, r)
+               return true
+       }
+
```

**Comment by TinySong** [comment]
thanks for your advice, work on it.

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4

**Comment by valyala** [comment]
The [vmui component](https://github.com/VictoriaMetrics/vmui) has been added into a single-node VictoriaMetrics and into `vmselect` component. It is available at `/ui` page. The static source files at `app/vmselect/ui` directory can be updated with `make vmui-update` command.

Next steps:
* Automatically fill `Server URL` field when navigating to `/ui` page.
* Move [vmui](https://github.com/VictoriaMetrics/vmui) source code to github.com/VictoriaMetrics/VictoriaMetrics 
* Improve `vmui` usability

**Comment by valyala** [comment]
The web ui page for cluster version of VictoriaMetrics has been moved from `/ui` to `/select/<accountID>/prometheus/ui`, so the web UI could automatically determine per-tenant datasource url from the referrer.

**Comment by valyala** [comment]
The `vmui` source code has been moved from https://github.com/VictoriaMetrics/vmui to https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui . The `vmui` page path suffix has been updated from `/ui` to `/vmui`:

* `http://victoriametrics:8428/vmui/` for single-node VictoriaMetrics.
* `http://vmselect:8481/select/<accountID>/prometheus/vmui/` for cluster version of VictoriaMetrics.

**Comment by valyala** [comment]
Now the vmui is exposed at `http://vmselect:8481/select/<accountID>/vmui`, e.g. the `/prometheus/` part has been removed from the url, since the vmui shouldn't be limited to Prometheus API in the future.

**Comment by TinySong** [comment]
awesome

**Comment by valyala** [comment]
The vmui has been integrated into victoriametrics starting from [v1.63.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It is available at the following urls:

* at `http://victoriametrics:8428/vmui/` for single-node VictoriaMetrics
* at `http://vmselect:8481/select/<accountID>/vmui/` for cluster version of VictoriaMetrics

Closing this issue as done.
