### ISSUE TITLE
An error occurred during the run

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1414]
panic: FATAL: cannot open file "/store/data/big/2021_05/6350890474_2056939_20210520040303.012_20210525132041.141_1680B2D4ABC26430/timestamps.bin" for reading: open /store/data/big/2021_05/6350890474_2056939_20210520040303.012_20210525132041.141_1680B2D4ABC26430/timestamps.bin: no such file or directory

**Comment by WuJingLearn** [comment]
This error also occurs when restarting POD,

**Comment by hagen1778** [comment]
Hi @WuJingLearn! Can you check if requested file exists? If not, do you know what could have removed it? Is the filesystem stable and there is no disk corruption? Is only this VM process has access to data folder? Could it have been overwritten by any other process?

**Comment by WuJingLearn** [comment]
The file does not exist. No other process has access to the file。How can this be fixed

**Comment by hagen1778** [comment]
What kind of filesystem do you use for storage and what version of VM?

**Comment by WuJingLearn** [comment]
The version I'm using is 1.56, I'll try upgrading it later

**Comment by WuJingLearn** [comment]
I upgraded the version to v1.60.0-cluster, but the container still couldn't start, so I deleted the entire /store directory to start it

**Comment by hagen1778** [comment]
Ok, thanks for letting me know. I'm interested into digging into the issue more. Please, let me know if this happens again. Thanks!

**Comment by hagen1778** [comment]
Closing as inactive.
