### ISSUE TITLE
Upgrade vm cluster from 1.60.0 to 1.62.0 increases memory and cpu usage for storage nodes.

### ISSUE THREAD

**Issue by zbindenren** [VictoriaMetrics/VictoriaMetrics#1416]
I updated our cluster from 1.60.0 to 1.62.0. Since then the cluster is practically unusable. See [slack thread](https://app.slack.com/client/TH86JGEEN/CGZF1H6L9). 

My question: is it possible to downgrade the cluster again to 1.60.0?

Answer: yes

**Comment by johnseekins** [comment]
This may be related to #1401. I've seen similar problems in my cluster, although not immediately after upgrade.

**Comment by zbindenren** [comment]
@johnseekins what leads you to this conclusion?

**Comment by johnseekins** [comment]
Two things:
1. I saw similar load/rerouting spikes when this happened to me
2. @valyala suggested my problem may be related to #1401 

I can't say for sure it's related, but it may be. This may also be something completely different. I'd wonder what type of ingest rate your cluster has. As an example, my cluster is consuming ~750k points/sec.

**Comment by zbindenren** [comment]
We *had* around 2Mio points/sec:

![image](https://user-images.githubusercontent.com/1607088/123812452-63a04600-d8f4-11eb-839f-ef558bb04cb9.png)

Then we lost a lot of datapoints.... And now it is oscillating.

I am downgrading to 1.60.0 and hoping 🤞 that it will work again.

**Comment by zbindenren** [comment]
I downgraded to 1.60.0 and cluster works again and I have a current ingestion rate of 10Mio points/sec 😮. problably agents resending datapoints....:

![image](https://user-images.githubusercontent.com/1607088/123817009-12925100-d8f8-11eb-833c-50e1bcada2f2.png)

**Comment by zbindenren** [comment]
The new version uses also more memory and cpu for the storage nodes:

![image](https://user-images.githubusercontent.com/1607088/123818720-82eda200-d8f9-11eb-812f-5153a46aeb87.png)
![image](https://user-images.githubusercontent.com/1607088/123819172-dcee6780-d8f9-11eb-9a85-90294465f14d.png)

**Comment by f41gh7** [comment]
Can you share CPU and Memory pprof collected from 1.62.0 version of `vmstorage` nodes? 

 This behavior is unexpected.

 @valyala

**Comment by zbindenren** [comment]
Unfortunatelly I have no memory or cpu dump :-(

**Comment by valyala** [comment]
@zbindenren , could you build `vmstorage` from the commit 71c856beb88c06b338ce4720368eb9d30fed0197 and verify whether this helps reducing memory usage for your case? See [build instructions for cluster components of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources). There is no need in re-building other components of the cluster.

**Comment by valyala** [comment]
The related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1338

**Comment by valyala** [comment]
It would be great also if memory and cpu profiles could be collected (and shared here) from `vmstorage` `v1.62.0` and from `vmstorage` built from the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/71c856beb88c06b338ce4720368eb9d30fed0197 according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#profiling). The profiles must be collected after 5-10 minutes after the start when `vmstorage` enters steady state.

**Comment by valyala** [comment]
@zbindenren , could you upgrade all the cluster components to the Docker tag `heads-public-cluster-0-ga12c6a52c` and check whether this helps reducing memory usage at `vmstorage` nodes? It is safe performing the upgrade to this tag and downgrade to `v1.60.0-cluster` tag.

You can upgrade only a single `vmstorage` node to the tag `heads-public-cluster-0-ga12c6a52c`, while leaving the remaining `vmstorage` nodes and other cluster components at `v1.60.0-cluster` tag. The cluster should work without issues, while you could compare memory usage of the new version of `vmstorage` node with the old version of `vmstorage` node. While at it, it would be great if you could collect and share memory profile from the new version of `vmstorage` node. See [how to collect memory profile from vmstorage node](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#profiling). It is safe sharing the memory profile here, since it doesn't contain any sensitive information - it contains only the memory allocation stats associated with VictoriaMetrics source code. It doesn't contain any user data.

**Comment by zbindenren** [comment]
> @zbindenren , could you upgrade all the cluster components to the Docker tag `heads-public-cluster-0-ga12c6a52c` and check whether this helps reducing memory usage at `vmstorage` nodes? It is safe performing the upgrade to this tag and downgrade to `v1.60.0-cluster` tag.
> 
> You can upgrade only a single `vmstorage` node to the tag `heads-public-cluster-0-ga12c6a52c`, while leaving the remaining `vmstorage` nodes and other cluster components at `v1.60.0-cluster` tag. The cluster should work without issues, while you could compare memory usage of the new version of `vmstorage` node with the old version of `vmstorage` node. While at it, it would be great if you could collect and share memory profile from the new version of `vmstorage` node. See [how to collect memory profile from vmstorage node](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#profiling). It is safe sharing the memory profile here, since it doesn't contain any sensitive information - it contains only the memory allocation stats associated with VictoriaMetrics source code. It doesn't contain any user data. The provided memory profile will help identifying and fixing memory hogs for your workload.

I try to do that today when I have a spare minute.

**Comment by zbindenren** [comment]
It looks much better now:

![image](https://user-images.githubusercontent.com/1607088/124566847-b70a1b00-de43-11eb-87a5-bbf653a5c751.png)
![image](https://user-images.githubusercontent.com/1607088/124566977-d2752600-de43-11eb-84d3-0b76aa486020.png)
![image](https://user-images.githubusercontent.com/1607088/124567045-e6b92300-de43-11eb-8143-c40822ab87f2.png)
![image](https://user-images.githubusercontent.com/1607088/124567185-110ae080-de44-11eb-85ee-86ae46590c27.png)


Profiles:

[profiles.tar.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6768516/profiles.tar.gz)
