### ISSUE TITLE
vmstorage use all available memory 

### ISSUE THREAD

**Issue by NikolayShama** [VictoriaMetrics/VictoriaMetrics#142]
I am using the clustered version of Victoria Metrics and noticed that vmstorage uses all available memory. Is it possible to limit the use of memory and will it affect performance?
![image](https://user-images.githubusercontent.com/45375448/62527606-1ddfbd80-b844-11e9-901f-9fddfd7e6562.png)

**Comment by valyala** [comment]
All the VictoriaMetrics cluster services - `vmstorage`, `vminsert` and `vmselect` - have `-memory.allowedPercent` command-line flag, which can be used for limiting memory usage for particular service. By default it is set to 60 - this means that the service can use up to 60% of the available RAM for various caches. It is expected that the service eventually will use `-memory.allowedPercent` percents of RAM. The service can use additional memory for various temporary data structures. Try reducing `-memory.allowedPercent` for `vmstorage` service and see whether this works for you.

**Comment by NikolayShama** [comment]
@valyala thanks a lot for the fast answer. In your opinion, is it worth limiting the use of memory? It will not affect performance? Perhaps there are recommended options?

**Comment by valyala** [comment]
Default value for `-memory.allowedPercent` should work well for most cases. It isn't recommended increasing this value beyond 60%, since this can lead to higher disk IO and slower performance. The value can be safely decreased if you have small number of active time series comparing to the maximum allowed RAM size for caches. Each million of active time series requires ~1GB of caches. Your workload has 800k active time series, so it should work with 1GB maximum allowed cache size.
Too small cache size (when active time series info doesnt fit the cache) will result in high CPU usage.

**Comment by NikolayShama** [comment]
TY for the answer. Based on the metrics in the screenshot, can you tell me why the memory consumption has increased?

**Comment by valyala** [comment]
> Based on the metrics in the screenshot, can you tell me why the memory consumption has increased? The number of metrics has not changed.

Caches continue growing to `-memory.allowedPercent` regardless of the number of active time series. Cached entries have no expiration time. They are evicted from the cache only if it reaches the maximum size derived from `-memory.allowedPercent`. So it is OK if cache sizes grow to `-memory.allowedPercent` percent of the RAM. 

`Disk space usage (index)` graph on the screenshot shows that the number of time series is continuously growing over time. It looks like your workload has constant number of active time series, but these time series are continuously substituted by new time series, i.e. there is non-zero time series churn rate. You can inspect the total number of time series by navigating `/api/v1/series/count` page. VictoriaMetrics scans all the index when navigating to the page, so it isn't recommended querying the page frequently. It is better to look at `disk space usage (index)` graph or at `vm_rows{type="indexdb"}` metric on the `/metrics` page. This metric shows the number of entries in the inverted index. This number is proportional to the total number of time series.

**Comment by valyala** [comment]
@NikolayShama , VictoriaMetrics should use less RAM in the face of non-zero time series churn rate starting from [v1.25.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Could you try this release?

**Comment by NikolayShama** [comment]
Thanks for the detailed answer, I will try to update VictoriaMetrics soon and write about the results

**Comment by valyala** [comment]
> Do you plan to do replication between nodes?

There are plans, but there is no hard deadline on when the replication will be implemented. The recommended approach is to store data on durable replicated disks such as [GCE disks](https://cloud.google.com/compute/docs/disks/#pdspecs). See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/32#issuecomment-495908458 and https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#replication-and-data-safety for more info.

**Comment by langecode** [comment]
One comment on the memory percentage. We are running VictoriaMetrics in a Kubernetes cluster setup (Azure managed Kubernetes). It seems that the 60% here will be 60% of the memory of the node. To be able to set sensible resource limits on the PODs it could be very nice if it was possible to set an absolute value instead.

**Comment by valyala** [comment]
@langecode , you can set absolute memory limits for pods in Kubernets - see https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory . VictoriaMetrics respects these limits.

**Comment by langecode** [comment]
Great - I will test this out. I do have a limit but it is reverse engineered from what VictoriaMetrics was grapping (which is, by default, 60% of the available memory on the node). I will try decreasing the memory allocation to see what happens.

**Comment by valyala** [comment]
File a separate issue if VictoriaMetrics doesn't respect memory limit set in Kubernetes pod.

**Comment by valyala** [comment]
I'm closing this issue as fixed. VictoriaMetrics should reclaim unused memory starting from `v1.25.0`. If this isn't the case, then feel free re-opening the issue.

**Comment by marquiswashere** [comment]
Please forgive me if I'm misunderstanding, for kubernetes deployments `-memory.allowedPercent` should cap at X percentage of the pod's memory limit?

For our new production deployment of `vmcluster` we're seeing:

```
vmstorage:
    Container ID:  docker://ae8b4792a420fb303044d81b80c03b7e90add1296db5143fddf0710cf67cb458
    Image:         victoriametrics/vmstorage:v1.74.0-cluster
    Image ID:      docker-pullable://victoriametrics/vmstorage@...
    Ports:         8482/TCP, 8400/TCP, 8401/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      -dedup.minScrapeInterval=1ms
      -httpListenAddr=:8482
      -memory.allowedPercent=45.0
      -retentionPeriod=2w
      -search.maxUniqueTimeseries=6000000
      -storageDataPath=/vm-data
      -vminsertAddr=:8400
      -vmselectAddr=:8401
    State:          Running
      Started:      Wed, 30 Mar 2022 17:49:57 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     4
      memory:  10Gi
```
```
kubectl top pod vmstorage-{app-name}-victoria-metrics-0
NAME                                      CPU(cores)   MEMORY(bytes)   
vmstorage-{app-name}-victoria-metrics-0   377m         7088Mi 
```

**Comment by valyala** [comment]
> Please forgive me if I'm misunderstanding, for kubernetes deployments `-memory.allowedPercent` should cap at X percentage of the pod's memory limit?
> 
> For our new production deployment of `vmcluster` we're seeing:
> 
> ```
> vmstorage:
>     Container ID:  docker://ae8b4792a420fb303044d81b80c03b7e90add1296db5143fddf0710cf67cb458
>     Image:         victoriametrics/vmstorage:v1.74.0-cluster
>     Image ID:      docker-pullable://victoriametrics/vmstorage@...
>     Ports:         8482/TCP, 8400/TCP, 8401/TCP
>     Host Ports:    0/TCP, 0/TCP, 0/TCP
>     Args:
>       -dedup.minScrapeInterval=1ms
>       -httpListenAddr=:8482
>       -memory.allowedPercent=45.0
>       -retentionPeriod=2w
>       -search.maxUniqueTimeseries=6000000
>       -storageDataPath=/vm-data
>       -vminsertAddr=:8400
>       -vmselectAddr=:8401
>     State:          Running
>       Started:      Wed, 30 Mar 2022 17:49:57 -0400
>     Ready:          True
>     Restart Count:  0
>     Limits:
>       cpu:     4
>       memory:  10Gi
> ```
> 
> ```
> kubectl top pod vmstorage-{app-name}-victoria-metrics-0
> NAME                                      CPU(cores)   MEMORY(bytes)   
> vmstorage-{app-name}-victoria-metrics-0   377m         7088Mi 
> ```

The `-memory.allowedPercent` command-line flag doesn't limit the overall memory usage of vmstorage or any other VictoriaMetrics component. It limits the maximum size of in-memory caches used by these components. The components can use additional memory (for example, every query takes additional memory for temporary data structures needed during the query execution), and it isn't limited by the `-memory.allowedPercent`.
