### ISSUE TITLE
Can multiple directories be configured with the storagedatapath option

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/VictoriaMetrics#1425]
I use docker swarm to create the vmstorage service. I create multiple copies for it on the same node, but a directory can only be mounted by one. Therefore, can multiple data directories be configured

**Comment by valyala** [comment]
@f41gh7 , could you help with this question?

**Comment by f41gh7** [comment]
As far, as i know, docker doesn't support it.

 You can create separate service for each vmstorage, for example
```yaml
services:
  vmstorage-0: ...
  vmstorage-1:...
```

**Comment by f41gh7** [comment]
complete example: https://gist.github.com/f41gh7/56ed4a10d455a9a66b44f28e36c268f6

**Comment by ktpktr0** [comment]
Thank you. What I want to try is high availability。
