### ISSUE TITLE
A trival question about the `lib/storage/dedup.go` implementation

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/VictoriaMetrics#1426]
Hi, I read the `lib/storage/dedup.go` code and found the implementation is a bit different from what I have expected from the doc:
```
-dedup.minScrapeInterval duration
    	Remove superflouos samples from time series if they are located closer to each other than this duration. 
```

I add a test case in `lib/storage/dedup_test.go/TestDeduplicateSamples`：
`f(10*time.Millisecond, []int64{102, 109, 111, 121, 125, 131}, []int64{102, 111, 121, 131})`
It passed. But I have thought the 111 should be dropped because 111-102<10.

Did I misunderstand the meaning of deduplication here?

**Comment by valyala** [comment]
The documentation for `-dedup.minScrapeInterval` command-line flag wasn't very clear. I tried improving the docs in the commit f6bb13089856ccfd77609662c6116a73723f6b3c .

Basically, for `-dedup.minScrapeInterval=d` VictoriaMetrics splits the time range into discrete time buckets with `d` duration and leaves only the first sample per each such bucket. See https://docs.victoriametrics.com/#deduplication . For example, if `-dedup.minScrapeInterval=10s`, then the buckets for the test case above have the following boundaries:

```
* [100 ... 110) - 102 is left, while 109 is removed
* [110 ... 120) - 111 is left
* [120 ... 130) - 121 is left, while 125 is removed
* [130 ... 140) - 131 is left
```

**Comment by chenlujjj** [comment]
Thank you for the quick response, now I understand it.
