### ISSUE TITLE
Why memoryPercent does not work

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#1437]
**Describe the bug**
VERSION=1.47.0-cluster
I set -memory.allowedPercent=20 in vmselect
the vmselect -memory.allowedPercent=20 does not work.
the whole host memory is 192GB, but the vmselect use more than 60GB sys. it should be 192 * 20% = 38.4GB

![image](https://user-images.githubusercontent.com/6347394/124763489-9a1a3880-df66-11eb-9a99-2cac052afae1.png)

![image](https://user-images.githubusercontent.com/6347394/124763517-a1414680-df66-11eb-973a-43ab8ea5e35f.png)

@valyala

**Comment by hagen1778** [comment]
Hi @davidsome! Flag `memory.allowedPercent` limits memory usage dedicated to various caches created/used by VM. It does not limit additional memory, which may be needed for processing incoming queries. Please see more details here https://docs.victoriametrics.com/FAQ.html?highlight=memory.allowedPercent#how-to-set-a-memory-limit-for-victoriametrics-components

Also, metric `go_memstats_heap_sys_bytes`  does not reflect the real usage of the memory by process. Please track `process_resident_memory_anon_bytes` metric to understand the actual memory usage. Memory usage also reflected in [VM Grafana dashboards](https://grafana.com/orgs/victoriametrics/dashboards) in `Resource usage` row with some explanations.

**Comment by nemobis** [comment]
Dupe https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1427

**Comment by hagen1778** [comment]
Closing as duplicate https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1427
