### ISSUE TITLE
vm-operator

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1439]
Can I use tag selectors like Prometheus-operator for vm-operator's podScrape auto-discovery?
Not this one down here

ports:
  - containerPort: 8080
    name: web
    protocol: TCP

**Comment by f41gh7** [comment]
Hello, yes, `VMServiceScrape` - has almost the same api, as `ServiceMonitor`, `VMPodScrape` the same as `PodMonitor`.  Related api docs for vmservicescrape.spec.endpoints:  https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#endpoint

**Comment by valyala** [comment]
VictoriaMetrics operator docs have been moved to https://docs.victoriametrics.com/operator/ , so the correct url now is https://docs.victoriametrics.com/operator/api/#endpoint

Closing the question as answered.
