### ISSUE TITLE
VictoriaMetrics cannot be built on CentOS 6 starting from v1.23.0

### ISSUE THREAD

**Issue by cite** [VictoriaMetrics/VictoriaMetrics#144]
**Describe the bug**
Binary releases since 1.23.0 don't start on default CentOS 6 kernels anymore:

```
# /var/tmp/victoria-metrics-prod.1.23.0
FATAL: kernel too old
Aborted
# uname -a
Linux carbon-1 2.6.32-754.15.3.el6.x86_64 #1 SMP Tue Jun 18 16:25:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Version**
```
victoria-metrics-20190725-211853-tags-v1.23.0-0-g89eb6d78
```

**Additional context**
I assume the builder used since 1.23.0 has a libc that doesn't support older kernels anymore. Since CentOS 6 (well, RHEL 6, really) is only EOL next year it would be great if you could re-add support for this.

**Comment by valyala** [comment]
v1.23.0 switched Docker image for Go builder from go1.12.6 to go1.12.7. It looks like the new builder removed support for RHEL 6

**Comment by valyala** [comment]
It would be great if somebody familiar with CentOS 6 could help with this issue if it is still relevant.

**Comment by Karsonito** [comment]
Still no proggess?
The problem appears in openvz containers with centos 7, while host os is centos 6
Though prometheus runs without any problems

**Comment by valyala** [comment]
There was no progress on the issue :( Probably, it is better to upgrade to newer CentOS version or switch to another Linux distributive?

**Comment by Karsonito** [comment]
Of course it's better. But this is a production server. Too many containers. Centos 6 will be supported until November 30, 2020.

**Comment by f41gh7** [comment]
Hello, was you able to solve this issue? I suppose, its needed to build pure version of vmdb without CGO support.

**Comment by valyala** [comment]
See docs about pure Go builds - https://docs.victoriametrics.com/#pure-go-build-cgo_enabled0

**Comment by valyala** [comment]
Closing this issue as outdated. I assume CentOS 6 isn't widely used now :)
