### ISSUE TITLE
Last value in graph is wrong (query_range/maxStepForPointsAdjustment)

### ISSUE THREAD

**Issue by mxsiegle** [VictoriaMetrics/VictoriaMetrics#1442]
Hey,

I noticed that all of our graphs in Grafana have a drop in their value for the last datapoint. It looks like this:

![image](https://user-images.githubusercontent.com/81744122/125052068-def7b980-e0a3-11eb-8ce6-d7677fbf9823.png)

This only affects range queries (/api/query_range); instant values are calculated correctly. The actual metric values are correct as well, i.e. if you wait a moment until new data arrives, the datapoint which had issues suddenly reports the correct value while the new one is wrong. You can repeat that indefinitely, it's always the latest datapoint that is wrong.

While troubleshooting, I made the following observations:

1)
Sometimes the values are reported correctly, other times they are not. This is how it looks like when I refresh the table a couple of times. Note the last entry on the bottom right:

![2021-07-09_10-44-10](https://user-images.githubusercontent.com/81744122/125052667-8248ce80-e0a4-11eb-8dc1-abbfe29aaa5f.gif)

When I run VMSelect with `-search.disableCache` the wrong value appears 100% of the time. So somehow the cache affects the value and sometimes reports it correctly.

2)
The issue only appears when a time range is selected with a step value higher than the max. adjusted time set by `-search.maxStepForPointsAdjustment`.
The default value is 1m0s. When I selected 'Last 6 hours' my step value in Grafana becomes 20s and the correct value is reported:

![image](https://user-images.githubusercontent.com/81744122/125053197-1dda3f00-e0a5-11eb-8bf0-44a4c3f2ab39.png)

When I change it to 'Last 7 days' it has 5m steps and then the issue is there:

![image](https://user-images.githubusercontent.com/81744122/125053268-35192c80-e0a5-11eb-9beb-23f9d230f16c.png)

If I set `-search.maxStepForPointsAdjustment` to e.g. 6m, the issue will disappear for 'Last 7 days' but it will re-appear of course as soon as the step value is bigger than that (e.g. 'Last 30 days' -> 30m steps).
Can anyone tell me why this is happening and how I can fix it?

Setup: Cluster with 4x VMStorage, 4x VMSelect and 3x VMInsert.
Version: v1.62.0
Retention: 90d
Scrape interval: 20s (VMAgent)

It does not matter which metric I choose or which target, all of them have that issue. Weirdly, recordings are totally fine. I assume it's because they are using the (correct) instant values but for some reason their last values are reported correctly in the graphs/tables.

I only noticed this behavior recently. Before, we had updated to v1.62.0 so I thought maybe it's that, but a rollback to v1.59.0 and v1.55.1 didn't make any difference (those were the versions we were running before).

Thanks in advance.

**Comment by valyala** [comment]
This may be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526

**Comment by valyala** [comment]
FYI, VictoriaMetrics and vmagent gained support for Prometheus staleness markers starting from [the release v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if the problem still exists.
