### ISSUE TITLE
Support Prometheus duration for rule group intervals in vmalert configuration

### ISSUE THREAD

**Issue by leizhag** [VictoriaMetrics/VictoriaMetrics#1444]
**Is your feature request related to a problem? Please describe.**
When I was migrating to `vmalert` from Prometheus, I got errors like:
```plain
2021-07-12TxxxZ	error	VictoriaMetrics/app/vmalert/main.go:95	error while reloading rules: cannot parse configuration file: errors(1): failed to parse file "xxx.yml": yaml: unmarshal errors:
  line 67: cannot unmarshal !!str `7d` into time.Duration
```

WIth rule file like:
```yaml
groups:
- name: xxx
  interval: 7d
  rules:
  - xxx
```

**Describe the solution you'd like**
Use [`PromValue`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a684408e27ccda469637830a681f3fe2426b8a24/app/vmalert/config/config.go#L135-L135) for [`Group.Interval`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a684408e27ccda469637830a681f3fe2426b8a24/app/vmalert/config/config.go#L29-L29), which seems compatible with [Prometheus duration configuration](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file).

**Comment by valyala** [comment]
@leizhag , could you build `vmalert` from the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/bfba4c28a4833e64d2b097c3b244c9f15dd3c476 and verify whether it accepts Prometheus-compatible durations in `interval` config option? See [build instructions for vmalert](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources).

**Comment by valyala** [comment]
`vmalert` should accept Prometheus-compatible durations in `interval` config option starting from [v1.63.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by leizhag** [comment]
> @leizhag , could you build `vmalert` from the commit [bfba4c2](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/bfba4c28a4833e64d2b097c3b244c9f15dd3c476) and verify whether it accepts Prometheus-compatible durations in `interval` config option? See [build instructions for vmalert](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources).

It works. Thanks for rolling out a solution so fast. `vmalert` is working great as a drop-in replacement of Prometheus rule manager for us.
