### ISSUE TITLE
Bug in grafana rev. 5 dashboard for vmagent

### ISSUE THREAD

**Issue by corporate-gadfly** [VictoriaMetrics/VictoriaMetrics#1448]
**Describe the bug**
[Grafana dashboard](https://grafana.com/grafana/dashboards/12683) shows a query error for several of the panels.

PromQL query:
```
buckets_limit(12, prometheus_buckets(sum(rate(vmagent_remotewrite_block_size_rows_bucket{job=~"gems-mgmt-vmagent", instance=~".*"}[$__interval])) by(vmrange)))
```
Query error:
```
"invalid parameter \"query\": 1:19: parse error: unknown function with name \"prometheus_buckets\""
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1200537/125506888-0b6ac38f-f829-4f99-842d-cd46bb33bfbf.png)

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20210625-103156-tags-v1.62.0-0-g008033a37
```
```
# grafana-server -v
Version 8.0.5 (commit: cbb2aa5001, branch: HEAD)
```

**Comment by hagen1778** [comment]
Hi! The query on this dashboard uses [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) syntax and can be executed only against VM datasource. The reason is that vmagent uses custom [histogram type](https://pkg.go.dev/github.com/VictoriaMetrics/metrics#Histogram) from VM [metrics package](https://github.com/VictoriaMetrics/metrics).

**Comment by corporate-gadfly** [comment]
@hagen1778: I am using [promxy](https://github.com/jacksontj/promxy) in front of VictoriaMetrics. Once I changed source to VictoriaMetrics, the error went away.

Is it worth filing a bug with promxy? What would I say in the bug?

**Comment by hagen1778** [comment]
There is a feature request for Promxy to support MetricsQL - https://github.com/jacksontj/promxy/issues/253

**Comment by corporate-gadfly** [comment]
TY, closing.
