### ISSUE TITLE
Multiple fields support feature

### ISSUE THREAD

**Issue by sundy-li** [VictoriaMetrics/VictoriaMetrics#145]
Hi, will it have a plan to support multiple fields?

**Comment by hagen1778** [comment]
Hi @sundy-li!
What exactly do you mean? Please, can you be more specific and provide some example?

**Comment by sundy-li** [comment]
I don't think OpenTSDB-like schema is a good schema for time-series data. 
Because it only supports one field named `value` in one log.
I want this, just as `Influxdb` or `lindb` did.

```
timestamp, metric, tags[tag1,tag2,tag3] ,  fields[field1, field2]
```
If I use ClickHouse or timescaledb, I could build tables to store this data, but it's not schema-free.

**Comment by valyala** [comment]
VictoriaMetrics supports [data ingestion with Influx line protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf), where multiple field values may be passed in a single line.

**Comment by valyala** [comment]
Closing the issue as resolved, since VictoriaMetrics accepts multiple fields via Influx line protocol.
@sundy-li , feel free re-opening the issue if you have additional questions.

**Comment by micw** [comment]
Hello,
I found this issue when searching exactly for this feature. Unfortunately, the suggested solution is not valid. While the ingestion indeed supports multiple fields, the underlying database does not. The doc states:

```
For example, the following Influx line:

foo,tag1=value1,tag2=value2 field1=12,field2=40
is converted into the following Prometheus data points:

foo_field1{tag1="value1", tag2="value2"} 12
foo_field2{tag1="value1", tag2="value2"} 40
```

Would you re-open the issue until a solution (or a Won't-Fix decision) is available?

**Comment by valyala** [comment]
@micw , I'm afraid I don't understand your request. What do you mean under `the underlying database does not support multiple fields`?

**Comment by micw** [comment]
On influx, if I add a dataset that contains a timestamp and two fields, all is stored together. On VM instead, each field is stored separately. So on influx I can query and get the whole data together while on VM I get two separate entries that are not releated to each other.
Or in other words, influx allows multiple columns while VM has only one. So the suggested solution here does not actually fix the issue. (if it's really an issue and not a non-goal).
