### ISSUE TITLE
vmauth doesnot works after adding extra-label

### ISSUE THREAD

**Issue by eleleme** [VictoriaMetrics/VictoriaMetrics#1450]
vmauth doesnot works after adding extra-label, however it works fine when deleting this extra-label flag in auth.confi.yaml

http://localhost:8428?extra_label=team=dev

- username: "local-single-node"
  password: "***"
  url_prefix: "http://localhost:8428?extra_label=team=dev"

<h2>Single-node VictoriaMetrics.</h2></br>See docs at <a
	href='https://victoriametrics.github.io/'>https://victoriametrics.github.io/</a></br>Useful endpoints: </br><a
	href='/targets'>"/targets"</a> - discovered targets list<br/><a href='/api/v1/targets'>"/api/v1/targets"</a> -
advanced information about discovered targets in JSON format<br/><a href='/metrics'>"/metrics"</a> - available service
metrics<br/><a href='/api/v1/status/tsdb'>"/api/v1/status/tsdb"</a> - tsdb status page<br/>

**Comment by hagen1778** [comment]
Hi @eleleme! Could you please define what exactly does not work? Can you also ensure that label pair `team=dev` exists in your metrics?

**Comment by eleleme** [comment]
After change the version of vmauth from 1.58 to 1.62 it works with extra_label now. 
Thanks @hagen1778
