### ISSUE TITLE
vmalert didnot send alert as expected

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/VictoriaMetrics#1452]
**Describe the bug**

We use vmalert to evaluate alert rules and send alert to alertmanager, it works fine. However, today I found that it didnot send alert as expected.

1. the alert rule graph:

![9b0dd170-097e-4e53-b3ab-74f43aa6ebf2](https://user-images.githubusercontent.com/17081528/125595545-73338da6-d488-44f4-b6cc-d4c1b20ebeb1.png)

Since the threshold is `< 1`, it should have sent alert after 05:30.

2. the ALERTS graph

![_bfa11e0f-84ef-46e8-bf7e-494df0af3798](https://user-images.githubusercontent.com/17081528/125595883-2d45ca1a-e645-4be9-8f0d-be2d396ce127.png)

(the `alertstate` label is `firing`)

But it didn't.

The vmalert version is `vmalert-20210524-130629-tags-v1.60.0-0-g08234aa7a`.

I'm not quite sure if it's a bug. Could you please provide some suggestions help to debug and solve this problem? 

Thanks.

**Comment by hagen1778** [comment]
Hi @chenlujjj! vmalert provides some metrics which might be useful for debug:
`vmalert_alerts_firing{alertname=%q, group=%q, id="%d"}` - is 1 if this specific alert is firing
`vmalert_alerts_sent_total` - shows how many notifications vmalert tried to send to Alertmanager (you can check if there was increase at that moment)
`vmalert_alerts_send_errors_total` - shows total number of errors during attempts to send something to Alertmanager (every faulty attempt is also logged so you might want to check the logs)

Please, check if there were any errors in attempt to send data to Alertmanager from vmalert's side.

The second screenshot you provided says that vmalert did send the notification (if there are no errors in logs). The first screenshot says metric has value 1 and then 0 all the time, but I suspect it just disappeared and Grafana plotted null as zero. That could be the reason why lifetime of active alert was so short.

**Comment by chenlujjj** [comment]
vmalert_alerts_send_errors_total, no errors

**Comment by chenlujjj** [comment]
@hagen1778 Thank you for the reply!

**Comment by hagen1778** [comment]
Thanks for the screenshots! Could you please provide alerting rule definition (obfuscated if you want)?

**Comment by chenlujjj** [comment]
The alert rule expression is :
`(count by(app, task, target, name) (http_probe_success_rate{app="xxx",task="yyy",target="http://10.10.10.10:9000"} == 1) or on() vector(0)) / count by(app, task, target, name) (http_probe_success_rate{app="xxx",task="yyy",target="http://10.10.10.10:9000"})`

We have multiple host distributed in several datacenters probing the target periodically. The alert rule aims to send alert when not all hosts probe successfully.

**Comment by hagen1778** [comment]
Thanks! I've tried to reproduce the issue, but no luck. Does it happen to other alerting rules with `<1` condition? Is vmalert configured with the same datasource.URL as Grafana?
Is it possible to get the exported version of these two series, so I can try it locally?

**Comment by chenlujjj** [comment]
> Does it happen to other alerting rules with <1 condition?
Not yet

> Is vmalert configured with the same datasource.URL as Grafana?
Yes, the `-datasource.url=` config is the same as grafana panels above.

> Is it possible to get the exported version of these two series, so I can try it locally?
Not sure how to export specific time series. I will check the documents to find the way.

**Comment by chenlujjj** [comment]
[alert_rule.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6834276/alert_rule.txt)
[ALERTS.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6834277/ALERTS.txt)

Just uploaded the two series in json line format.

**Comment by hagen1778** [comment]
Hi @chenlujjj! Sorry for the late replay, I was on holiday 🍹 
Thank you for provided data! Here's what I did:
1. I've built&started VM-single from the master branch;
2. I've imported the provided alert_rule.txt file via `curl -X POST http://localhost:8428/api/v1/import -T alert_rule.txt`
3. Then wrote an alerting config from my vmalert (also built from master branch):
```
groups:
  - name: vmsingleReplay
    interval: 30s
    concurrency: 2
    rules:
      - alert: issue-1452
        expr: (count by(app, task, target, name) (http_probe_success_rate == 1) or on() vector(0)) / count by(app, task, target, name) (http_probe_success_rate) < 1
        labels:
          severity: warning
```
4. I then ran a [replay](https://docs.victoriametrics.com/vmalert.html#rules-backfilling) process via vmalert to re-evaluate alerting rule against historical data. The result of the replay process should be a `ALERTS` metric written back to VM when alerting rule becomes active.
5. Then I used Grafana to plot two queries. See the screenshot below:
<img width="1277" alt="Screenshot 2021-08-04 at 17 20 58" src="https://user-images.githubusercontent.com/2902918/128198498-5b64b4fd-0ad8-4389-b0c8-94e9f54a501f.png">
On the screenshot I see that ALERTS metric was generated exactly when needed and continued as long as expression were returning results.

If that's possible, can you try to repeat my actions and see if it works for you in the same way? If no, is there any way to produce a repeatable scenario for this bug to reveal?
Thank you very much for patience and cooperation!

**Comment by hagen1778** [comment]
Closed as inactive
