### ISSUE TITLE
vmalertmanager: dropping messages because too many are queued

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1453]
level=warn ts=2021-07-14T22:21:26.993Z caller=delegate.go:272 component=cluster msg="dropping messages because too many are queued" current=4298 limit=4096

Hello, how to configure the size of this queue

**Comment by hagen1778** [comment]
Hi @WuJingLearn! It totally depends on how you use, your workload and alerts rate. You may find similar issues here:
https://github.com/prometheus/alertmanager/issues/1814
https://github.com/prometheus/alertmanager/issues/2440
