### ISSUE TITLE
grafana-vmcluster

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1454]
When I use the Victoriametric cluster method, how should the grafana data source be written?

http://10.1.2.52:8481/select/0/prometheus/api/v1/query，This way is wrong

**Comment by denisgolius** [comment]
Hi @WuJingLearn !
See this https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/provisioning/datasources/datasource.yml#L7

**Comment by WuJingLearn** [comment]
thank you
