### ISSUE TITLE
one vm-storage node  does not merge small parts to big parts

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#1455]
We suddenly found that the query p99 rose a lot, and a storage node was found to return a timeout through the log
Check this node and find that there are no small parts merged into big parts
`small dir`
![image](https://user-images.githubusercontent.com/2275120/125733124-5d6d295d-08f6-479d-86c3-60193fb27cb2.png)
`big dir`
![image](https://user-images.githubusercontent.com/2275120/125733167-17e0c4c8-b538-4672-9b6e-d2b2fe7ededc.png)

The disk space of this machine should be sufficient
![image](https://user-images.githubusercontent.com/2275120/125733266-bba4b165-c560-4862-a2c2-ece5b7e4ca0e.png)

After restarting the service or calling the force_merge, it is still useless

thx
**Version**
```
$ ./victoria-metrics-prod --version
vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5
```

**Comment by tangqipengleoo** [comment]
Hello,there're some information maybe useful. In the function `func appendPartsToMerge(dst, src []*partWrapper, maxPartsToMerge int, maxRows uint64) ([]*partWrapper, bool)`(in the process of smallPartMerge),all the src parts to merge is judged unbalanced, so the len(dst) == 0. 
![image](https://user-images.githubusercontent.com/83160619/125735439-e570dcf5-2d5b-48b0-bf5a-cd7dc76e2d7e.png)

**Comment by gaoxp** [comment]
Also have a question，when one vmstorage node(expect to 1 node) with some reason in maintain and stopped some time, vminsert will also send original to this stopped node data to another vmstorage node(expect to 2 node), after some time, this stopped node start(1 node start)，then 2 node have some small amount of data that belongs to 1 node, will this condition impact small merge?

**Comment by valyala** [comment]
@gaoxp , could you try building VictoriaMetrics from the commit 9a83e9018d5f0bc9b1d5c5159c8cda265f6a35c3 and verify whether it enables merging of small parts? The commit is intended for the issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1373 , but it additionally fixes an issue with improper calculations for minSrcParts and maxSrcParts.

> when one vmstorage node(expect to 1 node) with some reason in maintain and stopped some time, vminsert will also send original to this stopped node data to another vmstorage node(expect to 2 node), after some time, this stopped node start(1 node start)，then 2 node have some small amount of data that belongs to 1 node, will this condition impact small merge?

This shouldn't impact merge process.

> if have a lot of small parts, does it will impact query informance?

Yes - the query performance may become slower, since VictoriaMetrics needs to consult more parts if queries touch data across many parts.

**Comment by gaoxp** [comment]
> @gaoxp , could you try building VictoriaMetrics from the commit [9a83e90](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/9a83e9018d5f0bc9b1d5c5159c8cda265f6a35c3) and verify whether it enables merging of small parts? The commit is intended for the issue #1373 , but it additionally fixes an issue with improper calculations for minSrcParts and maxSrcParts.
> 
> > when one vmstorage node(expect to 1 node) with some reason in maintain and stopped some time, vminsert will also send original to this stopped node data to another vmstorage node(expect to 2 node), after some time, this stopped node start(1 node start)，then 2 node have some small amount of data that belongs to 1 node, will this condition impact small merge?
> 
> This shouldn't impact merge process.
> 
> > if have a lot of small parts, does it will impact query informance?
> 
> Yes - the query performance may become slower, since VictoriaMetrics needs to consult more parts if queries touch data across many parts.

We have tried use commit [https://github.com/VictoriaMetrics/VictoriaMetrics/commit/9a83e9018d5f0bc9b1d5c5159c8cda265f6a35c3](url), but it doesn't work, merge is also not work normal. On own merge not normal vmstorage node, in -storageDataPath specify small path, there a lot of small parts dictionary, greater than 256, it looks like 270+ small parts.
but after we tried some steps that storage node  looks like merge normal:
1. restart abnormal vmstorage node and disable vminsert that mean no data send to this storage node, and we wait this node cron merge, but it not merge normal
2. we print some log to debug why not merge, describe as this comment [https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1455#issuecomment-880414665](url)
3. we find small parts will first merge to small parts, then merge to big parts, so we disable some merge check in appendPartsToMerge function, like this 
![image](https://user-images.githubusercontent.com/13375117/125791252-7282a178-d95f-4211-af56-c08926310999.png)，and restart storage node without data send to this node, find this make  small parts begin merge to small parts
4. we checkout to our production storage node cluster version vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5, and restart storage node without data send to this node, find small parts begin merge to big parts, after we wait it merge complete, we enable vminsert to send data to this node, it works normal.

but we can't understand why there are so many small parts that not merge normal, under what circumstances will there be so many small parts?

**Comment by gaoxp** [comment]
@valyala is there any progress？

**Comment by valyala** [comment]
@gaoxp , thanks for the provided analysis. We are still investigating the issue. The code, which prevents from merging unbalanced parts, shouldn't prevent from merging small parts and shouldn't result in too big number of small parts.

**Comment by gaoxp** [comment]
@valyala Is there any progress? Now we find more instances have the same problem，but we can't find why this happen。
