### ISSUE TITLE
Add cluster binaries to realeses 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#146]
**Is your feature request related to a problem? Please describe.**
No cluster binaries in releases

**Describe the solution you'd like**
Add cluster binaries to releases

**Comment by valyala** [comment]
Cluster binaries are published in `*-cluster-<release_version>.tar.gz` starting from [v1.25.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
