### ISSUE TITLE
hi , where I can find the vmstorage design artitechture

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#1460]
hi , where I can find the vmstorage design artitechture

**Comment by hagen1778** [comment]
Hi @davidsome!
Please check the following article https://valyala.medium.com/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282
Also you can find more tech articles here https://docs.victoriametrics.com/Articles.html#technical-articles

**Comment by valyala** [comment]
See also https://docs.victoriametrics.com/#storage .

Closing the question as answered.
