### ISSUE TITLE
 add kubeconfig support in discovery module

### ISSUE THREAD

**Issue by lfrancke** [VictoriaMetrics/VictoriaMetrics#1464]
Prometheus recently (in 2.28.0) added support for providing a kubeconfig file to the kubernetes discovery module.

https://github.com/prometheus/prometheus/pull/8811

As the Victoria documentation just links to Prometheus we assumed that it'd be there as well (we were unaware that it was only added recently). This functionality would be useful to have.

**Comment by valyala** [comment]
@f41gh7 , could you look at this feature request?

**Comment by valyala** [comment]
[vmagent](https://docs.victoriametrics.com/vmagent.html) supports `kubeconfig_file` option in [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) section starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
