### ISSUE TITLE
vmselect

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1467]
Hello, does vm have a ui interface similar to prometheus

**Comment by denisgolius** [comment]
Hello @WuJingLearn !
**From changelog 1.63.0**
```
FEATURE: vmselect: embed vmui into a single-node VictoriaMetrics and into vmselect component of cluster version. See this feature request. The web interface is available at the following paths:

    /vmui/ for a single-node VictoriaMetrics
    /select/<accountID>/vmui/ for vmselect at cluster version of VictoriaMetrics
```
See this #1413  or if you asking about `/targets` status page interface - you can see it if you open `http://vmagent:8429` from cluster setup or `http://victoriametrics:8428/targets`from single node VictoriaMetrics.
