### ISSUE TITLE
Influx Line Protocol not inserting

### ISSUE THREAD

**Issue by Cnidarias** [VictoriaMetrics/VictoriaMetrics#147]
I am using the latest docker image to test out Victoria Metrics
and I have generated about 190mio data points that I want to insert. They have timestamps starting from 90 days ago. 
They are in influx format:

`m_name,uid=someuid,dataSetName=some_dataset value=82.28833956235734 1558025088636`

but when I post this to Victoria it does not seem to be added
`curl -d 'm_name,uid=someuid,dataSetName=some_dataset value=82.28833956235734 1558025088636' -X POST 'http://localhost:8428/write'`

Running `curl -G 'http://localhost:8428/api/v1/export' --data-urlencode 'match={__name__!=""}'` afterwards does not return a metric with the expected name `m_name_value`

The return is:

`{"metric":{"__name__":"foo.bar.baz","tag1":"value1","tag2":"value2"},"values":[123],"timestamps":[1565367168000]}
{"metric":{"__name__":"measurement_field1","tag1":"value1","tag2":"value2"},"values":[123],"timestamps":[1565365788132]}
{"metric":{"__name__":"measurement_field2","tag1":"value1","tag2":"value2"},"values":[1.23],"timestamps":[1565365788132]}`

(These values are there because I tested the influx curl example from the README.md as well as the openTSDB example (which both obviously worked)

I have also set the retention policy to 12 months but that does not seem to be the issue either.

**Comment by valyala** [comment]
Influx line protocol requires timestamps in *nanoseconds* by default - see https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/#timestamp , while VictoriaMetrics stores timestamps with *millisecond* precision. So the following line should work:
```
curl -d 'm_name,uid=someuid,dataSetName=some_dataset value=82.28833956235734 1565613454847000000' -X POST 'http://localhost:8428/write'
```

It is possible to send timestamps in milliseconds by providing `precision=ms` query arg:

```
curl -d 'm_name,uid=someuid,dataSetName=some_dataset value=82.28833956235734 1565613454848' -X POST 'http://localhost:8428/write?precision=ms'
```

**Comment by Cnidarias** [comment]
Ah thank you very much I thought that might be the case and tested it today and it now works as expected! Thank you for the quick reply!
