### ISSUE TITLE
Add support for multiple listening addresses

### ISSUE THREAD

**Issue by guillemj** [VictoriaMetrics/VictoriaMetrics#1470]
**Is your feature request related to a problem? Please describe.**

On systems with multiple interfaces, one might only want to listen on only a subset of addresses, for example for loopback and intranet facing addresses. 

**Describe the solution you'd like**

Adding support for specifying multiple -*ListenAddr options would solve this.

**Describe alternatives you've considered**

Listening on everything and then restricting based on firewall rules is not satisfactory as that is prone to accidentally opening the services (possibly unprotected) to external and hostile networks, due to firewall misconfiguration or in case it needs to be brought down or similar. Having security in depth, were the firewall is an additional layer on top of the restricted listening seems always superior.

**Additional context**

This would also make it possible to later on implement something like systemd sd_listen_fds(3) protocol.

**Comment by valyala** [comment]
The commit ae8a867924b4ee70c1f2cfb56425bd48300cfe86 adds support for multiple `-httpListenAddr` options to the following VictoriaMetrics components:
- [single-node VictoriaMetrics](https://docs.victoriametrics.com/)
- [vmagent](https://docs.victoriametrics.com/vmagent.html)
- [vmalert](https://docs.victoriametrics.com/vmalert.html)
- [vmauth](https://docs.victoriametrics.com/vmauth.html)
- [vminsert, vmselect and vmstorage](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html)

This commit will be included in the next release.

**Comment by valyala** [comment]
All the VictoriaMetrics components accept multiple `-httpListenAddr` options starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
