### ISSUE TITLE
vmagent how to  load more conf yml

### ISSUE THREAD

**Issue by jiangxinlingdu** [VictoriaMetrics/VictoriaMetrics#1473]
to facilitate management, i want to group configuration files，so i want to load more yml to vmagent，but i see code find -promscrape.config only one  conf yml file，i  hope vmagent can load more conf yml

**Comment by f41gh7** [comment]
Hello, atm, vmagent doesn't support such configuration. 

But, it's possible to separate configuration with some configuration management tool. Like ansible, puppet, helm and others.

**Comment by valyala** [comment]
@jiangxinlingdu , the following service discovery options may be useful for your use case:
* [file_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config), which allows splitting statically configured targets among multiple files, which can be dynamically reloaded.
* [http_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config), which allows splitting scrape targets among multiple http endpoints, which can be dynamically updated.

**Comment by valyala** [comment]
`vmagent` supports the ability to load [scrape configs](https://docs.victoriametrics.com/sd_configs/) from multiple files by listing them inside `scrape_config_files` block - see [these docs](https://docs.victoriametrics.com/vmagent/#loading-scrape-configs-from-multiple-files).

The `scrape_config_files` option has been appeared in `vmagent` [v1.65.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1559).

Closing this feature request as done.
