### ISSUE TITLE
How to add selfScrapeInterval in Victoria metrics cluster

### ISSUE THREAD

**Issue by sachinar** [VictoriaMetrics/VictoriaMetrics#1477]
Hi ,

We tried adding selfScrapeInterval: 10s in our victoria metrics cluster but as  i see this flag is not available in vmstore, vminsert & vmselect.

How we can enable it?

**Comment by f41gh7** [comment]
Hello, cluster version doesn't support selfScrapeInterval. Its recommended to setup monitoring for it with vmagent.

Related doc https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring

**Comment by sachinar** [comment]
Now how we can enable on prometheus? I see prometheus scraping is avaible but there is no documentation for how to add in it.

**Comment by denisgolius** [comment]
Hi @sachinar !
See this https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/docker-compose.yml#L12 . There is a compose file that configure **vmagent** for scraping and where you can configure prometheus scrape targets.

**Comment by sachinar** [comment]
Hi @denisgolius,

Thanks for info!
