### ISSUE TITLE
VmAlert

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1479]
Can the alert rule be dynamically updated?

**Comment by jiangxinlingdu** [comment]
cannot

**Comment by Cosrider** [comment]
yes, configmap-reload will update it

**Comment by hagen1778** [comment]
vmalert now can check config for changes if flag `-rule.configCheckInterval` is set. See more details here https://docs.victoriametrics.com/vmalert.html#configuration
