### ISSUE TITLE
vmctl support for migration via query_range

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#1480]
Case - data migration from a prometheus compatible metrics storage via /api/v1/query_range
An example of an almost necessary implementation is a vmalert in replay mode.
The problem with vmalert is that the recording rule replaces the metrics name with the rule name.

I would like to get a migrator that receives an expression for requesting metrics as input, example
   -filter-label = "__ name__"
   -filter-label-value = "http. *"
parameters of start and end of sampling, example
    -timeFrom = 2021-05-11T07: 21: 43Z
    -timeTo = 2021-05-29T18: 40: 43Z
parameter step
    - step = 15s
time period for one sample
    - batch-time = 60s
url for read metrics
    -datasource.url=http://localhost:9090     # PromQL/MetricsQL compatible datasource
url for remote write 
    -remoteWrite.url=http://localhost:8428

**Comment by f41gh7** [comment]
Work around with vmalert https://gist.github.com/ihard/493423806d3eae4d89d415a9a8ce462d

**Comment by hagen1778** [comment]
Hi @ihard!

In your example I don't understand how the batching or step works. If there are multiple points on 60s interval - what is the expectation of transferred data.

Btw, vmctl now supports data migration via [remote read protocol](https://docs.victoriametrics.com/vmctl.html#migrating-data-by-remote-read-protocol) which might be what you're looking for.
