### ISSUE TITLE
rollup_sum

### ISSUE THREAD

**Issue by rbariou** [VictoriaMetrics/VictoriaMetrics#1487]
Hello

Any plan to have a rollup function for counters where we could get the sum of values per step interval ?
I couldn't find a way to do this with the existing functions.

Thank you

**Comment by johnseekins** [comment]
Are you asking for the "over_time" functions? https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time

**Comment by valyala** [comment]
@rbariou , probably you are looking for `sum_over_time(m[d])` function. It returns the sum of all the raw samples for time series with the name `m` on the given lookbehind window `d` ending at the requested time. For example `/api/v1/query?query=sum_over_time(requests[5m])&time=2021-08-14T01:23:45Z` would return the sum of requests for the last 5 minutes ending at `2021-08-14T01:23:45Z`. See more details about `/api/v1/query` at [official Prometheus docs](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries).

The `[d]` may be missing for queries passed to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries). In this case it becomes equal to the `step` value. E.g. `/api/v1/query_range?sum_over_time(requests)&start=...&end=...&step=5m` would automatically set the missing `[d]` to `step=5m`.

If you need calculating increase for the [counter metric](https://prometheus.io/docs/concepts/metric_types/#counter) on the given `step` interval, then take a look at [increase()](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) function.

**Comment by rbariou2** [comment]
Hello 

Thank you for the answer. The official Prometheus doc is states that  <aggregation>_over_time() methods return instant vector per time serie. I didn't think this could be extrapolated to a matrix when used with query_range...

Thank's again

**Comment by valyala** [comment]
Closing this question as answered.
