### ISSUE TITLE
How to store indexes in ES

### ISSUE THREAD

**Issue by olajowon** [VictoriaMetrics/VictoriaMetrics#1488]
Prometheus API is not flexible enough and the query index is too slow. I want to store the index of VM in ES in real time. Is there any good scheme

**Comment by jinlongwang** [comment]
We do this by periodically reading data through APIs such as labels, label_values, etc., and then writing it to third-party storage by ourselves

**Comment by xiaozongyang** [comment]
@olajowon 
Why do you want to store index to ES? What you to look up by this index?

**Comment by valyala** [comment]
VictoriaMetrics doesn't support Elasticsearch as index storage. It uses built-in `indexdb` for fast lookups of matching time series. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1241#issuecomment-1934703374 for more details on how does `indexdb` work.

Closing the issue as answered.
