### ISSUE TITLE
[questions] about vmstorage nodes

### ISSUE THREAD

**Issue by sezuan** [VictoriaMetrics/VictoriaMetrics#1489]
I've some questions about the `vmstorage`.

Are the following statements true:

- Replication should be done by the underlying filesystem, like a cloud store, ceph or drdb.
- An alternative is the replication factor with the drawback, if the data on one node is lost, the replication level can't be recovered.

The manual states

>  Adding more `vmstorage` nodes scales cluster capacity.

Does that mean that more nodes can be added to an existing cluster when the current nodes are almost full? Will `vminsert` use different `vmstorage` nodes when they are full. If so, what is the definition of full?
Or do I have to manually remove `vmstorage` nodes from the list of available nodes of `vminsert`, but keep them in `vmselect`?

**Comment by jinlongwang** [comment]
I think vminsert will not judge whether the back-end vmstorage node is'full '; vminsrt will only do health checks on vmstorage nodes, and the standard for health checks is whether vmstorage can complete the TCP handshake;
I think this is an expansion requirement. You can add vmstorage nodes to vminsert at any time, but only if you do your capacity evaluation to prevent some vmstorage nodes from being filled up

**Comment by f41gh7** [comment]
> Are the following statements true:
> 
>     * Replication should be done by the underlying filesystem, like a cloud store, ceph or drdb.

 Yes, replication factor can be used as alternative as you mentioned.
 
>     * An alternative is the replication factor with the drawback, if the data on one node is lost, the replication level can't be recovered.

  Lost node can be recovered from backup. Delay between last backup and node crash can be restored with `vmctl` - import and export with native proctol.
> 
> The manual states
> 
> > Adding more `vmstorage` nodes scales cluster capacity.
> 
> Or do I have to manually remove `vmstorage` nodes from the list of available nodes of `vminsert`, but keep them in `vmselect`?

 Yes, you have to manually manage list of storage nodes for vminsert and remove full storage nodes from vminsert routing.

**Comment by valyala** [comment]
FYI, `vmstorage` can be configured to enter read-only mode if it has less than `-storage.minFreeDiskSpaceBytes` of reee disk space - see [these docs](https://docs.victoriametrics.com/cluster-victoriametrics/#readonly-mode). This flag has been appeared in `vmstorage` since [v1.67.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/269) for details.

Closing the question as answered.
