### ISSUE TITLE
Grafana 8 Unified Alerts Error Unsupported Path

### ISSUE THREAD

**Issue by arnoldyahad** [VictoriaMetrics/VictoriaMetrics#1493]
Hey guys, 
We are using VMDB 1.62.0, and recently we updated our grafana to 8.0.6
we opted-in the new unified alerts system: [link here](https://grafana.com/blog/2021/06/14/the-new-unified-alerting-system-for-grafana-everything-you-need-to-know/) and [here](https://grafana.com/docs/grafana/next/alerting/unified-alerting/opt-in/)

Now we see that in the alerts menu in grafana there is this message:
![image](https://user-images.githubusercontent.com/18227724/126986992-772c8463-575d-4eae-b608-43b2a9275e9b.png)

**To Reproduce**
Use VMDB as a prometheus datasource in Grafana(version 8.0.6), enable the new unified alerting system: 
[here](https://grafana.com/docs/grafana/next/alerting/unified-alerting/opt-in/) through your grafana configuration(usually /etc/grafana/grafana.ini) 

**Expected behavior**
Fixing the endpoint to be valid for Grafana 8.

**Logs**
Logs from our kibana show that this query is being performed multiple times in a second: 
![image](https://user-images.githubusercontent.com/18227724/126987651-6f5de39b-3a7a-4d73-8ecd-c5ece8917653.png)
It fills up the warning logs, and its also an unnecesary load on vmselect.

**Comment by jinlongwang** [comment]
It seems that there is no rule-related interface implemented in VictoriaMetric

**Comment by arnoldyahad** [comment]
thanks for replying @jinlongwang 

when using the endpoint you provided - it works, but its not the endpoint that grafana is querying:
```
# This is what grafana tries to query: 
curl https://my-vmselect/select/0/prometheus/rules
remoteAddr: "10.200.187.253:54348", X-Forwarded-For: "172.17.222.51"; unsupported path requested: "/select/0/prometheus/rules"
# This is what is implemented to work 
 curl https://my-vmselect/select/0/prometheus/api/v1/rules
{"status":"success","data":{"groups":[]}}%
```

so basically the change needed here is relatively small - just to open another case  of `prometheus/rules` which is a copy of `prometheus/api/v1/rules`

**Comment by Zhouhenry** [comment]
according to the error msg, it can be found it is the return of vm-auth, maybe you need to have a look of  `auth.config`.

**Comment by arnoldyahad** [comment]
Thanks for the reply @Zhouhenry but it doesnt work even locally: 
```
/ # curl localhost:8481/select/0/prometheus/api/v1/rules
{"status":"success","data":{"groups":[]}}/ #
/ #
/ # curl localhost:8481/select/0/prometheus/rules
remoteAddr: "127.0.0.1:55908"; unsupported path requested: "/select/0/prometheus/rules"
/ #
```

It just needs to be on a different endpoint to support grafana 8 unified alerting.

**Comment by valyala** [comment]
VictoriaMetrics should return dummy response for `/rules` page starting from [v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
