### ISSUE TITLE
vmalert expose metric when recording rule execution returns no data

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1494]
**Is your feature request related to a problem? Please describe.**
I want to have metric inside vmalert which counts no data responses from datasource and dump empty expresion query in log

**Describe the solution you'd like**
Exposed metric

**Describe alternatives you've considered**
Setup alert for same recording rule and fires it when no metrics in response

**Comment by Zhouhenry** [comment]
@tenmozes "no data responses" means no values in the query response?

**Comment by valyala** [comment]
@Zhouhenry , yes

**Comment by hagen1778** [comment]
Hi @tenmozes! The new metric was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1518 and will be likely present in the next release.

**Comment by valyala** [comment]
FYI, the `vmalert_alerting_rules_last_evaluation_samples` and `vmalert_recording_rules_last_evaluation_samples` metrics are exposed by `vmalert` starting from [v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
