### ISSUE TITLE
Layout error on big query

### ISSUE THREAD

**Issue by kevinvirs** [VictoriaMetrics/VictoriaMetrics#1497]
**Describe the bug**
If query have more 27 rows, fully hiding graph with results, wihout scrollbar on all tabs chart/json/table

**To Reproduce**
display dimension 1366x768
add any big query or insert empty rows

**Version**
1.63.0

Screenshots
https://user-images.githubusercontent.com/47024525/118494298-346eb480-b74c-11eb-847a-a03a599d5166.png

**Comment by valyala** [comment]
The issue must be fixed after the commit 236fc7d7396e68ab4e06146bef680d333222b468 . The bugfix will be included in the next release of VictoriaMetrics. In the mean time the bugfix can be verified by running VictoriaMetrics built from the latest commit in `master` branch according to [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by valyala** [comment]
vmui should correctly display graphs with more than 27 rows starting from [VictoriaMetrics v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
