### ISSUE TITLE
Using /api/v1/import/prometheus to ingest with timestamp, but failed

### ISSUE THREAD

**Issue by stormbroken** [VictoriaMetrics/VictoriaMetrics#1498]
**Describe the bug**
Using docker:latest to start victoriametrics, I fail to ingest data by using POST request /api/v1/import/prometheus?timestamp=1599894041764 to ingest data.

**To Reproduce**
I send POST request  /api/v1/import/prometheus?timestamp=1599894041764 with body "foo{bar="baz"} 123" and header "Content-Type"="text/plain; version=0.0.4; charset=utf-8", but once I remove timestamp, then it will success.

related issue is #750

**Comment by jinlongwang** [comment]
It should be that the timestamp you passed is less than the current time minus the retetion time

**Comment by stormbroken** [comment]
Yes, It is!
Thanks for your help
