### ISSUE TITLE
Query and Query range return empty set

### ISSUE THREAD

**Issue by stormbroken** [VictoriaMetrics/VictoriaMetrics#1500]
**Describe the bug**
After I insert data into VictoriaMetric, I can get it by /api/vi/export but failed by /api/v1/query and /api/v1/query_range

**To Reproduce**
1. Use /api/v1/import/prometheus?extra_label=db=bug with body "foo{} 123 1619517599000" to insert data with specific timestamp
2. Use /api/v1/export?match={db="bug"} to get this data，the result is as follows

{"metric":{"__name__":"foo","db":"bug"},"values":[123],"timestamps":[1619517599000]}

3. Use /api/v1/query?query={db="bug"} to get this data, the result is as follows which differs.

{"status":"success","data":{"resultType":"vector","result":[]}}

4. Same case in /api/v1/query_range

**Expected behavior**
Expect to get data by using /api/v1/query?query={db="bug"} 

**Logs**
No logs

**Screenshots**
No Usable Screenshots

**Version**
MyVersion is as follows(Using docker images)
```
$ ./victoria-metrics-prod --version
victoria-metrics-20210715-111307-tags-v1.63.0-0-g61cc13c16
```

**Used command-line flags**
-retentionPeriod 30 -search.latencyOffset 1s -search.disableCache=true

**Comment by stormbroken** [comment]
In addition, I setup VictoriaMetrics using follow steps:
1. `docker pull victoriametrics/victoria-metrics`
2. `docker run -it --rm -v /path/to/victoria-metrics-data:/victoria-metrics-data -p 8428:8428 -d --name=victoria victoriametrics/victoria-metrics -retentionPeriod 30 -search.latencyOffset 1s -search.disableCache=true`

**Comment by stormbroken** [comment]
In addition, If I ingest data with this body "foo{} 123", then all problems above is solved, but I still need to query the data before

**Comment by Zhouhenry** [comment]
@stormbroken because u set a timestamp when you import data,  so you get an empty result when you query. You can find that if 
 you dont set timestamp for datapoint when you do a query request, it will use the timestamp of when you query.(code function is `func QueryHandler(startTime time.Time, w http.ResponseWriter, r *http.Request) error {`)

**Comment by stormbroken** [comment]
Thanks! This surely solve my problem, I will close this issue.
