### ISSUE TITLE
Remotely backups with vmbackup

### ISSUE THREAD

**Issue by iglov** [VictoriaMetrics/VictoriaMetrics#1503]
Hi guys, hi Sanya! `^_^`
Is it somehow possible, to make backup with **vmbackup** from remotely VictoriaMetrics instance? I'll try to describe.
For ex. i have 2 hosts: **Host A** with vmbackup where i have a lot of free disk space and **Host B** where i have runned VictoriaMetrics instance. So the main idea to somehow connect with **vmbackup** from **Host A** to VictoriaMetrics on **Host B** . Something like this: `vmbackup-prod -snapshot.createURL='http://victoriametrics-1.local:8428/snapshot/create' -dst=fs:///mnt/backups/vm -memory.allowedBytes=20GB -maxBytesPerSecond=60MB`
As you can see, there is no `-storageDataPath` option, so i believe, in this case, this function should be delegated to VictoriaMetrics engine. Unfortunately, i am not a good programmer so i have no idea is it possible or not at all :) So i will read your thoughts about that with big pleasure!
P.S. Sorry for my eng, <3 u guys `^_^`

**Comment by valyala** [comment]
This requires including `vmbackup` code into a single-node VictoriaMetrics and into vmstorage component of cluster version of VictoriaMetrics. While this may be convenient from operator perspective, there are the following concerns with this approach:

* How to deal with multiple outstanding requests for backup?
* How to list the information about currently performed backups?
* How to interrupt the backup?
* How to continue the interrupted backup?
* How to clean up temporary data (snapshots) for the interrupted backup?
* How to deal with outstanding backups during the shutdown of VictoriaMetrics process?
* How do deal with backups, which were interrupted by unclean shutdown such as OOM, `kill -9` or hardware reset?

**Comment by valyala** [comment]
The functionality for making the backups via API at VictoriaMetrics side won't be implemented because of the issues mentioned in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1503#issuecomment-899039347). [vmbackup](https://docs.victoriametrics.com/vmbackup/) allows gracefully resolving these issues via manual control of the backup process.

Closing the feature request as won't implement.
