### ISSUE TITLE
vmui with the permanent server address

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#1506]
Hi,
It's cool that now there is a UI. But it would be much more convenient if you made it possible to add the URL Server Url on a permanent basis, so as not to enter it every time.
Thanks.

**Comment by valyala** [comment]
This should be fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/aca2cb245e40690c0b4da38f2211cdcf4be990f8 . This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
VictoriaMetrics should automatically fill Server URL at `/vmui` starting from [v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
