### ISSUE TITLE
Query_range wrong last value

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#1509]
Last metrics of query_range are wrong.

When i query VM through query_range the last value is either wrong or not present.

Prometheus query_range:

```
curl -sg "http://x.x.x.x:9090/api/v1/query_range?query=probe_duration_seconds{instance='xxx'}&start=1627893600&end=1627893900&step=60"
        "values": [
          [
            1627893600,
            "0.09316756"
          ],
          [
            1627893660,
            "0.104327531"
          ],
          [
            1627893720,
            "0.101365639"
          ],
          [
            1627893780,
            "0.09696379"
          ],
          [
            1627893840,
            "0.088306011"
          ],
          [
            1627893900,
            "0.094134059"
          ]
```

VM query_range :

```
curl -sg "http://x.x.x.x:8428/api/v1/query_range?query=probe_duration_seconds{instance='xxx'}&start=1627893600&end=1627893900&step=60

        "values": [
          [
            1627893600,
            "0.09316756"
          ],
          [
            1627893660,
            "0.104327531"
          ],
          [
            1627893720,
            "0.101365639"
          ],
          [
            1627893780,
            "0.09696379"
          ],
          [
            1627893840,
            "0.088306011"
          ]
```

The value with timestamp 1627893900 is missing from VM

Another example:

Prometheus query_range:

```
curl -sg "http://x.x.x.x:9090/api/v1/query_range?query=count(up)&start=1627893600&end=1627893900&step=60"

        "values": [
          [
            1627893600,
            "931"
          ],
          [
            1627893660,
            "931"
          ],
          [
            1627893720,
            "931"
          ],
          [
            1627893780,
            "931"
          ],
          [
            1627893840,
            "931"
          ],
          [
            1627893900,
            "931"
          ]
```

VM query_range :

```
curl -sg "http://x.x.x.x:8428/api/v1/query_range?query=count(up)&start=1627893600&end=1627893900&step=60"

        "values": [
          [
            1627893600,
            "931"
          ],
          [
            1627893660,
            "931"
          ],
          [
            1627893720,
            "931"
          ],
          [
            1627893780,
            "931"
          ],
          [
            1627893840,
            "931"
          ],
          [
            1627893900,
            "778"
          ]
``` 

Here the metrics with timestamp 1627893900 is wrong.

You can saw it in grafana too.

![last_value_wron,g](https://user-images.githubusercontent.com/35098906/127833297-d370fd13-3c66-4885-a0bd-c9e1bb365ae8.PNG)

![metrics late](https://user-images.githubusercontent.com/35098906/127833327-a0e81398-aee6-4dd4-8e96-5c1fa7e55a0c.PNG)

Querying through api/v1/query is good and through api/v1/export too. Only query_range is returning weird metrics

Version
docker exec victoriametrics ps
/victoria-metrics-prod -storageDataPath=/victoria-metrics-data -retentionPeriod=12 -dedup.minScrapeInterval=1m -search.latencyOffset=1s

docker exec victoriametrics /victoria-metrics-prod --version
victoria-metrics-20210715-111307-tags-v1.63.0-0-g61cc13c16

**Comment by hagen1778** [comment]
Hi @xenofree! Thanks for detailed description! I'll take a look and will get back to you.

**Comment by valyala** [comment]
This looks like a bug related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/748 . The temporary workaround is to wrap series selectors into `last_over_time()` function. For example, to use `count(last_over_time(metric))` instead of `count(metric)`.

**Comment by xenofree** [comment]
Thanks for your answer. I will not modify all my dashboard with this workaround, i'll wait for a fix :)

**Comment by hagen1778** [comment]
Seems relevant to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526

**Comment by valyala** [comment]
@xenofree , could you try the fix from the commit 4401464c229ec6ea7691b2ad61f91b2d8d0666f9 ? It should fix query results for newly ingested data. See [how to build VictoriaMetrics from sources](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by xenofree** [comment]
Thanks for the fix @valyala , dashboard and requesting VM query_range seems good.
The only issue that i see is exploring through grafana

![explore](https://user-images.githubusercontent.com/35098906/129369934-d78a2e80-56e2-4c8e-90b5-5995ec5c1450.gif)

Last value is still weird

**Comment by valyala** [comment]
@xenofree , do you use Prometheus or [vmagent](https://docs.victoriametrics.com/vmagent.html) for data ingestion into VictoriaMetrics? If you use `vmagent`, then it must be re-built from the latest commit as described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526#issuecomment-898323054), since the previous versions of `vmagent` didn't add Prometheus staleness markers when a particular scrape target disappears.

**Comment by xenofree** [comment]
I'm using prometheus for data ingestion

**Comment by valyala** [comment]
VictoriaMetrics and vmagent gained support for Prometheus staleness markers starting from [the release v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @xenofree , could you verify whether upgrading to v1.64.0 fixes the issue with inflated `count()` for newly ingested data after the upgrade? Note that query results for the previously ingested data can remain incorrect.

**Comment by xenofree** [comment]
Thanks for the release, I have upgrade to 1.64.0 and i still have issue with count().
/api/v1/query return the right value but last point of query_range is weird

**Comment by valyala** [comment]
The last point for `count()` query at `/api/v1/query_range` can be lower than expected if it is located close to the current time. This is because the database can miss the last sample for a part of time series because the last sample isn't scraped yet due to the given `scrape_interval`. The `count()` query results should be OK if the last point is located in the past.

**Comment by xenofree** [comment]
I understand, but how does Prometheus handle it ? Value returned by Prometheus query_range are pretty neat.

**Comment by valyala** [comment]
I don't know how does Prometheus handle it. VictoriaMetrics contains a special handling for the last point if it is located closer than `-search.latencyOffset` to the current time.: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/db1e62495be0435e2bcd75e77fe4925630679175/app/vmselect/prometheus/prometheus.go#L1142-L1147 

and

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/db1e62495be0435e2bcd75e77fe4925630679175/app/vmselect/prometheus/prometheus.go#L1206-L1234

Probably VictoriaMetrics skips the special handling for the last point due to a specific configuration for `-search.latencyOffset` and / or `-search.maxStepForPointsAdjustment` command-line flags.

**Comment by xenofree** [comment]
VictoriaMetrics was start with -search.latencyOffset=1s.
I tried to remove this flags. So now i have 1min scrape_interval, -search.latencyOffset 30s (default value) and -search.maxStepForPointsAdjustment 1m (default value) but i still have that wrong last point

**Comment by mxsiegle** [comment]
I think this is related to my issue #1442 (or even the same issue).
Adjusting the max step value won't really help, as soon as the interval is higher than the step value it will return the wrong value again.

**Comment by hagen1778** [comment]
Hi @xenofree! In your case, how exactly VM receives the data? Does Prometheus you're comparing with remote-writes to VM?

**Comment by xenofree** [comment]
Prometheus remote_write to a vminsert instance

`
remote_write:
  - url: http://x.x.x.x:8480/insert/0/prometheus/api/v1/write
    queue_config:
      batch_send_deadline: 5s
      min_backoff: 1s
      max_backoff: 30s
      max_shards: 30
`

**Comment by xenofree** [comment]
> Do you have the same issues when selecting time range in the past?
No, when i query old metrics, everything is good.

> Could that be data isn't just delivered to VM yet?
I'm guessing that it is the issue. Is it possible to don't show the last point until everything is delivered to VM ?
I thought that `-search.latencyOffset` was here for that kind of issue but setting it equal or greater than scrape_interval don't seems to work.

**Comment by hagen1778** [comment]
> Is it possible to don't show the last point until everything is delivered to VM ?

There is no a way to  know this. Prometheus does atomic scrapes, it means that all scraped datapoints become visible only after scrape is completed. These datapoints then are written to the WAL. The WAL is then re-reread for sending to remoteWrite. The remoteWrite senders can establish up to [max_shards](https://prometheus.io/docs/practices/remote_write/#max_shards) connections for data transferring, so data gradually flows into the remote storage. Remote storage isn't aware of any constraints except the received data. 

> I thought that -search.latencyOffset was here for that kind of issue

It is. It means datapoints with timestamps greater than `now()-search.latencyOffset` won't be returned by VM. But if writer falls behind more than that, it starts to deliver data with older timestamps which won't be covered by this offset. In two words, if Prometheus remote write lag is > than `latencyOffset` - the data may seem incomplete for the last datapoint.

I think, it may be useful to understand what is the lag for Prometheus remote-write in your case and how we can improve it.

**Comment by xenofree** [comment]
Thanks for the explanation.

I have ~60s remote write lag and a 60s scarpe_interval.
But even when I set `search.latencyOffset=600s` vmselect return datapoint

```
/vmselect-prod -storageNode=vmstorage:8401 -dedup.minScrapeInterval=1m -search.latencyOffset=600s -memory.allowedPercent=20
```

```
nowMinus900sec=$(date +%s --date '-900 sec') && curl -sg "127.0.0.1:8481/select/0/prometheus/api/v1/query_range?step=60&start=$nowMinus900sec&query=count(up)" | jq . && date +%s
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {},
        "values": [
          [
            1650354118,
            "3538"
          ],
          [
            1650354178,
            "3538"
          ],
          [
            1650354238,
            "3538"
          ],
          [
            1650354298,
            "3538"
          ],
          [
            1650354358,
            "3538"
          ],
          [
            1650354418,
            "3538"
          ],
          [
            1650354478,
            "3538"
          ],
          [
            1650354538,
            "3538"
          ],
          [
            1650354598,
            "3538"
          ],
          [
            1650354658,
            "3538"
          ],
          [
            1650354718,
            "3538"
          ],
          [
            1650354778,
            "3538"
          ],
          [
            1650354838,
            "3538"
          ],
          [
            1650354898,
            "3538"
          ],
          [
            1650354958,
            "3538"
          ],
          [
            1650355018,
            "3474"
          ]
        ]
      }
    ]
  }
}
1650355018
```

**Comment by hagen1778** [comment]
With `search.latencyOffset` datapoints will be still returned for the latest timestamps. Just last datapoints values covered by `search.latencyOffset` will be substituted with the previous point values.

Forgot to mention `search.maxStepForPointsAdjustment`:
```
-search.maxStepForPointsAdjustment duration
     The maximum step when /api/v1/query_range handler adjusts points with timestamps closer than -search.latencyOffset to the current time. The adjustment is needed because such points may contain incomplete data (default 1m0s)
```

In your example, you have `step=1m`, so adjustment won't work. If you extend `maxStepForPointsAdjustment` to value > `step` the adjustment start to work.

Try running VM with various `search.latencyOffset` values and send a query with a fixed `start` param to see how last datapoints in response change (remember to have `step` lower than `maxStepForPointsAdjustment`).

**Comment by xenofree** [comment]
I don't find any setup that satisfy my needs.

`maxStepForPointsAdjustment` duplicate the last valid data point (greater than `step`) which is a wrong value.
Is there a setup where the last datapoint become visible at `step + 1s` when every scrape is finished ?

**Comment by YuriKravetc** [comment]
Closing the issue, feel free to reopen it if consider unsolved.
