### ISSUE TITLE
operator

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1520]
Can vmagent also use prometheus ServiceMonitor directly?

**Comment by hagen1778** [comment]
@tenmozes could you please assist once you have a chance?

**Comment by valyala** [comment]
cc'ing @f41gh7 for the input

**Comment by f41gh7** [comment]
It cannot be used directly. But there is built-in conversion into own api objects. It allows to make smooth migration and don't depend on prometheus installation. 

 Related doc https://github.com/VictoriaMetrics/operator/blob/master/docs/quick-start.MD#migration-from-prometheus-operator-objects
