### ISSUE TITLE
Weekly High IO on cluster

### ISSUE THREAD

**Issue by johnseekins** [VictoriaMetrics/VictoriaMetrics#1521]
**Describe the bug**
I've described this bug in other places (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1441), but I feel like I'm stealing thunder from other issues, so I'm breaking this out to a separate issue...
At a high level:
We have a cluster configured to retain data for 1 year (`-retentionPeriod=365d`). Every Monday at midnight (00:00 UTC) we see a significant IO spike that directly causes data rerouting. The IO spike out-lasts the re-routes, so it doesn't seem directly connected to the re-routing.
Our instances are 8 CPUx 16 GB RAM instances running atop Ceph storage (with 4TB disks per storage node).

Because we see a significant drop in objects in Ceph itself at the same time, *we suspect this might be related to an aggressive number of deletes in the cluster.* The associated Ceph graph is also linked below.

**To Reproduce**
1. Have large ingest rate (>~800k points/sec) to large cluster (28 storage nodes)
2. wait a week

**Expected behavior**
No sudden weekly IO spikes.

**Logs**
No errors discovered in the logs other than messages about query timeouts (which are clearly symptoms of the problem).

**Screenshots**
Load profile:
![image](https://user-images.githubusercontent.com/5665929/128218342-9dd03467-e2d1-427a-a944-ac3ab209bafc.png)
Re-routing of data:
![image](https://user-images.githubusercontent.com/5665929/128218391-19abce45-12f6-4916-837b-6dedc215e424.png)
Ceph objects being removed:
![Screenshot from 2021-08-04 10-35-49](https://user-images.githubusercontent.com/5665929/128219732-5822b104-0561-4d50-bad4-817581b06506.png)

**Version**
1.63.0

**Used command-line flags**
```
 -search.maxUniqueTimeseries=300000000 -search.maxTagKeys=1000000 -search.maxTagValues=1000000000 -dedup.minScrapeInterval=1s -memory.allowedPercent=75 -storageDataPath=/var/lib/victoriametrics/storage/prod_cluster_1 -retentionPeriod=365d -vminsertAddr :8400 -vmselectAddr :8401 -httpListenAddr :8482
```

**Comment by hagen1778** [comment]
Hi @johnseekins! Thank you for so detailed issue!
Could you please provide some additional screenshots form [our dashboards](https://grafana.com/orgs/victoriametrics/dashboards):
* storage. LSM parts
* storage. Disk writes/reads 
* storage. Active merges
* resource usage. Open FDs 
* overview. Disk space used
Thank you!

**Comment by johnseekins** [comment]
active merges and lsm parts:
![Screenshot from 2021-08-05 07-51-23](https://user-images.githubusercontent.com/5665929/128361702-eabb72db-de6f-4c41-a8bf-6dc0d63b7c06.png)
writes/reads and FDs:
![Screenshot from 2021-08-05 07-49-13](https://user-images.githubusercontent.com/5665929/128361234-011d6a93-b46e-4a3a-92ac-5dd4d1cfd3b2.png)
Disk used:
![Screenshot from 2021-08-05 07-53-22](https://user-images.githubusercontent.com/5665929/128362003-70995ac2-01cc-4c5e-b6a4-b98e53d08406.png)
And a few other interesting panels:
![Screenshot from 2021-08-05 07-53-04](https://user-images.githubusercontent.com/5665929/128362062-842795b1-5e7e-4dc5-adce-f0601b5e7497.png)

There is _definitely_ a huge spike in indexdb and small merges during that time, but they seem to be symptoms (as they spike up suddenly during the event and then taper off...)

**Comment by hagen1778** [comment]
Hm, the LSM parts graph suggests VM has about 6-8k parts on disk. And "vm_hdd Objects" (if I'm reading it right) suggests there 3kk objects were deleted over the 2.5h. Which does not correlate with amount of parts either merged or deleted by VM.
The spike in ActiveMerges can be explained by RowsRerouted graph - every time vmstorage receives new time series it results into new parts for index on disk and consequent merges...

Is there any chance that some type of cronjob enabled in the OS which runs every Monday at midnight? I can recall a similar issue with cronjob for [fstrim](http://manpages.ubuntu.com/manpages/bionic/man8/fstrim.8.html#:~:text=fstrim%20is%20used%20on%20a,unused%20blocks%20in%20the%20filesystem.) process causing lags for our SSDs every week.

**Comment by johnseekins** [comment]
We can't find anything...but I'll check again. The one suspicious thing was an MD scan of the hypervisor's OS drive...but that only happens once a month..._and_ triggers two hours after the event starts.

But fstrim on the boxes _is_ scheduled for Monday at midnight!
```
root@store-1:~# systemctl status fstrim.timer
● fstrim.timer - Discard unused blocks once a week
     Loaded: loaded (/lib/systemd/system/fstrim.timer; enabled; vendor preset: enabled)
     Active: active (waiting) since Wed 2021-06-16 14:08:16 UTC; 1 months 19 days ago
    Trigger: Mon 2021-08-09 00:00:00 UTC; 3 days left
   Triggers: ● fstrim.service
       Docs: man:fstrim

Jun 16 14:08:16 store-1.datto.lan systemd[1]: Started Discard unused blocks once a week.
```
So drive trimming is causing this? That's strange, given the data drive is a ceph block device and the OS drive is an Openstack block device. But I'm ready to believe it!

**Comment by johnseekins** [comment]
This was `fstrim`. It may be worth documenting that fstrim can have an adverse affect on the system somewhere?

**Comment by hagen1778** [comment]
Hm, I'm not sure this is exactly relevant to VM. The [case I mentioned](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1521#issuecomment-893527781) happened to me 7y ago and it was a Postgres cluster suffering every Sunday because of fstrim. I was just lucky to recall it now and ask you to check if there is something similar in your system.
However, here's [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1527/commits/a85f356c7889f10bed6b75fd55d8305ce01ba843) to mention fstrim in Tuning section.

**Comment by johnseekins** [comment]
It wasn't directly _related_ to VictoriaMetrics, no. But disabling fstrim on these virtual hosts meant the weekly I/O spikes didn't happen.
