### ISSUE TITLE
VMagent see gaps at sample rate panel

### ISSUE THREAD

**Issue by veer123prathap** [VictoriaMetrics/VictoriaMetrics#1524]
Hi,
vmagent version 1.61.1
when we observe pod memory its  125mi
and CPU: 22m

**Question:**
How can we resolve gaps at the sample rate panel?
what configuration we need to add.

![IMG-8415](https://user-images.githubusercontent.com/62214817/128380025-423a2677-ae04-44bc-a2fd-49b24ee4add1.jpg)

these were reasons CPU panels getting spikes

**Comment by hagen1778** [comment]
Hi @veer123prathap!
Could you pls provide your vmagent scrape config? Are there any errors in vmagent's logs? Any chance you can share a full-length screenshot of all panels included for [vmagent dashboard](https://grafana.com/grafana/dashboards/12683)?

**Comment by veer123prathap** [comment]
![IMG-1857](https://user-images.githubusercontent.com/62214817/128560692-87a01ee5-609e-4574-ad37-d3f3856e2865.jpg)
![IMG-1858](https://user-images.githubusercontent.com/62214817/128560695-afcd4413-5f3d-4713-ad56-50c8c80a1b1f.jpg)
![IMG-1860](https://user-images.githubusercontent.com/62214817/128560696-49b23172-77d7-4d79-9cba-9373035016b8.jpg)
![IMG-1861](https://user-images.githubusercontent.com/62214817/128560700-4b34fbf0-014d-4e69-9688-069d3ce38bee.jpg)
![IMG-1859](https://user-images.githubusercontent.com/62214817/128560703-cf9ca23b-2ace-4197-a437-a05cc3256ea1.jpg)
![IMG-1856](https://user-images.githubusercontent.com/62214817/128560706-751e0140-560d-40c2-89ee-077c1e83adb7.jpg)

**Comment by hagen1778** [comment]
Hey @veer123prathap! In the slack you provided some additional info, but let's continee discussion here. Could you please check if you do not suppress any errors via `promscrape.suppressScrapeErrors` or `promscrape.suppressDuplicateScrapeTargetErrors` flags. If you do, please remove suppression and chek the logs again. Please post error logs here if any.
Please also provide your scrape configuration for vmagent and screenshot of `http://vmagent-host:8429/targets` page. Thank you!

**Comment by veer123prathap** [comment]
We have an issue with our load balancer.
we don't have any problem with vmagent
Thanks
