### ISSUE TITLE
Add staleness markers support

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1526]
**Is your feature request related to a problem? Please describe.**
VictoriaMetrics and Prometheus staleness detection is different.

VictoriaMetrics calculates [staleness](https://valyala.medium.com/evaluating-performance-and-correctness-victoriametrics-response-e27315627e87) threshold based on interval difference between datapoints timestamps (or scrape intervals).

Prometheus [staleness logic](https://www.robustperception.io/staleness-and-promql) is the following:
* if a scrape fails then all time series from the previous scrape will be marked as stale;
* if there's no samples within the 5 minutes before the evaluation, time series will be marked as stale.

VictoriaMetrics staleness detection behaves differently to Prometheus implementation for the following reasons:
* staleness should work for all [import protocols](https://docs.victoriametrics.com/#how-to-import-time-series-data), and Prometheus remote write protocol is only one of them;
* data may be ingested/backfilled into VictoriaMetrics, so "scrape" logic won't work;
* to address staleness issues for series with intervals between data points exceeding 5 minutes.

However, because of the differences, query results for stale series between Prometheus and VictoriaMetrics may differ and result into discrepancies when using VictoriaMetrics as remote storage.

**Describe the solution you'd like**
To improve compatibility with Prometheus ecosystem, VictoriaMetrics TSDB and vmagent should support staleness markers.

**Describe alternatives you've considered**
Manual queries modifications to account for staleness and resets.

**Comment by waldoweng** [comment]
so this feature is in development now?

**Comment by hagen1778** [comment]
It is not yet, but has a high priority.

**Comment by valyala** [comment]
Support for Prometheus staleness markers has been added to VictoriaMetrics in the following commits:
* Single-node: 4401464c229ec6ea7691b2ad61f91b2d8d0666f9
* Cluster version: c1f81f08d462862bea4e383c123f7ea76b8831a2

Please give it a try before it will be included into the next release of VictoriaMetrics. See [build instructions for single-node](https://docs.victoriametrics.com/#how-to-build-from-sources) and [build instructions for cluster version](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by valyala** [comment]
VictoriaMetrics and vmagent gained support for Prometheus staleness markers starting from [v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
