### ISSUE TITLE
compability VMAlert and Prometheus API for getting Alerts and Rules

### ISSUE THREAD

**Issue by aws2pizza** [VictoriaMetrics/VictoriaMetrics#1528]
For more compability with Prometheus needs to realize possibility get Alerts and Rules(alerting and recording) in Prometheus format, at this moment returned data formats of VMAlert and Prometheus are too different and also for getting this info VMAlert has 2 enpoints `/api/v1/alerts` and `/api/v1/groups` unlike Prometheus which has one endpoint `/api/v1/rules`.

For example you can add to VMAlert API additional endpoint `/api/v1/rules` for getting all Alerts and Rules in Prometheus format.

This feature is needed for more easier migration from Prometheus to VictoriaMetrics stack because some tools has hardcode for getting alerts, rules etc. from Prometheus via enpoint `/api/v1/rules`.

For example OpenShift UI metrics hardcoded to use only Prometheus API and it is not possible to get alerts and rules from VMAlert.

**Comment by valdis932** [comment]
+1

**Comment by johnalotoski** [comment]
It looks like this will be required for the new grafana unified alerts functionality also.
Current problem with VM and grafana unified alerts seems to revolve around the /api/v1/rules endpoint: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1739

**Comment by oldluke92** [comment]
+1 for this one as the new "unified alerting" in grafana which displays alerts configured in prometheus and prometheus-alertmanager does not work with victoriametrics as it currently is. For this to work properly victoriametrics would need to return the vmalert alerting rules in the prometheus format at the /api/v1/rules endpoint instead of the empty list it currently returns.

**Comment by hagen1778** [comment]
Hi! `api/v1/rules` was added in 1.75 release - see https://docs.victoriametrics.com/CHANGELOG.html#v1750

Please also see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1410
