### ISSUE TITLE
Target down but count function returns value

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#1530]
Hi VictoriaMetrics Community,

Thank you guys for resolving this issue, I meet an unexpected phenomenon querying metrics with grafana described following. 

## What I meet
I have a java app running in k8s pod and exposed Prometheus metrics. As shown in following screenshot, when the pod disappeared the query `count(app_hybrid_message_worker_active{pod="hybrid-tick-message-db56f476d-682p9"} == 1) by (pod)` still return values.

The yellow line `up...` shows that the pod did shut down and was deleted by k8s, but the count function return unexpected values.

![image](https://user-images.githubusercontent.com/8848479/129137038-f2c7a2f4-a7e6-4ee7-aed4-7e163fb43840.png)

And I also check the original time series of query `app_hybrid_message_worker_active{pod="hybrid-tick-message-db56f476d-682p9"}`, they disappeared as the pod shut down, shown in the following picture.

![image](https://user-images.githubusercontent.com/8848479/129137396-ec7fa584-cfea-431b-86fb-b364825bd8b8.png)

## Question
So I have some questions about the behavior of VM,
1. Why the count function produces result after original time series disappeared?
2. There is a spike after these time series disappeared, i.e. `5 → 7`, why did this value increase? 

Thanks!

ping @valyala 
cc @faceair

**Comment by hagen1778** [comment]
Might be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526

**Comment by valyala** [comment]
@xiaozongyang , could you build VictoriaMetrics from the commit, which adds support for Prometheus staleness markers according to [this message](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526#issuecomment-898323054) and verify whether this fixes the issue for queries over newly ingested data? Queries over already existing data may still work incorrectly. It is expected that the data is pushed to VictoriaMetrics either by Prometheus or by [vmagent](https://docs.victoriametrics.com/vmagent.html) built form the commits mentioned at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526#issuecomment-898323054 . Previous versions of `vmagent` do not generate Prometheus staleness marks when scrape target disappears.

**Comment by valyala** [comment]
FYI, VictoriaMetrics and vmagent gained support for Prometheus staleness markers starting from [the release v1.64.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by xiaozongyang** [comment]
@valyala OK, I'll try that build.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to re-open if the problem still exists.
