### ISSUE TITLE
kubelet metrics

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1531]
Hello, how to collect kubetlet metrics

**Comment by denisgolius** [comment]
Hi @WuJingLearn ! Check our [guides](https://docs.victoriametrics.com/guides/) for monitoring k8s with VM.

**Comment by WuJingLearn** [comment]
> Hi @WuJingLearn ! Check our [guides](https://docs.victoriametrics.com/guides/) for monitoring k8s with VictoriaMetrics.
How to use podscrape/servicescrape ，thanks

**Comment by valyala** [comment]
@f41gh7 , could you help with this question?

**Comment by f41gh7** [comment]
Hello, example of scraping metrics from kubelet (cadvisor), can be found at all-in-one helm chart:
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/servicemonitors/kubelet.yaml

  It easier to install this chart and observe metrics  https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack

 Or with VMNodeScrape: 
https://gist.github.com/f41gh7/1fed801c5e288e8a6bdbd931ae0f74fd#file-cadvisor-yaml

**Comment by WuJingLearn** [comment]
thanks
