### ISSUE TITLE
vmalert. disable alertgroup label 

### ISSUE THREAD

**Issue by dimakrapiva** [VictoriaMetrics/VictoriaMetrics#1532]
Vmalert add label alertgroup to alerts with send to Alertmanager
deduplication not working with prometheus Alert due to alergroup label

feature alergroup label add in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/611

**Comment by hagen1778** [comment]
Hi @dimakrapiva! Thanks for a feature request!

Please, take a look at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1534/commits/3b948642a384f7f83c3a1af479eb69817073f309. You can try to [build vmalert from sources ](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) to validate the solution.
Once merged, it will be included into the next VM release.

**Comment by valyala** [comment]
The pull request has been merged into `master` branch in the commit 9ee3d0378f6f9c4ba8d67688cf1224cda6f8db90

**Comment by valyala** [comment]
The `-disableAlertgroupLabel` command-line option is available in `vmalert` starting from [v1.65.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
