### ISSUE TITLE
VictoriaMetrics high CPU & RAM usage with extra_label

### ISSUE THREAD

**Issue by dimakrapiva** [VictoriaMetrics/VictoriaMetrics#1533]
extra_label feature use and calling /api/v1/labels & /api/v1/label/.../values high CPU/RAM usage and crash VictoriaMetrics

**Comment by hagen1778** [comment]
Hi @dimakrapiva! Could you please provide the following stats while using the labels API **with and without** extra_label func:
1. execution time
2. screenshot of VM resource usage from [dashboard](https://grafana.com/orgs/victoriametrics/dashboards)
3. the [CPU and Mem profiles ](https://docs.victoriametrics.com/#profiling)while executing the query

Thanks!

**Comment by valyala** [comment]
VictoriaMetrics uses different algorithms when locating labels via `/api/v1/labels`:
- If there are no additional filters, e.g. no `extra_label` and `match[]` filters, then the most optimized algorithm is used, which quickly scans the inverted index for unique label names. The performance of this algorithm depends only on the number of unique label names. It almost doesn't depend on the number of time series in the inverted index.
- If there are additional filters such as `/api/v1/labels?extra_label=...` or `/api/v1/labels?match[]=...`, then the slower algorithm is used, which selects all the time series matching the given `extra_label` and/or `match[]` filter on the given `start ... end` time range and then selects unique label names from the found time series. The performance of this algorithm linearly depends on the number of the matching time series on the given time range. If the number of matching time series is big, then the performance may be quite slow.

We need to think on how to improve the performance when `extra_label` and/or `match[]` query args are passed to `/api/v1/labels`.

**Comment by valyala** [comment]
@dimakrapiva , FYI, the commit 374beb350ee4af5f5a4d1a58550b2826f18d40c6 should improve performance for `/api/v1/labels` and `/api/v1/label/.../values` endpoints when non-empty `extra_label`, `extra_filters[]` or `match[]` query args are passed to them. This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
VictoriaMetrics should use lower amounts of CPU & RAM on requests to `/api/v1/labels` and `/api/v1/label/.../values` with additional filters in `extra_label`, `extra_filters[]` or `match[]` query args starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). These filters are documented [here](https://docs.victoriametrics.com/#prometheus-querying-api-enhancements).

Closing this issue as fixed.

@dimakrapiva , feel free re-opening the issue if you still see much higher CPU and RAM usage when `extra_label` query arg is passed to `/api/v1/labels` or `/api/v1/label/.../values`.

**Comment by valyala** [comment]
FYI, the `/api/v1/labels` and `/api/v1/label/.../values` endpoints should work faster starting from [VictoriaMetrics v1.79.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.3) when the `match[]` query arg passed to them matches small number of time series. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2978) for details.
