### ISSUE TITLE
bitwise operators in MetricsQL

### ISSUE THREAD

**Issue by bchess** [VictoriaMetrics/VictoriaMetrics#1541]
**Is your feature request related to a problem? Please describe.**
Some metrics have values that represent bitwise flags. `DCGM_FI_DEV_CLOCK_THROTTLE_REASONS` from [dcgm-exporter](https://github.com/NVIDIA/gpu-monitoring-tools) is one example. 

**Describe the solution you'd like**
I'd love to be able to use bitwise-and `&` to mask out metrics that match a particular bit.

**Describe alternatives you've considered**
1. Using greater-than or less-than for all common variety of combined flags
2. Exploding out each flag into its own separate metric. Workable but creates a lot more metrics

**Comment by valyala** [comment]
@bchess , the commit db1e62495be0435e2bcd75e77fe4925630679175 adds the following bitwise operations to [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html):

* `bitmap_and(q, mask)` - calculates bitwise "and": `v & mask` for every point returned from `q`.
* `bitmap_or(q, mask)` - calculates bitwise "or": `v | mask` for every point returned from `q`.
* `bitmap_xor(q, mask)` - calculated bitwise "xor": `v ^ mask` for every point returned from `q`.

This commit will be included in the next release of VictoriaMetrics. In the mean time these functions can be tested in VictoriaMetrics built from the following commits:
* Single-node: db1e62495be0435e2bcd75e77fe4925630679175 . See [build instructions](https://docs.victoriametrics.com/#how-to-build-from-sources).
* Cluster: 49886ecbc84a806a13fc11699d74384e3b5fe511 . See [build instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by bchess** [comment]
Fantastic!!

**Comment by valyala** [comment]
The `bitmap_and()`, `bitmap_or()` and `bitmap_xor()` functions are available starting from [v1.64.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
