### ISSUE TITLE
vmauth: also allow TLS client certificate authentication

### ISSUE THREAD

**Issue by pschulten** [VictoriaMetrics/VictoriaMetrics#1547]
**Is your feature request related to a problem? Please describe.**
Not a real problem. We use Hashicorp Vault for secrets. Username/Password/Bearer token cannot be defined dynamically and defining/sharing them is cumbersome.

**Describe the solution you'd like**
We'd like to use TLS client certificates which could be dynamically (and changed periodically) to separate our tenants.

Vmauth should read the `OrganizationalUnit` attribute of the client cert and should have a mapping for `ou` like the ones currently implemented for `bearer_token`/`username` & `password` for different `url_prefix`s.

**Describe alternatives you've considered**
We haven't put much thought into our multi-tenancy design, yet and use a "shared user" to view/write metrics

**Additional context**
`context deadline exceeded` :)

**Comment by YuriKravetc** [comment]
Hi @pschulten 
A follow-up on this feature request.
Feel free to update VictoriaMetrics to the latest version and let us know if this feature is still required.
If you can share your own progress/experience or workarounds on this - it would be greatly appreciated.

**Comment by valyala** [comment]
FYI, [vmauth](https://docs.victoriametrics.com/vmauth.html) will gain support for client TLS certificate verification (aka [mTLS](https://en.wikipedia.org/wiki/Mutual_authentication) ) starting from the next release (v1.98.0). See [these docs](https://docs.victoriametrics.com/vmauth/#mtls-protection).

**Comment by valyala** [comment]
FYI, the next release of `vmauth` (v1.98.0) will support mTLS-based routing of requests to different backends depending on the `Subject` field in the TLS certificate provided by the user. See [these docs](https://docs.victoriametrics.com/vmauth/#mtls-based-request-routing) for details.

**Comment by valyala** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth.html) supports mTLS-based routing starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmauth/#mtls-based-request-routing).

Closing the feature request as done.
