### ISSUE TITLE
vmbackupmanager add restore feature

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1549]
**Is your feature request related to a problem? Please describe.**
 It would be good to have an option to restore backups with `vmbackupmanager`. It also must simplify restoration at kubernetes based deployment with initContainer.

**Describe the solution you'd like**

- embed `vmrestore` into `vmbackupmanager`
-  add additional flag `--check_restore_from`, which specifies file path at disk, where user specify backup path for restoration.
- `vmbackupmanager` checks if file by given path exists. If it exists, it starts restoration from given backup path. When restore is done, it removes this file.

 It allows to run `vmbackupmanager` as constant initContainer and manually control restoration process, by creating restore file at disk.

**Describe alternatives you've considered**
 Use `vmrestore`: 
- add it as initContainer. 
- restore data
- remove it from init container.
 It can be a problem with cluster version, it leads to double cluster restart.

**Comment by valyala** [comment]
[vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager/) can restore backups starting from [v1.83.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [these docs](https://docs.victoriametrics.com/vmbackupmanager/#how-to-restore-backup-via-cli) and [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics-enterprise/pull/464).

Closing the feature request as done.
