### ISSUE TITLE
HTTP 422 is not a suitable status code to return when vmstorage is down

### ISSUE THREAD

**Issue by mattparkes** [VictoriaMetrics/VictoriaMetrics#156]
**Describe the bug**
I'm playing around with VictoriaMetrics and I was testing various failure states of the cluster version. I killed 2/2 storage nodes and VictoriaMetrics was returning [HTTP 422](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/main.go#L255) to inserts and selects, which means Prometheus was throwing my samples away rather than buffering them and retrying when it came back up.

The relevant Prometheus code is here: https://github.com/prometheus/prometheus/blob/master/storage/remote/client.go#L7

As you can see, any 5xx code will result in Prometheus retrying.

**To Reproduce**
1.) `helm install` the cluster version
2.) `kubectl scale` vmstorage to 0
3.) Check the logs and see HTTP 422 responses.

**Expected behavior**
I should receive a suitable HTTP status code such as HTTP 503.

I'm not sure that semantically HTTP 422 is the most suitable error in general, not just for inserts. I think HTTP 503 (or even just 500) is far more semantically correct and widely used for such cases.

**Comment by mattparkes** [comment]
In the meantime, I'll try putting Caddy or NGINX in front of VictoriaMetrics and having it translate 422s into 503s.

**Comment by valyala** [comment]
@mattparkes , the latest commit in [cluster branch](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster) should return 503 `ServiceUnavalable` error when all the storage nodes are unavailable.
Could you verify this?

**Comment by mattparkes** [comment]
Thanks heaps for jumping on this so fast.

I will verify this tomorrow and let you know.

**Comment by valyala** [comment]
@mattparkes , release [v1.27.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) must contain the fix for this issue. Could you verify this?

**Comment by mattparkes** [comment]
@valyala, from my quick local test, this looks to be working fine. Thanks!

**Comment by valyala** [comment]
Then closing the issue.
