### ISSUE TITLE
VMAlert: Add support for -notifier.basicAuth.passwordFile

### ISSUE THREAD

**Issue by mxsiegle** [VictoriaMetrics/VictoriaMetrics#1567]
For datasources, it's possible to provide the password via file like `-datasource.basicAuth.passwordFile`. This is not supported for the notifier option, i.e. it's only possible to provide the password directly with `-notifier.basicAuth.password`.

It would be cool if you could add support for this. Thank you very much :)

**Comment by hagen1778** [comment]
Hi @mxsiegle! Please see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2138
The PR will be included in the next release. Meanwhile you can build vmalert with this patch from sources https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources

**Comment by mxsiegle** [comment]
Thanks for adding this. Will close the issue
