### ISSUE TITLE
option to disable auto reset of result cache

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#1570]
**Is your feature request related to a problem? Please describe.**

> Single-node VictoriaMetrics automatically resets response cache when samples with timestamps older than now - search.cacheTimestampOffset are ingested to it

In our case, some remote devices may have problems (cron system, etc.) which may delay pushing metrics.

Since only a small percentage of remote devices will have the push issue, it seems acceptable to allow cache results that don't include the datapoints with old timestamps. 

**Describe the solution you'd like**
option to disable auto reset of the result cache that happens when `cacheTimestampOffset` is exceeded on incoming metric

**Describe alternatives you've considered**
Increasing `--cacheTimestampOffset`, but it isn't appealing to use a large duration accommodating all the situations, because then the cache won't be used for recent datapoints.

**Comment by valyala** [comment]
The `-search.disableAutoCacheReset` command-line option is available starting from [v1.65.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
