### ISSUE TITLE
When vmbackupmanager used call to create snapshot timeouts

### ISSUE THREAD

**Issue by eugenegoncharuk** [VictoriaMetrics/VictoriaMetrics#1571]
**Describe the bug**
Using Helm chart for Victoria Metrics from [here](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-single).
Our VM Database is quite huge and to create a snapshot it takes around 30 secs and so daily cron backup from vmbackupmanager fails to run with error.

**To Reproduce**
Create Big VM DB and try to run backupmanager it should fail with ClientTimeout waiting for response from VM Single Metrics App to create snapshot.

**Expected behavior**
Expected that snapshot is created and data gets backuped. Need to have the ability to set higher Timeout setting.

**Logs**
2021-08-25T00:00:10.972Z	info	VictoriaMetrics/app/vmbackupmanager/main.go:123	sleeping for 23h59m50s before the next backup
2021-08-26T00:00:10.988Z	error	VictoriaMetrics/app/vmbackupmanager/main.go:133	error creating backup: error creating snapshot: Post "http://localhost:8429/snapshot/create": context deadline exceeded (Client.Timeout exceeded while awaiting headers), continue

**Version**
```
vmbackupmanager-20210408-070225-tags-v1.58.0-enterprise-0-gf94ea03f4
```

**Comment by valyala** [comment]
The bugfix for the timeout error during snapshot creating has been included in [the release v1.65.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@eugenegoncharuk , feel free re-opening the issue if it still exists in `vmbackupmanager` v1.65.0 .
