### ISSUE TITLE
daily build and push to dockerhub

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#1578]
**Is your feature request related to a problem? Please describe.**
In the Victoria Metrics development process, often the reporter of a bug or feature request is asked to verify the software changes.  At least for me, often I don't have time to do a manual build and deploy (find the correct environment, install dependencies, build, push to some private docker repo, deploy to our cloud job).

**Describe the solution you'd like**
If a daily build from HEAD is pushed to dockerhub under a tag like `daily`, then most users can point to that easily with the same process used for tracking new production releases.

**Comment by f41gh7** [comment]
It can be done with github actions events https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule.

 Also, i suggest  name builds `nightly`.

**Comment by YuriKravetc** [comment]
Hi @belm0 
A follow-up on this feature request.
Can we consider it solved?
If you can share your own progress/experience or workarounds on this - it would be greatly appreciated.

**Comment by belm0** [comment]
Lately I haven't reported bugs, but the scenario is as already described.  If developers ask for confirmation of a bug fix prior to release, usually I don't do it because the process is time consuming.

**Comment by valyala** [comment]
I think that the nightly builds is just a waste of CPU at GitHub actions side and the wast of disk space resources at Dockerhub side without any visible gain. But let's see whether it will be useful after the merge of the https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3490 :)
