### ISSUE TITLE
Vmagent crd

### ISSUE THREAD

**Issue by WuJingLearn** [VictoriaMetrics/VictoriaMetrics#1579]
Hello, the replicaCount parameter of crd of vmagent, whether each node of the vmagent cluster collects data in full or fragments

**Comment by f41gh7** [comment]
Yes, its possible to increase replicas count and achieve some high-availabilty. But you have to configure `-dedup.minScrapeInterval`.

 Docs from operator page https://github.com/VictoriaMetrics/operator/blob/master/docs/high-availability.MD#vmagent

**Comment by YuriKravetc** [comment]
Hi @WuJingLearn 
A follow-up on this question.
Based on @f41gh7 reply I will consider this issue as solved and close it.
Feel free to reopen it if you still have any related questions.
