### ISSUE TITLE
Context canceled log message

### ISSUE THREAD

**Issue by ngpadp12** [VictoriaMetrics/VictoriaMetrics#1581]
Using vmselect and vmalert for an alerting solution.

Both are located in different AWS accounts.

vmalert uses rule files to query vmselect, but isn't able to complete its query due to the following error:

> info	VictoriaMetrics/app/vmalert/group.go:229	group "Infra metrics": context cancelled

This is followed by number of error log messages, one for each query present in the rules.file.yml.

> error	VictoriaMetrics/app/vmalert/group.go:256	group "Infra metrics": rule "Kafka_OfflinePartitionsCount": failed to execute: failed to execute query "(sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"kafka\"})by (StackName)) != 0": error getting response from https://xyz.com:8481/select/123/prometheus/api/v1/query?query=%28sum%28kafka_controller_kafkacontroller_offlinepartitionscount%7Bjob%3D%22kafka%22%7D%29by+%28StackName%29%29+%21%3D+0&step=1m0s&time=1630323180: Post "https://xyz.com:8481/select/123/prometheus/api/v1/query?query=%28sum%28kafka_controller_kafkacontroller_offlinepartitionscount%7Bjob%3D%22kafka-perf%22%7D%29by+%28StackName%29%29+%21%3D+0&step=1m0s&time=1630323180": context canceled

I am not sure if this in some way is a timeout issue.
Also, I observed that vmselect logs slow queries that the vmalert component tries to execute on vmselect.

What could be the reason for this issue?

**Comment by hagen1778** [comment]
Hi @ngpadp12! This error means that vmalert has been stopped by receiving SIGTERM signal. When this happens, vmalert propagates context cancellation to all rules which are evaluating in that moment to stop them. Please, check the logs for message "service received signal" to verify the assumption.
