### ISSUE TITLE
Data problem return error instead of skip data

### ISSUE THREAD

**Issue by vahid-sohrabloo** [VictoriaMetrics/VictoriaMetrics#159]
Why if data has a problem like in not range of time skip data and not return an error?

**Comment by valyala** [comment]
Currently such errors are tracked in `vm_rows_ignored_total` metric on the `/metrics` page - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring for details.

I think it would be great reporting the error additionally to the counting such errors in the metric mentioned above.

**Comment by valyala** [comment]
Added error reporting for timestamps outside retention in the commit 0dc0006f34b22a90ec90695e915dbb9cfcdbc060 . It will be available in the next release.

**Comment by valyala** [comment]
Oops, the commit title has been improperly copy-pasted from the previous comment :( But the commit body is correct :)

**Comment by vahid-sohrabloo** [comment]
Oh, good. thanks @valyala

**Comment by valyala** [comment]
@vahid-sohrabloo , the issue should be fixed in [v1.27.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Could you confirm this?

**Comment by vahid-sohrabloo** [comment]
Yes. It's fixed
