### ISSUE TITLE
Why vminsert limit the size of vmstorage addresses to 255

### ISSUE THREAD

**Issue by bleedfish** [VictoriaMetrics/VictoriaMetrics#1599]
In code of app/vminsert, We can see this:  
    app\vminsert\netstorage\netstorage.go:  func InitStorageNodes:
       if len(addrs) > 255 {
		logger.Panicf("BUG: too much addresses: %d; max supported %d addresses", len(addrs), 255)
	  }

  but in vmselect, we can configured more than 255 storageNode addresses to use.  
  I wonder why it must limit to  255 ?

**Comment by valyala** [comment]
This limit was set long time ago due to historical reasons. It has little sense now. So it has been removed in the commit dca6f0f7de9d1e379cfe7a80477c53a966f0043d .

**Comment by YuriKravetc** [comment]
Hi @bleedfish 
A follow-up on this question.
Based on the reply above I will consider this issue as solved and close it.
Feel free to reopen it if you still have any related questions.
