### ISSUE TITLE
About We tried using ClickHouse as a remote storage for Prometheus

### ISSUE THREAD

**Issue by lyl2008dsg** [VictoriaMetrics/VictoriaMetrics#16]
Hi,valyala.
Thank you very much for sharing. I following you.
I'm doing what you did.  As you said : [https://medium.com/devopslinks/victoriametrics-creating-the-best-remote-storage-for-prometheus-5d92d66787ac](url)

When I tried to implement promql counter with clickhouse, but it didn't have lag () or lead ().

e.g   https://rextester.com/ERTQ26880

Hope to get your help ,  how to realize Counter of Prometheus with CK .

Thanks very much

**Comment by valyala** [comment]
See how `$rate` and `$rateColumns` is implemented in [clickhouse-grafana](https://github.com/Vertamedia/clickhouse-grafana).

**Comment by valyala** [comment]
I'm closing this issue, since it isn't related to VictoriaMetrics.
@lyl2008dsg , feel free re-opening the issue if you have additional questions.
