### ISSUE TITLE
ql function rollup_candlestick/query return differences

### ISSUE THREAD

**Issue by hi-wayne** [VictoriaMetrics/VictoriaMetrics#1600]
**Describe the bug**
query1
http://127.0.0.1:8428/api/v1/query_range?query=rollup_candlestick({service=%22trade-service%22})&start=1630990811&end=1630990911&step=3600

query2
http://127.0.0.1:8428/api/v1/query_range?query=rollup({service=%22trade-service%22})&start=1630990811&end=1630990911&step=60

return json …
{
    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "__name__": "monitor_duration",

"__name__"  field only in query2 retrun

**Version**
victoria-metrics-20210901-141452-tags-v1.65.0-0-gf529058d3

**Used command-line flags**
 -selfScrapeInterval 1s -retentionPeriod 7d -storageDataPath /data1/victoria-data -memory.allowedPercent 80

**Comment by valyala** [comment]
This is a bug, which has been fixed in the commit ea943911bccbc74fcb612f282c5a3be7ca639f71  . This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
The bugfix has been included in [VictoriaMetrics v1.66.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Now `rollup_candlestick()` should keep the original metric names.

Closing the issue as fixed.
