### ISSUE TITLE
MetricQL returns wrong results

### ISSUE THREAD

**Issue by chenlujjj** [VictoriaMetrics/VictoriaMetrics#1601]
**Describe the bug**

When using MetricQL with no-exist label keys, it returns wrong results.

**To Reproduce**

We have a metric named `http_probe_success_rate`, and it DOES NOT have labels named `foo` and `bar`
(1) when the MetricQL is `http_probe_success_rate{foo=~"", bar=~""}`,it returns all results
(2) when the MetricQL is `http_probe_success_rate{foo=~"xxx|", bar=~""}`,it returns all results
![图片](https://user-images.githubusercontent.com/17081528/132336749-8fd9f8ed-4b01-463d-8b26-c61cc26c79f0.png)

(3) when the MetricQL is `http_probe_success_rate{foo=~"xxx|", bar=~"yyy|"}`,it returns NO results at all.
![图片](https://user-images.githubusercontent.com/17081528/132336824-7861a719-4a23-45b9-9ec8-d1ec0bc01277.png)

This behavior is out of expect and not consistent with PromQL:
![图片](https://user-images.githubusercontent.com/17081528/132336908-c6e91272-b4fb-411c-a823-154e1a0d12c0.png)

**Version**
vmstorage version is v1.60.0,
vmselect version is v1.62.0

**Comment by valyala** [comment]
@chenlujjj , thanks for the bug report! Confirmed that the bug exists in the latest release.

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/395

**Comment by valyala** [comment]
The bug should be fixed in the commit c2f37f049b7df542841f978d1cf4bf200b064ec1 . This commit will be included in the next release.

@chenlujjj , could you build cluster components of VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verify whether this fixes the issue?

**Comment by chenlujjj** [comment]
@valyala I have built the latest cluster VM and validated that this bug is fixed. Thanks very much for your quick reply and effort !

**Comment by valyala** [comment]
@chenlujjj , thanks for the confirmation! The bugfix has been included in [v1.66.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
