### ISSUE TITLE
Incorrect transformation of the InfluxDB data

### ISSUE THREAD

**Issue by vc43** [VictoriaMetrics/VictoriaMetrics#1604]
**Describe the bug**
I'm trying to send data from [k6 ](https://k6.io/docs/results-visualization/influxdb-+-grafana) and [Yandex.tank](https://yandextank.readthedocs.io/en/latest/core_and_modules.html#influxdb) to InfluxDB interface of the vminsert module.
I created locations in the nginx:
```
        location /query {
            proxy_pass vminsert-upstream/insert/1/influx/write;
        }
        location /write {
            proxy_pass vminsert-upstream/insert/1/influx/write;
       }
```
It helps to send data from k6 and Yandex.tank without errors. 
After run k6 or Yandex.tank I try to query some data (for example in Grafana Explore) but I get empty metrics.

**To Reproduce**
Configure nginx as in the example above. Create dataset in Grafana: http://nginx_host:vminsert_port/select/1/prometheus
Run k6:
`
k6 run -o influxdb=http://nginx_host:vmselect_port/k6_tests ./k6.js
`
Content of the ./k6.js:
```
import http from 'k6/http';

export let options = {
  discardResponseBodies: true,
  scenarios: {
    contacts: {
      executor: 'ramping-vus',
      startVUs: 2,
      stages: [
        { duration: '5s', target: 2},
      ],
      gracefulRampDown: '0s',
    },
  },
};

export default function () {
  http.get(`https://www.ya.ru`);
}

```

Try to Explore data in Grafana

**Expected behavior**
Grafana shows more than one (none zero) values http_req_duration for time range.

**Version**
VictoriaMetrics docker image tag: "v1.61.0-cluster"

**Comment by valyala** [comment]
@vc43 , could you look at logs for cluster components of VictoriaMetrics during the data ingestion? Probably they contain details on what was going wrong.

**Comment by vc43** [comment]
@valyala, there is no new logs in `vminsert`, `vmselect` and `vmstorage`. 
I found that `curl` request returns different data structure when I request prometheus-like data and InfluxDB. 
for prometheus-like it's:
```
{"metric":{"__name__":"node_cpu_seconds_total",...},"values":[[1632125047.781,"423057.99"],[1632125062.781,"423057.99"],...}
```
for InfluxDB:
```
{"metric":{"__name__":"http_reqs_url",...},"values":[0,0,...],"timestamps":[1631775417482,1631775417530,...]}
```
So values and timestamps looks differently. It's normal?

**Comment by hagen1778** [comment]
@vc43 Please see how ingestion works in VictoriaMetrics here https://docs.victoriametrics.com/guides/migrate-from-influx.html#write-data
If you find it incorrect or if it doesn't work for your case - feel free to reopen or create a new issue.
