### ISSUE TITLE
Missing metrics in VictoriaMetrics Cluster Per Tenant Statistic

### ISSUE THREAD

**Issue by jeremyrios** [VictoriaMetrics/VictoriaMetrics#1605]
Opening this Bug Request per @tenmozes direction in this [Slack thread](https://victoriametrics.slack.com/archives/CH98WTB3R/p1631121303034900)

CC. @f41gh7 @valyala 

## **Describe the bug**
We ’re evaluating vm-enterprise-cluster and Im having an issue with the [VictoriaMetrics Cluster Per Tenant Statistic](https://docs.victoriametrics.com/PerTenantStatistic.html) feature

The following metrics are exposed as expected
```
vminsert
    vm_tenant_inserted_rows_total 
vmselect
    vm_tenant_select_requests_duration_ms_total 
    vm_tenant_select_requests_total 
vmstorage
    vm_tenant_active_timeseries 
    vm_tenant_timeseries_created_total
```
but this one for `vmstorage` is not
```
vmstorage
    vm_tenant_used_tenant_bytes
```
I've port forward the vmstorage pods and directly inspected their `/metrics` endpoint and only see the following `vm_tenant_` metrics:
```
vm_tenant_active_timeseries{accountID="0",projectID="0"} 226888
vm_tenant_active_timeseries{accountID="1",projectID="0"} 338982
vm_tenant_timeseries_created_total{accountID="0",projectID="0"} 79920
```
Also, not sure why `vm_tenant_timeseries_created_total` is only publishing a metric for 1 tenant. 
Any idea whats going on here?
Is there something I’m missing?

## **Logs**
There is no warnings or errors being logged. Only normal `info` messages.

## **Version**
Im running latest tagged v1.65.0-enterprise-cluster images for all 3 services.
```
vmstorage-20210901-143604-tags-v1.65.0-enterprise-cluster-0-gf2d969c73
vmselect-20210901-143531-tags-v1.65.0-enterprise-cluster-0-gf2d969c73
vminsert-20210901-143443-tags-v1.65.0-enterprise-cluster-0-gf2d969c73
```

## **Used command-line flags**
vmstorage:
```
--retentionPeriod=13 --storageDataPath=/storage --eula=true
```
vmselect:
```
--cacheDataPath=/cache --storageNode=vmstorage-0.vmstorage.tsdb.svc.cluster.local:8401 --storageNode=vmstorage-1.vmstorage.tsdb.svc.cluster.local:8401 --storageNode=vmstorage-2.vmstorage.tsdb.svc.cluster.local:8401 --dedup.minScrapeInterval=1ms --eula=true --search.latencyOffset=15s --search.maxStalenessInterval=60s`
```
vminsert:
```
--storageNode=vmstorage-0.vmstorage.tsdb.svc.cluster.local:8400 --storageNode=vmstorage-1.vmstorage.tsdb.svc.cluster.local:8400 --storageNode=vmstorage-2.vmstorage.tsdb.svc.cluster.local:8400 --eula=true --maxLabelsPerTimeseries=50 --relabelConfig=/etc/vminsert/relabel/config/relabel.yml --replicationFactor=1
```

**Comment by valyala** [comment]
The code for the `vm_tenant_used_tenant_bytes` metric wasn't merged into the enterprise branch yet because of a few issues, which should be resolved soon.

**Comment by VRay27** [comment]
@valyala  Is there an alternate way to achieve the said metrics while the issue gets fixed?

**Comment by valyala** [comment]
The only alternative is to manually set up routing for per-tenant data to distinct vmstorage nodes, so each vmstorage node would contain data for a particular tenant or a group of tenants. Then the per-tenant disk usage stats can be obtained from individual vmstorage nodes.

**Comment by jeremyrios** [comment]
@valyala  It's been 2 months, have those few issues been resolved?

> The code for the `vm_tenant_used_tenant_bytes` metric wasn't merged into the enterprise branch yet because of a few issues, which should be resolved soon.

**Comment by valyala** [comment]
> Also, not sure why vm_tenant_timeseries_created_total is only publishing a metric for 1 tenant.

This metric is incremented only when new time series are created for the given tenant since the last `vmstorage` restart. If the given tenant didn't create new time series since `vmstorage` restart, then it won't have the `vm_tenant_timeseries_created_total` metric.

The `vm_tenant_used_tenant_bytes` metric (aka an approximate per-tenant disk usage) will be available in the next release. This metric is available for testing and evaluation in the docker image tag `heads-enterprise-cluster-0-g08359c037`.

VictoriaMetrics doesn't populate per-tenant disk usage stats for already existing data due to performance reasons - it may take non-trivial amounts of time, disk IO and CPU resources for populating this stats across terabytes of existing data. The per-tenant disk usage stats is populated for newly ingested data. The stats is updated every 7 seconds.

**Comment by valyala** [comment]
FYI, the `vm_tenant_used_tenant_bytes` metric should be available in enterprise version of `vmstorage` component starting from [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by nulldoot2k** [comment]
Now i still missing metrics 
- vm_tenant_timeseries_created_total
