### ISSUE TITLE
[vmslect]Help needs to log slow queries or link to jaeger

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#1629]
As original Prometheus, it reports all queries spins and thanos also reports queries spin to jaeger. This make the slow queries finding very easy. Zabbix also log slow log to log file.

Is this possible to out put more information about slow queries on vmselect?

**Comment by hagen1778** [comment]
Hi @renchili! Have you checked `-search.logSlowQueryDuration` flag?
```
 -search.logSlowQueryDuration duration
    	Log queries with execution time exceeding this value. Zero disables slow query logging (default 5s)
```

**Comment by renchili** [comment]
thanks a lot we have enabled the  slowQuery log, well log is helpful but it did not come with the full information such as "referral".
We still needs to look into other system as we use is nginx, there no tracing id so the log searching will be a little bit complex

**Comment by renchili** [comment]
any update about adding more tracking information or kept the client requests information when the query is slow?

**Comment by YuriKravetc** [comment]
Hi @renchili 
A follow-up on this feature request.
Feel free to update VictoriaMetrics to the latest version and let us know if this feature is still required as there were some updates regarding slow query tracking.
If you can share your own progress/experience or workarounds on this - it would be greatly appreciated.

**Comment by renchili** [comment]
thanks  can consider with this  
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/819

**Comment by renchili** [comment]
@YuriKravetc  hi  may we use jaeger as the solution to tracking the slow query?
is too hard to tracking the comming query source. cuase in vmselect log  only know the final query QL is not enough.
some user cases came with grafana panel set up with label value discover, which, vmselect did not write much more information, is hard to know where came this query.

**Comment by hagen1778** [comment]
@renchili could you provide an example of the log message with spins related to the slow query from Prometheus or Thanos? Thank you!
