### ISSUE TITLE
Possible bug? enterprise vs. OSS version string in metrics...

### ISSUE THREAD

**Issue by johnseekins** [VictoriaMetrics/VictoriaMetrics#1635]
Both the enterprise and OSS versions of VictoriaMetrics return the same version in `vm_app_version{short_version!=""}`. So it's difficult to differentiate between the versions of the program. Should we have `-enterprise` returned in the enterprise version?

**To Reproduce**
Collect metrics from both enterprise and OSS versions of VictoriaMetrics

**Expected behavior**
Possible to discern which instances are enterprise and which are OSS

**Comment by valyala** [comment]
The `short_version` label will contain `-enterprise` and/or `-cluster` suffixes in the next release. See the corresponding commit 9ca1cbced1d783a4889654f0c34ec4796c2373cb .
