### ISSUE TITLE
vmctl can't export from single to cluster

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#1637]
I would like to migrate from single node to cluster and keep my data but i have this issue.

**To Reproduce**
./vmctl-prod vm-native --vm-native-src-addr=http://x.x.x.x:8428 --vm-native-dst-addr=http://x.x.x.x:8480 --vm-native-filter-time-start='2021-09-16T10:00:00Z'
VictoriaMetrics Native import mode
Initing export pipe from "http://x.x.x.x:8428" with filters:
        filter: match[]={__name__!=""}
        start: 2021-09-16T10:00:00Z
Initing import process to "http://x.x.x.x:8480":
2021/09/21 13:35:25 import request failed: unexpected response code 400: remoteAddr: "x.x.x.x:49608"; requestURI: /api/v1/import/native; unsupported path requested: "/api/v1/import/native"

**Version**
```
./vmctl-prod --version
vmctl version vmctl-20210920-122501-tags-v1.66.0-0-g76811c2f6
2021/09/21 13:44:47 Total time: 204.641µs

docker exec -it victoriametrics /victoria-metrics-prod -version
victoria-metrics-20210920-122706-tags-v1.66.0-0-g76811c2f6

docker exec -it vminsert /vminsert-prod -version
vminsert-20210920-123448-tags-v1.66.0-cluster-0-gd43ebb831
```

**Comment by hagen1778** [comment]
Hi @xenofree! Please see importing tips here https://docs.victoriametrics.com/vmctl.html#native-protocol:
```
When importing into cluster version it is additionally required to specify the --vm-account-id flag. See more details for cluster version here.
```

**Comment by xenofree** [comment]
Hi,

Thanks for the answer, version 1.66.0 don't seems to understand this flag

```
vmctl-prod vm-native --vm-native-src-addr=http://x.x.x.x:8428 --vm-native-dst-addr=http://x.x.x.x:8480 --vm-native-filter-time-start='2021-09-16T10:00:00Z' --vm-account-id=0
Incorrect Usage: flag provided but not defined: -vm-account-id

NAME:
   vmctl-prod vm-native - Migrate time series between VictoriaMetrics installations via native binary format

USAGE:
   vmctl-prod vm-native [command options] [arguments...]

OPTIONS:
   --vm-native-filter-match value  Time series selector to match series for export. For example, select {instance!="localhost"} will match all series with "instance" label different to "localhost".
 See more details here https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-export-data-in-native-format (default: "{__name__!=\"\"}")
   --vm-native-filter-time-start value  The time filter may contain either unix timestamp in seconds or RFC3339 values. E.g. '2020-01-01T20:07:00Z'
   --vm-native-filter-time-end value    The time filter may contain either unix timestamp in seconds or RFC3339 values. E.g. '2020-01-01T20:07:00Z'
   --vm-native-src-addr value           VictoriaMetrics address to perform export from.
 Should be the same as --httpListenAddr value for single-node version or vmselect component. If exporting from cluster version see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format
   --vm-native-src-user value      VictoriaMetrics username for basic auth [$VM_NATIVE_SRC_USERNAME]
   --vm-native-src-password value  VictoriaMetrics password for basic auth [$VM_NATIVE_SRC_PASSWORD]
   --vm-native-dst-addr value      VictoriaMetrics address to perform import to.
 Should be the same as --httpListenAddr value for single-node version or vminsert component. If importing into cluster version see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format
   --vm-native-dst-user value      VictoriaMetrics username for basic auth [$VM_NATIVE_DST_USERNAME]
   --vm-native-dst-password value  VictoriaMetrics password for basic auth [$VM_NATIVE_DST_PASSWORD]
   --vm-extra-label value          Extra labels, that will be added to imported timeseries. In case of collision, label value defined by flagwill have priority. Flag can be set multiple times, to add few additional labels.
   --help, -h                      show help (default: false)

2021/09/22 10:15:52 flag provided but not defined: -vm-account-id
```

**Comment by hagen1778** [comment]
Oh, you're totally right and I'm not. For `native` mode there is no need in vm-account-id. It is assumed that user will specify accountID in the dst-addr. Apparently, it is so because both `src` and `dst` could be cluster versions, hence  `vm-account-id` can't define both URLs. 
Sorry for confusion - I'll update docs to make the usage clear.

Please, for now just use the following command:
```
vmctl-prod vm-native --vm-native-src-addr=http://x.x.x.x:8428 --vm-native-dst-addr=http://x.x.x.x:8480/insert/0/prometheus  --vm-native-filter-time-start='2021-09-16T10:00:00Z'
```

**Comment by xenofree** [comment]
Thx @hagen1778, i still have an issue.
import is crashing either because of native block size or metricName size

```
2021-09-22T14:29:06.894Z        warn    VictoriaMetrics/app/vminsert/main.go:223        remoteAddr: "x.x.x.x:60448"; requestURI: /insert/0/prometheus/api/v1/import/native; cannot read native block with size 168 bytes: unexpected EOF
2021-09-22T14:30:58.718Z        warn    VictoriaMetrics/app/vminsert/main.go:223        remoteAddr: "x.x.x.x:60454"; requestURI: /insert/0/prometheus/api/v1/import/native; cannot read metricName with size 195 bytes: unexpected EOF
```

**Comment by hagen1778** [comment]
Hi @xenofree! That would likely due to the `src` broke the connection for some reason. Is it possible to check logs of the `src` VictoriaMetrics?

**Comment by xenofree** [comment]
You are right ```src``` is killed by kernel

```
Sep 23 09:36:42 kernel: [2390971.083174] Out of memory: Kill process 20537 (victoria-metric) score 521 or sacrifice child
Sep 23 09:36:42 kernel: [2390971.083686] Killed process 20537 (victoria-metric), UID 0, total-vm:108251464kB, anon-rss:4165528kB, file-rss:0kB, shmem-rss:0kB
```

Is there a way to limit this behavior or do i have to add RAM on my machine ?

**Comment by hagen1778** [comment]
The memory consumption, unfortunately, can't be limited. The reason is that VM needs to locate all the series before exporting, and it basically like reading everything. So the easiest way just to add more memory. We'll think how we can improve that.
The workarounds are following:
* split importing into parts by time or/and by search query
* split by time helps if you have noticeable churn rate (series are frequently changing and are present only during short durations of time). If so, limiting the time range will reduce number of series to export at once
* split by search filter. Like exporting job-by-jobs (or multiple jobs) to reduce the number of series exported at once.

**Comment by xenofree** [comment]
I understand, i added RAM to my server and it's working.
Thanks @hagen1778 for your help !

**Comment by valyala** [comment]
Closing this issue as resolved.
