### ISSUE TITLE
metrics will lose when push them to vmagent if relabeling is on

### ISSUE THREAD

**Issue by ctdsyz** [VictoriaMetrics/VictoriaMetrics#1638]
Not sure if this is a bug..
 
**docker-compose.yml**
version: '3.5'
services:
  vmagent-push:
    container_name: vmagent-push
    image: victoriametrics/vmagent:v1.66.1
    ports:
      - 8429:8429
    volumes:
      - /data/xxx/conf:/vmagentconf
      - /data/xxx/data:/vmagentdata
    command:
      - '--promscrape.config=/vmagentconf/prometheus.yml'
      - '--remoteWrite.multitenantURL=http://xxx.xxx.xxx.xxx:8480'
      - '--remoteWrite.tmpDataPath=/vmagentdata'
      - '--remoteWrite.urlRelabelConfig=/vmagentconf/filter.yml'
      - '--remoteWrite.urlRelabelDebug'
    restart: always

**filter.yml**
\- action: keep_metrics
&nbsp;&nbsp;&nbsp;regex: "xxx"

**Test**
curl -d 'xxx{bar="baz"} 123' -X POST 'http://127.0.0.1:8429/insert/<accountID\>/prometheus/api/v1/import/prometheus'

**Result**
Relabeling works well, but then
curl 'http://127.0.0.1:8481/select/<accountID\>/prometheus/api/v1/export?start=-1m' -d 'match={\_\_name\_\_="xxx"}'
there's no metrics

**Comment by valyala** [comment]
The `-remoteWrite.urlRelabelDebug` option drops all the metrics after writing the debug information into log. This behaviour is documented at https://docs.victoriametrics.com/vmagent.html#relabeling .

**Comment by ctdsyz** [comment]
> The `-remoteWrite.urlRelabelDebug` option drops all the metrics after writing the debug information into log. This behaviour is documented at https://docs.victoriametrics.com/vmagent.html#relabeling .

Thank you.  @valyala  I removed -remoteWrite.urlRelabelDebug
