### ISSUE TITLE
Log entry for metrics having prometheus annotations are missing in vm-agent

### ISSUE THREAD

**Issue by amalsom10** [VictoriaMetrics/VictoriaMetrics#1651]
**Describe the bug**
We are working on migrating from our existing Prometheus single node to victoriametrics for monitoring. 

****Configuration****
Platform : GKE 
Prometheus Operator: v0.46.0
Victoriametrics version: v1.66.0 (Not Operator)

****Using Prometheus****
We are using a single GKE cluster for all the applications. The Prometheus in the cluster is able to scrape metrics using the following k8 pod annotations:
```prometheus.io/path,
  prometheus.io/port,
  prometheus.io/scheme,
  prometheus.io/scrape
```

The above Prometheus metric port and the application listening ports are different. The interesting part is that the metric port is not exposed in the pod configuration, but still, Prometheus is able to scrape metrics from the application metric port. 

****Using Victoriametrics****
After we switch to victoriametrics,  these metrics are not working. In order to resolve the issue, I have exposed the metric port in the pod configuration and now vmagent is able to scrape the metrics from the application pod with the same annotation given above.

In vmagent no errors were spotted in the logs, but in the case of Prometheus this might end up as an error after attempting to scrape. 

Attaching the pods running for vm-agent:

```NAME                                      READY   STATUS    RESTARTS   AGE
pod/vmagent-cluster-0                     1/1     Running   0          8h
pod/vmagent-cluster-1                     1/1     Running   0          8h
pod/vmagent-cluster-2                     1/1     Running   0          8h
pod/vmcluster-vminsert-7d6db54bc9-9kn4z   1/1     Running   0          8h
pod/vmcluster-vminsert-7d6db54bc9-fffzs   1/1     Running   0          8h
pod/vmcluster-vmselect-6978dcb449-kmnzw   1/1     Running   0          8h
pod/vmcluster-vmselect-6978dcb449-q8hqs   1/1     Running   0          8h
pod/vmcluster-vmstorage-0                 1/1     Running   0          8h
pod/vmcluster-vmstorage-1                 1/1     Running   0          8h
pod/vmcluster-vmstorage-2                 1/1     Running   0          8h
pod/vmcluster-vmstorage-3                 1/1     Running   0          8h
pod/vmcluster-vmstorage-4                 1/1     Running   0          8h
```

Attaching the scrape config: 
We just used the default configuration available [here](https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-cluster.html#3-install-vmagent-from-the-helm-chart)

**To Reproduce**
- Create a pod in GKE with different ports for application and metrics and expose only the application pod.
- Add the above annotation for the pod.
- Check the logs whether it's showing any errors related to the above target pods.

**Expected behavior**
- There should be logs in the error logs showing that the metrics port in the annotation is not reachable. 
- if vmagent is doing a check on each target and the target got mapped to dropped targets if not working using the metric port in annotations. Then it will be helpful if there is an error log stating that the target is unreachable.

**Logs**
There were no logs in the vmagent component that the metrics port fetched from the pod annotations are unreachable.

**Version**
```
victoriametrics/vmagent:v1.66.0
victoriametrics/vmselect:v1.66.0-cluster
victoriametrics/vminsert:v1.66.0-cluster
`victoriametrics/vmstorage:v1.66.0-cluster`
```

**Used command-line flags**
```
-promscrape.config=/config/scrape.yml \
 -promscrape.maxDroppedTargets=3000 \
-promscrape.maxScrapeSize=90000000 \
-promscrape.streamParse \
-promscrape.cluster.replicationFactor=2 \
-promscrape.cluster.membersCount=3 \
-promscrape.cluster.memberNum=${PROMSCRAPE_CLUSTER_MEMBER_NUM} \
-remoteWrite.tmpDataPath=/vmagentData \
-remoteWrite.url=URL \
-envflag.enable=true \
-envflag.prefix=VM_ \
-loggerFormat=json
```

**Comment by f41gh7** [comment]
Hello, key issue with default configuration, it uses following relabeling rule:
```
- action: keep_if_equal
  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port, __meta_kubernetes_pod_container_port_number]
```

 Which expects pod to export port for scraping. Its needed to suppress "duplicate target error", which usually mean, that something wrong happen with your configuration. Prometheus doesn't log such error and silently drops duplicate targets.

 You can remove such relabeling rules and get the same behavior as with prometheus.

**Comment by amalsom10** [comment]
@f41gh7 thanks for the response! I will test it and update the findings here.
