### ISSUE TITLE
Influx Line Write POSTs with Timestamps are not written

### ISSUE THREAD

**Issue by janemrich** [VictoriaMetrics/VictoriaMetrics#167]
**Describe the bug**
Influx Line Write POSTs with timestamps are not written to VictoriaMetrics.

**To Reproduce**
Use the example from the test and run it in curl:
`curl -d 'system,host=ip-172-16-10-144 uptime_format="3 days, 21:01",quoted_float="-1.23",quoted_int="123" 1557761040000000000' -X POST 'http://localhost:8428/write'`

**Expected behavior**
Data is being inserted with Timestamp.

**Version**
v1.26.0

**Comment by valyala** [comment]
It looks like your timestamp goes outside the allowed retention - see `vm_rows_ignored_total` metrics on the `/metrics` page. The upcoming release will emit error message for timestamps outside the allowed retention - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/159

**Comment by valyala** [comment]
See also [backfilling section](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling) in the README.md.

**Comment by valyala** [comment]
@janemrich , try [v1.27.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release - it should log errors on timestamp out of the configured retention.

**Comment by janemrich** [comment]
ok, thank you
