### ISSUE TITLE
Unbalanced data in multi-level cluster when importing metrics with vmimport protocol

### ISSUE THREAD

**Issue by ubcharron** [VictoriaMetrics/VictoriaMetrics#1672]
**Describe the bug**

We have a multi-level cluster spanning three AZs, following the model documented [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup). Each AZ has 4 vmstorage nodes. If the top-level vminsert runs with replicationFactor=3, all samples get distributed equally among the 4 vmstorage nodes in each AZ. 

However, if the top-level vminsert runs with replicationFactor=2, then the spread is very skewed in each AZ. Some vmstorage nodes get most of the samples, and some get almost none. But this **only** happens with data imported through "vmctl prometheus". Data received through the prometheus remote-write protocol gets distributed equally among all nodes of each AZ.

Feels like a weird interaction of the jump hash between the two vminsert levels.

**Expected behavior**

vmstorage nodes in each AZ should fill-up equally, no matter the protocol used to receive samples.

**Screenshots**

Screenshot of ingestion rate during two vmctl prometheus imports. (Same timeseries in both imports.)

19:42 to 19:48 is with replicationFactor=3. All vmstorage receive roughly the same amount of samples/s.
19:48 to 19:56 is with replicationFactor=2. Notice how skewed the fill-rate is, and how one vmstorage in every AZ is receiving almost nothing. (I think those 11k/s are entirely from prometheus remote-write, and none from vmimport).

![image](https://user-images.githubusercontent.com/8988813/135916037-7dfa7147-2810-457b-ae91-569f2456d44c.png)

**Version**

vminsert-20210920-123448-tags-v1.66.0-cluster-0-gd43ebb831 (victoriametrics/vminsert:v1.66.0-cluster)

**Used command-line flags**
Top vminsert:

            "-storageNode=localhost:18601",
            "-storageNode=localhost:18602",
            "-storageNode=localhost:18603",
            "-envflag.enable=true",
            "-envflag.prefix=VM_",
            "-loggerFormat=json",
            "-opentsdbHTTPListenAddr=0.0.0.0:4242",
            "-opentsdbListenAddr=0.0.0.0:4243",
            "-replicationFactor=2"

Bottom vminserts:

vminsert-az1:

            "-clusternativeListenAddr=0.0.0.0:18601",
            "-envflag.enable=true",
            "-envflag.prefix=VM_",
            "-loggerFormat=json",
            "-replicationFactor=1",
            "-storageNode=az1-1:8400,az1-2:8400,az1-3:8400,az1-4:8400"

vminsert-az2:

            "-clusternativeListenAddr=0.0.0.0:18602",
            "-envflag.enable=true",
            "-envflag.prefix=VM_",
            "-loggerFormat=json",
            "-replicationFactor=1",
            "-storageNode=az2-1:8400,az2-2:8400,az2-3:8400,az2-4:8400"

vminsert-az3:

            "-clusternativeListenAddr=0.0.0.0:18603",
            "-envflag.enable=true",
            "-envflag.prefix=VM_",
            "-loggerFormat=json",
            "-replicationFactor=1",
            "-storageNode=az3-1:8400,az3-2:8400,az3-3:8400,az3-4:8400"

**Comment by hagen1778** [comment]
Hi! It really looks like "weird interaction of the jump hash between the two vminsert levels". We'll check how we can re-seed the hash function in case if multi-layer topology is used (if `clusternativeListenAddr` is set or by introducing a new flag), Thanks for reporting this!
As a workaround, I think adding/removing vmstorage node from 2nd layer could result into much better distribution.
