### ISSUE TITLE
vmui restores previous query in a new browser session

### ISSUE THREAD

**Issue by Nastradamus** [VictoriaMetrics/VictoriaMetrics#1694]
**Describe the bug**

In the VM single **1.67** I see a bug: if open a new tab in browser with `/vmui`, it restores previous query from cookies (I think).

**To Reproduce**
- Open `http://instance-ip:8189/vmui/`
- Enable Autocomplete
- Perform a PromQL query
- Open a new tab and open `http://instance-ip:8189/vmui/` : vmui will execute query from previous session

This is also confirmed in the private browser mode.

**Expected behavior**
No saved queries in cookies.

**Version**
```
victoria-metrics-prod --version
victoria-metrics-20211008-135230-tags-v1.67.0-0-g6058edb0d
```

**Comment by valyala** [comment]
@Loori-R , could you look into this issue?

**Comment by valyala** [comment]
The issue must be fixed in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c6d592728161f88fe17a183750fb01bdf78538f6 , which will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
`vmui` shouldn't persist queries across restarts starting from [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
