### ISSUE TITLE
Vmagent http_sd_configs section dont work.

### ISSUE THREAD

**Issue by lysyy** [VictoriaMetrics/VictoriaMetrics#1696]
**Describe the bug**
http_sd_configs section dont works, without any error messages. 
lib/promscrape/config.go str 606, 
			dst, okLocal = appendSDScrapeWork(dst, sdc, cfg.baseDir, sc.swc, "http_sd_config")
Fix: change it to:
			dst, okLocal = appendSDScrapeWork(dst, sdc, cfg.baseDir, sc.swc, "http_sd_configs")

**Version**
Current

**Comment by f41gh7** [comment]
Its used only for logging, it shouldn't affect service discovery.
  
 Probably, you made typo at configuration? Can you verify it with `./bin/vmagent --promscrape.config=config.yaml -promscrape.config.strictParse` ?

**Comment by hagen1778** [comment]
@lysyy @f41gh7  is this issue still relevant?

**Comment by f41gh7** [comment]
I think no, it seems, that it was misconfiguration. 

 Any way, feel free to re-open this issue.
