### ISSUE TITLE
vmagent UI better way to display original labels

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1698]
**Is your feature request related to a problem? Please describe.**
Vmagent UI shows the parsed and origin label for targets:
![image](https://user-images.githubusercontent.com/2902918/136971341-a204487f-0217-40b5-ac34-d923394ce240.png)
Would be nice to have an option to display origin labels not in tooltip, but in form of text that would be easy to search/copy from.

**Comment by valyala** [comment]
The commit e3c8304deb7f0f3e1978c37fc0ddc478cb897f8d adds `show original labels` button per each scrape target at `http://vmagent:8429/targets` page. Click on this button shows the original labels for this target before relabeling. This should simplify debugging issues similar to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1664 .
