### ISSUE TITLE
"-dedup.minScrapeInterval" on vmstorage not effective

### ISSUE THREAD

**Issue by Sisphyus** [VictoriaMetrics/VictoriaMetrics#1710]
**Describe the bug**
Architecture:
1. a prometheus node for scrape metrics and remote-write to VM clusters
2. a vmagent node for proxy remote-write data to two VM clusters with different data precision
3. two VM clusters

We use "-dedup.minScrapeInterval" command flag to implement basic downsampling. In one of the clusters, we configured this parameter on the vmstorage node.

configuration for vmstorage:
vmstorage_v2:
    container_name: vmstorage_v2
    image: victoriametrics/vmstorage
    ports:
      - 28401:8401
      - 8482
      - 8400
    volumes:
      - ./strgdata1:/storage
    command:
      - '--storageDataPath=/storage'
      - '--dedup.minScrapeInterval=1m'
    restart: always
    networks:
      default:

Our prometheus node scrape interval is 15s, we want to store lower precision（like 1m）in one of VM cluster. However, from the actual query results, this configuration does not take effect

**Screenshots**
the promethues source metric
![image](https://user-images.githubusercontent.com/22763940/137474500-739ccdfc-8237-4cfa-ae9c-40acc90607de.png)

the VM cluster without minScrapeInterval flag
![image](https://user-images.githubusercontent.com/22763940/137474620-523161c8-1bc5-44d2-ac94-663fbcf885f3.png)

the VM cluster with minScrapeInterval flag
![image](https://user-images.githubusercontent.com/22763940/137474668-61887e90-b344-4a35-89ee-2baee3c6acd9.png)

**Version**
vmstorage-20211008-140940-tags-v1.67.0-cluster-0-g20fa4b01c

**Used command-line flags**
--dedup.minScrapeInterval=1m

**Comment by Sisphyus** [comment]
What puzzles me is that the data precision is the same in all clusters, which is not as expected

**Comment by rocdove** [comment]
> What puzzles me is that the data precision is the same in all clusters, which is not as expected

Is the data source from Prometheus？The  grafana data source should come from the VictoriaMetrics.
