### ISSUE TITLE
The last metric value disappears

### ISSUE THREAD

**Issue by autokilla47** [VictoriaMetrics/VictoriaMetrics#1719]
We are using a clustered version of 3 nodes. We have a application that sends metrics bypassing the vmagent (there is no "job:" in the prometheus.yml file), the application sending metrics through LB in something like this: `curl -s -d 'TestProbe{instance="10.10.10.10",host="test.host",product="app00",job="job_name"} 1' -X POST 'http://LB:8480/insert/0/prometheus/api/v1/import/prometheus'` (0 - when app is down and 1 - when app is up). 
I simulated a situation when the application crashes (send 0) - in this situation we have a alert that the application is down. Then I manually stopped sending metrics from the datapoint and receive a alert that the datapoints are no longer sending metrics. A little bit later we have a alert that the problem with the application has been resolved (1). But how if the datapoint is not available.
It is correct to send metrics to the address /insert/0/prometheus/api/v1/import/prometheus?
Why does the VM cluster clear the last received metric value and for this reason alert change status to resolved?

**To Reproduce**
Sending a metric that the application is down, and then stopping the datapoint.

**Version**
All component versions: v1.59.0
```

**Comment by autokilla47** [comment]
Thx for answer @hagen1778 

> Which system do you use for alerting? 

Alertmanager (cluster): prom/alertmanager:v0.21.0

> Could you please show the alerting rule?

groups:
- name: test
  rules:
  - alert: EndpointDoesNotReturnAnyMetrics
    expr: absent(FarmingSynthProbe{job="selenium"})
    for: 3m

  - alert: FarmingSynthTestProbeDown
    expr: avg_over_time(FarmingSynthProbe[1m]) < 0.9
    for: 5m

> Can you please also show the screenshot for Grafana or VM UI when executing the expression from the alerting rule?

![image](https://user-images.githubusercontent.com/49757910/137947887-5ca433b2-50d2-4d92-865d-108de3b73cab.png)

And check:
curl 'http://ip:8481/select/0/prometheus/api/v1/export?start=-10m' -d 'match={__name__="FarmingSynthProbe"}'                        {"metric":{"__name__":"FarmingSynthProbe","env":"dtln-prod","job":"selenium","instance":"10.80.3.4","host":"10.80.3.4","owner":"adl","product":"svoefermerstvo"},"values":[1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,1,1],"timestamps":[1634658588865,1634658638720,1634658671396,1634658705163,1634658722202,1634658741458,1634658755214,1634658778055,1634658797943,1634658813448,1634658836267,1634658847510,1634658864620,1634658873848,1634658890222,1634658904539,1634658917514]}

**Comment by valyala** [comment]
Another option to make sure that query results stop returning for stopped series is to pass small `step` value to [`/api/v1/query`](https://docs.victoriametrics.com/keyconcepts/#instant-query). This value can be configured at [vmalert](https://docs.victoriametrics.com/vmalert/) side via `-datasource.queryStep` command-line flag. See [these docs](https://docs.victoriametrics.com/vmalert/#troubleshooting) for more details.

Closing the issue as answered.
