### ISSUE TITLE
Cluster version VMStorage does not switch to readonly mode

### ISSUE THREAD

**Issue by dromedarius** [VictoriaMetrics/VictoriaMetrics#1727]
Hi, 
vmstorage continues write data when  -storage.minFreeDiskSpaceBytes=536870912000 is enabled,  with only 256GB free space 

**Expected behavior**

stop writing to the storage instance and see it in the vmstorage and vminsert logs 

**Logs**

#df -h /opt
Filesystem           Size  Used Avail Use% Mounted on
/dev/mapper/LVM-OPT  2.1T  1.8T  256G  88% /opt

Nothing unusual in logs vmstorage and vminsert

**Version**
vmstorage-20211008-140613-tags-v1.67.0-cluster-0-g20fa4b01c

**Used command-line flags**

-storageDataPath=/opt/victoria/data 
-retentionPeriod=11 
-bigMergeConcurrency=1
-storage.minFreeDiskSpaceBytes=536870912000 
-snapshotAuthKey==****************** 
-forceMergeAuthKey=****************** 
-forceFlushAuthKey==****************** 
-httpListenAddr=1.1.1.1:8482 
-loggerLevel=INFO 
-memory.allowedPercent=85 
-precisionBits=64 
-search.maxTagKeys=100000 
-search.maxTagValues=100000 
-search.maxUniqueTimeseries=500000 
-smallMergeConcurrency=1 
-finalMergeDelay=72h

**Comment by valyala** [comment]
The related feature request - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/269

**Comment by f41gh7** [comment]
Must be fixed. Feel free to re-open.

**Comment by Shrooblord** [comment]
> Neither `vminsert` nor `vmstorage` don't emit logs when `vmstorage` enters read-only mode in v1.67.0. The commit [93511b4](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/93511b4be7da5ae428acb6785abbf51fc168d0a4) adds `warn`-level logs at `vmstorage` when it enters read-only mode. This commit will be included in the next release.

Hey there! Is it possible to suppress / remove the warning or change its frequency using configuration? It's rather spammy and is filling our StackDriver full of messages for every single storage pod we have. That's a lot of $$$ just to get a confirmation that something is still the same situation as it was 5 seconds, 5 minutes, and 5 months ago.

And as you pointed out also, there's the metrics that expose "am I currently in read-only mode?" which we use for Grafana dashboards and alerts -- so the warning isn't strictly necessary in our situation.

**Comment by f41gh7** [comment]
> > Neither `vminsert` nor `vmstorage` don't emit logs when `vmstorage` enters read-only mode in v1.67.0. The commit [93511b4](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/93511b4be7da5ae428acb6785abbf51fc168d0a4) adds `warn`-level logs at `vmstorage` when it enters read-only mode. This commit will be included in the next release.
> 
> Hey there @valyala! Is it possible to suppress / remove the warning or change its frequency using configuration? It's rather spammy and is filling our StackDriver full of messages for every single storage pod we have. That's a lot of $$$ just to get a confirmation that something is still the same situation as it was 5 seconds, 5 minutes, and 5 months ago.
> 
> And as you pointed out also, there's the metrics that expose "am I currently in read-only mode?" which we use for Grafana dashboards and alerts -- so the warning isn't strictly necessary in our situation.

Hello, please check similar issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5159

It must be fixed since v1.95.0.

We have this metric, it's called `vm_storage_is_read_only`. And VictoriaMetrics already exposes it at official grafana dashboards.

**Comment by Shrooblord** [comment]
Amazing, thank you! And yes, that metric is very nice :)
