### ISSUE TITLE
Multitennancy support for Pull Model and Agent

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#1735]
**Is your feature request related to a problem? Please describe.**
No option to write to multiple tenants with vmagent   

**Describe the solution you'd like**
Property in config, property in label and meta label which define account and project ids

**Describe alternatives you've considered**
Setup many agents

**Comment by valyala** [comment]
Small clarification - vmagent supports accepting metrics from multiple tenants and routing them to the same tenants at the specified `-remoteWrite.url` - see [these docs](https://docs.victoriametrics.com/vmagent.html#multitenancy).

vmagent doesn't support scraping metrics from distinct targets and writing them to distinct tenants. The workaround is to run a 
 vmagent per each tenant, so each vmagent scrapes targets for the specified tenant and sends them to the specified tenant at `-remoteWrite.url`.

**Comment by Fury76** [comment]
I got this, i'll try it again, thank you very much~

**Comment by valyala** [comment]
FYI, `vmagent` can send scraped metrics to different tenants - just set `vm_account_id` / `vm_project_id` to the needed metrics and send them to [multitenant url](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy-via-labels) at VictoriaMetrics cluster. See [these docs](https://docs.victoriametrics.com/vmagent/#multitenancy) for details.

Closing this feature request as done.
