### ISSUE TITLE
Victoriametrics datasource causing errors in new Grafa alerting system

### ISSUE THREAD

**Issue by mark4409** [VictoriaMetrics/VictoriaMetrics#1739]
In Grafanas new unified alerting interface, when I click on 'alert rules', it presents me with an error:

`Failed to load rules config from Victoriametrics: unexpected content type from upstream. expected YAML, got application/json; charset=utf-8`

The log file shows:

`t=2021-10-22T13:10:42+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/ruler/5/api/v1/rules status=500 remote_addr=[::1] time_ms=1 size=103 referer=http://localhost:3000/alerting/list`

and the api endpoint at http://localhost:3000/api/ruler/5/api/v1/rules shows:

`{"message":"unexpected content type from upstream. expected YAML, got application/json; charset=utf-8"}`

I have setup victoriametrics in standalone single server mode. The version is victoria-metrics-20211022-171155-tags-v1.68.0-0-gf64f62692. I originally logged this over on the Grafana page but they suggested I log it here, This message does not appear with a Prometheus datasource. 

**To Reproduce**
Enable grafanas new alerting interface and add a victoriametrics datasource

**Expected behavior**
No error message.

**Used command-line flags**
  -storageDataPath /data \
  -retentionPeriod 2 \
  -promscrape.config /etc/victoriametrics/scraper.yml

**Comment by johnalotoski** [comment]
Also interested in resolution to this issue.

**Comment by oldluke92** [comment]
For now, I just disabled grafana unified alerting as victoriametrics does not yet support it. That way you'll get the "legacy" grafana alerting which does not throw that error. You can also disable grafana alerting altogether if you are not using it.

segments in grafana.ini
```ini

[unified_alerting]
#Enable the Unified Alerting sub-system and interface. When enabled we'll migrate all of your alert rules and notification channels to the new system. New alert rules will be created and your notification channels will be converted into an Alertmanager configuration. Previous data is preserved to enable backwards compatibility but new data is removed.
enabled = false

[alerting]
# Disable legacy alerting engine & UI features
enabled = true
```

**Comment by devops-setel-user** [comment]
It would be nice for vmalert to expose a ruler api, so that this can also be managed via grafana ui

**Comment by btorsaldivar** [comment]
> Or even better, just turn off managing alert rules in the Datasource by manageAlerts: false
> 
> ```yaml
> apiVersion: 1
> 
> datasources:
>     - name: VictoriaMetrics
>       type: prometheus
>       access: proxy
>       url: http://victoriametrics:8428
>       isDefault: true
>       jsonData:
>         manageAlerts: false
> ```
> 
> That way you still get to use the new alerting System.

I followed this suggestion to add a `manageAlerts: false` in the datasources section to solve a related issue we are seeing, see below. This also started after Grafana 8 migration and enabled the unified alerting. We use the Grafana alerting functionality, we don't rely on anything else so ymmv...fyi
 
Error in the UI Alerting > Alert Rules tab 
````
Errors loading rules
Failed to load the data source configuration for VictoriaMetrics: remoteAddr: "10.4.0.13:51348", X-Forwarded-For: "xxx.xx.44.121:60050, 10.4.1.4, 10.4.1.4"; requestURI: /api/v1/status/buildinfo; unsupported path requested: "/api/v1/status/buildinfo" ; Bad Request
````

**Comment by oldluke92** [comment]
Hi there,
I verified the above config snippet is still working in a docker-compose deployment using current Grafana (8.4.6) and victoriametrics (v1.76.1) docker images.
You say you added manageAlerts: false in the datasource - maybe you overlooked the "jsonData" section and put it directly in the Datasource ?

**Comment by btorsaldivar** [comment]
> 
@oldluke92 
Well it's working for me as well. I commented that I followed your suggestion and it worked perfectly. The error I stated is what prompted me to investigated and I'm glad to found your solution. Setting the `manageAlerts: false` is the best setting as that would allow us to use the unified alerting system.

**Comment by f41gh7** [comment]
Should be fixed at the next release. Optional proxy for vmalert will be added and stub for buildinfo.

**Comment by valyala** [comment]
Single-node VictoriaMetrics and `vmselect` component of the cluster version of VictoriaMetrics support `-vmalert.proxyURL` command-line flag starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). This flag can be used for proxying alerting API requests from Grafana to [vmalert](https://docs.victoriametrics.com/vmalert.html):

```
  -vmalert.proxyURL string
     Optional URL for proxying alerting API requests from Grafana. For example, if -vmalert.proxyURL is set to http://vmalert:8880 , then requests to /api/v1/rules are proxied to http://vmalert:8880/api/v1/rules
```

Closing the issue as fixed.
