### ISSUE TITLE
Does Victoriametrics support scientific notation?

### ISSUE THREAD

**Issue by mark4409** [VictoriaMetrics/VictoriaMetrics#1740]
Does victoriametrics support scientific notation within metrics? I'm fairly sure that prometheus does but I've looked through the raw output of a number of scrapers including node_exporter and quite a number of the metrics are in scientific notation. I am unable to retrieve these metrics using VMUI or grafana - I just get 'No Data'.

Is this related to the `VictoriaMetrics ignores NaN values during data ingestion.` section in the documentation?

**Comment by valyala** [comment]
Closing the question as answered
