### ISSUE TITLE
How do I guarantee high availability of vmalert?

### ISSUE THREAD

**Issue by yzhengwei** [VictoriaMetrics/VictoriaMetrics#1757]
I deployed a vmalert, but when it died, all the alarms could not be sent, including its own. How to solve this problem? Can there be a cluster mode where when an alarm is triggered, it is de-duplicated in the vmalert cluster before it is sent out?

**Comment by zbindenren** [comment]
We run vmalert on every vmselect node.

**Comment by yzhengwei** [comment]
Thanks very much!

**Comment by hagen1778** [comment]
Please also see https://docs.victoriametrics.com/vmalert.html#ha-vmalert
