### ISSUE TITLE
Create a tool for migrating data from single-node VictoriaMetrics to cluster version

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#176]
**Is your feature request related to a problem? Please describe.**
Currently there is no tool for quick migration of data from single-node to cluster version.

**Describe the solution you'd like**
It would be great to have such a tool.

**Describe alternatives you've considered**
A temporary workaround is to export data from single-node version via [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series), transform it to any supported ingestion format and [backfill](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling) it to VictoriaMetrics cluster. This approach can be slow and it requires writing scripts for data transformation.

**Comment by hagen1778** [comment]
It should be possible now via https://github.com/VictoriaMetrics/vmctl#migrating-data-from-victoriametrics

**Comment by valyala** [comment]
Closing the feature request as done.
