### ISSUE TITLE
Is it possible to restore data from vmstorage pvc

### ISSUE THREAD

**Issue by deng47** [VictoriaMetrics/VictoriaMetrics#1763]
I run a Victoriametrics cluster in a Kubenetes environment using operator. Then a data center disaster event happened. All I left is the PVC data of each vmstorage pod on hard drives like below. No backup, no snapshot.
```
[root@localhost ~]# du -sh /data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/*
65M	/data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/cache
6.4G	/data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/data
0	/data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/flock.lock
256M	/data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/indexdb
4.0K	/data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/metadata
0	/data/pvc-b4773904-bc3c-46c6-9fcc-yh2241002f3p-vm_vmstorage-db-vmstorage-3/snapshots
```
I created a new cluster with the same configuration, and simply rsync'ed all data from the old PVC to the new PVC folder. Logs from new vmstorage pods show vmstorage opened old data which is back in July and August. However, I can't find any data in July or August in Grafana.
```
...
2021-10-28T16:35:52.144Z	info	VictoriaMetrics/lib/storage/partition.go:1530	opened part "/vm-data/data/small/2021_07/9249529_152835_20210731231415.527_20210731235952.666_16ABD2311C7542D2" in 0.000 seconds
2021-10-28T16:35:52.154Z	info	VictoriaMetrics/lib/storage/partition.go:1530	opened part "/vm-data/data/big/2021_07/10596005848_9856471_20210702022935.000_20210725151157.706_168DD868C19099C5" in 0.009 seconds
2021-10-28T16:35:52.155Z	info	VictoriaMetrics/lib/storage/partition.go:1530	opened part "/vm-data/data/small/2021_08/10812_10812_20210831235947.585_20210831235955.327_169705A5E2FA178C" in 0.000 seconds
2021-10-28T16:35:52.155Z	info	VictoriaMetrics/lib/storage/partition.go:1530	opened part "/vm-data/data/small/2021_08/11786_11786_20210831235932.411_20210831235939.536_169705A5E2FA1788" in 0.000 seconds
... 
```
I would like to know if it's possible to restore data from vmstorage PVC. Thank you.

**Comment by valyala** [comment]
VictoriaMetrics should work correctly with the rsync'ed directory pointed by `-storageDataPath` command-line flag if the rsync was performed when the `vmstorage` node at rsync source was stopped.

If the data from the previous months isn't visible after the rsync, then it is likely the new `vmstorage` instance uses smaller `-retentionPeriod`. In this case it opens the data outside the retention and then deletes it. `vmstorage` should leave the `dropping partition ... at smallPartsPath=..., bigPartsPath=...` message in logs when it drops the partition outside the configured retention. The solution is to stop `vmstorage`, rsync the data again from the source in order to restore the dropped partitions and then start `vmstorage` with the correct `-retentionPeriod` command-line flag value.

**Comment by deng47** [comment]
Under the indexdb dir in each PVC, there are 2 index folders with unique ids. I noticed that the vmstorage pod deletes index folders that do not belong to it every time it starts. So even though I copied index folders I backup to this PVC, it got removed automatically. I ended up copying everything in the backup index folders to the new index folder(like  16B1F42B46954755 below) and restored a majority of my data
```
[root@data-node1 ~]# ll /data/k3s/pvc-4rwab594-8fe5-4246-9760-0f0p293e4723_-vm_vmstorage-db-vmstorage-1/indexdb/
total 4
drwxr-xr-x  4 root root   94 Nov  3 10:00 16B1F42B46954755
drwxr-xr-x 18 root root 4096 Nov  7 14:20 16B1F42B46954756
drwxr-xr-x  2 root root   10 Oct 27 10:43 snapshots
[root@d8-r11-c8-n1 ~]# 
```

**Comment by valyala** [comment]
> I noticed that the vmstorage pod deletes index folders that do not belong to it every time it starts.

`vmstorage` deletes sub-folders under `<-storageDataPath>/indexdb` folder only in the following cases:

- If it runs with different [`-retentionPeriod`](https://docs.victoriametrics.com/#retention) comparing to the original `vmstorage`
- If the `<-storageDataPath>/indexdb` folder contains some additional sub-folders comparing to sub-folders from from the backup. Note that you need to pass `--delete` to `rsync` when copying data from the backup storage, so `rsync` removes all the extra folders and files which do not exist in the backup. Also make sure that `vmstorage` is stopped during `rsync` execution.

Closing the question as answered.
