### ISSUE TITLE
vmalert remote writes non processed (non-firing) alerts as ALERTS_FOR_STATE metrics

### ISSUE THREAD

**Issue by sreejith-vk** [VictoriaMetrics/VictoriaMetrics#1766]
**Describe the bug**
vmalert remote writes non processed (non-firing) alerts as ALERTS_FOR_STATE metrics. Prometheus doesn’t.

**To Reproduce**
ALERTS_FOR_STATE{} in remote write compatible vmstorage

**Expected behavior**
Just like Prometheus, store only "alertstate=firing" alert metrics in ALERTS_FOR_STATE
This will tremendously reduce network traffic.

**Version**
victoriametrics/vmalert:v1.65.0

**Comment by valyala** [comment]
@f41gh7 , could you look into this issue?

**Comment by f41gh7** [comment]
`vmalert` generate metric ALERTS_FOR_STATE with `for` value for `pending` and `firing` alerts. Its needed to restore alert state.

  As far as i undertand, prometheus doesn't store `pending` result. In this case, it cannot restore alert state correctly for pending alerts.

  Correct me if i'm wrong.

**Comment by sreejith-vk** [comment]
In Prometheus value of ALERTS_FOR_STATE is the Unix timestamp of when the alert rule expression started being true; for rules with 'for' delays, this means that it is the timestamp when they started being 'pending', not when they became 'firing'. 

This data is what we expect from Victoria metrics as well. This data is the "real" alert start time. 

Due to a suspected bug, I am observing timestamps of alerts that never went to a pending state. I am not able to figure out the exact condition in which vmalert is sending the timestamp.

**Comment by hagen1778** [comment]
Hi @sreejith-vk! Sorry for the delay! I was on the holidays during the last month and now trying to catch up.

`vmalert` suppose to work just as you described - it writes ALERTS_FOR_STATE metric only for "active" (pending/firing) alerts with value of when alert changed the state. If you observe different behaviour - let's try to find a cause. Could you please provide raw datapoints (you can obtain it via export API) for ALERTS_FOR_STATE, ALERTS and actual time series processed by alerting expression?

**Comment by hagen1778** [comment]
Hi @sreejith-vk ! Please, let me know if you have more questions or concerns.
