### ISSUE TITLE
Use vmagent instead of prometheus pushgateway

### ISSUE THREAD

**Issue by yzhengwei** [VictoriaMetrics/VictoriaMetrics#1774]
I used vmagent instead of PushGateway, and when I pushed some data to the vmagent, then I export through the vmselect,  and query from prometheus query range api, why does the exporter has 2 datapoint, but query range has 32 datapoint?

push data to vmagent:
```
% curl -d 'push_gateway{job="push_test",user="yang"} 111' -X POST 'http://10.22.4.39:8429/api/v1/import/prometheus'
```
wait a monment......
```
% curl -d 'push_gateway{job="push_test",user="yang"} 222' -X POST 'http://10.22.4.39:8429/api/v1/import/prometheus'
```
export from vmselect:
```
% curl 'http://10.22.1.202:8481/select/0/prometheus/api/v1/export' -d 'match={__name__=~"push_gateway"}'
{"metric":{"__name__":"push_gateway","job":"push-test","user":"yang"},"values":[111,222],"timestamps":[1635928721455,1635928947001]}
```
query from vmselect use prometheus query range api:
```
push_gateway{job="push-test", user="yang"} =>
111 @[1635928725]
111 @[1635928740]
111 @[1635928755]
111 @[1635928770]
111 @[1635928785]
111 @[1635928800]
111 @[1635928815]
111 @[1635928830]
111 @[1635928845]
111 @[1635928860]
111 @[1635928875]
111 @[1635928890]
111 @[1635928905]
111 @[1635928920]
111 @[1635928935]
222 @[1635928950]
222 @[1635928965]
222 @[1635928980]
222 @[1635928995]
222 @[1635929010]
222 @[1635929025]
222 @[1635929040]
222 @[1635929055]
222 @[1635929070]
222 @[1635929085]
222 @[1635929100]
222 @[1635929115]
222 @[1635929130]
222 @[1635929145]
222 @[1635929160]
222 @[1635929175]
222 @[1635929190]
```

**Comment by valyala** [comment]
The [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) returns calculated samples instead of raw samples stored in the database. It returns up to `1 + (end - start) / step` samples with timestamps `[start, start+1*step, start+2*step, ... end]`. See [these docs](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) for details.

**Comment by rmrf** [comment]
@valyala  can vmagent be used as drop-in replacement of pushgateway? or will it be?

**Comment by rmrf** [comment]
> @valyala can vmagent be used as drop-in replacement of pushgateway? or will it be?

really wish this can be  done by vmagent. :)

**Comment by hagen1778** [comment]
@rmrf I think there is a misconception between Query API and export API. Both, VictoriaMetrics and Prometheus, may return ephemeral data points via Query API - see more about this here https://docs.victoriametrics.com/keyConcepts.html#range-query
