### ISSUE TITLE
Prometheus remote write replaces input timestamp with time of write

### ISSUE THREAD

**Issue by tazle** [VictoriaMetrics/VictoriaMetrics#1776]
**Describe the bug**
Prometheus remote write endpoint replaces input timestamp with time of write.

**To Reproduce**

Write e.g. the following to the remote write endpoint:
```
timeseries {
  labels {
    name: "__name__"
    value: "test"
  }
  labels {
    name: "device"
    value: "testdev54d1c9aeddbd43ec91c9aeddbd43ec39"
  }
  labels {
    name: "foo"
    value: "bar"
  }
  labels {
    name: "unique"
    value: "unique-0"
  }
  samples {
    value: 2.7622374877599754
    timestamp: 1635866440643
  }
}
```

Note that the timestamp here is in milliseconds as specified in the remote write protocol.

When reading through /api/v1/query we eventually got back:
```{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "__name__": "test",
          "device": "testdev54d1c9aeddbd43ec91c9aeddbd43ec39",
          "foo": "bar",
          "unique": "unique-0"
        },
        "value": [
          1635866564,
          "2.762237487759"
        ]
      }
    ]
  }
}
```

which has markedly different timestamp.

**Expected behavior**
Expected to get back the timestamp we wrote.

**Logs**
During this test we didn't observe any logs, but it might be because we don't capture Victoria logs. We can test again if you think there might be relevant logs.

**Version**
docker image victoriametrics/victoria-metrics:v1.67.0

**Used command-line flags**
Container started with the default command.

**Comment by tazle** [comment]
Hm, is the issue actually that Prometheus instant query returns the timestamp of the query and not timestamp of the data?

**Comment by valyala** [comment]
@tazle , could you share more details on how you send data to Prometheus / VictoriaMetrics? Which [data ingestion protocol](https://docs.victoriametrics.com/#how-to-import-time-series-data) do you use? The data ingestion format provided in the first message isn't supported neither by Prometheus nor by VictoriaMetrics:
```
timeseries {
  labels {
    name: "__name__"
    value: "test"
  }
  labels {
    name: "device"
    value: "testdev54d1c9aeddbd43ec91c9aeddbd43ec39"
  }
  labels {
    name: "foo"
    value: "bar"
  }
  labels {
    name: "unique"
    value: "unique-0"
  }
  samples {
    value: 2.7622374877599754
    timestamp: 1635866440643
  }
}
```

**Comment by tazle** [comment]
That's the format I get when I print out the remote write protobuf blob in Java.

**Comment by tazle** [comment]
Anyway, the issue was indeed that I had forgotten about the timestamp-of-query vs timestamp-of-data aspect of Prometheus queries.

**Comment by valyala** [comment]
@tazle , thanks for the update!
