### ISSUE TITLE
query  VictoriaMetrics metrics precision problem

### ISSUE THREAD

**Issue by jiangxinlingdu** [VictoriaMetrics/VictoriaMetrics#1777]
when i  query metrics,  i find this  problem
![1](https://user-images.githubusercontent.com/6373972/140024054-e497a42f-a92f-46d0-99b3-855d44d83297.jpg)
![2](https://user-images.githubusercontent.com/6373972/140024079-630d223c-b5e5-43a4-b6ae-6808f9a233aa.jpg)

why? and how to solve?

**Comment by valyala** [comment]
Probably the `y` axis on the first graph has much smaller value range compared to the second graph, so a small change on the graph becomes visible as a big step. Grafana automatically adjusts the `y` range according to the displayed values by default. This can be overridden by setting `Y-Min` and/or `Y-Max` values when editing the graph panel.

**Comment by jiangxinlingdu** [comment]
> Probably the `y` axis on the first graph has much smaller value range compared to the second graph, so a small change on the graph becomes visible as a big step. Grafana automatically adjusts the `y` range according to the displayed values by default. This can be overridden by setting `Y-Min` and/or `Y-Max` values when editing the graph panel.

bug   one  graph  and  second graph is the same metrics ，i refresh than one graph will show second graph,and i refresh than second graph will show one graph

**Comment by jiangxinlingdu** [comment]
i use vmui, I found it right：
![Xnip2021-11-04_15-39-16](https://user-images.githubusercontent.com/6373972/140275421-a37ae900-0040-4c5f-8758-deb8684b4ce3.jpg)
so it's a problem about Grafana
