### ISSUE TITLE
limitk() adds offset parameter to implement paging query

### ISSUE THREAD

**Issue by zhujzz** [VictoriaMetrics/VictoriaMetrics#1778]

**Comment by valyala** [comment]
The commit 27044b84d27d7814afd286fd1eae412155a707f8 adds `limit_offset` function, which can be used for paging over big number of time series. See [these docs](https://docs.victoriametrics.com/MetricsQL.html#limit_offset).

**Comment by zhujzz** [comment]
thanks

**Comment by valyala** [comment]
The `limit_offset(limit, offset, q)` function is available in VictoriaMetrics since [v1.69.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
