### ISSUE TITLE
List of all connected vmagents

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#1779]
**Is your feature request related to a problem? Please describe.**
There is no general list of all endpoints that send a request for remote_write to victoriametrics.

**Describe the solution you'd like**
Please add to ui victoriametrics in a separate tab a list of all connected to the vmagents that send data via remote_write. It would also be great if we added built-in monitoring for these vmagents to the functionality in order to receive notifications if any of them is unavailable.

**Comment by valyala** [comment]
VictoriaMetrics can accept data from any third-party service additionally to vmagen. It can accept data via [many data ingestion protocols](https://docs.victoriametrics.com/#how-to-import-time-series-data) additionally to Prometheus remote_write protocol (which is used for sending data from `vmagent` to VictoriaMetrics). It is recommended setting up monitoring for `vmagent` instances - see [these docs](https://docs.victoriametrics.com/vmagent.html#monitoring) and using [alerts for vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml), which can generate notifications if something goes wrong with the monitored `vmagent` instances.

@pollynesterovich , could you clarify the feature request?

**Comment by pollynesterovich** [comment]
several agents are used that send metrics to victoriametrics via remote_write.  and I would like all these vmagents to be displayed in one place, for example, in ui victoriametrics.

**Comment by valyala** [comment]
> several agents are used that send metrics to victoriametrics via remote_write. and I would like all these vmagents to be displayed in one place, for example, in ui victoriametrics.

Just set up scraping for these `vmagent` instances according to [these docs](https://docs.victoriametrics.com/vmagent.html#monitoring), and write the scraped data to VictoriaMetrics, so it can be monitored there.

Closing the question as answered.
