### ISSUE TITLE
clarify lifetime()

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#1780]
**Describe the bug**

I expected that `lifetime()` is counting the seconds that the series is present (and this would be the most useful).  But actually it has some unusual behavior about the non-present period.

For example, if a series was not present between now-1d and now-29d, `liftetime(foo[10d])` will give a value of 1 day (in seconds), but `lifetime(foo[30d])` will give a value of 30 days (I expect 2 days).

Please clarify the intended behavior in the docs.  If it's not matching my expectation, I wonder if another function can be added.

> lifetime(series_selector[d]) calculates the lifetime in seconds per each time series returned from the given series_selector. The returned lifetime is limited by the given lookbehind window d.

**Comment by valyala** [comment]
The [lifetime](https://docs.victoriametrics.com/MetricsQL.html#lifetime) function returns the duration in seconds between the last and the first sample on the given lookbehind window from square brackets. Clarified the docs at e44137d46b979e9a54a31b3ea947dbd0f833aa67 .

Also added [duration_over_time](https://docs.victoriametrics.com/MetricsQL.html#duration_over_time) function in the commit 3419ac1d36b54ca394926a36b7e72077998ed73c . This function can be used for calculating the actual lifetime of the time series with possible gaps.

**Comment by belm0** [comment]
thank you!

**Comment by valyala** [comment]
The `duration_over_time(m[d], max_interval)` function is available in VictoriaMetrics starting from [v1.69.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
