### ISSUE TITLE
vmalert some ui alert links do not utilize http.pathPrefix

### ISSUE THREAD

**Issue by johnalotoski** [VictoriaMetrics/VictoriaMetrics#1783]
In vmalert ui, version 1.68.0, when an `http.pathPrefix` is utilized, it is not applied the the "Details" link in the Alerts page, on the individual alert rule "Link Details" link.

Command line options used are:
```
vmalert \
  -datasource.url=http://localhost:8428 \
  -httpListenAddr=127.0.0.1:8880 \
  -notifier.url=http://localhost:9093/alertmanager \
  -external.alert.source= \
  -external.url=https://public-example.fqdn/vmalert \
  -http.pathPrefix=/vmalert \
  -rule=vmalert-rules.json
```

Screenshot:
![image](https://user-images.githubusercontent.com/39752197/140387468-47f723c5-4f90-46f3-ae26-5ac715515f17.png)

In the red circled link "Source" in the upper left, the external.url and pathPrefix is correctly applied, and the link is:
`https://public-example.fqdn/vmalert/api/v1/12197373939068453220/12792085297782517341/status`

In the red circled link "Details" in the lower right, the httpd.pathPrefix `.../vmalert/...` is missing:
`https://public-example.fqdn/12197373939068453220/12792085297782517341/status`

If the pathPrefix is added back, a details page is shown as expected:
`https://public-example.fqdn/vmalert/12197373939068453220/12792085297782517341/status`

Screenshot of pathPrefix fixed link:
![image](https://user-images.githubusercontent.com/39752197/140392012-aee2d6f5-dd86-4735-ab97-51ec87055a37.png)

However, that "Group" link is also similarly missing the pathPrefix.

**Comment by valyala** [comment]
@f41gh7 , could you look into this?

**Comment by drewp** [comment]
Reproducible in victoriametrics/vmalert:v1.72.0

**Comment by hagen1778** [comment]
Hi @drewp! Should be addressed here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2168 once merged.
