### ISSUE TITLE
Add remote read feature to read from prometheus compatible storage such as influx,m3db

### ISSUE THREAD

**Issue by naughtyGitCat** [VictoriaMetrics/VictoriaMetrics#1786]
**Is your feature request related to a problem? Please describe.**
I want to use VictoriaMetrics instead of legacy storage, but the historical data is important and huge amounts. 

**Describe the solution you'd like**
like Prometheus remote read config
 
**Describe alternatives you've considered**
import Prometheus data to VictoriaMetrics

**Comment by denisgolius** [comment]
Hi @naughtyGitCat !
There is a tool for migration data from different sources into VictoriaMetrics named **vmctl** . See https://docs.victoriametrics.com/vmctl.html .
Also check our articles with more information about **vmctl**:
1. https://medium.com/@romanhavronenko/victoriametrics-how-to-migrate-data-from-prometheus-d44a6728f043
2. https://medium.com/@romanhavronenko/victoriametrics-how-to-migrate-data-from-prometheus-filtering-and-modifying-time-series-6d40cea4bf21

**Comment by naughtyGitCat** [comment]
thanks, my data is store in `m3db` cluster, now have no plugins or tools to read data from `m3db`(have prometheus read api) to `VictoriaMetrics`

**Comment by hagen1778** [comment]
@naughtyGitCat as a workaround try using [prom-migrator](https://github.com/timescale/promscale/blob/master/cmd/prom-migrator/README.md).

**Comment by naughtyGitCat** [comment]
thanks, i will have a try
