### ISSUE TITLE
vmagent/vmalert entities filter in UI 

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#1796]
When targets more then 500 it is not convenient to use the interface without filtering

Filter may contains regex labels and  regex target name

**Comment by valyala** [comment]
A temporary workaround is to use search functionality built into the web browser: navigate to `http://vmagent:8429/targets`, press `Ctrl+F` (or `Cmd+F` on MacOS) and search for the needed text from there.

**Comment by nevlkv** [comment]
)))) web browser  searching is not as filter ! May be same functionality needed in webui  vmalert

thanks

**Comment by valyala** [comment]
`vmagent` supports filtering targets by endpoint url and by labels starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
