### ISSUE TITLE
Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#1797]
When a request is made in vmui and the "instant query as table" button is clicked browsers( google chrome, firefox) throws an error and the page loads empty.
`Uncaught TypeError: Cannot read properties of undefined (reading '1')`.
Used by victoriametrics v.1.68.0.
 

<img width="482" alt="Снимок экрана 2021-11-08 в 22 00 15" src="https://user-images.githubusercontent.com/72506251/140801732-749079eb-7d4a-44c5-b1ba-33a51b916604.png">

**Comment by Loori-R** [comment]
Could you please show which query string parameters you are using? 
Thank you for your help.

**Comment by pollynesterovich** [comment]
`rate(kafka_connect_sink_task_metrics_sink_record_send_rate{prometheus_from=~"cluster"})[5m]`

**Comment by valyala** [comment]
Side note: the query looks slightly incorrect - the lookbehind window in square brackets - `[5m]` - must be placed just after closing curly brace:

```
rate(kafka_connect_sink_task_metrics_sink_record_send_rate{prometheus_from=~"cluster"}[5m])
```

Otherwise the query is automatically converted to a [subquery](https://docs.victoriametrics.com/MetricsQL.html#subqueries), which may give unexpected results.

**Comment by pollynesterovich** [comment]
Yes indeed, this is how it works. Thanks.

**Comment by valyala** [comment]
The `Cannot read properties of undefined` issue should be fixed in vmui starting from [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue.

**Comment by soft-checkmate-kevin** [comment]
hkl;njkl;

**Comment by soft-checkmate-kevin** [comment]
jk;kl;jkl;lk;kl;jkljjjjjjjjjjjjjjjjjjjj;
