### ISSUE TITLE
Using Victoria Metrics with Grafana Label Legend does not work with Prometheus Labels

### ISSUE THREAD

**Issue by BenB196** [VictoriaMetrics/VictoriaMetrics#18]
I am testing out Victoria Metrics as a long term storage solution for Prometheus, however I have run into a weird bug, with Grafana Legends, where Prometheus labels are not working properly.

The below picture is a graph which I made, and each line should be a different interface. I use the Grafana Legend to be filled out with the ifName label. However, if you look at the graph you can see that the ifName is not set correctly.

![image](https://user-images.githubusercontent.com/8277432/55402795-54b66780-5522-11e9-99b6-ef3ec2c12094.png)

I know that everything works correctly on the query and Grafana end, because if I switch the data source to use Prometheus directly, I get the correct result.

![image](https://user-images.githubusercontent.com/8277432/55402998-ca223800-5522-11e9-871b-d4121f316669.png)

Versions of Software:

Grafana: 6.0.2 - Docker Container
Prometheus: 2.8.1 - Docker Container
Victoria Metrics: 1.12.3 Single-node - Docker Container

**Comment by valyala** [comment]
@BenB196 , thanks for the bug report. Could you remove `{{ifName}}` from the `Legend` field in Grafana for both VictoriaMetrics and Prometheus datasources and attach the resulting screenshots? In this case Grafana should display all the labels for the returned time series. This should help understanding the difference in these labels between Prometheus and VictoriaMetrics.

**Comment by BenB196** [comment]
@valyala Please see the screenshots below:

First screenshot is of VictoriaMetrics

![image](https://user-images.githubusercontent.com/8277432/55416398-b84d8e80-553c-11e9-91b1-1c10730c2b20.png)

Second screenshot is of Prometheus

![image](https://user-images.githubusercontent.com/8277432/55416496-e03cf200-553c-11e9-85c9-f0ec470f1d26.png)

**Comment by valyala** [comment]
Confirmed the bug. Will be fixed in the next release.

**Comment by valyala** [comment]
@BenB196 , could you confirm the bug has been fixed in [v1.12.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by BenB196** [comment]
@valyala I have tested v1.12.4 and this issue is now fixed. Thank you for assisting with this problem.

**Comment by valyala** [comment]
@BenB196 , thank you for reporting the bug and verifying the bugfix.
