### ISSUE TITLE
VM as a Graphite datasource in Grafana

### ISSUE THREAD

**Issue by rcousens** [VictoriaMetrics/VictoriaMetrics#1801]
I'm attempting to use VM as a sink for some legacy statsd traffic, but one I have so far been entirely unsuccessful in getting VM to be able to queried from Grafana for the StatsD metrics.

If I add VM as a Prometheus data source and then try to explore the StatsD metrics, I get an error saying 'faceting failed' whenever I click on one in a panel query and in the metrics browser.

I have tried adding VM as a Graphite data source, but it is unclear whether this is an enterprise only feature in the docs (https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#graphite-render-api-usage). The section directly above this just says it's possible to use VM as a Graphite data source. 

Can I get some clarification here?

Is there a way to chart StatsD metrics using VM as a Prometheus data source. Or is there a way to add VM as a Graphite data source?

**Comment by YuriKravetc** [comment]
Render API is indeed enterprise-only solution.

Please refer to integration with statsd  - https://docs.victoriametrics.com/#how-to-send-data-from-graphite-compatible-agents-such-as-statsd
Might be helpful for your case.

**Comment by rcousens** [comment]
@YuriKravetc Thank you very much! That syntax `{__graphite__="..."}` has helped me successfully query the data via MetricsQL which is good enough for me!

I will close this ticket.
