### ISSUE TITLE
VM resolution issue 

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#1803]
**Describe the bug**
I have  two VM cluster that have metrics more 10 months and it can't show data right, when you chose time range is biggest 41 - 209 days the VM shows wrong metrics, but if you zoom in 40 days, metrics is loading or if you use more 210 days time range

I've tried 1.65 1.69 version but bug exists, removed cache on VM storage, Vm select, try to check in VMUI, enable `search.denyPartialResponse`, increase timeouts for example `search.cacheTimestampOffset`,`search.maxQueryDuration`. restart clusters.
but any luck :(

**To Reproduce**

**Expected behavior**
load metrics

**Logs**
nothing :(

**Screenshots**
1 year (gaps in graph is ok, i don't have metrics in that period of time)
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/70581130/141092089-19b82d5c-5b92-4f2a-9b26-3c18f189c5c8.png">

210 days
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/70581130/141091613-b92cb8d1-097b-45a3-994c-bc43652ea2f7.png">

209 days
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/70581130/141091709-73a70d24-d760-43bb-88a2-d91acc57d902.png">

6 month
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/70581130/141091781-7da1ce4e-746b-49a9-9fb9-93c67c246233.png">

41 days
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/70581130/141091844-58b19f58-3020-4ec1-b999-212a0cf9f94c.png">

40 days
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/70581130/141091916-1ff14ec4-75b5-4fcd-91a4-d06058ab67cc.png">

30 days
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/70581130/141092985-b109e6ce-e0c2-41a4-917a-f788e6bbb86a.png">

range `from now-90d to now-60d`
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/70581130/141094489-cf1c1ece-e7a8-44ef-b852-09eeb0a23627.png">

our discussion https://victoriametrics.slack.com/archives/CGZF1H6L9/p1636031122134400

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
/ # ./vmstorage-prod --version
vmstorage-20211108-140531-tags-v1.69.0-cluster-0-gb1de18088
```

**Used command-line flags**
VM-select
```
    Args:
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-0.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-1.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-2.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-3.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8401
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
      --search.disableCache=true
      --search.denyPartialResponse=true
      --search.maxConcurrentRequests=4
```
VM-storage
```
    Args:
      --retentionPeriod=36
      --storageDataPath=/storage
      --dedup.minScrapeInterval=30s
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
```
VM insert
```
    Args:
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-0.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-1.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-2.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
      --storageNode=vm-cluster-01-victoria-metrics-cluster-vmstorage-3.vm-cluster-01-victoria-metrics-cluster-vmstorage.monitoring.svc.cluster.local:8400
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
```

the second VM cluster has the same flags, hust different DNS name

**Comment by valyala** [comment]
Try removing the file `metadata/minTimestampForCompositeIndex` inside directory pointed by `-storageDataPath` command-line flag at every `vmstorage` node. This issue may be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1102#issuecomment-789129312

**Comment by yuriydzobak** [comment]
> Try removing the file `metadata/minTimestampForCompositeIndex` inside directory pointed by `-storageDataPath` command-line flag at every `vmstorage` node. This issue may be related to [#1102 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1102#issuecomment-789129312)


I've removed the file and restarted vmstorage PODs and it works as excepted
Thank you!
--
Дякую
