### ISSUE TITLE
store "INSTANT QUERY AS TABLE" in url, for opening table by UI link

### ISSUE THREAD

**Issue by madmanidze** [VictoriaMetrics/VictoriaMetrics#1804]
Hello,

Please, add variable for "INSTANT QUERY AS TABLE" in url, when opening table by UI link.

Thanks.

**Comment by valyala** [comment]
FYI, this feature has been included in [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it as done.
