### ISSUE TITLE
vmalert address flags are confusing

### ISSUE THREAD

**Issue by flokli** [VictoriaMetrics/VictoriaMetrics#1810]
**Describe the bug**
Right now, there's `remoteRead.url`, `remoteWrite.url` and `datasource.url` flags.

 - `datasource.url` is used to query (source) metrics to produce alerts
 - `remoteRead.url` is used to restore `vmagent` state across restarts (read `ALERTS` and `ALERTS_FOR_STATE`)
 - `remoteWrite.url` is used to store `vmagent` state across restarts AND to write back VMRule results

There's few reason to separate `datasource.url` and `remoteRead.url`, as `remoteWrite.url` (at least for the purpose of separating `vmalert` state from the rest of the metrics).

`remoteWrite.url` is used to both store `vmagent` state and `VMRule` results, so `remoteRead.url` and `datasource.url` need to point to the same destination anyways.

It might make more sense to only have `remote{Read,Write}.url`, and a boolean flag describing whether state should be persisted or not.

**Comment by valyala** [comment]
The main reason for a separate `-remoteRead.url` is to cover a use case where the results of alerting and recording rules are written into a distinct database. This way you can set up recording rules, which will be evaluated against a short-term storage with high-frequency and high-cardinality samples, while the results will be written to a long-term storage with the decreased cardinality and bigger interval between samples.

**Comment by flokli** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1823 now documents this, PTAL.
