### ISSUE TITLE
VM agent lint remoteWrite.label

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#1818]
**Describe the bug**
When VM agent uses flag `-remoteWrite.label` and you provide parameters like `-remoteWrite.label=env=test,extra-label=true`
then VM agent doesn't check arg and send metric with wrong label format that cause the issue with VM storage, it couldn't be queried metrics in grafana

**To Reproduce**
configure VM agent with args:
```
-remoteWrite.label=env=test,extra-label=true
```
Open grafana and slect a metrics

**Expected behavior**
show fail POD vm agent, check if args doesn't have any `-`

**Version**
```
/ # ./vmagent-prod -version
vmagent-20211022-171351-tags-v1.68.0-0-gf64f62692
```

**Used command-line flags**
```
    Args:
      -promscrape.config=/config/scrape.yml
      -remoteWrite.tmpDataPath=/tmpData
      -remoteWrite.url=http://vm-cluster-01-victoria-metrics-cluster-vminsert:8480/insert/0/prometheus
      -remoteWrite.url=http://vm-cluster-02-victoria-metrics-cluster-vminsert:8480/insert/0/prometheus
      -envflag.enable=true
      -envflag.prefix=VM_
      -loggerFormat=json
      -promscrape.configCheckInterval=1m
      -promscrape.ec2SDCheckInterval=3m
      -promscrape.kubernetesSDCheckInterval=1m
      -promscrape.noStaleMarkers=true
      -promscrape.suppressDuplicateScrapeTargetErrors=true
      -remoteWrite.label=env=test,e2e-build=202
      -remoteWrite.maxDiskUsagePerURL=15GB
```

**Comment by f41gh7** [comment]
Hi, can you share grafana error? 

 VictoriaMetrics allows any symbols at label name and breaks Prometheus data model. 

 For instance, following request works at grafana with VictoriaMetrics `vm_active_merges{extra\-label="true"}`, `-` must be escaped with `\`.

 Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/990
