### ISSUE TITLE
Query failing for certain date ranges

### ISSUE THREAD

**Issue by setaou** [VictoriaMetrics/VictoriaMetrics#1819]
I am storing data for 12 month. Fore some series, I have a strange problem: a query works for the last 12 months, for the last 6 months, or for the last 1 hour, but fails for the last 3 month or last 30d, even though the data is present and appears if I "zoom in".
I can reproduce the problem using VM UI, which excludes a bug in Grafana.

This might be related to issue #1496, but in my case, when it fails there is nothing, not even partial data.

A curious thing is that some queries might work depending on the order they are made: for example, if I request a 4 month range straight away it will always fail, but if I request 6 month, then 5, then 4 it will work down to 2 months where it will always fail.

**Version**: victoria-metrics-20211108-134932-tags-v1.69.0-0-g69e655ba7 (latest to date)
**Command Line Flags** : -storageDataPath /data/self/victoriametrics -retentionPeriod 12 -promscrape.config /etc/victoriametrics/prometheus.yml -selfScrapeInterval=10s -search.latencyOffset=10s

7 days works:
![image](https://user-images.githubusercontent.com/524358/141801433-fce5f1dc-864c-4302-a616-8da21f78e9c8.png)
2 month fails:
![image](https://user-images.githubusercontent.com/524358/141801508-f8e8d44a-5f40-482d-bd1c-a1717b518ec7.png)
a 7 days "zoom" in the same 2 month period works :
![image](https://user-images.githubusercontent.com/524358/141802173-5de4d33a-b21f-411b-9d9f-7bdad5c403fb.png)
6 months works:
![image](https://user-images.githubusercontent.com/524358/141801582-7a4033ac-7dc2-4d20-8d57-f43b727a5d0a.png)

**Comment by f41gh7** [comment]
It looks like an issue with monthly index, @valyala  can you take a look.

**Comment by valyala** [comment]
@setaou , could you reproduce the issue in Grafana? `vmui` has a known issue, which may sometimes result in an empty graph even if VictoriaMetrics returns the data. It would be great if you could send queries directly to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) API and to [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) for different time ranges via curl. This will completely exclude possible UI issues.

**Comment by setaou** [comment]
Yes, I can reproduce the issue in Grafana. In fact, that is where I noticed it first, I then switched to VM UI to check if Grafana was involved in this bug.

Query for the last 7d works :
```
curl 'http://monitoring5:8428/prometheus//api/v1/query_range?query=mem_used%7Bhost%3D%22bdd1%22%7D&start=1636081000&end=1637290600&step=630&nocache=1'
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"mem_used","db":"telegraf","host":"bdd1"},"values":[[1636081000,"69136666624"], ...... ,[1637140660,"69595574272"]]}]}}
```


Query for the last 2 month fails :
```
curl 'http://monitoring5:8428/prometheus//api/v1/query_range?query=mem_used%7Bhost%3D%22bdd1%22%7D&start=1629212200&end=1639580200&step=5400&nocache=1' 
{"status":"success","data":{"resultType":"matrix","result":[]}}         
```                                                                                                              

Query for the last 6 month works :
```
curl 'http://monitoring5:8428/prometheus//api/v1/query_range?query=mem_used%7Bhost%3D%22bdd1%22%7D&start=1613660200&end=1644764200&step=16200&nocache=1' 
{"status":"success","data":{"resultType":"matrix","re
[vm_export.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7553302/vm_export.gz)
sult":[{"metric":{"__name__":"mem_used","db":"telegraf","host":"bdd1"},"values":[[1613660200,"69064003584"], ....... ,[1637150200,"69602009088"]]}]}}
```

You will find attached the export of the time series I have used for these queries.

**Comment by Menniti** [comment]
Hello guys,
I have face a similar issue,

Putting a step=3 and query, I will see this result.
Which is a correct one.
![image](https://user-images.githubusercontent.com/15658494/142780788-a65f86f8-0cc4-4ae1-a07a-503c9d6216b0.png)

But just query again with step=3, it will show few duplications

![image](https://user-images.githubusercontent.com/15658494/142780817-11e58d7c-86f5-439a-ab9a-1560972ea4b8.png)

It happens with another parameter in start=-10h or start =-11h it completely changes the results

**Comment by setaou** [comment]
@Menniti I do not see how problem you are experiencing is related to this issue, which is about missing data for some date ranges above 1 month. You should probably open a new issue concerning your specific problem.

**Comment by valyala** [comment]
@setaou , @Menniti , could you verify whether the issue still exists in [the latest VictoriaMetrics release](https://docs.victoriametrics.com/CHANGELOG.html). It is likely the issue has been already fixed there.

Also, try following [troubleshooting docs](https://docs.victoriametrics.com/troubleshooting/index.html#unexpected-query-results) - probably, they'll help identifying the root cause of the issue.

**Comment by setaou** [comment]
I think this issue has been resolved a few releases ago already: I have just tested on v1.95.1 that I am currently running, and I can't reproduce. I will close the issue.
Thanks for all the work on VictoriaMetrics, it is an awesome product !
