### ISSUE TITLE
Not able to run vmagent due to error: flag provided but not defined:

### ISSUE THREAD

**Issue by foxipub** [VictoriaMetrics/VictoriaMetrics#1821]
**Describe the bug**
Whenevery i try upgrade vmagent version above 1.60[that is work fine] i have got error into vmagent pode while it attempts to start so i get CrashLoopBackOff error!

**To Reproduce**
Start deploy throw the helmfile with latest chart version [0.7.34]

**Expected behavior**
Pod should be into Running state.

**Logs**
╰─➤  k logs vmagent-victoria-metrics-agent-8487ff759d-sghsc -n monitoring
flag provided but not defined: -remoteWrite.url

victoria-metrics is a time series database and monitoring solution.

See the docs at https://docs.victoriametrics.com/

Run "/victoria-metrics-prod -help" in order to see the description for all the available flags

**Version**
vmagen version 1.69
chart version 0.7.34

**Comment by f41gh7** [comment]
Can you check actual image for vmagent? Looks like, its not vmagent's docker image

```bash
kubectl get pod vmagent-victoria-metrics-agent-8487ff759d-sghsc -n monitoring -o yaml | grep image
```
  It must be victoriametrics/vmagent:v1.69.0

**Comment by foxipub** [comment]
Thank you Nikolay, realy my bad, i used wrong image for vmagent.

**Comment by foxipub** [comment]
Solution: USE RIGHT IMAGE! IDIDOT!
