### ISSUE TITLE
vmalert: Ability to connect using Header token

### ISSUE THREAD

**Issue by Knyage** [VictoriaMetrics/VictoriaMetrics#1824]
Hi! 

I would like to be able to specify for vmalert to send json to notification system (we plan to write our own, alertmanager is not suitable) using header token. 

Please implement the feature :) Modern requirements of information security hint that it's better to set up authorization by token right away.

**Comment by ArtemKaba** [comment]
Hi everyone,
we need this future too.
It would be helpful to connecting the openshift alertmanager to send alerts.

**Comment by noamApps** [comment]
Hey, a temporary workaround that might work is to set the token in a query parameter and then set notifier.url to something like 
`notifier.url=http://alertmanager1:9093/alert?apikey=<token>`
you can leverage products like https://konghq.com/ that allows verifying tokens that are presented in query parameters.
I've tested this method with other products (going to do it soon with vmalert) and it works great.

**Comment by dmitryk-dk** [comment]
Hi @Knyage , @ArtemKaba ! 
Thanks for your feature request.
I have implemented different types of auth but have a question. 
We have two possible auth with headers:
1. Basic auth
2. Bearer auth
Is it enough for you?

**Comment by ArtemKaba** [comment]
Hi @dmitryk-dk 
Thank you for your reply.
Yes, it's enough.

**Comment by hagen1778** [comment]
Hi @Knyage @ArtemKaba ! PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2287 has been merged and will be available in the next release. You also can [build vmalert from sources](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) to verify that change suits tour needs. Thanks!

**Comment by valyala** [comment]
FYI, vmalert supports `-notifier.bearerToken` and `-notifier.bearerTokenFile` command-line options starting from [v1.75.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
