### ISSUE TITLE
Vmselect on Cluster version not get correct tsdb status

### ISSUE THREAD

**Issue by biggrundik** [VictoriaMetrics/VictoriaMetrics#1825]
**Describe the bug**
Vminsert on cluster version not get tsdb stats on link
http://vminsert:8481/select/1/prometheus/api/v1/status/tsdb

**To Reproduce**
see http://vminsert:8481/select/1/prometheus/api/v1/status/tsdb

**Logs**
Logs clear

**Screenshots**
![Screenshot 2021-11-17 at 20-21-38 Screenshot](https://user-images.githubusercontent.com/52821074/142250946-c8e2a58d-d533-4023-9635-a90c247aacb2.png)

**Version**
```
/ # ./vmselect-prod --version
vmselect-20211008-140749-tags-v1.67.0-cluster-0-g20fa4b01c
```

**Used command-line flags**
Only used -envflag.enable

**Comment by denisgolius** [comment]
Hi @biggrundik!
Check that your first tenant is present in your cluster and try to open `http://vminsert:8481/select/0/prometheus/api/v1/status/tsdb` . 
See https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format to get more information about tenants.
