### ISSUE TITLE
Small parts are not merged

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#1828]
**Describe the bug**
[1455](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1455)

hi，@valyala 
This problem has been appearing on some of our servers. A large number of files in small directories are not merged into big directories, which often triggers slow queries. The main problem is that when vm merges, it is judged that the difference between the two parts is too large to merge. However, we have not found out what causes the difference between the two parts to be too large. What causes this problem? Is there any direction for investigation?

**Screenshots**
![image](https://user-images.githubusercontent.com/2275120/142351201-323837a4-c5e1-40e8-8ca7-f92437f108d2.png)
![image](https://user-images.githubusercontent.com/2275120/142351612-b8f7ce42-a5ba-464b-b028-db3a9711814d.png)

**Version**
/usr/local/bin/vmstorage-prod --version
vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5

**Comment by valyala** [comment]
@jinlongwang , try upgrading to the latest release and see whether this helps. The algorithm for selecting parts for background merge has been changed in v1.65.0 - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1560 . This may help resolving your case.

Note also that the number of parts can increase if there is no enough free disk space for background merge. It is recommended to have at least 30% of free disk space for optimal merges. See [these docs](https://docs.victoriametrics.com/#troubleshooting) for details.

**Comment by hagen1778** [comment]
Closing the issue due to lack of activity.

**Comment by valyala** [comment]
@jinlongwang , try [the latest available release of VictoriaMetrics](https://docs.victoriametrics.com/CHANGELOG.html) - it contains additional improvements into [background merge process](https://docs.victoriametrics.com/#storage), which should reduce the probability of sudden growth of small parts. The basic idea is to merge small and big parts by distinct sets of workers, so merges for big parts do not stop merges for small parts.

Please open a new issue if the latest release of VictoriaMetrics still fails to merge small parts in a timely manner.
