### ISSUE TITLE
no downloading fonts.googlesapi.com/css

### ISSUE THREAD

**Issue by goodqinjin** [VictoriaMetrics/VictoriaMetrics#1829]
vmui  no downloading fonts.googlesapi.com/css

**Comment by denisgolius** [comment]
Hi @goodqinjin!

Please add more information about your issue because I don't see any issue while build VM cluster or VM Single by running "make all" or "make package" .

**Comment by Loori-R** [comment]
`vmui` embeds fonts starting from [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
See [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3705).
