### ISSUE TITLE
Implement /-/healthy endpoint to be compatible with Prometheus management APIs

### ISSUE THREAD

**Issue by MustDie95** [VictoriaMetrics/VictoriaMetrics#1833]
**Is your feature request related to a problem? Please describe.**

I've deployed MinIO (https://github.com/minio/minio) + Console (https://github.com/minio/console) in my K8s. 

VM + VMAgent also running in this cluster.

I want to have MinIO metrics in Console .

I followed the instruction (https://docs.min.io/minio/baremetal/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.html#minio-metrics-collect-using-prometheus).

VM Agent has MiniO in targets, scrapping works well. I can visualize this metrics in Grafana using VM as data source.

But in Console I got en error "Prometheus URL is unreachable".

I've searched the VM's logs and found "VictoriaMetrics/lib/httpserver/httpserver.go:306","msg":"remoteAddr: \"x.x.x.x:29043\"; requestURI: /-/healthy; unsupported path requested: \"/-/healthy\""}

**Describe the solution you'd like**
Implement /-/healthy endpoint (may be /-/ready too) to be compatible with Prometheus management APIs

**Describe alternatives you've considered**
As workaround I had to rebuild Console with URI changed in test Prometheus URL here https://github.com/minio/console/blob/7f5de2d70e51699dc00b2f238131a6d72ded4ba3/restapi/admin_info.go#L922

**Comment by MustDie95** [comment]
As another workaround I can use Nginx-Ingress for VM's external URL with these additions: 

nginx.org/server-snippets: | 
   rewrite ^/-/healthy /metrics break;

**Comment by valyala** [comment]
The `/-/healthy` and `/-/ready` endpoints have been added in the commit 394a345ae0e9f03d1bcb6f402b8d1228c7a803ac . This commit will be included in the next release.

**Comment by MustDie95** [comment]
Oh, great, thanks!

**Comment by valyala** [comment]
The `/-/healthy` and `/-/ready` endpoints are supported by VictoriaMetrics components starting from [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by grinapo** [comment]
Sidenote: it seems that URL normalisation isn't performed here, since the (admittedly stupid) `//-healthy` path fails, while `/-healthy` works. (Former is the result of an extra slash in the VM url on minio side.)
