### ISSUE TITLE
resets does not work as expected

### ISSUE THREAD

**Issue by johnatannvmd** [VictoriaMetrics/VictoriaMetrics#1836]
**Describe the bug**
I have several service that expose uptime metrics. This is a counter, which increments every second. Merics gathers every minute. 

RAW metrics look like this:
![Screenshot from 2021-11-19 18-35-48](https://user-images.githubusercontent.com/4918448/142649245-f9e83751-4e18-4912-a8f8-d09c41eb62fe.png)
[Application health-data-as-seriestocolumns-2021-11-19 15_37_55.csv](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7571312/Application.health-data-as-seriestocolumns-2021-11-19.15_37_55.csv) - there are 6 hosts

A want to know when service is restarted. So I applied `resets` function with `1m` lookbehind and got something like this:
![Screenshot from 2021-11-19 18-41-19](https://user-images.githubusercontent.com/4918448/142650091-6f33ab4b-2d19-48aa-99ed-b6dead200630.png)
Which looks not quite right. Same result I got when remove lookbehind window and leave that to VM, according to the article this should work. https://valyala.medium.com/promql-tutorial-for-beginners-9ab455142085
> ... where [d] may be omitted — in this case it equals to the duration between two subsequent points on the graph (aka step):

**To Reproduce**
Import given csv, and make queries.

**Expected behavior**
Resets should return 1 on counter resets.

**Version**
cluster 1.67.0

**Command line**
```
vmselect -search.latencyOffset 0 \
-cacheDataPath /data/victora/vmselect_autogen \
-httpListenAddr :8481 \
-replicationFactor 2 \
-search.maxQueryDuration 30s \
-dedup.minScrapeInterval 10s \
-search.logSlowQueryDuration 5s \
-search.resetCacheAuthKey ASDFQWER \
...storages and selectors...
-loggerDisableTimestamps \
-memory.allowedPercent 20
```
```
vmstorage -dedup.minScrapeInterval 10s \
-forceFlushAuthKey ASDFQWER \
-forceMergeAuthKey ASDFQWER \
-http.shutdownDelay 5s \
-httpListenAddr :8482 \
-retentionPeriod 1 \
-snapshotAuthKey ASDFQWER \
-storageDataPath /data/victora/autogen \
-vminsertAddr :8400 \
-vmselectAddr :8401 \
-loggerDisableTimestamps \
-search.maxUniqueTimeseries 10000001 \
-memory.allowedPercent 60
```

**Comment by YuriKravetc** [comment]
Hello,
It seems to work normally.
According to the graphs, services are taking more than 1 minute to reload.
Please try to increase the interval to more than 1m

**Comment by johnatannvmd** [comment]
To achieve my goal, I need to change lookbehind window to `5m` and set min step `1m` explicitly.

![Screenshot from 2021-11-19 19-52-48_cut](https://user-images.githubusercontent.com/4918448/142917728-b0ec61e3-bce9-4f91-9829-d1ce7bedac1c.png)

Seems like this is my fault, sorry for inconvenience.
