### ISSUE TITLE
vmselect: /export API doesn't deduplicate data 

### ISSUE THREAD

**Issue by mariastroe** [VictoriaMetrics/VictoriaMetrics#1837]
**Describe the bug**
Doing a native or csv export doesn't deduplicate data even if vmselect has -dedup.minScrapeInterval=1ms flag.

**To Reproduce**
Having a setup like this, where A and B vmstorages have the same data:
![image](https://user-images.githubusercontent.com/61047631/142668375-1bdac234-a7cf-4751-a215-9c16249bb870.png)

with the -dedup.minScrapeInterval=1ms flag enabled in vmselect

Try to do a csv export from one tenant (the format includes all labels):
curl 'http://127.0.0.1:8481/select/10:10/prometheus/api/v1/export/csv?format=__name__,host,service,subscriptions,__value__,__timestamp__:unix_ms&start=-10d' -d 'match[]={__name__="test_metric"}' > export.csv
grep 'test_metric,server01,monitoring,console,1,1637311523000' export.csv
test_metric,server01,monitoring,console,1,1637311523000
test_metric,server01,monitoring,console,1,1637311523000

Try to do a native export from one tenant:
curl  'http://127.0.0.1:8481/select/10:10/prometheus/api/v1/export/native' -d 'match[]={__name__="test_metric"}&start=-10d' -o export.bin

Import it in a freshly started VM standalone:
curl -X POST http://localhost:8428/api/v1/import/native -T export.bin

Try to do a query on the VM standalone:
curl 'http://localhost:8428/api/v1/query' -d 'query=test_metric{host="server01", service="monitoring", subscriptions="console"}[10d]' 
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "test_metric",
          "service": "monitoring",
          "host": "server01",
          "subscriptions": "console"
        },
        "values": [
          [
            1637230462,
            "0"
          ],
          [
            1637230462,
            "0"
          ],
          [
            1637230522,
            "0"
          ],
          [
            1637230522,
            "0"
          ], ...........

Try to do an export in JSON line format:
curl  'http://127.0.0.1:8481/select/10:10/prometheus/api/v1/export' -d 'match[]={__name__="test_metric"}&start=-10d' > export.json
jq '. | select(.metric.host=="server01" and .metric.service=="monitoring" and .metric.subscriptions == "console")' export.json | grep 1637311523000

1637311523000,

The export in json line format seems to be the only one that returns deduplicated data.

**Expected behavior**
Get deduplicated data also when using native and csv exports.

**Version**
VMC 1.67.0
VM standalone 1.67.0

**Comment by f41gh7** [comment]
@valyala  can you take a look? for now it looks like bug.

**Comment by valyala** [comment]
The [native export](https://docs.victoriametrics.com/#how-to-export-data-in-native-format) doesn't unpack the data in order to reduce CPU usage and improve export speed. So it cannot deduplicate data, because the de-duplication needs data unpacking. It is expected that the de-duplication is performed at destination database during data import.

As for [the CSV export](https://docs.victoriametrics.com/#how-to-export-csv-data), it must de-duplicate data in the same way as [JSON line export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format). If tgis isn't the case, then this is a bug, which must be fixed.

**Comment by valyala** [comment]
The de-duplication isn't applied to data exported via `/api/v1/export/csv` because of the same performance reasons as for the `/api/v1/export/native` export. Updated the documentation with this information at f06495c50a317946955e39536b2976d5c41cea99 .

**Comment by mariastroe** [comment]
Thanks @valyala for the response! 
Regarding the CSV export, I think the data should be de-duplicated because maybe it's not going to be imported in a VictoriaMetrics afterwards, but used for analyzing or further processing with other tools.
I understand the performance reasons behind not de-duplicating via native export as it should be imported in another VictoriaMetrics to work, but since for CSV exports this may not be the case every time, it should de-duplicate data in the same way as JSON line export (as you said in the first comment).

**Comment by valyala** [comment]
> Regarding the CSV export, I think the data should be de-duplicated because maybe it's not going to be imported in a VictoriaMetrics afterwards, but used for analyzing or further processing with other tools.

Agreed. VictoriaMetrics should de-duplicate CSV data by default starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). The de-duplication can be disabled by passing `reduce_mem_usage=1` query arg to `/api/v1/export/csv` handler.
