### ISSUE TITLE
Improved data in returned error messages

### ISSUE THREAD

**Issue by ful09003** [VictoriaMetrics/VictoriaMetrics#1839]
**Is your feature request related to a problem? Please describe.**
When running `vmselect` in particular, the already exceptional return messaging for e.g. "this query requested too much memory" is very helpful. I find that - especially in cases when evaluating VictoriaMetrics for production use - it would be helpful to further increase the amount of detail returned.

In my particular case, we ran into an issue where a query ranging across high-cardinality data resulted in such an error message as:

```
cannot execute query: cannot evaluate "rate(high-cardinality-metric[15m])": not enough memory for processing 703183503 data points across 487983 time series with 1441 points in each time series; total available memory for concurrent requests: 8000000000 bytes; possible solutions are: reducing the number of matching time series; switching to node with more RAM; increasing -memory.allowedPercent; increasing `step` query arg (60s)
```

Through a series of trial-and-error, we were able to find an appropriate upper ceiling of memory allocation, but the experience highlighted at least one area where the (again -- already exceptional -- thank you for taking the time to think through your error messaging!) messaging could be improved.

**Describe the solution you'd like**
I would love to see the particular error messaging above improved to indicate how many bytes were requested. I took a naive look [at the code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9a3d0c43b5bad3bdd27fed752d20a799b8adb700/app/vmselect/promql/eval.go#L727-L735) sourcing this message, and it looks like by logging the `rollupMemorySize`, this would suffice?

I opened https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1838 for consideration to have this logged. I'd be happy to add this into any other error messaging, if the VictoriaMetrics maintainers feel it would be helpful in other areas, too. Pointers to those areas would be much appreciated, if they exist.

**Describe alternatives you've considered**
There are no clear alternatives to this that I arrived to, other than asking users to continue trial-and-error adjustments to `vmselect` resource limits.

**Additional context**
n/a

**Comment by valyala** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1838 has been merged into mainline and will be included in [v1.70.0 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
