### ISSUE TITLE
vmstorage: Need documents on how to increase retention period

### ISSUE THREAD

**Issue by pxy012** [VictoriaMetrics/VictoriaMetrics#1840]
Hi all
I've a cluster with 3 vmstorage instance with -retentionPeriod 90d currently. 
As "Cluster resizing and scalability" described here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-resizing-and-scalability , -retentionPeriod should be same in one cluster.
Is there any chance to gracefully increase retentionPeriod to 6 months without dataloss?

**Comment by YuriKravetc** [comment]
Hello,
You can specify new `-retentionPeriod` for `vmstorage` nodes and restart `vmstorage ` nodes in the cluster.

**Comment by pxy012** [comment]
> 

Hi
I tried to restart vmstorage instance with new -retentionPeriod gradually. And I expect there will be some error/warn like "different -retentionPeriod in cluster" logged in vmstorage logs, but I found nothing special in log during restart, so I'm not sure whether there's data loss happened. (In grafana it looks like no visible data loss)

I wonder how vmstorage dealing with different -retentionPeriod when they run as a cluster?  (i.e. pick the shortest retentionPeriod in this cluster?)

**Comment by YuriKravetc** [comment]
Hi,
All in all, there should be no data loss.

In general, you are configuring the users and routing to the required storage with a retention period.
For multiple retentions, please check the following:
https://docs.victoriametrics.com/#multiple-retentions

**Comment by hagen1778** [comment]
Should be addressed at https://docs.victoriametrics.com/#retention
