### ISSUE TITLE
When there are a lot of new metrics, what is the main memory consumption of vmstorage?

### ISSUE THREAD

**Issue by guidao** [VictoriaMetrics/VictoriaMetrics#1845]
When I crawl a relatively large k8s cluster via vmagent, I need to add a label to all the metrics. i reserved 40% of the memory, but the vmstorage process still gets killed (oom).

How should the linear relationship between memory and new metrics be predicted?

![image](https://user-images.githubusercontent.com/3192136/142852733-1d2acac9-b283-4579-a289-abcac14c2ba6.png)

![image](https://user-images.githubusercontent.com/3192136/142852858-de1309fc-196e-472e-a128-cc69d0ab77ec.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ vmstorage  --version
vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5
```

Four vmstorage processes are deployed per machine. Each vmstorage disk footprint is as follows:
```
# du -d 1 -h
250G . /data
4.0K . /snapshots
8.0K . /metadata
288K . /cache
. 217G . /indexdb
466G .
```

**Comment by YuriKravetc** [comment]
Hello,

Please try to upgrade to v1.69.
There was a memory usage optimization on v1.63.0
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.63.0

**Comment by guidao** [comment]
Thank you very much, test the new version, a lot of improvements.
