### ISSUE TITLE
Disk snapshots instead of using vmbackup

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#1846]
Hello,

Is it a good strategy to snapshot cloud persistent disks to backup VictoriaMetrics data? vmbackup works well but it's slow when backing up large amounts of data.
I imagine there is a risk for some data files to be out of sync (e.g. index vs data files) with this strategy if some buffers are not flushed to disk prior to taking the snapshot. Can VictoriaMetrics recover from this kind of issue during startup? Losing a few seconds or minutes of metrics in those conditions is not a problem for us but we'd like to make sure VictoriaMetrics will be able to restart.

Thanks

**Comment by YuriKravetc** [comment]
Hello,

Snapshots are safe to partially written data (writes are atomic).

`it's slow when backing up large amounts of data`
You can consider trying Smart Backups: https://docs.victoriametrics.com/vmbackup.html#smart-backups
Or try Backup Manager (part of the Enterprise package).

**Comment by alexandv** [comment]
Thanks Yuri.

We are already using incremental/smart backups with vmbackup but it can still be slow when a lot of merges have occurred or a lot of data has been received during 2 backups. I'll try the snapshot solution.
