### ISSUE TITLE
Packaging for MacBook m1

### ISSUE THREAD

**Issue by afoninsky** [VictoriaMetrics/VictoriaMetrics#1851]
Trying to launch binary on my new shiny macbook with ARM:

```
curl -L https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.69.0/victoria-metrics-arm64-v1.69.0.tar.gz --output /tmp/vm.gz
tar zxvf /tmp/vm.gz
❯ ./victoria-metrics-prod
zsh: exec format error: ./victoria-metrics-prod
```

Is it fine?

**Comment by f41gh7** [comment]
macOs uses darwin/arm64 format, for now it's not supported.

 Work around - build from sources with command: `GOARCH=arm64 GOOS=darwin make package-victoria-metrics`. Docker required.
