### ISSUE TITLE
vmgateway list of labels in extra_labels

### ISSUE THREAD

**Issue by zensu** [VictoriaMetrics/VictoriaMetrics#1863]
**Is your feature request related to a problem? Please describe.**
I've deployed vmgateway for access control to metrics that are in one tenant (because I can't split metrics by label-to-tenant).
I have only one vmagent in k8s cluster which scrapes kube-state-metrics/kubelet/etc metrics with further providing it to a lot of teams by namespace.

**Describe the solution you'd like**
I would like to be able specify one label (or two labels) with multiple different values.
For example now extra_labels 
```
"extra_labels": {
  "namespace": "dev-1",
  "cluster": "develop"
}
```
will be allow only metrics with labels `{cluster="develop",namespace="dev-1"}`
But I want to specified a list of available labels for user.
```
"extra_labels": [
  {
    "namespace": "dev-1",
    "cluster": "develop"
  },
  {
    "namespace": "prom-1",
    "cluster": "prom"
  }
]
```
Is it possible to add this feature? 

**Describe alternatives you've considered**
Also may be you have some workaround for case when vmagent scrapes kube-state-metrics/kubelet/whatever and split metrics by label to different tenants?

**Comment by denisgolius** [comment]
Hi @zensu !
You can try to use relabeling keep/drop metrics for each remote_write - see https://docs.victoriametrics.com/vmagent.html#relabeling and more information about relabeling on this link https://valyala.medium.com/how-to-use-relabeling-in-prometheus-and-victoriametrics-8b90fc22c4b2 . 
See also https://docs.victoriametrics.com/vmagent.html#splitting-data-streams-among-multiple-systems

**Comment by zensu** [comment]
Hi @denisgolius 

I have really a lot of namespaces and if I'll go to use relabelConfig then I should be write remote_write paths for each team. If I get this right, this will be almost impossible because there are many namespaces and they are different in each cluster.

May be you have any other workaround without using big amount of remote_writes for vmagent?

**Comment by f41gh7** [comment]
I think, it's better to add additional field - `extra_filters`, which supports promql filters. For instance:

```json
{
 "extra_labels": {
  "project": "dev"
}, 
 "extra_filters": [ "{namespace=~\"dev-1|dev-2\" }" ]
}
```
 In this case, label `project=dev` applies to the insert requests.
 
 for select request two additional filters applied - `{ project="dev", namespace=~"dev-1|dev-2" }`

 Working on this implementation.

**Comment by valyala** [comment]
VictoriaMetrics accepts `extra_filters[]` query arg in Prometheus querying APIs starting from the commit ff15a752c11c3f110ecd6f990f3aaa3b2075460f . For example, `/api/v1/query?query=up&extra_filters[]={env=~"dev|prod",project="xxx"}` would add the given `extra_filters[]` to the `query`.

@f41gh7 , could you add `extra_filters[]` handling to [vmgateway](https://docs.victoriametrics.com/vmgateway.html)?

**Comment by valyala** [comment]
FYI - VictoriaMetrics accepts `extra_filters[]` query args starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by zensu** [comment]
> FYI - VictoriaMetrics accepts `extra_filters[]` query args starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).


Hello @valyala @f41gh7 
Thanks for that feature, it works good. 
vmgateway still can't handle extra_filters[], right? I just tried to test extra_filters[] in vmgateway v1.71.0 and got failed :)

**Comment by f41gh7** [comment]
Work still in progress. It will be included into the next release.

**Comment by valyala** [comment]
`vmgateway` starts supports `extra_filters` option starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/vmgateway.html#access-control). Closing the feature request as done.
