### ISSUE TITLE
Rebalancing data when adding new vmstorage node

### ISSUE THREAD

**Issue by albertdb** [VictoriaMetrics/VictoriaMetrics#188]
Hi,

First, thank you for creating this awesome project and open sourcing it.

I understand that due to jump consistent hashing, when adding a new vmstorage node, part of the timeseries will be inserted onwards in the new node.

* But is there any rebalancing of the existing data?
In theory, 1/N timeseries should be rebalanced to the new node in order to use the same hashing algorithm on vmselect. 

* If it is not the case, how does a vmselect node know where to find certain data?
  * Does it query all vmstorage nodes?

Thanks again

**Comment by tenmozes** [comment]
Hi @albertdb thank you, 
we have an item in our roadmap which will solve re-balancing issue
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/103

**Comment by albertdb** [comment]
> Hi @albertdb thank you,
> we have an item in our roadmap which will solve re-balancing issue
> #103

That's good to know. So, since there is no rebalancing, how does a vmselect node know where to find certain data? Does it query all vmstorage nodes?

**Comment by tenmozes** [comment]
Yes, vmselect queires all nodes
If one(or more) of the nodes are off response is marked as partial

**Comment by albertdb** [comment]
Ok. Do you plan to change that behaviour once cluster rebalancing is implemented? So when the cluster is balanced (each vmstorage node only has its 1/N timeseries) use jump consistent hashing to determine which vmstorage nodes to query, and when the cluster is unbalanced query all nodes. I fear that querying always all nodes wouldn't scale properly.

**Comment by tenmozes** [comment]
You're right the current solution has limitations (up to 50 storage nodes), but it's hard to have setup which needs so many nodes.

**Comment by albertdb** [comment]
@valyala Thanks for the elaborated answer. I'm not against manual rebalancing, since adding more vmstorage nodes will be usually a manual process, and in case of automating it, running vmctl is also automatable.

Just one additional question and a comment.

>  But this rebalancing will work only on immutable data, i.e. when the vmstorage node used for data rebalancing is stopped.

Do you mean that only the new vmstorage node will need to be stopped or should the cluster be in a locked state (no inserts). I guess that since there are snapshots and rebalancing could be based on that, the cluster could be running normally.

> Data is eventually rebalanced after adding vmstorage nodes when old data on old vmstorage nodes is removed according to the configured -retentionPeriod.

Not really convincing. The aim of using a solution like VM is to store timeseries for years and years. For me that's the same as saying that if you drop all data, it will be balanced.

**Comment by valyala** [comment]
> Do you mean that only the new vmstorage node will need to be stopped or should the cluster be in a locked state (no inserts). I guess that since there are snapshots and rebalancing could be based on that, the cluster could be running normally.

Thanks for the pointer - it looks like rebalancing can be performed from snapshots, while `vmstorage` nodes can continue running. We should think more about this.

> Not really convincing. The aim of using a solution like VM is to store timeseries for years and years. For me that's the same as saying that if you drop all data, it will be balanced.

Agreed - in this case manual rebalancing via `vmctl` should help :)

**Comment by Oloremo** [comment]
Any updates on this?

**Comment by jicki** [comment]
Any updates on this?

**Comment by valyala** [comment]
Closing this issue as a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2324 . We aren't going to add automatic re-balancing of data among vmstorage nodes. There are chances that the manual re-balancing will be added sometimes in the future. This is tracked at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2324 .
