### ISSUE TITLE
warning:Querying metrics using Prometheus web console

### ISSUE THREAD

**Issue by k8sre** [VictoriaMetrics/VictoriaMetrics#1887]
**Describe the bug**
Querying metrics using Prometheus web console. 
warning: remote_read: remote server http://vmselect.monitoring.svc.cluster.local:8481/select/0/prometheus returned HTTP status 400 Bad Request: remoteAddr: "10.64.5.14:44062"; requestURI: /select/0/prometheus; unsupported path requested: "/select/0/prometheus"

It‘s normal to query metrics using grafana.

**Version**
VictoriaMetrics: 1.69.0
Prometheus: 2.31.1

**Comment by denisgolius** [comment]
Hi @k8sre !
VictoriaMetrics has an own **vmui** which is available at the  `http://vmselect.monitoring.svc.cluster.local:8481/select/0/vmui/`. Try it to run your queries.

**Comment by k8sre** [comment]
The vmui queries cannot automatically complete the metrics name

**Comment by k8sre** [comment]
It can't auto-completed the metrics name when I use the vmui queries.

**Comment by denisgolius** [comment]
Did you enable autocomplete ?
![image](https://user-images.githubusercontent.com/5650611/144015572-d9f1caca-5704-40c2-b3a7-95b77b8d494a.png)

**Comment by hagen1778** [comment]
Hi @k8sre!
From the err message I see that you're trying to configure `remote_read` with VM server as source. 
VM [does not support remote read API](https://docs.victoriametrics.com/FAQ.html?highlight=remote%20read#why-victoriametrics-doesnt-support-prometheus-remote-read-api) for reasons.
However, it understands PromQL, so you can use Grafana, Promxy or any other UI which will send PromQL queries (not remote read API).

**Comment by k8sre** [comment]
> Did you enable autocomplete ?
> ![image](https://user-images.githubusercontent.com/5650611/144015572-d9f1caca-5704-40c2-b3a7-95b77b8d494a.png)

Already enabled

**Comment by k8sre** [comment]
> Hi @k8sre!
> From the err message I see that you're trying to configure `remote_read` with VM server as source.
> VM [does not support remote read API](https://docs.victoriametrics.com/FAQ.html?highlight=remote%20read#why-victoriametrics-doesnt-support-prometheus-remote-read-api) for reasons.
> However, it understands PromQL, so you can use Grafana, Promxy or any other UI which will send PromQL queries (not remote read API).

The old version works

**Comment by hagen1778** [comment]
> The old version works

The old version of what? Could you please elaborate more on your setup? Thanks!

**Comment by k8sre** [comment]
> > The old version works
> 
> The old version of what? Could you please elaborate more on your setup? Thanks!

victoriametrics version: v1.48.0
Prometheus: v2.24.0
I can queries from Prometheus.So I thought the new version was OK.

Thank you very much, since the new version does not support, I try to use vmui
