### ISSUE TITLE
gaps in metrics after bumping vmagent to v1.69.0

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/VictoriaMetrics#1889]
**Describe the bug**
After upgrading `vmagent` to the latest version `v1.69.0` we faced the problem with wholes in the metrics.
I checked multiple metrics and for all of them I can find a skipped sample. We are scraping each 15s.

**To Reproduce**
I'm not sure, in my case only v1.69.0 shows such gaps, previously we faced high memory consumption on `vmagent-v1.67.0` which is fixed on `v.1.69.0`

**Expected behavior**
No samples are missing

**Logs**
I couldn't find anything about missing scrapes or something like that in the logs

**Screenshots**

here is an example counter with gaps
<img width="1378" alt="Screenshot 2021-11-30 at 15 56 37" src="https://user-images.githubusercontent.com/5423271/144075031-c58be290-8cc3-471a-9cbd-fa2aa95d4aa7.png">
and closer look

<img width="1364" alt="Screenshot 2021-11-30 at 16 18 26" src="https://user-images.githubusercontent.com/5423271/144075122-2568c6dc-a56b-4eb2-97bb-175919430548.png">

**Version**
```
/ # /vmagent-prod --version
vmagent-20211108-135505-tags-v1.69.0-0-g69e655ba7
```

**Used command-line flags**
```
  victoria-metrics-agent:
...
    Port:          8429/TCP
    Host Port:     0/TCP
    Args:
      -promscrape.config=/config/scrape.yml
      -remoteWrite.tmpDataPath=/tmpData
      -remoteWrite.url=http://victoria-metrics-cluster-a-vminsert:8480/insert/0/prometheus/
      -remoteWrite.url=http://victoria-metrics-cluster-b-vminsert:8480/insert/0/prometheus/
      -envflag.enable=true
      -envflag.prefix=VM_
      -loggerErrorsPerSecondLimit=2
      -loggerFormat=json
      -loggerLevel=INFO
      -loggerOutput=stdout
      -loggerWarnsPerSecondLimit=1
      -memory.allowedPercent=60
      -promscrape.config=/config/prometheus.yml
      -promscrape.configCheckInterval=10s
      -promscrape.maxScrapeSize=128MB
      -promscrape.suppressScrapeErrors=true
      -remoteWrite.showURL=true
```

please let me know what else I can provide

**Comment by YuriKravetc** [comment]
Hi,

Can you attach the graphs from the Troubleshooting part, please?

**Comment by shusugmt** [comment]
I think this is related to #1807 as the series which seems to be affected is `container_*` came from cadvisor in k8s cluster in both cases. I'm facing the quite similar issue with vmsingle 1.68.0 and came across [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1807#issuecomment-971676733) which DID actually solve the problem. But still I can't figure out why this `honor_timestamp: false` is related to this situation.

**Comment by Vladikamira** [comment]
sure!
Here are some details about our setup:
multiregional `k8s` cluster has 2 `Victoria-Metrics clusters` - one per zone.
2 `vmagents` are scraping all pods from the `k8s` cluster and points to both `Victoria-Metrics` clusters so we expect to have a copy of data in every zone.
all Pods scraped by only one `Job`.

The moment of switching to `v.1.69.0` was roughly at `2021-11-30 12-45`.
<img width="1373" alt="Screenshot 2021-12-01 at 11 54 04" src="https://user-images.githubusercontent.com/5423271/144221935-c0fdaa74-e7bd-4018-9995-953516bce3b6.png">

dashboard
<img width="1364" alt="Screenshot 2021-12-01 at 11 30 33" src="https://user-images.githubusercontent.com/5423271/144220710-8a0b5ae2-8c38-4f05-a617-172fd7bc7467.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 30 49" src="https://user-images.githubusercontent.com/5423271/144220736-1a921226-0513-45de-a242-db65de7ac2b8.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 31 02" src="https://user-images.githubusercontent.com/5423271/144220753-f0befbe4-da8a-4450-996f-628f5cb48d44.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 31 19" src="https://user-images.githubusercontent.com/5423271/144220757-42d4b8f2-0408-4e15-99f3-27b1b9188481.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 31 32" src="https://user-images.githubusercontent.com/5423271/144220761-b4a5a2b7-9883-4005-b7d0-89ccb6f80f80.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 31 43" src="https://user-images.githubusercontent.com/5423271/144220786-63fc445e-569a-4d3f-b46f-a76aef070553.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 32 01" src="https://user-images.githubusercontent.com/5423271/144220795-7cd1b2aa-f74d-44f7-9b5d-fe81d4088b99.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 32 28" src="https://user-images.githubusercontent.com/5423271/144220800-4a46a884-643d-4519-8fda-73b0d7a85b10.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 32 51" src="https://user-images.githubusercontent.com/5423271/144220809-df4dde6a-9ce9-4154-aeba-3d1036be2259.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 33 02" src="https://user-images.githubusercontent.com/5423271/144220814-7a937897-d9e4-4034-8d34-c7952e169cf5.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 33 16" src="https://user-images.githubusercontent.com/5423271/144220860-f0a12912-bc6e-4d96-964a-ccec5dfc1b16.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 33 30" src="https://user-images.githubusercontent.com/5423271/144220857-8cd7ff25-6590-467f-9b6b-a2d79747a5f1.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 33 42" src="https://user-images.githubusercontent.com/5423271/144220847-d6efdcfb-2146-422d-898c-baf251d8d1b4.png">
<img width="1356" alt="Screenshot 2021-12-01 at 11 33 56" src="https://user-images.githubusercontent.com/5423271/144220854-8ef211a2-e5d3-422f-938d-840ccf6e06dd.png">

**Comment by Vladikamira** [comment]
> I think this is related to #1807 as the series which seems to be affected are `container_*` came from cadvisor in k8s cluster in both cases. I'm facing the quite similar issue with vmsingle 1.68.0 and came across [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1807#issuecomment-971676733) which DID actually solve the problem. But still I can't figure out why/how this `honor_timestamp: false` is related to this situation.

thanks @shusugmt, that actually helped 👍 

interesting how VMagent's resource consumption has changed after that: 

<img width="1373" alt="Screenshot 2021-12-01 at 13 35 45" src="https://user-images.githubusercontent.com/5423271/144236277-e1711e6f-99a6-42c2-a858-ec8a6f318e1f.png">

at 13:20 I applied `honor_timestamps: false` and after that there were no gaps

**Comment by shusugmt** [comment]
> interesting how VMagent's resource consumption has changed after that:

I'm observing the exact same change. I only applied `honor_timestamps: false` parameter to the job that scrapes cadvisor, now question is whether I should apply this to all the jobs in scrape config or not. Need clarification from someone who can shed light on what's going on underneath...

**Comment by valyala** [comment]
@shusugmt , @Vladikamira , please see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1807#issuecomment-984523424 .

Closing this issue as a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1807 . Let's continue the conversation here.
