### ISSUE TITLE
InfluxDB Authorization: Token support

### ISSUE THREAD

**Issue by Karsonito** [VictoriaMetrics/VictoriaMetrics#1897]
**Is your feature request related to a problem? Please describe.**
1. I cannot configure authorization to write to victoriametrics via [influxdb-client-php](https://github.com/influxdata/influxdb-client-php) library. This library only supports the Authorization: Token scheme. There is no way to use Basic and Bearer schemas in influxdb-client-php library (intended for influxdb 2. *) does not support Basic (it remained only in influxdb 1. *). See https://docs.influxdata.com/influxdb/v2.0/api/#section/Authentication/TokenAuthentication
2. victoriametrics and vmauth does not support Token

**Describe the solution you'd like**
Please add support for Authorization: Token in victoriametrics and vmauth

**Comment by tedpearson** [comment]
I ran into this with a couple projects that used the golang influx v2 client. I just finished rearchitecting them to use the golang influx v1 client, which uses Basic/Bearer auth, and was rather onerous. Since the v2 clients are the only ones developed going forward, this enhancement seems fairly important to the future usability of VM.

**Comment by dcircelli** [comment]
I have the same problem trying to use the [Netapp Harvest tool](https://github.com/NetApp/harvest) with an InfluxDB exporter. It only supports Influx's "Token" authorization scheme.

**Comment by valyala** [comment]
`vmauth` supports `Auhtorization: Token ...` request header starting from [v1.75.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It is treated in the same way as `Authorization: Bearer ...` request header. Closing this feature request as done.
