### ISSUE TITLE
Data are not returned for specific interval and labels.

### ISSUE THREAD

**Issue by VitBartunek** [VictoriaMetrics/VictoriaMetrics#1899]
**Describe the bug**

On 90d interval the return array from VM is empty. When I change interval to 6 months or 30 days (in Grafana) data are returned properly.

Clearing cache does not resolve the problem this time (via reset_cache_on_startup file or manually), although it helped me and resolved the issue last time (3 month ago).

**To Reproduce**

Query which returns empty dataset:
curl -G 'http://192.168.1.105:8428/api/v1/query_range?query=node_memory_MemAvailable_bytes\{instance=~"192\\.168\\.1\\.109:9100"\}&start=1630418400&end=1638198000&step=3600&timeout:"30s"'

Result:
{"status":"success","data":{"resultType":"matrix","result":[]}}

I tried some modifications and these queries are working:

without instance label
curl -G 'http://192.168.1.105:8428/api/v1/quelable_bytes&start=1630418400&end=1638198000&step=3600&timeout:"30s"'
increased step
curl -G 'http://192.168.1.105:8428/api/v1/query_range?query=node_memory_MemAvailable_bytes\{instance=~"192\\.168\\.1\\.109:9100"\}&start=1630418400&end=1638198000&step=360000&timeout:"30s"'

**Expected behavior**

90day interval, query bellow returns data
curl -G 'http://192.168.1.105:8428/api/v1/query_range?query=node_memory_MemAvailable_bytes\{instance=~"192\\.168\\.1\\.109:9100"\}&start=1630418400&end=1638198000&step=3600&timeout:"30s"'

**Logs**
No new log entry during query.

**Screenshots**
![VM1](https://user-images.githubusercontent.com/5277835/144431177-dec4ca22-5b1e-48d0-9ad5-e41b22b2e287.png)
![VM2](https://user-images.githubusercontent.com/5277835/144431182-79524267-5a49-42a4-b36c-25166bd93ff6.png)

VictoriaMetrics health-state 
![VM3](https://user-images.githubusercontent.com/5277835/144431960-40e9a9b3-333b-4b2b-bd34-b3f32414ffce.png)
![VM4](https://user-images.githubusercontent.com/5277835/144431979-f5908962-679d-40c3-a26b-a6131bfc32bd.png)
![VM5](https://user-images.githubusercontent.com/5277835/144431985-633e46f0-08f8-4f84-81d5-2aaabad5a51b.png)
![VM6](https://user-images.githubusercontent.com/5277835/144431987-a3373719-89c4-46ca-a878-3283affcf3e7.png)
![VM7](https://user-images.githubusercontent.com/5277835/144431990-350d37f9-f694-4b45-b685-f0f23959a65f.png)

**Version**

I tried versions "v1.69.0" (victoria-metrics-20211108-135302-tags-v1.69.0-0-g69e655ba7) and  v1.66.2" with the same results.

**Used command-line flags**

 command: -envflag.enable
    env:
      bigMergeConcurrency: "8"
      dedup_minScrapeInterval: "2ms"
      deleteAuthKey: "XXXX"
      denyQueriesOutsideRetention: "true"
      finalMergeDelay: 90s
      httpAuth_username: "XXXX"
      httpAuth_password: "XXXX"
      influxSkipSingleField: "true"
      loggerFormat: json
      loggerLevel: INFO
      graphiteListenAddr: ":2003"
      maxLabelsPerTimeseries: "60"
      memory_allowedBytes: 32GB
      promscrape_config: "/config/scrape/config.yml"
      promscrape_disableKeepAlive: "false"
      promscrape_configCheckInterval: 1m
      promscrape_fileSDCheckInterval: 1m
      promscrape_maxScrapeSize: 32MB
      retentionPeriod: "49"
      search_cacheTimestampOffset: 7m
      search_maxQueryDuration: 30s
      search_maxQueryLen: "32768"
      search_maxUniqueTimeseries: "900000"
      search_logSlowQueryDuration: 20s
      selfScrapeInterval: 30s
      smallMergeConcurrency: "8"
      tmp_reload: "2"

**Comment by valyala** [comment]
@VitBartunek , try removing the file `metadata/minTimestampForCompositeIndex` in the directory specified by `-storageDataPath` and then restarting VictoriaMetrics. This can help if VictoriaMetrics has been upgraded from version prior v1.54.0 and then downgraded back to version prior to v1.54.0 . See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1486#issuecomment-899529214 for details.

**Comment by valyala** [comment]
Try also stopping VictoriaMetrics, then removing the `cache` subdirectory inside the directory specified by `-storageDataPath` and then starting VictoriaMetrics. Note that the `cache` subdirectory must be removed when VictoriaMetrics isn't running. Otherwise it will be re-created on VictoriaMetrics shutdown.

**Comment by VitBartunek** [comment]
> @VitBartunek , try removing the file `metadata/minTimestampForCompositeIndex` in the directory specified by `-storageDataPath` and then restarting VictoriaMetrics. This can help if VictoriaMetrics has been upgraded from version prior v1.54.0 and then downgraded back to version prior to v1.54.0 . See [#1486 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1486#issuecomment-899529214) for details.

Thank you for prompt reply, removing the metadata/minTimestampForCompositeIndex solved the issue. I cannot confirm or disprove the upgrade->downgrade as I'm not aware of that happened. Anyway thank you very much for your help and at last I wan't say that after experiences with Graphite, Prometheus / InfluxDB I'm very satisfied with performance and ability of VictoriaMetrics! Thanks for that!

**Comment by valyala** [comment]
@VitBartunek , thanks for the update. Then closing this issue as duplicate for #1486 .
