### ISSUE TITLE
SHA sum of binary in release files

### ISSUE THREAD

**Issue by hatemosphere** [VictoriaMetrics/VictoriaMetrics#19]
Could you please add sha256 sum of binary to release files, so it can be easily verified in configuration management routines? Thanks in advance!

**Comment by valyala** [comment]
@hatemosphere, I'm unsure I properly understand the request.
Could you point to an example project with release files containing sha256 sum?

**Comment by hatemosphere** [comment]
@valyala eg. https://github.com/dreamteam-gg/clickhouse_exporter/releases. you can use go releaser as a convenience wrapper for that.

**Comment by hatemosphere** [comment]
@valyala still no SHA in releases?)

**Comment by valyala** [comment]
Sorry for the long delay. The next release will contain files with SHA265 sums

**Comment by valyala** [comment]
@hatemosphere , `_checksums.txt` files are available starting from [v1.29.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
