### ISSUE TITLE
Add a description for the Query field in vmui

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#1900]
**Is your feature request related to a problem? Please describe.**
It is difficult to understand where is Query Field for the new users.

**Describe the solution you'd like**
Add a description for the Query field in vmui

See the screenshot 
![image](https://user-images.githubusercontent.com/5650611/144586406-295f984e-7852-400c-88f7-f8df722707fb.png)

**Comment by valyala** [comment]
The `query` caption has been added to query input field starting from [VictoriaMetrics v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
