### ISSUE TITLE
Vmagent: Add a configurable limit on label value length 

### ISSUE THREAD

**Issue by Alexul** [VictoriaMetrics/VictoriaMetrics#1908]
**Is your feature request related to a problem? Please describe.**
Current hardcoded maxLabelValueLen of 16 * 1024 is probably too high. Having target with a lot of huge labels leads to a very high mem usage on vmagent and OOM

**Describe the solution you'd like**
Ability to pass maxLabelValueLen as a param

**Comment by valyala** [comment]
The `-maxLabelValueLen` command-line flag has been added in the commit 45d082bbe24fe8f4672ddb56335bc01df6b35acf . This commit will be included in the next release. In the mean time it can be tested by building VictoriaMetrics from source code according to [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by valyala** [comment]
FYI, VictoriaMetrics accepts `-maxLabelValueLen` command-line flag starting from [v1.71.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
