### ISSUE TITLE
vmagent does not write an error when sending data to victoriametrics

### ISSUE THREAD

**Issue by CHERTS** [VictoriaMetrics/VictoriaMetrics#1911]
**Describe the bug**
vmagent does not write an error to the log when sending data to victoriametrics if an bad remoteWrite.url is specified.

**To Reproduce**
1. Install and run latest victoriametrics non cluster version using simple options (-storageDataPath=/var/lib/victoria -retentionPeriod=7d)
2. Install and run latest vmagent using simple options (-promscrape.config=/etc/victoriametrics/vmagent.yml -remoteWrite.url=http://localhost:8428/api/v1/writez -remoteWrite.tmpDataPath=/var/lib/vmagent)

**remoteWrite.url is BAD**, data collect but not sending to victoriametrics and there are no errors in the log

File /etc/victoriametrics/vmagent.yml:

```
global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: victoriametrics
    static_configs:
    - targets:
      - localhost:8428
  - job_name: vmagent
    static_configs:
    - targets:
      - localhost:8429
```

**Expected behavior**
I expect the vmagent to write to the log that it cannot send the collected data, but it does not. All data is accumulated in remoteWrite.tmpDataPath, but this is not clear and misleading me (makes it appear that everything is fine, but it is not).

**Logs**
ps -ef | grep vmagent-prod
```
victori+  19106      1  0 22:01 ?        00:00:00 /usr/local/bin/vmagent-prod -promscrape.config=/etc/victoriametrics/vmagent.yml -remoteWrite.url=http://localhost:8428/api/v1/writez -remoteWrite.tmpDataPath=/var/lib/vmagent
```

ps -ef | grep [v]ictoria-metrics-prod
```
victori+   6158      1  0 22:00 ?        00:00:01 /usr/local/bin/victoria-metrics-prod -storageDataPath=/var/lib/victoria -retentionPeriod=7d
```

vmagent log:
```
Dec 07 22:01:54 myhost systemd[1]: Started VictoriaMetrics Agent Service.
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.982Z        info        VictoriaMetrics/lib/logger/flag.go:12        build version: vmagent-20211202-133503-tags-v1.70.0-0-g7f2f26b25
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.983Z        info        VictoriaMetrics/lib/logger/flag.go:13        command line flags
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.983Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "promscrape.config"="/etc/victoriametrics/vmagent.yml"
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.983Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "remoteWrite.tmpDataPath"="/var/lib/vmagent"
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.983Z        info        VictoriaMetrics/lib/logger/flag.go:20        flag "remoteWrite.url"="secret"
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.983Z        info        VictoriaMetrics/app/vmagent/main.go:93        starting vmagent at ":8429"...
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.983Z        info        VictoriaMetrics/lib/memory/memory.go:37        limiting caches to 81105449779 bytes, leaving 54070299853 bytes to the OS according to -memory.allowedPercent=60
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.989Z        info        VictoriaMetrics/lib/persistentqueue/fastqueue.go:59        opened fast persistent queue at "/var/lib/vmagent/persistent-queue/1_BA2D4C9F3D30C578" with maxInmemoryBlocks=6400, it contains 0 pending bytes
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.989Z        info        VictoriaMetrics/app/vmagent/remotewrite/client.go:151        initialized client for -remoteWrite.url="1:secret-url"
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.989Z        info        VictoriaMetrics/app/vmagent/main.go:118        started vmagent in 0.007 seconds
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.989Z        info        VictoriaMetrics/lib/promscrape/scraper.go:101        reading Prometheus configs from "/etc/victoriametrics/vmagent.yml"
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.989Z        info        VictoriaMetrics/lib/httpserver/httpserver.go:87        starting http server at http://:8429/
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.990Z        info        VictoriaMetrics/lib/httpserver/httpserver.go:88        pprof handlers are exposed at http://:8429/debug/pprof/
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.990Z        info        VictoriaMetrics/lib/promscrape/config.go:78        starting service discovery routines...
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.990Z        info        VictoriaMetrics/lib/promscrape/config.go:84        started service discovery routines in 0.000 seconds
Dec 07 22:01:54 myhost victoria-agent[19106]: 2021-12-07T19:01:54.991Z        info        VictoriaMetrics/lib/promscrape/scraper.go:387        static_configs: added targets: 2, removed targets: 0; total targets: 2

```

victoriametrics log:
```
Dec 07 22:02:32 myhost victoria-prod[6158]: 2021-12-07T19:02:32.992Z warn        VictoriaMetrics/lib/httpserver/httpserver.go:320        remoteAddr: "127.0.0.1:55950"; requestURI: /api/v1/writez; unsupported path requested: "/api/v1/writez"
```

**Version**
vmagent-20211202-133503-tags-v1.70.0-0-g7f2f26b25

**Comment by hagen1778** [comment]
Hi @CHERTS!
vmagent drops packets if rw destination returns 400 or 409 status code starting from [v1.45.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.45.0) for compatibility’s sake.
Please see related issues:
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/873
* and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1149

**Comment by CHERTS** [comment]
Hi, the problem is that the vmagent does not write an error to the log file and is not aware of the problem from the server console.

**Comment by valyala** [comment]
> the problem is that the vmagent does not write an error to the log file and is not aware of the problem from the server console.
Agreed. I think it would be better if `vmagent` would log this case.

In the mean time the following workaround exists: `vmagent` exposes the `vmagent_remotewrite_packets_dropped_total` metric at `http://vmagent:8429/metrics` page. This metric shows the number of dropped packets when the remote storage returns 400 or 409 status code. This metric is also shown in [the official dashboard for vmagent](https://docs.victoriametrics.com/vmagent.html#monitoring) at `Data blocks dropped` graph.

@hagen1778 , WDYT about adding an alerting rule for the `increase(vmagent_remotewrite_packets_dropped_total) > 0` into [the official alerting rules for vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml)?

**Comment by CHERTS** [comment]
The vmagent_remotewrite_packets_dropped_total metric is very useful, but here we are talking about diagnosing work from the server console.

I wrote an issue [1915](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1915) with a proposal to add the ability to view the cluster health in the vmctl utility. For vmagent it would be useful too.

Thanks.

**Comment by valyala** [comment]
@CHERTS , vmagent should log error messages when remote storage returns 400 or 409 http status code starting from the commit 34fdc8881b607259782b9bcc2c7b4842dee20536 . This can be verified by building vmagent from the given commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by CHERTS** [comment]
Thanks, while I do not have the opportunity to build vmagent from source, I will wait for the official release.

**Comment by valyala** [comment]
`vmagent` should log 400 and 409 http status codes received from remote storage starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed.
