### ISSUE TITLE
Showing cluster health in vmctl

### ISSUE THREAD

**Issue by CHERTS** [VictoriaMetrics/VictoriaMetrics#1915]
**Is your feature request related to a problem? Please describe.**
If the cluster becomes bad and it stops working normally, then it becomes impossible to view the cluster monitoring data in Grafana.

**Describe the solution you'd like**
I would like vmctl to implement the functionality of the simplest view of the main cluster health indicators, for example, you can get them from /metrics from the cluster components.

**Comment by valyala** [comment]
I'm afraid [vmctl](https://docs.victoriametrics.com/vmctl.html) isn't the best tool for showing the health of [VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html). The `vmctl` is command-line tool, which doesn't perform any monitoring. I'd recommend you setting up a dedicated [single-node VictoriaMetrics instance](https://docs.victoriametrics.com/) for [monitoring](https://docs.victoriametrics.com/cluster-victoriametrics/#monitoring) VictoriaMetrics cluster components and other VictoriaMetrics components you may use - [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), etc.

This scheme is called [`monitoring of monitoring`](https://victoriametrics.com/products/mom/). It allows you diagnosing and debugging any issues with VictoriaMetrics components by just looking at the collected metrics from these components in the single-node VictoriaMetrics.

Closing this feature request as won't implement.
