### ISSUE TITLE
vmui: introduce application mode

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1918]
**Is your feature request related to a problem? Please describe.**
We want to embed vmui in our application, so users can execute queries and plot graphs. However, we don't want user to configure access URL on his own. Instead, we want to predefine a URL by default.

**Describe the solution you'd like**
A way to provide and additional configuration of the following or similar structure:
```
{
  "serverURL": ""http://localhost/myRouter?customParam=e0077a1a-5b8d-452b-ad89-7b3498f349be"
}

```
, where `serverURL` contains a URL for serverURL field - where to send requests.

The described config should be loaded & parsed before vmui starts to render in any appropriate way (e.g. via setting it to `data` param for parent container).

Please, let me know if there are any questions.

cc @dmitryk-dk @f41gh7

**Comment by valyala** [comment]
The application mode has been merged in 9baad510040cf5d2679130bcefd9ca6e8f198680 and will be available in the next release. See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1949 for details.
