### ISSUE TITLE
Make a sticky header for docs.victoriametrics.com on mobile devices

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#1919]
**Is your feature request related to a problem? Please describe.**
It is hard to scroll back to header or desired menu item when choose something like https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#readonly-mode .

**Describe the solution you'd like**
Make a sticky header for https://docs.victoriametrics.com on mobile devices.

<p align="center">
  <img src="https://user-images.githubusercontent.com/5650611/145436663-659e4d44-2f46-4269-b528-16a14e62cd5c.png" width="300" alt="">
</p>

**Comment by valyala** [comment]
This is already done - try navigating to https://docs.victoriametrics.com/ from smartphone or tablet. Closing the feature request as done.
