### ISSUE TITLE
Add ability to change vmstorage cache size per cache type

### ISSUE THREAD

**Issue by Muxa1L** [VictoriaMetrics/VictoriaMetrics#1940]
**Is your feature request related to a problem? Please describe.**
Problem is that on one of my victoria clusters, due to the load profile on this cluster (it's only reason to exist is for alerting) - I have some cache skew issues. Looks like I mostly need tsid cache, than any other else (if hit rate falls below 99% ingestion rate falls quickly). 
Plus I have some spare ram dedicated to caches, but tsid cache cant use it

**Describe the solution you'd like**
I want to be able to fine-tune cache sizes per type to allocate more memory to specific caches, and make the behavior of cache allocation more predictable

**Additional context**
![image](https://user-images.githubusercontent.com/9287490/145941879-f4f7a48b-74ce-420f-b2e7-d1b6fa8bf2ea.png)

**Comment by valyala** [comment]
VictoriaMetrics doesn't allow changing individual cache sizes. All the cache sizes depend on the available memory on the host where VictoriaMetrics runs. It also depends on `-memory.allowedPercent` and `-memory.allowedBytes` command-line flags:

>  -memory.allowedBytes size
    	Allowed size of system memory VictoriaMetrics caches may occupy. This option overrides -memory.allowedPercent if set to a non-zero value. Too low a value may increase the cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from OS page cache resulting in higher disk IO usage
    	Supports the following optional suffixes for size values: KB, MB, GB, KiB, MiB, GiB (default 0)

>  -memory.allowedPercent float
    	Allowed percent of system memory VictoriaMetrics caches may occupy. See also -memory.allowedBytes. Too low a value may increase cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from OS page cache which will result in higher disk IO usage (default 60)
  -metricsAuthKey string

A temporary workaround is to increase the `-memory.allowedPercent` command-line flag value at `vmstorage` nodes. This will increase the `storage/tsid` cache size proportionally.

**Comment by valyala** [comment]
Note also that the maximum cache size is exported by VictoriaMetrics components at `/metrics` page via `vm_cache_size_max_bytes` metrics starting from [the release v1.70.0](https://docs.victoriametrics.com/CHANGELOG.html#v1700).

Side note: @hagen1778 , it would be great to add the `vm_cache_size_bytes / vm_cache_size_max_bytes` graphs to `troubleshooting` section in the [official VictoriaMetrics dashboards](https://docs.victoriametrics.com/#monitoring). These graphs may help identifying too small caches.

**Comment by Muxa1L** [comment]
@valyala Why not allow change of these coefficients?
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e1a715b0f5cee93e5238dd1bc18990f444cb96aa/lib/storage/storage.go#L200-L202

**Comment by Muxa1L** [comment]
Looks like, in my case, I could lower indexdb/dataBlocks twice (7Gb) and raise this tsid cache for the same amount...
![image](https://user-images.githubusercontent.com/9287490/146165238-4f790ce4-99f1-42e5-843d-819050039ea9.png)

**Comment by valyala** [comment]
@Muxa1L , VictoriaMetrics gains support for overriding default cache size limits via the following command-line flags:
>   -storage.cacheSizeIndexDBDataBlocks size
        Overrides max size for indexdb/dataBlocks cache. See https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#cache-tuning
        Supports the following optional suffixes for size values: KB, MB, GB, KiB, MiB, GiB (default 0)

>  -storage.cacheSizeIndexDBIndexBlocks size
        Overrides max size for indexdb/indexBlocks cache. See https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#cache-tuning
        Supports the following optional suffixes for size values: KB, MB, GB, KiB, MiB, GiB (default 0)

>  -storage.cacheSizeStorageTSID size
        Overrides max size for storage/tsid cache. See https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#cache-tuning
        Supports the following optional suffixes for size values: KB, MB, GB, KiB, MiB, GiB (default 0)

The functionality can be tested by building VictoriaMetrics from the following commits:
* Single-node version: f72b35665ff34d834ca48db7411c9066325ac612 . See [build instructions](https://docs.victoriametrics.com/#how-to-build-from-sources).
* Cluster version: 89ead3dacacdba9857b1d343b300515841f93ab7 . See [build instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

These commits will be included in the next release of VictoriaMetrics.

**Comment by Muxa1L** [comment]
Cool, thank you! Will wait for release =)

**Comment by valyala** [comment]
Command-line flags mentioned above are available starting from [VictoriaMetrics v1.73.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [cache tuning docs](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#cache-tuning) for details.
