### ISSUE TITLE
improve parallelism for kafka consumer 

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1957]
**Is your feature request related to a problem? Please describe.**

  Currently vmagent runs dedicated thread for each consumed topic, it works fine in most cases. But it would be good option to configure consumer thread per topic, it should increase throughput per assigned partition.

**Describe the solution you'd like**
 
 Introduce new configuration flag - `-kafka.consumer.topic.concurrency`, it should define possible assigned partition count per vmagent instance and number of threads, which vmagent should launch per topic. 

**Describe alternatives you've considered**
 Launch multiple instances of vmagent - one per partition.

**Comment by f41gh7** [comment]
It has low priority, will take a look on it soon.

**Comment by valyala** [comment]
FYI, the upcoming release of `vmagent` [enterprise](https://docs.victoriametrics.com/enterprise.html) will support `-kafka.consumer.topic.concurrency` command-line flag for controlling the number of concurrent Kafka consumers.

**Comment by valyala** [comment]
The `-kafka.consumer.topic.concurrency` command-line flag is supported by [vmagent](https://docs.victoriametrics.com/vmagent.html) starting from [v1.90.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
