### ISSUE TITLE
vmrestore add restore lock file

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#1958]
**Is your feature request related to a problem? Please describe.**
  
  In cases of incomplete backup restore VictoriaMetrics may crash at runtime with panic.

**Describe the solution you'd like**

  vmrestore must add `restore-in-progress` file after restoration start and remove it after successfully completion. 

 vmsingle and vmstorage instances must check if this file exists. If it exists, exit with error at startup.

**Comment by valyala** [comment]
[vmrestore](https://docs.victoriametrics.com/vmrestore.html) creates `restore-in-progress` file when restoring data from backups starting from the commit 8ff7da72026f2f92df44e7f705e1462568c83734 . This commit will be included in the next release.

**Comment by valyala** [comment]
`vmrestore` creates `restore-in-progress` file starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), while VictoriaMetrics and vmstorage prevent from running when this file exists (this means that the restore process was interrupted and didn't finished properly). The solution is to re-run `vmrestore` with the same set of arguments again and make sure it completes successfully.
