### ISSUE TITLE
churn rate: why add nodes to cluster make churn rate increase too much

### ISSUE THREAD

**Issue by chengjianyun** [VictoriaMetrics/VictoriaMetrics#1959]
**Describe the bug**
Hi, 

We found churn rate increased too much after added 3 nodes to a 3 nodes cluster (6 nodes in the cluster after scale). Before scale, the churn rate is about 3k/s. After scale the value is become 10k/s. I can understand that the churn rate will increase in re-shard but in my case, it didn't drop after 10 hours. I can sure the business data didn't have big change during the time.

BTW, does my cache size make sense according to active time series?

**Expected behavior**
Churn rate should become same as before after scale in a few hours later.

**Logs** **Screenshots**
![image](https://user-images.githubusercontent.com/6150814/146482726-b1ff00a5-e1d4-4403-85b9-bfb5a31f43d5.png)
![image](https://user-images.githubusercontent.com/6150814/146482777-968a0ae2-c17d-4ff7-9114-67cadf771c61.png)
![image](https://user-images.githubusercontent.com/6150814/146482822-b6f76856-3b6b-490e-8584-af4550b533e6.png)
![image](https://user-images.githubusercontent.com/6150814/146483966-9dda01c3-23f7-45bb-aa4d-d07879ba0ce0.png)

**Version**
```
vmstorage-20211108-140323-tags-v1.69.0-cluster-0-gb1de18088
```

**Used command-line flags**
vminsert
![image](https://user-images.githubusercontent.com/6150814/146483611-4c1fb214-281f-4622-b3a3-76799d7f32b3.png)

vmstorage
```
-storageDataPath /data01/victoriametrics -retentionPeriod 90d -search.maxUniqueTimeseries 10000000
```

**Comment by YuriKravetc** [comment]
Hi,
According to graphs - cache is completely fine and makes sense.

Churn rate requires additional investigation though.
Can you do the following please?:
1) Attach the interconnection + troubleshooting graphs screenshots.
2) For churn rate graph, instead of showing the sum of all nodes, attach the screenshot on specific instance on the interval before resize and after resize.
3) Statsdb for a day before the upgrade and a day after upgrade - might take some time to load.
https://docs.victoriametrics.com/#tsdb-stats
4)What are you writing data with, vmagent\prometheus or something else? 
If vmagent\prometheus - can you check the output with this query and share the results?
 `topk(10, sum(sum_over_time(scrape_series_added[5m])) by (job))`

**Comment by chengjianyun** [comment]
Hi, YuriKravetc

Thanks for you analyse and explain. A day after scale, everything looks good right now. 

![image](https://user-images.githubusercontent.com/6150814/148548752-d80ee668-5296-4e0a-a0b6-33bea0994966.png)

However, I got another issue, if a node of cluster stuck or hung because lack of memory(may be it system were busy on memory page swap, I'm not sure), it will block the data ingest of whole system. Actually I'd like to kill and restart the process but block data ingestion in the situation.  Is there anyway I can acheive that?

![image](https://user-images.githubusercontent.com/6150814/148550245-4ab4081c-1751-44f0-b83f-91009e374b14.png)

![image](https://user-images.githubusercontent.com/6150814/148550566-274ca07b-c92d-4219-b872-2b8d263ff70f.png)

Check system log, process kill after a while.

![image](https://user-images.githubusercontent.com/6150814/148550798-a3215543-bbf0-4b0e-a38c-14da0b9af8c7.png)

**Comment by valyala** [comment]
This issue may be related to uneven data re-routing when a part of nodes in the cluster become overloaded. This may be the case immediately after adding new nodes to the cluster. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1337 . The next release of VictoriaMetrics has some improvements for this case, which should reduce churn rate and the increase in the number of active time series.

**Comment by chengjianyun** [comment]
Sorry reply late. 

It should be caused by data re-routing. After upgrading to latest version(1.76.1), we didn't find the issue any more. 

Close the issue as it has solved.
