### ISSUE TITLE
vmui interface enhancements request

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#1960]
**Is your feature request related to a problem? Please describe.**
While using vmui I realized I lack some UI enhancements. I'll try describe them here and let's see if others will find them useful:
- [x] #1994
- [x] move time-picker panel to the header and make it always visible: 
![image](https://user-images.githubusercontent.com/2902918/146500245-0a61be9f-26e1-4abd-9ef3-a976ad66f545.png)
Ofc, it can't be used as is. I think, we can minimize it into a field "Last: <duration>". Click on it should show a dropdown list from other preset durations (similar to grafana);
Move auto-refresh toggle right to the time picker
- [x] make auto-refresh similar to grafana's button;
- [x] always have Query Configuration field collapsed and rename it to just "Query". When opening UI I care only about how quick I can plot a graph, so having less fields in the view will make it easier to do;
- [x] move query configuration field URL to the header and hide behind "settings" link or relevant icon; Auth settings may be dropped at all
- [x] move buttons 
![image](https://user-images.githubusercontent.com/2902918/146504881-3f35d25a-b86d-4c4a-8440-9c5c6f4c36a0.png)
closer to the graph area, since that is the first place where I would look at when trying to change the display settings;
- [x] it is unclear what `1` are mean for query fields
![image](https://user-images.githubusercontent.com/2902918/146505543-737d8ba6-ad5a-4d50-b6ab-a08181cea409.png)
would it be better to give them aliases like `query A`, `query B` or `query 1`... etc? And use that in the graph legend instead of `Query result` 
![image](https://user-images.githubusercontent.com/2902918/146505673-2ca294af-2d7a-43d2-8909-035a9dcb8ab1.png)
- [x] maybe it is just me, but `click` and `cmd+click` behaviour on the graph's legend is inverted 
![image](https://user-images.githubusercontent.com/2902918/146505804-7cc85a1e-ff77-4f29-895b-4fbc1ef358ed.png)
I'm used to situation when clicking on the item in legend deselect the rest of the items.
- [x] move "Graph settings" toggle to other toggles and make it similar to Override step toggle

Anyway, thanks for your work on vmui! I can only imagine how much work it requires to build it!

cc @valyala @f41gh7

**Comment by valyala** [comment]
UX in the `vmui` has been improved according to this feature request in [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
