### ISSUE TITLE
Does VictoriaMetrics support User Defined Function?

### ISSUE THREAD

**Issue by AbdelouahabKhelifati** [VictoriaMetrics/VictoriaMetrics#1961]
I am currently working on a benchmark of time series database systems for analytical (complex) queries. These queries are algorithms that cannot (easily) be implemented in SQL language so they require a third-party programming language such as C, C++, Python, Java, etc.

I'd like to know whether VictoriaMetrics supports such a feature of a third-party programming language for User Defined Functions?

**Comment by valyala** [comment]
VictoriaMetrics doesn't support the ability to write User Defined Functions in a third-party programming language. It supports e.g. [WITH templates](https://play.victoriametrics.com/promql/expand-with-exprs), which allow re-using common [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) parts in complex queries.

If [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) functionality isn't enough for your data processing case, then the following solutions exist:
* To export raw time series via [export API](https://docs.victoriametrics.com/#how-to-export-time-series) and process it externally with any suitable programming language / platform / solution.
* To add the missing functionality into the source code of VictoriaMetrics at [app/vmselect/promql](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmselect/promql) and to build custom version of VictoriaMetrics from source code (see [these instructions on how to build VictoriaMetrics from sources](https://docs.victoriametrics.com/#how-to-build-from-sources)). We are happy to accept pull requests, which extend MetricsQL in useful ways.
