### ISSUE TITLE
Update documentation. 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#198]
Community request documentation update:
- [x] add information about releases to cluster version (docker hub and github releases)
- [x] update information about backups

**Comment by tenmozes** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#binaries

**Comment by valyala** [comment]
Initial docs about backups are available at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-work-with-snapshots and https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#backups .
