### ISSUE TITLE
VMUI request field overlaps others 

### ISSUE THREAD

**Issue by alex-vaisman** [VictoriaMetrics/VictoriaMetrics#1985]
when I pasted a long request from the clipboard, I got a picture as in the screenshot. This is visual glitch, no data corruption or malfunction detected

![photo_2021-12-20_08-49-16](https://user-images.githubusercontent.com/62017633/146803118-6325bedf-920d-4b26-98c4-766dac32be3c.jpg)

**Comment by valyala** [comment]
This should be addressed in commits 89ff7b24655269032b0c91a3f7682e977dd1a8b9 and ceade70d4ef7df9e132b33128d7493fd8882fe4a , which will be included in the next release.

**Comment by valyala** [comment]
The issue has been fixed in [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
