### ISSUE TITLE
Bump Go version requirement to 1.17, build is broken with 1.16

### ISSUE THREAD

**Issue by cschug** [VictoriaMetrics/VictoriaMetrics#1987]
**Describe the bug**
While the `go.mod` and `README.md` (and maybe other places) mention Go 1.16 as a minimum requirement to build, Go 1.17 is actually needed. 
Seems related to #1892, specifically the changes in [`app/vmalert/datasource/vm_graphite_api.go`](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1892/files#diff-138d70a505a90a02d9670cdec51920b09ff46f105a6ad2476e68f2d766bc59a5R58) and [`app/vmalert/datasource/vm_prom_api.go`](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1892/files#diff-24da32f131234b88ffbebd3cd5665fd93b452f2ebeeda26c2fb39571a4697f74R154) which make use of the [`Has`](https://pkg.go.dev/net/url#Values.Has) method introduced with [Go 1.17](https://go.dev/doc/go1.17)'s `net/url`.

**To Reproduce**
Try to build VictoriaMetrics 1.70 or 1.71 with Go 1.16.

**Expected behavior**
Successful build with the documented version of Go. References mentioning the minimum requirement of Go should be updated.

**Logs**
```
$ go version
go version go1.16.12 linux/amd64

$ make vmutils
[...]
make[1]: Entering directory `/home/vagrant/VictoriaMetrics-1.71.0'
CGO_ENABLED=1 GO111MODULE=on go build  -mod=vendor -ldflags "-X 'github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=vmalert-20211221-103124--dirty-da39a3ee'" -o bin/vmalert github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert
# github.com/VictoriaMetrics/VictoriaMetrics/app/vmalert/datasource
app/vmalert/datasource/vm_graphite_api.go:58:7: q.Has undefined (type url.Values has no field or method Has)
app/vmalert/datasource/vm_prom_api.go:154:7: q.Has undefined (type url.Values has no field or method Has)
make[1]: *** [app-local] Error 2
make[1]: Leaving directory `/home/vagrant/VictoriaMetrics-1.71.0'
make: *** [vmalert] Error 2
```

**Version**
VictoriaMetrics 1.70 and 1.71

**Comment by valyala** [comment]
This has been fixed in commits 9e17b51d4573c8351cb16ae936a0187a17380601 and f0c331c72477267708ff083c353737f67721bd81 .

Closing the issue as fixed.
