### ISSUE TITLE
grafana dashbord for victoriametrics cluster deprecated panel (grafana 8.3.3 and newer)

### ISSUE THREAD

**Issue by alex-vaisman** [VictoriaMetrics/VictoriaMetrics#1992]
Due deprecated panel in grafana 8.3.3 dashboard uptime no more showed (as pict 1)

I fixed it, it works like in picture 2, in the attachment, take it.
![photo_2021-12-21_20-00-30](https://user-images.githubusercontent.com/62017633/146969918-dfd50f02-2872-4c85-99e0-2f95247d97f3.jpg)
![photo_2021-12-21_20-00-43](https://user-images.githubusercontent.com/62017633/146969925-6f36fe22-1b89-4049-a820-0e12acafb42d.jpg)
[victoriametrics-cluster.json.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7756915/victoriametrics-cluster.json.zip)

**Comment by hagen1778** [comment]
Hi @alex-vaisman! Thanks for your request. It has been addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1993
Feel free to reopen if issue still persists.
