### ISSUE TITLE
vmui draws strange charts with more than 9h duration 

### ISSUE THREAD

**Issue by lstday** [VictoriaMetrics/VictoriaMetrics#2004]
**Description**
v.1.71 in docker, single. I see right angles in vmui in some cases, soidh:

**Screenshots**

Without more operator 2d:
![image](https://user-images.githubusercontent.com/7997100/147332892-7bd39792-8deb-41d8-8026-708110ddf28c.png)

With the operator 2d:
![image](https://user-images.githubusercontent.com/7997100/147332918-fb5f96fc-6010-4ce7-b06e-803f6cbba5e6.png)

Without the operator 9h:
![image](https://user-images.githubusercontent.com/7997100/147334513-beee98a4-edf4-4b24-a60c-bef93b3625dc.png)

Without the operator 10h:
![image](https://user-images.githubusercontent.com/7997100/147334575-5ba4c6ed-29f5-4a22-a37d-542a53ef8524.png)

**Version**

```
$ docker exec -it victoriametrics sh -c './victoria-metrics-prod --version'
victoria-metrics-20211220-172816-tags-v1.71.0-0-g4701c108f
```

**Used command-line flags**
```
-promscrape.config=/etc/victoriametrics/prometheus.yml -loggerTimezone=Europe/Moscow -search.maxUniqueTimeseries=4000000 -dedup.minScrapeInterval=30s -search.maxQueryDuration=60s -selfScrapeInterval=10s -retentionPeriod=90d
```

More:
In v1.70 there was also a bug, but it looked different: without the more operator it was displayed correctly, but with the more operator there was no break on the line chart, and the chart line was connected.
1.70, with the operator, 2d:
![2](https://user-images.githubusercontent.com/7997100/147334046-e0c5e034-9f48-42bb-b9f3-9ad550a7821b.jpg)
1.70, without the operator, 2d:
![1](https://user-images.githubusercontent.com/7997100/147334048-71974f53-ba17-4c1b-9927-060f336ca2c4.jpg)

**Comment by lstday** [comment]
> @lstday , could you check whether this issue exists in [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

1.73.0, don't you mind? Can't find any single chart with a weird shape, all looks legit. But a query without filters cuts off Y-axis, is it ok?
![image](https://user-images.githubusercontent.com/7997100/154025895-1593ef25-a394-4651-a1a3-a5471e257779.png)
![image](https://user-images.githubusercontent.com/7997100/154025983-dac0135e-f2af-48e4-818a-9419e439d740.png)

**Comment by valyala** [comment]
It looks like the graphs above are obtained from vmui v1.72.0, since vmui v1.73.0 should have different format for `y` axis numbers on the left side of the graph. @lstday , could you try v1.73.0 then and verify whether the issue is still present there?

**Comment by lstday** [comment]
Sorry, playbook worked wrong way, now it is 1.73.0:
![image](https://user-images.githubusercontent.com/7997100/154260644-ac46c5f2-7032-41c6-8833-62dd3303666b.png)
![image](https://user-images.githubusercontent.com/7997100/154260733-38eefced-a24e-4dc8-b952-077e4d848133.png)

**Comment by hagen1778** [comment]
Hi @lstday! This behaviour looks correct with assumption that `rabbitmq_queue_messages_ready` was `<1` and suddenly spiked to `>1` values. According to your query `rabbitmq_queue_messages_ready > 1` only metrics with `values>1` should be displayed. So if the metric had values like `0, 0, 0, 25000, 30000, 15000, 0, 0, 0, 0` - it will be displayed like on the screenshot.

**Comment by valyala** [comment]
Closing this issue because of long inactivity. @lstday , could you verify whether the issue still persists in [the latest VictiriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest)? If the issue is still there, feel free re-opening this issue or creating new one with the link to this issue.
