### ISSUE TITLE
Indicators lost after restart vmagent

### ISSUE THREAD

**Issue by mmkkoo** [VictoriaMetrics/VictoriaMetrics#2013]
Describe the bug
we are the cluster version for 1.67 with  three nodes，when we upgraded the version to 1.71，i found，whenever i restart vmagent，the indicator is missing，but recover immediately，this led to an alarm in our production
for example
![image](https://user-images.githubusercontent.com/42405491/147445784-67918a49-3b6c-4974-9182-d8a50456ef5e.png)
vmagent start command
![image](https://user-images.githubusercontent.com/42405491/147445871-514d5247-351d-4695-b896-5af5a4e748d6.png)

so we  do a fallback version to 1.68，the problem still exists
![image](https://user-images.githubusercontent.com/42405491/147446075-e6bc4070-a30a-439e-9fc8-b812ed7f4dce.png)
but when we fallback version to 1.67，the problem disappeared
wo why？

**Comment by mmkkoo** [comment]
add
when we Upgrade version，vm_promscrape_targets appear decline，but fallback version to 1.67，vm_promscrape_targets same as before
![image](https://user-images.githubusercontent.com/42405491/147449065-9e2faf0a-4a51-4307-9558-3ffd34919da0.png)

**Comment by YuriKravetc** [comment]
Hi,
Can you attach the Troubleshooting graphs for periods during a restart?
Any errors in the log after restart?

**Comment by mmkkoo** [comment]
i can see some errors from the log：
goroutine 70943 [IO wait]:
internal/poll.runtime_pollWait(0x7f9c79b36fc0, 0x72)
        runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000af6580, 0xc00179c000, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000af6580, {0xc00179c000, 0x1000, 0x1000})
        internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000af6580, {0xc00179c000, 0xc014e5cb40, 0xc013864f68})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00080a4e0, {0xc00179c000, 0xc014e59a00, 0x4})
        net/net.go:183 +0x45
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape.(*statConn).Read(0x0, {0xc00179c000, 0x0, 0x0})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/statconn.go:89 +0x27
net/http.(*persistConn).Read(0xc0008639e0, {0xc00179c000, 0xc014dba420, 0xc013864d30})
        net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc00c814c00)
        bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc00c814c00, 0x1)
        bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc0008639e0)
        net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
        net/http/transport.go:1747 +0x1e05

goroutine 441162 [semacquire]:
sync.runtime_SemacquireMutex(0x4022000000000000, 0x0, 0xc002df6eaa)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000182300)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*pendingSeries).Push(0xc000182300, {0xc1098b6000, 0x413, 0x555})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/pendingseries.go:55 +0x50
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*remoteWriteCtx).Push(0x2, {0xc1098b6000, 0x0, 0xc002df70a7})
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:506 +0x265
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.pushBlockToRemoteStorages.func1(0xc002df7111)
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:328 +0x65
created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.pushBlockToRemoteStorages
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:326 +0x69
any way，i also concerned about when i restart vmagent，the flag information is too little
![image](https://user-images.githubusercontent.com/42405491/147518346-df615e0c-ec38-4281-9db7-ae5819f718f7.png)

**Comment by YuriKravetc** [comment]
Can you provide the screenshot with Troubleshooting graphs, please?
And in regards to Flags, are you expecting more and only seeing a part of them?

**Comment by mmkkoo** [comment]
so i have two clusters available，azone and bzone，the cluster version for azone is 1.67，the cluster version for bzone is 1.68，when i restart vmagent at the same time，obviously easy to see，the bzone is error，the result for azone is still 3
![image](https://user-images.githubusercontent.com/42405491/147637503-0f97b7df-d9a4-47d7-99ee-2ffd321405aa.png)

**Comment by jiangxinlingdu** [comment]
me too

**Comment by f41gh7** [comment]
It could be an issue with 'stalenessMarkers', which was added to the streamParse mode at 1.68 release. Try to disable it with flag value for vmagent: `-promscrape.noStaleMarkers=true`.

 related doc https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers

**Comment by mmkkoo** [comment]
Thks，when i set the parameter to:-promscrape.noStaleMarkers=true
The problem was fixed!

**Comment by valyala** [comment]
More context - `vmagent` sends staleness markers to `-remoteWrite.url` for all the recently scraped metrics during graceful shutdown. This may lead to issues described above. It looks like Prometheus doesn't send stale markers on graceful shutdown, so it would be great following its behavior in `vmagent` as well.

**Comment by valyala** [comment]
vmagent shouldn't send staleness markers to the configured remote storage systems starting from the commit e4e36383e20f00d43d1bf8d96d7b2e31e2d79c8c . It will be included in the next release.

**Comment by valyala** [comment]
FYI, `vmagent` stops sending staleness markers on graceful shutdown starting from [v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
