### ISSUE TITLE
vmagent: add the ability to locate remote-write buffers in memory instead of disk

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#2018]
In normal mode vmagent is a stateless app, and not using disk. And it would be logical to deploy it to cloud compute instance with a small size and low speed disk.
But in case of inability to send remote-write data to vminsert, it starts buffering data on disk. And in this case, the disk speed begins to matter: disk speeds may not be sufficient for buffering to work correctly.

We bypassed this issue by mounting tmpfs and placing vmagent's tmpDataPath folder in it. But would be great to avoid this workaround by implementing some in-memory cache, instead of using cache on disk.

**Comment by valyala** [comment]
This feature has been implemented via `-remoteWrite.disableOnDiskQueue` command-line flag in [vmagent](https://docs.victoriametrics.com/vmagent.html) [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html) as a part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2110 . See [these docs](https://docs.victoriametrics.com/vmagent/#disabling-on-disk-persistence) for details.

Closing the feature request as done.
