### ISSUE TITLE
vmstorage supports read/write separation

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#2031]
**Is your feature request related to a problem? Please describe.**

I want to expand the query QPS cap of vmcluster horizontally to support more alarm queries.

Currently, vmselect queries are broadcast to all vmstorage nodes, and I cannot raise the query QPS cap by increasing the number of vmstorages. Currently I can only solve the query scalability problem by deploying multiple sets of vmcluster.

I am using cloud disk to deploy vmstorage and different machines can mount the same disk, so I want to split the role of vmstorage.
For example, I can have three machines mount the same cloud drive and have one of the vmsorage be responsible for writing data and the other two vmsorage be responsible for reading and responding to query requests from vmselect. When I want to raise the query QPS cap, I can continue to add the number of read-only vmsorage.

**Describe the solution you'd like**
Add vmstorage argument to support switching read-only, write-only, and read-writable modes.

**Additional context**
This solution is actually shared disk architecture, not sure if you guys only like shared nothing architecture.

**Comment by hagen1778** [comment]
Hi @faceair! What is the exact QPS cap you're reaching? Have you seen the read-only mode https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#readonly-mode ?
Or maybe two-layer topology could help in your case?

**Comment by faceair** [comment]
We currently have about 500 QPS of recording rule queries, and these recording rules are putting a lot of pressure on the cluster, which is already over 60% loaded.

The first is that we will continue to add recording rules (currently about 2000), and the second is that the cluster's metrics will grow many times over.

We want to relieve CPU pressure by splitting recording rule queries to multiple read-only clusters. Otherwise we would have to write an extra copy of the data to another cluster, which could be avoided if we were using cloud drives.

I'm not sure if two-layer topology can help us solve this kind of problem.

**Comment by valyala** [comment]
@faceair , did you try just increasing the number of `vmstorage` nodes in the cluster? For example, if you increase the number of `vmstorage` nodes in the cluster by 2 times, then every `vmstorage` node will eventually have 2x less active time series compared to the previous setup. This means that every query to `vmstorage` will consume 2x less CPU time (e.g. it will be performed 2 times faster), since it needs to scan and select 2x less time series on average. This also means 2x lower RAM usage per each `vmstorage` node. The end result is ~2x higher query capacity in the cluster, so it could handle 2x more queries per second.

**Comment by faceair** [comment]
Thanks @valyala  for such a detailed explanation.

When the per-query overhead is high, it is useful to add vmstorage nodes directly. Only when the per-query overhead is very small and the query QPS is very, very high, do you need the read-write separation solution I mentioned above.

This solution is not particularly useful, and there are not many such scenarios, so I'm closing this proposal.
