### ISSUE TITLE
Data inconsistency after calculation by promql

### ISSUE THREAD

**Issue by ethanliuu** [VictoriaMetrics/VictoriaMetrics#2056]
**Describe the bug**
The data calculated by vmselect is inconsistent with the data calculated on the source data prometheus

**To Reproduce**
Calculate and display the consumption speed of Kafka on grafana, select different source databases, and the calculated data will be different.
```
sum(delta(kafka_consumergroup_current_offset{topic=~"$topic",consumergroup=~"$consumergroup"}[5m])/5) by (consumergroup, topic)
```
**Expected behavior**

**Screenshots**

The picture above is the data source of prometheus, and the picture below is the data source of VictoriaMetrics. The promql is consistent and the time range is the same, but the calculated results are somewhat different. It seems that the data calculated on the VM is a little delayed?
![image](https://user-images.githubusercontent.com/64894334/148937311-85c4aec2-ef73-4375-a703-12618785c0bf.png)

You can see that the value of the start timestamp of the two data sources is the same as the value of the end timestamp
Below are the timestamps and values of the prometheus data source
![image](https://user-images.githubusercontent.com/64894334/148941036-1b37b897-2a62-4ce4-8699-410539a9d7b8.png)
![image](https://user-images.githubusercontent.com/64894334/148941117-b09ec6ff-c2d9-49f0-bd78-0048294c416f.png)

Below are the timestamps and values of the VM data source
![image](https://user-images.githubusercontent.com/64894334/148940885-3a36a4a8-e02f-4678-835d-3fafa0bd1ff1.png)
![image](https://user-images.githubusercontent.com/64894334/148941146-889fcf3d-c2c9-4556-80e3-9f7cd527da30.png)

But the values calculated by promql are not the same, there is a little differenc.
The picture above is the request of prometheus, and the picture below is the request of the VM.
![image](https://user-images.githubusercontent.com/64894334/148941718-0d603765-1ee5-4ca3-b01b-9968b53888b3.png)
![image](https://user-images.githubusercontent.com/64894334/148941799-52b5cfa0-534d-4102-becf-19b890c40f9d.png)

What is causing this problem? Can someone help take a look?

**Version**
The victoriaMetrics cluster installed using helm, the images is 
```
victoriametrics/vmstorage:v1.71.0-cluster
victoriametrics/vmselect:v1.71.0-cluster
```

prometheus version：
```
prom/prometheus:v2.25.0
```

**Comment by valyala** [comment]
It is likely the discrepancy between VictoriaMetrics and Prometheus results is related to the difference in `delta(m[d])` function handling in these systems. VictoriaMetrics takes into account the difference between the first sample on the selected lookbehind window `[d]` and the previous sample before this window. Prometheus silently skips this difference. Additionally, Prometheus may extrapolate `delta()` results in some cases, which will result in fractional values for integer counters. See more details about this [here](https://github.com/prometheus/prometheus/issues/3746).

Let's calculate `delta(m[20s])` at timestamp 35 on the following time series using Prometheus and VictoriaMetrics logic:

```
t  10 20 30 40
v  1  2  3  4
           ^
           t=35
```
* Prometheus selects samples on the time range `(35-20 ... 35]` -> `(15 ... 35]` - this are `[2 3]` in the case above - and then calculates the difference between the last and the first sample on the selected time range: `3-2=1`. So Prometheus returns 1 for `delta(m[20s]) @ 35`.
* VictoriaMetrics selects the same samples on the same time range - e.g. `[2 3]` - but it takes into account the previous sample before the selected time range, e.g. it takes `1` as a previous sample. Then it calculates the difference between the last sample in the selected time range and the previous sample before the selected time range: `3-1=2`. So VictoriaMetrics returns 2 for `delta(m[20s]) @ 35`.

As you can see, Prometheus loses the difference between 2 and 1 here. This difference may be crucial when calculating `delta()` at steps equal to the lookbehind window (e.g. when using `delta(m[$__interval])` in Grafana. Then the sum of the returned samples won't be equal to `delta(m[$__range])`, e.g. when the lookbehind window equals the selected time range for the graph.

**Comment by valyala** [comment]
I'd also recommend reading [MetricsQL docs](https://docs.victoriametrics.com/MetricsQL.html) and [troubleshooting guide](https://docs.victoriametrics.com/troubleshooting/index.html#unexpected-query-results).

Closing the issue as answered.
