### ISSUE TITLE
need a -origin="local dir" flag of vmrestore, thanks

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2057]
I want a historical vm-storage node for yesterday data.
so I use vmrestore every midnight to load yesterday data from s3.
But the -1 day and the -2 day have many same data files.
If vmrestore add a flag like `-origin="local dir"`, it will speed up for download data.
thanks.

**Comment by valyala** [comment]
[vmrestore](https://docs.victoriametrics.com/vmrestore.html) skips re-downloading files from `-src` if they already exist at `-storageDataPath` directory. This feature can be used for your use case - just copy local files from the directory with data for `-2 day` to the directory with data for `-1 day` and then run `vmrestore` with `-storageDataPath=<-1 day>`. In this case `vmrestore` should copy only new files from `-src` and remove local files, which were removed at `-src`. The copying of local files can be skipped if running `vmrestore` on the same `-storageDataPath` every day.

Note that there was an issue in `vmrestore` prior v1.70.0, which could result in re-downloading of already existing from `-src` to `-storageDataPath` - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/487) for details.

**Comment by valyala** [comment]
We aren't going to add `-origin` command-line flag to [vmrestore](https://docs.victoriametrics.com/vmrestore.html) because the solution described above helps avoiding slow copying of the most of backup files from the remote storage.

Closing this feature request as won't implement.
