### ISSUE TITLE
Does not support writing custom APIs ?	

### ISSUE THREAD

**Issue by GubMid** [VictoriaMetrics/VictoriaMetrics#2059]
Vmalert is remoteWrite to my own API, and the data is null ？

./bin/vmalert -rule=alert.rules \            
    -datasource.url=http://localhost:8428 \  
    -notifier.url=http://localhost:9093 \  
	-remoteWrite.url=http://localhost:5000
	
	
APi response -->
null
	
	
Does not support writing custom APIs ?

**Comment by GubMid** [comment]
My API interface is  http://localhost:5000/alter/api/v1/write，Data is null

**Comment by denisgolius** [comment]
Hi @GubMid !
What do you see in vmalert logs? 
note that vmalert can write data to any remote-write destination

**Comment by GubMid** [comment]
> 嗨@GubMid！ 您在 vmalert 日志中看到了什么？ 请注意，vmalert 可以将数据写入任何远程写入目标

There are no errors in the log

**Comment by denisgolius** [comment]
> > 嗨@GubMid！ 您在 vmalert 日志中看到了什么？ 请注意，vmalert 可以将数据写入任何远程写入目标
> 
> There are no errors in the log

So looks like your custom api can't process data from vmalert. What is the software you running on 5000 port?

**Comment by GubMid** [comment]
> > > 嗨@GubMid！ 您在 vmalert 日志中看到了什么？ 请注意，vmalert 可以将数据写入任何远程写入目标
> > 
> > 
> > There are no errors in the log
> 
> So looks like your custom api can't process data from vmalert. What is the software you running on 5000 port?

Python flash
![Uploading lQLPDhsMgxjjpfnMns0B67AupuUAqohDbQHlLEtXgEIA_491_158.png…]()
![Uploading lQLPDhsMgzh6zuJVzQK3sJd6X0Auo4KxAeUsf1MA0AA_695_85.png…]()

**Comment by GubMid** [comment]
> > > 嗨@GubMid！ 您在 vmalert 日志中看到了什么？ 请注意，vmalert 可以将数据写入任何远程写入目标
> > 
> > 
> > There are no errors in the log
> 
> So looks like your custom api can't process data from vmalert. What is the software you running on 5000 port?

Python flask 
![lQLPDhsMgxjjpfnMns0B67AupuUAqohDbQHlLEtXgEIA_491_158](https://user-images.githubusercontent.com/74485252/149139259-b22e34be-281f-4013-b185-42b8f511de9c.png)
![lQLPDhsMgzh6zuJVzQK3sJd6X0Auo4KxAeUsf1MA0AA_695_85](https://user-images.githubusercontent.com/74485252/149139278-9170e6fa-7ed8-4a31-af23-59fea952ce55.png)

**Comment by GubMid** [comment]
Isn't the returned data JSON？

**Comment by denisgolius** [comment]
> Isn't the returned data JSON？

No, it's not in JSON format. The data is written by remote write protocol  and use [protobuf](https://github.com/golang/protobuf) which is encoded in snappy - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/victoria-metrics/test/prom_writter.go .

**Comment by GubMid** [comment]
> > 返回的数据不是json吗？
> 
> 不，它不是 JSON 格式。数据由远程写入协议写入并使用以[snappy](https://github.com/golang/protobuf)编码的[protobuf](https://github.com/golang/protobuf) - 请参阅https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/victoria-metrics/test/prom_writter.go。

Thank you. This is the best help！

**Comment by GubMid** [comment]
@denisgolius 

Thank you. This is the best help！

Has Victoriametrics considered exporting JSON?

**Comment by denisgolius** [comment]
> @denisgolius
> 
> Thank you. This is the best help！
> 
> Has Victoriametrics considered exporting JSON?
> Isn't the returned data JSON？

See this https://github.com/prometheus/prometheus/blob/main/prompb/remote.proto

**Comment by denisgolius** [comment]
> @denisgolius
> 
> Thank you. This is the best help！
> 
> Has Victoriametrics considered exporting JSON?

You can export metrics from VictoriaMetrics in JSON - see https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-export-data-in-json-line-format

**Comment by hagen1778** [comment]
Closed due to lack of activity.
