### ISSUE TITLE
Strange behavior VictoriaMetrics with promxy

### ISSUE THREAD

**Issue by rumanzo** [VictoriaMetrics/VictoriaMetrics#208]
**Describe the bug**
A long time we  had a stack of promxy + prometneus + VictoriaMetrics. Today I update versions to latest (victoriametrics 1.24.0 -> 1.28.0-1, promxy 0.0.46 -> 0.0.53). 
The graphs in the grafana, the source for which the promxy defined, still work, but if I go directly to the promxy web interface, select metrics and execute query, it gives an empty result for any request. Moreover, if I switch the targets in promxy from VictoriaMetrics to Prometheus - everything is ok.

**To Reproduce**
Setup latest promxy, prometheus and VictoriaMetrics

**Expected behavior**
Before update query in promxy works correct

**Version**
```
# victoriametrics --version
victoria-metrics-20191009-135323-tags-v1.28.0-0-gf6334bffs-20190730-121249-heads-single-node-0-g671d9e55
```

**Comment by valyala** [comment]
- Try querying `promxy` at various zoom levels (1h, 24h, 7d, etc.) and see whether graphs are still missing.
- Try removing `<-storageDataPath>/cache` directory, where `<-storageDataPath>` is the corresponding command line flag value for `victoriametrics`, and verify whether Grafana dashboards work. This will rule out VictoriaMetrics caching.

cc'ing @jacksontj , since it looks like an issue on `promxy` side.

**Comment by rumanzo** [comment]
> * Try querying `promxy` at various zoom levels (1h, 24h, 7d, etc.) and see whether graphs are still missing.
No datapoints found. 

> * Try removing `<-storageDataPath>/cache` directory, where `<-storageDataPath>` is the corresponding command line flag value for `victoriametrics`, and verify whether Grafana dashboards work. This will rule out VictoriaMetrics caching.
not used

> cc'ing @jacksontj , since it looks like an issue on `promxy` side.
Loks like that, on dev I update VirtoriaMetrics first, all ok, update promxy to latest version, and get this behavior.
But with prometheus (not VictoriaMetrics) target works right. Still there is some difference between prometeus and VictoriaMetrics

**Comment by rumanzo** [comment]
Problem still there. And i can't use new promxy release, and I don't think thats it promxy problem because promxy work fine with prometeheus.
@jacksontj does it make sense for me to create a issue in your repository ?

**Comment by tenmozes** [comment]
@rumanzo sorry for a long delay we will take a look

**Comment by tenmozes** [comment]
@valyala could please take a look?

**Comment by valyala** [comment]
This can be related to https://github.com/jacksontj/promxy/issues/202 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/171 . Try adding `nocache: 1` query arg to Promxy config as defined at https://github.com/jacksontj/promxy/blob/ea447b64275827e3aada8b5f32877e11ac1c6e75/cmd/promxy/config.yaml#L50 .

**Comment by rumanzo** [comment]
> This can be related to [jacksontj/promxy#202](https://github.com/jacksontj/promxy/issues/202) and #171 . Try adding `nocache: 1` query arg to Promxy config as defined at https://github.com/jacksontj/promxy/blob/ea447b64275827e3aada8b5f32877e11ac1c6e75/cmd/promxy/config.yaml#L50 .
It works! I did not think of looking at the subject of changes in the promxy config, sorry. Thank you!

**Comment by valyala** [comment]
Great! Closing the issue as duplicate for #171 .
