### ISSUE TITLE
VMUI graph/json/table doesn't show data correctly.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#2084]
**Describe the bug**

  open VMUI https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?g0.range_input=15m&g0.end_input=2022-01-19T09%3A37%3A14&g0.step_input=1&g0.tab=chart&g0.expr=100%20*%20sum(rate(process_cpu_seconds_total))%20by%20(job)

   Click on json/table - it shows no data. Refresh page with selected json/table - data appears, but graph shows no data.

![out](https://user-images.githubusercontent.com/18450869/150314551-672be354-64bc-4b95-a3b0-a5fd71074ae2.gif)

**Comment by k8sre** [comment]
I have the same problem
Victoria Metrics version 1.72.0

**Comment by valyala** [comment]
The bugfix has been included in [VictoriaMetrics v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
