### ISSUE TITLE
how to decrease data points count in existing time series?

### ISSUE THREAD

**Issue by mykolashama** [VictoriaMetrics/VictoriaMetrics#2086]
Hello! Is there a possibility to decrease the data points count in the existing time series? 
For example, we have historical data for 6 months with a frequency of 1m, but we want to decrease (delete) the data point count for the first 3 months with a frequency of 5m.

**Comment by YuriKravetc** [comment]
Hi,

You can refer to:
 https://docs.victoriametrics.com/#downsampling

**Comment by valyala** [comment]
The issue has been answered at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2086#issuecomment-1018304282 , so closing it.
