### ISSUE TITLE
Failing to scrape jmx_metrics data

### ISSUE THREAD

**Issue by yuvraj2987** [VictoriaMetrics/VictoriaMetrics#2098]
**Describe the bug**
vmagent is not able to scrape any of jmx metrics. There is no networking issue. I am able get the metrics on vmagent containers using curl command. However logs always shows timeout or EOF error. 

jmx_export config is as follows:
```

- job_name: "jmx_exporter"
  scrape_interval: 60s
  scrape_timeout: 30s
  gce_sd_configs:
    - project: "xxxx"
      zone: xxxx
      port: 9404
    - project: "xxxx"
      zone: xxxx
      port: 9404
```

**To Reproduce**
NA

**Expected behavior**
vmagent should be able to scrape jmx metrics successfully.

**Logs**
Getting following errors while scraping jmx metrics.

```
state=down, endpoint=http://xx.xx.x.xxx::9404/metrics, labels={cluster="paas",environment="xxx",instance="xxx",instance_ip="xx.xx.x.xxx",instance_project="xxxx",instance_tags=",env-xxx,kafka",job="jmx_exporter"} , last_scrape=29.208s ago, scrape_duration=7.226s, error="cannot read data: cannot scrape \"http://xx.xx.x.xxx::9404/metrics\": Get \"http://xx.xx.x.xxx:9404/metrics\": EOF"
        state=down, endpoint=http://xx.xx.x.xxx:9404/metrics, labels={cluster="paas",environment="xxx",instance="xxx",instance_ip="xx.xx.x.xxx",instance_tags="env-xxx,kafka",job="jmx_exporter"} , last_scrape=53.698s ago, scrape_duration=1.136s, error="cannot read data: cannot scrape \"http://xx.xx.x.xxx:9404/metrics\": Get \"http://xx.xx.x.xxx:9404/metrics\": EOF"
```
This is after enabling `-promscrape.streamParse=true`. Before that all jmx export jobs were timing out.

I tried running curl command from vmagent instances. It returns success. So there is no networking issue.

```
curl -I http://xx.xx.x.xxx:9404/metrics
HTTP/1.1 200 OK
date: Tue, 25 Jan 2022 00:43:39 GMT
content-type: text/plain; version=0.0.4; charset=utf-8
content-length: 3661507
````

**Screenshots**
Vmagent Cluster Status
![image](https://user-images.githubusercontent.com/4722567/150889872-29f802e0-e8cf-4b9a-938c-112cc7f33990.png)
![image](https://user-images.githubusercontent.com/4722567/150890003-c4b3a77d-2d14-4aa7-8534-8f25f3d1830f.png)

Scrapping Related Metrics
![image](https://user-images.githubusercontent.com/4722567/150890049-6a264230-07cf-44ed-a6aa-615c1d280ec4.png)

I am not worried too many dropped metrics, because it tries to pattern match for target and filters are not set properly.
So there are many invalid hosts which are invalid targets.

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
vmagent --version
vmagent-20210203-211447-tags-v1.53.1-0-g19986da16
```

**Used command-line flags**

```
-httpListenAddr=:8000 -remoteWrite.tmpDataPath=/data/vmagent -promscrape.config=/config/vmagent.yml -promscrape.streamParse=true -promscrape.suppressScrapeErrors=false -maxConcurrentInserts=16 -insert.maxQueueDuration=1m -remoteWrite.url=https://internal-dns0/insert/0/prometheus -remoteWrite.url=https://internal-dns1/insert/0/prometheus
```

**Comment by f41gh7** [comment]
Hello, can you measure time for command: `time curl -I http://xx.xx.x.xxx:9404/metrics`, probably, jmx_exporter generates data slowly and ~3MB metrics response is quite big.

**Comment by yuvraj2987** [comment]
Hi @f41gh7,
I tested that earlier. It's always < 10s and my timeout is setup for 30s. I even went to extreme value of 10m without any success.
```
real    0m8.390s
user    0m0.004s
sys     0m0.035s
```

**Comment by yuvraj2987** [comment]
I want to note that I upgraded the vmagent to latest release. Still seeing the same behavior.
```
vmagent --version
vmagent-20220118-213237-tags-v1.72.0-0-gd79a91558
```

**Comment by yuvraj2987** [comment]
Figured out the issue. Last month we added linkerd2 as default sidecar to all our apps. That meant it got added for vmagent as well. This was not the intention. It make somewhat sense now. Since all outgoing IP addresses were going out to linkerd. linkerd wasn't able to find defined IP addresses since they were outside the cluster failing the request.

Thank you everyone for taking a look.
