### ISSUE TITLE
Create official Grafana dashboard for single-node VictoriaMetrics

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#21]
### The issue

[Single-node VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics) exposes various internal metrics in Prometheus format on `/metrics` page. But it is unclear which metrics are important and which metrics may be ignored.

### The solution

To create official Grafana dashboard for single-node VictoriaMetrics. The dashboard must contain essential information about VictoriaMetrics instance.

**Comment by valyala** [comment]
The following dashboard may be used as a basis - https://grafana.com/dashboards/9981 .

**Comment by hagen1778** [comment]
https://grafana.com/dashboards/10229
