### ISSUE TITLE
Solution for the slow query is proper

### ISSUE THREAD

**Issue by chengjianyun** [VictoriaMetrics/VictoriaMetrics#2104]
## Context

We're facing a problem that aggregate query for large timeseries takes too much time. Our data model like this:

```
"metric": {
	"__name__": "disk__used_percent",
	"disk__device": "udev",
	"disk__fstype": "devtmpfs",
	"disk__path": "/dev",
	"instance": "r021",
	"collecter_id": "-1",
	"group": "default",
	"idc": "idc-1",
	"key": "888888",
	"space_id": "0000000"
}
```

We want to show the average disk usage percent for the whole cluster group by `idc` or overall. Then our query would like this: 
```
http://<selecthost>:8481/select/0/prometheus/api/v1/query_range?end=1642550400&query=avg(disk__used_percent{space_id=~"0000000",idc=~"(sdc-1|sdc-2|sdc-3|sdc-4|sdc-5|sdc-6|sdc-7|sdc-8|sdc-9)",group=~"default"})&start=1641945600&step=14400
```

It turns out that the query is very slow (more than one minute). That because we have too many timeseries keys to aggregate instead of too many data points. 

According to instant query as below, each aggregate needs scan more than 127k timeseries keys. 

`http://<select_host>:8481/select/0/prometheus/api/v1/query?query=disk__used_percent{space_id=~"0000000",idc=~"(sdc-1|sdc-2|sdc-3|sdc-4|sdc-5|sdc-6|sdc-7|sdc-8|sdc-9)",group=~"default"}&time=1642520140` 

## Solution

We'd like to reduce the dimensions of  `disk__used_percent`  by some pre-calculation and save the result as a new metric like `disk__used_percent_by_idc`. Then the top-level query could run the query on the new generated. 

We plan to achieve this by query-then-write in VictoriaMetrics. A draft procedure would like this:

1. Schedule an eg. one minute regular task to aggregate the past minute data for the metric `disk__used_percent`
2. Write the result to VictoriaMetrics with new metric name `disk__used_percent_by_idc`

## Question
My question is, 
1. VictoriaMetrics can support the solution well? Such as would it lost/duplicate data in the solution. 
2. If there're too many such queries, the burden is on storage nodes or select nodes.
3. Anything else I have missed.
4. Any other solutions?

**Comment by f41gh7** [comment]
Hello, VictoriaMetrics supports data aggregation via `vmalert`'s recording rule feature.  You can setup recording rule with your query - it will be executed via /api/v1/query API and recorded into cluster. https://docs.victoriametrics.com/vmalert.html#features

  Historical data can be backfilled via rules replay feature https://docs.victoriametrics.com/vmalert.html#rules-backfilling

**Comment by chengjianyun** [comment]
@f41gh7 thanks for your suggestion. I will have a try.

**Comment by valyala** [comment]
The issue seems to be answered at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2104#issuecomment-1022120476 , so closing it.

@chengjianyun , feel free re-opening the issue or creating new one (and linking to this one) if you have the related questions / issues.
