### ISSUE TITLE
vmagent CPU saturation

### ISSUE THREAD

**Issue by tumd** [VictoriaMetrics/VictoriaMetrics#2107]
We are using the graphite-tcp endpoint to ingest stats from our application via two replicas of vmagent setup using the victoria-metrics-k8s-stack. We use a remoteWrite.relabelConfig with configuration similar to [this](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/368#issuecomment-598949394).

After deploying some (quite a lot, actually) of new metrics from the application, we started to notice some metrics sent by our application where missing in VM.

After some investigation we noticed that the CPU graph on vmagent were hitting the roof.
![Screenshot 2022-01-26 at 11 29 16](https://user-images.githubusercontent.com/463066/151147270-07d54a18-2019-404b-9261-5038613efb85.png)

This is caused by the k8s-operator setting a hard `resources.limits.cpu` to `200m` by default.
```
resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 200Mi
```
After setting the `resources.requests` in our values, the `resources.limits` where removed, and the immediate issue was resolved.

There is a couple of things I would love suggestion to or ideally solved upstream;

1. Is the `resources.limits` defaults in k8s-operator reasonable?
2. No graphs in the official dashboards (apart from CPU) nor the upstream alerts where showing signs of any issues, even though vmagent where clearly saturated on CPU and couldn't keeping up with the ingestion rate - and metrics went missing.
I think some metrics regarding the ingestion performance on the VM components would be great, together with dashboard panels & alerts.
3. I would love to see some upstream alerts on high cpu-usage saturation on the VM components.

Thank you for a lovely product!

**Comment by f41gh7** [comment]
Hello, 
1.  It's not reasonable, it must be adjusted to the needed payload.  Probably it can be removed, but it this case, vmagent will try to use all available cores at host system and may affect neighbor applications.

2. Good point, it could be improved with grafana panel and default alerts @hagen1778  can you take a look?

**Comment by tumd** [comment]
Great!
I would say that fixing 2. probably would make 1. a non-issue.

**Comment by valyala** [comment]
Commits ead66155efe17e13260ce65021e993ceee5bf334 and f50cf605346227cdd4fb80b3eb25d043b5b7f60f add `process_cpu_cores_available` metric to all the VictoriaMetrics apps. These commits will be included in the next release of VictoriaMetrics. The `process_cpu_cores_available` metric can be used for alerting on CPU saturation. For example, the following query alerts when the app uses more than 90% of CPU during the last 5 minutes:

```promql
rate(process_cpu_seconds_total[5m]) / process_cpu_cores_available > 0.9
```

@tumd , could you check whether the following vmagent image - `docker.io/victoriametrics/vmagent:heads-public-single-node-0-gf50cf6053` - exposes the correct value according to the configured cgo limit for `process_cpu_cores_available` at `http://vmagent:8429/metrics` page? You can build the image or binary on yourself from the commit f50cf605346227cdd4fb80b3eb25d043b5b7f60f by following [these instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by jelmd** [comment]
IMHO vmagent & firends (i.e. go apps) should not mutate to an OS monitoring system. KISS. IMHO one should leave such monitoring tasks to node_exporter and the like.

OT: There are probably a lot more things about vmagent (to make it less resource hogging thing, etc.), but github discussions is probably a better places than cluttering `Issues` ...

**Comment by valyala** [comment]
The `process_cpu_cores_available` metric is exposed by all the VictoriaMetrics components starting from [v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

@hagen1778 , could you add `rate(process_cpu_seconds_total[5m]) / process_cpu_cores_available > 0.9` to [default alerting rules for VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml)? Also it would be great adding `process_cpu_cores_available` as a threshold at `cpu usage` graph in the [official Grafana dashboard for VictoriaMetrics](https://docs.victoriametrics.com/#monitoring).

**Comment by hagen1778** [comment]
@valyala please see
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2191
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2190

**Comment by jelmd** [comment]
Hmmm, I've set the env var `GOMAXPROCS=2`, but vmagent says `process_cpu_cores_available 40`. Bug?

vmagent version: 1.74.0

**Comment by jelmd** [comment]
BTW: `/sys/fs/cgroup/system.slice/vmagent.service/cpuset.cpus.effective` shows `0-4` (set via systemd service config to make sure, vmagent does not misbehave ;-)).
