### ISSUE TITLE
the metric value show in grafana,sharp increase in a time

### ISSUE THREAD

**Issue by vipsql** [VictoriaMetrics/VictoriaMetrics#211]
**Describe the bug**
the metric is bigger increase!!
i used the prometheus java_client write the metric,the metric is Counters;
show in grafana,the value is sharp increase in a time;

**Screenshots**
![图片](https://user-images.githubusercontent.com/13550799/66839381-e9e9ec80-ef98-11e9-9640-6e0329057490.png)

**Version**
v1.28.0 cluster

**Comment by valyala** [comment]
@vipsql , could you provide the original query for this graph? It would be great if you could provide Graph for the same query on the same time range from Prometheus data source.

**Comment by vipsql** [comment]
1.The original query is **"power_meter{village="test"}"**;
2.I write the metric  direct to VictoriaMetric,not use the prometheus

**Comment by valyala** [comment]
Could you try storing the same data into another time series database - InfluxDB, Graphite or OpenTSDB - and check whether the metric value jumps there too at the same time?

**Comment by valyala** [comment]
@vipsql , do you have any updates on the issue?

**Comment by valyala** [comment]
@vipsql , I'm going to close this issue. Feel free re-opening it if you have updates.
