### ISSUE TITLE
/export time series seems cached after /delete_series

### ISSUE THREAD

**Issue by rjtokenring** [VictoriaMetrics/VictoriaMetrics#2116]
**Describe the bug**
If it is performed an /export of a time series and then /delete_series, if /export is executed again with same matcher, old data are returned for a long time. If matcher is changed, output of export changes and deleted time series is not returned.
It seems that /export data are kept in a cache.
We have tried to use nocache=1 (as per query_range), but result is similar (don't know if it is supported)

**To Reproduce**
1) /select/<id>/prometheus/api/v1/export?match={label="1"}
2) /delete/<id>/prometheus/api/v1/admin/tsdb/delete_series?match[]={label="1"}
3) /select/<id>/prometheus/api/v1/export?match={label="1"}  - same result as point 1), also after 30min

**Expected behavior**
After a delete, when deleted if performed, /export should not return data

**Version**
1.71
```

**Comment by jiangxinlingdu** [comment]
you can read this forced merge doc：https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#forced-merge

**Comment by jiangxinlingdu** [comment]
![image](https://user-images.githubusercontent.com/6373972/151648705-94bbd841-3487-48c4-b39d-cc45f7b8571f.png)
try no such problem

**Comment by valyala** [comment]
@rjtokenring , I cannot reproduce the issue on v1.71.0 with the following sequence of commands:

1. Import multiple time series with `{label="1"}` label:
```
curl -d 'm,label=1 x=123,y=1.23,z=42' -X POST 'http://localhost:8428/write'
```

2. Make sure that these time series can be read via `/api/v1/export`:
```
curl http://localhost:8428/api/v1/export -d 'match[]={label="1"}'
{"metric":{"__name__":"m_x","label":"1"},"values":[123],"timestamps":[1644674090444]}
{"metric":{"__name__":"m_y","label":"1"},"values":[1.23],"timestamps":[1644674090444]}
{"metric":{"__name__":"m_z","label":"1"},"values":[42],"timestamps":[1644674090444]}
```

3. Delete time series with `{label="1"}` label:
```
curl http://localhost:8428/api/v1/admin/tsdb/delete_series -d 'match[]={label="1"}'
```

4. Check that the deleted series aren't returned from `/api/v1/export`:

```
curl http://localhost:8428/api/v1/export -d 'match[]={label="1"}'
```

Make sure that nobody re-inserts the deleted time series between steps 3 and 4 in your case.

**Comment by denisgolius** [comment]
Hi @jiangxinlingdu !
Have you resolve this issue?

**Comment by denisgolius** [comment]
Closing the issue as inactive. Feel free to reopen if issue still remains.
