### ISSUE TITLE
RPM/deb generation

### ISSUE THREAD

**Issue by superguillen** [VictoriaMetrics/VictoriaMetrics#2118]
**Is your feature request related to a problem? 
RPM instalation in RHEL/OpenSuse

**Describe the solution you'd like**
Generate rpm artefact with the binarines

**Describe alternatives you've considered**
Custom generation of RPM

**Additional context**
in VM envirentment instalation is via RPM

**Comment by denisgolius** [comment]
Hi @superguillen !

There is a community rpm repo - https://github.com/patsevanton/victoriametrics-rpm .

**Comment by superguillen** [comment]
Thank's, 
where is the RPM's artifacts?

**Comment by denisgolius** [comment]
> Thank's, where is the RPM's artifacts?

@patsevanton could you help ?

**Comment by denisgolius** [comment]
Related issues:
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/107
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/128
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1909

**Comment by patsevanton** [comment]
> Thank's, where is the RPM's artifacts?

Hi!
Build here https://copr.fedorainfracloud.org/coprs/antonpatsev/VictoriaMetrics/package/victoriametrics/
RPM for arch here https://copr.fedorainfracloud.org/coprs/antonpatsev/VictoriaMetrics/build/3197239/

Installation guide here in readme https://github.com/patsevanton/victoriametrics-rpm

**Comment by superguillen** [comment]
Thanks @patsevanton , 
for victoriametrics rpm >=1.72 the rpm name is changed to vmsingle for non cluster version?,
regards.

**Comment by patsevanton** [comment]
@superguillen  https://github.com/patsevanton/victoriametrics-rpm/commit/ded922cf816e7f6acb1fc6b872756018c8cceeb6

Up version for vmagent,vmsingle,vmstorage
