### ISSUE TITLE
Maximum DB size on 32 Bit systems? 5 GB and more supported?

### ISSUE THREAD

**Issue by JsBergbau** [VictoriaMetrics/VictoriaMetrics#2119]
VictoriaMetrics is much faster, requires less RAM and CPU than influxdb, see https://valyala.medium.com/high-cardinality-tsdb-benchmarks-victoriametrics-vs-timescaledb-vs-influxdb-13e6ee64dd6b

It's a really fantastic project and since I'm also considering migrating from Prometheus to VictoriaMetrix on a Raspberry PI. I'm also considering to migrate from influxdb to VictoriaMetrics. But before that I have one very important question.

InfluxDB has on 32 Bit systems a very nasty problem: Database size can't exceed about 1,5 to 2 GB because of memory mapping the database files to memory. There is a pullrequest https://github.com/influxdata/influxdb/pull/12362 mitigating the mmap problem.

So my question is: Does VictoriaMetrics have the same limitation as influxdb on 32 bit systems? Or are database sizes of 5 GB and more on 32 bit no problem at all.

Would be great if some substantiated could be given.

**Comment by YuriKravetc** [comment]
Hi,

If you turn on long file support it should work.
Please note that for 32 bit systems there are limits in RAM - 2GB and for the disk, any file should not be larger than 4GB to work properly.

Best regards,

**Comment by JsBergbau** [comment]
Hi YuriKravetc,

thanks for your answer. What do you mean by turning on long file support? Didn't find a flag with that name.

**Comment by YuriKravetc** [comment]
Sorry for the typo.
It's a Large File Support, it depends on the specific filesystem. (Not turned on by using a flag)

**Comment by JsBergbau** [comment]
Found this by accident

> 
>  -fs.disableMmap
>     	Whether to use pread() instead of mmap() for reading data files. By default mmap() is used for 64-bit arches and pread() is used for 32-bit arches, since they cannot read data files bigger than 2^32 bytes in memory. mmap() is usually faster for reading small data chunks than pread()

in https://docs.victoriametrics.com/#list-of-command-line-flags

So now I'm really sure that VictoriaMetrix supports large databases.
