### ISSUE TITLE
Unexpected behavior for absent_over_time

### ISSUE THREAD

**Issue by psalaberria002** [VictoriaMetrics/VictoriaMetrics#2130]
**Describe the bug**
The absent_over_time in PromQL is expected to return 0 or 1 rows at most.
Definition taken from https://prometheus.io/docs/prometheus/latest/querying/functions/#absent_over_time:
```
absent_over_time(v range-vector) returns an empty vector if the range vector passed to it has any elements and a 1-element vector with the value 1 if the range vector passed to it has no elements.
```

VictoriaMetrics returns multiple rows in some cases, where it should not have reported any.

**Expected behavior**
See the following chart for example. Those are metrics from pods that are probably gone during the last few minutes, but there are still thousands of `up` metrics being reported. The expected result is an empty response.

![Screenshot 2022-01-31 at 11 40 24](https://user-images.githubusercontent.com/2410564/151780346-6a332e93-3f77-4c86-bdbf-f65ddbd73083.png)

**Version**
v1.71.0 cluster mode

**Comment by valyala** [comment]
@psalaberria002 , thanks for the bug report! It should be fixed in the commit 989668beba9a1bee82fb6a7645e259bef493a472 . Could you build `vmselect` from this commit according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and try executing `absent_over_time()` queries over this `vmselect` node in order to check whether the issue has been fixed?

This commit will be included in the next release of VictoriaMetrics.

**Comment by Wilderone** [comment]
We are face this problem in process of integrating VM with kubecost.
@valyala i build image from  this commit and everything seems ok now

**Comment by valyala** [comment]
@Wilderone , thanks for the update!

The bugfix has been integrated into [VictoriaMetrics v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by psalaberria002** [comment]
Thanks for the fix! Will try it in a couple of days.

**Comment by andywu1998** [comment]
hi, I don't think this function below matches the Prometheus definition of absent_over_time

```
// aggregateAbsentOverTime collapses tss to a single time series with 1 and nan values.
//
// Values for returned series are set to nan if at least a single tss series contains nan at that point.
// This means that tss contains a series with non-empty results at that point.
// This follows Prometheus logic - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2130
func aggregateAbsentOverTime(ec *EvalConfig, expr metricsql.Expr, tss []*timeseries) []*timeseries {
	rvs := getAbsentTimeseries(ec, expr)
	if len(tss) == 0 {
		return rvs
	}
	for i := range tss[0].Values {
		for _, ts := range tss {
			if math.IsNaN(ts.Values[i]) {
				rvs[0].Values[i] = nan
				break
			}
		}
	}
	return rvs
}
```
the function above means that tss contains a series with non-empty results at that point. but we can see the definition of absent_over_time on https://prometheus.io/docs/prometheus/latest/querying/functions/ . 

it says that

> absent_over_time(v range-vector) returns an empty vector if the range vector passed to it has any elements and a 1-element vector with the value 1 if the range vector passed to it has no elements.

it means that: return 1 when all the time series at that point is Nan, return 1 if any time series has elements

 But in the code above, absent_over_time will return nan when just only one time series has a nan value.

So I think the correct code is below:
change `if math.IsNaN(ts.Values[i]) {` to `if !math.IsNaN(ts.Values[i]) {`
```
func aggregateAbsentOverTime(ec *EvalConfig, expr metricsql.Expr, tss []*timeseries) []*timeseries {
	rvs := getAbsentTimeseries(ec, expr)
	if len(tss) == 0 {
		return rvs
	}
	for i := range tss[0].Values {
		for _, ts := range tss {
			if !math.IsNaN(ts.Values[i]) {
				rvs[0].Values[i] = nan
				break
			}
		}
	}
	return rvs
}
```
