### ISSUE TITLE
Error: UPGRADE FAILED: cannot patch "vm-agent-kube-state-metrics"

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#2131]
When I try to upgrade helm chart vm/victoria-metrics-k8s-stack from v1.68.0 to v1.72.0 I get the following error:
`Error: UPGRADE FAILED: cannot patch "vm-agent-kube-state-metrics" with kind Deployment: Deployment.apps "vm-agent-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"vm-agent", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

Before updating I execute the command:
`kubectl apply -f https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/crds/crd.yaml`
Temporary solution for me is deployment vm-agent-kube-state-metrics removal and again run helm upgrade.
Please tell me what could be the problem how to fix the update problem?

**Comment by mglotov** [comment]
Faced the same issue during the upgrade.

**Comment by f41gh7** [comment]
It seems to be an issue with breaking changes at kube-state-metrics dependency.  Faced the same problem during update.

**Comment by farmerluo** [comment]
Faced the same problem during update.

**Comment by f41gh7** [comment]
It's related with following PR 
https://github.com/prometheus-community/helm-charts/pull/927

 We can do nothing with it.. Delete manually kube-state metrics deployment and upgrade chart.
