### ISSUE TITLE
kubernetes service discovery incorrectly detects endpoints targets

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#2134]
**Describe the bug**
 
 Currently, only if endpoint port match container port of pod it works correctly - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d79a91558384ac9f49db68cdc1707a78b0e37475/lib/promscrape/discovery/kubernetes/endpoints.go#L176

 If nothing matched, this loop doesn't work https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.72.0/lib/promscrape/discovery/kubernetes/endpoints.go#L125

  
 Prometheus iterates over all seen pods, matched given endpoint subset

 https://github.com/prometheus/prometheus/blob/v2.33.0/discovery/kubernetes/endpoints.go#L267
 https://github.com/prometheus/prometheus/blob/v2.33.0/discovery/kubernetes/endpoints.go#L320

 It allows to discover targets without exposed ports for given service.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

 Even if endpoint doesn't have related port at pod, all container ports must be added to the targetLabels.

**Used command-line flags**
Please provide applied command-line flags used for running VictoriaMetrics and its components.

**Comment by valyala** [comment]
The bugfix has been included in [vmagent v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
