### ISSUE TITLE
vmagent does not identify some consul targets without a restart

### ISSUE THREAD

**Issue by richad1** [VictoriaMetrics/VictoriaMetrics#2140]
Hello everyone,

I am facing issue with a setup of consul servers and server consisting vmagent/victoriametrics setup.
Lately there are missing targets from consul server. They are registered with the consul agent just fine. But does not appear on the vmagent target list and in turn vmagent does not scrape them. We are looking for errors on both consul and VM logs but could not find anything which could help us with it.
Build version for VM is 
build version: victoria-metrics-20210815-205849-tags-v1.64.0-0-gc51885814

Please let me know in case further information is required.

**Comment by hagen1778** [comment]
Hi @richad1! Have you tried to update vmagent to the latest [v1.72](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.72.0) version?

**Comment by richad1** [comment]
Hi @hagen1778, thanks for such a prompt response!
Is this a known issue with the version 1.64?

**Comment by hagen1778** [comment]
> Is this a known issue with the version 1.64?

Looking in changelog I don't see any related issues. However, it is always recommended to stay up-to-date.

* Do you have any extra relabeling config in service discovery section for vmagent? 
* Is there anything specific about those targets which aren't discovered by vmagent? 
* Consul's agent by default logs all requests to the services/healthchecks, some of them should be from vmagent - is it possible to check those logs to verify that requests from vmagent are valid and filters are correct?
* Do you have flag `promscrape.suppressDuplicateScrapeTargetErrors` disabled? It can hide some config issues when set to `true`

**Comment by valyala** [comment]
There were multiple fixes in [Consul service discovery](https://docs.victoriametrics.com/sd_configs/#consul_sd_configs) over the last time:

- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4390
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3468
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/574
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2940
- https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2202

So it is likely this issue has been fixed too. So closing it for now.

@richad1 , please open a new issue if [the latest release of vmagent](https://docs.victoriametrics.com/CHANGELOG.html) still fails discovering some Consul targets.
