### ISSUE TITLE
Enable github discussions

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#2141]
Often there are problems where it is not clear, whether it is a real bug, or a misunderstanding of docs, shallow docs, or just no idea, how to solve it, etc. So having a separate place for discussion which doesn't flood real "issues" would probably helpful.

**Comment by hagen1778** [comment]
Hi @jelmd! Thanks for your request!

> So having a separate place for discussion which doesn't flood real "issues" would probably helpful.

We afraid that separating some questions to a different location will make user's experience worse because of the following reasons:
* not all github users are used to discussions and prefer search/follow issues only;
* the github search may hide relevant responses from discussions section, or users may not notice them;
* it is not clear if discussions are indexed by search engines such as google in the same way as issues.

While issues section in this repo may seem bloat, we try to add a proper label to each issue. We'd also check if there are old irrelevant issues which may be closed by now.

Please, let me know wdyt.

**Comment by jelmd** [comment]
Hi @hagen1778,

well, all reasonable points. But I see it more as an extension and a way to get more people from the community involved, get more feedback, and a place to see, how people use VM. Wrt. to your concerns:

a) IMHO people get used to it and if not they can still use issues for their "problems". It probably takes some time to get known but even if it doesn't get used, IMHO it is worth a try.

b) Yepp, but IMHO it often makes sense to just extract the meat of a [very long] discussion and push this into the issue instead. This makes user's life easier as well, because they do not need to study endless non-threaded "articles" (which might be of little use anyway because the user may not have the required insights/know how to classify it) and would save them a lot of time, too.  If too lazy to write a conclusion/"state of findings", one may just link in the relevant parts  - a little bit more work, yepp. In early days a mailing list with archived postings on a website would probably an equivalent.

c) Don't know. But since google takes everything it can ... ;-)

Last but not least I see discussion also as a place where to ask questions, where people can discuss their own setup with the community what, or one may announce VM related things, etc.  - just see https://github.blog/2021-08-17-github-discussions-out-of-beta/ (too lazy to repeat ;-)).

BTW: Of course proper labels are helpful as well, yes.

Anyway,  as long as the main developers have no problem with cluttered / "not a bug" / etc. issues, it is fine for me to ask questions here as well (just do not want to be guilty of stealing someones time ;-)).

**Comment by hagen1778** [comment]
Thank you for detailed response! I read the article and checked a couple of repos with discussions enabled. I like threads feature the mosе :-) However, the rest of functionality seems very the same as issues. I've also checked discussions in Prometheus repo and it looks far less popular than issues. The content there is also mixed between issues and discussions - bug reports and technical questions are present in both sections. So I don't see much benefit from it.

However, VM is a community-driven project. So let's see if this issue will get noticed and decide after.
Thanks for your efforts to make it better!

**Comment by valyala** [comment]
FYI, there are multiple places where VictoriaMetrics community can communicate - see https://docs.victoriametrics.com/#community-and-contributions .
