### ISSUE TITLE
Contents data/small and data/big folders? Storage format explained like InfluxDB does?

### ISSUE THREAD

**Issue by JsBergbau** [VictoriaMetrics/VictoriaMetrics#2151]
In VictoriaMetrics data folder is a `small` and a `big` folder. 
![grafik](https://user-images.githubusercontent.com/37013344/152765950-71ab8827-5c8d-408c-8aba-ff96532636ad.png)
Whereas the `small` folder contains almost twice the data of `big` folder.

How is this data distributed between these two folders? 

Is there some document that briefly explains the database storage format like influx does https://docs.influxdata.com/influxdb/v1.8/concepts/storage_engine/ ? Didn't find it.

**Comment by hagen1778** [comment]
Hi @JsBergbau!
See updated docs at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2155.

**Comment by JsBergbau** [comment]
@hagen1778 
Thanks for the fast update of the docs.

I've now forced a merge of all data like described here https://github.com/VictoriaMetrics/VictoriaMetrics#forced-merge
and now storage distribution is
![grafik](https://user-images.githubusercontent.com/37013344/152806506-0a57569c-31ac-49d8-8511-5f56f17a85c1.png)

Now all makes sense. I've imported the data about 12 hours ago from prometheus, so thats why data wasn't merged. Overall space utilization isn't much lower as before merge, but compared to prometheus it is a lot. Prometheus uses over 2,2 GB so 4 times more than VictoriaMetrics. 

There remain two files in each folder (december 2021 and january 2022)
![grafik](https://user-images.githubusercontent.com/37013344/152808032-4e034dd0-1d13-4397-8971-c19c430a3c4f.png)
Regarding timestamp they contain both the same data. Is this due to MergeTree that two files remain to make future merging easier?

**Comment by hagen1778** [comment]
> Regarding timestamp they contain both the same data

That doesn't mean exactly the same data, just that both parts containing series with the same min and max timestamps.

Btw, of what exact folder the latter screenshot is? Do you continue to write data into VictoriaMetrics after merging was finished?

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if further clarification is needed or you think docs aren't complete.
