### ISSUE TITLE
Two queries should return the same values but they don't.

### ISSUE THREAD

**Issue by mihailigoshin** [VictoriaMetrics/VictoriaMetrics#2154]
Hello everyone, 

I have two queries and it looks for me they have to return same values but they don't. I cannot understand why and what is happening. 
VictoriaMetrics version:  victoria-metrics-20210715-110943-tags-v1.63.0-0-g61cc13c16
Grafana: 8.3.3
![2022-02-07_15-08_1](https://user-images.githubusercontent.com/67579275/152794892-6da9f7e6-8c7d-4a9f-bbb0-f3142da281c4.png)
![2022-02-07_15-08](https://user-images.githubusercontent.com/67579275/152794905-30471e4d-7330-4d15-adb2-2d7754f4e8d4.png)

**Comment by valyala** [comment]
Closing the question as answered.
