### ISSUE TITLE
bug(vmalert): wrong href 

### ISSUE THREAD

**Issue by jmenan** [VictoriaMetrics/VictoriaMetrics#2167]
**Describe the bug**
there seems to be a bug in the href of VMalert :

From the home page, the links "vmalert", "groups", "alerts" are ok but they don't work anymore if in the detail page of an alert because the alert id is added 

**To Reproduce**
click to "Details" on an active alert and we can see the link for "vmalert","groups", "alerts" are wrong

**Expected behavior**
the link works on any pages

**Logs**
``` 
2022-02-08T18:23:06.974Z	warn	VictoriaMetrics/lib/httpserver/httpserver.go:324	remoteAddr: "10.25.183.109:35740", X-Forwarded-For: "10.93.16.129"; requestURI: /18337902286425335437/11125931252278312780/alerts; unsupported path requested: "/18337902286425335437/11125931252278312780/alerts"
```

**Screenshots**
![Capture d’écran 2022-02-08 à 18 57 47](https://user-images.githubusercontent.com/50320627/153051353-e8104e74-ba96-4f43-9993-cb4a96f1ed9d.png)

**Version**
```
# ./vmalert-prod --version
vmalert-20220118-213642-tags-v1.72.0-0-gd79a91558
```

**Used command-line flags**
```
    Args:
      -datasource.url=http://vmselect-victoria-metrics-k8s-stack.monitoring.svc:8481/select/0/prometheus
      -evaluationInterval=15s
      -external.url=https://vmalert.xxx.xxx.tech
      -httpListenAddr=:8080
      -notifier.url=http://vmalertmanager-victoria-metrics-k8s-stack-0.vmalertmanager-victoria-metrics-k8s-stack:9093,http://vmalertmanager-victoria-metrics-k8s-stack-1.vmalertmanager-victoria-metrics-k8s-stack:9093
      -remoteRead.url=http://vmselect-victoria-metrics-k8s-stack.monitoring.svc:8481/select/0/prometheus
      -remoteWrite.url=http://vminsert-victoria-metrics-k8s-stack.monitoring.svc:8480/insert/0/prometheus
      -rule="/etc/vmalert/config/vm-victoria-metrics-k8s-stack-rulefiles-0/*.yaml"
```

**Comment by hagen1778** [comment]
Hi @jmenan! Thanks for youre request!
Please see the following PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2168. To try if it works for you can [build from sources](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) or wait for it to be included into the next release.
