### ISSUE TITLE
How to properly query InfluxDB data in VictoriaMetrics?

### ISSUE THREAD

**Issue by n3k232** [VictoriaMetrics/VictoriaMetrics#2170]
Hi,

i tried to change my Database Backend from Influxdb2.0 to Victoriametrics but i seem to have some difficulties with quering my performance data.

I write all my perfdata with influx syntax via http into the victoriametrix and everything seems to be fine when i query my metrics manual with the /api/v1/export API but in Grafana all my datapoints are shifted to full 5 minutes.

Is there a way to query the  query the /api/v1/export endpoint with grafana?

Thanks and regards
Lars

**Comment by tredondo** [comment]
> PromQL (or [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html)) queries, which always return calculated data according to Prometheus data model (e.g. they cannot return raw data

I that really not possible? I can obtain from VM what appears to be raw data as explained here:

https://www.robustperception.io/extracting-raw-samples-from-prometheus explains how to return raw data:

> So how can you get the raw samples? The answer is to use a range vector selector with the query endpoint. For example `http://demo.robustperception.io:9090/api/v1/query?query=up[1m]` will return the last minute worth of raw data for the `up` time series

Results are in the screenshots at #2414.

**Comment by hagen1778** [comment]
See following docs 
* https://docs.victoriametrics.com/guides/migrate-from-influx.html#query-data
* https://docs.victoriametrics.com/keyConcepts.html#query-data
