### ISSUE TITLE
vminsert OOM killed by system

### ISSUE THREAD

**Issue by Planck0591** [VictoriaMetrics/VictoriaMetrics#2172]
**Describe the bug**
Because we have not enough mechines，we deploy vminsert, vmselect, vmstorage in a same node.
Each component set memory limit as belong:
vminsert -memory.allowedPercent=10
vmselect -memory.allowedPercent=10
vmstorage -memory.allowedPercent=40
most of time they work well, but sometimes vminsert got memory spike and killed by system as oom.
I checked the vminsert log, there is no error or warn log.
I check system log, it is killed by the system oom killer.The log is as belong:
![153372695-bf9b3579-ce15-49a2-8a73-7609f54ba4b2](https://user-images.githubusercontent.com/79493220/153719213-917e23ba-170f-4be5-ab08-2274b6a38875.png)
![153372801-a0da84d2-b12d-4b14-bd77-e797b79ef46b](https://user-images.githubusercontent.com/79493220/153719218-eb5efab1-328e-4b81-8f39-738cccc88912.png)

I check the grafana, and memory spike showed as belong:
![image](https://user-images.githubusercontent.com/79493220/153372004-eba37395-21da-4698-af88-c2ccd96632f5.png)

**Comment by hatemosphere** [comment]
why don't you just use single node?

**Comment by denisgolius** [comment]
> **Describe the bug** Because we have not enough mechines，we deploy vminsert, vmselect, vmstorage in a same node. Each component set memory limit as belong: vminsert -memory.allowedPercent=10 vmselect -memory.allowedPercent=10 vmstorage -memory.allowedPercent=40 most of time they work well, but sometimes vminsert got memory spike and killed by system as oom. I checked the vminsert log, there is no error or warn log. I check system log, it is killed by the system oom killer.The log is as belong: ![image](https://user-images.githubusercontent.com/79493220/153372695-bf9b3579-ce15-49a2-8a73-7609f54ba4b2.png) ![image](https://user-images.githubusercontent.com/79493220/153372801-a0da84d2-b12d-4b14-bd77-e797b79ef46b.png) I check the grafana, and memory spike showed as belong: ![image](https://user-images.githubusercontent.com/79493220/153372004-eba37395-21da-4698-af88-c2ccd96632f5.png)

Hi @Planck0591 !

Could you share the  screenshots from your [VM Cluster dashboards](https://grafana.com/grafana/dashboards/11176) ? 
It is a good practice to monitor your cluster by vmagent and use vmalert.

**Comment by Planck0591** [comment]
@hatemosphere thank you for your reply!We used 9 machines, each machine deploy three nodes together.

**Comment by Planck0591** [comment]
@denisgolius thank you for your reply!
VM Cluster dashboards is very big,I screenshot OOM machine resource usage as belong:
![image](https://user-images.githubusercontent.com/79493220/153527724-42b01ab7-dccd-4def-8818-e34b3e2cccd2.png)
We used vmagent to monitor our cluster,but vmalert not yet.We will try it ,thank you.

**Comment by Planck0591** [comment]
@denisgolius 
![image](https://user-images.githubusercontent.com/79493220/153528825-e381c734-fd4f-4c92-bae7-d8b4dd8fd893.png)
this picture shows vminsert is down a while,and it was restarted by systemd

**Comment by denisgolius** [comment]
> @hatemosphere thank you for your reply!We used 9 machines, each machine deploy three nodes together.

Please share the screenshot for all dashboard page.

**Comment by Planck0591** [comment]
@denisgolius 
![1](https://user-images.githubusercontent.com/79493220/153557236-e4d22870-a369-4d36-acc9-efcd62dab43f.png)
![2](https://user-images.githubusercontent.com/79493220/153557246-0096510b-eacb-48e3-a4c3-f5094147bd90.png)
![3](https://user-images.githubusercontent.com/79493220/153557250-59400d3d-77d7-46fa-82b6-c04b8c06241f.png)
![4](https://user-images.githubusercontent.com/79493220/153557256-4517e5a9-65cd-4aed-b826-d86e7819781d.png)
![5](https://user-images.githubusercontent.com/79493220/153557261-c1ef1453-e09e-443d-a9d8-40cd8e130c69.png)
![6](https://user-images.githubusercontent.com/79493220/153557263-86ffd395-b45f-4966-adf5-207309e05d66.png)
![7](https://user-images.githubusercontent.com/79493220/153557270-c3360ef5-12c5-45e6-8b7c-ba2a4b73a93d.png)
![8](https://user-images.githubusercontent.com/79493220/153557276-642b0a96-2103-4d86-a566-7a97ac2df676.png)
![9](https://user-images.githubusercontent.com/79493220/153557281-3e2e0007-5e63-43f6-8eb0-a29a98a28b91.png)
![10](https://user-images.githubusercontent.com/79493220/153557290-254b4bfd-6c80-485b-bb33-6c902c50890d.png)

**Comment by denisgolius** [comment]
Sorry, my mistake =) I meaned this screenshots for the same time range as you share in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2172#issuecomment-1035758736

**Comment by Planck0591** [comment]
@denisgolius It is ok.It just oomed a few moments ago,so i screenshot it.What is the difference or what is the focus?

**Comment by Planck0591** [comment]
@valyala Thanks for reply.There is 64GB memory each machine.Vminsert started with config -memory.allowedPercent=10.So it equal -memory.allowedBytes=6.4GiB,right?Should I try -memory.allowedBytes?

**Comment by Planck0591** [comment]
@denisgolius hi，please edit your comment which refered my comment.There is picture which has not been encrpyted.I will appreciate it.

**Comment by Planck0591** [comment]
@valyala hi, -maxConcurrentInserts was configed as 100000.Is it OK?

**Comment by valyala** [comment]
> There is 64GB memory each machine.Vminsert started with config -memory.allowedPercent=10.So it equal -memory.allowedBytes=6.4GiB,right?Should I try -memory.allowedBytes?

Correct. The `-memory.allowedPercent` and `-memory.allowedBytes` command-line flags at `vminsert` limit only the size of in-memory buffers used to send data to `vmstorage` nodes. These flags don't limit memory, which can be used during processing of incoming inserts.

> `-maxConcurrentInserts` was configed as 100000.Is it OK?

This isn't OK. The `-maxConcurrentInserts` effectively limits memory, which is used when processing incoming inserts. Default value should work OK in most cases. See description for this flag (it can be triggered by passing `-help` command-line flag to `vminsert`):

>   -maxConcurrentInserts int
        The maximum number of concurrent inserts. Default value should work for most cases, since it minimizes the overhead for concurrent inserts. This option is tigthly coupled with -insert.maxQueueDuration (default 16)

>   -insert.maxQueueDuration duration
        The maximum duration for waiting in the queue for insert requests due to -maxConcurrentInserts (default 1m0s)

Too high value for `-maxConcurrentInserts` is the most likely reason for vminsert OOMs.

**Comment by Planck0591** [comment]
@valyala Thank you very much.After these days experiments,I found you are right.This Issue could be closed now.
