### ISSUE TITLE
Questions for scaling multiple metrics with the __graphite__ parameters

### ISSUE THREAD

**Issue by TodorSamardziski** [VictoriaMetrics/VictoriaMetrics#2176]
When using `__graphite__` or the `label_graphite_group` I cannot do some operation on multiple metrics. For example :

`label_graphite_group({__graphite__=~"a.b.c.d.e.*.g"},5,6)` display all the value on grafana (445,563,112...) in the grafana panel.

Value for example stored :
a.b.c.d.e.150.g = 445
a.b.c.d.e.350.g = 563
a.b.c.d.e.220.g = 112
a.b.c.d.e.452.g = 153
a.b.c.d.e.448.g = 223

Is it possible to scale all the exsting series by a value ? For example :
`label_graphite_group({__graphite__=~"a.b.c.d.e.*.g"},5,6) / 10`

445 become 44.5
563 become 56.3
...

With graphite datasource on grafana, it's possible to use the scale function to do it.

Is it in plan to implement something like this with promQL ? Or maybe it's already possible, but as I'm not really experimented in promQL I didn't find a solution to do it.

**Comment by valyala** [comment]
So you need to convert metric name to a numeric value. This can be done with [label_value](https://docs.victoriametrics.com/MetricsQL.html#label_value) function:

```metricsql
label_value(label_graphite_group({__graphite__=~"a.b.c.d.e.*.g"},5,6), "__name__") / 10
```

**Comment by TodorSamardziski** [comment]
Hello @valyala 

Maybe my question wasn't really clear. But the goal of the promql query is to do like a scale(0.1) (Function when using graphite datasource) of {__graphite__=~"a.b.c.d.e.*.g"}

So for example : 
Key ----- Value
a.b.c.d.e.150.g ----- 445
a.b.c.d.e.350.g ----- 563

It works when using only one key, but not when using multiple metrics.
`{__graphite__=~"a.b.c.d.e.150.g"} /10
`

This is not working :
`{__graphite__=~"a.b.c.d.e.*.g"} /10
`

The label_graphite_group is used to have a specific ___name___ in the legend. So finally something like this :
`label_graphite_group({__graphite__="a.b.c.d.e.150.g"},5,6) /10
`

But on multiple key :
`label_graphite_group({__graphite__="a.b.c.d.e.*.g"},5,6) /10
`

Sorry if it wasn't really clear... Many thanks for you quick response.

**Comment by TodorSamardziski** [comment]
Hello @valyala 

Any news on how we can do this ?

Many thanks and Best regards !
