### ISSUE TITLE
Select doesn't return inserted data for significant period for the cluster version

### ISSUE THREAD

**Issue by abogdanovqa** [VictoriaMetrics/VictoriaMetrics#218]
**Describe the bug**
There is lag up to 1 minute between the moment when metrics were inserted and when select returns them.
According to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/163 it should be delay but just few seconds. I've checked it works for standalone version but for cluster versions it doesn't.

**To Reproduce**
``` bash
curl -d "t4,unit=1001 io1=30u" -X POST 'http://victoria-vminsert:8480/insert/0/influx/write?consistency=any&db=test&rp=autogen'  && \
sleep 10  && \
curl -X GET 'http://victoria-vmselect:8481/select/0/prometheus/api/v1/query?query=\{__name__=%22t4_io1%22,unit=~%221001%22\}[20s]'
```

**Expected behavior**
The lab is not exact 1 min. It's very random.
I expect that I can get inserted data in few seconds. May be 10 seconds, but not 1 minute.

**Version**
Cluster v1.0.28 

**Additional context**
I used to use Grafana to do queries as well and I noticed that in Grafana I see the point much earlier in comparison if I do requests on my own by curl. I mean when Grafana displays the new point already. I send the request by curl and I get an empty response anyway. And only after 1 min I finally receive the data.
The difference I found is that Grafana does queries to "query_range" method, but I use "query" instead.

**Comment by hagen1778** [comment]
Hi @abogdanovqa ! 
I guess, this is expected. See this [setting](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/prometheus/prometheus.go#L39).

**Comment by abogdanovqa** [comment]
Hi @hagen1778 , thanks a lot! We were looking for this everywhere except select :) Does it make sense to extract this value as an external parameter? It will be very helpful for test purposes. If there is no objections we can create a pull request with corresponding changes.

**Comment by valyala** [comment]
> Does it make sense to extract this value as an external parameter?

This sounds reasonable.

**Comment by valyala** [comment]
Starting from commit 4e6bf6f538e6b3e9da8945fe79a52cdc20c3f401 cluster version of VictoriaMetrics exposes the `-search.latencyOffset` command-line flag for tuning the time when data point becomes visible in query results after its collection. This commit will be included in the next release.

**Comment by valyala** [comment]
@abogdanovqa , the `-search.latencyOffset` flag is available starting from [v1.28.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
Closing the issue. Feel free re-opening it if additional questions arise regarding the issue.

**Comment by abogdanovqa** [comment]
@valyala, thanks a lot!

**Comment by valyala** [comment]
FYI, non-zero `-search.latencyOffset` significantly reduces isolation issue from Prometheus - see https://github.com/prometheus/prometheus/issues/1893 for details.
