### ISSUE TITLE
Vmalert to support `$externalLabels` and `$externalURL` template variables

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2193]
**Describe the bug**
External labels set via `-external.label` flag are available via `$labels` template variable. But in Prometheus all external labels are accessible via `$externalLabels` var. We need to support this variable for the sake of compatibility.

Prometheus also supports `$externalURL` var in templating. Vmalert allows to configure this param via flag `external.url`, but its value isn't available in template variables.

**Workaround**
Use `$labels` variable instead.

**Comment by valyala** [comment]
vmalert supports `$externalLabels` and `$externalURL` template variables starting from [v1.73.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
