### ISSUE TITLE
why reset tsid cache before save cache?

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2205]
see the code: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/3569352fe05a8255901a05631fd98b627f60bd09/lib/storage/storage.go#L743

I think there will be:
```go
func (s *Storage) resetAndSaveTSIDCache() {
        s.mustSaveCache(s.tsidCache, "MetricName->TSID", "metricName_tsid")
	s.tsidCache.Reset()  // save should in front of reset
}
```

Or tell me why.
thanks.

**Comment by valyala** [comment]
The cache is reset before saving to disk in order to prevent from possible inconsistent behaviour after unclean shutdown. See  ce10bdc82a2af0eb9e8340d73c54aac11e6571cd and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1347 for details.

**Comment by ahfuzhang** [comment]
sorry, still don't understand.
fastcache.Reset() will set all buckets to nil.
and saveFile can't get any data.

And, chunk put back to pool, it will  in use by other cache instance any moment.Data could be over write.
