### ISSUE TITLE
Add X-Influxdb-Version custom header support 

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#2209]
**Is your feature request related to a problem? Please describe.**
To work with InlfuxDB ntopng checks it version and get it by the header but VictoriaMetrics don't provide such header so ntopng can't work with VictoriaMetrics out of the box.

**Describe the solution you'd like**
Add `X-Influxdb-Version `custom header support which can be configured by a flag.

**Describe alternatives you've considered**
As a workaround it can be resolve by using nginx with placing needed header. See https://github.com/ntop/ntopng/issues/5449#issuecomment-1005347597

**Comment by valyala** [comment]
FYI, the commit 71ef3155c8733a5b8b4560af80fb557a1b64a71a hardcodes the `X-Influxdb-Version` http response header for InfluxDB-related APIs supported by VictoriaMetrics. This commit will be included in the next release of VictoriaMetrics

**Comment by valyala** [comment]
VictoriaMetrics emits `X-Influxdb-Version: 1.8.0` http response headers from `/write` and `/influx/write` APIs starting from [v1.73.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
