### ISSUE TITLE
VictoriaMetrics Duplicate Data

### ISSUE THREAD

**Issue by yzhengwei** [VictoriaMetrics/VictoriaMetrics#2216]
version: v1.72.0-cluster

I used the VictoriaMetrics cluster and deployed three vmagent clusters using the same configuration with `-promscrape.cluster.membersCount=2`,  and set the vminsert with `-replicationFactor=2`,  In vmstorage, I use `-dedup.minScrapeInterval=15s` to remove duplicate data from vmagent, vmagent scrape_interval is 15s.  There is no setting in vmselect to remove duplicates, I understand that I will get two copies of the same data from vmselect, but it looks like there is more than that, there is some extra data, Fox example, in vmstorage, I user `-dedup.minScrapeInterval=15s`, but there are multiple duplicates within 15s, Why?

### vmagent
```shell
# vmagent 0
/vmagent-prod -promscrape.config="/etc/vmagent/config/vmagent.yaml" \
    -promscrape.cluster.memberNum="0" \  
    -promscrape.cluster.membersCount="3" \
    -promscrape.cluster.replicationFactor="2" \
    -remoteWrite.tmpDataPath="/data" \
    -remoteWrite.url="http://vminsert.victoria.svc.cluster.local:8480/insert/0/prometheus" 

# vmagent 1
/vmagent-prod -promscrape.config="/etc/vmagent/config/vmagent.yaml" \
    -promscrape.cluster.memberNum="1" \  
    -promscrape.cluster.membersCount="3" \
    -promscrape.cluster.replicationFactor="2" \
    -remoteWrite.tmpDataPath="/data" \
    -remoteWrite.url="http://vminsert.victoria.svc.cluster.local:8480/insert/0/prometheus" 

# vmagent 2
/vmagent-prod -promscrape.config="/etc/vmagent/config/vmagent.yaml" \
    -promscrape.cluster.memberNum="2" \  
    -promscrape.cluster.membersCount="3" \
    -promscrape.cluster.replicationFactor="2" \
    -remoteWrite.tmpDataPath="/data" \
    -remoteWrite.url="http://vminsert.victoria.svc.cluster.local:8480/insert/0/prometheus" 
```
### vminsert
```shell
/vminsert-prod -storageNode=vmstorage-0.vmstorage.victoria.svc:8400,vmstorage-1.vmstorage.victoria.svc:8400,vmstorage-2.vmstorage.victoria.svc:8400 \
    -maxLabelsPerTimeseries=60 \
    -replicationFactor=2
```
### vmstorage
```shell
/vmstorage-prod -storageDataPath=/data \
    -retentionPeriod=7d \
    -dedup.minScrapeInterval=15s
```
Query result:
![image](https://user-images.githubusercontent.com/59439277/154658199-4f2b75de-143b-4d7b-a7de-c4337b77e2eb.png)

**Comment by valyala** [comment]
`vminsert` can write samples for the same time series to distinct `vmstorage` nodes under the following conditions:
* When there are multiple `vminsert` nodes with different order of `-storageNode` args. For example, the first `vminsert` has `-storageNode=vmstorage1,vmstorage2,vmstorage3`, while the second `vminsert` has `-storageNode=vmstorage3,vmstorage2,vmstorage1`.
* When a `vmstorage` node becomes temporarily unavailable. In this case `vminsert` re-routes incoming samples to the remaining `vmstorage` nodes.
* When `vminsert` runs with `-disableRerouting=false` command-line flag and a `vmstorage` node receives data at slower rate than other `vmstorage` nodes. In this case `vminsert` re-routes incoming samples from the slower `vmstorage` node to faster `vmstorage` nodes.

For example, the first sample with `17:44:13` timestamp could be written to `vmstorage1`, while the second sample with the same timestamp could be written to `vmstorage2`. Such samples cannot be de-duplicated at `vmstorage` nodes. They need to be de-duplicated at `vmselect`. So `vmselect` should run with the same `-dedup.minScrapeInterval` command-line flag, which is passed to `vmstorage` nodes. The solution for the case above is to run `vmselect` with `-dedup.minScrapeInterval=15s` command-line flag.

**Comment by dhanunjayanethala** [comment]
we too are facing similar issue where in we are seeing duplicate data in VMselect.for each record there is another similart with a time gap of 15seconds.the replication factor is set to 2 for each of VMselect,vminsert and Vmstorage.

we have already tried the -dedup.minScrapeInterval=15s configuration on the VMSELECT and VMSTORAGE and it did not help.

any other possible solution available?

**Comment by valyala** [comment]
@dhanunjayanethala , please see [de-duplication docs for VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/#deduplication) and [troubleshooting docs](https://docs.victoriametrics.com/troubleshooting/index.html#unexpected-query-results).

Closing the question as answered.
