### ISSUE TITLE
Victoria Metrics read only issue

### ISSUE THREAD

**Issue by DarthDickus** [VictoriaMetrics/VictoriaMetrics#2220]
System Specs:
```
Dell R440 
CPU 2x Xeon Plat 8153
RAM: 256g
OS Drv 1tb
Data Drv 24tb
Oracle Linux 8.4
```

I have Prometheus scraping targets for my netflow server. In turn I have VM trying to scrap Prom. I am running: \

```
./vmagent-prod -promscrape.config.strictParse=false -promscrape.config=/etc/prometheus/prometheus.yml -remoteWrite.url=https://127.0.0.1:8429/api/v1/import/prometheus
```
And when it runs I get the following error

>	warn	VictoriaMetrics/app/vmagent/remotewrite/client.go:272	couldn't send a block with size 53561 bytes to "1:secret-url": Post "https://127.0.0.1:8429/api/v1/import/prometheus": dial tcp4 127.0.0.1:8429: connect: connection refused; re-sending the block in 2.000 seconds

Thank you very much for reading this and any help would be greatly appeciated

**Comment by denisgolius** [comment]
Hi @DarthDickus !

When you use `vmagent`, it should write scraped data to the VictoriaMetrics Single or Cluster. But I see that you have a wrong `remoteWrite.url` in `vmagent` configuration.

You configure `vmagent` to send data to themself `-remoteWrite.url=https://127.0.0.1:8429/api/v1/import/prometheus` when the port should be 8428 for VictoriaMetrics Single)and your vmagent config will look like:
`./vmagent-prod -promscrape.config.strictParse=false -promscrape.config=/etc/prometheus/prometheus.yml -remoteWrite.url=http://victoriametrics:8428/api/v1/write` as an vmagent can only write scraped data to remote write.
Please refer https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml#L15 for VM SIngle and https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/deployment/docker/docker-compose.yml#L15 for VM Cluster.

**Comment by valyala** [comment]
@DarthDickus , I'd recommend also removing `-promscrape.config.strictParse=false` command-line option and instead fixing config errors at the file pointed by `-promscrape.config` .

**Comment by valyala** [comment]
Closing the question as answered.
