### ISSUE TITLE
Use relative URLs for vmalert

### ISSUE THREAD

**Issue by mr-karan** [VictoriaMetrics/VictoriaMetrics#2231]
**Describe the bug**

When `vmalert` and `vmagent` are as a sub path behind a reverse proxy (for eg `vicky.company.tld/vmagent` and `vicky.company.tld/vmalert`), the behaviour of both components are different.

Usage of `/` in the URLs on the links specified in `vmalert` UI, leads to removal of `/vmalert` in the URL which isn't correct.

**To Reproduce**

- Deploy `vmalert` and expose it on `vicky.company.tld/vmalert` via a reverse proxy like NGINX/Caddy
- Go to `vicky.company.tld/vmalert` and click on any URL (like `/api/v1/groups`).
- It points to `vicky.company.tld/api/v1/groups`. The `/vmalert` part is lost in the URL, so the reverse proxy throws a 404.

**Expected behavior**

Links in `vmalert` shouldn't have a `/` as the prefix as that leads to `vicky.company.tld/...` and `vmalert` is lost. Behaviour of `vmagent` is correct which doesn't have `/`

**Logs**

NA

**Screenshots**

This screenshot is of  `vmagent`, which doesn't have `/` prefixed on the endpoints, it works correctly when exposed via a reverse proxy.

![image](https://user-images.githubusercontent.com/5689132/154933901-1a1c2d27-67aa-48db-a949-acc5ea6b2a2a.png)

The below screenshot is `vmalert` which has `/` and that is causing issues:

![image](https://user-images.githubusercontent.com/5689132/154934931-cdd40c28-a451-433d-9cdd-27ea3a45b110.png)

**Version**

1.73.0

**Used command-line flags**

NA

**Comment by hagen1778** [comment]
Hi @mr-karan!
To make it work for `vmalert` you need to specify the proxy path via the following flag:
```
  -http.pathPrefix string
        An optional prefix to add to all the paths handled by http server. For example, if '-http.pathPrefix=/foo/bar' is set, then all the http requests will be handled on '/foo/bar/*' paths. This may be useful for proxied requests. See https://www.robustperception.io/using-external-urls-and-proxies-with-prometheus
```

**Comment by mr-karan** [comment]
@hagen1778 Thanks for the tip! Will do that. Feel free to close if this is the intended behaviour (but IMHO having both vmalert/vmagent components to be consistent) might be better. 👍

**Comment by hagen1778** [comment]
My opinion is that we need to keep `/` for links, since in vmalert there is a need for having it. For example, on the page `http://<vmalert>/<group-id>/<alert-od>/status` if we rm `/` sign from the navigation links - they will stop working.
It does not affect vmagent since it just does not have such a navigation or complex links.

**Comment by mr-karan** [comment]
Makes sense. Thanks!
