### ISSUE TITLE
Minimum AlertManager version supported 

### ISSUE THREAD

**Issue by lucianolacurcia** [VictoriaMetrics/VictoriaMetrics#2236]
As VictoriaMetrivs relays on AlertManager, I suggest to explicitly add to the docs which is the minimum AlertManager version supported by VictoriaMetrics.
I was trying to replace my current prometheus with vm and use the already deployed and working AlertManager (0.15.2) but I realized that this AlertManager version doesn't implemented yet api/v2 so got a "404 page not found" error when sending alerts from vmalert to AlertManager.

I think [this version 1.16](https://github.com/prometheus/alertmanager/releases/tag/v0.16.0-alpha.0) is the first to introduce api/v2.

Thanks!

**Comment by denisgolius** [comment]
Hi @lucianolacurcia !

Thanks for your investigation!
We will update the documentation.
