### ISSUE TITLE
why vm-storage only check the min date of TimeRange ?

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2239]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/acbea6c1ee162227d4ef8d11cf39b1abe6e2c7cd/lib/storage/index_db.go#L1872

func (is *indexSearch) containsTimeRange only check the min date.
I think there should be a for..range from min date to max date.

thanks.

**Comment by valyala** [comment]
@ahfuzhang , thanks for good question! I added a comment to this function, which explains why it doesn't check the upper bound of `tr` time range. See 8bf3fb917a535cdcf88f4e2df438ab95bdeabce4 .
