### ISSUE TITLE
Extend single-version dashboard

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#224]
Add panels for:
*  rate(vm_slow_queries_total[5m])
* on-going merges 
* merge speed

**Comment by valyala** [comment]
@hagen1778 , could you add `rate(vm_new_timeseries_created_total[5m])` graph to both single-node and cluster dashboards. This graph shows time series churn rate. See the corresponding [commit](e2121b84b4124d41df6f8aa129c56e6399007f0a). It will be available in the upcoming `v1.28.4' release.

**Comment by hagen1778** [comment]
Will update dashboards on grafana.com on release
