### ISSUE TITLE
Multitenant with VMGateway

### ISSUE THREAD

**Issue by maorlx** [VictoriaMetrics/VictoriaMetrics#2241]
Hi, 
We are looking into the enterprise edition of VM, specifically looking on the VMGateway component for the purpose of rate limiting. After looking in the documentation, I got a few questions:
1. We've got our own authorization pipe, being done before requests arriving the VMGateway. I saw the specific tenant can be given using a JWT token in the Authorization header.  Is there another way to supply the tenant ID or the VM Access json? (assuming we don't need the auth - the "exp" validation).
2. Is there any specific API to manage VMGateway ? for example - 
- Updating the rate limiting configuration for some tenants.
- Reloading the configuration (assuming it won't cause any downtimes)

Thanks for the help.
Maor

**Comment by valyala** [comment]
@f41gh7 , could you help with this question?

**Comment by maorlx** [comment]
@f41gh7  Thanks !
Regarding the second answer, what did you mean "I think, that at the next release it will loading configuration via http as vmagent does."?
From the documentation, it seems vmagent doesn't support loading configuration via http so not sure which configuration you are referencing

**Comment by f41gh7** [comment]
> And if you meant that, do you maybe have any estimation when is the next release expected to be released?

 Sorry, file reading from url wasn't added to the current release. It will be at the next one.



> From the documentation, it seems vmagent doesn't support loading configuration via http so not sure which configuration you are referencingץ
> Edit:
> did you mean that?

 Yep, this flag supports http url endpoint. For instance, `-promscrape.config=http://localhost:8436/scrape_config.yml`
 It's already used in our benchmark suite. https://github.com/VictoriaMetrics/prometheus-benchmark/blob/main/chart/templates/vmagent/deployment.yaml#L46

**Comment by valyala** [comment]
[vmageway](https://docs.victoriametrics.com/vmgateway.html) can read `-ratelimit.config` file from URL starting from [v1.76.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It also gained support for `-ratelimit.configCheckInterval` command-line option, which can be used for specifying the interval for re-reading the file pointed by `-ratelimit.config`.
