### ISSUE TITLE
compute jobid and InstanceID is not strict

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2244]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/99ee1c13c05479d974d496c8b44c5c6b84ed03b0/lib/storage/index_db.go#L634

there is no reason for job id is index 0, and instance id is index 1.
It will right for just lucky.

thanks.

**Comment by valyala** [comment]
@ahfuzhang , thanks for an excellent question! It has been answered directly in the code comments at commit 7e99bbb9678318c78bcfad79f6e84710d398ee2d

**Comment by valyala** [comment]
Closing the question as answered.
