### ISSUE TITLE
inmemoryBlock not need to sort data

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2245]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/99ee1c13c05479d974d496c8b44c5c6b84ed03b0/lib/mergeset/encoding.go#L149

I think sort Items is fine, no need to sort data.
it will improve a little.

thanks.

**Comment by valyala** [comment]
Indeed - there is no an obvious need in sorting the `ib.data` here. Thanks for the suggestion! It has been addressed in the commit af5bdb9254ec80e64b0ba5a999415de3b91dcd2d

**Comment by valyala** [comment]
Closing the issue as done. @ahfuzhang , feel free re-opening it if you think it needs additional handling.
