### ISSUE TITLE
func (tb *Table) mergeInmemoryBlocks, this function is terrible

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2249]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1967b9c211b05029da0b8ece7a717dc5e08957ed/lib/mergeset/table.go#L697

this function do so much useless works:
1. convert 15 inmemoryBlock to inmemoryPart: sort Items, marshalData, zstd compress
2. alloc 15 blockStreamReader for 15 inmemoryPart, and decode MetaindexRow
3. read 15 inmemoryPart data, convert to inmemoryBlock 

I think we can add a new function to merge inmemoryBlock  directly.

thanks.

**Comment by valyala** [comment]
@ahfuzhang , thanks for the pointer! The `mergeInmemoryBlocks` function has been optimized in the commit de6dd1cd5a69af41428ca3efda5aef43d3dd6ea3 . This commit removes unnecessary conversion from inmemoryBlock to inmemoryPart and back to inmemoryBlock for the input inmemory blocks. This commit will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics improve the performance for adding new entries into `indexdb` starting from [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
