### ISSUE TITLE
Vector.dev support in victoria metrics (or the opposite)

### ISSUE THREAD

**Issue by TomGudman** [VictoriaMetrics/VictoriaMetrics#2253]
[Vector.dev](https://www.vector.dev) is a log shipper and metrics broker. It has a nice and extensive lists of sources and sinks. I believe it's the next tool that everyone will use in logs land for a while and also the fact it can carry metrics is a nice plus. It allows us to have one single tool in our infrastructure to carry logs and metrics to destination.

**Describe the solution you'd like**
Vector.dev has support for [prometheus remote write](https://vector.dev/docs/reference/configuration/sinks/prometheus_remote_write/) however it does not seem to work with Victoria Metrics. I am unsure if it's a bug on the vector.dev or victoriametrics side but it seems incompatible at this point in time.

**Describe alternatives you've considered**
After exposing my challenge, @denisgolius recommended vmagent in place of vector.dev which obviously work and was overall quite easy to use but having victoria metrics as a sink in vector.dev would be nice and would also increase VM expose to the world. (Note that vector.dev was built timber.io now owned by Datadog - dunno if there is a commercial conflict there :) 

**Additional context**
I like vector.dev due to its transforms features and multiple sources and sinks. I am not related to any company, I am simply a user who would like vector.dev and VictoriaMetrics to work together ;)

I tried the following config without any luck

```[sources.prometheus_relay]
  type = "prometheus_remote_write"
  address = "0.0.0.0:8685"
  tls.enabled = true
  tls.key_file = "/etc/vector/ssl/vector.key"
  tls.crt_file = "/etc/vector/ssl/vector.crt"
  tls.ca_file  = "/etc/vector/ssl/vector-cachain.pem"

# Centralise all metrics into victoria-metrics
[sinks.prometheus_central]
  type = "prometheus_remote_write"
  inputs = [ "prometheus_relay" ]
  endpoint = "http://victoriametrics-elb-e7f1470da0f3190c.elb.ap-southeast-2.amazonaws.com:8428/api/v1/write"
```
_Vector logs (0.19.2)_
```
Feb 26 07:58:31 ip-10-10-16-226 vector[63796]: 2022-02-26T07:58:31.885296Z ERROR vector::topology::builder: msg="Healthcheck: Failed Reason." error=Unexpected status: 400 Bad Request component_kind="sink" component_type="prometheus_remote_write" component_id=prometheus_central component_name=prometheus_central
```

_Victoria Metrics logs (docker-compose git tag v1.73.1)_
```
2022-02-26T07:58:28.416Z	warn	VictoriaMetrics/app/vminsert/main.go:108	remoteAddr: "10.10.16.136:10506"; requestURI: /api/v1/write; cannot decompress request with length 0: snappy: corrupt input
```
Once again I am unsure if that's a bug on either side or if it's simply a missing feature. I leave that to the experts.

Thanks for your work on VM, I am only at the beginning but it does seem really nice. Lots of thoughts have been put in!

**Comment by f41gh7** [comment]
Current error is related with vector health check mechanism, you can disable health check or setup correct url for it:

```toml
[sinks.prometheus_central]
healthcheck = false
```

https://vector.dev/docs/reference/configuration/sinks/http/#healthcheck.uri

**Comment by zamazan4ik** [comment]
@f41gh7 by the way, could you share please, what is the right way to check the VictoriaMetrics health? Which endpoint shall be used?

**Comment by denisgolius** [comment]
> @f41gh7 by the way, could you please share, what is the right way to check the VictoriaMetrics health? Which endpoint shall be used?

Hi @zamazan4ik ! You can use `/-/healthy` and `/-/ready` path see examples below:

```console
curl 127.0.0.1:8428/-/healthy
VictoriaMetrics is Healthy.
```
```console
curl 127.0.0.1:8428/-/ready
VictoriaMetrics is Ready.

```
