### ISSUE TITLE
How to get the time it takes for vmalert to scan for alarm rules per round?

### ISSUE THREAD

**Issue by Fanduzi** [VictoriaMetrics/VictoriaMetrics#2257]
For a number of reasons, we have 1W+ alert rules. I would like to know if there is a bottleneck due to too many alert rules.  If I have another 10W, 100W alert rules, how long will it take to poll each round? Is there anywhere to see this polling time?
![image](https://user-images.githubusercontent.com/24428128/155919925-fdd29c60-3dce-40b4-9af6-c94d34290890.png)
Similar to the evaluation time in the chart above

**Comment by hagen1778** [comment]
Hi! There is no info about evaluation duration of each rule. But there is a histogram metric for group's evaluation duration `vmalert_iteration_duration_seconds`. You can use it plot avg duration via the following query:
```
sum(rate(vmalert_iteration_duration_seconds_sum{group=~"$group"}[$__rate_interval])) by(group) / 
sum(rate(vmalert_iteration_duration_seconds_count{ group=~"$group"}[$__rate_interval])) by(group)
```
^please note, https://grafana.com/grafana/dashboards/14950 already contains this panel.

You can also plot percentiles for that metric.

It is also possible to add EvaluationTime display in vmalert's UI. Let me know if that is needed.

**Comment by Fanduzi** [comment]
> Hi! There is no info about evaluation duration of each rule. But there is a histogram metric for group's evaluation duration `vmalert_iteration_duration_seconds`. You can use it plot avg duration via the following query:
> 
> ```
> sum(rate(vmalert_iteration_duration_seconds_sum{group=~"$group"}[$__rate_interval])) by(group) / 
> sum(rate(vmalert_iteration_duration_seconds_count{ group=~"$group"}[$__rate_interval])) by(group)
> ```
> 
> ^please note, https://grafana.com/grafana/dashboards/14950 already contains this panel.
> 
> You can also plot percentiles for that metric.
> 
> It is also possible to add EvaluationTime display in vmalert's UI. Let me know if that is needed.

thank you!
