### ISSUE TITLE
indexdb is consuming more storage . if we delete that index folder (since we do need want to old data), will VM recreate fresh one ?"

### ISSUE THREAD

**Issue by SrijalKarmacharya** [VictoriaMetrics/VictoriaMetrics#2258]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ahfuzhang** [comment]
I know something from source code:
see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/59877d9f32a0259cdaefce7152afa9104e65be94/lib/storage/storage.go#L644

by default, each indexDB life time is 31 days, aka the retention time.
every storage object have two indexDB object, current and prev. so you can search metric data most 62 days.
new indexDB will create every 31 days.
delete recent 2 indexDB folder might be dangerous.

**Comment by f41gh7** [comment]
If indexdb consuming much more disk space, then data folder, you have high churn rate at your metrics.

 Removing indexdb folder will lead to data loss, this folder is used for metric names search operations. 

 I can suggest you to try following options:
1) decrease retentionPeriod. As @ahfuzhang mentioned, with 1 month retention, indexdb folder will be rotated after 2 months.
2) setup multi retention cluster. Write importnant low-cardinality metrics to the long-term storage  and high cardinality metrics into short-term storage with small retentionPeriod.


  https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate

 https://docs.victoriametrics.com/guides/guide-vmcluster-multiple-retention-setup.html

**Comment by SrijalK** [comment]
Thanks for the response . I have decreased the retention period but got no leads on how to decrease the churn rate.
I have also gone through the several documentations. It would be very helpful, if you could help me on decreasing churn rate too.

**Comment by jiekun** [comment]
> if you could help me on decreasing churn rate too

I think it's a different topic and may need more info of your dataset. Closing this issue as answered now.
