### ISSUE TITLE
Building 1.73.1 in openBSD  - /vendor/embed missing ref since 1.63.0

### ISSUE THREAD

**Issue by dohnuts** [VictoriaMetrics/VictoriaMetrics#2265]
I saw the openBSD ports in the OS tree and try to build it.

```
build github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics: cannot load embed: open /usr/ports/pobj/victoriam
etrics-1.73.1/go/src/github.com/VictoriaMetrics/VictoriaMetrics/vendor/embed: no such file or directory
gmake[1]: *** [Makefile:267: app-local-pure] Error 1
gmake[1]: Leaving directory '/usr/ports/pobj/victoriametrics-1.73.1/go/src/github.com/VictoriaMetrics/VictoriaMetrics'
gmake: *** [app/victoria-metrics/Makefile:83: victoria-metrics-pure] Error 2
*** Error 2 in . (Makefile:33 'do-build')
```

Could be a slight mistake in the build process ?

**v1.62.0  does not have this error but v1.63.0**

Stay safe.

**Comment by f41gh7** [comment]
Which version of golang at your host system? 

 It's recommended to use the latest version - 1.17 or 1.16 at least.

 Error related to the new golang feature - embed.fs, that was introduced at 1.16 golang release.

**Comment by dohnuts** [comment]
# go version
go version go1.17.5 openbsd/amd64

Note that v1.62.0 is building bur required a new go


i have a few embed file but not a FS one in my package

/usr/local/go/pkg/openbsd_amd64/embed.a
/usr/local/go/src/cmd/compile/internal/staticdata/embed.go
/usr/local/go/src/cmd/go/testdata/script/embed.txt
/usr/local/go/src/embed/embed.go
/usr/local/go/src/embed/internal/embedtest/concurrency.txt
/usr/local/go/src/embed/internal/embedtest/embed_test.go
/usr/local/go/src/embed/internal/embedtest/embedx_test.go
/usr/local/go/src/embed/internal/embedtest/testdata/-not-hidden/fortune.txt
/usr/local/go/src/embed/internal/embedtest/testdata/.hidden/.more/tip.txt
/usr/local/go/src/embed/internal/embedtest/testdata/.hidden/_more/tip.txt
/usr/local/go/src/embed/internal/embedtest/testdata/.hidden/fortune.txt
/usr/local/go/src/embed/internal/embedtest/testdata/.hidden/more/tip.txt
/usr/local/go/src/embed/internal/embedtest/testdata/_hidden/fortune.txt
/usr/local/go/src/embed/internal/embedtest/testdata/ascii.txt
/usr/local/go/src/embed/internal/embedtest/testdata/glass.txt
/usr/local/go/src/embed/internal/embedtest/testdata/hello.txt
/usr/local/go/src/embed/internal/embedtest/testdata/i/i18n.txt
/usr/local/go/src/embed/internal/embedtest/testdata/i/j/k/k8s.txt
/usr/local/go/src/embed/internal/embedtest/testdata/ken.txt
/usr/local/go/src/time/embed.go
/usr/local/go/test/interface/embed.go
/usr/local/go/test/ken/embed.go

do you know how i can test this specifically ?

**Comment by dohnuts** [comment]
Ok new env var that are mandatory to build are:
BUILDINFO_TAG=openbsd PKG_TAG=openbsd

'Question' solved
