### ISSUE TITLE
Make documentation friendlier to non-Prometheus users

### ISSUE THREAD

**Issue by tredondo** [VictoriaMetrics/VictoriaMetrics#2267]
**Is your feature request related to a problem? Please describe.**
While searching for an alternative to InfluxDB for storing financial data, I found VictoriaMetrics. I've never used Prometheus, but the documentation refers to it heavily, which makes it hard to understand what exactly VM does (maybe it's [not](https://docs.victoriametrics.com/FAQ.html#what-is-the-main-purpose-of-victoriametrics) a good solution for financial data after all?). The README includes a lot of low-level technical details, and after spending a couple hours reading https://docs.victoriametrics.com, I'm still unclear on the key concepts. For users who've never used a TSDB, VictoriaMetrics may be even harder to understand.

Does VM deserve a place as a standalone TSDB, not just as a drop-in replacement for Prometheus or InfluxDB?

**Describe the solution you'd like**
A nice, clear, introduction to users new to TSDBs, similar to the InfluxDB one, which doesn't assume knowledge of any particular TSDB. InfluxDB has an easy-to-grasp documentation, which enabled me to get started quickly:

https://docs.influxdata.com/influxdb/v1.8/introduction/get-started/.

Also, its [key concepts](https://docs.influxdata.com/influxdb/v1.8/concepts/key_concepts/) page was super useful. Explaining or linking to some terms _considered_ known would be great. For example, I've been using Influx for years but the VM docs were the first time I ever saw terms like "helm charts" and "[scraping](https://prometheus.io/docs/introduction/overview/#architecture)", and they weren't explained.

**Describe alternatives you've considered**
Look around for random blogs introducing VictoriaMetrics?

**Comment by denisgolius** [comment]
Hi @tredondo !
Thanks for your request!

You can do it by sending us a PR with your suggestions. There is an app directory path https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app where you can find source code and documentation of VM utils or services. For example in https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmagent you will find **README.md** which is used for https://docs.victoriametrics.com/vmagent.html.

**Comment by tredondo** [comment]
Hi @denisgolius. Thanks for the links. They don't really clear up what the VictoriaMetrics concepts are, and while I'd be happy to submit PRs, I have no idea what to write in them. That's the problem.

Try putting yourself into the shoes of a user who's new to TSDBs. Or who's maybe used Influx, but not Prometheus, Kafka, Grafana and all other stuff. What's the starting point for such a user to understand VM?

I've read the [PromQL tutorial _for beginners_](https://valyala.medium.com/promql-tutorial-for-beginners-9ab455142085) and it's like building a house of cards in thin air, without a foundation. A lot of concepts aren't explained: label, metric, rate, gauge, counter etc.

The style is generally abrupt, making a lot of assumptions. For example,

> For instance, the following query would return all the time series with [the] name `node_network_receive_bytes_total`:
>
>     node_network_receive_bytes_total
>
> This name corresponds to [node_exporter metric](https://github.com/prometheus/node_exporter) containing the number of bytes received over the various network interfaces.

Took me several reads and clicks on links to understand what that means. Here's how I would start to rewrite it without necessitating prior knowledge from the user:

> For instance, let's consider a time series consisting of the number of bytes received over the various network interfaces of a machine. As a practical example, the tool [node_exporter metric](https://github.com/prometheus/node_exporter) will collect this metric on *NIX in a time series called `node_network_receive_bytes_total`. ...

I stopped because at that point, the user needs to know what a "label" is, which hasn't been explained yet, despite the tutorial being aimed at beginners (beginners in which technology?), and I haven't yet managed to understand what exactly a label is, though this is probably very simple, just not mentioned yet.

The problem with assumptions is that they lead to tortuous sections. For example, "Careful readers could notice that [Grafana](http://docs.grafana.org/features/datasources/prometheus/) draws constantly growing lines for all the queries above". This wouldn't be necessary if the article explained the concept of a counter first, and how it's always increasing.

What I think would help illustrate these concepts:
- an example data set that doesn't require any prior knowledge of tools like node_exporter. The InfluxDB docs does this very easily and naturally in their [sample data](https://docs.influxdata.com/influxdb/v1.8/concepts/key_concepts/#sample-data) section. A TSDB beginner probably knows the high-level concepts of fields, values, tags and so on but it's important to clarify their names, because various TSDB tools have different names for them, and the concepts *are* overlapping sufficiently that questions like "What is the difference between fields and values and tags" [still](https://dba.stackexchange.com/questions/163292/understanding-how-to-choose-between-fields-and-tags-in-influxdb) get [asked](https://stackoverflow.com/questions/54550715/telegraf-whats-the-difference-between-a-field-and-a-tag-in-a-metric). Clear documentation would clarify that, but I haven't found it yet for VictoriaMetrics.
- a list of knowledge/prerequisites required before reading the tutorial (e.g. "good to have some experience with Grafana")
- having someone new to TSDBs go through the tutorial and confirm that now they understand the concepts of VictoriaMetrics. While I'm not new to TSDBs, I can pt myself in a beginner's shoes, so I volunteer to go through such a tutorial.

**Comment by Recodify** [comment]
I found this issue due to the exact same problem. My google search was "victoriametrics for non prometheus". I am exploring VM as a way to store readings from IOT sensors and not for monitoring infrastructure (although I may use it for that also) and it's very hard finding a good starting point from which to start exploring that doesn't assume VM is being used as a data store for prometheus.

**Comment by hagen1778** [comment]
@tredondo @Recodify I'd appreciate your feedback on https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2572

**Comment by hagen1778** [comment]
@tredondo @Recodify please see https://docs.victoriametrics.com/keyConcepts.html
Any additions or feedback is welcomed

**Comment by valyala** [comment]
See also https://docs.victoriametrics.com/guides/migrate-from-influx/ - this guide may be useful for those who migrates from InfluxDB to VictoriaMetrics.
