### ISSUE TITLE
Clarify what the default data ingestion protocol is

### ISSUE THREAD

**Issue by tredondo** [VictoriaMetrics/VictoriaMetrics#2268]
**Is your feature request related to a problem? Please describe.**
I'm new to VM, trying to figure out how to use VictoriaMetrics as a drop-in replacement for InfluxDB. I've read the [How to import...](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-import-time-series-data) section.

For InfluxDB, https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf says that Telegraph can simply use the VictoriaMetrics URL, http://127.0.0.1:8428/. So I take it that the default data ingestion protocol of VM is the [Influx line protocol](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/) and any [InfluxDB client library](https://docs.influxdata.com/influxdb/v1.8/tools/api_client_libraries/) should work if pointed to that URL, just as it did when it was pointed to the InfluxDB [instance](https://docs.influxdata.com/influxdb/v1.8/administration/ports/#8086)?

But then the documentation goes on,

> Another option is to enable TCP and UDP receiver for InfluxDB line protocol via `-influxListenAddr` command-line flag and stream plain InfluxDB line protocol data to the configured TCP and/or UDP addresses.

How is this option different and useful, if simply pointing Telegraph to the VictoriaMetrics URL would work?

The CLI help further confuses things:

> -influxListenAddr string
>        TCP and UDP address to listen for InfluxDB line protocol data. Usually :8189 must be set. Doesn't work if empty. **This flag isn't needed when ingesting data over HTTP - just send it to http://<victoriametrics>:8428/write**

**Describe the solution you'd like**
- [ ] clarify what the various ingestion formats, ports and API endpoints are, and the differences between streaming and non-streaming (?)
- [ ] list Victoria Metrics client libraries for various languages (or explain there are none, and what to use instead). https://github.com/VictoriaMetrics/VictoriaMetric doesn't say anything about client libraries.

**Additional context**
#2267

**Comment by YuriKravetc** [comment]
Hi,

Influx line protocol is not a default one for VM. It will understand the protocol from the header in HTTP request in example of Telegraph. Influx line is transformed to Prometheus datapoints.

The difference and usefulness lies in UDP\TCP protocol. In first case, you are using HTTP protocol by indicating the url.

You can find more information on ingestion formats and api endpoints here:
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html?highlight=multi-level#url-format
https://docs.victoriametrics.com/victoriametrics/integrations/influxdb/#influxdb-compatible-agents-such-as-telegraf


As for client libraries, pretty much the same as Prometheus, though Go is the most preferred:
https://prometheus.io/docs/instrumenting/clientlibs/

**Comment by jiekun** [comment]
Closed as answered. Thanks for your comment @YuriKravetc
