### ISSUE TITLE
vmagent Kafka integration doesn't work on Arm-based machines

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#2271]
**Describe the bug**
Running vmagent (latest version v1.73.1 Enterprise), the image shows support for arm based systems (t4g.medium on AWS for example) but when trying to run it as a kafka consumer the following issue appears:
```
{"ts":"2022-03-02T07:39:20.910Z","level":"fatal","caller":"VictoriaMetrics/app/vmagent/kafka/consumer.go:38","msg":"cannot init kafka clients: kafka client is not supported at systems without CGO"}
```

**To Reproduce**
Deploy vmagent helm chart with the following params:
"remoteWrite.multitenantURL": "kafka://url-to-kafka/?topic=topic-name&security.protocol=SASL_SSL&sasl.mechanisms=PLAIN",
"remoteWrite.basicAuth.username": "username",
"remoteWrite.basicAuth.password": "password",

**Expected behavior**
The image shows support for arm, then the Kafka integration should also support this.

**Logs**
Full logs (credentials and urls removed for security)
```
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:12","msg":"build version: vmagent-20220222-194544-tags-v1.73.1-enterprise-0-ge05d83a8d"}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:13","msg":"command line flags"}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"envflag.enable\"=\"true\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"envflag.prefix\"=\"VM_\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"eula\"=\"true\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"kafka.consumer.topic\"=\"kafka-topic\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"kafka.consumer.topic.basicAuth.password\"=\"secret\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"kafka.consumer.topic.basicAuth.username\"=\"username\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"kafka.consumer.topic.brokers\"=\"kafka-url\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"kafka.consumer.topic.groupID\"=\"test\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"kafka.consumer.topic.options\"=\"security.protocol=SASL_SSL;sasl.mechanisms=PLAIN\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"loggerFormat\"=\"json\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"promscrape.config\"=\"/config/scrape.yml\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"remoteWrite.multitenantURL\"=\"http://vminsert:8480\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/lib/logger/flag.go:20","msg":"flag \"remoteWrite.tmpDataPath\"=\"/tmpData\""}
{"ts":"2022-03-02T07:39:20.910Z","level":"info","caller":"VictoriaMetrics/app/vmagent/main.go:94","msg":"starting vmagent at \":8429\"..."}
{"ts":"2022-03-02T07:39:20.910Z","level":"fatal","caller":"VictoriaMetrics/app/vmagent/kafka/consumer.go:38","msg":"cannot init kafka clients: kafka client is not supported at systems without CGO"}
```

Changing the node type to t3.medium which is not Arm, made the vmagent work, but we are mostly using arm based systems and would be happy to continue using arm for vmagent as well.

Hope you are all right in Kyiv! Stay strong! ❤️

**Comment by f41gh7** [comment]
Hello, kafka at arm bases systems is not supported for now. We are working on port. Currently, i don't have ETA for it.
 
 vmagent uses https://github.com/confluentinc/confluent-kafka-go

**Comment by valyala** [comment]
@Alon-Katz , could you try running `vmagent` from the attached tar.gz archive? It is built from the commit, which adds support [Kafka integration](https://docs.victoriametrics.com/vmagent.html#kafka-integration) on `arm64` architecture. This commit will be included in the next release if everything is OK with it.

[vmagent-linux-arm64.tar.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10984296/vmagent-linux-arm64.tar.gz)

**Comment by valyala** [comment]
[Kafka integration](https://docs.victoriametrics.com/vmagent.html#kafka-integration) at `vmagent` should work on arm-based machines starting from [v1.90.0 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as resolved.

@Alon-Katz , feel free re-opening the issue if you experience problems related to Kafka integration with `vmagent v1.90.0`
