### ISSUE TITLE
Utilization of cache with promxy

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#2280]
We have two instance of VictoriaMetrics deployed and querying them with promxy.
We have to enforce `no_cache=1` for this to work.

Is there a solution where we can query those 2 instance with promxy and took advantage of the cache offer by Victoria ?

**Comment by hagen1778** [comment]
Hi @xenofree! I'm afraid there is no a workaround. However, here's what I think:
* the promxy caching is similar to what VM does, so while you have caching enabled somewhere - it should be fine
* if you want to query one of the VM directly, you can enable caching via GET param for such requests. For example, in Grafana you can have Promxy datasource and two separate datasources for each VM with caching enabled.

We had some plans to implement VM proxy or extend vmselect functionality for this purpose, but we have no ETA for this.
