### ISSUE TITLE
vmagent relabelDebug: seems not to skip metrics

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#2289]
Wondering, why vmagent still tries to send data to the server even so all metrics are flagged with metric_relabel_debug: E.g.:
file: `/tmp/promscrape.json`
```
{
	"global": {
		"scrape_interval": "15s",
		"external_labels": { "gz": "q" }
	},
	"scrape_config_files": [ "test_*.json" ]
}
```
file: `/tmp/test_vmagent.json`
```
[{
	"job_name": "vmagent",
	"scrape_interval": "60s",
	"scrape_timeout": "25s",
	"static_configs": [{ "targets": [ "localhost:8429" ] }],
	"metric_relabel_debug": true,
	"metric_relabel_configs": [{
		"action": "drop",
		"source_labels": [ "__name__" ],
		"regex": "vm_log_messages_total|.*_discovery.*|flag"
	},{
		"action": "drop",
		"source_labels": [ "type" ],
		"regex": "(datadog|graphite|influx|opentsdb.*)|(consul|digitalocean|dns|docker|dockerswarm|ec2|eureka|gce|http|kubernetes|openstack)_sd_configs"
	},{
		"action": "labeldrop",
		"regex": "instance"
	}]
}]
```

And the startup script, e.g. `/tmp/run.sh`
```
#!/bin/ksh93

DATA_DIR='/var/tmp/vmagent'
CFG_DIR="/tmp"
DB_HOST=example.com

export GOMAXPROCS=2
ARGS=(
	#'--promscrape.suppressScrapeErrors'
	'--remoteWrite.flushInterval=5s'
	'--httpListenAddr=127.0.0.1:8429'
	"--promscrape.config=${CFG_DIR}/promscrape.json"
	'--promscrape.disableKeepAlive=false'
	'--promscrape.disableCompression'

	"--remoteWrite.url=http://${DBHOST}:8428/api/v1/write"
	"--remoteWrite.tmpDataPath=${DATA_DIR}"
)

/usr/sbin/vmagent "${ARGS[@]}"
```

If you block via firewall connections to the server, you'll see:
```
2022-03-08T02:46:57.631Z	warn	VictoriaMetrics/app/vmagent/remotewrite/client.go:277	couldn't send a block with size 275 bytes to "1:secret-url": Post "http://:8428/api/v1/write": dial tcp4 :8428: connect: connection refused; re-sending the block in 60.000 seconds
2022-03-08T02:46:57.631Z	warn	VictoriaMetrics/app/vmagent/remotewrite/client.go:277	couldn't send a block with size 278 bytes to "1:secret-url": Post "http://:8428/api/v1/write": dial tcp4 :8428: connect: connection refused; re-sending the block in 60.000 seconds
```

Because of relabel debugging is active for all metrics, it shouldn't send anything to the server. Bug or did I miss something?

**Comment by dmitryk-dk** [comment]
Hi @jelmd ! Thank you for your report. I have investigated the problem and what could happen with vmalert process.
1. When you stopped vmalert and it didn't send info to database it created folder named persistent-queue
2. When you restart vmalert and add flag `--remoteWrite.relabelDebug=true` it will try to send this unsent data to database

If you delete the folder and run vmalert like in the example below, the bug won't be reproduced
```./vmagent --promscrape.suppressScrapeErrors --remoteWrite.flushInterval=5s --httpListenAddr=127.0.0.1:8429 --promscrape.config=../app/vmagent/scrape.yaml --promscrape.disableKeepAlive=false --promscrape.disableCompression --remoteWrite.url=http://localhost:8428/api/v1/write --remoteWrite.relabelDebug=true```

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to re-open if the problem still exists.
