### ISSUE TITLE
no need to copy data when use mmap

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2291]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ef1afeed6c2bd427aee92d15e78c1330926b5af2/lib/fs/reader_at.go#L57

most times, it will use zstd decompress after read mmap buffer data.
so I think it is ok to use mmap address directly, not need to use copy.

**Comment by denisgolius** [comment]
@f41gh7 @hagen1778 folks could you take a look?

**Comment by f41gh7** [comment]
In-deeded, there are places where mmap buffer data can be borrowed. 

 I think, new method for reader must be introduced MustReadAtBorrow()([]byte,error). Caller must use returned value straight after call and do not modify it.

**Comment by f41gh7** [comment]
Thanks for your suggestion! We decided do not use such optimization, it didn't show practical benefits and it may lead to various bugs with memory ownership.
