### ISSUE TITLE
Some confusion about the performance of new time series data write scenarios

### ISSUE THREAD

**Issue by Sisphyus** [VictoriaMetrics/VictoriaMetrics#2292]
Suppose such a scenario.
one vm-storage cluster configured 1 month retentionPeriod and another vm-storage cluster configured 1 year retentionPeriod. The data sources of this two cluster is come from the same prometheus remote write input.
In the case that the tsid cache of both clusters are not full, will the cluster with a longer retentionPeriod be worse than a cluster with a shorter retentionPeriod in the scenario of writing new time series data, and if so, how much difference will there be? ? Where can this conclusion be drawn?

**Comment by hagen1778** [comment]
Hi @Sisphyus!
In scenario of writing and reading time series data both clusters should have the same performance level for the same queries on the same time ranges.

The TSID cache which is heavily utilized during the ingestion will have the same number of entries for the same payload. Its size or number of entries does not depend on the retention. It depends on number of unique series requested/ingested recently. If cache reaches its capacity the older entries will be evicted, so eventually both caches should look the same and have the same hit ratio.

The data in VictoriaMetrics is partitioned by month. It means, that max time range covered by one part can be 1 month. It means that in both cases you described, the minimal number of parts to read will be 1. Unless you request to read, let's say, last 6month of data - in this case cluster with bigger retention will take longer to scan the data.

Please also see these docs https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#storage

**Comment by Sisphyus** [comment]
Thank you very much for your answer, and sorry for adding another question.

When I saw the VictoriaMetrics sources code（our online version is v1.68.0）, I found that if TSID cache hit missing（when When the TSID reaches its capacity, it will be more frequent）, fast insert will turn to slow Insert, and try at most 100 times to get TSID by metric name from disk, then create it if always can't find the TSID. So is the factor that most affects ingestion rate is the number of new time series data per unit time?

To try to avoid this situation whether it is necessary to hold as large a memory resource as possible?

**Comment by hagen1778** [comment]
>  So is the factor that most affects ingestion rate is the number of new time series data per unit time?

That's correct. If you ingest the same data into two different VMs with different retention - both should have the same TSID cache size and hit ratio.

**Comment by Sisphyus** [comment]
Thanks!
