### ISSUE TITLE
Grafana 8.1.0 with VictoriaMetrics 1.72.0 help

### ISSUE THREAD

**Issue by kochoudh** [VictoriaMetrics/VictoriaMetrics#2301]
Hello Team,

I need information regarding the compatibility of Grafana 8.1.0 with VictoriaMetrics 1.72.0. I have upgraded Grafana 8.1.0 with VM 1.72.0, however I am not sure of any compatibility issues and was not able to find it anywhere.

Can someone please guide me here. 

Regards,
Komal

**Comment by denisgolius** [comment]
Hi @kochoudh !
It is hard to say which one version of Grafana is supported by VM v1.72.0 . Check the history of this line in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/victoriametrics.json#L8 . It contains the version of Grafana that was used to export dashboard. As I see v1.72.0 of VM was released in Janary, so exported version of the dashboard on released date must contains supported version of Grafana. If you want to find any other supported versions you need to check by yourself.

**Comment by kochoudh** [comment]
Hi @denisgolius!
Thank you so much for your response, I checked the line (https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/victoriametrics.json#L8 ) and your answer made a lot of sense, also resolved my most of the query. I will further check the compatibility by performing the sample test cases.
Appreciate quick help :)
