### ISSUE TITLE
diff between victoria and prometheus

### ISSUE THREAD

**Issue by alexkayzer** [VictoriaMetrics/VictoriaMetrics#2302]
Hello! i'm using victoriametrics as metrics collector from some cluster k8s. Inside cluster we use Prometheus. Victoria agent scrape metrics from this. And we look diff. Meric
 `histogram_quantile(0.99, rate(etcd_network_peer_round_trip_time_seconds_bucket[1m]))`
Victoria:
![Victoria](https://user-images.githubusercontent.com/53193110/157893006-da2f25cd-4da0-4112-87a8-aba5a03edaf2.png)
Prometheus in cluster:
![Screenshot 2022-03-11 at 18 07 38](https://user-images.githubusercontent.com/53193110/157893681-d684a37f-1029-4323-beb6-0f31754fded1.png)
VMAGENT v 1.64.1 config:
`ARGS= -promscrape.config='/etc/vmagent/vmtarget.yaml' \ 
 -remoteWrite.url='http://localhost:8480/insert/0/prometheus/api/v1/write' \
 -promscrape.configCheckInterval=10m \
 -promscrape.suppressDuplicateScrapeTargetErrors \
 -remoteWrite.tmpDataPath='/var/lib/vmagent-tmp' \
 -promscrape.maxScrapeSize='800MiB'  -promscrape.cluster.replicationFactor=2 \ 
 -promscrape.cluster.membersCount=3 -promscrape.cluster.memberNum=3 `

**Comment by YuriKravetc** [comment]
Hi,

Some differences in behavior might be expected.

Please refer to:
https://docs.victoriametrics.com/FAQ.html#why-do-the-same-metrics-have-differences-in-victoriametrics-and-prometheus-dashboards
https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350

**Comment by jiekun** [comment]
Closed as answered. Feel free to reopen it if you have more questions on this topic.
