### ISSUE TITLE
Whether paging query data is supported？Whether to support conditional query of total quantity？

### ISSUE THREAD

**Issue by kervin521** [VictoriaMetrics/VictoriaMetrics#2316]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hagen1778** [comment]
Hi @kervin521! The paging is not supported out of the box. However, please see [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function which would allow to implement the paging on your own.

**Comment by hagen1778** [comment]
Closed as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2467
