### ISSUE TITLE
ask a question: why indexdb.tagFiltersCache not set expires time?

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2319]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0fa7effc4bc14929b0df7e4fd5ed72f780c66493/lib/storage/index_db.go#L100

after index search, `TagFilters -> TSIDs` will store in fastcache.
but there will be a promblem: new metric which match the TagFilters will not add to TSIDs.
query result might be wrong.

I think there are two way to fix:
1.after get tsids from cache, and check recent new tsid whether match the TagFilters;
2. set a expires time to `TagFilters -> TSIDs`  cache.

thanks.

**Comment by f41gh7** [comment]
tagFilters cache invalidated when new metrics added by version counter `tagFiltersKeyGen`

Invalidation function `invalidateTagFiltersCache` https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/index_db.go#L415

**Comment by ahfuzhang** [comment]
> tagFilters cache invalidated when new metrics added by version counter `tagFiltersKeyGen`
> 
> Invalidation function `invalidateTagFiltersCache` https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/index_db.go#L415

thanks, I see now.

**Comment by ahfuzhang** [comment]
thanks again
