### ISSUE TITLE
ask a question：victoriametrics single-node how to avoid single point of failure?

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#2321]
victoriametrics single-node How to avoid single point of failure?

**Comment by ahfuzhang** [comment]
我觉得单个节点明显无法达到高可用。
单机版我觉得可以这样来提高可用性：
1.vm-agent设定复制因子为2；
2.vm-agent抓取数据后，把数据发到两个单机节点。
   这样的话，一个节点挂了，还有另一个。

**Comment by Shangchengzhi** [comment]
> 我觉得单个节点明显无法达到高可用。 单机版我觉得可以这样来提高可用性： 1.vm-agent设定复制因子为2； 2.vm-agent抓取数据后，把数据发到两个单机节点。 这样的话，一个节点挂了，还有另一个。

但是单机版不是可以已经pull Target了吗，还需要上vmagent吗？

**Comment by ahfuzhang** [comment]
两个单机版节点，抓取同样的target，也是相当于复制了。

总而言之，使用副本来提升可用性。

**Comment by hagen1778** [comment]
Hi @Shangchengzhi! Please see the following page - https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#high-availability

**Comment by jiekun** [comment]
Closed as answered. Feel free to reopen it if you have more questions on this topic.
