### ISSUE TITLE
vmctl returns 0 error code when flags validation fails

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2322]
**Describe the bug**
vmctl returns 0 error code when flags validation fails

**To Reproduce**
Run vmctl with incorrect time params

**Expected behavior**
vmctl should return non-zero error code if validation or subcommand fails 

**Version**
1.74.0

**Comment by valyala** [comment]
`vmctl` should return non-zero exit code on errors starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
