### ISSUE TITLE
vmagent block when a big size Timeseries

### ISSUE THREAD

**Issue by bleedfish** [VictoriaMetrics/VictoriaMetrics#2335]
**Describe the bug**
   file:   app/vmagent/remotewrite/pendingseries.go
   function:  pushWriteRequest
   vmagent  call pushBlock to write data.  but in the condition 
             ` if len(bb.B) >  maxUnpackedBlockSize.N  and len(wr.Timeseries) == 1`
  Timeseries cannot split any more. 
   it may endless loops and block the data send.  finally block the target scrape.

**To Reproduce**
        by default maxUnpackedBlockSize is 8M. 
       1. make an instance exporter ( a single series with very big size ,  should granter than maxUnpackedBlockSize  ).  
       2.  vmagent make static_configs  to Scrape the instance
      

**Expected behavior**
         Timeseries  with  too big size may be dropped.

**Used command-line flags**
![image](https://user-images.githubusercontent.com/3396080/158936615-b0cea74b-3172-4d67-811d-77d5e033c4b2.png)

**Comment by valyala** [comment]
@bleedfish , thanks for the bugreport and the proposed fix! The issue should be fixed in the commit ec03dec72d2e9164bc380b632f5044d89da61674 , which will be included in the next release.

**Comment by valyala** [comment]
The proposed fix has been included in [vmagent v1.75.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
