### ISSUE TITLE
Create ppc64le Build of VictoriaMetrics

### ISSUE THREAD

**Issue by nickmy9729** [VictoriaMetrics/VictoriaMetrics#235]
Could you please create a ppc64le version of VictoriaMetrics?

GOOS=linux  GOARCH=ppc64le

**Comment by valyala** [comment]
Added ability to build for `GOARCH=ppc64le` in the commit c56b9ed03bdd79b58a5ac9a8cd29cbae200f4be3 . Now the build can be made via `make victoria-metrics-ppc64le` for dev or `make victoria-metrics-ppc64le-prod` for prod.

**Comment by nickmy9729** [comment]
Thanks!

**Comment by valyala** [comment]
FYI, `victoria-metrics-ppc64le` and `victoria-metrics-ppc64le-prod` targets are available starting from [v1.29.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release.

**Comment by valyala** [comment]
FYI, ppc64le builds are automatically included in VictoriaMetrics docker images starting from [v1.31.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
