### ISSUE TITLE
Wrong percent storage usage in grafana

### ISSUE THREAD

**Issue by vitalvas** [VictoriaMetrics/VictoriaMetrics#2350]
**Describe the bug**
Dashboard in grafana shows unrealistic figures for used disk space.

**To Reproduce**
Mount `vmstorage-data` path to amazon efs.

**Expected behavior**
The percentage of used space is less than 1%

**Logs**
No any warnings or errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/571747/159277202-7bde1a58-fc9c-4dd4-8c00-66d2cd7e4ff1.png)

**Version**

* Grafana v8.4.4 (fcfb01faeb)
* dashboard version - today installed

```
vmstorage-20220318-181326-tags-v1.75.0-cluster-0-g7e67d61fd
```

**Used command-line flags**
Please provide applied command-line flags used for running VictoriaMetrics and its components.

**Comment by hagen1778** [comment]
Hi @vitalvas!
This panel uses the following expression:
```
sum(vm_data_size_bytes{job=~"$job_storage", instance=~"$instance"}) by(instance) /
(
  sum(vm_free_disk_space_bytes{job=~"$job_storage", instance=~"$instance"}) by(instance) +
  sum(vm_data_size_bytes{job=~"$job_storage", instance=~"$instance"}) by(instance)
)
```

Could you please plot the following two queries separately and attach the screenshots:
* sum(vm_data_size_bytes{job=~"$job_storage", instance=~"$instance"}) by(instance)
* sum(vm_free_disk_space_bytes{job=~"$job_storage", instance=~"$instance"}) by(instance)

Thanks!

**Comment by vitalvas** [comment]
I think `vm_free_disk_space_bytes` metric is correct.
Amazon EFS (elastic file system/nfs) provide mount with size of 8 exabytes.

**Comment by hagen1778** [comment]
Well, than `(45MB/8191PB)*100` is about `4.98733e-10`% of the disk space used :-)

**Comment by hagen1778** [comment]
Closing the issue for now. Let me know if you have further questions.
