### ISSUE TITLE
Any discussion groups?

### ISSUE THREAD

**Issue by hzw-go** [VictoriaMetrics/VictoriaMetrics#2354]
Just wondering Is there any place to discuss the `VictoriaMetrics`?

**Comment by hagen1778** [comment]
It is likely duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2141

@hzw-go if you're looking for community platforms please see https://docs.victoriametrics.com/#community-and-contributions

**Comment by hzw-go** [comment]
Oh yeah that's what I am looking for
