### ISSUE TITLE
Passing promscrape.cluster.memberNum argument in k8s is not easy as it is of type INT

### ISSUE THREAD

**Issue by venkatbvc** [VictoriaMetrics/VictoriaMetrics#2359]
**Is your feature request related to a problem? Please describe.**

To use cluster feature of vmagent, promscrape.cluster.memberNum argument has to be passed. In k8s, It is difficult to pass this argument unless a wrapper script is written to start the vmagent. But in distroless, we cannot have a wrapper script. 

**Describe the solution you'd like**

In k8s, cluster version can be deployed as statefulset, ${HOSTNAME##*-} gives the oridnal number of the pod. If memberNum parameter can be evaluated from the above expression then it will ease installation in k8s environment. Or read this from a file so that proper number would be generated.

**Describe alternatives you've considered**

**Additional context**

**Comment by hagen1778** [comment]
cc @tenmozes @f41gh7 
is this related to operator/helm-charts repos?

**Comment by valyala** [comment]
`vmagent` accepts statefulset pod names at `-promscrape.cluster.memberNum` command-line flag starting from [v1.76.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). For example, the following command-line flag `-promscrape.cluster.memberNum=vmagent-0` is equivalent to `-promscrape.cluster.memberNum=0`. See [these docs](https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets) for more details.
