### ISSUE TITLE
vmctl add verify-blocks command

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#2362]
**Is your feature request related to a problem? Please describe.**
 By exporting data with native format from vmcluster, it's not possible to check file for correctness, until you upload it to the vminsert.

**Describe the solution you'd like**

 Add `-verify-blocks` command to the `vmctl` command-line, it should accept -`-sourceFile` with path to the file on disk. It should re-use code from https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vminsert/native/request_handler.go#L31

 And print out stats - how many blocks at file, which block is broken. return non-zero exit code on verify failure.

**Comment by valyala** [comment]
vmctl can verify files exported via [native export API](https://docs.victoriametrics.com/#how-to-export-data-in-native-format) starting from [v1.76.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/vmctl.html#verifying-exported-blocks-from-victoriametrics) for details. Closing the feature request as done.
