### ISSUE TITLE
The query interface of vmui is unreasonable

### ISSUE THREAD

**Issue by LeonYanghaha** [VictoriaMetrics/VictoriaMetrics#2365]
When querying metrics in vmui, I have a very strange problem. I don't understand it. When my query type is table, it should be a time point rather than a time interval. Like your vmselect API, the parameters of each API are different, but the query in vmui uses the same API. This should be unreasonable．
｀｀｀
// Query graph
http://ip:port/api/v1/query_range?query=nginx_http_connections&start=1631227899.805&end=1631231499.805&step=14
//Query table
http://ip:port/api/v1/query?query=nginx_http_connections&time=1631239744.377

｀｀｀

**Comment by YuriKravetc** [comment]
Hi,

Can you elaborate on it further please?
Maybe provide some screenshot for visual understanding.

From what seen in examples 
1 - it's a query range so it will feedback all the points from this indicated range and with required step.
2 - the instant query works the same way as prometheus

You can refer to:
https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries
https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries

**Comment by LeonYanghaha** [comment]
This should be my fault. I closed it. sorry.
