### ISSUE TITLE
Error message in v1.75.0 document

### ISSUE THREAD

**Issue by LeonYanghaha** [VictoriaMetrics/VictoriaMetrics#2366]
In the document of VM 1.75.0, there is screenshot information, but in the actual use process, there is no ```/api/v1/groups``` api, but ```/api/v1/rules``` This can easily mislead users.

I added information to the [documents]((https://docs.victoriametrics.com/vmalert.html#web)) and pictures
<img width="1260" alt="WechatIMG6974" src="https://user-images.githubusercontent.com/23301914/160138899-41daa57d-0467-4f75-8f2c-e6992d5867ea.png">

**Comment by LeonYanghaha** [comment]
I should be involved in the development of VM to make it better.

**Comment by hagen1778** [comment]
Hi @LeonYanghaha! Sorry, I can't get the question. Image is not available as well. Could you please elaborate more on this?

**Comment by LeonYanghaha** [comment]
> and

I added information to the [documents and pictures] (https://docs.victoriametrics.com/vmalert.html#web)

**Comment by hagen1778** [comment]
This is now fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2380
Thanks!
