### ISSUE TITLE
Iterating over an entire DB

### ISSUE THREAD

**Issue by oronsh** [VictoriaMetrics/VictoriaMetrics#2367]
Hello, I was wondering if there Is any interface so I can iterate over the entire db like:
1. Iterate over all labels (index_db?) 
2. for each labels get all the samples

**Comment by YuriKravetc** [comment]
Hi,

If you are referring to iteration via some queries:

For the interface you can use inbuilt vmui interface.
You can also use Grafana.

Getting all the samples for each labels is easiest via export API.

You can try to elaborate further on what you are trying to achieve by this iteration to find suitable solution.

Please refer to:
https://docs.victoriametrics.com/#grafana-setup
https://docs.victoriametrics.com/url-examples.html
