### ISSUE TITLE
Disk space usage Panel in grafana dashboard

### ISSUE THREAD

**Issue by ncolboc** [VictoriaMetrics/VictoriaMetrics#2368]
Hello, 
I currently used your grafana dashboard (revision 21) with victoriametric 1.61.1
And I remarked that metrics from panel "disk space usage" (in the first "Stats" row) are filtered with type!="indexdb
`sum(vm_data_size_bytes{job="$job", type!="indexdb"})`
I would like to know why indexdb is not taken into account because on disk, i can see folder "/indexdb" uses disk space.

thanks in advance for your help

**Comment by hagen1778** [comment]
Hi @ncolboc! That's probably a copy-paste typo taken from "storage.Disk space usage" panel (which is represented by two panels: one for data points and second for index). This should be fixed for `stats` row. Thank you for report!

**Comment by valyala** [comment]
This issues should be fixed in the updated [monitoring dashboards for VictoriaMetrics](https://grafana.com/orgs/victoriametrics). @hagen1778 , FYU
