### ISSUE TITLE
Question: Failed to fetch metrics in Grafana [Graphite datasource]

### ISSUE THREAD

**Issue by cjagus** [VictoriaMetrics/VictoriaMetrics#2370]
Server information
```
vminsert - 3(2cpu, 4gb)
vmstrorage - 3(8cpu, 64gb)
vminsert + carbonapi - 2(2cpu, 16gb)
```

VM cluster metrics ( 4 hours of data) 
```
Total Datapoints 3.4 Bil
Index size 450 Mil
Bytes per point 5.5B
Ingestion Rate 180K
```

Command line options: 
```
/usr/bin/vminsert-prod -graphiteListenAddr=:2003 -storageNode=storage-a,storage-b,storage-c
/usr/bin/vmstorage-prod -storageDataPath=/opt/storage -search.maxUniqueTimeseries=100000000
/usr/bin/vmselect-prod -search.maxQueryDuration=60s -storageNode=storage-a,storage-b,storage-c
```

We are trying VM as graphite replacement and use carbon api for Grafana datasource. When trying to fetch top level metrics from Grafna explore UI, it's always timed out. 

```
Mar 25 19:57:20 select-b vmselect[26239]: 2022-03-25T19:57:20.009Z	warn	VictoriaMetrics/app/vmselect/main.go:563	error in "/select/0/prometheus/api/v1/series?match%5B%5D=%7B__name__%3D~%22.%2A%22%7D&start=1648237878": cannot fetch data for "AccountID=0, ProjectID=0, MinTimestamp=2022-03-25 19:51:18 +0000 UTC, MaxTimestamp=2022-03-25 19:56:18 +0000 UTC, TagFilters=[\n{Key=\"\", Value=\".*\", IsNegative: false, IsRegexp: true}\n]": error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage storage-c:8401: request timeout reached: 60.000 seconds (elapsed 62.007 seconds); the timeout can be adjusted with `-search.maxQueryDuration` command-line flag
```

![image](https://user-images.githubusercontent.com/10725765/160190928-89dec548-5d4b-402d-a761-cb6c01ac8559.png)

But this works when we directly Enter full graphite Query, (also noticing timeouts in graphs having too many wildcard globs) 

How do we handle this Victoriametrics cluster, do we nee to tune any settings in Victoriametrics side ?.

**Comment by hagen1778** [comment]
Hi @cjagus! 
The query Grafana sends to VM looks like this `api/v1/series?match[]={__name__=~".*"}` - it matches all existing series for last 5min. Its performance depends on the number of such series present in the database. 
You mentioned `Index size 450 Mil`. But could you please also show how many Active series you have?

**Comment by cjagus** [comment]
Hi @hagen1778 

```
Total Datapoints: 41.3 Bil
Index size: 1.66 Bil
Active Time series: 15 Mil
```

We also route the same metrics via carbon-c-relay to a single node VM cluster, which works just fine, noticing this issue only in clustered version.

**Comment by hagen1778** [comment]
So I believe it tries to return series for `Active Time series: 15 Mil`. 

>  single node VM cluster, which works just fine

How long it takes for single node to process this?

**Comment by cjagus** [comment]
Incase of single node cluster it will process in milli seconds

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/10725765/160842679-26ac729d-9d71-4673-91c0-fc6c89d0890c.png">

**Comment by hagen1778** [comment]
If you don't mind, could you pls execute the same query (which is in log from your initial message) via `curl` against cluster and single version and paste results of latency and amount of received bytes here?
Thanks!

**Comment by cjagus** [comment]
Looks like it's an issue with carbonapi, the way they handle cluster and single node VM(use different API's for find), will raise an issue in Carbonapi. 
Thanks @hagen1778, clossing the issue
