### ISSUE TITLE
vm 1.70.0 can't query data point in a time range

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2385]
I use a python script to send metric data to vm-insert by remote-write protocol.
And when I debug my program, I found I can get right result in a special time range.
(I don't use clb, just use single vm-select to query)
see:
![image](https://user-images.githubusercontent.com/4198375/160775749-869ddff0-6a2a-4dde-b736-c4f480e79ac0.png)

and after noon, the data shows again:
![image](https://user-images.githubusercontent.com/4198375/160775869-87626d21-1a18-49ba-9785-8185c23ca93e.png)

then I change the time range, the result is so strange:
![image](https://user-images.githubusercontent.com/4198375/160778435-aaea4804-d52b-409a-b5d5-7e67d960c4a9.png)

and result is random.

![image](https://user-images.githubusercontent.com/4198375/160778859-c974ae4d-a9b5-4238-ba85-0e6395403d9a.png)

![image](https://user-images.githubusercontent.com/4198375/160778979-ef29d5a6-bb16-48c1-a09e-c36f1013b02d.png)

thanks

**Comment by hagen1778** [comment]
cc @Loori-R

**Comment by hagen1778** [comment]
@ahfuzhang  Is this issue still relevant?

**Comment by hagen1778** [comment]
The vmui has changed significantly since 1.70. I recommend trying to update to newer versions of the VM and checking if the issue still exists.
Looks like this issue wasn't found by other users, so I assume this problem doesn't happen anymore.
