### ISSUE TITLE
Error in Dashboard panel when exemplars button selected

### ISSUE THREAD

**Issue by arramos84** [VictoriaMetrics/VictoriaMetrics#2396]
**Describe the bug**
Dashboards throw error `Cannot use 'in' operator to search for 'exemplars' in undefined` when upgrading after
VictoriaMetrics v1.72.0. Unsure if this is expected, but seems like it shouldn't require a change to all dashboards setting `exemplars: true`

**To Reproduce**
Use newer version of VictoriaMetrics and select exemplars button

**Expected behavior**
No error

**Screenshots**

<img width="788" alt="Screen Shot 2022-04-01 at 9 11 56 PM" src="https://user-images.githubusercontent.com/2239830/161365977-240b0c59-f948-496e-b502-6a7661547d54.png">

<img width="1252" alt="Screen Shot 2022-04-01 at 9 12 08 PM" src="https://user-images.githubusercontent.com/2239830/161365982-47eab8b1-d47b-42bd-ad99-6ac915562601.png">

**Comment by hagen1778** [comment]
Hi @arramos84! I've tried to reproduce it by running latest VM single version and Grafana 8.4.4.
I've created a Prometheus datasource pointing to VM. I've imported https://grafana.com/grafana/dashboards/11176 and didn't get the error you mentioned. I've also created a new dashboard with some custom panels and haven't seen the error. In both cases, I've tried to toggle Exemplars button in the panel.
Please, could you provide the exact step-by-step guide and Grafana version for reproducing this issue?

**Comment by arramos84** [comment]
> https://grafana.com/grafana/dashboards/11176

@hagen1778 , so sorry for the late response! My github filter had an incorrect setting so went straight to "marked as read." We are running grafana 7.4.2 at the moment. We haven't bumped to v8 yet as it will require us to make some custom changes to grafana for using it as iFrames don't seem to work as they did in v7. That being said, it looks like this only shows up with later versions of VM AND if grafana is on `7.4.2`. Grafana `7.5.11` seems to work ok since it looks like the exemplars is not a button, but it detects whether they're available or not.

Grafana `7.4.2`, VM: `v1.75.0`:

<img width="1520" alt="Screen Shot 2022-04-18 at 6 49 39 PM" src="https://user-images.githubusercontent.com/2239830/163904469-1f640dd0-d04f-40fa-9ed8-d747fe4593c0.png">


Grafana `7.5.11`, `v1.75.0`:

<img width="1518" alt="Screen Shot 2022-04-18 at 6 51 03 PM" src="https://user-images.githubusercontent.com/2239830/163904515-7d6325b6-51e0-41ec-84f7-178cd6a35876.png">

I suppose we will just upgrade to grafana `7.5.11`, that should work for us. Appreciate the response! I'm ok with closing it but will leave up to you as there is that compatibility issue.

Thanks!

**Comment by hagen1778** [comment]
Thanks for response! Looks like the issue is caused by exemplars API change. See more details here https://github.com/grafana/grafana/pull/32513
I think, we don't need to tweak VM behaviour here. If there is other opinion, please feel free to reopen the issue.
