### ISSUE TITLE
VMUI - support relative time selectors

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2402]
**Is your feature request related to a problem? Please describe.**
VMUI time picker always sets exect time range at which query would be executed:
<img width="439" alt="image" src="https://user-images.githubusercontent.com/2902918/161695362-b1da4917-e48e-4118-b22c-791be8e9e809.png">

Even when picking relative time option `last 5m` the exact time range would be set. Hence, refreshing the query/page will never result into displaying the new data. This especially useful when using VMUI in order to see when new event would happen.

**Describe the solution you'd like**
Would be great if VMUI's time picker would support relative time options like `last 5m`, `last 30m` instead of exact time value:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2902918/161695942-bd55079f-f5d2-4d7f-bfba-d044af82274b.png">

**Comment by Loori-R** [comment]
Auto-refresh support relative time options.

<img src="https://i.imgur.com/m4uagsL.png"/>

**Comment by hagen1778** [comment]
Yes, I've seen that. Would be great if the same option would be available for the time range picker.

**Comment by valyala** [comment]
@Loori-R , it looks like the selected relative time range is reset to the previous one on the graph when new query is entered. The selected relative time range should stay the same on the graph when new query is entered.

**Comment by valyala** [comment]
There is another bug - when clicking on `Prometheus` line during graph editing in Grafana, vmui doesn't show the graph until explicit click on the `graph` tab. See for, example, https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus//graph?g0.expr=WITH%20(%0A%20%20%20%20commonFilters%20%3D%20%7Bjob%3D%22node-exporter%22%2C%20cluster_retention%3D~%22accounting%22%2C%20cluster_num%3D~%221%22%2C%20service%3D~%22vmstorage%22%2C%20instance%3D~%22.*%3A.%2B%22%7D%2C%0A%20%20%20%20cpuUsage(filter)%20%3D%20rate(node_cpu_seconds_total%7BcommonFilters%2C%20filter%7D)%2C%0A)%0Asum(cpuUsage(%7Bmode!%3D%22idle%22%7D))%20by%20(mode)%20%2F%20sum(cpuUsage(%7B%7D))%20*%20100&g0.range_input=21600s&g0.end_input=2022-05-03%2007%3A39&g0.step_input=30&g0.tab=0

**Comment by valyala** [comment]
FYI, relative time selectors are available in `vmui` starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @Loori-R , the issues mentioned above ([here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115817302) and [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115830648)) still must be fixed.

**Comment by valyala** [comment]
The bugfix for [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115817302) has been included in [v1.77.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

[This issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115830648) still needs to be fixed

**Comment by valyala** [comment]
The [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115830648) has been resolved in [v1.77.2](https://docs.victoriametrics.com/CHANGELOG.html#v1772). Closing the feature request as done.
