### ISSUE TITLE
Using federation to scrap all points in time range

### ISSUE THREAD

**Issue by yangtaoran** [VictoriaMetrics/VictoriaMetrics#2405]
I used federation to scrap all points in time range with start and end params. According to the result of response, I find the result with only latest point data, not all point data between start and end. So what should I do to reach my desired.

**Comment by YuriKravetc** [comment]
Hi,

You can try using api/v1/export to see all points in time range.
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format
https://docs.victoriametrics.com/url-examples.html#apiv1exportnative
