### ISSUE TITLE
vmselect stop unregisterMetric rollupResult metrics

### ISSUE THREAD

**Issue by yangtaoran** [VictoriaMetrics/VictoriaMetrics#2406]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/promql/rollup_result_cache.go#L100
Here, I init vmselect, it will invoke `InitRollupResultCache` method. The method will registry metrics like `vm_cache_entries{type="promql/rollupResult`. Then, I stop vmselect, but the method `StopRollupResultCache` not unregistry the metrics  above.
So, I occured problem.If I init vmselect again, and it will report the metrics had been defined.

**Comment by valyala** [comment]
@yangtaoran , thanks for the pointer to an issue! This was an oversight, because `InitRollupResultCache` function wasn't used in repeated tests. This has been fixed in the commit 61c7f6beaefbb1a13fc39f3e8785b0bcd023eaaa . Closing the issue as fixed.
