### ISSUE TITLE
rollup_increase returns huge numbers near null values

### ISSUE THREAD

**Issue by mmatrosov** [VictoriaMetrics/VictoriaMetrics#2408]
**Describe the bug**
See this graph, it looks ok:
![Screenshot from 2022-04-06 15-54-02](https://user-images.githubusercontent.com/3617951/161981635-b09277cb-e307-43e8-91b8-d6e2a739929c.png)

But if I zoom out a bit, something strange happens:
![Screenshot from 2022-04-06 15-54-16](https://user-images.githubusercontent.com/3617951/161981662-7e3b3b4d-4509-4f51-93d6-fbaec18ca561.png)

It is not a grafana bug, this huge value is provided by the data source:
![Screenshot from 2022-04-06 15-54-37](https://user-images.githubusercontent.com/3617951/161981692-267b0c31-487f-4a08-a8b9-462b40eb28be.png)

It is not happening if I use regular `rate` function:
![Screenshot from 2022-04-06 15-54-51](https://user-images.githubusercontent.com/3617951/161981709-1c5774c5-46bb-4962-b9b0-599bb3bccc8c.png)

And I don't see any crazy things in the raw values:
![Screenshot from 2022-04-06 15-58-19](https://user-images.githubusercontent.com/3617951/161981735-0de5c727-0037-4015-bfea-03acbbe7000b.png)
![Screenshot from 2022-04-06 15-59-15](https://user-images.githubusercontent.com/3617951/161981743-2542780c-2f0d-420e-8278-1a078ef7dbea.png)

Hence I guess this is a bug in VictoriaMetrics.

**To Reproduce**
Not sure, try to generate similar increasing data

**Expected behavior**
Function returns similar values not depending on the zoom level

**Logs**
I don't have access to it.

**Screenshots**
See above.

**Version**
```
victoria-metrics-20211008-135230-tags-v1.67.0-0-g6058edb0d
```
It is not easy to try the latest version.

**Used command-line flags**
I don't have access to it.

**Comment by hagen1778** [comment]
Hi @mmatrosov!
Which version of VM do you use? What will happen if you apply `increase`, `increase_pure` or `increase_prometheus` functions instead of `rate`?

**Comment by mmatrosov** [comment]
Hi @hagen1778 !

> Which version of VM do you use?

`victoria-metrics-20211008-135230-tags-v1.67.0-0-g6058edb0d`

> What will happen if you apply increase, increase_pure or increase_prometheus functions instead of rate?

`increase`, `increase_pure` - I see the same spike, but it occurs not before the range of null values, but after it. `increase_prometheus` - "cannot execute query: unknown func"

**Comment by hagen1778** [comment]
I see. I remember a similar case, but can't find the related issue. There are chances that is is already fixed in newer VM versions. You can try it yourself, or send a data dump for this particular metric to [info@victoriametrics.com](mailto:info@victoriametrics.com) or [roman@victoriametrics.com](mailto:roman@victoriametrics.com), so I can check it locally.

**Comment by jiekun** [comment]
Closed for now. Feel free to reopen it if you want to able to provide more data as mentioned above.
