### ISSUE TITLE
Has 1.75.1 been released? or canceled?

### ISSUE THREAD

**Issue by vroad** [VictoriaMetrics/VictoriaMetrics#2412]
GitHub says that https://github.com/VictoriaMetrics/VictoriaMetrics/tree/v1.75.1 does not belong to any branch on this repository. Then why it's still showing up in the list of git tags?

**Comment by denisgolius** [comment]
> GitHub says that https://github.com/VictoriaMetrics/VictoriaMetrics/tree/v1.75.1 does not belong to any branch on this repository. Then why it's still showing up in the list of git tags?

Hi @vroad !
This release is security release which has only bumped version of alpine linux for docker builds and don't contains any other changes. That's why it's not showing in branches list.

**Comment by vroad** [comment]
Thanks. So the commit at least belong to this repository? GitHub's warning message is a bit misleading.
