### ISSUE TITLE
Display large numbers in full, not in exponential form.

### ISSUE THREAD

**Issue by vc43** [VictoriaMetrics/VictoriaMetrics#2418]
Large numbers on vmui charts and in alerts are displayed in exponential form.
It would be nice to have an option that will display the numbers completely without shortening.

**Comment by tredondo** [comment]
This is a dupe of #2409.

**Comment by hagen1778** [comment]
Closed as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2409
