### ISSUE TITLE
No error returned when trying to incorrectly import incorrectly formatted data

### ISSUE THREAD

**Issue by tredondo** [VictoriaMetrics/VictoriaMetrics#2420]
**Describe the bug**
I've tried to import data in the [Prometheus exposition format](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-data-in-prometheus-exposition-format). I noticed that the response to the POST request is always `204 No content`. This happens even if the data was in the incorrect format.

**To Reproduce**
```js
axios.post(vmurl, 'foo{"bar:"baz"} 123');
```

**Expected behavior**
There should be an error that the format was incorrect.

**Logs**
There is a `cannot unmarshal Prometheus line` error in the VM log, but this should be returned to the client as well.

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20220318-175816-tags-v1.75.0-0-g87d356348
```

**Used command-line flags**
`-retentionPeriod=100y`

**Comment by dmitryk-dk** [comment]
Hi @tredondo ! Thank you for your bug! First of all this proposition breaks backwards compatibility and also you can post not only one metric, because the data is streaming and if one record is not recorded, then this is a problem of one record and not a stream

**Comment by tredondo** [comment]
OK, if one line out of N fails to be parsed, how will the client find out about this?

What if there was only one line sent, and it failed to be parsed? Shouldn't the response be an error code in that case?

**Comment by tredondo** [comment]
>  and also you can post not only one metric

@dmitryk-dk: I've run into the same error with the [JSON ingestion protocol](https://docs.victoriametrics.com/keyConcepts.html#push-model). As far as I can tell, you can only send one metric at a time with the JSON protocol, so the server should respond with an actual error instead of `204 No content` if the input was malformed.

What I tried to send:
```
{
  "metric": {
    "__name__": "test",
    "sensor": "s1",
    "values": [
      1
    ],
    "timestamps": [
      1693240245771
    ]
  }
}
```

The server error was

> cannot unmarshal json line... missing `values` array; skipping it

but the client had no idea there was a problem, and lost a lot of data, until I looked in the server logs.

**Comment by valyala** [comment]
@tredondo , [/api/v1/import](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format) protocol accepts a **stream** of JSON lines - see [these docs](https://docs.victoriametrics.com/#json-line-format) on the format of every JSON line. This means that it can ignore invalid lines, while successfully accepting other lines.

If you want using non-stream-based protocols, then try the following ones:

- [OpenTSDB /api/put](https://docs.victoriametrics.com/#sending-opentsdb-data-via-http-apiput-requests)
- [DataDog /api/v1/series](https://docs.victoriametrics.com/url-examples/#datadogapiv1series)
- [DataDog /api/v2/series](https://docs.victoriametrics.com/url-examples/#datadogapiv2series)

These protocols must return errors on invalid input.

Closing this issue as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1077
