### ISSUE TITLE
OTLP support in VictoriaMetrics?

### ISSUE THREAD

**Issue by johnseekins** [VictoriaMetrics/VictoriaMetrics#2424]
**Is your feature request related to a problem? Please describe.**

OTLP is emerging as a potential real standard for "portable" telemetry. Are there any plans to support ingesting this format? Or any plans to support tracing ingest in general?

I realize tracing represents cardinality problems, but there aren't many self-hosted solutions for storing trace data and y'all are pretty great at building effective tools in this general space...

As an example, Grafana's new Mimir tool is working on supporting OTLP: https://github.com/grafana/mimir/pull/695/files

**Describe the solution you'd like**
Ability to store OTLP data in VictoriaMetrics.

**Describe alternatives you've considered**
A listener that converts OTLP data into a format VictoriaMetrics supports. Which would likely work, but could potentially lose metadata.

**Comment by johnseekins** [comment]
I realize there's a few small things I should clarify:

1. For the use-case I'm imagining we'd want the client to be able to push directly to VictoriaMetrics (not a OTLP collector that scrapes a target and then forwards results)
2. It's likely that these traces would have significant size concerns, so it may be worth having a separate retention setting for them? Like...obviously it's reasonable to default to using the same retention as other stats, but if we _could_ set a single different retention for span/trace storage, that would be nice.

**Comment by f41gh7** [comment]
1) Use it will support directly metrics push. I'm working on small blog post for it. An example of web application, that uses opentelemetry and victoriametrics https://gist.github.com/f41gh7/1a67850e2cc795af05d96085de9c6653
2) traces isn't supported by VM. It should be written into some other trace storage.

 Related PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2570

**Comment by Luckz** [comment]
This is a bit of a hybrid 'support OTLP metrics' and 'support tracing, including the OTLP tracing format' feature request.

**Comment by djesus-shell** [comment]
i also support that victoriametrics has a native listener for OTLP.

**Comment by Wondertan** [comment]
ViktoriaMetrics is a great backend for metrics. OTLP is a neat generic protocol. Having them both support each other would be priceless

**Comment by valyala** [comment]
The update on this feature request - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2570#issuecomment-1378026770

**Comment by valyala** [comment]
FYI, VictoriaMetrics gains support for data ingestion via OpenTelemetry format for metrics starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#sending-data-via-opentelemetry) for details. VictoriaMetrics cluster has slightly different URL for data ingestion - see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format).

Closing the feature request as done.
