### ISSUE TITLE
Broken ipv6

### ISSUE THREAD

**Issue by subvillion** [VictoriaMetrics/VictoriaMetrics#244]
**Describe the bug**
Doesn't work with ipv6

**To Reproduce**
Just try run listener on ipv6 address 

**Expected behavior**
Work with ipv6

**Additional context**
0_o
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/netutil/tcplistener.go#L16

**Comment by valyala** [comment]
This is by design, since most users don't expect that their service would listen for both ipv4 and ipv6 TCP ports. Added `-enableTCP6` command line flag at https://github.com/VictoriaMetrics/VictoriaMetrics/commit/9010c6a1d688f79951ecaf35d7c2fec991cf3e36 , so users could explicitly enable listening for ipv6 ports if they know what are they doing.

**Comment by wf1nder** [comment]
Ok, now it listening properly both ipv4 and ipv6. But it is still issue with accessing ipv6-only resources as client:

```Nov 30 12:52:50 <hostname> vmselect[9527]: 2019-11-30T09:52:50.295+0000        error        app/vmselect/main.go:259        error in "/select/0/prometheus/api/v1/query_range": cannot execute <query>: error occured during search: cannot perform search on vmstorage <hostname>:8401: cannot obtain connection from a pool: cannot dial <hostname>:8401: dial tcp4: address <hostname>: no suitable address found```

<hostname> - is DNS-record with only ipv6 AAAA-record.

**Comment by valyala** [comment]
This should be fixed in `cluster` branch with the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d456ec758933f9f5d42c8618eda7d2b91d8ae94c .

**Comment by valyala** [comment]
The `-enableTCP6` option is available starting from [v1.30.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed. Feel free re-opening it if you feel the issue isn't fully fixed.
