### ISSUE TITLE
VM doesn't apply search.maxUniqueTimeseries after upgrade to 1.76.0

### ISSUE THREAD

**Issue by deemon87** [VictoriaMetrics/VictoriaMetrics#2450]
After upgrade victoriametrics from 1.75.0 to 1.76.0 doesn't apply search.maxUniqueTimeseries.
When i did request from grafana i started to get the following error:

**error when searching tsids: the number of matching unique timeseries exceeds 10000; either narrow down the search or increase -search.maxUniqueTimeseries**

There is my increased setting search.maxUniqueTimeseries in logs:
**VictoriaMetrics/lib/logger/flag.go:20        flag "search.maxUniqueTimeseries"="1000000"**

Error disappeared after return back v1.75.0

I'm using VM on one node (not cluster version)

**Comment by valyala** [comment]
This issue has been addressed in the commit 81b7a31cb1118f010df9160e49e76bb828dd097f . It will be included in the upcoming bugfix release.

**Comment by valyala** [comment]
The bugfix is included in [v1.76.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by deemon87** [comment]
> Was this addressed in both cluster and single-node versions? We've started seeing this issues in the single-node VM after the upgrade.

You need to add one more option **-search.maxSeries**
