### ISSUE TITLE
bug: vm v1.70.0, all vmstorage switch indexdb in same time at 12:00pm, cause half vminsert oom

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2464]
1. found vm-insert not ok:
![image](https://user-images.githubusercontent.com/4198375/163129314-cf77eced-7af6-4d48-b316-830eb9bb66d7.png)

2. 13 of 25 instance oom, and restart
![image](https://user-images.githubusercontent.com/4198375/163129619-1cd59708-a8d9-4ecb-8e81-ad2fcb9036c4.png)
query: `(max by(pod_name)(rate(time()-process_start_time_seconds{tenant="$tenant",namespace="$namespace",env_name="$env_name",role="$role"})))!=1`

and process time reach to most 14s:
![image](https://user-images.githubusercontent.com/4198375/163130200-0f91a53d-fe55-4537-ab44-484e8c389fc4.png)

3. found strange things on vmstorage view:
![image](https://user-images.githubusercontent.com/4198375/163130032-30e40021-1bf3-4da6-80d9-24d8ae41a1a9.png)
see by container view:
![image](https://user-images.githubusercontent.com/4198375/163130382-ac02f810-db32-43a4-9ffb-a62d1091c14b.png)

so I think switch indexdb cause tsid cache reset.
----
I suggest:
1.when switch indexdb,  add a random time, not in a same abs time.
2. reset tsid cache not so fast, set a switch flag, write to indexdb when cache hit and switch flag set.
3. vminsert drop data when vmstorage become slow, and add a new metric to tell admin what happend, avoid oom.

thanks.

**Comment by hagen1778** [comment]
Hi @ahfuzhang! The indexdb [rotation issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401) was fixed in [1.73 release](https://docs.victoriametrics.com/CHANGELOG.html#v1730). We recommend keeping VM version updated - see https://docs.victoriametrics.com/CHANGELOG.html#v1761

**Comment by ahfuzhang** [comment]
thanks
