### ISSUE TITLE
A question about writeconcurrencylimiter

### ISSUE THREAD

**Issue by woodliu** [VictoriaMetrics/VictoriaMetrics#2470]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e6535a75f73c676e7138620838580286e14da68d/lib/writeconcurrencylimiter/concurrencylimiter.go#L32

@valyala Hi, I'm a little confuse about the writeconcurrencylimiter. In its comment, it says `can Limit the number of conurrent f calls in order to prevent from excess memory usage and CPU thrashing`
Vminsert uses it to limit the process of request, like this:
![image](https://user-images.githubusercontent.com/9976943/163552456-97d34ebb-24e8-4b18-b17f-4be97378dbb5.png)

I think when tcp accepts a connection, it will start a new goroutine to server it, accept request and call ServeHTTP. Writeconcurrencylimiter is in ServeHTTP, but at this point, it has received the request.  So i think Writeconcurrencylimiter just prevent conurrent calls to allocate more memory,  and the conurrent connection is controlled by kernal parameter: /proc/sys/net/core/somaxconn

Am i right? Thanks!

**Comment by valyala** [comment]
> So i think Writeconcurrencylimiter just prevent conurrent calls to allocate more memory, and the conurrent connection is controlled by kernal parameter: /proc/sys/net/core/somaxconn

Yes, this is correct understanding - `writeconcurrencylimiter` limits the number of concurrent calls for the inner callback (`parser.ParseStream` in the case above). This callback is usually bound by CPU and may use big amounts of memory, which are needed for parsing the incoming data and sending the parsed data to storage. So the main purpose of `writeconcurrencylimiter` is to prevent from out of memory errors when big number of concurrent insert requests hit `vminsert`.

The `writeconcurrencylimiter` doesn't limit the number of concurrent connections, which can be established to `vminsert`. If `vminsert` receives more concurrent connections than `writeconcurrencylimiter` allows, then the remaining connections will wait until the active connections finish processing in `writeconcurrencylimiter` callback.

**Comment by woodliu** [comment]
> > So i think Writeconcurrencylimiter just prevent conurrent calls to allocate more memory, and the conurrent connection is controlled by kernal parameter: /proc/sys/net/core/somaxconn
> 
> Yes, this is correct understanding - `writeconcurrencylimiter` limits the number of concurrent calls for the inner callback (`parser.ParseStream` in the case above). This callback is usually bound by CPU and may use big amounts of memory, which are needed for parsing the incoming data and sending the parsed data to storage. So the main purpose of `writeconcurrencylimiter` is to prevent from out of memory errors when big number of concurrent insert requests hit `vminsert`.
> 
> The `writeconcurrencylimiter` doesn't limit the number of concurrent connections, which can be established to `vminsert`. If `vminsert` receives more concurrent connections than `writeconcurrencylimiter` allows, then the remaining connections will wait until the active connections finish processing in `writeconcurrencylimiter` callback.

Thanks a lot, the VictoriaMetrics codes has use some tricks to help with the performance, that's amazing.
