### ISSUE TITLE
suggest: add a metric for index total count

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2471]
see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/4169b97af98ee89ce5b7d5b22c24a7a1574130dc/lib/storage/index_db.go#L559

there is only sum new time series.
but when timeseries have many labels, we need to knows index count also.

for example, a time series have 10 labels, storage will add almost 40 index to mergeset.

thanks.

**Comment by valyala** [comment]
@ahfuzhang , thanks for the feature request!

The commit 98129d4a8e2c4e7b8ade7834c039d6f395747914 adds `vm_indexdb_items_added_total` and `vm_indexdb_items_added_size_bytes_total` counters, which are exposed at `/metrics` page of a single-node VictoriaMetrics.

The commit ed1b394a1a1fcfbe0d0701a43bde84e8a9427a72 exposes the same metrics at `vmstorage` component in a cluster version of VictoriaMetrics.

Now it is possible to check the rate of addition of new entries in `indexdb` (aka inverted index) with `rate(vm_indexdb_items_added_total)` .

These commits will be included in the next release of VictoriaMetrics

**Comment by valyala** [comment]
@hagen1778 , it may be great adding a graph for `rate(vm_indexdb_items_added_total)` and `increase(vm_indexdb_items_added_total[1d])` metrics into `troubleshooting` section of [official Grafana dashboard for VictoriaMetrics](https://grafana.com/grafana/dashboards/10229). It should correlate with `slow inserts` and `churn rate` graphs and, probably, give more insights for troubleshooting.

**Comment by valyala** [comment]
FYI, VictoriaMetrics exposes `vm_indexdb_items_added_total` and `vm_indexdb_items_added_size_bytes_total` metrics starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
