### ISSUE TITLE
why go_threads is so much ? go_threads=429, go_goroutines=148, go_cpu_count=16

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#2474]
we found vm-storage overload this morning at 7:00 am.

![image](https://user-images.githubusercontent.com/4198375/163665353-b72b5461-1b15-4903-8bab-2868825826d1.png)

15 vm-storage overload:
`count(sum by(addr)(increase(vm_rpc_rows_dropped_on_overload_total{}[1m])>0))`

![image](https://user-images.githubusercontent.com/4198375/163665397-b7be7fdf-f3a9-4204-a5e2-435d5c90aa92.png)

----

choose one vm-storage to see detail:
* cores: 16
* mem: 128GB
* allowed mem: 81.1GB
* process_resident_memory_bytes: 80.0GB
* go_threads: 429
* go_goroutines: 148
* container cpu use: 15.1 cores
* container memory use: 92.1gb
![image](https://user-images.githubusercontent.com/4198375/163665602-8274231f-2045-43e8-b2ea-f664f0570173.png)
![image](https://user-images.githubusercontent.com/4198375/163665623-93363ed8-54bc-47d5-bf79-27090f52fad9.png)

I guess there might be two problem:
1. rss reach to limit memory;
2. too many physical threads.
    and we already set env var `GOMAXPROCS=16`

so, why physical threads is 26 times of cpu core ? 

vm-storage version is 1.75.0

**Comment by ahfuzhang** [comment]
how about use a cmd flag to let user set max threads count?

we can use this api: `debug.SetMaxThreads()`

**Comment by ahfuzhang** [comment]
> how about use a cmd flag to let user set max threads count?
> 
> we can use this api: `debug.SetMaxThreads()`

not works, program might be crash when threads count reach to max

**Comment by f41gh7** [comment]
count of go_threads can be higher, then GOMAXPROCS. It may happen, when go runtime spawns additional threads for blocking `syscall` and `cgo` calls.

 In your case, it seems, that storage was overloaded by merge or other operation, which uses a lot of cgo calls (usually it's zstd operations).

**Comment by ahfuzhang** [comment]
thanks
