### ISSUE TITLE
After i update to vmcluster 1.74.0, vminsert start drop some rows when there are  readonly nodes in storage nodes.

### ISSUE THREAD

**Issue by Buddruggy** [VictoriaMetrics/VictoriaMetrics#2478]
**Describe the bug**
After i update to vmcluster 1.74.0, vminsert start drop some rows when there are  readonly nodes in storage nodes.

i start vminsert with `-dropSamplesOnOverload=true`

**To Reproduce**
When vmcluster update to 1.74.0, and have readonly storage nodes, this problem is inevitable.

**Expected behavior**
When storage nodes changed to readonly mode, vminsert should reroute to other healthy storage nodes instead of dropping data, even vminsert started with commond `-dropSamplesOnOverload=true`

**Logs**

**Screenshots**
<img width="809" alt="image" src="https://user-images.githubusercontent.com/32037815/163957998-a7262b49-323d-4bf3-b92d-bb0c89711444.png">

total vmstorage node cnt: 65

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/32037815/163956351-adeb7b33-2148-4753-8d14-e9b3463d40cc.png">

readonly vmstorage node cnt: 15

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/32037815/163956440-a4620780-a0d3-4078-8756-5d5cb508ddd0.png">

**Version**
vmcluster 1.74.0

**Used command-line flags**
-dropSamplesOnOverload=true

**Comment by denisgolius** [comment]
Hi @Buddruggy !
1. How many `vmstorage` nodes you use?
2. What is the value of [replication factor](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety) you have set?

**Comment by Buddruggy** [comment]
> Hi @Buddruggy !
> 
> 1. How many `vmstorage` nodes you use?
> 2. What is the value of [replication factor](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety) you have set?

1. vmstorage nodes count : 65, read only nodes count: 15. vminsert start with `-storageNode=65nodes -dropSamplesOnOverload=true`
2. I not set replication factor, so i think should be default value.

vminsert commond line: `-maxConcurrentInserts=16 -maxInsertRequestSize=50MB -memory.allowedPercent=70 -storageNode=65 x ip:port -maxLabelsPerTimeseries=55 -insert.maxQueueDuration=2m -dropSamplesOnOverload=true`

**Comment by denisgolius** [comment]
> > Hi @Buddruggy !
> > 
> > 1. How many `vmstorage` nodes you use?
> > 2. What is the value of [replication factor](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety) you have set?
> 
>     1. vmstorage nodes count : 65, read only nodes count: 15. vminsert start with `-storageNode=65nodes -dropSamplesOnOverload=true`
> 
>     2. I not set replication factor, so i think should be default value.
> 
> 
> vminsert commond line: `-maxConcurrentInserts=16 -maxInsertRequestSize=50MB -memory.allowedPercent=70 -storageNode=65 x ip:port -maxLabelsPerTimeseries=55 -insert.maxQueueDuration=2m -dropSamplesOnOverload=true`

When one of the nodes becomes unavailable, it triggers re-rooting. At that moment the insertion can be slowed down and because of the `dropSamplesOnOverload` flag the data will be discarded. In this case you should remove the `dropSamplesOnOverload` flag.

**Comment by Buddruggy** [comment]
> > > Hi @Buddruggy !
> > > 
> > > 1. How many `vmstorage` nodes you use?
> > > 2. What is the value of [replication factor](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety) you have set?
> > 
> > 
> > ```
> > 1. vmstorage nodes count : 65, read only nodes count: 15. vminsert start with `-storageNode=65nodes -dropSamplesOnOverload=true`
> > 
> > 2. I not set replication factor, so i think should be default value.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > vminsert commond line: `-maxConcurrentInserts=16 -maxInsertRequestSize=50MB -memory.allowedPercent=70 -storageNode=65 x ip:port -maxLabelsPerTimeseries=55 -insert.maxQueueDuration=2m -dropSamplesOnOverload=true`
> 
> When one of the nodes becomes unavailable, it triggers **Rerouting**. At that moment the insertion can be slowed down and because of the `dropSamplesOnOverload` flag the data will be discarded. In this case you should remove the `dropSamplesOnOverload` flag.

In my opinion, data should not be discarded in this case. because `dropSamplesOnOverload` flag can prevent problems when the insertion slow down, but storage becomes readonly mode should be treated as a normal case. If i removed `dropSamplesOnOverload` flag,  i will have this [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2172). so is there have any solutions prevent this [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2172) when have read only storage nodes.

**Comment by valyala** [comment]
@Buddruggy , thanks for the bugreport! The issue should be fixed in the commit e613ca9ba8cbc03dea35f566e5301800b1526ddf , which will be included in the next release.

**Comment by valyala** [comment]
FYI, [vminsert v1.77.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) shouldn't drop incoming samples if they are routed to readonly `vmstorage` when `-dropSamplesOnOverload` command-line flag is set. Closing the issue as fixed.
