### ISSUE TITLE
range query vs export api

### ISSUE THREAD

**Issue by oronsh** [VictoriaMetrics/VictoriaMetrics#2480]
Hi @valyala ,
I would like to know please what is the difference between the two in terms of performance?
Is the regular range query api faster or uses less resources then using the export api?
Could the export json api be used to just query VM regularly?

Thanks a lot!

**Comment by YuriKravetc** [comment]
Hi @oronsh 
Export API is exporting the raw data.
As for range query API - it performs additional calculations on top of the query - so it is using more resources.

Using export JSON API be to query VM regularly - not really.

Best regards,

**Comment by oronsh** [comment]
Thank you @YuriKravetc !
