### ISSUE TITLE
very high pending datapoints with low cpu iowait

### ISSUE THREAD

**Issue by jiayouchongmingniao** [VictoriaMetrics/VictoriaMetrics#2483]
**Describe the bug**
dear support. we are using a large scale cluster of vmstorae, 56 nodes (4000+ Cpus, 24T+ memory)，meet performance issue，
about 12:10 everyday，merge index starts, we get high pending datapoints 0.4-0.6 billion and high churn rate and high indexdb，but with very low cpu iowait。

retentionPeriod=1d

**To Reproduce**
everyday during merging index，it will happen and last for about 2 hours

**Expected behavior**
rappidly flush to disk and no performance issue

**Logs**
{"ts":"2022-04-19T06:55:58.636Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:139","msg":"cannot process vminsert conn from 196.112.60.14:52988: cannot send `ack` to vminsert: write tcp4 196.112.144.149:8400->196.112.60.14:52988: write: broken pipe"}
{"ts":"2022-04-19T06:55:59.236Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:139","msg":"cannot process vminsert conn from 196.112.111.81:49132: cannot read packet with size 18044059 bytes: cannot read data in 0.001 seconds: cannot read data from the underlying reader: read tcp4 196.112.144.149:8400->196.112.111.81:49132: read: connection reset by peer; read only 9830392 bytes"}

**Screenshots**
![1650465362(1)](https://user-images.githubusercontent.com/55178588/164255365-07ed0164-eb96-4772-9fca-6c71c7360877.png)
![1650465398(1)](https://user-images.githubusercontent.com/55178588/164255532-3890ddd1-73a5-43a2-8faf-2062899d682d.png)

./vmstorage-prod --version
vmstorage-20211220-173542-tags-v1.71.0-cluster-0-g28a0d3faa

**Comment by jiayouchongmingniao** [comment]
{"ts":"2022-04-20T07:29:10.121Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:139","msg":"cannot process vminsert conn from 196.112.45.4:49096: cannot read packet with size 7510106 bytes: unexpecte
d EOF; read only 7077880 bytes"}
{"ts":"2022-04-20T07:29:12.523Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:139","msg":"cannot process vminsert conn from 196.112.252.203:45866: cannot read packet with size 12155656 bytes: unexp
ected EOF; read only 7995384 bytes"}

**Comment by valyala** [comment]
It is likely the issue has been fixed in [v1.73.0](https://docs.victoriametrics.com/CHANGELOG.html#v1730) - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401) for details. I'd recommend upgrading VictoriaMetrics to the [latest available version](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and see whether this helps resolving the issue.

**Comment by hagen1778** [comment]
Closing as inactive. Feel free to reopen if the issues still remains
