### ISSUE TITLE
UI issue with truncating alerts expression

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#2484]
**Describe the bug**
When you set long alert expression it truncated.
Please check image below

**To Reproduce**
Run vmalert and set alert for example
```100 * (count(up == 0) BY (job, namespace, service) / count(up) BY (job,namespace, service)) > 10```

**Expected behavior**
Alert expression will not truncated

**Screenshots**
<img width="1633" alt="Screen Shot 2022-04-20 at 09 07 18" src="https://user-images.githubusercontent.com/12189570/164276179-fcffc5ca-0ee9-4173-9aed-a2518f7ad05f.png">

**Comment by valyala** [comment]
The issue has been fixed in [vmalert v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
