### ISSUE TITLE
A question about tsid creation

### ISSUE THREAD

**Issue by alexandnpu** [VictoriaMetrics/VictoriaMetrics#2488]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/708a3ef27668d8eb2846091df2d8271424a95f5b/lib/storage/index_db.go#L559

I am reading code here, should `db.createIndexes` be called after checking `created`?

If it could be avoided, can it improve some performance in high-churn-rate scenarios?

**Comment by ahfuzhang** [comment]
this link might be help: https://github.com/ahfuzhang/victoria-metrics-1.72.0/blob/master/%E6%BA%90%E7%A0%81%E8%BF%BD%E8%B8%AA/%E6%8F%92%E5%85%A5%E7%B4%A2%E5%BC%95%E8%BF%87%E7%A8%8B.md

1.when addRow not find tsid of metric, call `func (db *indexDB) createTSIDByName`. that means current metric is complete new.
2.before create index, we need to create a new tsid for metric. so call `db.generateTSID`, then call `db.createIndexes`.

this is not about `high-churn-rate`, every new metric should do that.

**Comment by alexandnpu** [comment]
@ahfuzhang ， thanks for your reply and explanation, I should look a step further. 
The `createTSIDByName` is for creating tsid after failing to find tsid for a metric name. It is on the creation path.
if the `created` above is false above, it means that the metric appeared in the previous retention period. But we still need to create the index in current index db.
