### ISSUE TITLE
vmctl blocks when aborting import process

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#2491]
**Describe the bug**
When you have snapshot with single block and trying to abort the process 
it shows that the process is canceled but not finished correctly

**To Reproduce**
Run vmctl with snapshot which have only one block and press `CTRL+C`

**Expected behavior**
It should finish process correctly

**Version**
it produced on master code

**Used command-line flags**
```./vmctl prometheus --prom-snapshot=../../prometheus-2.34.0.darwin-amd64/data/snapshots/20220420T130152Z-27c1a595a43b4720 ```

**Comment by qiu-peng20** [comment]
hi，bro，Have you encountered this problem?
root@vida-5f5859fbd8-vgkph:/# ./vmctl-prod prometheus --prom-snapshot=/prometheus/snapshots/20220426T025904Z-268447a4189deb99 --vm-addr=http://10.37.205.27:8480/ --prom-filter-time-end=2021-11-01T00:00:00Z --prom-concurrency=3
Prometheus import mode
Prometheus snapshot stats:
blocks found: 40;
blocks skipped by time filter: 39;
min time: 1635292800000 (2021-10-27T08:00:00+08:00);
max time: 1635876000000 (2021-11-03T02:00:00+08:00);
samples: 36729829788;
series: 3350375.

Stats numbers are based on blocks meta info and don't account for applied filters.
Found 1 blocks to import. Continue? [Y/n] y
0 / 1 [________________________________________________________________________] 0.00% ? p/s

vmctl to import the data from Prometheus to VM, but the import is stuck at 0%

**Comment by dmitryk-dk** [comment]
Hi @qiu-peng20 ! We have fixed this problem in this PR
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2486

**Comment by qiu-peng20** [comment]
But I see this merge was rejected 🤣🤣🤣

**Comment by dmitryk-dk** [comment]
@qiu-peng20, this merge waiting review and blocking for merge

**Comment by qiu-peng20** [comment]
@dmitryk-dk Looking forward, I've been plagued by this problem for a long time

**Comment by valyala** [comment]
FYI, `vmctl` should exit on `ctrl+C` starting from [v1.77.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
