### ISSUE TITLE
Clarify argument syntax to prevent data loss

### ISSUE THREAD

**Issue by thetooth** [VictoriaMetrics/VictoriaMetrics#2496]
I have seen a lot of default configs ship with package manages/examples/tutorials that look as follows:
```-storageDataPath /var/lib/victoriametrics/ -retentionPeriod 100y```
What this actually means is "use the specified storage path and set the retention period to 0 nano seconds", the following does work as intended:
```-storageDataPath /var/lib/victoriametrics/ -retentionPeriod=100y```

I think either crashing out and reporting a retention period of 0 being invalid or making the argument parser more robust in handling different input styles would be a sensible fix for this. It was quite the head scratcher for me, trying to restore a db from backup only for VM to dutifully garbage collect it immediately on startup.

**Comment by valyala** [comment]
@thetooth , thanks for the suggestion on validating improper `-retentionPeriod` command-line flag values. It should be handled in the commit d6ad8d090dc163427012081c8fb1f90a6c1cf1dd , which will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics emits an error when `-retentionPeriod` is set to value smaller than one day starting from [v1.77.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
