### ISSUE TITLE
"-downsampling.period" is not effective

### ISSUE THREAD

**Issue by chenxianr** [VictoriaMetrics/VictoriaMetrics#2498]
**Describe the bug**
VictoriaMetrics Enterprise `-downsampling.period` does not work, it doesn't decrease the number of data points or data size.

I setup three single-node instances, two of them are open-source version, and one enterprise version, for evaluating downsampling.

**To Reproduce**
1. a prometheus node with 15s' scrape interval2. 
2. an open-source version node without minScrapeInterval3. 
3. an open-source version node with -dedup.minScrapeInterval=1m4. 
4. an enterprise version with -downsampling.period=10m:1m5. 

**Screenshots**
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/45402716/164971658-19610d3c-fdbe-4180-bdb4-90ef562fde80.png">
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/45402716/164971666-de1d8bbd-f109-48f9-ba5d-b405e70aaf56.png">

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20220412-135434-tags-v1.76.1-enterprise-0-g13133f1e1

$ ./victoria-metrics --version 
victoria-metrics-20220412-133902-tags-v1.76.1-0-gf8de318bf
```

**Used command-line flags**
./bin/victoria-metrics -retentionPeriod=5y
./bin/victoria-metrics -retentionPeriod=5y -dedup.minScrapeInterval=1m -httpListenAddr=:8429
./bin/victoria-metrics-prod -eula -downsampling.period=10m:1m -retentionPeriod=5y -httpListenAddr=:8430

**Comment by f41gh7** [comment]
`VictoriaMetrics` executes downsampling at partitions, data stored at disk partitioned by month. In this case, final downsampling starts only when partition leaves configured downsampling period, some data eventually downsampled during current month. In your case, final downsample starts only at the next month - `05_2022` (current month for now!).

**Comment by chenxianr** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/45402716/166887150-b37f0c5b-4da7-4748-a998-d4a1dab80e49.png">

Thanks for your patience!
It does downsample at the next month.
