### ISSUE TITLE
VictoriaMetrics/app/vmbackup/main.go:97 cannot create backup: cannot create `backup complete` file at fsremote "latest": cannot write 2 bytes to "latest/backup_complete.ignore": open latest/backup_complete.ignore: is a directory

### ISSUE THREAD

**Issue by haripcv** [VictoriaMetrics/VictoriaMetrics#2503]
Running daily backup script below results in fatal error:

```
sudo /apps/vmutils/vmbackup-prod -snapshotName=`date -I --date=' 1 days ago'` -storageDataPath=/apps/metric-storage -dst=fs:///apps/metric-storage/snapshots/`date -I`
```
```
 VictoriaMetrics/app/vmbackup/main.go:97 cannot create backup: cannot delete `backup complete` file at fsremote "/apps/metric-storage/snapshots/2022-04-25": cannot remove "/apps/metric-storage/snapshots/2022-04-25/backup_complete.ignore": remove /apps/metric-storage/snapshots/2022-04-25/backup_complete.ignore: directory not empty
```

I have a Victoriametrics cluster running and the attempt is to create daily and hourly backups. However, it works for the very first time and then subsequent backups fails with the above error.

**Version**

The line returned when passing `--version` command line flag to the binary. For example:
```
# ./vmbackup-prod --version
vmbackup-20220412-133957-tags-v1.76.1-0-gf8de318bf

# ./vmstorage-prod --version
vmstorage-20210715-111925-tags-v1.63.0-cluster-0-g4ec57102e
```

**Comment by haripcv** [comment]
/apps/vmutils/vmbackup-prod -snapshotName=daily/`date -I --date=' 1 days ago'` -storageDataPath=/apps/metric-storage -dst=fs:///apps/metric-storage/snapshots/daily/`date -I`;rm -f /apps/metric-storage/snapshots/daily/`date -I`/backup_complete.ignore

**Comment by haripcv** [comment]
We cannot use snapshot.createURL, since we want a smart backup setup(hourly, daily and weekly). So it is necessary to have snapshotName referencing to the previous backup. However, we have implemented a work around for our issue by deleting the backup_complete.ignore file everytime a backup successfully completes. This should actually be done automatically by the vmbackup and hence this could be a bug. Our working cron script is as below:
~~~~~~~~~~
/apps/vmutils/vmbackup-prod -snapshotName=daily/`date -I --date=' 1 days ago'` -storageDataPath=/apps/metric-storage -dst=fs:///apps/metric-storage/snapshots/daily/`date -I`;rm -f /apps/metric-storage/snapshots/daily/`date -I`/backup_complete.ignore
~~~~~~~~~~

**Comment by dmitryk-dk** [comment]
Hi @haripcv ! Thank you for your issue! I have tested your approach on my local and it works well. 

But It looks like somebody trying to deleted the backup files while vmbackup was trying to sync the -dst contents with the current snapshot. Make sure that a single vmbackup process performs the backup at the given -dst directory. Probably multiple vmbackup processes were running simultaneously, which resulted in a race condition of data removal.

**Comment by valyala** [comment]
> We cannot use snapshot.createURL, since we want a smart backup setup(hourly, daily and weekly). So it is necessary to have snapshotName referencing to the previous backup.

It looks like there is some misunderstanding on how backups work. I tried to clarify `vmbackup` docs in the commit 910f715ffea8387c4263c8df83cb25aca4019c75  - see [the updated docs about smart backup](https://docs.victoriametrics.com/vmbackup.html#smart-backups). Note that smart backup relies solely on `-snapshot.createURL` without the need to change snapshot names.

`vmbackup` creates `backup_complete.ignore` file in the `-dst` directory only **after the backup is complete**. [vmrestore](https://docs.victoriametrics.com/vmrestore.html) fails to restore from backup if it cannot find the `backup_complete.ignore` file in `-src` directory, since this means that the `-src` directory contains incomplete backup.

Both `cannot create backup complete file` and `cannot delete backup complete file` errors may occur in `vmbackup` only when the `-dst` directory contains `backup_complete.ignore` directory instead of file. The `backup_complete.ignore` directory may appear here only when the source directory with the snapshot contains the `backup_complete.ignore` file. Neither `victoriametrics` nor `vmbackup` don't put the `backup_complete.ignore` file into a snapshot directory. So it looks like there is some mis-configuration in your case. Please read [the updated docs for vmbackup](https://docs.victoriametrics.com/vmbackup.html).

**Comment by haripcv** [comment]
> > We cannot use snapshot.createURL, since we want a smart backup setup(hourly, daily and weekly). So it is necessary to have snapshotName referencing to the previous backup.
> 
> It looks like there is some misunderstanding on how backups work. I tried to clarify `vmbackup` docs in the commit [910f715](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/910f715ffea8387c4263c8df83cb25aca4019c75) - see [the updated docs about smart backup](https://docs.victoriametrics.com/vmbackup.html#smart-backups). Note that smart backup relies solely on `-snapshot.createURL` without the need to change snapshot names.
> 
> `vmbackup` creates `backup_complete.ignore` file in the `-dst` directory only **after the backup is complete**. [vmrestore](https://docs.victoriametrics.com/vmrestore.html) fails to restore from backup if it cannot find the `backup_complete.ignore` file in `-src` directory, since this means that the `-src` directory contains incomplete backup.
> 
> Both `cannot create backup complete file` and `cannot delete backup complete file` errors may occur in `vmbackup` only when the `-dst` directory contains `backup_complete.ignore` directory instead of file. The `backup_complete.ignore` directory may appear here only when the source directory with the snapshot contains the `backup_complete.ignore` file. Neither `victoriametrics` nor `vmbackup` don't put the `backup_complete.ignore` file into a snapshot directory. So it looks like there is some mis-configuration in your case. Please read [the updated docs for vmbackup](https://docs.victoriametrics.com/vmbackup.html).

Thanks for this @valyala. Our backups now run with -snapshot.createURL= and -origin=(referencing previous backup) and daily, hourly and weekly now run correctly. The point you added about restoration issues if we remove the `backup_complete.ignore` makes sense. We are yet to test a restore, we want the backups to run atleast 2-3 weeks before testing restore. We will keep you posted.

**Comment by valyala** [comment]
@haripcv , thanks for the update! Closing the issue as resolved.

**Comment by valyala** [comment]
FYI, `vmbackup` [v1.77.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) should prevent from storing backups into `-storageDataPath` directory, which is managed solely by VictoriaMetrics or `vmstorage`.
