### ISSUE TITLE
About indexdb retention duration's doubt

### ISSUE THREAD

**Issue by cnych** [VictoriaMetrics/VictoriaMetrics#2520]
**indexdb retention duration time doubt**
In the code show indexdb next retention duration from `nextRetentionDuration(s.retentionMsecs)` function(in `lib/storage/storage.go`), then will be trigger `mustRotateIndexDB`.

Doubt about this retention duration, for example, I test retentionMsecs from 1day - 5day:

```go
func nextRetentionDuration(retentionMsecs int64) time.Duration {
	retentionMsecs = ((retentionMsecs + msecPerDay - 1) / msecPerDay) * msecPerDay
	t := time.Now().UnixNano() / 1e6
	fmt.Printf("======now=%s\n", time.Now())
	deadline := ((t + retentionMsecs - 1) / retentionMsecs) * retentionMsecs
	deadline += 4 * 3600 * 1000
	fmt.Printf("deadline=%s\n", time.Unix(deadline/1e3, (deadline%1e3)*1e6).Local())
	return time.Duration(deadline-t) * time.Millisecond
}

func TestRetentionDuration(t *testing.T) {
	nextRetentionDuration(1 * msecPerDay)
	nextRetentionDuration(2 * msecPerDay)
	nextRetentionDuration(3 * msecPerDay)
	nextRetentionDuration(4 * msecPerDay)
	nextRetentionDuration(5 * msecPerDay)
}
```

But not the expected result.

<img width="842" alt="image" src="https://user-images.githubusercontent.com/3094973/165954079-6c7e1b33-7b14-4acc-b4b6-fbdb1bb9d97a.png">

**Comment by valyala** [comment]
IndexDB rotation is performed once per the specified `-retentionDuration` period rounded to days. The particular time for `indexdb` rotation is aligned to **multiples** of `-retentionDuration` starting from the [unix epoch](https://en.wikipedia.org/wiki/Unix_time). Let's suppose the current date is `January 7, 1970` and let's calculate the next indexdb rotation date for `-retentionPeriod=1d`, `-retentionPeriod=2d`, `-retentionPeriod=3d`, `-retentionPeriod=4d` and `-retentionPeriod=5d`:

```
retentionPeriod   next indexdb rotation date
1d                            Jan 8     = (1d*4)
2d                            Jan 8     = (2d*2)
3d                            Jan 9     = (3d*2)
4d                            Jan 8     = (4d*1)
5d                            Jan 10    = (5d*1)
```

The difference between these dates is similar to the difference between dates in the `TestRetentionDuration` output above.

**Comment by cnych** [comment]
@valyala Thank you very much, now I understand, because it is generally considered to be aligned according to the current time.

**Comment by vaskozl** [comment]
How soon does dropping retention have an effect on index storage? 

After dropping retention on two seperate clusters, I see datapoints storage falling (and bounding) while index continous growing with no drop at all.

I've tried this on two completely separate clusters running victoria-metrics and in both cases index size doesn't budge after a drop in retentionPeriod. Do you have to wait the full new retention period for the index to be pruned, or is it related to the old retention that was active when the index was created? This may be a problem for me as I mistakenly configured retention in months rather than days if that is the case.

**Comment by vaskozl** [comment]
I've found I can use `vm_next_retention_seconds` to tell how long I have to wait for the index to be rotated. Not ideal that when you are are running out of space you have to potentially wait for a long time for the index to shrink, but at least knowing when it will happen next can help with planning.
