### ISSUE TITLE
Extend documentation about PromQL via curl

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#253]
**Is your feature request related to a problem? Please describe.**
I'm trying to understand how to apply PromQL queries via `/api/v1/export` end-point using curl syntax. But I find it difficult to understand how it should be properly done. The current example in [documentation](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#sending-opentsdb-data-via-http-apiput-requests) points to use a `match[]=...` argument, but does not provide **any** examples how to apply PromQL syntax.

**Describe the solution you'd like**
Please provide few example using curl command how to apply PromQL on certain data, e.g.
find matching record, calculate their rates of today, yesterday, etc.

**Describe alternatives you've considered**
I tried a simple queries, e.g.
```
curl -G 'http://myhost:port/api/v1/export' -d 'match[]={myKey="123"}' -d 'rate(myKey[5m])'
```
but I don't see desired results and I doubt that I'm doing this right. 

Please note, that I'm injecting data directly to VictoriaMetrics engine, w/o Prometheus, i.e. using OpenTSDB data via HTTP `/api/put` requests.

**Additional context**
Proper examples will significantly help to understand how PromQL should be used on records fetched from VictoriaMetrics via curl queries, especially if you'll complement them with ExtendedPromQL syntax.

**Comment by valyala** [comment]
Note that `/api/v1/export` doesn't accept PromQL - it accepts only [time series selectors](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors) - see the corresponding docs for [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series). Time series selectors don't support any functions - they support only time series names and label filters.

PromQL and Extended PromQL queries must be sent to `/api/v1/query` or `/api/v1/query_range` endpoints from [Prometheus querying API](https://prometheus.io/docs/prometheus/latest/querying/api/) supported by VictoriaMetrics.

**Comment by vkuznet** [comment]
Great, this is what I was looking for and it was unclear from main documentation. Feel free to add those examples and make it clear what each API can do. I'm closing the ticket.

**Comment by valyala** [comment]
Added a chapter to README.md about Prometheus querying API support in VictoriaMetrics - https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#prometheus-querying-api-usage .
