### ISSUE TITLE
rawRowsShard may occupy too much memory when create many partitions

### ISSUE THREAD

**Issue by flashmouse** [VictoriaMetrics/VictoriaMetrics#2546]
**Describe the bug**
partition hold timeseries data for 1 month, and each partition would have some rawRowsShard to avoid lock contention in write path. rawRowsShard count depend on cpu cores num and each rawRowsShard keep a slice of rawRow during the whole vmstorage process lifetime, in our scenaro this slice may use 6MB memory(depend on system memory and allowedMemory param). 

when user write data from 1970 to current time(2022, and may not include some month) , it would create about 500+ partitions, each partition hold one rawRowsShard with 6MB []rawRow, it would occupy about 3GB memory, but in fact we only write few data to each partition.

**Expected behavior**
for now we use vm with version 1.37.1.  we think the simplest way to resolve this problem is release rawRowsShard's []rawRow after execute rawRowsShard.flush().

we check the current cluster branch code, the method change to rawRowsShard.appendRawRowsToFlush(), but this function seems not release either.

after we add ``rrs.rows = nil `` in rawRowsShard.flush() function, vmstorage use only 400MB memory, before is more than 4GB.

**Version**
1.37.1
```

**Comment by valyala** [comment]
@flashmouse , thanks for the detailed issue!

Could you verify whether changing the following line to `n := 0` reduces memory usage for your workload?

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/123aa4c79e06a41560e2a8b9a57a46a85351139d/lib/storage/partition.go#L461

**Comment by flashmouse** [comment]
@valyala sorry upgrade the producttion env cluster may need time more than 2 weeks, but I believe in our usage scenaro make rawRowsShard slice default capacity with 0 should resolve our problem too because we really write only few datapoints to each partition. Although I think make this slice capacity 0 may not suitable for all usage scenario, it could be useful in most case.

**Comment by hagen1778** [comment]
> when user write data from 1970 to current time(2022, and may not include some month) , it would create about 500+

Won't this be limited by retention setting? 
Ofcourse, when retention set to infinite then VM will be vulnerable to such sparsed data. But in most cases rentention is always limit by couple of month or years. For case of 5y retention (which is already outstanding), the number of partitions will be only 60.

**Comment by flashmouse** [comment]
@hagen1778  yes set retention to save less time data should resolve the problem.
