### ISSUE TITLE
Spontaneous restart  pod vm-agent-victoria-metrics-operator

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/VictoriaMetrics#2548]
**Describe the bug**
It was noticed that pod vm-agent-victoria-metrics-operator restarts periodically, the following errors are present in the logs.
**To Reproduce**
Steps to reproduce the behavior.
`NAME                                                           READY   STATUS    RESTARTS   AGE`
`vm-agent-victoria-metrics-operator-56746bcc5d            1/1     Running   5          9d`
**Logs**
`{"level":"error","ts":1651703002.5890493,"logger":"setup","msg":"problem running manager","error":"leader election lost","stacktrace":"github.com/VictoriaMetrics/operator/internal/manager.RunManager\n\tgithub.com/VictoriaMetrics/operator/internal/manager/manager.go:290\nmain.main\n\t./main.go:41\nruntime.main\n\truntime/proc.go:250"}`
`{"level":"error","ts":1651703002.593215,"logger":"setup","msg":"cannot setup manager","error":"leader election lost","stacktrace":"main.main\n\t./main.go:43\nruntime.main\n\truntime/proc.go:250"}`

**Version**
victoria-metrics-k8s-stack-0.8.1 (APP VERSION 1.76.1)

Please tell me the solution to this problem.

**Comment by f41gh7** [comment]
For some reason, operator wasn't able to access kubernetes API server an update leader-election lease. 

 Will investigate it.

**Comment by hagen1778** [comment]
Closing as inactive. If the issue is still relevant please re-open at https://github.com/VictoriaMetrics/operator
