### ISSUE TITLE
Can't login to AWS 1.77.0

### ISSUE THREAD

**Issue by nikitachrs** [VictoriaMetrics/VictoriaMetrics#2550]
**Describe the bug**
There is a problem in aws service discovery: can't get information from AWS API URL. Previous version 1.76.1 works correctly. 

**To Reproduce**
Upgrade to 1.77.0 version. Access Key and Access Secret Key not changed.

**Expected behavior**
Can reach aws API URL.

**Logs**
`{"ts":"2022-05-06T11:21:01.426Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/config.go:916","msg":"skipping ec2_sd_config targets for job_name \"aws_ec2_node_exporter\" because of error: error when fetching instances data from EC2: cannot obtain instances: unexpected status code for \"https://ec2.ap-south-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=tag%3Aapplication&Filter.1.Value.1=cinema&Filter.1.Value.2=cinema-redis&Filter.1.Value.3=srtgateway&Filter.1.Value.4=mediator&Version=2013-10-15\"; got 401; want 200; response body: \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>28ef89d6-5038-411b-8a5a-952241b933fd</RequestID></Response>\""}`

**Comment by f41gh7** [comment]
Thanks for reporting, working on release with fix.

**Comment by valyala** [comment]
It looks like this issue is related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2551 . @nikitachrs , could you build `vmagent` from the commit 123aa4c79e06a41560e2a8b9a57a46a85351139d according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether this fixes the issue?

**Comment by valyala** [comment]
@nikitachrs , could you verify whether [vmagent v1.77.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) is free from this issue?

**Comment by nikitachrs** [comment]
It works. Thanks a lot for quick fix!
