### ISSUE TITLE
victoriametrics-cluster(not Enterprise)how to use downsampling?

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#2559]
I want to save the monitoring data for two years. If I don't downsampling the data for a long time, I can't allocate the required disk. So is there a solution?

**Comment by dmitryk-dk** [comment]
Hi @Shangchengzhi ! Thank you for your request! Can you check this link
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#downsampling
It must be helpful for you
