### ISSUE TITLE
How to avoid repeating alerts?

### ISSUE THREAD

**Issue by shriramholla-moveworks** [VictoriaMetrics/VictoriaMetrics#2562]
If an alert has already been sent, is there a way to set a threshold period before sending it again? And could this be customizable for specific groups or alerts?

**Comment by YuriKravetc** [comment]
Hi @shriramholla-moveworks,

It is possible.
This is configured on alertmanager side.
For example:
`repeat_interval: 3h` time can be customized.

Alerts can also be silenced.

Please refer to this info:
https://github.com/prometheus/alertmanager
https://prometheus.io/docs/alerting/latest/configuration/

**Comment by shriramholla-moveworks** [comment]
Hi @YuriKravetc , thanks for the response. How can I silence alerts? I was under the impression that that's what `repeat interval` does.

**Comment by YuriKravetc** [comment]
Not to my knowledge.
Please refer to:
https://prometheus.io/docs/alerting/latest/configuration/#route
