### ISSUE TITLE
vmagent: parallelism + scrape_timeout handling?

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#2563]
Wondering, how vmagent distributes the workload [for scraping static targets, only] and how it handles timeouts.

Assuming it has sufficient CPUs available, does vmagent create a "scrape worker"  for each target, which submit/handle scrapes in parallel? Or is it using just a single worker for each job, only?

If a timeout happens, does it simply skip the next query and waits 'til the last issued query gets answered?

My guts say no, because vmagent seems to set the `scrape_timeout` always to `scrape_interval`, if the latter is < scrape_timeout in the config. This could be one reason for possibly overloading the target and causing more headaches than needed, i.e. in my case for targets with 1s scrape_interval and many "downs" (~20%).

Otherwise, if it waits for the last query, is there an option to tell vmagent, how long max. to wait 'til it stops waiting and continues with a new query?

BTW: Loosing some packets (UDP/SNMP) or getting a timeout from time to time seems to be normal for some devices. Wondering, whether vmagent marks a target immediately as `down` and back offs for some time (configurable per job???) or uses some rules like "need at least 5 consecutive queries to fail before back off". And if it backs off, for how long? Some pointers to the related source code would be nice.

Last but not least I wonder, what this means:
```
> curl -s localhost:8429/targets | grep state=down
	state=down, endpoint=http://127.0.0.1:9116/snmp?compact=1&module=pdu_socket_desc&target=pdu-k30a-m, labels={gz="pdu-k30a",instance="127.0.0.1:9116",job="pdu_sockets"}, scrapes_total=0, scrapes_failed=0, last_scrape=1652148525.398s ago, scrape_duration=0ms, samples_scraped=0, error=
```
`last_scrape=1652148525.398s ago` seems to be odd. The scrape_interval for this job is 30m. vmagent is running for ~ 15m. If it is real that long ago, shouldn't it be scraped immediately?

**Comment by dmitryk-dk** [comment]
Hi @jelmd ! Thank you for your request! 

```Assuming it has sufficient CPUs available, does vmagent create a "scrape worker" for each target, which submit/handle scrapes in parallel? Or is it using just a single worker for each job, only?```

vmagent runs a scrape worker for each defined target in a separate goroutine.

```If a timeout happens, does it simply skip the next query and waits 'til the last issued query gets answered?```

Each target is processed in a separate goroutine, so fail on one target does not affect the others.

Correct. If scrapeTimeout > scrapeInterval then we set scrapeTimeout will be set to be equal with scrapeInterval
To answer on this question i think it is better to check this comment which explain how timeouts sets and why 
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1281#issuecomment-840538907

```Otherwise, if it waits for the last query, is there an option to tell vmagent, how long max. to wait ’til it stops waiting and continues with a new query?``

At that moment vmagent is waiting for a response as long as it is defined in scrape_timeout, and it hasn’t any other flags or config fields for that.

```BTW: Loosing some packets (UDP/SNMP) or getting a timeout from time to time seems to be normal for some devices. Wondering, whether vmagent marks a target immediately as down and back offs for some time (configurable per job???) or uses some rules like "need at least 5 consecutive queries to fail before back off". And if it backs off, for how long? Some pointers to the related source code would be nice.```

vmagent doesn't mark any target as down it always tries to scrape information and it uses scrape_interval for continues scrape

**Comment by jelmd** [comment]
Hi @dmitryk-dk,

thanx a lot for your answer :)

...
> vmagent runs a scrape worker for each defined target in a separate goroutine.

Ahh ok, so something like "sum(i=0..n-1, length(job[i].targets))" with n=number_of_jobs.

I've seen, that vmagent chomps quite a bit of RAM (RSS) and that this seems to  be related to the number of available CPU strands aka hyper threads and not really to the number of targets. E.g. we have on the global zone alias bare metal one vmagent running, which just scrapes 3-4 targets on the localhost (node-exporter, nvmex (GPU agent), vmagent itself and depending on the platform ipmimex (IPMI agent)) but has depending on the box 20..96 strands available. By restricting the service with `AllowedCPUs=0-3` to 4 strands we got it to behave as expected, i.e. limit its RSS usage to an acceptable level (BTW: setting the env var `GOMAXPROCS` had no effect at all).

So would probably a good thing, if vmagent would align its resource usage automagically to the number of real scrape workers|targets?

...
> Each target is processed in a separate goroutine, so fail on one target does not affect the others.

OK.

> Correct. If scrapeTimeout > scrapeInterval then we set scrapeTimeout will be set to be equal with scrapeInterval To answer on this question i think it is better to check this comment which explain how timeouts sets and why [#1281 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1281#issuecomment-840538907)
> ...
> At that moment vmagent is waiting for a response as long as it is defined in scrape_timeout, and it hasn’t any other flags or config fields for that.

Aha, so wrt. a certain target a scrape worker's behavior can be taken as single threaded.

> `BTW: Loosing some packets (UDP/SNMP) or getting a timeout from time to time seems to be normal for some devices. Wondering, whether vmagent marks a target immediately as down and back offs for some time (configurable per job???) or uses some rules like "need at least 5 consecutive queries to fail before back off". And if it backs off, for how long? Some pointers to the related source code would be nice.`
> 
> vmagent doesn't mark any target as down it always tries to scrape information and it uses scrape_interval for continues scrape

Thought I've read something like "timeout gets doubled each time a scrape fails". But perhaps I mixed it up with submitting the data to vmdb ... ;-) With `down` I mean the state wrt. `curl -s localhost:8429/targets`.

**Comment by dmitryk-dk** [comment]
@jelmd can we close the issue?

**Comment by jelmd** [comment]
Hmmm, haven't checked yet, whether it (job/threading) found its way into the documentation. Did it?
The other point was vmagent's self-adjustment wrt. targets to scrape. As said, on "many-CPUs" systems it consumes a lot of memory, even if it needs to scrape 2-3 simple targets, only.

**Comment by jiekun** [comment]
@jelmd Hi! Thanks for raising the issue. It seems the original questions are answered. 

> on "many-CPUs" systems it consumes a lot of memory, even if it needs to scrape 2-3 simple targets, only.

I think `vmagent` does not cost **a lot of memory**. Could you provide some detailed resource data on your setup? Also, it would be nice if you could update to the latest version which contains many optimization and bugfix.
