### ISSUE TITLE
Add the time zone of indexdb rotation duration

### ISSUE THREAD

**Issue by cnych** [VictoriaMetrics/VictoriaMetrics#2568]
**Still about the time of indexdb rotation**

Regarding the time of indexdb rotation, according to the current algorithm, the rotation will normally start at 4:00 UTC.

```go
func nextRetentionDuration(retentionMsecs int64) time.Duration {
	// Round retentionMsecs to days. This guarantees that per-day inverted index works as expected.
	retentionMsecs = ((retentionMsecs + msecPerDay - 1) / msecPerDay) * msecPerDay

	t := time.Now().UnixNano() / 1e6
	deadline := ((t + retentionMsecs - 1) / retentionMsecs) * retentionMsecs

	// Schedule the deadline to +4 hours from the next retention period start.
	// This should prevent from possible double deletion of indexdb
	// due to time drift - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/248 .
	deadline += 4*3600*1000

	return time.Duration(deadline-t) * time.Millisecond
}
```

But due to the time zone problem, for example, we are in the **+8 time zone**, then the index will be rotated at **12:00**, and `this the business is relatively busy at the point in time`, and the index rotation will cause vminsert and vmselect to be slow. Although it has been optimized in the [1401](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401) problem and is now alleviated, but this problem still exists.

**Add the offset of the time zone**

Is it possible to add the offset of the time zone when calculating the index rotation time, so that we can start the rotation at 4 o'clock in the local time, which can avoid the busy time of the business, as shown below.

```go
func nextRetentionDuration(retentionMsecs int64) time.Duration {
	// Round retentionMsecs to days. This guarantees that per-day inverted index works as expected.
	retentionMsecs = ((retentionMsecs + msecPerDay - 1) / msecPerDay) * msecPerDay

	t := time.Now().UnixNano() / 1e6
	deadline := ((t + retentionMsecs - 1) / retentionMsecs) * retentionMsecs

	// Schedule the deadline to +4 hours from the next retention period start.
	// This should prevent from possible double deletion of indexdb
	// due to time drift - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/248 .

	_, offset := time.Now().Zone()
	deadline += 4*3600*1000 - int64(offset)*1000

	return time.Duration(deadline-t) * time.Millisecond
}
```

**Comment by valyala** [comment]
FYI, this feature has been implemented starting from [VictoriaMetrics v1.78.0](https://docs.victoriametrics.com/CHANGELOG.html#v1780). Closing the feature request as done.
