### ISSUE TITLE
vmalert: humanizeDuration not entirely Prometheus compatible

### ISSUE THREAD

**Issue by TamCore** [VictoriaMetrics/VictoriaMetrics#2569]
**Describe the bug**
Upstream Prometheus lists "number or string" for humanizeDuration input [1] However, vmalert expects float64[2] and therefore fails if the argument passed is a string:
```
executing "" at <humanizeDuration>: wrong type for value; expected float64; got string
```
The kube-prometheus-stack (which we're trying to replace) passes a string to humanizeDuration[3], which makes it harder to deploy VictoriaMetrics as a replacement for Prometheus, without having to make changes to existing deployments.

Therefore, for compatibility reasons VMAlert should also be able to handle it if the passed argument is a string instead of a float64.

[1] https://prometheus.io/docs/prometheus/latest/configuration/template_reference/
[2] https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/notifier/template_func.go#L163
[3] https://github.com/prometheus-community/helm-charts/blob/d6c45e97eca55e6212ef8acf546b45aa7851c72e/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kubernetes-apps.yaml#L259

**Comment by flokli** [comment]
Was this fixed by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2606?

**Comment by flokli** [comment]
Im not entirely sure how this interacts with all the different layers of the stack - in my case, I was importing some official PrometheusRules, which got converted to VMRules, which vmalert was configured with. I assume i need at least https://github.com/VictoriaMetrics/helm-charts/issues/331, so the operator contains https://github.com/VictoriaMetrics/operator/commit/f468ae02690e79ed72638f845535d19418b042af, no?

**Comment by f41gh7** [comment]
You can build vmalert docker image from source and push it to your own docker repository:
```bash
make package-vmalert
docker tag victoria-metrics/vmalert:version my-repo:my-version-name
docker push my-repo:my-version-name
```
Configure `victoria-metrics-k8s-stack` or `VMAlert` CR object with own docker image for vmalert.

```yaml
kind: VMAlert
spec:
  image:
    repository: my-repo
    tag: my-version-name
```

**Comment by flokli** [comment]
I pushed `flokli/vmalert:heads-master-0-ge79a1d147` and can confirm `PrometheusRules` alerts from https://github.com/monitoring-mixins/website/tree/master/assets/kubernetes (`{alerts,rules}.yaml`) are successfully parsed with that. Thanks!

**Comment by valyala** [comment]
vmalert supports `humanize*` templates in the same way as Prometheus does starting from [v1.77.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
