### ISSUE TITLE
Question: Label value modification

### ISSUE THREAD

**Issue by DMANSUTTI** [VictoriaMetrics/VictoriaMetrics#257]
Hello,

Is there a way to rename a label value of a time series in the storage so that any further requests will return this value. I am aware of the label_transform query but as far as I know the transformed value cannot be used in further queries to VictoriaMetrics.

Thanks for your help.

**Comment by valyala** [comment]
Labels cannot be modified in VictoriaMetrics storage.

There is [label_replace](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace) function from standard PromQL, plus various `label_*` functions from [extended PromQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL). These functions can be used for label renaming during queries.

@DMANSUTTI , what is your use case for label renaming on the storage level? Probably it is worth implementing.

**Comment by valyala** [comment]
@DMANSUTTI , label values can be modified with relabeling rules in [vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md) before being written into VictoriaMetrics.

**Comment by DMANSUTTI** [comment]
Thanks. I am closing the issue as I can work with that.
