### ISSUE TITLE
Unable to talk to dualstacked endpoints from single-stacked pods (Custom IPv6 disabling logic seems broken)

### ISSUE THREAD

**Issue by flokli** [VictoriaMetrics/VictoriaMetrics#2573]
**Describe the bug**
I have a `vmalert` pod (`v1.76.0`), described by a `VMAlert` CR.

In the `VMAlert.spec.datasource.url`, `VMAlert.spec.remote{Read,Write}.url` fields, a https://monitoring.some-domain.com/prometheus URL is configured. Basic auth is used.

The URL (outside of the cluster) is publicly reachable and has both A and AAAA records. From a dualstacked computer, I'm able to both curl with -4 and -6 parameters successfully.

The k8s cluster itself is dualstack capable, but the specific pod only has a (private) IPv4 address, and IPv6 link-local:

```
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
4: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN qlen 1000
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
5: eth0@if15: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP 
    link/ether 36:2a:94:35:35:a2 brd ff:ff:ff:ff:ff:ff
    inet 10.244.3.5/24 brd 10.244.3.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::342a:94ff:fe35:35a2/64 scope link 
       valid_lft forever preferred_lft forever
```

The machine has no IPv6 default route.

The alerts are not being updated properly. In the Logs, I see error messages about vmalert not being able to reach one of the IPv6 adresses behind the hostname:

```
vmalert 2022-05-12T20:11:49.772Z    error    VictoriaMetrics/app/vmalert/group.go:279    group "kubelet.rules": rule "node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile": failed to execute: failed to execute query "histogram_quantile(0.99, sum(rate(kubelet_pleg_relist_duration_seconds_bucket[5m])) by (instance, le) * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\", metrics_path=\"/metrics\"})\n": error getting response from https://monitoring.somedomain.com/prometheus/api/v1/query?query=histogram_quantile%280.99%2C+sum%28rate%28kubelet_pleg_relist_duration_seconds_bucket%5B5m%5D%29%29+by+%28instance%2C+le%29+%2A+on%28instance%29+group_left%28node%29+kubelet_node_name%7Bjob%3D%22kubelet%22%2C+metrics_path%3D%22%2Fmetrics%22%7D%29%0A&step=60s&time=1652386200: Post "https://monitoring.somedomain.com/prometheus/api/v1/query?query=histogram_quantile%280.99%2C+sum%28rate%28kubelet_pleg_relist_duration_seconds_bucket%5B5m%5D%29%29+by+%28instance%2C+le%29+%2A+on%28instance%29+group_left%28node%29+kubelet_node_name%7Bjob%3D%22kubelet%22%2C+metrics_path%3D%22%2Fmetrics%22%7D%29%0A&step=60s&time=1652386200": dial tcp [2a06:98c1:xxxx::a]:443: connect: network is unreachable
```

This was very confusing. I suspect the custom dialer config in `VictoriaMetrics/lib/netutil/tcplistener.go` to be the culprit. This doesn't seem to be a problem if a normal `http.Client` is used.

I wasn't able to check if things work if I manually set `-enableTCP6` in the command line, as it's not exposed in the `VMAlert` CRDs.

IMHO, disabling IPv6 is an antipattern, especially with https://kubernetes.io/docs/concepts/services-networking/dual-stack/ being stable.

Services should bind on both address families by default, and try to use both address families to establish connections (preferring IPv6, as per https://datatracker.ietf.org/doc/html/rfc6724#section-10.3).

I'd assume if we'd just drop all the custom dialing config, things might just work.

**Comment by f41gh7** [comment]
Can you try following flag:
```
kind: VMAlert
spec:
  extraArgs: 
     enableTCP6: "true"
```

 `ipv6`, by default, disabled for security purpose. It reduces attack surface. For instance, if you didn't configure ipv6 firewall properly, attacker could connect to your webserver. It may be surprising for common users.

**Comment by flokli** [comment]
> ipv6, by default, disabled for security purpose. It reduces attack surface. For instance, if you didn't configure ipv6 firewall properly, attacker could connect to your webserver. It may be surprising for common users.

I couldn't disagree more with this statement. :disappointed:  Most "common" users have a stateful firewall in their home router (so this is not an issue). Same applies to corporate users - they probably just don't configure IPv6 in their networks, or do apply similar firewalling.

In all cases, this shouldn't be a concern for VM itself, and having explicit logic for this in VictoriaMetrics is the wrong approach, and prone to create bugs such as the ones we see here.

Also, the described risk applies to all applications running on such host, not just VictoriaMetrics.

> Can you try following flag:

I tried, but now the healthchecks fail, probably as VM itself now *only* listens on IPv6 (and the host only has a IPv6 link-local address. This again wouldn't be a problem if it would use the Go defaults.

**Comment by f41gh7** [comment]
@flokli , Sorry for delay, I've double checked ipv6 issues.

 In your case, vmalert doesn't use custom dialer and enableTCP6 has effect only for listener, not a client. vmalert uses standard golang http client for VictoriaMetrics connection.

 Possible issues:
- there is an issue with cluster dns server and it returns only AAAA record, try dig within vmalert container
- access blocked by some firewall rule, check within vmalert container, that remote host is reachable via wget or curl (curl preferred).

**Comment by flokli** [comment]
I can't reproduce the odd behaviour with dualstacked endpoints anymore either :thinking:. Sorry.

What's the plan for

```
kind: VMAlert
spec:
  extraArgs: 
     enableTCP6: "true"
```
, and this breaking the (IPv4) healthchecks? Could `enableTCP6` listen on both IPv4 and IPv6? Aka, using `tcp` protocol instead of `tcp4`/`tcp6` explicitly?

**Comment by f41gh7** [comment]
`enableTCP6` - enables dual-stack mode, http server starts to listen at ipv4 and ipv6 addresses.

 For now, there is no only ipv6 mode, where ipv4 will be explicitly disabled.
