### ISSUE TITLE
log aggregation of scrape errors

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#2575]
Right now vmagent has all-or-nothing support for logging scrape errors. This is not really a proper behavior for enterprise apps: Loosing completely control/having no clue what's going on is not an option at all. But logging every single scrape error may  consume a huge amount of resources (IO, CPU, disk), is hard to read to get any sense of it and thus is not an option either.

A good compromise is IMHO to aggregate scrape errors for a certain time, and log it, when the next error occurs (similar as syslog does).

E.g. for certain SNMP devices it is normal to skip requests or to handle them with a low priority so that timeouts occur.
We scrape ~50 targets, only. But even with such a small amount of targets we see vmagent's excessive logging: ~ 64 GB/d uncompressed. If vmagent would aggregate them and remove most of the redundant information, even with a 1 min period, the log gets reduced to ~ 3 GB/d.

IMHO a default aggregation time of 10 min would make sense, which would reduce it to ~300 MB/d. Example is attached.
[vmagent-log.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8684051/vmagent-log.txt)

**Comment by valyala** [comment]
vmagent supports `-promscrape.suppressScrapeErrorsDelay` command-line flag starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). This flag allows suppressing repeated scrape errors during the configured duration on a per-target basis. Closing the feature request as done.
