### ISSUE TITLE
Publish ARM images to docker-hub

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#258]
**Is your feature request related to a problem? Please describe.**
Would be good to have ARM (32 and 64) images in docker hub

**Describe the solution you'd like**
Able to using docker hub instead of building images from sources 

Currently ARM images can be built from sources according to [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#arm-build).

**Comment by valyala** [comment]
Docker images for the following architectures are published starting from [v1.31.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases):
* amd64
* arm
* arm64
* ppc64le
* 386

See https://hub.docker.com/r/victoriametrics/victoria-metrics/tags .

**Comment by syepes** [comment]
Great stuff as always! thanks
