### ISSUE TITLE
vmalert: support `/rules` path for Grafana Alerting UI

### ISSUE THREAD

**Issue by vpedosyuk** [VictoriaMetrics/VictoriaMetrics#2583]
**Is your feature request related to a problem? Please describe.**
There's a new feature in v1.77.0 that allows proxying alerting requests from Grafana (v8.4.7) via `-vmalert.proxyURL` parameter. It works fine but Grafana complains that:

```
Failed to load rules config from <VM>: remoteAddr: "10.0.98.3:34878", X-Forwarded-For: "10.0.2.94"; requestURI: /rules; unsupported path requested: "/rules"
```

and in vmalert logs:
```
{"ts":"2022-05-13T15:08:30.501Z","level":"warn","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:319","msg":"remoteAddr: \"10.0.88.3:48656\", X-Forwarded-For: \"10.0.2.94\"; requestURI: /rules; unsupported path requested: \"/rules\""}
```

**Describe the solution you'd like**
vmalert supports `http://<vmalert-addr>/rules` path in addition to `http://<vmalert-addr>/api/v1/rules` like Prometheus does:
https://prometheus.io/docs/prometheus/latest/querying/api/#rules

**Additional context**
<img width="1356" alt="Знімок екрана 2022-05-13 о 18 09 54" src="https://user-images.githubusercontent.com/16594968/168315396-d8ba5c9e-8fd5-42fa-b921-3cf3f222f742.png">

**Comment by valyala** [comment]
vmalert should support `/rules` path needed for Grafana Alerting UI starting from [v1.77.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
