### ISSUE TITLE
Chinese chars bug

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#2585]
**Describe the bug**
when i write data like   
xxx_bu{bu_name='你好'} 1111
xxx_bu{bu_name='你好啊'} 1111
it will cause bugs
Chinese chars shows not correct, how to fix it ? thank you

**Screenshots**
![image](https://user-images.githubusercontent.com/6347394/168413964-14a77d49-fb83-44f5-bff8-b7aaf9df12b6.png)

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./victoria-metrics-prod --version
victoriametrics-cluster-v1.51.0
```

**Comment by denisgolius** [comment]
Hi @davidsome !
Could you check that your browser use `charset=utf-8` and if it not, try to set it check that issue will reproduce?

**Comment by davidsome** [comment]
it is ok now, thanks
