### ISSUE TITLE
bootstrap.js cann't load 

### ISSUE THREAD

**Issue by xiaoweihong** [VictoriaMetrics/VictoriaMetrics#2594]
**Describe the bug**
when i deploy vmagent-prod on my machine.i open chrome and found the bootstrap.js load from cdn. I can not visit it,can js in local file?

**To Reproduce**
![image](https://user-images.githubusercontent.com/13499653/168541319-50a50835-3230-428b-8f10-a15a65c59762.png)

**Version**

```
$ ./victoria-metrics-prod --version
./vmagent-prod --version
vmagent-20220506-230448-tags-v1.77.1-0-g043363750
```

**Comment by dmitryk-dk** [comment]
Hi @xiaoweihong ! Thank you for your issue. But can you reload the page. It is cdn and it must load everywhere.

**Comment by xiaoweihong** [comment]
I use it in the place that have no internet



---Original---
From: "Dmytro ***@***.***&gt;
Date: Mon, May 16, 2022 15:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [VictoriaMetrics/VictoriaMetrics] bootstrap.js cann't load (Issue #2594)




 
Hi @xiaoweihong ! Thank you for your issue. But can you reload the page. It is cdn and it must load everywhere.

**Comment by xiaoweihong** [comment]
sorry for replay late. It's perfect now.
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/13499653/172108737-936c0016-07a6-473b-8f57-97957b8e6b67.png">
