### ISSUE TITLE
Regular expression label match with empty group sometimes does not match expected result

### ISSUE THREAD

**Issue by rbizos** [VictoriaMetrics/VictoriaMetrics#2597]
We are using grafana variables that are sometimes empty. Such variables are `()` when there is no label and should match metrics without this label.

This is sometimes the case, sometimes not, for instance:

`dc:prometheus_tsdb_head_series:sum{perimeter=~"perimeter-a", shard=~"()"}` 
matches a subset of  
`dc:prometheus_tsdb_head_series:sum{perimeter=~"perimeter-a"}`

`dc:prometheus_tsdb_head_series:sum{perimeter=~"perimeter-a|perimeter-b", shard=~"()"}`
  matches a subset of 
`dc:prometheus_tsdb_head_series:sum{perimeter=~"perimeter-b|perimeter-a"}`
but  different from
`dc:prometheus_tsdb_head_series:sum{perimeter=~"perimeter-a", shard=~"()"} or dc:prometheus_tsdb_head_series:sum{perimeter=~"perimeter-b", shard=~"()"}`

We are using currently VictoriaMetrics in cluster with version 1.73.1

**Comment by hagen1778** [comment]
Hi @rbizos! There were multiple fixes for regex matching in 1.74, 1.75 and 1.77. Could you please try to update and check if issue still persists?

**Comment by rbizos** [comment]
Hey @hagen1778 let me try asap :)

**Comment by rbizos** [comment]
Against 1.76.1 I can't reproduce, it seems that the issue was fixed in the process. Great :)
