### ISSUE TITLE
vmagent：Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by qiu-peng20** [VictoriaMetrics/VictoriaMetrics#2599]
Hi，When I grab the data, vmagent reports an error
![image](https://user-images.githubusercontent.com/55682965/168781000-db4a22cb-aa63-4055-b9e3-0718ef7156cd.png)
Is there any way to solve this problem please?/(ㄒoㄒ)/~~

**Comment by hagen1778** [comment]
@qiu-peng20 according to the error message you're using wrong address for the targets. It suggests you change `http` to `https` scheme.

**Comment by srihas** [comment]
@hagen1778 when vmagent is configured with a job "kubernetes_sd_configs" and role: pod, and even though pod is 
annotated with "prometheus.io/scheme: https", i see similar issue.

$ kubectl get pod <pod_name>-o json | jq '.metadata.annotations'
{
  "prometheus.io/path": "/metrics",
  "prometheus.io/port": "8080",
  "prometheus.io/scheme": "https",
  "prometheus.io/scrape": "true"
}


job="kubernetes-pods"(10/19 up)
    state=up, endpoint=http://192.168.170.18:9000/minio/prometheus/metrics, labels={instance="192.168.170.18:9000",job="kubernetes-pods"}, scrapes_total=5, scrapes_failed=0, last_scrape=47.513s ago, scrape_duration=106ms, samples_scraped=263, error=
    state=down, endpoint=http://192.168.170.23:8080/metrics, labels={instance="192.168.170.23:8080",job="kubernetes-pods"}, scrapes_total=5, scrapes_failed=5, last_scrape=99.654s ago, scrape_duration=1ms, samples_scraped=0, error=unexpected status code returned when scraping "http://192.168.170.23:8080/metrics": 400; expecting 200; response body: "<mark>Client sent an HTTP request to an HTTPS server.</mark>\n"
