### ISSUE TITLE
Add ability to sign requests for all AWS services

### ISSUE THREAD

**Issue by transacid** [VictoriaMetrics/VictoriaMetrics#2605]
**Is your feature request related to a problem? Please describe.**
We are running VictoriaMetrics in an EKS cluster in AWS and would like to use API gateway for authentication. To sign requests for the API gateway the "service" needs to be "execute-api". However vmAgent hard codes it to be "aps.

**Describe the solution you'd like**
I have prepared #2604 with a posiible solution

**Comment by transacid** [comment]
thanks for merging. I believe we can close the issue

**Comment by valyala** [comment]
We usually close issues after publishing the release with the corresponding change. @transacid , thanks for the [pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2604)!

**Comment by valyala** [comment]
The [pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2604) has been included into `vmagent` and single-node VictoriaMetrics starting from [v1.77.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
