### ISSUE TITLE
vmalert slow startup due to state restoring for alerts

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/VictoriaMetrics#2608]
**Describe the bug**
During migration to VictoriaMetrics stack from `Thanos`(Thanos-ruler in this case), we found out that `vmalert` slowly loads our Recording rules and Alerting rules (we have around `600` groups to be loaded), it looks like it loads them sequentially. 
There are two problems here:
- Vmalert starts the HTTP server only after loading all groups, which affects `/health` page, so we have to increase time waiting for HEALTH page up to 5 minutes
- We run our workload on preemptible nodes at GCP, so we get vmalart Pod restarted at least once per day. Every time on restart, we don't have all recording rules evaluated for 5 minutes. Of course, we can run more `vmalerts` in parallel, but then we will double load on our Storage (we plan to run 2 instances of `vmalert` in future after migration from Thanos-Ruler).

**To Reproduce**
Configure more than 500 groups with 5-10 rules per group

**Expected behavior**
Vmalert loads groups in parallel at least within `evaluation_interval`

**Screenshots**
here on the screenshot you can see how long we can observe messages like `group GROUP_NAME started`
<img width="1242" alt="Screenshot 2022-05-17 at 16 38 09" src="https://user-images.githubusercontent.com/5423271/168847181-719db2ad-19ba-45db-b21f-e80f7822c8b6.png">
and here the same time, but with message timestamps, some of them loads in seconds
<img width="1194" alt="Screenshot 2022-05-17 at 16 44 28" src="https://user-images.githubusercontent.com/5423271/168847304-fdc2a764-bca0-4948-b985-4615b85c1818.png">
and here we can see how it looks from resource consumption perspective 
<img width="1384" alt="Screenshot 2022-05-17 at 16 39 18" src="https://user-images.githubusercontent.com/5423271/168847451-10071f1b-883d-438d-8630-a310a57928be.png">

**Version**
```
/ # /vmalert-prod --version
vmalert-20220506-231252-tags-v1.77.1-0-g043363750
```

**Used command-line flags**
```
  vmalert:
    Image:        ****/vmalert:v1.77.1
    Port:          8880/TCP
    Host Port:     0/TCP
    Args:
      -datasource.url=https://promxy-url
      -evaluationInterval=20s
      -httpListenAddr=:8880
      -notifier.url=http://localhost:9093 # nothing there
      -remoteRead.url=https://promxy-url
      -remoteWrite.url=http://vvmagent.svc.cluster.local:8429
      -rule="/etc/vmalert/config/vm-vmalert-cloud-rulefiles-0/*.yaml"
      -rule="/etc/vmalert/config/vm-vmalert-cloud-rulefiles-1/*.yaml"
      -rule="/etc/vmalert/config/vm-vmalert-cloud-rulefiles-2/*.yaml"
      -rule="/etc/vmalert/config/vm-vmalert-cloud-rulefiles-3/*.yaml"
```

**Comment by hagen1778** [comment]
Hi @Vladikamira! Groups start concurrently - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1fad4dc91992616dd7b1c361a2f4b3fe305ae5fc/app/vmalert/manager.go#L81-L84
But there is a `state-restore` phase before starting the group - it is performed [sequentially](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1fad4dc91992616dd7b1c361a2f4b3fe305ae5fc/app/vmalert/manager.go#L69-L77). Could you please verify that by checking number of read requests served by VictoriaMetrics during vmalert startup? Are there any really slow requests?

**Comment by Vladikamira** [comment]
Thanks @hagen1778 for such a fast response!
Indeed, I tried to feed `recording rules` and `alerts` to VMalert separately, and I saw that there were no problems with `recording-rules`, loaded almost simultaneously, But for `alerts` I observed the same 'slow start' as before.
Then I configured `remoteRead` for `VMalert` to the store where we store all results directly without extra `GLOBAL VIEW` hop, which wasn't necessary 😅. Here I probably have to explain that we have multiple layers of components:
```
Promxy (Global) --> Promxy (Cloud) --> Promxy ( per k8s cluster) --> VictoriaMetrics
```
so, previously it was pointed to `Promxy (Cloud)` with backends in US and EU, which can explain slow responses from storage. Now it looks directly to `Promxy (per k8s cluster)` which is located at the same Region.
Anyway, thanks for your explanation and help! 🙏 I think we can close this issue 😄

**Comment by hagen1778** [comment]
I think you had a valid point here. We could optimize the loading speed by requesting all series for state restore at once. The response can be cached and used by groups without need in sending separate requests.
I'll transform this issue into an enhancement request. Thanks for pointing this out!

**Comment by valyala** [comment]
`vmalert` should perform restore procedure for alerts' state much faster since [v1.87.1 release](https://docs.victoriametrics.com/CHANGELOG.html#v1871). Closing the issue as resolved then.
