### ISSUE TITLE
The loss was attributed to Prometheus "NaN" metrics

### ISSUE THREAD

**Issue by uppercaveman** [VictoriaMetrics/VictoriaMetrics#261]
"/api/v1/write", the metric of the special numeric type "NaN" is lost after processing data received prometheus data processing.

For example, such a metric：
prometheus_tsdb_wal_fsync_duration_seconds{quantile="0.5"} NaN
prometheus_tsdb_wal_fsync_duration_seconds{quantile="0.9"} NaN
prometheus_tsdb_wal_fsync_duration_seconds{quantile="0.99"} NaN

**Comment by valyala** [comment]
VictoriaMetrics strips all the `NaN` data points passed to it, since they mean `no value`. @uppercaveman , could you describe your use case when `NaN` values are needed?

**Comment by uppercaveman** [comment]
I see, I just checked the metrics from prometheus to VictoriaMetrics and found that the numbers were inconsistent, and checked the reasons. There are currently no case using NaN. @valyala, thanks for your reply.
