### ISSUE TITLE
Add metrics to show the downsampling state

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2612]
**Is your feature request related to a problem? Please describe.**
When downsampling is enabled, there is no a clear way to detect if it has started or what is the progress.

**Describe the solution you'd like**
Would be great to have metric gauge like `vm_storage_downsampling_partitions_scheduled` showing the
number of partitions which weren't downsampled yet. Additionally, it could contain a label `partition="<name>"`
so it would be easier to understand which partitions weren't processed yet.

**Describe alternatives you've considered**
Check the log messages.

**Additional context**
This metric would be good addition to the Grafana dashboard

cc @f41gh7

**Comment by freeseacher** [comment]
as far as i can see we already have some traces of downsampling is in progress. In vm_rows_merged_total metric. 
Maybe we can add modify vm_rows_merged_total and add reason. For example like this `vm_rows_merged_total{reason="downsample|final_merge|big_block",  type="storage/big"}}`

**Comment by valyala** [comment]
FYI, the `vm_storage_downsampling_partitions_scheduled` and `vm_storage_downsampling_partitions_scheduled_size_bytes` metrics were incorrectly updated in the previous releases. This has been fixed in [the release v1.85.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
The bugfix mentioned in the previous message has been also included in [v1.79.7 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.7).
