### ISSUE TITLE
about use of cluster

### ISSUE THREAD

**Issue by bruse-peng** [VictoriaMetrics/VictoriaMetrics#2614]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Single-node VictoriaMetrics has discovered targets list  below but when i  install cluster VictoriaMetrics, i can not find the discovered targets the document did not show 
![1](https://user-images.githubusercontent.com/47881861/169200631-976594c3-6a04-4546-a956-b1bab67d83dd.jpg)

**Comment by YuriKravetc** [comment]
Hi,
For cluster - you might be using vmagent, and it should be checked from there.
https://docs.victoriametrics.com/url-examples.html#apiv1targets

**Comment by bruse-peng** [comment]
> Hi, For cluster - you might be using vmagent, and it should be checked from there. https://docs.victoriametrics.com/url-examples.html#apiv1targets

yes  i get it, does the VictoriaMetrics occupied 1/7 resource Compared with prometheus?  it has test data ?

**Comment by YuriKravetc** [comment]
It is difficult to give any exact numbers as there are differences for all possible setups.
Though you can perform a benchmark test for your specific case to be sure, or refer to the existing ones:
https://docs.victoriametrics.com/Articles.html#benchmarks

**Comment by bruse-peng** [comment]
> It is difficult to give any exact numbers as there are differences for all possible setups. Though you can perform a benchmark test for your specific case to be sure, or refer to the existing ones: https://docs.victoriametrics.com/Articles.html#benchmarks


 i add datasource in grafana  http://victoria-metrics-victoria-metrics-cluster-vmselect:8481/select/1/prometheus  it test successful, but when i  query metric in grafana it return empty
![image](https://user-images.githubusercontent.com/47881861/169991121-28fe8fc3-aac9-4f06-85c7-cb8652efd470.png)


but i can query it on vmui below
![image](https://user-images.githubusercontent.com/47881861/169991312-b1c72264-9659-45f1-ad23-c0c4dd73ccef.png)

**Comment by jiekun** [comment]
@bruse-peng Hi Could you test it again and provide more information? It's not likely to happen, so I would like to ask you to check the datasource URL and VMUI's URL and see if they are different. I'm closing it for now due to inactivity. But please don't hesitate to re-open it if you need more help on it.
