### ISSUE TITLE
VMalert: Expose inteval per group as a metric

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/VictoriaMetrics#2618]
**Describe the solution you'd like**
It would be great to have a metric like `vmalert_iteration_interval_seconds` exposed by `Vmalert` which would show an evaluation interval as a value for each group configured in Config file. 
If we have that, we can calculate kind of Utilisation of recrding-rules/alerts evaluation like that:
```
(vmalert_iteration_duration_seconds / vmalert_iteration_interval_seconds) * 100
``` 
we had such a dashboard for Thanos-Ruler before with metrics
```
( prometheus_rule_group_last_duration_seconds / prometheus_rule_group_interval_seconds ) * 100
```
On which we heavily rely as the main indicator of our Metrics platform Health and Performance

**Comment by hagen1778** [comment]
Hi @Vladikamira! Please take a look at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2623 and let me know what you think.

**Comment by valyala** [comment]
vmalert exposes `vmalert_iteration_interval_seconds` metric starting from [v1.77.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
