### ISSUE TITLE
How can we block writes over some accountID in victoria-metrics

### ISSUE THREAD

**Issue by lav-kush** [VictoriaMetrics/VictoriaMetrics#2627]
In victoria-metrics random accountID is permitted where we can write/query data.
Is it possible to restrict/permit only defined accountID?

Say, we have 2 accounts 01, 02 where we want to allow to write and read using vmselect/vminsert apis.
So, can we block writes/read on other accountIds?

**Comment by denisgolius** [comment]
> In victoria-metrics random accountID is permitted where we can write/query data. Is it possible to restrict/permit only defined accountID?
> 
> Say, we have 2 accounts 01, 02 where we want to allow to write and read using vmselect/vminsert apis. So, can we block writes/read on other accountIds?

Hi @lav-kush !
You can use [vmauth](https://docs.victoriametrics.com/vmauth.html#auth-config) for this case where you can set needed rights for authorization and write/read data through it.

**Comment by lav-kush** [comment]
@denisgolius 
Users can still write/read data to/from vminsert/vmselect endpoints.

> You can use vmauth for this case where you can set needed rights for authorization and write/read data through it.
This can happen only if users would write/read to/from vmauth endpoint.
But if user would be aware about the vminsert/vmselect endpoints, they can use those.

Any suggestion, how we can prevent write/read to vminsert/vmselect by vmauth only not by any users directly?
