### ISSUE TITLE
Question: the concurrent flush rate has spikes

### ISSUE THREAD

**Issue by eddietanshuo** [VictoriaMetrics/VictoriaMetrics#2630]
The concurrent flush sometimes reaches the cgroup's limit:
![image](https://user-images.githubusercontent.com/103412360/169731262-3463096f-dc6a-455b-a6da-7d08151cb83c.png)

The cpu load is very stable
![image](https://user-images.githubusercontent.com/103412360/169731378-b0501f8b-e258-4557-b7b7-ad1832b43f9a.png)

The num of  goroutines is also not very high:
![image](https://user-images.githubusercontent.com/103412360/169731655-7f21e1f3-be2d-4398-982f-e700bc0e955b.png)

Is this a expected phenomenon?

**Comment by YuriKravetc** [comment]
Hi,
It seems like the storage is overloaded ad requires more CPU.
![image](https://user-images.githubusercontent.com/30324382/169822929-6dd7cd77-af88-4bbf-90fe-0b82025ee47c.png)

**Comment by eddietanshuo** [comment]
Thanks for reply, get it~
