### ISSUE TITLE
1.77.2How to store and write Chinese characters

### ISSUE THREAD

**Issue by TroyPotte** [VictoriaMetrics/VictoriaMetrics#2634]
I use teleraf plug-in to write data to vmstorage, but I can't store string data. I can't query string data using Prometheus querying API. What can I do to solve it? Thank you

**Comment by denisgolius** [comment]
> I use teleraf plug-in to write data to vmstorage, but I can't store string data. I can't query string data using Prometheus querying API. What can I do to solve it? Thank you

Hi @TroyPotte !
VictoriaMetrics do not store string data as InfluxDB/etc. Please refer:
1. https://docs.victoriametrics.com/Quick-Start.html
2. https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf
3. https://docs.victoriametrics.com/guides/migrate-from-influx.html

**Comment by TroyPotte** [comment]
thanks
