### ISSUE TITLE
alert_relabel_configs is not working with static_configs only

### ISSUE THREAD

**Issue by spectvtor** [VictoriaMetrics/VictoriaMetrics#2636]
Please see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2633

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2633

**Comment by spectvtor** [comment]
Can you please make release with this commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/9e343faa41b9603c8c6b43f71d0df026c03edc0a

**Comment by hagen1778** [comment]
Hi @spectvtor! Thank you for the fix!
We have a 2-week release schedule, so we can't make a release now. It will be published in two weeks approx.
Meanwhile, you can build vmalert on your own https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources

**Comment by spectvtor** [comment]
Ok, thank you

**Comment by hagen1778** [comment]
Hello @spectvtor! I hope this week

**Comment by valyala** [comment]
The bugfix has been included in [vmalert v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
