### ISSUE TITLE
Drop outs / scrape_timeout issue (?)

### ISSUE THREAD

**Issue by faust93** [VictoriaMetrics/VictoriaMetrics#2637]
**Describe the bug**
Drop outs/gaps in the Grafana graphs observed after migrating from Prometheus to VictoriaMetrics Cluster
I assume it's connected to 'scrape_timeout' errors found in vmagent logs

**Expected behavior**
Is it somehow possible to mimic Prometheus behavior in that sense? I mean it was able to scrape the same amount of targets without any gaps visible on the graphs. Any settings to look for and tune on the VM side to get rid of those gaps?

**Logs**
~~~
May 24 10:44:52 xxxx vmagent-prod[121392]: {"ts":"2022-05-24T10:44:52.605Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/scrapework.go:355","msg":"error when scraping \"http://xxxx:9100/metrics\" from job \"node-exporter\" with labels {environment=\"xxxx\",instance=\"xxxx\",job=\"node-exporter\"}: cannot read data: cannot scrape \"http://xxxx:9100/metrics\": Get \"http://xxxx:9100/metrics\": net/http: timeout awaiting response headers"}
....
~~~

**Screenshots**
![image](https://user-images.githubusercontent.com/4245918/170024568-40a00f48-3a84-4b33-8d35-5217044480cc.png)

**Version**
```
$ ./vmagent-prod --version
vmagent-20220412-133948-tags-v1.76.1-0-gf8de318bf
```

**Used command-line flags**
~~~
vmselect-prod --loggerFormat=json -cacheDataPath /opt/vm/cache \
    -search.maxSeries 600000 -search.maxQueryDuration=300s -search.maxQueueDuration=300s -search.maxConcurrentRequests=1024 -search.minStalenessInterval=20s -search.logSlowQueryDuration=60s \
    -storageNode=xxxx1,xxx2,xxx3 \
    -selectNode=xxxx1,xxx2,xxx3

vmstorage-prod --loggerFormat=json -storageDataPath /opt/vm/data \
    -retentionPeriod 30d \
    -loggerLevel INFO

vmagent-prod -loggerLevel INFO --loggerFormat=json \
    -remoteWrite.label=environment=live \
    -promscrape.streamParse=true -promscrape.config.strictParse=false \
    -remoteWrite.tmpDataPath=/opt/vm/vmagent-remotewrite-data -remoteWrite.maxDiskUsagePerURL=1GB \
    -promscrape.config=/opt/vm/vmagent.yml \
    -remoteWrite.url=http://xxxx/insert/0/prometheus
~~~

**Additional context**
~~~
vmagent config:
global:
  scrape_interval: 20s
  scrape_timeout: 15s
....

Targets:
"consul_sd_configs: added targets: 591, removed targets: 0; total targets: 591"
~~~

PS: All the targets are alive and respond quite fast while testing with curl:
~~~
May 24 11:55:07 xxxx vmagent-prod[127463]: {"ts":"2022-05-24T11:55:07.617Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/scrapework.go:355","msg":"error when scraping \"http://xxxx:9100/metrics\" from job \"node-exporter\" with labels {environment=\"xxx\",instance=\"xxxx\",job=\"node-exporter\"}: cannot read data: cannot scrape \"http://xxxx:9100/metrics\": Get \"http://xxxx:9100/metrics\": net/http: timeout awaiting response headers"}

$ time curl -s http://xxxx:9100/metrics >/dev/null

real	0m0.039s
user	0m0.005s
sys	0m0.008s
~~~

**Comment by pollynesterovich** [comment]
i get the same error in this version

**Comment by valyala** [comment]
Gaps on the graph are most likely related to scrape timeouts at `vmagent`. When `vmagent` cannot scrape the target during the configured `scrape_timeout`, then it sends to `-remoteWrite.url` [stale markers](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers) for all the metrics previously scraped from the target. This leads to gaps on the graph. The workaround is to increase `scrape_timeout`. Note that the `scrape_timeout` cannot exceed the `scrape_interval`. So it might be needed increasing the `scrape_interval` as well.

@faust93 , @pollynesterovich , could you try upgrading to [the latest available vmagent version](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and check whether this fixes the issue?

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if issue still remains and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2637#issuecomment-1178447875 had no effect.
