### ISSUE TITLE
VMUI enhancements

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2638]
**Is your feature request related to a problem? Please describe.**

- [ ] I think the following changes to the interface might improve the usability of VMUI:
- [ ] make datepicker to be set to `last 30 min` by default;
- [ ] visualize data loading to the graph via spinner. When I zoom in there is a moment (about a second) where all lines do disappear and then new lines appear. For this second I start to worry if data will show again or maybe something crashed, or my query is incorrect;
- [ ] "query N result" might be omitted in the legend  since it is already present in the column header. We also can highlight the top title a bit more so it become more noticeable
<img width="784" alt="image" src="https://user-images.githubusercontent.com/2902918/170191232-3fe1cbad-a841-4a6d-aeb9-65e76caf08dc.png">
- [ ] In the hover tooltip we can remove the `result` word, just have it as `Query N: <float64>`
<img width="284" alt="image" src="https://user-images.githubusercontent.com/2902918/170191572-147a5757-639c-4bd2-857d-9c7fd408edbb.png">

**Comment by valyala** [comment]
All the enhancements mentioned in [this message](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2638#issue-1247537336) are implemented in [VMUI](https://docs.victoriametrics.com/#vmui) starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
