### ISSUE TITLE
Two series results found with same metric names and labels

### ISSUE THREAD

**Issue by sundy-li** [VictoriaMetrics/VictoriaMetrics#264]
**Describe the bug**
I used node exporter and save the metrics to VictoriaMetrics as a remote storage.
But I found it results to two tables with same  metric names and labels, it's wired.

```
node_memory_MemTotal_bytes{instance=~"$node:$port",farm=~"$job"}
```

Grafana shows that 
```
Only queries that return single series/table is supported
```

**To Reproduce**
1. Node exporter
2. Query from VictorialMetrics(victoria-metrics-20191205-180305-tags-v1.30.5-0-gc09472df) in grafana

 
**Screenshots**
![image](https://user-images.githubusercontent.com/3325189/70763830-74c84700-1d90-11ea-9398-94d99ebbee09.png)

![image](https://user-images.githubusercontent.com/3325189/70764018-236c8780-1d91-11ea-8eb2-3d482ca671a5.png)

Just ignore the instances masks, they are same instances.

**Comment by hagen1778** [comment]
Hi @sundy-li ! Looks like label  `project` has different values on the screenshot.

**Comment by sundy-li** [comment]
all right.
