### ISSUE TITLE
[FEATURE] Add JSON log format via the --loggerFormat flag

### ISSUE THREAD

**Issue by syepes** [VictoriaMetrics/VictoriaMetrics#265]
Hello Guys,

It would be a great addition to the project if we could specify the format of the logging, this will be very helpful for storing and monitoring the VM activity.

Example on how it's been done on Prom and AM: https://github.com/prometheus/alertmanager/pull/1658

**Comment by valyala** [comment]
Added ability to set `-loggerFormat` to `default` and `json` values in the commit f5ac9b072122908c45a1cdcbb9796aafe4763ee0 . It will be included in the next release of VictoriaMetrics.

**Comment by syepes** [comment]
Great!

**Comment by valyala** [comment]
The `-loggerFormat` command line flag is available starting from [v1.31.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It supports `default` and `json` values.

Closing the issue as fixed.
