### ISSUE TITLE
Support for NUMA memory interleave on Linux

### ISSUE THREAD

**Issue by ubcharron** [VictoriaMetrics/VictoriaMetrics#2656]
**Is your feature request related to a problem? Please describe.**

vmstorage uses the default NUMA policy when starting (the default policy is "local", which allocates memory on the node where the thread is running). Our servers have two numa nodes and this frequently leads to an imbalance in memory allocation: vmstorage tends to allocate much more memory on one node than the other. If a node gets low on free memory, Linux will start swapping even though there is enough _total_ free memory across the system (regardless of vm.swappiness).

**Describe the solution you'd like**

I think it would be cool if vmstorage supported an option to change numa memory allocation policy to interleave, like mysql does for its innodb buffer pool (https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_numa_interleave)

Or, adding numactl to the docker container would also be a nice QoL.

Note: I have not compared vmstorage's performance in local vs interleave.

**Describe alternatives you've considered**

Using numactl to start a process can be used to override the memory policy. However, it's not currently installed in VM's public docker containers.

**Comment by f41gh7** [comment]
It's hard to implement for now. Golang architecture limits us. Golang scheduler is not aware of numa nodes. In case of multi-CPU VictoriaMetrics may show worse performance and use more memory.

https://groups.google.com/g/golang-dev/c/URgnGRzo4HA

 There is an example, how it may be done with some tricks https://github.com/lrita/numa

 But it's not production ready.

 For your case, i can suggest to run multiple `vmstorage` nodes and bind each to different numa node.

**Comment by jiekun** [comment]
Hi as commented above, I think we have no plan for this feature yet. I'm closing this issue as answered for now.
