### ISSUE TITLE
OpenTSDB /api/put HTTP requests fail - not parsing correctly

### ISSUE THREAD

**Issue by bfg111** [VictoriaMetrics/VictoriaMetrics#266]
**Describe the bug**
Unable to put data via HTTP API `/api/put` for OpenTSDB data

**To Reproduce**
Try to do what is mentioned in the documentation
https://github.com/VictoriaMetrics/VictoriaMetrics#sending-opentsdb-data-via-http-apiput-requests

```
curl -H 'Content-Type: application/json' -d '{"metric":"x.y.z","value":45.34,"tags":{"t1":"v1","t2":"v2"}}' http://localhost:4242/api/put
```

**Expected behavior**
Data would get inserted correctly

**Screenshots**

```
curl -v -H 'Content-Type: application/json' -d '{"metric":"x.y.z","value":45.34,"tags":{"t1":"v1","t2":"v2"}}' http://localhost:4242/api/put
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4242 (#0)
> POST /api/put HTTP/1.1
> Host: localhost:4242
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 61
>
* upload completely sent off: 61 out of 61 bytes
^C
```

```
victoriametrics    | 2019-12-13T15:29:21.343+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "POST /api/put HTTP/1.1": missing `put ` prefix in "POST /api/put HTTP/1.1"
victoriametrics    | 2019-12-13T15:29:21.344+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "Host: localhost:4242": missing `put ` prefix in "Host: localhost:4242"
victoriametrics    | 2019-12-13T15:29:21.344+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "User-Agent: curl/7.64.1": missing `put ` prefix in "User-Agent: curl/7.64.1"
victoriametrics    | 2019-12-13T15:29:21.344+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "Accept: */*": missing `put ` prefix in "Accept: */*"
victoriametrics    | 2019-12-13T15:29:21.344+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "Content-Type: application/json": missing `put ` prefix in "Content-Type: application/json"
victoriametrics    | 2019-12-13T15:29:21.344+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "Content-Length: 61": missing `put ` prefix in "Content-Length: 61"
victoriametrics    | 2019-12-13T15:29:24.344+0000	error	VictoriaMetrics@/app/vminsert/opentsdb/parser.go:127	cannot unmarshal OpenTSDB line "{\"metric\":\"x.y.z\",\"value\":45.34,\"tags\":{\"t1\":\"v1\",\"t2\":\"v2\"}}": missing `put ` prefix in "{\"metric\":\"x.y.z\",\"value\":45.34,\"tags\":{\"t1\":\"v1\",\"t2\":\"v2\"}}"
```

**Version**

```
victoriametrics    | 2019-12-13T15:00:22.557+0000	info	VictoriaMetrics@/lib/logger/flag.go:11	build version: victoria-metrics-20191211-223021-tags-v1.31.0-0-g440a1511
```

**Additional context**
It seems like looking through the code the parser is expecting line protocol and not JSON??
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9c9221d1b293838e750336946031976618a3e1de/app/vminsert/opentsdb/parser.go#L58

**Comment by valyala** [comment]
VictoriaMetrics supports OpenTSDB data ingestion via `telnet` and `http` protocols. These protocols must be enabled with distinct flags - see `-help` output for `-openTSDBListenAddr` and `-opentsdbHTTPListenAddr`:

```
/path/to/victoria-metrics-prod --help 2>&1 | grep -A 1 opentsdb
  -opentsdbHTTPListenAddr string
    	TCP address to listen for OpentTSDB HTTP put requests. Usually :4242 must be set. Doesn't work if empty
  -opentsdbListenAddr string
    	TCP and UDP address to listen for OpentTSDB put messages. Usually :4242 must be set. Doesn't work if empty
```

It looks like you enabled `telnet` listener instead of `http` listener on port `4242` for OpenTSDB protocol. Try using `-opentsdbHTTPListenAddr` instead of `-opentsdbListenAddr` as mentioned in [the docs](https://github.com/VictoriaMetrics/VictoriaMetrics#sending-opentsdb-data-via-http-apiput-requests).

**Comment by valyala** [comment]
Probably it would be good to merge these listeners into a single listener in the future like the original OpenTSDB server does. It detects the protocol by the first word in the request:
- `put` routes request parsing to `telnet` protocol
- `POST` routes request parsing to `http` protocol

**Comment by bfg111** [comment]
Thank you for clearing that up. I added '--opentsdbListenAddr=:4242' and I assumed that was for both telnet and HTTP traffic. It would be nice if that behavior was similar only because that was my assumption from working with OpenTSDB.

**Comment by valyala** [comment]
VictoriaMetrics should accept both `telnet put` and `http /api/put` messages on `-opentsdbListenAddr` starting from the next release.
@bfg111 , you can test it right now by building VictoriaMetrics from commit bc645152cbf88f21b8851cbbea0d80008a839e9a according to [the docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources).

**Comment by valyala** [comment]
VictoriaMetrics should accept both `telnet put` and `http /api/put` requests on `-opentsdbListenAddr` starting from [v1.31.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by bfg111** [comment]
I have verified that when specified on different ports, both protocols work as expected. (FWIW)

```
-opentsdbHTTPListenAddr=:4242
-opentsdbListenAddr=:4444
```

**Comment by valyala** [comment]
Note that `-opentsdbHTTPListenAddr` can be omitted now, since `-opentsdbListenAddr` should cover both `telnet put` and `http /api/put` like in the original OpenTSDB server.
