### ISSUE TITLE
question about the accuracy of victoriametrics cluster in storing 16 decimal places

### ISSUE THREAD

**Issue by TroyPotte** [VictoriaMetrics/VictoriaMetrics#2662]
I see in VictoriaMetrics metric's value is always float64。When I use telegraf to store 16 decimal places in vmstorage, only 14 decimal places are found, and the last 2 decimal places are lost. At first, I thought it was the problem of telegraf, but when I used HTTP to directly send the data of the incluxdb protocol to victoriametrics, the query was still 14 decimal places.

**Comment by hagen1778** [comment]
Hi @TroyPotte! 
Looks like the following info can be relevant https://docs.victoriametrics.com/FAQ.html?highlight=decimal#why-do-the-same-metrics-have-differences-in-victoriametrics-and-prometheus-dashboards

**Comment by TroyPotte** [comment]
Oh, thanks, I see
