### ISSUE TITLE
Relabeling: add support for lowercase and uppercase actions

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2664]
The feature is needed to keep compatibility with Prometheus relabeling engine, which was updated in https://github.com/prometheus/prometheus/pull/10641

**Comment by valyala** [comment]
All the VictoriaMetrics components, which support relabeling, gained support for `lowercase` and `uppercase` relabeling rules starting from [v1.78.0 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
