### ISSUE TITLE
unexpected not match regex result

### ISSUE THREAD

**Issue by andywu1998** [VictoriaMetrics/VictoriaMetrics#2668]
**Describe the bug**
I have 5 time series, 3 of them have client_id, another 3 have not client_id: 
```
generate_url_total{client_id="3", domain="shopee.com", type="type_a"} 1100
generate_url_total{client_id="4", domain="shopee2.com", type=""} 2100
generate_url_total{client_id="4", domain="shopee2.com", type="type_b"} 2100
generate_url_total{domain="shopee.com", type="type_a"} 1200
generate_url_total{domain="shopee2.com", type=""} 2200
generate_url_total{domain="shopee2.com", type="type_b"} 2200
```
then I query: 
generate_url_total{client_id=~"(4|)"}
expected result: return the time series that client_id=4 and client_id=""(or without client_id).
real result: return all time series.

**To Reproduce**
1. construct data like above
2. query generate_url_total{client_id=~"(4|)"}

**Expected behavior**
when I query generate_url_total{client_id=~"(4|)"}, it return the time series that client_id=4 and client_id=""(or without client_id).

**Screenshots**

as you see, the left is VM, the right is prometheus

<img width="1945" alt="iShot2022-06-01 17 00 38" src="https://user-images.githubusercontent.com/30118280/171368195-40b855ff-f960-4a8f-8076-7d73702cb15d.png">

**Comment by andywu1998** [comment]
> Hi @andywu1998! Which version of VM do you run?

Sorry I forgot to write the version. My version of VM is 1.67.0-cluster.

**Comment by hagen1778** [comment]
Please check the fixes for regex matching in https://docs.victoriametrics.com/CHANGELOG.html#v1720 and https://docs.victoriametrics.com/CHANGELOG.html#v1750. Try to update and see if issue still remains.
