### ISSUE TITLE
Implement Language Server Protocol for auto-completion in Grafana

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#267]
**Is your feature request related to a problem? Please describe.**
Prometheus datasource in Grafana contains a lot of custom client-side code for auto-completion in various contexts during editing dashboards, template vars and graphs. This code is executed in web browser context.

**Describe the solution you'd like**
It would be great to move all the complexity related to auto-completion in Grafana to VictoriaMetrics. This would simplify auto-completion handling in Grafana, since it could just send requests to VictoriaMetrics via [Language Server Protocol](https://en.wikipedia.org/wiki/Language_Server_Protocol) (aka LSP) and receive auto-completion responses for the current context.
The same LSP could be used by another clients in the future.

**Comment by hagen1778** [comment]
This would be super useful for https://github.com/VictoriaMetrics/grafana-datasource

**Comment by valyala** [comment]
Grafana and [vmui](https://docs.victoriametrics.com/#vmui) use the following APIs for auto-completion:

- [`/api/v1/labels`](https://docs.victoriametrics.com/url-examples/#apiv1labels)
- [`/api/v1/label/.../values`](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues)
- [`/api/v1/series`](https://docs.victoriametrics.com/url-examples/#apiv1series)

These APIs are enough for auto-completion tasks. So closing this feature request as won't implement.

Feel free creating a new feature request if you think VictoriaMetrics needs some additional APIs for improving auto-completion experience at Grafana, [VictoriaMetrics datasource for Grafana](https://github.com/VictoriaMetrics/grafana-datasource) or [vmui](https://docs.victoriametrics.com/#vmui).
