### ISSUE TITLE
vmagent: do not expose SD metrics for types which aren't configured

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2671]
**Is your feature request related to a problem? Please describe.**
By default, vmagent exposes metrics for all SD types, even for those which aren't actually configured. These metrics include histograms which could generate a lot of unique time series. Having this metrics always exposed could put additional pressure on database.

**Describe the solution you'd like**
Metrics for SD should be exposed only for those types which were configured.
If scrape config was hot reloaded and some of SD were removed - so should and corresponding metrics.

**Describe alternatives you've considered**
Drop excessive metrics on scrape time via relabeling.

**Comment by f41gh7** [comment]
I think, that we could use separate metrics.Set per each service discovery.

 metrics library must be extended with metrics.Register method, that takes metrics.Set and registers it at defaultSet for prometheusWrite.

 It allows to register and de register groups of metrics, instead of manually managing each metric by it's name.

Something like:

```
newScraperGroup(name string,...)
   ms := metrics.NewSet()
	sg := &scraperGroup{
		name:     name,
		m:        make(map[string]*scraper),
		pushData: pushData,
                metricsSet: ms,

		changesCount:    ms.NewCounter(fmt.Sprintf(`vm_promscrape_config_changes_total{type=%q}`, name)),
		activeScrapers:  ms.NewCounter(fmt.Sprintf(`vm_promscrape_active_scrapers{type=%q}`, name)),
		scrapersStarted: ms.NewCounter(fmt.Sprintf(`vm_promscrape_scrapers_started_total{type=%q}`, name)),
		scrapersStopped: ms.NewCounter(fmt.Sprintf(`vm_promscrape_scrapers_stopped_total{type=%q}`, name)),
      ....
	}
	ms.NewGauge(fmt.Sprintf(`vm_promscrape_targets{type=%q, status="up"}`, name), func() float64 {
		return float64(tsmGlobal.StatusByGroup(sg.name, true))
	})
	ms.NewGauge(fmt.Sprintf(`vm_promscrape_targets{type=%q, status="down"}`, name), func() float64 {
		return float64(tsmGlobal.StatusByGroup(sg.name, false))
	})
```

 and later use it as:

```
		if sg.activeScrapers.Get() > 0 {
                      metrics.Register(sg.ms)
                 }else{
                    metrics.DeRegister(sg.ms)
                }
```

**Comment by valyala** [comment]
`vmagent` and single-node VictoriaMetrics stop exposing `vm_promscrape_service_discovery_duration_seconds_bucket` metric for unused service discovery types starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
