### ISSUE TITLE
Expose cardinality info

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#268]
**Is your feature request related to a problem? Please describe.**
Prometheus since [v2.14.0](https://github.com/prometheus/prometheus/releases/tag/v2.14.0) exposes some cardinality statistics which may be very useful to track. And VM is frequently used as a remote storage for multiple Prometheus instances. So while we have possibility to look on such kind of stats on every particular Prometheus instance, it would be great to have the same statistics for global view over all collected metrics.

**Describe the solution you'd like**
I'd like to have HTTP API method which returns cardinality statistics for collected timeseries.

**Comment by vkuznet** [comment]
+1

**Comment by valyala** [comment]
FYI, the [/api/v1/status/tsdb](https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-stats) page has been added into VictoriaMetrics in the following commits:

* single-node version: 364db13c9c32999b2d0e9f0531773672408a0176
* cluster version: f9526809e57ed5f98da22661616f5a23d3320ac2

These commits will be included in the next release.

**Comment by valyala** [comment]
The `/api/v1/status/tsdb` page is available starting from [v1.35.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
