### ISSUE TITLE
Add scrape_pool label to vm_promscrape_targets

### ISSUE THREAD

**Issue by hroussez** [VictoriaMetrics/VictoriaMetrics#2704]
**Is your feature request related to a problem? Please describe.**
I have an alert triggered by `vm_promscrape_targets{status="down"}`
This alert is too noisy as there are some scrape pools that do not require immediate attention while others do.

I would like to be able to refine the alert for specific scrape pools.
Targets down from specific pools should alert me immediately while others can wait (low/high priority alerts).

**Describe the solution you'd like**
Ideally, vmagent would add the `scrape_pool` label to `vm_promscrape_targets` so that I can filter for specific `scrape_pool` in Grafana.

Is that feasible? Would that be a sustainable solution?
Otherwise, what might be good alternatives?

**Describe alternatives you've considered**
***Fetch data from vmagent API***
The vmagent API provides a JSON of all scrape targets, which can be used to extract the number of targets down grouped by scrape pool:
```
$ curl http://vmagent/api/v1/targets | jq -r '.data.activeTargets[] | select(.health == "down") | .scrapePool' | sort | uniq -c | sort -n
   1 eventservice
  3 bookingservice
```

We could use this URL to configure an exporter that would query the API and filter the relevant data, eg. using [json_exporter](https://github.com/prometheus-community/json_exporter)

While this solution would work, it would cost a significant amount of unnecessary data transfers as the API response grows quickly with the number of active targets.

**Additional context**
I am new to the VictoriaMetrics codebase, but I would be happy to implement the solution myself. Guidance on the feasibility and relevant code paths would be appreciated.

**Comment by hagen1778** [comment]
Hi @hroussez! Thanks for feature request. 
I'm not sure if that is the right approach to distinguish which jobs need immediate attention and which don't.
Is this an option to run multiple vmagents for different purposes? For example, vmagent-prod will contain only jobs which require immediate attention, and vmagent-dev is for jobs which don't.

**Comment by jiekun** [comment]
Closed as answered by hargen1778.
