### ISSUE TITLE
VMUI installation/access on Debian11?

### ISSUE THREAD

**Issue by genseb13011** [VictoriaMetrics/VictoriaMetrics#2708]
Hi,

I'm PoCing VictoriaMetrics and need to install it on debian 11

I've already install VM and VMauth and works fine (below)

VM localhost:8428 <== vmauth 0.0.0.0:8247

I've followed this guide https://www.vultr.com/docs/install-and-configure-victoriametrics-on-debian/ (without implementing TLS section)

I'd like to access UI but don't know how.

Do I need to install vmui? If so, is there a guide to documentation to install vmui?
Is it included in VM installation? If so how can I access it?

Thanks for your help.

Seb.

**Comment by denisgolius** [comment]
> Hi,
> 
> I'm PoCing VictoriaMetrics and need to install it on debian 11
> 
> I've already install VM and VMauth and works fine (below)
> 
> VM localhost:8428 <== vmauth 0.0.0.0:8247
> 
> I've followed this guide https://www.vultr.com/docs/install-and-configure-victoriametrics-on-debian/ (without implementing TLS section)
> 
> I'd like to access UI but don't know how.
> 
> Do I need to install vmui? If so, is there a guide to documentation to install vmui? Is it included in VM installation? If so how can I access it?
> 
> Thanks for your help.
> 
> Seb.

Hi @genseb13011 !
VMUI has been integrated to VictoriaMetrics Single - see https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#vmui and to [VictoriaMetrics Cluster as a part](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format) of `vmselect` and available at `http://<vmselect>:8481/select/<accountID>/vmui/`

**Comment by genseb13011** [comment]
Hi!

Thanks for your reply!

Seb.
