### ISSUE TITLE
vminsert /health endpoint return Ok when storage is dead

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#2725]
**Describe the bug**

vminsert:8480/health retrun `OK` when storage is inaccessible 

I have 2 instance of vminsert behing a load-balancer.
vmstorage became inaccessible for 1 instance of vminsert.

Load balancer is checking /health so it keep load-balancing to the vminsert that can't query vmstorage.

**Logs**
```
[root@xxxx]:/ $ curl 127.0.0.1:8480/health
OK

2022-06-13T16:03:23.327Z        warn    VictoriaMetrics/app/vminsert/netstorage/netstorage.go:206       cannot push 120165 bytes with 500 rows to storage nodes, since all the nodes are temporarily unavailable; re-trying to send the data
soon
```

**Screenshots**

![image](https://user-images.githubusercontent.com/35098906/173398150-7ea098e7-ecb2-4b59-9301-71e9c30a0451.png)

**Version**
```
docker exec vminsert /vminsert-prod --version
vminsert-20220412-135209-tags-v1.76.1-cluster-0-g4a6b56e5b
```

**Comment by dmitryk-dk** [comment]
Hi @xenofree ! `/health` endpoint is for vminsert and it just shows does vminsert alive or not.
vminsert always tries to check the avaliability of vmstorage and sends data to available one.
You can check it in the documentation
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability
`vminsert re-routes incoming data from unavailable vmstorage nodes to healthy vmstorage nodes`
