### ISSUE TITLE
label_values function in docs named incorrectly

### ISSUE THREAD

**Issue by Scott2e** [VictoriaMetrics/VictoriaMetrics#2727]
I believe the PromQL function `label_values` has been incorrectly named `label_value` in the VM docs here https://docs.victoriametrics.com/MetricsQL.html#label_value

**Comment by hagen1778** [comment]
Hello @Scott2e!
PromQL does not have `label_values` function at all. You're likely referring to Grafana's templating function - https://sbcode.net/grafana/dashboard-variables/#example-variables

**Comment by Scott2e** [comment]
Well that's embarrassing 😅 
Thank-you for your response @hagen1778
