### ISSUE TITLE
vmctl: improve migration process via native protocol

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2733]
**Is your feature request related to a problem? Please describe.**
In native mode vmctl has no control over the migration process and acts as a proxy between source and destination. This has following downsides:
* no sense of progress - it is unclear at which stage or how soon will migration be finished
* no process restore if interrupted - when migration fails it needs a full restart instead of just starting from the latest checkpoint

**Describe the solution you'd like**
Would be great if vmctl could track the progress by breaking the migration process into some units, like time. For example, when user starts migration of one month of the data, vmctl could automatically break it into 30 independent stages - a stage per day. The migration will start day-by-day which would bring the sense of progress and would allow to continue the migration if it breaks.
I assume, user would be able to specify the step by which migration interval can be split into parts.

**Describe alternatives you've considered**
Do the manual split of the migration interval by days or hours and run vmctl migration multiple times.

**Comment by avanier** [comment]
Other suggestion that was discussed in meeting with @hagen1778 and `@artem` is allow using custom labels to limit the amount of data being selected.

For example in our case we could segment our data coming from different Kubernetes clusters through a dedicated label.
