### ISSUE TITLE
vmagent: relabeling playground

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2734]
**Is your feature request related to a problem? Please describe.**
Relabeling mechanism is powerful tool for filtering and modifying scraped targets and series, or routing data to multiple destinations. But writing such configs might be not trivial and requires multiple iterations from user to make it done. User-friendly interface could help to make this simpler.

**Describe the solution you'd like**
Would be great if vmagent could contain a special web page where users can experiment with writing `relabel_configs`, `metric_relabel_configs` and `write_relabel_configs`. The web-page would allow to write a config example and immediately see the result displayed on the page. Would be also great to allow picking targets, destinations or series already loaded/scraped by vmagent directly in UI, so user won't need to manually enter examples for relabeling.
 
**Describe alternatives you've considered**
There is a great tool https://relabeler.promlabs.com/ but it has the following downsides:
* it does not support relabling features provided by VictoriaMetrics
* it requires from user manually load data examples

**Comment by jiekun** [comment]
I think this should be duplicated to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2734. Close as completed.
