### ISSUE TITLE
Improvement in Relabeling for Graphite metrics 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#2737]
**Is your feature request related to a problem? Please describe.**
Existing relabeling is a CPU intensive for Graphite metrics 

**Describe the solution you'd like**
Implement relabeling similar to:
- https://github.com/prometheus/statsd_exporter#glob-matching 
- https://github.com/prometheus/graphite_exporter#yaml-config).

**Describe alternatives you've considered**
Use standard relabeling but it's CPU intensive

**Comment by valyala** [comment]
The commit c18f8cccfa8119b30b631307c905e3cacff98fd3 adds support for Graphite metrics relabeling similar to [Glob matching in statsd_exporter](https://github.com/prometheus/statsd_exporter#glob-matching) to VictoriaMetrics components. See [Graphite relabeling docs](https://docs.victoriametrics.com/vmagent.html#graphite-relabeling) for details. This commit will be included in the next release.

**Comment by valyala** [comment]
All the VictoriaMetrics components, which support relabeling, gained support for `action: graphite` starting from [v1.78.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/vmagent.html#graphite-relabeling) for details.

Closing the feature request as done.
