### ISSUE TITLE
Data aggregation possible?

### ISSUE THREAD

**Issue by genseb13011** [VictoriaMetrics/VictoriaMetrics#2739]
Hi,

We'd like to setup a multi-retention victoriametrics architecture.

We are thinking to deploy 3 standalones servers with 3 retentions periods (1 month, 1 year, 5 years).

The source datas will be the same but we'd like to compress/aggregate on the 1year and 5 years instances because we don't need precise value on both (only for history purpose).

We're thinking to add the 3 outputs to our telegrafs .

telegraf_output1==> victoriametrics-1month
telegraf_output2 ==> victoriametrics-1year
telegraf_output3==> victoriametrics-5years

Telegraf will flush data every 10 seconds and sounds good for the victoriametrics-1month.
On the victoriametrics-1year and victoriametrics-5years, we'd like to aggregate datas per hour, so have average value on 1h instead of 360 values * 10s

Is there any compaction/agregation tools/modules that can handle this kind of tasks?
Do we have to rethink the architecture? maybe telegraf ==> victoria1month ==> some tool ==> victoria1year ==> some tool ==> victoria5years

Thanks for your precious advices!

Seb.

**Comment by hagen1778** [comment]
Hello! Thanks for question!

> The source datas will be the same but we'd like to compress/aggregate on the 1year and 5 years instances because we don't need precise value on both (only for history purpose).

VictoriaMetrics supports [downsampling](https://docs.victoriametrics.com/#downsampling) as part of ENT package. It leaves the last data point on the selected downsampling interval. Not exactly what you're looking for, but just in case you missed it.

> Is there any compaction/agregation tools/modules that can handle this kind of tasks?

One of the approaches you might want to take is https://docs.victoriametrics.com/vmalert.html#downsampling-and-aggregation-via-vmalert
Via vmalert you can define recording rules which would read from `victoria1month ` and remote write to `victoria1year `. The cool thing here is that you can decide which series and how you want to change just by writing MetricsQL expressions. But, you will need to write these expressions.

I've also heard about https://m3db.io/docs/architecture/m3aggregator/overview/ but never used it. From the docs it looks like it is compatible with remote write protocol, but not with ingestion protocol. Maybe there is a workaround for that.

You also can take a look at https://github.com/statsd/statsd which promises aggregation. VictoriaMetrics is compatible with [statsd protocol](https://docs.victoriametrics.com/#how-to-send-data-from-graphite-compatible-agents-such-as-statsd), so you can have the following architecture:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/2902918/174724330-e5caa8a2-117e-4bca-a22b-9eb1aecc05f6.png">

**Comment by genseb13011** [comment]
Thanks for your answer and advices!
