### ISSUE TITLE
Document supported hardware architectures

### ISSUE THREAD

**Issue by zamazan4ik** [VictoriaMetrics/VictoriaMetrics#2749]
Hi!

Could you please put the information about supported architectures to the documentation please? E.e. about supported architectures for different operating systems, some specific requirements to the supported instructions, if you have any (e.g. maybe AVX is required - I do not know).

This kind of information is important for the end-users.

Thanks in advance!

**Comment by denisgolius** [comment]
Hi @zamazan4ik !
We added a list of [supported architectures](https://docs.victoriametrics.com/BestPractices.html#supported-architectures). Any suggestions or PR's are appreciated.
