### ISSUE TITLE
Use a separate timeout for `/api/v1/export`

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#275]
**Is your feature request related to a problem? Please describe.**

Currently `/api/v1/export` uses `-search.maxQueryDuration` timeout, which is applied to all the Prometheus API functions. This isn't optimal solution, since `/api/v1/export` could be used for exporting big amounts of data, which cannot complete in small timeout set via `-search.maxQueryDuration` command-line flag.

**Describe the solution you'd like**
It would be great to have a separate command-line flag for configuring timeout for `/api/v1/export`.

**Describe alternatives you've considered**
An alternative is to increase `-search.maxQueryDuration` while exporting big amounts of data from `/api/v1/export`. This isn't good solution, since this automatically increases the timeout for all the Prometheus API functions such as `/api/v1/query_range`, which is undesired in most cases.

**Comment by hagen1778** [comment]
Since we know that `/api/v1/export` could be quite time expensive action, why wouldn't we remove timeout at all? It could be unpredictable for me to estimate exporting time, so I'll just set some enormous timeout of `1h` or higher.

**Comment by valyala** [comment]
New flag `-search.maxExportDuration` has been added in [v1.31.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). By default it equals to 10 minutes.

**Comment by valyala** [comment]
> Since we know that /api/v1/export could be quite time expensive action, why wouldn't we remove timeout at all? It could be unpredictable for me to estimate exporting time, so I'll just set some enormous timeout value of 1h or higher.

Removing the timeout from `/api/v1/export` would make it more vulnerable to improper usage. Probably limit to the number of concurrent calls to `/api/v1/export` must be added in order to reduce possible damage when the API is improperly used?

**Comment by valyala** [comment]
FYI, the upcoming VictoriaMetrics release will support optimized data export / import in native format. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/787#issuecomment-700632551 for details.

**Comment by valyala** [comment]
Optimized data export/import is available starting from release [v1.42.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
