### ISSUE TITLE
VMalert  "generatorURL"   Does not contain 'rules expr' 

### ISSUE THREAD

**Issue by GubMid** [VictoriaMetrics/VictoriaMetrics#2755]
![image](https://user-images.githubusercontent.com/74485252/174577651-69dc04c9-6d9e-44d1-8ecb-06cdf85f6fc8.png)

**Comment by Vladikamira** [comment]
you can use `-external.alert.source` option to generate yours.
We for instance have 
```
external.alert.source: 'graph?g0.expr={{$expr|queryEscape}}'
```
works for us because we've migrated from `Thanos`

**Comment by hagen1778** [comment]
hi @GubMid! 
Is this issue still relevant?

**Comment by GubMid** [comment]
> hi @GubMid! Is this issue still relevant?

Thank you, to end
