### ISSUE TITLE
potential buggy code in parsing partHeader from path

### ISSUE THREAD

**Issue by LokiWager** [VictoriaMetrics/VictoriaMetrics#2757]
**Describe the bug**
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9f6a19a904f93ad70cf498d870359ab167f01dd6/lib/mergeset/part_header.go#L139-L140

There is an assignment before the comparison. The condition is always true. I'm not sure what's the intention here. Maybe it's a bug.

**Comment by valyala** [comment]
@LokiWager , thanks for reporting and fixing this bug! The bugfix will be included in the next release of VictoriaMetrics.
