### ISSUE TITLE
/api/v1/admin/tsdb/delete_series return unsupported path requested

### ISSUE THREAD

**Issue by James601232** [VictoriaMetrics/VictoriaMetrics#2761]
**Describe the bug**
I use postman tool send /api/v1/admin/tsdb/delete_series request and work fined.
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/19258506/174640911-ccabd852-844b-4ff8-a5d2-f65010a6345e.png">

But when i use http-client in java send the request response following messages:
**remoteAddr: "192.168.123.22:55235"; requestURI: /delete/5/prometheus/api/v1/admin/tsdb/delete_series%3Fmatch%5B%5D%3Dprobe_success%7BxHawk_user_space_id%3D1527239135585157123%2CxHawk_job_id%3D1537381716730118146%2CxHawk_ins_id%3D3754%7D?end=1655703900&start=1655703720; **unsupported path requested:** "/delete/5/prometheus/api/v1/admin/tsdb/delete_series?match[]=probe_success{xHawk_user_space_id=1527239135585157123,xHawk_job_id=1537381716730118146,xHawk_ins_id=3754}"**
java codes snippet as following:

Code entry:

```
Map<String,String> params = new HashMap<>();
            params.put("start", ele.getStartTime().toString());
            params.put("end", ele.getEndTime().toString());
            String ret = null;
            String urlSuffix = String.format("?match[]=%s{xHawk_user_space_id=\"%s\",xHawk_job_id=\"%s\",xHawk_ins_id=\"%s\"}",ele.getMetric(), SecurityUtils.currentUser().getConcurrentSpaceId(), svcSloEntity.getSrcTaskId(), ele.getInsId());
            try {
                urlSuffix = URLEncoder.encode(urlSuffix,"UTF-8");
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();
            }
            try {
                ret = HttpClientUtils.**tokenPost**(deleteUrl + urlSuffix, params);
            } catch (IOException e) {
                e.printStackTrace();
            }
            System.out.println(ret);

 public static String tokenPost(String url, Map<String, String> map) throws IOException {
        List<NameValuePair> params = Lists.newArrayList();
        if (map != null && !map.isEmpty()) {
            for (Map.Entry<String, String> entry : map.entrySet()) {
                params.add(new BasicNameValuePair(entry.getKey(), entry.getValue()));
            }
        } else {
            map = Maps.newHashMap();
        }
        log.info("Executing post request, url:{},   body: {}", url, map);
        HttpPost httpPost = new HttpPost(url);
        RequestConfig requestConfig = RequestConfig.custom().setConnectTimeout(5000).setConnectionRequestTimeout(1000).setSocketTimeout(5000).build();
        httpPost.setConfig(requestConfig);

        httpPost.setHeader("Content-type", MediaType.APPLICATION_FORM_URLENCODED_VALUE);
        try {
            httpPost.setEntity(new UrlEncodedFormEntity(params, "UTF-8"));
        } catch (UnsupportedEncodingException e)  {
            e.printStackTrace();
        }
        return getResult(httpPost);
    }

    private static String getResult(HttpPost httpPost) {
        String result = "";
        try (CloseableHttpClient httpClient = HttpClients.createDefault();
             CloseableHttpResponse response = httpClient.execute(httpPost)) {
            log.info("Print response http status:{}", response.getStatusLine().getStatusCode());
            HttpEntity responseEntity = response.getEntity();
            if (responseEntity != null) {
                result = EntityUtils.toString(responseEntity, StandardCharsets.UTF_8);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }

```

Hope vm team-mate can help me fixed this problem. thanks in advance

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
Check if any warnings or errors were logged by VictoriaMetrics components
or components in communication with VictoriaMetrics (e.g. Prometheus, Grafana).

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

See how to setup monitoring here:
* [monitoring for single-node VictoriaMetrics](https://docs.victoriametrics.com/#monitoring)
* [monitoring for VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring)

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190730-121249-heads-single-node-0-g671d9e55
```

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components.

**Comment by hagen1778** [comment]
Hi @James601232!
Looks like you have malformed request in Java implementation:
```
remoteAddr: "192.168.123.22:55235"; requestURI: /delete/5/prometheus/api/v1/admin/tsdb/delete_series%3Fmatch%5B%5D%3Dprobe_success%7BxHawk_user_space_id%3D1527239135585157123%2CxHawk_job_id%3D1537381716730118146%2CxHawk_ins_id%3D3754%7D?end=1655703900&start=1655703720; unsupported path requested: "/delete/5/prometheus/api/v1/admin/tsdb/delete_series?match[]=probe_success{xHawk_user_space_id=1527239135585157123,xHawk_job_id=1537381716730118146,xHawk_ins_id=3754}"
```

Part `/delete/5/prometheus/api/v1/admin/tsdb/delete_series%3Fmatch%5B%5D%3D`
should be `/delete/5/prometheus/api/v1/admin/tsdb/delete_series?match[]=`
Looks like URL is not properly encoded. In order to fix it you need either encode it or send params as a part of request'ss body.

**Comment by James601232** [comment]
> Hi @James601232! Looks like you have malformed request in Java implementation:
> 
> ```
> remoteAddr: "192.168.123.22:55235"; requestURI: /delete/5/prometheus/api/v1/admin/tsdb/delete_series%3Fmatch%5B%5D%3Dprobe_success%7BxHawk_user_space_id%3D1527239135585157123%2CxHawk_job_id%3D1537381716730118146%2CxHawk_ins_id%3D3754%7D?end=1655703900&start=1655703720; unsupported path requested: "/delete/5/prometheus/api/v1/admin/tsdb/delete_series?match[]=probe_success{xHawk_user_space_id=1527239135585157123,xHawk_job_id=1537381716730118146,xHawk_ins_id=3754}"
> ```
> 
> Part `/delete/5/prometheus/api/v1/admin/tsdb/delete_series%3Fmatch%5B%5D%3D` should be `/delete/5/prometheus/api/v1/admin/tsdb/delete_series?match[]=` Looks like URL is not properly encoded. In order to fix it you need either encode it or send params as a part of request'ss body.

Hi  @hagen1778 
I use okhttp3 send the  delete_series  request with time range still error
**first method:**
` public static String post(String url, Map<String, String> map) {
        OkHttpClient client = new OkHttpClient();
        RequestBody formBody = new MultipartBody.Builder()
                .setType(MultipartBody.FORM)
                .addFormDataPart("start",map.get("start"))
                .addFormDataPart("end",map.get("end"))
                .build();
        Request request = new Request.Builder()
                .url(url)
                .post(formBody)
                .build();

        Call call = client.newCall(request);
        Response response = null;
        try {
            response = call.execute();
        } catch (IOException e) {
            e.printStackTrace();
        }

        try {
            return response.body().string();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {

        }
        return null;
    }
Code entry:
  Map<String, String> params = new HashMap<>();
            params.put("start", ele.getStartTime().toString());
            params.put("end", ele.getEndTime().toString());
            String ret = null;
            String urlSuffix = String.format("match[]=%s{xHawk_user_space_id=\"%s\",xHawk_job_id=\"%s\",xHawk_ins_id=\"%s\"}", ele.getMetric(), SecurityUtils.currentUser().getConcurrentSpaceId(), svcSloEntity.getSrcTaskId(), ele.getInsId());
            OkHttpClientUtil.post(deleteUrl + "?" + urlSuffix,params);

`
And error messages are following:
`remoteAddr: "10.123.123.123:6745"; requestURI: /delete/5/prometheus/api/v1/admin/tsdb/delete_series?match[]=xxx_topic_status{xHawk_user_space_id=%221527239135585157123%22,xHawk_job_id=%221527601351657590786%22,xHawk_ins_id=%22shbt_pub_infra%22}&end=1655797860&start=1655797800; start and end aren't supported. Remove these args from the query in order to delete all the matching metrics`

Does my codes passed start and end parameters is incorrect? how to fixed?

**Comment by hagen1778** [comment]
Yes, body params are supported by default for POST/PUT requests. Try the following request:
```
curl -v 'http://<vm-addr>/api/v1/admin/tsdb/delete_series' -d 'match[]=my_metric'
```

**Comment by hagen1778** [comment]
@James601232 delete API in VictoriaMetrics does not support `start` `end` params. Please see https://docs.victoriametrics.com/#how-to-delete-time-series.

**Comment by James601232** [comment]
@hagen1778  i send post request
![image](https://user-images.githubusercontent.com/19258506/174791824-19f79a57-ac9d-402a-8a79-c80776e618e3.png)

**Comment by James601232** [comment]
@hagen1778   
if no start and end  parameters the code  is worked fine.
