### ISSUE TITLE
timezone_offset offset if query time and data time fall into diffent day light saving

### ISSUE THREAD

**Issue by TomasVojacek** [VictoriaMetrics/VictoriaMetrics#2771]
If I query timezone_offset("Europe/London") to range to 1.1.2022 to 1.8.2022. I would expect to get two values 0 and 3600. But I got only 3600 query excuted in june 2022.
I there solution for situation then data time and query time differ?
Can be warring about this added to docs?
Is it possible to extend function timezone_offset take time as second parameter?
timezone_offset("Europe/London",timestamp(up{}))

**Comment by hagen1778** [comment]
Hi @TomasVojacek! The fix for `timezone_offset` function was added in  https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2842 and will be available in the next major release. Thank you for your request!
