### ISSUE TITLE
operator dashboard doesn't work

### ISSUE THREAD

**Issue by flokli** [VictoriaMetrics/VictoriaMetrics#2797]
I'm using victoria-metrics-operator (v0.23.3), with a custom service Monitor to scrape its metrics:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2022-06-29T13:01:18Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: victoria-metrics-operator
    app.kubernetes.io/name: victoria-metrics-operator
  name: victoria-metrics-operator
  namespace: victoria-metrics-operator
  resourceVersion: "95005087"
  uid: af8e4d9a-79c8-4f77-bb63-3b526d0dee67
spec:
  endpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/instance: victoria-metrics-operator
      app.kubernetes.io/name: victoria-metrics-operator
```

I installed the VictoriaMetrics / operator dashboards into grafana (from https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/operator.json).

`job` and `instance` variable selections stay empty. Looking at the dashboard definition, it seems they use the `operator_log_messages_total` and `vm_app_uptime` metrics, which are for some reason not exposed in the `/metrics` endpoint of `victoria-metrics-operator`:

```
$ curl localhost:8080/metrics | grep vm_app
$ curl localhost:8081/metrics | grep operator_
```

**Comment by hagen1778** [comment]
@denisgolius @f41gh7 could you please take a look?

**Comment by f41gh7** [comment]
Hello, operator dashboard compatible with operator version v0.25 or above. 

 It's mentioned at dashboard description: 

`"description": "Overview for operator VictoriaMetrics v0.25.0 or higher",`

 Previous operator versions don't have needed metrics.

**Comment by flokli** [comment]
Indeed, this fixes it for me. Thanks!

**Comment by kiyoad** [comment]
It seems that the `operator_log_messages_total` metric does not exist in VictoriaMetrics Operator v0.59.1.
As a result, the variables `job` and `instance` defined in the [VictoriaMetrics Operator Dashboard](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/operator.json) are undefined, causing the Grafana dashboard for the VictoriaMetrics Operator to not function properly.

**Comment by f41gh7** [comment]
> It seems that the `operator_log_messages_total` metric does not exist in VictoriaMetrics Operator v0.59.1. As a result, the variables `job` and `instance` defined in the [VictoriaMetrics Operator Dashboard](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/operator.json) are undefined, causing the Grafana dashboard for the VictoriaMetrics Operator to not function properly.

 Hello, metric must exist at given version according to https://github.com/VictoriaMetrics/operator/blob/a6729aa4a430b4bc5d1d061e8e9ce3af3f884120/internal/controller/operator/factory/logger/logger.go#L28

 Could you please make sure that metrics collection is configured properly?

**Comment by kiyoad** [comment]
Thank you for your comment, and apologies for the lack of information provided earlier.

It appears that the `operator_log_messages_total` metric depends on the log level of the operator. When the log level is set to the default "info", the metric is exposed. However, it seems that it is not exposed when the log level is set to "error".
