### ISSUE TITLE
Grafana VictoriaMetrics dashboard not collecting data

### ISSUE THREAD

**Issue by khansen1960** [VictoriaMetrics/VictoriaMetrics#28]
The Grafana VictoriaMetrics dashboard does not collect data. I have the VictoriaMetrics application 1.18.3. I believe that this is due to the "job" name not being set. The dashboard has a job selector that displays "None". The instructions for Prometheus setup  say nothing about assigning a job_name for the remote_write statements in the prometheus.yml.
How is this job field populated? is this an error in the document setup instructions?

**Comment by hagen1778** [comment]
Hi @khansen1960 
Please check https://github.com/VictoriaMetrics/VictoriaMetrics#monitoring
VictoriaMetrics does not store it's own metrics automatically - they must be scraped by Prometheus. If you already have Prometheus installation then modify `prometheus.yml` with following:
```
scrape_configs:
  - job_name: 'vmetrics'
    static_configs:
      - targets: ['<victoriametrics-addr>:8428']
```
Then apply changes via:
```
kill -HUP `pidof prometheus`
```
If everything was set correct, you will be able to query metric `vm_app_version` from Prometheus. This is what variable `job` does in dashboard.

**Comment by khansen1960** [comment]
Roman

Thank you. I know have the VictoriaMetrics dashboard working.

Keith Hansen | Network Operations Center | [24]7.ai | noc@247.ai<mailto:noc@247.ai>  | NOC: +1-866-861-1546 | www.247.ai<http://www.247.ai>

**Comment by valyala** [comment]
Closing the issue as resolved. @khansen1960 , feel free re-opening it if you have additional questions
