### ISSUE TITLE
vmagent: custom http headers for remote write requests

### ISSUE THREAD

**Issue by YuriKravetc** [VictoriaMetrics/VictoriaMetrics#2805]
**Is your feature request related to a problem? Please describe.**
It is not possible to send custom http headers for remote write requests with current vmagent functionality.

**Describe the solution you'd like**
Add the possibility to send custom http headers for remote write requests.

**Comment by f41gh7** [comment]
looks like duplicate https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2796

**Comment by YuriKravetc** [comment]
> looks like duplicate #2796

I was going to give #2796 a question label and set this one as a separate feature request.

**Comment by valyala** [comment]
`vmagent` gains support for sending custom http headers to the configured `-remoteWrite.url` in the commit c392d6d173edf95a2e46e686fa604d5332296ce6 . Custom http headers can be specified via `-remoteWrite.headers` command-line flag. For example: `-remoteWrite.headers=My-Auth:foo` would send `My-Auth: foo` http header with each request to `-remoteWrite.url`. It is possible to configure multiple headers - they must be delimited with `^^`. For example, `-remoteWrite.headers=Foo:bar^^baz:xyz` would send `Foo: bar` and `baz: xyz` http headers with each request to `-remoteWrite.url`.

This functionality will be available in the next release. In the mean time it is possible to evaluate this functionality by building `vmagent` from the commit c392d6d173edf95a2e46e686fa604d5332296ce6 according to [these build instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment]
`vmagent` supports specifying arbitrary http headers to send per each `-remoteWrite.url` starting from [v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Comment by truepele** [comment]
@valyala is there a way to prevent printing secrets to logs if a secret env was used for `-remoteWrite.headers`?

**Comment by f41gh7** [comment]
> @valyala is there a way to prevent printing secrets to logs if a secret env was used for `-remoteWrite.headers`?

 No, there is no way to hide it atm. But it makes sense to me. Could you please open new issue for it?

**Comment by truepele** [comment]
@valyala thanks, here: #6938

**Comment by truepele** [comment]
@valyala and a PR: #6940
