### ISSUE TITLE
vmui: datepicker improvements

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#2811]
1. Change date should not immediately result in to re-draw of graps.

Please re-draw graph only on pressing Enter OR Closing date picker window
Cancel button should reset changes AND close the window

2. Change TO should not result in changing FROM 
This is annoying, if FROM older than just wrap it in red (show error) and do nothing

**Comment by valyala** [comment]
The mentioned improvements to [vmui](https://docs.victoriametrics.com/#vmui) have been added to [VictoriaMetrics v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
