### ISSUE TITLE
vmui: graph action on moush hold and move

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#2812]
Need to change the hold and move the mouse action 

1. The current one - graph moves left or right 

Desirable 
1. ctrl (command on mac) + hold and move mouse  - graph moves left or right
2. hold and move mouse - graph zoom in 
3. Introduce another action button (or history back) to zoom out back

**Comment by valyala** [comment]
`vmui` supports Graphite-like zooming starting from [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See 
 [these docs](https://docs.victoriametrics.com/#vmui) for details. Closing the feature request as done.
