### ISSUE TITLE
vmui: add trace to json response if it's enable

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#2814]
show json trace too in response if it's enabled

**Comment by valyala** [comment]
Re-opening the issue until the next release is out with this feature.

**Comment by valyala** [comment]
[Query trace](https://docs.victoriametrics.com/#query-tracing) should be displayed in JSON view at [vmui](https://docs.victoriametrics.com/#vmui) starting from [v1.83.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
