### ISSUE TITLE
vmui: add copy button to row on Table view

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#2815]
The button should copy row in Metricqls format 

https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?g0.range_input=12h%2040m%20827ms&g0.end_input=2022-06-30T21%3A28%3A58&g0.step_input=108.573&g0.relative_time=none&g0.tab=table&g0.expr=process_cpu_seconds_total - copy button from first row should add to buffer 

process_cpu_seconds_total  {cluster_num:="1", cluster_retention="1m", instance="play-1m-1-vmagent.us-east1-b.c.victoriametrics-test.internal:8429", job= "vmagent"}

**Comment by valyala** [comment]
This feature has been implemented in [VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
