### ISSUE TITLE
vmsingle: external_labels are ignored during federation

### ISSUE THREAD

**Issue by afoninsky** [VictoriaMetrics/VictoriaMetrics#2824]
### Problem:
vmsingle doesn't add external labels:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/
```
global:
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    [ <labelname>: <labelvalue> ... ]
```

### Current configuration:

- vmsingle 1.78.0
- `/usr/bin/victoria-metrics-prod -storageDataPath=/var/lib/victoria-metrics-data -retentionPeriod=14d -httpListenAddr=127.0.0.1:9090 -maxLabelsPerTimeseries=40 -promscrape.suppressDuplicateScrapeTargetErrors=true -promscrape.suppressScrapeErrors=true -promscrape.streamParse=true -promscrape.config.strictParse=false -promscrape.maxScrapeSize=167772160 -search.cacheTimestampOffset=6m -promscrape.config=/etc/prometheus/prometheus.yaml`

```
global:
  external_labels:
    cluster: xxxx
    cluster_dc: lhr4
    cluster_region: eu-uk
    cluster_type: application
```

### Tests

The following command should return the same labelset:
`curl -G --data-urlencode 'match[]={__name__="memory_request_per_persona_per_cluster_bytes"}' https://domain.tld/federate
`

Both vm and prometheus are running with the same config.

#### vmsingle 1.78.0 output example:
```
memory_request_per_persona_per_cluster_bytes{namespace="kubernetes-dashboard",container="dashboard-metrics-scraper",label_service_directory_persona="..."} 400000000 1656935280000
```

#### prometheus output example:
```
memory_request_per_persona_per_cluster_bytes{container="vault-sidecar",label_service_directory_persona="...",namespace="panda",cluster="xxxx",cluster_dc="lhr4",cluster_region="eu-uk",cluster_type="application",cluster_zone="a",instance=""} 1.6777216e+07 1656934909901
````

**Comment by valyala** [comment]
Labels defined in `global -> external_labels` section of the file pointed by `-promscrape.config`, must be added only to metrics scraped from targets defined in this file. If the metric is pushed directly to VictoriaMetrics via other [supported data ingestion protocols](https://docs.victoriametrics.com/#how-to-import-time-series-data), then the labels from `global -> external_labels` section aren't added to the metric, because the `-promscrape.config` file isn't used at all when VictoriaMetrics accepts metrics via push protocols.

**Comment by afoninsky** [comment]
In my case, metrics are creating using evaluation rule. In prometheus evaluation mechanism is a part of binary itself so external metric is applied, in victoriametrics evaluated metrics are delivered by external vmalert component so labels from config are not adding automatically. Agreed with @valyala that is it expected behaviour not a bug. 

Bit from the point of end-user who migrates prometheus to vmsingle it can be a surprise, worth documenting though.
