### ISSUE TITLE
vmalert: UI routing update

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#2825]
**Is your feature request related to a problem? Please describe.**
With adding https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1739 vmalert component is now accessible from vmselect. This feature makes VictoriaMetrics experience better:
* no need to expose vmalert UI to users who already has access to vmselect;
* it is now possible to integrate vmalert's ui to vmselect ui, as we do with vmui;
* VictoriaMetrics now is partially compatible with ng-alerts in Grafana.

But currently, experience of accessing vmalert's UI has some issues:
* it is not clear which requests can be proxied from vmselect to vmalert, since both components could have conflicting `path`;
* reverse-proxy on vmalert's side does not allow proxying requests to static files;
* vmalert's UI is only partially accessible from vmselect side.

**Describe the solution you'd like**
Would be great if vmalert's UI was fully accessible from vmselect component. The list of actions we might want to take:
- [x] make all links in vmalert relative, so it continue to work even if vmalert sits behind the proxy;
- [x] update vmalert's routing to always have component-unique path prefix, e.g. `/vmalert`;
- [x] deprecate vmalert's `/api/v1/<groupID>/<alertID>/status` endpoint in favour of something simpler like `/api/v1/alerts?group_id=<>&alert_id=<>`
- [x] update vmselect to proxy all vmalert-specific requests, including static files.

**Comment by valyala** [comment]
Web urls in `vmalert` have been updated according to [the requirements](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2825#issue-1293193847) starting from [v1.79.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by valyala** [comment]
FYI, support for old paths in the form `/api/v1/<groupID>/<alertID>/status` has been removed from `vmalert` starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Now [vmalert](https://docs.victoriametrics.com/vmalert.html) supports only new paths in the form `/api/v1/alerts?group_id=<>&alert_id=<>`.
