### ISSUE TITLE
Can you implement Hoeffding Bound function

### ISSUE THREAD

**Issue by vkuznet** [VictoriaMetrics/VictoriaMetrics#283]
**Is your feature request related to a problem? Please describe.**
We would like to perform statistical analysis of time series using Hoeffding Bound function, see https://www.youtube.com/watch?v=6UwcqiNsZ8U&feature=youtu.be&t=1237
Since it is general type function which can be applied to any metric it would be nice to have in VM.

**Comment by valyala** [comment]
@vkuznet , the commit 8b14572f7032132e07f499dabae53bfae56c91b6 adds the following functions:

* `hoeffding_bound_upper(phi, m[d])` - returns upper bound for values from `m` time series over duration `d` for `phi` in the range `[0..1]` (`phi=0` returns values equal to `avg_over_time(m[d])`).
* `hoeffding_bound_lower(phi, m[d])` - returns lower bound for values from `m` time series over duration `d` for `phi` in the range `[0..1]` (`phi=0` returns values equal to `avg_over_time(m[d])`).

For example, the following query would return data points for `x`, which exceed 99.9% Hoeffding bound calculated over data points from the last minute:

`x > hoeffding_bound_upper(0.999, x[1m])`

Could you verify whether these functions are properly implemented (see commit 8b14572f7032132e07f499dabae53bfae56c91b6 ) and whether they match your needs? You can build VictoriaMetrics from this commit using [these instructions](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources).

**Comment by vkuznet** [comment]
I was able to build, deploy and run few queries with this patch. Everything looks fine, but I don't have enough statistics in my dev Prometheus instance and for production we need an official docker image. Can you build and tag one that we can use? So far, we used `image: victoriametrics/victoria-metrics`.

**Comment by valyala** [comment]
> Can you build and tag one that we can use? So far, we used image: victoriametrics/victoria-metrics.

I'm planning to publish the next release with `hoeffding_bound_*` functions in the next few days.

**Comment by valyala** [comment]
@vkuznet , `hoeffding_bound_*` functions are available starting from [v1.32.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing this issue as resolved. Feel free re-opening it if the current implementation of `hoeffding_bound_*` functions works incorrectly.
