### ISSUE TITLE
vmalert's label bug

### ISSUE THREAD

**Issue by Aigoss** [VictoriaMetrics/VictoriaMetrics#2843]
**Describe the bug**
When I configured vmalert/rules.yml, I added a label with a value of {{ $value }} to the rule, and then vmalert was abnormal. Either the alarm cannot be triggered, or the triggered alarm remains in the pending state. When I deleted the label and restarted vmalert (I tried /-/reload to no avail), it returned to normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/108331985/177955136-b0f9ea23-391e-496c-8818-3e0db69717bb.png)
![image](https://user-images.githubusercontent.com/108331985/177954581-b14f91b9-43aa-4afa-bb33-455b7df49bf5.png)
![image](https://user-images.githubusercontent.com/108331985/177954632-93fa4e6c-f6ff-492d-be60-e6e8ec4b448d.png)

**Version**
./vmalert-prod -version vmalert-20220621-070501-tags-v1.78.0-0-g091408be6

**Comment by dmitryk-dk** [comment]
Hi @Aigoss ! Thank you for you question. As you described, you tried to use dynamic value in alerting labels which is not correct. When your rule will fire it would be new rule, because it will have new label value for your alerting rule. That's why your alerts are always pending

**Comment by Aigoss** [comment]
> Hi @Aigoss ! Thank you for you question. As you described, you tried to use dynamic value in alerting labels which is not correct. When your rule will fire it would be new rule, because it will have new label value for your alerting rule. That's why your alerts are always pending

Thanks a lot, I forgot to use “annotations” 
![image](https://user-images.githubusercontent.com/108331985/179134029-54022446-3a28-4201-bc23-f2a3aca97d59.png)

**Comment by dmitryk-dk** [comment]
Hi @Aigoss ! Can we close the issue?

**Comment by hagen1778** [comment]
Closing the issue as inactive. 
@Aigoss let us know if there are still questions.
