### ISSUE TITLE
the new version of vmselect need -eula flag, thats mean my company must buy a enterprise license?  

### ISSUE THREAD

**Issue by forezp** [VictoriaMetrics/VictoriaMetrics#2855]
the new version of vmselect need -eula flag, thats mean my company must buy a enterprise license?

**Comment by YuriKravetc** [comment]
Hi,

It does not.

Any chance you downloaded the enterprise version of vmselect?
Non-enterprise version could be found here:
Binary:
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.78.1/victoria-metrics-amd64-v1.78.1-cluster.tar.gz
Docker:
https://hub.docker.com/layers/vmselect/victoriametrics/vmselect/v1.78.1-cluster/images/sha256-37d70eb68c8a90948dcd22addcd982daa37577ff9b606de3ebc5839d89057dec?context=explore

Tested it - works fine for me.

Feel free to test it with docker-compose by cloning the branch:
`git clone https://github.com/VictoriaMetrics/VictoriaMetrics --branch cluster && cd VictoriaMetrics/deployment/docker && docker-compose up`

build version: 1.78.1-cluster

**Comment by valyala** [comment]
Closing this issue as answered
