### ISSUE TITLE
rate() on long-running counter doesn't ignore the first reading, causing a huge spike

### ISSUE THREAD

**Issue by localpref** [VictoriaMetrics/VictoriaMetrics#286]
I've observed a stark difference in displaying a graph from the same data set in prometheus vs victoriametrics. I had changed some automation regarding scraping from bind_exporter which caused some of the labels to change, thus creating new time series. bind_exporter has been running for a while, and when the new scrapes came in, I observed this:
`rate(bind_incoming_queries_total{instance="192.0.2.1:9119",type="A"}[1m])`
![image](https://user-images.githubusercontent.com/9627849/72143193-8b18f100-3396-11ea-8935-7342d826810c.png)
![image](https://user-images.githubusercontent.com/9627849/72143756-94ef2400-3397-11ea-9860-20705c4a8d7b.png)

I've read #279, which seems related but not exactly the same issue. I suspect the same root cause, though. As this is a new series, the very first reading needs to be treated like a counter reset but apparently isn't - bind_exporter will give me a counter of approx 1.3G for the new series, VM displays the rate of (1.3G - 0) for the first data point. After the wrongly calculated first point, the rate is correct.
VM needs to make sure that new series treat the first value as a counter reset.

I've restarted VM with disableCache as suggested in #279 to no effect.

**Comment by localpref** [comment]
I've just seen that 1.32.1 was released yesterday and https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d5aeda0e1a7ef40985f2a8efcc562e583ec6e36e fixes this bug. :)

**Comment by localpref** [comment]
I've upgraded to 1.32.1 and this behaviour disappeared.

**Comment by tenmozes** [comment]
@localpref thanks for confirmation

**Comment by schmurfy** [comment]
I get this on 1.58.0, each time my service restart (and set the counter back to 0) I get a huge spike with this query:
```promql
rate(sum(packets_sent{}))
```

I fixed the issue by limiting the results but it's ugly (I have values around ~300 so this crude filter works):
```promql
rate(sum(packets_sent{})) < 1000
```

the counter is produced by a kubernetes pod.
