### ISSUE TITLE
VMAlert should have remoteWrite.label and remoteRead.header support

### ISSUE THREAD

**Issue by hellorill** [VictoriaMetrics/VictoriaMetrics#2860]
Related to https://github.com/VictoriaMetrics/operator/issues/492

We use M3 as a persistent multi-tenant storage, where tenants are implemented by using some specific headers to filter metrics by labels or change metric labels before writing to the storage, for example for queries:
M3-Restrict-By-Tags-JSON: '{"match":[{"name":"remotewrite_source","type":"EQUAL","value":"zone1"}],"strip":["remotewrite_source"]}'
VMAgent supports remoteWriteSettings, so we can add additional labels before sending metrics to the remoteWrite storage. VMAlert does not, so for M3 it manages alert/rule states globally. We need to setup an additional proxy to add headers on read/write operations, which is not very flexible for multiple VMAlert instances.

A possible workaround could be to use -external.label, but it only works for ALERTS, ALERTS_FOR_STATE, and rules generated from metrics. I think this logic should be kept.

**Comment by hellorill** [comment]
We need to add some specific labels to any vmalert metrics, before sending them to the remoteWrite storage. As I saw in the doc (and tested), external.label do the same work, as remoteWrite.label in vmagent.
For remoteRead we also need this to filter metrics before alert/rule evaluations. There is no external.label analogue, so we need something like:
- add remoteRead.header;
- add remoteRead.label.

In the closed pr I implement the remoteRead.header flag, but I dont think it is flexible, it might be better to implement remoteRead.label, which would do the same thing as m3 with [headers](https://m3db.io/docs/reference/m3query/api/query/#optional-1) logic.

**Comment by hellorill** [comment]
> You meant datasource.Url? remoteRead.Url is used only for reading ALERTS_FOR_STATE series in order to restore the state of pending alerts when vmalert is restarted.

Yes, datasource.url if external.labels is used for ALERTS_FOR_STATE queries.

> Adding flags for setting additional headers for requests via remoteWrite/remoteRead/datasource URLs seems feasible to me.

Seems good.

For clear, we have a cluster "ex1":
- for vmagent we add external.label=cluster=ex1;
- for vmalert we add external.label=cluster=ex1 and use extra_filters with cluster=ex1.

As a result, we have:
- all vmagent metrics have "cluster=ex1" label;
- all vmalert metrics (ALERTS/ALERTS_FOR_STATE and calculated by rules) have "cluster=ex1" label;
- all vmalert datasource/remoteRead queries have an additional label "cluster=ex1", for both the ALERTS_FOR_STATE and metrics for rule calculation.

I'm right?

**Comment by hellorill** [comment]
> Or did you ask for setting custom headers on the group or rule level?

After some tests, it would be great to set custom headers at the rule level. For example, we can route heavy rules, that request too many datapoints, to different tables with aggregated data, based on header information. This is necessary due to the [memory consumption of remoteRead](https://prometheus.io/blog/2019/10/10/remote-read-meets-streaming/).

**Comment by valyala** [comment]
The commit 70a822f3a00abb964c416e77b928377d7c5c919d adds ability to configure additional http headers to send to `-datasource.url`, `-remoteRead.url` and `-remoteWrite.url` via `-datasource.header`, `-remoteRead.headers` and `-remoteWrite.headers` command-line flags.

The commit 88edb3f6cfb0933b5b551cb4b1234af275c4fced adds ability to configure additional http headers to send to `-datasource.url` when performing alerting and recording rules on a per-group level. See [these docs](https://docs.victoriametrics.com/vmalert.html#groups) for details.

These commits will be included in the next release.

**Comment by hellorill** [comment]
Thanks!

**Comment by valyala** [comment]
`vmalert` [v1.80.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) allows specifying HTTP request headers for `-datasource.url`, `-remoteRead.url` and `-remoteWrite.url` via `-datasource.headers`, `-remoteRead.headers` and `-remoteWrite.headers` command-line flags. Closing the feature request as done.
