### ISSUE TITLE
vmagent: local dns cache is not used

### ISSUE THREAD

**Issue by agrimal** [VictoriaMetrics/VictoriaMetrics#2868]
**Describe the bug**
The setup with 2 vmagents, querying metrics on hosts using prometheus remote write generate millions of DNS queries per day.
Each vmagent is installed on a Debian 10 buster virtual machine. On the system side, the package unscd is installed and configured to cache postitive queries for an hour, and negative queries for 30 seconds.
However vmagent is not using the cache provided by the nscd process. It sends a `A` query every 15 seconds, which makes 5760 queries a day per target per vmagent. As there are dozens of targets, we are reaching over 2 millions requests per day.
The local cache is working well and can be verified with the command `getent hosts <hostname>`.

Is there a way I can configure DNS cache ttl or make vmagent use system DNS cache ?

**Version**
```
$ ./victoria-metrics-prod --version
vmagent-20220521-000611-tags-v1.77.2-0-g2d2d15b0d
```

**Used command-line flags**
```
vmagent-prod -envflag.enable
```

**Comment by denisgolius** [comment]
Hi @agrimal !
By default vmagent use dns from system and using dns cache should work. Do you use vmagent over docker or run it as compiled binary?

**Comment by agrimal** [comment]
It's the compiled binary from tar.gz archives available on github.

**Comment by denisgolius** [comment]
Hey @agrimal !
By default `vmagent` [use pure **go** DNS resolver](https://pkg.go.dev/net#hdr-Name_Resolution) because of lower performance on **cgo**. That's why `vmagent` don't use system DNS cache from your case. I've added feature request #2878 that should help for your case.

**Comment by agrimal** [comment]
Hello @denisgolius 
Maybe another solution is to use, if possible, the TTL of the record given by the DNS server ?
For example if TTL is 3600, then cache it locally for an hour.

**Comment by jiekun** [comment]
Please track it by https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2878.

I think we could close this issue (which is actually a feature request, tho).
