### ISSUE TITLE
delete metrics data not work

### ISSUE THREAD

**Issue by vb3328998** [VictoriaMetrics/VictoriaMetrics#2869]
127.0.0.1:8481/delete/0/prometheus/api/v1/admin/tsdb/delete_series?match[]={__name__!="advertCTRpredict_pctr"}

According to the API interface given by the official website, I deleted the index, but actually I still didn't delete it. Can you tell me what went wrong?

The deleted indicators remain unchanged
{"name":"advertCTRpredict_pctr","value":68967205}

**Comment by dmitryk-dk** [comment]
Hi @vb3328998 ! Thank you for your request. Can you check logs of your select component it should show whats wrong with your request? Can you check this api request ```http://<victoria-metrics-addr>:8428/api/v1/series?match[]=<timeseries_selector_for_delete>``` does it return any result with your selector?

**Comment by vb3328998** [comment]
The format error in curl is printed in the log, but the log is not printed after the output result is successful, and the return status code is 204

**Comment by vb3328998** [comment]
I use Cluster-VictoriaMetrics. Should the API interface be a select component?
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html

**Comment by dmitryk-dk** [comment]
Can you check log messages from select component not from curl?
If you are using cluster version you should use cluster API interface. 

To be shure that you correctly delete something you can check this data providing curl request to 
```http://<victoria-metrics-addr>:8428/0/prometheus/api/v1/series?match[]=<timeseries_selector_for_delete> ```

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/178984311-9c547772-4446-412c-995e-3e8473ce41c5.png)
Yes, return  204

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/178986152-b1b4f274-edd8-40d1-a697-4d9977e77dbf.png)
I can't query this indicator. There are 60million data. R & D has written the wrong code, resulting in 60million indicators. So now to delete this wrong indicator, I limit it to 6million. Opening larger data will lead to a full memory，oom

**Comment by dmitryk-dk** [comment]
I just want to be sure that you are correctly trying to delete metric name not label. To do that i want to see your metrics how it is looks like

```curl http://<vmselect>:8481/select/0/prometheus/api/v1/query_range -d 'query=advertCTRpredict_pctr' -d 'start=-1d' -d 'step=1h'```

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/178989220-7c45339f-3667-410a-b79f-e7874b73f132.png)
I'd like to see it, but I can't find it out
What else can I do？

**Comment by vb3328998** [comment]
This indicator is no longer being pulled, but it still can't be found, indicating that it exceeds the limit

**Comment by dmitryk-dk** [comment]
You can try to  increase ```-search.maxSeries``` flag on your vmselect component to 1M for example. Because at that moment it was set to 600K. And try to make this request, there is small time range between start and end
```curl http://<vmselect>:8481/select/0/prometheus/api/v1/series -d 'match[]=advertCTRpredict_pctr' -d 'start=1657804400' -d 'end=1657804401'```

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/178991875-08977cf7-2fd1-41b6-9944-d0ea6f92feee.png)
oh my god,it not enough

**Comment by vb3328998** [comment]
I have to configure vmstorage together to take effect

**Comment by vb3328998** [comment]
![image](https://user-images.githubusercontent.com/40584745/178992627-bb3d7709-3d74-44b2-879e-525d5c426399.png)
I set it to 70m

**Comment by dmitryk-dk** [comment]
Let's try this request
```curl http://<vmselect>:8481/select/0/prometheus/api/v1/series -d 'match[]={name=~"advertCTRpredict_pctr"}' -d 'start=1657804400' -d 'end=1657804501'```

**Comment by vb3328998** [comment]
Volametrics is a good software

**Comment by dmitryk-dk** [comment]
@vb3328998 can we close the issue?

**Comment by vb3328998** [comment]
yes，thank you
