### ISSUE TITLE
Table header overlaps datepicker calendar panel

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#2874]
**Describe the bug**
When you click into Table tab and try to change some date table header overlaps calendar panel
Please check the image below

**Expected behavior**
The table head should not overlap calendar panel

**Screenshots**
<img width="805" alt="Screenshot 2022-07-15 at 09 41 22" src="https://user-images.githubusercontent.com/12189570/179166781-0e682c01-d1f4-4563-8200-168ebf517a86.png">

**Comment by valyala** [comment]
The bug has been fixed in the commit edecd2493c8748aace1460865a5ac88ab60fda03 . This commit will be included in the next release.

**Comment by valyala** [comment]
FYI, the bugfix has been included in [VictoriaMetrics v1.79.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
