### ISSUE TITLE
Unable to assume role with ECS credentials

### ISSUE THREAD

**Issue by transacid** [VictoriaMetrics/VictoriaMetrics#2875]
**Describe the bug**
Assuming a role in an AWS ECS container does currently not work. The returned credentials do not assume arole.

**To Reproduce**
Run VMAgent in ECS and try to assume a role. returned credentials are of the Taskrole not the to-be-assumed role.

**Expected behavior**
returned credentials are of the to-be-assumed role

**Version**
1.78.1

**Comment by valyala** [comment]
FYI, the issue should be fixed in [vmagent v1.79.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
