### ISSUE TITLE
How to recover

### ISSUE THREAD

**Issue by kengan** [VictoriaMetrics/VictoriaMetrics#288]
I use victoriaMetrics to save the metric data from prometheus about tow hour.
For some reason, the server is down for about onehour. 
After recovery, I can not search the the new data , which is send to victoriaMetrics after server recovery.
For example, I send metrics data to victoriaMetrics at 9:00 . At 11:00 the server is down.  At 12:00 the server is recovered and the metrics data is send to victoriaMetrics  again. But I can not search the data after 12:00 with prometheus api  the /api/v1/query 
How to solve this problem. Thank you

**Comment by valyala** [comment]
Prometheus starting from v2.8 should be able to push up to 2 hours of recent data to remote storage such as VictoriaMetrics after it was unavailable for some time - see [this article for details](https://grafana.com/blog/2019/03/25/whats-new-in-prometheus-2.8-wal-based-remote-write/).

Could you check for Prometheus and VictoriaMetrics logs before and after server recovery?

Also try stopping VictoriaMetrics, deleting `<-storageDataPath>/cache` directory and starting VictoriaMetrics again (`<-storageDataPath>` is the corresponding command-line flag value passed to VictoriaMetrics). Probably VictoriaMetrics cached gaps in data on the time range from 11:00 to 12:00.

**Comment by valyala** [comment]
@kengan , could you look into Prometheus logs? Probably Prometheus stuck writing new data to VictoriaMetrics. Also could you show graphs for Prometheus metrics [mentioned here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/287#issuecomment-574543962) ?

**Comment by valyala** [comment]
@kengan , are there any updates on this issue?

**Comment by f41gh7** [comment]
Feel free to re-open or create new issue.
