### ISSUE TITLE
Add ability to set per-label retention period

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#289]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be great to have distinct retention periods across distinct sets of time series. For example, time series with label `job="app"` could be stored for 3 months, while time series with label `job="node_exporter"` could be stored for 6 months.

**Describe the solution you'd like**
It would be great if VictoriaMetrics could provide ability to set distinct retention periods for time series with the specified labels. For example, `-retentionByLabel='job="app":3m'` would set retention period for time series with the label `job="app"` to 3 months.

**Describe alternatives you've considered**
An alternative is to run multiple distinct VictoriaMetrics instances (or clusters), each with distinct `-retentionPeriod` and then ingest data via a proxy in front of these instances, which would route incoming data to instances with the needed retention period depending on the configured retention periods for labels. [vmagent](https://victoriametrics.github.io/vmagent.html) with multiple `-remoteWrite.url` and `-remoteWrite.urlRelabelConfig` command-line options can be used as such proxy. See [relabeling docs for vmagent](https://victoriametrics.github.io/vmagent.html#relabeling) for more details.

[Promxy](https://github.com/jacksontj/promxy) in front of VictoriaMetrics instances with distinct retention periods could be used for querying the data and merging results.

**Comment by Allineer** [comment]
influxdb-per-database-retention like feature

**Comment by ramm** [comment]
There's another (but probably related) feature, that would definitely solve a bunch of problems: retention OF label, rather than BY label.

I.e. I have a bunch of time series, that represent requests to a service, that is spread amongst multiple instances: **rps{service=<name>, allocation_id=<UUID>}**.
I don't really need allocation_id granularity for a long time (days/weeks at the most, they move around all the time), but I want the service rps metrics to be available for a really long time (historical reasons, years). 

It would be nice, if there was an ability to merge **rps{service=<name>, allocation_id=<UUID>}** into **rps{service=<name>}** after some time, throwing away a bunch of aggregation needed for old data.

**Comment by varuzam** [comment]
@ramm if you gather the metric by prometheus it is able to skip labels.

**Comment by lcfang** [comment]
Hi, @valyala 

> Sometimes it would be great to have distinct retention periods across distinct sets of time series. For example, time series with label job="app" could be stored for 3 months, while time series with label job="node_exporter" could be stored for 6 months.

I think this is very useful. and Is there any plan for the feature?

**Comment by valyala** [comment]
> I think this is very useful. and Is there any plan for the feature?

Unfortunately there is no ETA for the feature :(

**Comment by lcfang** [comment]
I think running multiple distinct VictoriaMetrics instances (or clusters) for distinct `retentionPeriods` is not a good idea especially when many `retentionPeriods` needed. Can we use subpath for `storageDataPath`  to distinct `retentionPeriod`?

**Comment by lcfang** [comment]
I think running multiple distinct VictoriaMetrics instances (or clusters) for distinct retentionPeriods is not a good idea especially when many retentionPeriods needed and using vm-cluster. 
Can we use subpath for storageDataPath to distinct retentionPeriod? @valyala

**Comment by valyala** [comment]
> Can we use subpath for storageDataPath to distinct retentionPeriod?

This is how multiple retention periods are going to be supported in the future - data for every configured retention will be stored in a separate folder under `-storageDataPath` directory. This isn't supported at the moment.

**Comment by valyala** [comment]
The related feature request - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/143

**Comment by valyala** [comment]
FYI, the next release of [VictoriaMetrics enterprise](https://victoriametrics.com/products/enterprise/) will support multiple retentions for distinct sets of time series and/or tenants via [series selectors](https://docs.victoriametrics.com/keyConcepts.html#filtering) - see [these](https://docs.victoriametrics.com/#retention-filters) and [these](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#retention-filters) docs for details. See also [the changelog](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment]
VictoriaMetrics supports the ability to set multiple retention periods for distinct sets of labels via [retention filters](https://docs.victoriametrics.com/#retention-filters) starting from [v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Comment by valyala** [comment]
Similar issues from Prometheus and Thanos:

* https://github.com/prometheus/prometheus/issues/1381
* https://github.com/thanos-io/thanos/issues/903
