### ISSUE TITLE
vmagent externalLabels override the same labels scraped from targets

### ISSUE THREAD

**Issue by okzheng** [VictoriaMetrics/VictoriaMetrics#2892]
When I add external labels to vmagent, I found some labels scraped from targets have been override by external labels. The action is inconsistent with Prometheus. I didn't understand the design. Maybe, Consider add an enable switch for override, for instance honorLabels?
Version: vmagent v1.72.0

**Comment by YuriKravetc** [comment]
Hi,
Can you elaborate on it, please?
If possible share the config.

**Comment by okzheng** [comment]
Following is the vmagent config about external labels.
```
external_labels:
    region: cn-sh
    env: production
    grafana_datasource: Prometheus-CM
```
The vmagent scraped metrics from some various targets, and some of metrics contain a label named **region** but different value. For example:
`cloudmonitor_nas_capacity{region="cn-sh", app="cloudmonitor", env="production", instance="172.17.15.2", job="cloudmonitor", namespace="monitoring", service="cloudmonitor"}
cloudmonitor_nas_capacity{region="cn-hk", app="cloudmonitor", env="production", instance="172.17.16.2", job="cloudmonitor", namespace="monitoring", service="cloudmonitor"}`
We expected vmagent could add that labels if them were not found in scraped metrics. But if them were found in scraped metrics already, vmagent would not attempt to modify it. 
Prometheus meets the above requirement.
However, vmagent modified labels which name was consistent with external_labels config. The result was that labels' value were override:
`cloudmonitor_nas_capacity{region="cn-sh", app="cloudmonitor", env="production", grafana_datasource="Prometheus-CM", instance="172.17.16.2", job="cloudmonitor", namespace="monitoring", service="cloudmonitor"}`
Vmalert also behave same results.

**Comment by okzheng** [comment]
sorry, some error messages had misleaded me. vmagent work normally. Close the issue.

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2903#issuecomment-1192435720

**Comment by valyala** [comment]
Another related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3215
