### ISSUE TITLE
vmselect: adding extra labels for received results on read path

### ISSUE THREAD

**Issue by YuriKravetc** [VictoriaMetrics/VictoriaMetrics#2904]
Possibility to append an extra label to result data when query independent vm cluster by using multi-level vmselect without any change write path. e.g. append az=az1 for area zone 1 and az=az2 for area zone2
For cases when it is not possible to determine the extra label content clearly in write path - but in read path, it can be distinguished by load balance VIP of vmselect

**Comment by Yuri1Kravets** [comment]
Duplicate of #2908
Closing

**Comment by YuriKravetc** [comment]
Duplicate of #2908
Closing
