### ISSUE TITLE
Improve panel hints for dashboards

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#292]
See this discussion for details https://victoriametrics.slack.com/archives/CGZF1H6L9/p1579612402030300?thread_ts=1579611990.028000&cid=CGZF1H6L9

```
The number of pending data points should be in the range 0 - 2*<ingestion_rate> , since VictoriaMetrics pushes pending data to persistent storage every second. @hagen1778, could you update hint information for this graph in order to reduce confusion in the future?
```

**Comment by valyala** [comment]
@hagen1778 , dashboard improvements have been merged into [v1.33.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
