### ISSUE TITLE
search.maxPointsPerTimeseries should be set independently for subqueries and final results

### ISSUE THREAD

**Issue by mactyr** [VictoriaMetrics/VictoriaMetrics#2922]
**Describe the solution you'd like**
I have a pretty frequent use case where I need to run a subquery at a high resolution that is then aggregated down to a reasonable number of points (less than search.maxPointsPerTimeseries) before returning. I often receive the "too many points for the given step", "cannot exceed -search.maxPointsPerTimeseries" 422 error when executing these queries. This confused me at first, because the [documentation](https://docs.victoriametrics.com/) says: 

> -search.maxPointsPerTimeseries int
>      The maximum points per a single timeseries returned from /api/v1/query_range. This option doesn't limit the number of scanned raw samples in the database. The main purpose of this option is to limit the number of per-series points returned to graphing UI such as Grafana. There is no sense in setting this limit to values bigger than the horizontal resolution of the graph (default 30000)

One thing that's confusing about this description is that I often get this error back from `/api/v1/query` rather than `query_range`. With `query` there clearly can't too many time points being returned, because only one per series will be returned.

The other thing that's confusing is that even when I'm doing a `query_range`, I have the step such that the final number of data points returned will be well under search.maxPointsPerTimeseries, it's only the intermediate result from the subquery that exceeds the limit.

Of course, I can make the query go through by increasing my search.maxPointsPerTimeseries, but then I lose the sanity check on the number of points actually returned from the _final_ query. I think a check on the final number of data points from `query_range` is a good idea, and I'd like to retain that without sacrificing the ability to do higher-res subqueries.

Therefore, I propose separating search.maxPointsPerTimeseries into two separate options, one applying to final results and one applying to subqueries. (Perhaps with one defaulting to the other since for many users having them be the same will be fine.)

Alternatively, perhaps we don't need a way to limit the max points from a subquery at all, and we can just limit the application of seach.maxPointsPerTimeseries to the final results?

**Describe alternatives you've considered**
For now, I can just increase search.maxPointsPerTimeseries, but as noted above there's some helpful functionality that's lost that way.

**Additional context**
It looks to me like this concern was previously raised in #77 and #2635, but not with this proposed solution.

**Comment by valyala** [comment]
@dmitryk-dk , could you look into this feature request?

**Comment by valyala** [comment]
FYI, the commit 463ea6897b2e9c700b6de07b8f0f6601b867b6ff adds `-search.maxPointsSubqueryPerTimeseries` command-line flag for limiting the number of points, which can be generated per each matching time series during [subquery](https://docs.victoriametrics.com/MetricsQL.html#subqueries) execution. This is documented in [resource usage limits docs](https://docs.victoriametrics.com/#resource-usage-limits).

The commit will be included in the next release of VictoriaMetrics. In the mean time it is possible to build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it works as expected.

As for the cluster version of VictoriaMetrics, the `-search.maxPointsSubqueryPerTimeseries` command-line flag is available at `vmselect` nodes starting from the commit d32a6359b0706266a3548f4a42c52be45460a3eb . This commit will be included in the next release. In the mean time it is possible to build cluster components of VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verify whether the limit works as expected.

**Comment by mactyr** [comment]
Thank you! I have built from source and confirmed that `-search.maxPointsPerTimeseries` and `-search.maxPointsSubqueryPerTimeseries` now work as requested.

One minor suggestion: I notice that when I exceed either of these limits, the error message says, "the maximum number of points is 50000 (see -search.maxPoints* command-line flags)". It would be helpful for the message to identify _which_ limit was exceeded so the user can immediately understand how they need to adjust their query or settings.

**Comment by valyala** [comment]
The `-search.maxPointsSubqueryPerTimeseries` command-line flag is available starting from [VictoriaMetrics v1.81.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

> One minor suggestion: I notice that when I exceed either of these limits, the error message says, "the maximum number of points is 50000 (see -search.maxPoints* command-line flags)". It would be helpful for the message to identify which limit was exceeded so the user can immediately understand how they need to adjust their query or settings.

Good suggestion. @dmitryk-dk , could you address it?

**Comment by dmitryk-dk** [comment]
Hi! Yeah will do)

**Comment by valyala** [comment]
@mactyr , the commit 4415c71a2b04cfa6d493616dd829a6e0aecbc1eb puts the correct flag name in error log message when one of `-search.maxPointsPerTimeseries` or `-search.maxPointsSubqueryPerTimeseries` limits are exceeded. This commit will be included in the next release of VictoriaMetrics.
