### ISSUE TITLE
API to fetch list of all tenants (Account IDs)

### ISSUE THREAD

**Issue by sharninder** [VictoriaMetrics/VictoriaMetrics#2929]
**Is your feature request related to a problem? Please describe.**

Because of the way we insert data into victoriametrics, we have thousands of tenants (account IDs) and there is currently no way for us to fetch the list of all tenants.

**Describe the solution you'd like**

It'd be nice to have an API that could give us a list of all the tenants on a victoriametrics cluster

**Comment by valyala** [comment]
VictoriaMetrics [enterprise](https://victoriametrics.com/products/enterprise/) exposes various per-tenant metrics - see [these docs](https://docs.victoriametrics.com/PerTenantStatistic.html) for details. This allows determining the list of active tenants if the exposed per-tenant metrics are scraped by another VictoriaMetrics or Prometheus. For example, the following query would return per-tenant disk usage:

```promql
sum(vm_tenant_used_tenant_bytes) by (accountID, projectID)
```

**Comment by hagen1778** [comment]
@zekker6 is this related to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3348 ?

**Comment by zekker6** [comment]
@hagen1778 Yes, PR added API to list all tenants.

**Comment by hagen1778** [comment]
> @hagen1778 Yes, PR added API to list all tenants.

Ok, so closing this. @sharninder feel free to re-open if it doesn't fulfill your needs.

**Comment by hagen1778** [comment]
@zekker6 what about this https://github.com/VictoriaMetrics/VictoriaMetrics/issues/540 ?

**Comment by zekker6** [comment]
@hagen1778 API is exposed at vmselect level, it is has ability to list all tenants, but it isn't available as vmstorage API

**Comment by valyala** [comment]
Some context - the added endpoint is located at `http://<vmselect>:8481/admin/tenants` - see [url format](https://docs.victoriametrics.com/cluster-victoriametrics/#url-format) for details. This endpoint returns a list of all the tenants, which have at least a single [sample](https://docs.victoriametrics.com/keyconcepts/#raw-samples) in the database.

Example output from this endpoint:

```
curl http://localhost:8481/admin/tenants | jq .
{
  "status": "success",
  "data": [
    "0:0",
    "1234:22",
    "42:34"
  ]
}
```

The `/admin/tenants` endpoint has been added to `vmselect` in [v1.84.0](https://docs.victoriametrics.com/CHANGELOG.html) release.
