### ISSUE TITLE
vmctl should be able to migrate multi tenant data without specifying account ID

### ISSUE THREAD

**Issue by sharninder** [VictoriaMetrics/VictoriaMetrics#2930]
**Is your feature request related to a problem? Please describe.**
While migrating data TO the cluster version of victoriametrics, vmctl needs the accountID in the URL. This can be avoided if vmctl reads data a little more intelligently.

**Describe the solution you'd like**

An internal vmselect/vmstorage API that reads the complete data without the need to specify accountID based URLs. It will be a big help in large installations with thousands of tenants. Right now, the only way to do migration is to run vmctl in a loop a thousand+ times and it's not very scalable.

**Comment by valyala** [comment]
@sharninder , [vmctl](https://docs.victoriametrics.com/vmctl.html) gained the ability for automatic data migration between VictoriaMetrics clusters across all tenants starting from the commit 86c31f2955c291da5bb652bffa9e0d5bfd59c96e . This commit will be included in the next release. In the mean time you can build `vmctl` from this commit according to [these instructions](https://docs.victoriametrics.com/vmctl.html#how-to-build) and try migrating multitenant data between VictoriaMetrics clusters according to [these docs](https://docs.victoriametrics.com/vmctl.html#cluster-to-cluster-migration-mode).

**Comment by valyala** [comment]
`vmctl` is able to migrate data between clusters across all tenants starting from [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
