### ISSUE TITLE
vmagent support for snappy encoded body used by Prometheus

### ISSUE THREAD

**Issue by SimaoPedro1** [VictoriaMetrics/VictoriaMetrics#2931]
**Is your feature request related to a problem? Please describe.**
VMagent expect to receive data via Prometheus remote write in plain text, but some tools like Vector delivery Prometheus data with content-encoding snappy.

**Describe the solution you'd like**
Support for snappy encoded body when using vmagent with option httpListenAddr.

**Comment by valyala** [comment]
`vmagent` accepts data at `http://vmagent:8429/api/v1/write` via Prometheus remote_write protocol. This protocol uses [Snappy compression](https://en.wikipedia.org/wiki/Snappy_(compression)), so `vmagent` should properly decompress the data at `/api/v1/write` path. It is likely there was a misconfiguration with the remote write url at Vector side.

**Comment by valyala** [comment]
Closing this question as answered
