### ISSUE TITLE
Support of SRV records for Storage Node service discovery 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#2939]
**Is your feature request related to a problem? Please describe.**
In a large system 1 new storage results in a rollout restart for tens of vmselect and insert 
It would be good to have an option to have DNS service discovery

**Comment by valyala** [comment]
Closing this issue as a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/270 .
