### ISSUE TITLE
dashboard: Cache size dashboard could be more informative

### ISSUE THREAD

**Issue by YuriKravetc** [VictoriaMetrics/VictoriaMetrics#2941]
Would be great to show not only the avg and current usage for each service and the total max allowed cache size - but also max allowed for each service. (Similar to cache hit ratio dashboard)

![image](https://user-images.githubusercontent.com/30324382/182895013-1b7ecfc0-925e-466e-a62c-c02cc88efef7.png)

@valyala tagging in case I missed something.

**Comment by valyala** [comment]
The current `cache usage` graph provided by [official dashboards](https://docs.victoriametrics.com/#monitoring) do not provide useful information for the question: "which particular cache type hits or approaches its size limit?". So it would be great to have a graph showing the percentage of every cache type comparing to its limit. This graph can be built using the following query:

```metricsql
vm_cache_size_bytes / vm_cache_size_max_bytes
```

**Comment by hagen1778** [comment]
This info is available at `Troubleshooting.Cache usage % by vmstorage`:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/2902918/183368335-0bef9454-a41d-458c-b798-283b641d1b96.png">

Should we move it to the `Caches` row?

**Comment by valyala** [comment]
> Should we move it to the Caches row?

I think it would be better just copying this graph into `Caches` section

**Comment by hagen1778** [comment]
Done in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2960
