### ISSUE TITLE
vmstorage is stuck at some disk intensive operation

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/VictoriaMetrics#2942]
**Describe the bug**
I should first say that's a bizarre case: 
There is a cluster with 6 shards of `vmstorage` components. At some point, when we decided to shrink memory for a Pod a bit (60GB --> 50GB  because we added more shards before) we faced a problem when one of the `vmstorage` stuck in some Disk operation and stopped receiving data (or receiving significantly less than it should). Returning memory back didn't help.
This pod blocks data ingestion from `Vmagent` as if we shutdown this `vmstorage`, we will get restore in ingestion, but when it's back - we blocked.
<img width="1378" alt="Screenshot 2022-08-04 at 22 59 06" src="https://user-images.githubusercontent.com/5423271/182953171-8bf4a7ca-8c5b-477f-8f89-3dde31a01d18.png">

** PPROF **
[pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9263376/pprof.zip)

**To Reproduce**
don't know to be honest

**Expected behavior**
No Disk operation is blocking the ingestion of data

**Screenshots**
<img width="1378" alt="Screenshot 2022-08-04 at 23 06 38" src="https://user-images.githubusercontent.com/5423271/182952897-2b29349d-b20a-4985-9a12-f2efe309cbc6.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 06 56" src="https://user-images.githubusercontent.com/5423271/182953147-5745e5a8-be15-4425-bb6a-b2db770058f0.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 06 44" src="https://user-images.githubusercontent.com/5423271/182953152-06109881-92ef-4eb0-ab20-96ee18f77614.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 20" src="https://user-images.githubusercontent.com/5423271/182953160-9fb15fb6-a07b-40e4-a807-fbc92efe4576.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 28" src="https://user-images.githubusercontent.com/5423271/182953166-379f0564-b139-400e-9fc7-12aa4efce8f5.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 09" src="https://user-images.githubusercontent.com/5423271/182953168-cd05b07a-bdc2-498e-acf9-b3f0ed3041b3.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 04" src="https://user-images.githubusercontent.com/5423271/182953173-2e1ed227-91ac-47d6-a196-1d300e1307ff.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 36" src="https://user-images.githubusercontent.com/5423271/182953176-4c747000-4fa3-48f5-bad2-d675ac1f2102.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 00" src="https://user-images.githubusercontent.com/5423271/182953177-9fc2edb5-322b-438f-940a-099c5b1190e8.png">
<img width="1378" alt="Screenshot 2022-08-04 at 23 07 32" src="https://user-images.githubusercontent.com/5423271/182953178-b79460fb-f9ee-416a-b6df-1ca989620390.png">

**Version**
```
/ # /vmstorage-prod --version
vmstorage-20220801-081914-tags-v1.79.1-cluster-0-g8b4726ed7
```

**Used command-line flags**
```
    Args:
      --retentionPeriod=6
      --storageDataPath=/storage
      --dedup.minScrapeInterval=15s
      --envflag.enable=true
      --envflag.prefix=VM_
      --http.maxGracefulShutdownDuration=10s
      --http.shutdownDelay=5s
      --loggerFormat=json
      --loggerLevel=INFO
      --loggerOutput=stdout
      --memory.allowedPercent=60
      --search.maxUniqueTimeseries=10000000
```

**Comment by Vladikamira** [comment]
btw, there is nothing in the logs regarding IO operations after startup 1 hour ago:
```
➜  tmp kubectl logs victoria-metrics-cluster-a-vmstorage-2 | egrep -v 'closing vmselect|processing vmselect|accepted vminsert|accepted vmselect|processing vminsert|cannot perform vmselect handshake|cannot process vminsert|closing vminsert|cannot perform vminsert' | tail
{"ts":"2022-08-08T07:41:08.615Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1607","msg":"opened part \"/storage/data/small/2022_03/10_10_20220331235959.917_20220331235959.917_16E19BBB97970D6D\" in 0.010 seconds"}
{"ts":"2022-08-08T07:41:09.007Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1607","msg":"opened part \"/storage/data/big/2022_03/244175414173_320087954_20220305112300.632_20220331234858.432_16E50343FB6763A8\" in 0.366 seconds"}
{"ts":"2022-08-08T07:41:09.111Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1607","msg":"opened part \"/storage/data/big/2022_03/33683670519_34006408_20220311020000.000_20220316153942.082_16DCE88C68A514EA\" in 0.096 seconds"}
{"ts":"2022-08-08T07:41:09.431Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1607","msg":"opened part \"/storage/data/big/2022_03/160960628356_193709229_20220301000000.000_20220314095421.680_16DC2A4857E25CA6\" in 0.281 seconds"}
{"ts":"2022-08-08T07:41:09.536Z","level":"info","caller":"VictoriaMetrics/lib/storage/partition.go:1607","msg":"opened part \"/storage/data/big/2022_03/41558226666_80837970_20220312000000.000_20220325034634.819_16DF8A936ECBA7C4\" in 0.096 seconds"}
{"ts":"2022-08-08T07:41:09.537Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/main.go:101","msg":"successfully opened storage \"/storage\" in 21.083 seconds; partsCount: 330; blocksCount: 3303754285; rowsCount: 2588888939905; sizeBytes: 3672629137654"}
{"ts":"2022-08-08T07:41:09.538Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:64","msg":"accepting vminsert conns at 0.0.0.0:8400"}
{"ts":"2022-08-08T07:41:09.538Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:93","msg":"starting http server at http://127.0.0.1:8482/"}
{"ts":"2022-08-08T07:41:09.538Z","level":"info","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:94","msg":"pprof handlers are exposed at http://127.0.0.1:8482/debug/pprof/"}
{"ts":"2022-08-08T07:41:09.538Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:120","msg":"accepting vmselect conns at 0.0.0.0:8401"}
```
except messages about connecting to `vmselect` and `vminsert` and dropping connections
```
{"ts":"2022-08-08T08:57:26.916Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:170","msg":"closing vmselect conn from 10.56.126.131:49964"}
{"ts":"2022-08-08T08:57:29.975Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.22.131:39754"}
{"ts":"2022-08-08T08:57:29.975Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.22.131:39756"}
{"ts":"2022-08-08T08:57:29.975Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.22.131:39760"}
{"ts":"2022-08-08T08:57:30.008Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.22.131:39760"}
{"ts":"2022-08-08T08:57:30.008Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.22.131:39754"}
{"ts":"2022-08-08T08:57:30.008Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.22.131:39756"}
{"ts":"2022-08-08T08:57:30.684Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:122","msg":"cannot process vminsert conn from 10.56.146.132:37110: cannot send `ack` to vminsert: write tcp4 10.56.58.103:8400->10.56.146.132:37110: write: broken pipe"}
{"ts":"2022-08-08T08:57:30.684Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:107","msg":"closing vminsert conn from 10.56.146.132:37110"}
{"ts":"2022-08-08T08:57:31.815Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.56.146.132:52356"}
{"ts":"2022-08-08T08:57:31.854Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:112","msg":"processing vminsert conn from 10.56.146.132:52356"}
{"ts":"2022-08-08T08:57:32.141Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.155.3:42530"}
{"ts":"2022-08-08T08:57:32.141Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.155.3:42528"}
{"ts":"2022-08-08T08:57:32.174Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.155.3:42530"}
{"ts":"2022-08-08T08:57:32.174Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.155.3:42528"}
{"ts":"2022-08-08T08:57:33.122Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.22.131:39772"}
{"ts":"2022-08-08T08:57:33.122Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.22.131:39774"}
{"ts":"2022-08-08T08:57:33.122Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.22.131:39776"}
{"ts":"2022-08-08T08:57:33.159Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.22.131:39772"}
{"ts":"2022-08-08T08:57:33.164Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.22.131:39774"}
{"ts":"2022-08-08T08:57:33.176Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.22.131:39776"}
{"ts":"2022-08-08T08:57:46.920Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.56.163.4:42148"}
{"ts":"2022-08-08T08:57:46.941Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:112","msg":"processing vminsert conn from 10.56.163.4:42148"}
{"ts":"2022-08-08T08:57:49.833Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.56.126.131:51226"}
{"ts":"2022-08-08T08:57:49.857Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:175","msg":"processing vmselect conn from 10.56.126.131:51226"}
{"ts":"2022-08-08T08:57:52.499Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.56.103.4:41028"}
{"ts":"2022-08-08T08:57:52.522Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:112","msg":"processing vminsert conn from 10.56.103.4:41028"}
{"ts":"2022-08-08T08:57:57.928Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.56.58.3:45348"}
{"ts":"2022-08-08T08:57:57.959Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:112","msg":"processing vminsert conn from 10.56.58.3:45348"}
{"ts":"2022-08-08T08:58:01.275Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:170","msg":"closing vmselect conn from 10.56.39.132:59724"}
{"ts":"2022-08-08T08:58:06.258Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:170","msg":"closing vmselect conn from 10.56.155.3:42530"}
{"ts":"2022-08-08T08:58:06.258Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:170","msg":"closing vmselect conn from 10.56.155.3:41272"}
```

**Comment by Vladikamira** [comment]
and sometimes it's recovering back to normal for a while as here on the screenshot ~  02:00 - 03:40 

<img width="1371" alt="Screenshot 2022-08-08 at 11 02 48" src="https://user-images.githubusercontent.com/5423271/183382423-1ea0c442-b57b-44e3-8bd4-65064d2ce2ee.png">

**Comment by hagen1778** [comment]
Hi @Vladikamira! Thanks for detailed report!
Have you tried removing this specific storage node from vminsert's listing just to remove ingestion load? How would storage behave in such conditions?

**Comment by Vladikamira** [comment]
sure, here is what I've got:
~ 10:35 - removed Problematic pod from Vminsert list
~ 10:35 - 10:55 - two other `vmstorage` pods started intensive Reading
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    We have 6 `vmstorage` pods, 3 old with `6` months of retention, and 3 new with `1-2` months of data.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    The problematic pod is the one with `6` months of retention, so clearly there are problems only on `vmstorage`  with a lot of data (4Tb)
```
/ # df -h /storage/
Filesystem                Size      Used Available Use% Mounted on
/dev/sdb                  8.0T      4.2T      3.7T  53% /storage
```
~ 10:55 - ingestion unblocked and queue from `Vmagent`

here are screenshots
<img width="1367" alt="Screenshot 2022-08-12 at 11 51 26" src="https://user-images.githubusercontent.com/5423271/184332943-cec663c2-caca-41bd-b63f-7db5b63611d4.png">
<img width="1368" alt="Screenshot 2022-08-12 at 11 53 34" src="https://user-images.githubusercontent.com/5423271/184332960-310a44cb-d26e-4ad4-b1bb-2fd9fa689022.png">

please let me know if you need something else

**Comment by hagen1778** [comment]
Just to clarify, the problematic storage that was removed all this time was performing very poorly so almost all the data were re-routed from it. So even removing it from the rotation didn't cause intensive rerouting change. Is this correct?
Could you please also provide screenshots of the official Grafana dashboard for the following matters:
1. How excluded vmstorage behaved after being removed from rotation: CPU, disk IO, merges
2. How excluding one vmstorage affected the resto fo the cluster: rerouting, churn rate, active series, CPU, memory, disk IO, LSM parts, concurrent flushes on disk.

Thank you!

**Comment by Vladikamira** [comment]
> Just to clarify, the problematic storage that was removed all this time was performing very poorly so almost all the data were re-routed from it. So even removing it from the rotation didn't cause intensive rerouting change. Is this correct?

actually, it helped, other storage nodes behave better than the problematic one, so after removing problematic node, I saw intensive IO on two others (with relatively the same size as the removed one) for 10 minutes, and after that all was good and cluster could process all ingestion normally.

> 1. How excluded vmstorage behaved after being removed from insert rotation: CPU, disk IO, merges

here I will post screenshots to answer on this question regarding excluded node
<img width="1368" alt="Screenshot 2022-08-15 at 13 14 08" src="https://user-images.githubusercontent.com/5423271/184626424-2ffad536-c910-4878-9e81-261ce89114d9.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 14 30" src="https://user-images.githubusercontent.com/5423271/184626433-7a609692-e519-423d-994c-52d36b901478.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 14 42" src="https://user-images.githubusercontent.com/5423271/184626445-b8ea3cc3-751e-4628-aaf1-00713c0ef53e.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 14 55" src="https://user-images.githubusercontent.com/5423271/184626473-98bef872-4bed-4c41-a4e7-53bcfe4bfdb5.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 15 23" src="https://user-images.githubusercontent.com/5423271/184632060-6d850772-b5e4-48e8-b994-d709f20ec3bf.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 15 43" src="https://user-images.githubusercontent.com/5423271/184626487-365f7703-138b-47ac-9bea-6246771ba4e2.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 15 57" src="https://user-images.githubusercontent.com/5423271/184626516-2fbfc10c-250e-4da6-87bd-a5240bc4a3b2.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 16 08" src="https://user-images.githubusercontent.com/5423271/184626526-8cefffeb-cc99-4d98-9390-f7ce79438adf.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 16 31" src="https://user-images.githubusercontent.com/5423271/184626540-c3bf040d-5eb8-4d21-90a7-d27d0c85054d.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 16 46" src="https://user-images.githubusercontent.com/5423271/184626547-2c9ad733-906a-43da-9c6e-606421b5d380.png">
<img width="1368" alt="Screenshot 2022-08-15 at 13 17 04" src="https://user-images.githubusercontent.com/5423271/184626555-894e8814-626e-4c8e-b4d9-6dc3840649a8.png">

**Comment by Vladikamira** [comment]
> 2. How excluding one vmstorage affected the resto fo the cluster: rerouting, churn rate, active series, CPU, memory, disk IO, LSM parts, concurrent flushes on disk.

~10:30-10:40 - is the time when problematic node was excluded from the ingestion list

and here are screenshots for the rest of the `vmstorage` nodes in the cluster:
<img width="1368" alt="Screenshot 2022-08-15 at 14 06 24" src="https://user-images.githubusercontent.com/5423271/184632895-c0337093-dd5d-4396-a2ac-bd950d1f5541.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 06 53" src="https://user-images.githubusercontent.com/5423271/184633007-897a0c8a-ce02-4868-b0c4-3c61cb7c758e.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 07 06" src="https://user-images.githubusercontent.com/5423271/184633019-379dd72b-059b-4157-ae99-6b0746c87c6f.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 07 18" src="https://user-images.githubusercontent.com/5423271/184633033-df90625d-1f40-4368-8eb7-3115c5200bba.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 07 29" src="https://user-images.githubusercontent.com/5423271/184633041-0a1bf79b-d375-4e62-9101-c140d767f02a.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 07 41" src="https://user-images.githubusercontent.com/5423271/184633069-655bc9e2-0b2f-45b4-bdc9-9fd71ba5ece2.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 08 17" src="https://user-images.githubusercontent.com/5423271/184633089-788412fc-0f1a-4c4e-8682-ce2d097dd12d.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 08 31" src="https://user-images.githubusercontent.com/5423271/184633103-0c02ca33-6327-4721-8ec7-aea331e62b05.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 08 45" src="https://user-images.githubusercontent.com/5423271/184633118-5973bdac-6920-4518-860d-b6360fba2d20.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 09 02" src="https://user-images.githubusercontent.com/5423271/184633133-27c75a99-b070-423a-99a7-db3ce647c2bd.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 09 23" src="https://user-images.githubusercontent.com/5423271/184633151-4c5418b1-a562-4e98-85a7-5490ef731ae0.png">
<img width="1368" alt="Screenshot 2022-08-15 at 14 09 38" src="https://user-images.githubusercontent.com/5423271/184633165-9a606dd9-d287-485b-8487-0f5830bf447e.png">

**Comment by hagen1778** [comment]
Thanks for detailed info! The p.2 screenshots are missing Rerouting but, I guess, I know what it would show.
So the removed storage node went calm once the ingestion went off. It means, there is no a deadloop inside which wastes resources.
Also, I noticed just now, the TSID cache hit rate is ridiculously low for this degraded vmstorage. I didn't see it first time, because panel SlowInserts showed good numbers (<1%). SlowInserts and TSID cache hit rate are tightly connected. When vmstorage receives a time series to ingest, it tries to locate its TSID (time series ID) based on labels. It first looks in the cache, and when it is missing - checks on disk (this is when it becomes "slow"). So when TSID hit rate drops, the SlowInserts are going up. But we didn't see that on the screenshots, because panel query doesn't account for instance filter and shows the % of slow inserts across all vmstorage nodes. This skews the graph and that's why I didn't notice it at first.

So, there are two reasons of TSID cache miss:
1. vmstorage receives totally new time series, never registered before. It happens when churn rate is high, or when rerouting starts, ir when just new time series were created by clients. Such new series need to be registered first and then their IDs will be added to the TSID cache.
2. There is no enough memory to hold all the ingested TSIDs in the cache. In this case, vmstorage will need to read a lot from the disk putting a lot of pressure on it and slowing down ingestion path.

I think, your case is 2. But why did it happen. I have two assumptions:
1. This specific shard has some data skew - it receives more unique series than rest.
2. This specific shard has weird cache settings. From the first screenshots you provided it shows that TSID cache for the faulty pod is about 200MB, which is very low. It is expected with default values it would occupy about 10GB. Are there any specific flag settings for this pod?

**Comment by Vladikamira** [comment]
We are using Statefulset for each `vmstorage` group, so each node/pod should be equal in terms of settings
Here are them:
```
    Args:
      --retentionPeriod=6
      --storageDataPath=/storage
      --dedup.minScrapeInterval=15s
      --envflag.enable=true
      --envflag.prefix=VM_
      --http.maxGracefulShutdownDuration=10s
      --http.shutdownDelay=5s
      --loggerFormat=json
      --loggerLevel=INFO
      --loggerOutput=stdout
      --memory.allowedPercent=60
      --search.maxUniqueTimeseries=10000000
```
version `v1.78.1` btw (I tried v1.79.1 before to check if would help, and it was overwritten after some deploy)

regarding TSID, should I try to tune `-storage.cacheSizeStorageTSID` setting? with 50GB `vmstorage` pod, should 10-15GB be enough?

**Comment by Vladikamira** [comment]
I guess tuning won't help, as `vm_cache_size_bytes/vm_cache_size_max_bytes` for TSID not went above `20%` for this particular cluster, please have a look:
<img width="1428" alt="Screenshot 2022-08-15 at 16 35 15" src="https://user-images.githubusercontent.com/5423271/184655967-1a6a7a21-f94d-466c-97a6-6884a809b980.png">

**Comment by hagen1778** [comment]
> for this particular cluster

for the whole cluster or for this specific vmstorage? 

The whole cluster shows good TSID cache hit ratio from previous screenshots ([100%](https://user-images.githubusercontent.com/5423271/184633089-788412fc-0f1a-4c4e-8682-ce2d097dd12d.png)). But from your very first comments this one specific degraded vmstorage shows [hit rate <20% and memory usage of 200MB](https://user-images.githubusercontent.com/5423271/182953160-9fb15fb6-a07b-40e4-a807-fbc92efe4576.png). Ofc, if the values on the screenshot are correct. I think, we should understand why is that. I also noticed, `--envflag.enable=true --envflag.prefix=VM_` settings - could it hide some additional settings behind ENV variables?

**Comment by Vladikamira** [comment]
> for the whole cluster or for this specific vmstorage?
all vmstorage nodes/pods/shards in one cluster which had problematic one

> The whole cluster shows good TSID cache hit ratio from previous screenshots ([100%](https://user-images.githubusercontent.com/5423271/184633089-788412fc-0f1a-4c4e-8682-ce2d097dd12d.png)).

yeah, sorry for the confusion, here 100% shows for pods without exclusion Pod, so problematic Pod wasn't taken into account there.

> But from your very first comments this one specific degraded vmstorage shows [hit rate <20% and memory usage of 200MB](https://user-images.githubusercontent.com/5423271/182953160-9fb15fb6-a07b-40e4-a807-fbc92efe4576.png). Ofc, if the values on the screenshot are correct. I think, we should understand why is that.

yeah, apologies for the confusion, this one is quite an old screenshot, I couldn't find a fast enough proper timestamp, so I took fresh screenshots from recent data. Further, I will stick to 8-22 timestamp from screenshot above 

> I also noticed, --envflag.enable=true --envflag.prefix=VM_ settings - could it hide some additional settings behind ENV variables?

only GOMAXPROCS, which configured as the number of CPU cores
```
➜  tmp kubectl describe pod victoria-metrics-cluster-a-vmstorage-2
Name:         victoria-metrics-cluster-a-vmstorage-2
Status:       Running
Controlled By:  StatefulSet/victoria-metrics-cluster-a-vmstorage
Containers:
  victoria-metrics-cluster-vmstorage:
    Image:         victoriametrics/vmstorage:v1.78.1-cluster
4
    Ports:         8482/TCP, 8400/TCP, 8401/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      --retentionPeriod=6
      --storageDataPath=/storage
      --dedup.minScrapeInterval=15s
      --envflag.enable=true
      --envflag.prefix=VM_
      --http.maxGracefulShutdownDuration=10s
      --http.shutdownDelay=5s
      --loggerFormat=json
      --loggerLevel=INFO
      --loggerOutput=stdout
      --memory.allowedPercent=60
      --search.maxUniqueTimeseries=10000000
...
    Limits:
      cpu:     10
      memory:  50Gi
    Requests:
      cpu:      10
      memory:   50Gi
    Liveness:   tcp-socket :http delay=5s timeout=5s period=15s #success=1 #failure=3
    Readiness:  http-get http://:http/health delay=5s timeout=5s period=15s #success=1 #failure=3
    Environment:
      GOMAXPROCS:  10
```

let me gather again information regarding cache for 8-22 time range.
So, for that time range we had 6 `vmstorage`  pods/shards:

# vmstorage Pods in normal condition
```
10.56.20.133
10.56.113.3
10.56.28.3
10.56.107.131
10.56.73.5
```
# affected `vmstorage` Pod
```
10.56.37.3
```
and here are graphs for them:

Excluded:
<img width="1367" alt="Screenshot 2022-08-16 at 00 12 21" src="https://user-images.githubusercontent.com/5423271/184731067-e801af1d-2946-4aab-b08a-7a436c892966.png">

In normal condition without excluded
<img width="1367" alt="Screenshot 2022-08-16 at 00 12 40" src="https://user-images.githubusercontent.com/5423271/184731110-3f3e66a6-4d47-4cfe-a0b1-81ffb77d82b8.png">

**Comment by Vladikamira** [comment]
alright, I have some thoughts to share and also some questions regarding cache of `vmstorage`.

- At first, I should say that some `vmstorage` nodes bound to IO on reads from the filesystem, which we can clearly see on the screenshots above.
- I was pointed several times to the cache, in particular to the `TSID` cache (which can be the bottle neck with the high churn rate or in the case of rerouting ) because from my understanding `TSID` is the cache to look before registering new metric in the storage. This part is clear.
- also, I can clearly see that ingestion into Nodes with fewer data (new shards) is way faster (cache miss for TSID cache is way lower ) than with more data. Here I have 3 nodes with 4-5 TB of data each (6 months of data) and 3 nodes with 1TB of data each (2 months of data), which were recently added to scale up the cluster and spread the load.

For here, I have several questions regarding TSID cache:
## 1. TSID cache size on restart
If I restart one pod of `vmstorage` I can see following picture:
save cache:
```
 {"ts":"2022-08-26T11:21:59.203Z",....,"msg":"saving MetricName->TSID cache to \"/storage/cache/metricName_tsid\"..."}
{"ts":"2022-08-26T11:21:59.581Z",....,"msg":"saved MetricName->TSID cache to \"/storage/cache/metricName_tsid\" in 0.377 seconds; entriesCount: 3198508; sizeBytes: 1660420096"}
{"ts":"2022-08-26T11:21:59.583Z",....,"msg":"saving MetricID->TSID cache to \"/storage/cache/metricID_tsid\"..."}
{"ts":"2022-08-26T11:21:59.602Z",....,"msg":"saved MetricID->TSID cache to \"/storage/cache/metricID_tsid\" in 0.019 seconds; entriesCount: 348323; sizeBytes: 67108864"}
```
restoring cache
```
{"ts":"2022-08-26T11:22:23.517Z",....,"msg":"loading MetricName->TSID cache from \"/storage/cache/metricName_tsid\"..."}
{"ts":"2022-08-26T11:22:24.280Z",....,"msg":"loaded MetricName->TSID cache from \"/storage/cache/metricName_tsid\" in 0.763 seconds; entriesCount: 1599126; sizeBytes: 830078976"}
{"ts":"2022-08-26T11:22:24.280Z",....,"msg":"loading MetricID->TSID cache from \"/storage/cache/metricID_tsid\"..."}
{"ts":"2022-08-26T11:22:24.480Z",....,"msg":"loaded MetricID->TSID cache from \"/storage/cache/metricID_tsid\" in 0.200 seconds; entriesCount: 174161; sizeBytes: 33554432"}
```
as you can see, size of the cache is different on persisting and restoring phases, basically, it's 2 times fewer on restore.
Is that mean that `vmstorage` does not restore the whole cache? or it's just the wrong metadata?
the same picture I can get from the metrics:
<img width="1431" alt="Screenshot 2022-08-26 at 13 27 32" src="https://user-images.githubusercontent.com/5423271/186899383-d07b4998-8e49-48c8-a5ee-bcd6e2729a26.png">
so, it's saving `3 mil` entries but restoring only half.

Another unclear moment is regarding metric and type `vm_cache_size_bytes{type="storage/tsid"}`, seems like it matches 
by amount of entries `/storage/cache/metricName_tsid` folder, but what metric covers `/storage/cache/metricID_tsid` than?

## 2. TSID cache utilization and resets
Is there a cache reset every 5 minutes? 
<img width="1431" alt="Screenshot 2022-08-26 at 14 11 55" src="https://user-images.githubusercontent.com/5423271/186901676-5ba2d58c-6914-47f0-9321-75d7a5e44dba.png">

## 3. TSID cache lookup
Another thing that I would like to understand, is how TSID lookup works in case of a cache miss? which files `vmstorage` is trying to read? I thought that force merge on heavy nodes for old partitions (> 2 months) will help us and speed up TSID lookup, but seems like we got even slower injection rate after that (more IO reads)

## 4. Adding new shards
If we are adding more shards to the growing cluster, is there a way to rebalance data between shards? because obviously, new shards would be light and fast, but old ones still be slow. So from here I only see two options to make them equal:
- wait `retention period` for old data to be dropped from the old shards
- setup new cluster and migrate data there via `vmctl`

is there another way?

**Comment by hagen1778** [comment]
> TSID cache size on restart

Cache structure in VictoriaMetrics works in different modes. One of the modes (picked mode depends on amount of occupied memory by the entries in cache) works in a split fashion, where the cache entries are split into two parts: current and previous. These parts interchange each other ones current part is already full. The split mode may be enabled on the cache load if all dedicated space to the cache was already occupied. So on load time the oldest cache part may be evicted.
Another detail is that entries eviction from caches happens each 5min or on the first load time. It is likely that some entries were evicted on the load time as well.

> TSID cache utilization and resets

Please see prev response. More details about cache structure can be found here https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/workingsetcache/cache.go

> TSID cache lookup

Please find detailed explanation here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2007#issuecomment-1032080840

> Adding new shards

There is no way, so far, except manual migration. And that won't help as well, since you'll need to have different retentions on storage nodes to do that. Delete API is also not recommended to use in this case, since it doesn't actually delete the data, only marks it as so.

But still, adding new shards would improve the overall performance of the cluster. If you read carefully [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2007#issuecomment-1032080840) you'll see that cache lookups may be improved by extending capacity of `indexdb/dataBlocks` cache. This can be done either by increasing available memory (to the process or to this specific cache) or by adding more shards to the cluster.

**Comment by Vladikamira** [comment]
alright, I think the problem is pretty clearly related to old shards with blown indexes, which are hard to keep in memory.
But the main problem seems to be in bad architecture planning from our side, which led to this situation where we have 
3 overloaded shards and 3 are almost empty, so those 3 old shards are limiting the ingestion performance of the whole cluster.

To us, indeed there is no better way than migrate data to a properly structured cluster with more shards and evenly distributed data over shards so no bottlenecks will appear. Hopefully, there is a `vmctl` tool to help us with that 👍 

@hagen1778 thanks for your help and explanation, I think we can close this issue :)

btw, adjusting `indexdb/dataBlocks` setting `x2` times didn't help with ingestion performance somehow, or at least it wasn't a noticeable improvement to us. But, it's pretty clear that the problem is in the not even data distribution so we don't want to spend more time on tunning of existing cluster..

**Comment by hagen1778** [comment]
> we have 3 overloaded shards and 3 are almost empty

"We recommend to run a cluster with big number of small vmstorage nodes instead of a cluster with small number of big vmstorage nodes. This increases chances that the cluster remains available and stable when some of vmstorage nodes are temporarily unavailable during maintenance events such as upgrades, configuration changes or migrations."

See more details here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning

>  I think we can close this issue :)

Ok! Thank you for good conversation!
