### ISSUE TITLE
VictoriaMetrics operator does not add the correct VMAgentRemoteWriteSettings to the deployment

### ISSUE THREAD

**Issue by sharninder** [VictoriaMetrics/VictoriaMetrics#2946]
**Describe the bug**
Configure a VMAgent deployment using the "Kind: VMAgent" and add a remoteWriteSettings option to change tmpDataPath or maxDiskUsagePerUrl parameters. 

**Logs**
This is what gets added to the vmagent-prod command line inside the POD:
 
/vmagent-prod -httpListenAddr=:8429 -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml -remoteWrite.maxDiskUsagePerURL=1073741824 -remoteWrite.maxDiskUsagePerURL=2000000 -remoteWrite.multitenantURL=http://vminsert-vmc-a:8480,http://vminsert-vmc-b:8480 -remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data -remoteWrite.tmpDataPath=buffer

See the maxDiskUsagePerUrl and tmpDataPath options are repeated twice. And vmagent-prod binary only takes the first option as default. So there is currently no way to set a different path (or a PVC) to vmagent.

**Comment by valyala** [comment]
@f41gh7 , could you look into this issue?

**Comment by f41gh7** [comment]
Issue was fixed at v0.28.0 operator release. Feel free to re-open if it wouldn't help.
