### ISSUE TITLE
The cluster major bug, Causing the entire cluster to down

### ISSUE THREAD

**Issue by Fury76** [VictoriaMetrics/VictoriaMetrics#2951]
**Describe the bug**
Vminsert and vmselect can connect to vmstorage without authentication. When another client tries to connect to a specific port of vmstorage, such as 8480, and the client does not return the expected Hello package. The server will disconnect the running vmselect and vminsert, and eventually the entire cluster will crash. This scenario occurs when the enterprise has security equipment to scan all ports opened in the intranet. In this case, the cluster is completely unavailable

**To Reproduce**
1、Build cluster environment
2、When the cluster ready, start the vmagent, try to scrape the vmstorage's 8480/8481 port （Simulate other unexpected connections）
3、Then vmselect and vminsert down

**Expected behavior**
It is expected that the cluster will be more robust

**Logs**
This is my env, in the error log. the vmselect is my vmagent's address, the vminsert is our company's security device

{"ts":"2022-08-07T03:31:11.797Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.229.145.6:41600"}
{"ts":"2022-08-07T03:31:11.797Z","level":"error","caller":"VictoriaMetrics/lib/vmselectapi/server.go:163","msg":"cannot perform vmselect handshake with client \"10.229.145.6:41600\": cannot read hello: unexpected message obtained; got \"GET /metric\"; want \"vmselect.01\""}
{"ts":"2022-08-07T03:31:14.899Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.229.144.183:39600"}
{"ts":"2022-08-07T03:31:14.899Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:101","msg":"cannot perform vminsert handshake with client \"10.229.144.183:39600\": cannot read hello: unexpected message obtained; got \"GET /metric\"; want \"vminsert.02\""}
{"ts":"2022-08-07T03:31:16.845Z","level":"info","caller":"VictoriaMetrics/lib/vmselectapi/server.go:132","msg":"accepted vmselect conn from 10.229.144.183:37772"}
{"ts":"2022-08-07T03:31:16.845Z","level":"error","caller":"VictoriaMetrics/lib/vmselectapi/server.go:163","msg":"cannot perform vmselect handshake with client \"10.229.144.183:37772\": cannot read hello: unexpected message obtained; got \"GET /metric\"; want \"vmselect.01\""}
{"ts":"2022-08-07T03:31:29.899Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:76","msg":"accepted vminsert conn from 10.229.144.183:54926"}
{"ts":"2022-08-07T03:31:29.899Z","level":"error","caller":"VictoriaMetrics/app/vmstorage/servers/vminsert.go:101","msg":"cannot perform vminsert handshake with client \"10.229.144.183:54926\": cannot read hello: unexpected message obtained; got \"GET /metric\"; want \"vminsert.02\""}

**Screenshots**
The vmstorage:
In this case, the vmselect is my vmagent, and the vminsert is our company's security device.
<img width="1994" alt="image" src="https://user-images.githubusercontent.com/7465355/183274452-295d6685-bd7c-46ab-bd2f-62ee84fd8a03.png">

The vmselect:
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/7465355/183274485-cfda7ca4-f639-4776-801a-048b232bfc7c.png">

The vminsert:
<img width="2544" alt="image" src="https://user-images.githubusercontent.com/7465355/183274661-b001405c-aabd-4204-9baf-da08e6dce384.png">

**Version**
vminsert-20220714-140205-tags-v1.79.0-cluster-0-ga87f143e9
vmstorage-20220714-140255-tags-v1.79.0-cluster-0-ga87f143e9

**Comment by valyala** [comment]
I cannot reproduce the issue - `vmstorage` accepts connections at TCP ports 8400 (vminsert) and 8401 (vmselect) from both legitimate `vminsert` and `vmselect` nodes and from incompatible clients. If the connected incompatible client doesn't provide the expected handshake message, then `vmstorage` closes the connection to incompatible client. It doesn't close connections to real `vminsert` and `vmselect` clients in this case.

`vmstorage` has no upper limit on the number of concurrent connections it can accept. The only limit can be set at the Operating system level for the number of open file descriptors - see https://www.google.com/search?q=linux+the+number+of+open+files+limit . Probably, security scanner establishes too many concurrent connections to `vmstorage`, so it hits the limit on the number of open files. In this case `vminsert` and `vmselect` could fail re-establishing new connections to `vmstorage`. The solution is to either tune the security scanner, so it opens lower number of concurrent connections or to increase the limit on the number of open file descriptors for `vmstorage` at the OS level.

**Comment by jiaoyan2017** [comment]
I met the same issue. I deployed `victoria-metrics-cluster` by `helm chart` on my K8s without any updates except adding resources limits for all components, disabling `persistentVolume` for `vmstorage` and `namespaced`. Then `kubectl logs <vmstorage>-pod` can get this error log.

**Comment by jiekun** [comment]
Close due to inactivity.
