### ISSUE TITLE
support for passing current command line arguments as new configuration file and if possble support dynamic update of current command line arguments

### ISSUE THREAD

**Issue by sriharshabm** [VictoriaMetrics/VictoriaMetrics#2966]
Hi Team,
All victoria metrics related binaries are having many command line arguments. Following improvements will help us in using victoria metrics in better way.
1) Few of command line arguments are having personal data. It would be really helpful if provision is provided to read current command line arguments from separate configuration file. Even passing personal data as environment variable is also not correct.
2) If few of the command line arguments can be updated dynamically then we can have 2 new configuration files. One which can be dynamically updated and other one needs restart of application.

**Comment by YuriKravetc** [comment]
Hi @sriharshabm ,

This is actually possible if you run it with systemd - though, for it to receive new data from new arguments or variables from the environment the service should be restarted. 

`Here is the service file:
==================
]# cat /etc/systemd/system/vmstorage.service
[Unit]
Description=vmstorage systemd service.
 
[Service]
User=runops
Type=simple
ExecStart=/apps/victoriametric-binary/vmstorage-prod -storageDataPath /apps/metric-storage -retentionPeriod 1y -httpListenAddr 0.0.0.0:8482 -vminsertAddr 0.0.0.0:8400 -vmselectAddr 0.0.0.0:8401
Restart=always
StandardOutput=file:/var/log/vmstorage/vmstorage.log
 
[Install]
WantedBy=multi-user.target
==================`

Should not be started from root.

**Comment by hagen1778** [comment]
@sriharshabm configuring secrets is possible via ENV variables - please see more details here https://docs.victoriametrics.com/#environment-variables

**Comment by sriharshabm** [comment]
@YuriKravetc , We are running victoria metrics from distroless docker. Running it with the help of systemd might not be good solution. 

@hagen1778, As I mentioned in initial request, configuring secrets as ENV variable is not acceptable as env var name and its value will be visible when we describe Pod etc in kubernetes. 

All victoria metrics components has too many parameters passed as argument and option is provided to pass then as env var. As I mentioned above, we can't send personal data in both ways. 

- one of the solution which we are thinking is store all personal data in kubernetes secret and mount it directly inside container and then use it directly (without ENV var).
- Also, there are too many args supported in victoria metrics. If dynamic value can be updated then better to move it from args to separate configuration file.

**Comment by hagen1778** [comment]
> If dynamic value can be updated then better to move it from args to separate configuration file.

Moving configuration flags to the config file is not considered now. It may be re-considered in future, but so far there are no plans to introduce a configuration file.

**Comment by sriharshabm** [comment]
Reading personal data from command line arguments OR from environment variable is not acceptable in our use case. If we are ready to contribute enhancement to community then will it be accepted?

**Current planned solution:** Along with reading parameter value from command line argument and env var, support provision to read parameter value from file. Format of file can be similar to command line argument. Priority of reading parameters could be Command line flag, reading from file(new way) and environment variable.

**Comment by hagen1778** [comment]
> Reading personal data from command line arguments OR from environment variable is not acceptable in our use case.

I don't understand why. Using [k8s secrets](https://kubernetes.io/docs/concepts/configuration/secret/) is meant for protecting sensitive data in ENV variables. 

> configuring secrets as ENV variable is not acceptable as env var name and its value will be visible when we describe Pod etc in kubernetes.

I might be mistaken, but that's not how secrets works. Here I'm using a secret for configuring Grafana's user name in my local env:
```
kubectl get deployment grafana -o yaml 
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: grafana
```

And this is how `describe` looks:
```
kubectl describe po grafana
    Environment:
      GF_SECURITY_ADMIN_USER:      <set to the key 'admin-user' in secret 'grafana'>      Optional: false
```
^ no sensitive data is exposed.

You can still get the secret if you `exec` into a pod. But so you can do with config file either.

> If we are ready to contribute enhancement to community then will it be accepted?

It is likely that live-reload of config files won't be accepted, since the program wasn't designed for this initially. Adding hot-reload now may cause many issues. Not all config elements are meant to be reloaded, like `httpListenAddr`, for example. Hence, introducing a config file is a huge piece of work for bringing new functionality, documentation and preserving backward compatibility. If PR which introduces the config files would contain all the listed items - it will be reviewed.

**Comment by jiekun** [comment]
Close as answered.
