### ISSUE TITLE
VMAgent Stream parsing mode expect maxScrapeSize

### ISSUE THREAD

**Issue by Ram-97** [VictoriaMetrics/VictoriaMetrics#2967]
**Issue Description**
Some target having response size greater than default scrape size (16.77Mb). For example, let's say - Target response size is 200Mb. I did tried increased the maxScrapeSize. But after some days, some target response size increased further.

So I ended up on [Stream parse mode](https://docs.victoriametrics.com/vmagent.html#stream-parsing-mode). In Official doc, `vmagent reads response from scrape target in chunks, then immediately processes every chunk and pushes the processed metrics to remote storage`.

 
Configured the Vmagent with stream parse mode.

`extraArgs:`
    `promscrape.minResponseSizeForStreamParse: "16000000"`
   ` promscrape.streamParse: "true"`
 

With this config, vmagent able to scrape the target. But the problem here is, metrics from the target getting scrapped till the default scrape size (16.77Mb). Only few metrics getting processed from these targets.

**Log**

`cannot read Prometheus exposition data: cannot read a block of data in 0.000s: the response from "http://IP/METRIC/PATH" exceeds -promscrape.maxScrapeSize=16777216; either reduce the response size for the target or increase -promscrape.maxScrapeSize`

**Version** : 
Victoria Operator: v0.25.1
VMAgent: v1.77.2

**Comment by hagen1778** [comment]
Hi @Ram-97! Having the total response size still having sense to me, even for streaming mode. Otherwise, there could be a case when parsing of one maliciously formed target will never finish. I think, the current behaviour is correct.

@valyala @f41gh7 wdyt?
