### ISSUE TITLE
graphite render incorrect query result with chained functions

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#2969]
**Describe the bug**
  Some graphite function changes timestamps for series (summarize, hitcount). When such functions wrapped with functions which changes evaluation interval and summarize points,  produced result differs from expected graphite output. Graphite keeps modified timestamps.  
  
  Query example:
graphite output
```
curl localhost:8083/render -g -d 'format=json' -d "target=averageSeries(timeShift(summarize(movingAverage(tech.metrics, 30), '2h', 'sum', false), 'current'))"  -d 'from=-6h' -d 'until=now' -d 'maxDataPoints=1479'

[{"target": "averageSeries(summarize(movingAverage(tech.metrics,30), \"2h\", \"sum\"))", "tags": {"name": "tech.metrics", "movingAverage": "30", "summarize": "2h", "summarizeFunction": "sum", "timeShift": "-2week", "aggregatedBy": "average"}, "datapoints": [[72.0, 1659924000], [432.0, 1659931200], [432.0, 1659938400], [36.0, 1659945600]]}]
```
victoria-metrics
```
curl localhost:8428/render -g -d 'format=json' -d "target=averageSeries(timeShift(summarize(movingAverage(tech.metrics, 30), '2h', 'sum', false), 'current'))"  -d 'from=-6h' -d 'until=now' -d 'maxDataPoints=1479'

[{"target":"averageSeries(summarize(movingAverage(tech.metrics,30),\u00272h\u0027,\u0027sum\u0027))","tags":{"aggregatedBy":"average","movingAverage":"30","name":"tech.metrics","summarize":"2h","summarizeFunction":"sum","timeShift":"2week"},"datapoints":[[1080,1659924060],[null,1659931260],[null,1659938460]]}]
```
 
**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190730-121249-heads-single-node-0-g671d9e55
```

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components.

**Comment by f41gh7** [comment]
I think, those difference at response is data model design of VictoriaMetrics and it should be marked as known difference between VictoriaMetrics and Graphite data models.

**Comment by hagen1778** [comment]
This limitation was documented here https://docs.victoriametrics.com/#known-incompatibilities-with-graphite-web
