### ISSUE TITLE
maxDiskUsagePerURL is applied per tenant with remoteWrite.multitenantURL

### ISSUE THREAD

**Issue by rbizos** [VictoriaMetrics/VictoriaMetrics#2970]
**Describe the bug**
We are using VMAgent between our prometheus collection layer and our VictoriaMetrics multitenant cluster to spool longer than prometheus can. We use maxDiskUsagePerURL to control the amount of data we keep.

The problem is that it set per tenant and not per remoteWrite.multitenantURL, making it difficult to correctly tune maxDiskUsagePerURL setting as some tenant write a lot, some less. Also new tenant could create issues as the total maximum usage is maxDiskUsagePerURL * <number_of_tenants>

**Expected behavior**
Shouldn't the value be for the whole multitenantURL rather than for individual tenants ?

**Version**
1.76.1

**Comment by hagen1778** [comment]
@valyala @f41gh7 @k1rk wdyt?

**Comment by chivunito** [comment]
Completing this issue as following is related : 

**Observation** 
We observe the same behavior on remote write rate limiting : I'd expect the rate limiting to be global, at least per multitenantURL, but the rate limit occurs per tenant.
Our number of tenant organically growing with time + being unbalanced in term of traffic, that makes it almost impossible to cap the global rate limit not to overwhelm our Victoria Metric backend. 
 
```bash
  -remoteWrite.rateLimit array
    	Optional rate limit in bytes per second for data sent to the corresponding -remoteWrite.url. By default the rate limit is disabled. It can be useful for limiting load on remote storage when big amounts of buffered data is sent after temporary unavailability of the remote storage
    	Supports array of values separated by comma or specified via multiple flags.
```

**Expected behavior**
 At least from the rateLimit help message, I'd expect the rate limit to occur per remote write url

**Potential Alternative**
Introducing another global rateLimit flag, that is not tenant specific

**Version**
1.76.1

**Comment by f41gh7** [comment]
It looks relevant to me. I think, that current multi tenancy implementation works incorrectly and doesn't scales well. 

 I suggest, that `vmagent` must add special meta label `__account_id` and `__project_id`, which would be parsed and striped by `vminsert`.

**Comment by rbizos** [comment]
That should indeed fix the issue. That could also adds some flexibility such as tenant override or so on VMAgent side :)

**Comment by rbizos** [comment]
I addressed the issue in this https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3083 also encountered another issue with the configuration of vmagent: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3071

**Comment by rbizos** [comment]
At least that is a middle step toward simplification :wink: which does not require any change on the configuration of vmagent

**Comment by valyala** [comment]
FYI, the next release of VictoriaMetrics cluster will support e.g. multitenant endpoints, which allow specifying tenant ids via `vm_account_id` and `vm_project_id` labels. See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy-via-labels) for details. In the mean time it is possible to build cluster components of VictoriaMetrics from the commit 505d359b397d3594a996253d49635ec83fd949d4 and verifying whether it works as expected.

**Comment by valyala** [comment]
FYI, VictoriaMetrics cluster accepts `vm_account_id` and `vm_project_id` labels via multitenant endpoints starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy-via-labels).
