### ISSUE TITLE
Incorrect work of retention

### ISSUE THREAD

**Issue by nightirbis95** [VictoriaMetrics/VictoriaMetrics#2975]
**Describe the bug**
Retention didn't work as expected. I have cluster of 3 vmstorage instances, in two of them retention works as it should, but in third looks like retention didn't work properly.

**To Reproduce**
Deploy vmcluster of 3 vmstorages, set retention period 3w

**Expected behavior**
Retention should work similar on each instance

**Logs**
No warning or errors

**Screenshots**
![image](https://user-images.githubusercontent.com/44660724/184292318-611ca2bf-fef8-40c5-9828-836e12612c53.png)
![image](https://user-images.githubusercontent.com/44660724/184292366-51c7866a-0f8a-49d8-8bff-35d40a6cd49d.png)

**Version**
```
./vmstorage-prod --version
vmstorage-20220506-232740-tags-v1.77.1-cluster-0-ge736de8e5
```

**Used command-line flags**
/vmstorage-prod -dedup.minScrapeInterval=1ms -httpListenAddr=:8482 -loggerFormat=json -retentionPeriod=3w -storageDataPath=vmstorage-data -vminsertAddr=:8400 -vmselectAddr=:8401

**Comment by hagen1778** [comment]
Hi @nightirbis95! Could you please check if there is a data folder for prev month at `-storageDataPath` `big` or `small` subfolders for the vmstorage which didn't shrink the data? Please also see more about https://docs.victoriametrics.com/#retention

**Comment by nightirbis95** [comment]
Yep there was data in vmstorage-data/data/big/2022_07, and it took up more space on one instance than on others. As i wrote earlier in telegram channel, looks like retention didn't work properly sometimes on one of instances.

Also i decided to perform upgrade to latest version (v1.80.0) and, some time after the pods restarting. space was released. I'm not sure what was the reason of it, restarting of pods, or upgrade, but i will check and return here, if retention will not work properly on one of instances in future

**Comment by valyala** [comment]
@nightirbis95 , it is likely there were data parts at `<-storageDataPath>/data/big/2022_07` with samples, which fit the specified `-retentionPeriod=3w` . In this case VictoriaMetrics cannot delete these parts until all the samples in the part go outside the configured retention. See more details on how retention works in VictoriaMetrics [in these docs](https://docs.victoriametrics.com/#retention). See also [these docs about VictoriaMetrics storage](https://docs.victoriametrics.com/#storage).

**Comment by nightirbis95** [comment]
@valyala Yes, i understand that. But as i can see all my instance have almost same ingestion rate, so i can't accept fact that part on one of the instances has not been deleted. 

You can see on the dashboard I provided, that after 7/30 the data in one instance just stops being deleted

**Comment by jiekun** [comment]
>  i decided to perform upgrade to latest version (v1.80.0) and, some time after the pods restarting. space was released.

I think the original issue is solved via upgrading. Let me close this issue for now. Feel free to re-open it if you encounter same issue in the latest version.
