### ISSUE TITLE
/api/v1/labels query timeout after upgrade to 1.80.0

### ISSUE THREAD

**Issue by Buddruggy** [VictoriaMetrics/VictoriaMetrics#2978]
**Describe the bug**
/api/v1/labels query timeout after upgrade to 1.80.0
![image](https://user-images.githubusercontent.com/32037815/184573225-af1e8f16-e4d9-4efa-8985-52140c476912.png)

**To Reproduce**
http://vmselect_addr/select/0/prometheus/api/v1/labels?end=1660532988.000000&match[]={label1="value1",label2=
value2"}&start=1660525788.000000

when filter `match[]= ` matches small amount of timeseries, timeout occur frequently

I found in 1.80.0, vmselec not fetching timeseries from vmstorage but get labels in vmstorage and return labels to vmselect.
see this commit. [374beb350ee4af5f5a4d1a58550b2826f18d40c6](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/374beb350ee4af5f5a4d1a58550b2826f18d40c6)

but in this code, 
![image](https://user-images.githubusercontent.com/32037815/184574358-7065c2ac-b026-47a7-80af-deed5ae12713.png)
if fliter has small count of timeseries, and ts has a lot of timeseries, so most timeseries can not match in 3, so will timeout. 

**Version**
v1.80.0-cluster

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1533

**Comment by valyala** [comment]
@Buddruggy , thanks for the bugreport with the detailed analysis! The commit dc929e0d168825d3894fb1fd74fbb94fb37f06da should address this issue by falling back to fetching label names or label values directly from the corresponding `metric_id -> metric_name` entries in the inverted index if the `match[]` filter matches less than 100K unique time series.

@Buddruggy , could you build VictoriaMetrics cluster components from this commit according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verify whether the commit works as expected?

**Comment by Buddruggy** [comment]
@valyala This commit solved the problem, thanks!

**Comment by Buddruggy** [comment]
@valyala  But i have one more question about this code
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/32037815/184908943-c7053170-e94f-4b33-be55-5888180e997d.png">
Why 100k? Is it better to use a ratio of count of ts and filter. like 10%?

**Comment by davidsome** [comment]
hello, @valyala  why remove /api/v1/labels/count ?

**Comment by davidsome** [comment]
hello, @valyala  why remove /api/v1/labels/count ?

**Comment by Buddruggy** [comment]
> @Buddruggy , thanks for the bugreport with the detailed analysis! The commit [dc929e0](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/dc929e0d168825d3894fb1fd74fbb94fb37f06da) should address this issue by falling back to fetching label names or label values directly from the corresponding `metric_id -> metric_name` entries in the inverted index if the `match[]` filter matches less than 100K unique time series.
> 
> @Buddruggy , could you build VictoriaMetrics cluster components from this commit according to [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verify whether the commit works as expected?

@valyala @valyala After i upgrade cluster to The commit [dc929e0](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/dc929e0d168825d3894fb1fd74fbb94fb37f06da) , there has a new problem
![image](https://user-images.githubusercontent.com/32037815/185395026-c635600b-957c-4d50-b5d6-599a125e99d7.png)
vmselect always return `duplicate output timeseries` when exec `{label1="v1", lable2="v2"}`

**Comment by valyala** [comment]
> hello, @valyala why remove /api/v1/labels/count

It has been decided to remove this endpoint because of the following issues:
- It wasn't useful in practice
- It wasn't documented well
- It wasn't supported by other monitoring systems

The removed `/api/v1/labels/count` endpoint can be emulated in the following way:
1. To query `/api/v1/labels`
2. To query `/api/v1/label/<labelName>/values` per each `<labelName>` returned from the step 1 and to count the number of unique values per each `<labelName>`.

> After i upgrade cluster to The commit [dc929e0](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/dc929e0d168825d3894fb1fd74fbb94fb37f06da) , there has a new problem

This issue should be resolved in the commit 87e0d69bf45d1157f8d79b415ff9292959077c3f

**Comment by valyala** [comment]
FYI, the [/api/v1/labels](https://docs.victoriametrics.com/url-examples.html#apiv1labels) and [/api/v1/label/<labelName>/values](https://docs.victoriametrics.com/url-examples.html#apiv1labelvalues) endpoints should work faster when the `match[]` query arg passed to these endpoints matches small number of time series, starting from [VictoriaMetrics v1.79.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.3).

**Comment by Buddruggy** [comment]
> The performance improvements for `/api/v1/labels` and `/api/v1/label/.../values` endpoints are available starting from [v1.81.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
> 
> @Buddruggy , feel free re-opening the issue or creating new one if you still experience unexpectedly slow responses to `/api/v1/labels` and/or `/api/v1/label/.../values` endpoints in VictoriaMetrics.

Thanks!

**Comment by junkfei** [comment]
不明觉厉
