### ISSUE TITLE
Can we change 'maxSearchQuerySize'  to configurable ?

### ISSUE THREAD

**Issue by thislyc** [VictoriaMetrics/VictoriaMetrics#2980]
**Describe the bug**
When my query parameter is very long, vmselect will return the following error
error when executing query="xxxxxxxxxxxxxx........":error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage 10.193.99.41:8401: cannot execute funcName=\"search_v7\" on vmstorage \"10.193.99.41:8401\": cannot write requestData: cannot write data in 0.000 seconds: write tcp4 10.193.100.219:36534->10.193.99.41:8401: write: connection reset by peer"

**To Reproduce**
post to  /prometheus/api/v1/query
with a very long promql as query parameter about 2.3MB

**Expected behavior**
successful result

**Logs**
error when executing query="xxxxxxxxxxxxxx........":error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage 10.193.99.41:8401: cannot execute funcName=\"search_v7\" on vmstorage \"10.193.99.41:8401\": cannot write requestData: cannot write data in 0.000 seconds: write tcp4 10.193.100.219:36534->10.193.99.41:8401: write: connection reset by peer"

**Screenshots**
![image](https://user-images.githubusercontent.com/42378143/184591354-b67076c8-ec6a-4c3c-b77e-eac4656946bf.png)

For VictoriaMetrics health-state issues please provide full-length screenshots 
I am sure the cluster is healthy

**Version**
root@furt--opinf-monitor-console-vmselect--63a26a app]# vmselect-prod --version
vmselect-20220714-171308-tags-v1.79.0-cluster-0-ga87f143e9

**Used command-line flags**
vmselect-prod \
-search.maxConcurrentRequests 10000 \
-search.maxPointsPerTimeseries 50000 \
-search.maxUniqueTimeseries 500000 \
-search.maxSeries=500000 \
-search.maxQueryLen=10485760 \
-search.maxQueryDuration 240s \
-httpListenAddr=:8481 \
-storageNode=$storageNode \
-replicationFactor=2 \
-dedup.minScrapeInterval=1s \

vminsert-prod \
-httpListenAddr=:8480 \
-storageNode=$storageNode \
-maxInsertRequestSize=536870912 \
-replicationFactor=2 \

vmstorage-prod  \
-httpListenAddr=:8482 \
-vminsertAddr=:8400 \
-vmselectAddr=:8401 \
-storageDataPath=/vmstorage-data/"${DAOKEIP}"/ \
-dedup.minScrapeInterval=1s \
-retentionPeriod=31d \
-search.maxTagKeys 100000 \
-search.maxTagValues 1000000 \
-search.maxUniqueTimeseries=10000000 \

**Comment by thislyc** [comment]
I have modified the - search.maxquerylen parameter

**Comment by thislyc** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/32ba5ec996ed8ac75ecfe2929e63aab677e800d4/app/vmselect/netstorage/netstorage.go#L1647

**Comment by thislyc** [comment]
promql just like this
cpu_free{ident=~"^2102310LXP10E5000070$|^8RXCDC2$|^8RYBDC2$|^8RZGDC2$|^BGJBDC2$|^TCGZ-MOBILE-MVTLOG-001$|^TCGZ-MOBILE-MVTLOG-002$|^TCGZ-MOBILE-MVTLOG-003$|^TCGZ-MOBILE-MVTLOG-004$|^TCGZ-ONLINE-WEBLOGZK-001$|^TCGZ-ONLINE-WEBLOGZK-002$|^TCSH-ONLINE-WEBLOGZK-001$|^TCSH-ONLINE-WEBLOGZK-002$|^TCSH-ONLINE-WEBMVT-001$|^TCSH-ONLINE-WEBMVT-002$|^TCSH-ONLINE-WEBMVT-003$|^TCSH-ONLINE-WEBMVT-004$.................................."}

**Comment by Yuri1Kravets** [comment]
Hi @thislyc can you share the logs on `vmstorage` side as well?
It is still not quite clear what might be the cause from `vmselect` logs only.

**Comment by thislyc** [comment]
> 你好@thislyc你也可以分享`vmstorage`侧面的日志吗？仅从日志 中可能是什么原因仍然不是很清楚。`vmselect`

 Hi, thank you for your reply

vmstorage logs:
VictoriaMetrics/lib/vmselectapi/server.go:181\tcannot process vmselect conn 10.198.206.124:54694: cannot process vmselect request: cannot execute "search_v7": cannot read searchQuery: too big data size: 1174932; it mustn't exceed 1048576 bytes

**Comment by Yuri1Kravets** [comment]
What is the current `search.maxquerylen` parameter?
(You mentioned that it was modified)

**Comment by thislyc** [comment]
>vmselect  -search.maxQueryLen=10485760

**Comment by thislyc** [comment]
> What is the current `search.maxquerylen` parameter? (You mentioned that it was modified)

vmselect -search.maxQueryLen=10485760

**Comment by Yuri1Kravets** [comment]
Can you try increasing it by 20% approximately and check if the same error will pop up again?

**Comment by thislyc** [comment]
> Can you try increasing it by 20% approximately and check if the same error will pop up again?

the same error pop up again

**Comment by Yuri1Kravets** [comment]
The same for `vmsotorage` and `vmselect`?
If yes, seems like limit change was not recognized.

**Comment by thislyc** [comment]
> The same for `vmsotorage` and `vmselect`? If yes, seems like limit change was not recognized.

search.maxquerylen parameter can be add at vmsotorage?

**Comment by thislyc** [comment]
> The same for `vmsotorage` and `vmselect`? If yes, seems like limit change was not recognized.

The error log is the same

**Comment by Yuri1Kravets** [comment]
> > The same for `vmsotorage` and `vmselect`? If yes, seems like limit change was not recognized.
> 
> search.maxquerylen parameter can be add at vmsotorage?

It can not.

**Comment by thislyc** [comment]
I don't think it's a problem that this parameter doesn't work. When I narrow this parameter, vmselect prompts me to increase it

**Comment by thislyc** [comment]
> The same for `vmsotorage` and `vmselect`? If yes, seems like limit change was not recognized.

I don't think it's a problem that this parameter doesn't work. When I narrow this parameter, vmselect prompts me to increase it

**Comment by thislyc** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/32ba5ec996ed8ac75ecfe2929e63aab677e800d4/lib/vmselectapi/server.go#L216
This sizebuf is assigned there. Is there any deviation in the assignment calculation

**Comment by thislyc** [comment]
Hi, @Yuri1Kravets  
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/32ba5ec996ed8ac75ecfe2929e63aab677e800d4/lib/vmselectapi/server.go#L314
// maxSearchQuerySize is the maximum size of SearchQuery packet in bytes.
const maxSearchQuerySize = 2048 * 1024
After I modify this parameter, the request can be returned successfully, but this parameter cannot be configured in the startup parameter

**Comment by thislyc** [comment]
Hi , @valyala @Yuri1Kravets 
Can we change 'maxSearchQuerySize'  to configurable ?
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/32ba5ec996ed8ac75ecfe2929e63aab677e800d4/lib/vmselectapi/server.go#L314

**Comment by hagen1778** [comment]
The `maxSearchQuerySize` is defined to 1MB, it means your query exceeds that size... Are there any other options to reduce the query size? Such a big regex expression as in your example looks very inefficient. 1MB seems to me like a good internal limit from malicious queries and I'd like not to change it.
