### ISSUE TITLE
Grafana dashboard - Network graphs unit type in bytes instead of bit/s

### ISSUE THREAD

**Issue by hekmon** [VictoriaMetrics/VictoriaMetrics#299]
On the grafana cluster dashboard, network graphs use binary prefix of bytes (ex: KiB) as unit as if it was storage but network should always be measured as decimal prefix of bits (ex: Kb). It also seems the values are generated from a `rate` so unit should definitely be in Kb/s. In Grafana the unit type is `bits/sec`.

I totally understand that for the timeserie (`vm_tcplistener_read_bytes_total`) storage purpose it is best to use bytes (who needs that kind of precision, it just a pure waste of space) we do it all the same on our custom agents.

But in that case the MetricsQL expression should be adapted to match the desired Grafana unit, for example:
`sum(rate(vm_tcplistener_read_bytes_total{job=~"$job_insert", instance=~"$instance"}[5m])) by (instance) > 0`
should be written
`sum(rate(vm_tcplistener_read_bytes_total{job=~"$job_insert", instance=~"$instance"}[5m])) by (instance) * 8 > 0`
before applying the `bits/sec` unit type on the graph.

**Comment by valyala** [comment]
Agreed. @hagen1778 , could you change bytes/s to bits/s on networking graphs in the official dashboards?

**Comment by hekmon** [comment]
Thanks!

BTW thanks for this dashboard, it is really helpful :)

**Comment by hekmon** [comment]
Closing as fix has been included in the latest release:
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.33.0
