### ISSUE TITLE
Incorrect histogram_quantile

### ISSUE THREAD

**Issue by borg-z** [VictoriaMetrics/VictoriaMetrics#3]
I'm using dashboard from https://github.com/kubernetes/ingress-nginx/blob/master/deploy/grafana/dashboards/nginx.json
This dashboard contains query with histogram_quantile function. Result from VictoriaMetrics and from Prometheus is different. histogram_quantile in VictoriaMetrics works incorrect.

**Comment by borgkun** [comment]
`histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!="",controller_pod=~"$controller",controller_class=~"$controller_class",controller_namespace=~"$namespace",ingress=~"$ingress"}[30s])) by (le, ingress))`

![2018-12-27_13-51](https://user-images.githubusercontent.com/31611228/50477760-c7252200-09de-11e9-9570-a32cd59a3bc8.png)

**Comment by valyala** [comment]
Confirmed the bug. Should be fixed soon.
