### ISSUE TITLE
vmalert: {{ $labels.alertname }} isn't available in labels and annotation templating on v1.79.2

### ISSUE THREAD

**Issue by stevenbeaullieu** [VictoriaMetrics/VictoriaMetrics#3013]
**Describe the bug**
If you include `{{ $labels.alertname }}` in an annotation or label it does not come through and shows `<no value>` in the alert output. 
 Other labels are working.  This was working fine with v1.72.0 and we just upgraded to v1.79.2 and started noticing this issue.

**To Reproduce**
Define alert with the following templating in the labels or annotations section `{{ $labels.alertname }}`.

**Expected behavior**
Templating for `{{ $labels.alertname }}` to work in labels and annotations.

**Version**
vmalert v1.79.2 (used with cluster version v1.79.2 of vmselect/storage etc)

**Comment by hagen1778** [comment]
Hello! Only original labels which belong to time series are available for annotations templating. Please see more details at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2403

**Comment by stevenbeaullieu** [comment]
Not sure I follow.  Here is what alertmanager looks like with vmalert 1.72.0 where it's working:
![image_123986672](https://user-images.githubusercontent.com/25550833/186245646-38e757ff-875f-47de-b8cc-2b2c74f0436d.JPG)

And here is what it looks like with vmalert 1.79.2 where it's not working:
![image_123986672 (1)](https://user-images.githubusercontent.com/25550833/186245809-7ecc9f2e-ff63-4b2c-9918-f70ab7a98023.JPG)

As far as I know it worked fine with Prometheus as well.

**Comment by valyala** [comment]
@hagen1778 , what about exposing the automatically generated `alertname` label during templating, and overriding it with non-empty `alertname` label received from the alert? This will improve experience for users expecting `$labels.alertname` in templates, while it will keep Prometheus-compatible behavior when the alert contains `alertname` label.

**Comment by hagen1778** [comment]
@valyala @stevenbeaullieu please see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3181

**Comment by valyala** [comment]
Extra labels are available in annotations starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed then.
