### ISSUE TITLE
Question: help with vmalert repeatedly sent resolved alerts to AlertManager?

### ISSUE THREAD

**Issue by waldoweng** [VictoriaMetrics/VictoriaMetrics#3014]
I'm confuse by the source code below:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a87f143e9203cc20c3203f50bd9c79bb403e342e/app/vmalert/alerting.go#L237-L239

and

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a87f143e9203cc20c3203f50bd9c79bb403e342e/app/vmalert/alerting.go#L257-L262

can somebody kindly explain why we keep sending resolved alerts to AlertManager?

thx.

**Comment by laixintao** [comment]
It's following alertmanager's specification:

> This implies that the inactive alert MUST be sent continuously with a fixed interval until 15 minutes after the ResolvedAt of the alert, or until a new alert is created with the same labels.

https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#conditions-for-sending-inactive-alerts

**Comment by waldoweng** [comment]
thx @laixintao, close this issue as the question has been answered.
