### ISSUE TITLE
VM alert - config reader

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#302]
It accepts yaml config as input parameter in Prometheus format, parses it into Go struct.

#### Requirements:
- Reuse existing code from VictoriaMetrics repo
- Every package should be covered by tests 
- Application uses command line flags for configuration

**Comment by valyala** [comment]
Closing this issue, since [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert) already implements config reading.
