### ISSUE TITLE
vmalert: debug mode for rule

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3025]
**Is your feature request related to a problem? Please describe.**
Sometimes it is unclear why some specific rule triggers or not triggers. vmalert does not provide any additional information besides current alert state. And there is no way to track how this state changed with time.

**Describe the solution you'd like**
Would be great to have a setting on a rule level named `debug` which would enable additional logs for each rule execution. The log may include the following data:
* moment when rule was executed
* the exact HTTP call issued by the rule
* details of received data
* the state change if any

**Comment by hagen1778** [comment]
Hi @Howie59! Sorry for unassigning you. The priority for this feature changed and I had to get it fast. Feel free to left comments and suggestions to the linked PR.

**Comment by valyala** [comment]
FYI, the `debug` mode is available in `vmalert` starting from the commit 0ead64b6cfe7eed31ccfdf5c0aab836c652b8c4e . The debug mode can be enabled at alerting rule by specifying `debug: true` option. See [these docs](https://docs.victoriametrics.com/vmalert.html#alerting-rules) for details. `vmalert` logs various debug information for alerting rules with the enabled debugging. The feature can be tested right now by building `vmalert` from the commit mentioned above according to [these build instructions](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources). The commit will be included in the next release if everything is OK with it.
