### ISSUE TITLE
VM alert - Source Caller

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#303]
Create own watchdog for every alert group (goroutines), which executes alert query on given source and issues an alert if source returns non-empty result. 
Source can be any service which supports PromQL (MetricsQL).

#### Requirements:
- Avoid external dependencies if possible
- Every package should be covered by tests 
- Application uses command line flags for configuration

**Comment by valyala** [comment]
Closing this issue, since [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert) already can query any datasource, which provides Prometheus querying API.
