### ISSUE TITLE
vmselect need to set the tmpDirPath

### ISSUE THREAD

**Issue by forezp** [VictoriaMetrics/VictoriaMetrics#3037]

**Comment by forezp** [comment]
I find this panic error:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/11371924/187184519-7f0c6575-cdde-455d-b0ec-f47d59569226.png">

that mybe occured by other people deleted the tmp dictory . so i want to set this Path. But i cannot !

**Comment by valyala** [comment]
FYI, `vmselect` stores temporary files at `/tmp` directory by default. The directory for temporary files can be changed by passing the needed directory path to `-cacheDataPath` command-line flag to `vmselect`.
