### ISSUE TITLE
VM alert - Alert Management Provider

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#304]
Send positive alert to alert management system, provides interface for every concrete implementation.
Should be ingratiated with Prometheus alertmanager.

#### Requirements:
- Stateless
- Avoid external dependencies if possible
- Every package should be covered by tests 
- Application uses command line flags for configuration

**Comment by valyala** [comment]
@tenmozes , I think this issue may be closed now since [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert) already supports sending alerts to AlertManager.

**Comment by hagen1778** [comment]
Correct. It covers all listed points. @tenmozes feel free to reopen if you feel differently.
