### ISSUE TITLE
`rate_over_sum` produces unexpected results compared to `sum_over_time(m[d]) / d`

### ISSUE THREAD

**Issue by qikiqi** [VictoriaMetrics/VictoriaMetrics#3045]
**Describe the bug**
Performing rate_over_sum via Grafana produces unexpected results that differ from the data produced by query `sum_over_time(m[d]) / d`

**To Reproduce**
We have three queries:
1. The data query:
  a. `sum_over_time(metric_name{status=~"5.*"} offset -$__interval)`
2. The `rate_over_sum` query
  a. `rate_over_sum(metric_name{status=~"5.*"}[5m] offset -$__interval)`
3. the "manual `rate_over_sum`" query (`sum_over_time(m[d]) / d`)
  a. `sum_over_time(metric_name{status=~"5.*"}[5m] offset -$__interval) / (5*60)`

Below is a CSV export of the results:

Time | sum_over_time | rate_over_sum | sum_over_time(m[d]) / d
-- | -- | -- | --
1659938520000 | 8 | 0.02666666666666667 | 0.02666666666666667
1659938540000 | 2 | 0.03333333333333333 | 0.03333333333333333
1659938560000 | 1 | 0.03666666666666667 | 0.03666666666666667
1659938580000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938600000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938620000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938640000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938660000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938680000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938700000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938720000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938740000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938760000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938780000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938800000 | undefined | 0.03666666666666667 | 0.03666666666666667
1659938820000 | undefined | 0.1 | 0.01
1659938840000 | undefined | 0.1 | 0.0033333333333333335

**Expected behavior**
I expect the values for timestamp `1659938820000` and `1659938840000` to match for columns `rate_over_sum` and `sum_over_time(m[d]) / d`

**Logs**
No logs for this.

**Screenshots**
![image](https://user-images.githubusercontent.com/11520039/187490105-5e947547-4125-45ef-9eb0-3130dfc2afc8.png)

**Version**
```
$ vmstorage --version
vmstorage-20220808-174312-tags-v1.80.0-cluster-0-g91d0b4553
```
```
$ ./vmselect-prod --version
vmselect-20220808-174451-tags-v1.80.0-cluster-0-g91d0b4553
```

**Used command-line flags**
```
$ sudo systemctl status vmstorage
...
             └─3682158 /usr/local/bin/vmstorage -bigMergeConcurrency 48 -dedup.minScrapeInterval 1ms -http.shutdownDelay 20s -httpListenAddr XXX -loggerErrorsPerSecondLimit 100 -memory.allowedPercent 60 -retentionPeriod 120d -storage.minFreeDiskSpaceBytes 100GB -storageDataPath /data/victoriametrics/vmstorage/data -vminsertAddr XXX -vmselectAddr XXX
```
```
~> k describe statefulset/vmselect-vmcluster -n victoriametrics | grep Args -A7                                                 19:33:11
    Args:
      -dedup.minScrapeInterval=1ms
      -httpListenAddr=:8481
      -search.latencyOffset=20s
      -search.maxStalenessInterval=3600s
      -search.minStalenessInterval=120s
      -selectNode=<vmselects>
      -storageNode=<vmstorages>
```

**Comment by valyala** [comment]
@qikiqi , thanks for the bugreport! It should be fixed in the commit c6b74148cf309dc3e57f8d48d2f15c6ca9e76771 for cluster version of VictoriaMetrics. This commit will be included in the next release. In the mean time it is possible to build `vmselect` from this commit according to [these instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) and verify whether this fixes the issue with unexpected [rate_over_sum()](https://docs.victoriametrics.com/MetricsQL.html#rate_over_sum) results.

**Comment by valyala** [comment]
The bugfix for this issue has been included in [VictoriaMetrics v1.79.4 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.4).

**Comment by valyala** [comment]
VictoriaMetrics should properly calculate `rate_over_sum(m[d])` as `sum_over_time(m[d]) / d` starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
