### ISSUE TITLE
VM alert - Web Server

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#305]
Endpoints:
- `/alerts` - it should display information similar to [the corresponding page in Prometheus](https://prometheus.io/docs/prometheus/latest/querying/api/#alerts)
-   `/<group>/<alert>/status`. Return json object with `name`, `status` and `expr_last_result`
- `/metrics`
- `/health`

open questions:
- should the tool provide API or UI for managing alerting rules? Where to store config updated via the API or UI?
- should the tool provide “alerting rules validation mode” for validating and debugging alerting rules? This mode is useful when creating and debugging alerting rules.

#### Requirements:
- Stateless
- Makefile rules for common tasks – see Makefiles for other apps in the app/ dir 
- Every package should be covered by tests 
- Dockerfile
- Graceful shutdown 
- Application uses command line flags for configuration

**Comment by valyala** [comment]
Closing this issue, since [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert) already implements these endpoints.
