### ISSUE TITLE
Vmalert send inactive messages repeatedly

### ISSUE THREAD

**Issue by ygsa** [VictoriaMetrics/VictoriaMetrics#3051]
English is not my native language; please excuse typing errors.

**Describe the bug**
I used my alert_plugin( just pretreat alert messages for add some other info before sent to alertmanager.) always recived  repetitive resolved messages (recived time after endsAt).
**To Reproduce**

**Expected behavior**
I think the inactive messages only sent once just enough to tell which is resolved.
And I want to know why it need repeat to alertmanager [code Where](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/alerting.go#L238-L240) 
Thanks!

**Logs**
No error logs for here

**Code where**
[where](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/alerting.go#L260)
**Version**
```
$ vmalert-prod --version
vmalert-20220808-142355-tags-v1.79.2-0-gfc0edfab1
```

**Comment by ygsa** [comment]
#2340

**Comment by hagen1778** [comment]
Hello @ygsa! This is done intentionally. Please see https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#conditions-for-sending-inactive-alerts

You can try tweaking this behaviour by updating the following flag:
```
  -rule.resendDelay duration
     Minimum amount of time to wait before resending an alert to notifier
```

**Comment by ygsa** [comment]
Oh Thanks! I will try it and deal in my plugin.
