### ISSUE TITLE
Use a custom header for authorization in vmgateway

### ISSUE THREAD

**Issue by maxkondr** [VictoriaMetrics/VictoriaMetrics#3054]
**Is your feature request related to a problem? Please describe.**
Let's consider the situation when we need on vmgateway side to authenticate incoming requests using `-httpAuth.username` and `-httpAuth.password`. In such a case we can't pass a jwt token at the same time because it should be passed in the same http header.

**Describe the solution you'd like**
Provide with possibility to define http header to read jwt token from and provide CLI param like `-httpJwt.header=X-My-Header`.

**Comment by valyala** [comment]
`vmgateway` will support `-auth.httpHeader` command-line flag, which can be used for specifying non-standard HTTP header to read JWT token from. By default JWT token is read from `Authorization` HTTP header.

**Comment by valyala** [comment]
[vmgateway](https://docs.victoriametrics.com/vmgateway.html) support `-auth.httpHeader` command-line flag starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
