### ISSUE TITLE
Victoria metrics cluster should write logs to stdout instead of stderr

### ISSUE THREAD

**Issue by freeseacher** [VictoriaMetrics/VictoriaMetrics#306]
**Describe the bug**
Given following systemd file
```
[Service]
Type=simple
LimitNOFILE=8192
User=victoriametrics
Group=victoriametrics
ExecStart=/opt/victoria-metrics/vminsert-prod \
...
    -httpListenAddr=":8480" \
    -loggerLevel="INFO" 


StandardOutput=append:/var/log/vminsert.log
StandardError=append:/var/log/vminsert-error.log

```
Expected that logs should be in `vminsert.log` but got all logs in `vminsert-error.log`

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
/opt/victoria-metrics/vminsert-prod --version 
vminsert-20200128-195548-tags-v1.32.8-cluster-0-gb28c9a39
```

**Comment by valyala** [comment]
Changing default output for logs from `stderr` to `stdout` can break existing setups, so it would be better adding a special command-line flag `-loggerOutput`, which could be used for changing log output.

**Comment by valyala** [comment]
The `-loggerOutput` command-line flag has been added in [v1.33.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
