### ISSUE TITLE
HTTP_AUTH doesn't work everywhere

### ISSUE THREAD

**Issue by Woart** [VictoriaMetrics/VictoriaMetrics#3060]
### **work server:**

**Version:**
victoria-metrics-20220902-190337-tags-v1.81.1-0-gac98ecdc1

**Parameters:**
- -storageDataPath /path/to/db
- -httpAuth.password test
- -httpAuth.username test
- -opentsdbHTTPListenAddr <_VICTORIA_METRICS_IP_>:4242
- -retentionPeriod 1w

--------------------------

### **test server**

**# curl -vv <_VICTORIA_METRICS_IP_>:8428**
HTTP_AUTH: Access denied

> GET / HTTP/1.1
> Host: _<VICTORIA_METRICS_IP>_:8428
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="VictoriaMetrics"
< X-Content-Type-Options: nosniff
< X-Server-Hostname: _<VICTORIA_METRICS_SERVER>_
< Date: Sun, 04 Sep 2022 17:04:43 GMT

---

**# curl -vv <_VICTORIA_METRICS_IP_>:8428/debug**
HTTP_AUTH: access denied

> GET /debug/ HTTP/1.1
> Host: _<VICTORIA_METRICS_IP>_:8428
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< Www-Authenticate: Basic realm="VictoriaMetrics"
< X-Content-Type-Options: nosniff
< X-Server-Hostname: _<VICTORIA_METRICS_SERVER>_
< Date: Sun, 04 Sep 2022 17:04:43 GMT

---
Also denied access.

**# curl -vv <_VICTORIA_METRICS_IP_>:8428/debug/pprof/**
HTTP_AUTH: not working here

> GET /debug/pprof/ HTTP/1.1
> Host: _<VICTORIA_METRICS_IP>_:8428
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< X-Content-Type-Options: nosniff
< X-Server-Hostname: _<VICTORIA_METRICS_SERVER>_
< Date: Sun, 04 Sep 2022 17:08:16 GMT
< Transfer-Encoding: chunked
```
<
<html>
<head>
<title>/debug/pprof/</title>
<style>
.profile-name{
	display:inline-block;
	width:6rem;
}
</style>
</head>
<body>
/debug/pprof/<br>
<br>
Types of profiles available:
<table>
<thead><td>Count</td><td>Profile</td></thead>
<tr><td>344</td><td><a href='allocs?debug=1'>allocs</a></td></tr>
<tr><td>0</td><td><a href='block?debug=1'>block</a></td></tr>
<tr><td>0</td><td><a href='cmdline?debug=1'>cmdline</a></td></tr>
<tr><td>86</td><td><a href='goroutine?debug=1'>goroutine</a></td></tr>
<tr><td>344</td><td><a href='heap?debug=1'>heap</a></td></tr>
<tr><td>0</td><td><a href='mutex?debug=1'>mutex</a></td></tr>
<tr><td>0</td><td><a href='profile?debug=1'>profile</a></td></tr>
<tr><td>16</td><td><a href='threadcreate?debug=1'>threadcreate</a></td></tr>
<tr><td>0</td><td><a href='trace?debug=1'>trace</a></td></tr>
</table>
<a href="goroutine?debug=2">full goroutine stack dump</a>
<br>
<p>
Profile Descriptions:
<ul>
<li><div class=profile-name>allocs: </div> A sampling of all past memory allocations</li>
<li><div class=profile-name>block: </div> Stack traces that led to blocking on synchronization primitives</li>
<li><div class=profile-name>cmdline: </div> The command line invocation of the current program</li>
<li><div class=profile-name>goroutine: </div> Stack traces of all current goroutines</li>
<li><div class=profile-name>heap: </div> A sampling of memory allocations of live objects. You can specify the gc GET parameter to run GC before taking the heap sample.</li>
<li><div class=profile-name>mutex: </div> Stack traces of holders of contended mutexes</li>
<li><div class=profile-name>profile: </div> CPU profile. You can specify the duration in the seconds GET parameter. After you get the profile file, use the go tool pprof command to investigate the profile.</li>
<li><div class=profile-name>threadcreate: </div> Stack traces that led to the creation of newOS threads</li>
<li><div class=profile-name>trace: </div> A trace of execution of the current program. You can specify the duration in the seconds GET parameter. After you get the trace file, use the go tool trace command to investigate the trace.</li>
</ul>
</p>
</body>
```

----
**# curl -vv <_VICTORIA_METRICS_IP_>:4242/api1/put**
HTTP_AUTH: not working for OpenTSDB HTTP requests

> GET /api/put HTTP/1.1
> Host: <_VICTORIA_METRICS_IP_>:4242
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Sun, 04 Sep 2022 17:15:32 GMT
< Content-Length: 154
<
remoteAddr: "<_TEST_SERVER_IP_>:63216"; requestURI: /api/put; cannot parse HTTP OpenTSDB json: cannot parse JSON: cannot parse empty string; unparsed tail: ""

----

**Comment by n10ty** [comment]
Quite critical, as for me

**Comment by jappaleinen** [comment]
Elaborating on the issue discussed here, which I believe to be related.

I'm setting up a `vmauth` container with the purpose of allowing some specific external users report metrics on behalf of some systems running outside our networks. Each such user are limited access to a few specific `url_prefix`:es.

All other endpoints should be protected from unauthenticated access, so I'm providing `-httpAuth.*`command line arguments. Yet, I find that many endpoints are still accessible without providing any credentials at all. Eg
* /metrics
* /-/reload
* /flags
* /debug/pprof

I've not specified any `-*AuthKey` command line options so I expected default behaviour to be falling back to `-httpAuth.*` credentials preventing unauthorized access. I expect all existing (and future) `-*AuthKey` command line parameters to be falling back to be protected with httpAuth credentials unless explicitly overridden.

**Comment by valyala** [comment]
The `-httpAuth.*` command-line flag should protect all the http endpoints starting from [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). A separate auth key can be specified for endpoints with the dedicated `-*AuthKey` command-line flags.
