### ISSUE TITLE
vm_slow_row_inserts_total seems wrong

### ISSUE THREAD

**Issue by hamelg** [VictoriaMetrics/VictoriaMetrics#3064]
We have a vmsingle instance with low traffic through many remote writes. Each vmagent sends scraped metrics with an interval of 10m. The vm_slow_row_inserts_total metric looks wrong and continuously raises the TooHighSlowInsertsRate alarm. The vmsingle instance works fine and shows no issues. Any ideas how to fix the alarm ?

**Screenshots**
![image](https://user-images.githubusercontent.com/9417309/188409948-ef99d2bb-9dd6-4f61-b278-5ee0939aec38.png)
![image](https://user-images.githubusercontent.com/9417309/188410065-6bd32fca-53de-4764-93a9-95b3f0cf99a9.png)

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20220521-000906-tags-v1.77.2-0-g2d2d15b0d

```

**Used command-line flags**
```
/victoria-metrics-prod -dedup.minScrapeInterval=10m -httpLi
stenAddr=:8429 -logNewSeries=true -loggerFormat=json -loggerTimezone=Europe/Pari
s -retentionPeriod=24 -search.maxQueryLen=1500000 -storageDataPath=/victoria-met
rics-data

/vmagent-prod -httpListenAddr=:8429 -loggerFormat=json -pro
mscrape.config=/etc/vmagent/config_out/vmagent.env.yaml -remoteWrite.basicAuth.p
assword="xxx","xxx" -remoteWrite.basicAuth.username="xxxx","xxxx" -remoteW
rite.maxDiskUsagePerURL=1073741824 -remoteWrite.tlsCAFile=/etc/vmagent-tls/certs
/ca-bundle.crt,/etc/vmagent-tls/certs/xxxxs_trusted-ca_ca-bun
dle.crt -remoteWrite.tmpDataPath=/tmp/vmagent-remotewrite-data -remoteWrite.url=
https://victoria-xxxx/api/v1/write,https://victoria-lc
xxxxx.fr/api/v1/write -remoteWrite.urlRelabelConfig=/etc
/vm/relabeling/url_rebaling-0.yaml,/etc/vm/relabeling/url_rebaling-1.yaml
```

**Comment by hamelg** [comment]
![image](https://user-images.githubusercontent.com/9417309/190099526-c0b8dc39-a3e7-4a5e-b305-febac0d3511b.png)
![image](https://user-images.githubusercontent.com/9417309/190099651-22a78002-dc1b-4865-a3b2-6cf3e32fd6a1.png)
![image](https://user-images.githubusercontent.com/9417309/190099748-3f8470d9-a264-484c-8ab3-def23e30932f.png)

**Comment by hagen1778** [comment]
Oh, I see now. The cache responsible for minimizing [slow inserts](https://docs.victoriametrics.com/FAQ.html?highlight=slow%20insert#what-is-a-slow-insert) has a TTL of 10m, and that is not configurable. So the advice is either do writes with higher frequency or just disable this alert. For the workload of 50k active time series and ingestion <1k samples/s it actually doesn't make sense. This cache was designed for much higher workloads.

**Comment by hamelg** [comment]
Many thanks for the explication.
