### ISSUE TITLE
vmui: cardinality explorer enhancement

### ISSUE THREAD

**Issue by YuriKravetc** [VictoriaMetrics/VictoriaMetrics#3070]
On the stage of merging statuses from each storage node, the same label could have different values on each node. 
But `vmselect` does not receive the actual values, so it can't compare them and find intersections or sum up unique values. Instead, it picks a node with the highest number of unique values and assumes it is the closest one to reality.

It would be good to add some explanations and expectations to the numbers shown on Cardinality Explorer.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), [cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer) tab shows the information about possible inaccuracy in the provided statistics for cluster version of VictoriaMetrics. Closing the feature request as done.
