### ISSUE TITLE
Please provide feature Timezone select for vmui and vmselect

### ISSUE THREAD

**Issue by zharymv** [VictoriaMetrics/VictoriaMetrics#3075]
There are different groups of developers in our team. 
But they allocated at different time zones. 
There is need to have debugging tools with common definitions.

That's why I'm asking you to provide option "Timezone Select".
It will help us to proceed with metrics that are not in grafana dashboards when trouble is under investigation.

**Comment by valyala** [comment]
This feature is available starting from [VictoriaMetrics v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it as done.
