### ISSUE TITLE
Unclear panic on vminsert or vmselect when user defines same storage nodes addresses in the `-storageNode` flag

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#3076]
**Describe the bug**
If i start `vmselect` or `vminsert` with duplicated addresses in the `-storageNode` flag i got a panic which not very clear and do not tell me what cause the problem. In the config can be present many different flags. 

**Log**
```bash
panic: BUG: metric "vm_tcpdialer_dials_total{name=\"vmselect\", addr=\":8410\"}" is already registered

goroutine 1 [running]:
github.com/VictoriaMetrics/metrics.(*Set).mustRegisterLocked(0xc0000e41c0, {0xc0000b4500, 0x37}, {0x472d700?, 0xc0000b22b8})
        /Users/dmitryk-dk/VictoriaMetrics-enterprise/vendor/github.com/VictoriaMetrics/metrics/set.go:452 +0x217
```

**To Reproduce**
Build `vmselect` or `vminsert` from root of project by executing command `make vmselect` or `make vminsert`
Run command from `bin` folder:
```bash
./vmselect -storageNode=:8410,:8410
```

**Expected behavior**
I think we should error when we are starting `vmselect` or `vminsert` and there is duplicates present on `-storageNode` flag. 
On start process this components can check duplicates of the storage nodes slice and if  it contains duplicated storage finish process with error message.

**Comment by valyala** [comment]
FYI, `vminsert` and `vmselect` should emit user-readable error when multiple identical addresses are passed to `-storageNode` command-line flag starting from the [release v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
