### ISSUE TITLE
Add version to vmagent & vmalert dashboards

### ISSUE THREAD

**Issue by tumd** [VictoriaMetrics/VictoriaMetrics#3077]
**Is your feature request related to a problem?**
In our deployment we run quite a few instances of vmagent; One vmagent-instance on each machine, and two in each k8s-cluster. As the number grows it gets harder to maintain an overview of what version of vmagent is running in the fleet.

**Describe the solution you'd like**
It would be helpful if the official vmagent (and also vmalert) dashboards would include information on what version each instance is running. The metric is already there, and _only_ needs to be visualized in some way.
My suggestion would be to add a version column to the Uptime table on the vmagent & vmalert dashboards.
Something like this;
<img width="418" alt="Screenshot 2022-09-06 at 15 00 39" src="https://user-images.githubusercontent.com/463066/188643067-b483937c-831f-4311-b622-dfdf47e87b01.png">

**Comment by hagen1778** [comment]
Versions are now available for vmagent and vmalert dashboards.
You can find updated versions of dashboards here https://grafana.com/orgs/victoriametrics/dashboards
