### ISSUE TITLE
Implement remote_write method

### ISSUE THREAD

**Issue by iglov** [VictoriaMetrics/VictoriaMetrics#308]
So that we can build the scheme
![prom-vm-scheme](https://user-images.githubusercontent.com/18374992/73732069-57de3d80-475b-11ea-8b30-1f5c3af71fca.png)

**Comment by valyala** [comment]
Thanks for the feature request! It looks useful. I'll think about the best implementation.

Currently the following workarounds exist that allow writing metric subsets into distinct VictoriaMetrics instances:

1. Prometheus can be configured with multiple [remote_write sections](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write). Each section can contain distinct configs for `write_relabel_configs` and distinct `url` values pointing to distinct VictoriaMetrics instances. This way Prometheus will write data simultaneously to all the configured `remote_write` destinations after applying `write_relabel_configs` to them.

2. VictoriaMetrics supports [`/federate` endpoint](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#federation), so it is possible to configure additional Prometheus instances that would scrape the required subset of metrics from VictoriaMetrics via `/federate` endpoint and write them to another VictoriaMetrics instances.

**Comment by valyala** [comment]
@iglov , the outlined scheme with metrics relabeling will be possible soon with the upcoming `vmagent` tool. It can accept data via `remote_write API`, relabel it and then write it to other remote storage systems via `remote_write API`. Read more information about it [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/260#issuecomment-565014679).

**Comment by valyala** [comment]
FYI, vmagent has been released - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md

**Comment by iglov** [comment]
Hey, Sashka! :)
Well, seems like it isn't exactly what i want, but ok. Is this possible with vmagent to do something like this:
![prom-vmagent-scheme-1](https://user-images.githubusercontent.com/18374992/75684254-3c167a80-5cba-11ea-8a0c-8d0d3339efc2.png)

**Comment by valyala** [comment]
Currently `-remoteWrite.relabelConfig` is shared among all the configured `-remoteWrite.url` values. I think it would be nice to add ability to set per-remote storage relabel configs in `vmagent`. In this case your schema should work.

In the mean time you can add yet another `vmagent` in front of each `victoriametrics`, which will delete unneeded metrics according to its relabel configs. Note that `vmagent` instances may be chained, since they support data ingestion via Prometheus remote_write API at `http://vmagent:8429/api/v1/write` endpoint.

**Comment by valyala** [comment]
@iglov , the per-remote storage relabeling has been added to `vmagent` in the commit 02b55c72dc018aedad1a40a4e674f074ed13f9fe . It allows setting `-remoteWrite.urlRelabelConfig` for each configured `-remoteWrite.url`:

```
/path/to/vmagent \
  -remoteWrite.url=http://vm1:8428/api/v1/write -remoteWrite.urlRelabelConfig=relabel1.yml \
  -remoteWrite.url=http://vm2:8428/api/v1/write -remoteWrite.urlRelabelConfig=relabel2.yml
```

Try building `vmagent` from sources according to [these instructions](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#how-to-build-from-sources) and verifying whether it works for your case.

**Comment by valyala** [comment]
The per-remote storage relabeling via `-remoteWrite.urlRelabelConfig` has been added in [v1.34.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing the feature request as done. @iglov , feel free re-opening it or creating new feature request if you feel you need additional functionality related to this feature request.

**Comment by iglov** [comment]
O-o-ok, i'll see and if i'll have any question, i'll ask on telegram, thx Sashka ;)
