### ISSUE TITLE
Find longest period that series has value satisfy a condition (greater than 0)

### ISSUE THREAD

**Issue by earable-nhunh** [VictoriaMetrics/VictoriaMetrics#3084]
I have a time series like the image:
![image](https://user-images.githubusercontent.com/88126442/188908755-51ba759c-74c8-4b4f-a927-00cfedd5a908.png)
I want to find the longest period that metric has value > 0. For example in the image, the third one is the longest

**Comment by dmitryk-dk** [comment]
Hi @earable-nhunh ! Thank you for your question.
Unfortunately VictoriaMetrics doesn't provide such function. But you can try using metric >bool 0 query - it will return 1 for metric values bigger than 0, and should return 0 for metric values lower than 0. This can help visually determining the longest duration of the metric bigger than 0.

Can we close the issue?

**Comment by hagen1778** [comment]
Closing issue as inactive
