### ISSUE TITLE
vmagent 1.79.3  always oomkilled

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#3085]
![image](https://user-images.githubusercontent.com/73687556/189031326-346f55f5-d785-4993-b936-0104edb58c3c.png)
![image](https://user-images.githubusercontent.com/73687556/189031429-e92ea51b-8312-4c8c-9d4a-b61466fbe354.png)

I gave him 5g of memory, but it was still oomkilled

**Comment by guidao** [comment]
https://docs.victoriametrics.com/vmagent.html#troubleshooting
