### ISSUE TITLE
Allow auto-deletion of certain metrics after a fixed period

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3086]
**Is your feature request related to a problem? Please describe.**
Production environments usually export a lot of metrics with high cardinality. Usually, such metrics are additionally processed by recording rules, in order to apply some aggregation and remove extra cardinality. However, raw metrics continue to exist in the database using disk space and affecting index resources.

**Describe the solution you'd like**
Would be great to have an option similar to downsampling, where users can configure to remove certain metrics after some period of time. This would simplify topology described [here](https://docs.victoriametrics.com/vmalert.html#downsampling-and-aggregation-via-vmalert), where user needs to run two clusters: one for raw data and second for aggregated data for long-term storing.

**Describe alternatives you've considered**
Use topology described here https://docs.victoriametrics.com/vmalert.html#downsampling-and-aggregation-via-vmalert

**Comment by zekker6** [comment]
@hagen1778 should we close this as [retention filters](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#retention-filters) are available now?

**Comment by hagen1778** [comment]
Yes. I guess [retention filters](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#retention-filters) and [stream aggregation](https://docs.victoriametrics.com/stream-aggregation.html) significantly improve the described situation.
