### ISSUE TITLE
vmctl: The flag vm-native-step-interval does't work in 1.81.2

### ISSUE THREAD

**Issue by nimda7** [VictoriaMetrics/VictoriaMetrics#3088]
**Describe the bug**
The latest version of **vmctl** doesn't process the new flag **vm-native-step-interval**

**To Reproduce**
`./vmctl-prod vm-native --vm-native-src-addr=http://src_host:8428  \
  --vm-native-dst-addr=http://localhost:8428 \
  --vm-native-filter-match='{mylabel!=""}' \
  --vm-native-filter-time-start='2022-03-01T00:00:00Z' \
  --vm-native-filter-time-end='2022-04-01T00:00:00Z' \
  --vm-native-step-interval=hour`

Reply with error message
`2022/09/08 16:09:08 flag provided but not defined: -vm-native-step-interval`

**Expected behavior**
According to the code & documentation, this flag should work.

**Version**
```
./vmctl-prod -v

vmctl version vmctl-20220908-105941-tags-v1.81.2-0-gdd1126dcc
2022/09/08 16:02:39 Total time: 454.709µs
```

**Comment by zekker6** [comment]
Hi @nimda7!
According to release docs for [1.81.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.81.2) this release only contains bugfix for 1.81.1 version:
```
Released at 08-09-2022

    BUGFIX: [VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html): properly calculate query results at vmselect. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3067. The issue has been introduced in [v1.81.0](https://docs.victoriametrics.com/CHANGELOG.html#v1810).
```
This release was published urgently and documentation was updated a bit ahead of time.
This feature will be available in next release.

If you'd like to use it now you can use [this](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-build-from-sources) instruction to build from source.

**Comment by nimda7** [comment]
Thanks! I've built **vmctl** from the master branch and it did the trick!

**Comment by hagen1778** [comment]
Please note, documentation at https://docs.victoriametrics.com/ is always built from the master branch. So it could contain newly added features which weren't released yet.
