### ISSUE TITLE
vmselect is getting slower and slower over time

### ISSUE THREAD

**Issue by laixintao** [VictoriaMetrics/VictoriaMetrics#3097]
**Describe the bug**

We have massive numbers of containers, and we want to see the overall CPU usage, in order to see the metrics we have a dedicate vmalert cluster running with a dedicate vmselect cluster, run for only do the recording rules. interval=60s, it takes ~40s to run a query, that's ok for us as long as we can get the data.

Recently we found that some queries are timeout, and we lost recording data.

Then we found that the vmselect's latency is getting higher and higher over the time.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/9675939/189610415-5ded7e48-9213-43fe-bacd-d8c817be44a7.png">

(it's more clear if we do `avg` for all instances)

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/9675939/189610515-c28454a8-27b7-4f0f-9041-db563f74f089.png">

I open this issue and suspect cloud is a vmselect issue because, after restarting, the latency reduced...

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/9675939/189612346-30f0bba3-112b-465a-8a91-b00c82fe335b.png">

The rows scanned barely change:

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/9675939/189611376-12f216d9-e08d-4a37-a41e-3b2c8288d806.png">

Process CPU increased:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/9675939/189611713-96bccf71-ed40-40dc-89c6-75ef04562f5f.png">

RSS increased as well:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/9675939/189611775-8ffc2b4c-6bd7-42d4-926a-974424772a8e.png">

**To Reproduce**
Steps to reproduce the behavior.

Maybe you can set up a vmselect cluster, its only client is vmalert, and make some slow queries (take ~40s to finish). Not sure if it can reproduce.

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
vm_app_version{version="vmselect-20220808-174309-tags-v1.80.0-cluster-0-g91d0b4553", short_version="v1.80.0-cluster"} 1
```

(I have already upgrade 1/3 of them to 1.81.2 version, see if there are any differences in future days)

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components. 

systemd:

```
ExecStart=/opt/vmselect-shard-7/vmselect-prod  \
  -search.maxUniqueTimeseries "0" \
  -search.maxQueryDuration "60s" \
  -search.maxSamplesPerQuery 10000000000 \
  -storageNode abc:9421      \
  -httpListenAddr ":8007" \
  -cacheDataPath /data/vmselect-shard-7-cache-data
```

---
My personal guess: 

Cloud it be due to some memory leak or cache issue, the longer time the vmselect running, the more work it needs to do for every query?

That's all I have for now, I will update here if I have more information.

**Comment by hagen1778** [comment]
Thanks for detailed report. Memory usage by vmselect looks like a memory leak. I assume some of the caches grows constantly, which makes lookups slower and slower. We need to find out which cache causes the issue. Could you please attach memory profile of such vmselect at the moment when it consumes the most of memory? See how to collect the profile here https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#profiling

**Comment by laixintao** [comment]
[heap-dump.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/9573457/heap-dump.zip)

Here is one dumped file using golang pprof from a vmselect port

**Comment by hagen1778** [comment]
Thanks for pprof. I don't see anything suspicious in it. How long it worked since the last restart? How much more memory it started to use since the the last restart?

**Comment by laixintao** [comment]
Yes, memory dump looks good to as well,

It runs about 5 days, memory didn't incrase a lot this time, but our query time still get slower.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/9675939/190442375-2f065389-ff62-4317-b952-df1618957b2d.png">

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/9675939/190443419-5ff3eace-188b-4136-acfc-8a47bdb93272.png">


One another thing that I changed for this restarting(sorry can't afford data loss to keep the vmselect running as the exactly same condition as before) is, before we use one group of recording rules for 8 rules and concurrency is 200. Now we divide it into 2 groups, put the important ones (4 of them) into a single group(one heavy query like `sum(rate(cput_time[1m])) by (container_id)` which is slow and generates a lot of new metrics, stays at the same group; another less heavy one `sum(rate(cput_time[1m])) by (container_image)` which generates less metrics into another new group), concurrency is also 200, it runs faster.

Btw do you know 2 groups is faster than one group? according to the docs, even put all of them into single group, it should be same fast as 2 groups as the concurrency is far above the rule numbers, so I suppose each rule should own a thread to execute?

**Comment by hagen1778** [comment]
> Btw do you know 2 groups is faster than one group? 

That shouldn't be a case. With `concurrency > number of rules`, the evaluation duration should be equal to the evaluation of the slowest rule. You can easy verify it by introducing artificial delay for rules evaluation.

> so I suppose each rule should own a thread to execute?

Each rule is executed in a separate goroutine. And the main goroutine waits for all rules to finish - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/348467356631efe5004dd691ef6b5b7a94e91824/app/vmalert/group.go#L373-L400

Can you show vmselect's requests rate and number of concurrent selects ?

**Comment by laixintao** [comment]
Hi this is the request per minutes

<img width="948" alt="image" src="https://user-images.githubusercontent.com/9675939/190890631-fbdd6410-2d7d-406c-8cc5-bfdfa119dffa.png">

> And the main goroutine waits for all rules to finish

So I suppose dividing my rules into 2 groups didn't make it run faster, but the vmalert's metrics are measured per group, which means the slowest rule as the group execute duration? So it only "looks" faster from metrics but actual duration is the same.

**Comment by hagen1778** [comment]
> Hi this is the request per minutes

Thanks! Looks good. I was thinking maybe vmalert for some reason increases requests rate because of slow responses. But looks like everything is ok.

> So it only "looks" faster from metrics but actual duration is the same.

If you measure latency on vmselect, then it should be objective.

**Comment by armagg** [comment]
there is no update in this issue?

**Comment by laixintao** [comment]
Hi @armagg I didn't follow up on this issue.

I did serval upgrades after this happened, just checked again, seems the performance is stable now, thanks.
