### ISSUE TITLE
vmui: delete query icon can be misleading

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3101]
**Is your feature request related to a problem? Please describe.**
Icon for deleting the second query is placed on the same position as icon for execute the query. This confuses me and frequently results in situation where I delete the query instead of executing it. This is especially frustrating, because there is no easy way to return deleted query back.

**Describe the solution you'd like**
I'd like to change the way how extra query is added or removed. I see the following options:
1. Adding or removing the query can be placed on the bottom right border of the query field:
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/2902918/189738208-210b89fd-561a-4f98-b6df-bd8ca588cce6.png">
2. extra query could have its own Execute icon, so it won't mislead the user

**Comment by valyala** [comment]
This enhancement has been included in [vmui v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
