### ISSUE TITLE
Can't seem to recover specific alert after `the metric ALERTS has a timestamp older than ...`

### ISSUE THREAD

**Issue by johnalotoski** [VictoriaMetrics/VictoriaMetrics#3110]
**Describe the bug**
After an unexpected and random virtual machine reboot on which victoriametrics is running in standalone mode and it is powered back up, a single alert no longer works, and the logs indicate a timestamp exists outside of `search.cacheTimestampOffset`.  I have seen these VMs get system times which are significantly wrong (ie: hours) on initial reboot for a few minutes before the timeserver adjusts time correctly, so maybe this has to do with data being ingested during this small window.

Vmalert and alertmanager appear to no longer be getting the alert related to this metric and label (see log snippet below) with this cache issue.  This should be a one-time event, or at least rare, so I would like to reset the data to behave normally rather than permanently expand the cacheTimestampOffset, or disable it altogether.

I have tried the following, but the behavior show below in the logs continues:
* Restart victoriametrics service
* Tried a GET curl to `http://localhost:8428/internal/resetRollupResultCache`
* Tried a `reset_cache_on_startup` ala [issue#1447](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1447), verified the cache files were gone and restarted
* Deleted the time series "ALERT" with a call to the following URL
```
curl -v http://localhost:8428/api/v1/admin/tsdb/delete_series -d 'match[]=ALERTS'
```
* Temporarily modified the VM systemd service startup to include the option: `-search.cacheTimestampOffset='24h'` at which point victoriametrics stopped logging the timestamp offset errors, but normal alert activity did not resume (other alerts continue to work fine).  Upon removing this extended timestamp offset, the log errors return.

Short of purging all of victoriametrics state at this point, I'm not sure what else to do to get back to normal behavior.

Any suggestions appreciated.

**To Reproduce**
Randomly power off a virtual machine with victoriametrics running as a service and a system time that tends to have large slippage immediately after reboot for a short period before timeserver synchronization and see if you get [un]lucky.

**Expected behavior**
To recover from this scenario, or an option to recover from this scenario. (There may already be one that I'm just not aware of, short of purging all victoriametrics state).

**Logs**
```
Sep 14 13:37:23 monitoring victoria-metrics[995]: 2022-09-14T13:37:23.163Z        warn        VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:68        resetting rollup result cache because the metric ALERTS{alertgroup="bitte_deadmanssnitch",alertname="DeadMansSnitch",alertstate="firing",severity="critical"} (Timestamp=1663119614000, Value=1.000000) has a timestamp older than -search.cacheTimestampOffset=5m0s by 42728.000s

Sep 14 13:37:23 monitoring victoria-metrics[995]: 2022-09-14T13:37:23.163Z        info        VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:199        rollupResult cache has been cleared
```

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
> victoria-metrics --version
1.78.0
```

**Used command-line flags**
From systemd service:
```
ExecStart=/nix/store/0v4lc8ppykv0x16nzhga94s6y1ir4afi-VictoriaMetrics-1.78.0/bin/victoria-metrics \
  -storageDataPath=/var/lib/victoriametrics \
  -httpListenAddr=':8428' \
  -retentionPeriod='12' \
  -selfScrapeInterval='60s' \
  -vmalert.proxyURL='http://0.0.0.0:8880/vmalert-vm'
```

**Comment by johnalotoski** [comment]
...and after another random reboot beyond our control several hours later, the problem appears to have resolved itself.

We can probably close this ticket out, but will leave it open for the moment in case there are any suggestions we can try next time if this re-occurs.

**Comment by dmitryk-dk** [comment]
Close as resolved
