### ISSUE TITLE
VM losts metrics until i scale timeline

### ISSUE THREAD

**Issue by turbotankist** [VictoriaMetrics/VictoriaMetrics#313]
**Describe the bug**
VM doesn't show some metrics.

**To Reproduce**
sometimes VM stop get all labels and metrics witch were exists in prometheus.
To fix it I need to scale timeline to 90d and then query works fine

**Expected behavior**
Expected nice work.

**Screenshots**
for example - last 1h
![image](https://user-images.githubusercontent.com/9462236/74027384-0fbc5680-49b9-11ea-95ea-3bf4549e5bae.png)
then I scale time to 90 days (scaling to 30d and fewer does not work)
![image](https://user-images.githubusercontent.com/9462236/74027574-7f324600-49b9-11ea-8aa5-b1136f194e74.png)
then I can see this metrics with any time scale
![image](https://user-images.githubusercontent.com/9462236/74027677-a7ba4000-49b9-11ea-9f5d-1174cd2c8dd4.png)

**Version**
1.33.0
and early from 1.2x.x

**Additional context**
there are nothing in VM just increase number of timeserias in VM
![image](https://user-images.githubusercontent.com/9462236/74028029-79893000-49ba-11ea-8ff9-22e4176e9372.png)

**Comment by hagen1778** [comment]
Hello @turbotankist! Are the metrics backfilled or ingested in real-time? Which VM installation do you use: single-node or cluster?

**Comment by turbotankist** [comment]
VM is single-node.
I don't understand that you mean. Metrics writes in real-time from prometheus with remote-write configuration.

**Comment by valyala** [comment]
> I don't understand that you mean

VictoriaMetrics contains response cache, which may work incorrectly when writing data with timestamps older than 5 minutes from the current time. Read [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#backfilling) for more information. If Prometheus delays writing data to VictoriaMetrics for periods longer than 5 minutes, this may result in incomplete graphs as in your case. See [the related issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/287).

@turbotankist , could you provide additional info by answering the following questions?

* Did you modify `-search.latencyOffset` command-line flag value?
* Could you provide the command line used for starting VictoriaMetrics?
* Did you upgrade from version lower than v1.29 to newer version? The release [v1.29.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.29.0) introduced per-day inverted index, which can sometimes return invalid results. The following issue could be related - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/290 .

**Comment by turbotankist** [comment]
```
  - args:
    - -httpListenAddr=:8080
    - -storageDataPath=/storage
    - -retentionPeriod=2
    - -maxConcurrentInserts=64
    - -search.maxUniqueTimeseries=20000000
    - -memory.allowedPercent=30
    image: victoriametrics/victoria-metrics:v1.33.0
```
we upgraded VM from version lower than v1.29. So as in  issue - #290 - should we drop metrics collected with old version VM?

**Comment by valyala** [comment]
There is no need in deleting data collected with the previous version of VictoriaMetrics. Just stop VictoriaMetrics, delete `storage/cache` folder and then start VictoriaMetrics again. Then report here whether this helped resolving the issue.

**Comment by turbotankist** [comment]
I did it. 
So after 5 days all looks fine.
Thanks
