### ISSUE TITLE
Is the percentage limited by memory.allowedpercent based on the memory of the node or the memory of the pod?

### ISSUE THREAD

**Issue by qiu-peng20** [VictoriaMetrics/VictoriaMetrics#3143]
Is the percentage limited by memory.allowedpercent based on the memory of the node or the memory of the pod?

On a machine with 8G memory, I set the memory.allowedpercent of vm_storage to 30%. As expected, it should use 2.4G, but it actually uses 4G, why is this?

**Comment by Kuri-su** [comment]
check #406 please, same case

**Comment by hagen1778** [comment]
Closing as duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/406
