### ISSUE TITLE
vmbackup: retrying remote FS errors

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#3147]
**Is your feature request related to a problem? Please describe.**
When using vmbackup with remote storage it is possible to get partial backup due to error handling logic.
Currently, in case of error during backup (like a temporary network error) backup will exit with error message. This will leave backup in inconsistent state.
For example:
```
vmstorage-0 vmbackuper 2022-09-22T12:01:48.155Z    error   VictoriaMetrics/app/vmbackupmanager/main.go:193 error creating hourly backup: cannot create backup: cannot copy part{path: "data/small/2021_09/20038748_61212_20210922000417.370_20210925235959.993_17133CF6D6C53806/values.bin", file_size: 1311303
5, offset: 0, size: 13113035} from origin GCS{bucket: "some-backup", dir: "some-backup/vmstorage-0/latest/"} to dst GCS{bucket: "", dir:
 "some-backup/vmstorage-0/hourly/2022-09-22:11/"}: cannot copy "data/small/2021_09/20038748_61212_20210922000417.370_20210925235959.993_17133CF6D6C53806/valu
es.bin" from GCS{bucket: "some-backup", dir: "some-backup/vmstorage-0/latest/"} to GCS{bucket: "some-backup", dir: "some-backup/vmstorage-0/hourly/202
2-09-22:11/"}: googleapi: Error 504: , gatewayTimeout
```

**Describe the solution you'd like**
Implementing retry policy for remote FS calls would significantly reduce a chance of having inconsistent backup created.
Also, it might be great to make backup upload more atomic, either upload successful or delete uploaded data.

**Comment by valyala** [comment]
`vmbackup` and `vmrestore` should retry failed [GCS operations](https://cloud.google.com/storage) for up to 3 minutes starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
