### ISSUE TITLE
VMUI custom panel table show value outside of screen

### ISSUE THREAD

**Issue by TomasVojacek** [VictoriaMetrics/VictoriaMetrics#3153]
VMUI in table view show tags only but value is missing.
Tested in firefox
on dbaas.victoriametrics.com
version v1.81.2-enterprise and v1.76.1-enterprise
result of "up" does not show value at all
result of "tlast_over_time(up)" show 16638 and rest is outside screen.

![image](https://user-images.githubusercontent.com/49019244/191922341-de3aeb87-0e65-4a96-b23d-c28e6d3ec229.png)

**Comment by dmitryk-dk** [comment]
Hi @TomasVojacek ! Thank you for your issue. Can you share an image of the problem, please?

**Comment by valyala** [comment]
@Loori-R , could you look into this issue?

**Comment by valyala** [comment]
This issue has been fixed in [VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
