### ISSUE TITLE
Support hetzner_sd_config

### ISSUE THREAD

**Issue by kkornienko-aparavi** [VictoriaMetrics/VictoriaMetrics#3154]
**Describe the solution you'd like**
It would very helpful if VMagent supported Hetzner SD discovery like Prometheus does.

**Describe alternatives you've considered**
We're currently using an additional instance with Prometheus to discover Hetzner instances

**Additional context**
Hetzner is a quite popular cloud solution, looks like this feature will be in demand.
And thanks a lot for your product!

**Comment by mhutter** [comment]
:+1: , I'm running a Prometheus just for that

**Comment by valyala** [comment]
The support for `hetzner_sd_configs` has been added via the pull request https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5550 . This pull request will be included in the next release.

In the mean time it is possible to build `vmagent` from the commit 74448a7e5721a209db49aac34acbaa462be98c0d according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether `hetzner_sd_configs` works as documented [here](https://docs.victoriametrics.com/sd_configs.html#hetzner_sd_configs).

**Comment by valyala** [comment]
FYI, VictoriaMetrics supports [hetzner_sd_configs](https://docs.victoriametrics.com/sd_configs.html#hetzner_sd_configs) starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as done.
