### ISSUE TITLE
VMUI: limit number of plotted series in return

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3155]
**Is your feature request related to a problem? Please describe.**
Sometime, query can return more series than user expects, which could negatively affect the browser or even crash it. 

**Describe the solution you'd like**
Would be great to artificially limit the number of plotted series in the VMUI by some fixed number. For example, by 100.

cc @Loori-R

**Comment by valyala** [comment]
vmui limits the number of plotted series starting from [v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
