### ISSUE TITLE
vmagent Integration with NATS

### ISSUE THREAD

**Issue by iliesh** [VictoriaMetrics/VictoriaMetrics#3166]
Will be handy if vmagent will have a direct integration with NATS system (https://nats.io/), for example something like: -remoteWrite.url=nats:127.0.0.1:9000

**Comment by hagen1778** [comment]
Hi @iliesh! Could you please describe in more details for which scenario you'd need such an integration?

**Comment by iliesh** [comment]
Hi @hagen1778, the idea was to create a sort of HA for the vmstorage service by using NATS cluster. In our case, we have 3 vmstorage services on 3 different servers and very low traffic (~20req/sec). 

<img width="685" alt="image" src="https://user-images.githubusercontent.com/14953151/192821487-5054588b-f2a4-456a-ac5c-1984e34f1c4a.png">

We don't want to lose any data in case one vmstorage is going down. Let's say if one vmstorage is going down (server crash, maintenance, etc) then nginx/haproxy will re-route all requests to another vmstorage and users won't be affected. But, when that vmstorage will come back online after a certain period of time and nginx/haproxy will route all requests back to it then users won't be able to see the data as it's missing from that vmstorage and there is no data replication between them. 
One workaround would be to keep nginx/haproxy to the same vmstorage even if the main one came back, or to use the vmcluster which already has replication embedded but I'm not sure that it's the best choice for our amount of traffic. But, as we already have NATS cluster in production I was thinking to use it as a temporary storage and when the vmstorage is coming back, NATS subscriber will pull all data from the cluster and push it into the vmstorage. 

I just started to deep into victoriametrics and maybe missing some details on how to achieve this in a better way.

**Comment by hagen1778** [comment]
Thanks for the detailed answer!

> a direct integration with NATS system (https://nats.io/)

I'm not sure how this would work, maybe my understanding of NATS is incomplete. Vmagent sends data in Prometheus remote-write protocol. So NATS server supposed to be able to accept the data, proxy it to the remote storage (vmstorage), or, in case of unreachable remote storage, buffer the data and retry later.

Actually, what I described above is already provided by vmagent itself. It collects the data, proxies it to configured storages, and can buffer data to the local disk in case if remote storage is unreachable. The size of buffer is limited by disk space only. Vmstorage keeps independent buffers for each configured remote-storage, so when 1 out of 3 storages goes off - vmagent continues to deliver data to the rest. And once 1st storage comes back - vmagent will backfill the data by draining the buffer queue.

> I just started to deep into victoriametrics and maybe missing some details on how to achieve this in a better way.

Another way to approach this is to make use of [replication support](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety). With this approach each vmstorage will store duplicates of data, but if one of them will go off - the rest will be able to serve the missing data.

**Comment by iliesh** [comment]
> Actually, what I described above is already provided by vmagent itself. It collects the data, proxies it to configured storages, and can buffer data to the local disk in case if remote storage is unreachable. The size of buffer is limited by disk space only.

That's exactly what I need actually, thank's a lot @hagen1778
