### ISSUE TITLE
VMUI: no way to add more than 2 queries

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [VictoriaMetrics/VictoriaMetrics#3169]
VMUI interface allows to add only one additional query, after what "add" button disappears.
But VMUI itself allows to have more than 2 queries via editing URL - adding extra `&g2.expr=...&g3.expr=...`.
It would be nice to have explicit "add" button for this.
VicrtoriaMetrics - single, 1.81.2 (victoria-metrics-20220908-105456-tags-v1.81.2-0-gdd1126dcc)

![image](https://user-images.githubusercontent.com/22332263/192352867-122fe6be-61ec-410b-89d9-c6dd385b54ed.png)

**Comment by hagen1778** [comment]
I think it would be great to add more queries but with a hard limit of 4, for example. The workaround for adding more queries via URL needs to be fixed :-) 
cc @Loori-R

**Comment by valyala** [comment]
[vmui](https://docs.victoriametrics.com/#vmui) supports up to 4 distinct queries starting from [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

**Comment by valyala** [comment]
FYI, [VictoriaMetrics v1.82.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) properly removes lines from the graph as soon as the corresponding query is removed from vmui.

**Comment by thomas725** [comment]
can I ask why this limit has been increased to 4 instead of removed entierly? why for example not 10 queries in a single graph?

**Comment by Loori-R** [comment]
We believe that this is the best option between performance and UI. Can you show a working example with 10 requests?

We abandoned multiple axes as it was confusing (especially for more than two requests). 
As a solution, we can add a switch to display queries on separate charts (as done in the [Prometheus demo](https://prometheus.demo.do.prometheus.io/graph?g0.expr=1&g0.range_input=30m&g0.end_input=2022-10-30T07%3A48%3A46&g0.step_input=6.097&g0.tab=0&g0.relative_time=last_30_minutes&g1.expr=2&g1.range_input=30m&g1.end_input=2022-10-30T07%3A48%3A46&g1.step_input=6.097&g1.tab=0&g1.relative_time=last_30_minutes))
You can also suggest your solution.

**Comment by thomas725** [comment]
Well I'm currently in the research phase for replacing my IO-Broker + MySQL smart-home solution. The most complex Graph I've setup with that looks like this:
![image](https://user-images.githubusercontent.com/68635351/200166840-10969dfb-c54d-471d-8593-e5a92e810bb0.png)

This has both quite a few more lines than 4 and also two separate axes and is very useful for me.

Though I guess I should check out separate tools from the VictoriaMetrics included VMUI for displaying my data, maybe that Grafana I've seen mentioned at quite a few places.

**Comment by hagen1778** [comment]
Hi @thomas725! Grafana is far more flexible in terms of plotting graphs and dashboards. That's the main purpose of Grafana. VMUI in VictoriaMetrics is for ad-hoc queries, verifying theories, and checking what's happening right now. VMUI doesn't replace Grafana, it just makes it possible to live without it. But when going serious with plotting complex dashboards with version and access control - Grafana is the best I know so far.
