### ISSUE TITLE
[lib/awsapi] Space character is encoding wrong when create a canonical request.

### ISSUE THREAD

**Issue by csf-andyliao** [VictoriaMetrics/VictoriaMetrics#3171]
**Describe the bug**

I move from Prometheus to VictoriaMetrics. VM always get "Auth Failure" response when call AWS EC2 api.
I found the url in the log as below.

```
https://ec2.ap-northeast-1.amazonaws.com/?Action=DescribeInstances&Filter.1.Name=instance-state-name&Filter.1.Value.1=running&Filter.2.Name=tag%3AName&Filter.2.Value.1=V2+Redis&Version=2013-10-15
```

And here is my ec2_sd_config example.

```
filters:
   - name: instance-state-name
     values:
        - running
   - name: tag:Name
     values:
        - V2 Redis
```

I reported this problem in Slack. Thanks to Dima had informed me to check your code for serializing tags.
Finally, I found this line in your code may have different encoding result from [AWS Doc - Step 3.b](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html) said.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6411bbcce7fa98333686d6818f841f78da444f31/lib/awsapi/sign.go#L43

```
URI-encode each parameter name and value according to the following rules:

Do not URI-encode any of the unreserved characters that [RFC 3986](https://tools.ietf.org/html/rfc3986) 
defines: A-Z, a-z, 0-9, hyphen ( - ), underscore ( _ ), period ( . ), and tilde ( ~ ).

Percent-encode all other characters with %XY, where X and Y are hexadecimal characters (0-9 and uppercase A-F). 
For example, the space character must be encoded as %20 (not using '+', as some encoding schemes do) and extended UTF-8 characters must be in the form %XY%ZA%BC.

Double-encode any equals ( = ) characters in parameter values.
```

**To Reproduce**
Please use example ec2_sd_config as above.

**Expected behavior**
Get success EC2 response.

**Logs**
None. System Log will rotating per day to reduce disk usage.

**Screenshots**
None.

**Version**
Installed from snap.
`victoria-metrics-20220908-121810-v1.81.2-0-gdd1126d-dirty-da39a3ee`

**Used command-line flags**
-retentionPeriod=6

**Comment by valyala** [comment]
The bugfix for this issue has been included in [VictoriaMetrics v1.79.4 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.4).

**Comment by valyala** [comment]
[vmagent](https://docs.victoriametrics.com/vmagent.html) and [single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) should properly encode space char when performing service discovery requests to AWS starting from [the release v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing the issue as fixed.

**Comment by csf-andyliao** [comment]
I upgrade to new version 1.82.0 and confirm it can get success response from AWS. Thank you.
