### ISSUE TITLE
TLS certificate over vminsertAddr and vmselectAddr ports

### ISSUE THREAD

**Issue by diegofdog** [VictoriaMetrics/VictoriaMetrics#3175]
According to docs, enabling TLS in Vmstorage component allows to secure, for example, HTTP 8482 port by providing a certificate and keyfile by means of -tlsCertFile and -tlsKeyFile flags.

Is it possible to do something similar in the port used to write samples and also in the one used to perform queries (8400 and 8401 by default)? If not, what is recommended to secure these ports?

**Comment by hagen1778** [comment]
Hello! Can the following doc be relevant for you https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html?highlight=mtls#mtls-protection ?

**Comment by diegofdog** [comment]
I think that's exactly what I was looking for. Thanks
