### ISSUE TITLE
Different numbers in the same time series are returned for different time periods

### ISSUE THREAD

**Issue by achin-netskope** [VictoriaMetrics/VictoriaMetrics#3184]
**Describe the bug**
When running the same query returning just one time series for different time intervals on grafana, returns different numbers.

When queried over 2 days - the actual values are seen, 
<img width="1294" alt="Screen Shot 2022-09-29 at 2 30 41 PM" src="https://user-images.githubusercontent.com/51725761/193149020-21856720-52a9-467a-a2a5-06ef44d70741.png">

But when you query it over 3 days, only zeroes are returned.
<img width="1307" alt="Screen Shot 2022-09-29 at 2 29 03 PM" src="https://user-images.githubusercontent.com/51725761/193149075-b5447149-188c-4701-b15f-b2384469633e.png">

It would be great to [upgrade](https://docs.victoriametrics.com/#how-to-upgrade) 
to [the latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
and verify whether the bug is reproducible there.
It's also recommended to read the [troubleshooting docs](https://docs.victoriametrics.com/#troubleshooting).

**To Reproduce**
Not reproducing with other time series.

**Expected behavior**
Return same numbers always.

**Logs**
Grafana logs
```
logger=context traceID=00000000000000000000000000000000 userId=3 orgId=1 uname=achin.gupta@netskope.com t=2022-09-29T21:57:26.54+0000 lvl=info msg="Request Completed" method=POST path=/api/datasources/proxy/1572/api/v1/series status=200 remote_addr=108.226.162.181 time_ms=10 duration=10.364941ms size=460 referer="https://xxxx.io/xxxx/d/xxxx/victoriametrics-alerting?xxxxxxxx" traceID=00000000000000000000000000000000

logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-09-29T21:57:27.7+0000 lvl=info msg="Request Completed" method=GET path=/api/datasources/proxy/1176/query status=200 remote_addr=34.82.49.93 time_ms=72 duration=72.567332ms size=2314 referer= traceID=00000000000000000000000000000000

logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-09-29T21:57:31.5+0000 lvl=info msg="Request Completed" method=GET path=/api/datasources/proxy/942/query status=200 remote_addr=34.151.104.68 time_ms=69 duration=69.247195ms size=63290 referer= traceID=00000000000000000000000000000000

logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-09-29T21:57:32.06+0000 lvl=info msg="Request Completed" method=GET path=/api/datasources/proxy/549/query status=200 remote_addr=34.107.11.124 time_ms=24 duration=24.140841ms size=57 referer= traceID=00000000000000000000000000000000

logger=context traceID=00000000000000000000000000000000 userId=3 orgId=1 uname=achin.gupta@netskope.com t=2022-09-29T21:57:32.64+0000 lvl=info msg="Request Completed" method=POST path=/api/datasources/proxy/1572/api/v1/series status=200 remote_addr=108.226.162.181 time_ms=8 duration=8.497083ms size=460 referer="https://xxxxx/xxxx/d/xxxxxx/victoriametrics-alerting?xxxx" traceID=00000000000000000000000000000000

logger=context traceID=00000000000000000000000000000000 userId=3 orgId=1 uname=achin.gupta@netskope.com t=2022-09-29T21:57:32.66+0000 lvl=info msg="Request Completed" method=POST path=/api/datasources/proxy/1572/api/v1/series status=200 remote_addr=108.226.162.181 time_ms=30 duration=30.374257ms size=38206 referer="https://xxxxxxx/xxxxxxx/d/xxxxxxxxxx/victoriametrics-alerting?xxxx" traceID=00000000000000000000000000000000
```

vmselect and vmstorage are clear.

**Screenshots**
Added above

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
/ # /vmstorage-prod --version
vmstorage-20220908-111837-tags-v1.81.2-cluster-0-ge9a0b803a
```
```
/ # /vminsert-prod --version
vminsert-20220908-111625-tags-v1.81.2-cluster-0-ge9a0b803a

```

Grafana version v.8.5.2
Victoria version 1.81.2

**Comment by hagen1778** [comment]
Hello! It is not clear from the description whether you've followed [troubleshooting docs](https://docs.victoriametrics.com/#troubleshooting).

**Comment by achin-netskope** [comment]
@hagen1778 
I had not followed the troubleshooting docs. Thank you for the link. I read them and crosschecked. Logs are clean and I do not see any errors anywhere in the pipeline. There is ample amount of resources dedicated to the cluster as well.

Is there a specific troubleshooting step you would like to see the output of ? I can send you right away. 

Thanks for helping out.

**Comment by hagen1778** [comment]
Ok, tx. Looks like I actually sent the wrong link. My bad, I'm sorry.
The right link is https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results
I'd specifically pay attention to steps 3, 4 and 5. But all steps are important to read.

**Comment by valyala** [comment]
@achin-netskope , try upgrading to [the latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and verifying whether this fixes the issue. See [the full changelog](https://docs.victoriametrics.com/CHANGELOG.html) for details on what's changed since the release you run.

**Comment by achin-netskope** [comment]
Appreciate the help @valyala and @hagen1778 
We have not seen this problem since we upgraded. Currently we have `1.87.1` running.
I will close this now as fixed.
