### ISSUE TITLE
Feature Request: Append other alert labels to vmalert_alerts_firing gauge

### ISSUE THREAD

**Issue by r0fls** [VictoriaMetrics/VictoriaMetrics#3193]
**Is your feature request related to a problem? Please describe.**
It would be helpful if the `vmalert_alerts_firing` metric included the other labels that are on the alerts. The use case is that we typically have a single alert on, let's say something like CPU utilization, but it has additional labels e.g. the environment (qa, prod, etc). Anyway, right now I see a metric coming through showing the count of the different alerts firing, but none of this additional metadata, which would be extremely helpful. Here is a code snippet that seems to be relevant:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/alerting.go#L94-L105

**Describe the solution you'd like**
Every label associated with the firing alert appended to the labels on the `vmalert_alerts_firing` metric

**Describe alternatives you've considered**
Having a separate alert for each environment. However this would result in significant code reuse, if the resulting action (e.g. slack alert, pagerduty page) are the same on some environments (which they typically are).

**Additional context**
I can provide additional context as needed

**Comment by hagen1778** [comment]
Hello! vmalert already does what you ask but in a different way - it [writes a time series](https://docs.victoriametrics.com/vmalert.html#alerts-state-on-restarts) named `ALERTS` to the configured `-remoteWrite.URL`. There you'll have all alert labels included.
The metric `vmalert_alerts_firing` is only needed for technical state purposes. I.e. to correlate if vmalert has active alerts but no notifications were received by consumers.

**Comment by r0fls** [comment]
Ah ha, thank you! I see that metric has all the data I need 🙏
