### ISSUE TITLE
Label rewrites/metric rewrite configs

### ISSUE THREAD

**Issue by AeroNotix** [VictoriaMetrics/VictoriaMetrics#320]
**Is your feature request related to a problem? Please describe.**
When using for example victoriametrics as the storage backend for a (legacy) influxdb set up - where it's difficult to modify metric sources to change/reduce the metrics they are sending, it would be very useful for VictoriaMetrics to include similar features to prometheus such that we can ignore specific metrics on ingest.

**Describe the solution you'd like**
The same features as prometheus where I can write a `metric_relabel_configs` block and ignore specific metrics.

**Describe alternatives you've considered**
I considered a tiered approach where instead of writing from influx, to victoria directly, I would instead write from influx, to prometheus, where some relabel configs could be applied and then on to victoria metrics.

I didn't actually set this up because it feels extremely wasteful - but if needs be then I can investigate it for the short-term.

**Comment by valyala** [comment]
@AeroNotix , thanks for the feature request! It looks useful.

This task will be solved by the upcoming `vmagent` component. This component will accept data via all the ingestion protocols supported by VictoriaMetrics and proxy it to VictoriaMetrics. The component will support metrics relabeling with [relabel_configs from Prometheus](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config).

**Comment by AeroNotix** [comment]
Are there any tickets regarding `vmagent`? Had a quick look through.

**Comment by valyala** [comment]
There is no a dedicated ticket for `vmagent` component yet. There is only a comment at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/260#issuecomment-565014679 , which describes its functionality.

**Comment by valyala** [comment]
@AeroNotix , the first release of vmagent has been published - see https://github.com/VictoriaMetrics/VictoriaMetrics/releases . See vmagent docs at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md

**Comment by AeroNotix** [comment]
Thanks! Will look about deploying a canary build of vmagent to replace a prometheus instance which essentially is just used for scraping/rewrite/remoteWrite.

**Comment by valyala** [comment]
@AeroNotix , `vmagent` gained support for per-remote storage relabeling via `-remoteWrite.urlRelabelConfig` starting from [v1.34.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). I think the feature request can be closed now as done. Feel free re-opening it if you need additional functionality related to this feature request.

**Comment by AeroNotix** [comment]
You lot don't mess around! Thanks so much. Will be making use of this soon. Thanks again.
