### ISSUE TITLE
Sending data to VictoriaMetrics as a influxdb client

### ISSUE THREAD

**Issue by ozn0417** [VictoriaMetrics/VictoriaMetrics#321]
Im trying to store data in VictoriaMetrics that would normally be written to a influx db (so that I can  leverage the promql in grafana and use the extensive benefits of VictoriaMetrics over influxdb).  Im still evaluating if its the right choice.
I've tried the the influx cli ([InfluxDB line protocol](https://victoriametrics.github.io/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf)) and looks good but I have bunch of Python code that uses python influxdb client that sends to an existing influx db.
I have few questions pertaining to my intended usage:

- Traditionally with influxdb I need to specify a database but if I were to inject data to a VictoriaMetrics I'm guessing there is no database?
- The influxdb line protocol is not the same as using a influx db client?
- When I tried to use curl influx line protocol, I don't see those metrics as under "<victoriametrics>:8428/metrics" but am I am able to identify it with other prometheus "/api/v1/query..." APIs (also in grafana).  Is this expected?
- VictoriaMetrics stores as 0 (int) for values that would be a string (ex: if I were to store <metric>;tag=<> value="hello").  Im guessing this is to work properly with promQL?
- To confirm, I don't think I could configure VictoriaMetrics as a influxdb Grafana datasource?

Im trying to see if I need to update my client to work with Victoria Metrics (where I write my http client instead of using the influxdb python package).

**Comment by hagen1778** [comment]
Hello @ozn0417! Pls see some details about influx protocol here - https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf

Answering your questions:
* Correct, there no such entity as `database` in VM data model. But if you send `db` as a param according to [influx HTTP API](https://docs.influxdata.com/influxdb/v1.7/tools/api/#write-http-endpoint) - it would be added as a label `db` to every inserted timeseries.
* Can't say for sure. I guess it depends on client implementation.
* The endpoint `":8428/metrics"` is for VM system metrics, like it's health, number of stored datapoints, number of connections etc. I'd say it is similar to `show stats` query in influxdb. 
For querying user metrics (e.g. ingested via Influx protocol) pls see following [link](https://github.com/VictoriaMetrics/VictoriaMetrics#prometheus-querying-api-usage)
* VM stores only numeric values for fields, strings are not supported. This is compatible with [Prometheus data model](https://prometheus.io/docs/concepts/data_model/).
* VM has it's own query language [MetricsQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL). It is compatible with [PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/), hence in Grafana use [Prometheus datasource](https://prometheus.io/docs/visualization/grafana/) for querying from VM.

**Comment by ozn0417** [comment]
I see.  Thanks for the quick response.
Question on the ":8428/metrics".  I assumed this is what grafana uses to get all the metric names (like when I start writing a query in the grafana query box).  I see there are other APIs (metadata, series, ...) that list all the metric names but it looks like I need to provide a filter.  I'll try to find something that gives me all (active and inactive) the available metrics available in Victoriametrics.

**Comment by hagen1778** [comment]
>  this is what grafana uses to get all the metric names

It's not true. Grafana queries `/api/v1/label/__name__/values`, `/api/v1/labels` and `/api/v1/label/<name>/values` to get the metric names and labels for autocompletion - see [this code for details](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/datasource.ts#L490). This endpoint [supported](https://github.com/VictoriaMetrics/VictoriaMetrics#prometheus-querying-api-usage) by VM as well, so it should work as expected.

> something that gives me all (active and inactive) the available metrics available in Victoriametrics

In Grafana type query `{__name__=~".*"}` - this returns all timeseries. Caution, if you have a lot of metrics stored in VM - Grafana may hang your browser trying to plot them all.
Another options is to export timeseries from VM - [see link for details](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-export-time-series).

The endpoint ":8428/metrics" is for system metrics and used only for monitoring VM health state. Pls see more about VM monitoring [here](https://github.com/VictoriaMetrics/VictoriaMetrics#monitoring).

Please join our slack community so you can ask and get responses faster. The github is mostly an issue/feature request tracker.

**Comment by ozn0417** [comment]
Thanks, I ended up using the `{__name__~=".*"}` yesterday.  Thanks for your quick response, very helpful.
