### ISSUE TITLE
vmagent externalLabels override the same labels scraped from targets

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#3215]
If  vmagent externalLabels  contain same labels as target, target values rewrited

in prometheus duplicate labels renamed with **exported_** prefix

externalLabels = "cluster=production-k8s"

prometheus 

ex:
`cassandra_stats{cluster="resizer",datacenter="datacenter1",keyspace="",table="",name="org:apache:cassandra:metrics:threadpools:internal:perdiskmemtableflushwriter_0:pendingtasks:value",} 0.0`

```
cluster="production-k8s",exported_cluster="resizer", 
```
vmagent 

```
cluster="production-k8s" 
```

**Comment by valyala** [comment]
@nevlkv , thanks for filing the issue! Which version of vmagent do you use?
vmagent should add `exported_` prefix to labels with conflicting names for external labels as Prometheus does. This is the case when the external labels are defined in the `global->external_labels` section of `-promscrape.config` file according to [the specification](). vmagent allows adding additional labels to the collected metrics via `-remoteWrite.label` command-line option and via relabelimg - see [these docs](https://docs.victoriametrics.com/vmagent.html#adding-labels-to-metrics). In these cases the original conflicting metric labels are replaced by the specified labels. 

@f41gh7 , probably you know more specifics on how does VictoriaMetrics operator handle the provided `externalLabels` option.

**Comment by nevlkv** [comment]
version - v1.81.2

I know about *exported_*  prefix and *honor_labels*, i migrate from prometheus with same config and expect identical metrics and labels  

I try with global section

**Comment by nevlkv** [comment]
resolve using `global->external_labels`
