### ISSUE TITLE
Warning when templating ENV variables left unparsed values.

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#3216]
**Is your feature request related to a problem? Please describe.**
Exiting ENV templating behaviour leaves variables without matched ENV replacement as is (e.g. as `%{MY_VAR}` in configuration file.
This leads to unclear error messages when this value is used further, for example for URL parsing:
```
error when parsing `static_configs` target "%{MY_VAR}:8429" for `job_name` "vmagent": invalid url "http
://%{MY_VAR}:8429/metrics" for scheme="http" ("http"), target="%{MY_VAR}:8429" ("%{MY_VAR}:8429"), metrics_path="/metrics" ("/metrics") for `job_name` "vmagent": parse "http://%{MY_VAR}
:8429/metrics": invalid URL escape "%{M"; skipping it
```
In environments where ENV configuration is configured outside component deployment it makes it harder to find misconfigurations due to unclear error messages. 

**Describe the solution you'd like**
It would be great if there was a log with warning saying that there are unmatched template patterns left without matching ENV variable.

**Comment by valyala** [comment]
All the VictoriaMetrics components should emit errors and stop immediately if they encounter environment variable reference inside their configs, which is missing in environment variables, starting from [v1.83.0](https://docs.victoriametrics.com/CHANGELOG.html) (see [this commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/069401a304462365a2bc8ec9259e081e43ff466a) ). For example, if the file pointed by `-promscrape.config` contains `%{FOO_BAR}` reference and there is no `FOO_BAR` environment variable when starting [vmagent](https://docs.victoriametrics.com/vmagent.html), then the `vmagent` will stop with the `cannot expand environment vars` error message.

Closing this feature as done then.
