### ISSUE TITLE
vminsert 1.33.1 performance regression

### ISSUE THREAD

**Issue by johnatannvmd** [VictoriaMetrics/VictoriaMetrics#322]
**Describe the bug**
We use the cluster version of VictoriaMetrics. 3 nodes(insert, select, storage)

Version: 1.33.1

rows insert rate around 12k per inserter, 40k in total. After some time inserter became unresponsive. Even metrics(/metrics) gathering fails. We run it in the Kubernetes cluster with huge limits for inserters, CPU: 4, MEM: 4G. No OOM events in logs. According to the dashboard CPU sticks around 250ms. Max memory usage 1.7GB(allowedPercent = 80 from 4GB)

Btw inserters version **1.30.4** works flawlessly under the same kind of load. With less CPU(150ms) usage and less MEM(800MB, with the same parameters) usage.

**Used command-line flags**
vminsert flags
```
flag "enableTCP6" = "false"
flag "graphiteListenAddr" = ""
flag "http.disableResponseCompression" = "false"
flag "httpListenAddr" = ":8480"
flag "influxMeasurementFieldSeparator" = "_"
flag "influxSkipSingleField" = "false"
flag "loggerLevel" = "INFO"
flag "maxConcurrentInserts" = "96"
flag "maxInsertRequestSize" = "33554432"
flag "maxLabelsPerTimeseries" = "30"
flag "memory.allowedPercent" = "80"
flag "opentsdbHTTPListenAddr" = ""
flag "opentsdbListenAddr" = ""
flag "rpc.disableCompression" = "false"
```

**Comment by valyala** [comment]
@johnatannvmd , thanks for the bug report!

Could you try other releases between `v1.30.4` and `v1.31.1` in order to detect the first release where the issue has been introduced?

I'd also recommend returning back `-memory.allowedPercent` to default value unless you have important reason to increase it. Default value for `-memory.allowedPercent` should work well in the majority of cases. See [troubleshooting section](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#troubleshooting) for more info.

**Comment by valyala** [comment]
@johnatannvmd , are there any updates on this issue from your side?

**Comment by johnatannvmd** [comment]
I'm sorry for the delay. This issue was connected with wrongly configured Kubernetes cluster(ipvs in particular). After changing some sysctl configs everything works fine. And after 1.5 weeks inserters continue to work without a hassle.

So I conclude that high resource usage and reboots connected with poor networking stack.

**Comment by valyala** [comment]
Thanks for the update!

**Comment by davidsome** [comment]
is it a bug? whick version has been fixed?

**Comment by valyala** [comment]
@davidsome , it looks like this isn't a bug as @johnatannvmd explained in the comment https://github.com/VictoriaMetrics/VictoriaMetrics/issues/322#issuecomment-592532078 .
