### ISSUE TITLE
vmui: fix resize browser button maps

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#3239]
Hi,
Please, fix resolution of the buttons, when I scale down browser window then the buttons are not shown up
Example
![image](https://user-images.githubusercontent.com/70581130/196003349-1a53925b-f420-4e92-b5fa-e4f36d3551a1.png)
decrease browser wide size
![image](https://user-images.githubusercontent.com/70581130/196003388-2117bc6c-11ab-41ac-81bb-93913a0b53a0.png)

**Comment by yuriydzobak** [comment]
Note:
it helps reload the web page

**Comment by valyala** [comment]
`vmui` should properly show its controls on small screens starting from [v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as fixed then.

@yuriydzobak , feel free re-opening this issue or creating new one if you see improper rendering in `vmui` v1.83.0
