### ISSUE TITLE
vmui: Memory optimization

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#3240]
Hi,
VMUI uses a lot of memory when you run query has a lot entries and browser is stuck
That's why i'm still using promxy
Example promxy(prometheus ui)
![iScreen Shoter - 20221015220454435](https://user-images.githubusercontent.com/70581130/196004220-c3e56f18-b6b1-4e08-969e-ac3fcc7fe8ed.jpg)
![iScreen Shoter - 20221015220734171](https://user-images.githubusercontent.com/70581130/196004311-fa4da602-88f4-4240-8d3c-425594c8ce1c.png)
![image](https://user-images.githubusercontent.com/70581130/196004587-c99b6e9d-92f2-4e54-a095-9c381163c984.png)

Example VMUI
Just load `up`
![iScreen Shoter - 20221015220837637](https://user-images.githubusercontent.com/70581130/196004324-aceda544-65b2-4b67-8ef8-a36efd9a894d.jpg)

![iScreen Shoter - 20221015221627926](https://user-images.githubusercontent.com/70581130/196004330-e97bcbe6-ac56-467b-aff6-348454a93a6e.jpg)

when i'm switching from graph to table it seems doesn't clean memory, i don't know
![iScreen Shoter - 20221015221722537](https://user-images.githubusercontent.com/70581130/196004354-d8a23221-3946-4542-8193-6cf7956b612a.jpg)

right now the VMUI is very laggy and it doesn't possible to use, because all time the browser crashes 

I've tried chrome,safari,firefox, but any browser crash
If the metrics have for example 10k entries then it can't load =)
I don't know how Prometheus UI is optimized but it works faster and uses fewer resources.

**Comment by valyala** [comment]
@yuriydzobak , could you verify whether `vmui` uses less CPU and RAM starting from [v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by Loori-R** [comment]
I created [issue #3297](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3297) for setting limits.
We will also continue to optimize CPU and RAM usage.

**Comment by yuriydzobak** [comment]
FYI
this problem exists for `json` block too, because there is not limit

**Comment by yuriydzobak** [comment]
i forgot to mention json block has limit as well, was add in a some old release VM
Close, the issue as resolved
Thank you!
