### ISSUE TITLE
vmui: Improve table view

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#3241]
Hi,
VM version is 1.82.1
When the same metrics has a lot labels it doesn't usefully to use table mode.
Could be somehow optimize or make like promethues does?
![image](https://user-images.githubusercontent.com/70581130/196004775-d85c80bf-4c9b-491b-9465-528ca44d0555.png)

I know VMUI has table settings but it doesn't usefully because you have to scroll horizontally each time to find metrics or etc
![image](https://user-images.githubusercontent.com/70581130/196004814-18357b97-f916-4d9e-8974-97a57bf9b3a9.png)

When i'm opening Prometheus i can easy find the label, VMUI is pain for me 
thanks

**Comment by valyala** [comment]
`vmui` gained compact table view starting from [VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
