### ISSUE TITLE
Add value "for" as a variable

### ISSUE THREAD

**Issue by PavelKolobaev** [VictoriaMetrics/VictoriaMetrics#3246]
**Is your feature request related to a problem? Please describe.**
We can use $labels.alertname to create message templates, but we cannot use $labels.for.

**Describe the solution you'd like**
Please add $labels.for

**Additional context**
vmalert v1.72.0

**Comment by hagen1778** [comment]
@PavelKolobaev `for` support was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3474 and will be included to the next release.

**Comment by valyala** [comment]
The `$labels.for` template variable is available in `vmalert` starting from [v1.85.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
