### ISSUE TITLE
Issue with Single v.1.82.0 azure_sd_configs

### ISSUE THREAD

**Issue by Turulda1** [VictoriaMetrics/VictoriaMetrics#3247]
**Describe the bug**

Single-node Victoriametrics is not able to get a list of VMs from subscription.
I'm using the ManagedIdentity authentication method and the VMs Identity has Reader role on subscription level.

It throws the error: 
404; expecting 200; response body: "{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}"

NOTE - it works when using recource_group parameter, but workaround of me scraping all resource groups this way is not suitable. 
NOTE2 - The subscriptions is for both dev & stage, currently am testing the victoriametrics in dev (it has no access to stage vm's due to firewall). Plan was to use relabel_configs to drop the stage vm's from the scrape
NOTE3 - It works fine on Prometheus, I'm currently testing VictoriaMetrics as a possible replacement., 

**To Reproduce**

1. Prepare YAML file with scrape config for victoriametrics to use
2. Grant VM on which victoriametrics is running Reader rights to the Azure Subscription
3. Run victoriametrics with -promscrape.config 
4. Get the following error:

Oct 13 12:22:17 dev-********* victoriametrics[18349]: 2022-10-13T12:22:17.634Z        error        VictoriaMetrics/lib/promscrape/config.go:1016        skipping azure_sd_config targets for job_name "azure_vms" because of error: cannot list virtual machines: cannot execute azure api request at https://management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/**********_STAGE/VMs/********: unexpected status code returned from "https://management.azure.comhttps//management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/***********_STAGE/VMs/*********": 404; expecting 200; response body: "{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}"

**Expected behavior**

Expecting the following log entry:
VictoriaMetrics/lib/promscrape/scraper.go:403        azure_sd_configs: added targets: 46, removed targets: 0; total targets: 46

**Logs**

Oct 13 12:22:17 dev-vic****** victoriametrics[18349]: 2022-10-13T12:22:17.634Z        error        VictoriaMetrics/lib/promscrape/config.go:1016        skipping azure_sd_config targets for job_name "azure_vms" because of error: cannot list virtual machines: cannot execute azure api request at https://management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/**********_STAGE/VMs/********: unexpected status code returned from "https://management.azure.comhttps//management.azure.com:443/subscriptions/********-****-****-****-************/providers/Microsoft.Compute/virtualMachines?api-version=2022-03-01&$skiptoken=********-****-****-****-**********!/Subscriptions/********-****-****-****-************/ResourceGroups/***********_STAGE/VMs/*********": 404; expecting 200; response body: "{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}"

**Screenshots**

Scrape config
![image](https://user-images.githubusercontent.com/106732716/196145238-5788c784-f430-494c-b3f8-349d26d25810.png)

Turned on System Assigned Identity
![image](https://user-images.githubusercontent.com/106732716/196145668-f385ffea-da36-4e1d-bcb0-c76fbba102f7.png)

Role Assignment
![image](https://user-images.githubusercontent.com/106732716/196145890-6e1e781a-43e1-471f-adc7-d51880caac33.png)

**Version**
victoria-metrics-20221007-004302-tags-v1.82.0-0-g832276064

**Used command-line flags**
/usr/local/bin/victoria-metrics-prod -storageDataPath=/data/victoria/ -selfScrapeInterval=30s -retentionPeriod=60 -maxConcurrentInserts=32 -search.maxUniqueTimeseries=900000 -promscrape.config=/data/scrape/prometheus.yml

**Comment by SamSpiri** [comment]
I just recently had the same issue. The azure API returns 404 error on the VM which is for sure there.

**Comment by Turulda1** [comment]
Just tried on my prod subscription, result is the same.
PROD-************": 404; expecting 200; response body: "{\"error\":{\"code\":\"MissingSubscription\",\"message\":\"The request did not have a subscription or a valid tenant level resource provider.\"}

Even though the VM is up and running, VictoriaMetrics machine having Reader role on whole subscription and SSH access to the machine itself. 

Currently the only way it works for me is if I set reaource_group parameter in the azure_sd_configs, but that's not a solution if one has many resource_groups.

**Comment by SamSpiri** [comment]
$skiptoken in url indicates that response was divided in pages. I'm not an expert on Azure API but perhaps the last page will normally give you 404 and this should indicate the end of response. Sounds dumb, but it is smart enough for Micro$oft

**Comment by denisgolius** [comment]
@f41gh7 could you take a look?

**Comment by f41gh7** [comment]
@Turulda1  Can you try fix for vmagent? You can build it from source from commit 02fef406d5bf6355174bae0e255154e63bf1dab8

 You try pre-built docker image for vmagent docker.io/victoriametrics/vmagent:02fef406d5bf

**Comment by valyala** [comment]
FYI, the bug should be fixed in [VictoriaMetrics v1.79.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.6).

**Comment by valyala** [comment]
This bug should be fixed in [VictoriaMetrics v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it then.
