### ISSUE TITLE
Can't query/match data send from PowerDNS through Graphite Protocol

### ISSUE THREAD

**Issue by Belphemur** [VictoriaMetrics/VictoriaMetrics#326]
**Describe the bug**
VictoriaMetrics accept the data without problem. But I can't query it because the tag contains a hyphen (-).

**To Reproduce**

```bash
echo "pdns.server.recursor.all-outqueries 15026 1582391620" | nc -N 127.0.0.1 2003
curl -G 'http://127.0.0.1:8428/api/v1/export' -d 'match=pdns.server.recursor.all-outqueries'
```
*Response*
```
error in "/api/v1/export": error when exporting data for queries=["pdns.server.recursor.all-outqueries"] on the time range (start=0, end=1582392513000): cannot parse "pdns.server.recursor.all-outqueries": expecting metricSelector; got "pdns.server.recursor.all - outqueries"
```

**Expected behavior**
Have the program replace the problematic hyphen when receiving the data since it's valid data for Graphite, but not for 

**Screenshots**
-

**Version**
victoria-metrics-20200213-161659-tags-v1.33.1-0-g7b1c7051

**Used command-line flags**
```
-retentionPeriod=1 -storageDataPath /var/lib/victoria-metrics/data -selfScrapeInterval=30s -httpListenAddr=:8428 -opentsdbListenAddr=:4242 -graphiteListenAddr=:2003
```

**Additional context**

**Comment by hagen1778** [comment]
Hi @Belphemur!
You need to escape hyphen while using `curl`. Try following:
`curl -G 'http://127.0.0.1:8428/api/v1/export' -d 'match=pdns.server.recursor.all\-outqueries'`

**Comment by Belphemur** [comment]
@hagen1778 Hoo I see, I need also to do the same in Graphana then !

Thank you.

Did I miss a documentation somewhere that explain this ?

**Comment by valyala** [comment]
> Did I miss a documentation somewhere that explains this ?

This is briefly explained at https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL - search for `escaped chars` there.

**Comment by valyala** [comment]
Another possible option is to use `match={__name__="pdns.server.recursor.all-outqueries"}` syntax. See (this article)[https://www.robustperception.io/whats-in-a-__name__] for details about `__name__`.

**Comment by Belphemur** [comment]
Thank you for the full explanation.
