### ISSUE TITLE
High churn rate 

### ISSUE THREAD

**Issue by theodrim** [VictoriaMetrics/VictoriaMetrics#3274]
Hello, we are using Victoria Metrics cluster v1.82.1 and periodically have high churn rate alert popping.
As suggested per documentation we did check cardinality for the metrics - but sadly didn't find any with really high %.
We did saw metrics with `prometheus_replica` label so
```
writeRelabelConfigs:
  - action: labeldrop
    regex: prometheus_replica
```
was added but alas it did not help.

Environment: Kubernetes v1.23.10-eks-15b7512

Now we are at loss - what might be the culprit and where to look for?
Attaching troubleshooting dashboards for last 30 days on our dev environment (we still have same issue on int / prod tho).
![image](https://user-images.githubusercontent.com/65532444/197976088-50d3496a-ffff-4052-ba95-c49c33a697fe.png)
![image](https://user-images.githubusercontent.com/65532444/197976154-73667df3-ced7-4883-b593-5b11e9b30d50.png)

Please let me know if I'm missing something.

**Comment by hagen1778** [comment]
Hello! Looks like you have churn spikes every few days. That's a sign new time series are registered at those moments. You can try using the following flag to understand what are they:
```
-logNewSeries
     Whether to log new series. This option is for debug purposes only. It can lead to performance issues when big number of new series are ingested into VictoriaMetrics
```

Please also read https://victoriametrics.com/blog/cardinality-explorer/ which might be helpful for your case.

**Comment by theodrim** [comment]
@hagen1778 Thanks! We'll enable that option on development environment and try to see which metrics is a culprit.
 
> Please also read https://victoriametrics.com/blog/cardinality-explorer/ which might be helpful for your case.

This was done as first measure, and we did identify duplicating metrics from `prometheus_replica` which we did disabled via `writeRelabelConfigs`
After removing those we don't see anything unusual in the cardinality explorer:
![image](https://user-images.githubusercontent.com/65532444/198396308-8babf755-0d89-4eed-9118-497048c8a923.png)

**Comment by hagen1778** [comment]
Thanks for the screenshots! Looks like the biggest (in terms of cardinality) is the `grps_server_handled_total` metric. You can try getting insights for it by clicking on the icon in the right column in the metric's row.
But in general, the metric doesn't look too big comparing to others. So probably everything is ok. The churn-rate alert is there only to notify you when big chunk of new metrics arrives. It could be a problem, it could be not. All depends on your use case. For example, if you monitor a one application in k8s which has 100 pods and then you do the new release - pod names will change and you'll see a churn spike. That is totally ok and maybe you need just update thresholds for the alert if that happens frequently. 
On the other hand, there could be a situation when someone adds a "bad label" (label which significantly increases cardinality and churn, like `timestamp=time()` label) and you'd better notice that as soon as possible. This is where ChurnRate alert can become handy.

**Comment by theodrim** [comment]
@hagen1778 Thank you for detailed explanation - I think in our use-case adjusting threshold for alert itself would be good solution, but looking into cardinality explorer from time to time will be also beneficial.
In any case looking at the metrics with `logNewSeries` still might be beneficial so we'll add that argument and monitor.
