### ISSUE TITLE
Support ARM images for all components

### ISSUE THREAD

**Issue by nthienan** [VictoriaMetrics/VictoriaMetrics#3284]
**Describe the solution you'd like**
Support ARM images for all components

**Comment by valyala** [comment]
VictoriaMetrics already provides Docker images and binaries for `arm` and `arm64` architectures for all the components. Multi-arch Docker images are available at https://hub.docker.com/u/victoriametrics . See, for example, [multi-arch Docker image for v1.82.1 release](https://hub.docker.com/layers/victoriametrics/victoria-metrics/v1.82.1/images/sha256-5d4bf2e3c1d73fab2a38ebf4ae8894e46c3511815810cef5f25ca14d64f874a8?context=explore), which supports both arm and arm64 architectures. Binaries for arm and arm64 are published at [releases page](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See, for example, https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.82.1/victoria-metrics-linux-arm-v1.82.1.tar.gz
