### ISSUE TITLE
Feature request: Add `no_stale_markers` to VMServiceScrape's `endpoints.vm_scrape_params`

### ISSUE THREAD

**Issue by tamcore** [VictoriaMetrics/VictoriaMetrics#3292]
**Describe the solution you'd like**
With the recent addition of a per-`scrape_config` `no_stale_markers` in release v1.83.0, it would be nice, if we could also set that parameter through `VMServiceScrape.endpoints.vm_scrape_params`.

**Comment by valyala** [comment]
Closing this feature request, since it has been implemented in https://github.com/VictoriaMetrics/operator/pull/546 .
