### ISSUE TITLE
vmui: setup series limits

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/VictoriaMetrics#3297]
**Is your feature request related to a problem? Please describe.**
Add a feature to the UI to set series limits

**Describe the solution you'd like**
- Add "Show all", when an alert about the limitation of the series
- Add limits setting to Global Settings (next to Setting Server URL)

The new value needs to be stored in localStorage

**Comment by valyala** [comment]
`vmui` supports setting custom limits for the number of displayed series starting from [VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
