### ISSUE TITLE
Embed mode

### ISSUE THREAD

**Issue by vtolstov** [VictoriaMetrics/VictoriaMetrics#33]
Thank you for opensourcing this.
Do you plan to support embed mode?
So import package and provide config and start server to get single node or cluster node setup.

**Comment by valyala** [comment]
There are no such plans, but it may be implemented by outside users by using [lib/storage](https://godoc.org/github.com/VictoriaMetrics/VictoriaMetrics/lib/storage) API. The storage may be opened with [storage.OpenStorage](https://godoc.org/github.com/VictoriaMetrics/VictoriaMetrics/lib/storage#OpenStorage) functions.
See [the code from vmstorage](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1836c415e6c686b8cc4ba8bb062a5abcc08e7761/app/vmstorage/main.go#L36) as a real-life example.

The only issue is we cannot afford backwards-compatibility guarantees for all the API from VictoriaMetrics sources. So external code may break when the API is changed.
