### ISSUE TITLE
new feature vmagent: support consul discovery config

### ISSUE THREAD

**Issue by nickmy9729** [VictoriaMetrics/VictoriaMetrics#330]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like vmagent to support consul service discovery.  Just like Prometheus

**Additional context**
Service mesh and service. Registration is getting more and more popular.  It would be great if vmagent supported getting targets from consul services.

**Comment by valyala** [comment]
See also the related feature request - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/334 .

**Comment by valyala** [comment]
FYI, `vmagent` and single-node VictoriaMetrics gained initial support for Prometheus-compatible service discovery for Consul aka `consul_sd_configs` in the commit 40c3ffb35953234912c45820d88761c12255f875 . This commit will be included in the upcoming release.

In the mean time it is possible to build `vmagent` from source code according to [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#how-to-build-from-sources) and test `consul_sd_configs` with it.

**Comment by valyala** [comment]
`consul_sd_configs` support has been added into release [v1.35.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
