### ISSUE TITLE
2 different vm clusters using 1 same vmagent, but the data are different

### ISSUE THREAD

**Issue by rickchen12** [VictoriaMetrics/VictoriaMetrics#3302]
Situation:
VMagent configured 2 different VMinsert alb so that can remote write to 2 different VM clusters, 

issues:
the data are different with same metric, for example:
For a same metric, here is the ss of 2 vm cluster:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/95666264/199436842-b61f8899-8cd0-4187-a71f-d554a1664b96.png">
<img width="776" alt="image" src="https://user-images.githubusercontent.com/95666264/199436948-ba156c2e-73b7-466b-8d5f-9a22e0f6ea1d.png">

also same in VMUI:
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/95666264/199437276-a339d48a-c36f-4044-9e01-dfa4163d3a6c.png">

in 1 vm clusters, seems like it has some data missing. 

and for some other same metric, it totally different, for example:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/95666264/199438084-49265c6e-16a1-4875-a03a-e1c8b1f9903e.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/95666264/199438115-cc80e99b-812f-43d4-ae67-e672fd415171.png">

but all the configurations are same for both 2 vm clusters, and I checked the log of cluster which has missing data, it doesn't have any err msg at all,  any one can give an advise?.

**Comment by dmitryk-dk** [comment]
Hi @rickchen12 ! Thank you for your issue. Can you share which version of the VM cluster do you use?

**Comment by rickchen12** [comment]
> Hi @rickchen12 ! Thank you for your issue. Can you share which version of the VM cluster you use?

sure,  victoria-metrics-amd64-v1.75.0-cluster.tar.gz, this is what I use.

**Comment by dmitryk-dk** [comment]
Can you try to use this part of the documentation
https://docs.victoriametrics.com/Troubleshooting.html

and check does it help with your problem.

**Comment by rickchen12** [comment]
Hi @dmitryk-dk , I tried to query in VMUI, and I find it maybe not due to data missing, it seems like due to vmselect issue, you can see the video, if I zoom in/out the query time period, the data are changing even at same timestamp, it's weird, I cant find any error msg in vmselect log, do you have any ideas?.

https://user-images.githubusercontent.com/95666264/199661016-c9d06f75-9a3e-448a-a296-6e753ed32ab8.mov

**Comment by zekker6** [comment]
@rickchen12 Could you try to check the following guide https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results ?
Also version 1.75 is quite outdated, this issue might already been fixed in later version.
It is better to update to either 1.79.x version(v1.79.x is a line of LTS releases (e.g. long-time support). It contains important up-to-date bugfixes) or to the latest release.

**Comment by rickchen12** [comment]
@zekker6 I upgraded to the latest version(victoria-metrics-linux-amd64-v1.83.0-cluster.tar.gz), and it still have 2 issues:
1. the trend of the charts are similar, but one of them has many spikes
<img width="799" alt="image" src="https://user-images.githubusercontent.com/95666264/200268940-dd423454-a514-4b7e-8405-e222b766036d.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/95666264/200268974-05d9dbee-9d92-494d-a719-4ffcbf0b032e.png">

2. the charts has some delay(about 5-10mins) 
<img width="803" alt="image" src="https://user-images.githubusercontent.com/95666264/200269094-c9f41d9d-00e8-4a4a-a4b2-553308e2009a.png">
<img width="803" alt="image" src="https://user-images.githubusercontent.com/95666264/200269158-3d61c660-1225-42e3-b1c2-6c7a1bdbe2e4.png">

do you have any ideas?

**Comment by dmitryk-dk** [comment]
Hi @rickchen12 ! Can you share your configuration of vmagent and both vmclusters?

**Comment by rickchen12** [comment]
and here is some performance monitor items for our vm clusters:
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/95666264/200746398-81694bb7-1f2b-4f31-8fca-37192d92919b.png">
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/95666264/200746551-d7f8539c-6331-4c22-ace9-1a38d61024bc.png">

**Comment by dmitryk-dk** [comment]
Hi @rickchen12 ! Thank you for the information we will take a look.

**Comment by rickchen12** [comment]
@dmitryk-dk hi, do you find something abnormal?.

**Comment by dmitryk-dk** [comment]
Hi @rickchen12 ! Today will try to take o look. sorry for delay

**Comment by dmitryk-dk** [comment]
Hi @rickchen12 ! I have tried to setup your configuration, but as I can see your vmagent just write to one cluster
```-remoteWrite.url=http://bijietech.radar.internal:18001/api/v1/write```. In the issue you described that you have one vmagent and two clusters. Can you please elaborate on how you write data from one vmagent to two vminserts. Sorry, maybe I missed something. I think you use some proxy. If yes can you share that proxy? Or you use one cluster?

**Comment by rickchen12** [comment]
sorry, my bad, I forget to describe the details, because the data missing and delay, I want to locate the root cause, so I added another vmagent with same jobs configurations to this vm clusters , which means totally individual for both 2 clusters now, but the data still get some issues as I showed above, and here is performance ss of the agent ,I find the cpu was very high,  is it due to the performance issue?.
![image](https://user-images.githubusercontent.com/95666264/202052304-51ec2a48-d588-414a-bbd8-d5cf72709910.png)
