### ISSUE TITLE
vmui: support sticky tooltips for text copying

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3321]
**Is your feature request related to a problem? Please describe.**
I'm looking for an easy way to copy value and labels of a specific datapoint on the graph.

**Describe the solution you'd like**
Would be nice to have a feature when user points on a specific data point on the graphs, sees the tooltip and then can left-click on the datapoint to make the tooltip to "stick". This would allow safely copy the text from tooltip and then close it when info is not needed anymore:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/2902918/200142065-219a539f-6cde-446c-ad98-3fc28882ad2c.png">

I assume that would require adding a "close" button to such sticky tooltips, so user can close them when not needed anymore.

**Describe alternatives you've considered**
To memorize it.

**Comment by valyala** [comment]
Sticky tooltips at `vmui` are available in VictoriaMetrics starting from [v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
