### ISSUE TITLE
Single-server VictoriaMetrics - define VMUI dashboards?

### ISSUE THREAD

**Issue by thomas725** [VictoriaMetrics/VictoriaMetrics#3322]
**Is your feature request related to a problem? Please describe.**
I'd like to use the feature I can see exists @ http://single-host-victoriametrics:8428/vmui/?g0.expr=#/dashboards
If I understand the documentation @ https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmselect/vmui/dashboards correctly, then at the moment to define custom Dashboards myself I would need to modify the files I can see @ http://single-host-victoriametrics:8428/vmui/dashboards before the VictoriaMetrics binary get's compiled from it' source.

**Describe the solution you'd like**
It would be nice if there was a way to modify vmui/dashboards/index.js and acompanying *.json config files on the fly, without having to recompile the single-server binary.

**Describe alternatives you've considered**
I suspect that maybe when using the distributed VictoryMetrics systems which is split into many parts that those files might exist in an extracted form on the server's file system. It doesn't seem like it does when using the Single-server VictoriaMetrics. I suspect it's included in the `victoria-metrics-prod` binary instead.

**Additional context**
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2243
* https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#vmui doesn't say anything about the Dashboards feature
* https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/vmui/dashboards/README.md doesn't say where to find / add / modify those files.

**Comment by thomas725** [comment]
maybe we could have a command line option that allows to tell the single server runtime the target path for the vmui dashboard definitions. without such an option, it would probably be best to simply hide the "dashboard" component of vmui since the predefined sample doesn't seem to work for the single server runtime.

**Comment by valyala** [comment]
> maybe we could have a command line option that allows to tell the single server runtime the target path for the vmui dashboard definitions. When that cli-option is not specified, it would probably be best to simply hide the "dashboard" component of vmui since the predefined sample doesn't seem to work for the single server runtime.

FYI, the https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3545 should implement this feature.

**Comment by valyala** [comment]
The commit 820312a2b183349e9dea2d4896ebea363f498792 adds the `-vmui.customDashboardsPath` command-line flag to single-node VictoriaMetrics . See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui/packages/vmui/public/dashboards) on how to use this flag. The commit will be included in the next release of VictoriaMetrics. In the meantime it is possible to build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether custom dashboards functionality works as expected.

**Comment by valyala** [comment]
The `-vmui-customDashboardsPath` command-line flag is available starting from [v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by thomas725** [comment]
Since I've reread our conversation here and saw how I was confused with the dashboard defined by default that didn't show anything (and no explanation how to fix it):

The solution to making those monitoring metrics available in the Single-Server version is to specify this command-line flag:
`-selfScrapeInterval="10s"`

**Comment by thomas725** [comment]
I've tried to use the specified command-line flag `-vmui-customDashboardsPath=/readable/path/`, but it failed to startup:
```
/opt/VictoriaMetrics/victoria-metrics-prod -storageDataPath /opt/VictoriaMetrics/data -inmemoryDataFlushInterval=24h -retentionPeriod=999y -search.maxPointsPerTimeseries=999999 -influxListenAddr=:8089 -search.minStalenessInterval=90s -search.maxStalenessInterval=90s -selfScrapeInterval=10s -vmui-customDashboardsPath=/opt/VictoriaMetrics/dashboards/
flag provided but not defined: -vmui-customDashboardsPath

victoria-metrics is a time series database and monitoring solution.

See the docs at https://docs.victoriametrics.com/

Run "/opt/VictoriaMetrics/victoria-metrics-prod -help" in order to see the description for all the available flags
```
the version I am currently using is: `victoria-metrics-20230407-010044-tags-v1.90.0-0-gb5d18c0d2`

Calling the referenced help funnily enough shows the flag I'm trying to use as last item:
```
  -vmui.customDashboardsPath string
    	Optional path to vmui dashboards. See https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui/packages/vmui/public/dashboards
```
