### ISSUE TITLE
Restore data of vmagent-remotewrite-data/persistent-queue after DB crash

### ISSUE THREAD

**Issue by JsBergbau** [VictoriaMetrics/VictoriaMetrics#3326]
I had make a configuration mistake and victoria-metrics-prod was not running for about one week.
vmagent-prod was running and collecting the data. 
After fixing the configuration and restarting victoria-metrics-prod, vmagent-prod was restoring the data. However victoria-metrics-prod crashed several times, because of max open files. After adding
```
LimitNOFILE=64000
LimitNOFILESoft=64000
```
in the systemd unit file victoria-metrics-prod was running stable. However some of the data that was beeing restored when the database service crashed, is missing. This is just an example of one machine, also the data of all other tested machines is missing. 

![grafik](https://user-images.githubusercontent.com/37013344/200428816-533cb7e5-10fe-4bb2-8259-e913e83ec17c.png)

I have a daily backup, so vmagent-prod was stopped and the contents of `vmagent-remotewrite-data/persistent-queue` restored (4.6 GB in total). After that  vmagent-prod was started again. However  vmagent-prod doesn't start to write the data back to the database as CPU usages shows. It just deletes the files. Log shows

```
2022-11-07T22:08:08.200Z#011error#011VictoriaMetrics/lib/persistentqueue/persistentqueue.go:301#011"vmagent-remotewrite-data/persistent-queue/1_A1034CECB2A6FE4E/0000000120000480" size (366384631 bytes) is smaller than the writer offset (366411775 bytes); removing the file
2022-11-07T22:08:08.324Z#011error#011VictoriaMetrics/lib/persistentqueue/persistentqueue.go:143#011cannot open persistent queue at "vmagent-remotewrite-data/persistent-queue/1_A1034CECB2A6FE4E": couldn't find chunk file for writing in "vmagent-remotewrite-data/persistent-queue/1_A1034CECB2A6FE4E"; cleaning it up and trying again
2022-11-07T22:08:08.631Z#011info#011VictoriaMetrics/lib/persistentqueue/fastqueue.go:59#011opened fast persistent queue at "vmagent-remotewrite-data/persistent-queue/1_A1034CECB2A6FE4E" with maxInmemoryBlocks=800, it contains 0 pending bytes
```

So how can the data be restored to the database? Thanks for help.

**Comment by hagen1778** [comment]
> I have a daily backup, so vmagent-prod was stopped and the contents of vmagent-remotewrite-data/persistent-queue restored (4.6 GB in total)

Just to be clear. You're saying you have vmagent's persistent queue backup - is this correct?
Have you tried to modify `metainfo.json` and setting offset equal to the file size?

**Comment by JsBergbau** [comment]
> Just to be clear. You're saying you have vmagent's persistent queue backup - is this correct?

Exactly, every day at midnight root filesystem is backed up. So I even have multiple versions and as you can see the missing data is a few days ago.

> Have you tried to modify metainfo.json and setting offset equal to the file size?

No, since I have restored this file, too.
Content: `{"Name":"1:secret-url","ReaderOffset":2107992,"WriterOffset":5198251135}`

Directory content:
```
-rw-r--r-- 1 victoriametrics victoriametrics 503338828  1. Nov 15:49 0000000000000000
-rw-r--r-- 1 victoriametrics victoriametrics 503318868  2. Nov 06:29 0000000020000080
-rw-r--r-- 1 victoriametrics victoriametrics 503325797  2. Nov 21:07 0000000040000100
-rw-r--r-- 1 victoriametrics victoriametrics 503319183  3. Nov 11:46 0000000060000180
-rw-r--r-- 1 victoriametrics victoriametrics 503323341  4. Nov 02:27 0000000080000200
-rw-r--r-- 1 victoriametrics victoriametrics 503326875  4. Nov 17:05 00000000A0000280
-rw-r--r-- 1 victoriametrics victoriametrics 503320566  5. Nov 07:44 00000000C0000300
-rw-r--r-- 1 victoriametrics victoriametrics 503320427  5. Nov 22:23 00000000E0000380
-rw-r--r-- 1 victoriametrics victoriametrics 503321519  6. Nov 13:15 0000000100000400
-rw-r--r-- 1 victoriametrics victoriametrics 366384631  7. Nov 00:00 0000000120000480
-rw-r--r-- 1 victoriametrics victoriametrics         0 20. Okt 14:45 flock.lock
-rw------- 1 victoriametrics pi                     72  7. Nov 00:00 metainfo.json
```

Can you tell me which values I should enter into metainfo.json?

**Comment by hagen1778** [comment]
If vmagent was stopped correctly, and data was restored correctly, then WriterOffset should contain the number of bytes written on disk queue, and ReaderOffset should contain the number of bytes read from the queue and sent to the remote storage.
So if you want to replay all these data, I assume, you need to set ReaderOffset=0, and WriterOffset=4392961207 //sum(file_sizes) 
Please, try this in safe environment where you're not afraid of data loss or corruption.

**Comment by JsBergbau** [comment]
Thank you very much. That worked, all data is finally back. I dared to use production environment since data can't be overwritten with wrong data (or at least I also have a backup). 
I used `{"Name":"1:secret-url","ReaderOffset":0,"WriterOffset":4896300035}` which is the sum of all the big data files.
So the question is why wasn't this data in metainfo.json set correctly at backup time? So I had luck that vmagent was still running when I got the DB running again, because with a server reboot it probably would have never recovered the data automatically.

I really love VictoriaMectrics. With prometheus I would have lost all the data of one week. With the modular system of VictoriaMetrics everything still exists

**Comment by hagen1778** [comment]
> So the question is why wasn't this data in metainfo.json set correctly at backup time?

How do you take the backups from the vmagent? Afaik, you need to stop it first, then take a backup. If you do backups in the runtime - it wont work)
Only [VictoriaMetrics TSDB](https://docs.victoriametrics.com/#how-to-work-with-snapshots) supports runtime snapshots mechanism so far.

**Comment by JsBergbau** [comment]
I do a backup with restic, meaning just reading the files. If stopping and restarting is required to have consistent backup would mean that after a server crash also no automatic restore of the data would be triggered. Instead this data would be lost. So I would suggest that vmagent updates the metainfo.json every minute. What do you think?

**Comment by hagen1778** [comment]
I'm not sure)
Maybe, vmagent needs something like snapshot mechanism. 
Maybe, it doesn't need it at all.

VM crashes shouldn't lead to data loss as you described at the beginning. When the process crashes, all it loses is the internal buffers of 1s of data. On your screenshot it is almost a day, which is super weird. I think something wrong happens there with either disk integrity or something else.

In normal operation, you have vmagents running 24/7. It is very rare for vmagent to crash. It is even rarer for vmagent to crash when destination (VM) has crashed. So backups need to be done for VM - just take a snapshot hourly and upload it with vmbackupmanager somewhere. It supports incremental backups which could significantly save space.

**Comment by JsBergbau** [comment]
> On your screenshot it is almost a day, which is super weird. I think something wrong happens there with either disk integrity or something else.

VM crashed because of too many open files. So this sounds plausible, VM reports written, but because of too many open files data wasn't written to disk. Linux allows by default only 1024 open files which are, as far as I know also network sockets. After increasing the limit it worked flawlessly. Found this article http://woshub.com/too-many-open-files-error-linux/

> It is very rare for vmagent to crash.
Thats true. I've never noticed a crash of vmagent. VM also didn't start because I had the retention period set too high and didn't check if it started.

I was talking about some kind of snapshot function for vmagent since the host could crash or have a poweroutage. Then data would be lost if you don't have a backup. It was luck that I discovered the cause of the crash of VM with too many open files fast enough so only some data in the past was lost. If I had discovered it too late my last backup would be 22 hours ago and all that data would have been lost.

**Comment by hagen1778** [comment]
> VM crashed because of too many open files. So this sounds plausible, VM reports written, but because of too many open files data wasn't written to disk. Linux allows by default only 1024 open files which are, as far as I know also network sockets. After increasing the limit it worked flawlessly. Found this article http://woshub.com/too-many-open-files-error-linux/

Correct. This is one of the recommendations we give for running VM https://docs.victoriametrics.com/BestPractices.html#install-recommendation


>  Then data would be lost if you don't have a backup.

The problem with that is that taking those backups from the vmagent is likely unsafe. Vmagent constantly modifies queue's files, so just copying those files can be inconsistent.

cc @valyala @f41gh7

**Comment by JsBergbau** [comment]
> The problem with that is that taking those backups from the vmagent is likely unsafe. Vmagent constantly modifies queue's files, so just copying those files can be inconsistent.

I would have expected that it just appends the data. So if file is read while being written maybe the last dataset might be included only partially in the backup and then will fail at restore time.

I did a test and stop VictoriaMetrics and took a look at metainfo.json. The file seems to be updated everytime new data was written into the queue and ReaderOffset starts with `0` and "WriterOffset" is constantly increased.

When starting DB again data is written to it, but persistent queue file still existed. 

Then when stopping the DB again ReaderOffset is not `0` anymore. So that is why it was not `0` at my case. But that still doesn't explain why WriterOffset didn't match.

Anyway it seems to work as it should. Thanks for all your support, especially for getting the data back. From my side this issue could be closed.
