### ISSUE TITLE
flag provided but not defined: -promscape.config

### ISSUE THREAD

**Issue by Thuan220820** [VictoriaMetrics/VictoriaMetrics#3332]
Hi, I'm building victoria metrics system. Through studying docs.victoriametrics, I am looking to replace prometheus and use victoria metrics to get metrics from exporter.service. But I am having problem in vmagent service and it is not working now.
According to the instructions of docs.victoriametrics.com/vmagent.html, i configure the flag -promscape.config to point to the file yml.

![image](https://user-images.githubusercontent.com/116623585/200774205-6a3a8bc9-3c23-42bc-87b8-6b8553442da8.png)

But after configuring, vmagent doesn't work!

![image](https://user-images.githubusercontent.com/116623585/200774649-4f1ff7b4-d6e3-40ac-8fcb-377877171355.png)
Bug:
![image](https://user-images.githubusercontent.com/116623585/200774710-273d7b8c-08fd-4804-98c4-a7943436264d.png)
Where did I go wrong? how to fix it?

**Comment by dmitryk-dk** [comment]
Hi @Thuan220820 ! You have typo in you flag name `promscape` instead of `promscrape` you forgot `r`

**Comment by dmitryk-dk** [comment]
Close issue as resolved
