### ISSUE TITLE
deduplication: compare values when timestamp comparison results in conflict

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3333]
**Is your feature request related to a problem? Please describe.**
Documentation mentions [downsampling](https://docs.victoriametrics.com/#deduplication) is based on comparing datapoints with identical label sets on a configured dedup.minScrapeInterval. The algorithm leaves the newest sample on the interval during deduplication. But when it detects two datapoints with the same timestamps - it picks the random one. The problem with this is that "random" isn't consistent - two distinct vmselects or vmstorage can pick different data points after the deduplication. Such behavior can result into "jumping" lines when plotted on Grafana, especially for recent series.

**Describe the solution you'd like**
Would be great to add one more condition to dedulication logic: if there are two or more datapoints with identical timestamp and labelset - keep the datapoint with the biggest value. The ratio behind this is the following:
* the biggest value is likely the newest value for counters. It is not true for gauges, but it still better than random;
* value comparisons seems as expensive as timestamps comparison;
* if values are identical - then deduplication still remains consistent;
* the change will allow running HA pairs of [vmagent](https://docs.victoriametrics.com/vmagent.html#high-availability) or [vmalert](https://docs.victoriametrics.com/vmalert.html#ha-vmalert) without the need of workarounds.

**Comment by valyala** [comment]
VictoriaMetrics should leave a sample with the biggest value if a time series contains multiple samples with the same timestamp during [deduplication](https://docs.victoriametrics.com/#deduplication) starting from [release v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by valyala** [comment]
FYI, it has been appeared that VictoriaMetrics v1.85.0 could return smaller sample out of multiple samples with identical timestamps. The issue has been fixed in [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
