### ISSUE TITLE
submit data via UDP with millisecond precision?

### ISSUE THREAD

**Issue by thomas725** [VictoriaMetrics/VictoriaMetrics#3334]
**Is your feature request related to a problem? Please describe.**
I'd like to send data with milisecond precision via one of the UDP interfaces, but both the one's I've found in the docs seem to only allow second precision. When sending milliseconds it still get's multiplied by 1000, the values are ignored and I get warnings like this in the log:
> VictoriaMetrics/lib/storage/storage.go:1821        warn occurred during rows addition: cannot insert row with too big timestamp 1668000647414000 exceeding the current time; maximum allowed timestamp is 1668173446000; metricName:>

**Describe the solution you'd like**
Maybe there's a different syntax / a switch to send milliseconds? Or something could be added to allow this?

**Describe alternatives you've considered**
I don't want to use one of the HTTP interfaces.

**Additional context**
The [docs](url) say to use `date +%s` - but that only gives seconds precision.

**Comment by thomas725** [comment]
Ah, I found it works when I pass seconds with a fractional part, sorry for not trying that obvious solution before requesting help.

**Comment by dmitryk-dk** [comment]
Closed as resolved

**Comment by thomas725** [comment]
Although it accepts date values with fractional parts, it seems to ignore them & round to the closest second:

```
$ echo "testmillis; 0 1668020768.512" | nc -vun victoriametrics-host 2003
$ curl -G 'http://victoriametrics-host:8428/api/v1/export' -d 'match=testmillis'
{"metric":{"__name__":"testmillis"},"values":[0],"timestamps":[1668020767000]}
```

**Comment by dmitryk-dk** [comment]
Hi @thomas725 ! Thank you for your request! As I see you are using Graphite-compatible protocol to import data. So by default Graphite doesn't support milliseconds. That is why VM round the timestamp to seconds. If you need to use millisend by using  Graphite-compatible protocol I will reopen the issue and we will make changes.

**Comment by thomas725** [comment]
What alternative protocols could I use, that are not Graphite-compatible and allow to use the millisecond precision?

**Comment by dmitryk-dk** [comment]
Try to check influx protocol https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf
it is also supports UDP and should save data with millisecond precision

**Comment by thomas725** [comment]
Okey, I will check that out next. I've just tried the OpenTSDB telnet interface, which gave the same result as the Graphite interface:
```
echo "put testmillis 1668020767.512 4242 " | nc victoriametrics-host 4242
```

**Comment by dmitryk-dk** [comment]
Try to change this flag 
```golang
trimTimestamp = flag.Duration("opentsdbTrimTimestamp", time.Second, "Trim timestamps for OpenTSDB 'telnet put' data to this duration. "+
		"Minimum practical duration is 1s. Higher duration (i.e. 1m) may be used for reducing disk space usage for timestamp data")
```

**Comment by thomas725** [comment]
ähm.. no idea where to change that flag, sorry... I'm using the precompiled single server binary and pass it command line flags. My systemd service definition looks like this right now:
```
ExecStart=/opt/VictoriaMetrics/victoria-metrics-prod -storageDataPath /opt/VictoriaMetrics/data -retentionPeriod=999y -search.maxPointsPerTimeseries=999999 -opentsdbListenAddr=:4242 -graphiteListenAddr=:2003 -influxListenAddr=:8089
```

**Comment by dmitryk-dk** [comment]
Just add it as another flag like `-opentsdbTrimTimestamp=1ms` and it should change the trim. 

But if not I will reopen the issue and we will improve that for some protocols.

**Comment by thomas725** [comment]
Sadly, it didn't work. I've added that flag and restarted victoriametrics and see that the flag is used in htop, but it the fractional seconds part is still ignored, at least I still get 3 zeros for the ms part in the export reply. So either it's not stored or cut off in the export.

**Comment by dmitryk-dk** [comment]
Reopened because we should check how we store timestamp if there are `1668020767.512` milliseconds defined

**Comment by thomas725** [comment]
Though now I've read the docs concerning those TrimTimestamp flags a bit more in depth, it seems that whoever wrote them already knew that the OpenTSDB telnet interface is limitted to second precision or less:

>-opentsdbTrimTimestamp duration
     Trim timestamps for OpenTSDB 'telnet put' data to this duration. Minimum practical duration is 1s. Higher duration (i.e. 1m) may be used for reducing disk space usage for timestamp data (default 1s)

Compare that with the sections about other TrimTimestamp flags:

>  -opentsdbhttpTrimTimestamp duration
     Trim timestamps for OpenTSDB HTTP data to this duration. Minimum practical duration is 1ms. Higher duration (i.e. 1s) may be used for reducing disk space usage for timestamp data (default 1ms)
>  -csvTrimTimestamp duration
     Trim timestamps when importing csv data to this duration. Minimum practical duration is 1ms. Higher duration (i.e. 1s) may be used for reducing disk space usage for timestamp data (default 1ms)
> ...

**Comment by dmitryk-dk** [comment]
In the Vm data would be without `_` character 
You can take a look into this part of the documentation
https://docs.victoriametrics.com/guides/migrate-from-influx.html#data-model-differences

**Comment by thomas725** [comment]
yes, I've found I can skip the measurement name, but it seems at least one tag is required.
This works (including milliseconds):
```
$ echo ",a=b testmillis=8089 1668020767512000000" | nc -vuc victoriametrics-host 8089
$ curl -G 'http://victoriametrics-host:8428/api/v1/export' -d 'match=testmillis'
{"metric":{"__name__":"testmillis","a":"b"},"values":[8089],"timestamps":[1668020767512]}
```

But leaving out that dummy tag like this:
```
echo ", testmillis=8089 1668020767512000000" | nc -vuc victoriametrics-host 8089
```
prints this error in the victoriametrics log:
```
VictoriaMetrics/lib/protoparser/influx/parser.go:216        cannot unmarshal InfluxDB line ", testmillis=8089 1668020767512000000": missing tag value for ""; skipping it
```

**Comment by dmitryk-dk** [comment]
We are waiting here for Influx-compatible data which is why you see this error.
Try to check this part of the documentation 
https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf

If it doesn't help please ping again)

**Comment by thomas725** [comment]
I've read the documentation section you've linked to, but I don't see any hint on how to use this protocol to send a metric without any tags.

**Comment by dmitryk-dk** [comment]
Hi @thomas725 ! Can you try to remove `,` in your request? It should work
`echo " testmillis=8089 1668020767512000000" | nc -vuc 127.0.0.1 8089`
<img width="1660" alt="Screenshot 2022-11-11 at 12 27 17" src="https://user-images.githubusercontent.com/12189570/201321162-e5bc1a39-36a3-465c-85cc-a45d69379329.png">

```
curl -G 'http://localhost:8428/api/v1/export' -d 'match={__name__=~"testmillis"}'
{"metric":{"__name__":"testmillis"},"values":[8089],"timestamps":[1668020767512]}

```

**Comment by thomas725** [comment]
yes that worked, thank you!
