### ISSUE TITLE
vmauth add support for Proxy Protocol

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#3335]
**Is your feature request related to a problem? Please describe.**
 Current, it's not possible to use vmauth behind network loadbalancer, which forward source IP address information via Proxy Protocol https://www.haproxy.org/download/2.3/doc/proxy-protocol.txt.

**Describe the solution you'd like**
 Allow support for proxy-protocol via special flag. Parsed information must be added to the `X-Forwarded-For` address.

**Describe alternatives you've considered**
Install nginx or ha proxy in front of vmauth. It creates additional point of failure and increases configuration complexity.

**Additional context**
 Cloud network load balancers, such as AWS, forwards client information via proxy protocol https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol

**Comment by valyala** [comment]
The commit 73256fe438ce63f5a44ee733678ba37d179bfada adds support for [proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) to [vmauth](https://docs.victoriametrics.com/vmauth.html) in the following way: if `vmauth` is started with the `-httpListenAddr.useProxyProtocol` command-line flag, then it reads the proxy protocol header from connections accepted at `-httpListenAddr`. The commit will be included in the next release. In the mean time it is possible to test the functionality by building `vmauth` from the commit according to [these docs](https://docs.victoriametrics.com/vmauth.html#how-to-build-from-sources).

**Comment by valyala** [comment]
`vmauth` accepts requests over proxy protocol at `-httpListenAddr` if `-httpListenAddr.useProxyProtocol` command-line flag is set starting from [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request then as done.

**Comment by f41gh7** [comment]
Need to add examples for k8s integration: 

1) how to collect metrics.
2) how to setup health checks.

**Comment by valyala** [comment]
FYI, `vmauth` could panic when http request is sent to a port listening for proxy protocol requests. This panic has been fixed in [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment]
The bugfix for the panic has been included in [v1.87.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.3) too.

**Comment by f41gh7** [comment]
Minor issue. vmauth logs errors:
```
"cannot read proxy proto conn for TCP addr \"0.0.0.0:8427\": proxy protocol error: the proxy protocol implementation doesn't support proto 0; expecting 1"
```

 But it's a valid case for health checks executed by loadbalancer (such as AWS lb).

`UNSPEC` proto could be used with `LOCAL` command. And it's valid case.

**Comment by hagen1778** [comment]
The fix from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4373 was included in https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.1

**Comment by valyala** [comment]
FYI, the bugfix for this issue has been back-ported to [long-term support release v1.87.7](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1675936197).
