### ISSUE TITLE
vmagent kubernetes_sd_configs

### ISSUE THREAD

**Issue by AeroNotix** [VictoriaMetrics/VictoriaMetrics#334]
First of all, great stuff on getting the vmagent out and available. It's a great addition to the suite. Will be making good use of this in the future.

**Is your feature request related to a problem? Please describe.**
No problem, only feature.

**Describe the solution you'd like**
Be able to use the same kubernetes_sd_config as with prometheus.

**Describe alternatives you've considered**
Something which generates the file_sd_configs and loads them into vmagent.

**Comment by valyala** [comment]
Thanks for the feature request!
The following service discovery mechanisms should be added soon to `vmagent`:

* [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)
* [ec2_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config)
* [gce_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#gce_sd_config)
* [dns_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config)
* [consul_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config)

**Comment by valyala** [comment]
@AeroNotix , `vmagent` just gained support for Prometheus-compatible k8s service discovery starting from the commit 2e4e202c2b077bc76504b68cf4ad40b78ba6bfdb . This commit will be included in the next release. In the mean time it is possible to test k8s service discovery in `vmagent` built from sources according [to these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#how-to-build-from-sources).

**Comment by valyala** [comment]
Prometheus-compatible Kuberntes service discovery is available in [vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md) and in [single-node VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-scrape-prometheus-exporters-such-as-node-exporter) starting from [v1.34.8](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by AeroNotix** [comment]
This is awesome! Congrats. Will get to running a canary deploy of this sometime soon and will report back any issues. :+1:
