### ISSUE TITLE
on v1.79.5 vmselect cannot fetch data from vmstorage

### ISSUE THREAD

**Issue by leo-minorui** [VictoriaMetrics/VictoriaMetrics#3344]
**Describe the bug**
migrate vmcluster from v1.72.0 to v1.79.5
vmselect on v1.79.5 cannot fetch data from vmstorage on v1.79.5
![image](https://user-images.githubusercontent.com/57588266/201863836-a6b1db40-2500-45aa-98fe-1f41a7252324.png)
vmselect on v1.72.0 can fetch data from vmstorage on v1.79.5

**Comment by tenmozes** [comment]
Hi @leo-minorui protocol between vmstorage and vmselect has changed and you need to run the same version of vmstorage and vmselect. Please take a look at release notes 

- https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.0 

and particularly 
```
Update note 3: this release introduces backwards-incompatible changes to communication protocol between vmselect and vmstorage nodes in cluster version of VictoriaMetrics because of added ability to query vmselect data from other vmselect nodes - see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup), so read requests to vmselect will fail until the upgrade is complete. These errors will stop after all the vmselect and vmstorage nodes are updated to the new release. It is safe to downgrade to previous releases at any time.
```

we are going to support two versions of protocols in the future to avoid situations like this

**Comment by leo-minorui** [comment]
thk,my bad!
