### ISSUE TITLE
Add a metric indicating the success of vmAgent config reload

### ISSUE THREAD

**Issue by virtualb0x** [VictoriaMetrics/VictoriaMetrics#3345]
**Is your feature request related to a problem? Please describe.**
Prometheus has  metric  called **prometheus_config_last_reload_successful** which indicates the config file is correct and can be read by utility

VMagent has no such a metric, so we have no exact indicator that the installed config file is wrong and can'be correctly read by VMagent

**Describe the solution you'd like**
A metric at https://vmagent-host.domain.any/metrics showing the vmagent_config_last_reload_successful

**Describe alternatives you've considered**
May be there are some WA metrics that can be used right now to understand config is wrong. Some log strings? Seems VMagent to use last successful config file without indicating smth is going wrong.

**Comment by valyala** [comment]
Commits 03d88bc066627cf4d32be681c85bb85aabdc86f3 and 9498f871e7514602301e2f56f9fb9a74c42ec10a add the following metrics to [vmagent](https://docs.victoriametrics.com/vmagent.html):

- `vmagent_relabel_config_reloads_total` - the number of `-remoteWrite.relabelConfig` and `-remoteWrite.urlRelabelConfig` reload attempts
- `vmagent_relabel_config_reloads_errors_total` - the number of failed `-remoteWrite.relabelConfig` and `-remoteWrite.urlRelabelConfig` reloads
- `vmagent_relabel_config_last_reload_successful` - whether the last reload of `-remoteWrite.relabelConfig` and `-remoteWrite.urlRelabelConfig` was successful
- `vmagent_relabel_config_last_reload_success_timestamp_seconds` - unix timestamp of the last successful `-remoteWrite.relabelConfig` and `-remoteWrite.urlRelabelConfig` reload

- `vm_promscrape_config_reloads_total` - the number of `-promscrape.config` reload attempts
- `vm_promscrape_config_reloads_errors_total` - the number of failed attempts for `-promscrape.config` reloads
- `vm_promscrape_config_last_reload_successful` - whether the last reload of `-promscrape.config` was successufl
- `vm_promscrape_config_last_reload_success_timestamp_seconds` - unix timestamp of the last successful `-promscrape.config` reload

These commits also add the following metrics to [single-node VictoriaMetrics](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html):

- `vm_relabel_config_reloads_total` - the number of `-relabelConfig` reload attempts
- `vm_relabel_config_reloads_errors_total` - the number of failed `-relabelConfig` reloads
- `vm_relabel_config_last_reload_successful` - whether the last reload of `-relabelConfig` was successful
- `vm_relabel_config_last_reload_success_timestamp_seconds` - unix timestamp of the last successful `-relabelConfig` reload

- `vm_promscrape_config_reloads_total` - the number of `-promscrape.config` reload attempts
- `vm_promscrape_config_reloads_errors_total` - the number of failed attempts for `-promscrape.config` reloads
- `vm_promscrape_config_last_reload_successful` - whether the last reload of `-promscrape.config` was successufl
- `vm_promscrape_config_last_reload_success_timestamp_seconds` - unix timestamp of the last successful `-promscrape.config` reload

It also adds the following metrics to [vminsert component of VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html):

- `vm_relabel_config_reloads_total` - the number of `-relabelConfig` reload attempts
- `vm_relabel_config_reloads_errors_total` - the number of failed `-relabelConfig` reloads
- `vm_relabel_config_last_reload_successful` - whether the last reload of `-relabelConfig` was successful
- `vm_relabel_config_last_reload_success_timestamp_seconds` - unix timestamp of the last successful `-relabelConfig` reload

These commits will be included in the next release.

**Comment by valyala** [comment]
The metrics mentioned [in this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3345#issuecomment-1322768545) are available starting from [VictoriaMetrics v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
