### ISSUE TITLE
vmauth allows to limit the number of proxied connections

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#3346]
**Is your feature request related to a problem? Please describe.**

  Currently, there is no limit for connections, that can be proxied by vmauth to backends. It may consume a lot of memory at vmauth and lead to possible OOMs.

**Describe the solution you'd like**
 Introduce connection limits - global for vmauth and limit per auth record. 

**Describe alternatives you've considered**
 Install haproxy or nginx in front of vmauth with connection limit.

**Comment by valyala** [comment]
The commit ff39a9114786aaf82682bdb574eedee561b5f969 adds `-maxConcurrentRequests` command-line flag to [vmauth](https://docs.victoriametrics.com/vmauth.html). This flag can be used for limiting the maximum number of concurrent requests `vmauth` can process at any given time. This allows limiting memory usage at `vmauth` side. This also allows limiting resource usage for backends behind `vmauth`. This commit will be included in the next release. In the meantime it is possible to build vmauth from source code according to [these instructions](https://docs.victoriametrics.com/vmauth.html#how-to-build-from-sources) and verify whether it works as expected.

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ff39a9114786aaf82682bdb574eedee561b5f969 adds the following metrics, which can be [monitored](https://docs.victoriametrics.com/vmauth.html#monitoring) at vmauth:

- `vmauth_concurrent_requests_capacity` - the maximum number of concurrent requests the `vmauth` can process. This metric equals to the value passed to `-maxConcurrentRequests` command-line flag.
- `vmauth_concurrent_requests_current` - the current number of concurrent requests `vmauth` processes right now
- `vmauth_concurrent_requests_limit_reached_total` - the number of requests, which were rejected with `429 Too Many Requests` http response error because `vmauth` was already processing the maximum number of concurrent requests.

**Comment by f41gh7** [comment]
@valyala  unfortenatly it's not enough. Per user request limit is required. 

 It's needed for case when `vmauth` clients is external users, which may ddos vmauth and make it unavailable for other users.

**Comment by valyala** [comment]
> Per user request limit is required.

> It's needed for case when vmauth clients is external users, which may ddos vmauth and make it unavailable for other users.

Agreed. Let's add per-user limit on the number of concurrent requests in a separate pull request then. @dmitryk-dk , could you create this pull request then?

The `-maxConcurrentRequests` command-line flag is available in [vmauth](https://docs.victoriametrics.com/vmauth.html) starting from [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It allows setting global limit on the number of concurrent requests `vmauth` can serve as described above.

**Comment by valyala** [comment]
The per-user limit on the number of concurrent requests has been added to [vmauth](https://docs.victoriametrics.com/vmauth.html) in the commit f582f9e8ab72277b85a9930e6b36f37ea0e7c82f . This commit will be included in the next release.

**Comment by valyala** [comment]
FYI, the `-maxConcurrentPerUserRequests` command-line flag has been added in `vmauth` recently. This flag allow setting per-user limit on the number of concurrent requests, which is applied individually per each configured user. This is much easier to manage at scale when the number of configured users is growing. The limit can be overridden via `max_concurrent_requests` option on a per-user basis. See [these docs](https://docs.victoriametrics.com/vmauth.html#concurrency-limiting) for details.

**Comment by valyala** [comment]
The `-maxConcurrentPerUserRequests` command-line flag and the `max_concurrent_requests` option can be evaluated by running `vmauth` Docker image `docker.io/victoriametrics/vmauth:heads-public-single-node-0-g438b2e11b`.

**Comment by valyala** [comment]
The `-maxConcurrentPerUserRequests` command-line flag and the `max_concurrent_requests` per-user option is available in [vmauth](https://docs.victoriametrics.com/vmauth.html) starting from [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
