### ISSUE TITLE
vmalert rules configuration from url

### ISSUE THREAD

**Issue by DenRozhko** [VictoriaMetrics/VictoriaMetrics#3352]
**Is your feature request related to a problem? Please describe.**
I want change rules but don`t want change rule file and restart pod.

**Describe the solution you'd like**
into  parameter "-rule " add possibility use rules from URL

**Describe alternatives you've considered**
We change file rules and restart pod.

**Comment by zekker6** [comment]
Hi @DenRozhko 
Did you consider using [configmap-reloader](https://github.com/jimmidyson/configmap-reload) ? 
It will send reload request to vmalert when rules stored in CM are changed.

Also, you can consider using [operator](https://github.com/victoriaMetrics/operator) for deployments. This will allow to create VMRules CRD which will trigger reload of VMAlert on change.

**Comment by DenRozhko** [comment]
The rules file is inside POD, we cannot use persistent storage.
I want start POD and forget about k8s. But rules can changes and rules files need refresh inside a running pod without restart.

Additional question
what UI is used to edit the rules?

**Comment by zekker6** [comment]
That is exactly what config-reloader does.
It does not require to set up persistent storage. Rules are mounted from CM directly into pod.
Once CM changes config-reloader reflects those changes in file and triggers [hot reload](https://docs.victoriametrics.com/vmalert.html#hot-config-reload) without pod restart.

> what UI is used to edit the rules?
Rules are plain yaml files, so there is no separate UI to edit these files.

**Comment by valyala** [comment]
FYI, [vmagent](https://docs.victoriametrics.com/vmagent.html) allows reading configuration files from url by passing the url to `-promscrape.config`. For example, `-promscrape.config=http://configserver/scrape-config-for-vmagent`. `vmagent` is able to re-read this config via multiple supported ways documented [here](https://docs.victoriametrics.com/vmagent.html#configuration-update). So it would be great from consistency PoV if [vmalert](https://docs.victoriametrics.com/vmalert.html) also could support the ability to read config file pointed by `-rule` command-line flag.

**Comment by Haleygo** [comment]
@hagen1778 I see vmalert already supported reading rules from object storage, but what about read from http url like vmagent or vminsert. Is that still needed ?
If so, I would like to take that :)

**Comment by hagen1778** [comment]
Yeah, it would make vmalert consistent with vmagent ability to read cfg from HTTP URL. Ofc, if that wouldn't bring too much complexity in the current implementation)

**Comment by hagen1778** [comment]
Issue will be closed on next release

**Comment by valyala** [comment]
`vmalert` is able to read configuration from HTTP urls starting from the commit cae87da4bbb54e901bfc5b355958b413488a6840 . This commit will be included in the next release. In the mean time it is possible to build `vmalert` from this commit according to [these instructions](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) and verify whether it can read config files from HTTP urls.

**Comment by valyala** [comment]
[vmalert](https://docs.victoriametrics.com/vmalert.html) is able to read configs from http and https urls starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
