### ISSUE TITLE
dns+srv discovery add records filters

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#3353]
**Is your feature request related to a problem? Please describe.**
  [Srv records](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#automatic-vmstorage-discovery) for vmstorage nodes with vmselect and vminsert ports could be registered with single dns srv record. In this case vminsert tries to connect to vmselect ports and vice versa.

**Describe the solution you'd like**
 Introduce `-storageNode.filter` command-line flag, which may contain a regexp for filtering the discovered `-storageNode` addresses. For example, `-storageNode.filter=^[^:]+:8400$` can be passed to `vminsert` in order to leave only `-storageNode` addresses ending with `8400` port (the default port used by `vmstorage` for accepting data from `vminsert` according to `-vminsertAddr` command-line flag at `vmstorage`).

**Describe alternatives you've considered**
To set up a separate `dns+srv` records for `vminsert` and `vmstorage` nodes. For example, `vminsert` would run with `-storageNode=dns+srv:vminsert-addr`, while `vmselect` would run with `-storageNode=dns+srv:vmstorage-addr`.

Actually, this setup is preferred over the setup with a single `dns+srv` record containing addresses for both `vminsert` and `vmstorage`. Separate `dns+srv` records for `vminsert` and `vmselect` allow performing fine-grained cluster configuration and maintenance. Examples:

- It is possible to run multiple groups of `vminsert` nodes, which write data to distinct sets of `vmstorage` nodes, while `vmselect` can be pointed to `dns+srv` record containing all the `vmstorage` nodes from both sets for global querying view.
- It is possible removing data ingestion from some `vmstorage` nodes without removing these nodes from `vmselect` during cluster re-configuration or maintenance.

**Comment by valyala** [comment]
The `-storageNode.filter` command-line flag has been added in enterprise version of VictoriaMetrics cluster. This flag allows filtering the [discovered storage nodes](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#automatic-vmstorage-discovery) with arbitrary regexp filters. For example, `-storageNode.filter='^[^:]+:8400$' would leave only discovered addresses with 8400 port. This feature will be available in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
The `-storageNode.filter` command-line flag is available in [enterprise version](https://docs.victoriametrics.com/enterprise.html) of VictoriaMetrics cluster starting from [v1.84.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
