### ISSUE TITLE
vmctl: got error `cannot unmarshal native block ... src is too short for reading string` when migrating metrics using vm-native method

### ISSUE THREAD

**Issue by ekarisky** [VictoriaMetrics/VictoriaMetrics#3357]
**Describe the bug**
We're trying to migrate from the old cluster VictoriaMetrics to the new cluster VictoriaMetrics. Based on this documentation
- https://victoriametrics.com/blog/storage-node-decommission/ 
- https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics

we can use `vmctl` to fulfill the requirement. But when we experimented with `vmctl` we got the error below and the migrating process failed. Any pointer or config we should use?

**To Reproduce**
- Run `vmctl` to migrate, check logs below for commands.

**Expected behavior**
Migration should work.

**Logs**
```
vmctl vm-native \
--vm-native-filter-time-start=2022-08-15T00:00:00Z \
--vm-native-filter-time-end=2022-08-15T23:59:59Z \
--vm-native-src-addr=http://old-vmselect:8481/select/2/prometheus \
--vm-native-dst-addr=http://new-vminsert:8480/insert/2/prometheus \
--vm-native-step-interval=hour

Initing import process to "http://new-vminsert:8480/insert/2/prometheus":
Total: 3.77 GiB ↘ Speed: 212.33 MiB p/s s
2022/11/17 07:58:54 import request failed: unexpected response code 400: remoteAddr: "x.x.x.x:52046"; requestURI: /insert/2/prometheus/api/v1/import/native; error when processing native block: cannot unmarshal native block from 17 bytes: cannot read timestampsData: src is too short for reading string with size 468; len(src)=1
```

**Version**
v1.83.0 & v1.83.1 both got errors.

**Comment by zekker6** [comment]
Hi @ekarisky 

This is related to breaking change introduced at release 1.82.0 - https://docs.victoriametrics.com/CHANGELOG.html#v1820 
> Update note 1: this release changes data format for [/api/v1/export/native](https://docs.victoriametrics.com/#how-to-export-data-in-native-format) in incompatible way, so it cannot be imported into older version of VictoriaMetrics via [/api/v1/import/native](https://docs.victoriametrics.com/#how-to-import-data-in-native-format).

In order to migrate data to the latest version you need to use the following upgrade path:
- Setup new cluster with version 1.81.2(version before 1.82.0)
- Migrate data to new cluster
- Update cluster to 1.83.1

**Comment by ekarisky** [comment]
Got it, will try to downgrade the new cluster version and rerun the `vmctl`. Thanks.
