### ISSUE TITLE
Nomad service discovery

### ISSUE THREAD

**Issue by nikita-b** [VictoriaMetrics/VictoriaMetrics#3367]
**Is your feature request related to a problem? Please describe.**
Do you plan to add service discovery for Nomad? It has native SD now:
https://github.com/hashicorp/nomad/pull/12368

**Describe the solution you'd like**
The same as for digital ocean or Kubernetes

**Additional context**
Prometheus already has it:
https://github.com/prometheus/prometheus/blob/875c4aa12eb0b1f0a9b0f72bd5245036f8f5a0c4/discovery/nomad/nomad.go

**Comment by nikita-b** [comment]
(if you don't have time for it I can do PR)

**Comment by valyala** [comment]
> if you don't have time for it I can do PR

That would be great!

**Comment by youngpabl0** [comment]
hello, @nikita-b will u do PR soon, or we can dont wait it and i can do it myself?) i too have nomad-sd in prometheus and want to replace it with vm)) thank u!)

**Comment by nikita-b** [comment]
@youngpabl0 I already have the code and it is now in the testing stage.
Most likely I'll create MR in Jan.

**Comment by mr-karan** [comment]
Ah, crap - I saw this issue a bit too late. 

I'd been working on this on my personal fork as I wanted Nomad service discovery in production for my own usecase. I've sent a PR for the same but it's alright if you want me to close this one if you already were planning to send.

**Comment by hagen1778** [comment]
The https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3549 was merged and will be available in the next VictoriaMetrics release. Meanwhile, try [building VcitoriaMetrics from sources](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources) to test the change.

**Comment by valyala** [comment]
See available config options and available meta labels for the discovered Nomad targets in [nomad_sd_configs docs](https://docs.victoriametrics.com/sd_configs.html#nomad_sd_configs).

**Comment by valyala** [comment]
`vmagent` and single-node VictoriaMetrics support Nomad service discovery starting from [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/sd_configs.html#nomad_sd_configs). Closing the feature request as done.
