### ISSUE TITLE
Error while setting up VM single 1.83.1

### ISSUE THREAD

**Issue by samar-elsayed** [VictoriaMetrics/VictoriaMetrics#3372]
**Describe the bug**
I am facing the below error while trying to set up the VM single server (for the first time) using **victoria-metrics:v1.83.1 image** :

`{"ts":"2022-11-21T08:50:18.933Z","level":"panic","caller":"VictoriaMetrics/lib/fs/fs_unix.go:29","msg":"FATAL: cannot flush \"/storage/snapshots\" to storage: sync /storage/snapshots: invalid argument"}`

**To Reproduce**
to apply the victoria-metrics-single-0.8.43 helm chart which will apply the statefulset using default values

**Comment by hagen1778** [comment]
Hi @samar-elsayed! Could you please provide list of command-line flags you pass to the victoria-metrics:v1.83.1?

**Comment by samar-elsayed** [comment]
Hi @hagen1778 
Sure,  the below args are used
args:
            - "--retentionPeriod=1"
            - "--storageDataPath=/storage"
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json

**Comment by samar-elsayed** [comment]
[vmsingle.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10067025/vmsingle.txt)
here is the file I am applying (the output from helm chart) I just changed the extension so I can attach it here

**Comment by hagen1778** [comment]
Thanks! The error comes from the OS. Are you sure in your container you have `/storage` folder and all permissions are correct? Consider the case [from our example](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/633ad34eb7732515075137f2b2363d0c00e264a1/deployment/docker/docker-compose.yml#L29-L32) - before pointing to `/storage` we mount it first.

**Comment by samar-elsayed** [comment]
Thanks @hagen1778 it was a misconfiguration for the storage as you said and now it working fine after fixing that
