### ISSUE TITLE
$activeAt is not available in alert label

### ISSUE THREAD

**Issue by Wyfy0107** [VictoriaMetrics/VictoriaMetrics#3379]
**Describe the bug**
I'm trying to use the $activeAt template variable in alert rule labels. But when the alert is triggered, the value for this label is `0001-01-01 00:00:00 +0000 UTC`, It seems that the value is nil, however works fine if $activeAt is used in annotations

After checking vmalert code, I think this is because of the `toLabels` function in `alerting.go`. This function evaluate the template of alert labels, but it was called before `a.ActiveAt` is set. So when the template is evaluated, `a.ActiveAt` is nil and hence the default date above.

Example rule:

```
- alert: "test"
   expr: cpu_usage>500
   for: 1s
   labels:
     activeAt: '{{$activeAt}}'
```

**To Reproduce**
vmalert version: 1.81.2 configured with the above alert rule. Querying active alarm from vmalert at `http://localhost:8880/api/v1/alerts` should get the above `activeAt` value

**Expected behavior**
The value should be the trigger time of the alert.

**Logs**
No warning or error logs

**Screenshots**

**Comment by hagen1778** [comment]
Hm, I don't think there is a sense in adding `activeAt` to labels. List of labels defines Alert ID. Using Alert ID vmalert can identify how long the alert was active. Adding `activeAt` to labels breaks the logic: Alert ID can't be calculated without knowing `activeAt`, and `activeAt` can't be calculated without knowing Alert ID.

I think vmalert should forbid using this variable in labels templating.

**Comment by hagen1778** [comment]
I understand. You still can have that information in a slightly different format by querying [timestamps](https://docs.victoriametrics.com/MetricsQL.html#tfirst_over_time) of when ALERTS became firing, or when it stopped being so.

Adding `activeAt` to labels seems too complicated to me because of the reasons I provided in the first response. I also think, that having `$value` in labels should be also forbidden. But I think we need to keep it because Prometheus has it available as well.

**Comment by Wyfy0107** [comment]
@hagen1778 Thanks for the response. The `tfirst_over_time` query function needs a lookbehind window to work. So in the perspective of user that wants to see active alerts, they might not know how much is reasonable to look behind, so I'm not sure if this is suitable.

**Comment by hagen1778** [comment]
Do you use Grafana for querying this data? Or is it a custom UI? Have you tried using vmalert's API instead?

**Comment by Wyfy0107** [comment]
No we're not using this alert data for graph, but for service to service communication. I tried vmalert api, however we need to be able to filter on active alerts as well, which vmalert api does not support

**Comment by hagen1778** [comment]
API filtering should be easy to add, if it fits your needs. As a workaround, you can perform filtering on application side.

**Comment by DaazKu** [comment]
This is a problem for us before we're trying to create a link (as a label) to vmui with a proper `end_input` but we can't because of this.

```
victoriametrics/vmui/?#/?g0.expr={{ $expr | queryEscape }}&g0.range_input=1h&g0.end_input={{ $activeAt.Format ("2006-01-02T15:04:05") | queryEscape }}
```

**Comment by hagen1778** [comment]
Hi @DaazKu! The problem of having `activeAt` as a label value is described here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3379#issuecomment-1325255400

But you still can have it as annotation. It is common approach to put dashboard link to annotations - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ddb3ae0f0091ac07d59d890ef5ee0a52d8b269ef/deployment/docker/alerts.yml#L29
