### ISSUE TITLE
vmgateway add support of JWK set endpoint for token signature verification 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3382]
We need to pull keys from endpoints and add an option to retry in N seconds/minutes

**Comment by zekker6** [comment]
vmgateway supports pulling keys from JWKS endpoints starting from [v1.88.0](https://docs.victoriametrics.com/changelog_2023/#v1880).
There is a separate FR about keys reload in the background - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3874
Closing this feature request as completed.
