### ISSUE TITLE
kuma_sd_config for Kuma Control Plane targets discovery

### ISSUE THREAD

**Issue by shedimonG** [VictoriaMetrics/VictoriaMetrics#3389]
**Is your feature request related to a problem? Please describe.**
We would like to use `kuma_sd_config` to retrieve scrape target from the [Kuma](https://kuma.io/) control plane. It would also be a feature parity with the latest Prometheus.

**Describe the solution you'd like**
`kuma_sd_config` available for vmagent.

**Describe alternatives you've considered**
There is an alternative of using `file_sd_config` with something that populates it with targets, but it would be a least desired workaround.

**Additional context**
Apparently, there is a need to implement a Service Discovery mechanism via the [xDS REST protocol](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#rest-json-polling-subscriptions), which looks like a too much of a change from an external contributor without the vision on using other packages and protobufs for the `vmagent` app. Would be glad to help if the vision and third-party packages usage policy is clear to me :)

**Comment by tenmozes** [comment]
we are going to release Kuma SD in q1 2023

**Comment by valyala** [comment]
Initial version of Kuma service discovery aka [kuma_sd_config](https://docs.victoriametrics.com/sd_configs.html#kuma_sd_configs) is available starting from the commit 9fbd45a22fdba49fd496aa6d2760b1cd4e44a46f . Thanks to @Amper for the implementation!

It will be included in the next release. In the mean time it is possible to test it by building `vmagent` from the commit mentioned above according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment]
`vmagent` supports [Kuma service discovery](https://docs.victoriametrics.com/sd_configs.html#kuma_sd_configs) starting from [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
