### ISSUE TITLE
vmalert: add "evaluation_offset" option to group configuration

### ISSUE THREAD

**Issue by stevenbeaullieu** [VictoriaMetrics/VictoriaMetrics#3409]
**Is your feature request related to a problem? Please describe.**
For recording rules with a high interval, say > 5m, it would be desirable to be able to specify when they evaluate.  One issue we had was with a 60m interval, it was evaluating toward the end of the hour, but writing with a timestamp at the top of the hour.  This was excluding it from federation because of staleness.  If we could give it an evaluation-offset of 2m or something like that, that would make sure it evaluates and writes the result within the first 5m of the hour so it is included in Federation.  Other use cases are recording rules that run once every 24 hours to produce metrics for other things to consume.  Since the metrics need to be available before what depends on them, it makes sense to be able to specify when they run rather than let it be random.

**Describe the solution you'd like**
Add a configuration option to group configurations called "evaluation_offset" that works similar to the "scrape_offset" for vmagent scrape configurations.  Instead of an algorithm choosing when the rules run, they would run at the specified offset within their interval.  So a 1m interval with an evaluation_offset of 0s would run at the top of the minute, or a 60m interval with an evaluation_offset of 2m would run at 2m after the hour every hour.  This would be paired with the existing `-datasource.queryTimeAlignment` to either keep the timestamp at the top of the interval, or have the timestamp match the offset exactly if alignment is disabled.

**Describe alternatives you've considered**
We've worked around this for now, but could simplify some solutions with this ability.

**Additional context**
N/A

**Comment by spotifyprism** [comment]
@hagen1778 I can take a look at this

**Comment by stevenbeaullieu** [comment]
@spotifyprism Yes, but you could also keep queryTimeAlignment as true and it would write at the top of the interval and evaluate at the offset.  queryTimeAlignment would keep doing what it's doing and this new configuration would just override when the rule is evaluated.

In hindsight our original problem would likely have been fixed by setting queryTimeAlignment to false, but we weren't sure about other repercussions of that.  I'm guessing there would have been none, but didn't have the appetite to change it at the time.

For the original problem, we no longer have recording rules with an interval > 5m, so we haven't had an issue with staleness anymore.  I could still see such a configuration being useful to mirror the capability with vmagent.

**Comment by spotifyprism** [comment]
yeah sounds good, queryTimeAlignment & rule evaluation are two separate mutually exclusive problems.
That being said I think where this feature might be useful is when a user wants to have some kind of control of when the rules in a group get evaluated within the group interval vs it being totally random

**Comment by Haleygo** [comment]
>Yes, but you could also keep queryTimeAlignment as true and it would write at the top of the interval and evaluate at the offset. 

Doesn't sound right to me here, to write data belong to one timestamp with other timestamp. It will be very confusing and group eval_offset can change.

**Comment by hagen1778** [comment]
>  And now group has eval_offset, it shouldn't affect the firstTS cause we still want the result to be consistent[users can turn off queryTimeAlignment if they don't want it], so it will only change the secondTS to secondTS+eval_offset.

I think it will be not `secondTS+eval_offset` but `eval_interval % eval_offset`. For example with 11:58 (secondTS) and 11:00 (firstTS), user would be able to set `eval_offset: 1m` and secondTS will become `11:01`.

In other words: at `11:01` vmalert will execute expression with `time=11:00` and will persist its results with `time=11:00`. 

If user disables `queryTimeAlignment`, then it will become the following: at `11:01` vmalert will execute expression with `time=11:01` and will persist its results with `time=11:01`.

**Comment by hagen1778** [comment]
@stevenbeaullieu the support of `eval_offset` was added in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/45c0e4bb3129d26630e7ad5fa6652649780d2b44. It will be likely included in the next major release. Meanwhile, you can try building vmalert from [sources](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources).

**Comment by valyala** [comment]
The `eval_offset` option is available in `vmalert` starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmalert.html#groups) for more details.

Closing the feature request as done.
