### ISSUE TITLE
Enforce deduplication on old data

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#341]
**Is your feature request related to a problem? Please describe.**
I need to deduplicate data that i have in VM 

**Describe the solution you'd like**
Separate method to enforce deduplication for time interval and/or metrics

**Describe alternatives you've considered**
Wait for retention

**Comment by valyala** [comment]
This functionality has been already implemented starting from [v1.41.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) - see [these docs](https://victoriametrics.github.io/#forced-merge) for details.
