### ISSUE TITLE
dns+srv discovery for cluster components heavily loads dns server

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#3417]
**Is your feature request related to a problem? Please describe.**

 Currently `vminsert` and `vmselect` nodes perform `dns+srv` requests every two seconds when [automatic discovery of vmstorage nodes](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#automatic-vmstorage-discovery) is enabled. This can cause significant load on DNS server when the number of `vminsert` and `vmselect` nodes is high.

**Describe the solution you'd like**

To add `-storageNode.discoveryInterval` command-line flag for controlling the interval for sending `dns+srv` requests to DNS server when [automatic dscovery of vmstorage nodes](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#automatic-vmstorage-discovery) is enabled.

It would be great if every `vminsert` and `vmselect` node could randomize the initial offset for querying DNS server on the range `0 .. -storageNode.discoveryInterval`. This should spread load on DNS server over time.

**Comment by valyala** [comment]
The `-storageNode.discoveryInterval` command-line flag is available at [enterprise versions](https://docs.victoriametrics.com/enterprise.html) of `vmselect` and `vminsert` starting from [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
