### ISSUE TITLE
Build QuerierParams behavior in VMALERT restore state

### ISSUE THREAD

**Issue by zhulaker** [VictoriaMetrics/VictoriaMetrics#3418]
**Describe the bug**
it would be better that when vmalert restore alert state, we should also Build QuerierParams same to recording rule and alert rule, or we will missing our headers in this case.
<img width="675" alt="图片" src="https://user-images.githubusercontent.com/20249430/204697970-f170c764-e475-4462-9d47-867f0c8cd6b7.png">

<img width="876" alt="图片" src="https://user-images.githubusercontent.com/20249430/204698110-da5b4010-8777-4704-82bd-132423411ea0.png">

**To Reproduce**
the behavior will be when restore restores the state of active alerts basing on previously written time series, the query request to remote storage will missing headers and also EvaluationInterval

**Expected behavior**
we shuold build QuerierParams in same behaviour to recording rule and alert rule

**Logs**
<img width="1339" alt="图片" src="https://user-images.githubusercontent.com/20249430/204698678-180842b6-79c6-4dcd-bb92-aa0d226e21e1.png">

**Version**
1.83.1 also in master

**Comment by hagen1778** [comment]
Thanks for noticing! The headers are now properly set in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3420.
There is no need in adding EvaluationInterval, because it only matters on actual rule evaluations. Rules restore is performed on 1h duration and EvaluationInterval will not have an effect.

**Comment by valyala** [comment]
This bug has been fixed in `vmalert` [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
