### ISSUE TITLE
vmui: sticky tooltip sizing is sometimes wrong

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3427]
**Describe the bug**
When using sticky tooltip I found that Close button isn't always visible. Checking the web page I realized it was locate far out of the tooltip div:
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/2902918/205047563-f96cafbb-b4f0-4222-8c4b-d555db338c57.png">

**To Reproduce**
Create a time series with a label which width is twice bigger than tooltip width. Try plotting it and use sticky tooltip.

**Expected behavior**
Probably, adding horizontal scroll or word break-down could help.

**Comment by valyala** [comment]
Closing this bug as fixed, since it has been fixed in the `master` branch and it corresponds to the feature, which hasn't been released yet - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3321 .

**Comment by valyala** [comment]
oops, the sticky tooltip feature has been already released in v1.84.0. Re-opening the issue then.

**Comment by valyala** [comment]
The bug has been fixed in [vmui v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
