### ISSUE TITLE
Configure vmselect to log all MetricsQL queries it performs

### ISSUE THREAD

**Issue by nesterwsx** [VictoriaMetrics/VictoriaMetrics#344]
**Is your feature request related to a problem? Please describe.**
To speedup dashboards/alerts/etc. we want to find/log all "slow" queries against vmselect and optimise them

**Describe the solution you'd like**
Something like --query.slowlog.threshold=3s in command line to log all queries into log

**Comment by hagen1778** [comment]
Hi @nesterwsx !
I guess you're looking for `search.logSlowQueryDuration`. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7b1c7051a37316ce2ebe10733416d0b92edf8822/app/vmselect/promql/exec.go#L18

**Comment by anesterov-joom** [comment]
Exactly! Thx
