### ISSUE TITLE
Why can't I delete time series

### ISSUE THREAD

**Issue by tanxiao1990** [VictoriaMetrics/VictoriaMetrics#3443]
I have an error metric that can be found in the topN of the UI interface（/prometheus/api/v1/status/tsdb?topN=10&date=2022-12-05）and I would like to delete this metric ,
I follow the document for delete time series，as below ，
https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-delete-time-series
i do /api/v1/admin/tsdb/delete_series
then merge it ,/internal/force_merge?partition_prefix=YYYY_MM,
In the UI topN display, he does disappear, but when I execute the proml query, he is still there
It still prompts the following error，It seems that the data has not been deleted

“the number of matching timeseries exceeds 300000”

**Comment by hagen1778** [comment]
> but when I execute the proml query, he is still there

Have you tried to disable or reset the cache? There are more tips to this can be found [here](https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results).

> It still prompts the following error，It seems that the data has not been deleted

Are you sure that deleted metric was the only contributor to the number of matching time series? Have you considered to narrow the filter in your query or lift up the 300e3 limitation?

**Comment by tanxiao1990** [comment]
Thank you for your reply, I will try again as suggested

**Comment by hagen1778** [comment]
Closing as inactive
