### ISSUE TITLE
vm lost data

### ISSUE THREAD

**Issue by dw-3** [VictoriaMetrics/VictoriaMetrics#3451]
**Describe the bug**
It would be great to [upgrade](https://docs.victoriametrics.com/#how-to-upgrade) 
to [the latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
and verify whether the bug is reproducible there.
It's also recommended to read the [troubleshooting docs](https://docs.victoriametrics.com/#troubleshooting).

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
Check if any warnings or errors were logged by VictoriaMetrics components
or components in communication with VictoriaMetrics (e.g. Prometheus, Grafana).

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

See how to setup monitoring here:
* [monitoring for single-node VictoriaMetrics](https://docs.victoriametrics.com/#monitoring)
* [monitoring for VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring)

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20190730-121249-heads-single-node-0-g671d9e55
```

**Used command-line flags**
Please provide the command-line flags used for running VictoriaMetrics and its components.

**Comment by dw-3** [comment]
vminsert-20221126-050830-tags-v1.84.0-cluster-0-gd0461bec2

**Comment by dw-3** [comment]
![image](https://user-images.githubusercontent.com/20983001/205811485-6b4465b7-1258-4dfe-8fb6-90fbff5eb1e8.png)
Query vm directly

**Comment by dw-3** [comment]
It is normal to query promtheus directly
![image](https://user-images.githubusercontent.com/20983001/205811768-1e963412-666e-4292-be5b-576c884a3d3c.png)

**Comment by dw-3** [comment]
The vm and prometheus components do not report any errors

**Comment by hagen1778** [comment]
Hi! Could you please describe your topology? You mention both vminsert (cluster component) and vmsingle (a single-binary) in the report - how exactly do you use them? What is the metric you think data was lost? How frequently is it scraped by prometheus?

**Comment by hagen1778** [comment]
Okay. The proper way to investigate this is to verify that VM indeed lost data. To do so, you need to compare raw data in Prometheus and VM for the given time series:
1. See how to get raw data in [Prometheus](https://www.robustperception.io/extracting-raw-samples-from-prometheus/)
2. See how to get raw data in [VM](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-export-data-in-json-line-format)

Try fetching the raw data and verify datapoints from each source. If you find the gap in VM for which Prometheus has datapoints - try checking the logs of Prometheus, vminsert and vmstorage at that moment of time. [VictoriaMetrics dashboard](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/) could also help you to check if something weird happened to the cluster (restarts, limits exceeding, etc).

If you didn't find the gap, then problem is likely in staleness detection difference between VM and Prom. You can find more details about it [here](https://docs.victoriametrics.com/keyConcepts.html#range-query). Try checking the following flag on VM side:
```
 -search.maxStalenessInterval duration
     The maximum interval for staleness calculations. By default it is automatically calculated from the median interval between samples. This flag could be useful for tuning Prometheus data model closer to Influx-style data model. See https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness for details. See also '-search.setLookbackToStep' flag
```

**Comment by dw-3** [comment]
> 
I requested the interface according to the method you gave me. I have confirmed that the original data of vm and Prometheus are not lost. It should be a problem of staleness detection. My current Prometheus crawling time is 30s, and remote_write is also 30s. How much should I set -search.maxStalenessInterval? ?

**Comment by dw-3** [comment]
![image](https://user-images.githubusercontent.com/20983001/206159632-deeb3d32-d977-476c-951e-f3311f2a0e26.png)
I have set -search.maxStalenessInterval to 60s, but it still breaks

**Comment by dw-3** [comment]
Prometheus
  [
                        1670410410.586,
                        "15"
                    ],
                    [
                        1670410424.908,
                        "15"
                    ],

**Comment by dw-3** [comment]
VM：
1670410371704,
1670410424908, --->just this one
1670410460628,

**Comment by dw-3** [comment]
![image](https://user-images.githubusercontent.com/20983001/206164048-757e828e-48bb-4b50-a400-a0dfcac5c5a8.png)

**Comment by dw-3** [comment]
--search.minStalenessInterval=120s

**Comment by hagen1778** [comment]
I'm sorry. I don't understand last two comments of yours. Could you please elaborate on them?

**Comment by dw-3** [comment]
I added the --search.minStalenessInterval=120s parameter, and there was no breakpoint in the data

**Comment by hagen1778** [comment]
Ok, thanks! Do you understand why there was a gap in the first place?

**Comment by dw-3** [comment]
To be honest, I don't quite understand, and my understanding of this parameter is also very vague, and the explanation in the official website document is not very clear.

**Comment by hagen1778** [comment]
> To be honest, I don't quite understand, and my understanding of this parameter is also very vague, and the explanation in the official website document is not very clear.

The issue is in irregular intervals between data points collected by Prometheus. If you would dig into the [pull model](https://prometheus.io/blog/2016/07/23/pull-does-not-scale-or-does-it/) details you'd notice that Prometheus doesn't guarantee the exact scraping interval. For example, if you have `scrape_interval: 15s` it doesn't guarantee that you'll have datapoints on 15s, 30s, 45s and 60s seconds. The exact scrape time always shifts, and, sometimes, scrapes are missed. 
If you'd take a look at raw data from your example, you'd notice that on the moment when VictoriaMetrics shows the gap - it actually shows that data samples are missing.
Why Prometheus doesn't show the gap? Because Prometheus continues to return the last recorded sample during the 5min after it stopped receiving any data. Try disconnecting one of the targets in Prometheus and check its metrics - you'd see they're still present up to 5min after target get away. This behavior is called staleness detection, and in Prometheus time series is considered as stale if it didn't receive new samples during the 5min.

VictoriaMetrics has different way to detect staleness. It doesn't operate with fixed 5min interval. Instead it calculates  the staleness interval as two medians of the intervals between the first 20 raw samples in the requested time range.

So what happened in your case is that VM detected that time series became stale faster than Prometheus did. That's why you see the gap in VMUI and don't see it in Prometheus UI. That's why overriding the staleness interval via --search.minStalenessInterval=120s helped to remove the gap.

**Comment by dw-3** [comment]
> > To be honest, I don't quite understand, and my understanding of this parameter is also very vague, and the explanation in the official website document is not very clear.
> 
> The issue is in irregular intervals between data points collected by Prometheus. If you would dig into the [pull model](https://prometheus.io/blog/2016/07/23/pull-does-not-scale-or-does-it/) details you'd notice that Prometheus doesn't guarantee the exact scraping interval. For example, if you have `scrape_interval: 15s` it doesn't guarantee that you'll have datapoints on 15s, 30s, 45s and 60s seconds. The exact scrape time always shifts, and, sometimes, scrapes are missed. If you'd take a look at raw data from your example, you'd notice that on the moment when VictoriaMetrics shows the gap - it actually shows that data samples are missing. Why Prometheus doesn't show the gap? Because Prometheus continues to return the last recorded sample during the 5min after it stopped receiving any data. Try disconnecting one of the targets in Prometheus and check its metrics - you'd see they're still present up to 5min after target get away. This behavior is called staleness detection, and in Prometheus time series is considered as stale if it didn't receive new samples during the 5min.
> 
> VictoriaMetrics has different way to detect staleness. It doesn't operate with fixed 5min interval. Instead it calculates the staleness interval as two medians of the intervals between the first 20 raw samples in the requested time range.
> 
> So what happened in your case is that VM detected that time series became stale faster than Prometheus did. That's why you see the gap in VMUI and don't see it in Prometheus UI. That's why overriding the staleness interval via --search.minStalenessInterval=120s helped to remove the gap.

Thank you very much for your explanation, really appreciate it, I think I have put a new light on this question, I have understood the parameter and the answer to this question, thank you very much
