### ISSUE TITLE
Facing issues with the cardinality Page of VMUI

### ISSUE THREAD

**Issue by ravishkhullar** [VictoriaMetrics/VictoriaMetrics#3457]
Getting below error on the cardinality page of VMUI
<img width="1437" alt="Screenshot 2022-12-07 at 10 47 43 PM" src="https://user-images.githubusercontent.com/14993713/206247645-8eeb82b4-1012-4189-a757-e4342ef4a4d3.png">

**Comment by dmitryk-dk** [comment]
Hi @ravishkhullar ! Can you add more information about the issue? What version of the VM do you use?

**Comment by ravishkhullar** [comment]
Hi @dmitryk-dk, thanks for your prompt response, we are using version v1.61.1-cluster

**Comment by dmitryk-dk** [comment]
@ravishkhullar ! This feature was added in the https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.78.0 release. So I think `/api/v1/status/tsdb` https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#tsdb-stats doesn't return correct data for that tab

**Comment by dmitryk-dk** [comment]
Close this issue as resolved. Feel free to reopen if you find some problems

**Comment by ravishkhullar** [comment]
@dmitryk-dk I am facing this issue only for the cardinality page on vmui. 
Do I have to use ver >= 1.78.0 of Victoria metrics select, insert and storage in order to make it work? We are running this K8s
