### ISSUE TITLE
Are there any plans to implement recording rules in vmagent ?

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#346]
**Describe the solution you'd like**
We use prometheus scrape kubernetes metric and do some pre-aggregation through [recording rule](https://prometheus.io/docs/practices/rules/) (like [this](https://github.com/coreos/kube-prometheus/blob/master/manifests/prometheus-rules.yaml#L90)). 
Is there any plan to add recording rule feature in vmagent? 

**Describe alternatives you've considered**
An independent program executes the recoding rule through the promql http api and writes back the pre-aggregated data through the remote write api.

**Comment by valyala** [comment]
It is likely support for recording rules will be eventually added into `vmalert` tool. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/304 . cc'ing @tenmozes .

**Comment by hagen1778** [comment]
Hi @faceair! Recording rules support was added to `vmalert` in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/270552fde4cd5c511b4e39d1c814d231de0bab99. Would appreciate your feedback!

**Comment by valyala** [comment]
FYI, [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/README.md) supports recording rules starting from [v1.37.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing this feature request as done.

**Comment by Haleygo** [comment]
@valyala Hi, I have the same need here. 
I'm trying to only install vmagent on my work cluster[that's all I need, just use it as a metric collector] and upload all metric data to my global cluster, so all the recording work would have to be executed in global vm cluster.
But with more and more work cluster, I'm thinking let work cluster upload their metrics after recording. Since vmagent doesn't support rules, only vmalert do. I need to increase a vmalert service on cluster, and vmalert also need a datasource, so I need to replace vmagent with a single victoriaMetrics.[Is that right?]

So the components on work cluster become more and more complicated, is there any plan to implement Prometheus recording rules in vmagent now?

**Comment by kzhou1994** [comment]
vmagent现在支持rules了吗？

**Comment by Haleygo** [comment]
> vmagent现在支持rules了吗？

@kzhou1994 No, and it's not in the plan.
Instead, check [stream-aggregation](https://docs.victoriametrics.com/stream-aggregation/#recording-rules-alternative) in vmagent, it can replace some recording rules.

**Comment by kzhou1994** [comment]
1、有一个hh3cCBQoSQueueMatchedBytes指标，指标包含instance标签
2、有一个hh3cCBQoSApplyObjectMainSite指标，指标包含instance标签
3、需要根据相同的instance标签，把hh3cCBQoSApplyObjectMainSite指标中的hh3cCBQoSApplyObjectIndex标签，插入hh3cCBQoSQueueMatchedBytes指标中

我的需求如上，

写了以下stream-aggregation规则：

- name: 'test'
  match: 'hh3cCBQoSQueueMatchedBytes{instance=~".+"}'
  interval: 1m
  input_relabel_configs:
    - source_labels: [instance]
      action: replace
      target_label: hh3cCBQoSApplyObjectIndex
      replacement: `hh3cCBQoSApplyObjectMainSite{instance="$1"}`
  outputs: [total]
  keep_metric_names: true
  
  但是报错了，好像不支持使用Prometheus查询表达式来动态获取标签值，如果是Prometheus，则可以直接使用rule：
  groups:
- name: test
  rules:
  - record: hh3cCBQoSQueueMatchedBytes_ifIndex
    expr: hh3cCBQoSQueueMatchedBytes * on (hh3cCBQoSApplyObjectIndex,instance) group_left (hh3cCBQoSApplyObjectMainSite) hh3cCBQoSApplyObjectMainSite

**Comment by hagen1778** [comment]
@kzhou1994 could you please update you comment by translating it to English? Please note that English is the official language for VictoriaMetrics community: questions, answers, interfaces and documentation are provided in English.
