### ISSUE TITLE
vmagent: streaming aggregation

### ISSUE THREAD

**Issue by danmaasrbx** [VictoriaMetrics/VictoriaMetrics#3460]
**Is your feature request related to a problem? Please describe.**
Some of our metrics sources produce data with higher cardinality than we need. For example, node_exporter reports CPU usage per cpu core, when we only really care to know CPU usage per machine. Because we use machines with 64 cores, we are processing 64x more data than we really need. (note: in most cases, we cannot easily re-configure the metrics source to perform its own pre-aggregation).

We would like a way to tell vmagent to aggregate incoming metrics along certain label dimensions, and push only the aggregated data out. 

**Describe the solution you'd like**
Telegraf's "BasicStats" aggregator plugin is similar to what we need:
https://github.com/influxdata/telegraf/blob/release-1.14/plugins/aggregators/basicstats/README.md

Ideally, we would specify a regex to match metric names, a set of label(s) to aggregate over, and the aggregation outputs we want.

Example of what the configuration might look like:

```
  - name: cpu-metrics-aggregator
    interval: 1m
    aggregations:
    - match: "node_cpu_.*"
      aggregate_on_labels: ["instance_id", "core"]
      aggregate_outputs: ["sum", "count", "min", "max", "avg", "p90", "p99"]
```

Then, if this vmagent receives metrics that look like this: (note: this may include metrics from *different scrape targets*... the aggregator needs to operate on the full set of metrics available to the vmagent fleet, *not just one individual scrape target*)
```
node_cpu_time_seconds{region="us-east", instance_id="foo", core="0"} 1234
node_cpu_time_seconds{region="us-east", instance_id="foo", core="1"} 4321
node_cpu_time_seconds{region="us-east", instance_id="bar", core="0"} 5678
node_cpu_time_seconds{region="us-east", instance_id="bar", core="1"} 8765
```

It outputs metrics that look like this:
```
# output of cpu-metrics-aggregator on (instance_id, core)
# = sum(...) without (instance_id, core)
node_cpu_time_seconds_sum{region="us-east"} 19998
# = min(...) without (instance_id, core)
node_cpu_time_seconds_min{region="us-east"} 1234
# = max(...) without (instance_id, core)
node_cpu_time_seconds_max{region="us-east"} 8765
# etc...
```

Note: It is important that this system can handle arbitrary metric names. We should *not* have to list specific metric names to apply the aggregation on, because we might not know those names ahead of time (the "match" expression could be ".*"). The aggregation should be triggered by the presence of the label(s).

**Describe alternatives you've considered**
Today, we use recording rules to compute aggregations. This has two drawbacks: first, we still pay the cost of ingesting and storing the high-cardinality metrics, even though no charts or alerts will ever query them. Second, recording rules evaluate inefficiently. They load a large amount of data and stress CPU/memory/network bandwidth, even though our rules only need to look at the "freshest" data samples.

We are experimenting with M3DB's aggregator component and/or Telegraf to perform streaming aggregation. We would prefer if vmagent could take care of this directly.

**Comment by zekker6** [comment]
@danmaasrbx As another workaround you could set up VMSingle with short retention in order to store unaggregated metrics for recording rules and write recording results into primary storage.
This will allow avoiding storing large amounts of data that you don't need by cost of adding another component and making overall setup a bit more complex.

**Comment by danmaasrbx** [comment]
Thanks Zekker6 - We've actually implemented what you describe - we call it the "hot/cold" architecture. However, it did not help as much as we expected. In particular, the performance of recording rules on the "hot" cluster is still a major bottleneck, even though it is scaled quite large.

**Comment by abursavich** [comment]
We would also like to have automated aggregation, as mentioned, with the ability to drop unnecessary labels.

To focus on additional, tangential functionality... In general, we would like to have several tiers that aggregate up and have different retention periods. The aggregation types would depend on the metric type (gauge, counter, histogram, etc.). Exactly how this would be structured would depend on the workload, but as a rough example for something running in multiple Kubernetes clusters:

- raw pod metrics are retained for 3d
- pod metrics are aggregated up to a (cluster, job, foo) level and retained for 14d
- (cluster, job, foo) metrics are aggregated up to a (cluster, job) level and retained for 90d
- (cluster, job, foo) metrics are aggregated up to global (job, foo) level and retained for 180d
- global (job, foo) metrics are aggregated up to a global job level and retained for 365d

We would like to achieve something sane by default without requiring users to handwrite a bunch of recording rules for every metric they add. We have some ideas for how to achieve this within the current functionality of VM, but it would involve a lot of work on our end to automate recording rule generation.

**Comment by valyala** [comment]
The commit fa13bbc48a4cfe4683c2f6101029a0ff20f6b72a adds initial support for streaming aggregation. It is possible to evaluate it by building `vmagent` from this commit according to [these instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and setting up the streaming aggregation according to [these docs](https://docs.victoriametrics.com/stream-aggregation.html).
Another option is to use `vmagent` Docker image docker.io/victoriametrics/vmagent:heads-public-single-node-0-gfafece1af .

Here is an example config for aggregating the metrics ending with `_total` (aka [counters](https://docs.victoriametrics.com/keyConcepts.html#counter)) by 5 minute intervals:

```yaml
- match: '{__name__=~".+_total"}'
  interval: 5m
  outputs: [total]
```

By default the aggregated output metrics have the following suffix for this config: `:5m_total` according to [output metric naming convention](https://docs.victoriametrics.com/stream-aggregation.html#output-metric-names). For example, the 5-minute aggregate for the `http_requests_total` metric name is `http_requests_total:5m_total`. The output metric name and labels can be changed to any desired name with relabeling according to [these docs](https://docs.victoriametrics.com/stream-aggregation.html#relabeling).

The `outputs` section can contain different aggregations from [this list](https://docs.victoriametrics.com/stream-aggregation.html#aggregation-outputs). For example, `outputs: [min, max, avg]` would calculate the minimum, the maximum and the average value for the input metrics.

By default all the labels from the input metrics are preserved in the aggregated output metrics. This behavior can be changed with `by` and `without` sections according to [these docs](https://docs.victoriametrics.com/stream-aggregation.html#aggregating-by-labels). For example, the following config emits summary `http_requests_total` counter per each combination of `(cluster, namespace, job)` labels every 60 seconds:
```yaml
- match: http_requests_total
  by: [cluster, namespace, job]
  outputs: [total]
  interval: 60s
```

This stream aggregation functionality will be included in the next release.

**Comment by valyala** [comment]
[Streaming aggregation](https://docs.victoriametrics.com/stream-aggregation.html) is available in vmagent and in single-node VictoriaMetrics starting from [v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by hagen1778** [comment]
Similar feature request for evaluating aggregations on scrape time in Prometheus - https://github.com/prometheus/prometheus/issues/394.
