### ISSUE TITLE
accept inf value in MetricsQL function parameters

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#3461]
**Is your feature request related to a problem? Please describe.**
I noticed that functions like `limitk()` do not understand `inf` (for the k parameter).  We can't tie such parameters to a simple Grafana dashboard variable having values like [100, 1000, inf].

**Describe the solution you'd like**
Magnitude parameters should understand `inf` and `-inf`.

**Describe alternatives you've considered**
Using arbitrary large numbers.  In contrast, using `inf` is future-proof, and conveys explicit intention (to the person reading the query, the person seeing the value in a graph URL link, etc.).

**Comment by valyala** [comment]
The commit e272a0ec78b3c05c6f17cbb608adf90849218928 adds support for passing `inf` values to functions, which accept numeric args for limiting the number of output time series. This commit will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics accepts `inf` values at functions, which limit the number of output time series, starting from [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
