### ISSUE TITLE
Provide Azure Blob details and sample in vmbackup

### ISSUE THREAD

**Issue by linkinchow** [VictoriaMetrics/VictoriaMetrics#3463]
**Is your feature request related to a problem? Please describe.**
Provide example how to use Azure Blob in vmbackup

**Describe the solution you'd like**
I only see below short description. What does "bucket" mean here? storage account name or container name? Can you please provide an example?
[Azure Blob Storage](https://azure.microsoft.com/en-us/products/storage/blobs/). Example: azblob://<bucket>/<path/to/backup>

In addition, I only see env variable method to set credentials. Any method to use file? Can you please provide example?
For Azure storage either set env variables AZURE_STORAGE_ACCOUNT_NAME and AZURE_STORAGE_ACCOUNT_KEY, or AZURE_STORAGE_ACCOUNT_CONNECTION_STRING.

**Describe alternatives you've considered**

**Additional context**

**Comment by zekker6** [comment]
Hi @linkinchow 

> I only see below short description. What does "bucket" mean here? storage account name or container name? Can you please provide an example?

"bucket" here will be container name in azure terms. Storage account name will be passed as env `AZURE_STORAGE_ACCOUNT_NAME` variable.

> In addition, I only see env variable method to set credentials. Any method to use file? Can you please provide example?
Currently, there is no support to set credentials via file. Could you describe which credentials you need to pass as a file in your use-case?

**Comment by valyala** [comment]
FYI, docks for Azure backup / restore have been updated in the commit ebcb4ab617da2d44310793da676ab4c033af5c5d . See the updated docs below:

* [vmbackup](https://docs.victoriametrics.com/vmbackup.html)
* [vmrestore](https://docs.victoriametrics.com/vmrestore.html)

Closing this issue as addressed.

@linkinchow , feel free re-opening it or creating new one if there are other Azure-related issues exist either in docs or in vmbackup / vmrestore functionality.
