### ISSUE TITLE
VMAlert memory usage rise to 90% from 25% after upgrading to v1.83.1

### ISSUE THREAD

**Issue by vvxxvvxx** [VictoriaMetrics/VictoriaMetrics#3464]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.
We did a victoria metrics version upgrade yesterday from v1.79.3 to v1.83.0. After the upgrade, the memory usage of our VMAlert instances increased from previous 25% to a crazy 90%+ immediately. you could see the graph as below.

![image](https://user-images.githubusercontent.com/48271609/206370089-c3bd565c-4406-47ec-b62b-dcd820cc072a.png)

**Expected behavior**
no memory spike during and after upgrading to a new victoria metrics version.

**Logs**
Check if any warnings or errors were logged by VictoriaMetrics components
or components in communication with VictoriaMetrics (e.g. Prometheus, Grafana).

**Screenshots**

For VictoriaMetrics health-state issues please provide full-length screenshots 
of Grafana dashboards if possible:
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

See how to setup monitoring here:
* [monitoring for single-node VictoriaMetrics](https://docs.victoriametrics.com/#monitoring)
* [monitoring for VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring)

**Version**
memory usage spike happened during and after upgrading to v1.83.1 from v1.79.3.

**Comment by ebensom** [comment]
The memory usage increase can be a side-effect of this change in vmalert:
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3149

**Comment by f41gh7** [comment]
Hello, can you collect and share memory profile for vmalert [doc](https://docs.victoriametrics.com/#profiling)

 It would be great if you share profiles for 1.83 and 1.79 versions.

**Comment by f41gh7** [comment]
> Hi @f41gh7 , will performing this memory profiling impact anything (e.g. current performance)?

 No, memory profiling is instant and has no impact on performance. It's safe to execute on production env.

**Comment by hagen1778** [comment]
Hi @vvxxvvxx! The memory usage increase is likely caused by:
```
FEATURE: [vmalert](https://docs.victoriametrics.com/vmalert.html): add experimental feature for displaying last 10 states of the rule (recording or alerting) evaluation. The state is available on the Rule page, which can be opened by clicking on Details link next to Rule's name on the /groups page.
```

In absolute numbers, about what increase in memory usage do we talk?

**Comment by vvxxvvxx** [comment]
Hi @hagen1778 , another issue is during the upgrade to v1.83.1 from v1.79.3, or upgrade to v1.84.0 from v1.83.1, the recording rules got incorrect results, but using raw metrics which are to compute the recording rule was good. Is it also caused by the FEATURE you mentioned?
for example, this recording rule as below got value `-1` during the upgrade.
![image](https://user-images.githubusercontent.com/48271609/206690651-e1189a7d-60dd-4175-b2bd-201d980bca41.png)

but using its raw metrics, no `-1` value during upgrade.
![image](https://user-images.githubusercontent.com/48271609/206690769-fd914fdf-51a5-46aa-abc9-f8d61702259c.png)

It's same for other recording rules, their results were all different during upgrade from the results computed directly using raw metrics.

**Comment by hagen1778** [comment]
> Is it also caused by the FEATURE you mentioned?

No, it is orthogonal.

>  another issue is during the upgrade to v1.83.1 from v1.79.3, or upgrade to v1.84.0 from v1.83.1, the recording rules got incorrect results, 

I am not sure this is caused by the upgrade. The difference between query evaluation and recording rule can be explained by delayed data - see https://docs.victoriametrics.com/vmalert.html#troubleshooting
From your screenshot it is unclear what is the `step` of the executed queries and what is the evaluation interval of the recording rule you mention.

**Comment by f41gh7** [comment]
Related PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3467

**Comment by valyala** [comment]
FYI, `vmalert` should use lower amounts of RAM and CPU starting from [v1.85.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by vvxxvvxx** [comment]
Hi @valyala @f41gh7 , do you know if v1.85.0 also contains below security changes which are mentioned in 1.79.6
```
SECURITY: update Go builder from v1.19.3 to v1.19.4. See [the changelog](https://github.com/golang/go/issues?q=milestone%3AGo1.19.4+label%3ACherryPickApproved).

SECURITY: update base Docker image for VictoriaMetrics components from Alpine 3.16.2 to Alpine v3.17.0. See [the changelog](https://alpinelinux.org/releases/).
```

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to re-open if the issue still remains.
