### ISSUE TITLE
wrong estimation of scrape interval lead to incorrect query result

### ISSUE THREAD

**Issue by lichuan0620** [VictoriaMetrics/VictoriaMetrics#3465]
**Describe the bug**

Our setup: a VM cluster with 5 storage nodes. Data replication is set to 3.

When doing range queries with `step` close to the actual scrape interval, the query result within the same time window would change with each request. Parts of some time series were missing.

For example:

![wrong-query-example](https://user-images.githubusercontent.com/7102510/206389710-4a6575d8-98f2-4902-86c4-dbe2a722094a.jpeg)

We expect our container count to remain relatively stable but we can see it jitters repeatedly on the graph. 

We also have the following observations:

* The chance of this problem appearing increases as the number of selected time series increases. 
* If we set `step` to be at least two times the actual scrape interval, the problem would go away.

After inspecting, we suspected that this has to do with [how VM calculate scrape interval](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8162e4ee3f79764ab34d621e565a6e9dfb613f40/app/vmselect/promql/rollup.go#L703-L729). I'll illustrate with an example. Let's say we have the a time series with samples on the following timestamps:

```
0s    30s    60s    90s    120s
```

After distributing to two Storage node:

```
Storage 0: 0s    30s    60s    90s    120s
Storage 1: 0s    30s    60s    90s    120s
```

What vmselect retrieved:

```
0s 0s    30s 30s    60s 60s    90s 90s    120s 120s
```

`getScrapeInterval` would think the data above has a scrape interval of 18s (by taking p60), and in turn cause VM to think there is a gap or NaN in between each sample pair, thus causing the problem described above.

We can confirm this because we could get around this problem by setting dedup to 1 second on vmselect or using larger `step`.

**To Reproduce**

Set up a VM cluster with data replication larger than one. Scrape some data in 30s intervals. Query the data in large quantity with `step` set to 30s.

**Expected behavior**

Correct query result without specific `step` or extra configuration.

**Logs**

**Screenshots**

**Version**

v1.73.1-cluster

**Used command-line flags**

**Comment by lichuan0620** [comment]
We should be able to fix this by removing the `dedupInterval > 0` condition in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8162e4ee3f79764ab34d621e565a6e9dfb613f40/app/vmselect/netstorage/netstorage.go#L530, but I haven't tested it. Or we could add a 1-second dedup by default.

**Comment by lichuan0620** [comment]
@jianglinjian

**Comment by zekker6** [comment]
@lichuan0620 Could you check if your `vmselect` has `-dedup.minScrapeInterval=1ms` flag set?
When replication is used vmselect needs to deduplicate endpoints received from vmstorages. Currently, it has been picking random sample if there were multiple datapoints with same timestamp. This could lead to inconsistent results among requests. 
This PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3421 will change this behaviour to always pick datapoint with higher value. This will make query results consistent in cases when there are multiple data points with same timestamps stored.

**Comment by lichuan0620** [comment]
> Could you check if your vmselect has -dedup.minScrapeInterval=1ms flag set?

**Comment by lichuan0620** [comment]
@zekker6 
> Could you check if your vmselect has -dedup.minScrapeInterval=1ms flag set?

We did not set dedup when the problem occurred. We did get around the problem by setting it to 1s.

> This PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3421 will change this behaviour to always pick datapoint with higher value. This will make query results consistent in cases when there are multiple data points with same timestamps stored.

Yes, looks like this would work.
