### ISSUE TITLE
Queries return no results after gap unless timespan starts before gap

### ISSUE THREAD

**Issue by AdmiralNemo** [VictoriaMetrics/VictoriaMetrics#3469]
Yesterday, one of my systems being scraped by vmagent was offline for a couple of hours.  During this time, of course, vmagent was unable to scrape any metrics from it.  Once the system was back up, vmagent resumed scraping metrics and sending them to Victoria Metrics (single instance) via the Prometheus remote write protocol.  Unfortunately, Victoria Metrics has started behaving strangely with respect to those metrics: any query for a metric that was missing while the system was down returns no results, UNLESS the time span of the query starts BEFORE the system went offline.  This affects both `/api/v1/query` and `/api/v1/export`.

The outage started 2022-12-09 20:47 UTC and ended 2022-12-10 01:20 UTC.

Here's an example showing data before and after the gap:

```
curl -g -D /dev/stderr 'localhost:8428/api/v1/export?match[]=homeassistant_sensor_temperature_celsius{entity="sensor.outdoor_temperature"}&start=2022-12-09T20:45:00Z&end=2022-12-10T01:22:00Z'
HTTP/1.1 200 OK
Content-Type: application/stream+json; charset=utf-8
X-Server-Hostname: mtrcs0.pyrocufflink.red
Date: Sat, 10 Dec 2022 23:13:36 GMT
Content-Length: 349

{"metric":{"__name__":"homeassistant_sensor_temperature_celsius","job":"homeassistant","instance":"homeassistant.pyrocufflink.blue:443","domain":"sensor","entity":"sensor.outdoor_temperature","friendly_name":"Outdoor Temperature"},"values":[3.2,3.2,null,2.7,2.7],"timestamps":[1670618732913,1670618792913,1670618852913,1670635232913,1670635292913]}
```

I can leave off the `end` query parameter and the export returns timestamps all the way up until the current time.

However, if the `start` query parameter refers to a time _after_ the outage, no data are returned at all:

```
curl -g -D /dev/stderr 'localhost:8428/api/v1/export?match[]=homeassistant_sensor_temperature_celsius{entity="sensor.outdoor_temperature"}&start=2022-12-10T01:20:00Z'
HTTP/1.1 200 OK
Content-Type: application/stream+json; charset=utf-8
X-Server-Hostname: mtrcs0.pyrocufflink.red
Date: Sat, 10 Dec 2022 23:15:02 GMT
Content-Length: 0
```

(Note that the `start` parameter here is a timestamp returned in the export above that had a value of 2.7)

I have tried restarting the Victoria Metrics service, deleting the `cache` directory (and restarting again), and forcing a merge for the current partition, but nothing has helped.

Other metrics unrelated to this system appear to be unaffected.

Victoria Metrics version: 1.78.0
vmagent version: 1.78.0

**Comment by valyala** [comment]
@AdmiralNemo , thanks for the detailed bugreport!

Could you upgrade to the latest release - [v1.84.0 now](https://docs.victoriametrics.com/CHANGELOG.html#v1840) - and see whether this helps fixing the issue? It is safe upgrading directly to this release and then downgrading to `v1.78.0` if this won't help - see [how to upgrade VictoriaMetrics](https://docs.victoriametrics.com/#how-to-upgrade-victoriametrics). This issue may be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3309 .

Try also collecting and comparing traces returned by VictoriaMetrics for both queries - see [how to collect query traces](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#query-tracing). You can post query traces here, so they could be investigated by us.

**Comment by AdmiralNemo** [comment]
Interestingly, a few hours after I opened this ticket, everything apparently returned to normal.  I make the exact same requests as before, but Victoria Metrics now returns data where it did not earlier.  I did not make any further changes to my deployment, so I do not know how it got fixed.
