### ISSUE TITLE
VM Kubernetes Operator

### ISSUE THREAD

**Issue by klebediev** [VictoriaMetrics/VictoriaMetrics#347]
With introducing `vmagent` and `vmalert` VictoriaMetrics may be used as a replacement for Prometheus. 
Taking into account a lot of existing Prometheus installations on k8s clusters use prometheus-operator, are there any plans to implementVictoriaMetrics k8s operator with CRDs similar to those implemented in [prometheus-operator](https://godoc.org/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1)?
I guess this would speed up adoption of VM.

**Comment by valyala** [comment]
Yes, there are such plans. @ctrlok may provide more details.

**Comment by tenmozes** [comment]
hi please try https://github.com/VictoriaMetrics/operator, it’s fully supported by opensource community and users of victoria metrics so please try, review and contribute
