### ISSUE TITLE
retentionPeriod less a month

### ISSUE THREAD

**Issue by varuzam** [VictoriaMetrics/VictoriaMetrics#348]
**Is your feature request related to a problem? Please describe.**
It would be nice to have possibility to configure retentionPeriod less a month.

**Describe the solution you'd like**
Configure the parameter in such manner: 1h, 1d, 1m, 1y etc

**Comment by valyala** [comment]
Duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/17 .

**Comment by valyala** [comment]
FYI, the following commits add support for `-retentionPeriod` smaller than one month:

* for single-node VictoriaMetrics - 5bfd4e62188f74606b463aab3135beb17a8456c8
* for cluster VictoriaMetrics - 0db7c2b500940d278c7c71bb7b0dd6ec9b097b33

These commit allow to set:
- fractional `-retentionPeriod`, i.e. `-retentionPeriod=0.5` sets retention to a half of month
- `-retentionPeriod` with suffixes such as `d` (days), `w` (weeks) or `y` (years). For example, `-retentionPeriod=5d` would set retention period to 5 days.

See more details about retention in [the docs](https://victoriametrics.github.io/#retention).

These commits can be tested right now by building VictoriaMetrics from sources according to the following docs:

* [how to build single-node VictoriaMetrics](https://victoriametrics.github.io/#how-to-build-from-sources)
* [how to build cluster version of VictoriaMetrics](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#building-from-sources).
