### ISSUE TITLE
Support `-search.latencyOffset` as query param on vmselect level

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3481]
**Is your feature request related to a problem? Please describe.**
Would be great to have an option to configure `-search.latencyOffset` on query level, instead of global setting.

**Describe the solution you'd like**
To support query param `latency_offset` on vmselect level, so query issuer could decide its value on per-query basis.

**Additional context**
This feature would be useful for recording and alerting rules.

**Comment by valyala** [comment]
The commit 86dae56bd0296c32962bc84c6c6c07b124bd67f2 adds support for `latency_offset` query arg, which can be passed to [/api/v1/query](https://docs.victoriametrics.com/keyConcepts.html#instant-query) and [/api/v1/query_range](https://docs.victoriametrics.com/keyConcepts.html#range-query) and override the value passed in `-search.latencyOffset` command-line flag. This commit will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics and `vmselect` accept `latency_offset` query arg at `/api/v1/query` and `/api/v1/query_range` starting from [v1.85.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
