### ISSUE TITLE
count_values() with labels preserved

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#3485]
**Is your feature request related to a problem? Please describe.**
I'd like to display the count and value of distinct values for each labelset.

**Describe the solution you'd like**
A variant of `count_values("val_label", q)` that preserves the labels of the `q`.

**Describe alternatives you've considered**
I haven't found a workaround yet.

**Comment by hagen1778** [comment]
Hi @belm0! But `count_values` is an [aggregate function](https://docs.victoriametrics.com/MetricsQL.html#aggregate-functions) - it aggregates time series with **different** label sets. The result of the aggregation can't contain original labels, unless `by` or `without` modifiers are specified.

**Comment by belm0** [comment]
Thank you.  It sounds like I can do `count_values by(label) ("val")`.
