### ISSUE TITLE
IP range Allowlist for vmauth

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3491]
To protect streaming protocols (TCP/UDP where you can not easily send auth details) and add additional protection for HTTP protocols.

Allow specifying IPs or IP ranges and limit access only from these addresses.

**Comment by valyala** [comment]
`vmauth` [enterprise](https://docs.victoriametrics.com/enterprise.html) gains support for global and per-user ip filters in the commit   https://github.com/VictoriaMetrics/VictoriaMetrics-enterprise/commit/2f08ed3be252354822b7d24cccbb03d76e429b62 . This commit will be included in the next release. See [the docs for IP filters in vmauth](https://docs.victoriametrics.com/vmauth.html#ip-filters).

**Comment by valyala** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth.html) supports filtering incoming requests by IP starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmauth.html#ip-filters) for details. Closing the feature request as done.
