### ISSUE TITLE
-usePromCompatibleNaming is ignored unless there are extraLabels or relabel configs

### ISSUE THREAD

**Issue by dustbyrn** [VictoriaMetrics/VictoriaMetrics#3493]
**Describe the bug**
"vmagent -usePromCompatibleNaming" does not rewrite incompatible labels of pushed metrics unless other configuration is present.  I had to add 1 -remoteWrite.label to get the prom compatible relabeling to happen.  Looking at the code here: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a8b8e23d6851d22c0b8ba3f5c40185be8d56ec08/app/vmagent/remotewrite/relabel.go#L89
I think it will also work if there's an relabel configs, but I didn't try that.

**To Reproduce**

1. run vmagent with -usePromCompatibleNaming but no -remoteWrite.label and no relabel configs (using -remoteWrite.url to push metrics upstream)
2. push metrics with prom incompatible labels to vmagent on the InfluxDB api
3. no labels get rewritten/changed

**Workaround**
run vmagent with -usePromCompatibleNaming AND -remoteWrite.label OR relabel configs 

**Expected behavior**
Incompatible labels should get rewritten when -usePromCompatibleNaming is specified.

**Version**
1.83.0

**Used command-line flags**
-promscrape.config
-promscrape.configCheckInterval
-remoteWrite.url
-usePromCompatibleNaming

and then to make it work:
-remoteWrite.label

**Comment by valyala** [comment]
@dustbyrn , thanks for the bugreport! The bug should be fixed in [vmagent v1.85.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed then.
