### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3495]
**Describe the bug**
![image](https://user-images.githubusercontent.com/799021/208253527-04b20031-e619-44f5-aca3-8df0917afbf1.png)

**To Reproduce**
See it here:
https://github.com/VictoriaMetrics/VictoriaMetrics

**Expected behavior**
Picture should be displayed

**Comment by denisgolius** [comment]
Hello!
It could be the problem with Github or CDN. You can try to use our [documentation page](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#sending-metrics-to-datadog-and-victoriametrics) instead of using docs from repository.

**Comment by KES777** [comment]
@denisgolius The problem is that your picture inside `/docs` on github. But on main your site it is in root `/`

**Comment by denisgolius** [comment]
> @denisgolius The problem is that your picture inside `/docs` on github. But on main your site it is in root `/`

I don't see any issue with image if I open https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/README.md#sending-metrics-to-datadog-and-victoriametrics or if I run curl query.

**Comment by KES777** [comment]
@denisgolius Please compare how you duplicate `logo.png` at root `/` and at `/doc`.

Probably you should similarly duplicate those two broken `.png` files in `/`.

PS. Just closing the issue does not resolve problem.

**Comment by hagen1778** [comment]
@valyala I see that the link to image was changed by you in 36584ef52cd74d64809d113dd50312fc72cfee1a
Was it intentional or did `make docs-sync` fail for you?

**Comment by valyala** [comment]
> I see that the link to image was changed by you in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/36584ef52cd74d64809d113dd50312fc72cfee1a
Was it intentional or did make docs-sync fail for you?

The `docs/` prefix has been removed from image urls in this commit by mistake.

**Comment by valyala** [comment]
The issue has been fixed in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7ca49290b621b4032ec543c22a823a7f4b571cc1 - now images are correctly displayed at  https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-send-data-from-datadog-agent . Closing the issue as fixed.
