### ISSUE TITLE
vmagent couldnt retrieve prom/cloudwatch exporter metrics

### ISSUE THREAD

**Issue by dnull88** [VictoriaMetrics/VictoriaMetrics#350]
**Describe the bug**
vmagent couldnt scrape metrics from cloudwatch exporter ([prometheus/cloudwatch_exporter](https://github.com/prometheus/cloudwatch_exporter))
It raises error, because cannot parse tags. All cloudwatch metrics has a comma after last label value, example:
aws_ecs_cpuutilization_average{job="aws_ecs",instance="\",service_name="mr-prod",cluster_name="cluster1"**,**} 3.3049095912235575 1582797660000

It generates error:

**logs**
`2020-02-27T10:05:16.763Z	error	VictoriaMetrics/lib/protoparser/prometheus/parser.go:187	error when scraping "http://cloudwatch-mr.***-prod.int:80/metrics": cannot unmarshal Prometheus line "aws_ecs_cpuutilization_average{job=\"aws_ecs\",instance=\"\",service_name=\"mr-prod\",cluster_name=\"cluster1\",} 3.3049095912235575 1582797660000": cannot unmarshal tags: missing value for tag "} 3.3049095912235575 1582797660000"`

**Comment by valyala** [comment]
The bug should be fixed in the commit 1d7ab78b552ef60e190672c7344560822a719bfa . @dnull88 , could you build `vmagent` from this commit and verify whether it fixes the issue? See [build instructions for vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#how-to-build-from-sources).

**Comment by svesh** [comment]
I tested this fix today. Works fine. Thank you.

**Comment by valyala** [comment]
The bugfix has been included in the release [v1.34.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
