### ISSUE TITLE
Dockerhub latest tags

### ISSUE THREAD

**Issue by fretb** [VictoriaMetrics/VictoriaMetrics#3505]
When using the docker image from dockerhub, I like to use the "latest" tag, however, this appears to be a reference to the latest enterprise image now. Resulting in the container not starting up without passing `-eula` as command.

It would be nice to have differentiating latest tags, e.g. latest-ee and latest-ce, being the latest enterprise edition, and the latest community edition.

This way, if you use the community edition, you don't have to worry about accidentaly pulling the latest enterprise image when updating from latest.

**Comment by dit101** [comment]
I'm having this issue also with the container not starting. It happened before and was fixed so maybe it's the same issue?https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1135

**Comment by valyala** [comment]
See also the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2911

**Comment by valyala** [comment]
VictoriaMetrics code, which is responsible for publishing Docker images at DockerHub, has been updated - now the latest images are published with the following tags:

* `latest` - all the open source VictoriaMetrics components except of cluster components - [victoria-metrics](https://docs.victoriametrics.com/), [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), [vmbackup](https://docs.victoriametrics.com/vmbackup.html), [vmrestore](https://docs.victoriametrics.com/vmrestore.html), [vmctl](https://docs.victoriametrics.com/vmctl.html)
* `cluster-latest` - all the open source [cluster components of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) - `vminsert`, `vmselect` and `vmstorage`
* `enterprise-latest` - all the [enterprise](https://docs.victoriametrics.com/enterprise.html) VictoriaMetrics components except of cluster components - [victoria-metrics](https://docs.victoriametrics.com/), [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), [vmbackup](https://docs.victoriametrics.com/vmbackup.html), [vmrestore](https://docs.victoriametrics.com/vmrestore.html), [vmctl](https://docs.victoriametrics.com/vmctl.html), [vmgateway](https://docs.victoriametrics.com/vmgateway.html), [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html).
* `enterprise-cluster-latest` - all the [enterprise](https://docs.victoriametrics.com/enterprise.html) [cluster components](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) of VictoriaMetrics - `vminsert`, `vmselect` and `vmstorage`.

Closing this feature request as done.

**Comment by tiny6996** [comment]
it appears the latest tag is pointing at [heads-public-single-node-0-g1d7b5cb83](https://hub.docker.com/layers/victoriametrics/victoria-metrics/heads-public-single-node-0-g1d7b5cb83/images/sha256-f82b174a47ac17b76f3a260e71fcda4ad3f92451344f90cf1294a2f47ca5f666?context=explore) instead of 1.85.3 should this be the case or should it be pointing at 1.85.3?

**Comment by fretb** [comment]
> VictoriaMetrics code, which is responsible for publishing Docker images at DockerHub, has been updated - now the latest images are published with the following tags:
> 
>     * `latest` - all the open source VictoriaMetrics components except of cluster components - [victoria-metrics](https://docs.victoriametrics.com/), [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), [vmbackup](https://docs.victoriametrics.com/vmbackup.html), [vmrestore](https://docs.victoriametrics.com/vmrestore.html), [vmctl](https://docs.victoriametrics.com/vmctl.html)
> 
>     * `cluster-latest` - all the open source [cluster components of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) - `vminsert`, `vmselect` and `vmstorage`
> 
>     * `enterprise-latest` - all the [enterprise](https://docs.victoriametrics.com/enterprise.html) VictoriaMetrics components except of cluster components - [victoria-metrics](https://docs.victoriametrics.com/), [vmagent](https://docs.victoriametrics.com/vmagent.html), [vmalert](https://docs.victoriametrics.com/vmalert.html), [vmauth](https://docs.victoriametrics.com/vmauth.html), [vmbackup](https://docs.victoriametrics.com/vmbackup.html), [vmrestore](https://docs.victoriametrics.com/vmrestore.html), [vmctl](https://docs.victoriametrics.com/vmctl.html), [vmgateway](https://docs.victoriametrics.com/vmgateway.html), [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html).
> 
>     * `enterprise-cluster-latest` - all the [enterprise](https://docs.victoriametrics.com/enterprise.html) [cluster components](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) of VictoriaMetrics - `vminsert`, `vmselect` and `vmstorage`.
> 
> 
> Closing this feature request as done.

This is awesome, thank you for the speedy fix! Using the stable tag now. :-) 👍
