### ISSUE TITLE
vmui: wrong legend when queries are hidden

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3512]
**Describe the bug**
The legend shows incorrect query when one of the queries is hidden.

**To Reproduce**
Try having two queries plotted in VMUI. Then hide the 1st and check the legend - it will have a title of a hidden query.
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/2902918/208704930-9d4f7493-31bf-4480-93f7-b2f4ae25ed93.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/2902918/208704970-584f0e2f-bcbb-42e6-8ca0-e087c2fe6a84.png">

**Expected behavior**
The legend should correctly show the query.

**Version**
The line returned when passing `--version` command line flag to the binary. For example:
```
$ ./bin/victoria-metrics --version
victoria-metrics-20221220-151843-heads-master-0-g18e55d14c
```

**Comment by valyala** [comment]
The bugfix has been included in [VictoriaMetrics v1.85.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
