### ISSUE TITLE
vmui: properly display e.g. `range` results at Table view

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#3516]
**Describe the bug**

`vmui` doesn't show `range` results at Table view. `range` results are generated by VictoriaMetrics when the query ends with a lookbehind window in square brackets. In this case it is expected that the Table view should show all the samples per each returned time series in the form `sample_value @ sample_timestamp`

**To Reproduce**
1. Navigate to the Table view at `vmui`
2. Execute the query `sum(up)[1h:10m]`
3. Notice the empty response results in the table - see https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?g0.expr=sum(up)%5B1h%3A10m%5D&g0.range_input=30m&g0.end_input=2022-12-21T01%3A22%3A03&g0.step_input=3.886&g0.tab=1&g0.relative_time=last_30_minutes .

**Expected behavior**

The Table must contain all the samples returned by the query in the form `sample_value @ sample_timestamp`. See how Prometheus does this [here](http://demo.robustperception.io:9090/graph?g0.expr=sum(up)%5B1h%3A10m%5D&g0.tab=1&g0.stacked=0&g0.range_input=1h).

**Comment by tve** [comment]
Given how things are presented in the UI I expect the graph, json, and table tabs to display exactly the same data, just in different formats. Currently the json and table tabs are broken IMHO.

**Comment by valyala** [comment]
The issue has been fixed in [v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it then.

> Given how things are presented in the UI I expect the graph, json, and table tabs to display exactly the same data, just in different formats. Currently the json and table tabs are broken IMHO.

@tve , could you open a new issue if you think that `json` and `table` views are still broken in `v1.86.2` release?
