### ISSUE TITLE
Newrelic agent support

### ISSUE THREAD

**Issue by mightydok** [VictoriaMetrics/VictoriaMetrics#3520]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Community need support of newrelic apm agents protocol in victoria metrics
The VM already supports datadog agents, so supporting new agents shouldn't be a problem

**Describe alternatives you've considered**
No

**Additional context**
As i know newrelic agents send metrics over http in json format, thas all i know, need further investigation

**Comment by dmitryk-dk** [comment]
Hi @mightydok ! Do you have any experience to write metrics from newrelic apm agents to any timeseries database?
I want to know how to define URL where newrelic apm agents should write scraped metrics.

**Comment by hagen1778** [comment]
@mightydok or anyone interested in this support. Would you mind taking a look at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4712 and possibly evaluate it for your setup?

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4712 has been merged and will be included into the next release.

**Comment by valyala** [comment]
VictoriaMetrics and [vmagent](https://docs.victoriametrics.com/vmagent.html) can accept data from [NewRelic infrastructure agent](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent) starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-send-data-from-newrelic-agent) for details.

Closing this feature request as done.
