### ISSUE TITLE
Wrong link at template

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3532]
* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)

404

Please provide correct link

**Comment by tenmozes** [comment]
Hi, thank you for the report please use https://grafana.com/grafana/dashboards/10229-victoriametrics/ we will update link soon.

**Comment by KES777** [comment]
@tenmozes Thank you for the correct link.

This is a bit strange: Some graphs does not have data.
![image](https://user-images.githubusercontent.com/799021/209473331-8ce3cdbf-fd9f-48b8-8d1c-a0fa7ad648b0.png)

Could you please provide some tips for me to debug problem?
