### ISSUE TITLE
Implement warnings for ignored options

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3535]
**Is your feature request related to a problem? Please describe.**
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3533#issuecomment-1364676070
```
line 4: field evaluation_interval not found in type promscrape.GlobalConfig; pass -promscrape.config.strictParse=false command-line flag for ignoring unknown fields in yaml config
```

When I provide legitimate option not known to VM, then VM fails. But when I provide `-promscrape.config.strictParse=false` there is not warnings about not known options.

**Describe the solution you'd like**
I want warnings for all not known metrics, because probably there are other unknown metrics at configuration file or just typos, but I do not know about them.

**Comment by hagen1778** [comment]
> I want warnings for all not known metrics, because probably there are other unknown metrics at configuration file or just typos, but I do not know about them.

Isn't this a default behavior right now?
