### ISSUE TITLE
Hide healthy active targets

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3536]
**Describe the bug**
![image](https://user-images.githubusercontent.com/799021/209469599-76069cdd-2e11-4661-b4a1-a6884d9c9d53.png)

When I want to see only `unhealthy` targets, all targets are displayed

**To Reproduce**
http://victoria/targets?endpoint_search=&label_search=&show_only_unhealthy=true

**Expected behavior**
I want to see here empty list, because there is no unhealthy targets

**Version**
```
victoria-metrics-20221220-184303-heads-public-single-node-0-g1d7b5cb83
```

**Comment by dmitryk-dk** [comment]
Hi @KES777! It works correctly. See screenshots below. 
Each job name, can have multiple targets and some of them can be up or down.
In that case when you click unhealthy button you will see all jobs and if there if one of the target is unhealthy you will is it 
<img width="1680" alt="Screenshot 2022-12-28 at 13 37 47" src="https://user-images.githubusercontent.com/12189570/209806365-5dfcdc00-1296-40fe-aa3d-d9b0df715b3c.png">

<img width="1680" alt="Screenshot 2022-12-28 at 13 41 25" src="https://user-images.githubusercontent.com/12189570/209806876-014f7991-c79d-4894-bf72-d43fc8d77386.png">

**Comment by KES777** [comment]
But behavior still is not consistent. When you will use `.*` filter for unhealthy targets, `victoria` will be hidden. But on here (without filter) it is not hidden.

I expect, that if there is not unhealthy targets, no info should be displayed.

**Comment by dmitryk-dk** [comment]
It works per each job name, not per target; that is why the target is always visible

**Comment by KES777** [comment]
Not always. It is hidden, when filter is used. Suppose it should be consistent and always hidden. Because `Unhelthy` is some type of filtering.

**Comment by dmitryk-dk** [comment]
Double checked, and it works as expected. Please reopen if you have any question

**Comment by zekker6** [comment]
Reopening this as we've received more feedback about this behavior and would like to make this more intuitive to the users. It would be more intuitive to hide groups where filters do not match any targets. This also makes vmagent UI behaviour similar to Prometheus, so this will align well with expectations of users migrating from Prometheus.

**Comment by hagen1778** [comment]
@KES777 job rows with all targets healthy won't be displayed when `unhealthy` filter is enabled starting from [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040).
