### ISSUE TITLE
Nothing is displayed for active queries page

### ISSUE THREAD

**Issue by KES777** [VictoriaMetrics/VictoriaMetrics#3538]
**Describe the bug**
![image](https://user-images.githubusercontent.com/799021/209469921-6896153a-298c-4a7d-93b2-df9c7e0dd44d.png)

**To Reproduce**
Go to `/api/v1/status/active_queries`

**Expected behavior**
I expect some info is displayed

**Version**
```
victoria-metrics-20221220-184303-heads-public-single-node-0-g1d7b5cb83
```

**Comment by KES777** [comment]
Hm... there is some top queries, so there should be some active queries too.

![image](https://user-images.githubusercontent.com/799021/209470040-ead2905e-1f94-46e9-a59b-b7f85721275f.png)

**Comment by dmitryk-dk** [comment]
Hi @KES777 ! If you want to see active queries you should run query and then use this api. If you haven't any active queries when you check this api response whould be empty

**Comment by KES777** [comment]
Do you mean `queries in progress`? Which takes 5-10-30 or more seconds.

Seems like I misunderstand `active`. Would it be better, if we clarify that label?

**Comment by dmitryk-dk** [comment]
Yeah, active, mean queries in progress. I think we should update our documentation

**Comment by dmitryk-dk** [comment]
Hi ! I have double checked documentation and 
`/api/v1/status/active_queries - returns a list of currently running queries.`
You can check this information (here)[https://docs.victoriametrics.com/#prometheus-querying-api-enhancements]
So close this issue as resolved
