### ISSUE TITLE
import multi-column CSV lines with null-valued fields

### ISSUE THREAD

**Issue by fluxion-t** [VictoriaMetrics/VictoriaMetrics#3540]
The problem:

When trying to import multi-column CSV data line where there are null values, the API does not show any error, but the line is not imported.

Example: I want to import this line:
str="test,2022-12-25T16:57:12+01:00,10,20,30,,,60,70,80"

where metrics M40 and M50 have no value (null value). When calling the import API with the command

`curl -v -d "$str" 'http://localhost:8428/api/v1/import/csv?format=1:label:mytest,2:time:rfc3339,3:metric:M10,4:metric:M20,5:metric:M30,6:metric:M40,7:metric:M50,8:metric:M60,9:metric:M70,10:metric:M80'
`

there is no sign of error:

```
*   Trying ::1:8428...
* connect to ::1 port 8428 failed: Connection refused
*   Trying 127.0.0.1:8428...
* Connected to localhost (127.0.0.1) port 8428 (#0)
> POST /api/v1/import/csv?format=1:label:mytest,2:time:rfc3339,3:metric:M10,4:metric:M20,5:metric:M30,6:metric:M40,7:metric:M50,8:metric:M60,9:metric:M70,10:metric:M80 HTTP/1.1
> Host: localhost:8428
> User-Agent: curl/7.74.0
> Accept: */*
> Content-Length: 50
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 50 out of 50 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< X-Server-Hostname: bcn-verda
< Date: Mon, 26 Dec 2022 17:46:54 GMT
< 
* Connection #0 to host localhost left intact

```

But data is not imported:

`curl -s http://localhost:8428/api/v1/series -d 'match[]=M10' -d 'start=-1d' | jq`

```
{
  "status": "success",
  "data": []
}
```
The solution I would like:

I would like victoriametrics to be able to accept lines like these. When having many sensors it is very frequent to have some throwing null values, either temporarily or permanently. When two consecutive commas `,,` appear, the value should be interpreted as null.

If instead of two consecutive commas we obtain something like `,null,` or more generically `,word,` perhaps we could interpret this value as null as well, or at least throw an error message when trying to import the line and failing.

Alternatives I tried:

I made tests trying to feed lines with 1) `,,` 2) `,null,` 3)` ,NULL,` 4) `,nan, ` but in none of the cases I got the line imported. 

There is also the alternative of not feeding multi-column lines, so we would not have this problem: either the value exists and is imported or is null and it's not imported. But dealing with multi-column files is very convenient.

Additional context:

/var/syslog does not log anything for the last command. 

Would appreciate any help. Thank you.

**Comment by valyala** [comment]
VictoriaMetrics should properly skip empty fields during [csv import](https://docs.victoriametrics.com/#how-to-import-csv-data) starting from the commit 2cedb3e883e27f899b0403ad0a20a614c0d3c090 . This commit will be included in the next release. In the mean time it is possible to build VictoriaMetrics from this commit according to [the build instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it properly accepts CSV lines with empty fields.
