### ISSUE TITLE
Ask why active merge works for a long time

### ISSUE THREAD

**Issue by sharkpc0813** [VictoriaMetrics/VictoriaMetrics#3546]
**Describe the bug**
Active merge runs for a long time, resulting in high disk usage.
According to the guide, it is assumed that this is because temporary files are created during the merge process. Can this occur for a long period of time?

The strange thing is, `vm_merge_need_free_disk_space` was seen before this phenomenon occurred, but the merge worked even though the disk usage did not decrease. (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1682#issuecomment-938608067)
Is this the intended behavior?

**To Reproduce**
do not know

**Expected behavior**
If this phenomenon is the intended behavior, I'll make an alarm with `vm_merge_need_free_disk_space` before the disk usage rate increases.
Or, I wonder if the disk required for merge can be calculated by a metric.

**Logs**
couldn't collect logs

**Screenshots**

##### active merge works for a long time
<img width="740" alt="64f06986-6558-4610-bd5e-0f1e2ab765de" src="https://user-images.githubusercontent.com/6148396/209590647-103866c9-e2db-4912-b499-eb24ca4b136f.png">

<img width="819" alt="스크린샷 2022-12-27 오전 9 41 29" src="https://user-images.githubusercontent.com/6148396/209590949-89b8b7b7-6616-46a6-b62a-5e9be960621c.png">

##### `vm_merge_need_free_disk_space ` was seen before
![407517ae-76b0-44b2-9da2-9433a9faf07f](https://user-images.githubusercontent.com/6148396/209590643-a9a03491-9e6c-43c7-888e-6d734df2865a.png)

##### Couldn't get any hint from parts & data size
<img width="1276" alt="92f72082-4883-488a-91ab-162d4e18f75e" src="https://user-images.githubusercontent.com/6148396/209590648-ed47a133-b957-48ba-aff2-08fcfd0ee8c9.png">
<img width="1298" alt="스크린샷 2022-12-27 오전 9 34 23" src="https://user-images.githubusercontent.com/6148396/209590650-e7882799-226f-4528-8a99-56d42f6a3c22.png">

**Version**

```
/ # /victoria-metrics-prod --version
victoria-metrics-20211108-135302-tags-v1.69.0-0-g69e655ba7
```

**Used command-line flags**

```
-retentionPeriod=30d 
-promscrape.config=/config/prometheus.yml 
-promscrape.configCheckInterval=30s 
-promscrape.suppressDuplicateScrapeTargetErrors 
-promscrape.suppressScrapeErrors 
-search.maxLookback=30s 
-storageDataPath=/storage 
-httpListenAddr=:80 
-search.logSlowQueryDuration=60s 
-search.maxPointsPerTimeseries=1000000 
-search.maxQueryDuration=180s 
-search.maxQueryLen=1638400 
-search.minStalenessInterval=30s 
-promscrape.maxScrapeSize=150MiB 
-maxLabelsPerTimeseries=50
```

**Comment by dmitryk-dk** [comment]
Hi @sharkpc0813 ! Thank you for your issue. From your graph we can see that you use ceph disks, and merges are depends on the disks speed, so if your disks are slow so the merges can be slow. I think we can't calculate the disk space which is required for merges, because at the same time the san be process different merges. So one possible recommendation is
at least 20% of free storage space at the directory pointed by -storageDataPath command-line flag at vmstorage nodes.

**Comment by valyala** [comment]
See also the related question - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2711

**Comment by sharkpc0813** [comment]
Thanks for the quick check!
I'll register again, If there are any other problems.
