### ISSUE TITLE
HaProxy Number of Connections Explosed

### ISSUE THREAD

**Issue by Whisper40** [VictoriaMetrics/VictoriaMetrics#3552]
**Describe the bug**
On our production environment (which is not used a lot compared to our non production environment), we encouter a problem of high number of connections on Haproxy.
It is causing a lot of latences (timeout etc..).
We use Victoria with cluster mode ( it's why we use haproxy to loadbalance )
We already tried to restart all the cluster without consequences.

(i can't provide grafana monitoring because HAPROXY cannot be accessed due to the number of connections)
**To Reproduce**
I can't tell you... No changes at all, the configuration is working for 1 year now..

**Expected behavior**
We should never see more than 1000 connections ( 800 on our non production environment )

**Logs**

```
LB:
Dec 28 07:58:18 localhost haproxy[7252]: 10.246.140.94:37792 [28/Dec/2022:07:58:18.393] https-sni/1: SSL handshake failure
Dec 28 07:58:18 localhost haproxy[7252]: 10.56.188.205:29832 [28/Dec/2022:07:58:18.393] https-sni/1: SSL handshake failure
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.223:56752 [28/Dec/2022:07:58:17.588] https-sni~ insert_dal/vm-insert-dal-02 11/0/8/850/869 204 113 - - ---- 16167/16167/429/220/0 0/0 "POST /insert/2671119:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.223:46010 [28/Dec/2022:07:58:15.632] https-sni~ insert_dal/vm-insert-dal-02 0/0/2055/771/2826 204 113 - - ---- 16167/16167/428/219/0 0/0 "POST /insert/11520703:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.222:44438 [28/Dec/2022:07:58:06.678] https-sni~ insert_dal/vm-insert-dal-02 23/0/1092/10664/11779 204 113 - - ---- 16167/16167/427/218/0 0/0 "POST /insert/11520703:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.223:35710 [28/Dec/2022:07:58:15.662] https-sni~ insert_dal/vm-insert-dal-02 0/0/2056/740/2796 204 113 - - ---- 16167/16167/426/217/0 0/0 "POST /insert/1388173:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.222:48894 [28/Dec/2022:07:58:17.704] https-sni~ insert_dal/vm-insert-dal-02 16/0/20/717/753 204 113 - - ---- 16167/16167/425/216/0 0/0 "POST /insert/10089093:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.223:34488 [28/Dec/2022:07:58:16.697] https-sni~ insert_dal/vm-insert-dal-02 0/0/1020/741/1761 204 113 - - ---- 16167/16167/424/215/0 0/0 "POST /insert/9934258:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.222:48988 [28/Dec/2022:07:58:17.740] https-sni~ insert_dal/vm-insert-dal-02 20/0/19/679/718 204 113 - - ---- 16167/16167/423/214/0 0/0 "POST /insert/10174259:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.28.113.223:46272 [28/Dec/2022:07:58:17.061] https-sni~ insert_did/vm-insert-did-02 4/0/10/1383/1397 204 113 - - ---- 16167/16167/445/226/0 0/0 "POST /insert/1388173:0/prometheus/api/v1/write HTTP/1.1"
Dec 28 07:58:18 localhost haproxy[7252]: 10.246.140.94:31211 [28/Dec/2022:07:58:18.393] https-sni/1: SSL handshake failure
Dec 28 07:58:18 localhost haproxy[7252]: 10.11.52.76:62165 [28/Dec/2022:07:58:18.458] https-sni/1: SSL handshake failure
Dec 28 07:58:18 localhost haproxy[7252]: 10.56.188.219:60180 [28/Dec/2022:07:58:18.393] https-sni/1: SSL handshake failure
Dec 28 07:58:18 localhost haproxy[7252]: 10.11.52.76:6349 [28/Dec/2022:07:58:18.458] https-sni/1: SSL handshake failure

...

vm-replicate-01
Memory: 9.9G
...
Dec 28 08:54:56 vm-replicate-01 vmagent-prod[35512]: 2022-12-28T07:54:56.735Z        warn        VictoriaMetrics/app/vmagent/remotewrite/client.go:277        couldn't send a block with size 8409 bytes to "1:secret-url:9934258:0": P>
Dec 28 08:54:57 vm-replicate-01 vmagent-prod[35512]: 2022-12-28T07:54:57.426Z        warn        VictoriaMetrics/app/vmagent/remotewrite/client.go:277        couldn't send a block with size 61537 bytes to "1:secret-url:9934258:0": >
...
....

```

**Screenshots**
![image](https://user-images.githubusercontent.com/30440458/209778486-a9420a24-727a-4efb-bb0c-5164b3467eb8.png)
**Version**
```
vm-replicate-01:~# /usr/local/bin/vmagent-prod --version
vmagent-20211022-171207-tags-v1.68.0-0-gf64f62692
```

**Used command-line flags**
```
victoriametrics-agent.service:
ExecStart=/usr/local/bin/vmagent-prod --remoteWrite.tmpDataPath=/srv/data \
                                      --remoteWrite.multitenantURL=https://insert-dal.victoria.domain.fr \
                                      --remoteWrite.multitenantURL=https://insert-did.victoria.domain.fr

storage:
ExecStart=/usr/local/bin/vmstorage-prod -storageDataPath=/srv/data/victoria-storage \
                                                        -memory.allowedPercent=60 \
                                                        -retentionPeriod=3 \
                                                        -dedup.minScrapeInterval=30s

insert:
ExecStart=/usr/local/bin/vminsert-prod -memory.allowedPercent=60 \
    -relabelConfig=/etc/victoria/relabel.yml \
    -replicationFactor=1 \
-storageNode=10.28.113.228:8400,10.28.113.229:8400,10.28.113.230:8400 \
-insert.maxQueueDuration=90s \
```

**Comment by Whisper40** [comment]
Is it related to this vmagent bug ? : https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2552

**Comment by Whisper40** [comment]
95% of connections are coming from replicate-01 and replicate-02
Number of requests :
125780 10.28.113.223
146583 10.28.113.222

**Comment by dmitryk-dk** [comment]
Hi @Whisper40 ! Do you have grafana dashboards for your cluster setup? Because it is hard to understand what cause the issue. You can use our official [dashboards](https://grafana.com/orgs/victoriametrics/dashboards)

**Comment by dmitryk-dk** [comment]
Also as i can see you use old components of vm. It would be better if you can upgrade it to the latest version or to LTS version and check it on your dev environment how it works

**Comment by Whisper40** [comment]
"(i can't provide grafana monitoring because HAPROXY cannot be accessed due to the number of connections)"

Actually i can't upgrade the production without knowing if it will work..
We don't have the problem on out of production

**Comment by dmitryk-dk** [comment]
@Whisper40 can you share full log messages from `vm-replicate-01` and `vm-replicate-01`? Because in the description which you provided there is only part of the log

**Comment by Whisper40** [comment]
It seems that we have more problems
`vm-replicate-01` and `vm-replicate-01` have 20 GB of tmp dir.
We extended the size to 50GB, and now ( few minutes after ) it's full again ! So VictoriaMetrics is crashing

**Comment by dmitryk-dk** [comment]
This folder can grow only if vmagent can't write to the vmstorage

If the remote storage is unavailable, the collected metrics are buffered at -remoteWrite.tmpDataPath. The buffered metrics are sent to remote storage as soon as the connection to the remote storage is repaired. The maximum disk usage for the buffer can be limited with `-remoteWrite.maxDiskUsagePerURL`.

**Comment by Whisper40** [comment]
On vmstorage side we have only these logs : (only vmselect normal ??)
```
Dec 28 17:01:33 vm-storage-did-01 vmstorage-prod[788]: 2022-12-28T16:01:33.484Z        info        VictoriaMetrics/app/vmstorage/transport/server.go:164        accepted vmselect conn from 10.28.113.235:47500
Dec 28 17:01:33 vm-storage-did-01 vmstorage-prod[788]: 2022-12-28T16:01:33.486Z        info        VictoriaMetrics/app/vmstorage/transport/server.go:207        processing vmselect conn from 10.28.113.235:47500
Dec 28 17:03:06 vm-storage-did-01 vmstorage-prod[788]: 2022-12-28T16:03:06.133Z        info        VictoriaMetrics/app/vmstorage/transport/server.go:164        accepted vmselect conn from 10.28.113.235:49152
Dec 28 17:03:06 vm-storage-did-01 vmstorage-prod[788]: 2022-12-28T16:03:06.133Z        info        VictoriaMetrics/app/vmstorage/transport/server.go:164        accepted vmselect conn from 10.28.113.235:49154
Dec 28 17:03:06 vm-storage-did-01 vmstorage-prod[788]: 2022-12-28T16:03:06.136Z        info        VictoriaMetrics/app/vmstorage/transport/server.go:207        processing vmselect conn from 10.28.113.235:49152
Dec 28 17:03:06 vm-storage-did-01 vmstorage-prod[788]: 2022-12-28T16:03:06.136Z        info        VictoriaMetrics/app/vmstorage/transport/server.go:207        processing vmselect conn from 10.28.113.235:49154
```

**Comment by zekker6** [comment]
@Whisper40 That's abnormal, could you check vminsert logs?

**Comment by dmitryk-dk** [comment]
Have any logs where vminsert conected? As i can see only vmselect connected and if vminsert no connected then your vmalert tries to write but can't

**Comment by Whisper40** [comment]
@zekker6  @dmitryk-dk No explicit communication error
Only : "cannot read compressed request in 1 seconds: read tcp4 10.28.113.224:8480->10.28.113.220:39648: read: connection reset by peer" multiples times

```
vm-insert-did-01:~# systemctl status victoriametrics-insert.service 
● victoriametrics-insert.service - VictoriaMetrics-insert
     Loaded: loaded (/etc/systemd/system/victoriametrics-insert.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-12-27 16:01:05 CET; 1 day 1h ago
   Main PID: 879 (vminsert-prod)
      Tasks: 25 (limit: 77140)
     Memory: 389.2M
     CGroup: /system.slice/victoriametrics-insert.service
             └─879 /usr/local/bin/vminsert-prod -memory.allowedPercent=60 -relabelConfig=/etc/victoria/relabel.yml -replicationFactor=1 -storageNode=10.28.113.228:8400,10.28.113.229:8400,10.28.113.230:8400 -insert.maxQueueDuration=>

...
Dec 28 17:40:59 vm-insert-did-01 vminsert-prod[879]: 2022-12-28T16:40:59.311Z        warn        VictoriaMetrics/app/vminsert/main.go:195        remoteAddr: "10.28.113.220:39648", X-Forwarded-For: "10.28.113.223"; requestURI: /inse> ...467918:0/prometheus/api/v1/write; cannot read compressed request in 1 seconds: read tcp4 10.28.113.224:8480->10.28.113.220:39648: read: connection reset by peer
...
..
read: connection reset by peer
lines 1-19/19 (END)
```

**Comment by zekker6** [comment]
@Whisper40 it seems like vmagent can't keep up with load and gets OOM killed before it is able to write its data into vminsert.
Log message has: `applying 1 bytes per second rate limit` which means vmagent tries to send 1 byte  per second. If this is true, there should be a flag `-remoteWrite.rateLimit` set, and you need to adjust it value (or remove it).

**Comment by zekker6** [comment]
Also, feel free to join our public slack at https://slack.victoriametrics.com/ in order to get responses faster as GitHub is hard to use as messaging platform.

**Comment by Whisper40** [comment]
@zekker6 It was for testing, we have remove it now, i will join your slack tomorrow thanks

**Comment by zekker6** [comment]
@Whisper40 After removing vmagent flag please check if vmstorage still has no messages regarding connection from vminsert and logs for vminsert itself.

**Comment by Whisper40** [comment]
@zekker6 @dmitryk-dk 

The problem is now solved. (2 hours after my last message)
What we found (and what you made us find):
- Explosion of the number of connections on Haproxy
--remoteWrite.tmpDataPath=/srv/data (full) = Agent crash
- Attempt to increase disk space from 20GB to 400GB ( not knowing if it needed more space ) -> Consumed 400GB ( 1GB / second )
- Checked all communication flows between the machines : OK
- @dmitryk-dk and @ zekker6 give us an information we didn't have, the temporary space keeps the metrics until they could be pushed to the storage VMs.
- So we look at the logs of vm-storage-did-01, and we notice that there are only logs of the type: processing vmselect/accepted vmselect. No presence of insertion logs.
So we confirm that there is a problem of logs ingestion on the storage vm.
Attempt to restart the service /usr/local/bin/vmstorage-prod. We notice that from now on, we have logs of the type insert, what confirms us that the ingestion of the logs has begun.
- Temporary increase of the number of Haproxy connections in order to catch up with the accumulated delay. -> We notice an increase to 19000 connections, then a gradual decrease as the ingestion progresses until we reach 900 connections (normal status).
- Restart of the other storage services, observation of the ingestion of the logs.

(You can comment and close the issue), we will add to our backlog to upgrade VictoriaMetrics :)

**Comment by dmitryk-dk** [comment]
Hi @Whisper40 ! Than you for your information!

**Comment by dmitryk-dk** [comment]
Close the issue as resolved
