### ISSUE TITLE
Log expensive queries

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3553]
**Is your feature request related to a problem? Please describe.**
Would be great to log not only slow queries, but also log expensive queries. Expensive in term of used resources.

**Describe the solution you'd like**
Would be nice to add something like `search.logQueryMemoryUsage=1GiB` to log all the queries which consume more the 1GiB of memory during evaluation.

**Comment by hagen1778** [comment]
Relevant PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3434

**Comment by valyala** [comment]
The commit b285207aa7b6c16bbfec74a0611ed8c901e85c16 adds `-search.logQueryMemoryUsage` command-line flag for logging queries, which require more memory than specified in the command-line flag value. This commit will be included in the next release.

**Comment by valyala** [comment]
The `-search.logQueryMemoryUsage` command-line flag is available in VictoriaMetrics starting from [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this feature request as done.

**Comment by nthienan** [comment]
@valyala, are there any metrics relevant to `-search.logQueryMemoryUsage`, and `-search.maxMemoryPerQuery` exposed? Would like to have an easy way to monitor/tune these settings.
