### ISSUE TITLE
vm has grpc interface？

### ISSUE THREAD

**Issue by hq2022** [VictoriaMetrics/VictoriaMetrics#3554]
becouse wo use thanos grpc query thanos sidecar，thanos sidecar query prometheus， thanos->thanos sidecar->prometheus，so wo use vm replace prometheus，vm has grpc interface for thanos query when grade release?

<img width="1080" alt="thanos" src="https://user-images.githubusercontent.com/9512914/209799876-869fce00-5d62-424e-9204-ce59c6cee447.png">

**Comment by denisgolius** [comment]
> 

Hi @hq2022 !
vmselect has no grpc interface. It implements the prometheus HTTP API

**Comment by hq2022** [comment]
> > 
> 
> Hi @hq2022 ! vmselect has no grpc interface. It implements the prometheus HTTP API

vm has tools for thanos grpc query?

**Comment by zekker6** [comment]
@hq2022 No, VM does not have such component.

**Comment by zekker6** [comment]
Closing this as resolved, feel free to reopen if you will have any other related questions.
