### ISSUE TITLE
deduplication per tenant

### ISSUE THREAD

**Issue by xenofree** [VictoriaMetrics/VictoriaMetrics#3569]
Hi, I don't see anything on the doc so i ask it here.
Is it possible to configure multiple `-dedup.minScrapeInterval` per tenant ?

**Comment by zekker6** [comment]
Hi @xenofree 
Unfortunately, this option can only be defined on per vmselect basis.

As a workaround, you can set different values on different vmselect nodes and route tenants to the node with required `-dedup.minScrapeInterval` value.

**Comment by xenofree** [comment]
Thanks for your answer.
`-dedup.minScrapeInterval` have to be set on both vmselect and vmstorage right ? 

So if it can't be set per tenant, i have to have multiple select and storage

**Comment by zekker6** [comment]
@xenofree No, it is only present at vmselect.

**Comment by xenofree** [comment]
I'm pretty sure you have to passed it to vmselect and storage. Or I may have misunderstood the doc.    

https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#deduplication  
`The only difference is that the same -dedup.minScrapeInterval command-line flag value must be passed to both vmselect and vmstorage`

**Comment by zekker6** [comment]
Ah, yes, my bad. You are correct, this flag should be present both on vmselect and vmstorage nodes.

**Comment by hagen1778** [comment]
You can also have deduplication configured on vmselect only. Then, all deduplication will happen in-flight, and no changes will be made on storage level. With this you can have distinct vmselect with different deduplication config.
