### ISSUE TITLE
Introduce API for turning enabling/disabling ReadOnly 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3601]
### Is your feature request related to a problem? Please describe

Introduce API for turning enabling/disabling ReadOnly 

### Describe the solution you'd like

Manually switch on/off the flag and restart vmstorage

**Comment by valyala** [comment]
`vmstorage` already supports read-only mode via `-storage.minFreeDiskSpaceBytes` command-line flag - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/269

It would be great to give more details on why an additional flag or an API is needed for controlling the read-only mode at `vmstorage`? Which use cases will it cover? How will it interact with the existing logic behind `-storage.minFreeDiskSpaceBytes` command-line flag?

**Comment by valyala** [comment]
Another option to enable read-only mode at vmstorage node is to remove the vmstorage node from the `-storageNode` list passed to `vminsert` nodes

**Comment by valyala** [comment]
It is unlikely that a new command-line flag will be added for enabling read-only mode at `vmstorage` node because there are alternatives exist as described in the comments above. So closing this feature request as won't implement.
