### ISSUE TITLE
The value is incorrect after the vmalert alarm is resolved

### ISSUE THREAD

**Issue by zxlxgd** [VictoriaMetrics/VictoriaMetrics#3602]
### Describe the bug

The value is incorrect after the vmalert alarm is resolved

I get the value in this way：{{ $value }}

### Version

./vmalert-prod --version 
vmalert-20220801-082124-tags-v1.79.1-enterprise-0-gb429b90e7

**Comment by zxlxgd** [comment]
I get the value in this way：{{ $value }}

**Comment by hagen1778** [comment]
Hi @zxlxgd! Could you please provide more details on this?
What is the alerting rule, and what are alert annotations before and after alert was resolved?

**Comment by zxlxgd** [comment]
The rule is as follows:

- alert: '1611270932354080769'
    annotations:
      summary: test
      description: test：当前值：{{printf "%.3f" .Value}}
    expr: absent(a)==1
    for: 2m

When the alarm is firing, the message is as follows:

**test 当前值:1.000**

Then when I change the threshold value to 0, let the alarm recover，the message is also as follows:

**test 当前值:1.000**

**Comment by hagen1778** [comment]
Thanks for the details!

The thing is that vmalert doesn't know what the value is, so it can't change it.

Imagine the alerting rule with the following expression:`memory_usage_bytes > 1e9`. 
For such a rule, vmalert will run a read query `/query?query=memory_usage_bytes > 1e9` once in `evaluationInterval`.
While vmalert gets no response - alert remains inactive. Once it gets a response, let's say `{metric: "memory_usage_bytes", value: "2e9"}` vmalert will switch the alert to FIRING state and will notify Alertmanager that the alert is active and its value is `2e9`.

Now, at some point memory usage drops and the alert has to become inactive again. That would mean `/query?query=memory_usage_bytes > 1e9` will return an empty result. Hence, vmalert **doesn't know the current value** and can't update the alert object in Alertmanager. It can only notify Alertmanager that this alert became inactive and needs to be expired at once.
