### ISSUE TITLE
VMUI fails to load in Firefox with "Uncaught RangeError: invalid array length"

### ISSUE THREAD

**Issue by zackelan** [VictoriaMetrics/VictoriaMetrics#3607]
### Describe the bug

VMUI works perfectly in Chrome (I'm on 108.0.5359.124 on Linux), but on Firefox (108.0.1, also on Linux) it displays a loading spinner indefinitely, and an "Uncaught RangeError: invalid array length" error is logged to the F12 dev console

other web endpoints (eg `/metrics`, `/targets`, `/config`) load fine in Firefox, it seems to be limited to the `/vmui` page

### To Reproduce

as far as I can tell it does not depend on the config file contents - I was able to repro using this minimal config file (doesn't require Consul to be running):

```
$ cat << EOF > scrape-config.yaml
scrape_configs:
  - job_name: 'services'
    consul_sd_configs:
      - server: '127.0.0.1:8500'
EOF
$ ./victoria-metrics-prod -promscrape.config=scrape-config.yaml
```

### Version

victoria-metrics-20221220-225455-tags-v1.85.3-0-gf443fad56

### Screenshots

![2023-01-05_14 35 36](https://user-images.githubusercontent.com/10138830/210894311-7e42212b-d0f4-4519-a6d9-9f4b02c91591.png)

### Additional information

if I revert the version to 1.84.0, the UI works as expected in both Chrome and Firefox, so it seems to be a regression introduced by 1.85

**Comment by zackelan** [comment]
OK, I assume I just unzip that and open `index.html`? (I am very much not a frontend dev)

doing that gives me this in Firefox:

```
Uncaught RangeError: invalid array length
    o CalendarBody.tsx:21
    ae Preact
    $o CalendarBody.tsx:16
    Preact 125
```

which points to a `const monthDays = new Array(days).fill(startDate).map((d,i) => d.add(i, "day"));` line

if I set a debugger breakpoint on that line, in Firefox `days` is `NaN` and `startDate` is listed as "invalid date", with all its components as NaN. the same thing in Chrome gives me 31 for `days` and a `startDate` of 2023-01-01T00:00.

firefox:

![firefox](https://user-images.githubusercontent.com/10138830/212208043-ab4c465b-1e2c-442a-9d81-12bb9db1454f.png)

chrome:

![chrome](https://user-images.githubusercontent.com/10138830/212208041-3238ae4a-4f5a-48c9-9a17-c01f14b25378.png)

**Comment by hagen1778** [comment]
The change mentioned by @Loori-R was included in https://docs.victoriametrics.com/CHANGELOG.html#v1870
Closing the issue as stale. Feel free to reopen if it still remains.
