### ISSUE TITLE
Why  parsing config (YAML) using marshalJSON and unmarshalJSON ?

### ISSUE THREAD

**Issue by recoilRailGun** [VictoriaMetrics/VictoriaMetrics#3622]
### Describe the bug

```GO
func (sc *ScrapeConfig) clone() *ScrapeConfig {
	data := sc.marshalJSON()
	var scCopy ScrapeConfig
	if err := scCopy.unmarshalJSON(data); err != nil {
		logger.Panicf("BUG: cannot unmarshal scrape config: %s", err)
	}
	return &scCopy
}
``` 

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e640ff72f1336d09d3e53c8581e2d6ce5af32c92/lib/promscrape/config.go#L473

As i am coding a configuration file interface UI, the FE and BE interactive using json, but scrapeConfig rewrite the marshaller/unmarshaller in no reason! The configuration file is a 

# YAML!!!!!!!!

### To Reproduce

N/A  the configfile is not a json file  should not overide json marshaller / unmarshaller !

### Version

N/A whatever version, from the first line this code occupied the json marshaller / unmarshaler

**Comment by recoilRailGun** [comment]
> Hello! [YAML is a superset of JSON](https://williamhayes.medium.com/yaml-is-a-superset-of-json-it-is-explained-in-more-detail-here-1d758a069508) and you can use json parser for converting yaml structs - see https://go.dev/play/p/LdOlm9FJUhR

haha no wounder you will quote this. But in no means yaml is not a realize of yaml. 

Whatever you said, for me i will not take it. YAML is YAML, JSON is JSON. 
You can not say the are the same format. as they are not. 

for example  Little Bush is US president, he is also human. But you cannot assume every function of president suit for human. And in some extreme cases president might not be human. (They are Lizard Man in believe of some people)

**Comment by jiekun** [comment]
Close as answered.
