### ISSUE TITLE
Pushgateway endpoint should return 200 or 202 on success

### ISSUE THREAD

**Issue by zigmund** [VictoriaMetrics/VictoriaMetrics#3636]
### Describe the bug

VictoriaMetrics starting from v1.84.0 accepts pushgateway protocol via /api/v1/import/prometheus endpoint.

It returns `204 No Content` on success, but prometheus' push lib expects `200 OK` or `202 Accepted`: https://github.com/prometheus/client_golang/blob/main/prometheus/push/push.go#L299

So VictoriaMetrics' pushgateway implementation is unusable with apps that using std prometheus' push lib.

### To Reproduce

Push metrics in prometheus push protocol to victoriametrics:
`echo 'foo{bar="baz"} 123' | curl --data-binary @- http://localhost:8429/api/v1/import/prometheus/metrics/job/test -v`

Observe `204 No Content` response code:
`< HTTP/1.1 204 No Content`

### Version

vmstorage-20221220-230705-tags-v1.85.3-cluster-0-g30b15111a

**Comment by valyala** [comment]
@zigmund , `vmagent` and single-node VictoriaMetrics should return 200 HTTP status code when improting data via [Pushgateway protocol](https://docs.victoriametrics.com/#how-to-import-data-in-prometheus-exposition-format) starting from [v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

Feel free re-opening the issue if `v1.86.2` release doesn't work as expected.

**Comment by tufitko** [comment]
@valyala Hello! `vmagent` still uses 204. tested with `victoriametrics/vmagent:v1.86.2-enterprise` https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a971bcc3fe6d57bc2c0bbacd8505b27191e5c9a1/app/vmagent/main.go#L226

**Comment by zigmund** [comment]
@valyala 

Couldn't reopen the issue. Changes were made for vminsert, not vmagent.

**Comment by valyala** [comment]
@tufitko , @zigmund , thanks for the notification! The commit 06f6b765217fa75a6d1dbb32d4bb810629ea10ee should finally fix the issue. This commit will be included in the next release. In the meantime it is possible to build `vmagent` from this commit and verify whether it properly returns `200 OK` response code when importing data via [Pushgateway protocol](https://docs.victoriametrics.com/#how-to-import-data-in-prometheus-exposition-format). See [how to build vmagent from source code](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/06f6b765217fa75a6d1dbb32d4bb810629ea10ee has been included in the release [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed then.
