### ISSUE TITLE
irate/rate support in streaming aggregation?

### ISSUE THREAD

**Issue by laixintao** [VictoriaMetrics/VictoriaMetrics#3638]
### Describe the solution you'd like

support `irate`/ `rate` in https://docs.victoriametrics.com/stream-aggregation.html#aggregation-outputs like `increase`

### Describe alternatives you've considered

it seems that we can use the `increase(requests_total[1m]) / 60` to achieve the same result with `rate(requests_total[1m])`

**Comment by KorhanOzturk90** [comment]
is there a way to achieve `increase(requests_total[1m]) / 60` in stream aggregation config file?

**Comment by laixintao** [comment]
the doc said:

> increase can be used as an alternative for [rate](https://docs.victoriametrics.com/MetricsQL.html#rate) function. For example, if we have increase with interval of 5m for a counter some_counter, then to get rate we should divide the resulting aggregation by the interval in seconds: some_counter:5m_increase / 5m is similar to rate(some_counter[5m]). Please note, opposite to [rate](https://docs.victoriametrics.com/MetricsQL.html#rate), increase aggregations can be combined safely afterwards. This is helpful when the aggregation is calculated by more than one vmagent.

https://docs.victoriametrics.com/stream-aggregation.html#increase

**Comment by AndrewChubatiuk** [comment]
hey @laixintao 
rate aggregation output is available since [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1)

**Comment by AndrewChubatiuk** [comment]
@hagen1778 can we close this issue?

**Comment by laixintao** [comment]
> @hagen1778 can we close this issue?

thank you so much!
