### ISSUE TITLE
query result is different every time

### ISSUE THREAD

**Issue by Planck0591** [VictoriaMetrics/VictoriaMetrics#3639]
### Describe the bug

I used grafana to query metric result.Every time I refresh the page,I got different result.Then I used curl tool to query result from vmselect directly,each vmselect node return different result.I checked each vmselect node connection to each vmstorage node, there is no connection problem.Is it a bug?

### To Reproduce

My query is :
/select/2:0/prometheus/api/v1/query_range?end=2023-01-12T06:00:00Z&query=arescurllog__flag{taskName="bscstorage-3copy"} !=200&start=2023-01-12T03:00:00Z&step=60

### Version

docker image is v1.85.2-cluster

### Logs

no log

### Screenshots

![image](https://user-images.githubusercontent.com/79493220/212013124-d608eb1e-aff6-45c6-ae7a-691b46554f0a.png)
![image](https://user-images.githubusercontent.com/79493220/212013218-0f97cbdb-e487-4eca-893a-8877f944dff3.png)

### Used command-line flags

- '--search.maxQueryLen=99999'
- '--dedup.minScrapeInterval=1ms'
- '--search.maxSeries=50000'
- '--search.maxQueryDuration=15s'

**Comment by Planck0591** [comment]
Hi@zekker6 
I'm sure all vmselects are using same set of flags an query all storage nodes,because the query result of other metrics is correct.

Set for vmstorage is 
`vmstorage:
    image: victoriametrics/vmstorage:v1.85.2-cluster
    mem_limit: 20G
    container_name: vmstorage
    network_mode: host
    restart: always
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - /data/vm-data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--retentionPeriod=35d'`
Thank you for your suggestion,but I try query with nocache=1 parameter via curl,there is nothing different.
I run requests with trace=1,but the result did not contain trace.My request is 
`curl --get --data-urlencode "end=2023-01-12T06:00:00Z" --data-urlencode 'query=arescurllog__flag{taskName="bscstorage-3copy"} !=200' --data-urlencode 'start=2023-01-12T03:00:00Z' --data-urlencode 'step=60' --data-urlencode 'trace=1' http://127.0.0.1:8481/select/2:0/prometheus/api/v1/query_range`

**Comment by Planck0591** [comment]
Hi @zekker6 
I'm sure all vmselects are using same set of flags an query all storage nodes,because the query result of other metrics is correct.
I used docker-compose to run vmstorage.Set for vmstorage is
version: '2'
services:
  vmstorage:
    image: victoriametrics/vmstorage:v1.85.2-cluster
    mem_limit: 20G
    container_name: vmstorage
    network_mode: host
    restart: always
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - /data/vm-data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--retentionPeriod=35d'

**Comment by Planck0591** [comment]
Hi @zekker6 
Thank you for your suggestion,but I try query with nocache=1 parameter via curl,there is nothing different.
I run requests with trace=1, there is two results.
One is
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "__name__": "arescurllog__flag",
                    "agent_endpoint": "dx-anhui-hefei-1-223-247-108-207",
                    "d2Cache": "unknown",
                    "d2IP": "unknown-simple-storage.bscstorage.com",
                    "d2Node": "unknown",
                    "dCity": "unknown",
                    "dEndpoint": "unknown-simple-storage.bscstorage.com",
                    "dIP": "simple-storage.bscstorage.com",
                    "dIsp": "unknown",
                    "dProv": "unknown",
                    "dRIsp": "unknown",
                    "dStatus": "unknown",
                    "dType": "bscstorage-3copy",
                    "dUrl": "-k \"https://simple-storage.bscstorage.com/x3d6R5YxEKe4K0c2xD/favicon/favicon.ico\"",
                    "endpoint": "dx-anhui-hefei-1-117-71-105-16",
                    "port": "80",
                    "s2Cache": "dx-anhui-hefei-1-cache-2",
                    "s2Ip": "dx-anhui-hefei-jd-1-117.71.105.16",
                    "s2Node": "dx-anhui-hefei-jd-1",
                    "sCity": "hefei",
                    "sIp": "117.71.105.16",
                    "sIsp": "dx",
                    "sProv": "anhui",
                    "sStatus": "2102|2007|2201",
                    "sertypes": "cache_cache,comp_pcdn_schedule,live_push",
                    "taskName": "bscstorage-3copy"
                },
                "values": [
                    [
                        1673856960,
                        "7"
                    ]
                ]
            },
            {
                "metric": {
                    "__name__": "arescurllog__flag",
                    "cachegroup": "dx-liaoning-anshan-4-cache-1",
                    "d2Cache": "unknown",
                    "d2IP": "unknown-simple-storage.bscstorage.com",
                    "d2Node": "unknown",
                    "dCity": "unknown",
                    "dEndpoint": "unknown-simple-storage.bscstorage.com",
                    "dIP": "simple-storage.bscstorage.com",
                    "dIsp": "unknown",
                    "dProv": "unknown",
                    "dRIsp": "unknown",
                    "dStatus": "unknown",
                    "dType": "bscstorage-3copy",
                    "dUrl": "-k \"https://simple-storage.bscstorage.com/x3d6R5YxEKe4K0c2xD/favicon/favicon.ico\"",
                    "endpoint": "dx-liaoning-anshan-4-42-202-39-14",
                    "port": "80",
                    "s2Cache": "dx-liaoning-anshan-4-cache-1",
                    "s2Ip": "dx-liaoning-anshan-jd-4-42.202.39.14",
                    "s2Node": "dx-liaoning-anshan-jd-4",
                    "sCity": "anshan",
                    "sIp": "42.202.39.14",
                    "sIsp": "dx",
                    "sProv": "liaoning",
                    "sStatus": "2101|2007|2201",
                    "sertypes": "cache_cache,live_edge,comp_pcdn_schedule,sdwan_popaccess,sdwan_popnetwork,static_parent",
                    "taskName": "bscstorage-3copy"
                },
                "values": [
                    [
                        1673856480,
                        "7"
                    ],
                    [
                        1673857440,
                        "7"
                    ],
                    [
                        1673857500,
                        "7"
                    ]
                ]
            },
            {
                "metric": {
                    "__name__": "arescurllog__flag",
                    "cachegroup": "lt-shandong-zaozhuang-12-cache-4",
                    "d2Cache": "unknown",
                    "d2IP": "unknown-simple-storage.bscstorage.com",
                    "d2Node": "unknown",
                    "dCity": "unknown",
                    "dEndpoint": "unknown-simple-storage.bscstorage.com",
                    "dIP": "simple-storage.bscstorage.com",
                    "dIsp": "unknown",
                    "dProv": "unknown",
                    "dRIsp": "unknown",
                    "dStatus": "unknown",
                    "dType": "bscstorage-3copy",
                    "dUrl": "-k \"https://simple-storage.bscstorage.com/x3d6R5YxEKe4K0c2xD/favicon/favicon.ico\"",
                    "endpoint": "lt-shandong-zaozhuang-12-124-132-138-89",
                    "port": "80",
                    "s2Cache": "lt-shandong-zaozhuang-12-cache-4",
                    "s2Ip": "lt-shandong-zaozhuang-jd-12-124.132.138.89",
                    "s2Node": "lt-shandong-zaozhuang-jd-12",
                    "sCity": "zaozhuang",
                    "sIp": "124.132.138.89",
                    "sIsp": "lt",
                    "sProv": "shandong",
                    "sStatus": "2101|2007|2201",
                    "sertypes": "cache_cache,live_edge,static_parent",
                    "taskName": "bscstorage-3copy"
                },
                "values": [
                    [
                        1673856000,
                        "7"
                    ],
                    [
                        1673856060,
                        "7"
                    ],
                    [
                        1673856360,
                        "7"
                    ],
                    [
                        1673856660,
                        "7"
                    ],
                    [
                        1673856960,
                        "7"
                    ],
                    [
                        1673857260,
                        "7"
                    ]
                ]
            },
            {
                "metric": {
                    "__name__": "arescurllog__flag",
                    "cachegroup": "lt-shandong-zibo-13-cache-8",
                    "d2Cache": "unknown",
                    "d2IP": "unknown-simple-storage.bscstorage.com",
                    "d2Node": "unknown",
                    "dCity": "unknown",
                    "dEndpoint": "unknown-simple-storage.bscstorage.com",
                    "dIP": "simple-storage.bscstorage.com",
                    "dIsp": "unknown",
                    "dProv": "unknown",
                    "dRIsp": "unknown",
                    "dStatus": "unknown",
                    "dType": "bscstorage-3copy",
                    "dUrl": "-k \"https://simple-storage.bscstorage.com/x3d6R5YxEKe4K0c2xD/favicon/favicon.ico\"",
                    "endpoint": "lt-shandong-zibo-13-60-210-23-59",
                    "port": "80",
                    "s2Cache": "lt-shandong-zibo-13-cache-8",
                    "s2Ip": "lt-shandong-zibo-jd-13-60.210.23.59",
                    "s2Node": "lt-shandong-zibo-jd-13",
                    "sCity": "zibo",
                    "sIp": "60.210.23.59",
                    "sIsp": "lt",
                    "sProv": "shandong",
                    "sStatus": "2101|2007|2201",
                    "sertypes": "cache_cache,xdp_director,live_edge",
                    "taskName": "bscstorage-3copy"
                },
                "values": [
                    [
                        1673856000,
                        "7"
                    ],
                    [
                        1673856300,
                        "7"
                    ],
                    [
                        1673857740,
                        "7"
                    ]
                ]
            },
            {
                "metric": {
                    "__name__": "arescurllog__flag",
                    "cachegroup": "yd-henan-nanyang-4-cache-1",
                    "d2Cache": "unknown",
                    "d2IP": "unknown-simple-storage.bscstorage.com",
                    "d2Node": "unknown",
                    "dCity": "unknown",
                    "dEndpoint": "unknown-simple-storage.bscstorage.com",
                    "dIP": "simple-storage.bscstorage.com",
                    "dIsp": "unknown",
                    "dProv": "unknown",
                    "dRIsp": "unknown",
                    "dStatus": "unknown",
                    "dType": "bscstorage-3copy",
                    "dUrl": "-k \"https://simple-storage.bscstorage.com/x3d6R5YxEKe4K0c2xD/favicon/favicon.ico\"",
                    "endpoint": "yd-henan-nanyang-4-183-204-72-13",
                    "port": "80",
                    "s2Cache": "yd-henan-nanyang-4-cache-1",
                    "s2Ip": "yd-henan-nanyang-jd-4-183.204.72.13",
                    "s2Node": "yd-henan-nanyang-jd-4",
                    "sCity": "nanyang",
                    "sIp": "183.204.72.13",
                    "sIsp": "yd",
                    "sProv": "henan",
                    "sStatus": "2101|2007|2201",
                    "sertypes": "cache_cache,live_edge",
                    "taskName": "bscstorage-3copy"
                },
                "values": [
                    [
                        1673856060,
                        "7"
                    ]
                ]
            }
        ]
    },
    "trace": {
        "duration_msec": 2.279,
        "message": "vmselect-20221219-215715-tags-v1.85.2-cluster-0-g1ed0d07aa: /select/3:0/prometheus/api/v1/query_range: start=1673856000000, end=1673857800000, step=60000, query=\"arescurllog__flag{taskName=\\\"bscstorage-3copy\\\"} !=200\": series=5",
        "children": [
            {
                "duration_msec": 2.001,
                "message": "eval: query=arescurllog__flag{taskName=\"bscstorage-3copy\"} != 200, timeRange=[2023-01-16T08:00:00Z..2023-01-16T08:30:00Z], step=60000, mayCache=true: series=118, points=3658, pointsPerSeries=31",
                "children": [
                    {
                        "duration_msec": 1.991,
                        "message": "binary op \"!=\": series=118",
                        "children": [
                            {
                                "duration_msec": 0.754,
                                "message": "eval: query=arescurllog__flag{taskName=\"bscstorage-3copy\"}, timeRange=[2023-01-16T08:00:00Z..2023-01-16T08:30:00Z], step=60000, mayCache=true: series=118, points=3658, pointsPerSeries=31",
                                "children": [
                                    {
                                        "duration_msec": 0.652,
                                        "message": "rollup default_rollup(): timeRange=[2023-01-16T08:00:00Z..2023-01-16T08:30:00Z], step=60000, window=0: neededMemoryBytes=0",
                                        "children": [
                                            {
                                                "duration_msec": 0.644,
                                                "message": "rollup cache get: query=arescurllog__flag{taskName=\"bscstorage-3copy\"}, timeRange=[2023-01-16T08:00:00Z..2023-01-16T08:30:00Z], step=60000, window=0",
                                                "children": [
                                                    {
                                                        "duration_msec": 0.053,
                                                        "message": "load compressed entry from cache with size 10211 bytes"
                                                    },
                                                    {
                                                        "duration_msec": 0.407,
                                                        "message": "unpack the entry into 120803 bytes"
                                                    },
                                                    {
                                                        "duration_msec": 0.172,
                                                        "message": "unmarshal 118 series"
                                                    },
                                                    {
                                                        "duration_msec": 0.005,
                                                        "message": "return 118 series on a timeRange=[2023-01-16T08:00:00Z..2023-01-16T08:30:00Z]"
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                "duration_msec": 0.004,
                                "message": "eval: query=200, timeRange=[2023-01-16T08:00:00Z..2023-01-16T08:30:00Z], step=60000, mayCache=true: series=1, points=31, pointsPerSeries=31"
                            }
                        ]
                    }
                ]
            },
            {
                "duration_msec": 0.035,
                "message": "sort series by metric name and labels"
            },
            {
                "duration_msec": 0.141,
                "message": "generate /api/v1/query_range response for series=5, points=14"
            }
        ]
    }
}

**Comment by Planck0591** [comment]
@zekker6 
Another one is too long.I paste it in a file.
[transfer.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10424680/transfer.txt)

**Comment by zekker6** [comment]
@Planck0591 It seems like one of traces you've shared is using cache for response, so there is not much information. Could you use both `nocache` and `trace` to produce traces?
Also, please attach both as files so that it won't be truncated by Github.

As far as I can see, both traces end up with:
```
Trace 1: generate /api/v1/query_range response for series=5, points=14
Trace 2: generate /api/v1/query_range response for series=5, points=14
```
So the result should be the same.

**Comment by valyala** [comment]
@Planck0591 , could you try updating to [v1.89.1 release](https://docs.victoriametrics.com/CHANGELOG.html#v1891) and verifying whether the issue is fixed there? It may be related to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3946 .

**Comment by hagen1778** [comment]
Hi @Planck0591! Is the problem still relevant for your?
