### ISSUE TITLE
Vmagent benchmark publishing

### ISSUE THREAD

**Issue by ep4sh** [VictoriaMetrics/VictoriaMetrics#3640]
### Is your feature request related to a problem? Please describe

Dear team, 

I'd like to replace the existing scrapers with VMAgent, but I need some facts to perform this.
I've seen the VMAgent presentation on [youtube](https://youtu.be/A1zRkSdWPJg) and there was a mention, that the VMAgent benchmark exists in the docs:
https://docs.victoriametrics.com/Articles.html#benchmarks

But I haven't found anything there - so, could you please point me if such benchmark exist or create/publish it?

### Describe the solution you'd like

-

**Comment by zekker6** [comment]
Hi @ep4sh 
Unfortunately, that reference was to an internal benchmark we have used to test it. Currently, there is no benchmark that we use and publish results.

**Comment by ep4sh** [comment]
Saaaad :(
Anyway, thank you for quick turnaround!
