### ISSUE TITLE
Performance degradation in v1.85.3

### ISSUE THREAD

**Issue by Alexul** [VictoriaMetrics/VictoriaMetrics#3647]
### Describe the bug

TSDB became slow or sometimes totally unavailable for the duration of indexdb/file merges
<img width="1388" alt="Screenshot 2023-01-12 at 21 23 55" src="https://user-images.githubusercontent.com/10867201/212164120-6060a8a2-6e17-4319-9a9c-67b970a29339.png">

### To Reproduce

-

### Version

v1.85.3

### Logs

error when searching for metricIDs in the current indexdb: deadline exceeded
search error after reading 0 data blocks: error when searching for tagFilters=[{__name__="vm_rows_inserted_total",instance!="self",type="promremotewrite"}] on the time range [2023-01-12T07:03:00Z..2023-01-12T19:09:00Z]: error when searching for metricIDs in the current indexdb: error when searching for metricIDs for tagFilter in fast path: deadline exceeded; tagFilter=composite(vm_rows_inserted_total,instance)="self"

### Additional information

only happens on tsdb that under user queries, did not happen on the tsdb that under alerts queries (same version)

**Comment by hagen1778** [comment]
Hi @Alexul! What was the previous version where everything was ok?

**Comment by Alexul** [comment]
Previously v1.84.0

**Comment by Alexul** [comment]
thats the [snapshot](https://grafana.wixpress.com/dashboard/snapshot/KEGEUHpt9shqUti6rSO1M8GVnKfDT4mg) at the timeframe of a crash (tsdb didnt return data for around 13min and then recovered by itself):

**Comment by Alexul** [comment]
Happened again, managed to get dumps this time
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10427064/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10427065/mem.pprof.txt)
[dashboard snapshot](https://grafana.wixpress.com/dashboard/snapshot/ucpYCcFNqWJ9QQd6uNUni1moGdmh7J69)

**Comment by valyala** [comment]
@Alexul , thanks for filing the detailed bugreport! Could you try single-node VictoriaMetrics from the following Docker image - `docker.io/victoriametrics/victoria-metrics:heads-public-single-node-0-g09d7fa273` ? It is [built](https://docs.victoriametrics.com/#how-to-build-from-sources) from the commit 09d7fa27372fc9252e01de00a863f3b7e075b4a5 , which should address the issue by removing an additional slowdown for concurrently executed queries when there are active assisted merges. This slowdown is no longer needed after the refactoring of background merge logic in v1.85.0.

The related issues:

* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3641
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3425

**Comment by Alexul** [comment]
Installed, runs ok, but will take to actually validate the problem is gone. Its to intermittent of a problem

**Comment by Alexul** [comment]
Also there a big spikes of pending datapoints with the new version
<img width="1372" alt="Screenshot 2023-01-17 at 10 49 19" src="https://user-images.githubusercontent.com/10867201/212851740-d274b1ac-1b53-4829-9596-b37f241e8731.png">

**Comment by valyala** [comment]
@Alexul , could you try `docker.io/victoriametrics/victoria-metrics:heads-public-single-node-0-g2ac530eb2` ? It should address both big number of pending datapoints and increased number of assisted merges.

**Comment by Alexul** [comment]
Yes,[ it did](https://grafana.wixpress.com/dashboard/snapshot/JyAdkpilX4NjMPJV7q0MbShqGBemN2rd), thank you

**Comment by valyala** [comment]
@Alexul , thanks for the confirmation!

All the performance improvements mentioned above have been included in [v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue then.
