### ISSUE TITLE
vmui: wrong number format in the tooltip

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3649]
### Describe the bug

VMUI page TopQueries has wrong number formatting for the limit
<img width="601" alt="image" src="https://user-images.githubusercontent.com/2902918/212276723-8d4da9a9-9ba8-4ce8-812a-44f1c1503313.png">

### To Reproduce

Check https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?topN=20&maxLifetime=10m0s#/top-queries

### Version

upstream

**Comment by valyala** [comment]
The issue has been fixed in the commit 04c408e9863f6ad528e348014a0008a80b7439f1 . Closing the issue, since it hasn't be exposed in any release yet.
