### ISSUE TITLE
Does vm support specifying a log output path?

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#3650]
### Describe the solution you'd like

no

### Additional information

# #

**Comment by denisgolius** [comment]
Hi!
There is no such functionality at the moment.
By default VictoriaMetrics Single, Cluster binaries and utilities use stdout output for logs, but you can forward them to a file with **systemd** service. See example for **vmstorage** below:

```console
ExecStart=/usr/bin/vmstorage-prod -storageDataPath=/var/lib/vmstorage \
    -storage.minFreeDiskSpaceBytes=1GB \
    -retentionPeriod=180d \
    -dedup.minScrapeInterval=1s \
    -loggerOutput=stdout  \
    -loggerFormat=json
ExecStop=/bin/kill -s SIGTERM $MAINPID
StandardOutput=append:/var/log/vmstorage/vmstorage.json
```
or with unix way:

```console
foo > allout.txt
```

**Comment by FengZh61** [comment]
> ```
> -loggerFormat=json
> ```

tks!!!
I added the StandardOutput configuration to the systemd service file and it took effect.
But the systemd version in my production environment is too low ,no support for specifying the log output path, I'll try to upgrade the systemd version, thanks again!

**Comment by FengZh61** [comment]
> Hi! There is no such functionality at the moment. By default VictoriaMetrics Single, Cluster binaries and utilities use stdout output for logs, but you can forward them to a file with **systemd** service. See example for **vmstorage** below:
> 
> ```
> ExecStart=/usr/bin/vmstorage-prod -storageDataPath=/var/lib/vmstorage \
>     -storage.minFreeDiskSpaceBytes=1GB \
>     -retentionPeriod=180d \
>     -dedup.minScrapeInterval=1s \
>     -loggerOutput=stdout  \
>     -loggerFormat=json
> ExecStop=/bin/kill -s SIGTERM $MAINPID
> StandardOutput=append:/var/log/vmstorage/vmstorage.json
> ```
> 
> or in unix way:
> 
> ```
> foo > allout.txt
> ```

tks!!!
I added the StandardOutput configuration to the systemd service file and it took effect.
But the systemd version in my production environment is too low ,no support for specifying the log output path, I'll try to upgrade the systemd version, thanks again!
