### ISSUE TITLE
PromLens and vmui

### ISSUE THREAD

**Issue by v1gnesh** [VictoriaMetrics/VictoriaMetrics#3654]
Hello,

Thank you for this project & the relentless work that goes into improving it over the years.

Wanted to know your thoughts on [PromLens](https://promlabs.com/blog/2022/10/25/promlabs-and-chronosphere-open-source-the-promlens-query-builder) and if it's beneficial to VM (as an addition into vmui, maybe).
PromLens works with PromQL, however, is VM interested in having this functionality within VM's implementation natively, therefore adding MetricsQL support too?

**Comment by denisgolius** [comment]
> Hello,
> 
> Thank you for this project & the relentless work that goes into improving it over the years.
> 
> Wanted to know your thoughts on [PromLens](https://promlabs.com/blog/2022/10/25/promlabs-and-chronosphere-open-source-the-promlens-query-builder) and if it's beneficial to VM (as an addition into vmui, maybe). PromLens works with PromQL, however, is VM interested in having this functionality within VM's implementation natively, therefore adding MetricsQL support too?

Hello!
There is no such plans for adding support of MetricsQL to Promlens or creation fork/etc. See also https://twitter.com/juliusvolz/status/1258486765062684672
