### ISSUE TITLE
i386 artifacts not provided?

### ISSUE THREAD

**Issue by jadbaz** [VictoriaMetrics/VictoriaMetrics#3661]
Hello, the [vmagent documentation](https://docs.victoriametrics.com/vmagent.html#iot-and-edge-monitoring) specifies that vmagent works on i386

> vmagent works on various architectures from the IoT world - 32-bit arm, 64-bit arm, ppc64, 386, amd64

I would expect that there would be artifacts provided for i386. But I couldn't find anything so I had to compile it. I think if this is the case, this should be explicitly specified in the documentation (that i386 artifacts need to built)

**Comment by michelbitar-99** [comment]
An i386 build would really be helpful for us as well!

**Comment by valyala** [comment]
`i386` binaries for `vmagent`, `vmalert`, `vmauth`, `vmbackup` and `vmrestore` will be published at [releases page](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) in the next release.

**Comment by valyala** [comment]
Binaries for `GOARCH=386` are available at the [releases pages](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) starting from `v1.87.0`. Closing the feature request as done.
