### ISSUE TITLE
Slow insert v's Cache hit rate for storage/tsid

### ISSUE THREAD

**Issue by conormarkmurphy** [VictoriaMetrics/VictoriaMetrics#3662]
Hi,

We're trying to troubleshoot a problem with slow inserts in VM Cluster. The usage is a bit different from normal in that inserts are done in batches. The systems being monitored are not directly connected and upload batches of metrics about every two hours.

We've two vmstorage pods. When we look at the "Slow Inserts" graph in the Grafana dashboard, it's averaging about 6%. However, the Cache Hit % for storage/tsid is less then 0.01% which I'm confused by. Doesn't a Cache Miss on storage/tsid imply a slow insert?

Thanks,
Conor

**Comment by hagen1778** [comment]
Hello! Sorry for the late reply.
Is the issue still relevant?
