### ISSUE TITLE
vmagent oom when delete kubernetes clusters from kubernetes_sd_configs

### ISSUE THREAD

**Issue by lzfhust** [VictoriaMetrics/VictoriaMetrics#3668]
### Describe the bug

We are using vmagent to scrape metrics. When delete the existing  kubernetes clusters from kubernetes_sd_configs, OOM happened and vmagent had been killed. 
<img width="1499" alt="企业微信截图_fada52d4-93b1-4623-a325-c1cb768f2a97" src="https://user-images.githubusercontent.com/9677371/213076242-55cbb001-c18f-4414-8f52-5a2648aba47b.png">

The number of targets of the deleted kubernetes clusters is about 7000 and the machine is 32 core + 64GB
<img width="1281" alt="企业微信截图_b0fc543f-cbc3-49b4-b054-f5d595f6a604" src="https://user-images.githubusercontent.com/9677371/213076600-5a7972ac-8378-44ae-95a4-e43783e9e0c4.png">

### To Reproduce

add kubernetes clusters and then delete them

### Version

v1.83.0

**Comment by lzfhust** [comment]
We debug this problem and find out that this case could be fixed by using writeRequestCtxPool in sendStaleSeries function.
We commit a pull request: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3669

**Comment by valyala** [comment]
@lzfhust , see also the follow-up commit 68463c9e87303a587a9af1d054aa32c9efeae31a , which should further reduce memory usage spikes when big number of scrape targets disappear at once. It limits the number of concurrent calls to `sendStaleSeries()` to the number of available CPU cores. This automatically limits the maximum memory usage for this function. Could you build `vmagent` from this commit and verify whether this reduces memory usage spikes in your case?

**Comment by lzfhust** [comment]
> @lzfhust , see also the follow-up commit [68463c9](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/68463c9e87303a587a9af1d054aa32c9efeae31a) , which should further reduce memory usage spikes when big number of scrape targets disappear at once. It limits the number of concurrent calls to `sendStaleSeries()` to the number of available CPU cores. This automatically limits the maximum memory usage for this function. Could you build `vmagent` from this commit and verify whether this reduces memory usage spikes in your case?

Ok，I will try this

**Comment by valyala** [comment]
Both improvements - https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d79f1b106c2fd60d8760419fc4acb57d39cfd1c2 and https://github.com/VictoriaMetrics/VictoriaMetrics/commit/68463c9e87303a587a9af1d054aa32c9efeae31a - have been included in [vmagent v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @lzfhust , could you confirm that `vmagent v1.86.2` doesn't have memory spikes when big number of scrape targets disappear?

**Comment by valyala** [comment]
@lzfhust , could you try building vmagent from the commit babecd83632446b6f24b57266def3782cf39c07d and verifying whether this fixes memory usage spikes when big number of scrape targets are deleted in kubernetes?

**Comment by lzfhust** [comment]
> Both improvements - [d79f1b1](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d79f1b106c2fd60d8760419fc4acb57d39cfd1c2) and [68463c9](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/68463c9e87303a587a9af1d054aa32c9efeae31a) - have been included in [vmagent v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @lzfhust , could you confirm that `vmagent v1.86.2` doesn't have memory spikes when big number of scrape targets disappear?

I have tried and the `vmagent v1.86.2` doesn't have memory spikes when big number of scrape targets disappear.

**Comment by valyala** [comment]
@lzfhust , thanks for the confirmation! The [vmagent v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) contains an additional improvement for [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3675). It should reduce memory usage spikes when targets with big number of exported metrics are removed from the list of discovered targets. Closing this issue as fixed then.
