### ISSUE TITLE
vmselect flag provided but not defined: -deleteAuthKey

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#3674]
### Describe the bug

[Official documentation says the next](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-delete-time-series): ` The /api/v1/admin/tsdb/delete_series handler may be protected with authKey if -deleteAuthKey command-line flag is set.` but vmselect do not accept this flag.

This flag is present in the source code:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/main.go#L31
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/main.go#L429
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/main.go#L489

### To Reproduce

1. Clone repository https://github.com/VictoriaMetrics/VictoriaMetrics
2. Set ` --deleteAuthKey=true` flag for vmselect in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose-cluster.yml
3. Run `docker-compose -f docker-compose-cluster.yml up -d`
3. Check vmselect logs: `docker-compose -f docker-compose-cluster.yml logs -f vmselect`

or 
1. Download https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.86.1/victoria-metrics-linux-amd64-v1.86.1-cluster.tar.gz
2. Run: `tar -xzvf victoria-metrics-linux-amd64-v1.86.1-cluster.tar.gz`
3. Run `./vmselect-prod -deleteAuthKey=true`

### Version

**docker container version:** `victoriametrics/vmselect:v1.86.1-cluster`

**executable vmselect file:** `vmselect-20230111-095209-tags-v1.86.1-cluster-0-g23ed83504`

### Logs

docker-compose -f docker-compose-cluster.yml logs -f vmselect
```
vmselect  | Run "/vmselect-prod -help" in order to see the description for all the available flags
vmselect  | flag provided but not defined: -deleteAuthKey
vmselect  | 
vmselect  | vmselect processes incoming queries by fetching the requested data from vmstorage nodes configured via -storageNode.
vmselect  | 
vmselect  | See the docs at https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html .
vmselect  | 
vmselect  | Run "/vmselect-prod -help" in order to see the description for all the available flags
vmselect  | flag provided but not defined: -deleteAuthKey
vmselect  | 
vmselect  | vmselect processes incoming queries by fetching the requested data from vmstorage nodes configured via -storageNode.
vmselect  | 
vmselect  | See the docs at https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html .
vmselect  | 
vmselect  | Run "/vmselect-prod -help" in order to see the description for all the available flags
vmselect  | flag provided but not defined: -deleteAuthKey
vmselect  | 
vmselect  | vmselect processes incoming queries by fetching the requested data from vmstorage nodes configured via -storageNode.
vmselect  | 
vmselect  | See the docs at https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html .
vmselect  | 
vmselect  | Run "/vmselect-prod -help" in order to see the description for all the available flags
```

### Used command-line flags

All flags are default from https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose-cluster.yml

**Comment by f41gh7** [comment]
Some auth flags aren't added to the cluster components intentionally. You have to use [vmauth](https://docs.victoriametrics.com/vmauth.html) with per-tenant url protection . 


 We have to introduce `Security` section for cluster and explain how to harden cluster components.

**Comment by denisgolius** [comment]
Ok, it make sens.

**Comment by hagen1778** [comment]
@denisgolius @f41gh7 would you care to add the mentioned Security section to docs?

**Comment by valyala** [comment]
Closing this issue, since [VictoriaMetrics cluster now has the "security" chapter](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#security).
