### ISSUE TITLE
vmui: time to introduce hierarchical menu

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3678]
### Is your feature request related to a problem? Please describe

VMUI navigation panel doesn't fit one row on my laptop's screen
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/2902918/213445348-64f22aff-1909-4f35-8a21-0dd07bcc4de9.png">

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/2902918/213445432-fe162516-7538-44ee-ab81-1eb3e8513132.png">

### Describe the solution you'd like

To have multivelel menu, so multiple links can be grouped and don't take too much space in the nav bar.

### Describe alternatives you've considered

Buy bigger laptop)

**Comment by valyala** [comment]
The updated top menu in `vmui` is available starting from [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
