### ISSUE TITLE
API for getting metrics without tags (graphite)

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#368]
Graphite metrics have separators in the form of a dot and they do not fit well with tagged metrics - I would like to be able to request them using separate APIs. This will allow you to separate tagged and non- tagged metrics in Grafana and implement a request for only graphite metrics using carbonapi.

**Comment by valyala** [comment]
@ihard , could you give more information on the feature request? Currently you can freely query graphite metrics like `foo.bar.baz` with [MetricsQL](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL). If the metric name contains special chars such as `-` (for example, `foo-bar-baz`), then these chars can be escaped with backslash. For example, `foo\-bar\-baz`. An alternative syntax is to put the metric name inside label filters: `{__name__="foo-bar-baz"}`.

As I know, `go-graphite/carbonapi` already supports VictoriaMetrics as data source - see [this example](https://github.com/go-graphite/carbonapi/blob/master/cmd/carbonapi/carbonapi.example.prometheus.yaml) for details.

**Comment by ihard** [comment]
I have a stream of graphite metrics without tags, the number of unique metrics is 1 M+, the number of fields (names between points .field. ) 10+. If I send them to the VM they appear in the list of metrics with full names field1.field2.field3. field4.field5.field6.field7.field8.field9.field10 what makes auto-top-up in Grafana non-working as there will appear 1M + unique metrics in the list. 
Building PromQL or MetricQL queries becomes completely inconvenient. 
I would like to translate graphite metrics without tags to VM and have access to them, via the Carbon API, but so that they do not overlap with metrics with tags, the metrics with tags in PromQL should not contain a dot. 
This would definitely give you the flexibility and convenience to work with different types of metrics in a single storage.

**Comment by valyala** [comment]
@ihard , thanks for the details! I need to think more about design for this feature.

In the meantime the following workarounds exist:

- To store Graphite metrics in a separate instance of VictoriaMetrics, so they don't clash with Prometheus metrics when exploring them in Grafana.
- To push Graphite metrics to [graphite-exporter](https://github.com/prometheus/graphite_exporter), which can convert Graphite metric names to Prometheus metrics with tags - see [these docs](https://github.com/prometheus/graphite_exporter#metric-mapping-and-configuration) for details.
- To convert Graphite metric names to Prometheus-like metrics with tags before storing them in VictoriaMetrics. This can be done by [vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md) via [relabeling](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#relabeling) config passed to `-remoteWrite.relabelConfig`. For instance, the `us-east.prod.vmselect.memory_usage` Graphite metric may be converted to `memory_usage{region="us-east", env="prod", app="vmselect"}` Prometheus metric with the following relabel config:
```yml
- source_labels: [__name__]
  target_label: region
  regex: "([^\\.]+).*"
- source_labels: [__name__]
  target_label: env
  regex: "(?:[^\\.]+\\.){1}([^\\.]+).*"
- source_labels: [__name__]
  target_label: app
  regex: "(?:[^\\.]+\\.){2}([^\\.]+).*"
- source_labels: [__name__]
  target_label: __name__
  regex: "(?:[^\\.]+\\.){3}([^\\.]+)"
```

**Comment by valyala** [comment]
FYI, VictoriaMetrics gained support for Graphite API, so it can be queried with Graphite queries - see [these docs](https://docs.victoriametrics.com/#querying-graphite-data).

**Comment by ihard** [comment]
thanks, I'll try to check with the current version

**Comment by valyala** [comment]
Update: VictoriaMetrics [v1.78.0](https://docs.victoriametrics.com/CHANGELOG.html) gained support for Graphite-specific relabeling. See [these docs](https://docs.victoriametrics.com/vmagent.html#graphite-relabeling).
