### ISSUE TITLE
Flaky TestMarshalUnmarshalInt64Array (got 6; expecting 4)

### ISSUE THREAD

**Issue by zhsj** [VictoriaMetrics/VictoriaMetrics#3683]
### Describe the bug

```
--- FAIL: TestMarshalUnmarshalInt64Array (0.09s)
    encoding_cgo_test.go:23: unexpected MarshalType for va=[...], precisionBits=22: got 6; expecting 4
```

### To Reproduce

It's flaky, but with `go test -count=10`, it has more chance to reproduce.

```
go test -count=10 -run '^TestMarshalUnmarshalInt64Array$'
```

### Version

master, and Go is 1.19.5.

**Comment by valyala** [comment]
@zhsj , thanks for the bugreport! It should be fixed in the commit 3d1cb011b671b71fdda8c82c2a65106b6a0dbe1e .
