### ISSUE TITLE
Vmselect 1.86.2 memory usage

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#3692]
### Describe the bug

After upgrade from 1.84.0 to 1.86.2 geted huge memory usage and OOM events on vmselect. I was forced downgrade to 1.85.3

### To Reproduce

upgrade to 1.86.2

### Version

1.86.2

### Screenshots

1.84.0 -> 1.86.2

![photo_2023-01-23_07-51-05](https://user-images.githubusercontent.com/46656585/213967937-e136daab-8a79-4912-8252-a11d2b3cbfef.jpg)

1.86.2 -> 1.85.3
![photo_2023-01-23_07-52-05](https://user-images.githubusercontent.com/46656585/213968030-795b53f8-19eb-43b4-b066-bed93a3dd105.jpg)

### Additional information

vmselect 186.2 pprof
[select.pprof.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10477326/select.pprof.zip)

**Comment by valyala** [comment]
@nevlkv , could you try building `vmselect` from the commit 0698467ae545d60d60601f093c6f50e2f49d594b and verify whether it uses lower amounts of memory than `vmselect v1.86.2` on your workload? See [how to build vmselect from source code](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by nevlkv** [comment]
@valyala where i can pull image with last changes ?

**Comment by hagen1778** [comment]
Hi @nevlkv! The image wasn't pushed yet. Is it possible to build from sources as @valyala suggested?

**Comment by valyala** [comment]
@hagen1778 , could you build and publish the Docker image from https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0698467ae545d60d60601f093c6f50e2f49d594b , so @nevlkv could try it?

**Comment by hagen1778** [comment]
Sure! Here is the image for amd64 -  [victoriametrics/vmselect:heads-cluster-0-g29fd95d42-amd64](https://hub.docker.com/layers/victoriametrics/vmselect/heads-cluster-0-g29fd95d42-amd64/images/sha256-44be895164596f7ac5c3a481d359ae87b9fee9ea16d60187ea1abaa4689aa4ed?context=explore)

**Comment by valyala** [comment]
@nevlkv , could you share CPU usage and memory usage graphs for `vmselect` on a time range, which cover the following releases (minimum a hour per each release):

1. v1.85.3
2. v1.86.2
3. the `heads-public-cluster-0-gaae7b0dc9` Docker image tag for `vmselect` (I just created this Docker image from the latest changes to vmselect)

These graphs should help understanding how the CPU and memory usage changed on your workload between the following release pairs:

- v1.85.2 and v1.86.2
- v1.86.2 and `heads-public-cluster-0-gaae7b0dc9`
- v1.85.2 and `heads-public-cluster-0-gaae7b0dc9`

**Comment by valyala** [comment]
The improvements mentioned above have been included in [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @nevlkv , could you verify whether `vmselect v1.87.0` uses less memory than `vmselect v1.86.2` on your workload?

**Comment by nevlkv** [comment]
vmselect 

1.85.2 vs 1.87.0
memory
![изображение](https://user-images.githubusercontent.com/46656585/217287974-cb5b9a93-e936-426a-87b7-1d4808fe489f.png)
cpu
![изображение](https://user-images.githubusercontent.com/46656585/217288155-c1b04ac8-0aab-4641-86b3-afd02cce646a.png)


I`m sorry for not existence screenshots for `heads-public-cluster-0-gaae7b0dc9`

**Comment by nevlkv** [comment]
6h uptime 1.87.0
![изображение](https://user-images.githubusercontent.com/46656585/217334222-143aeabf-5018-4ad0-901c-5dc1450a910b.png)
![изображение](https://user-images.githubusercontent.com/46656585/217334393-f52c7974-386e-4c2f-9930-03cbb7fc4dcf.png)

**Comment by nevlkv** [comment]
downgrade vmselect 
1.87.0 -> 1.85.3

memory
![изображение](https://user-images.githubusercontent.com/46656585/217726576-a2f259cd-78ef-4112-a6f5-25698a9b4e49.png)
cpu
![изображение](https://user-images.githubusercontent.com/46656585/217726676-bd915ebb-f54a-4b4b-8f15-265a3af13307.png)
vmalert
group avg evaluation duration
![изображение](https://user-images.githubusercontent.com/46656585/217727091-5948615c-d32a-4b14-a9bc-22551db43d06.png)

**Comment by valyala** [comment]
@nevlkv , thanks for the provided screenshots and sorry for the delayed answer.

Could you run `vmselect` [v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html) with the command-line flag `-internStringMaxLen=100` and see whether this reduces memory usage on your workload? If this will not help reducing memory usage, try running `vmselect` with lower values for `-internStringMaxLen` such as `-internStringMaxLen=30` and `-internStringMaxLen=10` .

**Comment by nevlkv** [comment]
![image](https://user-images.githubusercontent.com/46656585/223361324-b966fbdf-7364-4cbb-b66e-dba423d15d0f.png)
@valyala thank you
1.85.3 / 1.88.1 (-internStringMaxLen=100) mass OOMs  / 1.88.1 (-internStringMaxLen=50)

**Comment by valyala** [comment]
@nevlkv , thanks for providing memory usage graphs for different values of `-internStringMaxLen`!

Could you verify whether `vmselect` uses lower amounts of memory by default (e.g. without the need to configure `-internStringMaxLen` command-line flag) starting from [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html)?

**Comment by nevlkv** [comment]
@valyala  I will try upgrade my clusters on next week

**Comment by nevlkv** [comment]
upgrade to 1.90.0, clean custom `-internStringMaxLen`, all ok
