### ISSUE TITLE
Not able to add datasource to grafana

### ISSUE THREAD

**Issue by alexa22013** [VictoriaMetrics/VictoriaMetrics#3695]
Hey, 
I am using single server victoriametrics for metrics from prometheus, but I am not able to add datasource to grafana
url - http://victoriametrics-url:8428
It shows "Failed to load resource: the server responded with a status of 502"
Although I can access the url on browser and also the vmui dashboard

Am I missing out something?

**Comment by dmitryk-dk** [comment]
Hi @alexa22013 ! Try to check this [link](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker)
Here you can find how datasource is configured. And you can find some helpful information.

Can you run ```curl http://victoriametrics-url:8428/health```?

**Comment by hagen1778** [comment]
Hello @alexa22013!
The error from the screenshot points to the issues with Grafana, not the datasource. I'd recommend to follow recommendation and check JS console logs.

Another piece of advice is to try running our [docker-compose](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker) environment first to ensure everything works correctly. When you're happy with it - migrate its configuration to your primary installation.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if problem still exists.
