### ISSUE TITLE
Chaining external vmselects, influencing port number

### ISSUE THREAD

**Issue by jstaffans-relex** [VictoriaMetrics/VictoriaMetrics#3701]
We have two geographically separated K8s setups with the clustered version of VictoriaMetrics deployed. vmselect is deployed behind an nginx ingress controller. We'd like to add a vmselect layer on top which would run in one of the K8s clusters and aggregate results from both. 

It seems that by default, when chaining vmselects, the top-level vmselect always appends port 8401 when querying data. 

```
...
storageNode: "vmselect.in.another.cluster.example.com"
...
```

which in our case fails because port 8401 is not open in nginx ingress controller:

```
error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage vmselect.in.another.cluster.example.com:8401: cannot obtain connection from a pool: cannot dial vmselect.in.another.cluster.example.com:8401
```

Is the port that the top-level vmselect uses hard-coded or can we influence it? We'd like to change it to 443 so that queries to the external storage nodes would go via their nginx ingress controllers and not straight to their native port.

**Comment by jstaffans-relex** [comment]
It seems we can overwrite the port:

```
storageNode: "vmselect.in.another.cluster.example.com:443"
```

```
error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage metrics-select.dev.dev.ia.relexsolutions.com:443: cannot obtain connection from a pool: cannot perform "vmselect" handshake with server "metrics-select.dev.dev.ia.relexsolutions.com:443": cannot read success response after sending hello: unexpected message obtained; got "HT"; want "ok"
```

... so I guess TLS is not supported, I found https://github.com/VictoriaMetrics/VictoriaMetrics/issues/550 though.

**Comment by jstaffans-relex** [comment]
It seems we can influence the port but anyways, TLS is not supported. But I did find https://github.com/VictoriaMetrics/VictoriaMetrics/issues/550 which I guess would be the solution.

**Comment by jiekun** [comment]
Hello @jstaffans-relex 
I think you've found it on [Multi-level cluster setup](https://docs.victoriametrics.com/cluster-victoriametrics/#multi-level-cluster-setup) and `-clusternativeListenAddr=:8401`.

So I'm closing this issue now.
