### ISSUE TITLE
vmui: add min/max/avg values to line legends and line tooltips

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#3706]
### Is your feature request related to a problem? Please describe

Sometimes it is useful to know min, max and avg values per each line displayed on the graph.

### Describe the solution you'd like

It would be great if min, max and avg values are displayed per each line's legend.
It would be great also to see min, max and avg values in a tooltip when hovering the line on the graph.

### Describe alternatives you've considered

To try to estimate the min, max and avg values by looking at the graph :)

**Comment by tenmozes** [comment]
which one is better average or median?

**Comment by valyala** [comment]
This feature has been implemented in [vmui v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html). Closing it as done.

**Comment by valyala** [comment]
> let's start with the average. Probably, it should be substituted with median in the future.

**Comment by valyala** [comment]
The `avg` has been substituted with `median` in the commit 25a9017a72c82d3cbc4ce295c7cee3be8c0f827d . This commit will be included in the next release.

**Comment by hagen1778** [comment]
Hi @Loori-R ! 
Thanks for implementing the feature! I find it really cool but I'd like to request a change:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/2902918/218789042-efa6c25f-a8fc-4c50-921f-e8e1ce597bca.png">

Can we visually separate the current value from all other values? The usage pattern assumes you always look for the current value at the specific moment of time in the tooltip. All extra values overcomplicate the task of checking the current value. 
As a solution, I'm proposing to at least separate current value and rest with a new line:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/2902918/218790097-8155f107-03f0-4214-adbd-45cc0f1aaf93.png">

I also think there is no point in `last` value in the tooltip, but it makes sense in the legend though.
And I think there is no point in printing empty labels `{}` sign either.

**Comment by valyala** [comment]
@hagen1778 , the proposed enhancement has been implemented in the commit 87f1ed5d87fd2eba0d7aa724e4f60366489246b4 . This commit will be included in the next release. In the mean time you can test it at [vmui playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/?g0.expr=sum(rate(process_cpu_seconds_total))&g0.range_input=30m&g0.end_input=2023-02-15T07%3A44%3A42&g0.relative_time=last_30_minutes).

**Comment by valyala** [comment]
FYI, the `avg` has been substituted with `median` on graph tooltip and graph legend in [VictoriaMetrics v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by timkuijsten** [comment]
> FYI, the `avg` has been substituted with `median` on graph tooltip and graph legend in [VictoriaMetrics v1.88.0](https://docs.victoriametrics.com/CHANGELOG.html).

As an example of where the average is more interesting than the median. I'm measuring the latency of many network peers by continuously pinging them. Here I'm very interested in hosts that show spiky behaviour and I don't want the extremes to be leveled out, to the contrary.
