### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/VictoriaMetrics#371]
**Describe the bug**
```
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xbe5f7a, 0x16)
        runtime/panic.go:1112 +0x72
runtime.sysMap(0xc6b8000000, 0x4000000, 0x114cdf8)
        runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1132260, 0x800000, 0x1132268, 0x2e4)
        runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x1132260, 0x2e4, 0x0)
        runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x1132260, 0x2e4, 0x7f587eff0100, 0x114ce08, 0x24)
        runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x1132260, 0x2e4, 0x460001, 0x1132260)
        runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x5c8000, 0x100, 0x0)
        runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        runtime/malloc.go:1047 +0x46
runtime.systemstack(0xc0080e6480)
        runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        runtime/proc.go:1041

goroutine 3466077 [running]:
runtime.systemstack_switch()
        runtime/asm_amd64.s:330 fp=0xc0a0abe708 sp=0xc0a0abe700 pc=0x466690
runtime.mallocgc(0x5c8000, 0x0, 0xc0a0abe800, 0x4ab853)
        runtime/malloc.go:1046 +0x895 fp=0xc0a0abe7a8 sp=0xc0a0abe708 pc=0x40e685
runtime.growslice(0xb0f4e0, 0xc6a06e6000, 0x25e000, 0x25e000, 0x4bc000, 0x0, 0x0, 0xc0080e4380)
        runtime/slice.go:175 +0x14e fp=0xc0a0abe810 sp=0xc0a0abe7a8 pc=0x44dcde
github.com/VictoriaMetrics/VictoriaMetrics/lib/bytesutil.(*ByteBuffer).ReadFrom(0xc1e787c990, 0xcc72a0, 0xc030146580, 0x7f58e05c1150, 0xc4f5f74000, 0x4159e3)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/bytesutil/bytebuffer.go:62 +0x2dc fp=0xc0a0abe8c0 sp=0xc0a0abe810 pc=0x7454ec
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/opentsdbhttp.ParseStream(0xc2b6cec900, 0xc12648, 0x0, 0x0)
```

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./victoria-metrics-prod -version
victoria-metrics-20200226-202222-tags-v1.34.1-0-g63a88a61
```

**Used command-line flags**
`
./victoria-metrics-prod -opentsdbHTTPListenAddr=:4222 -httpListenAddr=:8428 -storageDataPath=/data1/victoria-metrics-data/ -promscrape.maxScrapeSize=167772160 -search.maxUniqueTimeseries=10000000 -retentionPeriod=6 
`

**Additional context**
Add any other context about the problem here such as error logs from VictoriaMetrics and Prometheus,
`/metrics` output, screenshots from the official Grafana dashboards for VictoriaMetrics:

**Comment by hagen1778** [comment]
Hi @yincongcyincong!
The `out of memory` is not the application error and hardly may be interpreted as bug. The reason of such an error could be either very tight memory limits on the machine where VM is running or amount of data that doesn't correspond to available resources.

In order to detect the cause could you please answer following questions:
1. What are the memory limits of the instance or container where VM runs
2. What is the payload that you ingest into VM
3. When does the error happens? On query time? What exact query do you run?

To answer questions 2 and 3 please use our dashboards https://grafana.com/orgs/victoriametrics/dashboards. The screenshots should be fine.

Some additional information that may explain the memory usage:
```
Each active time series requires up to 1KB of RAM. Active means that the time series is recently queried or new data is inserted into the time series. This means that the maximum number of active time series can be calculated as RAM size / 1KB. For instance, machine with 64GB of RAM can process up to 64 millions of active time series. The actual RAM size per active time series depends on the number of labels and the lengths of the label values per each time series. Higher number of labels per time series require more RAM.
```

**Comment by yincongcyincong** [comment]
```Mem:  65564400k total, 57164092k used,  8400308k free,   288064k buffers```
this is my instance memory, i use ```-memory.allowedPercent=40``` to limit vm's memory, 
but its memory over 40 percent, now it is 60 percent, i don't know how to solve the problem

**Comment by yincongcyincong** [comment]
this is the error log 
```
2020-03-15T14:35:09.078Z        info    VictoriaMetrics/lib/storage/partition.go:1169  
 merged 12820591 rows in 12.936 seconds at 991053 rows/sec to 
"/data1/victoria-metricsdata/data/small/2020_03/
12820591_5724311_20200315143000.000_20200315143400.000_15FC1
06F15303685"; sizeBytes: 69663550
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0xbe5f7a, 0x16)
        runtime/panic.go:1112 +0x72
runtime.sysMap(0xc804000000, 0x4000000, 0x114cdf8)
        runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x1132260, 0x1800000, 0x1132268, 0xa98)
        runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x1132260, 0xa98, 0x0)
        runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x1132260, 0xa98, 0x7f5bace10000, 0x114ce08, 0xaa)
        runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x1132260, 0xa98, 0x460100, 0x1132260)
        runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x1530000, 0x100000001, 0x0)
```

**Comment by hagen1778** [comment]
Could you pls also provide screenshots from Grafana dashboard for VM? I'm highly interested in: active time series, churn rate, concurrent inserts, datapoints, datapoints ingestion rate, pending datapoints, merge speed.

**Comment by yincongcyincong** [comment]
i find the answer, because Too much memory in Java which result in my vm down, thank you very much

**Comment by laratutoteam** [comment]
**get this easy error solving** https://laratuto.com/solved-out-of-memory-error-in-query-sybase_connect/
