### ISSUE TITLE
Why there are 2 jobs when defining a vmpodscrape

### ISSUE THREAD

**Issue by dw-3** [VictoriaMetrics/VictoriaMetrics#3718]
### Describe the bug

Why there are 2 jobs when defining a vmpodscrape

### To Reproduce

1

### Version

1

**Comment by dw-3** [comment]
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  labels:
    app: kube-prometheus-stack-coredns
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 43.2.1
    chart: kube-prometheus-stack-43.2.1
    heritage: Helm
    release: prometheus-operator
  name: kubernetes-java
  namespace: gke-monitor
spec:
  jobLabel: job
  podMetricsEndpoints:
  - relabelConfigs:
    - action: replace
      source_labels:
        - job
      targetLabel: job
      replacement: 'kubernetes-java'
    path: /actuator/prometheus
    port: actuator
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      language: java

**Comment by dw-3** [comment]
![image](https://user-images.githubusercontent.com/20983001/215303747-89fff420-9f76-4d2f-96bd-4b303556da4e.png)

**Comment by dw-3** [comment]
Why does this happen？

**Comment by dw-3** [comment]
I just want to modify the name of the job in vmscrape

**Comment by fatsheep9146** [comment]
I think this issue should be created in the operator repo? @f41gh7

**Comment by f41gh7** [comment]
I think it's an issue with yaml indent. You have to remove `-` in front of `bearerTokenFile`. In your case given `VMPodScrape` has two different `podMetricsEndpoints`. Separate job created for each endpoint by operator.
