### ISSUE TITLE
How to delete "instance" label

### ISSUE THREAD

**Issue by liuxiaoliu-lxl** [VictoriaMetrics/VictoriaMetrics#3719]
### Is your feature request related to a problem? Please describe

Because our current metrics is too large,found a label "instance" default "__address__",delete label "instance" the data will be wrong.instance is necessary?

### Describe the solution you'd like

Want to remove "instance" label from the metrics,does not cause data error.

**Comment by denisgolius** [comment]
Hi!
I recommend to check our [blog post](https://victoriametrics.com/blog/cardinality-explorer/ ) which should give more information about cardinality in VictoriaMetrics and https://docs.victoriametrics.com/Troubleshooting.html .

As for label deletion - there is no such functionality but as workaround you can export time series via https://docs.victoriametrics.com/url-examples.html#apiv1export, make modifications to data, [remove time series from VictoriaMetrics](https://docs.victoriametrics.com/guides/guide-delete-or-replace-metrics.html) and [import modified data to VIctoriaMetrics](https://docs.victoriametrics.com/url-examples.html#apiv1import).

**Comment by hagen1778** [comment]
@denisgolius response seems to be relevant and has all the details.
@liuxiaoliu-lxl I think it covers the question, so I am closing the issue.
