### ISSUE TITLE
Metrics migrated using VMCTL is deleted/missing

### ISSUE THREAD

**Issue by SaiUmeshKumar** [VictoriaMetrics/VictoriaMetrics#3722]
### Describe the bug

I have two victoria metrics clusters, cluster1 with 21d retention and cluster2 with 180d retention. I used VMCTL to migrate data of a week (22 Nov to 29 Nov, 2022) from cluster1 to cluster2. After the migration, validated the metrics were present in the cluster2. Checking now, not seeing data in the cluster2

Original metrics from cluster1: 
![Screenshot 2022-12-13 at 5 39 59 PM](https://user-images.githubusercontent.com/47415432/215397087-ffdee2eb-9b12-4d49-8470-230a39f24107.jpeg)

Migrated metrics from cluster2:

![Screenshot 2022-12-13 at 5 37 47 PM](https://user-images.githubusercontent.com/47415432/215397169-1e95caff-dcd3-4d04-a25c-66d3525de37f.jpeg)

### To Reproduce

NA

### Version

Both the victoria metrics clusters are on `v1.83.1-cluster` version and running on K8s.

vmstorage-20221110-224904-tags-v1.83.1-cluster-0-g6d984cdef

**Comment by dmitryk-dk** [comment]
HI @SaiUmeshKumar ! This is not vmctl related. Please check this part of the change log
https://docs.victoriametrics.com/CHANGELOG.html#v1831
and upgrade your cluster, please

**Comment by SaiUmeshKumar** [comment]
@dmitryk-dk thanks for quick response. Will upgrade and let you know

**Comment by dmitryk-dk** [comment]
@SaiUmeshKumar ! Can we close the issue?

**Comment by SaiUmeshKumar** [comment]
Sure... Will revert if i'm still seeing the issue after the upgrade

**Comment by dmitryk-dk** [comment]
Close resolved!

**Comment by SaiUmeshKumar** [comment]
@dmitryk-dk  Able to get around to the upgrade... I'm able to see those metrics now.
