### ISSUE TITLE
add more sample limit metrics for alert 

### ISSUE THREAD

**Issue by lzfhust** [VictoriaMetrics/VictoriaMetrics#3723]
### Is your feature request related to a problem? Please describe

We are using vmagent for scraping many applications. Sometimes sample limit happened. When sample limit happened, the metrics is dropped and alerts are pushed to our colleagues. Their metrics are gone and they usually don't know why.
Therefore we want to know more information about the corresponding sample limit target. Whith the metrics, we can push a sample limit alert to tell them more information such as application&namespace&job

### Describe the solution you'd like

save more information about the corresponding sample limit target, such as the lables of the target.

**Comment by lzfhust** [comment]
We are trying to commit a pull request to this feature.
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3724

**Comment by hagen1778** [comment]
Hi @lzfhust!

> Whith the metrics, we can push a sample limit alert to tell them more information such as application&namespace&job

These labels are already present in auto-generated metrics. For example:
```
scrape_samples_limit{instance="demo.robustperception.io:9090"job="demo-rp"}
scrape_samples_limit{instance="localhost:8428"job="victoriametrics"pod="victoriametrics-pod"}
```
Do you observe something different?

**Comment by lzfhust** [comment]
> #3724
The scrape_samples_limit metrics tells us the sample limit value of the config. Howerver, if we use vmagent scraping multiple applications, when sample limit happened, we want to know which the corresponding application is.

**Comment by lzfhust** [comment]
> Hi @lzfhust!
> 
> > Whith the metrics, we can push a sample limit alert to tell them more information such as application&namespace&job
> 
> These labels are already present in auto-generated metrics. For example:
> 
> ```
> scrape_samples_limit{instance="demo.robustperception.io:9090"job="demo-rp"}
> scrape_samples_limit{instance="localhost:8428"job="victoriametrics"pod="victoriametrics-pod"}
> ```
> 
> Do you observe something different?

The current scrape_samples_limit metric tells us the sample limit value of the config.

**Comment by hagen1778** [comment]
> When sample limit happened for one application, we need to know and get alert, since sample limit means all the metrics of one application is gone.

What exactly do you mean by `application`? Do you have multiple applications per `job`?

**Comment by lzfhust** [comment]
> > When sample limit happened for one application, we need to know and get alert, since sample limit means all the metrics of one application is gone.
> 
> What exactly do you mean by `application`? Do you have multiple applications per `job`?

Hi @hagen1778 
Yes. For example, we have more than twenty applications in one namespace of a kubernetes cluster. We use one vmagent job to scrape these applications

**Comment by hagen1778** [comment]
I see. Thanks for sharing details.

I've checked the PR and I am confused even more. I'll tag other contributors just in case they get it @zekker6 @f41gh7 

I'll try to write down my interpretation of what I understand from this request. And please correct me if I am wrong.

So let's imagine we have a scrape job:
```
  - job_name: 'my-job'
    sample_limit: 20
    static_configs:
      - targets:
          - 'host1'
          - 'host2'
         labels:
          app: my-app
```

When `sample_limit: 20` will be reached, we'll get the following metrics:
```
scrape_samples_limit{instance="host1", job="my-job", app="my-app"}
scrape_samples_limit{instance="host2", job="my-job", app="my-app"}
```
This ^ is what we have already.

What you're proposing is that we should add to `scrape_samples_limit` labels from the samples that were dropped because of the limit? Is this correct?

**Comment by f41gh7** [comment]
Hello, currently vmagent exposes following metrics per target:

`scrape_samples_post_metric_relabeling` - number of samples after relabeling scrapped from target.
`scrape_samples_limit` - configured limit for target.

 Alerting rule should check following expression:

`expr: scrape_samples_post_metric_relabeling > scrape_samples_limit`

**Comment by lzfhust** [comment]
> 
In this example, sample_limit in config is 20 and we get this:

**Comment by lzfhust** [comment]
> I see. Thanks for sharing details.
> 
> I've checked the PR and now I am confused even more. I'll tag other contributors just in case they get it @zekker6 @f41gh7
> 
> I'll try to write down my interpretation of what I understand from this request. And please correct me if I am wrong.
> 
> So let's imagine we have a scrape job:
> 
> ```
>   - job_name: 'my-job'
>     sample_limit: 20
>     static_configs:
>       - targets:
>           - 'host1'
>           - 'host2'
>          labels:
>           app: my-app
> ```
> 
> When `sample_limit: 20` is reached, we'll get the following metrics:
> 
> ```
> scrape_samples_limit{instance="host1", job="my-job", app="my-app"}
> scrape_samples_limit{instance="host2", job="my-job", app="my-app"}
> ```
> 
> This ^ is what we have already.
> 
> What you're proposing is that we should add to `scrape_samples_limit` labels from the samples that were dropped because of the limit? For example, if there was a metric `cpu_seconds_total{cpu="1", pod="my-pod"}` then its labels need to be copied to `scrape_samples_limit`:
> 
> ```
> scrape_samples_limit{instance="host1", job="my-job", app="my-app", cpu="1", pod="my-pod"}
> ```
> 
> Is this correct?
@hagen1778 Hi
In this example, sample limit is 20 and we get the metrics:
      scrape_samples_limit{instance="host1", job="my-job", app="my-app"}
But I think this metric tell us we have set sample limit in scrape config, but can not tell us whether sample limit really happen or when sample limit really happen? Is that correct? so this metric can not be used in alerting rule which can tell us sample limit really happened?

**Comment by hagen1778** [comment]
> So I want to add another metric when sample limit really happened and use the added metric in alerting rule

I think, you can use the following expression:
```
  scrape_samples_scraped / scrape_samples_limit > 1
```
It would return you only those jobs which exceed the `scrape_samples_limit`. And you can use it as an alerting rule.

**Comment by lzfhust** [comment]
> > So I want to add another metric when sample limit really happened and use the added metric in alerting rule
> 
> I think, you can use the following expression:
> 
> ```
>   scrape_samples_scraped / scrape_samples_limit > 1
> ```
> 
> It would return you only those jobs which exceed the `scrape_samples_limit`. And you can use it as an alerting rule.

yes, you are right. I haven't noticed this. sorry for this issue

**Comment by hagen1778** [comment]
Feel free to open a new issue if you find other obstacles.

**Comment by valyala** [comment]
The following docs may be useful regarding this issue - [automatically genetated metrics](https://docs.victoriametrics.com/vmagent.html#automatically-generated-metrics)
