### ISSUE TITLE
Azure blob storage: VM doesn't start - permission denied to move folder

### ISSUE THREAD

**Issue by Ags-saltillo** [VictoriaMetrics/VictoriaMetrics#3729]
### Describe the bug

I want to upgrade VM from 1.75.0 to 1.86.2, but when pod start give me this error.

VM has a persistent storage on Azure Blob Storage. If a rollback to previous version of VM (v.175.0), it's start correcty.
I have tried with previous versions (v1.86.0, v1.86.1) and we have the same issue.  I have tried too, with empty shared folder with the same error.
What has changed to be able to access the storage correctly?

### To Reproduce

Deploy new deployment with v1.86.2 with persistent volume on Azure Blob Storage.

### Version

AKS: v1.24.6
VM Single: v1.86.2

### Logs

2023-01-30T14:24:04.620Z panic VictoriaMetrics/lib/fs/fs.go:237 FATAL: cannot move /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 to /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: rename /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: permission denied
panic: FATAL: cannot move /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 to /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: rename /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679 /victoria-metrics-data/data/small/2023_01/16772_16772_20230130141920.176_20230130141927.660_173F1BF07C75A679.must-remove.1675088560992895650: permission denied

goroutine 44 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xb6c582, 0x5}, {0xc001f64b40, 0x224}, 0x3?)
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa9d
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xb6c582, 0x5}, {0xb7f58b?, 0x2?}, {0xc0138f7888?, 0xc0138f7858?, 0x0?})
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1d6
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustRemoveDirAtomic({0xc018b9c000, 0x6c})
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs.go:237 +0x1d0
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.runTransaction(0xc0160e4680?, {0xc00002b230, 0x29}, {0xc00002b260, 0x27}, {0xc0160e4680, 0x3e})
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:2084 +0x825
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).openCreatedPart(0xc00010c300, 0xc000e4f2f0, {0xc0130f3e00?, 0xf, 0x10}, 0x0, {0xc00002b230, 0x29}, {0xc00dc80e40, 0x3e}, ...)
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1515 +0x3c5
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeParts(0xc00010c300, {0xc0130f3e00, 0xf, 0x10}, 0xc000a0cf00?, 0x0)
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1346 +0x9e7
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeExistingParts(0xc00010c300, 0x48?)
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1187 +0x388
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).mergeWorker(0xc00010c300)
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1059 +0x65
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers.func1()
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1046 +0x25
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).startMergeWorkers
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go:1045 +0x37

### Used command-line flags

          - -promscrape.config=/etc/prometheus/prometheus.yml
          - -storageDataPath=/victoria-metrics-data
          - -selfScrapeInterval=10s
          - -retentionPeriod=30d
          - -search.maxConcurrentRequests=16
          - -search.maxQueryDuration=60s
          - -search.maxUniqueTimeseries=2000000
          - -search.maxQueueDuration=60s
          - -memory.allowedPercent=70
          - -promscrape.dropOriginalLabels
          - -maxConcurrentInserts=6
          - -http.maxGracefulShutdownDuration=30s
          - -httpAuth.username=$(VM_USER)
          - -httpAuth.password=$(VM_PWD)

**Comment by f41gh7** [comment]
It may be related to this commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/5b488a339d7c81cf33473235a8ab85420c5a10c7

 But in general it may be an issue with your filesystem, as far as I know Azure Blob Storage is object storage.  Maybe its driver is not POSIX complaint.

**Comment by f41gh7** [comment]
It was introduced at v1.82.0 version https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.82.0

**Comment by Ags-saltillo** [comment]
Wow! ... i wanted to fix this issue [#3038](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3038) but ... it's fixed on v1.82.0, what can i do?

**Comment by mariol-ais** [comment]
I experience same issue using Azure File storage, installing latest helm chart which uses:
victoriametrics/vmstorage:v1.86.2-cluster

```
{"ts":"2023-02-01T12:17:30.194Z","level":"panic","caller":"VictoriaMetrics/lib/fs/fs.go:237","msg":"FATAL: cannot move /storage/data/small/2023_02/8328_8328_20230201121621.785_20230201121643.707_173FB2717EB09724 to /storage/data/small/2023_02/8328_8328_202302011216 ││ 21.785_20230201121643.707_173FB2717EB09724.must-remove.1675253781743922993: rename /storage/data/small/2023_02/8328_8328_20230201121621.785_20230201121643.707_173FB2717EB09724 /storage/data/small/2023_02/8328_8328_20230201121621.785_20230201121643.707_173FB2717EB09 ││ 724.must-remove.1675253781743922993: permission denied"
```

**Comment by zekker6** [comment]
@mariol-ais As far as I can see, Azure file storage is a cloud-based NFS/SMB offering. Most likely you are facing permissions issue. You need to configure file system permissions to be matching user which is used to run VictoriaMetrics.
For k9s you can use [securityContex](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod) to achieve that:
```
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
```

@Ags-saltillo Azure Blob Storage is S3-like storage, which can be mounted to be used as VictoriaMetrics storage by using different FUSE drivers. Using this approach can cause issues as FUSE drivers are usually not fully POSIX compliant.
If you're using regular block devices please check if advice above helps.
