### ISSUE TITLE
vmbackup: snapshots are not deleted after backup

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#3735]
### Describe the bug

When vmbackup completes backup it does not delete create snapshot.

### To Reproduce

/usr/local/bin/victoriametrics/vmbackup-prod \
                  -storageDataPath=/var/lib/victoria-metrics-data \
                  -snapshot.createURL=http://localhost:8482/snapshot/create \
                  -dst=fs:///srv/backup/$(hostname -f)/

### Version

v1.86.2

### Logs

2023-02-01T09:18:18.472Z info VictoriaMetrics/app/vmbackup/main.go:72 Snapshot delete url http://localhost:8482/snapshot/create

**Comment by valyala** [comment]
This issue has been fixed in [vmbackup v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it then.
