### ISSUE TITLE
PromQL - Differences between Prometheus and VictoriaMetrics

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#374]
**Describe the bug**
We are currently evaluating VictoriaMetrics to centralize metrics collected from Prometheus. The Prometheus instance is receiving 25k samples/s and sending them through the remote write API to a single node VictoriaMetrics and a VictoriaMetrics cluster for comparison.
Everything works fine except that we are seeing different results from PromQL queries between VictoriaMetrics and Prometheus. We are using the same Prometheus instance to do the query and the remote write.
VM Single Node and VM Cluster produce the same result but not Prometheus.
What can explain the differences seen?

**To Reproduce**
Here is an example of a query that produces different results: sum(rate(fastly_rt_errors_total[30s]))

**Expected behavior**
Same query result between Prometheus and VictoriaMetrics

**Screenshots**
From VictoriaMetrics:
<img width="1603" alt="Screen Shot 2020-03-18 at 1 54 06 PM" src="https://user-images.githubusercontent.com/37348934/76992746-13c98580-6922-11ea-8223-c2212a840505.png">

From Prometheus:
<img width="1585" alt="Screen Shot 2020-03-18 at 1 53 56 PM" src="https://user-images.githubusercontent.com/37348934/76992716-09a78700-6922-11ea-9908-2dc8dc635276.png">

**Version**
```
image: "victoriametrics/victoria-metrics:v1.33.1"
```

**Used command-line flags**
```
- "--retentionPeriod=1"
- "--selfScrapeInterval=10s"
- "--storageDataPath=/storage"
```

Thanks!

**Comment by hagen1778** [comment]
Hi @alexandv ! The difference is expected. Pls see second paragraph for more details https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL

**Comment by alexandv** [comment]
Thanks @hagen1778 
I guess this is the main difference in the case of the query I'm using:
> MetricsQL takes into account the previous point before the window in square brackets for range functions such as rate and increase. It also doesn't extrapolate range function results. This addresses this issue from Prometheus.

**Comment by denisgolius** [comment]
Closing it as done.
