### ISSUE TITLE
Provide an option to override Step query param for specific alert

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3741]
### Is your feature request related to a problem? Please describe

There is no option to redefine step for one alert (in specific cases we need to increase the default provider)

### Describe the solution you'd like

Add option `step` or `queryStep` in yaml configuration for specific alert

**Comment by hagen1778** [comment]
@tenmozes the `step` param can be set on Group's level via params option:
```
groups:
  - name: TestGroup
     params:
       step: ["1s"]
```
Rules with such `params` config will issue queries with `step=1s`, overriding the default `-datasource.queryStep` value.
