### ISSUE TITLE
VMalert is failing to execute queries

### ISSUE THREAD

**Issue by kumarshivam12** [VictoriaMetrics/VictoriaMetrics#3751]
We have our vmcluster setup running in Kubernetes and VMagent running in standalone EC2 machine in AWS. We have one more EC2 machine which is running vmalert and alertmanager as systemd service. Data ingestion is working fine and running queries via UI is also working fine. 
We are getting errors in vmalert for multiple alert groups once the service is started after ~5-8 minutes.
Error logs looks like
```
vmalert[15398]: 2023-02-03T05:00:15.146Z  error   
VictoriaMetrics/app/vmalert/group.go:288  group "GROUP NAME": rule "RULE NAME": failed to execute: failed to execute query 
"count(samza:org_apache_samza_system_kafka_KafkaSystemConsumerMetrics:messages_behind_high_watermark{}) != 60":
error getting response from https://vmselect.x.com/select/1003:2/prometheus/api/v1/query?
query=QUERY Post "https://vmselect.x.com/select/1003:2/prometheus/api/v1/query?
query=QUERY": EOF
```
We are running the VMcluster components in ARM64 machines. We tried increasing the compute resources as well, but that didn’t helped either.
These are the flags used in all the components
```
Vmstorage -
bigMergeConcurrency: '3'
search.maxUniqueTimeseries: '9000000'
```
```
VMselect
search.maxConcurrentRequests: '64'
search.maxQueryLen: '1638400'
search.maxQueueDuration: 600s
search.maxSamplesPerSeries: '50000000'
search.maxSeries: '2500000'
search.maxTSDBStatusSeries: '800000000'
search.maxUniqueTimeseries: '2500000'
```
```
VMinsert
All default
```
```
VMalert
/bin/vmalert-prod  -rule=/home/ubuntu/alert-rules/rule1/*.yml -rule=/home/ubuntu/alert-rules/rule2/*.yml -configCheckInterval=5m 
-datasource.url=https://vmselect.x.com/select/1003:2/prometheus -
remoteWrite.url=https://vminsert.x.com/insert/1003:2/prometheus -
remoteRead.url=https://vmselect.x.moengage.com/select/1003:2/prometheus -notifier.url=http://localhost:9093
```
```
Metrics Dashboards for more information - Last 6 Hours
```
<img width="1354" alt="Screenshot 2023-02-03 at 12 49 59 PM" src="https://user-images.githubusercontent.com/26067882/216536957-ec3841f9-38eb-417d-a1e0-2bb9d5355209.png">

<img width="1353" alt="Screenshot 2023-02-03 at 12 51 05 PM" src="https://user-images.githubusercontent.com/26067882/216537153-6d588648-247f-4a9d-a7de-168eb2a15cdf.png">

<img width="1367" alt="Screenshot 2023-02-03 at 12 52 07 PM" src="https://user-images.githubusercontent.com/26067882/216537353-f0beb796-547c-48ee-8ef1-dda69c7c86bc.png">

**Comment by hagen1778** [comment]
Hello @kumarshivam12!
Thanks for detailed issue and sorry for the late reply.

The config and charts looking good except the "Slow Inserts" panel - it is something wrong with it. It shouldn't exceed 100% and is usually below 1% on avg. Worth checking what's wrong with it. Please refer to publicly available dashboard [here](https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz/victoriametrics-cluster?orgId=2&viewPanel=107&editPanel=107)

Regarding the vmalert issue - it is likely a network connection issue between vmalert and vmselects. Usually, EOF refers to the fact that network connection was closed. Either by vmselect or by some balancer between vmalert and vmselect. It is worth checking the logs of both components to see what exactly happens.
Sometimes, old types of network balancers do not respect KeepAlive connections. Try disabling using those on the vmalert side by setting `-datasource.disableKeepAlive=true` command-line flag.

I'd also add that if you occasionally see EOF errors - it is not a big problem. Vmalert and VictoriaMetrics are tolerant to such errors and you shouldn't worry too much.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to re-open if the issue still remains.
