### ISSUE TITLE
A typo in GitHub release notes

### ISSUE THREAD

**Issue by Chupaka** [VictoriaMetrics/VictoriaMetrics#3760]
### Describe the bug

Releases since v1.29.0 mention "`vmutils-*.tag.gz` archive" which should be "`tar.gz`" instead.

### To Reproduce

Open https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.29.0 or any later release and see.

### Version

Any version >= v1.29.0

### Screenshots

<kbd><img width="285" alt="image" src="https://user-images.githubusercontent.com/3432808/216781036-e21604d0-6f8e-4121-bccd-dced2140deea.png"></kbd>

**Comment by valyala** [comment]
@Chupaka , thanks for filing the issue! The typo has been fixed in [the latest release docs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
