### ISSUE TITLE
Wrong vmstorage port number for vminsert image in docker-compose-cluster.yml

### ISSUE THREAD

**Issue by SunKyu** [VictoriaMetrics/VictoriaMetrics#3767]
### Describe the bug

It looks like wrong port number for vminsert image

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c9a32ebaf745c7136e9730133dcd49203b61c332/deployment/docker/docker-compose-cluster.yml#L57-L65

`line 64` `.1.87.0` supposed to be fix to `:8400`

### To Reproduce

.

### Version

.

**Comment by hagen1778** [comment]
Thanks for report! Is addressed at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3769
