### ISSUE TITLE
vmstorage not running after OOM 

### ISSUE THREAD

**Issue by edyaya** [VictoriaMetrics/VictoriaMetrics#3774]
### Describe the bug

After OOM vmstorage didn't start with error on the virtual machine in the proxmox cluster

### To Reproduce

Delete flag -memory.allowedPercent  from storages
Apply load until the memory on the virtual machine is exhausted

### Version

/usr/bin/vmstorage-prod -version
vmstorage-20220707-232254-tags-v1.78.1-cluster-0-gd27a375d3

### Logs

` cannot find both source and destination paths: "/data/victoria-metrics/indexdb/170561D25BFB4401/tmp/174114B9922F4F0D" -> "/data/victoria-metrics/indexdb/170561D25BFB4401/179239_779_174114B9922F4F0D"; this may be the case after unclean shutdown (OOM, kill -9, hard reset) on NFS disk`

### Additional information

```
df -hT

/dev/sdb1        xfs       1000G         753G  248G           76% /data

```

```
cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

Delete folder  /data/victoria-metrics/indexdb/170561D25BFB4401/txn helped me , but it is not "NFS disk"

**Comment by hagen1778** [comment]
It is likely related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3038 and was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.82.0
Can you try updating and trying to reproduce the issue again?

**Comment by hagen1778** [comment]
Closing as inactive. Feel free to reopen if https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3774#issuecomment-1420660763 doesn't help.
