### ISSUE TITLE
Inconsistent results of queries with aggregation

### ISSUE THREAD

**Issue by cskinfill** [VictoriaMetrics/VictoriaMetrics#3776]
### Describe the bug

This query `(count(cluster_partition_under_replicated_replicas{cluster=~"prod1",topic!="",topic!="_schemas"}) by (cluster,topic,partition) < 3)` returns over 1K responses, including a response with `{topic="mytopic"}`, however if I run the following filtered query `(count(cluster_partition_under_replicated_replicas{cluster=~"prod1",topic!="",topic!="_schemas", topic="mytopic"}) by (cluster,topic,partition))` I get back a result of `3`, which means it should NOT have been returned by the query with original query.  When I use the VMUI and trace the two queries, once I dig down to where vmselect queries all the vmstorage nodes, I see storage node `vmstorage-vm-13` report ```sent 0 blocks to vmselect``` for the first query (without the `topic` filter), while for the second query (with the explicit topic filter), that same vmstorage node reports ```sent 7 blocks to vmselect```.  Why?  The first query is used in a VMRule, and vmalert is firing alerts because of it.

We upgraded this morning from v1.83.1-cluster to v1.87.0-cluster and tracked the alerts starting to fire to around the time we upgraded.  We rolled back the from v1.87.0-cluster back to v1.83.1-cluster are still see the same problem.

### To Reproduce

In my cluster, running these queries consistently reproduces this result.  

### Version

v1.87.0-cluster and v1.83.1

### Additional information

Using the victoriametrics operator and helm chart.

**Comment by hagen1778** [comment]
Hello @cskinfill! 
That's a weird way of using query filters `topic!="",topic!="_schemas", topic="mytopic"`. 
Can you try modifying the original query to `topic!~"|_schemas"` and check if `mytopic` is present? And also try modifying the second query to filter just via `cluster=~"prod1",topic="mytopic"`?
I'd also appreciate traces if inconsistency remains.

**Comment by cskinfill** [comment]
approximately 3 hours later the same query was executed again in grafana and the expected results where returned.  In addition, the alert from vmalert cleared.  I don't know if this is related to rolling back the upgrade or due to something else.

Is it possible to download a trace?

**Comment by hagen1778** [comment]
> Is it possible to download a trace?

Sure! You can just share the json text or file here. Such file can be then executed in VMUI. See playground here https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/trace

**Comment by hagen1778** [comment]
> approximately 3 hours later the same query was executed again in grafana and the expected results where returned. In addition, the alert from vmalert cleared. I don't know if this is related to rolling back the upgrade or due to something else.

Have you out ruled the possible cache inconsistency? See more here https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results

**Comment by hagen1778** [comment]
Closing the issue due to lack of activity
