### ISSUE TITLE
FATAL: cannot determine free disk space on "/tmp/searchResults": open /tmp/searchResults: no such file or directory

### ISSUE THREAD

**Issue by yangzai2717** [VictoriaMetrics/VictoriaMetrics#3778]
### Describe the bug

When vmselect starts, it will get the storageDataPath+/tmp directory and create a temporary directory.After a period of time, after/tmp/searchResults is cleared by the system, vmselect will report an error: FATAL: cannot determine free disk space on "/tmp/searchResults": open /tmp/searchResults: no such file or directory, and then stop running

### To Reproduce

After the server cleans up the /tmp/searchResults directory file.

### Version

vmselect-20221126-050742-tags-v1.84.0-cluster-0-gd0461bec2

### Logs

2023-01-31T19:40:06.675Z        panic   VictoriaMetrics/lib/fs/fs_unix.go:50    FATAL: cannot determine free disk space on "/tmp/searchResults": open /tmp/searchResults: no such file or directory
panic: FATAL: cannot determine free disk space on "/tmp/searchResults": open /tmp/searchResults: no such file or directory

goroutine 30406189 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
        github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:229 +0x65
panic({0x8cc7c0, 0xc0012b7da0})
        runtime/panic.go:890 +0x262
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x930f68, 0x5}, {0xc000595a80, 0x73}, 0x2?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:269 +0x975
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x930f68, 0x5}, {0x94ae3e?, 0x4cc993?}, {0xc0022833d0?, 0x40e59f?, 0xc0023eec00?})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:137 +0x1d6
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:129
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:125
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.mustGetFreeSpace({0xc00098a090, 0x12})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs_unix.go:50 +0x125
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustGetFreeSpace({0xc00098a090, 0x12})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs.go:399 +0x110
github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.glob..func3()
        github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:91 +0x27
github.com/VictoriaMetrics/metrics.(*Gauge).marshalTo(0x8b3bc0?, {0x9461d7, 0x28}, {0xabe720, 0xc00062e690})
        github.com/VictoriaMetrics/metrics@v1.23.0/gauge.go:40 +0x42
github.com/VictoriaMetrics/metrics.(*Set).WritePrometheus(0xc0002bc200, {0xabe9e0, 0xc000383758})
        github.com/VictoriaMetrics/metrics@v1.23.0/set.go:53 +0x1c4
github.com/VictoriaMetrics/metrics.WritePrometheus({0xabe9e0, 0xc000383758}, 0x1)
        github.com/VictoriaMetrics/metrics@v1.23.0/metrics.go:85 +0x257
github.com/VictoriaMetrics/VictoriaMetrics/lib/appmetrics.writePrometheusMetrics({0xabe9e0, 0xc000383758})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/appmetrics/appmetrics.go:46 +0x45
github.com/VictoriaMetrics/VictoriaMetrics/lib/appmetrics.WritePrometheusMetrics({0x7f87dc46e080, 0xc00062e630})
        github.com/VictoriaMetrics/VictoriaMetrics/lib/appmetrics/appmetrics.go:29 +0xc5
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper(0xc000b98510, {0xac1080?, 0xc00062e630}, 0xc0010b0a00, 0xa434f0)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:301 +0xabc
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.gzipHandler.func1({0xac1290?, 0xc0024f62a0?}, 0x7f87dc6cbee8?)
        github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:197 +0x76
net/http.HandlerFunc.ServeHTTP(0x0?, {0xac1290?, 0xc0024f62a0?}, 0x469b8e?)
        net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0xc000c76210?}, {0xac1290, 0xc0024f62a0}, 0xc0010b0a00)
        net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc00099c140, {0xac1800, 0xc000c761b0})
        net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db

**Comment by hagen1778** [comment]
Hello @yangzai2717! Why would `/tmp/searchResults` be cleared by system? The directory is created and should belong to the vmselect process. It is not expected this directory can be modified by other processes in the system.

**Comment by yangzai2717** [comment]
Because there is tmpwatch on our server, the temporary files in the /tmp directory will be cleaned regularly

**Comment by yangzai2717** [comment]
hello， @hagen1778 ，Can we set the storageDatapath when vmselect is started? I didn't find it in vmselect in the document？

**Comment by hagen1778** [comment]
>hello， @hagen1778 ，Can we set the storageDatapath when vmselect is started? I didn't find it in vmselect in the document？

Yes, you can set the full path via `cacheDataPath` command-line flag.

**Comment by yangzai2717** [comment]
All right. Thank you
