### ISSUE TITLE
Extend HTTP API response for /query and /query_range handlers with processing stats

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3779]
### Is your feature request related to a problem? Please describe

When executing a query, user has access only to two metrics:
1. Time it gets to execute
2. Data in response

However, this data is not enough to answer the following questions:
1. How expensive was the query in terms of matched series?
2. How much resources (cpu or mem) was spent on the processing?
3. Did the query actually match something?

The first two questions could help to build a system that would notify users about expensiveness of their queries. It is also a first step for building a quota-based system which would limit the amount of resources one user could spend for their queries.

The third question would be extremely helpful for alerting rules. It would help to identify the correctness of the rule's expression. Because if alerting rules doesn't match a single series - it is likely a bad query with wrong filters.

### Describe the solution you'd like

I'd like to extend HTTP API response to add an additional object to the JSON in response:
```json
{
  "status": "success",
  "isPartial": false,
  "data": {
    "resultType": "vector",
    "result": []
  },
+  "stats":{
+    "series": <int>,
+    "samples": <int>,
+    "blocks": <int>,
+    "memory_bytes": <int>,
+  }
}
```

The new object `stats` could have contain additional stats collected during the query processing:
* series - amount of processed time series
* samples - amount of data samples within processed series
* blocks - amount of data blocks transferred from vmstorage to vmselect
* memory_bytes - memory needed to process the query

### Describe alternatives you've considered

Use query [tracing](https://docs.victoriametrics.com/#query-tracing). This is good alternative, but a bit complex to use.

**Comment by hagen1778** [comment]
cc @valyala

**Comment by f41gh7** [comment]
I believe it's relevant and useful information.

 Related issue which needs some of these stats https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3553
