### ISSUE TITLE
vm-storage component not merge correctly

### ISSUE THREAD

**Issue by gaoxp** [VictoriaMetrics/VictoriaMetrics#3782]
### Describe the bug

we use vmstorage to store our monitor data, but if often appears that one or some storage node not merge correctly, small part can not merge into big part.

### To Reproduce

here is some picture
![vm-merge](https://user-images.githubusercontent.com/13375117/217415869-db159b52-b973-46ed-b2ce-03047cc97998.png)
![vm-merge2](https://user-images.githubusercontent.com/13375117/217415893-ebf742f8-3b1f-4d81-9d6f-f3a1e8b8e883.png)
![vm-merge3](https://user-images.githubusercontent.com/13375117/217415921-bc03df30-248c-4072-8204-5620276a6e89.png)
we find when vmstorage do merge work, it use disk free space to caculate a maxOutBytes, when it find part which can be merged it use maxOutBytes/concurrencyMergeCount/minMergeMultiplier(1.7) as maxInPartBytes。In our case small increase to 20G, when free disk space reduce, maxOutBytes also reduce, then maxInPartBytes also reduce, then this big small part will not merged into big part because when it find parts can be merged,it skipped those 20G parts. as far we can change small/big concurrent worker count make those small parts merged into big part,but this is not a good idea, so how can i avoid this case occurs？

### Version

 vmstorage-prod -version
vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5

### Used command-line flags

/usr/local/bin/vmstorage-prod \
   -enableTCP6 \
   -retentionPeriod=14d \
   -memory.allowedBytes=150GiB \
   -search.maxTagKeys=5000 \
   -search.maxTagValueSuffixesPerSearch=200000 \
   -search.maxTagValues=200000 \
   -smallMergeConcurrency=8 \
   -storageDataPath=/data25/vm/vmstorage-data/

**Comment by valyala** [comment]
VictoriaMetrics needs at least `sum(source part sizes)` free disk space when merging source parts, because it merges the source parts into a destination part in a temporary directory. When the merge is complete, VictoriaMetrics atomically replaces source parts with the destination part, and then removes the source parts. The size of the destination part is usually less or equal to the sum of sizes of the source parts. That's why it needs `sum(source part sizes)` free disk space for the merge. If VictoriaMetrics has no enough free disk space for the merge some source parts, then it doesn't merge them in order to prevent from out of disk space errors, as in your case. So it is recommended to have at least 20% of free disk space in order to guarantee normal merge process. See [these docs](https://docs.victoriametrics.com/#storage) for more details.

**Comment by gaoxp** [comment]
> free



> VictoriaMetrics needs at least `sum(source part sizes)` free disk space when merging source parts, because it merges the source parts into a destination part in a temporary directory. When the merge is complete, VictoriaMetrics atomically replaces source parts with the destination part, and then removes the source parts. The size of the destination part is usually less or equal to the sum of sizes of the source parts. That's why it needs `sum(source part sizes)` free disk space for the merge. If VictoriaMetrics has no enough free disk space for the merge some source parts, then it doesn't merge them in order to prevent from out of disk space errors, as in your case. So it is recommended to have at least 20% of free disk space in order to guarantee normal merge process. See [these docs](https://docs.victoriametrics.com/#storage) for more details.

our machine has 30% of free disk space,but small part also can't be merged into big part until i changed small part and big part concurrency worker. 
![merge11](https://user-images.githubusercontent.com/13375117/218023271-fe4281e7-b184-4aa2-957d-6063dfd68f3c.png)
![Uploading merge12.png…]()

**Comment by gaoxp** [comment]
![merge12](https://user-images.githubusercontent.com/13375117/218023433-9c1f2758-2474-484d-9167-164666730861.png)

**Comment by gaoxp** [comment]
<img width="1545" alt="image" src="https://user-images.githubusercontent.com/13375117/218026491-ee51d1ae-1cba-40fd-a643-675dd6a9a63b.png">
<img width="1821" alt="image" src="https://user-images.githubusercontent.com/13375117/218026673-7f7495f0-452b-4b86-85cd-dcf7f62f0841.png">
this machine also have the same issue as above mentioned.In storage path we only have too many small parts, there is no one big parts

**Comment by gaoxp** [comment]
There is another problem, when  we change 10.135.29.171 this machine small/big concurrency worker count and restart vmstorage service, it started to do merge work, but this merge work exhausted the free disk space which is 600G+(45% free disk space). I read the merge parts logic， with that logics, i think it should not happen, can you give us some more advise?

**Comment by gaoxp** [comment]
> ![merge12](https://user-images.githubusercontent.com/13375117/218023433-9c1f2758-2474-484d-9167-164666730861.png) Why does this happen?It looks like merge worker was not normally worked, and we have less and less disk space, then we only have too many small parts and zero big parts



> VictoriaMetrics needs at least `sum(source part sizes)` free disk space when merging source parts, because it merges the source parts into a destination part in a temporary directory. When the merge is complete, VictoriaMetrics atomically replaces source parts with the destination part, and then removes the source parts. The size of the destination part is usually less or equal to the sum of sizes of the source parts. That's why it needs `sum(source part sizes)` free disk space for the merge. If VictoriaMetrics has no enough free disk space for the merge some source parts, then it doesn't merge them in order to prevent from out of disk space errors, as in your case. So it is recommended to have at least 20% of free disk space in order to guarantee normal merge process. See [these docs](https://docs.victoriametrics.com/#storage) for more details.

#####
I add some log print to find why small parts can't merge to big parts, i also find partition struct has bigMergesCount and small merges count, this indicates how many merge workers is working for now, is it ok to use this sum(bigMergesCount, smallMergesCount) to calculate maxOutBytes？
#####
2023-02-13T08:18:27.987Z	info	lib/storage/partition.go:1449	###search outSize: 18763760394 is bigger than maxOutBytes: 17563893248, src[27:35], first path is: /data00/vm/vmstorage-data/data/small/2023_02/248903194_15210745_20230213030303.000_20230213032657.000_174343F82F2CA7B4, last path is: /data00/vm/vmstorage-data/data/small/2023_02/2358811794_12765724_20230212152200.000_20230212163458.000_17431BE03DE7D663

**Comment by gaoxp** [comment]
> > ![merge12](https://user-images.githubusercontent.com/13375117/218023433-9c1f2758-2474-484d-9167-164666730861.png) Why does this happen?It looks like merge worker was not normally worked, and we have less and less disk space, then we only have too many small parts and zero big parts
> 
> > VictoriaMetrics needs at least `sum(source part sizes)` free disk space when merging source parts, because it merges the source parts into a destination part in a temporary directory. When the merge is complete, VictoriaMetrics atomically replaces source parts with the destination part, and then removes the source parts. The size of the destination part is usually less or equal to the sum of sizes of the source parts. That's why it needs `sum(source part sizes)` free disk space for the merge. If VictoriaMetrics has no enough free disk space for the merge some source parts, then it doesn't merge them in order to prevent from out of disk space errors, as in your case. So it is recommended to have at least 20% of free disk space in order to guarantee normal merge process. See [these docs](https://docs.victoriametrics.com/#storage) for more details.
> 
> I add some log print to find why small parts can't merge to big parts, i also find partition struct has bigMergesCount and small merges count, this indicates how many merge workers is working for now, is it ok to use this sum(bigMergesCount, smallMergesCount) to calculate maxOutBytes？
> 
> 2023-02-13T08:18:27.987Z info lib/storage/partition.go:1449 ###search outSize: 18763760394 is bigger than maxOutBytes: 17563893248, src[27:35], first path is: /data00/vm/vmstorage-data/data/small/2023_02/248903194_15210745_20230213030303.000_20230213032657.000_174343F82F2CA7B4, last path is: /data00/vm/vmstorage-data/data/small/2023_02/2358811794_12765724_20230212152200.000_20230212163458.000_17431BE03DE7D663

If use sum(bigMergesCount, smallMergesCount) there will have another issue..

**Comment by valyala** [comment]
@gaoxp , thanks for the additional details!

> If `-smallMergeConcurrency` and `-bigMergeConcurrency` parameters are related to merge work, it is better to have a hint

Yes, these parameters may limit the maximum size of parts, which can be generated by the [background merge process](https://docs.victoriametrics.com/#storage). But this is because of a side effect - in order to try to prevent out of disk space state when multiple background merges are performed simultaneously.

It isn't recommended modifying the default values for `-smallMergeConcurrency` and `-bigMergeConcurrency` command-line flags, since this may lead to non-optimal [background merges](https://docs.victoriametrics.com/#storage) and various issues such as infinite growth of small parts if big merge workers have no enough CPU for the keeping up with the data ingestion rate.

@gaoxp , could you try upgrading VictoriaMetrics cluster components to [the latest release](https://docs.victoriametrics.com/CHANGELOG.html) according to [these instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#updating--reconfiguring-cluster-nodes) and verify whether it fixes the issue with too many small parts? The version you run - `vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5` (e.g. v1.62.0) is too old and may contain some issues with the background merge process, which were fixed in later releases.

**Comment by gaoxp** [comment]
> @gaoxp , thanks for the additional details!
> 
> > If `-smallMergeConcurrency` and `-bigMergeConcurrency` parameters are related to merge work, it is better to have a hint
> 
> Yes, these parameters may limit the maximum size of parts, which can be generated by the [background merge process](https://docs.victoriametrics.com/#storage). But this is because of a side effect - in order to try to prevent out of disk space state when multiple background merges are performed simultaneously.
> 
> It isn't recommended modifying the default values for `-smallMergeConcurrency` and `-bigMergeConcurrency` command-line flags, since this may lead to non-optimal [background merges](https://docs.victoriametrics.com/#storage) and various issues such as infinite growth of small parts if big merge workers have no enough CPU for the keeping up with the data ingestion rate.
> 
> @gaoxp , could you try upgrading VictoriaMetrics cluster components to [the latest release](https://docs.victoriametrics.com/CHANGELOG.html) according to [these instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#updating--reconfiguring-cluster-nodes) and verify whether it fixes the issue with too many small parts? The version you run - `vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5` (e.g. v1.62.0) is too old and may contain some issues with the background merge process, which were fixed in later releases.

Sorry, it has been a long time since you gave me this reply，now we upgrade our cluster to version 1.87.3. I find this feature: * FEATURE: deprecate `-bigMergeConcurrency` command-line flag, since improper configuration for this flag frequently led to uncontrolled growth of unmerged parts, which, in turn, could lead to queries slowdown and increased CPU usage. The concurrency for [background merges](​https://docs.victoriametrics.com/#storage) can be controlled via `-smallMergeConcurrency` command-line flag, though it isn't recommended to do in general case.
we will check if it works well. We have been plagued by this "uncontrolled growth of unmerged parts" problem for a long time

**Comment by gaoxp** [comment]
> @gaoxp , thanks for the additional details!
> 
> > If `-smallMergeConcurrency` and `-bigMergeConcurrency` parameters are related to merge work, it is better to have a hint
> 
> Yes, these parameters may limit the maximum size of parts, which can be generated by the [background merge process](https://docs.victoriametrics.com/#storage). But this is because of a side effect - in order to try to prevent out of disk space state when multiple background merges are performed simultaneously.
> 
> It isn't recommended modifying the default values for `-smallMergeConcurrency` and `-bigMergeConcurrency` command-line flags, since this may lead to non-optimal [background merges](https://docs.victoriametrics.com/#storage) and various issues such as infinite growth of small parts if big merge workers have no enough CPU for the keeping up with the data ingestion rate.
> 
> @gaoxp , could you try upgrading VictoriaMetrics cluster components to [the latest release](https://docs.victoriametrics.com/CHANGELOG.html) according to [these instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#updating--reconfiguring-cluster-nodes) and verify whether it fixes the issue with too many small parts? The version you run - `vmstorage-20210625-104421-tags-v1.62.0-cluster-0-gdb66ea9a5` (e.g. v1.62.0) is too old and may contain some issues with the background merge process, which were fixed in later releases.

Sorry, it has been a long time since you gave me this reply，now we upgrade our cluster to version 1.87.3. But I find this feature in master branch: * FEATURE: deprecate -bigMergeConcurrency command-line flag, since improper configuration for this flag frequently led to uncontrolled growth of unmerged parts, which, in turn, could lead to queries slowdown and increased CPU usage. The concurrency for background merges can be controlled via -smallMergeConcurrency command-line flag, though it isn't recommended to do in general case.
I hope this future version will solve our problem because we have been plagued by this "uncontrolled growth of unmerged parts" problem for a long time.
