### ISSUE TITLE
Victoria Metrics Pod Restarts

### ISSUE THREAD

**Issue by kochoudh** [VictoriaMetrics/VictoriaMetrics#3786]
### Is your feature request related to a problem? Please describe

Hello,

We have Victoria Metrics deployed on 3 different Kubernetes Red Hat clusters, and we are observing pod restarts only on 1 cluster and NFS version of all three cluster is 4.

Below are the logs observed while restart.

Logs:

"/victoria-metrics-data/data/small/2022_03/txn/16D8482DA4E6534F.tmp.1999": open /victoria-metrics-data/data/small/2022_03/txn/16D8482DA4E6534F.tmp.1999: permission denied
panic: FATAL: unrecoverable error when merging small parts in the partition "/victoria-metrics-data/data/small/2022_03": cannot create transaction file "/victoria-metrics-data/data/small/2022_03/txn/16D8482DA4E6534F": cannot create file "/victoria-metrics-data/data/small/2022_03/txn/16D8482DA4E6534F.tmp.1999": cannot create file "/victoria-metrics-data/data/small/2022_03/txn/16D8482DA4E6534F.tmp.1999": open /victoria-metrics-data/data/small/2022_03/txn/16D8482DA4E6534F.tmp.1999: permission denied
 
goroutine 230 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0xb5dd1c, 0x4b}, {0xc000a1f600, 0x1ee}, 0x2)
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:270 +0x994
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0xb5dd1c, 0x0}, {0xb8def9, 0x0}, {0xc0000b3f88, 0x0, 0x0})

 Can someone please guide on this. 

### Describe the solution you'd like

Is this Application Issue or Cluster Issue?

**Comment by dmitryk-dk** [comment]
Hi @kochoudh ! As I can see from your logs, you have a permissions error. Can you check that Vm can read from folder?

**Comment by hagen1778** [comment]
It is likely the problem is caused by misconfiguration or insufficient permissions as @dmitryk-dk noticed [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3786#issuecomment-1422339965).
Closing the issue as inactive.
