### ISSUE TITLE
/api/v1/import not work when import big data

### ISSUE THREAD

**Issue by lzyan** [VictoriaMetrics/VictoriaMetrics#379]
VictoriaMetric version 1.34.2

Use /api/v1/export to export exist vm data
curl -H 'Accept-Encoding: gzip' http://x.x.x.x:8428/api/v1/export -d 'match={__name__!=""}' > exported_data.jsonl.gz

data file size is 205546310079 byte. When use /api/v1/import to import this data file 
curl -X POST -H 'Content-Encoding: gzip' http://x.x.x.x:8428/api/v1/import -T exported_data.jsonl.gz

but it not works and promotes:
error in "/api/v1/import": cannot read vmimport data: too long line: more than 104857600 bytes"

After read all doc can't find any answer. 
How to solve this issue?

Thanks

**Comment by lzyan** [comment]
Find that new VM version 1.34.3 already support new param 'max_rows_per_line' when export. 
ignore and close this topic.

**Comment by valyala** [comment]
FYI, the upcoming VictoriaMetrics release will support optimized data import/export via `/api/v1/export/native` and `/api/v1/export/native`. See [the corresponding docs](https://victoriametrics.github.io/#how-to-import-time-series-data) and [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/787#issuecomment-700632551) for details.

**Comment by valyala** [comment]
Optimized data export/import is available starting from [v1.42.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
