### ISSUE TITLE
Introduce disk IO limiting option for historical data downsamping and deduplication

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#3790]
### Is your feature request related to a problem? Please describe

 Currently, deduplication may saturate disk usage and slow down data ingestion. It's limited for single CPU, but at high load clusters it may be not enough.

### Describe the solution you'd like

 Introduce flags: --mergeLimitReadMBs --mergeLimitWriteMBs.

 It should define read and write limits with MB per second.

**Comment by valyala** [comment]
It has been appeared that long background merges could lead to data ingestion slowdown and query performance degradation on systems with low number of available CPU cores (1 or 2). This issue has been addressed in the commit 3ec8a4dc80e650dbdad9a73b0cd9b78eb292a1bf , which will be included in the next release. The temporary workaround is to run single-node VictoriaMetrics (or `vmstorage` in cluster version) with the `GOMAXPROCS=3` environment variable.

**Comment by valyala** [comment]
FYI, the issue mentioned in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3790#issuecomment-1426867464) has been fixed in [v1.87.2](https://docs.victoriametrics.com/CHANGELOG.html).
