### ISSUE TITLE
vmui: tenant selection is not ready for the bit amount of tenants

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3792]
### Is your feature request related to a problem? Please describe

<img width="270" alt="CleanShot 2023-02-08 at 19 22 00@2x" src="https://user-images.githubusercontent.com/1381404/217589518-d9868f64-381f-42c5-8d38-b171ae820b1e.png">
<img width="247" alt="CleanShot 2023-02-08 at 19 22 06@2x" src="https://user-images.githubusercontent.com/1381404/217589528-3439a9b2-fe88-42c3-b3b7-ec46157085ac.png">

### Describe the solution you'd like

- Need to sort tenants: by account id than by project id
- Display up to N of tenants (let be 10 or 25)
- Provide an option to search by tenant

**Comment by valyala** [comment]
This issue has been addressed in [vmui v1.87.1](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as done.
