### ISSUE TITLE
vmctl container not starting / always crashing

### ISSUE THREAD

**Issue by homecasagit** [VictoriaMetrics/VictoriaMetrics#3798]
### Describe the bug

I would like to use vmctl.
I am running VictoriaMetrics on docker and from what I have read, I think I have to use the seperate docker container to do so.

I tried the following containers of the official docker repository:
- victoriametrics/vmctl:v1.87.0
- victoriametrics/vmctl:v1.86.2
- victoriametrics/vmctl:v1.79.8
- victoriametrics/vmctl:v1.79.8-enterprise

All of them keep exiting (exit code 0) immediately. 
With restart policy "unless-stopped" they are in a constant restart loop.
Result: it is not possible to access the console of the container.

Unfortunately I found no documentation on how I can start vmctl. There is none in the repository on docker-hub and also no information in the docs of VM. (The docs explain the usage of vmctl, but not the configuration. If I understand it correctly, using the binary, e.g. via these docker containers, is the recommended deployment method.)

Does it need any specific configuration?
I started the container "as-they-are", without any flags or configuration.

Please point me in the right direction, what am I doing wrong?
Thanks in advance!

### To Reproduce

Deploy the mentioned container and try to start them and access the console.

### Version

I am not sure how to do this when the container is not starting.
But I guess the answer is in the logs of the v1.79.8 containers:
vmctl-20230209-071220-tags-v1.79.8-enterprise-0-g185386cab
vmctl-20230209-065844-tags-v1.79.8-0-gf2907b5d8

### Logs

The logs of the container loop the following for each restart of the container:

Please note:
The VERSION lines are only present in the v1.79.8 containers, both v1.8x.x do not have these two lines.

NAME:
   vmctl - VictoriaMetrics command-line tool
USAGE:
   vmctl [global options] command [command options] [arguments...]
VERSION:
   vmctl-20230209-071220-tags-v1.79.8-enterprise-0-g185386cab
     
:
   opentsdb      Migrate timeseries from OpenTSDB
   influx        Migrate timeseries from InfluxDB
   prometheus    Migrate timeseries from Prometheus
   vm-native     Migrate time series between VictoriaMetrics installations via native binary format
   verify-block  Verifies exported block with VictoriaMetrics Native format
   help, h       Shows a list of commands or help for one command
GLOBAL OPTIONS:
   --help, -h     show help (default: false)
   --version, -v  print the version (default: false)
2023/02/09 13:36:30 Total time: 1.212296ms

### Used command-line flags

none for vmctl

**Comment by dmitryk-dk** [comment]
Hi @homecasagit ! When you run `docker run victoriametrics/vmctl:v1.87.0` it just executes `vmctl`, and in this state `vmctl` shows only its flags like this:
``` docker run victoriametrics/vmctl:v1.87.0
Unable to find image 'victoriametrics/vmctl:v1.87.0' locally
v1.87.0: Pulling from victoriametrics/vmctl
a9eaa45ef418: Already exists 
a35ba3448bbb: Pull complete 
Digest: sha256:488f0890d06893ce59d9d5dfddd2e018eb5e248e19c62bf5b65ca3393603b7ea
Status: Downloaded newer image for victoriametrics/vmctl:v1.87.0
NAME:
   vmctl - VictoriaMetrics command-line tool

USAGE:
   vmctl [global options] command [command options] [arguments...]

COMMANDS:
   opentsdb      Migrate time series from OpenTSDB
   influx        Migrate time series from InfluxDB
   remote-read   Migrate time series via Prometheus remote-read protocol
   prometheus    Migrate time series from Prometheus
   vm-native     Migrate time series between VictoriaMetrics installations via native binary format
   verify-block  Verifies exported block with VictoriaMetrics Native format
   help, h       Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h  show help
2023/02/10 10:48:22 Total time: 757.125µs
```
If you want to use `vmctl` via `docker` you should define all flags after the name of the image something like this
```
docker run -i -t  victoriametrics/vmctl:v1.87.0 remote-read \                                   
--remote-read-src-addr=http://127.0.0.1:10080 \
--remote-read-filter-time-start=2021-10-18T00:00:00Z \
--remote-read-step-interval=hour \
--vm-addr=http://127.0.0.1:8428 \
--vm-concurrency=6
```

Which flags and what how to import data you can read in this part of the documentation [vmctl](https://docs.victoriametrics.com/vmctl.html)

**Comment by homecasagit** [comment]
Hi @dmitryk-dk ,
thank you very much for your help!

This helped me to start the container with the flags. However, unfortunately I ran into the next issue.
I keep it here, as the reason is most likely the same: That I don't know what I have to do ;) 

### Issue

I am trying to import data from influxdb (version 1.8.10)

If I run the command as mentioned below, timeseries are found on the source but I have no option to confirm with "Y".
If I add "-s" to the command to run it without confirmation, it exits before timeseries are found.

**I do not know how to solve this error:**
`error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device`
_full log below_

There is nothing on github and google was not of help for me...

Logs of vmctl are included below, there are no logs in vm.

**Used command:**
_I use this command in Portainer, so it is a single line and therefore backspaces must not be used_

```
influx 
--influx-addr http://[host1]:8086 
--influx-database homeassistant 
--vm-addr http://[host2]:8428 
--influx-filter-time-start 2022-01-01T00:00:000Z 
--influx-filter-time-end 2022-12-31T00:00:000Z 
--vm-extra-label influxdata=1
```

### Log of vmctl

**without -s**
```
InfluxDB import mode
2023/02/10 15:50:10 Exploring scheme for database "homeassistant"
2023/02/10 15:50:10 fetching fields: command: "show field keys"; database: "homeassistant"; retention: "autogen"
2023/02/10 15:50:10 found 124 fields; skipped 172 non-numeric fields
2023/02/10 15:50:10 fetching series: command: "show series"; database: "homeassistant"; retention: "autogen"
2023/02/10 15:50:10 found 302 series
panic: EOF
goroutine 1 [running]:
main.prompt({0xc0001483f0, 0x2b})
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/utils.go:19 +0x216
main.(*influxProcessor).run(0xc0002a5e30, 0x0, 0x40?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/influx.go:47 +0x136
main.main.func2(0xc0001f88c0?)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/main.go:110 +0x647
github.com/urfave/cli/v2.(*Command).Run(0xc0001f88c0, 0xc0000b8ec0, {0xc0002805b0, 0xd, 0xd})
	github.com/urfave/cli/v2@v2.23.7/command.go:271 +0xa42
github.com/urfave/cli/v2.(*Command).Run(0xc0001f9040, 0xc0000b8b00, {0xc0000b2000, 0xe, 0xe})
	github.com/urfave/cli/v2@v2.23.7/command.go:264 +0xc97
github.com/urfave/cli/v2.(*App).RunContext(0xc0002a23c0, {0xb28fd0?, 0xc0000b4000}, {0xc0000b2000, 0xe, 0xe})
	github.com/urfave/cli/v2@v2.23.7/app.go:333 +0x665
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.23.7/app.go:310
main.main()
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmctl/main.go:227 +0xd0b
Found 13862 timeseries to import. Continue? [Y/n] 
```


**including -s for silent mode**
```
InfluxDB import mode
2023/02/10 15:46:14 Exploring scheme for database "homeassistant"
2023/02/10 15:46:14 fetching fields: command: "show field keys"; database: "homeassistant"; retention: "autogen"
2023/02/10 15:46:14 found 124 fields; skipped 172 non-numeric fields
2023/02/10 15:46:14 fetching series: command: "show series"; database: "homeassistant"; retention: "autogen"
2023/02/10 15:46:14 found 302 series
2023/02/10 15:46:14 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
```

### Background
I have a home assistant setup with influxdb as addon. 
I now switched to victoria metrics, running on my docker host and would like to transfer the historic data of 2022 from influx to vm.

- I disabled auth and ssl on the influxdb addon
- I set the -search.disableCache flag in vm
- retention time in vm is 5 years 
- the vm container is running an a macvlan on the dockerhost

I tried vmctl on the dockerhost where vm is running, but with is original IP (as vm is running on macvlan its IP is different)
I also tried it from a completely separate docker host

In both scenarios I can ping both, the source and the target, from a debian container running on the docker hosts. 
I therefore think, that networking is not the issue here.

**Comment by dmitryk-dk** [comment]
Hi @homecasagit ! As a workaround, before I investigate the problem, I recommend you use the binary file to execute. You can find it [releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.1) here as vmutils. 
Maybe we can disable tty usage if it doesn't present. But I need some time to investigate

**Comment by dmitryk-dk** [comment]
Have checked on my local how to backfill by native protocol and use this command
```
docker run -i -t --net=host  victoriametrics/vmctl:v1.87.0 vm-native --vm-native-src-addr=http://host.docker.internal:8428  \
  --vm-native-dst-addr=http://host.docker.internal:8430 \
  --vm-native-filter-match='{__name__!=""}' \
  --vm-native-filter-time-start='2021-10-18T00:00:00Z'
VictoriaMetrics Native import mode
2023/02/10 18:42:14 Initing export pipe from "http://host.docker.internal:8428/api/v1/export/native" with filters: 
        filter: match[]={__name__!=""}
        start: 2021-10-18T00:00:00Z
Initing import process to "http://host.docker.internal:8430/api/v1/import/native":
Total: 29.77 MiB ↗ Speed: 5.45 MiB p/s 
Total: 29.77 MiB ↘ Speed: 4.21 MiB p/s 
2023/02/10 18:42:21 Total time: 7.405063545s
```
As you can see, I use `host.docker.internal` instead of localhost, but I use mac. For linux you should use 
`--add-host host.docker.internal:host-gateway` option.

**Comment by homecasagit** [comment]
**Thank you very much for your time!** 

I had success by using the binary in a separate debian instance.
I used the same command as listed above, so to me it seems like the issue is not the command itself, but rather something in the docker container?

But for me, the issue is solved and if no one else has this issue, the most likely case is, that I am doing something wrong with that vmctl container ;)

**Comment by dmitryk-dk** [comment]
@homecasagit , thank you for the issue)! There seems to be some problem present, but I need to check. Have another request with the influx, and I want to test it tomorrow with your problem. If I find a problem with the terminal, I will fix it).

But at that moment, can we close the issue?

**Comment by homecasagit** [comment]
No problem, thanks again for your time :)

Yes, you can close the issue.

If it helps you (and others that are working on vmctl), here is what I expected from the vmctl container:
I run the container, the container would contain the binary in the folder of the entrypoint.
So I could access the console / command line of the container and use vmctl with exactly the commands as if I would run the binary in a separate machine, which would then be exactly the same as described in the docs.

If this is intentionally not the case, than a small note, either in the docs or in docker hub, regarding the container would be helpful.
Something like the following, used a lot of your first comment as it helped me:

> Please note:
> If you are using the vmctl docker container you should define all flags after the name of the image.
> Example:
> ```
> docker run -i -t  victoriametrics/vmctl:v1.87.0 remote-read \                                   
> --remote-read-src-addr=http://127.0.0.1:10080 \
> --remote-read-filter-time-start=2021-10-18T00:00:00Z \
> --remote-read-step-interval=hour \
> --vm-addr=http://127.0.0.1:8428 \
> --vm-concurrency=6
> ```
> 
> Available flags and how to import data can be read in this part of the documentation: [vmctl](https://docs.victoriametrics.com/vmctl.html).

**Comment by dmitryk-dk** [comment]
Yes, you are right! We should update the documentation with some docker examples and how to use It with docker! 

Close it as resolved. But need to investigate and update docs as I mentioned before.
