### ISSUE TITLE
Mismach query results when using step 

### ISSUE THREAD

**Issue by thunderbird86** [VictoriaMetrics/VictoriaMetrics#3799]
### Describe the bug

When I increasing step interval in queries, I've got a mismatching results for related metrics
e.g.
here is the chart with 2 queries on it 
`sum(container_memory_working_set_bytes{namespace="foo",pod=~"bar-.*"})`
and
`sum(kube_pod_container_resource_limits_memory_bytes{namespace="foo",pod=~"bar-.*"})`

And here is how chart looks like 

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/11559172/218039543-6395fcca-7f3a-4e46-bee2-800f9f4b56b8.png">

But when I add step for queris:
`sum(container_memory_working_set_bytes{namespace="foo",pod=~"bar-.*"})[:1h]`
and
`sum(kube_pod_container_resource_limits_memory_bytes{namespace="foo",pod=~"bar-.*"})[:1h]`
Is't starts look like this, usage overlap limit, what actually can not be
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/11559172/218040237-512e7fb3-4e1e-4951-931d-966ce7d0a9af.png">

I've fond that is happening because step aggregation  return different  amount of datapoints for this two metrics.
Here is I'am adding `by (bod)` to queries 
`sum(container_memory_working_set_bytes{namespace="foo",pod=~"bar-.*"}) by (bod) [:1h]`
and
`sum(kube_pod_container_resource_limits_memory_bytes{namespace="foo",pod=~"bar-.*"}) by (bod) [:1h]`

It's filtered by one particular pod 
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/11559172/218041059-6f98c31f-5f30-4e3b-acb0-beb1ea162f83.png">

and here is the next one 
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/11559172/218041375-28f00e51-c6d0-43ea-ab7e-ad302927533d.png">

So we can find that is limit merics goes more or less like one line, but for usage metric we have overlap windows 
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/11559172/218042056-87e1b800-046e-4854-b5dc-cadcaf38b0cd.png">

Which became a spikes which overlap limit line.

And raw metrics for each pod has the same amount of datapoints 

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/11559172/218042543-12799e97-24b5-4c13-acf9-6b9a10db66bb.png">

### To Reproduce

Add step interval for queries  
`sum(container_memory_working_set_bytes{namespace="foo",pod=~"bar-.*"})[:1h]`
and
`sum(kube_pod_container_resource_limits_memory_bytes{namespace="foo",pod=~"bar-.*"})[:1h]`

### Version

vminsert-20230118-202834-tags-v1.86.2-cluster-0-g069042653

**Comment by zekker6** [comment]
@thunderbird86 You're facing so-called `ephemeral` datapoints here.
You can find a detailed overview of query exectution logic [here](https://docs.victoriametrics.com/keyConcepts.html#range-query)

The idea is that query result might contain datapoints which do not exist in real data. This is needed to cover cases with missed scrapes and allows to fill the gaps between successful scrapes.
In this case, when step is set to 1h so it query result is aligned to 1h intervals. For example here is a metric which stops receiving samples at 04:05.
![1676560517](https://user-images.githubusercontent.com/1367798/219407495-844596ad-a47d-4146-ad7e-db30e59d75cf.png)
As far as you can see, rounding result will produce a datapoint at 05:00 since we did have data for this and one more datapoint which is `ephemeral`.

In your case, when some metric for pod is disappearing and new pod is created large steps produces clash for those metrics, so that `sum()` will receive datasamples from 2 timeseries(old and new pod). 
If you will filter limit metric one-by-one you will notice that same thing happens with it.

**Comment by thunderbird86** [comment]
@zekker6 you can find on 3-rd chart `working` and `limit` metrics for one particular pod. I can share more charts with , both metrics has step `[:1h]` in query, and for working limits I'm getting `ephemeral ` for `working` metric, but not for `limit`. And on last chart you can see that raw data has started and stoped receiving  at the same time, with same amount of datapoints. And if I would have `ephemeral` datapoints for `limit`  it wasn't be the issue.

**Comment by zekker6** [comment]
@thunderbird86 Could you share an example of the following queries graphs:
```
 sum(kube_pod_container_resource_limits_memory_bytes{namespace="foo",pod=~"bar-.*"})[:1h]
 sum(kube_pod_container_resource_limits_memory_bytes{namespace="foo",pod=~"bar-.*"})

 sum(container_memory_working_set_bytes{namespace="foo",pod=~"bar-.*"})[:1h]
 sum(container_memory_working_set_bytes{namespace="foo",pod=~"bar-.*"})
```
To see raw data and data with step for both limits and actual memory usage.

It seems to me that `kube_pod_container_resource_limits_memory_bytes` will disappear a little bit earlier than `container_memory_working_set_bytes` and that leads to graphs with `emphemeral` datapoints.

**Comment by thunderbird86** [comment]
@zekker6  here is it

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/11559172/219876270-e27623bd-0a06-4487-aa1c-92d211970c18.png">

this one with the scale, and we can see that `container_memory_working_set_bytes` disappear earlier for few scrapes. 

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/11559172/219876178-09a0f560-4abc-4602-ad6b-3fbccc51bb45.png">

**Comment by thunderbird86** [comment]
Let me elaborate on this problem. 
Here is the same querys in Prometheus  (request/limit/usage)
<img width="1699" alt="image" src="https://user-images.githubusercontent.com/11559172/219879536-eaf939ce-feed-499d-b558-ff859308a65b.png">
And here how it looks like in Victoria 
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/11559172/219879610-421cd1ff-5440-400a-9c8a-1c8d0f4cfcc2.png">

Raw data the same (Prometheus scraping and than send data to Victoria via remote write)

My concern for now, that I can not use Victoria because charts shows me unreal results

**Comment by zekker6** [comment]
@thunderbird86 Could you [export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) time series used in your example so that I could reproduce this and advice on how to fix this?
In order to have accurate results it is needed to include 4 time series total into export: usage and limit for old and new pod.
Feel free to remove any labels containing sensitive information, only values related to these queries are needed to reproduce this case.

**Comment by thunderbird86** [comment]
@zekker6 it's tricky. I've exported ts like you said. Change some labels (didn't delete any), and Import this data to test VM Cluster to check. And get a proper result, even with twice increased step 

sum(kube_pod_container_resource_limits_memory_bytes{namespace="my_ns"}) [:2h]
sum(container_memory_working_set_bytes{namespace="my_ns"}) [:2h] 

<img width="1648" alt="image" src="https://user-images.githubusercontent.com/11559172/222692119-c2ee3be9-9583-4c72-a32a-4bbf839653d0.png">


But In main database still have corrupted result 

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/11559172/222693026-9fcc0c51-2e78-4e61-9581-e190d7e988ae.png">

Anyway here is raw data:
[exported_ts.json.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10880828/exported_ts.json.zip)

**Comment by hagen1778** [comment]
@zekker6 could you please take a look?

**Comment by zekker6** [comment]
I've tested those queries on 1.86.2 with exported data and it doesn't reproduce here either.

@thunderbird86 Could you check if this reproduces when importing the same raw data without modifications?
Ideally, it would be great if you could export data for those metrics without additional filters and run tests based on this data.

It seems like there are duplicated datapoints present which were filtered out during export or during labels modifications. Those datapoints might be created by having multiple scraping prometheus/vmagent instances. If that's the case you will need to configure `-dedup.minScrapeInterval=1ms` at vmselect and vmstorage level.

**Comment by thunderbird86** [comment]
Importing metrics without any changes gives the same result - it doesn't reproduce the issue. 

My suggestion that it's because dynamically detected lookback from interval between time series datapoints works in different way which is related about of data. 
When I've added `-search.maxLookback=30s`,  even if it 5m, it completely change result in a good way.

Here is how it looks now 
<img width="1643" alt="image" src="https://user-images.githubusercontent.com/11559172/224993101-3ffac131-24f0-442b-aefe-1109fd24cf3c.png">

Realted architecture: I have 2 Prometheus instances with following config 
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
```
And they use `remote_write` to send data to Victoria
Also this configs for vm instances 
```
  vmselect:
    extraArgs:
      search.minStalenessInterval: 120s
      dedup.minScrapeInterval: 15s
      memory.allowedPercent: '90'
      replicationFactor: '2'
      search.maxConcurrentRequests: '6'
      search.maxMemoryPerQuery: 1GB
      search.maxQueryLen: 4MB
      search.maxQueryDuration: 2m
      search.maxQueueDuration: 30s
      search.maxSamplesPerQuery: '1000000000'
      search.maxUniqueTimeseries: '150000'
      vmalert.proxyURL: "http://victoria-metrics-alert-server.vmalert.svc.cluster.local:8880"
  vmstorage:
    extraArgs:
      dedup.minScrapeInterval: 15s
      search.maxUniqueTimeseries: '500000'
```
