### ISSUE TITLE
The number of `match[]={__name__=~".*"}` and `Active time series` are different

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#380]
**Describe the bug**

with 2 storage node, the number of `match[]={__name__=~".*"}` and `Active time series` are 
 different. see step 1, and step 2.

1. `series count by /series api`
``` 
curl -s 127.0.0.1:8481/select/0/prometheus/api/v1/series -d 'match[]={__name__=~".*"}' -d "start=$(date +%s -d '2 day ago')" | jq -c '.data[]'  | wc -l
14766253
```

2. `sum of active timeseries`
```
sum(vm_cache_entries{type="storage/hour_metric_ids"})
20889112
```

3. `vm_cache_entries`
```
10.89.96.55:8482 storage/tsid 29168403
10.89.96.57:8482 storage/tsid 28905669
10.89.96.57:8482 storage/hour_metric_ids 10444719
10.89.96.55:8482 storage/hour_metric_ids 10444393
10.89.96.55:8482 storage/date_metricID 10136885
10.89.96.57:8482 storage/date_metricID 9865537
10.89.96.55:8482 storage/metricName 5191
10.89.96.57:8482 storage/metricName 4889
...
```

4.  `/series/count`
```
curl -s 127.0.0.1:8481/select/0/prometheus/api/v1/series/count | jq '.data[]'
66637258
```

**Expected behavior**
the number of `series count by /series` is close to the `sum(vm_cache_entries{type="storage/hour_metric_ids"})` 

**Version**
```
cluster version, commitID: d23df53ba28bd80bd17508586d01847c6d34dbda
```

**Used command-line flags**
```
vmstorage -search.maxUniqueTimeseries 10000000
vminsert -storageNode=10.89.96.55:8400 -storageNode=10.89.96.57:8400 -influxSkipSingleField
vmselect -storageNode=10.89.96.55:8401 -storageNode=10.89.96.57:8401 -search.maxQueryDuration 86400s
```

**Comment by valyala** [comment]
The `/api/v1/series` handler by default returns metainfo for time series with values inserted during the last 5 minutes unless `start` arg is set. See [the /api/v1/series docs](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) for details on query args. See also #91 .

The `vm_cache_entries{type="storage/hour_metric_ids"}` metric reflects the number of time series with values inserted during the last hour (actually, up to 2 hours).

So these numbers may differ.

**Comment by n4mine** [comment]
i think, the api result must `great than` the active number of series.
when they have `same duration` or the api request use `2 days ago` as `start` in this case

it's show up:
1. in last 2 days: `14766253` series were inserted
2. but in last 1/2 hours, it's `20889112` series is active.

it's confused

**Comment by valyala** [comment]
Correct - the `vm_cache_entries{type="storage/hour_metric_ids"}` is just an estimation and it can count each active time series twice if it was receiving new data points during the last 2 hours. So it can return up to 2x of actual number of active time series if these time series stay the same during the last 2 hours (i.e. if time series churn rate is close to 0). It is likely the number of active time series is closer to the lower bound of the range `[20889112 / 2 ... 20889112]` in your case.

**Comment by n4mine** [comment]
Is there a way to count exact number of series fast?

**Comment by valyala** [comment]
> Is there a way to count exact number of series fast?

The `/api/v1/series/count` scans all the time series and returns the _total_ number of time series stored in the database. This handler may be slow when the number of time series is too big.

The `/api/v1/series` returns only series with data points on the given time range specified by `start` and `end` args. By default `start` arg equals to `now-5m` while `end` arg equals to `now`. It doesn't return series outside the given time range. That's why it returns only 14.788M time series, while `/api/v1/series/count` returns 66.637M time series.

**Comment by n4mine** [comment]
got it, thanks.
