### ISSUE TITLE
vmalert does not trigger some alerts

### ISSUE THREAD

**Issue by codedumper1** [VictoriaMetrics/VictoriaMetrics#3802]
### Describe the bug

Substantial percentage of alerts are not triggered although alert expression is constantly true. For example, WebUI at /vmalert/groups shows "Alert | Details" of a rule with following cURL requests in "last updates" list:
`curl -k -X POST -H 'Content-Type: application/json' 'https://promxy.host.local:443/api/v1/query?query=sum%28cloudwatch_aws_elastic_map_reduce_core_nodes_running_average%29+by+%28job_flow_id%29+%3E%3D+bool+3&step=300s&time=1676043060'`

Above curl request run from **within vmalert container** gives value of "**1**", i.e. "true":
`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"job_flow_id":"j-1V46EF13PZA6X"},"value":[1676043060,"1"]}]}}`

Alert itself:
```
  - alert: EMRTaskCount
    expr: sum(cloudwatch_aws_elastic_map_reduce_core_nodes_running_average) by (job_flow_id) >= bool 3
    for: 0
    debug: true
    update_entries_limit: 10
    labels:
      severity: warning
    annotations:
      description: "TESTING BOOL EMR cluser: {{ $labels.job_flow_id }} task count is more than 3"
      summary: "TESTING BOOL EMR cluser: {{ $labels.job_flow_id }} task count is more than 3"
```
We have `"for:"` set to 0, tested with other intervals - no luck.
We enabled `"debug:"` for alert, log shows:

> 2023-02-10T16:55:52.276Z info VictoriaMetrics/app/vmalert/alerting.go:169 DEBUG rule "emr":"EMRTaskCount" (17759214232489726627) at 2023-02-10T16:55:52Z: query returned 0 samples (elapsed: 3.238789ms)
> 2023-02-10T16:55:52.273Z info VictoriaMetrics/app/vmalert/datasource/vm.go:162 DEBUG datasource request: executing POST request with params "query=sum%28cloudwatch_aws_elastic_map_reduce_core_nodes_running_average%29+by+%28job_flow_id%29+%3E%3D+bool+3&step=300s&time=1676043060"

Datapoints are constant at the same value:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/26918275/218161567-f1368915-8c09-4a5c-bebd-5d5b1719a347.png">

No errors or changes of alert state ever at /metrics:
```$ curl -s https://vmalert.host.local/metrics | grep EMRTaskCount
vmalert_alerting_rules_error{alertname="EMRTaskCount", group="emr", id="17759214232489726627"} 0
vmalert_alerting_rules_last_evaluation_samples{alertname="EMRTaskCount", group="emr", id="17759214232489726627"} 0
vmalert_alerts_firing{alertname="EMRTaskCount", group="emr", id="17759214232489726627"} 0
vmalert_alerts_pending{alertname="EMRTaskCount", group="emr", id="17759214232489726627"} 0
```

It seems every condition I can think of is there for alert to be triggered but it isn't happening. Bug?

### To Reproduce

Alert example provided.

### Version

`./vmalert --version`
vmalert-20230201-220357-tags-v1.87.0-0-gfe736c538

`./promxy-v0.0.75-linux-amd64 --version`
Version v0.0.75

`./victoria-metrics-prod --version`
victoria-metrics-20220902-190337-tags-v1.81.1-0-gac98ecdc1

### Used command-line flags

```
/vmalert \
--envflag.enable \
--envflag.prefix=VM_ \
--remoteWrite.showURL \
--rule=alerts.yml \
--notifier.url=https://alertmanager.host.local:443 \
--datasource.url=https://promxy.host.local:443 \
--remoteWrite.url=https://vmagent.host.local:443
```

**Comment by hagen1778** [comment]
Hello! Debug message suggests that query returned 0 samples at the moment of execution:
```
2023-02-10T16:55:52.276Z info VictoriaMetrics/app/vmalert/alerting.go:169 DEBUG rule "emr":"EMRTaskCount" (17759214232489726627) at 2023-02-10T16:55:52Z: query returned 0 samples (elapsed: 3.238789ms)
```

And you say that when you execute curl command and it returns data. So the only explanation, I think, is described here 
https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by codedumper1** [comment]
> So the only explanation, I think, is described here

could you please point to exact cause you are referring to, because link you are referring to shows number of reasons none of which applies in my case.

Also if "query returned 0 samples" refers to "no data" then why cURL link provided in details->last updates 
1. returns result;
2. returns exact value of "true" that should trigger alert?

**Comment by codedumper1** [comment]
`-datasource.lookback=5m` vmalert parameter solved the problem. Shouldn't it be non-zero by default?

**Comment by hagen1778** [comment]
There is an ongoing discussion in the public slack chat here https://victoriametrics.slack.com/archives/CGZF1H6L9/p1676043284992159

**Comment by hagen1778** [comment]
The issue was likely solved with the following recommendation from the docs:
> If [time series resolution](https://docs.victoriametrics.com/keyConcepts.html#time-series-resolution) in datasource is inconsistent or >=5min - try changing vmalert's -datasource.queryStep command-line flag to specify how far search query can lookback for the recent datapoint. The recommendation is to have the step at least two times bigger than the resolution.

See more here https://docs.victoriametrics.com/vmalert.html#troubleshooting

I'm closing the issue as inactive. Feel free to re-open if it still remains.
