### ISSUE TITLE
vmagent: all targets are removed in config  update when add kubernetes_sd_configs

### ISSUE THREAD

**Issue by lzfhust** [VictoriaMetrics/VictoriaMetrics#3808]
### Describe the bug

I use vmagent to scape metrics using kubernetes_sd_configs.
Firstlly, I started the  vmagent with two kubernetes clusters in kubernetes_sd_configs and got about 9000 targets
<img width="483" alt="企业微信截图_310b5811-9c4e-4477-9e0a-f27d1c9f7289" src="https://user-images.githubusercontent.com/9677371/218465136-ffd6a2bb-b703-4d0a-86ef-55c556177211.png">
Then, during scraping metrics, I update the promscrape.config file adding a new kubernetes cluster:
<img width="576" alt="企业微信截图_b2de5dfa-91b7-4094-9c6c-4917645b69d9" src="https://user-images.githubusercontent.com/9677371/218466046-8d9bcc59-157a-4456-b43b-0230797c4890.png">
All targets of the existing two kubernetes clusters were removed and then all the three kubernetes clusters were added.
<img width="1319" alt="企业微信截图_3d7f47ea-82aa-4259-bd7e-1d3c912ac8ce" src="https://user-images.githubusercontent.com/9677371/218467128-6fc0effa-e21e-4838-8c6b-6d312f1bdd78.png">

And the metrics are gone for about one minuter:
<img width="1100" alt="企业微信截图_40994eda-a865-45a2-9371-2d61c1636597" src="https://user-images.githubusercontent.com/9677371/218467470-edf5b71a-689e-40f8-b859-73755ec47592.png">

Since I just add a new kubernetes clusters, the targets of the existing two kubernetes clusters should stay unchanged.

### To Reproduce

Using this command:
./bin/vmagent -loggerTimezone=Local -promscrape.suppressDuplicateScrapeTargetErrors=true -promscrape.config=vmagent-scrape.yaml -promscrape.configCheckInterval=30s -remoteWrite.url=http:xxxxxxx

### Version

1.83

### Additional information

I debug this issue and find this may be caused by the promscrape.configCheckInterval is 30s and the promscrape.kubernetesSDCheckInterval is also 30s. During updating scrape workers, all the targets are removed by mustRestart function. So there should be a lock?
we are trying to pull a request to fix this issue: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3809

**Comment by f41gh7** [comment]
@zekker6  Can you take a look plx?

**Comment by zekker6** [comment]
Hi @lzfhust 
Could you verify that still happens when using [v1.87.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.1)?
I've just tested this with latest version, currently it does add new targets without removing previous ones. See the log:
```
2023-02-20T11:47:02.261Z        info    lib/promscrape/discovery/kubernetes/api_watcher.go:509     started pod watcher for "https://xxx:6443/api/v1/pods"
2023-02-20T11:47:02.872Z        info    lib/promscrape/discovery/kubernetes/api_watcher.go:641     reloaded 138 objects from "https://xxx:6443/api/v1/pods" in 0.611s; updated=0, removed=0, added=138, resourceVersion="85403828"
2023-02-20T11:47:02.872Z        info    lib/promscrape/config.go:126       started service discovery routines in 0.612 seconds
2023-02-20T11:47:02.905Z        info    lib/promscrape/scraper.go:422      kubernetes_sd_configs: added targets: 392, removed targets: 0; total targets: 392
2023-02-20T11:47:32.874Z        info    lib/promscrape/config.go:131       restarting service discovery routines...
2023-02-20T11:47:32.876Z        info    lib/promscrape/config.go:174       restarted service discovery routines in 0.002 seconds, stopped=0, started=1, restarted=0
2023-02-20T11:47:32.877Z        info    lib/promscrape/scraper.go:193      found changes in "./conf/vmagent-k8s.yml"; applying these changes
2023-02-20T11:47:32.897Z        info    /home/zekker/Code/victoria-metrics/VictoriaMetrics-4/lib/promscrape/scraper.go:422      kubernetes_sd_configs: added targets: 392, removed targets: 0; total targets: 784

```

**Comment by lzfhust** [comment]
> Hi @lzfhust Could you verify that still happens when using [v1.87.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.1)? I've just tested this with latest version, currently it does add new targets without removing previous ones. See the log:
> 
> ```
> 2023-02-20T11:47:02.261Z        info    lib/promscrape/discovery/kubernetes/api_watcher.go:509     started pod watcher for "https://xxx:6443/api/v1/pods"
> 2023-02-20T11:47:02.872Z        info    lib/promscrape/discovery/kubernetes/api_watcher.go:641     reloaded 138 objects from "https://xxx:6443/api/v1/pods" in 0.611s; updated=0, removed=0, added=138, resourceVersion="85403828"
> 2023-02-20T11:47:02.872Z        info    lib/promscrape/config.go:126       started service discovery routines in 0.612 seconds
> 2023-02-20T11:47:02.905Z        info    lib/promscrape/scraper.go:422      kubernetes_sd_configs: added targets: 392, removed targets: 0; total targets: 392
> 2023-02-20T11:47:32.874Z        info    lib/promscrape/config.go:131       restarting service discovery routines...
> 2023-02-20T11:47:32.876Z        info    lib/promscrape/config.go:174       restarted service discovery routines in 0.002 seconds, stopped=0, started=1, restarted=0
> 2023-02-20T11:47:32.877Z        info    lib/promscrape/scraper.go:193      found changes in "./conf/vmagent-k8s.yml"; applying these changes
> 2023-02-20T11:47:32.897Z        info    lib/promscrape/scraper.go:422      kubernetes_sd_configs: added targets: 392, removed targets: 0; total targets: 784
> ```

Sorry for repling late.
Using the latest "cluster" branch, this problem still happens.
<img width="1354" alt="企业微信截图_2f11690d-5321-43e4-ab07-4a8ad01bcb80" src="https://user-images.githubusercontent.com/9677371/221550182-46b186b6-7624-4a79-bfb7-46a9e5b59d63.png">
you can see, when i add a new kubernetes cluster, all the existing targets were removed and then all the targets are added.

**Comment by zekker6** [comment]
@lzfhust Could you please share config before and after update? (without any sensitive info)

**Comment by lzfhust** [comment]
> @lzfhust Could you please share config before and after update? (without any sensitive info)

the scape config is :
<img width="680" alt="企业微信截图_5031b1c5-3356-4873-8e60-46b9eb15184c" src="https://user-images.githubusercontent.com/9677371/221554095-06cd9b35-3c43-4530-ba47-f2250d12013d.png">
The diff before and after update is the red rectangle. I add a new kubernetes cluster with the red rectangle.

**Comment by lzfhust** [comment]
Hi @zekker6 
I tried adding this as the last config in terms of ordering, this still happens.
The promscrape.kubernetesSDCheckInterval is 30s and my -promscrape.configCheckInterval is also 30s.
There are two thread here. one is runScraper which check config file and cfgNew.mustRestart(). The other getScrapeWork and update.  These two thread start with the timer of 30s.
I noticed and guessed that when the runScraper called cfgNew.mustRestart, the getScrapeWork get zero scrape worker and all the existing scrape workers are removed

**Comment by zekker6** [comment]
Thanks for the details!

vmagent checks changes per job and restarts changed jobs. In your configuration there will be 1 scrape job with several k8s service discovery configs.
In order to perform reloads without re-adding all those targets you need to create a distinct job for each SD discovery config.

So it will become similar to:
```
scrape_configs:
  - job_name: kubernetes
    kubernetes_sd_configs:
      - role: pod
        kubeconfig_file: ...
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: instance
        action: replace
  - job_name: kubernetes2
    kubernetes_sd_configs:
      - role: pod
        kubeconfig_file: ...
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_ip]
        target_label: instance
        action: replace
```

**Comment by lzfhust** [comment]
> Thanks for the details!
> 
> vmagent checks changes per job and restarts changed jobs. In your configuration there will be 1 scrape job with several k8s service discovery configs. In order to perform reloads without re-adding all those targets you need to create a distinct job for each SD discovery config.
> 
> So it will become similar to:
> 
> ```
> scrape_configs:
>   - job_name: kubernetes
>     kubernetes_sd_configs:
>       - role: pod
>         kubeconfig_file: ...
>     relabel_configs:
>       - source_labels: [__meta_kubernetes_pod_ip]
>         target_label: instance
>         action: replace
>   - job_name: kubernetes2
>     kubernetes_sd_configs:
>       - role: pod
>         kubeconfig_file: ...
>     relabel_configs:
>       - source_labels: [__meta_kubernetes_pod_ip]
>         target_label: instance
>         action: replace
> ```

But online we have more than fifty kubernetes clusters. we can not create a distinct job with a kubernetes cluster. Our config will be very large and unreadable.

**Comment by zekker6** [comment]
@lzfhust I can suggest this as an immediate solution to avoid discovery delays, but we will also improve this on vmagent side.

**Comment by lzfhust** [comment]
> @lzfhust I can suggest this as an immediate solution to avoid discovery delays, but we will also improve this on vmagent side.

Ok, thanks. In our inner branch forked from github, I added a mutex here and the problem dose not happen so far. 
Look forward for your improvement.

**Comment by lzfhust** [comment]
> 2023-02-27T13:00:04.737Z        info    lib/promscrape/scraper.go:430      kubernetes_sd_configs: added targets: 2, removed targets: 0; total targets: 407

I have tested several times and the problem did not happen again. And I also applied the PR in our production environment.
Using the same config above, the new log with my PR:
<img width="1411" alt="企业微信截图_02661a89-765c-48bf-afb9-7b85c633223c" src="https://user-images.githubusercontent.com/9677371/221598480-ad8e19f3-5492-4f63-8a23-30f4491213b3.png">
<img width="1057" alt="企业微信截图_f4ed0a14-f90f-463c-ae2e-181feca73cd0" src="https://user-images.githubusercontent.com/9677371/221598916-6d12ca96-917f-4a0a-a28c-c1c96b8b69bf.png">

**Comment by hagen1778** [comment]
@zekker6 @lzfhust do we have any updates on this?

**Comment by hagen1778** [comment]
Closing due to lack fo activity
