### ISSUE TITLE
vmbackup: example of credentials file for Minio

### ISSUE THREAD

**Issue by thedje** [VictoriaMetrics/VictoriaMetrics#381]
Hello,
I want to use vmbackup with Minio.
I have the key access and the key secret.
However, I don't know how to fill them in a credential file.
Do you have any examples?

Thank you

**Comment by valyala** [comment]
@glebsam , could you provide the requested examples to @thedje as an author of 15b7406f7bf4af8433a561896a9420f92b3e548d ?

**Comment by valyala** [comment]
@glebsam , it would be great to add these examples into a dedicated section of [vmbackup docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md).

**Comment by ThomasADavis** [comment]
After lots of searching, and realizing the URL given in the command line help does not point you to a working S3 configuration file, let alone explain how to get it work with minio..

Here's how to do it.

1) create the ~/.aws directory
2) create a file called 'credentials'
3) in that file, contents are:

```[default]
aws_access_key_id=theaccesskey
aws_secret_access_key=thesecretaccesskeyvalue
```
You may also need a config file, in the ~/.aws/config, put:

```
[default]
region=us-west-2
output=json
```

Now, when you run the vmbackup_prod, if you put the credentials/config file in ~/.aws, you simply use -customS3Endpoint 'http://your.min.io:port_address", ie: http://192.168.86.50:9000, and tell it to use '-dst=s3:/bucket/directory/ else, you will need to tell vmbackup-prod where the credential/config file is.

this came from https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by f41gh7** [comment]
@ThomasADavis  thanks!

 I've also want to mention, that it's possible to use credentials from env variables:

```bash
export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

**Comment by valyala** [comment]
FYI, [vmbackup docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md#advanced-usage) now have information about this case.

**Comment by thedje** [comment]
Hi,
Thank you for your contributions

**Comment by glebsam** [comment]
Sorry for late response. Yep, current documentation reflects exactly how to use options `-credsFilePath` and `-customS3Endpoint`. I personally used to use them to backup VM database in Minio.

**Comment by valyala** [comment]
@glebsam , thanks for the update! Then closing the issue as resolved.
