### ISSUE TITLE
How to build a separate `vmselect` binary?

### ISSUE THREAD

**Issue by kidiboy** [VictoriaMetrics/VictoriaMetrics#3815]
In the root `README.md` I can find only how to build `victoria-metrics` binary. How can I build a separate `vmselect` binary? I can't find any instructions nor Makefiles nor main function of `vmselect`.

**Comment by zekker6** [comment]
@kidiboy You need to use `cluster` branch to find cluster components: https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster#production-builds

**Comment by kidiboy** [comment]
Thank you!
