### ISSUE TITLE
Unexpected query results

### ISSUE THREAD

**Issue by thislyc** [VictoriaMetrics/VictoriaMetrics#3818]
### Describe the bug

Hello, I have configured - replicationFactory=2. There are two vmstorage nodes in total, and one node needs to be migrated. I used rsync to migrate the files of a vmstorage node to a new node, but the data in the migration process was lost. Among the latest two nodes, one data is complete, and the other is missing half an hour of data. As expected, complete records should be returned, But the current situation is that the complete data is displayed at one time, and the half hour is missing from the data returned at the other time

### To Reproduce

configured - replicationFactory=2. There are two vmstorage nodes in total, and one node needs to be migrated. I used rsync to migrate the files of a vmstorage node to a new node

### Version

cluster 1.79.2

### Screenshots

![image](https://user-images.githubusercontent.com/42378143/218748387-a0d2ff60-75bb-4cf4-b384-4c91264522f6.png)
![image](https://user-images.githubusercontent.com/42378143/218748396-de2924c1-3866-42e5-b046-c79dd282c246.png)
There will be no data later, and there will be data later

### Used command-line flags

vmselect-prod \
-search.disableCache \
-search.maxConcurrentRequests 10000 \
-search.maxPointsPerTimeseries 50000 \
-search.maxUniqueTimeseries 500000 \
-search.maxSeries=500000 \
-search.maxQueryLen=10MB \
-search.maxQueryDuration 240s \
-httpListenAddr=:8481 \
-storageNode=$storageNode \
-replicationFactor=2 \
-dedup.minScrapeInterval=1s \

vminsert-prod \
-httpListenAddr=:8480 \
-storageNode=$storageNode \
-maxInsertRequestSize=536870912 \
-maxConcurrentInserts=32 \
-replicationFactor=2 \

vmstorage-prod  \
-httpListenAddr=:8482 \
-vminsertAddr=:8400 \
-vmselectAddr=:8401 \
-storageDataPath=/vmstorage-data/"${DAOKEIP}"/ \
-dedup.minScrapeInterval=1s \
-retentionPeriod=5y \
-search.maxTagKeys 100000 \
-search.maxTagValues 1000000 \
-search.maxUniqueTimeseries=10000000 \

**Comment by hagen1778** [comment]
Hello!

> Hello, I have configured - replicationFactory=2. There are two vmstorage nodes in total, and one node needs to be migrated.

That's odd. Please see recommendations to [replication and data safety](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety):
```
The cluster must contain at least 2*N-1 vmstorage nodes, where N is replication factor, in order to maintain the given replication factor for newly ingested data when N-1 of storage nodes are unavailable.
```

With replicationFactory=2 you need at least 3 vmstorage nodes for replication to make sense.


>  But the current situation is that the complete data is displayed at one time, and the half hour is missing from the data returned at the other time

Can you try removing `-replicationFactor=2` from the vmselect config and try again?

**Comment by thislyc** [comment]
> 
Thank you for your answer
After I tried to delete - replicationFactor=2 from the vmselect configuration, the query result met the expectation
But I still want to know what causes it. Can you give me some advice

**Comment by hagen1778** [comment]
> But I still want to know what causes it. Can you give me some advice

Sure! `replicationFactor` setting for vmselect is not required. It is rather an optimization that could backfire unexpectedly:
```
  -replicationFactor int
     How many copies of every time series is available on vmstorage nodes. vmselect cancels responses from the slowest -replicationFactor-1 vmstorage nodes if -replicationFactor is set by assuming it already received complete data. It isn't recommended setting this flag to values other than 1 at vmselect nodes, since it may result in incomplete responses after adding new vmstorage nodes even if the replication is enabled at vminsert nodes (default 1)
```
In your case, vmselect assumes that response from one vmstorage is totally enough to produce complete result. When in reality you have only 1 vmstorage with full data, and 2nd storage with partial data. So in 50% chances vmselect receives the data from 2nd storage, cancels request to 1st storage and returns you what it gets.

We do not recommend setting `-replicationFactor` on vmselect and docs do not contain such recommendation either.

**Comment by thislyc** [comment]
> 
I see, thank you very much.

**Comment by thislyc** [comment]
Hi, I discovered a new problem. When I removed the - replicationFactor parameter from vmselect and ran it for a period of time, I found that the data queried by two vmselect methods were different. When I restarted vmselect, the query results were the same again. Could this be caused by the - replicationFactor parameter @hagen1778

**Comment by hagen1778** [comment]
Yes, since vmselects do cache rollup responses. If they got incorrect response and cached it - it will be served until the cache is evicted or reset.

**Comment by thislyc** [comment]
> Yes, since vmselects do cache rollup responses. If they got incorrect response and cached it - it will be served until the cache is evicted or reset.

How should I configure the - replicationFactor parameter of vmselect

**Comment by thislyc** [comment]
> Yes, since vmselects do cache rollup responses. If they got incorrect response and cached it - it will be served until the cache is evicted or reset.

"I have two vmselect nodes in total. If I remove the - replicationFactor configuration for all vmselect nodes, it should not result in inconsistent summary data cached by the two vmselect nodes. Is there a situation where overwriting historical data can result in partial historical data being cached by vmselect, resulting in inconsistent caches of the two vmselect nodes within a certain period of time?"

**Comment by hagen1778** [comment]
> How should I configure the - replicationFactor parameter of vmselect

You shouldn't. "We do not recommend setting -replicationFactor on vmselect and docs do not contain such recommendation either."

>  Is there a situation where overwriting historical data can result in partial historical data being cached by vmselect

Yes, adding or modifying historical data may result in cache corruption. Since vmselect has no way to detect that data in past has changed, it can continue serving previously cached data as response. Docs recommend [invalidating caches after the backfilling](https://docs.victoriametrics.com/#backfilling).

**Comment by thislyc** [comment]
> Since vmselect has no way to detect that data in past has changed, it can continue serving previously cached data as response. Docs recommend [invalidating caches after the backfilling](https://docs.victoriametrics.com/#backfilling).

Thank you very much for your answer. I'm getting more familiar with it. I've looked at the two recommended solutions for backfill. If you can have a configuration item that controls the cache expiration time, it will be more friendly for backfill data

**Comment by jiekun** [comment]
Closing as answered.
