### ISSUE TITLE
vmctl: automatically disable progress bar if TTY is not available

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#3823]
### Is your feature request related to a problem? Please describe

When running vmctl in k8s you will need to either specify flag to disable progress, or add tty to container.
Otherwise vmctl will fail with an io error which confuses users.

### Describe the solution you'd like

vmctl could check whether TTY is available and disable progress bar when needed

**Comment by valyala** [comment]
[vmctl](https://docs.victoriametrics.com/vmctl.html) disables progress bar when TTY is unavailable starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
