### ISSUE TITLE
vmselect: cannot store series in the cache since they would occupy more than N bytes

### ISSUE THREAD

**Issue by grigorev-lm** [VictoriaMetrics/VictoriaMetrics#3828]
### Describe the bug

Hello team, I'm using VMCluster deployed in k8s, recently I noticed that our vmselect pods are not storing any cache on its pvc and I don't see any time improvements after 2 consequent requests  although vmselect deployed  with `cacheDataPath=/select-cache` flag. I tried to measure request time before cache reset with `/internal/resetRollupResultCache` and after, there is no difference in request time (`/select-cache` directory not growing in size too), both requests take 20-21 sec. Is this normal behavior for vmselect?

### To Reproduce

I measured request time with this request ` histogram_quantile( 0.99, sum by (le) ( increase_pure( {__name__="xxx_operation_duration_bucket", application_name="xxx", xxx_operation_type="in", xxx_operation_name=~".*", instance=~"xxx-.*"}[3600s] ) / 3600 ) or on() vector(0) ) or on() vector(0)` on 30 day range because it's the slowest request in my environment.

### Version

```
# /vmselect-prod --version
vmselect-20230118-202936-tags-v1.86.2-cluster-0-g069042653
```

### Used command-line flags

Vmselect pods deployed with this command-line arguments:
```
      - args:
        - -cacheDataPath=/select-cache
        - -cacheExpireDuration=43200m0s
        - -dedup.minScrapeInterval=1h
        - -httpListenAddr=:8481
        - -loggerLevel=INFO
        - -memory.allowedPercent=90
        - -prevCacheRemovalPercent=0.01
        - -search.maxQueryDuration=60s
        - -selectNode=...
        - -storageNode=...
```

### Additional information
[trace.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10791656/trace.txt)

_No response_

**Comment by zekker6** [comment]
Hi @grigorev-lm 
Could you run this query with [tracing](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#query-tracing) enabled and attach your traces here?

**Comment by grigorev-lm** [comment]
@zekker6 @hagen1778 added trace json in the issue

**Comment by zekker6** [comment]
@grigorev-lm Thanks for the details!
According to the stack trace:
```
rollup cache put: query=increase_pure(xxx_operation_duration_bucket{instance=~"xyz-.*", xxx_application_name="xxx", xxx_operation_name=~".*", xxx_operation_type="in"}[3600s]), timeRange=[2023-01-22T08:00:00Z..2023-02-21T08:00:00Z], step=7200000, window=3600000, series=773832

cannot store series in the cache, since they would occupy more than 966367641 bytes
```
That means that data was not stored because it will exceed caching limit threshold. This threshold is calculated as 1/4 of overall rollup cache. Rollup cache size is using up to 1/8 of overall available memory.
Those thresholds are used in order to avoid single or several requests to take all available cache and preempt all other cache results.

You can use the following metrics to monitor usage of caching at your vmstorage instances:
```
vm_cache_entries{type="promql/rollupResult"}
vm_cache_size_bytes{type="promql/rollupResult"}
vm_cache_size_max_bytes{type="promql/rollupResult"}
vm_cache_requests_total{type="promql/rollupResult"}
vm_cache_misses_total{type="promql/rollupResult"}
```
In your case misses metric would show that there is no data stored in cache for the given query.

**Comment by grigorev-lm** [comment]
@zekker6 Thanks! Closing the issue.

**Comment by grigorev-lm** [comment]
@zekker6 Idk if I need to open new issue, but maybe you know how to find out correctly why my query will occupy 966367641 bytes in cache? 1Gb is a lot, because I have 10Gb metrics in total on vmstorage.

**Comment by hagen1778** [comment]
Hi @grigorev-lm! 
You can find the exact math here https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8bab50dc29b2d7cd84c3aaf5db3c681907991b76/app/vmselect/promql/timeseries.go#L85-L92

> 1Gb is a lot, because I have 10Gb metrics in total on vmstorage.

In storage, data is compressed. So these values can't be compared like this. The query you mentioned fetches 773832 time series and data for each of them needs to be parsed into memory and stored to the cache. That's a lot. But that's unlikely the answer you're looking for.

I guess, what you need is a way to override the maxRollupCacheSize. The current limitation is more like a sane filter to prevent one query from evicting cache results for other queries. I assume, you have reasons to query all 773832 time series separately without aggregating them. So probably, you just need a way to bump the cache size limit.

**Comment by grigorev-lm** [comment]
@hagen1778 Thank you. Is there any way to increase cache size limit by using some command line args or the only option is to increase k8s requests for the vmselect pod?

**Comment by hagen1778** [comment]
There is no way to configure this so far. Would you mind opening a feature request for this?
I'm also curios of your usage scenario: why would someone need to request about 1Mil of time series in one request?

**Comment by zekker6** [comment]
Going to close this as original issue have been resolved, feel free to reopen if new questions will arise.
