### ISSUE TITLE
vmctl: add support of basic auth and bearer tokens for VictoriaMetrics

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3835]
### Is your feature request related to a problem? Please describe

It's not obvious how to pass credentials via vmctl

### Describe the solution you'd like

additional flags for username, password and/or bearer token

**Comment by valyala** [comment]
`vmctl` can be configured to send basic auth and bearer tokens to source and destination storage via the following command-line flags starting from [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html):

* `--vm-native-src-bearer-token` - bearer token for source storage
* `--vm-native-src-user` and `--vm-native-src-password` - basic auth for source storage
* `--vm-native-dst-bearer-token` - bearer token for destination storage
* `--vm-native-dst-user` and `--vm-native-src-password` - basic auth for destination storage


Closing the feature request as done.
