### ISSUE TITLE
Imported Data from InfluxDB to VM with vmctl - but where to find?

### ISSUE THREAD

**Issue by madface303** [VictoriaMetrics/VictoriaMetrics#3838]
I imported data from influxdb to vm, to test just one measurement. Here is the log from vmctl:

```
InfluxDB import mode
2023/02/04 12:39:40 Exploring scheme for database "homeassistant"
2023/02/04 12:39:40 fetching fields: command: "show field keys"; database: "homeassistant"; retention: "y2_5m"
2023/02/04 12:39:40 found 9 fields
2023/02/04 12:39:40 fetching series: command: "show series from people where entity_id = 'sk_hamburg_count'"; database: "homeassistant"; retention: "y2_5m"
2023/02/04 12:39:40 found 1 series
Found 1 timeseries to import. Continue? [Y/n]
2023/02/04 12:39:50 Import finished!
2023/02/04 12:39:50 VictoriaMetrics importer stats:
  idle duration: 0s;
  time spent while importing: 142.880858ms;
  total samples: 1216;
  samples/s: 8510.59;
  total bytes: 25.2 kB;
  bytes/s: 176.2 kB;
  import requests: 1;
  import requests retries: 0;
VM worker 0:↖ ? p/s
VM worker 1:↖ ? p/s
Processing series: 1 / 1 [████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 100.00%
2023/02/04 12:39:50 Total time: 9.402037448
```

Seemed to work without problems, but i can't find the imported data. When i look at this sensor in the ui it looks like this:

![image](https://user-images.githubusercontent.com/61362651/219879254-38493102-573d-436d-bc60-e88b67142844.png)

(i switched to vm around the new year). The import has the data from 2020 to 2022, but i can't see it, neither in the ui or with grafana.
I am using the home assistant addon which has vm 1.86.1 and vmctl-prod from the 1.86.1 package.
Is there anything more to do than running vmctl and importing, or how can i double check if the data is there?
Sorry for my noob questions, but with vm i am at the very beginning. What i found is, after the import there are several folders in the database path that have 2020 and 2021 in the name, so i think the data is there ...

**Comment by dmitryk-dk** [comment]
Hi @madface303 ! Can you make a request on vmui with the `Disable cache` switch enabled? 
Also, can you make [export](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-export-data-in-json-line-format). This API returns raw data from DB, and you should see imported data.

**Comment by madface303** [comment]
Thank you for pointing me in the right direction. The export looks like that:
```
{"metric":{"__name__":"sensor.sk_hamburg_count_value","db":"home_assistant","domain":"sensor","entity_id":"sk_hamburg_count","friendly_name":"SK Hamburg count","unit_of_measurement":"people"},"values":[796043,796043,796043,796730,796730,797325,797325,797822,797822,797822,797822,797822,798324,798324,798324,798324,798324,798324,798324,798324,798324,798324,798324,798754,798754,798754,799258,799258,799258,799506,799506,799506,799506,799506,799506,800173,800173,800173,800425,800425,800425,800425,800683,800683,800876,801055,801206,801328,801328,801554,801718,801718,801859,801991,802094,802094,802309,802503,802668,802668,802814,802814,802929,802972,803249,803413,803535,803626,803626,803626,803626,803806,803970,804203,804390,804589],"timestamps":[1672576648623,1672597887189,1672680977886,1672713380601,1672772484490,1672804887214,1672859126948,1672891529337,1672938320128,1672943791949,1672944929078,1672945537224,1672977940429,1673014491153,1673022235597,1673027181488,1673027449360,1673027531873,1673029305370,1673030892788,1673031821098,1673031970323,1673032158732,1673064561340,1673108421664,1673109295054,1673322551153,1673376386842,1673376797763,1673549928688,1673550168241,1673554006037,1673554219241,1673554601895,1673555048803,1673576650157,1673631580333,1673632457893,1673668164299,1673780630518,1673798407940,1673798459324,1673928071291,1673986230627,1674018633422,1674105043920,1674191451400,1674277859398,1674314743503,1674530763816,1674618684463,1674667263595,1674710467719,1674796876356,1674883285342,1675107890710,1675140294856,1675226703494,1675313111627,1675367088480,1675399491253,1675443632181,1675486836541,1675749432548,1675835840618,1675911447486,1675997855533,1676084491477,1676131292936,1676309317977,1676314249073,1676346652331,1676433060211,1676519468225,1676605879219,1676688914383]}```

These are the only data submitted by home assistant since switching. 

But i found following in the export:
```
{"metric":{"__name__":"people_value","db":"homeassistant","domain":"sensor","entity_id":"sk_hamburg_count"},"values":[50673,50673,50673,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,50919,51262,51262,51262,51262,51262 ...```

The name does not match with the actual measured and therefore it isn't displayed when showing sensor.sk_hamburg_count_value. 
Thank you very much, i see where i have to search further. 
Question, did i make a mistake in importing, is there an option so that the data name will be imported not as people_value but as sensor.sk_hamburg_count_value?
And second one, how can i delete the wrong imported data?

**Comment by dmitryk-dk** [comment]
Hi @madface303 ! If you want to delete the wrong data, you should check this part of the documentation [delete](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-delete-time-series)

The answer to your first question is it depends on your influx data struct. Influx always returns data struct as __name__ it is the first tag from influx db.
You can check some additional information bu this link [migration](https://docs.victoriametrics.com/guides/migrate-from-influx.html#migrate-from-influxdb-to-victoriametrics)

**Comment by madface303** [comment]
@dmitryk-dk Thank you very much for the explanations and the links. I think i have now understood it's logic and how to work with vm, the first steps are the most difficult in most cases.
Closing the issue since it is solved for me.
