### ISSUE TITLE
Graphite queries w/ carbonapi don't work

### ISSUE THREAD

**Issue by arslanm** [VictoriaMetrics/VictoriaMetrics#384]
**Describe the bug**

I believe this is a bug of vmselect and not of carbonapi.

Carbonapi generates the query here: https://github.com/go-graphite/carbonapi/blob/master/zipper/protocols/prometheus/prometheus_helper.go#L225 and runs against the vmselect URL specified in carbonapi.yml config file.

I can simulate this query with a similar curl execution such as below:

`curl -XPOST http://localhost:8481/select/0/prometheus/api/v1/series --data-urlencode 'match[]={__name__=~"kafka\\.[^.][^.]*"}'`

which should return the first two fields of the metrics that match this regex but vmselect doesn't return anything unless it is kafka.* (the first item when you plot a graph).

No matter what regex I tried, vmselect never returned a result. The only time it returns anything is when I curl `kafka.*` which makes me believe it is a vmselect bug, not particularly a carbonapi bug. Below are some of the queries I manually tried with curl that failed to return a result from vmselect:

`{__name__=~"kafka.[^.][^.]*"}`
`{__name__=~"kafka\\.[^.][^.]*"}`
`{__name__=~"kafka\\\\.[^.][^.]*"}`
`{__name__=~"kafka.[^.]*"}`
`{__name__=~"kafka.([^.][^.])*"}`

**To Reproduce**

Just send some plaintext graphite metrics to vminsert, then run a similar curl against vmselect.

**Expected behavior**

vmselect should return the matching metric fields.

**Version**

1.34.2 cluster version

**Comment by hagen1778** [comment]
Hi @arslanm! Could you please share expected result? What are the metric names you want to get in response?

**Comment by arslanm** [comment]
Hi @hagen1778 

I'll give the same example that VictoriaMetrics gives for Graphite input.

`echo "foo.bar.baz;tag1=value1;tag2=value2 123 $(date +%s)" | nc -w 1 localhost 2003`

This adds foo.bar.baz metric with tag1 and tag2 tags, and 123 as the value, to the vm storage. When I run curl command to simulate carbonapi, I get below results:

`curl -s -XPOST http://localhost:8481/select/0/prometheus/api/v1/series --data-urlencode 'match[]={__name__=~"foo.*"}'`

Returns:

`
{
  "status": "success",
  "data": [
    {
      "__name__": "foo.bar.baz",
      "tag1": "value1",
      "tag2": "value2"
    }
  ]
}
`

which is good. Per https://github.com/go-graphite/carbonapi/blob/master/zipper/protocols/prometheus/prometheus_helper.go#L225 I try below curl:

`curl -s -XPOST http://localhost:8481/select/0/prometheus/api/v1/series --data-urlencode 'match[]={__name__=~"foo.[^.][^.]*"}'`

Returns:

`
{
  "status": "success",
  "data": []
}
`

I'm not a regex genius but it seems to me above regex in the curl data should return `foo.bar` (see: https://regex101.com/r/IWJVXM/1), so that when you're plotting the graph in Grafana, after selecting `foo`, grafana should trigger carbonapi to run the second curl above, which should return `foo.bar` which would make it possible for you too select `bar` after `foo`, and then query data `{__name__=~"foo.bar.[^.][^.]*"}` to get the next field, and goes on with the next fields matching the query in the database.

Since vmselect doesn't return any result data back to carbonapi, it isn't possible to plot graphs on Grafana by selecting the fields in metric names separated by dots which is the plaintext graphite format. However, I can change datasource back to Prometheus, type in the whole name of the metric and have data, but instead of using Prometheus datasource I'd like to use Graphite datasource with carbonapi in order to be able to plot graphs and take advantage of Graphite functions. Our goal is to 100% move to VictoriaMetrics but since the transition will take some time, and since VM supports graphite, we'd like to provide an interface to our developers to plot graphs using their Graphite metrics while they transition to VM (Prometheus).

**Comment by valyala** [comment]
All the regexps in PromQL and MetricsQL are automatically anchored, i.e. `regex` is converted to `^regex$` before matching - see https://github.com/prometheus/prometheus/issues/1519 for historical details. So regexps must match the whole metric name. In your case you should add `.*` in the end of the regexp, so it should start working:

`{__name__=~"foo\\.[^.][^.]*.*"}`

Note also that dots outside square brackets in the regexp must be escaped with backslashes as in the example above. Otherwise they match any char.

**Comment by arslanm** [comment]
In that case that should be covered in the carbonapi code at https://github.com/go-graphite/carbonapi/blob/master/zipper/protocols/prometheus/prometheus_helper.go#L225

I'll test this today and update this thread.

**Comment by arslanm** [comment]
Hey @valyala, I appreciate your help and what you're doing with VM. Great product!

I did some testing. It looks like adding `.*` at the end of query helped -- I added this right before the return in function `convertGraphiteTargetToPromQL` at https://github.com/go-graphite/carbonapi/blob/master/zipper/protocols/prometheus/prometheus_helper.go#L225

But this time `query_range` complained about unexpected token and it returned no data, which happened at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d410c78c7e72c9e7daaf4237ae02603fd9d9d166/lib/metricsql/parser.go#L426 in function `parseSingleExprWithoutRollupSuffix`.

```
2020-03-27T22:14:22.126Z	info	lib/httpserver/httpserver.go:50	starting http server at http://:8481/
2020-03-27T22:14:22.126Z	info	lib/httpserver/httpserver.go:51	pprof handlers are exposed at http://:8481/debug/pprof/
sq is AccountID=0, ProjectID=0, MinTimestamp=2020-03-27 22:09:30 +0000 UTC, MaxTimestamp=2020-03-27 22:14:30 +0000 UTC, TagFilters=[
{Key="", Value=".*", IsNegative: false, IsRegexp: true}
]
sq is AccountID=0, ProjectID=0, MinTimestamp=2020-03-27 22:09:32 +0000 UTC, MaxTimestamp=2020-03-27 22:14:32 +0000 UTC, TagFilters=[
{Key="", Value="foo.*", IsNegative: false, IsRegexp: true}
]
query is foo\\.*
2020-03-27T22:14:32.176Z	error	app/vmselect/main.go:306	error in "/select/0/prometheus/api/v1/query_range?query=foo%5C%5C.%2A&start=1585343672&step=15s&stop=1585347272": error when executing query="foo\\\\.*" on the time range (start=1585343672000, end=1585347272000, step=15000): cannot execute query: singleExpr: unexpected token ""; want "(", "{", "-", "+"; unparsed data: ""
sq is AccountID=0, ProjectID=0, MinTimestamp=2020-03-27 22:09:33 +0000 UTC, MaxTimestamp=2020-03-27 22:14:33 +0000 UTC, TagFilters=[
{Key="", Value="foo.[^.][^.]*.*", IsNegative: false, IsRegexp: true}
]
sq is AccountID=0, ProjectID=0, MinTimestamp=2020-03-27 22:09:34 +0000 UTC, MaxTimestamp=2020-03-27 22:14:34 +0000 UTC, TagFilters=[
{Key="", Value="foo.bar.*", IsNegative: false, IsRegexp: true}
]
query is foo\\.bar\\.*
2020-03-27T22:14:34.074Z	error	app/vmselect/main.go:306	error in "/select/0/prometheus/api/v1/query_range?query=foo%5C%5C.bar%5C%5C.%2A&start=1585343674&step=15s&stop=1585347274": error when executing query="foo\\\\.bar\\\\.*" on the time range (start=1585343674000, end=1585347274000, step=15000): cannot execute query: singleExpr: unexpected token ""; want "(", "{", "-", "+"; unparsed data: ""
sq is AccountID=0, ProjectID=0, MinTimestamp=2020-03-27 22:09:34 +0000 UTC, MaxTimestamp=2020-03-27 22:14:34 +0000 UTC, TagFilters=[
{Key="", Value="foo.bar.[^.][^.]*.*", IsNegative: false, IsRegexp: true}
]
query is foo\\.bar\\.baz\\.*
2020-03-27T22:14:35.401Z	error	app/vmselect/main.go:306	error in "/select/0/prometheus/api/v1/query_range?query=foo%5C%5C.bar%5C%5C.baz%5C%5C.%2A&start=1585343675&step=15s&stop=1585347275": error when executing query="foo\\\\.bar\\\\.baz\\\\.*" on the time range (start=1585343675000, end=1585347275000, step=15000): cannot execute query: singleExpr: unexpected token ""; want "(", "{", "-", "+"; unparsed data: ""
```

My knowledge on VictoriaMetrix is limited and I wasn't able to debug any further but it seems to me the parser is not recognizing Graphite metrics (with no token or with token `;`) properly and this causes the issue.

**Comment by valyala** [comment]
It looks like carbonapi passes Graphite metric name as is to `/api/v1/query_range`, while it must be wrapped into `{__name__=~"<regexp_here>"}` construct the same way when it is passed to `/api/v1/series` above. I.e. instead of passing Graphite metric name selector `foo.*` to `query` arg, the following PromQL query must be passed: `{__name__=~"foo\\.[^.][^.]*.*"}` .

**Comment by valyala** [comment]
FYI, VictoriaMetrics implements Graphite Metrics API starting from [v1.41.0](https://github.com/prometheus/prometheus/releases) - see [these docs](https://victoriametrics.github.io/#graphite-metrics-api-usage) for details. This API may be used by [go-graphite/carbonapi](https://github.com/go-graphite/carbonapi) as faster alternative to `/api/v1/series` when using VictoriaMetrics backend.

**Comment by arslanm** [comment]
Thanks valyala, I'll give it a shot next week. Unrelated but since 1.41.0 introduces a change that is not backward compatible with prior versions (data incompatibility) shouldn't it ideally be 2.0.0?

**Comment by valyala** [comment]
> since 1.41.0 introduces a change that is not backward compatible with prior versions (data incompatibility) shouldn't it ideally be 2.0.0?

It is safe to upgrade from older releases to v1.41.0 and newer releases. It is impossible to downgrade to releases prior v1.41.0 though. The 2.0.0 version will be released only if it won't support seamless upgrade from older releases.

**Comment by tantra35** [comment]
@valyala Hm, but why for graphite support not implemented render api? Suppose we can find metrics names for now, but how can we use it with carbonapi, without possibility of return datapoints

**Comment by valyala** [comment]
@tantra35 , VictoriaMetrics will gain [Graphite render API](https://graphite.readthedocs.io/en/stable/render_api.html) support soon. It will be available in an [enterprise package at first](https://victoriametrics.com/enterprise.html).

**Comment by f41gh7** [comment]
Graphite render API was added to the [enterprise package](https://victoriametrics.com/enterprise.html)
