### ISSUE TITLE
Discrete String Values

### ISSUE THREAD

**Issue by robobeaver6** [VictoriaMetrics/VictoriaMetrics#385]
I am migrating some Telegraf collectors to victoriametrics, which were sending to InfluxDB.  Some of the data is Discrete strings like "Enabled", "Up", "Down", "Synced".  The data is appearing in VM as 0.  Is VM unable to accept Strings as data values like InfluxDB?

If not I guess I will either have to rewrite the poller to map to an integer or go back to InfluxDB

**Comment by hagen1778** [comment]
Hi @robobeaver6! 

> VM unable to accept Strings as data values like InfluxDB?

Correct, VM stores only numeric values.

> If not I guess I will either have to rewrite the poller to map to an integer or go back to InfluxDB

That would work. However, I'd recommend to convert such data into Prometheus-like format. For example:
```
<name>_is_enabled 1 // means metric is enabled
<name>_is_enabled 0 // means metric is disabled
```
You also can store text value in labels:
```
<name>{mode="enabled"} 1
```

**Comment by robobeaver6** [comment]
OK,  Thanks for the top tip.

**Comment by nulldoot2k** [comment]
> Hi @robobeaver6!
> 
> > VM unable to accept Strings as data values like InfluxDB?
> 
> Correct, VM stores only numeric values.
> 
> > If not I guess I will either have to rewrite the poller to map to an integer or go back to InfluxDB
> 
> That would work. However, I'd recommend to convert such data into Prometheus-like format. For example:
> 
> ```
> <name>_is_enabled 1 // means metric is enabled
> <name>_is_enabled 0 // means metric is disabled
> ```
> 
> You also can store text value in labels:
> 
> ```
> <name>{mode="enabled"} 1
> ```
> 
> The following link may be useful https://prometheus.io/docs/practices/naming/#labels

how can i do it ??
i will change influxdb or victoriametrics to do that

**Comment by hagen1778** [comment]
> how can i do it ??

Could you please elaborate on this?

**Comment by zekker6** [comment]
Liking a Slack thread related to the discussion above: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1718613433876169
Also  a link to a [VictoriaLogs](https://docs.victoriametrics.com/victorialogs/) playground with messages transferred by [slack2logs](https://github.com/VictoriaMetrics/slack2logs): https://play-vmlogs.victoriametrics.com/select/vmui/?#/?query=thread_id%3A+18ada74479&g0.range_input=180d&g0.end_input=2024-06-17T12%3A30%3A42&g0.relative_time=last_180_days
