### ISSUE TITLE
VM Lost 1 hour of data

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#3852]
### Describe the bug

The program is running normally, but on February 4, 0:35 to 1:35 this time period when the query is not available, and the storage component appears error log.
My program started running on January 3, and the retentionPeriod is 35 days.

### To Reproduce

No

### Version

1.85.3-cluster

### Logs

vmstorage.log

Feb  4 01:28:24 hostname vmstorage-prod: 2023-02-04T01:28:24.534+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:179#011cannot process vmselect conn IP.232:54540: cannot flush compressed buffers: cannot flush internal buffer to the underlying writer: write tcp4 IP.228:8401->IP.232:54540: write: broken pipe

Feb  4 01:28:25 hostname vmstorage-prod: 2023-02-04T01:28:25.386+0800#011error#011VictoriaMetrics/app/vmstorage/servers/vminsert.go:122#011cannot process vminsert conn from IP.231:46210: cannot send `ack` to vminsert: write tcp4 IP.228:8400->IP.231:46210: write: broken pipe
Feb  4 01:28:26 hostname vmstorage-prod: 2023-02-04T01:28:26.159+0800#011error#011VictoriaMetrics/app/vmstorage/servers/vminsert.go:122#011cannot process vminsert conn from IP.231:51320: cannot read packet with size 31457251 bytes: cannot read data in 0.000 seconds: cannot read data from the underlying reader: read tcp4 IP.228:8400->IP.231:51320: read: connection reset by peer; read only 10616824 bytes

Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.466+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56162": cannot read success response on isCompressed: cannot read message with size 2: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.466+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56156": cannot read success response on isCompressed: cannot read message with size 2: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.467+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56164": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.467+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56166": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.468+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56168": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.468+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56170": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.468+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56172": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes
Feb  8 09:50:13 hostname vmstorage-prod: 2023-02-08T09:50:13.479+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:166#011cannot perform vmselect handshake with client "IP.232:56158": cannot read success response on isCompressed: cannot read message with size 2: EOF; read only 0 bytes
Feb 21 14:31:56 hostname vmstorage-prod: 2023-02-21T14:31:56.489+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:179#011cannot process vmselect conn IP.232:42170: cannot process vmselect request: cannot execute "search_v7": cannot send MetricBlock: cannot write data with size 1357: cannot write data in 0.000 seconds: cannot flush internal buffer to the underlying writer: write tcp4 IP.228:8401->IP.232:42170: write: connection reset by peer
Feb 21 14:31:56 hostname vmstorage-prod: 2023-02-21T14:31:56.539+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:179#011cannot process vmselect conn IP.232:42232: cannot process vmselect request: cannot execute "search_v7": cannot send MetricBlock: cannot write data with size 403: cannot write data in 0.001 seconds: cannot flush internal buffer to the underlying writer: write tcp4 IP.228:8401->IP.232:42232: write: connection reset by peer
Feb 21 14:32:15 hostname vmstorage-prod: 2023-02-21T14:32:15.263+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:179#011cannot process vmselect conn IP.232:42260: cannot process vmselect request: cannot execute "search_v7": cannot send MetricBlock: cannot write data with size 2459: cannot write data in 0.001 seconds: cannot flush internal buffer to the underlying writer: write tcp4 IP.228:8401->IP.232:42260: write: broken pipe
Feb 21 14:32:15 hostname vmstorage-prod: 2023-02-21T14:32:15.329+0800#011error#011VictoriaMetrics/lib/vmselectapi/server.go:179#011cannot process vmselect conn IP.232:42288: cannot process vmselect request: cannot execute "search_v7": cannot send MetricBlock: cannot write data with size 284: cannot write data in 0.001 seconds: cannot flush internal buffer to the underlying writer: write tcp4 IP.228:8401->IP.232:42288: write: connection reset by peer

vminsert.log

Feb  4 00:40:37 query vminsert-prod: 2023-02-03T16:40:37.883Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:306#011cannot send 2031394 bytes with 8430 rows to -storageNode="IP.228:8400": cannot read `ack` from vmstorage: cannot read data in 60.001 seconds: read tcp4 IP.231:46210->IP.228:8400: i/o timeout; closing the connection to storageNode and re-routing this data to healthy storage nodes
Feb  4 00:40:37 query vminsert-prod: 2023-02-03T16:40:37.885Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:219#011cannot make a copy #3 out of 3 copies according to -replicationFactor=3 for 2024479 bytes with 8399 rows, since a part of storage nodes is temporarily unavailable
Feb  4 00:40:37 query vminsert-prod: 2023-02-03T16:40:37.899Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:219#011cannot make a copy #3 out of 3 copies according to -replicationFactor=3 for 2089047 bytes with 8671 rows, since a part of storage nodes is temporarily unavailable
Feb  4 00:40:37 query vminsert-prod: 2023-02-03T16:40:37.906Z#011info#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:268#011successfully dialed -storageNode="IP.228:8400"
Feb  4 00:42:22 query vminsert-prod: 2023-02-03T16:42:22.102Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:306#011cannot send 31457251 bytes with 127014 rows to -storageNode="IP.228:8400": cannot write data with size 31457251: cannot write data in 104.000 seconds: cannot flush internal buffer to the underlying writer: write tcp4 IP.231:51318->IP.228:8400: i/o timeout; closing the connection to storageNode and re-routing this data to healthy storage nodes
Feb  4 00:42:22 query vminsert-prod: 2023-02-03T16:42:22.103Z#011warn#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:219#011cannot make a copy #3 out of 3 copies according to -replicationFactor=3 for 31457166 bytes with 126908 rows, since a part of storage nodes is temporarily unavailable
Feb  4 00:42:22 query vminsert-prod: 2023-02-03T16:42:22.105Z#011info#011VictoriaMetrics/app/vminsert/netstorage/netstorage.go:268#011successfully dialed -storageNode="IP.228:8400"
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.126Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48640"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.127Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48642"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.127Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48644"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.127Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48638"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.127Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48636"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.130Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48650"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.130Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48648"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.131Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48654"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.131Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48646"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.131Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.166:48652"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity
Feb  4 00:42:42 query vminsert-prod: 2023-02-03T16:42:42.464Z#011warn#011VictoriaMetrics/app/vminsert/main.go:220#011remoteAddr: "IP.164:50450"; requestURI: /insert/0/prometheus/api/v1/write; cannot handle more than 32 concurrent inserts during 1m0s; possible solutions: increase `-insert.maxQueueDuration`, increase `-maxConcurrentInserts`, increase server capacity

**Comment by dmitryk-dk** [comment]
Hi @FengZh61 ! As you can see in your logs, vmstorage can't send data to the vmselect because of the network issue. On the other side, vminsert can't write data because one of the storage was unavailable. It tries to write via rerouting but can't. 
Why can't it? Hard to say. Maybe your vmstorage had OOM and tried to restart. Can you share some grafana graphs?

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! As you can see in your logs, vmstorage can't send data to the vmselect because of the network issue. On the other side, vminsert can't write data because one of the storage was unavailable. It tries to write via rerouting but can't. Why can't it? Hard to say. Maybe your vmstorage had OOM and tried to restart. Can you share some grafana graphs?

I deployed the service in the same network segment, and I didn't find any network failure alarms during the period.
And replicationFactor=3

![捕获](https://user-images.githubusercontent.com/98309003/220556304-457ca195-a614-4333-91ce-dca736626abb.PNG)

![捕获1](https://user-images.githubusercontent.com/98309003/220556340-37ffc895-352c-4d69-8e77-6db85edc6240.PNG)

![捕获2](https://user-images.githubusercontent.com/98309003/220556366-3bbf7c48-bd2d-4bb5-b025-dae81e786ebf.PNG)

![捕获3](https://user-images.githubusercontent.com/98309003/220556376-9ea45568-40e5-4f05-8af4-17412bee53e6.PNG)

![捕获4](https://user-images.githubusercontent.com/98309003/220556411-93b7d8d0-a5a3-4b14-b834-e2e61f6a9729.PNG)

![捕获5](https://user-images.githubusercontent.com/98309003/220556431-2e0f7c1d-9763-48b3-a152-872e2dac1c80.PNG)

![捕获6](https://user-images.githubusercontent.com/98309003/220556442-99169ca6-b95d-42a3-98cd-378f14560826.PNG)

![捕获7](https://user-images.githubusercontent.com/98309003/220556452-5b48a3fa-0d80-4905-84ba-fc86837a8ad6.PNG)

![捕获8](https://user-images.githubusercontent.com/98309003/220556465-2a187b9b-ecd4-4744-ba67-8a4a42e1c20b.PNG)

![捕获9](https://user-images.githubusercontent.com/98309003/220556480-6a14d371-528a-4ac3-92b3-867dc91bbaf4.PNG)

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! As you can see in your logs, vmstorage can't send data to the vmselect because of the network issue. On the other side, vminsert can't write data because one of the storage was unavailable. It tries to write via rerouting but can't. Why can't it? Hard to say. Maybe your vmstorage had OOM and tried to restart. Can you share some grafana graphs?

Hi @dmitryk-dk 
I checked the logs and found kernel alerts, my data files are stored in nfs servers, such as netapp, but the data is 3 copies, 2 of them have nfs service exception problems, 1 is a normal node also lost data, what is the mechanism of insert?

I tried looking in the nfs service to see if there was a problem.

**Comment by dmitryk-dk** [comment]
If you asking about how storage save data so the mechanism is like this:

VictoriaMetrics creates files on disk at <-storageDataPath>/data/ folder in the following way:

It buffers incoming data in memory and saves the buffered data to a temporary directory under <-storageDataPath>/data/small/YYYY_MM/tmp directory. The temporary directory is named part.
It calls [fsync](https://man7.org/linux/man-pages/man2/fdatasync.2.html) on all the files inside the created part directory under <-storageDataPath>/data/small/YYYY_MM/tmp in order to make sure that the operating system saves the data to disk, and then calls fsync on the part directory itself in order to make sure that the operating system saves the part directory contents (aka directory structure) to disk.
It atomically moves the created part directory from the <-storageDataPath>/data/small/YYYY_MM/tmp folder into <-storageDataPath>/data/small/YYYY_MM/ with the [rename](https://man7.org/linux/man-pages/man2/rename.2.html) syscall.
It calls fsync on the directory <-storageDataPath>/data/small/YYYY_MM/ where the part was moved to in order to guarantee that the operating system stores to disk the updated directory structure for <-storageDataPath>/data/small/YYYY_MM/
VictoriaMetrics periodically merges already existing parts into bigger ones in background. This is needed in order to minimize the number of parts on disk, to improve compression rate for the data stored on disk (bigger parts usually have better compression rate) and to improve query performance (smaller number of parts are inspected faster during queries). The background merge process is performed in the temporary directory - <-storageDataPath>/data/small/YYYY_MM/tmp, and then the contents of this directory is atomically moved to <-storageDataPath>/data/small/YYYY_MM/ in the way described above. See [these docs](https://docs.victoriametrics.com/#storage) for details on how VictoriaMetrics storage work.

These algorithms guarantee that the contents of <-storageDataPath>/data/ directory is always in a consistent state even if VictoriaMetrics is terminated uncleanly (e.g. via hardware reset, kill -9, out of memory error, etc.).

**Comment by FengZh61** [comment]
> If you asking about how storage save data so the mechanism is like this:
> 
> VictoriaMetrics creates files on disk at <-storageDataPath>/data/ folder in the following way:
> 
> It buffers incoming data in memory and saves the buffered data to a temporary directory under <-storageDataPath>/data/small/YYYY_MM/tmp directory. The temporary directory is named part. It calls [fsync](https://man7.org/linux/man-pages/man2/fdatasync.2.html) on all the files inside the created part directory under <-storageDataPath>/data/small/YYYY_MM/tmp in order to make sure that the operating system saves the data to disk, and then calls fsync on the part directory itself in order to make sure that the operating system saves the part directory contents (aka directory structure) to disk. It atomically moves the created part directory from the <-storageDataPath>/data/small/YYYY_MM/tmp folder into <-storageDataPath>/data/small/YYYY_MM/ with the [rename](https://man7.org/linux/man-pages/man2/rename.2.html) syscall. It calls fsync on the directory <-storageDataPath>/data/small/YYYY_MM/ where the part was moved to in order to guarantee that the operating system stores to disk the updated directory structure for <-storageDataPath>/data/small/YYYY_MM/ VictoriaMetrics periodically merges already existing parts into bigger ones in background. This is needed in order to minimize the number of parts on disk, to improve compression rate for the data stored on disk (bigger parts usually have better compression rate) and to improve query performance (smaller number of parts are inspected faster during queries). The background merge process is performed in the temporary directory - <-storageDataPath>/data/small/YYYY_MM/tmp, and then the contents of this directory is atomically moved to <-storageDataPath>/data/small/YYYY_MM/ in the way described above. See [these docs](https://docs.victoriametrics.com/#storage) for details on how VictoriaMetrics storage work.
> 
> These algorithms guarantee that the contents of <-storageDataPath>/data/ directory is always in a consistent state even if VictoriaMetrics is terminated uncleanly (e.g. via hardware reset, kill -9, out of memory error, etc.).

Thanks for the answer, I'll keep an eye on my nfs service, vm is great! I close the issue!
