### ISSUE TITLE
Web Application Potentially Vulnerable to Clickjacking (vmagent)

### ISSUE THREAD

**Issue by AlinS23** [VictoriaMetrics/VictoriaMetrics#3855]
### Describe the bug

Hi Team,

We've got Nessuss vulnerability scan and it highlighted the following finding:

> **Web Application Potentially Vulnerable to Clickjacking** 
>The remote web server does not set an X-Frame-Options response header or a Content-Security-Policy 'frame-ancestors' response header in all content responses. This could potentially expose the site to a clickjacking or UI redress attack, in which an attacker can trick a user into clicking an area of the vulnerable page that is different from what the user perceives the page to be. This can result in a user performing fraudulent or malicious transactions.
> X-Frame-Options has been proposed by Microsoft as a way to mitigate clickjacking attacks and is currently supported by all major browser vendors.
> Content-Security-Policy (CSP) has been proposed by the W3C Web Application Security Working Group, with increasing support among all major browser vendors, as a way to mitigate clickjacking and other attacks. The 'frame-ancestors' policy directive restricts which sources can embed the protected resource. 
> 
> Return the X-Frame-Options or Content-Security-Policy (with the 'frame-ancestors' directive) HTTP header with the page's response. 

It was found on the following web-interface (IP address just for sample):

```
Output: 
The following pages do not use a clickjacking mitigation response header and contain a clickable event :
http://192.168.1.17:8429:8429/service-discovery
```

More explanation of Clickjacking is here - [link](https://www.synopsys.com/glossary/what-is-clickjacking.html#:~:text=Clickjacking%20is%20an%20attack%20that,describes%20what%20is%20going%20on).

Could you please help how we could fix it or fix in the the futire releases? Thank you.

### To Reproduce

Run a vulnerability scan to the servers with VM installed.

### Version

We are using victoria-metrics/vmagent/:1.87.1

**Comment by zekker6** [comment]
@AlinS23 In case you need to implement security hardening it is better to expose components endpoints behind a reverse-proxy which will add security-related headers.
Check out [this](https://webdock.io/en/docs/how-guides/security-guides/how-to-configure-security-headers-in-nginx-and-apache) guide for example, it provides a list of the most important security-related headers configuration examples for Apache and Nginx.

**Comment by denisgolius** [comment]
I can recommend to try https://doc.traefik.io/traefik/ as Load Balancer and revers proxy.

**Comment by mamoep** [comment]
I got a similar finding in a security audit. I would appreciate if the response headers could be added to VictoriaMetrics. It is not much code and won't do no harm. Using a reverse proxy adds unnecessary complexity of the setup.

**Comment by zekker6** [comment]
Hello @mamoep
Starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html#v1950) it is possible to configure security-related headers at VictoriaMetrics components:
> FEATURE: support Strict-Transport-Security, Content-Security-Policy and X-Frame-Options HTTP response headers in the all VictoriaMetrics components. The values for headers can be specified via the following command-line flags: -http.header.hsts, -http.header.csp and -http.header.frameOptions.

**Comment by zekker6** [comment]
Closing this issue since as completed since it is possible to configure security headers for VictoriaMetrics components starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html#v1950).

**Comment by mamoep** [comment]
The right feature at the right time. Thank you for the quick response!

For future reference, the following header configuration works with 1.96.0 without breaking the UI:
```
--http.header.csp="default-src 'self'; frame-ancestors 'self'; form-action 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
--http.header.frameOptions=SAMEORIGIN
--http.header.hsts='max-age=86400; includeSubDomains'
```
