### ISSUE TITLE
Question about not using prometheus

### ISSUE THREAD

**Issue by jsloan117** [VictoriaMetrics/VictoriaMetrics#386]
Hello,

Sorry if this isn't the correct course for a question, as I didn't see anywhere to ask one. Does using VM mean I could simply not use Prometheus then? Completely cut it out of my setup? I did find [this](https://victoriametrics.github.io/#how-to-scrape-prometheus-exporters-such-as-node-exporter) which I believe is the answer but wanted to confirm. I'm testing InfluxDB vs Prometheus vs VM, and after reading how Prometheus's rate and related functions handle data I don't want to use it.

My setup is not complex, it's a personal media server that I run multiple containers from and which to monitor my OS/Docker environment and related metrics. At the moment I have 4-5 jobs in the Prometheus.conf file and its writing to VM via the remote_write_api.

**Comment by hagen1778** [comment]
Hello @jsloan117 
VictoriaMetircs supports both push and pull models for ingestion. Pull model acts just as it Prometheus does - VictoriaMetrics will scrape targets and store metrics. You can also push/write timeseries into VictoriaMetrics if you need to. Both models are optimized and efficient.

You can remove Prometheus from your setup and configure VictoriaMetrics to scrape the jobs, so you will have less moving parts in the system. The downside for now is that VictroiaMetrics doesn't support alerting, but we're working on it. However, alerting may be achieved by using some 3d party systems like Grafana or Promxy. 
Let me know if you have more questions. Please also join the [slack](http://slack.victoriametrics.com/) community where you can find answers faster)

**Comment by jsloan117** [comment]
Perfect and thanks for the additional info and slack link!
