### ISSUE TITLE
vmstorage high disk io when big merge complete

### ISSUE THREAD

**Issue by 647-coder** [VictoriaMetrics/VictoriaMetrics#3862]
### Describe the bug

vmstorage high disk io when big merge complete.

### To Reproduce

big merge complete.

### Version

vmstorage-20220908-111519-tags-v1.81.2-cluster-0-ge9a0b803a

### Logs

Feb 23 11:18:24 vmstorage-prod[26270]: 2023-02-23T03:18:24.833Z        info        VictoriaMetrics/lib/storage/partition.go:1294        merged 662547578293 rows across 189091419 blocks in 37742.614 seconds at 17554363 rows/sec to "/data/big/2023_02/662547578293_106946454_20230201000000.000_20230222163947.064_173F8A417A20EBED"; sizeBytes: 402093515901
Feb 23 11:18:39 vmstorage-prod[26270]: 2023-02-23T03:18:39.586Z        error        VictoriaMetrics/lib/vmselectapi/server.go:177        cannot process vmselect conn :48898: cannot process vmselect request: cannot execute "search_v7": cannot send MetricBlock: cannot write data with size 7869: cannot write data in 0.001 seconds: cannot flush internal buffer tothe underlying writer: write tcp4 :8401->:48898: write: broken pipe
.... write: broken pipe

### Screenshots

<img width="1603" alt="image" src="https://user-images.githubusercontent.com/15723603/220825080-557edbbf-45eb-4aeb-bdf2-2ce748b72f37.png">
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/15723603/220824011-a8dbdfd5-f8ed-449b-a9cb-1146979fdf08.png">
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/15723603/220824121-1617c39e-3711-454e-aa78-b9261368bade.png">

### Used command-line flags

default

**Comment by zekker6** [comment]
@647-coder This is expected behavior as in the end of merge VM does a system [fsync](https://man7.org/linux/man-pages/man2/fsync.2.html) call in order to force OS to do an actual write to persistent storage.

This is required in order to be sure that data was committed to disk and in case of unexpected shutdown(crash, OOM, power loss or any other) data will be available on disk.

According to the graphs it seems like ingestion rate drops after the end of merge, this means that there was not enough disk IO available during `fsync` call for further timeseries ingestion.

**Comment by valyala** [comment]
Small correction to what @zekker6 said: VictoriaMetrics performs `fsync` per [every 16MiB](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/dfe3939665ef6ec7a94e36683ea272400c726db3/lib/filestream/filestream.go#L16) of data written to the big destination part during [background merge](https://docs.victoriametrics.com/#storage). It also [advises the operating system to do not pollute the operating system page cache with the data written to big part](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/dfe3939665ef6ec7a94e36683ea272400c726db3/lib/filestream/filestream_linux.go#L22). This allows keeping recently queried data in the [OS page cache](https://en.wikipedia.org/wiki/Page_cache) during the big merge, thus reducing disk read IO.

When the big merge is finished, then the source parts used for the merge are deleted and instantly substituted by the created big part. The data in the big part isn't cached in the OS page cache yet. So the OS needs to read the data on the first access. It looks like in your case the queries touch big amounts of data stored in the big part. This leads to the spike in disk read IO just after the big merge until the requested data is cached in the OS page cache. I suspect there are some SLO/SLI-type alerting queries exist, which frequently query big amounts of historical data in your case. For example, something like `avg_over_time(up[30d]) < 0.99` - this query reads 30 days worth of data each time it is executed.

**Comment by 647-coder** [comment]
@zekker6 @valyala thank you for your replies! i will check it.
