### ISSUE TITLE
Vmselect uses multiple times the memory in the v1.88.1

### ISSUE THREAD

**Issue by Jani19966** [VictoriaMetrics/VictoriaMetrics#3863]
### Describe the bug

After an upgrade from `v1.85.3` to `v1.87.1` vmselect started to using ~3 times the memory it previously. The network i/o although decreased almost the same amount. There was no change in the workloads themselves, only upgrade. This seems to be a tradeoff of memory(and CPU but this one's not that significantly)-network between vmstorage and vmselect.

### To Reproduce

Upgrade from older version to a newer one (`v1.85.3` to `v1.87.1`).

### Version

v1.87.1

### Screenshots

CPU and memory usage after upgrade:
![image](https://user-images.githubusercontent.com/34961213/220865658-8d5e7f66-6cda-4523-9709-b9094a0e7662.png)

Network usage after upgrade:
![image](https://user-images.githubusercontent.com/34961213/220865703-e181a518-d4fa-421b-8215-4c392b457a60.png)
![image](https://user-images.githubusercontent.com/34961213/220878748-cf5c9940-30cb-442d-8f00-8ee8c37e6b7b.png)

**Comment by zekker6** [comment]
@Jani19966 Thanks for filling detailed bugreport!

Could you share [memory profile](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#profiling) from vmselect nodes with high memory consumption?

**Comment by Jani19966** [comment]
@zekker6 sure, here it is:  [mem.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/10813259/mem.zip)

**Comment by zekker6** [comment]
@Jani19966 Thanks!

It seems like you're seeing same issue as #3692.
An issue there is that in case there are metrics with long label values vmselect will do "interning" which is basically caching those values in RAM. In case label values are large vmselect will use significant amount of memory.

In the [v1.87.0](https://docs.victoriametrics.com/CHANGELOG.html#v1870) release a flag was added to mitigate this issue:
>FEATURE: add -internStringMaxLen command-line flag, which can be used for fine-tuning RAM vs CPU usage in certain workloads. For example, if the stored time series contain long labels, then it may be useful reducing the -internStringMaxLen in order to reduce memory usage at the cost of increased CPU usage. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3692).

>  -internStringMaxLen int
        The maximum length for strings to intern. Lower limit may save memory at the cost of higher CPU usage. See https://en.wikipedia.org/wiki/String_interning (default 500)

Default value for this flag is 500, could you try setting something like `-internStringMaxLen=200` and check if that helps?

**Comment by valyala** [comment]
FYI, `vmselect` supports the ability to completely disable the [interned string](https://en.wikipedia.org/wiki/String_interning) cache via `-internStringDisableCache` command-line flag starting from [v1.88.1](https://docs.victoriametrics.com/CHANGELOG.html). @Jani19966 , it would be great to check the memory usage of `vmselect v1.88.1` with the disabled cache additionally to checking `vmselect` memory usage with smaller `-internStringMaxLen` values as @zekker6 proposed above. I'd check also 100, 50 and 30 additionally to 200 for this flag on your workload. This will help determining optimal default value, since it looks like the current default value - 500 - is too big, and causes increased memory usage at `vmselect`.

**Comment by Jani19966** [comment]
The `-internStringMaxLen` arg saved the day, tested it, waited some time and memory consumption decreased to the previous numbers, thanks @zekker6

**Comment by valyala** [comment]
Merging this issue into https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3692
