### ISSUE TITLE
Add High Avialability doc seciton for vmalert

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#3865]
### Is your feature request related to a problem? Please describe

Please add something similar to https://docs.victoriametrics.com/vmagent.html#high-availability into vmalert

### Describe the solution you'd like

some documentation that describe HA setup for vmalert

**Comment by hagen1778** [comment]
Please see https://docs.victoriametrics.com/vmalert.html#ha-vmalert
