### ISSUE TITLE
Performance advantages in using tenants?

### ISSUE THREAD

**Issue by julien-sobczak** [VictoriaMetrics/VictoriaMetrics#388]
Hi, I'm asking if there are additional benefits in using tenants (in addition to namespace isolation)? 

For example, I need to collect similar metrics for a large number of users (1k+):

```
node_cpu_seconds_total{cpu="0",mode="nice",hostname="host01"} 0
```

What will be the impact when reading metrics between those two options:

```
http://<vminsert>:8480/insert/0/<suffix>           # Using the a static value for the tenant
http://<vminsert>:8480/insert/<accountID>/<suffix> # Using the user account for the tenant
```

Based on this function, 

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8fa80a2dbc56e425fb6cdc62ac5d3926ba12b7b8/app/vminsert/netstorage/insert_ctx.go#L169-L188

It seems to me that metrics for the same tenant are spreaded among all vmstorage instances in both cases. Do you confirm? I would have expected, for a given timeseries and a single tenant, all samples to be sent to the same vmstorage (to limit the number of files to check when reading the metrics).

**Comment by valyala** [comment]
> I'm asking if there are additional benefits in using tenants (in addition to namespace isolation)?

There are no additional benefits in using tenants other than namespace isolation.

> It seems to me that metrics for the same tenant are spreaded among all vmstorage instances in both cases. Do you confirm?

Correct.

>  I would have expected, for a given timeseries and a single tenant, all samples to be sent to the same vmstorage (to limit the number of files to check when reading the metrics)

Such a strategy could result in uneven load on vmstorage nodes if a certain tenant has many more time series comparing to other tenants. So all the time series for all the tenants are evenly spread among available vmstorage nodes.

**Comment by julien-sobczak** [comment]
Yes, I understand. Thank you for the explanations.
