### ISSUE TITLE
label value api return the result that out of the -retentionPeriod

### ISSUE THREAD

**Issue by wu0407** [VictoriaMetrics/VictoriaMetrics#3880]
### Describe the bug

I use prometheus `api/v1/label/{lable name}/values` to query list of "pod" label on specifica  metrics.  
The end time is now, and start is before 30d. The vmstorage set arg `-retentionPeriod=14d`
```
 curl 'http://xxx.com/select/0/prometheus/api/v1/label/pod/values?start=1674900853&end=1677492853' --data-urlencode 'match[]=kube_pod_info{namespace="saas-jcpt-java-online"}' -g
```
expect:  not retrun out of 14d labels value that pod is deleted 14d ago
result:  retrun out of 14d labels value

### To Reproduce

1. query deleted pod lable that before 14d

### Version

# ./vmstorage-prod --version
vmstorage-20220714-140255-tags-v1.79.0-cluster-0-ga87f143e9

### Used command-line flags

vmstorage:
```
containers:
  - args:
    - -dedup.minScrapeInterval=30s
    - -httpListenAddr=:8482
    - -retentionPeriod=14d
    - -search.maxUniqueTimeseries=4000000
    - -storageDataPath=/vm-data
    - -vminsertAddr=:8400
    - -vmselectAddr=:8401
```
vmselect:
```
 containers:
  - args:
    - -cacheDataPath=/select-cache
    - -dedup.minScrapeInterval=30s
    - -http.idleConnTimeout=91s
    - -httpListenAddr=:8481
    - -search.maxQueryDuration=180s
    - -search.maxSeries=300000
    - -search.maxUniqueTimeseries=1000000
    - -selectNode=vmselect-victoria-metrics-k8s-stack-0.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-1.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-2.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-3.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-4.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-5.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-6.vmselect-victoria-metrics-k8s-stack.victoria:8481,vmselect-victoria-metrics-k8s-stack-7.vmselect-victoria-metrics-k8s-stack.victoria:8481
    - -storageNode=vmstorage-victoria-metrics-k8s-stack-0.vmstorage-victoria-metrics-k8s-stack.victoria:8401,vmstorage-victoria-metrics-k8s-stack-1.vmstorage-victoria-metrics-k8s-stack.victoria:8401,vmstorage-victoria-metrics-k8s-stack-2.vmstorage-victoria-metrics-k8s-stack.victoria:8401,vmstorage-victoria-metrics-k8s-stack-3.vmstorage-victoria-metrics-k8s-stack.victoria:8401,vmstorage-victoria-metrics-k8s-stack-4.vmstorage-victoria-metrics-k8s-stack.victoria:8401
```

**Comment by hagen1778** [comment]
Hello @wu0407! 
This is expected behavior:

> Data is split in per-month partitions inside <-storageDataPath>/data/{small,big} folders. Data partitions outside the configured retention are deleted on the first day of the new month. Each partition consists of one or more data parts with the following name pattern rowsCount_blocksCount_minTimestamp_maxTimestamp. Data parts outside of the configured retention are eventually deleted during background merge.
> Please note, the time range covered by data part is not limited by retention period unit. Hence, data part may contain data for multiple days and will be deleted only when fully outside of the configured retention.

from https://docs.victoriametrics.com/#retention

**Comment by wu0407** [comment]
Thanks  for your explanation
