### ISSUE TITLE
Victoria Metrics: Seeing multiple data points when only one is written

### ISSUE THREAD

**Issue by SaiUmeshKumar** [VictoriaMetrics/VictoriaMetrics#3885]
### Describe the bug

I have a victoria metrics cluster and writing metrics using `insert/0/influx/write` endpoint.  I have only written once but when i query from grafana, i am seeing data points with the same value for 5 mins. Is this expected ? If so, is there any reference docs as to why it is like this ? Is the 5m duplication interval configurable (checked the docs but couldn't find anything for this) ?

 
<img width="1383" alt="Screenshot 2023-03-01 at 10 55 22 AM" src="https://user-images.githubusercontent.com/47415432/222052655-bab80ee5-7210-437b-86a8-f22eee91f32c.png">

I wrote at around 10.08 but graph continued till 10.14. After sometime, i wrote the same value (10) and updated to 30 after sometime. It again showed as 30 for 5 mins.

### To Reproduce

`curl -d 'test,cluster=cluster1,job=job1 stats=10' -X POST <HOST>/insert/0/influx/write`

### Version

v1.83.1-cluster

**Comment by hagen1778** [comment]
Hello @SaiUmeshKumar!
Please take a look at https://docs.victoriametrics.com/guides/migrate-from-influx.html#basic-concepts
> Visualizations from both databases are a bit different - VictoriaMetrics shows some extra points filling the gaps in the graph. This behavior is described in more detail [here](https://docs.victoriametrics.com/keyConcepts.html#range-query). In InfluxDB, we can achieve a similar behavior by adding fill(previous) to the query.

**Comment by SaiUmeshKumar** [comment]
@hagen1778 This answers what i was looking for. Thank you !!
