### ISSUE TITLE
Aggregate metrics with anomalous data(Much higher than average)

### ISSUE THREAD

**Issue by crossoverJie** [VictoriaMetrics/VictoriaMetrics#3887]
### Describe the bug

We aggregated the `istio_request_duration_milliseconds_bucket` metric for the purpose of calculating the request elapsed time for p99.

Occasionally, however, abnormal data appears, such as elapsed time reaching one hour.

When not using aggregated data but raw data statistics, everything is fine.

### To Reproduce

```yaml
    - interval: 30s
      name: istio.service.source.url.istio_request_duration_milliseconds_bucket
      rules:
        - expr: "sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"source\"}[1m]))\nby
         (\n  source_app,\n  source_workload_namespace,\n  destination_app,\n  le,\n
         \ url\n)      \n"
          record: istio_request_duration_milliseconds_bucket:url:rate1m


        - expr: |
            histogram_quantile(0.90,
              sum(istio_request_duration_milliseconds_bucket:url:rate1m)
              by (
                source_app,
                source_workload_namespace,
                destination_app,
                le,
                url
              )
            ) >= 0
          record: istio_request_duration_milliseconds_bucket:source:url:p90:rate1m
```

Grafana's query statement:

```sql
avg(istio_request_duration_milliseconds_bucket:source:url:p99:rate1m{destination_app="$app", 
source_workload_namespace="$ns"}) by (url) / 1000
```

### Version

v1.82.0

### Logs

No error log

### Screenshots

<img width="480" alt="image" src="https://user-images.githubusercontent.com/15684156/222196308-66fd01f5-d2fd-4b1d-9efe-02b42000315e.png">

When I query aggregated data directly:
```sql
istio_request_duration_milliseconds_bucket:source:url:p99:rate1m{source_workload_namespace="$ns",
 destination_app="$app", url="/com.xxx"}
```
<img width="461" alt="image" src="https://user-images.githubusercontent.com/15684156/222196615-6d3722ac-20a0-43b5-a602-2a31a72573e2.png">

------
But when I use the raw data query, everything works fine.
```sql
avg(histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{source_workload_namespace="prod", reporter="source", destination_app="ypsx-marketing", url="/com.ypshengxian.marketing.proto.service.activity.manage.ActivityManageService/batchQueryActivityPriceBySkuId"}[1m]))  by (source_app,
                source_workload_namespace,
                destination_app,
                le,
                url)) >=0)
```
<img width="2082" alt="image" src="https://user-images.githubusercontent.com/15684156/222198042-efc982dd-a39e-4d89-908f-f08409f973c6.png">

**Comment by dmitryk-dk** [comment]
Hi @crossoverJie ! On this version of VM was a bug found. This bug was related to unexpected query results. can you upgrade your version to LTS or to v1.82.1
https://docs.victoriametrics.com/CHANGELOG.html#v1820

**Comment by dmitryk-dk** [comment]
Close as inactive
