### ISSUE TITLE
vmui: do not send `step` param for instant queries

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3896]
### Is your feature request related to a problem? Please describe

`step` param isn't required for [instant queries](https://docs.victoriametrics.com/keyConcepts.html#instant-query) but still can affect the output. For example, `step` param may interfere with `search.maxLookBack` param set on vmselect.

### Describe the solution you'd like

It would be nice not to send `step` param for instant queries.

**Comment by valyala** [comment]
`vmui` doesn't send `step` query arg in requests to [/api/v1/query](https://docs.victoriametrics.com/keyConcepts.html#instant-query) starting from [v1.89.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.

**Comment by hagen1778** [comment]
Looks like this change negatively affected instant queries with subqueries. It is allowed in subqueries to skip the step of inner rollup queries like here `max_over_time(rate(process_cpu_seconds_system_total[5m])[30m:])`. It is expected that the step for inner query will be used from `step`. But since vmui doesn't send `step` for instant queries this behavior doesn't work as expected:
<img width="1331" alt="Screenshot 2024-01-17 at 22 06 11" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/320ac502-5e9e-4a8a-aa51-cc443b0a9cb2">

**Comment by valyala** [comment]
FYI, `vmui` sends `step` query arg when performing instant queries starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).
