### ISSUE TITLE
Retention filter cant parse multiple labels

### ISSUE THREAD

**Issue by paragor** [VictoriaMetrics/VictoriaMetrics#3915]
### Describe the bug

retention filter cant parse multiple labels.

with flag
```
-retentionFilter={job_name!="pushgateway",purpose="cp"}:14d
```

victoria metrics storage fail with fatal.

### To Reproduce

run vm storage  with flag -retentionFilter that have 2+ labels in filter

### Version

vmstorage-20230228-023920-tags-v1.88.1-enterprise-cluster-0-g66191a84a

### Logs

```
Copyright 2018-2022 VictoriaMetrics, Inc - All Rights Reserved.
For any questions please contact info@victoriametrics.com
{"ts":"2023-03-06T06:34:28.617Z","level":"fatal","caller":"VictoriaMetrics/app/vmstorage/main.go:114","msg":"cannot parse -retentionFilter: cannot find ':' in -retentionFilter='{job_name!=\"pushgateway\"'; see https://docs.victoriametrics.com/#retention-filters"}
```

### Used command-line flags

-retentionFilter={job_name!="pushgateway",purpose="cp"}:14d

**Comment by f41gh7** [comment]
It's an issue with go flags. currently go splits flag values by `,`. We cannot escape it with "",  coz it's already used for value of filter escaping.

 Possible solutions for future issue fix:
1) use custom flag delimiter `^^`. e.g. -retentionFilter={job_name!="pushgateway",purpose="cp"}:14d^^
2) use custom filter delimiter `^^`. e.g. -retentionFilter={job_name!="pushgateway"^^purpose="cp"}:14d.

**Comment by paragor** [comment]
have tried do it via env flags - does not work any cases.

mb create specific env flag that will support comma?

**Comment by valyala** [comment]
@paragor , try the following workaround:

```
-retentionFilter='"{job_name!=\"pushgateway\",purpose=\"cp\"}:14d"'
```

The workaround wraps the `-retentionFilter` into two quotes:
- The outer single quotes are consumed by the Go flag library during parsing the flag value.
- The inner double quotes are consumed by the implementation, which provides support for multiple flag values inside VictoriaMetrics. This implementation supports individual values put inside double quotes. Such values can contain comma and other special chars. Double quotes must be escaped with `\` inside such values.

P.S. The upcoming release of VictoriaMetrics will support commas inside `{}` braces without the need to put flag values into double quotes. See the commit 85ca077a88414a443645dfd3951b5167831c14c3 for details.

**Comment by tenmozes** [comment]
@valyala same issues in in vmctl in all fields where you can specify the filter, please check https://victoriametrics.slack.com/archives/CGZF1H6L9/p1680520763439239

```
We are using vmctl vm-native command to perform data migrations and we need to limit the data we copy. We use --vm-native-filter-match for that, but it feels like itt only accepts one filter while ignoring the provided rest.
For example,
--vm-native-filter-match='{__name__="http_request_count_total",cluster="kube1"}'
will limit to metric http_request_count_total but not to the specific cluster label the former metric has. Is there a doc on how to use it?
```

**Comment by valyala** [comment]
> same issues in in vmctl in all fields where you can specify the filter, please check

This is unrelated issue, since [vmctl](https://docs.victoriametrics.com/vmctl.html) doesn't allow passing comma-separated array of values to `--vm-native-filter-match` command-line flag. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4062 and https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4063 .

VictoriaMetrics [v1.87.5 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.5) should properly parse `-retentionFilter='{job_name!="pushgateway",purpose="cp"}:14d'`. Closing the issue as fixed then.

**Comment by valyala** [comment]
FYI, the bugfix has been included also in all the VictoriaMetrics releases starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
Starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) it is allowed to use commas in command-line flags, which accept multiple comma-separated args. Such commas can present now inside `{}`, `[]` and `()` braces, additionally to single-quoted and double-quoted strings.

For example, `-retentionFilter='{foo="bar",baz="abc"}:14d,{a="b",c="d"}:30d'` is properly parsed as two [retention filters](https://docs.victoriametrics.com/#retention-filters): `{foo="bar",baz="abc"}:14d` and `{a="b",c="d"}:30d`.
