### ISSUE TITLE
sum_over_time function results in a value of 0

### ISSUE THREAD

**Issue by yincongcyincong** [VictoriaMetrics/VictoriaMetrics#394]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24344673/77839603-dcc06300-71b0-11ea-8a98-a3bcfdb0acf3.png)

as you can see. data is exist. but when i use 
```
sum(sum_over_time(like\.queue_monitor_agg1min{__aggType__="sum",proc="welog_video_recom_discover"}[1m]))
```
the result always is 0.
but when i use 
```
sum_over_time(sum(like\.queue_monitor_agg1min{proc="welog_video_recom_discover",__aggType__="sum"})[1m])
```
the result is right. i don't know why result in this.

![image](https://user-images.githubusercontent.com/24344673/77839595-c61a0c00-71b0-11ea-9f67-799964fd7c99.png)

when i use 
```
sum_over_time(like\.queue_monitor_agg1min{__aggType__="sum",proc="welog_video_recom_discover"}[1m])
```
it just have a little data.

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$  ./victoria-metrics-prod -version
victoria-metrics-20200326-234245-tags-v1.34.4-0-g047849e8
```

**Comment by valyala** [comment]
Try removing `[1m]` from the query:

```promql

sum_over_time(like\.queue_monitor_agg1min{__aggType__="sum",proc="welog_video_recom_discover"})

```

It is likely the interval between data points (aka `scrape_interval`) for time series exceeds 1 minute, so `sum_over_time(q[1m])` returns 0, since it cannot find data points on `1m` lookbehind intervals for each returned point. When the `[1m]` is removed, then VictoriaMetrics automatically sets the lookbehind interval to `$__interval`, i.e. the distance between points on the returned graph aka `step`.

Note also that the correct query is `sum(sum_over_time(...))`, not `sum_over_time(sum(...))`.

**Comment by yincongcyincong** [comment]
i remove ```1m```
but 0 is still exist
![image](https://user-images.githubusercontent.com/24344673/77864826-8ceba580-725d-11ea-8ac1-9724d1a97ac2.png)

**Comment by valyala** [comment]
Could you add wrap the query on the second graph to `sum_over_time()`? It should show individual lines, which are then summed into a single line on the first graph.

The non-zero line on the second graph at 18:23 may be an artifact of [staleness handling in Prometheus data model](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness):
> If no sample is found (by default) 5 minutes before a sampling timestamp, no value is returned for that time series at this point in time. This effectively means that time series "disappear" from graphs at times where their latest collected sample is older than 5 minutes

It is possible obtaining raw data for the given time series on the given interval from VictoriaMetrics via [/api/v1/export](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series) and then manually verifying whether VictoriaMetrics calculates `sum_over_time()` correctly for this data. Could you verify this data or provide the raw data, so I could help verifying the data?
