### ISSUE TITLE
Consul Agent based service discovery for VMAgent

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#3953]
### Is your feature request related to a problem? Please describe

The current service discovery mechanism in VM for Consul ([`consul_sd_config`](https://docs.victoriametrics.com/sd_configs.html?highlight=consul_sd_config#consul_sd_configs)) allows retrieving scrape targets from [Consul's Catalog API](https://www.consul.io/api-docs/catalog), which returns data for all services in the cluster. 
For large clusters there is an alternative mechanism - [Agent API](https://www.consul.io/api-docs/agent), which allows to get services only for current agent (i.e. cluster node). This may significantly reduce the load on Consul in large-scale setups.

### Describe the solution you'd like

To add `consulagent_sd_configs` for using Consul Agent API instead of Consul Catalog API.

### Describe alternatives you've considered

To use [consul_sd_configs](https://docs.victoriametrics.com/sd_configs.html#consul_sd_configs)

### Additional information

Related issues from Grafana:
- https://github.com/grafana/loki/issues/3744
- https://github.com/grafana/agent/issues/1419

Related issues from VictoriaMetrics:
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4183
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/574

**Comment by valyala** [comment]
The [consulagent_sd_configs](https://docs.victoriametrics.com/sd_configs.html#consulagent_sd_configs) functionality has been added in the commit 56b84140a95d02fdf8e56e0a003041c45c26d34f . This commit will be included in the next release. In the mean time it is possible to build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether Consul Agent service discovery works as expected there.

**Comment by valyala** [comment]
The [consulagent_sd_configs](https://docs.victoriametrics.com/sd_configs.html#consulagent_sd_configs) is available in `vmagent` and in [single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
