### ISSUE TITLE
VMSelect expose unrelated metrics

### ISSUE THREAD

**Issue by artmakh** [VictoriaMetrics/VictoriaMetrics#3958]
### Describe the bug

When you use VictoriaMetrics cluster version, VMSelect part of it exposes unrelated metrics `vm_promscrape_*` This triggers [default configuration reload failed VMAgent alert](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/6f6333831e080b3f7108d22903b9bc596a0fa69f/deployment/docker/alerts-vmagent.yml#L124-L134), although there is no promscape config needed for vmselect. 
<details>
  <summary>Full list of unrelated metrics exposed by vmselect</summary>
  
  ```vm_promscrape_config_last_reload_success_timestamp_seconds 0
vm_promscrape_config_last_reload_successful 0
vm_promscrape_config_reloads_errors_total 0
vm_promscrape_config_reloads_total 0
vm_promscrape_conn_bytes_read_total 0
vm_promscrape_conn_bytes_written_total 0
vm_promscrape_conn_read_errors_total 0
vm_promscrape_conn_reads_total 0
vm_promscrape_conn_write_errors_total 0
vm_promscrape_conn_writes_total 0
vm_promscrape_conns 0
vm_promscrape_dial_errors_total 0
vm_promscrape_dials_total 0
vm_promscrape_discovery_consul_service_watchers 0
vm_promscrape_discovery_consul_service_watchers_created_total 0
vm_promscrape_discovery_consul_service_watchers_stopped_total 0
vm_promscrape_discovery_kubernetes_group_watchers 0
vm_promscrape_discovery_requests_total 0
vm_promscrape_discovery_retries_total 0
vm_promscrape_discoveryutils_configmap_entries_count 0
vm_promscrape_max_scrape_size_exceeded_errors_total 0
vm_promscrape_scrape_requests_total 0
vm_promscrape_scrape_retries_total 0
vm_promscrape_scrapes_failed_total 0
vm_promscrape_scrapes_gunzip_failed_total 0
vm_promscrape_scrapes_gunziped_total 0
vm_promscrape_scrapes_skipped_by_sample_limit_total 0
vm_promscrape_scrapes_timed_out_total 0
vm_promscrape_scrapes_total{status_code="200"} 0
vm_promscrape_stale_samples_created_total 0 
```
  
</details>

### To Reproduce

1. Install VictoriaMetrics cluster
2. Curl vmselect `/metrics` endpoint
3. Find `vm_promscrape_*` metrics

### Version

v1.85.3-cluster

**Comment by hagen1778** [comment]
Hello! This was fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/5bca3a5be2ed1e5b8c91f1c19caebaa0ec3ab14a and is available starting from 1.86.0 version.
