### ISSUE TITLE
Data migration between VM clusters 

### ISSUE THREAD

**Issue by queca** [VictoriaMetrics/VictoriaMetrics#3963]
### Is your question request related to a specific component?

data migration, vmselect

### Describe the question in detail

Hello VictoriaMetrics Team,

I seek advice about data migration from VM clusters using the VM native protocol. 

We are trying to migrate data from an EC2-based VM cluster(**v.181.2**) to an EKS-based one, and we decided to use the time-based chunking of migration since we need the three months' metrics to be transferred. 

I could not find in the documentation if we can point the `--vm-native-src-addr` flag to the VMselect load balancer, or do we need to perform the data migration on the individual EC2 instances?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by queca** [comment]
Hi @dmitryk-dk thank you so much for your quick reply, but the documentation said that the cluster-to-cluster migration mode was released on v.1.84.0 and unfortunately we are on v.1.81.2

**Comment by dmitryk-dk** [comment]
@queca in that case, you can specify 
`--vm-native-src-addr` like `http://<vmselect>:8481/select/<accountID>/prometheus/`
`--vm-native-dst-addr` like `http://<vminsert>:8480/insert/<accountID>/prometheus/`

Where accountID `accountID:projectID` if you are using multitenancy

**Comment by queca** [comment]
Hi @dmitryk-dk, thank you. That will work for us.

**Comment by dmitryk-dk** [comment]
Hi @queca ! Can we close the question?
