### ISSUE TITLE
Cardinality explorer improvements

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3967]
### Is your feature request related to a problem? Please describe

Cardinality explorer is great for experienced and knowledgeable users. But IMHO it lacks some tools for improving user's experience in the process of identifying expensive time series.
Here's what I think can be improved.

### Describe the solution you'd like

1. Date picker.
By design, VictoriaMetrics indexdb stats are split by days. This is why in Cardinality explorer user needs to select a specific day for analysis:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/2902918/225613373-a3138e04-c278-4a5a-8a4e-e331765eca58.png">

But let's think what precedes this step. Usually, users refer to Cardinality explorer when they need to identify time series which can be dropped to reduce the pressure on the database. This usually means that database was working fine for some time and then something changed in the ingested data. That change negatively affected database performance or resource usage and user needs to identify what changed. For this, user would need to refer to Churn Rate registered by VictoriaMetrics:
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/2902918/225614780-1d15cca0-bcbb-4165-be6c-4802bc9c2f87.png">
From the graph above I will know that I need to pick 2023-02-18 day and analyze it, because that's the day when we got +2 Mil of new time series.

Now imagine that user can get access to this information right from the CardinalityExplorer UI:
<img width="856" alt="image" src="https://user-images.githubusercontent.com/2902918/225616537-d79a6ec5-68b2-453b-abb8-55d56663e60a.png">
Here on the picture each day in date picker shows what the Churn Rate on that day was. And only looking on it user can quickly decide that 2023-02-22 is worth checking, because that's the day when Churn Rate skyrockets.

2. Comparison.
As was mentioned, VictoriaMetrics indexdb stats are split by days. And getting stats even for one day is pretty expensive. But this is how it works. However, while cardinality information for one day can be useful, it can be even more useful if you know what changed.
So here's how stats on Cardinality Explorer page look like right now:
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/2902918/225617413-fda620ba-18f3-42ce-a63e-5537f15fadde.png">

What if Cardinality explorer could make one more request to fetch the data for the previous day and compare it to current one? If it could do so, the page would look like the following:
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/2902918/225619060-c56e99e9-01c8-49fd-b453-e370cc3a3e4b.png">

The change on the picture will immediately give an idea what metric has changed compared to the previous day.

**Comment by valyala** [comment]
[Cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer) shows the difference between the number of series / label values between the selected day and the previous day, starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See, [this example at VMUI playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality?date=2023-05-18).

Closing the feature request as done.
