### ISSUE TITLE
Hot reload for stream aggregation configs

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#3969]
### Is your feature request related to a problem? Please describe

It is necessary to be able to change the stream aggregation config without restarting vmagent.

### Describe the solution you'd like

Need to add a reinit stream aggregation configs in vmagent on `/-/reload` endpoint or sighup signal

**Comment by valyala** [comment]
Hot reload of stream aggregation configs is supported starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/stream-aggregation.html#configuration-update). Closing the feature request as done.
