### ISSUE TITLE
Add a graph for remaining disk space into official Grafana dashboards

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#397]
**Is your feature request related to a problem? Please describe.**
Currently there is no straightforward way for monitoring the remaining free disk space at `-storageDataPath`.

**Describe the solution you'd like**
I added `vm_free_disk_space_bytes` metric to VictoriaMetrics in the following commits (these commits will be included into the upcoming release v1.34.6):
* b38d048dd90f49648dae278cd132455e2cb9a6b8 for single-node version
* f838cdc86e9833a27d116284c2cbdefde21e462a for cluster version

This metric reports the remaining disk space at `-storageDataPath`. It would be great if official Grafana dashboards would show graph for this metric.

**Describe alternatives you've considered**
Alternative solutions is determine the volume for `-storageDataPath` and monitor free space at it via `node_exporter` or something like that. This is error prone and non-trivial task in general case, especially when VictoriaMetrics is deployed in Kubernetes.

**Additional context**
cc'ing @hekmon , so he could update [unofficial dashboard for VictoriaMetrics](https://grafana.com/grafana/dashboards/11831) as well.

**Comment by hekmon** [comment]
I saw the release notes and this was already on my todo :) thx for cc'ing anyway !

**Comment by hagen1778** [comment]
Dashboards were updated:
* https://grafana.com/grafana/dashboards/11176/revisions
* https://grafana.com/grafana/dashboards/10229/revisions
