### ISSUE TITLE
Unexpected query results when using 'offset -1m'

### ISSUE THREAD

**Issue by Buddruggy** [VictoriaMetrics/VictoriaMetrics#3974]
### Describe the bug

promql: round(sum(sum_over_time(rpc_client_handled_total{namespace="Development",target="xxx"}[1m] )) by (callee_service)) 

result:
![image](https://user-images.githubusercontent.com/32037815/225903773-1197bc5b-3ddb-4d6f-8a32-eb6a0269f30c.png)

promql: 
round(sum(sum_over_time(rpc_client_handled_total{namespace="Development",target="xxx"}[1m] )) by (callee_service)) offset -1m

result:
![image](https://user-images.githubusercontent.com/32037815/225903983-195d95e9-5422-49fe-beff-fc9ca584842c.png)

### To Reproduce

Single datapoint changed  to timeseies after added 'offset -1m' at the end of  promql.

The expected result is that all datapoints timestamp increase by one step.

### Version

vmstorage-20221007-005541-tags-v1.82.0-cluster-0-g58ee1b9ed

This problem also happened in version: vmstorage-20230209-232756-tags-v1.87.1-cluster-0-ga68bb879d

**Comment by Buddruggy** [comment]
> Hello! Can you provide the data on which I can reproduce the issue? To do so, export the raw samples via [export API](https://docs.victoriametrics.com/url-examples.html#apiv1export). Choose the time period and specific time series where issue can be reproduced. Feel free to obfuscate the data if needed. Attach the data sample to the ticket or send it to [roman@victoriametrics.com](mailto:roman@victoriametrics.com).

I have sent you the exported timeseries data by email, please check!

**Comment by Buddruggy** [comment]
@hagen1778 Thanks for your answer, I encountered a new problem that the same promql is executed twice at the same time range but get different results, even though offset modificator applied only to a metric selector.

I will sent the query param and timeseries to your email.

**Comment by hagen1778** [comment]
Do you have deduplication enabled in your setup? Do you have HA pairs writing the same data in VictoriaMetrics?

**Comment by Buddruggy** [comment]
> Do you have deduplication enabled in your setup? Do you have HA pairs writing the same data in VictoriaMetrics?

Deduplication is disabled in my setup. I am not sure about the second question, It is possiable to writing the same data in VM.

vmselect : `/usr/bin/vmselect-prod -storageNode=xxx -memory.allowedPercent=80 -search.maxUniqueTimeseries=1000000 -search.maxSeries=100000 -search.maxSamplesPerQuery=500000000`

vmstorage: `/usr/bin/vmstorage-prod -storageDataPath=/data -retentionPeriod=30d -search.maxUniqueTimeseries=3000000`

**Comment by Buddruggy** [comment]
Hi Roman, i tried this promql : `histogram_quantile(0.990000,sum(sum_over_time(rpc_server_handled_seconds_bucket{namespace="Production",target="PCG-123.opdd.dg_report",namespace="Production"}[1m])) by (callee_con_setid,callee_method,namespace,vmrange)) > 2` with the timeseries i sent you before, the same problems exist. So this problem should not caused by `offset`.

**Comment by hagen1778** [comment]
Thanks. I can confirm it reproduces. Moving to the new issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4024

**Comment by valyala** [comment]
Side note: @Buddruggy , the name of the `rpc_client_handled_total` metric suggests this is a [counter](https://docs.victoriametrics.com/keyconcepts/#counter). The [`sum_over_time()` function](https://docs.victoriametrics.com/metricsql/#sum_over_time) is usually applied to [gauges](https://docs.victoriametrics.com/keyconcepts/#gauge). There is little sense in applying this function to counters.
