### ISSUE TITLE
Victoria Metrics unable to display migrated data ( InfluxDB)

### ISSUE THREAD

**Issue by puneet336** [VictoriaMetrics/VictoriaMetrics#3980]
### Describe the question in detail

Hi , 
We are currently using prometheus and influx 1.8 db to monitor aur infrastructure.

We have some data from 2022 to 2023 . For testing, i tried migrating 1 hour of data into the Victoria Metrics using - 
```
time /usr/local/bin/vm/vmctl-prod influx --influx-addr "http://den-grafana-01:8086" --influx-filter-time-start "2023-01-18T08:48:32Z" --influx-filter-time-end "2023-01-18T09:48:32Z" --vm-addr "http://127.0.0.1:8428" --influx-database monitoring
```
![image](https://user-images.githubusercontent.com/5935825/226277420-02260887-438d-4b61-9f47-62d45ef811bc.png)

So , in summary 1248598/20585657 samples appears to have been loaded in Victoria Metrics.

but when i try checking the data using VM UI  for 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/5935825/226284592-afd6384c-02b1-40ff-b808-1a6abff11516.png">

i am unable to see any data in table  -
<img width="954" alt="image" src="https://user-images.githubusercontent.com/5935825/226284318-58b5ba61-9928-4b5d-90ae-32b2ea57ad54.png">

same with json - 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/5935825/226284390-d5241ff6-cd98-4f17-9563-5da7bf0695e4.png">

and graph view 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/5935825/226284492-b76e3e71-9425-419d-895b-9d99045b7937.png">

To verify the influx DB data , i took a dump of the data for which VM is unable to show data in table, and it seems that we have the data. I had created a line profocol file using `influx_inspect` utility. 
```
influx_inspect export -database "monitoring" -datadir "/database/influxdb/data" -waldir "/database/influxdb/wal" -out "$HOME/backup1" -start 2023-01-18T08:48:32.157000Z -end 2023-01-18T09:48:32.157000Z
```
here;s the content of file - 
```
]~> grep "^up,__name__" backup1|head
up,__name__=up,instance=100.23.17.11:9335,job=lsf_jobs value=0 1674031751789000000
up,__name__=up,instance=100.23.17.11:9335,job=lsf_jobs value=0 1674031756790000000
up,__name__=up,instance=100.23.17.11:9335,job=lsf_jobs value=0 1674031761790000000
up,__name__=up,instance=100.23.17.11:9335,job=lsf_jobs value=0 1674031766790000000

]~> grep "^up,__name__" backup1 | tail
up,__name__=up,instance=localhost:9340,job=flexlm-ibm value=0 1674034739678000000
up,__name__=up,instance=localhost:9340,job=flexlm-ibm value=0 1674034799678000000
up,__name__=up,instance=localhost:9340,job=flexlm-ibm value=0 1674034859691000000
up,__name__=up,instance=localhost:9340,job=flexlm-ibm value=0 1674034919681000000
```

Could you please help me in understanding as to in why VM is unable to show the data for the selected timerange with table and json views?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @puneet336 ! Have you tried recommendations from this part of the documentation?
https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results
Do you use a single or cluster version of the VM?

**Comment by puneet336** [comment]
Hi @dmitryk-dk 
Thnak you for the response,
I am currently exploring single node version of VM.

I will explore the link, but do you think that there is issue with my query ?

**Comment by dmitryk-dk** [comment]
@puneet336 ! Possibly, yes, try to enable `Disable cache` switch on VMUI, second proposal  - try to check your data via `/api/v1/export` [call](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format). 
And I think you should check logs when you migrate data from influx to VM, maybe you can find there something

**Comment by puneet336** [comment]
Thank you @dmitryk-dk ,
It seems that the confusion on the graph was related to the timezone settings.
I was trying to use   -start `2023-01-18T08:48:32.157000Z` -end `2023-01-18T09:48:32.157000Z`
Which is in UTC time, so i should have used UTC in the setting of VMUI.
This is what i see after changing the timezone to +UTC 00:00

![image](https://user-images.githubusercontent.com/5935825/227141745-70c911a5-c4bf-42e4-8f91-2f440fe0a55e.png)


However,  the table tab is still unable to display the data - 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/5935825/227145095-bd36c307-55ee-484c-8a5b-e79726759cee.png">

**Comment by dmitryk-dk** [comment]
Hi @puneet336 ! It might be a bug on VMUI. We will take a look. Can we close this issue, and can you create a separate one about VMUI?

**Comment by dmitryk-dk** [comment]
@Loori-R can you check described problem on VMUI, please?

**Comment by Loori-R** [comment]
JSON and Table tabs use [Instant query](https://docs.victoriametrics.com/keyConcepts.html#instant-query) that tries to locate a data sample is equal to `5m`. This is done intentionally to ensure compatibility with Prometheus.
You can adjust the `end time` or use [last_over_time](https://docs.victoriametrics.com/MetricsQL.html#last_over_time). See more details in [Frequently asked questions](https://docs.victoriametrics.com/guides/migrate-from-influx.html#frequently-asked-questions).
We'll also add detailed information to the UI.

**Comment by dmitryk-dk** [comment]
Close it as resolved
