### ISSUE TITLE
vmui: error is displayed for wrong query

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#3987]
### Describe the bug

While error is related to Query 2 - it is also displayed or Query 1.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2902918/226627630-9d41c8ae-87c7-4e92-80d1-cc209c5833f0.png">

### To Reproduce

[Check the query ](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=vm_http_requests_total&g0.range_input=30m&g0.end_input=2023-03-21T13%3A55%3A12&g0.relative_time=last_30_minutes&g1.expr=vm_http_requests_total+offset&g1.range_input=30m&g1.end_input=2023-03-21T13%3A55%3A12&g1.relative_time=last_30_minutes)

### Version

latest

**Comment by valyala** [comment]
The bug with incorrect error displaying at `vmui` for multiple queries has been fixed in [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue then.
