### ISSUE TITLE
configCheckInterval for vmauth

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#3990]
### Is your feature request related to a problem? Please describe

Need to add `configCheckInterval` flag to vmauth for feature compatibility with vmgateway.

### Describe the solution you'd like

Add `configCheckInterval` flag. it's interval for config file re-read.
Zero value disables config re-reading. By default, refreshing is disabled.

**Comment by valyala** [comment]
`vmauth` gains support for `-configCheckInterval` command-line flag in the commit 36edba9bfbb6baed4e74078d83851cef2bd2920a . This commit will be included in the next release. In the mean time it is possible to test this command-line flag by building `vmauth` from this commit according to [these docs](https://docs.victoriametrics.com/vmauth.html#how-to-build-from-sources).

**Comment by valyala** [comment]
The `-configCheckInterval` command-line flag is available at `vmauth` starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request then.
