### ISSUE TITLE
cluster's performance degradation when vmstorage IO is near 100%

### ISSUE THREAD

**Issue by Planck0591** [VictoriaMetrics/VictoriaMetrics#3998]
### Describe the bug

Sometime cluster is not avalible.From grafana we could find out that query is very slow and metric insert is fail.And from server monitor  we could find out that disk io is 100% because of vmstorage.Our disk is hdd and raid10,speed is 400MB/s.
My solution is to restart vmstorage node,then cluster could work again.

### To Reproduce

I could provide some grafana screenshots,but could not reproduce.

### Version

v1.76.1-cluster

### Screenshots

![FireShot Capture 013 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196286-99857acf-a120-423d-b320-a5aa327c734d.png)
![FireShot Capture 014 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196308-1f9dc74d-d6fe-4964-af0d-17cbf344c525.png)
![FireShot Capture 015 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196315-bb0dbe90-60ab-4d1c-8281-78b8c4b77e3b.png)
![FireShot Capture 016 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196330-9631db84-3c88-4b4f-a92e-bd48e6bde244.png)
![FireShot Capture 017 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196335-dd0f260c-b045-4aca-a9ef-1e99e1e1a5a1.png)
![FireShot Capture 018 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196341-3e2f2c56-b3dd-4b91-a145-ceef34f8bd8f.png)
![FireShot Capture 019 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196343-66f9e7a8-6b71-47ef-ab49-f08a0c0841b7.png)
![FireShot Capture 020 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196347-24bb474d-9b23-4138-939e-3262b40783e7.png)
![FireShot Capture 021 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196350-d7aa8ccf-0778-4fff-93e5-d06374ce3434.png)
![FireShot Capture 022 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196353-a04aceb1-58ba-412f-82f7-c42fde1aad9e.png)
![FireShot Capture 023 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227196360-2366d397-906e-4621-93f7-b5c8bf050ce8.png)

**Comment by nevlkv** [comment]
same state [1.88.1](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2110#issuecomment-1480969165) on active background merges

**Comment by hagen1778** [comment]
> same state https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2110#issuecomment-1480969165 on active background merges

Background merges are limited by 4 threads. If 4 threads can exhaust disk IO, it is recommended to manually lower number of threads for background merges via flag `bigMergeConcurrency`.

**Comment by Planck0591** [comment]
@hagen1778 Thanks for reply.Yes,I restarted vmstorage node to repair the cluster fast.
![FireShot Capture 024 - vm-cluster-default-bak运营图 - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227405545-ca4eb143-62e7-4abf-9015-afacb7910200.png)
From this screenshot we could find out that disk io is 100%,after restart it back to normal faster than I do nothing.
I have tried 1.85.1,there is disk io problem also.
From official doc disk speed is not important,but I found that only sdd could work more available。But this year I found more and more disk io 100%.
Could you provider some suggestions?thanks

**Comment by hagen1778** [comment]
> From this screenshot we could find out that disk io is 100%,after restart it back to normal faster than I do nothing.

Could you provide the same list of screenshot only for a situation where vmstorage got stuck first, before you did a restart?

> From official doc disk speed is not important,but I found that only sdd could work more available。But this year I found more and more disk io 100%.

VM is indeed optimized for slow HDD disks. Unfortunately, it works well when everything else works well. Once cluster starts to experience memory shortage, or rerouting happens because of vmstorage restarts - VM starts to recover with all available speed. And it depends on the disks and other resources limitations how fast VM will recover from disaster. I think, this is appropriate behavior - it should utilize everything it has to recover as fast as possible.

So what we need to understand here is why in the first place, your cluster became unstable. For this I need screenshots I requested above.

**Comment by Planck0591** [comment]
![FireShot Capture 025 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575948-d13e60dd-f2fb-4686-bbdc-12cae2717764.png)
![FireShot Capture 026 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575962-78ccbbda-011e-4ae2-98ba-c0e06f2d6fef.png)
![FireShot Capture 027 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575968-e90667ac-1825-41cc-b24b-c21c795f3eb3.png)
![FireShot Capture 028 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575972-ffe7276f-84c2-4ac8-96f5-3b457fd46024.png)
![FireShot Capture 029 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575977-e87a3cb5-6e2a-4206-b230-77734aab9f74.png)
![FireShot Capture 030 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575981-d69173e5-8c5a-455a-85b6-6bc3db82f066.png)
![FireShot Capture 031 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575984-b5110d4a-13c6-4141-a87f-a6a4508f4419.png)
![FireShot Capture 032 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575989-7740b819-a9e5-47bf-9afa-89b411df8011.png)
![FireShot Capture 033 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575994-ada52798-5162-4383-9ec8-e68b1a7769cd.png)
![FireShot Capture 034 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227575997-e736cc83-6e08-4131-abcb-b513a2b91aa5.png)
![FireShot Capture 035 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227576000-c400cfc7-4b01-4496-9600-0e63bee7eb15.png)
![FireShot Capture 036 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227576007-6fa4a9c4-32a3-4972-aef6-0a1721288d8e.png)
![FireShot Capture 037 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227576010-15e668ea-2469-4222-9ce6-748df05ea9b7.png)
![FireShot Capture 038 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227576017-346b238a-f069-454f-b994-b869b8d17583.png)
![FireShot Capture 039 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227576022-79ef7b4a-7b50-4f36-b541-0e3c44f707a5.png)
@hagen1778

**Comment by Planck0591** [comment]
@hagen1778 
vmstorage started with docker-compose.Config is as below:
version: '2'
services:
  vmstorage:
    image: victoriametrics/vmstorage:v1.76.1-cluster
    mem_limit: 40G
    container_name: vmstorage
    network_mode: host
    restart: always
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - /data/vm-data:/victoria-metrics-data
    command:
      - '--storageDataPath=/victoria-metrics-data'
      - '--retentionPeriod=35d'
 vminsert node config is as below:
- '--search.maxQueryLen=49152'
- '--search.maxSeries=50000'
- '--search.maxQueryDuration=20s'

**Comment by Planck0591** [comment]
![FireShot Capture 025 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582198-a9bcb3af-7302-4f48-835c-5c18506a2799.png)
![FireShot Capture 026 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582207-85cb1623-83cc-461d-812b-32602b6db626.png)
![FireShot Capture 027 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582209-a5ed00ba-ed58-48c7-8dcb-990a1f3e4156.png)
![FireShot Capture 028 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582213-5e1552ba-4992-4c68-945e-e5b95d720898.png)
![FireShot Capture 029 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582217-42a02460-7686-4d7f-ac1d-4c2ca272de32.png)
![FireShot Capture 030 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582221-5144775f-a558-4218-944f-bcbc4ded0f23.png)
![FireShot Capture 031 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582225-82e50044-942b-4f86-8b19-cc8762c521b9.png)
![FireShot Capture 032 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582229-948b9372-e6d4-4756-9b63-252496a03e5a.png)
![FireShot Capture 033 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582237-3d32a3af-c8c9-47bb-a193-6c3c38bdf54f.png)
![FireShot Capture 034 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582240-dd5caadf-a55b-4e10-8659-da081b9cdb82.png)
![FireShot Capture 035 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582245-a5f8cbe9-b818-4a7a-ac9b-2ed0c07cd1e9.png)
![FireShot Capture 036 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582248-a125ee7c-2a36-488f-9e4e-a9c469d8ae28.png)
![FireShot Capture 037 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582250-ce23d434-ee3a-4fe7-bc63-f93043b041a9.png)
![FireShot Capture 038 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582254-7b647dc3-d93c-40ca-a0b5-b215343090c3.png)
![FireShot Capture 039 - VictoriaMetrics - cluster - Dashboards - Dashboards - Grafana_ - hummer bs58i baishancloud com](https://user-images.githubusercontent.com/79493220/227582258-71d53713-b7a2-4964-999f-7b2334c97010.png)
@hagen1778

**Comment by hagen1778** [comment]
Hello @Planck0591 ! Sorry for the late reply and thanks for providing screenshots.

From the screenshots I see multiple issues:
1. vmstorage memory usage is almost 95% according to the limit `mem_limit: 40G`. The memory limit needs to be increased or the load need to be lowered.
2. SlowInserts is > 40%, when recommended value should be lower than 5%. This is result of memory shortage - you can read more about slow inserts [here](https://docs.victoriametrics.com/FAQ.html#what-is-a-slow-insert).

If you've configured recommended [alerting](https://docs.victoriametrics.com/Quick-Start.html#monitoring) you'd be notified about these issues.

Memory shortage means vmstorages need to touch disk more frequently, which causing 100% IO and makes vmstorage too slow. I recommend reading https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion

My personal recommendation is to get updated to latest versions or to latest LTS version. Then scale cluster's resources or reduce the workload. Remember, it is recommended to run a cluster with big number of small vmstorage nodes instead of a cluster with small number of big vmstorage nodes. See more here - https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning

**Comment by Planck0591** [comment]
@hagen1778 Thanks for reply and your suggestions.
But I am confused as the official documentation states that :
1. It is recommended to use the [single-node version](https://github.com/VictoriaMetrics/VictoriaMetrics) instead of the cluster version for ingestion rates lower than a million data points per second.
2. if you are going to ingest hundreds of millions of active time series at ingestion rates exceeding a million samples per second, then it is better to use cluster version of VictoriaMetrics, since its capacity can [scale horizontally with the number of nodes in the cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-resizing-and-scalability).
In my scenario,the ingestion rate is 800,000 and  active time series is 250 millions.So I have selected cluster version using 10 servers with 32 cores and 64 GB of RAM. But now it still face slowinsert > 40% and memory not enough problem as you pointed.
Is the cluster's resources really need to be scaled or is there some problem with my cluster configuration?

**Comment by jiekun** [comment]
Close as answered.
