### ISSUE TITLE
Add /graph page for PromQL debugging

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#4]
### The issue

`VictoriaMetrics` doesn't have `/graph` page like [Prometheus does](https://prometheus.io/docs/visualization/browser/). This page is also known as `Prometheus expression browser`. This page is linked when editing PromQL queries in Grafana. It is useful for PromQL debugging.

### The solution

Add `/graph` page to `VictoriaMetrics`.

**Comment by tenmozes** [comment]
@dlazerka could please comment an issue, are we ready to add graph?

**Comment by valyala** [comment]
@tenmozes , I'm is in charge of this feature now. It isn't ready yet because of [big dependencies in `node_modules`](https://www.reddit.com/r/ProgrammerHumor/comments/6s0wov/heaviest_objects_in_the_universe/). These dependencies must be stripped before merging the feature to master branch.

**Comment by tfpereira** [comment]
Hi @valyala , any developments on this?

**Comment by valyala** [comment]
We decided to implement `/graph` page as a part of separate `vmui` executable, which will provide various web pages for querying VictoriaMetrics and debugging [MetricsQL](https://victoriametrics.github.io/MetricsQL.html) queries. There is no ETA for `vmui` yet.

**Comment by lexfrei** [comment]
Any news?

**Comment by TinySong** [comment]
any progress ?

**Comment by valyala** [comment]
Please see https://github.com/VictoriaMetrics/vmui
