### ISSUE TITLE
How does dedup.minScrapeInterval work when we have different scrape intervals for jobs

### ISSUE THREAD

**Issue by brucelee138** [VictoriaMetrics/VictoriaMetrics#4003]
### Is your question request related to a specific component?

Deduplication config (dedup.minScrapeInterval) when targets are scrape with different scrape intervals (global scrape interval and scrape interval for jobs)

### Describe the question in detail

We are using Victoria Metrics Cluster version in HA (2 instances). We have a global scrape interval of 30s and following the "Deduplication docs", we have already set dedup.minScrapeInterval for vmstorage & vmselect as 30s.
Now, we are planning to have a smaller scrape interval only for selective targets and so configured a separate job and configured a smaller scrape_interval (10s).
We tried to query metrics from this new job and found that samples are present only for each global_scrape_interval. We had to set dedup.minScrapeInterval to 10s to get samples for each 10s.
But we think think this would affect the deduplication of the metrics discovered by other job. Is there any means to solve this?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello! 

> But we think think this would affect the deduplication of the metrics discovered by other job. Is there any means to solve this?

Yes, you're right regarding this. dedup.minScrapeInterval is a global interval applied to all data samples. According to the implementation, deduplication leaves the newest sample on each configured interval. If 3 samples will fall in 30s interval - the newest one will be kept. 

However, deduplication on the storage is permanent - it modifies data on the disk dropping extra samples.
But deduplication on vmselect is performed in-flight. Hence, you can have vmselects for 30s or 10s dedup interval and perform deduplication in-flight.

**Comment by brucelee138** [comment]
Thanks for the feedback @hagen1778 ! So it would be alight to set the minimum scrape interval configured as the dedup.minScrapeInterval(maybe thats why its named so!?) so that metrics would be available for the job scrape interval (10s).
I think the metrics from other jobs (with larger globe scrape_interval) should not get affected value correctness-wise. Any issues it could cause with the vmselect/vmstorage performance though?

**Comment by brucelee138** [comment]
Thanks @hagen1778 for the reply! Then I think we could safely put the minimum of the scrape intervals configured in dedup.minscrape as it wont affect the value correctness-wise for the jobs with scrape intervals more than that.
Thanks for your support on this.
