### ISSUE TITLE
namespace level retention support

### ISSUE THREAD

**Issue by manojgowda** [VictoriaMetrics/VictoriaMetrics#4011]
### Is your feature request related to a problem? Please describe

yes we have a scenario where we store different kind of metrics in different namespace in a single cluster, but this cluster does not have support for namespace level retention, these metrics can have different retention policy.

### Describe the solution you'd like

retention of data should be applicable on namespace level, lets say i have nginx logs metrics in 2222:1 namespace, which need retention policy of 15 days, in another namespace 2222:2 i have syslog which need retention policy of 2 days.

### Describe alternatives you've considered

to achieve this i had to launch a completely new cluster which is costlier, but keeping data for same retention policy for all namespaces also results more resources for existing cluster.

**Comment by f41gh7** [comment]
Enterprise version has [retentionFilters](https://docs.victoriametrics.com/#retention-filters), which could be applied for namespace labels. 

  ```-retentionFilter='{namespace="2222:1"}:15d -retentionFilter='{namespace="2222:2"}:2d```
