### ISSUE TITLE
VMagent keeps previous deleted remotewrite configs persistent queues.

### ISSUE THREAD

**Issue by mohammadkhavari** [VictoriaMetrics/VictoriaMetrics#4014]
### Describe the bug

According to network issues I'm using vmagent with persistent volume for remotewrite pending data. I have enabled statefulMode option from vmagent crd for Kubernetes. so if there was a network problem and meanwhile vmagent pod has been reseted persistent queue data stays in persistent volume.
The main problem is that vmagent does not flush pending queue of a removed remotewrite URL. if I modify a remotewrite url in vmagent config previous queue will stay in persistent volume. 

### To Reproduce

Setup a volume for remotewrite pending queues or use statefulmode option on kubernetes cluster and victoriametrics operator. 
block vmagent egress network until it pending queues increases.
change remotewrite url that has pending queue.
now previous queue will stay in volume and it will never flush cause it doesn't relate to any remotewrite. 

### Version

vmagent-20221220-230030-tags-v1.85.3-0-gf443fad56

### Additional information

This problem can be fixed with an additional option on each vmagent like (remoteWrite.removeDanglingQueues)
so the agent will remove queues that are not related to any remotewirte config.

**Comment by valyala** [comment]
`vmagent` should automatically drop unused persistent queues at `-remoteWrite.tmpDataPath` on startup when there is no matching `-remoteWrite.url` after the commit aea6df81974ae2ead680c7f28007add57e4c5a3f . This commit will be included in the next release. In the mean time it is possible to test it by building `vmagent` from this commit according to [these instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

If unused persistent queues must be preserved for some reason, then `vmagent` must be started with `-remoteWrite.keepDanglingQueues` command-line flag.

**Comment by valyala** [comment]
`vmagent` automatically drops unused persistent queues at `-remoteWrite.tmpDataPath` starting from [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as resolved.

**Comment by valyala** [comment]
FYI, this change introduced an issue when `vmagent` runs with [`-remoteWrite.multitenantURL`](https://docs.victoriametrics.com/vmagent.html#multitenancy) command-line flag. The issue may result in `FATAL: cannot flush metainfo` panic - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5357 for details. The workaround is to run `vmagent` with `-remoteWrite.keepDanglingQueues` command-line flag.
