### ISSUE TITLE
For label values queries, the start time and end time parameters have no effect

### ISSUE THREAD

**Issue by zxlxgd** [VictoriaMetrics/VictoriaMetrics#4016]
**For label values queries, the start time and end time parameters have no effect**

When I execute this query：
http://vm-addr/select/1/prometheus/api/v1/label/pod/values?match[]=kube_pod_info&start=1679638818&end=1679638818

**Query result exceeds the time range**

**Comment by zekker6** [comment]
@zxlxgd This endpoint does respect `start` and `end` parameters, you can verify this by using [tracing](https://docs.victoriametrics.com/#query-tracing). You can check date ranges which were used to execute query.

Here is an example line you will need to look for:
```
search for label values: labelName=\"pod\", filters=[{AccountID=0,ProjectID=0,__name__=\"kube_pod_info\"}], timeRange=[2023-03-27T10:46:17Z..2023-03-27T10:46:17Z], maxLabelNames=100000, maxMetrics=300000
```
You will see the `timeRange` value which will be based on timesamps provided as `start` and `end` value.

**Comment by zxlxgd** [comment]
@zekker6 Hi~,I added the trace parameter for verification, and the trace information display expanded the query scope to the current day

`{
                                                                "duration_msec": 93.111,
                                                                "message": "parallel search for label values: labelName=\"pod\", filters=[{AccountID=764244226,ProjectID=0,__name__=\"kube_pod_info\",xHawk_user_space_id=\"1599680843224244226\"}], timeRange=[2023-03-28T09:00:00Z..2023-03-28T09:01:00Z]",
                                                                "children": [
                                                                    {
                                                                        "duration_msec": 93.082,
                                                                        "message": "search for label names: filters=[{AccountID=764244226,ProjectID=0,__name__=\"kube_pod_info\",xHawk_user_space_id=\"1599680843224244226\"}], date=2023-03-28",
                                                                        "children": [
                                                                            {
                                                                                "duration_msec": 61.404,
                                                                                "message": "search for metric ids: filters=[{AccountID=764244226,ProjectID=0,__name__=\"kube_pod_info\",xHawk_user_space_id=\"1599680843224244226\"}], timeRange=[2023-03-28T00:00:00Z..2023-03-28T23:59:59.999Z], maxMetrics=1000000",
                                                                                "children": [
                                                                                    {
                                                                                        "duration_msec": 61.397,
                                                                                        "message": "update metric ids: filters={AccountID=764244226,ProjectID=0,__name__=\"kube_pod_info\",xHawk_user_space_id=\"1599680843224244226\"}, timeRange=[2023-03-28T00:00:00Z..2023-03-28T23:59:59.999Z]: updated 12534 metric ids",
                                                                                        "children": [
                                                                                            {
                                                                                                "duration_msec": 61.39,
                                                                                                "message": "search for metric ids on a particular day: filters={AccountID=764244226,ProjectID=0,__name__=\"kube_pod_info\",xHawk_user_space_id=\"1599680843224244226\"}, date=2023-03-28, maxMetrics=1000001",
                                                                                                "children": [
                                                                                                    {
                                                                                                        "duration_msec": 4.139,
                                                                                                        "message": "search for the first non-negative filter with the smallest cost",
                                                                                                        "children": [
                                                                                                            {
                                                                                                                "duration_msec": 4.126,
                                                                                                                "message": "get metric ids for filter and date: filter={__name__=\"kube_pod_info\"}, date=2023-03-28, maxMetrics=50000050, maxLoopsCount=9795105",
                                                                                                                "children": [
                                                                                                                    {
                                                                                                                        "duration_msec": 4.118,
                                                                                                                        "message": "found 12534 metric ids for filter={__name__=\"kube_pod_info\"} using exact search; spent 12534 loops"
                                                                                                                    }
                                                                                                                ]
                                                                                                            },
                                                                                                            {
                                                                                                                "duration_msec": 0.003,
                                                                                                                "message": "the filter={__name__=\"kube_pod_info\"} matches less than 50000050 series (actually 12534 series); use it"
                                                                                                            }
                                                                                                        ]
                                                                                                    },`

**Comment by zxlxgd** [comment]
@zekker6 Thank you very much，i understand.
