### ISSUE TITLE
Add a graph for open file descriptors to official Grafana dashboard

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#402]
**Is your feature request related to a problem? Please describe.**
Highly loaded VictoriaMetrics process can consume all the available per-process file descriptors. After that VictoriaMetrics won't accept new connections from Prometheus, [vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md) or any other client.

**Describe the solution you'd like**
It would be great to have a graph on the number of open file descriptors via `process_open_fds` and the maximum number of open file descriptors via `process_max_fds`. This could help quickly identifying the issue with too small `ulimit -n` limit.

**Describe alternatives you've considered**
An alternative is to create an alert like `process_open_fds / process_max_fds > 0.9`, which will signal when the number of open file descriptors approaches the limit.

**Additional context**
See https://www.robustperception.io/kernel-file-descriptor-metrics-from-the-node-exporter for details.

**Comment by hagen1778** [comment]
Looks like these metrics aren't exported by default:
```
curl -s http://localhost:8428/metrics | grep process_open_fds

```
Should I configure something to get it exported?

**Comment by valyala** [comment]
oops, it looks like `process_max_fds` and `process_open_fds` metrics are missing in [github.com/VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) due to performance reasons for processes with big number of open file descriptors. I'll explore ways for obtaining these metrics with lower CPU overhead.

**Comment by valyala** [comment]
FYI, `process_open_fds` and `process_max_fds` metrics have been added in the commit 9fb38569eb34236a66de4640c1f058922bf0d658 . It will be included in the next release.

**Comment by anjakefala** [comment]
Thanks @valyala! :blush:

**Comment by valyala** [comment]
The `process_open_fds` and `process_max_fds` metrics are available starting from [v1.54.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). @hagen1778 , could you add the corresponding graph to the official VictoriaMetrics dashboards for Grafana? Additionally, it would be great adding the corresponding alerting rule in [deployment/docker/alerts.yml](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts.yml).

**Comment by valyala** [comment]
Graphs on open file descriptors have been added in the following commits:
* cluster version - 540c00f2a0ae324915b759b8217747bc006f71a1
* single-node version - b457739f87c4bd30ccf2d51f69829b6fa2b2e336

@hagen1778 , should this issue be closed now?

**Comment by hagen1778** [comment]
Published updates here https://grafana.com/orgs/victoriametrics/dashboards
