### ISSUE TITLE
histogram_quantile produces different results on repeated executions

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4024]
### Describe the bug

Query`histogram_quantile(0.990000,sum(sum_over_time(rpc_server_handled_seconds_bucket{namespace="Production",target="PCG-123.opdd.dg_report",namespace="Production"}[1m])) by (callee_con_setid,callee_method,namespace,vmrange)) > 2` repeated multiple times returns different results.

Originally issue was raised here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3974#issuecomment-1482179858

### To Reproduce

Use data provided by the author of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3974#issuecomment-1482179858 and repeat multiple times the following query `histogram_quantile(0.990000,sum(sum_over_time(rpc_server_handled_seconds_bucket{namespace="Production",target="PCG-123.opdd.dg_report",namespace="Production"}[1m])) by (callee_con_setid,callee_method,namespace,vmrange)) > 2` 

### Version

v1.88.1

### Used command-line flags

All default

**Comment by hagen1778** [comment]
Hey @Buddruggy!
Which library do you use for histogram metrics?

**Comment by Buddruggy** [comment]
@hagen1778 Sorry i don't quite understand what you mean, do you mean the way about how data write into vminsert?

In my case, data is wirtten by the remote wite interface `insert/0/promthesu/api/v1/write` from other app (not vmagent).

**Comment by hagen1778** [comment]
> In my case, data is wirtten by the remote wite interface insert/0/promthesu/api/v1/write from other app (not vmagent).

Right. But which library that app is using for maintaining and pushing its metrics? Is it https://github.com/victoriaMetrics/metrics ?

**Comment by Buddruggy** [comment]
> > In my case, data is wirtten by the remote wite interface insert/0/promthesu/api/v1/write from other app (not vmagent).
> 
> Right. But which library that app is using for maintaining and pushing its metrics? Is it https://github.com/victoriaMetrics/metrics ?

I did not use the vm library or any other library. the labels and values were constructed according to the data format of prometheus, and then written directly to the vm via http request.

**Comment by Buddruggy** [comment]
Is there something unusual about this metrics data?

**Comment by hagen1778** [comment]
> Is there something unusual about this metrics data?

Yes, looks like histogram bucket ranges do overlap each other:
```
sum(rpc_server_handled_seconds_bucket) by(vmrange)

0.000e+00...5.000e-03 | 2 |  
1.000e+00...5.000e+00 | 2 |  
1.000e-01...2.000e-01 | 2 |  
1.000e-01...2.500e-01 | 10 |  
1.000e-02...2.000e-02 | 20 |  
1.000e-02...2.500e-02 | 43 |  
2.000e-01...5.000e-01 | 13 |  
2.000e-02...5.000e-02 | 21 |  
2.500e-01...5.000e-01 | 32 |  
2.500e-02...5.000e-02 | 15 |  
5.000e+00...+Inf | 0 |  
5.000e+00...6.000e+01 | 0 |  
5.000e-01...1.000e+00 | 1 |  
5.000e-02...1.000e-01 | 8 |  
5.000e-03...1.000e-02 | 9 |  
6.000e+01...+Inf | 0
```

You see, buckets `1.000e-01...2.000e-01` and `1.000e-01...2.500e-01` are overlapping, so do `1.000e-02...2.000e-02` and `1.000e-02...2.500e-02`.
The histogram_quantile assumes that histogram buckets do never overlap each other, only under this condition percentile can be calculated correctly. And this is how https://github.com/victoriaMetrics/metrics should produce the histogram metric. If you're using our lib for metrics in your application then it means our lib has a bug and we should fix it. 
If you're using your own implementation for histograms - please revise it and make sure it won't produce buckets with overlapping ranges.

**Comment by Buddruggy** [comment]
@hagen1778 Thanks so much for your analysis, i checked this data and found overlapping buckets does exist. I will fix my implementation for histograms. Thanks again.
