### ISSUE TITLE
Using vmalert's recording to calculate the cpu idle value, a value greater than 100 appears!

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#4030]
### Is your question request related to a specific component?

vmalert-1.85.3

### Describe the question in detail

![捕获](https://user-images.githubusercontent.com/98309003/228445920-b18d3cb6-8db8-4657-a3ea-8727647440d4.PNG)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @FengZh61 ! Can you get data by [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) and share it? It will help to define values stored in the DB that shows usage of more than 100. Can you explain how you collect data from vmalert?

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! Can you get data by [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) and share it? It will help to define values stored in the DB that shows usage of more than 100. Can you explain how you collect data from vmalert?

groups:
  - name: node.cpu
    interval: 2m
    concurrency: 10000
    rules:
    - record: node_cpu_idle_pct
      expr: (sum(increase(node_cpu_seconds_total{mode='idle'}[4m]))by(ip,job,business_name,business_id))/(sum(increase(node_cpu_seconds_total[4m]))by(ip,job,business_name,business_id))*100


This is my rules for using vmalert recording rules

[idle.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/11097588/idle.txt)

**Comment by dmitryk-dk** [comment]
@FengZh61 ! Thank you for your information, will check it and back soon

**Comment by dmitryk-dk** [comment]
Hi @FengZh61 ! I investigated your question, so how can this happen? I suppose you have distributed system, and when you scrape your metrics the numerator has already been updated, and the denominator has an outdated value. In that case, you see the calculation is over 1 or 100%. How you can fix this problem - just try to add this flag to the vmalert 
```
-datasource.lookback duration
     Lookback defines how far into the past to look when evaluating queries. For example, if the datasource.lookback=5m then param "time" with value now()-5m will be added to every query.
```
and also check this part of the [documentation](https://docs.victoriametrics.com/vmalert.html?highlight=datasource.lookback#data-delay)

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! I investigated your question, so how can this happen? I suppose you have distributed system, and when you scrape your metrics the numerator has already been updated, and the denominator has an outdated value. In that case, you see the calculation is over 1 or 100%. How you can fix this problem - just try to add this flag to the vmalert
> 
> ```
> -datasource.lookback duration
>      Lookback defines how far into the past to look when evaluating queries. For example, if the datasource.lookback=5m then param "time" with value now()-5m will be added to every query.
> ```
> 
> and also check this part of the [documentation](https://docs.victoriametrics.com/vmalert.html?highlight=datasource.lookback#data-delay)

Hi @dmitryk-dk ! I added this parameter
I will give feedback on the results after running for a while

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! I investigated your question, so how can this happen? I suppose you have distributed system, and when you scrape your metrics the numerator has already been updated, and the denominator has an outdated value. In that case, you see the calculation is over 1 or 100%. How you can fix this problem - just try to add this flag to the vmalert
> 
> ```
> -datasource.lookback duration
>      Lookback defines how far into the past to look when evaluating queries. For example, if the datasource.lookback=5m then param "time" with value now()-5m will be added to every query.
> ```
> 
> and also check this part of the [documentation](https://docs.victoriametrics.com/vmalert.html?highlight=datasource.lookback#data-delay)

Hi @dmitryk-dk !
After adding the parameters, the calculation was run for 2 days and the results were OK.
But the calculated time is the last time, -datasource.lookback=2m, calculated at 9:00 minutes, in the query, the recorded time is 8:58, is there a way to solve this situation?

**Comment by dmitryk-dk** [comment]
Hi @FengZh61 ! 
One potential solution is to adjust the `datasource.lookback` parameter to be larger than the time discrepancy you are experiencing. For example, if you are experiencing a 2-minute time discrepancy, you could increase`datasource.lookback` to 4 minutes or more.

If not, you could adjust the time parameter in your queries to compensate for the time discrepancy. For example, if you are experiencing a 2-minute time discrepancy and your query is using now(), you could adjust the query to use now()-2m instead.

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! One potential solution is to adjust the `datasource.lookback` parameter to be larger than the time discrepancy you are experiencing. For example, if you are experiencing a 2-minute time discrepancy, you could increase`datasource.lookback` to 4 minutes or more.
> 
> If not, you could adjust the time parameter in your queries to compensate for the time discrepancy. For example, if you are experiencing a 2-minute time discrepancy and your query is using now(), you could adjust the query to use now()-2m instead.

Hi @dmitryk-dk !
I think I may not have expressed my question clearly.
After I set datasource.lookback=2m, vmalert does the calculation at 9:00, but he writes the data to vm at 8:58.
 I think the time point when it writes to vm should be 9:00.

**Comment by dmitryk-dk** [comment]
Hi @FengZh61 ! your request will be evaluated at `now() - datasource.lookback`, so at 09:00 the query will go at 08:58 and accordingly write a point for this time. This is expected behavior

**Comment by FengZh61** [comment]
> Hi @FengZh61 ! your request will be evaluated at `now() - datasource.lookback`, so at 09:00 the query will go at 08:58 and accordingly write a point for this time. This is expected behavior and this is necessary in the case when the metrics may appear with a delay, and you need to wait for some time before counting the recording

I understand, thanks for the answer, and I wish VictoriaMetrics the best!
Thank you @dmitryk-dk !
