### ISSUE TITLE
is it possible for vmagent to write out-of-order samples while it is being scaled?

### ISSUE THREAD

**Issue by lichuan0620** [VictoriaMetrics/VictoriaMetrics#4038]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Assuming I have a high latency target reporting counter metrics. Scraping it in parallel could lead to out-of-order counter samples and spikes on the graph (I am aware that data exposed in OpenMetrics format comes with timestamps but native Prometheus format does not).

Then, assume I deployed vmagent with multiple shards, and I might scale it up or down.

So here comes my question: while vmagent is scaling, can multiple instances to scrape the same target in parallel? If so, then the out-of-order counter problem can occur, right? How do I avoid this?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
> while vmagent is scaling, can multiple instances to scrape the same target in parallel?

Yes, this is possible.

> If so, then the out-of-order counter problem can occur, right? How do I avoid this?

VictoriaMetrics allows storing data with timestamps being out of order, so this will not be an issue.

But scraping same target by multiple vmagents will produce duplicate data points being stored in the DB. In this case DB must be instructed to do [deduplication](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#deduplication) of ingested data points by setting `-dedup.minScrapeInterval` flag to minimal interval value used for scraping.

Please, note that for cluster version this flag should be set for both `vmselect` and `vmstorage` nodes.

**Comment by lichuan0620** [comment]
I have thought about `-dedup.minScrapeInterval` but I believe there would still be problems. I'll explain.

The problem is not out-of-order timestamps, is data like these:

> example counter data

| timestamp | value |
|:---              |:---     |
|1680148900  |1000  |
|1680148914  |1014  |
|1680148931  |1033  |
|1680148933  |1031  |
|1680148945  |1045  |

The data at t=1680148931 and t=1680148933 are out of order, causing a decreasing counter problem. But VictoriaMetrics or any receiver can't tell because the timestamps are in order. Deduplication can't solve this problem because while 1-second deduplication is acceptable but 10-second is not; there could be high-frequency scrapers out there.

The data is wrong, obviously, and I know that, with OpenMetrics, it is not possible to get this kind of error. But if we are dealing with native Prometheus format in which timestamps are added by scrapers, and pull requests were lagging, then the problematic data described above could very well occur, right?

**Comment by zekker6** [comment]
> The data is wrong, obviously, and I know it is not possible to get this kind of error with OpenMetrics. But if we are dealing with the native Prometheus format in which timestamps are added by scrapers, and if pull requests were lagging, then the problematic data described above could very well occur, right?

Yes, this is possible but in very rare cases. Usually timestams are generated at the beginning scrape processing and all samples captured during scrape get same timestamp assigned. This means that two scrape results will always have timestamps going one after another and counters will also only increment.

Situation with an example data above would only happen in case `/metrics` response would contain already increased data for an earlier timestamp. Effectively the only way for this to happen should be some kind of network delay or delay in processing `/metrics` request by the target. Here is a diagram showing this:
![4038 drawio](https://user-images.githubusercontent.com/1367798/229787078-1b5f2967-9795-4c33-b6ee-4e5d5749b782.png)
Here you can see that request for `t=1680148933` was completed before `t=1680148931` and observed lower counter value. This can happen because of network lag, some kind of queuing mechainsm in between vmagent and application.

Since counters are expected to be incremented monothonically VictoriaMetrics treats this as counter being reset and handled accordingly.
However, VictoriaMetrics has special handling for "partial" counter resets for cases like this since [v1.79.0](https://docs.victoriametrics.com/CHANGELOG.html#v1790):
> BUGFIX: [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html): properly handle partial counter resets when calculating [rate](https://docs.victoriametrics.com/MetricsQL.html#rate), [irate](https://docs.victoriametrics.com/MetricsQL.html#irate) and [increase](https://docs.victoriametrics.com/MetricsQL.html#increase) functions. Previously these functions could return zero values after partial counter resets until the counter increases to the last value before partial counter reset. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2787).

So that in this case it will automatically detect a "partial" reset and will still produce expected query results.

**Comment by lichuan0620** [comment]
so there is no fix for PromQL?

I'd like to propose one but I don't have any good fix on my hands. I'll try to come up with a practical proposal.

**Comment by zekker6** [comment]
It is handled properly since v1.79.0:
> BUGFIX: [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html): properly handle partial counter resets when calculating [rate](https://docs.victoriametrics.com/MetricsQL.html#rate), [irate](https://docs.victoriametrics.com/MetricsQL.html#irate) and [increase](https://docs.victoriametrics.com/MetricsQL.html#increase) functions. Previously these functions could return zero values after partial counter resets until the counter increases to the last value before partial counter reset. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2787.

**Comment by zekker6** [comment]
Closing this as original question have been answered, feel free to reopen if you will have any other questions.

**Comment by pdewilde** [comment]
> 
> VictoriaMetrics allows storing data with timestamps being out of order, so this will not be an issue.
> 

Couldn't find documentation referencing this but was wondering if it holds true for the case of an OTLP datasource providing metrics out-of-order.

Prometheus has `out_of_order_time_window` as an option and was wondering if anything needs to be done to have similar behavior with VM.

**Comment by tiny-pangolin** [comment]
> Couldn't find documentation referencing this but was wondering if it holds true for the case of an OTLP datasource providing metrics out-of-order.

Victoriametrics can handle writing samples out of order for every supported ingestion protocol including OTLP as long as they fall within the retention period https://docs.victoriametrics.com/#backfilling
