### ISSUE TITLE
Vmalert recursive loading directory of rules

### ISSUE THREAD

**Issue by fredrik84** [VictoriaMetrics/VictoriaMetrics#4041]
### Is your feature request related to a problem? Please describe

We want to build a directory structure for alerting that is corresponding to our team structure. To include the rules today we can use `--rule=/etc/alerts.d/*.yaml --rule=/etc/alerts.d/*/*.yaml` to handle "dynamic loading" of rules. This only works thou for a depth of 1 directory, if we create more depth we need to apply more `--rule` arguments manually and if the directories does not exist inbeforehand then vmalert crashes with directory not found.

### Describe the solution you'd like

I would like a recurse rules directory argument

**Comment by zekker6** [comment]
Hi @fredrik84 

https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4148 adds support of loading rules recursively by using the following syntax: `-rule=/etc/alerts.d/**/*.yaml`. This will load all `*.yaml` files in `/etc/alerts.d/` and it's subdirectories.

You can build from sources to test this by using [this](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) instruction, any feedback is much appreciated.

**Comment by fredrik84** [comment]
Hi @zekker6!

Thank you for the quick turnaround. I've tested the build and it does exactly what I wished for. It loads all yaml files in the directory structure.

**Comment by valyala** [comment]
[vmalert](https://docs.victoriametrics.com/vmalert.html) supports recursive globs in `-rule` command-line option starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
