### ISSUE TITLE
What is the connection between github's latest release and docker hub's latest tag?

### ISSUE THREAD

**Issue by electrofloat** [VictoriaMetrics/VictoriaMetrics#4047]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

So, I'm trying to figure out what is the latest version and how to run it.

On github, I can see that the latest tag is:
`https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.89.1`
and running the downloaded binary with `--version` it says:
`victoria-metrics-20230313-021656-tags-v1.89.1-0-g388d6ee16`

Now.. pulling the binary from docker using the latest tag and running it with `--version`, it says:
`victoria-metrics-20230118-091500-heads-public-single-node-0-g2ac530eb2`

So I don't really understand that which latest is the latest and how and when the latest is latest.
Can you please enlighten me? Thanks.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by jiekun** [comment]
close as answered

**Comment by electrofloat** [comment]
Oh I'm sorry.. maybe I forgot to put a question mark to the and of the sentence that's why you think it was answered?

Let me try it again:
"Where exactly on the https://docs.victoriametrics.com/ site stated that the latest tag is not recommended to use, because I could not find it."???????
