### ISSUE TITLE
When vmagent is in cluster mode, if objects are returned in a non-unique order for sd, will collection objects be missed?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4051]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I have some questions about using some kind of xxx_sd_config in vmagent cluster mode to discover objects:

The scene is as follows:

vmagent is started in cluster mode, and different instances use the same crawl configuration:

/path/to/vmagent -promscrape.cluster.membersCount=3 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=0 -promscrape.config=/path/to/config.yml ...
/path/to/vmagent -promscrape.cluster.membersCount=3 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=1 -promscrape.config=/path/to/config.yml ...
/path/to/vmagent -promscrape.cluster.membersCount=3 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=2 -promscrape.config=/path/to/config.yml ...

If some kind of xxx_sd_config returns objects in random order for each call:

When called by the first vmagent for the first time,  return x, y, z
When called by the second vmagent for the second time,  return y, x, z
When called by the third vmagent for the third time,  return y, z, x

For the above scene, my question is as follows:

1、In vmagent cluster mode, what algorithm is vmagent based on each time to select the objects it wants to grab
2、When the order of objects returned by xxx_sd_config is random, is it possible to ensure that all objects can be evenly allocated to different vmagents in the cluster?That is, whether it is possible to achieve three vmagents to obtain x, y, z respectively

These are my questions, I sincerely hope to get a detailed answer.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hi @luzejia.

vmagent uses hash from target labels for shard targets selection, so you don't have to worry about order of objects.
