### ISSUE TITLE
vmctl vm-native doesn't allow multiple filters in --vm-native-filter-match option

### ISSUE THREAD

**Issue by drundusvit** [VictoriaMetrics/VictoriaMetrics#4062]
### Describe the bug

We use **vmctl vm-native** command to perform data migrations and we need to limit the data we copy. We use `--vm-native-filter-match` for that, but it feels like it only accepts one filter while ignoring the provided rest.
For example,
`--vm-native-filter-match='{__name__="http_request_count_total",cluster="kube1"}'`
will limit to metric **http_request_count_total** but not to the specific cluster label the former metric has. 
The tools is expected to migrate only data with the labels specified.

[Slack thread](https://victoriametrics.slack.com/archives/CGZF1H6L9/p1680520763439239)

### To Reproduce

Perform a migration:
./vmctl vm-native --vm-native-src-addr=http://127.0.0.1:8481/select/0/prometheus \
  --vm-native-dst-addr=http://localhost:8428/ \
  --vm-native-filter-match='{\_\_name\_\_="vm_http_request_errors_total", container="vmagent"}' \
  --vm-native-filter-time-start='2023-03-01T00:00:00Z' \
  --vm-native-filter-time-end='2023-03-10T23:59:59Z'

Check data in the dst storage. I must contain only specified data

### Version

victoriametrics/vmselect:v1.89.1-enterprise-cluster

### Additional information

Version of vmutils
vmutils-linux-amd64-v1.89.1-enterprise

**Comment by valyala** [comment]
FYI, this issue has been fixed in [vmctl v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing it then.
