### ISSUE TITLE
In vm cluster mode, big data is inserted as multi-tenant. Compared with single-tenant, can this improve query performance?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4064]
### Is your question request related to a specific component?

VictoriaMetrics cluster mode

### Describe the question in detail

My scenario is as follows:

There are different types of machines such as hosts and virtual machines that need to be collected.
One way is to write all data with the same tenant id.Another way is to write different data with different tenant id.

My problem is as follows:

1.If the data is split by tenant, can the write performance be improved?

Because different data is stored in different tenants than using the same tenant. In this way, the data of each tenant becomes less, will it reduce the use of some indexes and locks, thereby improving performance

2.If the data is split by tenant, can the read performance be improved?

Because different data is stored in different tenants.In this way, the data of each tenant becomes less.
Therefore, when you want to search for a certain type of data, you actually search in the tenant's data collection, not in all data collections.

For example: to search for the cpu usage rate of a certain vm, you only need to search in the data collection of the vm's tenant id, and you don't need to care about the data of the host.

Recently, I intend to migrate a large amount of data from prometheus to vm, and I am in the process of technical selection, hoping to get a detailed answer.Thanks in advance if you can give advice on high availability in production

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @luzejia ! 
Splitting data by tenant can improve your scenario's write and read performance. 
Here's how:

Write Performance: If the data is split by tenant, each tenant's data will be stored separately. This means that when you write data for a specific tenant, you will be writing to a smaller subset of the data, which can improve write performance. Additionally, configure your VictoriaMetrics cluster with multiple nodes and shard the data. Each node will be responsible for storing data for specific tenants, which can further improve write performance.

Read Performance: When you split data by tenant, you can search for specific data in a smaller subset, improving read performance. For example, if you want to search for the CPU usage rate of a certain VM, you only need to search in the data collection of the VM's tenant ID, rather than searching through all the data. This can significantly reduce the amount of data that needs to be searched and improve query response times.

**Comment by luzejia** [comment]
Consistent with what I expected. Thank you very much for your answer, I will use multi-tenancy in production environment.

**Comment by luzejia** [comment]
> Hi @luzejia ! Splitting data by tenant can improve your scenario's write and read performance. Here's how:
> 
> Write Performance: If the data is split by tenant, each tenant's data will be stored separately. This means that when you write data for a specific tenant, you will be writing to a smaller subset of the data, which can improve write performance. Additionally, configure your VictoriaMetrics cluster with multiple nodes and shard the data. Each node will be responsible for storing data for specific tenants, which can further improve write performance.
> 
> Read Performance: When you split data by tenant, you can search for specific data in a smaller subset, improving read performance. For example, if you want to search for the CPU usage rate of a certain VM, you only need to search in the data collection of the VM's tenant ID, rather than searching through all the data. This can significantly reduce the amount of data that needs to be searched and improve query response times.

Consistent with what I expected. Thank you very much for your answer, I will use multi-tenancy in production environment.

**Comment by luzejia** [comment]
> Hi @luzejia ! Splitting data by tenant can improve your scenario's write and read performance. Here's how:
> 
> Write Performance: If the data is split by tenant, each tenant's data will be stored separately. This means that when you write data for a specific tenant, you will be writing to a smaller subset of the data, which can improve write performance. Additionally, configure your VictoriaMetrics cluster with multiple nodes and shard the data. Each node will be responsible for storing data for specific tenants, which can further improve write performance.
> 
> Read Performance: When you split data by tenant, you can search for specific data in a smaller subset, improving read performance. For example, if you want to search for the CPU usage rate of a certain VM, you only need to search in the data collection of the VM's tenant ID, rather than searching through all the data. This can significantly reduce the amount of data that needs to be searched and improve query response times.

hi, https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4129

**Comment by luzejia** [comment]
> Hi @luzejia ! Splitting data by tenant can improve your scenario's write and read performance. Here's how:
> 
> Write Performance: If the data is split by tenant, each tenant's data will be stored separately. This means that when you write data for a specific tenant, you will be writing to a smaller subset of the data, which can improve write performance. Additionally, configure your VictoriaMetrics cluster with multiple nodes and shard the data. Each node will be responsible for storing data for specific tenants, which can further improve write performance.
> 
> Read Performance: When you split data by tenant, you can search for specific data in a smaller subset, improving read performance. For example, if you want to search for the CPU usage rate of a certain VM, you only need to search in the data collection of the VM's tenant ID, rather than searching through all the data. This can significantly reduce the amount of data that needs to be searched and improve query response times.

Hi, I tested the query performance of single-tenant and multi-tenant in the test environment before applying it to the production environment. In fact, it seems that the gap between the two is not very big. Is my testing method wrong?The specific test steps and results are in this [https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4129](isuue 4129), hoping to get guidance

**Comment by luzejia** [comment]
> Hi @luzejia ! Splitting data by tenant can improve your scenario's write and read performance. Here's how:
> 
> Write Performance: If the data is split by tenant, each tenant's data will be stored separately. This means that when you write data for a specific tenant, you will be writing to a smaller subset of the data, which can improve write performance. Additionally, configure your VictoriaMetrics cluster with multiple nodes and shard the data. Each node will be responsible for storing data for specific tenants, which can further improve write performance.
> 
> Read Performance: When you split data by tenant, you can search for specific data in a smaller subset, improving read performance. For example, if you want to search for the CPU usage rate of a certain VM, you only need to search in the data collection of the VM's tenant ID, rather than searching through all the data. This can significantly reduce the amount of data that needs to be searched and improve query response times.

Hi, I tested the query performance of single-tenant and multi-tenant in the test environment before applying it to the production environment. In fact, it seems that the gap between the two is not very big. Is my testing method wrong?The specific test steps and results are in this  [isuue 4129](https://github.com/https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4129) , hoping to get guidance
