### ISSUE TITLE
How to set storage.cacheSizeIndexDBTagFilters and storage.cacheSizexxx ?

### ISSUE THREAD

**Issue by dw130** [VictoriaMetrics/VictoriaMetrics#4065]
### Describe the question in detail

Hi,I use (
    rate(vm_cache_misses_total[$__rate_interval])  /  rate(vm_cache_requests_total[$__rate_interval]) ) > 0

    and catch  indexdb/tagFilters gets very high cache miss ratio
![image](https://user-images.githubusercontent.com/43978442/229796611-c0305b5e-cd5d-40e5-a8dd-099ea37d3a38.png)

-storage.cacheSizeIndexDBTagFilters   -storage.cacheSizeIndexDBDataBlocks and other -storage.cacheSizeXXX is not set
Could you give some advise to set these params?
thanks

I try to set -memory.allowedBytes 45GB -storage.cacheSizeIndexDBTagFilters 1GB -storage.cacheSizeStorageTSID 5GB
But indexdb/tagFilters gets very high cache miss ratio is still very high and  machine memory used is 19%
### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @dw130 ! 

The cache size parameters you set for VictoriaMetrics storage should be proportional to the amount of data being stored and the number of queries being performed. Therefore, it's important to correctly size these caches for optimal performance.

Please note, default cache sizes were carefully adjusted accordingly to the most practical scenarios and workloads. Change the defaults only if you understand the implications and vmstorage has enough free memory to accommodate new cache sizes.
