### ISSUE TITLE
Official Grafana dashboard: change graph unit from seconds to `none` with `CPU cores used` title for the CPU usage graph

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#407]
**Is your feature request related to a problem? Please describe.**
Official Grafana dashboards [for single-node version](https://grafana.com/grafana/dashboards/10229) and [for cluster version](https://grafana.com/grafana/dashboards/11176) contain CPU usage graph, which is calculated as `rate(process_cpu_seconds_total)`. It uses `time (s)` unit, which is quite misleading and hard to understand.

**Describe the solution you'd like**
 It would be better changing the unit to `none` and adjusting the title for this graph as `CPU cores used` in order to make this graph more clear.

**Describe alternatives you've considered**
Use `percent (0 - 1)` unit. IMHO, this is less misleading than `time (s)` unit, but it isn't ideal, since graphs can exceed 100% when multiple CPU cores are used.

**Comment by hagen1778** [comment]
Dashboards were updated:
* https://grafana.com/grafana/dashboards/11176/revisions
* https://grafana.com/grafana/dashboards/10229/revisions
