### ISSUE TITLE
Frequent rollup result cache resets

### ISSUE THREAD

**Issue by andvary** [VictoriaMetrics/VictoriaMetrics#4070]
I'm getting  warnings like this frequently (2-3 times per minute) in my VM instance:
```
2023-04-05T07:15:12.878Z        warn    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:65   resetting rollup result 
cache because the metric XXX (Timestamp=1680674986541, Value=52.000000) has a timestamp older than 
-search.cacheTimestampOffset=5m0s by 3624.459s
2023-04-05T07:15:12.878Z        info    VictoriaMetrics/app/vmselect/promql/rollup_result_cache.go:185  rollupResult cache has
been cleared
```

Could someone please advice what is the rollup result cache for and does resetting it affect performance (or point to the respective piece of documentation)?

Thanks.

**Comment by dmitryk-dk** [comment]
Hi @andvary ! 
This cache includes raw datapoint on the interval.
When you see this warning, your timestamp metric is older than the default value of the cache used for the query. This situation may affect query performance and, in some cases, CPU usage. Increase this value if you see gaps in responses due to time synchronization issues between VictoriaMetrics and data sources.

**Comment by pollynesterovich** [comment]
I get similar errors and even after increasing search.cacheTimestampOffset , the problem remains. Maybe there is another solution?

**Comment by dmitryk-dk** [comment]
Hi @pollynesterovich ! Try to set this flag
```
 -search.disableAutoCacheReset
     Whether to disable automatic response cache reset if a sample with timestamp outside -search.cacheTimestampOffset is inserted into VictoriaMetrics
     ```

**Comment by pollynesterovich** [comment]
Thank you. It works! Do I understand correctly that in this case the cache will not be cleared? Won't it cause other problems?

**Comment by pollynesterovich** [comment]
> Hi @pollynesterovich ! Try to set this flag
> 
> ```
>  -search.disableAutoCacheReset
>      Whether to disable automatic response cache reset if a sample with timestamp outside -search.cacheTimestampOffset is inserted into VictoriaMetrics
> ```
Thank you. It works! Do I understand correctly that in this case the cache will not be cleared? Won't it cause other problems?

**Comment by dmitryk-dk** [comment]
Close as solved
