### ISSUE TITLE
Use of vmalert to alert when the victoria metrics cluster itself is down

### ISSUE THREAD

**Issue by brucelee138** [VictoriaMetrics/VictoriaMetrics#4071]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

We are using Victoria metrics cluster version to monitor our k8s cluster. We are using Ceph as storage backend for the vmstorage. 
At times we have observed that the vmstorage itself not responding (due to ceph issues) to vmselect causing all the alarms to be not triggered as well. So, we thought of adding a new alarm to alert when the vmstorage/vmselect doesnt respond to vmalert.

Is there any way we could use the vmalert to alert when the datasource (vmselect) itself is not available?
Thanks in advance!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by denisgolius** [comment]
Hi!
Maybe https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts-health.yml#L17-L24 is what you looking for?

**Comment by brucelee138** [comment]
@denisgolius Thanks for your suggestion!
But wouldn't these metrics ('up') used for alerting also fetched from vmselect (in turn from vmstorage)?
We would try these out though and provide the results here, thanks!

**Comment by denisgolius** [comment]
> @denisgolius Thanks for your suggestion! But wouldn't these metrics ('up') used for alerting also fetched from vmselect (in turn from vmstorage)? We would try these out though and provide the results here, thanks!

When vmselect/vminsert/vmalert/vmagent can't establish connection to other component - then it will print error in logs.  So you can use logs to understand that something is going wrong and send alerts from something like Loki/ELK/etc. The other way is to use MoM ([monitoring of monitoring](https://victoriametrics.com/blog/victoriametrics-monitoring/)) which is also a good practice.
