### ISSUE TITLE
Graph is incomplete with large time range

### ISSUE THREAD

**Issue by quanvuminh** [VictoriaMetrics/VictoriaMetrics#4073]
### Describe the bug

I'm moving from Prometheus to VictoriaMetrics and running 1 cluster VictoriaMetrics in parallel with my current standalone Prometheus to compare. Query performance of the former is impressive but the plotting experience with Grafana is so bad. Graph usually leaves some blank areas with 6h, 12h time range and worser with 2d, 7d, 30d time range. Same result when plotting in Prometheus UI and VMUI.

### To Reproduce

Setup Prometheus and VictoriaMetrics with same targets. The only different is that I set the scrape interval to 1m in Prometheus and 30s in VictoriaMetrics

### Version

vmselect-20230111-005232-tags-v1.86.0-cluster-0-ga2488f9e2

### Logs

No log

### Screenshots

With VictoriaMetrics datasource
<img width="1995" alt="Screenshot 2023-04-05 at 19 00 53" src="https://user-images.githubusercontent.com/18607902/230074527-6e69d569-9e58-4a42-87a7-c1c8b046a796.png">

Data appears again when zooming in a blank area but still have a blank area at the left side
<img width="1155" alt="Screenshot 2023-04-05 at 21 32 43" src="https://user-images.githubusercontent.com/18607902/230113573-0e0f5d69-a5a2-43fb-b5d7-7ab72f8a1953.png">

With Prometheus datasource
<img width="1995" alt="Screenshot 2023-04-05 at 19 01 03" src="https://user-images.githubusercontent.com/18607902/230074626-a6cbd89b-edba-494b-a60a-cc22aed8af04.png">

### Used command-line flags

            - --cacheDataPath=/cache
            - --storageNode=victoriametrics-vmstorage-0.victoriametrics-vmstorage-inf:8401
            - --storageNode=victoriametrics-vmstorage-1.victoriametrics-vmstorage-inf:8401
            - --storageNode=victoriametrics-vmstorage-2.victoriametrics-vmstorage-inf:8401
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
            - --dedup.minScrapeInterval=30s
            - --search.logSlowQueryDuration=1m

**Comment by dmitryk-dk** [comment]
Hi @quanvuminh ! Try to upgrade your cluster to the newest version, because there was a bug with query results. PLease check [change](https://docs.victoriametrics.com/CHANGELOG.html#v1860) log

**Comment by quanvuminh** [comment]
@dmitryk-dk thank you very much, you saved my OKR!
