### ISSUE TITLE
[Vmalert] Notification in the user interface when a rule is not loaded 

### ISSUE THREAD

**Issue by Lowanski** [VictoriaMetrics/VictoriaMetrics#4076]
### Is your feature request related to a problem? Please describe

I modify my rules file very often but when one of my rules is broken, I can only see the error in the logs. Moreover, in the user interface, nothing tells me that something is wrong after reloading a rule.

### Describe the solution you'd like

It would be nice if I could retrieve the file upload information directly from the Vmalert user interface. For example, in the groups section:	
        - Group 1 (every 60s)                                                                     32 (in greenbox )
	File 1  
	- Group 2 (every 60s)                                                                     32 (in greenbox )
	File 1  
	- Group 2                                                                                          _**Load Failed (in red box)**_ + __*error message*__
	File 2
	…

**Comment by denisgolius** [comment]
> ### Is your feature request related to a problem? Please describe
> 
> I modify my rules file very often but when one of my rules is broken, I can only see the error in the logs. Moreover, in the user interface, nothing tells me that something is wrong after reloading a rule.
> ### Describe the solution you'd like
> 
> It would be nice if I could retrieve the file upload information directly from the Vmalert user interface. For example, in the groups section: - Group 1 (every 60s) 32 (in greenbox ) File 1 - Group 2 (every 60s) 32 (in greenbox ) File 1 - Group 2 _**Load Failed (in red box)**_ + **_error message_** File 2 …
> ### Describe alternatives you've considered
> 
> _No response_
> ### Additional information
> 
> _No response_

Hi @Lowanski !
Thanks for your proposal!
As a workaround for now I recommend to to use vmalert's flag
```bash
  -dryRun
     Whether to check only config files without running vmalert. The rules file are validated. The -rule flag must be specified.
```
and https://github.com/cloudflare/pint .

**Comment by hagen1778** [comment]
Hi @Lowanski!
The config reload starts from parsing the new config update. And on that moment there is no connection between updates and already loaded groups. Moreover, update could contain new groups and how to show their validation problem in UI?

Instead of what you proposed, I suggest to make it simpler and show the last error message received during config reload in vmalert's UI header. It could be implemented as a WARN icon and click/hover on icon would show the error message emitted during last config reload. This would save some time to detect an issue for users.

**Comment by Lowanski** [comment]
Hi @hagen1778!

Thank you for your proposal, it seems good to me and will for sure help users.

**Comment by Lowanski** [comment]
Hi @hagen1778!

Thank you for your proposal, it seems to be a good answer to my issue.

**Comment by valyala** [comment]
[vmalert]https://docs.victoriametrics.com/vmalert.html) should display config reload error in its [web UI](https://docs.victoriametrics.com/vmalert.html#web) starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
