### ISSUE TITLE
vmctl verbose output for docker installations

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#4081]
### Is your feature request related to a problem? Please describe

 Currently, vmctl with docker doesn't provide verbose output and it's hard to identify is it working or not.

### Describe the solution you'd like

 Print out stats for migration every N interval.

**Comment by valyala** [comment]
This feature has been implemented in [vmctl v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing it as done.
