### ISSUE TITLE
what to use for the datasource URL in the grafana dashboard for a vm cluster

### ISSUE THREAD

**Issue by jjone36** [VictoriaMetrics/VictoriaMetrics#4085]
Hi, I'm having a trouble with setting a monitoring dashboard for a vm cluster. 
I successfully set up the components of a vm cluster (vminsert, vmstorage, vmselect and vmagent) 
And I tried to set the dashboard for these as the document explained [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#monitoring).

But I'm a bit confused which URL endpoint I should use for the datasource in grafana. 
Should I use the address to vmagent or vmselect as a datasource? 
If I want to get the metrics from vminsert and monitor it, then what API should I use? 
I'm still confused whether it's possible.. cause there are no API for this according to the doc [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format).

Thank you for your help in advance :)

**Comment by jjone36** [comment]
@denisgolius 

Hi, thank so much you for the comment and all the links.
I put `vmselect` as a data source in Grafana and was able to see the metrics coming in on the dashboard. 
Not configuring the promethues scrape yml file was the main reason of my problem :)

I have a few more questions to ask for help.
First, It's about `vmauth` configuration. I installed `vmauth` but after I replaced `--remoteWrite.url` from `vmselect` to `vmauth`, `vmagent` failed to write/get metrics and I got the error log as follows.
```
2023-04-09T07:19:41.087Z        info    VictoriaMetrics/lib/promscrape/config.go:121    starting service discovery routines...
2023-04-09T07:19:41.088Z        info    VictoriaMetrics/lib/promscrape/config.go:127    started service discovery routines in 0.000 seconds
2023-04-09T07:19:41.091Z        info    VictoriaMetrics/lib/promscrape/scraper.go:427   static_configs: added targets: 10, removed targets: 0; total targets: 10
2023-04-09T07:19:42.079Z        error   VictoriaMetrics/app/vmagent/remotewrite/client.go:400   sending a block with size 15884 bytes to "1:secret-url" was rejected (skipping the block): status code 400; response body: remoteAddr: "10.1.0.216:37210"; requestURI: /; cannot determine targetURL: missing route for ""
2023-04-09T07:19:42.080Z        error   VictoriaMetrics/app/vmagent/remotewrite/client.go:400   sending a block with size 38004 bytes to "1:secret-url" was rejected (skipping the block): status code 400; response body: remoteAddr: "10.1.0.216:37222"; requestURI: /; cannot determine targetURL: missing route for ""
```

This is because there is no url map rule set for `/` root path in the `config.yml` of `vmauth`.
```
- username: "foobar"
  url_map:
  - src_paths:
    - "/api/v1/query"
    - "/api/v1/query_range"
    - "/api/v1/label/[^/]+/values"
    url_prefix:
    - "http://vmselect1:8481/select/42/prometheus"
    - "http://vmselect2:8481/select/42/prometheus"
  - src_paths: ["/api/v1/write"]
    url_prefix: "http://vminsert:8480/insert/42/prometheus"
    headers:
    - "X-Scope-OrgID: abc"
```

I'm not sure what to set for `/` in this case.. 
And is there a more simple way for differentiating a src path, instead of listing all the url formats or using different basic auths for each instance? I think It'd be easier if I can let all urls except for `/api/v1/write` pass to `vminsert`.

And If I want to set no `Basic Auth` to some Urls (ex. to `/` root path), then what the config yml format would be like? 
The `username` and `password` fields can simply be omitted? 

Secondly, I'd also like to use [downsampling](https://docs.victoriametrics.com/#downsampling), but it seems only available on an enterprise version.
I'm using an oss version([v1.89.1-cluster](https://hub.docker.com/layers/victoriametrics/victoria-metrics/v1.89.1/images/sha256-d19e5108624f0b40562b021f9ee4248f0bc30d1d1c4962fe55b6ac204b1dfb77?context=explore)), so would it be not be applicable to me?

Thank you for your help.

**Comment by denisgolius** [comment]
> requestURI: /; cannot determine targetURL: missing route for ""

This error from log is expected behavior if `/` not set in `vmauth` configuration file.

> And is there a more simple way for differentiating a src path, instead of listing all the url formats or using different basic auths for each instance? I think It'd be easier if I can let all urls except for /api/v1/write pass to vminsert.

You can use **Regular expression** to set needed URL but if not feat your case, then please [create a feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/new?assignees=&labels=enhancement&template=feature_request.yml) and describe your needs

> Secondly, I'd also like to use [downsampling](https://docs.victoriametrics.com/#downsampling), but it seems only available on an enterprise version.

Yes, you're right, see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#downsampling .

**Comment by evertonspader-tomtom** [comment]
How would you set up VictoriaMetrics as a datasource in Grafana Cloud since there is no plugin for VictoriaMetrics, only Prometheus? I'm having a hard time getting it to work properly (not seeing metrics) using an URL like `https://<endpoint>:8481/select/0/prometheus`

**Comment by zekker6** [comment]
@dmitryk-dk Could you please take a look?
AFAIK you've been working on examples of integration between Grafana cloud and VictoriaMetrics recently.

**Comment by dmitryk-dk** [comment]
Hi @zekker6 , @evertonspader-tomtom ! I have integrated our VictoriaMetrics Cloud solution with the Grafana Cloud solution.
1. First you should create datasource
<img width="1680" alt="Screenshot 2024-01-16 at 10 35 39" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/59ad03fb-74b3-4d0f-8868-d451d1599ac4">

2. Choose Prometheus as datasource
<img width="1679" alt="Screenshot 2024-01-16 at 10 38 13" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/439cd314-ce19-493a-b464-8656a2444f29">

3. Provide the URL for the VictoriaMetrics datasource. In my example I have used the VictoriaMetrics Cloud generated URL with basic auth

<img width="1678" alt="Screenshot 2024-01-16 at 10 44 49" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/0c075a78-1056-4314-b641-39306a6d61b7">

4. Click Save & test button and you should see the success message
<img width="1678" alt="Screenshot 2024-01-16 at 10 46 15" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/ce4f0eef-8c60-4a3f-8b2f-affe7a59639f">

**Comment by hagen1778** [comment]
A bunch of VictoriaMetrics components have their dashboard published at https://grafana.com/orgs/victoriametrics/dashboards. Each dashboard published has a requirements section in the description.

The dashboards are designed to work with [Prometheus datasource](https://grafana.com/docs/grafana/latest/datasources/prometheus/). The datasource can be configured to query Prometheus or VictoriaMetrics backend.

The source of truth for dashboards is in VictoriaMetrics repo in [dashboards folder](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/dashboards). All the changes are made in github repo first, and then synced to grafana.com.

Each VictoriaMetrics component has `#montoring` section in docs:
* single-node - https://docs.victoriametrics.com/#monitoring
* cluster - https://docs.victoriametrics.com/cluster-victoriametrics/#monitoring
* vmagent - https://docs.victoriametrics.com/vmagent/#monitoring
* vmalert - https://docs.victoriametrics.com/vmalert/#monitoring
* vmauth - https://docs.victoriametrics.com/vmauth/#monitoring

These docs explain how component should be monitored, what dashboard and alerting rules to use, which metrics are the most important.

VictoriaMetrics also has its own [datasource plugin](https://github.com/VictoriaMetrics/grafana-datasource). Dashboards compatible with this plugin are available [here](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/dashboards/vm).

--------------

See examples of deploying and monitoring VictoriaMetrics components [here](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker#docker-compose-environment-for-victoriametrics).
