### ISSUE TITLE
vm-native-filter-time-start does not accept unix timestamps

### ISSUE THREAD

**Issue by damluk** [VictoriaMetrics/VictoriaMetrics#4091]
### Describe the bug

Before the upgrade to 1.90.0, `vm-native-filter-time-start` accepted unix timestamps, in accordance with the cli help output. With 1.90.0 I get
```
failed to parse vm-native-filter-time-start, provided: 1680854393.179, expected format: 2006-01-02T15:04:05Z07:00, error: parsing time "1680854393.179" as "2006-01-02T15:04:05Z07:00": cannot parse "854393.179" as "-"
```

The help text still says:
```
--vm-native-filter-time-start value  The time filter may contain either unix timestamp in seconds or RFC3339 values. E.g. '2020-01-01T20:07:00Z'
```

### To Reproduce

Run `vmctl vm-native --vm-native-filter-time-start <unix-timestamp> ...`

### Version

victoria-metrics-20230407-010036-tags-v1.90.0-0-gb5d18c0d2

**Comment by dmitryk-dk** [comment]
Hi @damluk ! As I understand, your question is about `vmctl`. `vmctl` parses time range flags as 
```golang
start, err := time.Parse(time.RFC3339, p.filter.TimeStart)
	if err != nil {
		return fmt.Errorf("failed to parse %s, provided: %s, expected format: %s, error: %w",
			vmNativeFilterTimeStart, p.filter.TimeStart, time.RFC3339, err)
	}
```
I think we should update flag description

**Comment by valyala** [comment]
The commit e2053baf326b4b75183b2b8a15e1de8c3e9e000d adds support to `vmctl` for the same set of time formats as VictoriaMetrics supports according to [these docs](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#timestamp-formats). This commit will be included in the next release of `vmctl`. In the mean time it is possible to build `vmctl` from this commit according to [these docs](https://docs.victoriametrics.com/vmctl.html#how-to-build) and verify whether it works as expected.

**Comment by valyala** [comment]
[vmctl](https://docs.victoriametrics.com/vmctl.html) supports the same set of time formats at `--vm-native-filter-time-start` and `--vm-native-filter-time-end` command-line flags as VictoriaMetrics does according to [these docs](https://docs.victoriametrics.com/vmctl.html#how-to-build) starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the issue as fixed then.
