### ISSUE TITLE
Error Sort in multi tenant env

### ISSUE THREAD

**Issue by changshun-shi** [VictoriaMetrics/VictoriaMetrics#4094]
### Describe the bug

I find there is a bug when use multi tenant in the latest `VictoriaMetrics` cluster version. the code may works as unexpectedly.
The code is as followed: 
```golang
        sort.Slice(pendingDateMetricIDs, func(i, j int) bool {
		a := pendingDateMetricIDs[i]
		b := pendingDateMetricIDs[j]
		if a.accountID != b.projectID {
			return a.accountID < b.accountID
		}
		if a.projectID != b.projectID {
			return a.projectID < b.projectID
		}
		if a.date != b.date {
			return a.date < b.date
		}
		return a.metricID < b.metricID
	})
```
which is located at line `2123` in golang file `lib/storage/storage.go` in the latest `VictoriaMetrics` cluster version.

the bug is when sort pendingDateMetricIDs, the comparation one should be `a.accountID != b.accountID` but not `a.accountID != b.projectID`. The result is It may not be the expected effect, and it just looks like a mistake.

### To Reproduce

please check the code.

### Version

I have checked the bug exist in all cluster version.

### Screenshots

![image](https://user-images.githubusercontent.com/41324444/230593420-aa8be4df-ab0d-42ee-80ed-3dc1b72fd49e.png)

**Comment by Haleygo** [comment]
> // Sort pendingDateMetricIDs by (accountID, projectID, date, metricID) in order to speed up `is` search in the loop below.
According to the code comments, seems like a bug

**Comment by valyala** [comment]
@changshun-shi , thanks for pointing to the bug! It has been fixed by @Haleygo in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7ee32ed06a586d901a0d31fad91d3f28200d2cfc .
