### ISSUE TITLE
How to use only one vmagent to support multi-tenant writing？

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4098]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I wish to support the following crawls:

    - name: default
      scrape_configs:
        - job_name: victual-host
          static_configs:
            - targets: ['vm-ip:9100']
          remote_write:
            - url: vminsert:8480/insert/0/prometheus
        - job_name: physical-host
          static_configs:
            - targets: ['pm-ip:9100']
          remote_write:
            - url: vminsert:8480/insert/1/prometheus

But at present, it seems that vmagent does not support the following configurations in scrape.conf. If remote.url is specified in the startup parameters, it is global, and it is impossible to set a special url for each job.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hi @luzejia.

VM supports writing data to multiple tenants specified via special labels - see ["Multitenancy via labels" docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy-via-labels). This allows specifying tenant ids via [relabeling](https://docs.victoriametrics.com/vmagent.html#relabeling) and writing multitenant data to a single -remoteWrite.url=http://<vminsert-addr>/insert/multitenant/prometheus/api/v1/write.

**Comment by luzejia** [comment]
> Hi @luzejia.
> 
> VM supports writing data to multiple tenants specified via special labels - see ["Multitenancy via labels" docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy-via-labels). This allows specifying tenant ids via [relabeling](https://docs.victoriametrics.com/vmagent.html#relabeling) and writing multitenant data to a single `-remoteWrite.url=http://<vminsert-addr>/insert/multitenant/prometheus/api/v1/write`.

Hi, this solved my problem. thank you very much for your answer
