### ISSUE TITLE
How to use the vm multi-tenant collection mode in production with higher availability？

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4099]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

At present, what I can think of is to support the collection of vm multi-tenancy in the following ways:

vmagent-cluster-1 -------> collect metrics1 -------> send to vminsert as tenant id 1
vmagent-cluster-1 -------> collect metrics2 -------> send to vminsert as tenant id 2
vmagent-cluster-1 -------> collect metrics3 -------> send to vminsert as tenant id 3

But it feels like it brings complexity in operation and maintenance.
Therefore, I hope to support it in the following ways, but I have not found a way to support it for the time being, and I hope to get an answer:

vmagent-cluster-only-one-------> collect metrics1 -------> send to vminsert as tenant id 1
vmagent-cluster-only-one-------> collect metrics2 -------> send to vminsert as tenant id 2
vmagent-cluster-only-one-------> collect metrics3 -------> send to vminsert as tenant id 3

Is there any more reasonable approach for multi-tenant collection? If you have a more reasonable approach, welcome to discuss how to solve it!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hi @luzejia.
Does the answer from [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4098) not solve your problem?

**Comment by luzejia** [comment]
> 



> Hi @luzejia. Does the answer from [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4098) not solve your problem?

Hi, this solved my problem. thank you!
