### ISSUE TITLE
metric names

### ISSUE THREAD

**Issue by nwies** [VictoriaMetrics/VictoriaMetrics#41]
Hello,
Could it be possible to update the metric names in order to be more compliant to the prometheus rule?
Prometheus team ask to have the exporter name are first part of each metrics to be able to separate everyone of it.
For example, "uptime" is used in nearly every exporter.

If so could you,also update the grafana dashboard?

Thanks a lot

**Comment by valyala** [comment]
@nwies , do you mean internal metric names published by VictoriaMetrics at `/metrics` page? They are already updated in the [latest releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and should contain `vm_` prefix, including the mentioned `uptime` metric - now it is named  `vm_app_uptime_seconds`.

**Comment by nwies** [comment]
hello,

Thanks for the quick reply.
I setup the rpm official repo and I was on an old version.

With the latest release, everything is ok.

Thanks for your help

**Comment by valyala** [comment]
@nwies , rpm is supported by outside contributor - @patsevanton . It looks like the synchronization between [VictoriaMetrics releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and [rpm releases](https://copr.fedorainfracloud.org/coprs/antonpatsev/VictoriaMetrics/) doesn't work properly. @patsevanton , could you address this?

**Comment by patsevanton** [comment]
@nwies 
https://copr.fedorainfracloud.org/coprs/antonpatsev/VictoriaMetrics/
https://github.com/patsevanton/victoriametrics-rpm

**Comment by valyala** [comment]
Thanks!
