### ISSUE TITLE
Is there a way to query the meaning of the metrics exposed by each component of vm itself？

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4110]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I want to get the meaning of the metrics exposed by each component of vm itself.

for example,I get the following metrics from xxxx:8429/metrics:
```
vm_promscrape_push_data_duration_seconds_sum 429798.205059193
vm_promscrape_push_data_duration_seconds_count 1754388309
```

I want to know the detailed difference between these two metrics.

Therefore, I want a method that can query the specific meaning of metrics, just like the explanations of various exporters when exposing metrics,like this:

```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
```

If you have a good way, I hope you can share it with me!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @luzejia 

Currently, VictoriaMetrics does not store those values, so it will not be possible to query these values.

**Comment by luzejia** [comment]
> Hi @luzejia
> 
> Currently, VictoriaMetrics does not store those values, so it will not be possible to query these values.

ok, thanks
