### ISSUE TITLE
In vm cluster mode, the total cpu used by each component of vm is three times that of prometheus. Is this expected?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4114]
### Is your question request related to a specific component?

vmagent，vmstorage，vmselect，vminsert

### Describe the question in detail

Use the same scrape configuration file to configure prometheus and vm, and then compare the performance of both:

## prometheus:
```
sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="map[:prometheus]"}[60s]) )without (mode) > 0
```

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/52991866/231045870-e4882738-d027-4fea-9571-0e1acbd97c74.png">

## victoria metrics:

vmagent
```
sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="map[:vmagent-prod]"}[60s]) )without (mode) > 0
```
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/52991866/231046210-7d29793c-b678-4e23-8a09-94129b30cb0c.png">

vminsert
```
sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="map[:vminsert-prod]"}[60s]) )without (mode) > 0
```

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/52991866/231046344-2930b940-c675-42e5-8fef-204e26560854.png">

vmselect
```
sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="map[:vmselect-prod]"}[60s]) )without (mode) > 0
```

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/52991866/231046401-58e74b2f-35aa-413c-95eb-14f16be948bd.png">

vmstorage
```
sum (rate(namedprocess_namegroup_cpu_seconds_total{groupname="map[:vmstorage-prod]"}[60s]) )without (mode) > 0
```

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/52991866/231046479-d05ff20f-870e-4ae9-819b-d34e249e9d5d.png">

## comparison of the total amount of cpu on both sides:
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/52991866/231046696-97237462-1e09-4ba6-ae1b-9a732269f376.png">

my problem is as follows:
* 1、In the case of collecting the same target, the disk and memory used by vm are much less than prometheus, but the cpu is about 3 times more than prometheus. Is this the expected behavior?
* 2、Is it possible for vm to perform cpu optimization, and I use the default configuration, which causes this problems

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, cluster version has penalty cause of high-availability and uses additional CPU for data transfer between components.

  It's better to compare CPU usage for VictoriaMetrics single node and prometheus.

 Cluster version should be compared with Cortex, Thanos, Mimir or any other multi-node solution.

**Comment by luzejia** [comment]
> Hello, cluster version has penalty cause of high-availability and uses additional CPU for data transfer between components.
> 
> It's better to compare CPU usage for VictoriaMetrics single node and prometheus.
> 
> Cluster version should be compared with Cortex, Thanos, Mimir or any other multi-node solution.

Got it, thank you very much for your answer!
