### ISSUE TITLE
Does the vmselect always mark query resluts as partial when some vmstorage node down?

### ISSUE THREAD

**Issue by kramerli** [VictoriaMetrics/VictoriaMetrics#4115]
### Is your question request related to a specific component?

vmselect vmstorage vminsert

### Describe the question in detail

This is my understanding after reading the doc about cluster availability. Please help to confim if it is right, thanks.

Although victoria metrics support replication, the vmselect does not know the map between datapoints and vmstorage nodes. So the vmselect will always mark query result as partial when vmstorae node down. Even if the data is actually consistent(the node that down does not have replication of the queried data)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @kramerli 

> Does the vmselect always mark query resluts as partial when some vmstorage node down?
> Although victoria metrics support replication, the vmselect does not know the map between datapoints and vmstorage nodes. So the vmselect will always mark query result as partial when vmstorae node down. Even if the data is actually consistent(the node that down does not have replication of the queried data)

Yes, this is correct. Results will always be marked as partial in case some nodes were not available during query execution.

**Comment by zekker6** [comment]
Closing this as original question have been answered, feel free to reopen if you will have other related questions.
