### ISSUE TITLE
custom build of vmstorage panics occasionally

### ISSUE THREAD

**Issue by alexandnpu** [VictoriaMetrics/VictoriaMetrics#4119]
### Describe the bug

vmstorage panics after running a period of time, usually a couple of weeks.

### To Reproduce

N/A

### Version

vmstorage-20220523-072334-v1.77.1-cluster-0-ge736de8

### Logs

below are the first few lines of panic stack

> runtime: pointer 0xcd0008ff00 to unallocated span span.base()=0xcd00080000 span.limit=0xcd0008fd9e span.state=0
> fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)
> 
> runtime stack:
> runtime.throw({0x91fecb?, 0x430dd9?})
>         /usr/local/go/src/runtime/panic.go:992 +0x71 fp=0x7f77b27fbda8 sp=0x7f77b27fbd78 pc=0x43dcd1
> runtime.badPointer(0x7f7609b33120, 0x0?, 0x0, 0x2000?)
>         /usr/local/go/src/runtime/mbitmap.go:368 +0x150 fp=0x7f77b27fbdf8 sp=0x7f77b27fbda8 pc=0x41c4d0
> runtime.findObject(0x7f77b27fbe70?, 0x7f77b27fbe80?, 0x42eda5?)
>         /usr/local/go/src/runtime/mbitmap.go:410 +0xa6 fp=0x7f77b27fbe30 sp=0x7f77b27fbdf8 pc=0x41c666
> runtime.wbBufFlush1(0xc00005e500)
>         /usr/local/go/src/runtime/mwbbuf.go:260 +0xe5 fp=0x7f77b27fbe78 sp=0x7f77b27fbe30 pc=0x438ea5
> runtime.wbBufFlush.func1()
>         /usr/local/go/src/runtime/mwbbuf.go:201 +0x25 fp=0x7f77b27fbe90 sp=0x7f77b27fbe78 pc=0x438ce5
> runtime.systemstack()
>         /usr/local/go/src/runtime/asm_amd64.s:469 +0x49 fp=0x7f77b27fbe98 sp=0x7f77b27fbe90 pc=0x46e149
> 
> goroutine 105423646 [running]:
> runtime.systemstack_switch()
>         /usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc18c807738 sp=0xc18c807730 pc=0x46e0e0
> runtime.wbBufFlush(0x7f7912886e98?, 0x1000?)
>         /usr/local/go/src/runtime/mwbbuf.go:200 +0x6c fp=0xc18c807758 sp=0xc18c807738 pc=0x438d6c
> runtime.wbBufFlush(0xc29fa930d0, 0x0)
>         <autogenerated>:1 +0x2a fp=0xc18c807778 sp=0xc18c807758 pc=0x47272a
> runtime.gcWriteBarrier()
>         /usr/local/go/src/runtime/asm_amd64.s:1669 +0xa3 fp=0xc18c8077f8 sp=0xc18c807778 pc=0x4703e3
> runtime.gcWriteBarrierDX()
>         /usr/local/go/src/runtime/asm_amd64.s:1697 +0x7 fp=0xc18c807800 sp=0xc18c8077f8 pc=0x470467
> github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partSearch).reset(...)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/mergeset/part_search.go:42
> github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*partSearch).Init(...)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/mergeset/part_search.go:61
> github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*TableSearch).Init(0xc246084008, 0xc0cad232c0)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/mergeset/table_search.go:79 +0x251 fp=0xc18c807870 sp=0xc18c807800 pc=0x711eb1
> github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).getIndexSearch(0xc0c69bc300, 0x1, 0x65, 0x6424c036)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/storage/index_db.go:547 +0xa8 fp=0xc18c8078a0 sp=0xc18c807870 pc=0x72dcc8
> github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*indexDB).searchTSIDs(0xc0c69bc300, {0xc096ad4000?, 0x1?, 0xc246082001?}, {0xc11f0d4080?, 0x1?}, 0x493e0, 0x6424c036)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/storage/index_db.go:1760 +0x287 fp=0xc18c807a88 sp=0xc18c8078a0 pc=0x739b07
> github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Storage).searchTSIDs(0xc0000003c0, {0xc096ad4000, 0x1, 0x1}, {0x1?, 0xca4f363c28?}, 0x78fad3?, 0x6424c036)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/storage/storage.go:1186 +0x30b fp=0xc18c807b98 sp=0xc18c807a88 pc=0x76daab
> github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*Search).Init(0xc242148088, 0xc0000003c0, {0xc096ad4000, 0x1, 0x1}, {0xc11f0d4028?, 0x4?}, 0x8?, 0x6424c036)
>         /tmp/build/src/VictoriaMetrics-cluster/lib/storage/search.go:182 +0x14a fp=0xc18c807c38 sp=0xc18c807b98 pc=0x7633aa
> github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).processVMSelectSearch(0xc002854100, 0xc242148000)
>         /tmp/build/src/VictoriaMetrics-cluster/app/vmstorage/transport/server.go:1070 +0x1dc fp=0xc18c807d08 sp=0xc18c807c38 pc=0x78f4dc
> github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).processVMSelectRequest(0xc66d966080?, 0xc242148000)
>         /tmp/build/src/VictoriaMetrics-cluster/app/vmstorage/transport/server.go:496 +0x385 fp=0xc18c807e10 sp=0xc18c807d08 pc=0x78b7c5
> github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).processVMSelectConn(0x1?, 0xcb3399abd0)
>         /tmp/build/src/VictoriaMetrics-cluster/app/vmstorage/transport/server.go:275 +0xca fp=0xc18c807ea0 sp=0xc18c807e10 pc=0x789e2a
> github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).RunVMSelect.func1()
>         /tmp/build/src/VictoriaMetrics-cluster/app/vmstorage/transport/server.go:208 +0x2c5 fp=0xc18c807fe0 sp=0xc18c807ea0 pc=0x789825
> runtime.goexit()
>         /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc18c807fe8 sp=0xc18c807fe0 pc=0x470301
> created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmstorage/transport.(*Server).RunVMSelect
>         /tmp/build/src/VictoriaMetrics-cluster/app/vmstorage/transport/server.go:173 +0x2aa

### Used command-line flags

-retentionPeriod 35d 
-storageDataPath xxxxx

**Comment by f41gh7** [comment]
Hello, could you test it with v1.89.1 version? And It looks like hardware/os error to me.

**Comment by alexandnpu** [comment]
> Hello, could you test it with v1.89.1 version? And It looks like hardware/os error to me.

It is in our production environment, I am afraid  I cannot do the upgrade right now.
I compiled vmstorage using go1.18. I will give go1.20 a try to see if the panic still exists.


BTW, does backwards-incompatible change exist between v1.77.1 and v1.89.1?

**Comment by f41gh7** [comment]
> It is in our production environment, I am afraid I cannot do the upgrade right now.
I compiled vmstorage using go1.18. I will give go1.20 a try to see if the panic still exists.

 It could be an issue. I recommend to use only Makefile commands for compiling binaries. Since possible bugs at local C compiler may be a source of memory corruption. VictoriaMetrics uses docker with musl for compiling C code.

> BTW, does backwards-incompatible change exist between v1.77.1 and v1.89.1?

 There is no such changes. But API version for communication protocol between vmselect and vmstorage components changed. And during upgrade you may see query fails.

**Comment by alexandnpu** [comment]
> > It is in our production environment, I am afraid I cannot do the upgrade right now.
> > I compiled vmstorage using go1.18. I will give go1.20 a try to see if the panic still exists.
> 
> It could be an issue. I recommend to use only Makefile commands for compiling binaries. Since possible bugs at local C compiler may be a source of memory corruption. VictoriaMetrics uses docker with musl for compiling C code.

aha, I never know VM uses musl before you mention it. I will also give musl a try and do a statically-linked build.

> > BTW, does backwards-incompatible change exist between v1.77.1 and v1.89.1?
> 
> There is no such changes. But API version for communication protocol between vmselect and vmstorage components changed. And during upgrade you may see query fails.

I hope new releases can make the upgrade more smooth by supporting backwards-compatible

**Comment by jiekun** [comment]
Close as answered
