### ISSUE TITLE
Influxdb query 

### ISSUE THREAD

**Issue by Razikus** [VictoriaMetrics/VictoriaMetrics#4141]
### Is your question request related to a specific component?

How to do inlfuxdb query on top of VM?

### Describe the question in detail

How to do inlfuxdb query on top of VM? Is that even possible? Is there anything that can leverage this function?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @Razikus ! VictoriaMetrics doesn't support influxdb query language. The only way to query data from VictoriaMetrics is using [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html). You can rewrite your influxql queries to MetricsQL. Please check some additional information from this part of the [documentation](https://docs.victoriametrics.com/guides/migrate-from-influx.html#migrate-from-influxdb-to-victoriametrics)

**Comment by Razikus** [comment]
Thank you very much!

**Comment by dmitryk-dk** [comment]
Close as reloved!
