### ISSUE TITLE
Could you please add VMalert linter

### ISSUE THREAD

**Issue by AmandeepSaxena** [VictoriaMetrics/VictoriaMetrics#4147]
### Is your feature request related to a problem? Please describe

I tried using prom tool but there are few edge case that are not being caught by that. For ex: Value= {{ $ value }}" (this is wrong as their should not be space between $ and value) such cases are passing fine with promtool. 
Can we please have VMalert linter? 

### Describe the solution you'd like

VMalert linter can lint and save us from getting vmalerts alert rule errors. `2021-07-23T09:15:37.127Z	error	VictoriaMetrics/app/vmalert/main.go:269	cannot parse configuration file: errors(2): invalid group "Attachment Validation Failures greater than 3" in file "/config/vp_rules.yaml": invalid annotations for rule "Attachment Validation Failures greater than 3"."[xxx] - [More than 3 attachments validation failed]": errors(1): key "description", template "<!subteam^S01R98ZHUF5> Number of attachments failed due to {{ $labels.reason }} is {{ $ value }}": error evaluating annotation template: template: :1:152: executing "" at <$>: can't give argument to non-function $`

**Comment by denisgolius** [comment]
Hey @AmandeepSaxena please refer [#4076](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4076#issuecomment-1498519746)

**Comment by hagen1778** [comment]
Rules can be validated via [vmalert-tool](https://docs.victoriametrics.com/vmalert-tool/index.html). It will perform the following actions:
- sets up an isolated VictoriaMetrics instance;
- simulates the periodic ingestion of time series;
- queries the ingested data for recording and alerting rules evaluation like [vmalert](https://docs.victoriametrics.com/vmalert/);
- checks whether the firing alerts or resulting recording rules match the expected results.
