### ISSUE TITLE
What is the vmstorage data deletion mechanism?

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#4150]
### Describe the question in detail

 -retentionPeriod parameter is the default, the actual data has been stored for 49 days and has not been cleared

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @FengZh61 ! Thank you for your question. Can you check this part of the [documentation](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html?highlight=if%20-retentionPeriod%20is%20set%20to%201,%20data%20for%20January%20is%20deleted%20on%20March%201st.#retention)
