### ISSUE TITLE
Does vmalert have a plan to support the editing of alert rules in the ui?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4151]
### Describe the solution you'd like

I would like to know if there is any plan to support the editing of rules in the ui provided by vmalert in the future, currently it is only displayed.

My scenario is as follows:
Our monitoring department provides a unified alarm service for other teams, but this configuration currently relies on manually configuring the yaml file. I hope that if vmalert can provide the ability to edit rules in the ui in the future, colleagues in each department can go to the ui by themselves. Configure the alarm rules you want in it

**Comment by dmitryk-dk** [comment]
Hi @luzejia ! Thank you for your proposition. We will discuss does this feature request would be helpful

**Comment by luzejia** [comment]
> Hi @luzejia ! Thank you for your proposition. We will discuss does this feature request would be helpful

ok, I am very much looking forward to the result of your discussions.

**Comment by dmitryk-dk** [comment]
HI @luzejia ! We have a similar feature request, please check this [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/520)

**Comment by luzejia** [comment]
> HI @luzejia ! We have a similar feature request, please check this [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/520)

ok,thankyou!
