### ISSUE TITLE
VictoriaMetrics cluster mode: No data  after write data 

### ISSUE THREAD

**Issue by nl594** [VictoriaMetrics/VictoriaMetrics#4158]
### Is your question request related to a specific component?

VictoriaMetrics cluster mode

### Describe the question in detail

VictoriaMetrics cluster mode: After writing data, I can't query the data for the last hour, but I can query the data for the last 6 hours, which includes the last hour's data. Why is this happening?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by nl594** [comment]
VictoriaMetrics components was v1.78.0 , now id upgrad to v1.90.0 ,  this question is gone.

**Comment by zekker6** [comment]
Going to close this as resolved, feel free to reopen if issue will become reproducible.
