### ISSUE TITLE
VMBackup S3 Storage class

### ISSUE THREAD

**Issue by justcompile** [VictoriaMetrics/VictoriaMetrics#4164]
### Describe the solution you'd like

The ability to specify which storage class objects use when they are uploaded to S3. Specifying a non-default storage class reduces cost :) 

### Describe alternatives you've considered

It is possible to use Lifecycle rules in S3 to transition the storage class, but this in itself incurs cost, plus objects cannot be transitioned until after 30 days which, dependent on retention policy, may be redundant

**Comment by valyala** [comment]
The `-s3StorageClass` command-line flag is available at [vmbackup](https://docs.victoriametrics.com/vmbackup.html) starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
