### ISSUE TITLE
A promql query one point data, get 4 same data

### ISSUE THREAD

**Issue by nl594** [VictoriaMetrics/VictoriaMetrics#4165]
### Is your question request related to a specific component?

![image](https://user-images.githubusercontent.com/23700054/233543301-f229f3dd-61ea-4657-9bed-015db964e93c.png)

### Describe the question in detail

just one point data，get 4 same data
and VictoriaMetrics components is v1.90.0
### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @nl594 ! I have tested on my local, and I got only one point if one sender sends this point
<img width="1675" alt="Screenshot 2023-04-21 at 10 14 13" src="https://user-images.githubusercontent.com/12189570/233567059-0b402dae-98e0-45d2-8954-fd03924d4b4a.png">

But if simultaneously different sender write to VM the same point, you will see four same points
 
<img width="1680" alt="Screenshot 2023-04-21 at 10 15 30" src="https://user-images.githubusercontent.com/12189570/233567333-90b0dff4-d01a-48f1-ab0e-e7923b7be35b.png">

**Comment by dmitryk-dk** [comment]
Close as inactive
