### ISSUE TITLE
How to rename a label

### ISSUE THREAD

**Issue by Razikus** [VictoriaMetrics/VictoriaMetrics#4167]
### Is your question request related to a specific component?

Hello guys

Can i relabel existing label?

Basically i have a label xx.bb.cc and i want to rename the entire label to bb.cc.dd

Is that possible with API or something?

Victoria Metrics is super project by the way

### Describe the question in detail

Hello guys

Can i relabel existing label?

Basically i have a label xx.bb.cc and i want to rename the entire label to bb.cc.dd

Is that possible with API or something?

Victoria Metrics is super project by the way

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Razikus** [comment]
Important thing - i want to rename after some time, not on injestion
So in this case relabellin on ingestion will not work

**Comment by dmitryk-dk** [comment]
Hi @Razikus ! You can't do it via API if the metric is already saved to the storage. But you can use the MetricsQL function, which helps you to change any metric name and label.
One of the excellent functions is [label_replace](https://docs.victoriametrics.com/MetricsQL.html#label_replace). With this function, you can manipulate any label which you need.

**Comment by Razikus** [comment]
oh no...
there is not ANY option to do that on storage level?
label replace function is not enough, because my particular case is that i want to use graphite source not promql :(

**Comment by dmitryk-dk** [comment]
Another option is to migrate this metric via vmctl and use relabeling on the vmagent side. But this approach is quite complicated. You should configure vmagent with relabel config, and vmctl can read from storage and send data to vmagent where ralebel config will be applied. After that vmagent will send those metric to the storage.

**Comment by Razikus** [comment]
but i want to relabel on particular event

so if upstream will send me info that some infrastructure changes happened i want to change metric name to reflects that

**Comment by dmitryk-dk** [comment]
Yes, this is a similar issue. So label values can be modified before being written into VictoriaMetrics.

**Comment by Razikus** [comment]
can i delete all particular labels somehow?
and add again

**Comment by Razikus** [comment]
label replace function is not somethig that i can use with graphite compatible api

**Comment by dmitryk-dk** [comment]
Another possible solution can be (but it is not very good):
1. Export  data via api/v1/export;
2. Change whatever you want in the data what you exported
3. Import that changed data via /api/v1 import
4. Delete previous metric via /api/v1/admin/tsdb/delete_series
Please check this part fo the documentation [https://docs.victoriametrics.com/guides/guide-delete-or-replace-metrics.html#how-to-update-metrics](url)

**Comment by dmitryk-dk** [comment]
Close as resolved

**Comment by tredondo** [comment]
@dmitryk-dk thanks for linking to the workaround. However there's a fundamental problem with performing a simple conceptual operation as renaming a label, via this series of steps. The export→modify→import→delete workflow is inherently unsafe for production data.

1. The `/api/v1/import` endpoint returns `204 No Content` on success, and also returns nothing useful on partial failure. There is no way to know if all data was imported. I filed #2420 four years ago.

2. The guide says to delete *after* importing, but provides no verification step. If the import silently loses data (as mine did), the subsequent delete destroys the only copy.

3. Documentation these days is also read by AI agents, and complexity increases the chance for mistake. My agent attempted to skip the intermediate file step, and use piping. That led to a cascade of errors and data loss. The more steps in the pipeline, the more ways it can silently fail.

#### Proposal: native `POST /api/v1/admin/tsdb/rename_label` endpoint

Atomically renames a label name or value in-place, without requiring an export→reimport→delete cycle. Something like:

```
POST /api/v1/admin/tsdb/rename_label
  match[]={symbol="old value"}
  label=symbol
  value=new value
```

Every TSDB user eventually needs to rename a label to fix a typo, change a naming convention, migrate symbology etc.

I understand that a fully atomic server-side rename is architecturally difficult. How about going half way, for example, an endpoint that copies series with label transformations applied, so the original is never touched until the user explicitly deletes it after verification?

**Comment by makasim** [comment]
Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9019

**Comment by dmitryk-dk** [comment]
Hi @tredondo ! Your question was discussed and here is some of the decision
In summary, we do not want to modify the stored data through an update API, because doing so is expensive and alters the source data, which can make debugging and troubleshooting more difficult.
Instead, the current proposals focus on applying transformations at query time, allowing the original data to remain the source of truth:
Support in MetricsQL, as proposed in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3992
Support in vmselect, as proposed in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9019
The first approach is safer because all transformation logic must be defined explicitly in the query. However, this can become inconvenient if users do not want to update their existing expressions — for example, when renaming a label, adding a new label, or handling a large number of changes.
The second approach avoids the need to modify expressions and could offer greater flexibility depending on the supported syntax. However, there is currently no well-defined use case that clearly specifies the required functionality.

Please keep tracking the issue was mentions.

Tank you for your question.
