### ISSUE TITLE
Let VM or vmagent round incoming data timestamps  to custom precision.

### ISSUE THREAD

**Issue by yuyutime** [VictoriaMetrics/VictoriaMetrics#417]
Quite often data ingested by VM from influx line protocol has millisecond or higher precision while timestamps rounded to seconds would be more than enough in many use cases. This prevents better compression and leads to unnecessary grows of storage space usage.

In my use case I have telegraf influxdb output data feed to VM and I didn't find a sane way to configure telegraf to send timestamps withous milliseconds.

**Suggestion**
It would be nice to introduce an optional `minTimeResolution` flag to set required custom timestamp precision for input data with values like `1s`, `100ms`, `1ms` and let VM or vmagent round (or truncate) incoming timestamps to this precision.

For VM it can be a global flag affecting all timeseries in VM instance. It may be not applicable if VM accepts data mix with multiple procisions.

For vmagent it can implement a more fine-grained approach, for example with regex filters for metrics name or labels. Or user can just run several instances of vmagent.

**Comment by valyala** [comment]
This has been already done in the following commits:
* single-node version: e62afc7366fdeba69849424bc7ae5815c208531b
* cluster version: 661cfb03e26d40ff1ba99a3446869d688a66d903

These commits will be included in the next release.

Now VictoriaMetrics accepts the following flags for trimming timestamps in the ingested data via various ingestion protocols:
* `influxTrimTimestamp` for [Influx line protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf)
* `graphiteTrimTimestamp` for [Graphite protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-send-data-from-graphite-compatible-agents-such-as-statsd)
* `opentsdbTrimTimestamp` for [OpenTSDB telnet protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#sending-data-via-telnet-put-protocol)
* `opentsdbhttpTrimTimestamp` for [OpenTSDB http protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#sending-opentsdb-data-via-http-apiput-requests)
* `csvTrimTimestamp` for [CSV protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-import-csv-data)

Example:

`/path/to/victoria-metrics ... -influxTrimTimestamp=1s` would trim timestamps for incoming Influx line protocol data to 1 second.

**Comment by valyala** [comment]
The `*TrimTimestamp` flags mentioned above are available starting from [v1.34.8](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
