### ISSUE TITLE
Upper bound of -memory.allowedPercent

### ISSUE THREAD

**Issue by zouxiang1993** [VictoriaMetrics/VictoriaMetrics#4171]
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/05ab34f2c8b536c5cb98e2686602726fbe59f0f2/lib/memory/memory.go#L36

Maybe the upper bound of *-memory.allowedPercent* should be 100 ?

**Comment by valyala** [comment]
@zouxiang1993 , thanks for raising this question!

Yeah, the upper bound for the `-memory.allowedPercent` command-line flag should be 100. This has been fixed in [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html).
