### ISSUE TITLE
Create a command-line tool for ad-hoc querying of VictoriaMetrics

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#418]
**Is your feature request related to a problem? Please describe.**
Sometimes users want performing ad-hoc queries for VictoriaMetrics. This is cumbersome to do now with `curl` or `wget` tools, since it is hard to properly escape query args.

**Describe the solution you'd like**
It would be great to have an interactive command-line tool for ad-hoc querying of VictoriaMetrics. The tool should support [readline](https://en.wikipedia.org/wiki/GNU_Readline) for quick auto-completion, navigation and editing of the previous queries.

**Describe alternatives you've considered**
See https://github.com/prometheus-junkyard/prometheus_cli . This tool isn't interactive :(

**Comment by hagen1778** [comment]
Looks like VMUI now covers this request - see https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#vmui
