### ISSUE TITLE
VMAuth should return generic information about incorrect credentials

### ISSUE THREAD

**Issue by JooKop** [VictoriaMetrics/VictoriaMetrics#4188]
### Is your feature request related to a problem? Please describe

There already exists a flag `-logInvalidAuthToken` for `vmauth` if one does not want to log incorrect tokens in the vmauth log. However, vmauth still includes the base64 encoded wrong credentials in its response to the client.

In this case, a misconfigured client might output the slightly typoed credentials to its own log, or there could be some service in the middle (in insecure networks) sniffing the packets.

### Describe the solution you'd like

We already have the `-logInvalidAuthToken` option, so in our opinion it would be nice to have also `-respondInvalidAuthToken` flag (and defaulting to false).

The default response if `-respondInvalidAuthToken` is not set could be just `invalid user credentials`. As far as I know, this is the recommended security practice anyway.

### Additional information

Currently getting this as a response when I have a slight typo in the username:
```
vmauth version: vmauth-20230313-024014-tags-v1.89.1-enterprise-0-g1b332616b

curl --user usernametypo:realpassword https://vmauth-url/select/0/prometheus/api/v1/status/tsdb
cannot find the provided auth token "Basic dm0lFYThIQ2c4bQ==" in config
```

**Comment by f41gh7** [comment]
related PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4190

**Comment by valyala** [comment]
The commit 16df18ec14db9f8bbde43c1a084ab6effa846ff5 should fix the issue with exposing incorrect credentials in vmauth response. This commit will be included in the next release. In the mean time it is possible to build `vmauth` from this commit according to [these docs](https://docs.victoriametrics.com/vmauth.html#how-to-build-from-sources) and verify whether it works as expected.

**Comment by valyala** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth.html) should stop returning incorrect credentials in the response starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the issue as fixed.

**Comment by valyala** [comment]
The bugfix has been backported to [v1.87.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.6).
