### ISSUE TITLE
promscrape.* command-line flags for VM?

### ISSUE THREAD

**Issue by Allineer** [VictoriaMetrics/VictoriaMetrics#419]
**Describe the bug**

The `victoria-metrics-prod -help` command output fragment:

```
  -promscrape.config string
  -promscrape.config.strictParse
  -promscrape.disableCompression
  -promscrape.fileSDCheckInterval duration
  -promscrape.kubernetesSDCheckInterval kubernetes_sd_configs
  -promscrape.maxScrapeSize int
 ```

This flags are related to `vmagent` only. Isn't?

**Version**

`victoria-metrics-20200415-095208-tags-v1.34.8-0-gccb887c0`

**Comment by valyala** [comment]
Single-node VictoriaMetrics supports scraping Prometheus metrics - see [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-scrape-prometheus-exporters-such-as-node-exporter) for details. The `-promscrape.*` flags are needed for enabling scraping for Prometheus exporters.

**Comment by Allineer** [comment]
Wow. Thanks.
