### ISSUE TITLE
Specify warning message if `--remoteWrite.maxDiskUsagePerURL` flag set lower than 500MB

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4195]
### Is your feature request related to a problem? Please describe

vmagent uses a persistent queue to save data  If the remote storage is unavailable. In that case, all the collected metrics are buffered at `-remoteWrite.tmpDataPath`. The buffered metrics are sent to remote storage as soon as the connection to the remote storage is repaired. The maximum disk usage for the buffer can be limited with `-remoteWrite.maxDiskUsagePerURL`. But buffered data is stored in ~500MB chunks, and it is unclear if the user specifies this flag, for example to 100MB and persistent queue growth to ~500MB

### Describe the solution you'd like

Updated documentation with better flag descriptions and show a warning message if the user specified flag `--remoteWrite.maxDiskUsagePerURL` lower than 500MB

**Comment by valyala** [comment]
`vmagent` should emit a warning message during startup if it receives too small value for the `-remoteWrite.maxDisckUsagePerURL` command-line flag starting from the commit bc17f4828c8f9d0fa073033a0ff7863921a60f43 . This commit will be included in the next release.

**Comment by valyala** [comment]
`vmagent` should emit a warning when too small value is passed to `-remoteWrite.maxDiskUsagePerURL`, starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
