### ISSUE TITLE
writeconcurrencylimiter is useless when using the opentsdbhttp protocol

### ISSUE THREAD

**Issue by zouxiang1993** [VictoriaMetrics/VictoriaMetrics#4204]
### Describe the bug

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/041e188df856ddfc80477d73b73c2a26c901aefb/lib/protoparser/opentsdbhttp/stream/streamparser.go#L33-L36

Maybe we should use *wcr* in *line 36* instead of *req.Body* ?

### To Reproduce

None

### Version

vminsert-20230407-011334-tags-v1.90.0-cluster-0-g64cf8fe49

**Comment by valyala** [comment]
VictoriaMetrics and vmagent should properly take into account `-maxConcurrentInserts` command-line flag when ingesting the data via [OpenTSDB http protocol](https://docs.victoriametrics.com/#sending-opentsdb-data-via-http-apiput-requests) starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by valyala** [comment]
The bugfix has been backported to [v1.87.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.6).
