### ISSUE TITLE
High cpu usage and panic

### ISSUE THREAD

**Issue by imroc** [VictoriaMetrics/VictoriaMetrics#4207]
### Describe the bug

High cpu usage, panic and exit, restarted several times and then recovered by itself

### To Reproduce

Unknown

### Version

```bash
$ /victoria-metrics-prod --version
victoria-metrics-20230407-010518-tags-v1.90.0-0-gb5d18c0d2
```

### Logs

Restart Count:  9

I can only get the last previous log:

[victoria.log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/11339163/victoria.log)

### Screenshots

High cpu usage, and time matches the last previous log (UTC 2023-04-26T21:59)

grafana time zone is UTC+8:00:

![image](https://user-images.githubusercontent.com/7448852/234748698-a73ecf62-f122-4c4b-95fa-ef19d63ddac4.png)

The above is the overall cpu usage of the machine where victoria is running at(percentage), and the following is the cpu usage of the victoria container(cpu cores, total 2c). 

Some data point is missing due to high cpu usage.

### Used command-line flags

```bash
/victoria-metrics-prod -promscrape.config=/etc/prometheus/promscrape-config.yaml -storageDataPath=/data/victoria-metrics-data -retentionPeriod=1w -retentionTimezoneOffset=8h -selfScrapeInterval=15s
```

### Additional information

The running environment is my home router, 2c8g.

**Comment by zekker6** [comment]
Hi @imroc 

Could you try building VictoriaMetrics [from sources](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-build-from-sources) in [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4206) and check if it helps?
Seems like @faceair did found an issue causing IndexDB rotation in infinite loop which is exactly what happened in this case according to the shared logs.

**Comment by imroc** [comment]
> Hi @imroc
> 
> Could you try building VictoriaMetrics [from sources](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-build-from-sources) in [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4206) and check if it helps? Seems like @faceair did found an issue causing IndexDB rotation in infinite loop which is exactly what happened in this case according to the shared logs.

But I don't know how to reproduce it, It happened to me after 2 weeks of running `v1.90.0`:

```bash
❯ kubectl get pod
NAME                  READY   STATUS    RESTARTS      AGE
victoria-7vlb9        1/1     Running   9 (13h ago)   14d
```

**Comment by zekker6** [comment]
@imroc It should have happened when there was an indexdb rotation scheduled which is once per `retentionPeriod`. Could you set up another VictoriaMetrics instance and set retention to some shorter value and see if an same will occur?

**Comment by faceair** [comment]
It is easy to determine whether this issue is related to the problem I fixed.

```
package main

import (
	"log"
	"time"
)

const (
	msecPerDay                   = 24 * 3600 * 1000
	retentionTimezoneOffsetMsecs = 8 * 3600 * 1000
	msecPerWeek                  = 7 * msecPerDay
)

func main() {
	tz, _ := time.LoadLocation("Asia/Shanghai")

	// 03:58
	t := time.Date(2023, 4, 27, 3, 58, 0, 0, tz)
	log.Printf("t: %d, nextRetentionDuration: %s", t, nextRetentionDuration(t.UnixMilli(), msecPerWeek))

	// 04:01
	t = time.Date(2023, 4, 27, 4, 1, 0, 0, tz)
	log.Printf("t: %d, nextRetentionDuration: %s", t, nextRetentionDuration(t.UnixMilli(), msecPerWeek))

	// 06:00
	t = time.Date(2023, 4, 27, 6, 0, 0, 0, tz)
	log.Printf("t: %d, nextRetentionDuration: %s", t, nextRetentionDuration(t.UnixMilli(), msecPerWeek))

	// 08:02
	t = time.Date(2023, 4, 27, 8, 2, 0, 0, tz)
	log.Printf("t: %d, nextRetentionDuration: %s", t, nextRetentionDuration(t.UnixMilli(), msecPerWeek))
}

// Implementation of nextRetentionDuration in previous versions.
func nextRetentionDuration(t, retentionMsecs int64) time.Duration {
	// Round retentionMsecs to days. This guarantees that per-day inverted index works as expected.
	retentionMsecs = ((retentionMsecs + msecPerDay - 1) / msecPerDay) * msecPerDay
	deadline := ((t + retentionMsecs - 1) / retentionMsecs) * retentionMsecs
	// Schedule the deadline to +4 hours from the next retention period start.
	// This should prevent from possible double deletion of indexdb
	// due to time drift - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/248 .
	deadline += 4 * 3600 * 1000
	// The effect of time zone on retention period is moved out.
	// See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2574
	deadline -= retentionTimezoneOffsetMsecs
	return time.Duration(deadline-t) * time.Millisecond
}
```

**Comment by valyala** [comment]
The bug with infinite loop at `indexdb` rotation time should be fixed in [VictoriaMetrics v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue then.

@imroc , feel free re-opening the issue if it still persists on `v1.91.0` in your environment.

**Comment by valyala** [comment]
The bugfix has been backported to [v1.87.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.6).

**Comment by pyfdtic** [comment]
@valyala  we meet the same error in our vm cluster, version 1.89.1 , but after we restart the vmstorage , monitor data before we restart cannot be search (new data can be search). the data file are still on disk . any idea why this happend ? and is there any thing i can do to make the old data retrievable ?
