### ISSUE TITLE
vmui: notify user that expression didn't match any time series

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4211]
### Is your feature request related to a problem? Please describe

With https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3925 it is now possible to detect whether the query matches any time series during execution. Would be nice if vmui could notify user about such situations.

### Describe the solution you'd like

Pobably a small notification icon next to query field which would pop-up after the execution. The icon could have a tooltip which explains what happened. Similarly to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4039

**Comment by valyala** [comment]
[vmui](https://docs.victoriametrics.com/#vmui) shows a notification icon if the query doesn't match any time series in the database, starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this example at VictoriaMetrics playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=count%28non_existing_metric%29&g0.range_input=30m&g0.end_input=2023-05-18T23%3A55%3A26&g0.relative_time=last_30_minutes).

Closing the feature request as done.
