### ISSUE TITLE
Label cardinality

### ISSUE THREAD

**Issue by nevlkv** [VictoriaMetrics/VictoriaMetrics#4213]
### Is your feature request related to a problem? Please describe

In previos releases cardinality dashboard was with section Top labels with unique values

In 1.90.0 it was droped and labels with huge unique values i can see only  from top of timeseries metrics, **but its wrong**

**Timseries with top of values may not have  labels with huge unique values**

### Describe the solution you'd like

need old dashboard with global labels values statictics

**Comment by valyala** [comment]
The `Labels with the highest number of unique values` table has been returned to [cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer) in [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). See [this example from VictoriaMetrics playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality?date=2023-05-18). Closing the issue as fixed.
