### ISSUE TITLE
Add snapshot logic to vmbackup

### ISSUE THREAD

**Issue by allen13** [VictoriaMetrics/VictoriaMetrics#422]
**Is your feature request related to a problem? Please describe.**
Currently vmbackup requires a pre-existing snapshot to exist before running. 

**Describe the solution you'd like**
Be able to snapshot and backup in a single container run. This would make it possible to run vmbackup as a kubernetes CronJob that continually keeps data backed up. It would be nice if this functionality was integrated into vmbackup. Would be interested in doing the change myself if there is interest.

**Describe alternatives you've considered**
One possibility would be to run a bash script that does the snapshot then runs vmbackup. Unfortunatley, the current container is `FROM scratch` so all scripting is out of the question. This necessitates building a custom container with the the necessary utilities.

If the vmbackup container was built with alpine instead of scratch I would consider this issue resolved.

**Additional context**
Building a custom container isn't hard in most situations. However, when working within the walls of an enterprise every binary and container must be reviewed, scanned, and then repackaged with a controlled release process.

**Wish List**
All vm cluster binaries packaged in a single container image based on any image that has basic scripting utilities.

**Comment by valyala** [comment]
It would be great to have the ability to call [snapshot api](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-work-with-snapshots) from [vmbackup](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md)!

> Would be interested in doing the change myself if there is interest.
This sounds great!

> All vm cluster binaries packaged in a single container image based on any image that has basic scripting utilities.

I think it would be nice to have a separate Makefile rules for building Docker containers from `alpine` or similar base images instead of `scratch`. Then these images could be published on next releases alongside the images based on `scratch`. Could you look into this possibility?

**Comment by allen13** [comment]
Great! We should have something implemented by next week.

**Comment by valyala** [comment]
FYI, now it should be easier to build docker images on top of base image other than `scratch` - just pass the base image to `ROOT_IMAGE` environment variable when building docker image. See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#building-docker-images) for details. Probably, this should be enough for writing a custom shell script for making snapshots via snapshot API.

**Comment by allen13** [comment]
Thanks @valyala! We got the PR for the golang side of things as well.

**Comment by allen13** [comment]
Once this feature has been released would you like a backup cronjob to be added to the helm charts @valyala ?

**Comment by valyala** [comment]
> Once this feature has been released would you like a backup cronjob to be added to the helm charts?

I think this will be great contribution. Please, coordinate it with @tenmozes , the maintainer of [helm-charts repository for VictoriaMetrics](https://github.com/VictoriaMetrics/helm-charts).

**Comment by valyala** [comment]
FYI, the `-snapshot.createURL` and `-snapshot.deleteURL` command-line flags are available in `vmbackup` starting from [v1.35.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
