### ISSUE TITLE
vmui: Explore tab doesn't work for metrics with `job` label

### ISSUE THREAD

**Issue by helmut72** [VictoriaMetrics/VictoriaMetrics#4226]
### Is your question request related to a specific component?

vmui

### Describe the question in detail

How to explore metrics in vmui with metrics from telegraf in influxdb format?

I use this configuration in telegraf:
```
[[outputs.influxdb]]
  urls = ["http://<victoriametrics-addr>:8428"]
```

From this example:
<https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf>

When going into vmui -> explore metrics, I need to select a job. But there is no job. Therefore no instance and no search metric name.
I have connected Grafana to VictoriaMetric with Prometheus data source and getting all metrics, but want to see it in VM too. To be sure I don't make any mistake or a further configuration is needed.

Intention: I want to use Telegraf on every server to get metrics from all Prometheus endpoints on the server and send it in influx format to VictoriaMetrics. Also Telegraf can be used to capture other metrics than from Prometheus endpoints. Therefore I want to use Telegraf to have single ingester for all metrics (and log) stuff.

Thank you.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @helmut72!
Indeed, [metrics explorer](https://docs.victoriametrics.com/#metrics-explorer) is oriented on Prometheus-like approach where each metric has a `job` label. We should think of making the label dropdowns configurable cc @Loori-R 

However, this doesn't prevent you from browsing your telegraf metircs via [Query page](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.range_input=30m&g0.end_input=2023-05-02T10%3A02%3A36&g0.relative_time=last_30_minutes)  - just try entering something like `foo_field1{tag1="value1"}` (please substitute metric name and labels with your own) and execute the query. It works in the same way as Grafana's Explore mode or Prometheus UI.

**Comment by helmut72** [comment]
> However, this doesn't prevent you from browsing your telegraf metircs via [Query page](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.range_input=30m&g0.end_input=2023-05-02T10%3A02%3A36&g0.relative_time=last_30_minutes) - just try entering something like `foo_field1{tag1="value1"}` (please substitute metric name and labels with your own) and execute the query. It works in the same way as Grafana's Explore mode or Prometheus UI.

Works, thank you! My questions is answered.

**Comment by hagen1778** [comment]
Closing this issue. New feature request was formed here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4248
