### ISSUE TITLE
VM does not provide same query results as Prometheus

### ISSUE THREAD

**Issue by jangrewe** [VictoriaMetrics/VictoriaMetrics#423]
**Describe the bug**
We have a Grafana dashboard that contains a table which combines 3 queries. This table works fine with Prometheus as the data source, but with VictoriaMetrics there are some results missing from the table.

**To Reproduce**
Grafana query:
```
sum by(pod) (label_replace(rate(container_cpu_usage_seconds_total{container_name!="POD",namespace="$namespace"}[15m]), "pod", "$1", "pod_name", "(.+)"))
 / sum by(pod) (kube_pod_container_status_running * on(namespace, pod, container) group_left(node) kube_pod_container_resource_requests_cpu_cores)
```

**Expected behavior**
I would expect VM to return the same 23 results i get with Prometheus, instead of only 6.

**Screenshots**
data source VM:
![https://i.snipboard.io/v3NEnl.jpg](https://i.snipboard.io/v3NEnl.jpg)

data source Prometheus:
![https://i.snipboard.io/B4O5zD.jpg](https://i.snipboard.io/B4O5zD.jpg)

**Version**
```
victoria-metrics-20200417-111636-tags-v1.34.9-0-g43375df9
```

**Used command-line flags**
```
-storageDataPath=/data -retentionPeriod=6
```

**Comment by valyala** [comment]
@jangrewe , thanks for the detailed bug report! I suppose it may be related to the delay of data propagation from Prometheus to VictoriaMetrics persistent storage. This delay shouldn't exceed a few seconds under normal conditions when both Prometheus and VictoriaMetrics aren't overloaded with new data. There are pathological cases when the delay may become bigger - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/287 for details.

As I understood, Grafana sends a query to [/api/v1/query](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries) endpoint with `time` arg set to the current time when it generates reports from screenshots above. This means that VictoriaMetrics may see only a part of recently added data, so it returns partial response.

VictoriaMetrics provides the following command-line flags for overcoming possible issues with delay in data propagation when performing queries:
* `-search.latencyOffset` - the time offset from `now` where data may be incomplete. VictoriaMetrics adjusts query time, so it doesn't cover `-search.latencyOffset` time range until `now`.
* `-search.maxLookback` - the maximum duration to look back for the last data point per each time series.

Try increasing values for these flags and see whether this fixes the issue.

If this doesn't fix the issue, then it would be great to have the following information:

* Could you post graphs with lines for the last 1 hour for the query below from both Prometheus and VictoriaMetrics?

```promql
sum by(pod) (label_replace(rate(container_cpu_usage_seconds_total{container_name!="POD",namespace="$namespace"}[15m]), "pod", "$1", "pod_name", "(.+)"))
 / sum by(pod) (kube_pod_container_status_running * on(namespace, pod, container) group_left(node) kube_pod_container_resource_requests_cpu_cores)
```

* If the graphs above will have different number of lines for Prometheus and VictoriaMetrics on the whole 1h time range, then it would be great to see graphs for dividend and divisor in the original query for both Prometheus and VictoriaMetrics. This should help determining the part of the query which leads to incomplete results. The queries are:


```promql
sum by(pod) (label_replace(rate(container_cpu_usage_seconds_total{container_name!="POD",namespace="$namespace"}[15m]), "pod", "$1", "pod_name", "(.+)"))
```

and

```promql
sum by(pod) (kube_pod_container_status_running * on(namespace, pod, container) group_left(node) kube_pod_container_resource_requests_cpu_cores)
```

If the last query will return different number of time series for Prometheus and VictoriaMetrics, then it could be split further into the following subqueries, which should be checked too:

```promql
sum by(pod) (kube_pod_container_status_running)
```

and

```promql
sum by(pod) (kube_pod_container_resource_requests_cpu_cores)
```

**Comment by valyala** [comment]
This also can be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/426 . [The comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/426#issuecomment-616677745) explains possible root cause of the issue and proposes a few workarounds.

**Comment by jangrewe** [comment]
Thanks @valyala ,
i have built and tested the version with the commit from #426 , but that didn't fix it for me.
For reference, these are the arguments i tried, individually and combined:
```
-search.latencyOffset=60s
-search.maxLookback=60s
-search.minStalenessInterval=60s
```

Here are the graphs for the original query, from both data source:
![https://i.snipboard.io/DMxV7P.jpg](https://i.snipboard.io/DMxV7P.jpg)

This is for the dividend query:
![https://i.snipboard.io/SgI9qP.jpg](https://i.snipboard.io/SgI9qP.jpg)

And this for the divisor query, adjusted to only query for the same namespace
```
sum by(pod) (kube_pod_container_status_running{container_name!="POD",namespace="$namespace"} * on(namespace, pod, container) group_left(node) kube_pod_container_resource_requests_cpu_cores)
```
![https://i.snipboard.io/SWGTYA.jpg](https://i.snipboard.io/SWGTYA.jpg)

So the issue is with the dividend query, as it seems.

**Comment by jangrewe** [comment]
I have further simplified the query that already causes a mismatch in results, to:
```
sum by(pod_name) (rate(container_cpu_usage_seconds_total{container_name!="POD",namespace="$namespace"}[15m]))
```
and then looked at some other namespaces.
While some, if not most, of them look pretty identical, there are some wild divergents:
![https://i.snipboard.io/JZkOlN.jpg]https://i.snipboard.io/JZkOlN.jpg()

**Comment by valyala** [comment]
@jangrewe , I'm sorry for late reply.

Could you add a filter on `pod_name` for a single series with the largest discrepancy and then remove `sum by(pod_name)` from the query, so it has only `rate(...)` and see whether there are differences? If the resulting query returns many time series, then try adding additional the most specific filter in order to reduce the number of returned time series with the largest discrepancy. Then remove `rate` from the query, which will leave only a metric name with filters. Then post graphs for `rate(...)` and for a plain time series here for both Prometheus and VictoriaMetrics.

**Comment by denisgolius** [comment]
Hi @jangrewe !
Did you resolve your issue?

**Comment by jangrewe** [comment]
Hi all, it's been a while and ... "things" happened. ;-)
I haven't run into this issue again, also because it didn't look into it anymore, but unless proven otherwise i guess it's been resolved, so i'll close this issue. Thanks! :-)
