### ISSUE TITLE
Enterprise retention filter

### ISSUE THREAD

**Issue by Razikus** [VictoriaMetrics/VictoriaMetrics#4231]
### Is your question request related to a specific component?

Hello I have a question about dynamic retention filter (without need of restarting vmstorage container)
Is that possible?

I saw in documentation that retention filter can be applied as command parameter, but can it be applied somehow in running system?

Doc that i read:
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#retention-filters

### Describe the question in detail

Hello I have a question about dynamic retention filter (without need of restarting vmstorage container)
Is that possible?

I saw in documentation that retention filter can be applied as command parameter, but can it be applied somehow in running system?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hi @Razikus.

At the present time retention filters can't be changed without restart.

**Comment by Razikus** [comment]
thanks, 
what if i will run 2 replicas pointing to same volume, and just restart one?
