### ISSUE TITLE
How do I solve a problem with Telegraf and Tag naming creating multiple timeseries data?

### ISSUE THREAD

**Issue by dkowis** [VictoriaMetrics/VictoriaMetrics#4234]
### Is your question request related to a specific component?

So this is probably related to VictoriaMetrics and using telegraf with it, and then querying out data.

### Describe the question in detail

What I'm trying to do is using the [telegraf upsd plugin](https://github.com/influxdata/telegraf/blob/release-1.26/plugins/inputs/upsd/README.md) and there's a "status" tag in there.

Unfortunately that's coming across as two different time series data streams, and I'm not able to figure out what I need to do to make sure it's one stream.

In this example from my grafana, I sent the UPS into a test mode to see what the graphs would do, and now every single data source on my graph is doubled, because of that status tag that changed from `status_OL` to `status_OB` and back. They're really the same field, it's just a status string that indicated it was OnLine and then OnBattery.

I'd really like to know how I can either query properly to combine them, or change the input so it doesn't create two data sets, but I'm unable to figure out the right words to google. Thanks for any help!
![image](https://user-images.githubusercontent.com/28048/235542775-c3e025e9-1243-4b47-8887-f743785309e4.png)
 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dkowis** [comment]
Maybe related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1557

**Comment by hagen1778** [comment]
Hello! There are probably two ways to get rid of the extra label:
1. On query time. You can apply any [aggregation function](https://docs.victoriametrics.com/MetricsQL.html#aggregate-functions) with `without` modifier. For example, `max(upsd_time_left_ns) without (status_OB, status_LB)`. 
2. On ingestion time. You can apply relabeling to unify your two labels into one:
```
- source_labels: [status_OB]
  target_label: status
- source_labels: [status_OL]
  target_label: status
- action: labeldrop
  regex: "status_.*"
```
This would convert your data like the following:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/2902918/235654259-e7731ffd-a213-4225-9c2e-0b0759fae6bd.png">


The latter way is preferred because you won't need to account for complex queries in the future and all your data will be normalized.

**Comment by dkowis** [comment]
@hagen1778 Thanks for your reply! I agree I'd like to fix it on ingest so that the data is nice and clean, however, I don't know how I'd do this with a telegraf input. It's all coming in as the influxdb Line protocol, and so I'm not sure where I'd configure those actions you mentioned.

I've also tried some telegraf specific things like below, but telegraf still sends the status field (I think?):

```
  fielddrop = ["status"]
  tagexclude = ["status"]
```

Thanks!

**Comment by hagen1778** [comment]
I'm not familiar with telegraf. Maybe it allows to change it somehow.

Relabeling feature is supported by VictoriaMetrics vmagent, VM single node and vminsert. You can feed that relabeling config to any of this components and on ingestion they would clean your data. Read more here https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#relabeling

**Comment by dkowis** [comment]
https://docs.victoriametrics.com/relabeling.html

Looking at this documentation, I see many examples of how to do it during a prometheus scrape, but I'm sending in metrics using telegraf, so it's not part of a prometheus scrape. Is it possible to somehow attach the relabeling logic to be run for all possible ingestions, or as part of a influxdb listener?

I have not configured anything special, since it's already listening, and can ingest the metrics: https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf

**Comment by hagen1778** [comment]
So relabeling can be applied not only for scraped, but for ingested metrics as well. 
Consider the following example:
```
# relabeling config:
 cat relabel.yml 
- source_labels: [status_OB,status_OL]
  separator: ""
  target_label: status
- action: labeldrop
  regex: "status_.*"%  

# run VM single-node with relabeling enabled:
./bin/victoria-metrics -relabelConfig=relabel.yml

# ingest some metrics 
% curl -d 'upsd,host=myhost,status_OL=true time_left_ns=1' -X POST 'http://localhost:8428/write'
% curl -d 'upsd,host=myhost,status_OB=true time_left_ns=2' -X POST 'http://localhost:8428/write'

# export metrics to verify relabeling correctness
% curl -G http://localhost:8428/api/v1/export -d 'match={__name__="upsd_time_left_ns"}'
{"metric":{"__name__":"upsd_time_left_ns","host":"myhost","status":"true"},"values":[1,2],"timestamps":[1683100232341,1683100240868]}

```

You can apply this config in the same fashion to vmagent or vminsert.

**Comment by jiekun** [comment]
Closed as answered.

**Comment by tiny-pangolin** [comment]
another solution to this problem would be to use drop the status tag and use the status value since that is an integer and in your dashboards map the status code back to a text value.
