### ISSUE TITLE
/api/v1/write msg="non-recoverable error"

### ISSUE THREAD

**Issue by smalderez** [VictoriaMetrics/VictoriaMetrics#4236]
### Describe the question in detail

Hello, I have got 2 clusters with 2 prometheus sending their data to the same victoria metrics server.
It was working fine the last weeks but since we redeployed victoria metrics, one of my Prometheus seems to not send anymore metrics to victoria metrics and I have got the following errors:
/api/v1/write msg="non-recoverable error" count=13 exemplarCount=0 err="server returned HTTP status 400 Bad Request: remoteAddr: \"X.X.X.X:43916\", X-Forwarded-For: \"Y.Y.Y.Y\"; requestURI: /api/v1/write; cannot decompress snappy-encoded request with length 0: snappy: corrupt input"
Do you know how to solve this issue?
Thanks in advance!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Do you know how to solve this issue?

This is an unexpected error. Does Prometheus restart help somehow?

**Comment by smalderez** [comment]
Hi @hagen1778 , unfortunately it does not help.
The last time I saw it working properly, we used helm victoria-metrics-single 0.8.55.
Now we are in 0.8.59. I will try to downgrade to see the behaviour with the previous version.

**Comment by hagen1778** [comment]
Hm, if only one Prom can't write data then it is unlikely caused by VM version. I'm not sure what to recommend here, this error is totally unexpected. Would be nice to get it reproducable somehow.

**Comment by smalderez** [comment]
The remote write was in HTTP, changing it HTTPS solved the issue.
