### ISSUE TITLE
Retry requests with body in case of request exec error in vmauth 

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#4242]
### Describe the solution you'd like

At the moment vmauth doesn't retry non-get requests (requests with body), because it can lead to problems in non-idempotent endpoints.

But we can make an exception for the case when request execution error occurs and not an error from the backend, because in this case body was not sent to backend and we can retry request.

**Comment by valyala** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth.html) should retry `POST` requests with non-empty body if they weren't sent yet to the backend, starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
