### ISSUE TITLE
Keep only non-matched series in streaming aggregation

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#4243]
### Is your feature request related to a problem? Please describe

At the moment regardless of matching in config streaming aggregation:

- keeps all input series altogether if `keepInput=true`
- drops all input series altogether if `keepInput=false`

But in typical case user need to keep non-matched input series and drop all matched input series.

Now this effect can only be achieved with two coordinated remoteWrite (see additional information of this issue).

### Describe the solution you'd like

There are two options for implementation (without backward compatibility break):

- new flag `streamAggr.dropMatched`, that drops all matched series if flag `streamAggr.keepInput` is set
- new flag `streamAggr.keepMismatched`, that keep all matched series if flag `streamAggr.keepInput` isn't set

**Update**:
As described in this [comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4243#issuecomment-1588949050): based on user feedback it makes more sense to implement it with backward incompatible change and implement the following flow:
- if series did not match any rules - pass it to remote write
- if series did match some rule - pass aggregated results
  Setting keepInput=true in this case allows keeping full source data (both aggregated and original).

### Additional information

Discussion: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1682204682016349

**Comment by Amper** [comment]
Hi @oleg-tolmashov, i hope to do it in the next quarter. For now, you can use workaround with separate remoteWrite and dropping metrics with relabeling.

**Comment by zekker6** [comment]
Hi @oleg-tolmashov @Amper 
We've discussed this issue last week and decided that it will make more sense to change existing behavior.
Based on user feedback, it makes more sense to keep metrics which did not match any `streamAggr` rules by default.

So the idea is to change default behavior to:
- if series did not match any rules - pass it to remote write
- if series did match some rule - pass aggregated results
Setting `keepInput=true` in this case allows keeping full source data (both aggregated and original).

Also, I was going to implement this one next.

**Comment by valyala** [comment]
FYI, the commit 62651570bb6142f94025266e9e65353f3d6c37e2 changes the default behavior for [stream aggregation](https://docs.victoriametrics.com/stream-aggregation.html), so now non-matched input series are preserved in the output. The old behavior can be restored by passing `-remoteWrite.streamAggr.dropInput` command-line option to `vmagent` or by passing `-streamAggr.dropInput` command-line option to single-node VictoriaMetrics. In this case all the input series are dropped when stream aggregation is enabled.

This commit will be included in the next release. In the mean time it is possible to test the new stream aggregation behavior by building `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verifying that `vmagent` keeps input samples, which do not match any `match` filter in [stream aggregation configs](https://docs.victoriametrics.com/stream-aggregation.html#stream-aggregation-config).

**Comment by hagen1778** [comment]
vmagent changes the default behavior for [stream aggregation](https://docs.victoriametrics.com/stream-aggregation.html) for matched series starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
