### ISSUE TITLE
tsdb status

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#425]
**Describe the solution you'd like**
hi, is there any tools/api provides tsdb status like https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-stats ?
by the way, i think it's should be provides start/end and match[] args too
so we can identify high cardinality, and then block or optimize this series.

**Comment by hagen1778** [comment]
duplicate #268

**Comment by valyala** [comment]
FYI, the [/api/v1/status/tsdb](https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-stats) page has been added into VictoriaMetrics in the following commits:

* single-node version: 364db13c9c32999b2d0e9f0531773672408a0176
* cluster version: f9526809e57ed5f98da22661616f5a23d3320ac2

These commits will be included in the next release.

**Comment by valyala** [comment]
The `/api/v1/status/tsdb` page is available starting from [v1.35.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)
