### ISSUE TITLE
How do I pass state as a label to alertmanager as a grouping tia

### ISSUE THREAD

**Issue by zxlxgd** [VictoriaMetrics/VictoriaMetrics#4259]
The current configuration of my alertmanager grouping is as follows

> route:
>   group_by: ['alertgroup','**state**']
>   group_wait: 10s
>   group_interval: 30s
>   repeat_interval: 30m
>   receiver: 'web.hook.message'

But **state** is not an alarm label and does not work as a grouping in alertmanager，How should I implement grouping alarms by state？

**Comment by Haleygo** [comment]
if `state` means alert state in alertmanager, it's not supported, they attempt to send resolved and active alerts in the same notification, details in https://github.com/prometheus/alertmanager/issues/2334.

**Comment by zxlxgd** [comment]
@Haleygo I understand. Thank you very much
