### ISSUE TITLE
Config reload metrics persist indefinitely

### ISSUE THREAD

**Issue by akamensky** [VictoriaMetrics/VictoriaMetrics#4260]
### Describe the bug

- We run vmagent in remote sites and the network link to those sites may degrade periodically.
- Vmagent loads configurations from http endpoint in central location
- When link degrades the alert raised correctly
- However the metrics don't ever recover after that even if the next reload is successful

### To Reproduce

- Have vmagent load configuration from http endpoint using `--promscrape.config=http://some.http.endpoint`
- Define alert as `vm_promscrape_config_last_reload_successful != 1 or vmagent_relabel_config_last_reload_successful != 1`
- Break the network in between temporarily and restore it
- Verify config reloaded successfully after network recovered
- Check whether corresponding metrics have recovered (hint: they are not)

### Version

1.89.1

### Logs

N/A

### Screenshots

N/A

**Comment by Amper** [comment]
Hi @akamensky.

I did manage to reproduce the error for srape config + `vm_promscrape_config_last_reload_successful` and i going to fix it.

But i don't see same error for relabel config + `vmagent_relabel_config_last_reload_successful`, are you sure that the error has occurred for this metric?
If so, please send the log and graphs for the metrics `vmagent_relabel_config_reloads_total`, `vmagent_relabel_config_reloads_errors_total`, `vmagent_relabel_config_last_reload_successful`, `vmagent_relabel_config_last_reload_success_timestamp_seconds` for the period of the error reproducing.

**Comment by akamensky** [comment]
@Amper you are right, the only metric that I see stuck is `vm_promscrape_config_last_reload_successful`, the `vmagent_relabel_config_last_reload_successful` seems fine. The alert is defined as one for both metrics, so is what I reported.

OTOH, can this please be backported to earlier releases. We are on 1.89.1 and we had issues moving to 1.90.0 (see #4113 )

**Comment by Amper** [comment]
No, we are backport bugfixes only to LTS releases (the latest line of LTS releases is `1.87.*`).
A few perfomance improvements have been made in then current version (`master`) - perhaps you should try it when it will be released.

**Comment by valyala** [comment]
The `vm_promscrape_config_last_reload_successful` metric should be updated properly during config reload after the commit 8225a48b56dd89515411209498a4c60e8b0999b0 . This commit will be included in the next release. In the mean time it is possible to build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether the metric is updated properly on `-promscrape.config` [reload](https://docs.victoriametrics.com/vmagent.html#configuration-update).

**Comment by valyala** [comment]
The `vm_promscrape_config_last_reload_successful` metric should be updated properly during config reload starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the issue as fixed.

**Comment by valyala** [comment]
The bugfix has been backported to [v1.87.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.6).
