### ISSUE TITLE
vmagent: support `follow_redirects` on SD level 

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4282]
### Describe the bug

According to https://prometheus.io/docs/prometheus/latest/configuration/configuration/ `follow_redirects` can be set on scrape_config level, and per each configured SD. vmagent supports it only on scrape_config level.

### To Reproduce

Try setting `follow_redirects` for `kubernetes.SDConfig`.

### Version

v1.90

**Comment by Haleygo** [comment]
/assign
Glad to help :)

**Comment by hagen1778** [comment]
Fix was included to [1.91.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.1)
Thanks to @Haleygo !
