### ISSUE TITLE
The results vary when histogram_quantile is repeatedly executed

### ISSUE THREAD

**Issue by ahrtolia** [VictoriaMetrics/VictoriaMetrics#4285]
### Is your question request related to a specific component?

vmselect produces different histogram_quantile results on the same query

### Describe the question in detail

Describe the bug:
promQL:
`histogram_quantile(0.99, sum by (app,service,method,host,le) (rate(zeus_rpc_seconds_bucket{app=~"plat-sms-gateway",method="singleSend",service="SMSService",kind="server",deploy_lane=~"default|"}[10m]))) `

My promQL expression matched the timestamp exactly and I was accessing the same vmselect endpoint. Using this metric to record the TP99 of the service, I found that I often got different responses when calling the interface

request example：
`
http://192.168.107.41:8481/select/6666/prometheus/api/v1/query?query=histogram_quantile%280.99,%20sum%20by%20%28app,service,method,host,le%29%20%28rate%28zeus_rpc_seconds_bucket%7Bapp=~%22plat-sms-gateway%22,method=%22singleSend%22,service=%22SMSService%22,kind=%22server%22,deploy_lane=~%22default%7C%22%7D[10m]%29%29%29%20&time=1683715808.589&step=4s
`

response example:
`
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": [
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.11.74",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "10"
                ]
            },
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.34.38",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.009599999999999997"
                ]
            },
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.40.207",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.00495"
                ]
            },
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.45.92",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.00495"
                ]
            }
        ]
    }
}
`

another response example used same request:
`
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": [
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.11.74",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.00495"
                ]
            },
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.34.38",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.009599999999999997"
                ]
            },
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.40.207",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.00495"
                ]
            },
            {
                "metric": {
                    "app": "plat-sms-gateway",
                    "host": "10.30.45.92",
                    "method": "singleSend",
                    "service": "SMSService"
                },
                "value": [
                    1683715808.589,
                    "0.00495"
                ]
            }
        ]
    }
}
`
You can see that the index value of "host": "10.30.11.74 "is an abnormal 10
I would like to know why there is such a big difference between the data I get when I initiate the same request twice, and this phenomenon often occurs, which leads to my failure to use vmalert to configure alarms normally

If necessary, I can provide relevant contents of my vm cluster construction.  I do not know whether the data queried each time may be requested to different vmstorage due to my construction problem, which leads to data inconsistency

Thanks for answering your questions.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @ahrtolia! Sorry for the late response.

Could you please verify that:
1. You have no duplicates or deduplication enabled on your vmselect
2. Metric `zeus_rpc_seconds_bucket ` has consistent buckets across all applications
3. Metric `zeus_rpc_seconds_bucket ` buckets do not overlap each other

If all 3 are yes, then I'd like to request a data sample where I can reproduce the issue, if possible. 
I'd also recommend browsing other related questions here https://github.com/VictoriaMetrics/VictoriaMetrics/issues?q=is%3Aissue+is%3Aopen+histogram_quantile

**Comment by ahrtolia** [comment]
> Hello @ahrtolia! Sorry for the late response.
> 
> Could you please verify that:
> 
> 1. You have no duplicates or deduplication enabled on your vmselect
> 2. Metric `zeus_rpc_seconds_bucket ` has consistent buckets across all applications
> 3. Metric `zeus_rpc_seconds_bucket ` buckets do not overlap each other
> 
> If all 3 are yes, then I'd like to request a data sample where I can reproduce the issue, if possible. I'd also recommend browsing other related questions here https://github.com/VictoriaMetrics/VictoriaMetrics/issues?q=is%3Aissue+is%3Aopen+histogram_quantile

Thank you very much for your reply. I have followed the troubleshooting plan you provided to investigate our VM and found the following issues

I can confirm that I have the first point turned on, but my buckets may not be consistent across applications, and my buckets may overlap

1、My `vmselect` configuration：

```
nohup ./vmselect-prod -dedup.minScrapeInterval=30s \
  -replicationFactor=${REPLICATION_COUNT} \
  -storageNode=${SELECT_STORAGE_NODE_LIST} \
  -httpListenAddr=:8481 \
  -search.maxSeries=3000000 \
  -search.maxPointsPerTimeseries=3000000 \
  -search.maxUniqueTimeseries=3000000 \
  -search.maxSamplesPerQuery=10000000000 \
  -search.maxConcurrentRequests=48 \
  > ../logs/vmselect.log 2>&1 &
```

2、The query that went wrong, I can guarantee that the buckets of this app are consistent when reporting data. I am not sure if different apps will affect each other

3、When my service reports buckets, it uses a micrometer `https://github.com/micrometer-metrics/micrometer` client for reporting, and there is a phenomenon of bucket coverage. Moreover, we have only recently started using VictoriaMetrics, and we have never used native Prometheus before. I have also collected the problematic data from the previous Prometheus, but it has not been reproduced.

Besides, how can I send you my data?

Thank you very much for your answer

**Comment by hagen1778** [comment]
Sorry for the late reply.
Points 2 and 3 are important and required for both VM and Prometheus. You can check this related thread https://github.com/micrometer-metrics/micrometer/issues/120

It is fine to have different histgorams with different buckets, unless you want to aggregate them in one response. In this case you'll get unexpected results. Buckets should be consistent and do not overlap when aggregated.

>Besides, how can I send you my data?

Send it to roman@victoriametrics.com

**Comment by rodrigomageste** [comment]
Hey @ahrtolia, I'm experiencing a similar issue to the one you reported. Have you made any progress on this? I'm going to try the troubleshooting steps that @hagen1778 suggested for my case as well.
