### ISSUE TITLE
vmui - top queries add Action button

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4292]
### Is your feature request related to a problem? Please describe

We need to add an Action button to the query

### Describe the solution you'd like

Action button (like in cardinality explorer) that opens Graph page and executes the query AND/OR copy button for the query

**Comment by valyala** [comment]
Queries listed at [top queries](https://docs.victoriametrics.com/#top-queries) page can be copied and executed starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
