### ISSUE TITLE
"make docker-cluster-up" fails with current version (V2) of docker-compose

### ISSUE THREAD

**Issue by mactyr** [VictoriaMetrics/VictoriaMetrics#4300]
### Describe the bug

When I run `make docker-cluster-up` as suggested in [the docs](https://docs.victoriametrics.com/Quick-Start.html#starting-vm-cluster-via-docker) the response is:
```
docker-compose -f deployment/docker/docker-compose-cluster.yml up
make: docker-compose: No such file or directory
make: *** [deployment/docker/Makefile:180: docker-cluster-up] Error 127
```

I discovered that this is because with the current version of `docker-compose` that I installed today (V2), the docker compose command has changed from `docker-compose` to `docker compose` with no dash. By replacing all instances of `docker-compose` with `docker compose` in `deployment/docker/Makefile`, I was able to get the cluster up successfully. It seems that the build process should be updated to account for the fact that users may have V1 or V2 installed.

### To Reproduce

Run `make docker-cluster-up` with docker-compose V2 installed.

### Version

v1.90.0-cluster

### Additional information

I should also mention that I don't think the command given in the doc will generally work as written:
``` 
git clone https://github.com/VictoriaMetrics/VictoriaMetrics && 
make docker-cluster-up
```
because by default git clones the repo into a subdirectory. So I believe it would have to be something like:
``` 
git clone https://github.com/VictoriaMetrics/VictoriaMetrics &&
cd VictoriaMetrics &&
make docker-cluster-up
```
to work without error as one command.

**Comment by denisgolius** [comment]
@mactyr could you please check that  #4314 fixed your issue?

**Comment by denisgolius** [comment]
@mactyr  FYI, this feature is available starting from [v1.91.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.0)
Closing this issue as done.

**Comment by mactyr** [comment]
Thank you @denisgolius, I know I started responding to your prior comment but it looks like I never clicked submit! I did confirm that #4314 fixed the issue.

As I mentioned under "Additional Information" above, it would be helpful to newcomers if you updated the example command [here](https://docs.victoriametrics.com/Quick-Start.html#starting-vm-cluster-via-docker). The version currently shown results in an error:
```
make: *** No rule to make target 'docker-cluster-up'.  Stop.
```
It really needs the `cd VictoriaMetrics` in the middle.

**Comment by denisgolius** [comment]
> Thank you @denisgolius, I know I started responding to your prior comment but it looks like I never clicked submit! I did confirm that #4314 fixed the issue.
> 
> As I mentioned under "Additional Information" above, it would be helpful to newcomers if you updated the example command [here](https://docs.victoriametrics.com/Quick-Start.html#starting-vm-cluster-via-docker). The version currently shown results in an error:
> 
> ```
> make: *** No rule to make target 'docker-cluster-up'.  Stop.
> ```
> 
> It really needs the `cd VictoriaMetrics` in the middle.

Thanks for suggestion, fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4375
