### ISSUE TITLE
vmalert: Add a flag for alert to indicate the state of alert when sending alerts to notifiers

### ISSUE THREAD

**Issue by sShiiyu** [VictoriaMetrics/VictoriaMetrics#4307]
### Is your feature request related to a problem? Please describe

Why doesn't vmAlert provide a flag  to indicate whether the state of alert is firing or inActive when sending alerts to notifiers? 

Is there any other method we can use for judging the the state of alert besides comparing the endsAt time with current time?

### Describe the solution you'd like

add a flag for alert which sent to notifier to indicate the state of alert

**Comment by hagen1778** [comment]
> Why doesn't vmAlert provide a flag to indicate whether the state of alert is firing or inActive when sending alerts to notifiers?

vmalert follows Prometheus specification for [alert_generator](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#alert-format).

> Is there any other method we can use for judging the the state of alert besides comparing the endsAt time with current time?

Besides vmalert's UI, you can configure vmalert to persist alerts state to remote-write TSDB. See how to do this here https://docs.victoriametrics.com/vmalert.html#alerts-state-on-restarts. When configured, alerts state will be available in remote TSDB as metrics. For example, query `ALERTS(alertstate=firing)` will show you alerts in FIRING state.

**Comment by jiekun** [comment]
Close as answered.
