### ISSUE TITLE
vmctl: migrate data with month step for native mode by default

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4309]
### Describe the solution you'd like

Would be nice if time-based chunking would be enabled for vmctl by default. And the safest and most reasonable value seems to be a `month`.
Having it enabled by default should work well for 99% of cases.

**Comment by valyala** [comment]
[vmctl](https://docs.victoriametrics.com/vmctl.html) enables by default the [time-based chunking](https://docs.victoriametrics.com/vmctl.html#using-time-based-chunking-of-migration) for [data migration from other VictoriaMetrics instances](https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics), starting from [v1.91.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the feature request as done.
