### ISSUE TITLE
vmalert/vmagent: automatic config reload on changes

### ISSUE THREAD

**Issue by afoninsky** [VictoriaMetrics/VictoriaMetrics#431]
**Describe the solution you'd like**
To have command-line flag which specifies config reload interval.

**Is your feature request related to a problem? Please describe.**
Currently, vmagent/vmalert does not have ability to reload configs when they change (except ability to send SIGHUP to vmagent).
In order to make changes work it's required to restart services manually. In some environments (ex.: kubernetes) in brings undesired complication (restart pods using hacks etc.).

**Comment by valyala** [comment]
Added command-line flag `-promscrape.configCheckInterval` in the commit 00e897119f8d63a0866c65551fdd45735e6bfb41 . This commit will be available in the next release.

**Comment by afoninsky** [comment]
Great, thank you @valyala. It was incredibly fast :)

**Comment by tenmozes** [comment]
@valyala you've added the config reload for agent, but vmalert is also a part of issue :)

**Comment by valyala** [comment]
> @valyala you've added the config reload for agent, but vmalert is also a part of issue :)

Oops. Re-opening the issue then and assigning it to @hagen1778

**Comment by valyala** [comment]
FYI, `-promscrape.configCheckInterval` flag is available in `vmagent` and single-node VictoriaMetrics starting from [v1.35.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
@hagen1778 , can we close this issue as done?

**Comment by hagen1778** [comment]
@valyala it is done partially, I guess. The mentioned commit implements hot reload but misses auto reload on config file change. But this may be listed as separate FR, so I'm closing this.
