### ISSUE TITLE
Provide an official vmauth grafana dashboard 

### ISSUE THREAD

**Issue by sushovan23** [VictoriaMetrics/VictoriaMetrics#4313]
It would be good if an official vmauth grafana dashboard was available similar to the ones for vmagent, victoria metrics single and cluster mode. It will help in getting support via slack and give us better observability into the application

**Comment by hagen1778** [comment]
@Amper would you like to take this ticket?

**Comment by Amper** [comment]
@hagen1778 Yes, sure, but not in the near future, I have higher priority tasks at the moment.

**Comment by hagen1778** [comment]
It would be nice to provide basic alerting rules together with the dashboard. In the same way as single node and cluster version do that.

**Comment by hagen1778** [comment]
@sushovan23 vmauth dasbhoard was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6491
It was also published at grafana.com - see https://grafana.com/grafana/dashboards/21394
Additionally to dashboard we added default alerting rules - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts-vmauth.yml
See also updated monitoring docs for vmauth - https://docs.victoriametrics.com/vmauth/#monitoring

Closing this ticket as done.
