### ISSUE TITLE
rate function difference

### ISSUE THREAD

**Issue by vldops** [VictoriaMetrics/VictoriaMetrics#4319]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Hello. I've already seen issues about this problem, but I can't find solution how to avoid it.
I have prometheus and vm, and when I use sum(rate(some_metric[1h])) I have completely different results. So I don't know how to create alerts/charts properly. 

Screen from prometheus:
<img width="1411" alt="Screenshot 2023-05-17 at 00 33 23" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/64347625/5356ff66-f91f-4752-998d-3d987a68d4f7">

Screen from VM with the same query:
<img width="1424" alt="Screenshot 2023-05-17 at 00 33 56" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/64347625/9a63b703-8c52-4a41-a5c0-9a9ca704d13a">

It happens when I redeploy my app (k8s service) which creates new metrics.
[valyala](https://github.com/valyala) [said](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/165#issuecomment-525876291) that prometheus ignores the previous point before the range window.

VM Version
```
victoria-metrics-20220521-000544-tags-v1.77.2-0-g2d2d15b0d
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @vldops!

I see that X axis is different between 1st and 2nd screenshot. Is this expected? Also, can you make sure you're using the same `step` param in both cases?

**Comment by jiekun** [comment]
Close due to inactivity.
