### ISSUE TITLE
VMUI: add support for Prometheus URL in Cardinality Explorer

### ISSUE THREAD

**Issue by sharathfeb12** [VictoriaMetrics/VictoriaMetrics#4320]
### Is your feature request related to a problem? Please describe

I wanted to use [VMUI Cardinality Explorer](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality) for Prometheus instances that we have in our environment. VMUI looks to be much better UX than any other solutions available on market to interact with cardinality. 

Discussion with Victoria team can be found here: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1680716612547779

It would be cool if we can support VMUI be compatible with Prometheus, so they can be visualized and interpreted much easily.

### Describe the solution you'd like

Add support to connect to Prometheus using VMUI.

**Comment by valyala** [comment]
`vmui` should be able to query Prometheus from the [Cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer) tab starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
