### ISSUE TITLE
vmui: can get tenants from the clsuter 

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4322]
### Describe the bug

If the cluster supports multi-tenancy vmui doesn't send the request to the correct cluster tenant ID if we are changing that URL via settings form. 

### To Reproduce

Run vmui on your local machine with a cluster with multiple isolated tenants. Go to the vmui main page and observer the settings page. Try to change the URL in the settings form and save it.
<img width="771" alt="Screenshot 2023-05-17 at 16 16 55" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/1af4f2e7-aff0-4eea-9958-733a81a6ef62">

When it was saved successfully request will be sent to the old tenant id.
<img width="702" alt="Screenshot 2023-05-17 at 16 17 45" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/93766dfb-4950-4de7-89ce-b11ecb028981">

### Version

v1.90.0

**Comment by hagen1778** [comment]
Fix was included to [1.91.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.91.1)
