### ISSUE TITLE
vmagent lose data point for only one metric

### ISSUE THREAD

**Issue by renyuntao** [VictoriaMetrics/VictoriaMetrics#4323]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I am use vmagent to collect metric in k8s cluster，and store the metrics to vmsingle. Today I found one metric lose data point in vmui，but all other metrics looks fine, what's the possible reason?

The metric that lose data point:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/11660067/74127dac-2070-4c39-bbb9-23b761812621)

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@renyuntao Could you check if there are any logs printed in vmagent?
Also, which versions of vmagent and vmsingle are you using?

**Comment by hagen1778** [comment]
Related https://stackoverflow.com/questions/76252880/vmagent-lose-only-one-metrics-data-point-what-is-the-possible-reason/76287037#76287037

**Comment by zekker6** [comment]
Closing this as it seems to be resolved according to SO question. Feel free to reopen if this is still relevant.
