### ISSUE TITLE
VMselect 1.90.0 cannot expand WITH expressions

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#4325]
### Describe the bug

If you use values with a substitution and a dot in the name (for example, a fqdn) in a grafana, a parsing error occurs when requesting a vmselect. If you specify the domain with a dot in the request directly, then there is no error.

### To Reproduce

in grafana set multiple var with value with dot and send request for graph (example.ru, example2.ru)
 

### Version

docker exec vmselect /vmselect-prod --version
vmselect-20230407-011514-tags-v1.90.0-cluster-0-g64cf8fe49

### Logs

`2023-05-17T22:30:36.933+0300	warn	VictoriaMetrics/app/vmselect/main.go:717	error in "/select/0/prometheus/api/v1/query_range?end=1684351800&max_lookback=15s&query=ip_addresses_count%7Binstance%3D%22metric-server-1%22%2C+job%3D%22myjob%22%2C+domain%3D~%22example%5C.ru%22%7D&start=1684348200&step=15s": error when executing query="ip_addresses_count{instance=\"metric-server-1\", job=\"myjob\", domain=~\"example\\.ru\"}" on the time range (start=1684348200000, end=1684351800000, step=15000): cannot expand WITH expressions: cannot parse string literal "\"example\\.ru\"": invalid syntax`

**Comment by zekker6** [comment]
@ihard I've just tested this with Grafana 9.3.0 and blackbox exporter metrics, query works for me without any issues.

In the error message above resulting query will be:
```
ip_addresses_count{instance="metric-server-1", job="myjob", domain=~"example\.ru"}
```
Which is indeed invalid and will produce this error.

Most likely you need to update Grafana version to a newer one which includes fix for this case.

**Comment by ihard** [comment]
@zekker6 i tested with grafana version 9.3.14 and 9.51 - same error

**Comment by zekker6** [comment]
@ihard Could you share an example query/variable or dashboard JSON?
Most likely there is something to do with Grafana dashboard configuration.

Also, is it possible to check original label value which are stored in the database?
Probably Grafana is not escaping something properly.

**Comment by ihard** [comment]
@zekker6 I found a problem, there was a not quite obvious variable substitution with a regex type
${domain:regex} - fail
$domain -  it works
Thanks for the help!
