### ISSUE TITLE
[VMAlert] Could we persist normal alert state to VictoriaMetrics

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#4329]
### Is your question request related to a specific component?

My question is related to the VMAlert component.
Specifically, the persisting alert state on restart behavior: [VictoriaMetrics](https://docs.victoriametrics.com/vmalert.html#alerts-state-on-restarts)
I am using VictoriaMetrics Cluster with Version: 1.83.0

### Describe the question in detail

- As behavior that VMAlert will persist alert state to VictoriaMetrics, I saw that when alarm state switches back to normal state: firing -> oke or pending -> oke.

- I create a Grafana chart with metrics ALARMS and `only see points with firing and pending state`.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/67a31dc8-17a4-4709-9c98-42f6251b2000)
 `I think VMAlert does not persist normal state because it's unuseful for restart state when failure`.
But, Retrieving the alarm state history is hard as it only has firing and pending state.
- For example:
I receive the alert from telegram at 2023:05:19 10:29 AM:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/072cdc65-7eec-42a1-87ee-c19acaf56cf4)

- At 2023:05:19 10:34 AM, I received the resolved message of that alarm, but the Grafana chart does not have any point metrics that indicate an alert switch to normal state at 10:34 AM

- So, is this necessary for persisting normal alert state to VictoriaMetrics for enhancing alarm history?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@hagen1778 What do you think about this?

**Comment by hagen1778** [comment]
Related discussion https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3056

>So, is this necessary for persisting normal alert state to VictoriaMetrics for enhancing alarm history?

Why not use `ALERTS` for tracking history? It shows when alert becomes FIRING, and when it stops.

**Comment by tantm3** [comment]
I think I used the wrong word "normal state" in question so it becomes unclear.
In the Grafana image above, I used  `ALERTS` metrics name for creating the chart.
But I can only see the history that the alert becomes PENDING and FIRING. 
When the alert in the FIRING state switches back to the INACTIVE state, I think currently we do not persist the INACTIVE state to VictoriaMetrics.

**Comment by hagen1778** [comment]
> But I can only see the history that the alert becomes PENDING and FIRING.

That sounds reasonable to me... You only see what matters. 

> When the alert in the FIRING state switches back to the INACTIVE state, I think currently we do not persist the INACTIVE state to VictoriaMetrics.

True, vmalert doesn't do that according to Prometheus [spec](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#inspecting-alerts-during-runtime). It doesn't mean it carved in stone, but so far I'm not convinces that persisting inactive state makes sense. Some installations run thousands of alerting rules. Persisting state for big number of rules could have performance impact.

**Comment by tantm3** [comment]
That's true!
I think we need more reasons to do the persisting INACTIVE state than just to watch history.
I will close the issue here, maybe we can reopen it in the future.
