### ISSUE TITLE
vmbackup/vmrestore improvements

### ISSUE THREAD

**Issue by allen13** [VictoriaMetrics/VictoriaMetrics#433]
**Overview**

After spending a week operationalizing vmbackup and vmrestore I had an idea on how to improve the user experience. Currently these two functionalities are run in independent processes/containers. These items could be merged into the vmstorage api. This would improve usability and increase operational flexibility.

**Implementation**

- /backup/create - create a backup from a snapshot or latest data
- /backup/job/create - create a job that continously backs up on an interval
- /backup/restore - restore from a backup

**Benefits**

- Continuous Backups don't have to worry about how to mount the data directory. This can be challenging if the container is running in kubernetes on a single mount pvc. This has to be worked around with either a host mount or sidecar with script
- Easier to capture prometheus metrics on continuous backups and alert when things go wrong
- Significant reduction in ops work needed coordinate the different jobs
- 2 less containers
- Could coexist with current vmbackup/vmrestore solution

**Drawbacks**

- Less modular. Still looking for a situation where this might make things more difficult...
- More configuration parameters for vmstorage
- Potentially complicated api requests

**Awknowledgement**

The functional aspect of vmstorage/vmbackup has been fantastic. Once everything has been properly configured backups and restores happen extremely fast with no issues encountered. VictoriaMetrics is an amazing time series database. Thanks!

**Comment by valyala** [comment]
I like the idea of integrating backup / restore functionality directly into `vmstorage`, but it can complicate `vmstorage` with additional configuration parameters related to backup/restore and with potentially complicated api with many edge cases. Some edge case examples:
- When to return from `/backup/create`? Backup process can take non-trivial amounts of time, so it is expected that `/backup/create` must schedule backup and immediately return backup id, which could be used later for status checking.
- How to cancel backup?
- How to manage multiple calls to `/backup/create` when the previous backup isn't finished yet?
- How to deal with failed backups?
- There are various backup strategies such as making hourly, daily, weekly, etc. backups and how many backups of each type should be available before deletion of old backups. All these backup types may be placed in different folders on backup storage. How to configure all these aspects via `/backup/job/create`?

All these questions is easy to cover by writing custom code around `vmbackup` / `vmrestore` utilities. It isn't hard to build custom tool on top of [lib/backup](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/lib/backup) package (the core of `vmbackup` / `vmrestore`), which can implement the desired backup strategy. Actually, we already built `vmbackuper` tool on top of `lib/backup` package for paid customers. This tool can be configured to make periodic hourly/daily/weekly backups in the most efficient way.

**Comment by allen13** [comment]
Thanks for reviewing this and providing a good answer. A custom sidecar based on lib/backup would make a lot of sense.

**Comment by valyala** [comment]
FYI, see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/466 about `vmbackuper` tool for automating backup creation.
