### ISSUE TITLE
Victoria Metrics federation

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#4334]
### Is your question request related to a specific component?

Victoria Metrics, vmagent, vmalert.

### Describe the question in detail

When monitoring several different targets, the amount of data scrapped can be overwhelming and can cause a bottleneck when sending the metrics from the vmagent to the storage. 
1- Is there a way to setup some sort of a Prometheus federation using different instances of vmagent or Victoria Metrics in a Docker environment? If so how?
2 - Assuming it is possible how can vmalert be setup so that alerts are directly propagated when detected and not only when the alert reaches the "top" node of the federation?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> 1- Is there a way to setup some sort of a Prometheus federation using different instances of vmagent or Victoria Metrics in a Docker environment? If so how?

Federation is the same as scraping targets, isn't it? So both vmagent or VictoriaMetrics single-node could federate metrics from Prometheis. But I would suggest using federation at all.

> 2 - Assuming it is possible how can vmalert be setup so that alerts are directly propagated when detected and not only when the alert reaches the "top" node of the federation

I don't understand the question. vmalert runs alerting rule against specific datasource. If you specify as datasource top node - rules will be evaluated with data at top node. If you specify it at low node - it will do it on that data. You can even use vmalert with Prometheus as datasource, if you'd like)
