### ISSUE TITLE
vmalert merge label from data and rule is not compatible with prometheus

### ISSUE THREAD

**Issue by xbsura** [VictoriaMetrics/VictoriaMetrics#434]
**Describe the bug**
vmalert use such steps to merge labels from data and alert rule:

1. use data labels
2. merge alert rule label with data labels, alert rule labels first

sometimes, this kind of labels can not be templated ok

**To Reproduce**
use template in alert rule labels, then the label send to alert manager remain template

**Expected behavior**

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
vmalert alpha version
```

**Comment by xbsura** [comment]
We are using vm (storage, cluster, agent, alert and so on) replacing prometheus to reduce memory usage and do global alert

this labels merge bug may make alert-manager silence rule not work

thanks

**Comment by hagen1778** [comment]
Hi @xbsura! Could you give pls a bit more information about `sometimes, this kind of labels can not be templated ok`? Some example would be great!

**Comment by xbsura** [comment]
for example:

1. 
```
data: {"__name__": "data_name", "a": "data_a", "b": "data_b"}
rule: {"a": "rule_a", "b": '{{$labels.a}}' }
```
before vs after:
{"a": "rule_a", "b": '{{$labels.a}} } vs {"a": "rule_a", "b": 'data_a' }

2. 
```
data: {"__name__": "data_name", "a": "data_a", "b": "data_b"}
rule: {"a": "rule_a", "__name__":'{{$labels.__name__}}' }
```
before vs after:
{"a": "rule_a", "__name__":'{{$labels.__name__}}' } vs {"a": "rule_a", "b": 'data_name' }

the pull request works ok in our env and online now, but I'm not sure whether it's absolute same with prometheus, beacuse prometheus template code seems more complicated than here
