### ISSUE TITLE
Are static targets sharded when membersCount > 1

### ISSUE THREAD

**Issue by steeling** [VictoriaMetrics/VictoriaMetrics#4354]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

If I add a static scrape config, https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L246, is that sharded among multiple vmagent pods if I set membersNum and membersCount flags?

If not, this might be considered a bug in any scenario where the target is on the local host, or may be confusing to users? 

Related: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4200

Thanks in advance for your help! 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, yes, target will be sharded according to the membersNum and membersCount flags.

**Comment by steeling** [comment]
@f41gh7 would you consider this a bug when it is set to localhost? Since only `|replicationFactor|` number of localhost targets will actually be scraped?

Would it make sense to add an `overrideSharding` field to the scrape config to support this?

**Comment by steeling** [comment]
Would it make sense to add a feature to allow not sharding in this case though? This prevents vmagent from accurately scraping any local containers. This would be a useful feature IMO

**Comment by Haleygo** [comment]
> Would it make sense to add a feature to allow not sharding in this case though? This prevents vmagent from accurately scraping any local containers. This would be a useful feature IMO

Adding a new option `disable_sharding` for scrape_config sounds like a good enhancement to me, it could be useful when:
1. users prefer hostnetwork for some scrape jobs
2. (would be less realistic:))when `replicationFactor=1`, users can enable it for some important targets, then those targets will be scraped by multiple vmagent instances, to make sure their data to be delivered more reliably[if one shard of vmagent died, the targets won't be scraped before] and quickly[the quickest vmagent upload the data first].
wdyt @f41gh7 @hagen1778

**Comment by hagen1778** [comment]
@Haleygo I'm not convinced in adding the feature. I don't see a difference between vmagent scraping targets collocated on the localhost vs scraping targets on other hosts.

**Comment by Haleygo** [comment]
> @Haleygo I'm not convinced in adding the feature. I don't see a difference between vmagent scraping targets collocated on the localhost vs scraping targets on other hosts.

@hagen1778 The difference will be @steeling 's case [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4354#issuecomment-1569056908). 
if sharding enabled and using static_configs like `localhost:8429/metrics` to try scraping each vmagent's metrics, this scrapeWork will only be assigned to one vmagent[default replicationFactor=1], other instances are missing.

**Comment by hagen1778** [comment]
@Haleygo please see my comment here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4200#issuecomment-1855604198

**Comment by jiekun** [comment]
Close as answered. @steeling Feel free to raise another issue if you still want to request for extra enhancement.
