### ISSUE TITLE
vmagent: In HA mode some data points are not consistent on restarts

### ISSUE THREAD

**Issue by lzfhust** [VictoriaMetrics/VictoriaMetrics#4367]
### Describe the bug

When I use two vmagent clusters to scape the same targets, one of the vmagent cluster restarted and the time series are not consistent. 
<img width="1339" alt="企业微信截图_f1b67c4b-ba4f-4d83-9fad-f693f145d0b0" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9677371/6abe351d-68d3-433f-9ed5-ad074e253845">
<img width="1348" alt="企业微信截图_60e74f29-b30a-4c81-9227-98978a7ecabb" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9677371/9ce90c85-d487-434c-b430-ae76db16d5d5">

with the lastest version, during the restarting period(vmagent were offline and then online), the time series are consistent in the offline and not consistent in the beginning of online again. So, it seems part of the time series are not consistent at the beginning of another vmagent instance start to scrape.

I don't know this is a bug or because I run the clusters with something wrong.

### To Reproduce

1). start two vmagent instances to scrape metrics from the targets. The two vmagent started with the same scrape config . The scape interval is 30s

./bin/vmagent -remoteWrite.url=http://xxxxx:8480/insert/21/prometheus -promscrape.suppressScrapeErrors -promscrape.maxScrapeSize=5536870912 -loggerTimezone=Local -promscrape.suppressDuplicateScrapeTargetErrors=true -promscrape.config=vmagent-scrape.yaml -promscrape.configCheckInterval=30s -httpListenAddr=:8430 -promscrape.cluster.name=vmagent-test-8430

./bin/vmagent -remoteWrite.url=http://xxxxx:8480/insert/21/prometheus -promscrape.suppressScrapeErrors -promscrape.maxScrapeSize=5536870912 -loggerTimezone=Local -promscrape.suppressDuplicateScrapeTargetErrors=true -promscrape.config=vmagent-scrape.yaml -promscrape.configCheckInterval=30s -httpListenAddr=:8431 -promscrape.cluster.name=vmagent-test-8431

2). The -dedup.minScrapeInterval is 30s for vmstorage instances and vmselect instance.

3). Restarted one of the two vmagent instance and some timeseries are not consistent

 

### Version

I have tested the v1.75, v1.83 and v1.91

**Comment by lzfhust** [comment]
> Hello @lzfhust!
> 
> So you have two vmagents running with identical scraping config, and each vmagent is configured with a unique `-promscrape.cluster.name` cmd-line flag. Is your expectation for these two to work as HA pair? If yes, which part of documentation did you use for defining this configuration?

Yes. I use these two vmagents to works as HA pair.
https://docs.victoriametrics.com/#deduplication

**Comment by hagen1778** [comment]
Thanks! Based on your response I filed the following PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4371

The way how HA pair need to be set up was poorly communicated in the current docs. Two vmagents in HA pair need to be configured identically, so all data they produce would have the same label-set. The docs you mentioned were referring to the deduplication between **two** HA pairs, so VM can be consistent in samples of which HA pair need to be deduplicated.

In two words, you need to remove `promscrape.cluster.name` cmd-line flag and repeat your test.

I'd also appreciate your feedback regarding the docs change. Did it become more clear how deduplication works and how to build an HA pair of vmagents>

**Comment by lzfhust** [comment]
> Thanks! Based on your response I filed the following PR #4371
> 
> The way how HA pair need to be set up was poorly communicated in the current docs. Two vmagents in HA pair need to be configured identically, so all data they produce would have the same label-set. The docs you mentioned were referring to the deduplication between **two** HA pairs, so VM can be consistent in samples of which HA pair need to be deduplicated.
> 
> In two words, you need to remove `promscrape.cluster.name` cmd-line flag and repeat your test.
> 
> I'd also appreciate your feedback regarding the docs change. Did it become more clear how deduplication works and how to build an HA pair of vmagents>

Hello, @hagen1778 
Thank you very much. It works.
I have read the deduplication function in the lib/storage/dedup.go, but I still know why the promscrape.cluster.name should be identical in ha pair.

**Comment by hagen1778** [comment]
> With the same promscrape.cluster.name, we are trying to guarantee that the same scrape target is scraped at the same offsets in the ha pair?

Yes. And that other HA pair will be scraped with different offset.

> So, when one vmagent instance in the ha pair are offline, the dedup will consistently leaves samples?

No, it is for consistent deduplication between data from two different HA pairs. As you've read, deduplication in VictoriaMetrics chooses sample with the biggest timestamp on deduplication interval. If timestamps are equal, VM selects the biggest value among duplicates. But for a long time[ this wasn't a case and VM chose a random sample instead](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3333). 

So in order to provide a better consistency this `promscrape.cluster.name` was introduced, which makes HA pairs to scrape at different offsets. In result, one of the HA pairs which has the bigger offset becomes kinda "master". It means, that VM will keep its samples in the most of cases, and will deduplicate samples from "slave" HA pair.

**Comment by hagen1778** [comment]
Closing the issue as solved.
