### ISSUE TITLE
why not leave the newest value when timestamp comparison results in conflict in deduplication

### ISSUE THREAD

**Issue by luwang-epic** [VictoriaMetrics/VictoriaMetrics#4370]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

generate merge id when push metrics to vm storage and merge id is incremental, so we can distinguish the newest value. 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @luwang-epic!

Adding this unique ID would have negative impact on disk usage and on ingestion speed. Because the new ID would need to be generated and stored alongside with each data point. If you'd take into a account a fact that each data point consists of timestamp (int64) + value (float64) - adding a new ID value will increase disk space usage by 33%. And it is not only disk usage, compressing, decompressing, cache efficiency - everything will be impacted.

**Comment by luwang-epic** [comment]
Hello @hagen1778 

<img width="496" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26619518/f415a23d-34b5-4012-bd82-6eeaa221f570">

block folder name retains merge id, we can use it when merge blocks.  method of blockStreamReaderHeap.Less  modified as    followed in version v1.84.0-cluster, can the goal be achieved ?
<img width="708" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/26619518/3dc4f195-f731-4773-97e9-833e34531119">

**Comment by hagen1778** [comment]
This is a good idea, but still not ideal. Imagine the following situation:
1. You ingest two duplicates: one at now()-1m and second at now()-30s
2. The first sample falls into a data block with timestamp=now()-1m
3. The second sample falls into a data block with timestamp=now()-30s
4. After 10s after p1, the data block with  timestamp=now()-1m gets merged with even older data block. After merge, a new block is created with timestamp=now().
5. VM schedules another merge for newly created data block with timestamp=now() and a bit older data block timestamp=now()-30s. How would deduplication work in this case?

**Comment by luwang-epic** [comment]
I didn't think carefully, the idea don't work in above situation, thanks
