### ISSUE TITLE
Recovering from the loss of any one `vmstorage` with `-replicationFactor=2` set

### ISSUE THREAD

**Issue by nick-kentik** [VictoriaMetrics/VictoriaMetrics#4376]
### Is your question request related to a specific component?

`vmstorage`, `vmctl`

### Describe the question in detail

A quick topology overview:

* v1.87.5-cluster
* Three `vmstorage` nodes, configured with  `-retentionPeriod=26w`
* `vminsert` is configured with `-replicationFactor=2`
* `vmselect` with `-dedup.minScrapeInterval=30s`
* No backups :love_you_gesture: . https://valyala.medium.com/speeding-up-backups-for-big-time-series-databases-533c1a927883 is very accurate, but we are where we are.

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2613 tells me that some datapoints are only stored on a single node, but I expect the vast majority are stored on two of the three nodes.

Today, one of the three `vmstorage` nodes has been irrevocably lost. So rather than us having two copies of almost every point, perhaps 33% of them only have a single copy. A tiny proportion will have been lost for good, but I'm not sensitive about that.

What I'm looking to do is to introduce a new, empty `vmstorage` and then ensure that all the N=1 points we have become N=2 again.

Is it as simple as adding `-dedup.minScrapeInterval=30s` to the `vmstorage` processes and then doing a `vmctl` run that will export the entire cluster's data, and import it back into the same cluster, in native format? In particular, I'm looking for the result to be `N=2`, not `N=3` :sweat_smile:.

I do have an open task to add backups, I promise. Failing hardware beat us to it, is all.

Thanks for the great work on victoriametrics, and any guidance you can provide!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @nick-kentik 

> Is it as simple as adding -dedup.minScrapeInterval=30s to the vmstorage processes and then doing a vmctl run that will export the entire cluster's data, and import it back into the same cluster, in native format? 

That's correct. Running vmctl with `dedup.minScrapeInterval` will write same data with current replication factor to the cluster(RF=2). Considering that this data is already there it might create quite a lot of duplicates, so it might make more sense to create a new cluster and write data there and then perform a switch to a new cluster.

Also, you might want to check for `vm_rpc_rows_incompletely_replicated_total{name="vminsert"}` metric to find when datapoints were incompletely replicated and use vmctl to do replication for periods when this metric was increasing to make RF restoring more granular and lower performance penalty of having duplicates.

**Comment by nick-kentik** [comment]
Great, thanks for the confirmation @zekker6 . In this case, data since the cluster started was lost, so while `vm_rpc_rows_incompletely_replicated_total` could tell us when the loss ended, it wouldn't capture when the loss began.

As I understand the process for choosing which `vmstorage` nodes to write to, it's deterministic as long as the topology doesn't change? So by replacing (rather than removing) the dead host with an empty one, then doing the restoration, `vminsert` should *generally* pick the empty node alongside the node that contains the remaining copy of the point - although I appreciate there are cases where that won't be true :sweat_smile:.

Importing into an empty cluster is an interesting idea to guarantee we end up with N=2, I hadn't thought of it - thanks!

**Comment by zekker6** [comment]
> Great, thanks for the confirmation @zekker6 . In this case, data since the cluster started was lost, so while vm_rpc_rows_incompletely_replicated_total could tell us when the loss ended, it wouldn't capture when the loss began.

Because of such cases we usually recommend setting up a separate VM instance to keep metrics of the main installation. This instance will require much less resources than main one, but will allow you to guarantee that you will have required information when dealing with any issues.

> As I understand the process for choosing which vmstorage nodes to write to, it's deterministic as long as the topology doesn't change?

Yes, it uses consistent hashing based on value of `storageNode` flag, so if address (or FQDN if it used) is the same it will pick same node.
