### ISSUE TITLE
/api/v1/query_range method return more datapoint than /api/v1/query

### ISSUE THREAD

**Issue by Buddruggy** [VictoriaMetrics/VictoriaMetrics#4377]
### Describe the bug

/api/v1/query_range method return more datapoint than /api/v1/query

### To Reproduce

/api/v1/query method return 4 datapoints in the past three hours
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/32037815/4a96ec63-1a82-46fa-987f-1fd38c65e49a)

but /api/v1/query_range method return 590 datapoints in the past three hours
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/32037815/fbfd7e33-0455-4e2e-87bd-781372407a50)

### Version

vminsert-20230406-064250-tags-v1.87.5-cluster-0-gfff15ae05

**Comment by zekker6** [comment]
Hi @Buddruggy 

Please, give a read to the following doc - https://docs.victoriametrics.com/keyConcepts.html#query-data
It describes difference between `/query` and `/query_range` query execution flow and explains purposes of having different endpoints.

**Comment by Buddruggy** [comment]
> Hi @Buddruggy
> 
> Please, give a read to the following doc - https://docs.victoriametrics.com/keyConcepts.html#query-data It describes difference between `/query` and `/query_range` query execution flow and explains purposes of having different endpoints.

Hi @zekker6, thanks for your reply!

I just finished reading this document, but i still confused about the result of this case, because this timeseries only have 4 points in the past 3 hours, and the `step` param of `query_range` is `60s`, so the gap is bigger than lookbehind window, and the result of `query_range` should not have 520 points.

I exec the case another time, and give the origin sample data, and `query_range` result:

`http://xxx/select/0/prometheus/api/v1/export?match[]={namespace=%22Production%22,target=%22PCG-123.eff_tool.app_task%22,__name__=%22custom_gauge_overview_dashboard_success_metric_v002_set%22}&end=1685621460&start=1685610840` 
-> 
`{"metric":{"__name__":"custom_gauge_overview_dashboard_success_metric_v002_set","namespace":"Production","con_setid":"-","env_name":"formal","k10":"-","k11":"-","k12":"-","k13":"-","k14":"-","k15":"formal","k7":"-","k8":"-","k9":"-","metrics_name":"pp_trc_eff_tool.app_task_overview_dashboard_success_metric","monitor_name":"overview_dashboard_success_metric","region":"-","target":"PCG-123.eff_tool.app_task","version":"v0.0.1"},"values":[100,100,100],"timestamps":[1685611380041,1685614980036,1685618580036]}`

and 

`http://11.160.114.140/select/0/prometheus/api/v1/query_range?end=1685621460&query=avg%28custom_gauge_overview_dashboard_success_metric_v002_set%7Bnamespace%3D%22Production%22%2Ctarget%3D%22PCG-123.eff_tool.app_task%22%2Ctarget%3D%22PCG-123.eff_tool.app_task%22%7D%29&start=1685610840&step=60`
->
`{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{},"values":[[1685611440,"100"],[1685611500,"100"],[1685611560,"100"],[1685611620,"100"],[1685611680,"100"],[1685611740,"100"],[1685611800,"100"],[1685611860,"100"],[1685611920,"100"],[1685611980,"100"],[1685612040,"100"],[1685612100,"100"],[1685612160,"100"],[1685612220,"100"],[1685612280,"100"],[1685612340,"100"],[1685612400,"100"],[1685612460,"100"],[1685612520,"100"],[1685612580,"100"],[1685612640,"100"],[1685612700,"100"],[1685612760,"100"],[1685612820,"100"],[1685612880,"100"],[1685612940,"100"],[1685613000,"100"],[1685613060,"100"],[1685613120,"100"],[1685613180,"100"],[1685613240,"100"],[1685613300,"100"],[1685613360,"100"],[1685613420,"100"],[1685613480,"100"],[1685613540,"100"],[1685613600,"100"],[1685613660,"100"],[1685613720,"100"],[1685613780,"100"],[1685613840,"100"],[1685613900,"100"],[1685613960,"100"],[1685614020,"100"],[1685614080,"100"],[1685614140,"100"],[1685614200,"100"],[1685614260,"100"],[1685614320,"100"],[1685614380,"100"],[1685614440,"100"],[1685614500,"100"],[1685614560,"100"],[1685614620,"100"],[1685614680,"100"],[1685614740,"100"],[1685614800,"100"],[1685614860,"100"],[1685614920,"100"],[1685614980,"100"],[1685615040,"100"],[1685615100,"100"],[1685615160,"100"],[1685615220,"100"],[1685615280,"100"],[1685615340,"100"],[1685615400,"100"],[1685615460,"100"],[1685615520,"100"],[1685615580,"100"],[1685615640,"100"],[1685615700,"100"],[1685615760,"100"],[1685615820,"100"],[1685615880,"100"],[1685615940,"100"],[1685616000,"100"],[1685616060,"100"],[1685616120,"100"],[1685616180,"100"],[1685616240,"100"],[1685616300,"100"],[1685616360,"100"],[1685616420,"100"],[1685616480,"100"],[1685616540,"100"],[1685616600,"100"],[1685616660,"100"],[1685616720,"100"],[1685616780,"100"],[1685616840,"100"],[1685616900,"100"],[1685616960,"100"],[1685617020,"100"],[1685617080,"100"],[1685617140,"100"],[1685617200,"100"],[1685617260,"100"],[1685617320,"100"],[1685617380,"100"],[1685617440,"100"],[1685617500,"100"],[1685617560,"100"],[1685617620,"100"],[1685617680,"100"],[1685617740,"100"],[1685617800,"100"],[1685617860,"100"],[1685617920,"100"],[1685617980,"100"],[1685618040,"100"],[1685618100,"100"],[1685618160,"100"],[1685618220,"100"],[1685618280,"100"],[1685618340,"100"],[1685618400,"100"],[1685618460,"100"],[1685618520,"100"],[1685618580,"100"],[1685618640,"100"],[1685618700,"100"],[1685618760,"100"],[1685618820,"100"],[1685618880,"100"],[1685618940,"100"],[1685619000,"100"],[1685619060,"100"],[1685619120,"100"],[1685619180,"100"],[1685619240,"100"],[1685619300,"100"],[1685619360,"100"],[1685619420,"100"],[1685619480,"100"],[1685619540,"100"],[1685619600,"100"],[1685619660,"100"],[1685619720,"100"],[1685619780,"100"],[1685619840,"100"],[1685619900,"100"],[1685619960,"100"],[1685620020,"100"],[1685620080,"100"],[1685620140,"100"],[1685620200,"100"],[1685620260,"100"],[1685620320,"100"],[1685620380,"100"],[1685620440,"100"],[1685620500,"100"],[1685620560,"100"],[1685620620,"100"],[1685620680,"100"],[1685620740,"100"],[1685620800,"100"],[1685620860,"100"],[1685620920,"100"],[1685620980,"100"],[1685621040,"100"],[1685621100,"100"],[1685621160,"100"],[1685621220,"100"],[1685621280,"100"],[1685621340,"100"],[1685621400,"100"],[1685621460,"100"]]}]}}`

According to the doc, in my opinion, `query_range` shoule not return so many points. because the gap is bigger than lookbehind window.

**Comment by zekker6** [comment]
@Buddruggy Thank you for the detailed response!
Could you please share which flags are set for vmselect and vmstorage?

**Comment by Buddruggy** [comment]
@zekker6 Sure.
- vmstorage
`vmstorage-prod -storageDataPath=/data -retentionPeriod=30d -search.maxUniqueTimeseries=1000000 -storage.minFreeDiskSpaceBytes=10GiB -memory.allowedPercent=80`
- vmselect
`vmselect-prod -storageNode=xxx,xxx -memory.allowedPercent=80 -search.maxUniqueTimeseries=1000000 -search.maxSeries=100000`

**Comment by hagen1778** [comment]
@Buddruggy on the screenshot for /query_range you have step=15s and it suppose to return you `180*60/15 = 720` datapoints. It returns you about 600 because looks like you didn't have data before 1:20 pm

In the second comment you have start=1685610840, end=1685621460 and step=60. Hence, `(1685621460-1685610840) / 60` should return you `177` datapoints and you get like `170`. Where first datapoints starts at 1685611440 - 10min after your `start`. Which explains why you have less than 177.

**Comment by hagen1778** [comment]
Please see the following doc:
```
Sometimes, the lookbehind window for locating the datapoint isn't big enough and the graph will contain a gap. For range queries, lookbehind window isn't equal to the step parameter. It is calculated as the median of the intervals between the first 20 raw samples in the requested time range. In this way, VictoriaMetrics automatically adjusts the lookbehind window to fill gaps and detect stale series at the same time.
```

Difference between data point timestamps in exported data is about 1h, and it is used as lookbehind window.

**Comment by Buddruggy** [comment]
@hagen1778 O, i see. It is indeed more reasonable to use the median of the intervals between the first 20 raw samples in the requested time range as the value of lookbehind window compared to use the value of step. Thanks so much for your reply!
