### ISSUE TITLE
vmagent: eureka discovery loses target

### ISSUE THREAD

**Issue by w564791** [VictoriaMetrics/VictoriaMetrics#4380]
### Describe the bug

when we use vmagent scrape eureka register instances , we found we loss some targets

### To Reproduce

I don't now hao to reproduce

### Version

/ # /vmagent-prod --version
vmagent-20230313-063224-tags-v1.87.3-0-g16be82b95

**Comment by w564791** [comment]
we had 3000+ targets use eureka discovery ,and 13 instances, lost 2 targets

**Comment by hagen1778** [comment]
What about configuration for eureka_sd? Do you have any additional flags configured for vmagent? Have you tried using the latest vmagent?

**Comment by hagen1778** [comment]
Closing as stale
