### ISSUE TITLE
vmagent silently fails to write with invalid remoteWrite.url

### ISSUE THREAD

**Issue by mactyr** [VictoriaMetrics/VictoriaMetrics#4385]
### Describe the bug

We set up a `vmagent` to write to two instances of single-node VictoriaMetrics. The `remoteWrite.url` values incorrectly ended with `/api/v1/import` rather than `/api/v1/write`. `vmagent` accepted POSTs to its own `/api/v1/import` and apparently responded with a success status code (because my application didn't log any errors while writing) but no data made it to the single-node VictoriaMetrics instances. `vmagent` did not write any errors to its own log when attempting to do the remote writes. My only clue to the problem was that when `vmagent` started up, I saw this in the logs:
```
{"ts":"2023-05-26T13:45:36.437Z","level":"info","caller":"VictoriaMetrics/app/vmagent/remotewrite/client.go:162","msg":"the remote storage at \"1:secret-url\" doesn't support VictoriaMetrics remote write protocol. Switching to Prometheus remote write protocol. See https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol"}
```
Investigating why the VictoriaMetrics protocol wasn't being used led me to discover the incorrect `remoteWrite.url` values, but otherwise the problem would have been totally silent.

`vmagent` should respond with an error code to write requests when it doesn't have a valid `remoteWrite.url` to remote-write to, or should at least log an error in its own log in this situation.

### To Reproduce

Set up a vmagent to remote write to two standalone VictoriaMetrics instances, but end the `remoteWrite.url` values with `/api/v1/import` rather than `/api/v1/write`. Observe that writes to `vmagent`'s `/api/v1/import` fail silently.

### Version

Both `vmagent` and VictoriaMetrics standalone were v1.91.0.

### Logs

As noted above, the only relevant item in the `vmagent` log was related to protocol negotiation.

### Used command-line flags

`vmagent`: `-promscrape.config=/config/scrape.yml -remoteWrite.tmpDataPath=/tmpData -remoteWrite.url=http://victoriametrics1:8428/api/v1/import -remoteWrite.url=http://victoriametrics2:8428/api/v1/import -envflag.enable=true -envflag.prefix=VM_ -loggerFormat=json`

single-node VictoriaMetrics: `-retentionPeriod=120 -dedup.minScrapeInterval=1s -search.disableCache -search.maxPointsPerTimeseries=100000 -search.maxPointsSubqueryPerTimeseries=3000000 -search.latencyOffset=0s -selfScrapeInterval=10s`

**Comment by tenmozes** [comment]
that would be awesome to add check in initial handshake mechanism and verifies that destination endpoint supports remote write. We can use existing handshake mechanism to ensure that, however it must be backward compatible 

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/protoparser/common/vmproto_handshake.go#L11 - associated code

**Comment by Haleygo** [comment]
> that would be awesome to add check in initial handshake mechanism and verifies that destination endpoint supports remote write. We can use existing handshake mechanism to ensure that, however it must be backward compatible
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/protoparser/common/vmproto_handshake.go#L11 - associated code

@tenmozes You mean add an initial handshake check for all the remote write urls when vmagent start? Maybe in here
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2c876227e403a736f624584e159720309cf92885/app/vmagent/remotewrite/client.go#L105-L169
But what if one remote endpoint isn't ready at that moment, that shouldn't affect vmagent to do other things. So we should log this fail handshake as an error and not send data to that endpoint again or keep trying and log every failure request?
I think the latter is better.

**Comment by Haleygo** [comment]
@mactyr Unlike invalid or unreachable url, when vmagent send data to vmsingle/vminsert's `/api/v1/import`, there will be no error response, so vmsingle will not have any error log or retry those requests.
But there should be a lot of unmarshal error logs from vmsingle side, and you can see `vm_rows_invalid_total{type="vmimport"}` from the dashboard.

**Comment by mactyr** [comment]
@Haleygo, thanks. I don't understand why there wouldn't be an error response when vmagent sends invalid data to vmsingle's `/api/v1/import`. Shouldn't there be some kind of 4xx response in that case? Silently accepting the bad data seems like a bug on the vmsingle side.

**Comment by Haleygo** [comment]
`/api/v1/import` is normally used to import data which produced by `/api/v1/export` in [json format](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format). Using that path means user want to import data to vmsingle or vmcluster, so they will query those data after the request, and debug the log of vmsingle/vminsert if data can't be found.
But `/api/v1/import` do hide the data format error from the client side, seems like an enhancement to me.

**Comment by mactyr** [comment]
Thanks @Haleygo, I've filed an enhancement request for that: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4446

**Comment by hagen1778** [comment]
@mactyr @Haleygo please see my response here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4446#issuecomment-1590636702

**Comment by hagen1778** [comment]
Closing this issue as solved.
