### ISSUE TITLE
vmctl: increase backoff delay for migration processes

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4402]
### Is your feature request related to a problem? Please describe

When users try to migrate a lot of data, it takes a lot of time, and sometimes network or different issues can happen during the migration process. These issues can be persistent and require you to restart the migration process.

### Describe the solution you'd like

Increase constant values for backoff factor and number of retriesthe

**Comment by valyala** [comment]
This feature has been added in [vmctl v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing it as done.
