### ISSUE TITLE
Latest Windows binaries detected as trojan

### ISSUE THREAD

**Issue by vkalladath** [VictoriaMetrics/VictoriaMetrics#4406]
### Describe the bug

While download the latest release, Windows defender identifies it as a threat and quarrantines it. This is not a problem for victoria-metrics-windows-amd64-v1.91.0.zip. 

Following are the files I tested.
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.91.2/victoria-metrics-windows-amd64-v1.91.2.zip
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.91.2/victoria-metrics-windows-amd64-v1.91.2-enterprise.zip
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.91.2/victoria-metrics-windows-amd64-v1.91.1.zip
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.91.2/victoria-metrics-windows-amd64-v1.91.1-enterprise.zip

Please see attached screenshot.

### To Reproduce

On Windows 10 Pro (10.0.19045 Build 19045) with Virus and threat protection turned on, download the above mentioned versions of Windows releases from https://github.com/VictoriaMetrics/VictoriaMetrics/releases.

### Version

v1.91.1, v1.91.2

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/25205626/e196b57c-ce08-4bd7-8fb1-e3756c3d28b2)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/25205626/bf588d2b-3e7d-4835-84d3-d0538aae17e2)

**Comment by denisgolius** [comment]
Hi @vkalladath !
I've tried to check these release archives from win11 but  windows defender don't see any issues. I also contact with company who detect this signature and I'll let you know as soon as I get feedback.

As a workaround for now you can use socker containers for VictoriaMetrics or try to run it in WSL/WSL2.

**Comment by vkalladath** [comment]
The latest windows defender update seems to have fixed this issue. 
Thank you for the support.
Closing.
