### ISSUE TITLE
VMAlertmanagerConfig: source_matchers: got "map", expected "string"

### ISSUE THREAD

**Issue by bruse-peng** [VictoriaMetrics/VictoriaMetrics#4410]
### Is your question request related to a specific component?

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: webhook
  namespace: monitoring
  labels:
    alertmanagerConfig: sams-qa
spec:
  route:
    group_by: ['alertname','alertgroup','InstanceName']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhook_configs:
    - url: 'http://wechatalarm/webhook_send'
      send_resolved: true
  inhibit_rules:
  - source_matchers:
      - "time_range_out": "true"
    target_matchers:
      - alertname =~ "kafka分区消息积压告警|kafka分区消息积压告警-分组oceanus_sam_iceberg_basic_sam_online_01"
    equal: ['alertname','env','ip','topic']

### Describe the question in detail

when i apply this yaml file it arise error below,how i can solved it
error: error validating "vmalertmanager-config-new.yaml": error validating data: ValidationError(VMAlertmanagerConfig.spec.inhibit_rules[0].source_matchers[0]): invalid type for com.victoriametrics.operator.v1beta1.VMAlertmanagerConfig.spec.inhibit_rules.source_matchers: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by bruse-peng** [comment]
<img width="1294" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/47881861/d54fe604-81ab-4cd1-bc96-9590c4f49269">

**Comment by Haleygo** [comment]
@bruse-peng `"time_range_out": "true"` is a map, try using `time_range_out = "true"` instead.

**Comment by hagen1778** [comment]
@bruse-peng please follow the recommendation give in error message. According to [spec](https://docs.victoriametrics.com/operator/api.html?highlight=source_matchers#inhibitrule):
```
SourceMatchers defines a list of matchers for which one or more alerts have to exist for the inhibition to take effect.
```
and is of type `[]string`. For more details on what is inhibit rule and source matcher - please see [these docs](https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule).
