### ISSUE TITLE
Does victoriametrics support paging queries?

### ISSUE THREAD

**Issue by wanzh909** [VictoriaMetrics/VictoriaMetrics#4411]
### Is your question request related to a specific component?

limit_offset(limit, offset, q) is a [transform function](https://docs.victoriametrics.com/MetricsQL.html#transform-functions), which skips offset time series from series returned by q and then returns up to limit of the remaining time series per each group.

### Describe the question in detail

For example, there are 100 pieces of data in this time series grouping, and 10 pieces are queried per page.
Not 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Thanks! Do you find the description of [limit_offset](https://docs.victoriametrics.com/MetricsQL.html#limit_offset) function incomplete or misleading? Have you tried using it for paging?

**Comment by jiekun** [comment]
Close due to inactivity.
