### ISSUE TITLE
Ignore datapoints that didn't change during scrapes

### ISSUE THREAD

**Issue by geogeim** [VictoriaMetrics/VictoriaMetrics#4414]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I'm migrating from InfluxDB to VictoriaMetrics and i have some questions regarding scraping.
I have one IOT gateway source that exports multiple metrics, some that update relatively slowly (temperature sensors, presence sensors, etc). I understand that every time VictoriaMetrics scrapes the data it creates new datapoints, even if the data itself did not change. This create a staircase effect in the graphs. For example: 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16436533/1434bb0c-cb94-48e0-8415-68357ed74b10)
1. Can VictoriaMetrics be configured to ignore datapoints if they did not change since the last scrape?
2. Will VictoriaMetrics use more disk space to store all these redundant datapoints?
3. How can i adjust the queries to get graphs resembling InfluxDB (i.e. remove this staircase effect)

I don't want to increase the scrape interval because some sensors are faster than others and i want fairly accurate series.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
>  I understand that every time VictoriaMetrics scrapes the data it creates new datapoints, even if the data itself did not change. 

It is true and is aligned with [Pull model](https://docs.victoriametrics.com/keyConcepts.html#pull-model), where each scrape represents the current state of the observed system.

> This create a staircase effect in the graphs

This shouldn't be so. If value of metric isn't changing, then you should observe it as a constant flat line on the graph. Unless, the value is changing or you have a query that shows not a value but something else. See the [following example](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=sum%28up%29&g0.range_input=5h33m7s786ms&g0.end_input=2023-06-06T13%3A19%3A24&g0.relative_time=none)  - the value stays the same during 6h despite the fact it is scraped each 15s.

> Can VictoriaMetrics be configured to ignore datapoints if they did not change since the last scrape?

It cannot. But there is not much sense in it. As I explained above there is no staircase effect for the scraped value. And in terms of compression - identical values are compressed extremely well.

> Will VictoriaMetrics use more disk space to store all these redundant datapoints?

It will, but not that much. See explanation above ^.

> How can i adjust the queries to get graphs resembling InfluxDB (i.e. remove this staircase effect)

It is impossible to answer without knowing queries you use. But please see https://docs.victoriametrics.com/guides/migrate-from-influx.html#query-data

**Comment by geogeim** [comment]
@hagen1778 is the image not visible somehow?
the value of the sensor stays the same so the series will have multiple consecutive points with the same value. Because the value updates infrequently grafana will plot all these intermediary values, then a sudden jump when the sensor changes values, then the new value repeated and so on hence the staircase. When i plot the value coming from influxdb it only plots the datapoints that were updated, hence the smooth graph.

My queries are as simple as possible i.e `sensor_temperature_celsius{entity="sensor.0x00158d00034983ae_temperature"}`

I didn't find any information in the MetricsQL query language documentation on how to ignore consecutive values that are the same for a data source, so i don't know how to make these graphs to look the same.

Will it help to export into victoriametrics using the Influx protocol or victoriametrics will fill up intermediary values also?

**Comment by hagen1778** [comment]
> I didn't find any information in the MetricsQL query language documentation on how to ignore consecutive values that are the same for a data source, so i don't know how to make these graphs to look the same.

Have you checked the information below?

> VictoriaMetrics fills the gaps on the graph assuming time series are always continuous and not discrete. To limit the interval on which VictoriaMetrics will try to fill the gaps, set -search.setLookbackToStep command-line flag. This limits the gap filling to a single step interval passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyConcepts.html#range-query). This behavior is close to InfluxDB data model.

From https://docs.victoriametrics.com/guides/migrate-from-influx.html#basic-concepts

**Comment by geogeim** [comment]
I tried the flag but now the graphs look weird:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16436533/26266186-738e-4acd-b715-783faf442d0c)
Still the points are repeated every scrape interval but now the points are not connected. If i remove the flag the series seems to stay like that.. I can increase the min interval in the query options but they still don't look as close to InfluxDB.

>> I didn't find any information in the MetricsQL query language documentation on how to ignore consecutive values that are the same for a data source, so i don't know how to make these graphs to look the same.

> Have you checked the information below?

I was referring if there is some sort of MetricsQL function that will return the time series as sparse, only returning different consecutive points.

Is it correct to say that victoriametrics cannot store sparse time series?

**Comment by hagen1778** [comment]
> I was referring if there is some sort of MetricsQL function that will return the time series as sparse, only returning different consecutive points.

No, there is no such functionality. 

> Is it correct to say that victoriametrics cannot store sparse time series?

VictoriaMetrics stores what you put in it. If you put the same value 10 times each 10sec - then this is what it would store and return on request. 
I think, you're confused with [Pull model](https://docs.victoriametrics.com/keyConcepts.html#pull-model). With pull model it is expected to scrape data with fixed time interval even if it didn't change. No change to data doesn't mean it can be ignored. Consider example of CPU usage: if CPU usage was 80% 30sec ago and 80% now it still means that CPU was utilized for 80% during last 30s. 

If you want to write changes only, take a look at [Push model](https://docs.victoriametrics.com/keyConcepts.html#push-model). With Push model you decide what to write to the database, and when.
