### ISSUE TITLE
vmauth: add brokenBackendDeadline Flag 

### ISSUE THREAD

**Issue by SunKyu** [VictoriaMetrics/VictoriaMetrics#4415]
### Is your feature request related to a problem? Please describe

There's no flag to set broken Backend Deadline time. (`3s` in code)
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/de948120889529af03c1dbc644eb7305d46bae19/app/vmauth/auth_config.go#L130-L137
I'd like to suggest add flag for that. 

### Describe the solution you'd like

add flag for that.

**Comment by hagen1778** [comment]
Hello @SunKyu! If you'd have that flag, to what value will you set it and under what conditions?

**Comment by SunKyu** [comment]
@hagen1778 
Sorry to late reply 
There's some comment at this PR 

here's decription! 
```
brokenBackendBackoff
Sets a delay period for load balancing to skip a malfunctioning backend. (defaults 3s) 
```

**Comment by hagen1778** [comment]
Sorry for the late reply. I'd change my question a bit: to what value would you set `brokenBackendBackoff` in your installation. Is this a real-case scenario where you need override the default value, or it is a theoretical scenario where one would need to override the default value?

**Comment by SunKyu** [comment]
@hagen1778 
In my case, I usually do load balancing for two backend URLs, which are located in IDC1 and IDC2 respectively. 
Our system collect-interval of metrics is a minute basis in a push-based, for fast collection and alerting. 
When one IDC goes down(sometime it happens more than few minutes), there is a need to quickly process requests without making requests to the down IDC until next scrape time, so there's case when I wanted to increase it rather than the default 3 seconds.

**Comment by valyala** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth.html) gains support for `-failTimeout` command-line option starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
