### ISSUE TITLE
vmagent configuration 

### ISSUE THREAD

**Issue by rodkfoster** [VictoriaMetrics/VictoriaMetrics#4419]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

How do you configure vmagent to only scrape metrics from vmcluster components (vminsert, vmstorage, vmselect) including vmagent itself? We have tried deploying a VMServiceScrape CRD but vmagent is still scraping everything that's being exposed by prometheus.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by rodkfoster** [comment]
Hi @zekker6 , yes I am using VMOperator to deploy our VictoriaMetrics cluster including the vmagent component. Below you'll find my manifest for the vmagent which has `.spec.selectAllByDefault: false` .

`apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: o11y-vmagent
spec:
  selectAllByDefault: false
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  extraArgs:
    memory.allowedPercent: "40"
  remoteWrite:
  - url: http://vminsert-vmcluster.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
  replicaCount: 3
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 2000m
      memory: 1Gi
  statefulMode: true
  statefulStorage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
`

According to the documentation, it works in coordination with namespacesSelector and selector which is configured in a `VMServiceScrape` manifest. We tried that as well with the below setup and it also exhibited the same behavior. Is there something that I'm missing here?

`spec:
  endpoints:
    - port: http
  namespaceSelector:
    any: false
    matchNames: ["dev-devx-o11yvictoriametrics-usw2-qal"]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster
      monitored-by: vm-operator`

**Comment by zekker6** [comment]
@rodkfoster I think there is misunderstanding of how `namespaceSelector` and `selector` fields are used.
 `serviceScrapeNamespaceSelector` in `VMAgent.spec` is used to discover `VMServiceScrape` objects. While `namespaceSelector` at `VMServiceScrape` will be used to discover services which will be used to scrape metrics.

**Comment by zekker6** [comment]
Closing this as the question have been answered, feel free to reopen if this is still relevant for you.
