### ISSUE TITLE
vmstorage: downsampling configuration per series

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#4424]
### Is your feature request related to a problem? Please describe

There is a use-case where it is required to define different downsampling configurations for some series.
For example:
- Time-series A(raw data granularity 5min) --> -downsampling.period=21d:1h - deduplicate samples older than 21days with 1hr interval)
- Time-series B(raw data granularity 1min) --> -downsampling.period=3d:5m,21d:1h - deduplicate samples older than 3 days with 5min interval and samples older than 21days with 1hr interval)

### Describe the solution you'd like

It would be great if it would be possible to define a query which would match against series to apply downsampling similar to [retention filters](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#retention-filters).

### Describe alternatives you've considered

Currently, it is required to use one of:
- Setting up multiple clusters with different retention
- Setting up [streaming aggregation](https://docs.victoriametrics.com/stream-aggregation.html) and configuring aggregation for such series

**Comment by hagen1778** [comment]
Closing this FR in favor of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4960
