### ISSUE TITLE
[vmctl] vmctl container in Kubernetes Pod fail with error inappropriate ioctl for device

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#4432]
### Describe the bug

I created the k8s Job that does migrate data from VictoriaMetrics cluster version 1 to VictoriaMetrics cluster version 2 using `vmctl` tool. 
When the Pod (with vmctl container) is created, it's failed and shows an error message:
```
VictoriaMetrics Native import mode
2023/06/10 10:00:09 Initing export pipe from "http://cluster-1-vmselect.backend:8481/select/0:320/prometheus/api/v1/export/native" with filters: 
 filter: match[]={__name__!=""}
Initing import process to "http://cluster-2-vminsert.backend:8480/insert/0:320/prometheus/api/v1/import/native":
2023/06/10 10:00:09 error start process bars pool: error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
2023/06/10 10:00:09 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
```

### To Reproduce

Create a k8s Job with the yaml file that I attached. 
[jobs-vmctl.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/11712185/jobs-vmctl.zip)

### Version

K8s env version: v1.24.4
Container Runtime: cri-o 1.24.4
VictoriaMetrics cluster version: v1.87.6
vmctl version: v1.87.6

**Comment by dmitryk-dk** [comment]
Hi @tantm3 ! This issue was fixed int the [v1.90.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.90.0) release. And also it was improved and will be updated in the next release.PLease check this release [notes](https://docs.victoriametrics.com/CHANGELOG.html#tip). 
Related issues: 
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4081
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3823

**Comment by tantm3** [comment]
Hi @dmitryk-dk,

Thanks for your information!
Could you tell me if I can use vmctl version v1.90.0 with the VictoriaMetrics cluster version v1.87.6?

**Comment by dmitryk-dk** [comment]
Hi @tantm3 ! Yes, you can use it, there was no changes regarding migration process

**Comment by tantm3** [comment]
Thanks for your help!
I will close the issue here because it was solved already.

**Comment by IsQiao** [comment]
same issue, vmctl-20240425-150251-tags-v1.101.0-0-g5334f0c2c

**Comment by dmitryk-dk** [comment]
Hi @IsQiao , @hkmdxlftjf ! You are using the same approach? Can you share a little bit more information to identify the problem

**Comment by IsQiao** [comment]
context: i use supervisor to run victorial-metrics and vmctl in k8s pod container,
## supervisorctl output:

<img width="751" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8536046/fba97c4d-8c92-4d25-acd0-d86024d50630">

## supervisor config:
``` conf
[program:vm-migration]
command=/home/orion/vm-migration.sh
stdout_logfile=/var/log/vm-migration.log
directory=/home/orion
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
logfile_maxbytes=10MB
```
## command shell:
``` shell
#!/bin/bash

. ./scripts/lib_func.sh

echo "Start migrate prometheus data to victorial metrics"
echo "Log path: /var/log/vm-migration.log"

PROMETHEUS_DATA_DIR="/home/orion/prometheus"
MIGRATION_DONE="$PROMETHEUS_DATA_DIR/.migration_done"
VM_URL="http://127.0.0.1:9090"
VM_READY_URL="$VM_URL/-/ready"

max_tries=20
count=0

while ((count < max_tries))
do
    response=$(curl -o /dev/null -s -w "%{http_code}\n" $VM_READY_URL)

    if [ "$response" -eq 200 ]; then
        echo "The ready API check is successful, the returned status code is 200."
        break
    else
        echo "The ready API check failed, the returned status code is $response, retrying in 3 seconds."
        let "count++"
        sleep 3
    fi

    if ((count == max_tries)); then
        echo "Failed after 20 attempts."
        exit 1
    fi
done

if [ ! "$(ls -A $PROMETHEUS_DATA_DIR)" ]; then
    echo "Directory is empty or does not exist, no need to execute the script"
    exit 0
fi

if [ -f "$MIGRATION_DONE" ]; then
    echo "Data has already been successfully migrated, no need to execute the script again"
    exit 0
fi

vmctl prometheus -s --verbose=true --vm-disable-progress-bar=true --vm-addr="$VM_URL" --prom-snapshot="$PROMETHEUS_DATA_DIR"

if [ $? -eq 0 ]; then
    echo "Data migration successful"
    touch ""$MIGRATION_DONE""
else
    echo "Data migration failed"
fi
```
## error output:
``` shell
$ cat /var/log/supervisor/vm-migration-stderr---supervisor-kjtd19c2.log
2024/05/28 06:13:45 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
2024/05/28 06:13:46 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device

$ supervisorctl tail vm-migration
is successful, the returned status code is 200.
Prometheus import mode
Prometheus snapshot stats:
  blocks found: 14;
  blocks skipped by time filter: 0;
  min time: 1656064729389 (2022-06-24T09:58:49Z);
  max time: 1661248800000 (2022-08-23T10:00:00Z);
  samples: 1904716825;
  series: 24550.
Data migration failed
```

**Comment by dmitryk-dk** [comment]
> ## context
> i use supervisor to run victorial-metrics and vmctl in k8s pod container,
> 
> ## supervisorctl output:
> <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/8536046/334293375-fba97c4d-8c92-4d25-acd0-d86024d50630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzkzNjYsIm5iZiI6MTcxNjg3OTA2NiwicGF0aCI6Ii84NTM2MDQ2LzMzNDI5MzM3NS1mYmE5N2M0ZC04YzkyLTRkMjUtYWNkMC1kODYwMjRkNTA2MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDY1MTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE2ZmJjN2UwMmM5Y2M5MjI4Mzk1OTAwN2ExMTljZTJkZDU2ZjQ0ZmZmOGFmOTYzNTlmNmVjZDA3ZDFmNDVhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YsJlW0AWRCnM-rA6DgcdiHY8yJlhr90dbVsi6LaLP6c">
> ## supervisor config:
> ```
> [program:vm-migration]
> command=/home/orion/vm-migration.sh
> stdout_logfile=/var/log/vm-migration.log
> directory=/home/orion
> stdout_logfile_maxbytes=100MB
> stdout_logfile_backups=10
> logfile_maxbytes=10MB
> ```
> 
> ## command shell:
> ```shell
> #!/bin/bash
> 
> . ./scripts/lib_func.sh
> 
> echo "Start migrate prometheus data to victorial metrics"
> echo "Log path: /var/log/vm-migration.log"
> 
> PROMETHEUS_DATA_DIR="/home/orion/prometheus"
> MIGRATION_DONE="$PROMETHEUS_DATA_DIR/.migration_done"
> VM_URL="http://127.0.0.1:9090"
> VM_READY_URL="$VM_URL/-/ready"
> 
> max_tries=20
> count=0
> 
> while ((count < max_tries))
> do
>     response=$(curl -o /dev/null -s -w "%{http_code}\n" $VM_READY_URL)
> 
>     if [ "$response" -eq 200 ]; then
>         echo "The ready API check is successful, the returned status code is 200."
>         break
>     else
>         echo "The ready API check failed, the returned status code is $response, retrying in 3 seconds."
>         let "count++"
>         sleep 3
>     fi
> 
>     if ((count == max_tries)); then
>         echo "Failed after 20 attempts."
>         exit 1
>     fi
> done
> 
> if [ ! "$(ls -A $PROMETHEUS_DATA_DIR)" ]; then
>     echo "Directory is empty or does not exist, no need to execute the script"
>     exit 0
> fi
> 
> if [ -f "$MIGRATION_DONE" ]; then
>     echo "Data has already been successfully migrated, no need to execute the script again"
>     exit 0
> fi
> 
> vmctl prometheus -s --verbose=true --vm-disable-progress-bar=true --vm-addr="$VM_URL" --prom-snapshot="$PROMETHEUS_DATA_DIR"
> 
> if [ $? -eq 0 ]; then
>     echo "Data migration successful"
>     touch ""$MIGRATION_DONE""
> else
>     echo "Data migration failed"
> fi
> ```
> 
> ## error output:
> ```shell
> $ cat /var/log/supervisor/vm-migration-stderr---supervisor-kjtd19c2.log
> 2024/05/28 06:13:45 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
> 2024/05/28 06:13:46 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
> 
> $ supervisorctl tail vm-migration
> is successful, the returned status code is 200.
> Prometheus import mode
> Prometheus snapshot stats:
>   blocks found: 14;
>   blocks skipped by time filter: 0;
>   min time: 1656064729389 (2022-06-24T09:58:49Z);
>   max time: 1661248800000 (2022-08-23T10:00:00Z);
>   samples: 1904716825;
>   series: 24550.
> Data migration failed
> ```
> 
> ## version
> ```shell
> $ vmctl -v
> vmctl version vmctl-20240425-150251-tags-v1.101.0-0-g5334f0c2c
> ```

Thank you for your information. 
At that moment vmctl terminal check for the
```//go:build aix || linux || solaris || zos```
```//go:build darwin || freebsd || openbsd```
```//go:build windows```

There can be two options: you have a system which terminal can't be identified. Or something changes in the build.

Can you try to use v1.90.0? Does it works as expected?

**Comment by IsQiao** [comment]
> > ## context
> > i use supervisor to run victorial-metrics and vmctl in k8s pod container,
> > ## supervisorctl output:
> > <img alt="image" width="751" src="https://private-user-images.githubusercontent.com/8536046/334293375-fba97c4d-8c92-4d25-acd0-d86024d50630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzkzNjYsIm5iZiI6MTcxNjg3OTA2NiwicGF0aCI6Ii84NTM2MDQ2LzMzNDI5MzM3NS1mYmE5N2M0ZC04YzkyLTRkMjUtYWNkMC1kODYwMjRkNTA2MzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDY1MTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE2ZmJjN2UwMmM5Y2M5MjI4Mzk1OTAwN2ExMTljZTJkZDU2ZjQ0ZmZmOGFmOTYzNTlmNmVjZDA3ZDFmNDVhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YsJlW0AWRCnM-rA6DgcdiHY8yJlhr90dbVsi6LaLP6c">
> > ## supervisor config:
> > ```
> > [program:vm-migration]
> > command=/home/orion/vm-migration.sh
> > stdout_logfile=/var/log/vm-migration.log
> > directory=/home/orion
> > stdout_logfile_maxbytes=100MB
> > stdout_logfile_backups=10
> > logfile_maxbytes=10MB
> > ```
> > ## command shell:
> > ```shell
> > #!/bin/bash
> > 
> > . ./scripts/lib_func.sh
> > 
> > echo "Start migrate prometheus data to victorial metrics"
> > echo "Log path: /var/log/vm-migration.log"
> > 
> > PROMETHEUS_DATA_DIR="/home/orion/prometheus"
> > MIGRATION_DONE="$PROMETHEUS_DATA_DIR/.migration_done"
> > VM_URL="http://127.0.0.1:9090"
> > VM_READY_URL="$VM_URL/-/ready"
> > 
> > max_tries=20
> > count=0
> > 
> > while ((count < max_tries))
> > do
> >     response=$(curl -o /dev/null -s -w "%{http_code}\n" $VM_READY_URL)
> > 
> >     if [ "$response" -eq 200 ]; then
> >         echo "The ready API check is successful, the returned status code is 200."
> >         break
> >     else
> >         echo "The ready API check failed, the returned status code is $response, retrying in 3 seconds."
> >         let "count++"
> >         sleep 3
> >     fi
> > 
> >     if ((count == max_tries)); then
> >         echo "Failed after 20 attempts."
> >         exit 1
> >     fi
> > done
> > 
> > if [ ! "$(ls -A $PROMETHEUS_DATA_DIR)" ]; then
> >     echo "Directory is empty or does not exist, no need to execute the script"
> >     exit 0
> > fi
> > 
> > if [ -f "$MIGRATION_DONE" ]; then
> >     echo "Data has already been successfully migrated, no need to execute the script again"
> >     exit 0
> > fi
> > 
> > vmctl prometheus -s --verbose=true --vm-disable-progress-bar=true --vm-addr="$VM_URL" --prom-snapshot="$PROMETHEUS_DATA_DIR"
> > 
> > if [ $? -eq 0 ]; then
> >     echo "Data migration successful"
> >     touch ""$MIGRATION_DONE""
> > else
> >     echo "Data migration failed"
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## error output:
> > ```shell
> > $ cat /var/log/supervisor/vm-migration-stderr---supervisor-kjtd19c2.log
> > 2024/05/28 06:13:45 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
> > 2024/05/28 06:13:46 error when puts the terminal connected to the given file descriptor: inappropriate ioctl for device
> > 
> > $ supervisorctl tail vm-migration
> > is successful, the returned status code is 200.
> > Prometheus import mode
> > Prometheus snapshot stats:
> >   blocks found: 14;
> >   blocks skipped by time filter: 0;
> >   min time: 1656064729389 (2022-06-24T09:58:49Z);
> >   max time: 1661248800000 (2022-08-23T10:00:00Z);
> >   samples: 1904716825;
> >   series: 24550.
> > Data migration failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## version
> > ```shell
> > $ vmctl -v
> > vmctl version vmctl-20240425-150251-tags-v1.101.0-0-g5334f0c2c
> > ```
> 
> Thank you for your information. At that moment vmctl terminal check for the `//go:build aix || linux || solaris || zos` `//go:build darwin || freebsd || openbsd` `//go:build windows`
> 
> There can be two options: you have a system which terminal can't be identified. Or something changes in the build.
> 
> Can you try to use v1.90.0? Does it works as expected?

ok, i will try to use v1.90.0, wait for me about 15 minutes.

**Comment by IsQiao** [comment]
@dmitryk-dk same issue in v1.90
<img width="954" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8536046/d38a401f-6f44-4c74-8081-6ca4a9e184ad">

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk same issue in v1.90 <img alt="image" width="954" src="https://private-user-images.githubusercontent.com/8536046/334304264-d38a401f-6f44-4c74-8081-6ca4a9e184ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODA2NzcsIm5iZiI6MTcxNjg4MDM3NywicGF0aCI6Ii84NTM2MDQ2LzMzNDMwNDI2NC1kMzhhNDAxZi02ZjQ0LTRjNzQtODA4MS02Y2E0YTllMTg0YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMDcxMjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2MyNGQ3M2E5MWIxODMwMmJiM2VmNjA4ZTI0ZGI1MDU3ZDlmOTQ5YTZlMzkyOGVlYWEyZDljMzM0YjU0ZTJhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AiD9S3nI8b8urLfSPraBVwLWiiD2VTP_KKRIEGd2zbk">

So, probably we need to support some another system to check the terminal. Can you check what the system is used when you try to use vmctl?

**Comment by IsQiao** [comment]
> So, probably we need to support some another system to check the terminal. Can you check what the system is used when you try to use vmctl?

``` shell
$ cat /proc/version
Linux version 4.15.0-204-generic (buildd@lcy02-amd64-030) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #215-Ubuntu SMP Fri Jan 20 18:24:59 UTC 2023

$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
same output on launch script

**Comment by Melody-zyy** [comment]
> > So, probably we need to support some another system to check the terminal. Can you check what the system is used when you try to use vmctl?所以，我们可能需要支持另一个系统来检查终端。当你尝试使用vmctl时，你能检查一下系统使用的是什么吗？
> 
> $ cat /proc/version
> Linux version 4.15.0-204-generic (buildd@lcy02-amd64-030) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #215-Ubuntu SMP Fri Jan 20 18:24:59 UTC 2023
> 
> $ cat /etc/*release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=20.04
> DISTRIB_CODENAME=focal
> DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
> NAME="Ubuntu"
> VERSION="20.04.6 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.6 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> same output on launch script启动脚本上的输出相同


Have you solved the above issue? I have encountered the same issue.

**Comment by IsQiao** [comment]
use `--disable-progress-bar` flag to skip the problem.
