### ISSUE TITLE
Using time() with 'at' (@) modifier does not work

### ISSUE THREAD

**Issue by jait** [VictoriaMetrics/VictoriaMetrics#4440]
### Describe the bug

Making a query with the time function in at expression does not work. E.g. when querying for `my_metric @ (time() - time() % 86400)` I would expect to get the value of my_metric at previous midnight. Supplying a hardcoded value or an expression with constants works but using the time function does not.

Instead of evaluating the at modifier expression (and time function) for each sample time, the result seems to be always the same, as if `time()` is actually the same as `start()`.

### To Reproduce

1. Make a query like  `my_metric @ (time() - time() % 86400)`  or simply `my_metric @ time()` which should return the metric time series unmodified.
2. Observe the result

### Version

1.85.1

**Comment by Amper** [comment]
Hello @jait.
It's not a bug. `at` (`@`) modifier is calculated once before the query and then serves as a limit for query execution. It works same as Prometheus. In the case you mentioned, we would have to run the query for each timestamp separately - it will complicate the code and may cause performance problems.

**Comment by hagen1778** [comment]
@Amper should we transfer this issue from Enhancement to Question label?
