### ISSUE TITLE
share_eq_over_time

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#4441]
### Is your feature request related to a problem? Please describe

To complement `share_{gt|lt}_over_time`, having `share_eq_over_time` may be useful for series with discrete values.

### Describe the solution you'd like

There is a metric with value that is an enum or status.  I'd like to know the percent time in state X.

### Describe alternatives you've considered

I think it's possible with something like `count_eq_over_time() / total_points`, but same alternative exists for `share_gt_over_time` etc.

**Comment by Damon07** [comment]
I'd like to take this issue, can you assign it to me? @hagen1778

**Comment by hagen1778** [comment]
Thanks @Damon07 !

**Comment by hagen1778** [comment]
@belm0 support for `share_eq_over_time` was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4725
It will be included into the next release. Thanks to @Damon07 for the pull request!

**Comment by valyala** [comment]
The [share_eq_over_time](https://docs.victoriametrics.com/MetricsQL.html#share_eq_over_time) MetricsQL function is available in VictoriaMetrics starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
