### ISSUE TITLE
Datadog: add support for API v2 for metrics

### ISSUE THREAD

**Issue by pahaz** [VictoriaMetrics/VictoriaMetrics#4451]
### Is your question request related to a specific component?

DataDog

### Describe the question in detail

Hi. We want to use the VictoriaMetrics for DataDog agents. At the moment Victoria support only v1 API. And it looks like not all of our DataDog metrics presented in Victoria. For example, no any APM traces. 

Do you have any plans for datadog support? Do you need any help to add datadog v2 API support to the Victoria?

**Comment by Amper** [comment]
Hello @pahaz.
Before that, there were no requests for api/v2 support. I converted your issue to a feature request. We will try to consider it as resources become available. But we always welcome PR from users :)
Did I understand correctly that we are talking about [this API](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics)? I was a little confused by the wording "APM traces".

**Comment by hagen1778** [comment]
Currently, VM supports /api/v1 API for [metrics](https://docs.datadoghq.com/api/latest/metrics/). It would be great to support updates /api/v2 version of this API.

**Comment by a26nine** [comment]
> Currently, VM supports /api/v1 API for [metrics](https://docs.datadoghq.com/api/latest/metrics/). It would be great to support updates /api/v2 version of this API.

+1

**Comment by tstm** [comment]
Indeed this would be great to have!

**Comment by tstm** [comment]
@dmitryk-dk Have you done anything on this? Implementing this does not seem terribly complicated. I could perhaps whip up some kind of a PR for review for v2 metrics specifically, as this is what the datadog-agent natively pushes out at this point and without it, well, the datadog agent cannot send much of any metrics (other than just relaying the v1 metrics)

**Comment by dmitryk-dk** [comment]
HI @tstm ! Not yet. will take a look on it as soon as posibble

**Comment by tstm** [comment]
I did find a workardound though. Starting from DataDog Agent version 7.39 they have set the v2 series API as the default.

But there is an undocumented environment variable that can be set to disable v2 API, `DD_USE_V2_API_SERIES` can be set to false and we can again ingest data from datadog just fine. No guarantees of course on how long this will work, so the v2 api still probably should be implemented.

**Comment by a26nine** [comment]
> I did find a workardound though. Starting from DataDog Agent version 7.39 they have set the v2 series API as the default.
> 
> But there is an undocumented environment variable that can be set to disable v2 API, `DD_USE_V2_API_SERIES` can be set to false and we can again ingest data from datadog just fine. No guarantees of course on how long this will work, so the v2 api still probably should be implemented.

Thanks, this works! However, it will be still good to have v2 compatibility in Victoria Metrics.

**Comment by valyala** [comment]
FYI, the support for DataDog metrics ingestion via `/api/v2/series` (aka API v2) has been added in master branch - see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5094#issuecomment-1891051072 . It will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics and [vmagent](https://docs.victoriametrics.com/vmagent.html) gains support for DataDog v2 API for metrics' ingestion starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/#how-to-send-data-from-datadog-agent) for details. Closing this feature request as done.
