### ISSUE TITLE
vmselect: allow using unix timestamps in millisecond for query API

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4459]
### Is your feature request related to a problem? Please describe

VictoriaMetrics query API expects timestamp to be in a [certain format](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#timestamp-formats). This format is compatible with Prometheus API. However, this format expects timestamps in seconds, with milliseconds set after a floating point.
While in ingestion API it is allowed to use unix timestamps with millisecond precision without the need to use floating point.

See the related discussion here - https://stackoverflow.com/questions/76437098/how-to-handle-time-unit-and-step-while-ingesting-or-querying-in-victoriametrics/76438405

### Describe the solution you'd like

Would be nice for VM to extend query API and support unix timestamps with millisecond precision.

**Comment by valyala** [comment]
The commit b49d04b3dcfcd309270abd750cde96c3624c7aaa adds support for timestamps in milliseconds. This commit will be included in the next release. In the mean time it is possible to build VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it properly accepts timestamps in milliseconds at `start`, `end` and `time` query args as described [here](https://docs.victoriametrics.com/#timestamp-formats).

**Comment by valyala** [comment]
VictoriaMetrics accepts timestamps with millisecond precision at `start`, `end` and `time` query args of [Prometheus querying API](https://docs.victoriametrics.com/#prometheus-querying-api-usage) starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/#timestamp-formats) for more details.

Closing the feature request as done.
