### ISSUE TITLE
Delete data from VictoriaMetrics

### ISSUE THREAD

**Issue by varun-wadhwani** [VictoriaMetrics/VictoriaMetrics#4463]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

I have my VictoriaMetrics setup hosted in AKS(Azure Kubernetes) cluster.

I am able to select and insert data into it using the following curl commands,

**For selecting the data,**
curl -G -v https://my_url/select/0/prometheus/api/v1/export -d 'match={__name__!="*"}' 

**For inserting the data,**
curl -d '{"metric":{"__name__":"foo","job":"node_exporter"},"values":[0,1,2],"timestamps":[1549891472010,1549891487724,1549891503438]}' -X POST 'https://my_url/insert/0/prometheus/api/v1/import'

But I am not able to find a proper endpoint for deleting the data,

I have inserted a test_metrics data and trying to delete it now. I have used following commands till now but I am unable to delete the data,

curl -v https://my_url/delete/0/prometheus/api/v1/admin/tsdb/delete_series -d 'match[]=test_metrics
curl -v https://my_url/delete/0/prometheus/api/v1/admin/tsdb/delete_series -d 'match={__name__="test_metrics"}'
 
**Error I am getting -**

**502 Bad Gateway**

Can anyone please help me with the correct end point for deleting the data from VictoriaMetrics?

 

 
 
 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello, what version do you use for vmselect and did you set up some proxy in front of "my_url"?
For me, both ways worked and returned code 204 like the [doc](https://docs.victoriametrics.com/url-examples.html#apiv1admintsdbdelete_series) said.
curl -v 'http://{{vmselect}}/delete/0/prometheus/api/v1/admin/tsdb/delete_series?match[]=node_boot_time_seconds'
curl -v http://{{vmselect}}/delete/0/prometheus/api/v1/admin/tsdb/delete_series -d 'match[]=node_boot_time_seconds'

**Comment by hustchihieu143** [comment]
i used this curl to delete data, response is HTTP/1.1 204 No Content Date: Fri, 28 Jul 2023 03:00:23 GMT, but data is not deleted

**Comment by Haleygo** [comment]
> i used this curl to delete data, response is HTTP/1.1 204 No Content Date: Fri, 28 Jul 2023 03:00:23 GMT, but data is not deleted

@hustchihieu143 Can you get results from `curl -s 'http://vmselect:8481/select/0/prometheus/api/v1/series?match[]=<delete-series>' | jq` before delete them? Can you paste the curl delete command?

**Comment by hagen1778** [comment]
@hustchihieu143 have you tried the suggest by @Haleygo  way to verify matcher correctness?

**Comment by hagen1778** [comment]
Closing as inactive.
