### ISSUE TITLE
Support recording rules

### ISSUE THREAD

**Issue by weenxin** [VictoriaMetrics/VictoriaMetrics#447]
**Describe the solution you'd like**
`vmagent` or `vmalert` and recording rules fetature.

**vmalert need alertmanager as requried param**

For some situation. We just want to record the value, not for alert.

**Additional context**
Prometheus supported two kinds or rules : recording rules and alerting rules. 

`Recording rules allow you to precompute frequently needed or computationally expensive expressions and save their result as a new set of time series. Querying the precomputed result will then often be much faster than executing the original expression every time it is needed. This is especially useful for dashboards, which need to query the same expression repeatedly every time they refresh.`

This is Promethes recording rule description. 

Will we support this future in any components?

**Comment by hagen1778** [comment]
duplicated #346

**Comment by valyala** [comment]
FYI, recording rules are supported by [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/README.md) starting from [v1.37.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
