### ISSUE TITLE
Resource Usage Panel: add network overview graphs 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4478]
### Is your feature request related to a problem? Please describe

We need to add the following panels to the Resource Usage tab in VictoriaMetrics dashboards (single and cluster)

- the number of open TCP connections  - metric `vm_tcplistener_conns`
- the churn rate of TCP connections  - the rate of `vm_tcplistener_accepts_total`
- read and written data over TCP connections - the rate of `vm_tcplistener_read_bytes_total` and `vm_tcplistener_written_bytes_total` metrics

We need to define the correct name for the panels as far as they cover only incoming connection

### Describe the solution you'd like

new panels on dashboards

**Comment by hagen1778** [comment]
Requested panels were added to VM single-server and Cluster versions of VM. Updated versions are available at https://grafana.com/orgs/victoriametrics/dashboards.
Closing this ticket as done.
