### ISSUE TITLE
How to change the compressionLevel

### ISSUE THREAD

**Issue by karanrk** [VictoriaMetrics/VictoriaMetrics#4496]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I would like to know what is the default compressionLevel and how can I change it per my requirements without having to rebuild binaries.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @karanrk 
Could you elaborate which compression you need to adjust?

At the moment, you can only adjust compression level for [native protocol](https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol) of vmagent by using the following flag:
```
  -remoteWrite.vmProtoCompressLevel int
     The compression level for VictoriaMetrics remote write protocol. Higher values reduce network traffic at the cost of higher CPU usage. Negative values reduce CPU usage at the cost of increased network traffic. See https://docs.victoriametrics.com/vmagent.html#victoriametrics-remote-write-protocol
```

**Comment by zekker6** [comment]
Closing this as original question have been answered, feel free to reopen if you will have more questions.
