### ISSUE TITLE
vmalert: add metric for measuring remote-write path saturation

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4516]
### Is your feature request related to a problem? Please describe

vmagent has metric named `vmagent_remotewrite_send_duration_seconds_total`. It measure the time vmagent spends while pushing data to remote storage. If rate over this metric exceeds 1, it means connection to remote storage is saturated and vmagent can't keep up with the ingestion for various reasons.

vmalert doesn't have such metric.

### Describe the solution you'd like

Would be great to add `vmalert_remotewrite_send_duration_seconds_total` metric for vmalert, so we can check the remote-write connection saturation.

**Comment by hagen1778** [comment]
New metric `vmalert_remotewrite_send_duration_seconds_total ` was added to vmalert in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4517 and will be available in the next release.

**Comment by valyala** [comment]
The `vmalert_remotewrite_send_duration_seconds_total` metric is exposed by `vmalert` at [`/metrics`](https://docs.victoriametrics.com/vmalert.html#monitoring) page starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
