### ISSUE TITLE
vmstorage doesn't deduplicate some metrics

### ISSUE THREAD

**Issue by perederyaev** [VictoriaMetrics/VictoriaMetrics#4519]
### Describe the bug

if run vmstorage with "-dedup.minScrapeInterval 1m" and push metrics with scrape_interval 30 seconds(vmagent -> vminsert -> vmstorage) in export output (http://127.0.0.1:8481/select/0/prometheus/api/v1/export -d 'match[]=node_memory_Dirty_bytes') we see some metrics with 30s interval:

**Timestamp    -   Diff**      
1687627196071 60000
1687627256071 60000
1687627316071 60000
1687627376071 60000
1687627436071 60000
1687627496071 60000
1687627556071 60000
1687627616071 60000
1687627676071 60000
**1687627706071 30000
1687627736071 30000**
1687627796071 60000
1687627856071 60000
1687627916071 60000
1687627976071 60000
1687628036071 60000
1687628096071 60000
1687628156071 60000
1687628216071 60000
1687628276071 60000
1687628336071 60000
1687628396071 60000
**1687628426071 30000
1687628456071 30000**
1687628516071 60000
1687628546071 30000
1687628576071 30000
1687628636071 60000
**1687628666071 30000
1687628696071 30000**
1687628756071 60000
**1687628786071 30000
1687628816071 30000**
1687628876071 60000
1687628906071 30000
1687628936071 30000
1687628996071 60000

if run vmstorage with "-dedup.minScrapeInterval 1h" and have scrape_interval 30 seconds in export output we see some metrics also with interval less than 1h:

1687370379736 3600000
1687373979736 3600000
1687377579736 3600000
**1687379829736 2250000
1687381179736 1350000**
1687384779736 3600000
1687388379736 3600000
1687391979736 3600000
1687395579736 3600000
1687399179736 3600000
1687402779736 3600000
1687406379736 3600000
1687409979736 3600000
1687413579736 3600000
1687417179736 3600000

### To Reproduce

Run vmstorage with -dedup.minScrapeInterval option push metrics to it and check export output for raw metrics.

### Version

vmstorage-20230518-231045-tags-v1.87.6-cluster-0-g468cd5f7b
vmstorage-20230602-113236-tags-v1.91.2-cluster-0-ga1b6a9317

### Logs

no errors or warnings

**Comment by perederyaev** [comment]
Hello,

Looks like having metrics with not constant timestamp interval causes skips on graphics.
Does vmselect guarantee correct deduplication according dedup.minScrapeInterval?

**Comment by Amper** [comment]
> Does vmselect guarantee correct deduplication according dedup.minScrapeInterval?

As far as i know - yes, it does. 
But it won't protect you from skips.
