### ISSUE TITLE
The query executed takes much longer than the specified maxQueryDuration.

### ISSUE THREAD

**Issue by just1900** [VictoriaMetrics/VictoriaMetrics#4520]
### Describe the bug

Query executed by vmselect takes about 14 minutes, which is much longer than the value of `-search.maxQueryDuration`, we use the default value of `maxQueryDuration`.

### To Reproduce

No idea how to reproduce it yet.

### Version

v1.82.1-cluster

### Logs

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16233178/d1c7f4e7-6750-4f7c-b85a-7197c65fa807)

### Screenshots

The issue is observed as these 4 requests filled up the concurrent select (with capacity = 4), which in turn limited other requests.(19:57~20:10)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16233178/4acf2bff-1965-4393-bd32-011852e485ad)

Only one replica of vmselect is affected, causing it to behave as if it were paused.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16233178/522da8cd-1f84-4117-8ad4-54828b17d87b)

### Used command-line flags

 Here are the flags for vmselect.
```
    - -cacheDataPath=/select-cache
    - -dedup.minScrapeInterval=1ms
    - -httpListenAddr=:8481
    - -selectNode=vmselect-vmcluster-0.vmselect-vmcluster.observability:8481,vmselect-vmcluster-1.vmselect-vmcluster.observability:8481,vmselect-vmcluster-2.vmselect-vmcluster.observability:8481
    - -storageNode=vmstorage-vmcluster-0.vmstorage-vmcluster.observability:8401,vmstorage-vmcluster-1.vmstorage-vmcluster.observability:8401,vmstorage-vmcluster-2.vmstorage-vmcluster.observability:8401,vmstorage-vmcluster-3.vmstorage-vmcluster.observability:8401,vmstorage-vmcluster-4.vmstorage-vmcluster.observability:8401
```

### Additional information

The resource usage of vmstorage and vmselect is normal.

**Comment by Amper** [comment]
Hi @just1900.
Could you [provide trace](https://docs.victoriametrics.com/#query-tracing) for these queries?

**Comment by just1900** [comment]
Unfortunately, the query trace wasn't turned on, and I can not reproduce it now.
The promql is 

```
      container_memory_working_set_bytes{ image!=""}
      * on (namespace, pod) group_left(node) topk by(namespace, pod) (1,
        max by(namespace, pod, node) (kube_pod_info)
      )
```

Do you guys have any clue about this?

**Comment by Amper** [comment]
@just1900 I'm afraid that without understanding how the request was executed, it's too difficult to figure out the reasons. I am couldn't to reproduce this issue on our environments.
