### ISSUE TITLE
vmauth: expose request duration metrics per users

### ISSUE THREAD

**Issue by Sin4wd** [VictoriaMetrics/VictoriaMetrics#4522]
### Is your feature request related to a problem? Please describe

We sometime observe high latency on our queries based on storage metrics, but we cannot drill down the problem to specific vmuser facing these issues.

### Describe the solution you'd like

vmauth expose these metrics
```
vmauth_user_http_request_duration_seconds_bucket
vmauth_user_http_request_duration_seconds_sum
vmauth_user_http_request_duration_seconds_count
```

### Describe alternatives you've considered

- We can setup one vmauth per user which is not really a solution.
- We can replace vmauth with an nginx.

### Additional information

I would be glad to develop this feature if I can get some hints.

**Comment by f41gh7** [comment]
Linked PR added `vmauth_user_request_duration_seconds` metric with summary metric type.
