### ISSUE TITLE
Add keep_firing_for rule parameter to vmalert for feature parity with Prometheus

### ISSUE THREAD

**Issue by jstaffans-relex** [VictoriaMetrics/VictoriaMetrics#4529]
### Describe the solution you'd like

Since version 2.42.0, Prometheus has a new `keep_firing_for` alert rule parameter that can help with reducing alert flappiness. It would be great to have this functionality in vmalert as well.

https://github.com/prometheus/prometheus/pull/11827

**Comment by valyala** [comment]
The `keep_firing_for` option is available in [vmalert](https://docs.victoriametrics.com/vmalert.html) starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
