### ISSUE TITLE
vmselect pod restart 

### ISSUE THREAD

**Issue by BigbigY** [VictoriaMetrics/VictoriaMetrics#4537]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

{"ts":"2023-06-28T09:16:18.439Z","level":"panic","caller":"VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:164","msg":"FATAL: cannot unmarshal data at offset 1697, size 94, tbfIdx 0: cannot unmarshal blockHeader: RowsCount in block header cannot be zero"}

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@BigbigY Could you elaborate on:
- what is cluster version is used?
- is this panic reproducible or it happens occasionally?

This error means that vmselect was not able to decode response received from vmstorage node. This can either be a bug at vmstorage side or an issue with data in transit(e.g., a network glitch).

**Comment by BigbigY** [comment]
@zekker6 
version:v1.88.1-cluster
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16998173/7836e512-f862-4264-ba87-1d77f1065da9)

**Comment by Sin4wd** [comment]
We are facing same issue on version 1.89.1
I'm trying to reproduce the problem but it's not that obvious. Do you have any suggestions?

**Comment by zekker6** [comment]
@BigbigY @Sin4wd Could you please also provide a list of flags set for vmselect?

**Comment by Sin4wd** [comment]
All off flags
```
-httpListenAddr=:8481
-search.logSlowQueryDuration=5s
-search.maxConcurrentRequests=15
-search.maxQueryDuration=30s
-search.maxQueryLen=20000
-search.maxQueueDuration=20s
-search.maxUniqueTimeseries=2500000
-selectNode=vmselect-mt-0.vmselect-mt.monitoring-system:8481,vmselect-mt-1.vmselect-mt.monitoring-system:8481,vmselect-mt-2.vmselect-mt.monitoring-system:8481
-storageNode=vmstorage-mt-0.vmstorage-mt.monitoring-system:8401,vmstorage-mt-1.vmstorage-mt.monitoring-system:8401,vmstorage-mt-2.vmstorage-mt.monitoring-system:8401
```

**Comment by BigbigY** [comment]
extraArgs:
      dedup.minScrapeInterval: 30s
      search.maxConcurrentRequests: "16"
      search.maxQueueDuration: "20s"
      search.maxLookback: 10m
      search.maxFederateSeries: "20000000"
      search.maxExportSeries: "20000000"
    cacheMountPath: /cache
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2G

**Comment by BigbigY** [comment]
/vmselect-prod -cacheDataPath=/cache -dedup.minScrapeInterval=30s -httpListenAddr=:8481 -loggerFormat=json -search.maxConcurrentRequests=16 -search.maxExportSeries=20000000 -search.maxFederateSeries=20000000 -search.maxLookback=10m -search.maxQueueDuration=20s -selectNode=vmselect-vmcluster-0.vmselect-vmcluster.monitoring:8481,vmselect-vmcluster-1.vmselect-vmcluster.monitoring:8481,vmselect-vmcluster-2.vmselect-vmcluster.monitoring:8481,vmselect-vmcluster-3.vmselect-vmcluster.monitoring:8481,vmselect-vmcluster-4.vmselect-vmcluster.monitoring:8481 -storageNode=vmstorage-vmcluster-0.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-1.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-2.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-3.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-4.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-5.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-6.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-7.vmstorage-vmcluster.monitoring:8401,vmstorage-vmcluster-8.vmstorage-vmcluster.monitoring:8401

**Comment by zekker6** [comment]
In order to improve query speed vmselect saves temporary search results in disk.
An error mentioned in the issue can only happen when vmselect reads data from disk cache and can't decode this data.

This can happen in the following cases:
-  there is some issue with an underlying storage 
- if those files are modified by some other program running on the same host
- vmselect was terminated in the middle of writing file contents

To avoid the last case I would suggest to clear cache directory to make sure there are no corrupted files stored.

@BigbigY in case vmselect is running in k8s I would recommend to check if PVCs were having any issues at the same time when vmselect had those issues.

@Sin4wd Based on provided flags I can see that `-cacheDataPath` is not set, in this case vmselect will use OS default tmp directory. Is there any chance that something on server can modify data which is stored there?
It would be great if you could configure `-cacheDataPath` to point at location on disk which will be dedicated to vmselect cache and check if it helps.

**Comment by Sin4wd** [comment]
I'm using k8s too and don't think something else caused the problem. However, unexpected terminations are probable, but it should recover from the corrupted cache, shouldn't it? 
I'm using `terminationGracePeriodSeconds: 30` is that enough?
About the cache, I usually use local disk for performance reasons and persisting cache sacrifices stateless nature and mobility of our VMselects, but I will definitely try specifying cache dir and share the results.

I was collecting logs and captured this panic today. Is this relevant to your guess?
```
Panic	VictoriaMetrics/lib/fs/reader_at.go:52	off=12587847 is out of allowed range [0...8388142] for len(p)=648
vmselect panic: off=12587847 is out of allowed range [0...8388142] for len(p)=648
vmselect
vmselect goroutine 99190 [running]:
vmselect github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x9950882023-07-19T11:51:23.968988860+03:30 , 0x5}, {0xc0653a04b0, 0x41}, 0x3?)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
vmselect github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x995088, 0x5}, {0x9b3ecb?, 0xc075f9f45d?}, {0xc000d6d9c0?, 2023-07-19T11:51:23.969024226+03:30 0x3a3?, 0x2?})
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
vmselect github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:130
vmselect github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:126
vmselect github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.(*ReaderAt).MustReadAt(0xc032bdf9c0, {0xc075f9f400, 0x288, 0xc0223aa4e0?}, 0xc01347)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go:52 +0x1b0
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*tmpBlocksFile).MustReadBlockAt(0xc047c35c50, 0x3?, {0xc01347, 0x288, 0x0})
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/tmp_blocks_file.go:159 +0x1fd
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*sortBlock).unpackFrom(0xc01543b240, 0xc063324e00, {0xc0814d82b8?, 0xc00ac159e02023-07-19T11:51:23.969158377+03:30 ?, 0xc000d6dca8?}, {0xd?, 0xc000d6dc18?, 0x46ca67?}, {0x1896cc99ea02023-07-19T11:51:23.969186207+03:30 , 0x1896d3c0f80})
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:718 +0xa8
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*unpackWork).unpack(0xc03b297ec0, 0x76c840?2023-07-19T11:51:23.969217127+03:30 )
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:379 +0xaa
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*packedTimeseries).unpackTo(0xc0b81b00a0, {2023-07-19T11:51:23.969245804+03:30 0xc08f78cf00, 0x0, 0x20}, {0xc0814d82b8, 0x3, 0x3}, {0xc006fca0002023-07-19T11:51:23.969292498+03:30 ?, 0xc00002f400?})
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:496 +0x2ab
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*packedTimeseries).Unpack(0xc0b81b00a0, 0xc01c828a80, {0xc0814d82b8, 0x3, 0x3}, {0xc000d6dec82023-07-19T11:51:23.969321362+03:30 ?, 0x4075b8?})
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:465 +0x21b
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*timeseriesWork).do(0xc056ab0e80, 0xc01c828a802023-07-19T11:51:23.969349331+03:30 , 0x0?)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:138 +0x77
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.timeseriesWorker(0xc000000240?, {0xc03d0cf4402023-07-19T11:51:23.969375983+03:30 , 0x5, 0x5}, 0x4)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:160 +0x130
vmselect github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*Results).runParallel.func2(2023-07-19T11:51:23.969403102+03:30 0xc000d6dfb8?)
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go:326 +0x3d
vmselect created by github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*Results).runParallel
vmselect 	github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go2023-07-19T11:51:23.969432405+03:30 :325 +0x6cd

```

**Comment by Sin4wd** [comment]
Moreover I'm using memory for the /tmp is that a bad idea?
```
    volumeMounts:
    - mountPath: /tmp
      name: tmpfs
    volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 4Gi
      name: tmpfs
 ```
 and I also reduced `memory.allowedPercent` to  `50` today. It might help.

**Comment by Sin4wd** [comment]
After upgrading to 1.92.1, I have not seen the issue yet but I'm not sure if it's resolved. I will keep you updated.

**Comment by Sin4wd** [comment]
I have not seen the issue since the update.

**Comment by zekker6** [comment]
@Sin4wd Thank you for the feedback. I'm going to close an issue as resolved as it does not reproduce with the newer version, but feel free to reopen if this will occur again.

**Comment by just1900** [comment]
I am still experiencing the issue in v1.97.1. Do I need to set `-rpc.disableCompression` to true to resolve it?
@zekker6 @hagen1778 PTAL, thks

**Comment by hagen1778** [comment]
@just1900 the error seems like data corruption. But I am not sure where it happens: on storage, during network transition, or when vmselect tries to read it from the disk. Compression disabling should rule out the network, so please try it.

How frequently does it happen? Have you read prev discsussion and has somthing to add to discussed possibilities?

**Comment by just1900** [comment]
This is the first time I've encountered this issue. I suspect it may be related to the cache disk.
Could a large request or something consume the entire cache volume of vmselect and potentially cause corruption?

![Image](https://github.com/user-attachments/assets/993db12e-2667-4a49-9f56-75048a8d775b)

I have already expanded this disk and will observe for a period of time.

**Comment by hagen1778** [comment]
> Could a large request or something consume the entire cache volume of vmselect and potentially cause corruption?

It might be. Are there more restarts close to the moment when you get this error? 
Let's try bumping pvc size to 10GiB (recommended value) and see if issue still remains after some time.
