### ISSUE TITLE
Can Prometheus be fully replaced by VictoriaMetrics?

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#4540]
### Is your question request related to a specific component?

VictoriaMetrics, vmagent, vmalert

### Describe the question in detail

Currently I have setup a Prometheus server to pull metrics from several VictoriaMetrics instances which in turn store metrics scraped from several vmagents. The metrics are then visuzalized through Grafana which is connected to said Prometheus Server.
Is there a way I can replace this Prometheus Server, if so how?

I also have vmalert instances running at the vmagent level, vmagents are gathering metrics from Node Exporters, how can I can coordinate the various vmalert instances so that alerts are triggered as soon as possible instead of having to wait for them to reach the Prometheus Server previously mentioned?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @DaRealCapz 
You can scrape metrics from VictoriaMetrics instances with [single-node](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html) installation of VictoriaMetrics, so it will replace Prometheus.

Could you elaborate on why are you pulling metrics from VictoriaMetrics instances into Prometheus at the first place and what kind of installation do you have?
You can query data with Grafana directly from VictoriaMetrics, same applies to vmalert.

**Comment by hagen1778** [comment]
@DaRealCapz see also following docs:
* https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter
* https://docs.victoriametrics.com/#grafana-setup
* https://docs.victoriametrics.com/#alerting

In short, you can scrape, store, visualize and alert on metrics with VictoriaMetrics components only.

**Comment by zekker6** [comment]
Closing this as original question have been answered, feel free to reopen if you will have more questions.

**Comment by DaRealCapz** [comment]
> Hi @DaRealCapz You can scrape metrics from VictoriaMetrics instances with [single-node](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html) installation of VictoriaMetrics, so it will replace Prometheus.
> 
> Could you elaborate on why are you pulling metrics from VictoriaMetrics instances into Prometheus at the first place and what kind of installation do you have? You can query data with Grafana directly from VictoriaMetrics, same applies to vmalert.

![proposta](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/ba1411a1-0634-4698-8488-89c763c1607d)

My goal is to implement a system with this display, but I am not sure if I could replace the top level Prometheus instance. If so, any tips on how to do it?

**Comment by hagen1778** [comment]
@DaRealCapz it is unclear from your diagram why you need Prometheus there.
Grafana can "talk" to VictoriaMetrics directly. And for rules execution you already have vmalert on the scheme. So I don't understand what "work" Prometheus is doing here.
