### ISSUE TITLE
vmctl fails to write to vminsert

### ISSUE THREAD

**Issue by boufleur** [VictoriaMetrics/VictoriaMetrics#4546]
### Is your question request related to a specific component?

vmctl

### Describe the question in detail

While trying to import data from Prometheus using remote read api, `vmctl` fails when trying to reach` vminsert`:

```shell
./vmctl-prod remote-read \
  --remote-read-src-addr=http://prometheus-k8s-0.monitoring.svc.cluster.local:9090 \
  --remote-read-filter-time-start=2021-10-18T00:00:00Z \
  --remote-read-step-interval=hour 
  --vm-addr=http://vminsert-vmcluster.victoriametrics.svc.cluster.local:8480/insert/0/prometheus \
  --vm-concurrency=6
2023/06/30 14:58:49 failed to create VM importer: ping to "http://vminsert-vmcluster.victoriametrics.svc.cluster.local:8480/insert/0/prometheus" failed: bad status code: 400
```

According to the [docs](https://docs.victoriametrics.com/vmctl.html#migrating-data-by-remote-read-protocol), we should use the path `/insert/0/prometheus`, however, I see the following error on `vminsert`:

```
2023-06-30T15:05:20.391Z        warn    VictoriaMetrics/lib/httpserver/httpserver.go:346        remoteAddr: "172.16.167.30:52850"; requestURI: /insert/0/prometheus/health; unsupported path requested: "/insert/0/prometheus/health"
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by uhthomas** [comment]
I am also struggling with this. The help page suggests an additional flag may help, but I get #4553 if I use that.

```sh
   --vm-addr vmctl                     VictoriaMetrics address to perform import requests.
      Should be the same as --httpListenAddr value for single-node version or vminsert component.
      When importing into the clustered version do not forget to set additionally --vm-account-id flag.
      Please note, that vmctl performs initial readiness check for the given address by checking `/health` endpoint. (default: "http://localhost:8428")
```

```ah
--vm-account-id value  AccountID is an arbitrary 32-bit integer identifying namespace for data ingestion (aka tenant).
      AccountID is required when importing into the clustered version of VictoriaMetrics.
      It is possible to set it as accountID:projectID, where projectID is also arbitrary 32-bit integer.
      If projectID isn't set, then it equals to 0
```

**Comment by boufleur** [comment]
@uhthomas thank you for your message. My `--vm-addr` was wrong. `vmctl` was unable to reach the `/health` endpoint, as stated in the logs. Once I fixed that and properly set `--vm-account-id`, I could start the ingestion as expected.

**Comment by Saigut** [comment]
> @uhthomas thank you for your message. My `--vm-addr` was wrong. `vmctl` was unable to reach the `/health` endpoint, as stated in the logs. Once I fixed that and properly set `--vm-account-id`, I could start the ingestion as expected.

I met the same problem. --vm-addr seems should like "http://vminsert-my-victoria-metrics-k8s-stack:8480", just have no path suffix. I can run the migration with parameters like below:
```
/vmctl-prod remote-read --remote-read-src-addr=http://my-kube-prometheus-stack-prometheus:9090 --vm-addr=http://vminsert-my-victoria-metrics-k8s-stack:8480/ --remote-read-use
-stream=true --remote-read-filter-time-start=2021-10-18T00:00:00Z --remote-read-step-interval=hour --vm-account-id=0 --verbose=true --remote-read=true
```
