### ISSUE TITLE
Is it "VictoriaMetrics" or "Victoria Metrics"? 

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/VictoriaMetrics#4547]
### Describe the question in detail

Apologies for the seemingly silly question, but is it "VictoriaMetrics" or "Victoria Metrics"? Is it both? Does it change depending on context? 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @uhthomas!
It is "VictoriaMetrics".

> Does it change depending on context?

Not, from what I know. Why would you ask?

**Comment by uhthomas** [comment]
Thanks!

I was asking because I was struggling to know how I should be naming resources. There are quite a few results for both kinds in this repo.

https://github.com/search?q=repo%3AVictoriaMetrics%2FVictoriaMetrics%20%22Victoria%20Metrics%22&type=code (14)

https://github.com/search?q=repo%3AVictoriaMetrics%2FVictoriaMetrics+%22victoria-metrics%22&type=code (113)

**Comment by hagen1778** [comment]
@uhthomas it is "VictoriaMetrics', as the first sentence of https://docs.victoriametrics.com/ suggests.

Verbally you can use both `VictoriaMetrics` or `Victoria Metrics`.

In resource naming sometimes there are conventions, like not using uppercase. So this may result in using `victoria-metrics` or `victoriametrics`.
