### ISSUE TITLE
vmselect sometimes returns wrong metrics

### ISSUE THREAD

**Issue by anesterov-joom** [VictoriaMetrics/VictoriaMetrics#455]
**Describe the bug**
vmselect sometimes returns wrong metrics

**To Reproduce**
Maybe it's reproducible only on our dataset, we don't know (corrupted data?)

**Expected behavior**
vmselect should return only queried metrics

**Example**
query:
```
cassandra_stats{name="org:apache:cassandra:metrics:clientrequest:read:latency:oneminuterate"}
```
may returns another metrics, not only `cassandra_stats`:
```
ProductIndexFromService_productService_getProductInfo_bucket...
PhoenixAnalyticsAccess_statsByCampaign_phoenix_query_bucket...
PhoenixAnalyticsAccess_statsByCampaign_phoenix_query_bucket...
PhoenixAnalyticsAccess_statsByCampaign_access_total_bucket...
storage_operation_duration_seconds_count...
kernel_context_switches...
executor_seconds_count...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
cassandra_stats...
system_n_cpus...
```
Sometimes it reproduced with other metrics names.

**Version**
v1.32.8-cluster

**Comment by valyala** [comment]
This issue should be already fixed in `v1.34.4` - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/360 . I'd recommend upgrading to the latest available release from [the releases page](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
