### ISSUE TITLE
Is there a way to use vmselect as something like promxy?

### ISSUE THREAD

**Issue by Sin4wd** [VictoriaMetrics/VictoriaMetrics#4551]
### Is your question request related to a specific component?

vmselect,vmsingle,vmstorage

### Describe the question in detail

There is a great tool promxy in prometheus world. Sometimes we need to combine data from multiple vmsingle/vmstorage. For example when we want to migrate a vmsingle to another location or when we use another vmsingle for recording rules and we want to query them both.
I have found a [rotten issue](https://github.com/jacksontj/promxy/issues/253) on promxy that has no updates. Yet I was reading vmselect code and it solves our problem for combining vmstorages. I was wondering if there is a way that vmsingle exposes similar api to vmselect that we can use vmselect as a promxy? Should I write a feature request?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Sin4wd** [comment]
@valyala I have seen your comment on multilevel vmselect [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1767). Do you have plans to support a similar api on vmsingle too?
It ends the long running lack of promxy for metricsql.

**Comment by Sin4wd** [comment]
I will elaborate on the use-case and it might interest someone:
The idea is to have multi zone monitoring system like in [this document](https://sre.google/sre-book/practical-alerting/#fig_borgmon_dataflow).
First consider we have one giant metric store that knows everything:
- cardinality is an issue
- query isolation is poor
- /api/v1/labels timeouts with matchers
- alerts rely on a central infrastructure
simply it does not scale that much and if it scales it is not reliable.
 Being able to have multiple smaller storages as well as the aggregated view:
- allows multi k8s-cluster setups. you can have a local storage for each cluster as well as having an aggregated view through this tool.
- Having local storage for each domain helps with reliability as in network outages or so.
- any cardinality boom remains a local problem and does not affect all.
- alerts can be calculated locally and fire without relying on a central infrastructure.

For anyone who may want to :
There is a workaround here, and it is to use vmcluster and configure multi level vmselects instead of promxy / vmsingle. It comes at multiple costs but It is worth trying.

**Comment by jiekun** [comment]
Hi @Sin4wd For the original question, I thin you've found the answer using [Multi-level cluster setup](https://docs.victoriametrics.com/cluster-victoriametrics/#multi-level-cluster-setup). I believe VictoriaMetrics Single-Node is not designed for complex deployment architecture, and it does not support multi-level query now.

**Comment by valyala** [comment]
FYI, vmselect can query other vmselect nodes starting from v1.79.0 release. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2778 for details.

We are going to add support of querying multiple single-node VictoriaMetrics instances from vmselect - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4328
