### ISSUE TITLE
Basic Auth. support in Cluster version

### ISSUE THREAD

**Issue by gcotone** [VictoriaMetrics/VictoriaMetrics#456]
**Is your feature request related to a problem? Please describe.**
HTTP endpoints in the cluster version do not support basic authentication

**vmstorage**
```bash
flag provided but not defined: -httpAuth.username      
vmstorage-20200427-222230-tags-v1.35.0-cluster-0-g50af16ba
```
**vmselect**
```
flag provided but not defined: -httpAuth.username     
vmselect-20200427-221955-tags-v1.35.0-cluster-0-g50af16ba
```
**vminsert**
```
flag provided but not defined: -httpAuth.username              
vminsert-20200427-221639-tags-v1.35.0-cluster-0-g50af16ba
```

**Describe the solution you'd like**
Single node version supports basic-auth as described [here](https://github.com/VictoriaMetrics/VictoriaMetrics#security)
For feature parity, at least basic auth should be implemented in the same way for all http endpoints.

**Describe alternatives you've considered**
Additionally, all the others [flags](https://github.com/VictoriaMetrics/VictoriaMetrics#security) should be implemented as well, in particular the `-deleteAuthKey` and `-snapshotAuthKey` for `vmstorage` component

**Comment by tenmozes** [comment]
Hi @gcotone, cluster version doesn't have flag because of:
- if it's baremetal setup, people usually put load balancers in front of select and insert, and auth lays there  
- if it's k8s setup, this can be done in ingress level. Some of our useres have already done that

possible we will create separate service for authorization

**Comment by gcotone** [comment]
Hi @tenmozes ,

we're testing it in k8s and while you are right about the use of an Ingress to do TLS/auth/etc, nothing prevent other pods within your cluster from reaching the service directly, bypassing the ingress.

So potentially within a cluster anyone could reach the `vmstorage` service and perform a delete operation, or fill your storage by hitting the `vminsert` service.

Alternatively, a basic validation of an `X-Auth-Token` would also work for us.

**Comment by valyala** [comment]
Unfortunately I'm not going to implement basic authorization for cluster components due to reasons outlined by @tenmozes above. Closing this feature request as `won't implement`.

**Comment by valyala** [comment]
There is yet another reason why Basic Auth isn't implemented in cluster components of VictoriaMetrics:

VictoriaMetrics cluster supports multiple tenants. Each tenant should have its own auth tokens. This authorization must be managed by a proxy sitting in front of VictoriaMetrics cluster. It is impossible to cover this authorization with a single `-httpAuth.username` and `-httpAuth.password` pair.
