### ISSUE TITLE
Add link to MetricsQL.html doc to vmui

### ISSUE THREAD

**Issue by freeseacher** [VictoriaMetrics/VictoriaMetrics#4562]
### Is your feature request related to a problem? Please describe

Currently we have link do general docs in vmui. 
Looks like link to https://docs.victoriametrics.com/MetricsQL.html would be much more relevant

### Describe the solution you'd like

add link to MetricsQL. remove link to general docs

**Comment by hagen1778** [comment]
The link is available starting from [v1.92.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.92.0)
