### ISSUE TITLE
TSID index: switch to per-day index instead of global one

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4563]
### Is your feature request related to a problem? Please describe

TSID index is most vulnerable to high-churn rate issue. This not only make index bigger in high churn-rate environment but also makes `index/*` caches less efficient, as they rely on data blocks size on disk.

### Describe the solution you'd like

Would be nice to switch to per-day partitioning for TSID indexes. This may result in bigger disk usage in a long-run, but would significantly reduce memory usage and increase cache-hit rate for environments with high churn rate

**Comment by hagen1778** [comment]
cc @valyala

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7094fa38bc207c7bd7330ea8a834310a310ce5e3 adds per-day index for `MetricName -> TSID`. This commit will be included in the next release.

**Comment by valyala** [comment]
VictoriaMetrics uses per-day index for `MetricName -> TSID` mapping starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing this feature request as done.
