### ISSUE TITLE
Transitioning period ~30s between metrics

### ISSUE THREAD

**Issue by igor-tsiglyar** [VictoriaMetrics/VictoriaMetrics#4567]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Given VictoriaMetrics + node exporter monitoring a running systemd service, once the service is stopped, I expect the immediate transition from `node_systemd_unit_state{name="systemd-resolved.service", state="active"} == 1` to `node_systemd_unit_state{name="systemd-resolved.service", state="active"} == 0` to be recorded in vmdb, taking into account a low scrape interval (1s) for the respective job.

Instead I am seeing the following behavior:
1. vmui continues to report the old metric state for around 30s since the actual service state change
2. once the above threshold has passed, the vmui starts to report the expected metric state with the correct start time, i.e. the graph is "corrected" to match the expected picture.

The behavior is captured in a screencast: https://youtu.be/T0ZJaqShxKU

Please advise whether this behavior is correct and whether it can be adjusted to remove the observed delay.

Thanks!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @igor-tsiglyar 

@Amper has updated doc here - https://docs.victoriametrics.com/keyConcepts.html#query-latency to describe why that happens with default configuration of VictoriaMetrics.
For your use-case you can adjust value of `-search.latencyOffset` command-line flag to make it 1-2s. This allows to you to see changes in metric value much faster.
