### ISSUE TITLE
Running vmalert against google managed prometheus(gmp-frontend)

### ISSUE THREAD

**Issue by mirkan** [VictoriaMetrics/VictoriaMetrics#4573]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

We're trying to add a vmalert-object to our gmp-frontend prometheus instance, but we're getting this error when adding a vmrule object:

Error:  
`
unexpected response code 400 for http://gmp-frontend.sre.svc.cluster.local:9090/api/v1/query?query=cloudsql_googleapis_com%3Adatabase_up+%3D%3D+1&step=300s&time=1688458590. Response body { "error": { "code": 400, "message": "Invalid JSON payload received. Unknown name \"step\": Cannot bind query parameter. Field 'step' could not be found in request message.", "status": "INVALID_ARGUMENT", "details": [ { "@type": "type.googleapis.com/google.rpc.BadRequest", "fieldViolations": [ { "description": "Invalid JSON payload received. Unknown name \"step\": Cannot bind query parameter. Field 'step' could not be found in request message." } ] } ] } }
`

It works if `&step=300s` is removed the query. We've tested against a regular prometheus and that works so I'm assuming this would be the google side that rejects this. Is it possible to omit step completely or fix this from the vmalert somehow? 

Any guidance is much appreciated, thanks.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
@mirkan thanks for opening FR!
It should be addressed here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4574

vmalert adds `step` param to [instant queries ](https://docs.victoriametrics.com/keyConcepts.html#instant-query) since VictoriaMetrics uses it for some calculations or as a lookback window. But original Prometheus doesn't do that (it uses static lookback window). Looks like Managed Prometheus is very strict about extra params, so we adding option to disable `step` param in vmalert.

**Comment by mirkan** [comment]
@hagen1778 That's great, thank you!
Amazing response 🙏

**Comment by valyala** [comment]
`vmalert` provides `-datasource.disableStepParam` command-line flag starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). If this option is set, then `vmalert` doesn't send `step` query arg to [`/api/v1/query`](https://docs.victoriametrics.com/keyConcepts.html#instant-query) at the configured datasource.

Closing the issue as done.
