### ISSUE TITLE
VictoriaLogs documentation nits

### ISSUE THREAD

**Issue by candlerb** [VictoriaMetrics/VictoriaMetrics#4579]
### Is your question request related to a specific component?

I found some minor documentation issues for VictoriaLogs. These didn't seem to be appropriate for the "Bug" or "Feature request" forms, so I'm posting in the "question" format.

### Describe the question in detail

In the [phrase filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#phrase-filter) documentation, it says:

> This query doesn't match the following log messages:
>
> * `cannot open file`, since the number of whitespace chars between words doesn't match the number of whitespace chars in the search phrase

I think some extra spaces have been stripped out in this example, since as shown, it *does* exactly match the search phrase.

-------

In the [regexp filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#regexp-filter) documentation it says:

> For example, the `re("error|warning")` query can be substituted with `error OR warning` query, which usually works much faster

I don't believe that's an equivalent expression, because "error OR warning" will only match whole words, whilst as far as I can tell, `re()` is not anchored and matches anywhere in the line.  It would be closer to `re("\b(error|warning)\b")` I think (although that's using ASCII word boundaries, not UTF-8 words).

The following examples are given:

> The query matches the following [log messages](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#message-field):
> 
> * `error: cannot read data`
> * `A warning has been raised`

If the regexp is unanchored then I think it would be helpful to give some additional examples which do match, e.g.

* `2 warnings have been raised`
* `terrorist activity blocked`

Finally, it's unclear if you can use `i(re(...))` to do a case-insensitive regexp match. Here it says:

> See also:
> * [Case-insensitive filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#case-insensitive-filter)

If you follow that link, it says:

> Case-insensitive filter can be applied to any word, phrase or prefix by wrapping the corresponding [word filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#word-filter), [phrase filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#phrase-filter) or [prefix filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#prefix-filter) into `i()`

But it doesn't mention regexp filters.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by valyala** [comment]
@candlerb , thanks for paying close attention to VictoriaLogs docs and filing this issue! The commit c93cf8dba4e24add172258dac99ec20a3f238523 should address all the comments above.

**Comment by valyala** [comment]
Closing the issue as fixed then.
