### ISSUE TITLE
Import historical metrics with v1/import/prometheus

### ISSUE THREAD

**Issue by contrudar** [VictoriaMetrics/VictoriaMetrics#4581]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I'm trying to import my metrics to VictoriaMetrics. I have curl like this and it works fine if I don't use timestamp

PROMETHEUS_URL_FOR_IMPORT_HISTORICAL_DATA="myAddress/api/v1/import/prometheus"

curl -d "test_test_metric_name{release=\"${release_name}\"} ${apk_size_bytes}" -X POST "$PROMETHEUS_URL_FOR_IMPORT_HISTORICAL_DATA"

But I need to import my data with timestamps. I tried to put timestamp in 2 ways:

1. curl -d "test_test_metric_name{release=\"${release_name}\"} ${apk_size_bytes} ${timestamp}" -X POST "$PROMETHEUS_URL_FOR_IMPORT_HISTORICAL_DATA"
2. curl -d "test_test_metric_name{release=\"${release_name}\"} ${apk_size_bytes}" -X POST "$PROMETHEUS_URL_FOR_IMPORT_HISTORICAL_DATA?timestamp=${timestamp}"

Both commands are successful, no errors. I tried with milliseconds and nanoseconds, but no luck.

Any suggestions how make it work?

Thanks in advance.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Both commands are successful, no errors.

If there is an error, you should look for it on VictoriaMetrics side. Check VictoriaMetrics logs to see if there are any error log messages.

> I tried with milliseconds and nanoseconds, but no luck.

VM supports the following timestamps:

- Unix timestamps in seconds with optional milliseconds after the point. For example, 1562529662.678.
- Unix timestamps in milliseconds. For example, 1562529662678.
- Unix timestamps in seconds. For example, 1562529662.

For example:
```
$ curl -d 'metric_name{foo="bar"} 123 1562529662.678' -X POST http://localhost:8428/api/v1/import/prometheus
$ curl -d 'metric_name{foo="bar"} 123 1562529662678' -X POST http://localhost:8428/api/v1/import/prometheus 
$ curl -d 'metric_name{foo="bar"} 123 1562529662' -X POST http://localhost:8428/api/v1/import/prometheus 

$ curl http://localhost:8428/api/v1/export -d 'match[]=metric_name'
{"metric":{"__name__":"metric_name","foo":"bar"},"values":[123,123,123],"timestamps":[1562529662000,1562529662678,1562529662678]}
```

**Comment by contrudar** [comment]
Thanks, now it works. Probably was a problem in bash script
