### ISSUE TITLE
cannot checkout 1.19.3

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#4587]
### Is your question request related to a specific component?

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/33677006/17c7e3e0-92c9-4285-b9f6-7652b8cf1380)

### Describe the question in detail

cannot fetch and get this version using your repo based from 1.89.1 branch cluster

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @renchili 
This message is displayed because commit which is referenced by `1.91.3` tag was cherry-picked from another branch before release. You can safely use `1.91.3` and disregard this message.

**Comment by zekker6** [comment]
Closing this one as question have been answered, feel free to reopen if you will have another questions about this.
