### ISSUE TITLE
vmagent targets UI does not show proper response for targets

### ISSUE THREAD

**Issue by sergk-mambu** [VictoriaMetrics/VictoriaMetrics#4597]
### Describe the bug

In vmagent Targets UI (/targets) for every endpoint there is a link (response) which should show a response of corresponding target. When I can click on any of those response links it always redirect me to the URL `http://localhost:8429/target_response?id=0000000000000000`, i.e. always the same zero id for any target. And that URL returns an output of some random target not of the one which I clicked the link of. If I refresh this page in a browser it keeps returning an output of some other random target.
As far as I understand the id in that URL should be not zero but specific to the corresponding target.

### To Reproduce

Open http://localhost:8429/targets page of vmagent, click on the (response) link of any present targets in the list

### Version

1.87.6

### Screenshots

<img width="589" alt="Screenshot 2023-07-07 at 16 30 46" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73960053/f1594e4e-cc5d-4cfb-b3b1-ca885b1b10cb">

**Comment by dmitryk-dk** [comment]
Hi @sergk-mambu ! Can you share how you run `vmagent` and `--promscrape.config`? Do you use this flag `--promscrape.dropOriginalLabels`?

I ran `vmagent` v1.87.6 and all targets had correct ids

**Comment by valyala** [comment]
`vmagent` stops displaying broken links, which depend on the original labels for the discovered targets, if `-promscrape.dropOriginalLabels` command-line flag is set, starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
