### ISSUE TITLE
vmui: add Active Queries page for Explore tab

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4598]
### Is your feature request related to a problem? Please describe

Would be nice if VMUI could provide the list of currently running queries, apart of Top Queries. This could help in detecting issues or expensive queries which are consuming resources in the current moment

### Describe the solution you'd like

VictoriaMetrics exposes the following API:
> api/v1/status/active_queries - for currently executed active queries. Note that every vmselect maintains an independent list of active queries, which is returned in the response.

Would be nice to have a page under Explroe tab where the output of the API can be viewed.

Currently, this API returns data in plaintext. But I think we can easily change it to json if that would be simpler to use.

**Comment by valyala** [comment]
@Loori-R , could you make UX improvements for the `Active Queries` page mentioned [in this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4653#issuecomment-1642888619)?

**Comment by Loori-R** [comment]
@valyala, the changes you requested have been made as part of this pr: #4676.

**Comment by valyala** [comment]
The `Active Queries` page is available in [vmui](https://docs.victoriametrics.com/#vmui) starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/#active-queries). Closing the feature request as done.
