### ISSUE TITLE
Is it compatible with statsd clients?

### ISSUE THREAD

**Issue by Koilanetroc** [VictoriaMetrics/VictoriaMetrics#4600]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Documentation says:
> Stream aggregation can be used as [statsd](https://github.com/statsd/statsd) alternative

But vmagent does not support the format in which clients send metrics to statsd. It's a bit confusing, should it be mentioned somewhere in docs at least? I'm expecting that if I replace statsd with vmagent with enabled streaming aggregation, then it should support statsds' metrics format.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @Koilanetroc.

Currently stream aggregation is indeed not compatible with Statsd clients, I have added an explicit indication of it in [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4621).

In the future we are going to add support for the Statsd format in [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/206).

**Comment by Koilanetroc** [comment]
@Amper, do you accept PRs? I'd like to try to add compatibility with statsd clients, it does not seem like a big feature.
