### ISSUE TITLE
logs web ui doesn't use http.pathPrefix for queries

### ISSUE THREAD

**Issue by drewp** [VictoriaMetrics/VictoriaMetrics#4604]
### Describe the bug

https://bigasterisk.com/logs/select/vmui/#/?query=log_level%3A*&page=1

That page requests this, which is good:
https://bigasterisk.com/logs/select/vmui/static/js/main.46d11611.js

but also this:
POST https://bigasterisk.com/select/logsql/query

which is bad, since /logs/ is lost.

Also, https://bigasterisk.com/logs/select/vmui/dashboards/index.js looks like a good path, but returns 404. Maybe that one is expected.

### To Reproduce

```
          args:
            - -storageDataPath=/data
            - -http.pathPrefix=/logs/
            - -loggerTimezone=America/Los_Angeles
            - -memory.allowedBytes=512MB
            - -retentionPeriod=8w
```

### Version

          image: victoriametrics/victoria-logs:v0.1.0-victorialogs

**Comment by valyala** [comment]
`vmui` should properly handle `-http.pathPrefix` starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.

@drewp , feel free re-opening this issue or creating new one if the issue still persists after the upgrade to v1.92.0.
