### ISSUE TITLE
VictoriaLogs: unable to see non-stream fields

### ISSUE THREAD

**Issue by candlerb** [VictoriaMetrics/VictoriaMetrics#4609]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

I am sending messages from rsyslog to VictoriaLogs, with the following config, loosely based on [this one](https://www.rsyslog.com/rsyslog-and-elasticsearch/).

```
module(load="omelasticsearch")

template(name="victoriaLogs"
         type="list"
         option.json="on") {
           constant(value="{")
             constant(value="\"_time\":\"")      property(name="timereported" dateFormat="rfc3339")
             constant(value="\",\"_msg\":\"")     property(name="msg")
             constant(value="\",\"host\":\"")        property(name="hostname")
             constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
             constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
             constant(value="\",\"syslogtag\":\"")   property(name="syslogtag")
           constant(value="\"}")
         }

*.*  action(type="omelasticsearch"
  server="localhost:9428/insert/elasticsearch"
  # total abuse of syntax, no official way to add params
  timeout="1m&_stream_fields=host,facility"
  template="victoriaLogs"
  searchIndex="elasticsearch"
  bulkmode="on")
& stop
```

Using tcpdump, I can see the documents being submitted as expected, for example:

```
POST /insert/elasticsearch/_bulk?timeout=1m&_stream_fields=host,facility HTTP/1.1
Host: localhost:9428
Accept: */*
Content-Type: application/json; charset=utf-8
Content-Length: 257

{"index":{"_index": "elasticsearch","_type":"events"}}
{"_time":"2023-07-10T20:32:01+00:00","_msg":"pam_unix(cron:session): session opened for user www-data by (uid=0)","host":"lxdmosaic","severity":"info","facility":"authpriv","syslogtag":"CRON[278602]:"}

# RESPONSE
HTTP/1.1 200 OK
Content-Type: application/json
Vary: Accept-Encoding
X-Elastic-Product: Elasticsearch
X-Server-Hostname: loki
Date: Mon, 10 Jul 2023 20:44:01 GMT
Content-Length: 61

{"took":0,"errors":false,"items":[{"create":{"status":201}}]}
```

However, when I query back this log, this is what I get:

```
# curl -fsS http://localhost:9428/select/logsql/query -d 'query=www-data' | grep '2023-07-10T20:32:01'
{"_msg":"pam_unix(cron:session): session opened for user www-data by (uid=0)","_stream":"{facility=\"authpriv\",host=\"lxdmosaic\"}","_time":"2023-07-10T20:32:01Z"}
```

You can see that we have `_msg` and `_time`, and that "facility" and "host" fields have been subsumed into the `_stream` attribute.  However the "severity" and "syslogtag" fields are missing in the response.

My question is: have I missed out some step, either at the ingestion stage, or the querying stage? As far as I can see from the [data model](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#data-model), all `key:value` fields in the log entry ought to be stored by VictoriaLogs.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by valyala** [comment]
VictoriaLogs stores and indexes all the log fields. But it returns only those fields, which are explicitly mentioned in the query, plus `_msg`, `_stream` and `_time` fields. So, if you need obtaining other fields, then just mention them in the end of the query with `field_name:*` syntax. For example, if you want obtaining `severity` and `syslogtag` fields, then try the following query to VictoriaLogs:

```
curl http://localhost:9428/select/logsql/query -d 'query=www-data severity:* syslogtag:*'
```

In the future [LogsQL](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html) will support the ability to specify the needed fields by appending `| fields field1, field2, ..., fieldN` to the end of the query. It will also support `SELECT *`-like functionality for selecting all the fields for the selected log entries: `| fields *`. In general, the `| fields *` isn't recommended to use, since:

- It requires reading all the field values during query execution, thus reducing query perfromance
- It may clutter the response with a ton of unneeded fields
- Different log entries may contain different set of fields. `| fields *` will select all of them for all the matching log entries, so the output will become irregular, e.g. every line may contain its own set of fields.

**Comment by valyala** [comment]
Note also that it may be convenient to use debugging capabilities of VictoriaLogs in order to understand which data is ingested into it. See [these docs](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/#troubleshooting) for details.

**Comment by candlerb** [comment]
Thank you: that works, and your explanation is clear. LogsQL is not only filtering which logs to match, but also selecting which fields from each log to return.  e.g. if I query `severity:info` then I get `_msg`, `_stream`, `_time` and `severity` in the result (but nothing else).

I missed this in the documentation, but on searching again I found it [here](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#logsql-tutorial):

> The query returns the following [log fields](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#data-model) by default:
>
> * [_msg field](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#message-field)
> * [_stream field](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#stream-fields)
> * [_time field](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#time-field)
>
> Logs may contain arbitrary number of other fields. If you need obtaining some of these fields in query results, then just refer them in the query with field_name:* [filter](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#any-value-filter). For example, the following query returns host.hostname field additionally to _msg, _stream and _time fields:
> 
> ```
> error _time:[now-5m,now] host.hostname:*
> ```

I think this information could be more conspicuous - it's a long way under the "LogsQL tutorial" subheading, and perhaps deserves its own subheading (especially when you add the new features for controlling the fields returned).

It might also be useful to mention it in the "data model" section, and/or at the [HTTP API](https://docs.victoriametrics.com/VictoriaLogs/querying/#http-api), where it currently says:

> The /select/logsql/query endpoint returns [a stream of JSON lines](http://ndjson.org/), where each line contains JSON-encoded log entry in the form {field1="value1",...,fieldN="valueN"}.

Neither place currently says that you'll only get a subset of fields.

**Comment by valyala** [comment]
@candlerb , thanks for valuable suggestions on how to improve VictoriaLogs docs! Docs have been updated according to these suggestions at a0ff5c2627aead668bf9cdae4ec85c325a562c26 .

**Comment by candlerb** [comment]
BTW, having an easy way to return 'all fields' would be especially useful for structured JSON logs which don't contain a `_msg` field at all - e.g. Netflow records.  Otherwise, you could search on a stream label (say), and see nothing from each result apart from the stream labels and timestamp.

I also wonder if the `| fields ...` syntax is also a precursor to having aggregation functions. Right now it's hard to say "what distinct values of the `severity` field are present?", or to get counts of them, without doing some jq-like processing client-side.

**Comment by valyala** [comment]
> BTW, having an easy way to return 'all fields' would be especially useful for structured JSON logs which don't contain a _msg field at all - e.g. Netflow records.

If the log entry contains the log messages in other than`_msg` field, then it is advised to move the message to `_msg` field during data ingestion by specifying it via `_msg_field` query arg - see [these docs](https://docs.victoriametrics.com/VictoriaLogs/keyConcepts.html#message-field).

If the log entry doesn't contain any log messages, as in the netflow case, or as in some other event-based logging without explicit log message, then it should be OK to ingest such log entries into VictoriaLogs (could you check whether this is supported now. It this isn't supported, then please file a new feature request for adding the support for data ingestion with missing log message).

> I also wonder if the | fields ... syntax is also a precursor to having aggregation functions. Right now it's hard to say "what distinct values of the severity field are present?", or to get counts of them, without doing some jq-like processing client-side.

Aggregate functions and the ability to select particular fields are going to be implemented around the same time. This functionality doesn't depend on each other and doesn't block each other in terms of implementation priority.
