### ISSUE TITLE
VictoriaLogs: add ability to receive systemd (journald) logs over network

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#4618]
### Is your feature request related to a problem? Please describe

journald is the standard subsystem for log collection from programs operated by systemd.
By default it puts the collected logs into local files. Logs from these files can be forwarded to [VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/) via one of the [supported log shippers](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/).

This solution works, but it requires an intermediate program - log shippers - for sending journald logs to VictoriaLogs.

Journald can be configured for sending the locally collected logs to remote server via [systemd-journal-remote](https://manpages.debian.org/testing/systemd-journal-remote/systemd-journal-remote.service.8.en.html) package. It would be great if journald could send logs directly to VictoriaLogs without intermediate applications.

### Describe the solution you'd like

To add support for journald network protocol for logs' transfer to VictoriaLogs. This will remove the need for intermediate log shippers between journald and VictoriaLogs.

### Describe alternatives you've considered

To use one of the supported log shippers for forwarding journald logs to VictoriaLogs.

**Comment by valyala** [comment]
@zekker6 , could you look into this task?

**Comment by udf2457** [comment]
+1

I don't like the maintenance debt associated with installing third-party log-shipping "agents" everywhere.

Support for native systemd journal format would be great.

**Comment by AndrewChubatiuk** [comment]
Added [PR](https://github.com/systemd/systemd/pull/34595) with zstd compression and custom headers support for systemd-journal-upload

**Comment by valyala** [comment]
VictoriaLogs supports receiving systemd (journald) logs starting from [v0.38.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). See [these docs](https://docs.victoriametrics.com/victorialogs/data-ingestion/journald/) for details.

Closing the feature request as done.
