### ISSUE TITLE
VictoriaLogs: add support for accepting syslog logs

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#4619]
### Is your feature request related to a problem? Please describe

Syslog protocol is frequently used for log shipping. Syslog logs can be ingested into [VictoriaLogs](https://docs.victoriametrics.com/VictoriaLogs/) via one of [the supported log shippers](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion). This adds an intermediate program between the application, which emits logs, and VictoriaLogs. It would be great if VictoriaLogs could accept syslog logs directly without the need of intermediate program.

### Describe the solution you'd like

To implement the ability to accept logs in syslog format by VictoriaLogs itself. Both TCP and UDP transports must be supported.

The open question is how to deal with [possible options](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/#http-parameters), which could be passed to VictoriaLogs during data ingestion.

### Describe alternatives you've considered

To use one of [the supported log shippers](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/) for routing syslog logs to VictoriaLogs. See, for example, [how to configure Filebeat for accepting syslog logs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-syslog.html).

**Comment by Yoda-BZH** [comment]
> Both TCP and UDP transports must be supported.

And SSL/TLS (?)

**Comment by valyala** [comment]
VictoriaLogs supports syslog protocol for data ingestion starting from [v0.20.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). See [these docs](https://docs.victoriametrics.com/victorialogs/data-ingestion/syslog/). Closing the feature request as done.

**Comment by tiny-pangolin** [comment]
> > Both TCP and UDP transports must be supported.
> 
> And SSL/TLS (?)
Yes, Victorialog's syslog ingestion supports TLS see [these docs](https://docs.victoriametrics.com/victorialogs/data-ingestion/syslog/#security) for details
