### ISSUE TITLE
Strange values returned on promql request on data with missing timestamp

### ISSUE THREAD

**Issue by DMANSUTTI** [VictoriaMetrics/VictoriaMetrics#462]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

While dumping a metric (named installation) using the export API:
curl http://127.0.0.1:8428/api/v1/export -d 'match[]={__name__="installation"}' -d start=1586736000 -d end=1586822340

This metrics is collected each hour (i.e. there is a value for each hour), except if the value is not provided, in that case nothing is stored in the db for this timestamp. The result shows the following information:

2020-04-13 12:00:00 (1586779200): 53
2020-04-13 15:00:00 (1586790000): 67
2020-04-13 19:00:00 (1586804400): 74
2020-04-13 10:00:00 (1586772000): 6
2020-04-13 16:00:00 (1586793600): 63
2020-04-13 09:00:00 (1586768400): 1
2020-04-13 21:00:00 (1586811600): 23
2020-04-13 13:00:00 (1586782800): 56
2020-04-13 18:00:00 (1586800800): 77
2020-04-13 23:00:00 (1586818800): 13
2020-04-13 14:00:00 (1586786400): 77
2020-04-13 11:00:00 (1586775600): 20
2020-04-13 20:00:00 (1586808000): 54
2020-04-13 07:00:00 (1586761200): 3
2020-04-13 17:00:00 (1586797200): 65
2020-04-13 00:00:00 (1586736000): 1
2020-04-13 22:00:00 (1586815200): 31

We clearly see that no value is stored for some timestamp.

But when a request is made through the query API, it also returns values for missing timestamps where I would expect no data for these timestamps. The command is the following:
/api/v1/query_range?query=sum%20by(status)%20(installation%7Boperator%3D%22STC%22%2Cdevice%3D~%2253277190%7C53378690%7C53925111%7C53275890%7C53278890%7C53937901%7C53166690%7C53271990%7C53936901%7C53837201%7C53270890%7C53935201%7C53272890%7C53832401%7C53837301%7C53045001%7C53937101%7C53566701%7C53928211%7C53838301%7C53937001%7C53936201%7C53935101%7C53935701%7C68906940%7C53933101%7C53830401%7C53239301%7C53272090%7C53035701%7C53271090%7C53043001%7C53933901%7C53272290%7C53271290%7C53276190%7C53276990%7C53277290%7C53279990%7C53936101%7C53460601%7C53934201%7C53935901%7C53938901%7C53274190%7C53371590%7C53270990%7C53565701%7C53834301%7C53275290%7C53270190%7C53831901%7C53564701%7C53279190%7C53931101%7C53131201%7C53237301%7C53036701%7C53273990%7C53032801%7C53272190%7C53271190%7C53936001%7C53569601%7C53930201%7C53037901%7C53274790%7C53273190%7C53560801%7C53278990%7C53276890%7C53833401%7C53930101%7C53379590%7C53924211%7C53932101%7C53375590%7C53561801%7C53132301%7C53835301%7C53271890%7C53039701%7C53839301%7C53939101%7C53275990%7C53277990%7C53788190%7C53037801%7C53830301%7C53939801%7C53272990%7C53279290%7C53377590%7C53279890%7C53372590%7C53831301%7C53934901%7C53836301%7C53276290%7C53136601%7C53169690%7C53934101%7C99002110%7C53831401%7C53373690%7C53034701%7C53162790%7C53839201%7C53375690%7C53565601%7C53832301%7C53273890%7C53370590%7C53939001%7C53032901%7C53838201%7C53136501%7C53040001%7C53036801%7C53372690%7C53566601%7C53379390%7C53275190%7C53933201%7C53277790%7C53834401%7C53376590%7C53374690%7C53938101%7C53278190%7C53370690%7C53037701%7C53044001%7C53277890%7C53930901%7C53379690%7C53130701%7C53937801%7C53038701%7C53938001%7C53035801%7C53046001%7C53465501%7C53270290%7C53931201%7C53274990%7C53932201%7C53938801%7C53835401%22%2C%20profile%3D~%22STC_06%5C%5C.51%7CSTC_09%5C%5C.51%22%2C%20status%3D~%22.%2B%22%7D)&start=1586728800&end=1586815200&step=3600

Please note that I did try with different step value but the result was the same.

And the result is (typically I was not expecting the timestamp in bold).

                            Member Key: "values"
                                Array
                                    Array
                                        Number value: 1586736000
                                        String value: 1
                                    Array
                                        Number value: 1586761200
                                        String value: 3
                                    Array
                                        Number value: **1586764800**
                                        String value: 3
                                    Array
                                        Number value: 1586768400
                                        String value: 4
                                    Array
                                        Number value: 1586772000
                                        String value: 9
                                    Array
                                        Number value: 1586775600
                                        String value: 27
                                    Array
                                        Number value: 1586779200
                                        String value: 69
                                    Array
                                        Number value: 1586782800
                                        String value: 94
                                    Array
                                        Number value: 1586786400
                                        String value: 104
                                    Array
                                        Number value: 1586790000
                                        String value: 111
                                    Array
                                        Number value: 1586793600
                                        String value: 118
                                    Array
                                        Number value: 1586797200
                                        String value: 119
                                    Array
                                        Number value: 1586800800
                                        String value: 129
                                    Array
                                        Number value: 1586804400
                                        String value: 118
                                    Array
                                        Number value: 1586808000
                                        String value: 119
                                    Array
                                        Number value: 1586811600
                                        String value: 81
                                    Array
                                        Number value: 1586815200
                                        String value: 73

Is there any way to have only the timestamps that are filled with values? Is it the expected behavior?

**Version**
This was tested on the latest version at this time (1.35.2).

**Used command-line flags**
victoria-metrics-prod -storageDataPath /var/victoriametrics/data -retentionPeriod 36 -influxSkipSingleField

**Additional context**
The actual content of the curl result on the export API is the following:

[metrics.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4580797/metrics.txt)

And the full JSON response is:

[wireshark.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4580802/wireshark.txt)

**Comment by valyala** [comment]
The `/api/v1/query_range` returns calculated points at regular interval equal to `step` arg according to Prometheus data model. The value for each point is equivalent to the last real value stored in the database before the point's timestamp. See https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness for details. VictoriaMetrics stops returning points only if real points are missing during 2x interval between them. This means 2h in your case.

Try setting `-search.maxStalenessInterval=5m` command-line flag in order to make the data model closer to the expected. Below is the corresponding snippet from `-help` output for `-search.maxStalenessInterval` flag:

```
  -search.maxStalenessInterval duration
    	The maximum interval for staleness calculations. By default it is automatically calculated from the median interval between samples. This flag could be useful for tuning Prometheus data model closer to Influx-style data model.
```

**Comment by DMANSUTTI** [comment]
Thanks, 

This is working for us.
