### ISSUE TITLE
Too high IO saturation during prolonged big merges

### ISSUE THREAD

**Issue by yshch** [VictoriaMetrics/VictoriaMetrics#4623]
### Describe the bug

Big merges cause vmstorage nodes to completely saturate SATA SSDs, which leads to cluster instability, insert degradation and so on. In practice this means, that during prolonged big merges clusters become essentially unusable. Even one or just a few nodes doing prolonged big merges is enough to destabilize the entire cluster. This is mostly noticeable during final monthly merges, because those can take more than 48 hours to complete in my case.

Looking at the old issues it seems that this problem is known. Is there any mitigation for this issue? If there isn't, maybe there really should be some way to limit the maximum bandwidth or something similar?

By old issues i mean this one for example: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/648#issuecomment-662423377

This really is a critical issue in my case and i see no good way to solve it right now.

### To Reproduce

1. setup a cluster
2. insert a bunch of data, in my case about 750Gi monthly per vmstorage node is definitely enough
3. initiate finalMerge

### Version

vmstorage-20230518-213137-tags-v1.91.0-cluster-0-g93f934eae

### Logs

There is nothing suspicious in the logs, just notices of long merges.

Here is one example from one of the nodes pictured on the graph below.

```
merged (10 parts, 696657227493 rows, 670022566 blocks, 524931714425 bytes) into (1 part, 571903097952 rows, 560147601 blocks, 463842294106 bytes) in 81632.654 seconds at 8534050 rows/sec to "/storage/data/big/2023_06/176EC2EDDD5945D0"
````

### Screenshots

First, here's how amount of running big merges looks in two separate clusters. It's easy to see finalMerge here.
![vm-merges](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8925723/44fdf73a-a882-433d-a8b5-aebc84eb283c)

And here is utilization of drives on corresponding nodes in one of the clusters.
![vm-io](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8925723/90ead67c-ab50-4b06-b3ee-37fdf3f326b1)

This is a recurring issue and i can observe this same behaviour during every big merge session.

### Additional information

Majority of the SSDs are INTEL SSDSC2KG038T8 or similar.

**Comment by hagen1778** [comment]
Hello @yshch!

You can slow down background merges intensity via `-smallMergeConcurrency` flag. This flag controls the amount of threads working on background merge. The more threads is allocated, the higher intensity (speed) of the merges is expected. By default, this flag is limited by 50% of available CPUs, but won't exceed 16. Try lowering it to 8 or 4.

Triggering the `finalMerge` shouldn't be something regular. In normal operation, it is ok for a single partition to contain many parts. Compressing everything to 1 part within a partition doesn't provide compression benefits. It is better to allow VM to do the merges automatically, without forcing. This is why the merge concurrency limit is not mentioned explicitly in recommendations for tuning, since it should work correctly during normal operation.

**Comment by yshch** [comment]
@hagen1778, hey thanks for quick response!

> You can slow down background merges intensity via -smallMergeConcurrency flag.

I have already setup `-smallMergeConcurrency` to 1 and even `-bigMergeConcurrency` to 1 also even though it seems it is deprecated now. There are a few problems with this.

First, i don't really have a problem with background merges. Actually they work just fine.

Second, from my understanding, `-smallMergeConcurrency` only limits small merges. Is this correct? Because i don't have a problem with small merges. You can see in my screenshot i'm only showing `vm_active_merges` for `type=storage/big`.

And finally, the concurrency is not the issue here. In my screenshot you can see that the peak is about 10 to 12 active big merges at on time. The amount of vmstorage nodes in those clusters is 10 each. So there's one active big merge going per node, if i understand the metrics correctly. This one concurrently active big merge is enough to completely saturate drives IO.

> Triggering the finalMerge shouldn't be something regular. In normal operation, it is ok for a single partition to contain many parts. Compressing everything to 1 part within a partition doesn't provide compression benefits.

This is true, i can probably just avoid final merges. The problem is, we're evaluating enterprise version, especially for features like downsampling. And it seems like during downsampling vmstorage actually does merges everything into one part, just like during final merge. Even though `-finalMergeDelay` flag is not set at all. This isn't obvious from documentation. But it does make sense sense, because as far as i understand, downsampling and deduplication is tied hard to merging? Is it possible to use deduplication and/or downsampling without triggering `finalMerge` like process? For example, to downsample previous month you obviously have to go through the whole partition, so at this point why not merge?

**Comment by hagen1778** [comment]
> But it does make sense sense, because as far as i understand, downsampling and deduplication is tied hard to merging?

Indeed, downsampling is a special case of background merge.

> Is it possible to use deduplication and/or downsampling without triggering finalMerge like process?

No, AFAIK.

> For example, to downsample previous month you obviously have to go through the whole partition, so at this point why not merge?

It performs both merge and downsampling simultaneously. The final downsampling is applied to partition (a month unit) and is limit by one CPU thread AFAIK. It usually doesn't cause any issues on the systems we maintain. Could you please show results for the following queries for each vmstorage:
```
rate(vm_filestream_read_duration_seconds_total) 
rate(vm_filestream_write_duration_seconds_total)

rate(process_io_storage_read_bytes_total)
rate(process_io_storage_written_bytes_total)
```
?

**Comment by jiekun** [comment]
Close due to inactivity
