### ISSUE TITLE
vmalert dashboard: show absolute usage of memory and cpu metrics

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4627]
vmalert provides panels for viewing mem/cpus usage in %. This is useful for detecting if vmalert is near the limits. But it might be useful to show absolute numbers as well, like we do for single/cluster dashboard.

**Comment by valyala** [comment]
[The official dashboard for vmalert](https://grafana.com/grafana/dashboards/14950-victoriametrics-vmalert/) shows absolute memory and cpu usage metrics starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html).
