### ISSUE TITLE
stream aggregation: support list for `match` param

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4635]
### Is your feature request related to a problem? Please describe

Sometimes it is needed to have multiple time series selector in [aggregation config](https://docs.victoriametrics.com/stream-aggregation.html#stream-aggregation-config), but `match` can be specified only once.

### Describe the solution you'd like

Would be great if `match` field supported a list of time series selectors. This should simplify configuration from user's perspective:
```
- match: 
  - http_request_duration_seconds_bucket{env="prod"}
  - http_request_duration_seconds_bucket{env="staging"}
```

**Comment by valyala** [comment]
VictoriaMetrics and VictoriaLogs support a list of series selectors inside `match` option starting from [v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this feature request as done.
