### ISSUE TITLE
vmagent: enable `attach_metadata.node` in all scrape configs

### ISSUE THREAD

**Issue by carlos4ndre** [VictoriaMetrics/VictoriaMetrics#4640]
### Is your feature request related to a problem? Please describe

I would like to automatically set `attach_metadata.node` to `true` in all scrape configs without having to explicitly do it for each PodMonitor/ServiceMonitor or VMPodScrape/VMServiceScrape resources.

This would avoid toil of ensuring this option is set in all scrape configs, and avoid potentially misconfigurations.

### Describe the solution you'd like

It would be useful to have the ability to customize all scrape configs generated by VMAgent, and be able to for example set `attach_metadata.node` to `true`.

This could be done with global options (e.g., `enableAttachMetadataAll`) or via some sort of yaml patching allowing the set of many fields and potentially filtering of scrape configs but that would be more complex (e.g., `scrapeConfigPatches`).

### Additional information

The `attach_metadata.node` option is only available for [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) so it can only be applied to that type of scrape config.

**Comment by wasim-nihal** [comment]
Hi, I would like to contribute here if no one has picked this up.

**Comment by hagen1778** [comment]
Sure @wasim-nihal! Want me to assign you to the ticket?

**Comment by wasim-nihal** [comment]
Sure. Thanks!

**Comment by valyala** [comment]
The commit 7fba73ce11ffe8cd7be379fa7119768895c0c1da adds `-promscrape.kubernetes.attachNodeMetadataAll` command-line flag to [vmagent](https://docs.victoriametrics.com/vmagent.html) and to [single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter). This allows enabling `attach_metadata.node=true` for all the [`kubernetes_sd_configs`](https://docs.victoriametrics.com/sd_configs.html#kubernetes_sd_configs) defined in the file specified via `-promscrape.config` command-line flag.

This commit will be included in the next release. In the mean time it is possible to verify whether this change works as expected by running `vmagent` built from the commit 7fba73ce11ffe8cd7be379fa7119768895c0c1da according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources).

**Comment by valyala** [comment]
`vmagent` supports `-promscrape.kubernetes.attachNodeMetadataAll` command-line flag starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
