### ISSUE TITLE
Running transform before rollups (eg how to do abs_sum_over_time)

### ISSUE THREAD

**Issue by lihmc** [VictoriaMetrics/VictoriaMetrics#4641]
### Is your question request related to a specific component?

metricsql

### Describe the question in detail

Hi, I have a metric that has both positive and negative values. Say it is Metric_shares_traded (negative for sells). I would like to retrieve a rolling sum of the absolute value. However, when I wrap the metric I query inside abs before doing sum_over_time, I drop results as now the Metric_shares_traded is auto-wapped by default_rollup and values are dropped.

eg `sum_over_time(abs(Metric_shares_traded))` will drop randomly, especially over longer query time ranges because default_rollup does a last rollup.

Similarly, trying to do sum_over_time(Metric_shares_traded > 0) - sum_over_time(Metric_shares_traded < 0) gives the same issue because Metric_shares_traded is wrapped by default_rollup before the comparison.

I think this is similar to #2020 

Is there a workaround to getting what I want to work?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by valyala** [comment]
This functionality isn't supported by [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) at the moment, but I think we can add `sum_gt_over_time(m[d], threshold)` and `sum_lt_over_time(m[d], threshold)` functions, which would calculate the sum of [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) on the given lookbehind window `d` if they are bigger (for sum_gt_over_time) or smaller (for sum_lt_over_time) than the given threshold. MetricsQL already provides similar functions - [count_gt_over_time](https://docs.victoriametrics.com/metricsql/#count_gt_over_time) and [count_lt_over_time](https://docs.victoriametrics.com/metricsql/#count_lt_over_time),

**Comment by valyala** [comment]
FYI, the commit d6e22f28882fc06fb8ddb2f5408491b5eea20d58 adds support for [sum_eq_over_time](https://docs.victoriametrics.com/MetricsQL.html#sum_eq_over_time), [sum_gt_over_time](https://docs.victoriametrics.com/MetricsQL.html#sum_gt_over_time) and [sum_le_over_time](https://docs.victoriametrics.com/MetricsQL.html#sum_le_over_time) functions. This commit will be included in the next release. In the mean time it is possible to test these functions by building VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources). If you run [cluster version of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html), then you can build cluster components from the commit 5f2905d1205c9549880a18067a9dec926f48e6c2 according to [these instructions](https://docs.victoriametrics.com/cluster-victoriametrics/#building-from-sources).

**Comment by valyala** [comment]
The `sum_eq_over_time`, `sum_gt_over_time` and `sum_le_over_time` functions are available in VictoriaMetrics starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html).

Now the `sum_over_time(abs(Metric_shares_traded))` query can be properly processed when re-written to the following one:

```metricsql
sum_gt_over_time(Metric_shares_traded[duration], 0)
```

Closing the feature request as done.
