### ISSUE TITLE
What happens if data capacity is reached is there a case where old or new data may be dropped ?

### ISSUE THREAD

**Issue by hasanawad94** [VictoriaMetrics/VictoriaMetrics#4644]
### Is your question request related to a specific component?

VictoriaMetrics cluster version.

### Describe the question in detail

I plan to start using VictoriaMetrics cluster as a storage solution for my Prometheus, and I'm doing some research before committing to it and I was wondering if there is a possibility where I might lose data in case of not enough storage.

In the storage section form the documentation it is written: 

> "VictoriaMetrics doesn't merge parts if their summary size exceeds free disk space. This prevents from potential out of disk space errors during merge."

Is there no case where data get deleted due to insufficient storage?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hi @hasanawad94 
vmstorage will stop accepting new samples in case there is no free space available on disk. in this case vminsert will do re-routing of series to another storage nodes, so that if there are nodes with disk space available - data will be written to disk.
If all vmstorage nodes do not have any disk space available vminsert returns an error meaning data was not written to the cluster, so that Prometheus(or any tother client) should buffer data and retry later.

**Comment by Amper** [comment]
Hey @hasanawad94.

> Is there no case where data get deleted due to insufficient storage?

It works as follows:
- When disk occupancy is high, background merges may no longer be performed, but incoming data will be written to the new parts. VictoriaMetrics doesn't merge parts if their summary size exceeds free disk space. This prevents from potential out of disk space errors during merge. It's also worth quoting this:
  
  > The number of parts may significantly increase over time under free disk space shortage. This increases overhead during data querying, since VictoriaMetrics needs to read data from bigger number of parts per each request. That's why it is recommended to have at least 20% of free disk space under directory pointed by -storageDataPath command-line flag. If free disk space is lower than 20%, then VictoriaMetrics is unable to perform optimal background merge of the incoming data.
- When the storage data path contains less than `-storage.minFreeDiskSpaceBytes` of free space then storage automatically switch to [read-only mode](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#readonly-mode). `vminsert` nodes stop sending data to such nodes and start re-routing the data to the remaining vmstorage nodes.
- When `vminserts` can't write data to the necessary number of storages (taking into account the desired `relicationFactor` and re-routing) then they'll return an error to the client. And handling this situation becomes the client's responsibility. 
- If vmagent is the client, then it can [accumulate data in a persistent queue on disk](https://docs.victoriametrics.com/vmagent.html#replication-and-high-availability):
  
  > If the remote storage is unavailable, the collected metrics are buffered at -remoteWrite.tmpDataPath. The buffered metrics are sent to remote storage as soon as the connection to the remote storage is repaired. The maximum disk usage for the buffer can be limited with -remoteWrite.maxDiskUsagePerURL.

Thus there are several "lines of defense" in the VM, that depend on your settings.

Related links:
- [Storage](https://docs.victoriametrics.com/#storage)
- [Read-only mode](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#readonly-mode)
- [Cluster availability](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability)
- [High availability](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#high-availability)
- [Replication and data safety](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety)
- [VMAgent replication and high availability](https://docs.victoriametrics.com/vmagent.html#replication-and-high-availability)

**Comment by hasanawad94** [comment]
Great thanks for the clarification @Amper @zekker6
