### ISSUE TITLE
Ability to drop metric on vmagent before any processing

### ISSUE THREAD

**Issue by szibis** [VictoriaMetrics/VictoriaMetrics#4658]
### Is your feature request related to a problem? Please describe

In some cases, we would like to drop some metrics based on regexp on the push intake from some external reporters to better handle the garbage that may come in.
I think based on labels or metrics names or field
Maybe such a thing exists but cannot find it in the docs.

### Describe the solution you'd like

Similar to labels relabeling feature to drop metrics based on the pattern.

**Comment by hagen1778** [comment]
Hello @szibis!
You're probably looking for [How to drop metrics during scrape](https://docs.victoriametrics.com/relabeling.html#how-to-drop-metrics-during-scrape).

**Comment by szibis** [comment]
Yeah this is more or less what I was looking for but this is specific for scraping and not see any option when doing push for example via Datadog, Graphite or InfluxDB.

**Comment by hagen1778** [comment]
@szibis please refer to https://docs.victoriametrics.com/vmagent.html#relabeling
> At the -remoteWrite.relabelConfig file. This relabeling is used for modifying labels for all the collected metrics (including [metrics obtained via push-based protocols](https://docs.victoriametrics.com/vmagent.html#how-to-push-data-to-vmagent)) and for dropping unneeded metrics before sending them to all the configured -remoteWrite.url addresses.

This relabeling can be debugged via http://vmagent:8429/metric-relabel-debug page. See [these docs](https://docs.victoriametrics.com/vmagent.html#relabel-debug) for details.

You can use the same relabeling rules but specify them to the -remoteWrite.relabelConfig file, and metrics will be dropped on push.

**Comment by szibis** [comment]
Thank you for clarification
