### ISSUE TITLE
Create a tool for creating regular backups - vmbackmanager

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#466]
**Is your feature request related to a problem? Please describe.**
There is a [vmbackup](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md) tool, which can create a single backup per run. Unfortunately it requires additional code for creating regular backups, because it is unclear how to embed this functionality into `vmbackup` tool itself - see the following issue for details -  https://github.com/VictoriaMetrics/VictoriaMetrics/issues/433 .

**Describe the solution you'd like**
It would be great creating a `vmbackuper` tool with the following functionality:
- It should automate creating regular backups.
- It should support regular backups at the following intervals: hourly, daily, weekly, monthly. Multiple backup intervals must be supported at once. I.e. the `vmbackuper` must create hourly backups every hour, while it must create daily backups every day, etc.
- It should be easy to use - i.e. just run unattended with the minimal number of args:
  * `-storageDataPath` - path to VictoriaMetrics or vmstorage node data to backup.
  * `-snapshot.createURL` - url for creating snapshots
  * `-dst` - backup destination at s3, gcs or local filesystem.

The `vmbackuper` tool must create the following directory hierarchy at `-dst`:

* /latest/ - contains the latest backup
* /hourly/ - contains hourly backups. Each backup is named as `YYYY-MM-DD:HH`
* /daily/ - contains daily backups. Each backup is named as `YYYY-MM-DD`
* /weekly/ - contains weekly backups. Each backup is named as `YYYY-WW`
* /monthly/ - contains monthly backups. Each backup is named as `YYYY-MM`

The latest backups under `/hourly/`, `/daily/`, `/weekly/` and `/monthly/` folders must contain the latest backup for the current hour, day, week or month.

**Describe alternatives you've considered**
An alternative is to create custom scripts around [vmbackup](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md) tool.

**Additional context**
`vmbackuper` is intended for paid Enterprise version only. It won't be available in free open source version of VictoriaMetrics. Feel free expressing interest in this feature either by commenting it or by contacting us at info@victoriametrics.com .

**Comment by valyala** [comment]
FYI, `vmbackuper` has been developed in `enterprise` branch according to the requirements outlined above.

**Comment by valyala** [comment]
`vmbackuper` has been renamed to `vmbackupmanager`. See `vmbackupmanager` docs at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackupmanager/README.md . Note that `vmbackupmanager` is available as a part of [enterprise package](https://victoriametrics.com/enterprise.html).

**Comment by hagen1778** [comment]
@valyala @tenmozes  can we close this?

**Comment by tenmozes** [comment]
Close an issue as vmbackupmanager is a feature complete; see https://docs.victoriametrics.com/vmbackupmanager.html and https://victoriametrics.com/blog/latest-updates-for-backup-compnents-2023-q1/
