### ISSUE TITLE
Stream aggregation: allow configuring staleness for total, increase and histogram_bucket outputs

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4667]
### Is your feature request related to a problem? Please describe

Outputs total, increase and histogram_bucket maintain a static staleness period for aggregated time series. If a time series wasn't captured by the output for a period longer than the staleness period - the series is reseted. The default staleness periods are usually working fine as they cover x2 of the aggregation interval. But sometimes users need to extend the interval for aggregating sporadic observations, like the one produced by lambda functions. For example, if we have an aggregation interval of 1m and lambda-function produces metric on interval from 1m to 3m - then there is a chance the state for time series will reset.

### Describe the solution you'd like

Would be nice if user could manually override the staleness interval for aggregating outputs total, increase and histogram_bucket:
```
- match: 'http_request_duration_seconds_bucket'
  interval: 5m
  staleness_interval: 20m # the metric is expected to be updated at least once in 20m
  without: [instance]
  outputs: [total]
```

### Describe alternatives you've considered

Extend `interval` field to the expected max update interval of the aggregated metric.

**Comment by Amper** [comment]
The feature was released in [VictoriaMetrics v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html#v1920).
