### ISSUE TITLE
incorrect removal of components due to incorrect work of finalizers

### ISSUE THREAD

**Issue by Nello-Angelo** [VictoriaMetrics/VictoriaMetrics#4673]
### Describe the bug

![Screenshot_5](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/82488489/dccb5f55-fe56-4803-aa9a-51cdf6c4fc79)

Always when i try to delete chart the finalizers cant finish correct and because of that i cant delete namespace with victoria metrics components

### To Reproduce

install chart and delete release and you will see that kubernetes delete correct only dependencies charts 

### Version

the latest

### Used command-line flags

i delete via helm and lens

### Additional information
i use [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)
if you want i can show the problem in discord

**Comment by Haleygo** [comment]
@Nello-Angelo 
Hello, can you move the issue [here](https://github.com/VictoriaMetrics/helm-charts) since it's about chart.

**Comment by Nello-Angelo** [comment]
okay
