### ISSUE TITLE
vmui: add button to prettify entered query 

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4681]
### Is your feature request related to a problem? Please describe

Sometimes MetricsQL expressions could be quite complex. Would be great if vmui could auto-format entered queries.

### Describe the solution you'd like

After https://github.com/VictoriaMetrics/metricsql/pull/11 MetricsQL lib can auto-format expressions. Would be nice if vmui had a button next to query field click on which would apply auto-formatting for the entered query.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), [vmui](https://docs.victoriametrics.com/#vmui) allows formatting the query by pressing the `format` button - see [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4694) for details. Closing the feature request as done.
