### ISSUE TITLE
vmalert not re-firing after 1 evaluation 

### ISSUE THREAD

**Issue by victoramsantos** [VictoriaMetrics/VictoriaMetrics#4682]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

Hi, I'm facing a strange behavior with vmalert :confused:
I'm read the issues [#1686](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1686), [#870](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/870) and some messages in VictoriaMetrics slack channel and understood that when vmalert come up, it will query storage (via select) to identify the state of the last alerts. 
If it finds that some alert was in firing state it will put this alert as pending and after the first alert evaluation, if it keeps true, [then vmalert will put it as ](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/870#issuecomment-721398803)`firing` , [independent of the ](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1686#issuecomment-939845777) `for`[ minutes defined for that alert](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1686#issuecomment-939845777). 

**Is that true?**

I performed some tests in my environment but sounds to me that all my alerts, even if it was `firing`, come back as `pending` and starts to wait for the `for` minutes constraint to fire again. 

**Am I missing something :cry: ?**

I can ensure that `-remoteWrite.url` and `-remoteRead.url` are working because I can see the metrics `ALERTS` and `ALERTS_FOR_STATE`. (right? this means that vmalert can save and read the information from vm-storage and vm-insert)

I also noticed in the [doc](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/870) about the difference between labels but it wasn't clear to me (maybe some example over there could help). Because in my architecture, I have prometheus (as agent) performing remote write to vm-insert which send its `external_labels `. I have my record rules and alerts in vmalert which also has its `external_labels` and we are getting this log:
{"ts":"2023-07-19T16:53:06.935Z","level":"info","caller":"VictoriaMetrics/app/vmalert/group.go:87","msg":"label \"cluster_name\"=\"c1\" for rule \"tasks_generic_alert_group\".\"my_rule\" overwritten with external label \"cluster_name\"=\"c1\""}
So I don't know if there is some problem with these override of `external_labels` :confused: 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Resolved on slack https://victoriametrics.slack.com/archives/CGZF1H6L9/p1689884077585049, close as completed)
