### ISSUE TITLE
False Spike with Grafana visualization tool.

### ISSUE THREAD

**Issue by puneet336** [VictoriaMetrics/VictoriaMetrics#4706]
### Describe the bug

I have 2 setup of victoria metrics . One is test bed and another is production.
I use prometheus as main database  and VMs are used for write back copy.

In the test bed, I had collected ~30 days of data, and i migrated the VM data from the test bed to production.
The data monitoring was stopped at 10:02:00 on test bed, data was migrated and and the monitoring resumed at 22:21:30 on the production.

On visualization with Grafana i see a weird issue.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/5935825/41415fe7-3574-4005-9f4c-07d550a10b8e)

but the VM UI shows correct data - 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/5935825/b01693ed-98e1-48d8-b84c-3b8c67b23975)

There is a spike at 10:30 PM in the graph, which is ~2x the normal value and this representation is incorrect. I tried latest version of Grafana but that too shows this peak.

Weird observation is that if i zoom in to last 3/4/5 days , ( the graph on the left) then the spike disappears and if i zoom out to 7 days or more , then the spike re-appears.
i am using sum(feature_name1{label1="value1"})  function.

Please let me know if there is a way to handle / remove this spike. I think the data in the VMs is fine and spike is double counting a value.

Please do let me know if i can provide any further information from my end on this issue.

### To Reproduce

migrated the data base from 1 server to the other.

### Version

victoria-metrics-20230602-095850-tags-v1.91.2-0-gde9481208

**Comment by hagen1778** [comment]
> Please do let me know if i can provide any further information from my end on this issue.

@puneet336 could you please give more context about migration procedure? How exactly you performed it? 
Have you gone through https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results ?

**Comment by puneet336** [comment]
Hi @hagen1778  , i think i got hold of this issue
After stopping the prometheus and VM processes, I was copying the data collected on the test bed  using rsync to the new cluster.

The old cluster had instance label - monitoringcluster2:8481 
and new one had monitoringcluster1:8428 

The migration happened started 10:15  and finished at ~10:20 .

so when i select 7 days , then the Grafana shows intervals as - 
10:00 , 10:30 , 11:00 . and as there is data from  2 instances between 10:01 to 10:30 in the database, i think promeheus is adding up the data . But i find it strange that why VM did not do the same.


https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4708
