### ISSUE TITLE
/api/v1/labels returns empty response after upgrading from 1.79.13 to 1.87.6 

### ISSUE THREAD

**Issue by rassvetalov** [VictoriaMetrics/VictoriaMetrics#4707]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I'm experiencing an issue after upgrading VictoriaMetrics from version 1.79.13 to 1.87.6 by replacing the binary. It seems like data is getting lost after the update. Before the update, the command 
curl -XGET http://victoria-a-tmp.service.consul:2022/api/v1/labels gave this output: {"status":"success","data":["__name__","agent_name","app_id","appname","build_branch","build_type","build_type_id","bver","country","datacenter","fleet_type","instanceaz","instancetype","level","location","meta_runner","model","name","os","page","path","percentile","platform","pool","project","project_name","responsible","source","status","step_group","step_name","sub_project","tag32","task","tg","trigger","type","type1","type2","type3","user","vcs_name","version","vmrange"]}. 

However, after the update, the same command returns an empty list: {"status":"success","data":[]}. The VictoriaMetrics logs show that the parts are being opened successfully and the cache has been cleared, yet the problem persists. I'm reaching out to the community for any assistance or suggestions on how to troubleshoot this. If anyone has experienced a similar issue, your insights would be highly appreciated. 

Thank you in advance!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hi @rassvetalov!
I believe you're facing the following change introduced in https://docs.victoriametrics.com/CHANGELOG.html#v1820:

> FEATURE: set the start arg to end - 5 minutes if isn't passed explicitly to [/api/v1/labels](https://docs.victoriametrics.com/url-examples.html#apiv1labels) and [/api/v1/label/…/values](https://docs.victoriametrics.com/url-examples.html#apiv1labelvalues). See [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3052).

You need to explicitly set `start` and `end` args for this API.

**Comment by jiekun** [comment]
Close as answered.
