### ISSUE TITLE
How to migrate data and keep the instance name as same

### ISSUE THREAD

**Issue by puneet336** [VictoriaMetrics/VictoriaMetrics#4708]
### Is your question request related to a specific component?

Victoria Metrics

### Describe the question in detail

Hi , 
I am using Prometheus and Victoria Metrics where setup is as - 

`Cluster1: (July20 - current)`
node exporter <---- prometheus ----(remote write)---->   Victoria Metrics4 , Victoria Metrics5, Victoria Metrics6
Where  instance="monitoringcluster1:55200",

`Cluster2: (July 3 - July 19)`
node exporter <---- prometheus ----(remote write)---->   Victoria Metrics1 , Victoria Metrics2, Victoria Metrics3

Where  instance="monitoringcluster2:55100",

I wish to merge/migrate the Data from Cluster2 to Cluster 1 as  :
```
Victoria Metrics1  -->   Victoria Metrics4 
Victoria Metrics2 --> Victoria Metrics5
Victoria Metrics3 --> Victoria Metrics6

```
How can i keep the instance name as same ?i.e. 
i wish to keep  instance="monitoringcluster1:55200" while migrating data from Cluster2 to 1 to avoid situation like - 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/5935825/6efe2393-ec50-46c7-8df1-0aeeb734f57e)

Where Grafana ends up showing multiple color and multiple labels as there are 2 different instances.

Say for Victoria Metrics1  -->   Victoria Metrics4  - 
Q1: As i am moving data from Victoric Metrics1 to Victoria Metrics4, How do i change the name of the instance from   instance="monitoringcluster2:55100", to instance="monitoringcluster1:55200"   using following command - ?
```
 ./vmctl vm-native \
    --vm-native-src-addr=http://monitoringcluster2:8481/select/0/prometheus \ # migrate from
    --vm-native-dst-addr=http://monitoringcluster1:8428                     # migrate to
    --vm-native-filter-time-start='2022-11-20T00:00:00Z' \           # starting from
```
    
    
Q2: While running the above command, do i need to stop the remote-writes from prometheus to VM at monitoringcluster1:8428 ?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @puneet336 ! You can migrate your data using relabeling. In that case, you should enable reliable config into prometheus or use [vmagent](https://docs.victoriametrics.com/vmagent.html). Both of them support [relabeling](https://docs.victoriametrics.com/vmagent.html#relabeling). In your case, you should config relabeling, which you need into prometheus or vmagent, and vmctl should write the data into them. Into prometheus or vmagent data will be relabeled and written to your cluster. 
So into `--vm-native-dst-addr=http://prometheusorvmagent:port` - you should specify vmagent or prometheus address

**Comment by puneet336** [comment]
Thank you , I was able to migrate the data using vmctl.

--vm-extra-label instance="monitoringcluster1:55200"
