### ISSUE TITLE
excessive resource usage after enabling vmalert/vmalertmanager

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/VictoriaMetrics#4710]
### Describe the bug

I've been using VictoriaMetrics for a couple of weeks and resource usage has been generally great. I enabled VMAlert/VMAlertmanager and the resource usage 100x'd in some cases.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/58dedb0e-7314-415b-8afb-99ddbf9cb3ee)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/e9c48984-f33d-4f37-89b4-540848acd204)

[VMAlert](https://github.com/uhthomas/automata/blob/5a5f55f61928df884a8b4422091f4d5fbfef86bc/k8s/unwind/vm/vm_alert_list.cue#L17)

[VMAlertManager](https://github.com/uhthomas/automata/blob/5a5f55f61928df884a8b4422091f4d5fbfef86bc/k8s/unwind/vm/vm_alertmanager_list.cue#L17)

[VMCluster](https://github.com/uhthomas/automata/blob/5a5f55f61928df884a8b4422091f4d5fbfef86bc/k8s/unwind/vm/vm_cluster_list.cue#L17)

### To Reproduce

See above

### Version

docker.io/victoriametrics/vmstorage:v1.91.3-cluster

**Comment by hagen1778** [comment]
Hey @uhthomas!
From the provided screenshots it is clear that resource usage increase correlates with increase of /api/v1/query produced by vmalert. The more queries VM has to serve, the bigger resource usage one should expect. 

To reduce resource usage I'd recommend revise configured rules for vmalert and following https://docs.victoriametrics.com/Troubleshooting.html#slow-queries
