### ISSUE TITLE
VictoriaLogs Will Support Log Alerts？

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#4711]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

VictoriaLogs Will Support Log Alerts as loki ？

**Comment by hagen1778** [comment]
Hi @tripitakav! It is likely alerting for VictoriaLogs will be supported by vmalert eventually.
@valyala should we add this to https://docs.victoriametrics.com/VictoriaLogs/Roadmap.html
or is this something to be tracked for vmalert separately? Or do you have other plans for alerting?
