### ISSUE TITLE
Metrics is drop when i using telegraf to push metrics to victoria metrics.

### ISSUE THREAD

**Issue by iamhieupc** [VictoriaMetrics/VictoriaMetrics#4715]
### Describe the question in detail

when i config label rule as below figure, label is monitor: test-nginx
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/72189639/0d341c69-775a-4ed2-9e15-fc444c5067c0)
But in some case, i test insert metrics to victoria metrics by api, such as: curl -i -XPOST 'http://10.3.55.207:10013/write' -u 'test-nginx:bW9uaXRvcmluZwo=' --data-binary 'my_measurement,monitor=test tag1=1526918498000000000'.
Hmmmm, Then metric is droped because the label is assigned wrong (monitor=test not match monitor: test-nginx).
How to get metrics is droped or get labels is not match to labels is defined?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @hustchihieu143 
In your case when you're sending `my_measurement,monitor=test tag1=1526918498000000000` it is parsed as
```
{"__name__":"my_measurement_tag1","monitor":"test"}
```
But your relabeling rule will search for `monitor=test-nginx`, so that this will be dropped.

It seems like you're mixing basic auth credentials with an actual metric data here, so you need to either adjust your relabeling rule or to correct data format for label to have `test-nginx` value.

**Comment by hustchihieu143** [comment]
Thank @zekker6, I'm testing case is drop metrics to fix bug. Because I was built victoria cluster and other team will push metrics to victoria metrics and i dont know way they relabel. How to get metrics is droped or labels is wrong?

**Comment by zekker6** [comment]
@hustchihieu143 You can use [cardinality explorer](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#cardinality-explorer) to expore metrics and labels which might create too many unique values for your setup.

**Comment by hustchihieu143** [comment]
@zekker6 When too much metrics is droped make CPU and RAM go to limit. How to flush or delete metrics is droped?

**Comment by zekker6** [comment]
@hustchihieu143 I'm not sure if I understand the question correctly. Could you elaborate a bit on what do you mean by "flush metrics is dropped"?
