### ISSUE TITLE
vmui: query history

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4718]
### Is your feature request related to a problem? Please describe

it would be nice to have the option to see the latest N queries or/and have them in autocompletion 

### Describe the solution you'd like

N/A

**Comment by hagen1778** [comment]
I personally dislike this feature request. I haven't seen good implementation of it yet. In all cases, query history was one more obstacle to entering the query you need.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), query history is available in `vmui` by clicking the `history` icon - see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4759#issue-1831590053 for details. Closing the feature request as done.
