### ISSUE TITLE
vmui: option to see/copy the full error message

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4719]
### Is your feature request related to a problem? Please describe

Long error messages get cropped in vmui, so they won't take too much space. But in rare cases users want to share the error message and because of cropping they have no way to do this.
It would be nice to have the option to see the full error message or copy it.

**Comment by valyala** [comment]
Starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html), [vmui](https://docs.victoriametrics.com/#vmui) shows full error message after clicking on it. Closing the feature request as done.
