### ISSUE TITLE
vmagent: persistentqueue metric data missing

### ISSUE THREAD

**Issue by amalsom10** [VictoriaMetrics/VictoriaMetrics#4720]
### Describe the bug

I am seeing data missing in the Grafana dashboard using Victoriametrics as the data source and in the Vmagent error log I am seeing the below logs
`"/vmagentData/persistent-queue/1_F0660D40678E4D34/0000000A00002800" size (9968502 bytes) is bigger than writer offset (8632042 bytes); this may be the case on unclean shutdown (OOM, `kill -9`, hardware reset); trying to fix it by adjusting fileSize to 8632042
cannot open persistent queue at "/vmagentData/persistent-queue/1_F0660D40678E4D34": couldn't find chunk file for writing in "/vmagentData/persistent-queue/1_F0660D40678E4D34"; cleaning it up and trying again`

This can be related to the vmagent pod restart, but I am hoping that the vmagent pods are supposed to restart gracefully without data corruption or data loss.

I am trying to find out how to correlate this error with the metrics missing issue.

### To Reproduce

This is happening when the vmstorage pods are unavailable and the vminsert service endpoints are completely unreachable.

In the metrics of vminsert the ingestion rate went to 0 and vmagent persistent queue metrics started spiking.

### Version

victoriametrics/vmagent:v1.78.1

### Logs

"/vmagentData/persistent-queue/1_F0660D40678E4D34/0000000A00002800" size (9968502 bytes) is bigger than writer offset (8632042 bytes); this may be the case on unclean shutdown (OOM, `kill -9`, hardware reset); trying to fix it by adjusting fileSize to 8632042
cannot open persistent queue at "/vmagentData/persistent-queue/1_F0660D40678E4D34": couldn't find chunk file for writing in "/vmagentData/persistent-queue/1_F0660D40678E4D34"; cleaning it up and trying again

### Used command-line flags

  ./vmagent-prod \
        -promscrape.config=/config/scrape.yml \
        -promscrape.maxDroppedTargets=3000 \
        -promscrape.maxScrapeSize=130000000 \
        -promscrape.streamParse \
        -promscrape.cluster.replicationFactor=2 \
        -promscrape.cluster.membersCount=6 \
        -remoteWrite.maxDiskUsagePerURL=49GB \
        -promscrape.cluster.memberNum=${PROMSCRAPE_CLUSTER_MEMBER_NUM} \
        -promscrape.kubernetesSDCheckInterval=7s \
        -remoteWrite.tmpDataPath=/vmagentData \
        -remoteWrite.url=http://vminsert.victoriametrics-system.svc.cluster.local:8480/insert/0/prometheus/ \
        -remoteWrite.queues=20 \
        -envflag.enable=true \
        -envflag.prefix=VM_ \
        -loggerFormat=json

**Comment by dmitryk-dk** [comment]
Hi @amalsom10 ! If the vmagent finished unexpectedly data can be corrupted. In that case, vmagent tries to restore data. If it is impossible it cleans data and tries to start the process again. So that you see this problem.

**Comment by dmitryk-dk** [comment]
Yes it is the reason, because data from persistent queue did not insert to the storage

**Comment by valyala** [comment]
> So is it the reason for the metrics missing gap in the Grafana dashboard?

Yes - when `vmagent` is shut down uncleanly (such as `kill -9`, `OOM crash`, hardware reset), then it may leave persistent queues with the buffered data, which wasn't sent to remote storage systems yet, in inconsistent state. After the restart it tries recovering the data from persistent queues, but it may fail to do this. In this case it logs the message like you provided in the original bugreport, then just drops the persistent queues and continues working. This may result in data loss. The solution for avoiding this is to use graceful shutdown at `vmagent`, e.g. by sending `SIGINT` signal to it. In this case `vmagent` gracefully completes the current work, then saves the remaining unsent data to persistent queues, and then exits. The graceful shutdown may take non-trivial amounts of time, so by default `vmagent` limits the duration for graceful shutdown to 7 seconds. After that it just terminates the process, which may lead to inconsistent persistent queue data. The graceful shutdown duration limit can be configured via `-http.maxGracefulShutdownDuration` command-line flag.

> We are running Victoriametrics in a GKE cluster, so pod restart can happen anytime, Is there any way to avoid such a situation?

There are the following ways for avoiding data loss during `vmagent` restarts:

- To always use graceful shutdown, e.g. to send `SIGINT` signal to `vmagent` and wait until it finishes.
- To increase the `-http.maxGracefulShutdownDuration` command-line flag value if `vmagent` cannot perform graceful shutdown in under 7 seconds for your workload.
- To give move resources to `vmagent` (CPU, RAM, disk IO bandwidth), so it can perform graceful shutdown in under default 7 seconds.

**Comment by jiekun** [comment]
Close as answered.

**Comment by viktornordling** [comment]
Any chance we can reopen this? I think this can be fairly easily reproduced by causing a queue to build up to a large size (by disconnecting a network interface, for example), then killing the process while the queue is being worked off (after the network interface has been reconnected).

In our case, we had a significant amount (gigabytes) of important data we wanted to write to the `remoteWriteUrl` when this happened. Would it be feasible to split the "file" (if it is one file) backing this queue into multiple files, such that if one file gets corrupted, we only need to discard a part of the queue?
