### ISSUE TITLE
vmui: display partial response warning

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4721]
### Is your feature request related to a problem? Please describe

Cluster installation of VictoriaMetric could return partial responses if one or vmstorage nodes didn't respond. But in vmui interface it is impossible to tell whether response is complete or partial.

### Describe the solution you'd like

Would be great if vmui could understand `isPartial` field from VM HTTP API response and show a warning if result is marked as partial.
<img width="180" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/bdd881ab-3dd8-4203-aa32-4b194b1c678f">

**Comment by valyala** [comment]
[vmui](https://docs.victoriametrics.com/#vmui) should display partial response warning starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.

BTW, it would be great to provide a checkbox at `vmui` for toggling `deny_partial_response` query arg when sending the query to VictoriaMetrics, in the same way as `disable cache` checkbox works now. See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) for details about the `deny_partial_response` query arg. @hagen1778 , @Loori-R , what do you think about this?

**Comment by hagen1778** [comment]
> provide a checkbox at vmui for toggling deny_partial_response query arg when sending the query to VictoriaMetrics, in the same way as disable cache checkbox works now. See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) for details about the deny_partial_response query arg. @hagen1778 , @Loori-R , what do you think about this?

I don't think this is necessary. Deny of partial response is useful for automation, so it won't take any actions (hpa or alerting) based on incomplete data. But for ad-hoc purposes, it doesn't matter that much because a human operator expected to take this decision on they own.

In other words, I don't see why one should deny partial responses in VMUI and get errors instead of partial data + warning that data is partial.

**Comment by Loori-R** [comment]
This issue is no longer relevant as it has been addressed in another discussion. Please refer to #4848.
