### ISSUE TITLE
Backtrace / panic

### ISSUE THREAD

**Issue by thierry-f-78** [VictoriaMetrics/VictoriaMetrics#4722]
### Describe the bug

The process is already running in background, and the lock cannot be acquired.

I think a panic/backtrace is not justified for this common case.

Note: In my mind, panic message is for developper, error message is for administrator, this case is an administrator case.

```
2023-07-27T08:24:52.911Z	info	lib/logger/flag.go:12	build version: vmstorage-20230726-090515-tags-v1.91.3-cluster-0-g12f262c33
2023-07-27T08:24:52.911Z	info	lib/logger/flag.go:13	command-line flags
2023-07-27T08:24:52.911Z	info	lib/logger/flag.go:20	  -httpListenAddr=":18482"
2023-07-27T08:24:52.911Z	info	lib/logger/flag.go:20	  -retentionPeriod="90d"
2023-07-27T08:24:52.911Z	info	lib/logger/flag.go:20	  -storageDataPath="/home/thierry/vmstorage01"
2023-07-27T08:24:52.911Z	info	lib/logger/flag.go:20	  -vminsertAddr=":18400"
2023-07-27T08:24:52.912Z	info	lib/logger/flag.go:20	  -vmselectAddr=":18401"
2023-07-27T08:24:52.912Z	info	app/vmstorage/main.go:100	opening storage at "/home/thierry/vmstorage01" with -retentionPeriod=90d
2023-07-27T08:24:52.912Z	panic	lib/fs/fs.go:366	FATAL: cannot create lock file: cannot acquire lock on file "/home/thierry/vmstorage01/flock.lock": resource temporarily unavailable; make sure a single process has exclusive access to "/home/thierry/vmstorage01"
panic: FATAL: cannot create lock file: cannot acquire lock on file "/home/thierry/vmstorage01/flock.lock": resource temporarily unavailable; make sure a single process has exclusive access to "/home/thierry/vmstorage01"

goroutine 1 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x96f6ea, 0x5}, {0xc00015a0e0, 0xd4}, 0x2?)
	/home/thierry/VictoriaMetrics/lib/logger/logger.go:281 +0xa96
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, {0x96f6ea, 0x5}, {0x9964a5?, 0xc00014e390?}, {0xc00023f618?, 0xc0000a00f0?, 0xc0000d46c0?})
	/home/thierry/VictoriaMetrics/lib/logger/logger.go:138 +0x1a5
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevel(...)
	/home/thierry/VictoriaMetrics/lib/logger/logger.go:130
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.Panicf(...)
	/home/thierry/VictoriaMetrics/lib/logger/logger.go:126
github.com/VictoriaMetrics/VictoriaMetrics/lib/fs.MustCreateFlockFile({0x7fff0d4f55f9, 0x19})
	/home/thierry/VictoriaMetrics/lib/fs/fs.go:366 +0xfd
github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.MustOpenStorage({0x7fff0d4f55f9?, 0x96f3a1?}, 0x1cf7c5800, 0x0, 0x0)
	/home/thierry/VictoriaMetrics/lib/storage/storage.go:181 +0x3ed
main.main()
	/home/thierry/VictoriaMetrics/app/vmstorage/main.go:102 +0x4a5
```

### To Reproduce

Start vmstorage two times, second time hang.

### Version

I try with release "v1.91.3-cluster", and with current branch "cluster 2e39070f95ed6"

### Used command-line flags

~/VictoriaMetrics/bin/vmstorage \
	-retentionPeriod "90d" \
	-storageDataPath "~/vmstorage01" \
	-vminsertAddr ":18400" \
	-vmselectAddr ":18401" \
	-httpListenAddr ":18482"

**Comment by dmitryk-dk** [comment]
Hi @thierry-f-78 ! Why it happens if described in this [comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3578#issuecomment-1373071787)

In the previous version, it doesn't panic need some time for investigation

**Comment by dmitryk-dk** [comment]
Hi @thierry-f-78 ! This panic is create by design please check this [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/2a3b19e1d21ffee9b74fbb92fa5e435f94d433ef). So it would panic if process can't create flock.lock file

**Comment by thierry-f-78** [comment]
Dealing with the error in the `MustCreateFlockFile` function seems like a good thing, as the commit message explains. On the other hand, triggering a panic with a backtrace is a sign of a "software error" and not a "functional error". An administrator who is not a developer can be misled (as I was when I saw the backtrace).

Maybe it would be better if the `MustCreateFlockFile` function is renamed `CreateFlockFileOrQuit` (it seems that in Go, functions prefixed with `Must` generate panics on failure), just issue a log with `Fatalf ` or the behavior and reporting seems more appropriate to the situation.

**Comment by thierry-f-78** [comment]
ok

**Comment by valyala** [comment]
Let me explain our decision in more detail. `FATAL` errors may occur inside deeply nested functions. These functions may be called from different code paths. If we just log the `FATAL` error inside the function, then it may miss important details on the context where the error has been occurred. This may complicate determining what went wrong at which context. So previously the `FATAL` error wasn't logged at the place where it has been occurred. Instead, the error was returned to the caller. The caller was adding its' context to the error and returning the error to its' caller, and so on, until the top-level caller is reached, which, in turn, could log the error alongside the collected contexts from all the caller chain. This approach had the following issues:
- It required adding non-trivial amounts of code alongside nested function call chains for handling fatal errors.
- The resulting error message could become too long and could contain repeated text obtained from different levels of function call chain.

So we decided it would be better to just log the `FATAL` error at the place it occurs, alongside printing the stack trace, which can help debugging the error.

As for the `BUG` log messages, they are most likely bugs at our code, which must be fixed. So it is recommended filing bugreports whenever you see `BUG` messages in your logs. Do not forget providing the full stack trace alongside the `BUG` log message in such bugreports.

**Comment by thierry-f-78** [comment]
HI, thanks for the explanation, its very clear. I understand your choice.
On my side, it implies some explanations for administrators.
