### ISSUE TITLE
Leaking connections in service discovery

### ISSUE THREAD

**Issue by skoppe** [VictoriaMetrics/VictoriaMetrics#4724]
### Describe the bug

We are using `consulagent_sd_configs` and `consul_sd_configs` and saw connection leaks with vmagent `v1.91.3`.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/6967044/bc8cc4a1-4ed1-44a0-9b63-68b6d7d8c6bb)

This was the error we got in the log:

```
2023-07-27T07:52:12.139Z error VictoriaMetrics/lib/promscrape/config.go:1097 skipping consulagent_sd_config targets for job_name "consul-agent-services" because of error: cannot get API config: cannot obtain consul datacenter: cannot query consul agent info: unexpected status code returned from "https://127.0.1.1:8501/v1/agent/self": 403; expecting 200; response body: "Permission denied: anonymous token lacks permission 'agent:read' on \"xyz\". The anonymous token is used implicitly when a request does not specify a token."
```

As you can see we had misconfigured the consul anonymous policy to not include the `agent:read` permission. 

However, while `vmagent` was correctly bailing out at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/4cd1497ac12e97d07b5690b96ac3dd57318fe5df/lib/promscrape/discovery/consulagent/api.go#L79 it *also* leaked client connections, causing consul to apply rate limiting on `localhost`, which in turn triggered failures in other systems on that host.

I see that in the code the `apiConfig` is cached into `SDConfig`, however this is only *after* `newAPIConfig` returns successfully. Any failure there causes connections to leak.

### To Reproduce

Use either `consulagent_sd_configs` and `consul_sd_configs`  and connect them to a consul agent / server with insufficient privileges.

### Version

```
$ vmagent --version
vmagent-20230630-132309-tags-v1.91.3-0-g7226242070
```

**Comment by valyala** [comment]
@skoppe , thanks for filing the detailed bugreport! Could you build `vmagent` from the commit 3d73640815f76d5a5a1260ba1ecd65dbe4437a98 according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether it properly closes HTTP connections to Consul now?

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/3d73640815f76d5a5a1260ba1ecd65dbe4437a98 has been included in [vmagent v1.92.0](https://docs.victoriametrics.com/CHANGELOG.html). @skoppe , could you upgrade to v1.92.0 and verify whether this fixes the issue is connection leak?

**Comment by skoppe** [comment]
@valyala Thanks for the quick response. Connections have been stable for the past days.

**Comment by valyala** [comment]
FYI, the bugfix for this issue has been back-ported to [long term support release v1.87.7](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.7).
