### ISSUE TITLE
victorialogs: increase promtail visibility 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#4728]
### Is your feature request related to a problem? Please describe

We recently add Promtail to VictoriaLogs and need to cover several areas and increase the visibility 

- [x] Update data ingestion section in documentation https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/#log-collectors-and-data-ingestion-formats (collectors section)
- [x] Update roadmap mark is completed and link to the documentation 
- [x] Add a docker example as we have for other collectors 
- [x] Update QuickStart and add an example from the docker 
- [x] https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/Promtail.html Update stream section, how to map Loki streams to VL streams 

### Describe the solution you'd like

n/a

**Comment by valyala** [comment]
All the tasks from the list above are done in the commit 116623a0f0993ba45407ffe93d8b621dd1c3ecb7 . Closing the issue as done.
