### ISSUE TITLE
Latest HELM charts missing

### ISSUE THREAD

**Issue by sreejith-vk** [VictoriaMetrics/VictoriaMetrics#4729]
### Is your question request related to a specific component?

victoria-metrics-cluster

### Describe the question in detail

The latest helm charts are not available for download. Please check.
```
$ wget https://victoriametrics.github.io/helm-charts/packages/victoria-metrics-cluster-0.10.2.tgz
--2023-07-28 08:07:13--  https://victoriametrics.github.io/helm-charts/packages/victoria-metrics-cluster-0.10.2.tgz
Resolving victoriametrics.github.io (victoriametrics.github.io)... 185.199.109.153, 185.199.110.153, 185.199.111.153, ...
Connecting to victoriametrics.github.io (victoriametrics.github.io)|185.199.109.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-28 08:07:13 ERROR 404: Not Found.

```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello! 
I don't think we have this chart under `https://github.com/orgs/VictoriaMetrics/packages?repo_name=helm-charts` in the first place.
Please try the [add the helm repo](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/README.md) and pull from there.
```
helm repo add vm https://victoriametrics.github.io/helm-charts/
helm repo update
helm search repo vm/victoria-metrics-cluster -l
```
