### ISSUE TITLE
Qustion about counter value reset

### ISSUE THREAD

**Issue by rightly** [VictoriaMetrics/VictoriaMetrics#4732]
### Is your question request related to a specific component?

Victoria metrics (cluster v1.85.3)

### Describe the question in detail

- The custom exporter developed performs the operation of parsing and exporting the value after performing a specific command.
- vmagent scraping this metrics every 1m.
- The result value of the command is initialized every hour, and the counter metric value is also initialized accordingly.
- I expected the rate(), increase() functions to handle it well, but the reality was not.
- please refer below images
  - rate(one_of_counter_total[1m])
    - <img width="839" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17899505/e472553d-44e3-41c5-baf5-65c7d4d38df4">
  - one_of_counter_total
    - <img width="831" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17899505/78e1e543-9e7c-448b-98fa-04bfa4130b2e">

How can I get a graph without a spike?
Can anyone help me with this?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, counter reset must be properly handled in your case. Probably, it's a bug.

 May I ask you to provide a data sample for testing? It can be exported via API call:

```text
curl http://localhost:8428/api/v1/export -g -d 'match[]=one_of_counter_total' -d 'start=-2h' -d 'reduce_mem_usage=true' > data_sample.json`
```

 Important param - `reduce_mem_usage=true`, it must export data without de-duplication.

Timestamps + values is actually required, series name could be obscured.

**Comment by rightly** [comment]
@f41gh7 
Sorry for late.
Here is sample data.
- [data_sample.json.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12210625/data_sample.json.zip)

Thank you for your help!

**Comment by rightly** [comment]
@f41gh7 
Thank you.

I understand what you're saying to a issue.
However, may I know how to resolve the vmagent's inconsistent counter reset issue?
Can I solve it by reducing the scrape interval..  or Whether the custom exporter should force the value to be corrected to zero when counter reset occurs

**Comment by f41gh7** [comment]
> @f41gh7 Thank you.
> 
> I understand what you're saying to a issue. So can I ask for advice on how to fix the inconsistent counter reset problem ? Can I solve it by reducing the scrape interval.. or Whether the custom exporter should force the value to be corrected when counter reset occurs

 Possible workaround for me - update timestamps and values for your exported metrics according to the your scrape interval. It should make changes consistent. 

pseudo-code example
```

var currentTimestamp = now()
var currentMetrics = metricsSet
var nextMetrics = metricsSet

 type metricsSet struct{
    timestamp int64
    metrics []metric(name,value)
 }

for {
   time.sleep(60)
   currentTimestamp += 60
   newMetrics = metricsSet{timestamp: currentTimestamp}
   currentMetrics = nextMetrics
   nextMetrics = newMetrics
 }

func writePrometheusMetrics(w writer){
  w.Write(currentMetrics)
}
```

**Comment by rightly** [comment]
@f41gh7 
Thank you for your advice :)
Good!

**Comment by f41gh7** [comment]
Other option, you can use push model instead of pull.
