### ISSUE TITLE
vmalert getting error "dial tcp: lookup victoria-metrics on 127.0.0.11:53: no such host"  when executing query on victoria-metrics

### ISSUE THREAD

**Issue by jitendragedam** [VictoriaMetrics/VictoriaMetrics#4733]
### Is your question request related to a specific component?

VictoriaMetrics and vmalert

### Describe the question in detail

I am using docker swarm and in my docker-compose.yml I have configured multiple services and defined overlay network. Have configured **victoriametrics** and **vmalert** as follows:
`  victoria-metrics:
    image: "victoriametrics/victoria-metrics:v1.82.0"
    ports:
        - 8428:8428        
    networks:
     my-network:
	 
  vmalert:
    image: "victoriametrics/vmalert:v1.83.1"
    depends_on:
      - "victoria-metrics"
      - "alertmanager"
    ports:
      - 8880:8880
    command:
      - "--datasource.url=http://victoria-metrics:8428/"
      - "--remoteRead.url=http://victoria-metrics:8428/"
      - "--notifier.url=http://alertmanager:9093/"
      - "--rule=/etc/alerts/*.yml"
    networks:
     my-network:`

All works file for some time after starting the services, I am able to see alerts on vmalert UI and vmalert is also notifying correctly to alertmanager, so the configurations seems fine. However after sometime I am seeing following logs in vmalert

`vmalert.1.xxxx@xxx    | 2023-07-27T09:26:37.027Z error   VictoriaMetrics/app/vmalert/group.go:298        group "custom_metrics_rules": rule "test_critical_alert": failed to execute: failed to execute query "<query-expression>": error getting response from http://victoria-metrics:8428/api/v1/query?query=<query>&step=300s&time=1690449960: Post "http://victoria-metrics:8428/api/v1/query?query=<query>&step=300s&time=1690449960": dial tcp: lookup victoria-metrics on 127.0.0.11:53: no such host`

Not able to figure out why this is happening as the configuration seems to be correct and working fine for some time after starting the services. After getting this error, subsequent all rules keep failing with same error and this error does not go away.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by denisgolius** [comment]
Hi @jitendragedam !
Looks like you failed in issue with DNS on your docker swarm. AFAIK `tcp: lookup victoria-metrics on 127.0.0.11:53: no such host` will return when your host can't resolve domain name into ip address.

**Comment by jitendragedam** [comment]
Hi [denisgolius](https://github.com/denisgolius) !

Thanks for your quick reply and pointing me in the right direction. There was an issue with my setup, the host machine's default DNS service was competing with the configured dnsmasq docker service. After correcting this issue the vmalert API calls to victoriametrics are working fine and I have not seen the error for last two hours.

Thanks for the help!

Regards,
Jitendra
