### ISSUE TITLE
How to handle this situation：cannot execute funcName=\"searchMetricNames_v3\" on vmstorage 

### ISSUE THREAD

**Issue by sunyu-2020** [VictoriaMetrics/VictoriaMetrics#4736]
### Is your question request related to a specific component?

wmstorage

### Describe the question in detail

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/63139578/7da4b242-ebfb-4ff8-bbe9-e81fcf421b14)
{
    "status": "error",
    "errorType": "422",
    "error": "cannot fetch time series for \"accountID=0, projectID=0, filters=[{__name__=\\\"kafka_consumergroup_lag_sum\\\"}], timeRange=[2023-07-28T08:30:29Z..2023-07-28T09:30:29Z]\": cannot fetch metric names from vmstorage nodes: cannot search metric names on vmstorage {{ip}}: cannot execute funcName=\"searchMetricNames_v3\" on vmstorage \"10.107.1.60:8401\": EOF"
}

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, EOF usually means, that connection between vmselect and  vmstorage was unexpectedly closed. It could be a restart of vmstorage. I'd recommend to check vmstorage logs and state.

**Comment by jiekun** [comment]
Close as answered.
