### ISSUE TITLE
vlogs: add support of `storage.minFreeDiskSpaceBytes` flag

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#4737]
### Is your feature request related to a problem? Please describe

Currently, when VLogs is running out of free disk space there is no graceful handling similar to how VictoriaMetrics does this.
This results in DB getting into crash loop when trying to create new files.

### Describe the solution you'd like

Add support of `--storage.minFreeDiskSpaceBytes` command-line flag.

**Comment by valyala** [comment]
The `-storage.minFreeDiskSpaceBytes` command-line flag is available in VictoriaLogs starting from [v0.4.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.4.0-victoralogs). Closing the feature request as done.
