### ISSUE TITLE
vmctl: support `week` step for time-based chunks

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4738]
### Is your feature request related to a problem? Please describe

vmctl supports [time-based chunking of migration](https://docs.victoriametrics.com/vmctl.html#using-time-based-chunking-of-migration) with the following time units: month, day, hour, minute.

But there is a big difference in time between a `day` and `month`.

### Describe the solution you'd like

Would be nice to support `week` time unit for time-based chunking migration.

**Comment by valyala** [comment]
The `--vm-native-step-interval` command-line flag at [vmctl](https://docs.victoriametrics.com/vmctl.html) gains support for `week` option starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
