### ISSUE TITLE
vmstorage, high-avalaibility and data restoration

### ISSUE THREAD

**Issue by thierry-f-78** [VictoriaMetrics/VictoriaMetrics#4740]
### Is your question request related to a specific component?

vmstorage, high-avalaibility and data restoration

### Describe the question in detail

After reading and rereading the documentation, I conclude if I want a high availability of a cluster with the avalaibility of all the data, I must configure a replication factor so that the data is replicated on several nodes. In the event of a node failure, the only way to preserve the data is to use a type of high availability storage such as EBS in the cloud, or a SAN if on-premise. To prevent a failed node and unrecoverable corrupted data, backups must be made, there is no other way to restore data from a failed node.

If what I'm saying above is wrong, the rest of my post is pointless.

Since the data is replicated, wouldn't it be interesting to be able to rebuild the broken vmstorage from the other vmstorage ? This software evolution would make it possible to have high availability at a very moderate cost (a high availability SAN is very expensive, and not everyone is not concerned by the cloud).

I think a "vmrebuild" binary which knows all the storage pools, which connects to them and searches for the data which lacks a duplicate to recreate them on a new node, which will suffice to insert into the pool when it is recreated.

In other way, I read that it is recommended to add vmstorage nodes, rather than having nodes with a large volume of data. If I put several vmstorage on virtual machines, hosted on two hypervisors only (or several vmstorage on the same physical server) how can I be sure that the replicas will be between two physical servers? I couldn't find any documentation on this. Perhaps add in "vminsert" the notion of storage group or each group must be understood as being independent (ex: two physical servers, two datacenters, ...). I imagine something like below, based on facultative prefix of each vmstorage address:

```
vminsert \
	-replicationFactor 2 \
	-storageNode group0@10.211.55.13:18400 \
	-storageNode group0@10.211.55.13:28400 \
	-storageNode group0@10.211.55.13:38400 \
	-storageNode group0@10.211.55.13:48400 \
	-storageNode group1@10.211.55.14:18400 \
	-storageNode group1@10.211.55.14:28400 \
	-storageNode group1@10.211.55.14:38400 \
	-storageNode group1@10.211.55.14:48400
```

It may also be interesting to set the replica groups so that all the data from vmstarage A is replicated to vmstorage B, and only vmstorage B. In this way, the restoration of node B in the event of a failure would be a copy of data from any other node in the same replication group group.

```
vminsert \
	-replicationFactor 3 \
	-storageNode replica0@10.211.55.13:18400 \
	-storageNode replica1@10.211.55.13:28400 \
	-storageNode replica2@10.211.55.13:38400 \
	-storageNode replica3@10.211.55.13:48400 \
	-storageNode replica0@10.211.55.14:18400 \
	-storageNode replica1@10.211.55.14:28400 \
	-storageNode replica2@10.211.55.14:38400 \
	-storageNode replica3@10.211.55.14:48400 \
	-storageNode replica0@10.211.55.13:18400 \
	-storageNode replica1@10.211.55.13:28400 \
	-storageNode replica2@10.211.55.13:38400 \
	-storageNode replica3@10.211.55.13:48400
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by denisgolius** [comment]
@valyala wdyt?

**Comment by Amper** [comment]
Hey @thierry-f-78.

> Since the data is replicated, wouldn't it be interesting to be able to rebuild the broken vmstorage from the other vmstorage ? This software evolution would make it possible to have high availability at a very moderate cost (a high availability SAN is very expensive, and not everyone is not concerned by the cloud).
> I think a "vmrebuild" binary which knows all the storage pools, which connects to them and searches for the data which lacks a duplicate to recreate them on a new node, which will suffice to insert into the pool when it is recreated.

It seems to me that this is a bad substitute for backups For many reasons, for instance:

- Such "recovery" looks extremely resource-intensive, especially searching for unreplicated data across all storages will load them very heavily. It may cause other storages to crash.
- If there is a failure in two or more storages (or in all the storages as a result of a faulty update), without backups, some of the data will be lost forever

But perhaps colleagues think differently: @valyala @hagen1778 @f41gh7 wdyt? 

> In other way, I read that it is recommended to add vmstorage nodes, rather than having nodes with a large volume of data. If I put several vmstorage on virtual machines, hosted on two hypervisors only (or several vmstorage on the same physical server) how can I be sure that the replicas will be between two physical servers? 

In k8s you can do it with [anti-affinity](https://docs.victoriametrics.com/operator/high-availability.html#vmcluster), if you have labels with physical server on your nodes.

> Perhaps add in "vminsert" the notion of storage group or each group must be understood as being independent (ex: two physical servers, two datacenters, ...). I imagine something like below, based on facultative prefix of each vmstorage address:
> ...
> It may also be interesting to set the replica groups so that all the data from vmstarage A is replicated to vmstorage B, and only vmstorage B. In this way, the restoration of node B in the event of a failure would be a copy of data from any other node in the same replication group group.

We already have similar feature request about [storage groups](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3531).

**Comment by jiekun** [comment]
Please track with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3531
