### ISSUE TITLE
[VMStorage] Warn log vmstorage nodes were unavailable during the query "dial tcp4 vmstorage i/o timeout" 

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#4741]
### Is your question request related to a specific component?

Related component:
VMStorage & VMSelect component
Cluster Infor:
VictoriaMetrics Cluster Version (v1.87.6)
Replicas of All components are 3 
And data ReplicaFactor = 2
Environment: Kubernetes: v1.15.1

### Describe the question in detail

Hi everyone!
When I operating my VM Cluster, I noticed that the VMSelect component appear warning log:
```
{"ts":"2023-07-29T14:36:50.039Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/netstorage/netstorage.go:1761","msg":"1 out of 3 vmstorage nodes were unavailable during the query; a sample error: cannot perform search on vmstorage vm-60d-victoria-metrics-cluster-vmstorage-0.vm-60d-victoria-metrics-cluster-vmstorage.backend.svc.cluster.local:8401: cannot obtain connection from a pool: cannot dial vm-60d-victoria-metrics-cluster-vmstorage-0.vm-60d-victoria-metrics-cluster-vmstorage.backend.svc.cluster.local:8401: dial tcp4: lookup vm-60d-victoria-metrics-cluster-vmstorage-0.vm-60d-victoria-metrics-cluster-vmstorage.backend.svc.cluster.local: i/o timeout"}

```
I tried to explore monitoring metrics exposed from VM and thought that this warning maybe happened in the merge process. 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/1e4abcdb-2a63-4b37-aa99-f2a76ec020ea)

When VMStorage entered this process, I think the process slowdown the VMStorage and make it slow in response query from VMSelect and VMInsert.
Are there some configurations that help to improve performance in the merge process or something that increase the timeout from the VM's components?

Feel free to ask me for more information! 
Thanks for your time reading my question!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
>Are there some configurations that help to improve performance in the merge process or something that increase the timeout from the VM's components?

You can set `-vmstorageDialTimeout` for [vmselect](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md?plain=1#L995) to increase the timeout for establishing RPC connections from vmselect to vmstorage (default 5s).
Is "vmstorage vm-60d-victoria-metrics-cluster-vmstorage-0" the only one became available or all three of them will?
Can you query `vm_tcpdialer_errors_total`, see if the `addr` always be storage-0, maybe there is some network issue between vmselect and that vmstorage.

**Comment by tantm3** [comment]
Hi @Haleygo,

Thanks for your response!
Here is the image that shows `vm_tcpdialer_errors_total` metrics value (sorry for the hidden information):

![tcp-error-debug](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/47195326-1884-4078-8d6b-386f59d45763)

> Is "vmstorage vm-60d-victoria-metrics-cluster-vmstorage-0" the only one became available or all three of them will?
I saw that it's happened in all vmstorage instances.
I tried to find something from exposed VM metrics, but I can only see some points here:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/3631167c-0477-4f6e-9276-f42da2696f22)

**Comment by tantm3** [comment]
Hi @Haleygo!

Thanks for your suggestion!
I increased the `-vmstorageDialTimeout` configuration to `10s` and then the timeout log disappeared.
The slow query is related to this problem.
I have some slow queries that take more than 5 seconds (exceed 5s vmstorageDialTimeout) query time, so these slow queries cause VMStorage timeout.
