### ISSUE TITLE
How does remote_read work ?

### ISSUE THREAD

**Issue by hasanawad94** [VictoriaMetrics/VictoriaMetrics#4748]
### Is your question request related to a specific component?

VictoriaMetrics cluster version

### Describe the question in detail

How does the remote_read work in high level?
I plan to have a Prometheus setup and a remote_write and remote_read configuration to VictoriaMetrics cluster version
In case of querying Prometheus for a metric will Prometheus first lookup in memory then local storage and then remote_read?
Apologies if this question is more on the client side of VictoriaMertrics.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @hasanawad94.

VictoriaMetrics doesn't provide prometheus remote_read protocol.

There are the supported APIs:
- https://docs.victoriametrics.com/url-examples.html
- https://docs.victoriametrics.com/#prometheus-querying-api-usage
- https://docs.victoriametrics.com/#how-to-export-time-series

**Comment by hasanawad94** [comment]
@Amper So one has to query VictoriaMetrics directly and not through Prometheus with remote_read ?
Is there no other way to query Prometheus and if the data isn't in memory or localstorage then go to VictoriaMetrics?

**Comment by Amper** [comment]
@hasanawad94 Unfortunately, the only way I can suggest is to query the data directly through VictoriaMetrics.

[Here's a description](https://docs.victoriametrics.com/FAQ.html#why-doesnt-victoriametrics-support-the-prometheus-remote-read-api) of why we made that decision.

**Comment by hasanawad94** [comment]
@Amper Much appreciated for the response and sharing.
