### ISSUE TITLE
VictoriaLogs v0.3.0 doesn't support data injection with Logstash as the documentation describes?

### ISSUE THREAD

**Issue by deng47** [VictoriaMetrics/VictoriaMetrics#4750]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

I tried injecting syslog into VictoriaLogs v0.3.0 with logstash(both 7.16.2 and 8.8.1), but VictoriaLogs output "unsupported path requested" errors.

VictoriaLogs version:
```
~ $ /victoria-logs-prod --version
victoria-logs-20230721-040232-tags-v0.3.0-victorialogs-0-gda0caa1d34
```
VictoriaLogs error message:
```
{"ts":"2023-07-30T23:00:32.135Z","level":"warn","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:348","msg":"remoteAddr: \"10.42.5.30:40534\"; requestURI: /insert/elasticsearch/logstash?_time_field=@timestamp&_stream_fields=cluster,data_type,hostname,program&_msg_field=message; unsupported path requested: \"/insert/elasticsearch/logstash\""}
```
Logstash error message:
```
[2023-07-30T23:00:48,390][ERROR][logstash.outputs.elasticsearch][my-system_syslog-pipeline][feef33ed7554e4f4def635b1f596ddc93c9f3a249c897d07a582e63238d2ce3c] Elasticsearch setup did not complete normally, please review previously logged errors {:message=>"Got response code '400' contacting Elasticsearch at URL 'http://my-system-vl-victoria-logs-single-server.my-system-vl.svc:9428/insert/elasticsearch/logstash?_time_field=@timestamp&_stream_fields=cluster,data_type,hostname,program&_msg_field=message'", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError}
```
Below is what logs look like with debug set to 1 in VictoriaLogs
```
{"ts":"2023-07-30T22:03:35.865Z","level":"info","caller":"VictoriaMetrics/app/vlinsert/insertutils/common_params.go:80","msg":"remoteAddr=\"10.42.7.121:47580\"; requestURI=/insert/elasticsearch/_bulk?_time_field=@timestamp&debug=1&_stream_fields=cluster,data_type,hostname,program&_msg_field=message; ignoring log entry because of `debug` query arg: {\"_msg\":\"some syslog message\",\"@version\":\"1\",\"_stream\":\"{cluster=\\\"my-system\\\",data_type=\\\"syslog\\\",hostname=\\\"hostname123\\\",program=\\\"sudo\\\"}\",\"_time\":\"2023-07-30T22:03:35Z\",\"cluster\":\"my-system\",\"data_type\":\"syslog\",\"facility\":\"0\",\"facility_label\":\"kernel\",\"host\":\"192.168.85.129\",\"hostname\":\"hostname123\",\"priority\":\"0\",\"program\":\"sudo\",\"severity\":\"0\",\"severity_label\":\"Emergency\",\"timestamp\":\"2023-07-30T15:03:35-07:00\"}"}
```

How I config my Logstash output
```
        elasticsearch {
          hosts => ["http://my-system-vl-victoria-logs-single-server.my-system-vl.svc:9428/insert/elasticsearch/"]
          parameters => {
            "_msg_field" => "message"
            "_time_field" => "@timestamp"
            "_stream_fields" => "cluster,data_type,hostname,program"
          }
        }
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @deng47.

> ```{"ts":"2023-07-30T23:00:32.135Z","level":"warn","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:348","msg":"remoteAddr: \"10.42.5.30:40534\"; requestURI: /insert/elasticsearch/logstash?_time_field=@timestamp&_stream_fields=cluster,data_type,hostname,program&_msg_field=message; unsupported path requested: \"/insert/elasticsearch/logstash\""}```

I believe it's some kind of problem with the elasticsearch plugin, it can, depending on various parameters, change the endpoint for writing data (in this case, he added `/logstash`). Are you sure the parameters you quoted are all the parameters you are specifying? What version of logstash are you using?

It's strange that after enabling debug you give an example with an already correct endpoint, as if you changed some parameter between the two attempts.

Have you tried running [our example (based on docker-compose)](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker/victorialogs/logstash)? Note that it uses [OpenSearch plugin](https://github.com/opensearch-project/logstash-output-opensearch) instead of elcasticsearch (see [README](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/victorialogs/logstash/README.md)).

In addition, based on the same example, I tried running an example with the following config:

```
input {
  generator {
    lines => [
      'test 1 msg',
      'test 2 msg',
      'test 3 msg'
    ]
    count => 3
  }
}

output {
  elasticsearch {
    hosts => ["http://victorialogs:9428/insert/elasticsearch/"]
    parameters => {
        "_stream_fields" => "host.name"
        "_msg_field" => "message"
        "_time_field" => "@timestamp"
    }
    custom_headers => {
        "AccountID" => "0"
        "ProjectID" => "0"
    }
  }
}
```

And I got the expected result:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/4bd3b308-4eec-46b9-b837-c52998859022)

**Comment by deng47** [comment]
I think I figured out what is wrong.
In the documentation [here](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/Logstash.html#logstash-setup) and your example posted above, you use the elasticsearch output plugin

It simply works after I switched from elasticsearch to opensearch
```
        opensearch {
          hosts => ["http://mysystem-vl-victoria-logs-single-server.mysystem-vl.svc:9428/insert/elasticsearch/"]
          parameters => {
            "_msg_field" => "message"
            "_time_field" => "@timestamp"
            "_stream_fields" => "cluster,data_type,hostname,program"
          }
        }
```

**Comment by hagen1778** [comment]
> I think I figured out what is wrong.
In the documentation [here](https://docs.victoriametrics.com/VictoriaLogs/data-ingestion/Logstash.html#logstash-setup) and your example posted above, you use the elasticsearch output plugin

It simply works after I switched from elasticsearch to opensearch

The issue with elasticsearch output plugin was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6742 and will be available in the next release of victorialogs.

**Comment by valyala** [comment]
FYI, VictoriaLogs should accept data from Logstash out of the box starting from [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).
