### ISSUE TITLE
Index merge lasts close to 10 minutes on other vmstorages, and lots of error about broken pipe when one vmstorage goes off

### ISSUE THREAD

**Issue by andyli029** [VictoriaMetrics/VictoriaMetrics#4757]
### Describe the bug

When one vmstorage goes off,  Index merge lasts close to 10 minutes on other vmstorages, and lots of error about broken pipe .
`
info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (12 parts, 1830093 items, 8013 blocks, 73888640 bytes) into (1 part, 1207556 items, 6274 blocks, 49567928 bytes) in 38.828 seconds at 47133 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF793C"
`

`
error#011VictoriaMetrics/lib/vmselectapi/server.go:216#011cannot process vmselect conn 10.100.184.4:47152: cannot process vmselect request: cannot execute "search_v7": cannot send MetricBlock: cannot write data with size 3269: cannot write data in 0.002 seconds: cannot flush internal buffer to the underlying writer: write tcp4 10.100.100.5:8401->10.100.100.4:47152: write: broken pipe
`

`
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/mergeset/table.go#L96
`

https://victoriametrics.slack.com/files/U05KC4HN33K/F05K0FG0B9C/image.png

### To Reproduce

One vmstorage goes off in the cluster.

### Version

$ /usr/local/bin/vmstorage-prod--version
vmstorage-20230602-113236-tags-v1.91.2-cluster-0-ga1b6a9317

### Logs

```
Jul 26 20:46:13 local vmstorage-prod[52269]: 2023-07-26T20:46:13.719+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (9 parts, 1767174 items, 8980 blocks, 77580928 bytes) into (1 part, 1250428 items, 6862 blocks, 53954219 bytes) in 41.657 seconds at 42422 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF78D0"
Jul 26 20:46:17 local vmstorage-prod[52269]: 2023-07-26T20:46:17.823+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (12 parts, 1830093 items, 8013 blocks, 73888640 bytes) into (1 part, 1207556 items, 6274 blocks, 49567928 bytes) in 38.828 seconds at 47133 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF793C"
Jul 26 20:46:21 local vmstorage-prod[52269]: 2023-07-26T20:46:21.243+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (14 parts, 1962986 items, 7492 blocks, 74022272 bytes) into (1 part, 1308304 items, 5741 blocks, 47311390 bytes) in 30.285 seconds at 64817 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF79D9"
Jul 26 20:46:38 local vmstorage-prod[52269]: 2023-07-26T20:46:38.530+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (13 parts, 2812388 items, 12596 blocks, 117788783 bytes) into (1 part, 2025792 items, 9852 blocks, 84263801 bytes) in 57.444 seconds at 48958 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF7956"
Jul 26 20:46:55 local vmstorage-prod[52269]: 2023-07-26T20:46:55.934+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (11 parts, 2509034 items, 11269 blocks, 108526320 bytes) into (1 part, 1672320 items, 8651 blocks, 72205983 bytes) in 42.215 seconds at 59435 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF7B69"
Jul 26 20:47:10 local vmstorage-prod[52269]: 2023-07-26T20:47:10.193+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (15 parts, 3898272 items, 16670 blocks, 137694995 bytes) into (1 part, 3145914 items, 14259 blocks, 113930387 bytes) in 108.215 seconds at 36023 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF77E3"
Jul 26 20:47:30 local vmstorage-prod[52269]: 2023-07-26T20:47:30.623+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (15 parts, 4267006 items, 19843 blocks, 174709888 bytes) into (1 part, 2901159 items, 14982 blocks, 124586317 bytes) in 81.638 seconds at 52267 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF7B5C"
Jul 26 20:47:42 local vmstorage-prod[52269]: 2023-07-26T20:47:42.523+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (12 parts, 1862393 items, 8307 blocks, 84480448 bytes) into (1 part, 1354780 items, 6382 blocks, 54421524 bytes) in 46.588 seconds at 39975 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF7B98"
Jul 26 20:48:16 local vmstorage-prod[52269]: 2023-07-26T20:48:16.984+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (11 parts, 5210028 items, 23486 blocks, 209758628 bytes) into (1 part, 4089869 items, 18919 blocks, 167515064 bytes) in 124.729 seconds at 41770 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF7B67"
Jul 26 20:53:35 local vmstorage-prod[52269]: 2023-07-26T20:53:35.888+0800#011info#011VictoriaMetrics/lib/mergeset/table.go:1134#011merged (15 parts, 62022719 items, 241433 blocks, 2286199821 bytes) into (1 part, 54902456 items, 222754 blocks, 2442565263 bytes) in 385.693 seconds at 160808 items/sec to "/data/vmstorage-data/indexdb/176A5C18679F65D7/1773776E1CAF7BA8"
```

**Comment by hagen1778** [comment]
@andyli029 Could you please provide more information on your setup:
1. Ingestion rate
2. Active time series
3. Amount of vmstorage nodes and replication factor
4. Screenshots from Grafana cluster dashboard for: ResourceUsage, Troubleshooting

I'd also recommend reading https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion and https://docs.victoriametrics.com/Troubleshooting.html#cluster-instability to get the basic understanding for troubleshooting cases of slow ingestion rate and cluster stability.

**Comment by andyli029** [comment]
> @andyli029 Could you please provide more information on your setup:
> 
> 1. Ingestion rate
2.5mil/s
> 2. Active time series
34.0 Mil
> 3. Amount of vmstorage nodes and replication factor
6 vmstorage and  replicationFactor = 2
> 4. Screenshots from Grafana cluster dashboard for: ResourceUsage, Troubleshooting
Is the following information useful？
<img width="1382" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15212006/8de38049-fe02-4f07-b96a-7b19311a336b">

> I'd also recommend reading https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion and https://docs.victoriametrics.com/Troubleshooting.html#cluster-instability to get the basic understanding for troubleshooting cases of slow ingestion rate and cluster stability.
How to Troubleshoot，can you give me some advice？

**Comment by hagen1778** [comment]
> Is the following information useful？

No. I was referring to screenshots from [official Grafana dashboard](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/).

> How to Troubleshoot，can you give me some advices？

Sure! The troubleshooting docs I mentioned describe the way how components of VictoriaMetrics behave and communicate. Following the docs you should be able to install Grafana dashboard and see exactly what happens during the mentioned 10minutes. It could be that your storage nodes are just overloaded and just unable to keep up with the load when one vmstorage node goes off. The full height screenshot of the Grafana dashboard would help me to understand what's happening to the installation.

**Comment by andyli029** [comment]
> official Grafana dashboard
Dependencies:  grafana 9.2.7

But the version of my environment is lower than this version

**Comment by hagen1778** [comment]
> But the version of my environment is lower than this version

I see. You can try older revisions of the dashboard [here](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/?tab=revisions). The older is the revision, the older is the Grafana version when it was made. So you can try using older revisions for your specific env.

**Comment by hagen1778** [comment]
Closing as stale
