### ISSUE TITLE
Different behavior than Prometheus when filling a variable dropdown

### ISSUE THREAD

**Issue by CoreMoni** [VictoriaMetrics/VictoriaMetrics#4763]
### Describe the bug

Hi,
We are in the process of replacing our Prometheus with Victoria Metrics and noticed a different behavior between the both data sources, in the way how the values in a variable dropdown are filled.

My query consists of two partqueries combined with OR, and I want the results from the first partquery in the dropdown, and only results from the second partquery if they aren't already available from the first one. Prometheus does exactly this. Victoria Metrics apparently sorts the entire query result first and then selects whatever row is first after the sorting, which can also be from the second partquery, even if there's one from the first partquery as well.

### To Reproduce

Here is an example query that returns two results, with the same value for label _value and different values for label _text:

label_join(label_join(vector(1),"_text", "Result I want", "dummy1", "dummy2") or label_join(vector(1),"_text", "Result I don't want", "dummy1", "dummy2"),"_value", "Value", "dummy1", "dummy2")

The query returns the same two rows (e.g. in Explorer) when using a Prometheus as datasource and when using Victoria Metrics. However, when I use it in a Grafana dashboard to fill a variable dropdown, depending on the selected datasource, different entries are chosen for the dropdown list.

This is an example dashboard:
[VariableDropdownQuery.json.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12237248/VariableDropdownQuery.json.txt)

### Version

We are currently using version 1.91.2 of Victoria Metrics.
Grafana is on version v9.5.6

### Screenshots

Prometheus uses the result from the first partquery:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/be9808d0-2110-42f4-b4fd-d26f7f4ac0b8)

Victoria Metrics orders all results alphabetically and then selects the first one, which is here the result from the second partquery:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/2e1b995d-645a-4367-84f9-540bb04e333f)

### Additional information

Background: My real use case is a query that selects ids of available systems, and for convenience, joins some additional info to the id. This text shows up in the dropdown so that the users can easily recognise the system they are interested in, but the selected variable only contains the system id. Sometimes, for some systems, this additional info is not available. In order to have these systems in the dropdown as well, the second partquery (after the OR) selects the system ids again without the additional info. In the dropdown, I want the systems listed with info, and only where this info is missing, the systems ids alone.

**Comment by dmitryk-dk** [comment]
Hi @CoreMoni ! Sorry for delay. If you want the same behavior as Prometheus does, you can use [sort_by_label_desc](https://docs.victoriametrics.com/MetricsQL.html#sort_by_label_desc) function. The query example
```
sort_by_label_desc(label_join(label_join(vector(1),"_text", "Result I want", "dummy1", "dummy2") or label_join(vector(1),"_text", "Result I don't want", "dummy1", "dummy2"),"_value", "Value", "dummy1", "dummy2"), "_text")
```

I want to explain the behavior. You are right that Prometheus doesn't sort the result, but if we change the `or` left and right side, it will return the same value as VictoriMetrics. 
Please check the images below
<img width="1678" alt="Screenshot 2023-08-07 at 11 28 47" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/cabb0f7e-77b2-41c6-a4e8-af6746aefe48">
Change the right and left sides of the `or` query:
<img width="1680" alt="Screenshot 2023-08-07 at 11 29 30" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/3f6b61ea-d12f-4cfd-856e-30ea0d3807b6">
And you will get the same as VictoriMetrics does.
Let's check the VictoriaMetrics. It always sends you the correct result with different left and right side of the `or` query
<img width="1675" alt="Screenshot 2023-08-07 at 11 31 16" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/6638c27d-d7b6-4e02-91a9-8dadcf3b1889">

I hope this helps you to build the correct variables!

**Comment by CoreMoni** [comment]
Btw, this is still a different behavior than Prometheus. If you explicitly want to behave differently here, ok, that's fine, but you should document this then, because VM is known for behaving like Prometheus as much as it can, and if someone switches from Prometheus to VM, they'd like to know beforehand which queries won't do this.

The [definition of OR](https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators) says: 
> vector1 or vector2 results in a vector that contains all original elements (label sets + values) of vector1 and additionally all elements of vector2 which do not have matching label sets in vector1.

i.e. you should always get the left side result (vector1), and not a consistent result independent of what is left and what is right.

**Comment by valyala** [comment]
@CoreMoni , the commit 3b9605dba5a29d62bb68607e170b6db902482c78 makes sure that `q2` series are returned after `q1` series in `q1 or q2` query results. This commit will be included in the next release of VictoriaMetrics. In the mean time you can build VictoriaMetrics from this commit according to [these instructions](https://docs.victoriametrics.com/#how-to-build-from-sources) and verify whether it works as expected when executing `q1 or q2` queries.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), VictoriaMetrics should consistently return `q1` series before returning `q2` series when `q1 or q2` query is executed.

Closing this issue as done then.
