### ISSUE TITLE
Support Rule Group Time Interval

### ISSUE THREAD

**Issue by weenxin** [VictoriaMetrics/VictoriaMetrics#477]
**Is your feature request related to a problem? Please describe.**
Prometheus Rule Group can define Group Rules, Right now VMAlert does not .

see https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule_group for details.

**Describe the solution you'd like**
- Add `Interval` field to rule group struct 
- Use default evaluation Interval if user not define group Interval
- Use group interval if use has defined.

**Describe alternatives you've considered**
No, Right now

**Additional context**
Prometheus Rule Group Config
```
# The name of the time series to output to. Must be a valid metric name.
record: <string>

# The PromQL expression to evaluate. Every evaluation cycle this is
# evaluated at the current time, and the result recorded as a new set of
# time series with the metric name as given by 'record'.
expr: <string>

# Labels to add or overwrite before storing the result.
labels:
  [ <labelname>: <labelvalue> ]
```

**Comment by hagen1778** [comment]
Hi @weenxin! Groups interval support was added in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/270552fde4cd5c511b4e39d1c814d231de0bab99. Would appreciate your feedback!

**Comment by valyala** [comment]
FYI, the groups interval has been added in [vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/README.md) starting from [v1.37.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

@hagen1778 , should we close this feature request as done?

**Comment by hagen1778** [comment]
@weenxin I'm closing this issue. Feel free to reopen or file a bug if TimeInterval for groups works in unexpected way.
