### ISSUE TITLE
Why is the recommended value of -dedup.minScrapeInterval greater than or equal to the value of evaluation_interval?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#4774]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

My problem is as follows:

Why is the recommended value of -dedup.minScrapeInterval greater than or equal to the value of evaluation_interval?

If the value of -dedup.minScrapeInterval is greater than the value of evaluation_interval, then the precision of reocrd cannot be greater than the value of -dedup.minScrapeInterval.

As follows: If the value of -dedup.minScrapeInterval is 60s and the value of evaluation_interval is 30s, then reocrd will lose half of the data.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
>-dedup.minScrapeInterval greater than or equal to the value of evaluation_interval
To me, that's means I can set `dedup.minScrapeInterval` with equal or greater value, but definitely not less.

> If the value of -dedup.minScrapeInterval is 60s and the value of evaluation_interval is 30s
I can only imagine that when groups have different interval like 30s for ruleA, 60s for ruleB, which is not recommended I think. But if we do, then we have to decide setting `dedup.minScrapeInterval` to 30s or 60s, 30s means duplicate ruleB data, 60s mean lossing ruleA data.

**Comment by luzejia** [comment]
> My doubt is assuming that the evaluation_interval of all my record rules is the same, then dedup.minScrapeInterval is less than evaluation_interval to ensure that data will not be repeated, and if it is greater than that, data loss will occur.

It seems to be right to keep dedup.minScrapeInterval always less than evaluation_interval

**Comment by Haleygo** [comment]
>then dedup.minScrapeInterval is less than evaluation_interval to ensure that data will not be repeated

If `dedup.minScrapeInterval` is less than evaluation_interval, there will be multiple datapoint in one interval.
For example, I have alert-0 and alert-1 instance to calculate one rule with evaluation_interval=30s, alert-0 produce datapoint at [28s,58s,88s,118s] and alert-1 produce at [29s,59s,89s,119s].
If I set `dedup.minScrapeInterval=29s` and VictoriaMetrics will leave a single [raw sample](https://docs.victoriametrics.com/keyConcepts.html#raw-samples) with the biggest [timestamp](https://en.wikipedia.org/wiki/Unix_time) for each [time series](https://docs.victoriametrics.com/keyConcepts.html#time-series) per each -dedup.minScrapeInterval discrete interval. I will get result at [29s,58s,59s,89s], datapoint at 58s and 59s is duplicate then.
<img width="1065" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/0f0ec1fe-328a-429c-be31-6704a1e6ff69">

**Comment by luzejia** [comment]
Thank you for your answer, it solved my problem

**Comment by zekker6** [comment]
@luzejia I'll close the issue as resolved. If you will have any related questions feel free to reopen.
