### ISSUE TITLE
streaming aggregation: align interval boundaries for aggregation

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4791]
### Is your feature request related to a problem? Please describe

streaming aggregation requires `interval` field to be specified. The `interval` field defines a time window for aggregation function. The time window starts when vmagent starts, and ends after `interval` value. Hence, time window for interval `1m` can start at 11:00:12 and end at 11:01:12. While this is expected behavior, it could be confusing for users who compare aggregation results with query results in Grafana. The confusion may be caused by the fact that Grafana aligns time boundaries for queries and will plot results fro 11:00:00-11:01:00 boundary.

### Describe the solution you'd like

Would be nice if streaming aggregation would align its time window boundaries as well, so results of aggregation would be much closet to Grafana visualisation. We already have the similar approach in vmalert - see `--datasource.queryTimeAlignment`.

Considerations:
1. Boundaries alignment would mean that first time window would be always <= `interval`
2. The bigger is the interval, the more inaccurate would be the first aggregated result due to the alignment.

**Comment by AndrewChubatiuk** [comment]
@hagen1778 isn't it fixed with https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ac3cf3f35724f3bcb1ba8016a5a65d4785a979c0
?

**Comment by hagen1778** [comment]
Stream aggregation aligns the time of aggregated data flush to the specified aggregation interval starting from [v1.100.0](https://docs.victoriametrics.com/changelog/#v11000).

For example, if interval is set to 1m, then the aggregated data will be flushed at the end of every minute. The alignment can be disabled by setting no_align_flush_to_interval: true option at [stream aggregation config](https://docs.victoriametrics.com/stream-aggregation/#stream-aggregation-config). See [these docs](https://docs.victoriametrics.com/stream-aggregation/#flush-time-alignment) for details.
