### ISSUE TITLE
Prometheus drop-in replacement in grafana not working correctly (last rows - NaN)

### ISSUE THREAD

**Issue by rumanzo** [VictoriaMetrics/VictoriaMetrics#48]
I try replace prometheus with victoriametrics in grafana and I observe strange behavior of the VictoriaMetrics. It is clearly visible on node_exporter dashboard in grafana.
From response from VM, the last several values are NaN, after a while these values appear. Elements that use the last value (current value) - do not work correctly. This behavior is not seen with standard prometheus.

`{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/2/api/v1/query_range?query=node_memory_MemFree_bytes%7Binstance%3D~%22testserver.local%3A9100%22%2Cjob%3D~%22test-prometheus-servers%22%7D&start=1559580404&end=1559580440&step=4&timeout=1s"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "__name__": "node_memory_MemFree_bytes",
            "instance": "testserver.local:9100",
            "job": "test-prometheus-servers"
          },
          "values": [
            [
              1559580404,
              "5702692864"
            ],
            [
              1559580408,
              "5702909952"
            ],
            [
              1559580412,
              "5702909952"
            ],
            [
              1559580416,
              "5703041024"
            ],
            [
              1559580420,
              "5703041024"
            ],
            [
              1559580424,
              "5703041024"
            ],
            [
              1559580428,
              "5703041024"
            ],
            [
              1559580432,
              "NaN"
            ],
            [
              1559580436,
              "NaN"
            ],
            [
              1559580440,
              "NaN"
            ]
          ]
        }
      ]
    }
  }
}`

![grafanascreen](https://user-images.githubusercontent.com/15186512/58818918-afaa2f00-8637-11e9-8e4f-9030d75c9fc2.png)

\# victoria-metrics -version
victoria-metrics-20190603-091324-heads-master-0-gda45a20
\# grafana-server -v
Version 5.4.2 (commit: d812109, branch: HEAD)
\# prometheus --version
prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)

**Comment by hagen1778** [comment]
Hi @rumanzo!
Could you pls also check prometheus and victoriametrics logs and add them to the issue?
Can we assume that victoriametrics is always behind prometheus for couple of minutes?

**Comment by rumanzo** [comment]
Hi! I attach prometheus and victoriametrics logs and configs and env's (args).

I made several requests to VictoriaMetrics and I have a suspicion that this behavior is due to the fact that Grafana use the browser time in query (absolute, not relative like "now"), and the time on the server is not synchronized. VictoriaMetrics gives series of NaN values if end time in request from the future. 
I check clock skew from from workstation and server, and diff ~15s, and if I curl api with &end=now - all ok, no NaN, and if I change time parameter in grafana to now-20s - all ok.
Tomorrow I synchronize the time on the server, and probably the problem will go away, but I’m not sure if this is the correct behavior.

[victoriametrics.log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3249456/victoriametrics.log)
[prometheus.log](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3249457/prometheus.log)
[prometheus.yml.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3249461/prometheus.yml.txt)
[victoriametrics.env.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3249462/victoriametrics.env.txt)
[prometheus.env.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/3249463/prometheus.env.txt)

**Comment by rumanzo** [comment]
I'm sync time on servers, and problem gone

**Comment by hagen1778** [comment]
Great! I assume delays in data are possible between writing into Prometheus and sync into remote storage, but not significant if network is stable. However, feel free to reopen if you see it causing issues.

**Comment by rumanzo** [comment]
@hagen1778 I think it's not drop-in replacement behavior. I set end time to future, and do same query to different endpoint. First query to prometheus, second to VictoriaMetrics:

[root@server-prometheus-2 ~]# curl "http://server-prometheus-3.openstacklocal:9090/api/v1/query_range?query=node_memory_MemTotal_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D%20-%20node_memory_MemFree_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D%20-%20(node_memory_Cached_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D%20%2B%20node_memory_Buffers_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D)&start=1559641004&end=1559641200&step=4&timeout=1s"
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"instance":"server-prometheus-1.openstacklocal:9100","job":"server-prometheus-servers"},"values":[[1559641004,"652955648"],[1559641008,"652881920"],[1559641012,"652816384"],[1559641016,"652828672"],[1559641020,"652804096"],[1559641024,"652840960"],[1559641028,"652693504"],[1559641032,"652664832"],[1559641036,"652767232"],[1559641040,"652627968"],[1559641044,"653107200"],[1559641048,"653082624"],[1559641052,"653025280"],[1559641056,"653107200"],[1559641060,"653180928"],[1559641064,"654270464"],[1559641068,"654020608"],[1559641072,"654123008"],[1559641076,"654036992"],[1559641080,"653852672"],[1559641084,"654077952"],[1559641088,"653643776"],[1559641092,"653103104"],[1559641096,"652001280"],[1559641100,"651722752"],[1559641104,"651792384"],[1559641108,"651509760"],[1559641112,"651321344"],[1559641116,"651169792"],[1559641120,"651014144"],[1559641124,"651014144"],[1559641128,"651014144"],[1559641132,"651014144"],[1559641136,"651014144"],[1559641140,"651014144"],[1559641144,"651014144"],[1559641148,"651014144"],[1559641152,"651014144"],[1559641156,"651014144"],[1559641160,"651014144"],[1559641164,"651014144"],[1559641168,"651014144"],[1559641172,"651014144"],[1559641176,"651014144"],[1559641180,"651014144"],[1559641184,"651014144"],[1559641188,"651014144"],[1559641192,"651014144"],[1559641196,"651014144"],[1559641200,"651014144"]]}]}}


[root@server-prometheus-2 ~]# curl "http://server-prometheus-2.openstacklocal:8428/api/v1/query_range?query=node_memory_MemTotal_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D%20-%20node_memory_MemFree_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D%20-%20(node_memory_Cached_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D%20%2B%20node_memory_Buffers_bytes%7Binstance%3D~%22server-prometheus-1.openstacklocal%3A9100%22%2Cjob%3D~%22server-prometheus-servers%22%7D)&start=1559641004&end=1559641200&step=4&timeout=1s"
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"instance":"server-prometheus-1.openstacklocal:9100","job":"server-prometheus-servers"},"values":[[1559641004,"653086720"],[1559641008,"652886016"],[1559641012,"652861440"],[1559641016,"652832768"],[1559641020,"652808192"],[1559641024,"652845056"],[1559641028,"652836864"],[1559641032,"652673024"],[1559641036,"652771328"],[1559641040,"652718080"],[1559641044,"652476416"],[1559641048,"653086720"],[1559641052,"653029376"],[1559641056,"653225984"],[1559641060,"653062144"],[1559641064,"653541376"],[1559641068,"654028800"],[1559641072,"654000128"],[1559641076,"654041088"],[1559641080,"653856768"],[1559641084,"654082048"],[1559641088,"653930496"],[1559641092,"653234176"],[1559641096,"652066816"],[1559641100,"651853824"],[1559641104,"651796480"],[1559641108,"651513856"],[1559641112,"651354112"],[1559641116,"651173888"],[1559641120,"651022336"],[1559641124,"650739712"],[1559641128,"650588160"],[1559641132,"650526720"],[1559641136,"650616832"],[1559641140,"650616832"],[1559641144,"650616832"],[1559641148,"650616832"],[1559641152,"NaN"],[1559641156,"NaN"],[1559641160,"NaN"],[1559641164,"NaN"],[1559641168,"NaN"],[1559641172,"NaN"],[1559641176,"NaN"],[1559641180,"NaN"],[1559641184,"NaN"],[1559641188,"NaN"],[1559641192,"NaN"],[1559641196,"NaN"],[1559641200,"NaN"]]}]}}


There are start, end and step parameters in the request, and the behavior looks right, but it different from prometheus. If customers(clients) have problems with time synchronization, it will affect with VictoriaMetrics, and not affect with stock prometheus. May be it's a bug, or its need configurable parameter?

**Comment by valyala** [comment]
This may be related to the fact that Prometheus fills gaps in the end of graph for 5 minutes, while VictoriaMetrics fills gaps worth only up to two scrape intervals:

```
If no sample is found (by default) 5 minutes before a sampling timestamp, no value is returned for that time series at this point in time. This effectively means that time series "disappear" from graphs at times where their latest collected sample is older than 5 minutes or after they are marked stale.
```

I'm unsure this should be fixed, since VictoriaMetrics' behavior allows detecting disappeared metric much quicker - in two scrape intervals instead of 5 minutes.
