### ISSUE TITLE
streaming aggregation: saves raw samples

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4804]
### Describe the bug

When using a simple config for streaming aggregation 
```
- match: 'm1_rate{metric=~"(ajax|grpc|rpc)_call"}'
  interval: 1m
  without: [instance, kubernetes_pod_name]
  outputs: [sum_samples]
```
In the TSDB saves both metrics: aggregated and not aggregated. Not matched metrics are dropped but both aggregated and matching source metrics are ingested

Please see the picture below.
<img width="1680" alt="Screenshot 2023-08-09 at 18 23 30" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/d028a4eb-92b3-4c9a-907f-73fedea635bf">

  

### To Reproduce

Start single VictoriaMetrics with the next command line flags
```
./victoria-metrics -search.latencyOffset=10s -search.maxUniqueTimeseries=5000000 -retentionPeriod=100y -search.maxSamplesPerSeries=5000000 -httpListenAddr=:8428 -search.maxLookback=1m
```

Start vmagent with the next command line flags
```
./vmagent  --remoteWrite.flushInterval=5s --httpListenAddr=:8429 --promscrape.config=./test.yaml --promscrape.disableKeepAlive=false --remoteWrite.url=http://127.0.0.1:8428/api/v1/write --remoteWrite.streamAggr.config=./stream.yaml
```

Where stream.yaml is a stream aggregation config:
```yaml
- match: 'm1_rate{metric=~"(ajax|grpc|rpc)_call"}'
  interval: 1m
  without: [instance, kubernetes_pod_name]
  outputs: [sum_samples]
```
Observe the result in the VMUI  

### Version

`victoria-metrics v1.92.1`
`vmagent v1.92.1`

**Comment by hagen1778** [comment]
@dmitryk-dk the bug was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/a4a1884237dfe0360397f932856c01d6a6f32098 and will be included into the next release

**Comment by valyala** [comment]
[stream aggregation](https://docs.victoriametrics.com/stream-aggregation.html) should properly leave unmatched samples by default starting from [v1.93.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
