### ISSUE TITLE
vmagent: properly handle unexpected EOF

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4817]
### Is your feature request related to a problem? Please describe

When the client closes the connection, vmagent creates a log message with `warning` severity. See the example below:
```
cannot read block of data: unexpected EOF
```
This warning message produces an alert to which the user cannot handle.

### Describe the solution you'd like

We can handle unexpected EOF errors like it was done for the vmalert component
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4146/files

This will prevent producing and firing an alert that which user cannot handle

**Comment by hagen1778** [comment]
The fix was merged here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b7d07e5acf230b271cd49cc8fb9da7f9e0c1b636 and will be available in the next release.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), `vmagent` shouldn't emit `unexpected EOF` error logs when the remote side unexpectedly closes connection. Closing this issue as done.
