### ISSUE TITLE
memory.allowedBytes flag not respected by vmstorage

### ISSUE THREAD

**Issue by matej-bellus-w** [VictoriaMetrics/VictoriaMetrics#4820]
### Describe the bug

On the memory chart, there is a period where mem hits high percentage, to fix this I decided to limit the caches with `-memory.allowedBytes 3G`, but 3G is never reached. Recently I switched to `6G` but that number is also not reached.

### To Reproduce

try to use the `-memory.allowedBytes` flag 

### Version

victoriametrics/vmstorage:v1.90.0-cluster

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/113900651/98dd1bcd-0d18-4069-bc02-6d63983ac91b)

### Used command-line flags

```
  -httpListenAddr :8452 \
  -vminsertAddr 0.0.0.0:8462 \
  -vmselectAddr 0.0.0.0:8472 \
  -retentionPeriod 31d \
  -storage.minFreeDiskSpaceBytes 1024GiB \
  -storageDataPath /vmstorage-data \
  -memory.allowedBytes 6GiB \
```

**Comment by denisgolius** [comment]
Hi @matej-bellus-w !
I think that you need to configure `-memory.allowedPercent` because it set to 60  percent by default.

```
-memory.allowedPercent float
     Allowed percent of system memory VictoriaMetrics caches may occupy. See also -memory.allowedBytes. Too low a value may increase cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from the OS page cache which will result in higher disk IO usage (default 60)
```

See also https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#resource-usage-limits

**Comment by matej-bellus-w** [comment]
Why? `-memory.allowedBytes` takes priority before `-memory.allowedPercent`

```
  -memory.allowedBytes size
     Allowed size of system memory VictoriaMetrics caches may occupy. This option overrides -memory.allowedPercent if set to a non-zero value. Too low a value may increase the cache miss rate usually resulting in higher CPU and disk IO usage. Too high a value may evict too much data from the OS page cache resulting in higher disk IO usage
     Supports the following optional suffixes for size values: KB, MB, GB, TB, KiB, MiB, GiB, TiB (default 0)
```

**Comment by hagen1778** [comment]
@matej-bellus-w `-memory.allowedBytes` or `-memory.allowedPercent` are not hard limits for process memory usage - see below:
> -memory.allowedPercent and -memory.allowedBytes limit the amounts of memory, which may be used for various internal caches at VictoriaMetrics. Note that VictoriaMetrics may use more memory, since these flags don't limit additional memory, which may be needed on a per-query basis.

from https://docs.victoriametrics.com/#resource-usage-limits

These flags also not guarantee VM will use as much mem as you set it. The specified memory limit is then shared across various caches maintained by the process. Each cachse gets its share from the specified `-memory.allowedBytes` or `-memory.allowedPercent` by setting hard cap limit on amount of entries it could contain. But that doesn't guarantee that all caches will fully utilize all the allowed memory, some caches may remain underutilized.

**Comment by matej-bellus-w** [comment]
> Each cachse gets its share from the specified -memory.allowedBytes

I think this answers the question. I can see the shares % in source.

**Comment by hagen1778** [comment]
Closing the issue as solved then.
