### ISSUE TITLE
Grafana InfluxDB datasource returns no data

### ISSUE THREAD

**Issue by readmodifywrite** [VictoriaMetrics/VictoriaMetrics#4831]
### Describe the bug

VM 1.93.0

I'm setting up an InfluxDB datasource in Grafana and pointing it to my VictoriaMetrics instance on http port 8248.

The datasource connects, however, there is apparently no data.  All of the Grafana query selections list "_internal" with no associated data.  None of my actual data is there.

I can query with the Prometheus data source (though it has problems as well, another issue to follow).  The data is physically in the database, but the Influx queries don't seem to reach it.

The reason I am trying to use the Influx data source is because the Prometheus data source is not returning the full data set.  I'll post that as a separate issue.  I don't actually care which data source is used, but I do need all of the data to be queryable via Grafana.

I don't know if this is actually a bug, or that I am just doing something wrong.  I have not been able to find any actual documentation on how to configure VM with the Influx data source.

### To Reproduce

Try to use Grafana's InfluxDB data source with VM.

### Version

1.93.0

### Logs

There is no log output with the Influx queries.  They just return no data.

**Comment by johnseekins** [comment]
I'm pretty sure VictoriaMetrics expects to be a _Prometheus_ data source, not an InfluxDB one. VictoriaMetrics supports MetricsQL (a superset of PromQL) for querying, so I would be pretty surprised if InfluxDB queries worked at all.

**Comment by hagen1778** [comment]
> I don't know if this is actually a bug, or that I am just doing something wrong. I have not been able to find any actual documentation on how to configure VM with the Influx data source.

@readmodifywrite as @johnseekins pointed out, VM doesn't support Influx query language - see https://docs.victoriametrics.com/guides/migrate-from-influx.html#query-data

You can ingest data in Influx line protocol, but for querying it back you should expect to use [Prometheus](https://grafana.com/docs/grafana/latest/datasources/prometheus/) or [VictoriaMetrics](https://github.com/VictoriaMetrics/grafana-datasource) datasource.

**Comment by readmodifywrite** [comment]
OK thanks!  That's about what I was expecting, but was a bit confused.  The docs (to me) make it sound like VM can perform the functions of Prometheus AND InfluxDB, rather than just being able to ingest data from either format.

So given my other ticket, it sounds like VM is really just a Prometheus replacement, and suitable to replace InfluxDB *if* you were using InfluxDB to do what Prometheus does.

The two really don't work the same, so it's a bit disappointing to get one and not the other, but at least I'm clear on how it is supposed to work!
