### ISSUE TITLE
vmbackup check storage path prefix mistake

### ISSUE THREAD

**Issue by flashmouse** [VictoriaMetrics/VictoriaMetrics#4837]
### Describe the bug

vmbackup would check local filesystem prefix, but the predict ``hasFilepathPrefix("fs:///data1", "/data") `` is true.

### To Reproduce

just run 
``./vmbackup-prod -storageDataPath=/data -snapshot.createURL=http://127.0.0.1:8482/snapshot/create -dst=fs:///data1``

### Version

1.83.1

**Comment by valyala** [comment]
The bugfix has been included in [v1.93.1](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.

**Comment by valyala** [comment]
FYI, the bugfix has been backported to [v1.87.8 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.8).
