### ISSUE TITLE
VictoriaMetrics eats burst credits on AWS EFS volumes pretty fast

### ISSUE THREAD

**Issue by esergion** [VictoriaMetrics/VictoriaMetrics#4842]
### Is your question request related to a specific component?

VictoriaMetrics Single Node setup on AWS EKS, collects data from Prometheus server by `remote_write`

### Describe the question in detail

Hi guys, awesome project, the charts loading speed we got after installing VictoriaMetrics is wonderful!

Although, there is an issue with AWS EFS volume (Performance mode: "General Purpose", Throughput mode: "Bursting", 3 Access points in 3 different subnets) - VictoriaMetrics eats burst credits pretty fast, and I don't really understand why.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3315244/95da9056-c2c0-4e3e-a242-d4a49172d29c)
These are filesystem-metrics for VictoriaMetrics from AWS console.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3315244/2717e924-9ee0-4301-b622-7af3a9a1c920)
And here are for Prometheus server filesystem.

As you can see the Burst Credits balance for VM-volume is melting down pretty fast right since the beginning, even though the "Data write IO bytes" and "Data read IO bytes" are much lower than on Prometheus server. And "Percent IO limit" is in opposite are 10x times higher. It seems like VM is writing (and also constantly reading from FS, is this supposed to be?) to FS with small chunks of data, and Prometheus uses bigger chunks instead.

So my main question is - Is there are configuration params that I've missed, to decrease the IO usage, probably by increasing the Flush Chunk size or something like that, to prevent EFS to slowing down after exhausting all Burst credits?

Also, as you can see on "Data read IO bytes" charts, there are lot of read-events coming from VM. And Prometheus, on the contrary, uses reading infrequently and in large portions of data. Is this some internal service process on VM that is constantly reading the indices from the volume? Can we somehow decrease it's frequency if it so?

**Comment by esergion** [comment]
@hagen1778 Thanks for the answer Roman! Got it now, will try to increase inmemoryDataFlushInterval and check how it performs on bursting EFS volumes

**Comment by esergion** [comment]
Works perfectly, thanks once again!
 I've set
```
  env:
    - name: VM_inmemoryDataFlushInterval
      value: 60s
```
And now Burst credits are getting up!
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3315244/30c4da45-4951-49ad-97e9-99c7a5c869e0)

**Comment by jlimai** [comment]
@esergion Hi Sergey, I know this issue has closed, but i would like to know from your experience regarding using EFS storage with Victoriametrics.  Have you find any issue so far using EFS beside this bursting issue ?

**Comment by esergion** [comment]
@jlimai Hey Joseph, everything is working perfectly so far, with no issues at all. Overall performance could certainly be better on EBS volumes, but even with EFS, Victoria is showing significantly better performance than Prometheus which we used before.

**Comment by jlimai** [comment]
@esergion Thanks for the input.  That really helps alot.
