### ISSUE TITLE
`scrape_timeout` not honored in stream parsing mode

### ISSUE THREAD

**Issue by apolak** [VictoriaMetrics/VictoriaMetrics#4847]
### Describe the bug

When stream parsing mode is on and the scrape target is down, the scrape duration exceeds the scrape timeout. The effective scrape timeout seems to be `max(1m-scrape_interval, 30s)`, e.g. when `scrape_interval` is 1m, 30s, 20s, 10s, and 5s, scrape duration is 30s, 30s, 40s, 50s and 55s, respectively.

### To Reproduce

I was only able to reproduce this issue in Kubernetes. Steps below require `kind` and `kubectl` (https://kubernetes.io/docs/tasks/tools/).

1. Create a local Kubernetes cluster:

    ```shell
    kind create cluster
    ```

2. Run `node_exporter` in a Pod:

    ```shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.6.1
          ports:        
            - containerPort: 9100
      restartPolicy: Never
    EOF
    ```

4. Monitor the Pod until it gets an IP:

    ```shell
    watch 'kubectl get pod node-exporter -o wide'
    ```

5. Prepare the `promscrape` config file and run VictoriaMetrics in a Pod. Note that it's important to use an IP address here to avoid DNS name resolution failures later, which would cause the scraping job to fail fast:

    ```shell
    target_ip=$(kubectl get pod node-exporter --template '{{.status.podIP}}')
    
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: promscrape-config
    data:
      prometheus.yml: |
        scrape_configs:
          - job_name: node-exporter
            honor_timestamps: false
            scrape_interval: 10s
            scrape_timeout: 9s
            static_configs:
              - targets:
                  - $target_ip:9100
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: victoria-metrics
      labels:
        app: victoria-metrics
    spec:
      containers:
        - name: victoria-metrics
          image: victoriametrics/victoria-metrics:v1.93.0
          ports:        
            - containerPort: 8428
          args:
            - --promscrape.config=/etc/prometheus/prometheus.yml
            - --promscrape.streamParse=true
            - --search.disableCache=true
            - --search.latencyOffset=5s
          volumeMounts:
          - name: promscrape-config
            mountPath: /etc/prometheus
      volumes:
        - name: promscrape-config
          configMap:
            name: promscrape-config
      restartPolicy: Never
    EOF
    ```

6. Delete the Pod running `node_exporter`:

    ```shell
    kubectl delete pod node-exporter
    ```

7. In another terminal, port-forward the port 8428 of the Pod running VictoriaMetrics:

    ```shell
    kubectl port-forward victoria-metrics 8428:8428
    ```

8. Open VMUI at http://localhost:8428/vmui and monitor the `scrape_duration_seconds` metric.

9. When done, delete the local Kubernetes cluster:

    ```shell
    kind delete cluster
    ```

### Version

victoria-metrics-20230812-215739-tags-v1.93.0-0-g59f7d810c9 (current)
victoria-metrics-20210920-122706-tags-v1.66.0-0-g76811c2f6 (first observed)

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4267996/79cf8104-5f3e-431d-b68c-cf32f1b35ec8)

### Used command-line flags

--promscrape.config=/etc/prometheus/prometheus.yml
--promscrape.streamParse=true
--search.disableCache=true
--search.latencyOffset=5s

### Additional information

- This issue is not observed in v1.65.0 or earlier.
- The given steps to reproduce, including the command line flags used to run VictoriaMetrics, are meant to imitate basic setup including PMM (https://docs.percona.com/percona-monitoring-and-management/). To reproduce this issue with PMM, use this setup:

    ```shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: pmm-server
      labels:
        app: pmm-server
    spec:
      containers:
        - name: pmm-server
          image: percona/pmm-server:2.38.1
          ports:        
            - containerPort: 443
          env:
            - name: METRICS_RESOLUTION_HR
              value: 10s
            - name: METRICS_RESOLUTION_MR
              value: 30s
            - name: METRICS_RESOLUTION_LR
              value: 60s
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 443
              path: /v1/readyz
      restartPolicy: OnFailure
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: pmm-server
    spec:
      selector:
        app: pmm-server
      ports:
        - name: https
          protocol: TCP
          port: 443
          targetPort: 443
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: pmm-client
    spec:
      containers:
        - name: pmm-client
          image: percona/pmm-client:2.38.1
          ports:        
            - containerPort: 9100
          env:
            - name: PMM_AGENT_SERVER_ADDRESS
              value: pmm-server:443
            - name: PMM_AGENT_SERVER_USERNAME
              value: admin
            - name: PMM_AGENT_SERVER_PASSWORD
              value: admin
            - name: PMM_AGENT_SERVER_INSECURE_TLS
              value: '1'
            - name: PMM_AGENT_SETUP
              value: '1'
            - name: PMM_AGENT_SETUP_FORCE
              value: '1'
            - name: PMM_AGENT_SETUP_NODE_TYPE
              value: container
            - name: PMM_AGENT_SETUP_METRICS_MODE
              value: pull
            - name: PMM_AGENT_SIDECAR
              value: '1'
            - name: PMM_AGENT_CONFIG_FILE
              value: /usr/local/percona/pmm2/config/pmm-agent.yaml
      restartPolicy: OnFailure
    EOF
    ```

**Comment by zekker6** [comment]
@apolak `scrape_duration_seconds` metric is gathered differently for default and stream parsing mode.
For the default mode it only includes time required to download response body from scrape target.
For the stream parsing mode this metric includes both time taken to download(stream) response and process it. This is an intended behavior because for stream parsing mode parsing is performed for each data block.

Difference between 1.65.0 and 1.66.0 is caused by this commit: https://github.com/VictoriaMetrics/VictoriaMetrics/commit/728c4c3841bc791040a97a84fd2e20686a78b433
Before 1.66.0 timeout value for stream parsing was equal to timeout for reading data in the default mode. This was not intended since in stream parsing this timeout would also cover response processing.
In order to address this timeout value has been increased and timeout for receiving first response byte was added.

**Comment by apolak** [comment]
Then what is the expected behavior in stream parsing mode when `scrape_timeout` is 9s and the scrape target is down? I would expect that after not being able to receive any data for 9s, the job will time out like it did before v1.66.0.

This is not only about how the `scrape_duration_seconds` metric value is calculated. Take a look at this exported `up` metric data:

```shell
# Executed on Wed Aug 16 15:00:06 CEST 2023
curl http://localhost:8428/api/v1/export -d 'match[]=up' -d 'start=5m' 2> /dev/null
```

Result, formatted and annotated:

```json
{
    "metric": {
        "__name__": "up",
        "job": "node-exporter",
        "instance": "10.244.0.41:9100"
    },
    "values": [
        1,  // 1.  14:55:16 - ok, samples show up in 10s intervals
        1,  // 2.  14:55:26
        1,  // 3.  14:55:36
        1,  // 4.  14:55:46
        1,  // 5.  14:55:56
        1,  // 6.  14:56:06
        1,  // 7.  14:56:16
        1,  // 8.  14:56:26
        1,  // 9.  14:56:36
        1,  // 10. 14:56:46
        1,  // 11. 14:56:56
        0,  // 12. 14:57:06 - 1st failed scrape
        0,  // 13. 14:57:16
        0,  // 14. 14:57:46 - starting from here, samples show up in 30s intervals
        0,  // 15. 14:58:16
        0,  // 16. 14:58:46
        0   // 17. 14:59:16 - the latest sample available at command execution time is 50s old
    ],
    "timestamps": [
        1692190516123,
        1692190526123,
        1692190536123,
        1692190546123,
        1692190556123,
        1692190566123,
        1692190576123,
        1692190586123,
        1692190596123,
        1692190606123,
        1692190616123,
        1692190626123,
        1692190636123,
        1692190666123,
        1692190696124,
        1692190726123,
        1692190756124 
    ]
}
```

Note that:

1. Soon after the 1st failed scrape, interval between scrapes drops from 10s to 30s.
2. The latest sample available at command execution time is between 50s and 79s old.

This is problematic from availability monitoring point of view. In my scenario, for legacy reasons, `vmalert` is run with `--datasource.queryStep` below 30s. We monitor the `up` metric, but when nodes become unavailable, no alerts are fired because no results are returned from queries.

**Comment by apolak** [comment]
I believe that the two timeouts that you mentioned are:
1. `Transport.ResponseHeaderTimeout` - Time to read first response byte. This is set to `scrape_timeout`.
2. `Client.Timeout` - Time from opening a TCP connection before sending the first request byte to closing it after reading the last response byte. In stream parsing mode this includes response processing time. This is set to 30 times the `scrape_timeout`.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1d7eaf0f5bd2431b47882b200d9e9a7e4c5040d3/lib/promscrape/client.go#L140-L162

But the 30s interval between scrapes that I'm seeing is likely caused by the `Dialer.Timeout` which is fixed:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1d7eaf0f5bd2431b47882b200d9e9a7e4c5040d3/lib/promscrape/statconn.go#L37-L46

Before v1.66.0 we would never hit this timeout because the context deadline would be exceeded faster:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/1d7eaf0f5bd2431b47882b200d9e9a7e4c5040d3/lib/promscrape/client.go#L187-L190

**Comment by apolak** [comment]
@zekker6 Seems like the entire response is read into memory in stream parsing mode starting from  https://github.com/VictoriaMetrics/VictoriaMetrics/commit/74c00a87623718f9c1a8ecaeab3a6a0febc2db2f. Is there any reason to keep using a longer timeout in this case?

**Comment by zekker6** [comment]
@apolak Great catch, it seems to me like this is no longer necessary. I'll send a PR to restore timeout value.

**Comment by hagen1778** [comment]
@apolak the issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/6e8611f301a72a67a5c4032da7e54cccfa1202bb. The fix will be included to the next release.

**Comment by apolak** [comment]
@zekker6, @hagen1778 Thank you! I will confirm if this solves the problem when the release is out.

**Comment by valyala** [comment]
@apolak , you can verify whether the issue with the timeout is fixed right now, without waiting for the release. Just build `vmagent` from the commit 6e8611f301a72a67a5c4032da7e54cccfa1202bb according to [these instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether it works as expected.

**Comment by apolak** [comment]
@valyala Thank you, I managed to build and run the image from the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/6e8611f301a72a67a5c4032da7e54cccfa1202bb via `make package-victoria-metrics` (not without a bit of a hiccup due to missing https://github.com/VictoriaMetrics/VictoriaMetrics/commit/eabcfc9bcddac37725c61f25b7e0dd35fa27212e). I can confirm that it works as expected. Thanks once again!

**Comment by valyala** [comment]
@apolak , thanks for the confirmation!

FYI, `vmagent` should honor `scrape_timeout` in [stream parsing mode](https://docs.victoriametrics.com/vmagent.html#stream-parsing-mode) starting from [v1.93.2](https://docs.victoriametrics.com/CHANGELOG.html).
