### ISSUE TITLE
vmui: make the warning message more noticeable

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/VictoriaMetrics#4848]
### Is your feature request related to a problem? Please describe

The current warning message is not very noticeable, and users may not see it.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/29711459/fa1c32ad-d9ff-48e4-8115-7f67681de595)

### Describe the solution you'd like

Make the warning message similar to the error message.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/29711459/b0ddbf72-606a-4b53-aa52-4a7c732d0ab9)

### Additional information

As warning messages are intended to alert the user to potential issues or important information, it's crucial that they are easily visible and noticeable.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), error message is more visible in [vmui](https://docs.victoriametrics.com/#vmui). Closing the feature request as done.
