### ISSUE TITLE
The performance of bottomk/topk is worse than standard Prometheus

### ISSUE THREAD

**Issue by wanghaao** [VictoriaMetrics/VictoriaMetrics#4853]
### Is your question request related to a specific component?

vmSelect

### Describe the question in detail

We have done a benchmark test using [prometheus-benchmark](https://github.com/VictoriaMetrics/prometheus-benchmark) project. The scraped targets are "5000" and the biggest timeseries cardinality is 1280000.

```
PromQL:
bottomk(3, node_cpu_seconds_total) 
topk(3, node_cpu_seconds_total)
range: 10 min
step: 10s
```
The average latency of Prometheus is 31710ms, while 103643ms for VM. Why?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, can you share more information about test setup?

1) allocated resources for vmcluster components (values.yaml).
2) Allocated resources for prometheus (values.yaml).
3) query examples for measuring latency with api endpoint. E.g. `curl http://localhost:8428/api/v1/query_range -g -d 'query=bottomk(3, node_cpu_seconds_total)' -d 'start=-10m'

**Comment by wanghaao** [comment]
node: 32core / 128GB

```
vmCluster: 1 vmSelect (node) / 6 vmStorage (node) / 1 vmInsert (node)
Prometheus: single node version
```

In [prometheus-benchmark](https://github.com/VictoriaMetrics/prometheus-benchmark) project, the 5000 targets will generate 1280000 timeseries for metric ``node_cpu_seconds_total ``.

**Comment by hagen1778** [comment]
Hello @wanghaao! 

> node: 32core / 128GB

Could you please elaborate more on that? Is that 1 Prom instance with that config and 8 VM components on the another instance? Or each VM component has a dedicated 32core / 128 GB instance?
Have you checked the https://docs.victoriametrics.com/Troubleshooting.html#slow-queries guide? Could it be that vmselect is maxed out by CPU during the tests?

**Comment by jiekun** [comment]
Close due to inactivity.
