### ISSUE TITLE
vmagent kubernetes_sd `resourceVersion` filed default value set 0

### ISSUE THREAD

**Issue by yinchengjian** [VictoriaMetrics/VictoriaMetrics#4855]
### Is your feature request related to a problem? Please describe

In the current Kubernetes service discovery mechanism of vmagent, the resourceVersion field is set to an empty string by default. This can result in a situation where, if a connection is interrupted, requests are directed to etcd, bypassing the caching of the apiserver. This could potentially lead to significant pressure on the apiserver's resources.

### Describe the solution you'd like

kubernetes_sd `resourceVersion` filed default value set 0

**Comment by f41gh7** [comment]
Can you add some link for documentation, that describes difference between setting resourceVersion=0 and omitting this param?

**Comment by yinchengjian** [comment]
https://kubernetes.io/zh-cn/docs/reference/using-api/api-concepts/

**Comment by f41gh7** [comment]
Correct link https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-watch

 Indeed, it must be set to zero value. It must reduce load for etcd. Thanks for information!

**Comment by yinchengjian** [comment]
> Can you add some link for documentation, that describes difference between setting resourceVersion=0 and omitting this param?

look at this.thanks

**Comment by valyala** [comment]
@yinchengjian , thanks for filing this issue! It should be addressed in the commit 00685b627f8fb353adb0f892f99a0e4c9e071991 . Could you build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether `vmagent` reduces the load on Kubernetes during service discovery?

**Comment by Haleygo** [comment]
cc @tjucoder 
This should help your case too, can you build vmagent like instructed [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4855#issuecomment-1699261476) to see if apiserver resource get reduced?

**Comment by tjucoder** [comment]
> i

Yes, I will build and retry :)
thanks a lot.

**Comment by yinchengjian** [comment]
> @yinchengjian , thanks for filing this issue! It should be addressed in the commit [00685b6](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/00685b627f8fb353adb0f892f99a0e4c9e071991) . Could you build `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify whether `vmagent` reduces the load on Kubernetes during service discovery?
@valyala 
ok I will try. thank you.

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), `vmagent` should add `resourceVersion=0` to initial query to Kubernetes API server. This should reduce load on the API server. Closing the issue as fixed.

**Comment by valyala** [comment]
FYI, the change, which uses `resourceVersion=0` during initial query to Kubernetes API server, has been included since [v1.93.4 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.4) in the commit 3665c16444bd8fee24e04935bb003838fcd71691 .
