### ISSUE TITLE
One more fields is added, and the data cannot be queried by this fields

### ISSUE THREAD

**Issue by ly0511** [VictoriaMetrics/VictoriaMetrics#4856]
### Describe the bug

My log aggregation has a path dimension, as shown in the figure below, I can’t query the data when I use the path, only occasionally, but in most cases, I can’t query it, why is this?

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/23255488/f0c98d3b-4bdc-4a9d-8c50-183ed43d9719)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/23255488/79b12217-79ea-42ef-8852-0d6b99e1f248)

### To Reproduce

Nothing more, see bug description

### Version

version is docker.io/victoriametrics/victoria-logs:v0.2.0-victorialogs

**Comment by f41gh7** [comment]
@zekker6  PTAL

**Comment by ly0511** [comment]
The problem can be reproduced stably. The data cannot be queried after adding the path, but can be found after removing the path. Why?

**Comment by zekker6** [comment]
@ly0511 I've tried to reproduce this issue on our environments, but it doesn't seem to be the case there.

Is it possible to share the data with us to have a reproducible way to check the issue?
If it is possible, you can send it to z.bessarab@victoriametrics.com

If this is not possible, could you share your write configuration(configuration of stream fields, msg and time fields) and some artificial examples. This might help to reproduce an issue with data format similar to yours.

**Comment by ly0511** [comment]
@zekker6 
I use vector to collect logs, and add path as the log label to query. The configuration is as follows:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/23255488/3e1659e0-a9ab-4a6f-a623-7c0da2ddfaca)

Vector is programmed into my docker test environment. After the environment runs, it will be cleaned up and the docker container will be stopped. Only when the vector is running will the log be uploaded to Victorialogs, which is mainly used for log collection during CICD

My Victorialogs query statement is to splice the _stream_fields I added into url for query. Except for the path field, other fields are valid

The path query field does not take effect. It is a few hours after the environment has finished running. I don’t know why the query is fine when the environment is first running. After a while, it cannot be queried.

All query fields are as follows：
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/23255488/1917ed39-a854-46e9-8702-9a5640643787)

**Comment by XLONG96** [comment]
Hi, I submitted the PR #5295 for this issue. You can fetch the patch and try if it resolves the problem.

**Comment by valyala** [comment]
The bug should be resolved in the commit cef7a39ba38c55f02b408bc548f3cd71efddba66 . This commit will be included in the next release. In the mean time it is possible to check the bugfix by running VictoriaLogs built from this commit according to [these instructions](https://docs.victoriametrics.com/VictoriaLogs/QuickStart.html#building-from-source-code).
