### ISSUE TITLE
AD: I write a long article about vm tsdb internal.If it is useful, who can translate a English version?

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#4867]
### Is your question request related to a specific component?

I read vm code for about half years, and I write a long article to analyse vm storage internal at Feb 2022.
Now I share this article at: https://github.com/ahfuzhang/victoria-metrics-1.72.0/blob/master/VictoriaMetrics%E5%AD%98%E5%82%A8%E5%BC%95%E6%93%8E%E5%88%86%E6%9E%90.pdf.

Sorry, I am not good at English. If this article can help other people, I might try to translate to English.
And sorry to send a ad here, I am a huge fan of vm anyway.

### Describe the question in detail

N/A

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Looks good! I can't say I understood everything (don't have translator for pdfs), but it looks very impressive to me. Would you mind opening a PR to add the article to https://docs.victoriametrics.com/Articles.html#third-party-articles-and-slides-about-victoriametrics ?

**Comment by Haleygo** [comment]
@ahfuzhang Maybe I can help, you can contact me on slack or through email if you like)

**Comment by jiekun** [comment]
Close due to inactivity. Thank you for your great article @ahfuzhang .
