### ISSUE TITLE
vmrestore should have flag to sync from backup not replace it

### ISSUE THREAD

**Issue by freeseacher** [VictoriaMetrics/VictoriaMetrics#487]
**Is your feature request related to a problem? Please describe.**
vmrestore took backup from external source and updates current datadir. Restore typically took lots of time. While testing backup we found a problem that requires machine reboot.

**Describe the solution you'd like**
Flag that will continue downloading after reboot

**Describe alternatives you've considered**
`gcloud sync` to local fs and then vmrestore but it requeres double space usage and huge amount of iops

**Comment by valyala** [comment]
Note that `vmrestore` should continue downloading the backup from the interruption point after reboot. I.e. it shouldn't re-download already downloaded parts at `-storageDataPath` directory. If this doesn't work as expected, then this must be fixed.

**Comment by valyala** [comment]
It looks like `vmrestore` drops partially downloaded parts and downloads them from scratch on restart. This behaviour isn't optimal for multi-TB parts - `vmrestore` should download only missing blocks for partially downloaded parts after restart.

**Comment by valyala** [comment]
@freeseacher , could you try building `vmrestore` from the commit 27f7cca7ff9e9ddf14d1839587f11427714e6184 and verify that it doesn't re-download big files at `-storageDataPath` on restarts?

**Comment by valyala** [comment]
FYI, the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/27f7cca7ff9e9ddf14d1839587f11427714e6184 has been included in [v1.35.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release.

Closing the issue. @freeseacher , feel free re-opening it if you encounter issues with new behaviour on incomplete files' downloading after `vmrestore` restart.

**Comment by valyala** [comment]
It has been appeared that `vmrestore` could delete partially downloaded file on the next run after the interruption. This may be sub-optimal for big files (for example, when restoring 1000GB file). This should be fixed starting from [v1.70.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Now only the last partially downloaded part of the file will be re-downloaded after `vmrestore` restart with the same set of command-line options. The maximum part size, which may be re-downloaded, is 1GB.
