### ISSUE TITLE
vmauth: a request to the `/-/reload/?authKey=KEY` returns list of IPs

### ISSUE THREAD

**Issue by arseny-zinchenko** [VictoriaMetrics/VictoriaMetrics#4878]
### Describe the bug

I request to the `/-/reload/` endpoint with a Basic authentification and `authKey` returns list of IPs:

```
$ curl --user vmsvc:vmtest https://vmauth.dev.example.co/-/reload/?authKey=tttt
remoteAddr: "10.0.2.101:34382, X-Forwarded-For: 217.147.165.253, 10.0.0.74, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.101, 10.0.2.1
...
URI: /-/reload/?authKey=tttt; cannot handle more than 300 concurrent requests from user vmsvc
```

### To Reproduce

Deploy VMAuth from the `victoria-metrics-auth` Helm chart `v ~0.3.3`

Configure a `users` section with the following config:

```
    - username: vmsvc
      password: vmtest
      url_map:
      - src_paths:
        - /-/reload.*
        - /flags.*
        - /metrics.*
        - /debug/pprof.*
        url_prefix: http://atlas-victoriametrics-victoria-metrics-auth.dev-monitoring-ns.svc:8427
```

(the "`.*`" is used because of the [another](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4868) issue)

_**UPD**: also reproduced with `/-/reload/` in the `src_paths`_

Add `reloadAuthKey` to the values:

```
  extraArgs:
    reloadAuthKey: tttt
```

Make q request `curl --user vmsvc:vmtest https://vmauth.dev.example.co/-/reload/?authKey=tttt`

Without adding config to the `users` block, and requesting just `curl https://vmauth.dev.example.co/-/reload/?authKey=tttt` VMAuth returns "**missing `Authorization` request header**" error.

It's unclear from the [docs](https://docs.victoriametrics.com/vmauth.html#advanced-usage), what's the proper way to set the key, as docs only mention "_"It must be passed as authKey=..."_".

### Version

`image: victoriametrics/vmauth:v1.93.0`

### Screenshots

![Screenshot_20230823_161733(1)](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/132904972/7c968092-2c2f-4b85-854c-8cc2ff68c28e)

**Comment by hagen1778** [comment]
> I request to the /-/reload/ endpoint with a Basic authentification and authKey returns list of IPs:

It looks like a loop. Does ` url_prefix: http://atlas-victoriametrics-victoria-metrics-auth.dev-monitoring-ns.svc:8427` and `https://vmauth.dev.example.co/` point to the same service?

**Comment by hagen1778** [comment]
Closing as answered
