### ISSUE TITLE
vmauth: incorrect message when user tries to call `/-/reload/` path

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#4880]
### Describe the bug

When the user sets `--reloadAuthKey` flag and tries to curl the wrong route

```bash
curl http://localhost:8427/-/reload/?authKey=tttt
```
The user will get the wrong message, `Unauthorized`. But the message should be about the incorrect path. 

### To Reproduce

Run 
```bash
 ./vmauth --auth.config=auth.yml --reloadAuthKey=tttt
```

Run 
```bash
curl https://localhost:8427/-/reload/?authKey=tttt
```

### Version

vmauth v1.93.0

**Comment by hagen1778** [comment]
> The user will get the wrong message, Unauthorized. But the message should be about the incorrect path.

@dmitryk-dk could you please provide the full error message and URL you tried to hit?

**Comment by dmitryk-dk** [comment]
@hagen1778 another case 
run 
```
./vmauth --auth.config=auth.yml --reloadAuthKey=tttt
```
and after run
```
curl -H "Authorization: tttt" http://localhost:8427/-/reload/?authKey=tttt
```

you will get the next error message
<img width="863" alt="Screenshot 2023-08-24 at 15 13 50" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/990397f7-edd7-4cf5-8b9d-a8145d85035d">

**Comment by dmitryk-dk** [comment]
Close as resolved
