### ISSUE TITLE
Inconsistent value for the User-Agent header from VMAgent 

### ISSUE THREAD

**Issue by Gokul-Radhakrishnan** [VictoriaMetrics/VictoriaMetrics#4884]
### Describe the bug

By default, VMAgent sets `vm_promscrape` as value for the `User-Agent` header.

When we set the `streamParse` by passing the argument `promscrape.streamParse: "true"`, it sets `Go-http-client/1.1` as value for  the `User-Agent` header.

Since it the `User-Agent` header is different, we are not able to differentiate the calls coming from VMAgent at the application side.

### To Reproduce

Set the  `streamParse` by passing the argument `promscrape.streamParse: "true"`

### Version

`v1.77.2`

### Used command-line flags

    promscrape.maxScrapeSize: "300000000"
    promscrape.minResponseSizeForStreamParse: "16000000"
    promscrape.streamParse: "true"
    promscrape.suppressDuplicateScrapeTargetErrors: "true"
    promscrape.suppressScrapeErrors: "true"

**Comment by valyala** [comment]
`vmagent` should consistently set `User-Agent` http request header to `vm_promscrape` during targets' scraping starting from [v1.93.2](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
