### ISSUE TITLE
vmauth: enhance logic for retrying configured backends

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#4893]
### Is your feature request related to a problem? Please describe

In the current implementation, vmauth can retry network errors like host being unrechable or unresponsive. This makes scheme with 1 vmauth (as a gateway) and N vmselects (as query frontends) more robust, since even if one vmselect will become unrechable - vmauth will retry request to another vmselect.

However, there are cases where vmauth may do better and support some enhanced logic for retries. Consider the following ticket for multi-AZ installation https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4792. Ideally, we'd like to replace top-lvl nginx with vmauth, so when one AZ fails to respond (due to partial response) - vmauth will retry request to another AZ. But this won't work right now, as vmauth retries only network errors.

### Describe the solution you'd like

Would be great if vmauth had a config option where user can describe when vmauth should retry the request. For example, user may want to specify to retry a request if a specific header or status code was received. User should be able to disable such retries if needed.

### Cache request body

In order to retry a failed request, vmauth should be able to cache received request's body in the memory. Caching all requests in memory unconditionally may significantly increase resource usage on vmauth side. Especially, when proxying heavy requests, like requests from vmagents or vmctl. To avoid excessive mem usage vmauth could use a buffer of a fixed size, e.g. 1KB, for caching the body. If 1KB wasn't enough to cache the body, the request is marked as non-retryable.

### Retry logic

In order to retry a failed request, vmauth should be able to determine what is retryable. It can use an HTTP status code for this purpose. For example, retry on 503s or any other status code user will define.

But status codes aren't always enough. For example, vmselect always responds with the same status code 422 for errors. It doesn't matter if this is a missing param or request was denied as partial. So in order to solve the problem with partial response, vmauth should be able to distinguish these two errors. Ideally, vmselect could return a specific status code for partial response or a header. If it would be the header then vmauth should gain the ability to read headers to determine what is retryable.

The user should be able to disable retry logic completely.

#### Mutli-AZ setup

In this setup, similar to that described at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4792, user should be able to configure vmauth with backends from multiple AZ and instruct it to retry requests on condition of partial response. For other errors, the request should be returned to the caller as is.

#### Default setup

In this setup, vmauth is used as a balancer for vmselects. It should retry network errors, but shouldn't retry partial responses as it makes no sense. So user should be able to disable retry logic. Or the retry logic should be disabled by default.

### Config

The example of retry logic config is the following:
// TBD

cc @f41gh7 @Amper @valyala 

### Describe alternatives you've considered

Nginx with custom modules to check the response body/header/status code can be used as alternative.

**Comment by valyala** [comment]
The commit a315694dd94c35368979b37061681f5813031976 adds ability to specify `retry_status_codes` optional list when [load balancing](https://docs.victoriametrics.com/vmauth.html#load-balancing) is enabled. [vmauth](https://docs.victoriametrics.com/vmauth.html) retries requests at the remaining backends if response from backend contains one of these http response status codes. This commit will be included in the next release. In the mean time it is possible to test this functionality by building `vmauth` from this commit according to [these instructions](https://docs.victoriametrics.com/vmauth.html#how-to-build-from-sources).

**Comment by valyala** [comment]
The `retry_status_codes` functionality is available in `vmauth` starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.

**Comment by valyala** [comment]
FYI, `vmauth` will gain support for creating `hot standby` highly available setups in the next release - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4792#issuecomment-1847887887 for more details.
