### ISSUE TITLE
Does VM support sql like syntax?

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/VictoriaMetrics#49]
https://docs.influxdata.com/influxdb/v1.3/concepts/crosswalk/#influxql-and-sql

There is some features, that I need in influx, it's support little bit sql syntax, does VM support something like that or it works just over http queries at all?

**Comment by hagen1778** [comment]
Hi @denisgolius !
As query language VM supports only [PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/) and some additional [extension](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL).
Please also check [PromQL for beginners](https://medium.com/@valyala/promql-tutorial-for-beginners-9ab455142085) where you can find comparisons to sql syntax.
