### ISSUE TITLE
[vmui] Query   SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jicki** [VictoriaMetrics/VictoriaMetrics#4916]
### Describe the bug

query  record 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/c5f4ecaf-2461-46a7-8fec-1365062de614)

### To Reproduce

none

### Version

~ $ ./vmselect-prod --version
vmselect-20230824-081515-tags-v1.93.1-cluster-0-g54a67d439c

**Comment by Loori-R** [comment]
Yes, I'll take a look into it.
@jicki, would you be able to inform us which request is causing the error? It should be visible in the Network tab.

**Comment by hagen1778** [comment]
@jicki do you still observe this behavior?

**Comment by esn89** [comment]
I am seeing this right now with helm chart:  0.13.4, Victoria Metrics Single: v1.108.1

On the /vmui, which is routed via Istio's VirtualServices I am getting errors about JSON syntax:

https://imgur.com/a/d1Y4nJB

But port forwarding and then browsing /vmui over localhost is fine:
https://imgur.com/a/OJObXxN
