### ISSUE TITLE
Option to show all fields in Victorialogs query response

### ISSUE THREAD

**Issue by mr-karan** [VictoriaMetrics/VictoriaMetrics#4918]
### Is your feature request related to a problem? Please describe

Consider the following log entries insert command:

```sh
echo '{ "log": { "level": "info", "message": "hello world" }, "date": "0", "stream": "stream1" }
{ "log": { "level": "error", "message": "oh no!" }, "date": "0", "stream": "stream1" }
{ "log": { "level": "info", "message": "hello world" }, "date": "0", "stream": "stream2" }
' | curl -X POST -H 'Content-Type: application/stream+json' --data-binary @- \
  'http://localhost:9428/insert/jsonline?_stream_fields=stream&_time_field=date&_msg_field=log.message'
  ```
  
  On querying for `hello world` only the default fields are shown in response [as documented here](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#querying-specific-fields)  
 
 
```
 curl http://localhost:9428/select/logsql/query -d 'query=hello world' 
{"_msg":"hello world","_stream":"{stream=\"stream1\"}","_time":"2023-08-30T07:20:58.574021406Z"}
{"_msg":"hello world","_stream":"{stream=\"stream2\"}","_time":"2023-08-30T07:20:58.574028903Z"}
```

### Describe the solution you'd like

Would it be possible to show all fields in the response related to this log entry? For eg, if I am querying for `_stream:"stream1", I'd like to see what all fields are associated to the particular log:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/5689132/f6ea7166-c06a-499a-b0ac-f5e7e77c1b5e)

### Describe alternatives you've considered

Explicitly specifying each field like `log.level:*` is the only alternate solution. This might be a problem if the user needs to specify a lot of such ad-hoc fields. 

### Additional information

I understand that the data model in VictoriaLogs might prevent reading columns across multiple streams, but within a particular stream, is this not possible due to performance constraints?

**Comment by tschifftner** [comment]
+1 This issue is crucial for central logging

**Comment by hagen1778** [comment]
@mr-karan @tschifftner 

VictoriaLogs returns all fields by default in query results starting from [v0.6.0](https://docs.victoriametrics.com/victorialogs/changelog/#v060):

>The response by default contains all the [fields](https://docs.victoriametrics.com/victorialogs/keyconcepts/#data-model) for the selected logs. Use [fields pipe](https://docs.victoriametrics.com/victorialogs/logsql/#fields-pipe) for selecting only the needed fields.

The mentioned [doc link](https://docs.victoriametrics.com/victorialogs/logsql/#querying-specific-fields) was updated as well.

> Consider the following log entries insert command:

See the same exercise executed against [v0.28.0 VictoriaLogs](https://docs.victoriametrics.com/victorialogs/changelog/#v0280):

```
hagen@MacBook-Pro-6 ..ojects/VictoriaMetrics/VictoriaMetrics (git)-[master] % echo '{ "log": { "level": "info", "message": "hello world" }, "date": "0", "stream": "stream1" }
{ "log": { "level": "error", "message": "oh no!" }, "date": "0", "stream": "stream1" }
{ "log": { "level": "info", "message": "hello world" }, "date": "0", "stream": "stream2" }
' | curl -X POST -H 'Content-Type: application/stream+json' --data-binary @- \
  'http://localhost:9428/insert/jsonline?_stream_fields=stream&_time_field=date&_msg_field=log.message'
hagen@MacBook-Pro-6 ..ojects/VictoriaMetrics/VictoriaMetrics (git)-[master] %  curl http://localhost:9428/select/logsql/query -d 'query=hello world' 

{"_time":"2024-07-11T09:09:40.074218Z","_stream_id":"0000000000000000356bfe9e3c71128c750d94c15df6b908","_stream":"{stream=\"stream1\"}","_msg":"hello world","date":"0","stream":"stream1","log.level":"info"}
{"_time":"2024-07-11T09:09:40.074233Z","_stream_id":"0000000000000000db1269eafe0b151b8f37d371eeaad405","_stream":"{stream=\"stream2\"}","_msg":"hello world","date":"0","log.level":"info","stream":"stream2"}
```

I'm closing this FR as done. Feel free to re-open if something is missing.
