### ISSUE TITLE
vmalert: unexpected error log EOF and "read: connection reset by peer"

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#4920]
### Describe the bug

I am currently running the VictoriaMetrics Cluster in K8s env.
When I created multiple instances of VMAlert for benchmarking performance, I saw that sometimes VMAlert appears error log that does not have an error message inside that error log.
I also encountered the connection reset error log, I think this connection issue is related to a network issue from the K8s env.

### To Reproduce

Create ~100 VMAlert instances query to VictoriaMetrics cluster version.

### Version

./vmalert-prod --version
vmalert-20230518-230445-tags-v1.87.6-0-g4c1241d33
./vmstorage-prod --version
vmstorage-20230518-231341-tags-v1.87.6-cluster-0-g468cd5f7b
More configurations:
VictoriaMetrics Cluster Version.
data replica-factor = 2
data retention = 60days

### Logs

{
  "ts": "2023-08-21T00:52:47.425Z",
  "level": "error",
  "caller": "VictoriaMetrics/app/vmalert/group.go:281",
  "msg": "group \"benchmark-40\": rule \"Benchmark alarm 40 test % change values\": failed to execute: failed to execute query \"(avg(avg_over_time(benchmark_alarm_40[2m])) by (hostname) - avg(avg_over_time(benchmark_alarm_40[2m] offset 5m)) by (hostname))/(avg(avg_over_time(benchmark_alarm_40[2m] offset 5m)) by (hostname))*100 >= 0\": error getting response from http://vm-victoria-metrics-cluster-vmselect.backend:8481/select/0:40/prometheus/api/v1/query?query=%28avg%28avg_over_time%28benchmark_alarm_40%5B2m%5D%29%29+by+%28hostname%29+-+avg%28avg_over_time%28benchmark_alarm_40%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2F%28avg%28avg_over_time%28benchmark_alarm_40%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2A100+%3E%3D+0&step=60s&time=1692579120: Post \"http://vm-victoria-metrics-cluster-vmselect.backend:8481/select/0:40/prometheus/api/v1/query?query=%28avg%28avg_over_time%28benchmark_alarm_40%5B2m%5D%29%29+by+%28hostname%29+-+avg%28avg_over_time%28benchmark_alarm_40%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2F%28avg%28avg_over_time%28benchmark_alarm_40%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2A100+%3E%3D+0&step=60s&time=1692579120\": EOF"
}

{
  "ts": "2023-08-17T07:55:36.504Z",
  "level": "error",
  "caller": "VictoriaMetrics/app/vmalert/group.go:281",
  "msg": "group \"benchmark-0\": rule \"Benchmark alarm 0 test % change values\": failed to execute: failed to execute query \"(avg(avg_over_time(benchmark_alarm_0[2m])) by (hostname) - avg(avg_over_time(benchmark_alarm_0[2m] offset 5m)) by (hostname))/(avg(avg_over_time(benchmark_alarm_0[2m] offset 5m)) by (hostname))*100 >= 0\": error getting response from http://vm-victoria-metrics-cluster-vmselect.backend:8481/select/0:47/prometheus/api/v1/query?query=%28avg%28avg_over_time%28benchmark_alarm_0%5B2m%5D%29%29+by+%28hostname%29+-+avg%28avg_over_time%28benchmark_alarm_0%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2F%28avg%28avg_over_time%28benchmark_alarm_0%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2A100+%3E%3D+0&step=60s&time=1692258900: Post \"http://vm-victoria-metrics-cluster-vmselect.backend:8481/select/0:47/prometheus/api/v1/query?query=%28avg%28avg_over_time%28benchmark_alarm_0%5B2m%5D%29%29+by+%28hostname%29+-+avg%28avg_over_time%28benchmark_alarm_0%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2F%28avg%28avg_over_time%28benchmark_alarm_0%5B2m%5D+offset+5m%29%29+by+%28hostname%29%29%2A100+%3E%3D+0&step=60s&time=1692258900\": read tcp 192.168.195.191:39774->10.96.152.63:8481: read: connection reset by peer"
}

**Comment by tantm3** [comment]
Here are k8s resources that I used to create the benchmark scenario (100 pods vmalert with 100 configmaps), I think these resources are essential to create the environment for reproducing the error.
So, I have attached the resources here.
[vmalert-k8s.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12481834/vmalert-k8s.zip)

**Comment by dmitryk-dk** [comment]
Hi @tantm3 ! Can you upgrade your vmalert to the latest version? There was an improvement if EOF happens vmalert tries to retry the request. 

When you get `read: connection reset by peer` can you check the vmselect does not OOM killed? Can you show resource usage for vmselect and storage when this error happens? Other problem which can happen it when vmselect doesn't pass the redness or liveness probe.

**Comment by tantm3** [comment]
Hi @dmitryk-dk,

Thanks for your response!
> Can you upgrade your vmalert to the latest version? There was an improvement if EOF happens vmalert tries to retry the request.

Is this normal for running VMAlert's latest version with the VictoriaMetrics Cluster Version v1.87.6?

> When you get read: connection reset by peer can you check the vmselect does not OOM killed? Can you show resource usage for vmselect and storage when this error happens? Other problem which can happen it when vmselect doesn't pass the redness or liveness probe.

Here is the screenshot that shows VMSelect pods have no restart times:

![vmselect-oom](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/9e5b4add-6d6f-4e30-b4e4-109ddc215a07)

Here are the resource usage images:
![vmselect-memory](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/6656ac4f-2424-4935-9dc7-a56a604e5231)
![vmselect-cpu](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/aa457ec6-eea1-40e6-9962-59457825fb86)
![vmselect-file](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/6991fae8-5b37-445c-a40a-22540e473e8d)

**Comment by tantm3** [comment]
Oh, I will try it now and get back to you soon.
Are there any insights from the resource VMSelect and VMStorage images?

**Comment by dmitryk-dk** [comment]
> Are there any insights from the resource VMSelect and VMStorage images?
Can explain more this question?

**Comment by tantm3** [comment]
>  Can you show resource usage for vmselect and storage when this error happens? Other problem which can happen it when vmselect doesn't pass the redness or liveness probe.

I mean, did you see anything abnormal in the Grafana images that I attached above?

**Comment by tantm3** [comment]
Hi @dmitryk-dk,

The error log EOF disappeared when I upgraded the VMAlert to the latest version.
I think the enhancement is in the change log here:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/112939454/291e8a62-cee7-4d94-be4a-41c75b4f2c31)

Could you please give me the GitHub pull request of that change log?
I would like to explore more about the VMAlert retries mechanism.

**Comment by dmitryk-dk** [comment]
Hi @tantm3 ! Please take a look into this changes 
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4146

**Comment by tantm3** [comment]
Hi @dmitryk-dk,

Thanks for your information!
I think the problem is solved. I will close the issue here.
