### ISSUE TITLE
Alert rule with interval longer than time series resolution may not be triggered

### ISSUE THREAD

**Issue by lostyear** [VictoriaMetrics/VictoriaMetrics#4925]
### Is your question request related to a specific component?

vmalert, vmselect

### Describe the question in detail

I have an alert rule which is set for 0s, so it is supposed to firing when there is a point match the expression. But it did not.

this is the testing rule: 
```yaml
groups:
  - name: rule_group
    interval: 60s
    rules:
      - alert: happened
        expr: single_point>0
        for: 0s
```

and then, vmalert run a query with args:
`query=single_point%3E0&step=60s&time=1693380060`
but got result:
```json
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": []
    }
}
```

I export the data to find out why it happens:
```json
{
    "metric": {
        "__name__": "single_point",
        "ip": "10.10.10.1"
    },
    "values": [
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0
    ],
    "timestamps": [
        1693380002000,
        1693380012000,
        1693380022000,
        1693380032000,
        1693380042000,
        1693380052000,
        1693380062000,
        1693380072000,
        1693380083000
    ]
}
```

the raw samples shows than there is a value above 0 at time 1693380042000.
But it seems the query use the sample at 1693380052000 which has value 0 to execute the binary op '>', so the query got no samples return. Finally the rule not triggered to be fire.

This is a bug or it is supposed to be so?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
From the data you provided, it's expected.
>query=single_point%3E0&step=60s&time=1693380060

VMAlert did query with those parameters, and the nearest data point is 1693380052000 instead of 1693380042000, see https://docs.victoriametrics.com/keyConcepts.html#query-data for more details.
Your original data have 10s interval, so if you want the rule to be more sensitive, you can decrease the group interval.

**Comment by lostyear** [comment]
I checked again the `Instant query` concept. I miss the `raw sample` in step param.
> step - optional, the max [interval](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations) for searching for raw samples in the past when executing the query. For example, request /api/v1/query?query=up&step=1m will look for the last written raw sample for metric up on interval between now() and now()-1m. If omitted, step is set to 5m (5 minutes).

But decrease the group interval did not make sense also.
The `vmalert Troubleshooting` doc suggest to set the group interval bigger;
> Always configure group's evaluationInterval to be bigger or at least equal to [time series resolution](https://docs.victoriametrics.com/keyConcepts.html#time-series-resolution);

I run the vmalert with `queryStep=0` so that the query can look for the group interval time at first.
Because I suggest the query will look for back to step time and return the sample which can match the giving query.

**Comment by Haleygo** [comment]
>The vmalert Troubleshooting doc suggest to set the group interval bigger;

Yeah, that's true. But you got 6*resolution as group interval here, so there is a big chance that short spike will be missed by alerting rule, like above.

>I run the vmalert with queryStep=0 so that the query can look for the group interval time at first.

`step` is the max interval to search backward, and the last written raw sample will always be picked.
```
For example, request /api/v1/query?query=up&step=1m will look for the last written raw sample for metric up on interval between now() and now()-1m.
```

**Comment by Haleygo** [comment]
Hi @lostyear 
Is this still relevant to you?

**Comment by jiekun** [comment]
Close due to inactivity.
