### ISSUE TITLE
Migrate Grafana Dashboards with OpenTSDB queries to PromQL/MetricsQL queries

### ISSUE THREAD

**Issue by rajeshksv** [VictoriaMetrics/VictoriaMetrics#4927]
### Is your question request related to a specific component?

Grafana, Victoria Metrics

### Describe the question in detail

We are migrating from OpenTSDB to Victoria Metrics. We already have 100's of custom hand crafted grafana dashboards with OpenTSDB Queries. Is there any tool that migrates these dashboards to PromQL/MetricsQL dashboards so that users don't have to manually re-create new dashboards ? 

Alternatively any proxy that converts opentsdb Queries to PromQL/MetricsQL queries might also be helpful. 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
@rajeshksv Unfortunately, we haven't heard of successful implementations of such migrations tools yet.
Users who did similar migration before ended up with manually rewriting dashboards to adopt MetricsQL instead of OpenTSDB query language.

**Comment by rajeshksv** [comment]
Okay! We might end up building one. In that case, we will open source it :)

**Comment by bluesliverx** [comment]
@rajeshksv, we're about to start the exact same project here. Did you ever end up writing a tool to convert queries?

**Comment by rajeshksv** [comment]
We built it and migrated thousands of dashboards successfully. It might take a while to open source the project though (some code restructuring, cleanup etc)

**Comment by bluesliverx** [comment]
That's awesome! We are doing PoCs right now on what it would take to move, so the hope would be in the next month or so to be able to demonstrate that it can work.

**Comment by bluesliverx** [comment]
@rajeshksv, well, we got distracted with other priorities, but finally getting back here. We did build something rudimentary to get us off the ground, but the dashboards were still unusable and the only one with some serious promql language just left the company. Any help you could possibly give would be extremely appreciated! Even just the core logic of opentsdb queries to promql queries would be much appreciated. :)

**Comment by hagen1778** [comment]
Hello @bluesliverx! I have no enough knowledge of opentsdb to be helpful here. 
I can only recommend related docs and articles that could help to get on track with MetricsQL:
* https://docs.victoriametrics.com/keyConcepts.html#metricsql
* [Counters, Gauges, Histograms & Summaries](https://victoriametrics.com/blog/prometheus-monitoring-metrics-counters-gauges-histogram-summaries/)
* [Instant Queries and Range Queries Explained](https://victoriametrics.com/blog/prometheus-monitoring-instant-range-query/)
* [Functions, Subqueries, Operators, and Modifiers](https://victoriametrics.com/blog/prometheus-monitoring-function-operator-modifier/)

If you seek communtiy help - see https://docs.victoriametrics.com/victoriametrics/#community-and-contributions.
If you observe issues or inconsistencies with MetricsQL - raise a ticket on GitHub.
If you seek professional help - contact sales@victoriametrics.com.

Hope this helps!

**Comment by rajeshksv** [comment]
Sure, we will try to open source rudimentary version of the tool to unblock you. May be we can collaborate to make it modular and extensible

**Comment by bluesliverx** [comment]
That would be great, thank you!

**Comment by rajeshksv** [comment]
Sorry for the long delay. Here is the first version (Some cleanup has to be done, but released it in OSS to unblock you)

Github Repo - https://github.com/flipkart-incubator/prometheus-dashboard-porter
Design doc - https://docs.google.com/document/d/1wKSEk9cgeYAzo7vvKcnB2wUB8eBwGxEUPJ6SHVhOJNY/edit

We migrated 20k+ dashboards in Production successfully using minor variant of this script (as per for our company's data model)

This includes
* Simple Static Dashboards - Single data source (Multiple rows, panels and multiple queries per panels supported)
* Dynamic/Templated Dashboards - Single datasource and with Variable Support
* Complex dashboards -  Multiple data sources at dashboard, panel level with Variables, Transform capabilities

Hope it helps. If any concern, please raise a issue in the repo

(In a couple of days, we are aiming to do next release with Production Level guarantees of OSS version)

**Comment by bluesliverx** [comment]
@rajeshksv, thank you so much! Unfortunately, I cannot see https://github.com/flipkart-incubator/prometheus-dashboard-porter, perhaps you can give me access to read the repo (or maybe it was removed?).

**Comment by rajeshksv** [comment]
Oops some permission issue. Check now.

**Comment by bluesliverx** [comment]
Great, I can see it now, thanks!
