### ISSUE TITLE
VMalert. Validation of functions in expr.

### ISSUE THREAD

**Issue by sinitsa1740** [VictoriaMetrics/VictoriaMetrics#4933]
### Is your feature request related to a problem? Please describe

I would like to use `./vmalert -rule=./*.yml -dryRun ` to check my alert rules. But in this way, the functions of MetricsQL expressions are not checked, as in **promtool** for PromQL functions.
For example, I can write in `expr: sdvdfbdb(foo_count)` - and a rule with this expression will be accepted by `vmalert -dryRun`, but **promtool** will output: "_parsing error: unknown function named "sdvdfbdb"_"

### Describe the solution you'd like

I would probably tie the ability to validate functions in **vmalert** rules to the **vmselect** connection when running `vmalert -dryRun`, of course, if i right undestand how it works)

### Describe alternatives you've considered

I used **promtool**) It's correct for PromQL.
But for check MetricsQL expressions, I need another resolve for this task. 
I think, I would use some script with functions list, but I do not know where I can find this list, because it maybe depend of version VictoriaMetrics's cluster.

### Additional information

I tested vmalert v1.88.1

**Comment by Haleygo** [comment]
Hello! 
There is validation for expressions now using [MetricsQL engine](https://github.com/VictoriaMetrics/metricsql/blob/2892124e067625ee179008eea0315832c95a8989/parser.go#L15)
```
  -rule.validateExpressions
     Whether to validate rules expressions via MetricsQL engine (default true)
```

It will check syntax error on expr like "sdvdfbdb(foo_count", but won't failed on non-exist func like "sdvdfbdb(foo_count)".
@hagen1778  Should we enhance a strictParse for MetricsQL?

**Comment by valyala** [comment]
@sinitsa1740 , `vmalert` should validate function names in [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) queries starting from the commit d5f9619984698d4b4536345df1ce26cac2765a29 . This commit will be included in the next release. In the mean time you can build `vmalert` from this commit according to [these docs](https://docs.victoriametrics.com/vmalert.html#how-to-build-from-sources) and verify whether it properly validates MetricsQL function names when executed with `-dryRun` command-line flag.

**Comment by sinitsa1740** [comment]
@valyala , i checked it, everything is working correctly. I wiil be waiting a new release, thank you!

**Comment by valyala** [comment]
FYI, [vmalert](https://docs.victoriametrics.com/vmalert.html) should properly validate [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) functions on `-dryRun` starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html).
