### ISSUE TITLE
Grafana dashboard: add a graph for determining memory shortage for the current workload

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#494]
**Is your feature request related to a problem? Please describe.**

VictoriaMetrics may use high amounts of CPU and disk IO when it has no enough memory for caching the information required for the current number of active time series. See [troubleshooting](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#troubleshooting) section for details.

Sometimes users under-provision VictoriaMetrics with RAM and struggle with bad performance and high disk IO usage.

**Describe the solution you'd like**
It would be great to provide easy-to-interpret graph on the [official Grafana dashboards for VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring), which could indicate on RAM shortage for the current workload.

The following metric has been added in the [v1.35.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) for building such a graph - `vm_slow_row_inserts_total`. It counts the number of rows that were ingested on slow path, which may trigger high CPU usage and high disk IO. The slow path is triggered in two cases:
  * when the first row (aka data point or sample) arrives for new time series. Usually this event shouldn't be frequent, otherwise it may lead to issues related to time series high churn rate.
  * when VictoriaMetrics has no enough RAM for caching the information about active time series. In this case the `increase(vm_slow_row_inserts_total[5m])` will be consistently high during extended periods of time.

So it would be great to have a graph for `sum(increase(vm_slow_row_inserts_total[5m]))` with the hint built from the information above.

**Describe alternatives you've considered**

It is possible to determine memory shortage for the current workload via indirect metrics such as CPU usage, RAM usage and disk IO usage. But these metrics depend on may other factors, so they may point to another root cause.

**Additional context**

Usually VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to [capacity planning docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#capacity-planning). But the resulting number may be far from the real number because the required amounts of memory depends on may other factors such as the number of labels per time series and the length of label values.

**Comment by hagen1778** [comment]
Dashboards were updated:
* https://grafana.com/grafana/dashboards/11176/revisions
* https://grafana.com/grafana/dashboards/10229/revisions
