### ISSUE TITLE
stream aggregation: support sharding  by custom label  ?

### ISSUE THREAD

**Issue by aluode99** [VictoriaMetrics/VictoriaMetrics#4942]
### Is your feature request related to a problem? Please describe

As mentioned in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4637, vmagent supports sharding function。 However, when configured ‘without’ or ‘by’, the sharding function cannot work perfectly.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/1c7a1fb9-3893-4013-bf9d-e8746376b24f)
Is it possible to support user-defined label hash, such as hashing by metric name?”

### Describe the solution you'd like

support user-defined label hash, such as hashing by metric name

**Comment by hagen1778** [comment]
Hi @aluode99! Good question!
I don't think option to set custom hash function will be provided. Probably, it make sense to allow to select from pre-set hash functions.

But I'd also mention that `count`, `sum`, `total` aggregations would still work and provide consistent output. And the produced result aggregation will need to be finalized on query time via `count()` or `sum()` functions over `<aggregated_metric>`.

Alternative workaround to define custom hash functions is to use vmagent's relabeling with [hashmod](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7be3848ee6f06cc90e17331f300b7135c64fb376/lib/promrelabel/relabel.go#L337-L344) action.

**Comment by hagen1778** [comment]
I'm afraid sharding via custom function or letting user change the hash function to account for metric name only can result in uneven load balance on vmagents in cluster mode. This could result in more serious problems and only increase the complexity of the system.

I'd mention once again that consistent sharding by the whole label set still allows using `count`, `sum`, `total`, etc. aggregations which can be finalized on query time later. The only affected output is [quantiles](https://docs.victoriametrics.com/stream-aggregation.html#quantiles) and I mentioned this incompatibility [here](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/40c94b26dd93c6de714908f7328b35ba65a628f6).

**Comment by hagen1778** [comment]
After reviewing more real-world usecases it looks like we should take a risk and add this feature to vmagent. It should gain support for a setting (possibly cmd-line flag) to list label names to be used in a hash function for sharding. By default, hashing function should account for all labels in the time series.

**Comment by valyala** [comment]
@aluode99 , the commit ed70a40669b81d9ba46f86342d464429a656bf55 adds `-remoteWrite.shardByURL.labels` command-line flag to `vmagent`. This command-line flag accepts a list of labels for sharding outgoing samples among the configured `-remoteWrite.url` systems if `-remoteWrite.shardByURL` command-line flag is specified as [documented here](https://docs.victoriametrics.com/vmagent.html#sharding-among-remote-storages). A few examples:

- `-remoteWrite.shardByURL=__name__` writes metrics with the same name to the same `-remoteWrite.url`
- `-remoteWrite.shardByURL=tenant` writes metrics with the same `tenant` label to the same `-remoteWrite.url`
- `-remoteWrite.shardByURL=__name__,instance` writes metrics with the same name and the same `instance` label to the same `-remoteWrite.url`

When the `-remoteWrite.shardByURL.labels` command-line flag isn't specified, then sharding is performed by metric name plus all the metric labels. This increases chances to make even distribution of outgoing time series among the configured `-remoteWrite.url` systems.

The commit ed70a40669b81d9ba46f86342d464429a656bf55 will be included in the next release. In the mean time you can build `vmagent` from this commit according to [these instructions](https://docs.victoriametrics.com/vmagent.html#how-to-build-from-sources) and verify how the `-remoteWrite.shardByURL.labels` option works.

**Comment by valyala** [comment]
The `-remoteWrite.shardByURL.labels` command-line flag is available in `vmagent` starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmagent.html#sharding-among-remote-storages) for details.

Closing the feature request as done.
