### ISSUE TITLE
[vmselect] Query fails when 1 vmstorage cannot delivery results - query should succeed as partial?

### ISSUE THREAD

**Issue by PerGon** [VictoriaMetrics/VictoriaMetrics#4944]
### Describe the bug

As per [VM Docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability), when a few `vmstorages` are unavailable, queries to `vmselect` should still succeed but only with partial data. We have seen this happening in other occasions and it's cool.

But it seems that, under certain `vmstorage` fail to reply scenarios, `vmselect` will fail a query instead of succeeding the query with partial data.

We have seen that, if a `vmstorage` node is fully unavailable (down), `vmselect` queries will succeed with partial data. But if a `vmstorage` node is available, but too busy to reply to the queries, than the `vmselect` query will fail (instead of succeeding with partial data).

So, see the following error message from `vmselect`:
```
2023-09-01T02:33:27.443Z	warn	VictoriaMetrics/app/vmselect/main.go:467	error in "/select/866551945/prometheus/api/v1/query_range?end=1693535590&query=QUERY": error when executing query="QUERY" on the time range (start=1693534990000, end=1693535590000, step=1000): error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage vmstorage-az-eu-north-1b-1.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401: cannot execute funcName="search_v7" on vmstorage "10.86.37.140:8401": couldn't start executing the request in 10.000 seconds, since -search.maxConcurrentRequests=16 concurrent requests are already executed. Possible solutions: to reduce the query load; to add more compute resources to the server; to increase -search.maxQueueDuration=10000000000; to increase -search.maxConcurrentRequests
```

This is an error message that has various error messages aggregated in one. I'll try to break them down to make the code stacktrace a bit easier to identify:
```
2023-09-01T02:33:27.443Z	warn	VictoriaMetrics/app/vmselect/main.go:467	error in "/select/866551945/prometheus/api/v1/query_range?end=1693535590&query=QUERY":

error when executing query="QUERY" on the time range (start=1693534990000, end=1693535590000, step=1000): 

error occured during search: 

cannot fetch query results from vmstorage nodes: 

cannot perform search on vmstorage vmstorage-az-eu-north-1b-1.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401: 

cannot execute funcName="search_v7" on vmstorage "10.86.37.140:8401": 

couldn't start executing the request in 10.000 seconds, since -search.maxConcurrentRequests=16 concurrent requests are already executed. Possible solutions: to reduce the query load; to add more compute resources to the server; to increase -search.maxQueueDuration=10000000000; to increase -search.maxConcurrentRequests
```

From what I understand, the last error message is the return from `vmstorage` [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.93.1-cluster/lib/vmselectapi/server.go#L545). The rest of the errors in the stack are from `vmselect` (starting from the bottom: [netstorage.go:2097](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.93.1-cluster/app/vmselect/netstorage/netstorage.go#L2097), [netstorage.go:1629](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.93.1-cluster/app/vmselect/netstorage/netstorage.go#L1629), [netstorage.go:1650](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.93.1-cluster/app/vmselect/netstorage/netstorage.go#L1650), [netstorage.go:1555](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.93.1-cluster/app/vmselect/netstorage/netstorage.go#L1555), etc.)

From my understanding, there are various ways a `vmstorage` might not be avaiable and `vmselect`, depending on the "type of unavailability" of the `vmstorage` might fail executing a query or not.

I can see by the error message we got from `vmstorage`, that this particular node was having a high load and couldn't respond to all queries in time. But my point is that `vmselect` should still succeed in executing the query even tho it didn't get a reply from 1 `vmstorage` node.

### To Reproduce

Haven't found an easy way to reproduce it

### Version

/vmstorage-prod --version
vmstorage-20230824-081552-tags-v1.93.1-cluster-0-g54a67d439c

/vmselect-prod --version
vmselect-20230824-081515-tags-v1.93.1-cluster-0-g54a67d439c

### vmselect
```
2023-09-01T02:33:27.443Z	warn	VictoriaMetrics/app/vmselect/main.go:467	error in "/select/866551945/prometheus/api/v1/query_range?end=1693535590&query=QUERY": error when executing query="QUERY" on the time range (start=1693534990000, end=1693535590000, step=1000): error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage vmstorage-az-eu-north-1b-1.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401: cannot execute funcName="search_v7" on vmstorage "10.86.37.140:8401": couldn't start executing the request in 10.000 seconds, since -search.maxConcurrentRequests=16 concurrent requests are already executed. Possible solutions: to reduce the query load; to add more compute resources to the server; to increase -search.maxQueueDuration=10000000000; to increase -search.maxConcurrentRequests
```

### vmstorage

Nothing

### vmselect
```
/ # ps aux
PID   USER     TIME  COMMAND
    1 root     21h44 /vmselect-prod --envflag.enable=true --envflag.prefix=VM_
   50 root      0:00 sh
   65 root      0:00 ps aux
/ #
/ #
/ # env | grep VM_
VM_search_maxQueryDuration=30s
VM_storageNode=vmstorage-0.vmstorage.victoriametrics.svc.cluster.local:8401,vmstorage-1.vmstorage.victoriametrics.svc.cluster.local:8401,vmstorage-2.vmstorage.victoriametrics.svc.cluster.local:8401,vmstorage-3.vmstorage.victoriametrics.svc.cluster.local:8401,vmstorage-4.vmstorage.victoriametrics.svc.cluster.local:8401,vmstorage-5.vmstorage.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-0.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-1.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-2.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-3.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-4.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-5.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-6.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-7.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-8.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-9.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-10.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-11.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-12.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1a-13.vmstorage-az-eu-north-1a.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-0.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-1.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-2.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-3.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-4.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-5.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-6.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-7.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-8.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-9.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-10.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-11.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-12.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401,vmstorage-az-eu-north-1b-13.vmstorage-az-eu-north-1b.victoriametrics.svc.cluster.local:8401
VM_http_shutdownDelay=3s
VM_http_maxGracefulShutdownDuration=30s
VM_search_maxQueueDuration=35s
VM_cacheDataPath=/cache
VM_search_maxPointsPerTimeseries=5000000
VM_memory_allowedPercent=95
```

### vmstorage
```
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      2d07 /vmstorage-prod --envflag.enable=true --envflag.prefix=VM_
   55 root      0:00 sh
  109 root      0:00 /bin/sh
  577 root      0:00 sh
  583 root      0:00 ps aux
/ #
/ #
/ # env | grep VM_
VM_storageDataPath=/storage
VM_bigMergeConcurrency=2
VM_maxConcurrentInserts=24
VM_retentionPeriod=6
VM_search_maxUniqueTimeseries=10000000
VM_memory_allowedPercent=70
```

**Comment by hagen1778** [comment]
Hello @PerGon! Each error transmitted from vmstorage to vmselect via grpc is considered as a misconfig error and should be terminated asap to let user know. It could be not only limits exceeding, but also a wrong query. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/dbcfffeedf6406133344c0061e1252dcb9d2b54d/app/vmselect/netstorage/netstorage.go#L1736-L1743

I'm not sure yet if we should introduce a class for grpc errors, to separate query errors from limit errors.

**Comment by PerGon** [comment]
Thank you for your replies. I now understand the issue better, but I still have a question: given the way data is stored in `vmstorages` which is well described in [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4922), it can happen that a certain query could disproportionally create a much heavier load in a specific `vmstorage` node than in the others, right? Which can make that specific `vmstorage` take longer to reply and/or have a queue of requests, right?

> Each vmstorage in the cluster setup is represented as a shard. The shard holds only a fraction of the data. During ingestion, vminsert component consistently shards data across available vmstorage nodes, making sure that each unique time series ends up on the same shard/vmstorage. For example, series foo and bar ingested in a 2-shard cluster will end up on separate vmstorages, no matter how many vminserts were doing the ingestion. Such an approach provides the benefit of better data locality, improves search speed, compression ratio, memory usage for caches, page cache, etc.

In our case, we have 30+ `vmstorage` all configured the same way - but we saw issues with a particular `vmstorage` that at some point, seemed to struggle to reply to all queries and eventually gave an "application level timeout" (described in the first post). In this case, what would be the best approach to deal with this issue? More resources (cpu/memory)? Increase the request time-out in `vmstorage`?

Thanks again! 🙇

**Comment by hagen1778** [comment]
>  In this case, what would be the best approach to deal with this issue? 

I think the question is related to all distributed systems. The bigger system gets (in terms of shards), the higher are chances for network/hardware glitches. This is also known as [Universal Scalability Law](https://wso2.com/blog/research/scalability-modeling-using-universal-scalability-law/). The proper ways fighting it are the following:
1. Using homogenous installations to reduce the difference in processing speed across the shards
2. Using 2-layer architecture, shards within shards, to improve data locality for each specific query. 

Adding more resources usually helps, but it doesn't protect from network glitches.

**Comment by PerGon** [comment]
Thanks for the input!

> Using 2-layer architecture, shards within shards, to improve data locality for each specific query.

When you refer to 2-layer architecture, you refer to what in the docs is referred to [Multi-level cluster setup](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup)?

In a rough sketch, something like this: 
<img width="934" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/725020/177c5c59-db45-4a82-8e09-02bfbddb8d09">

**Comment by hagen1778** [comment]
> When you refer to 2-layer architecture, you refer to what in the docs is referred to [Multi-level cluster setup](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup)?

No. I wasn't clear, sorry. I was referring to bi-level sharding: splitting the cluster shards into subshards, layers.
For example, you have a cluster consisting of 100 shards. Querying in fan-out manner 100 shards could be slower than querying 10 shards (with the same amount of data) in some cases just because of network latency. So what you can is to split 100 shards in 10 top-level shards, and each top-level shard will consist of 10 sub-shards (the splitting can be uneven, depends on hashing function).
On the ingestion path you add extra logic: data with `label=foo` goes to shard 1, data with `label=bar` goes to shard 2, and so on. The shard 1 is actually a bunch of vminserts configured with N vmstorage nodes. When this shard 1 receives ingestion request - it shards evenly across its N vmstorage nodes.
On read path you have two options:
1. Read from all shards to get global view (vmselect configured with all 100 vmstorage nodes)
2. Read from specific top-level shard if you can tell which one you need based on query.

This approach requires extra logic, ofc:
1. Additional logic for top-level sharding
2. Additional logic for matching read query to specific shard

But it gives you the following benefits:
1. Global query is still available
2. Queries selecting only specific subset of data will read only from limited list of shards.

I might be poor in explaining, but this is a common approach for distributed databases. Here's one example on SO which [explains it better](https://stackoverflow.com/questions/56589290/how-yandex-implemented-2-layered-sharding) for different database, but the logic is the same.

**Comment by PerGon** [comment]
Thanks for your help and in-depth explanation.
I feel that applying a 2-layer architecture is currently a premature optimisation for our case. But we will keep that in mind and consider it as our usage scales.

We will try to mitigate the cases were we see this issue by tweaking resources and some other optimisations that we could find.
