### ISSUE TITLE
Question: Will the alarm be restored if the relevant indicators are not uploaded when using vmalert

### ISSUE THREAD

**Issue by thislyc** [VictoriaMetrics/VictoriaMetrics#4951]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

If the monitoring data is not uploaded, will all generated alarms be restored
I understand that without monitoring data and not reaching the alarm threshold should be different. If the data is not uploaded due to network or cluster failures, it may trigger repeated alarm recovery and triggering

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hi @thislyc!

Not sure I understood the question completely, but here's the doc about state restore in vmalert https://docs.victoriametrics.com/vmalert.html#alerts-state-on-restarts
If alerts state metrics were delayed for some reason, then vmalert will restore the state based on the available metrics in the `remoteRead.url`.

**Comment by thislyc** [comment]
Hi @hagen1778 
If we generate an alarm, and the metric data latency involved in this alarm lasts about 5 minutes, it will cause my alarm to recover, but in fact this is caused by data latency or data loss. In this case, this alarm should not be restored

**Comment by jiekun** [comment]
Close as answered.
