### ISSUE TITLE
vmagent: do not crash on bad scrape config, as promethues does

### ISSUE THREAD

**Issue by rmartinez3** [VictoriaMetrics/VictoriaMetrics#4959]
### Describe the bug

Podmonitor was updated for a scrape config which prompted reaload-config to update vmagent as well.

After update vmagent began to crash

> 2023-09-05T17:01:21.741Z        fatal   VictoriaMetrics/lib/promscrape/scraper.go:116   cannot read "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse Prometheus config from "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse `scrape_config`: cannot parse auth config for `job_name` "podScrape/kube-system/goldpinger/0": cannot load TLS certificate from `cert_file`="/etc/vmagent-tls/certs/kube-system_goldpinger-tls_tls.key", `key_file`="/etc/vmagent-tls/certs/kube-system_goldpinger-tls_tls.key": tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched

Overall I did check to see code logic that at bad parse of a scrape config . fatal is logged and no config/setup is attempted.

Though on prometheus/operator setup continued to run fine . 

Overall issue is that if doing tls auth 
if one mismatches cert with key via podmonitor
```
    tlsConfig:
      ca:
        secret:
          key: ca.crt
          name: app-tls
      cert:
        secret:
          key: tls.key
          name: app-tls
      keySecret:
        key: tls.key
        name: app-tls
```
        
Fix is to correct what should be used for authentication

Though overall wondering if it makes sense for vmagent to just  log as error vs fatal and create config and proceed with scrapping other targets and disregard/null trying to scrape the bad target.

### To Reproduce

add tls authentication for podmonitor and for cert/key sets the opposite needed cred.

This will trigger reaload config and then vmagent to crash

### Version

victoria agent
v0.58.0

### Logs

> 2023-09-05T17:01:21.741Z        fatal   VictoriaMetrics/lib/promscrape/scraper.go:116   cannot read "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse Prometheus config from "/etc/vmagent/config_out/vmagent.env.yaml": cannot parse `scrape_config`: cannot parse auth config for `job_name` "podScrape/kube-system/goldpinger/0": cannot load TLS certificate from `cert_file`="/etc/vmagent-tls/certs/kube-system_goldpinger-tls_tls.key", `key_file`="/etc/vmagent-tls/certs/kube-system_goldpinger-tls_tls.key": tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched

**Comment by f41gh7** [comment]
Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4625

**Comment by valyala** [comment]
`vmagent` and single-node VictoriaMetrics shouldn't exit on startup when the `-promscrape.config` file refers to non-existing or invalid auth files, starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
