### ISSUE TITLE
armv5 builds not provided with latest packages starting vm 1.87.7 / golang1.21

### ISSUE THREAD

**Issue by cah-jad-baz** [VictoriaMetrics/VictoriaMetrics#4965]
### Describe the bug

Starting version 1.87.7, all victoriametrics packages (I tried victoriametrics, vmalert, vmagent) do not start on armv5.

Prior to this version, we could run normally on armv5. Starting with this version, we get an "Illegal instruction" error.
```
~# ./vmagent-1.87.6 --version
vmagent-20230518-230000-tags-v1.87.6-0-g4c1241d33

~# ./vmagent-1.87.7 --version
Illegal instruction
```

I'm certain this is a golang bug as I tried building a simple hello world and it failed with "Illegal instruction" as well

### To Reproduce

Run the following on armv5: ` ./vmagent-1.87.7 --version `

### Version

I tried this with 1.87.7 and 1.87.8

### Additional information

```
~# uname -a
Linux SDcard 2.6.34 #17 PREEMPT Fri Nov 11 15:06:02 MST 2011 armv5tel GNU/Linux
```

**Comment by cah-jad-baz** [comment]
It seems this is certainly a golang 1.21.0 bug. Here is the corresponding issue: https://github.com/golang/go/issues/62475

**Comment by cah-jad-baz** [comment]
Given the last comment on the golang issue, as I see it, the issue is now that, very simply, arm builds provided do not work on armv5 as GOARM version default is 6. armv5 builds now require specifically setting GOARM to 5.

As such, I'm changing the issue title to "armv5 builds not provided with latest packages starting vm 1.87.6 / golang1.21".

**Comment by hagen1778** [comment]
Hello @cah-jad-baz! armv5 seems like a very outdated legacy arch. What purpose/device do you need it for?

**Comment by valyala** [comment]
@hagen1778 , the same applies to `GOARCH=arm` - it is also an outdated arch, but it is still in use. I think it is OK to return back support for armv5 for `GOARCH=arm`. This has been returned back in the commit 04afae2aa87cc6d0b0500082a44a4199f84a4b86 , which will be included in the v1.87.9 release.

**Comment by valyala** [comment]
FYI, `GOARCH=arm` VictoriaMetrics components are built with `GOARM=5` starting from [v1.93.4](https://docs.victoriametrics.com/CHANGELOG.html). The bugfix will be backported to v1.87.9 soon.

**Comment by valyala** [comment]
The bugfix has been backported to [v1.87.9 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.9). Closing the issue as fixed.

**Comment by valyala** [comment]
@cah-jad-baz , do you still need `GOARM=5` support for `GOARCH=arm` VictoriaMetrics? See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6158/files . If you still need it, then, probably, it is better to make a separate build (or Makefile rule) for `GOARM=5`, while building `GOARCH=arm` without this restriction, since it looks like most users do not need `GOARM=5` support. cc @f41gh7 and @AndrewChubatiuk .

**Comment by cah-jad-baz** [comment]
@valyala yes, we still have armv5 devices and we will be very grateful if there are armv5 artifacts out of the box. But if we necessarily need to build it, we'll do that.

Thank you very much for keeping us in the loop about this.
