### ISSUE TITLE
Which way of writing the "or expression" is more efficient and why?

### ISSUE THREAD

**Issue by groobyming** [VictoriaMetrics/VictoriaMetrics#4974]
### Describe the question in detail

Which way of writing the "or expression" is more efficient and why？

method 1：
`sum(
  sum_over_time(ingressctrl_api_request_total_value{cluster_id='K8S-1'}[1m])
  or 
  sum_over_time(ingressctrl_api_request_total_value{cluster_id='K8S-2'}[1m])
) by (cluster_id, handler)
`

method 2：
`sum(
 sum_over_time(ingressctrl_api_request_total_value{id='K8S-1' or cluster_id='K8S-2'}[1m])
) by (cluster_id, handler)`

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by jiekun** [comment]
Hi. From the parser's perspective I think the 2nd one could run faster. However, for evaluating actual query performance, I recommend executing and comparing based on your real dataset.
