### ISSUE TITLE
 Is there a better way to query all points of a metrics?

### ISSUE THREAD

**Issue by hkmdxlftjf** [VictoriaMetrics/VictoriaMetrics#4989]
### Describe the question in detail

I want to query all points of a metrics, and find this [issues](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1623)，learned about using sum(count_over_time(metricsName{}[1d])) can solve the problem,  So is there any other better way to solve it?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by jiekun** [comment]
I think it's answered in the issue you've mentioned. If you have follow up question, feel free to add comment to [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1623)
