### ISSUE TITLE
Escape autocompleted metrics

### ISSUE THREAD

**Issue by pikrzysztof** [VictoriaMetrics/VictoriaMetrics#4993]
### Describe the bug

When I ask VMUI to autocomplete `my-long-metric-name` VM won't escape `-` signs. I hit the autocomplete button, run a query and I don't get any results which is confusing - I'm thinking how come autocomplete works if there's no data?

### To Reproduce

1. Push a metric with a `-` sign in it
2. navigate to vmui and make autocomplete add the `-` sign for you
3. observe the metric not working as expected.

### Version

vmselect-20230812-211801-tags-v1.87.7-cluster-0-ga783d88886

**Comment by Loori-R** [comment]
This issue has been fixed in vmui starting from [v1.95.0](https://docs.victoriametrics.com/changelog_2023/#v1950). Closing the issue as fixed.
