### ISSUE TITLE
Indexdb taking up too much space

### ISSUE THREAD

**Issue by dkusidlo** [VictoriaMetrics/VictoriaMetrics#4995]
### Describe the bug

After an automatic cycle of the underlying nodes and the restart of the pods, resource consumption increased significantly although incoming data did not change. Especially the index:
```/storage # du -h -d 1 .
8.0K	./metadata
85.5G	./data
4.0K	./snapshots
11.7G	./cache
936.7G	./indexdb
16.0K	./lost+found
1.0T	.
```

We had similar problems some weeks ago. We assumed they were related to our storage reaching the limit. We then increased the number of storage instances and reduced retention to 1 (from 2), which reduced slow inserts, churn and memory consumption over some time. But the indexdb always took up too much space.

### To Reproduce

No specific configuration.

### Version

During the increase `v1.92.0-cluster`. In the meantime running `v1.93.4-cluster` showing no improvement.

### Logs

No errors or suspicious logs.

### Screenshots

<img width="1008" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/8508efa1-6887-4102-9f90-06e36d2ebd7a">
<img width="1004" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/0ba6dd24-eb29-49d2-8904-cd4f513e0454">
<img width="1003" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/a3f90451-aead-4f1c-86e9-d29d29f9083d">
<img width="1006" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/448edd91-e28f-4423-b19e-4068c2b4ff4e">
<img width="1001" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/4eef01b5-ea6d-4780-917b-6e084bb63138">
<img width="1001" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/88b88dde-704d-4089-86a7-0370d40519f5">
<img width="1006" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/343604cb-cda7-4b29-875a-fca4a0703695">
<img width="991" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/9769e4d7-07fe-46ef-b65d-b24f9f0aa4a3">
<img width="1954" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/10347782/7ccb551d-331f-4ac3-a845-5eac587c7062">

### Used command-line flags

```        - name: victoria-metrics-cluster-vmstorage
          image: victoriametrics/vmstorage:v1.93.4-cluster
          args:
            - '--retentionPeriod=1'
            - '--storageDataPath=/storage'
            - '--envflag.enable=true'
            - '--envflag.prefix=VM_'
            - '--loggerFormat=json'
            - '--memory.allowedPercent=70'
            - '--search.maxUniqueTimeseries=2000000'
            - '--storage.minFreeDiskSpaceBytes=5GiB'
```

**Comment by dmitryk-dk** [comment]
Hi @dkusidlo ! Can you look at your  Chirn rate graph for the last two months? 
If you have similar spikes, the growth of the indexdb is expected because metrics are recreated with every spike. 
Please take a look at https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate documentation. 
You can analyze your data via cardinality explorer if you find that churn rate if the reason for the indexdb growth,
https://docs.victoriametrics.com/#cardinality-explorer

**Comment by jiekun** [comment]
Close due to inactivity.
