### ISSUE TITLE
MetricsQL: bitmap_*() functions unexpectedly return a value where input series has no value

### ISSUE THREAD

**Issue by mactyr** [VictoriaMetrics/VictoriaMetrics#4996]
### Describe the bug

I recently noticed that [bitmap_and(q, mask)](https://docs.victoriametrics.com/MetricsQL.html#bitmap_and) will output 0 at timestamps when its input series (that is, q) has no value. This is unexpected, and seems contrary to the documentation that states that the output will contain one value for each value of the input. I believe @dmitryk-dk has confirmed that this is a bug [on Slack](https://victoriametrics.slack.com/archives/CGZF1H6L9/p1694468075518089).

I just did a quick check and `bitmap_or()` and `bitmap_xor()` appear to have similar behavior (the output is not zero but rather a very large number on the order of 9e18 when there is no input).

### To Reproduce

Run a `bitmap_*()` query against any data set with a time window that extends into the future where there is no data. You'll notice that the output for the function extends beyond the domain of the input data.

### Version

victoria-metrics-20230407-010036-tags-v1.90.0-0-gb5d18c0d2

### Used command-line flags

```
-retentionPeriod=120 -dedup.minScrapeInterval=1s \
-search.disableCache -search.maxPointsPerTimeseries=50000 -search.maxPointsSubqueryPerTimeseries=600000 -search.latencyOffset=0s
```

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), VictoriaMetrics should return an empty point when `a` or `b` point is empty in `bitmap_*(a, b)`. Closing the issue as fixed.
