### ISSUE TITLE
Add ability to delete time series

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#5]
### The issue

There is no way to delete time series from the storage

### The solution

Add Prometheus-compatible API for metrics deletion. See https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series .

**Comment by valyala** [comment]
Ability to delete time series matching the given selector has been added in [v1.7.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)

**Comment by valyala** [comment]
Closing the issue

**Comment by timo-klarshift** [comment]
It does work to delete but prometheus client receives an error, i guess it has to do with the fact that the endpoint returns 204 and no body:

`bad_response: readObjectStart: expect { or n, but found r, error found in #1 byte of ...|remoteAddr:|..., bigger context ...|remoteAddr: "127.0.0.1:60870"; requestURI: /delete/|...`

```
*   Trying 127.0.0.1:8481...
* Connected to localhost (127.0.0.1) port 8481 (#0)
> POST /delete/1/prometheus/api/v1/admin/tsdb/delete_series?match[]={__name__="foo_field1"} HTTP/1.1
> Host: localhost:8481
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< X-Server-Hostname: vm-victoria-metrics-cluster-vmselect-5b78d6b69f-k4qck
< Date: Thu, 30 Jun 2022 19:26:17 GMT
< 
* Connection #0 to host localhost left intact
```
