### ISSUE TITLE
vmbackup: inconsistent backup being created

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#5005]
### Describe the bug

When difference between remote content and local snapshot is calculated we use the following as key for comparison:
```golang
func (p *Part) key() string {
	return fmt.Sprintf("%s%016X%016X%016X", p.Path, p.Offset, p.Size, p.ActualSize)
}
```

It works well for everything inside parts since content is append-only and re-writing part means path will be changed.
The problem arises when we're checking parts.json file, here are some paths for example:
- `./monthly/2023-09/indexdb/177BE3B0DE985B7B/parts.json`
- `./monthly/2023-09/data/small/2023_08/parts.json`

For indexdb it is located under part ID directory which will be changed, but for small parts it is very likely that file name and size will remain the same, which means that we will skip file during sync and result in malformed backup.

### To Reproduce

Create and restore a backup

### Version

v1.93.4

### Logs

Restoring from such inconsistent backup will result in:
```
FATAL: cannot parse metadata from "/vmstorage-data/data/big/2023_07/1770F5A7B3BEBCA8": unexpected number of subs
panic: FATAL: cannot parse metadata from "/vmstorage-data/data/big/2023_07/1770F5A7B3BEBCA8": unexpected number of substrings in the part name "1770F5A7B3BEBCA8": got 1; want 5
```

**Comment by valyala** [comment]
[vmbackup](https://docs.victoriametrics.com/vmbackup.html) and [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html) should properly create [incremental backups](https://docs.victoriametrics.com/vmbackup.html#incremental-backups) starting from the commit 4d01bc6d52e7f581d5e3db7c6a3f295fc6b3868f . This commit will be included in the next release. In the mean time it is possible to verify whether `vmbackup` works correctly by building it from this commit according to [these docs](https://docs.victoriametrics.com/vmbackup.html#how-to-build-from-sources).

**Comment by hagen1778** [comment]
The fix was released at [v1.93.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.5).

**Comment by valyala** [comment]
FYI, starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), `vmbackup` properly copies the `appliedRetention.txt` file during incremental backups. Previously old version of this file could remain in the backup, which could result in increased CPU usage when running VictoriaMetrics on the backup restored with [vmrestore](https://docs.victoriametrics.com/vmrestore.html).

**Comment by valyala** [comment]
FYI, the bugfix has been back-ported to [v1.93.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.6).
