### ISSUE TITLE
Will vmstorage do data migration when horizon scale ?

### ISSUE THREAD

**Issue by derecknowayback** [VictoriaMetrics/VictoriaMetrics#5010]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Hi guys, I have read about [#issue1207](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1207), and there is one thing confusing me that will vmstorage do data migration when horizon scale ? The promblem here seems to be the disability of migrating data to new vmstorage instance or data sync across the cluster. 

Btw: I have **already** read about the recent change you guys done for the case.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by divinesecret** [comment]
`vmstorage` does not do any rebalancing and data migration, it does not know anything about other storage instances too. If you add a storage node then `vminsert` instance will use it for inserting new metrics or inserting old metrics if one of the current nodes is not available. `vmselect` does query all of the storage nodes to fetch and merge the data. According to documentation we can make an assumption that VictoriaMetrics was designed to be best used against storage solutions that handle the replication and failover on its own (i.e. ceph, minio, etc).

**Comment by derecknowayback** [comment]
> `vmstorage` does not do any rebalancing and data migration, it does not know anything about other storage instances too. If you add a storage node then `vminsert` instance will use it for inserting new metrics or inserting old metrics if one of the current nodes is not available. `vmselect` does query all of the storage nodes to fetch and merge the data. According to documentation we can make an assumption that VictoriaMetrics was designed to be best used against storage solutions that handle the replication and failover on its own (i.e. ceph, minio, etc).

Much appreciate!
