### ISSUE TITLE
How to get the uuid of a disk in disk_used_percent metric ?

### ISSUE THREAD

**Issue by sanvegeta** [VictoriaMetrics/VictoriaMetrics#5013]
### Is your question request related to a specific component?

Victoriametrics

### Describe the question in detail

hi all,

I am trying to create an alert rule on disk usage of my hadoop cluster 
However, it appears that the disk device can change after the server reboot (for example, /dev/sda1 can change to /dev/sdb1)
Therefore, I want to get the metric disk_used_percent by the uuid of my disk instead of its device name
Do you know how can I do it ?

VictoriaMetrics version : 1.87.1

thanks

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, VictoriaMetrics doesn't export any information related to the disk identifiers (such as name or uuid), only mounted folder utilization. 

 I suggest to use  node-exporter or any similar tool for monitoring host metrics. https://github.com/prometheus/node_exporter

**Comment by sanvegeta** [comment]
alright thank you for your quick reply
I'll try with that
