### ISSUE TITLE
vmalert: result of rate(recording rule) differs from rate(original) 

### ISSUE THREAD

**Issue by towolf** [VictoriaMetrics/VictoriaMetrics#5014]
### Describe the bug

Something really puzzling is happening to some CPU metrics that I send from VM to a central VM cluster.

I created a recording rule to enrich some basic CPU metrics with labels and drop anything irrelevant. It's a simple counter.

The result looks like this (The result of the recording rule is shifted in time by 30s for some reason, but otherwise numerically identical)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/345210/b0daf699-a2c6-495d-9ae6-6453bbd57e7b)

But since this is a counter of CPU seconds, I need to apply a rate(), and the result of that is completely different. From four datapoints it creates five datapoints with a weird slope.Somehow the rate of the recording rule is not computed right.
Anyone have a clue as to why that's happening?

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/345210/76d3fd4f-2f0e-4a6e-a8a3-ec531b07788f)

### To Reproduce

My recording rule is this:

          - expr: |-
              label_move(
                  sum by (cluster, node, namespace, pod) (
                      container_cpu_usage_seconds_total{job="kubelet", metrics_path="/metrics/cadvisor", image!="", container=~"default"}
                  )
                  * on (cluster, pod)
                  group_left (
                      namespace,
                      node,
                      label_armada_name,
                      label_armada_rev,
                      label_armada_set_name,
                      label_region_name,
                      label_type_name,
                  )
                  kube_pod_labels{label_armada_name!=""}
                  * on (cluster, pod)
                  group_left (
                      namespace,
                      node
                  )
                  kube_pod_info{namespace="default"},
                   "label_armada_name", "armada",
                   "label_armada_rev", "rev",
                   "label_armada_set_name", "armadaset",
                   "label_region_name", "region",
                   "label_region_type_name", "type",
              )
            record: agones_cluster_pod_cpu:container_cpu_usage_seconds_total

### Version

v1.93.4-cluster

**Comment by towolf** [comment]
Here's another example:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/345210/dffc5b2e-9e47-49ab-9f76-fb4652fe4d1f)

How do I create a recording rule that matches the original? 

Yellow  good, green bad.

**Comment by hagen1778** [comment]
Hello! 
> By default, recently written samples to VictoriaMetrics aren't visible for queries for up to 30s (see -search.latencyOffset command-line flag at vmselect). Such delay is needed to eliminate risk of incomplete data on the moment of querying, since metrics collectors won't be able to deliver the data in time.

See https://docs.victoriametrics.com/vmalert.html#data-delay

**Comment by towolf** [comment]
Hi, but my main problem is not the delay but the result of the recording rule.

Our customer is confused because there is no straight line `----` but something that slopes up at the end. The source and the result differ even though they should be identical, even if they are shifted in time.

**Comment by hagen1778** [comment]
> The source and the result differ even though they should be identical, even if they are shifted in time.

There is no such guarantee. Recording rule doesn't know if data in datasource is up to date or delayed. Recording rule is executed once per configured `interval` by sending /query request. Even if raw data stopped updating, recording rule will continue adding new datapoints after each evaluations, as it will be getting the last raw datapoint each time.

Can we compare results of raw query and recording rule without using `rate`?
