### ISSUE TITLE
Will a huge number of vmauth users cause a performance bottleneck for vmauth?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5024]
### Is your question request related to a specific component?

vmauth

### Describe the question in detail

I have a scenario like this:

I use the project label in metrics to convert it into metrics, and provide labels for people from different external projects to access their projects. I need to configure a corresponding user for the label of each project. There will be about 1,000 users. Is this right? Will there be a performance bottleneck?

users:
   - username: "project_1"
      password: "passwd_1"
      url_prefix: "http://vmselect.victoriametrics.svc.cluster.local:8481?extra_label=project=1"
   - username: "project_2"
      password: "passwd_2"
      url_prefix: "http://vmselect.victoriametrics.svc.cluster.local:8481?extra_label=project=2"
   ...
   ...
   - username: "project_1000"
      password: "passwd_1000"
      url_prefix: "http://vmselect.victoriametrics.svc.cluster.local:8481?extra_label=project=1000"

Is there a more reasonable or efficient and scalable method to recommend?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Is this right?

Looks like a good way to limit the access of the users to specific data. Would you prefer something auto-generated?

>  Will there be a performance bottleneck?

Because of the big config? Unlikely. 
Performance could be an issue when handling high RPS number of high number of connections transferring a lot of data.

**Comment by luzejia** [comment]
> > Is this right?
> 
> Looks like a good way to limit the access of the users to specific data. Would you prefer something auto-generated?
> 
> > Will there be a performance bottleneck?
> 
> Because of the big config? Unlikely. Performance could be an issue when handling high RPS number of high number of connections transferring a lot of data.

If there is an automatically generated method, I would also like it very much.

**Comment by dave2wave** [comment]
I use a script to add to `vmauth.yml`
```
#!/bin/bash
cd /home/ubuntu
echo "" >> vmauth.yml
echo "- bearer_token: \"${1}\"" >> vmauth.yml
echo "  url_prefix: \"http://localhost:8428\"" >> vmauth.yml
echo "  max_concurrent_requests: 60" >> vmauth.yml
```
Followed by

**Comment by hagen1778** [comment]
> If there is an automatically generated method, I would also like it very much.

I'd be glad to have one, but if passwords will be generated automatically by vmauth - it would be easy for user to "guess" password for another tenant.
It also would require to provide a list of label values for vmauth, so it can do such autogeneration. 

So far it looks like having a custom script, which you own and don't disclose to your users, sounds like the most secure and flexible way to do this.

**Comment by jiekun** [comment]
Close as answered.
