### ISSUE TITLE
Optimizing the use of vmalert

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#5037]
### Is your question request related to a specific component?

VictoriaMetrics, vmagent, vmalert

### Describe the question in detail

I am trying to develop a optimized solution for monitoring edge systems at scale, I will leave a sketch here for better comprehension.

![vmalert_hipotetical](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/879e7ced-3da4-4797-9bff-e0cb90b04584)

My question is, since the vmagent has a cache for the metrics scraped, is there a possibility that instead of executing rules against a VM storage the vmalert can acess the vmagents cache at the edge layer (Red Arrows), this would allow for a faster error detection?
If not and given the architecture presented what would be the best solution in order to allow for the fastest error detection possible given that there will be millions of devices running different applications being monitored?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @DaRealCapz 

> My question is, since the vmagent has a cache for the metrics scraped, is there a possibility that instead of executing rules against a VM storage the vmalert can acess the vmagents cache at the edge layer (Red Arrows), this would allow for a faster error detection?

No, this is not possible as vmagent does not provide query interface.

>  If not and given the architecture presented what would be the best solution in order to allow for the fastest error detection possible given that there will be millions of devices running different applications being monitored?

To get the fastet error detection you might host an installation of VictoriaMetrics single-node and vmalert in each region and do alerts evaluation locally for each region. This will allow to make sure that data is always up-to-date and also allow to ensure that alerting will continue to work in case central VictoriaMetrics will be unavailable due to some reason.

**Comment by DaRealCapz** [comment]
Ok, thank you for your assistance!
