### ISSUE TITLE
Query is executed through vmui, but occasionally the result is empty.

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5039]
### Describe the bug

Query is executed through vmui, but the following results occasionally appear: 

{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": []
    },
    "stats": {
        "seriesFetched": "2805"
    }
}

At this time vmui displays as follows:
<img width="518" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52991866/8ded38f0-38c4-4723-a2f9-0c9c72a16a43">

The normal situation is as follows:
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": [
            {
                "metric": {
                    "addr": "x.x.x.x",
                    "app": "metrics-collector",
                    "statefulset_kubernetes_io_pod_name": "metrics-collector-0"
                },
                "value": [
                    1695287994.46,
                    "0"
                ]
            }
            ...
            ...
    },
    "stats": {
        "seriesFetched": "2805"
    }
}

why does seriesFetched have a value, but the result is empty?And it appears sporadically

### To Reproduce

Repeat query

### Version

victoriametrics cluster v1.92

**Comment by zekker6** [comment]
@luzejia Could you please attach [query traces](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#query-tracing) for both cases?
It seems like this might be caused by cache on one of vmselect nodes. Could you also try to use "disable cache" in VMUI and see if the same happens?

**Comment by zekker6** [comment]
Could you please attach JSON contents for both traces?

**Comment by luzejia** [comment]
> Could you please attach JSON contents for both traces?

[root@~]# curl http://x.x.x.x./select/0/prometheus/api/v1/query_range -d 'query=2*rand()' -d 'start=-1h' -d 'step=1m' -d 'trace=1' |  jq '.trace'

{
  "duration_msec": 0.195,
  "message": "vmselect-20230728-102702-tags-v1.92.1-cluster-0-gc5c539f97: /select/0/prometheus/api/v1/query_range: start=1695289380000, end=1695292920000, step=60000, query=\"2*rand()\": series=1",
  "children": [
    {
      "duration_msec": 0.032,
      "message": "eval: query=2 * rand(), timeRange=[2023-09-21T09:43:00Z..2023-09-21T10:42:00Z], step=60000, mayCache=true: series=1, points=60, pointsPerSeries=60",
      "children": [
        {
          "duration_msec": 0.03,
          "message": "binary op \"*\": series=1",
          "children": [
            {
              "duration_msec": 0.003,
              "message": "eval: query=2, timeRange=[2023-09-21T09:43:00Z..2023-09-21T10:42:00Z], step=60000, mayCache=true: series=1, points=60, pointsPerSeries=60"
            },
            {
              "duration_msec": 0.017,
              "message": "eval: query=rand(), timeRange=[2023-09-21T09:43:00Z..2023-09-21T10:42:00Z], step=60000, mayCache=true: series=1, points=60, pointsPerSeries=60",
              "children": [
                {
                  "duration_msec": 0.016,
                  "message": "transform rand(): series=1"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "duration_msec": 0.005,
      "message": "sort series by metric name and labels"
    },
    {
      "duration_msec": 0.031,
      "message": "generate /api/v1/query_range response for series=1, points=60"
    }
  ]
}

**Comment by zekker6** [comment]
@luzejia As far as I can see, this trace is not related to originally posted issue as it uses `2 * rand()` query instead of real one.

**Comment by luzejia** [comment]
> @luzejia As far as I can see, this trace is not related to originally posted issue as it uses `2 * rand()` query instead of real one.

more info:
[trace.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12696028/trace.txt)

**Comment by zekker6** [comment]
Thank you. Could you also attach the trace when same query returns no datapoints?

**Comment by luzejia** [comment]
> Thank you. Could you also attach the trace when same query returns no datapoints?

Hello, when I use curl to execute, I don’t find empty, but it will appear when executing on vmui.

**Comment by zekker6** [comment]
@luzejia Could you check for result of request in network tab of browser dev tools when VMUI shows no results?

@Loori-R could you please take a look?
Seems like under certain conditions VMUI switches to parsing instant query result and thus does not display any result since it should be `query_range` response.

**Comment by Loori-R** [comment]
Hello, @luzejia 

`query_range` is used for displaying the `Graph`.
`instant_query` is used for the `JSON` and `Table` tabs.

The `seriesFetched` field indicates the number of time series that were read from storage before the comparison operator was applied. If you have `seriesFetched: 0`, it means that the expression doesn't match any time series. If the value is greater than `0`  but the response is empty, this might suggest that the corresponding time series were filtered out. @hagen1778 , correct me if I'm wrong.

The problem might be related to the time interval and step. Since `instant_query` displays a graph for the `last 5 minutes`, there's a possibility that some data doesn't fall into this time frame or gets filtered out due to a specific step. I recommend checking the settings for the `time interval` and `step`, and also verifying this behavior on the `Graph` tab.

**Comment by luzejia** [comment]
> Hello, @luzejia
> 
> `query_range` is used for displaying the `Graph`. `instant_query` is used for the `JSON` and `Table` tabs.
> 
> The `seriesFetched` field indicates the number of time series that were read from storage before the comparison operator was applied. If you have `seriesFetched: 0`, it means that the expression doesn't match any time series. If the value is greater than `0` but the response is empty, this might suggest that the corresponding time series were filtered out. @hagen1778 , correct me if I'm wrong.
> 
> The problem might be related to the time interval and step. Since `instant_query` displays a graph for the `last 5 minutes`, there's a possibility that some data doesn't fall into this time frame or gets filtered out due to a specific step. I recommend checking the settings for the `time interval` and `step`, and also verifying this behavior on the `Graph` tab.

hello, what does "instant_query displays a graph for the last 5 minutes" mean exactly?Does it mean that instant_query will return all data points for 5 minutes by default?

**Comment by Loori-R** [comment]
The phrase indicates that by default, [instant_query](https://docs.victoriametrics.com/keyConcepts.html#instant-query) automatically retrieves data for the last 5 minutes in JSON or table format, without considering the step. If you require data over a different interval, the [last_over_time](https://docs.victoriametrics.com/MetricsQL.html#last_over_time) function can be used to define a custom interval.

You can read more about data retrieval in the documentation: 
- https://docs.victoriametrics.com/keyConcepts.html#instant-query
- https://docs.victoriametrics.com/MetricsQL.html#last_over_time

**Comment by luzejia** [comment]
> The phrase indicates that by default, [instant_query](https://docs.victoriametrics.com/keyConcepts.html#instant-query) automatically retrieves data for the last 5 minutes in JSON or table format, without considering the step. If you require data over a different interval, the [last_over_time](https://docs.victoriametrics.com/MetricsQL.html#last_over_time) function can be used to define a custom interval.
> 
> You can read more about data retrieval in the documentation:
> 
> * https://docs.victoriametrics.com/keyConcepts.html#instant-query
> * https://docs.victoriametrics.com/MetricsQL.html#last_over_time

thanks!
