### ISSUE TITLE
vmagent: failing to get data from consul on jobs with high amount of services

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#504]
Some scrape jobs with `consul_sd_configs` service discovery, which returns many registered services to scrape data from, do not working properly, getting many errors in log:

```2020-05-19T08:50:39.567Z        error   VictoriaMetrics/lib/promscrape/config.go:345    error when discovering consul targets for `job_name` "service_discovery_bridge": error when fetching service nodes data from Consul: cannot obtain instances for serviceName="<service_name>": cannot fetch "http://<hostname>:8500/v1/health/service/<service_name>?dc=<dc>&stale": no free connections available to host; skipping it```

Looks like there is no enough concurrency to pull data from consul about all services. May be this may be fixed by increasing `Client.MaxConnsPerHost` option in fasthttp. So it will be great to get ability to define this setting in vmagent.

**Comment by valyala** [comment]
This issue has been addressed in the commit cf87b810b7326bd4d9034d4332498c060af79602 . It limits the maximum concurrency for Consul API calls, so the maximum number of connections per host isn't reached. The commit will be included in the next release.

**Comment by wf1nder** [comment]
I builded vmagent from this commit and checked it, now it works correctly. Thanks!

**Comment by valyala** [comment]
The bugfix has been included in the release [v1.35.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
