### ISSUE TITLE
vmalert: cUrl example in UI should hide sensitive info

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5044]
### Describe the bug

vmalert's UI provides an [alert state feature](https://docs.victoriametrics.com/vmalert.html#alerts-state) which shows the example of cUrl command to repeat the query. Looks like this example could contains sensitive data, like basic auth params. We should hide this data from UI and leave placeholders <secret> instead.
The same should be checked for logs printed in [debug mode](https://docs.victoriametrics.com/vmalert.html#debug-mode) and configured notifiers URLs displayed in web UI. Notifiers should also have secured cmd-line flags.

### To Reproduce

Setup vmalert with `datasource.basicAuth.*` params and check [alert state](https://docs.victoriametrics.com/vmalert.html#alerts-state).

### Version

Starting from [v1.82](https://docs.victoriametrics.com/CHANGELOG.html#v1820)

**Comment by hagen1778** [comment]
@dmitryk-dk I've updated the issue description to account for notifiers security questions

**Comment by valyala** [comment]
[vmalert](https://docs.victoriametrics.com/vmalert.html) should hide sensitive information in [web UI](https://docs.victoriametrics.com/vmalert.html#web) starting from the release [v1.93.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.6). Closing the issue as fixed then.

**Comment by valyala** [comment]
FYI, this change has been also included into vmalert since [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html).
