### ISSUE TITLE
Does vmalert remotewrite address support multiple?

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#5047]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

I am using the recording feature of vmalert to calculate metrics and I want to write the calculated results to multiple vm stores, does vmalert support this feat

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, no, vmalert doesn't support such feature. But you can use vmagent for data routing. 

 Configure vmalert to write recording rules into vmagent, vmagent'll route data between multiple remote write targets.
