### ISSUE TITLE
Statsd protocol compatibility for vmagent

### ISSUE THREAD

**Issue by Koilanetroc** [VictoriaMetrics/VictoriaMetrics#5052]
### Is your feature request related to a problem? Please describe

I want to use vmagent as a drop in replacement for Statsd server and send metrics there directly from statsd clients. Currently its [not supported](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4600)

### Describe the solution you'd like

Compatibility with statsd clients in vmagent. For example [this](https://github.com/Shopify/statsd-instrument) and [this](https://github.com/DataDog/dogstatsd-ruby) statsd clients should be able to send metrics directly to vmagent

**Comment by Koilanetroc** [comment]
Please have a look at my draft implementation - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5053
Basically I copied graphite implementation and adapted it for statsd protocol.

Please let me know if you accept PRs and if you are interested in this feature. Also maybe you have other plans for compatibility with statsd protocol.

If you are interested in merging this, I'd be happy to finish it and improve with your feedback.

**Comment by Koilanetroc** [comment]
Marked PR as ready for review, waiting for maintenerses review 👀

**Comment by valyala** [comment]
Closing as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/206
