### ISSUE TITLE
About migrating data from a vm cluster using vmctl

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#5058]
### Describe the question in detail

I want to migrate more than a month's worth of data from a vm cluster to another database, this storage is compatible with the Prometheus remote_write protocol, does vmctl support data migration in this way?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @FengZh61.

VictoriaMetrics supports two methods for importing:

- By default: `/native` (works only for VictoriaMetrics)
- With `-vm-native-disable-binary-protocol` flag: `/api/v1/import` (works in a similar way to prometheus remote write, but you can't change this endpoint)

You can try, but we don't guarantee to work with anything other than VM.
