### ISSUE TITLE
vminsert: multitenant url doesnt work for opentsdbhttp

### ISSUE THREAD

**Issue by ysh7** [VictoriaMetrics/VictoriaMetrics#5061]
### Describe the bug

Multitenant opentsdbhttp endpoint for vminsert doesn't work. 

### To Reproduce

```curl -H 'Content-Type: application/json' -d '{"metric":"x.y.z","value":45.34,"tags":{"t1":"v1","t2":"v2"}}' 'http://localhost:4242/insert/multitenant/api/put?extra_label=vm_account_id=1'```

> remoteAddr: "10.67.111.183:52552, X-Forwarded-For: 172.30.201.37"; requestURI: /insert/multitenant/api/put?extra_label=vm_account_id=1; auth error: cannot parse accountID from "multitenant": strconv.ParseUint: parsing "multitenant": invalid syntax

### Version

v1.93.4-cluster

### Additional information

The same fix applied for fixing #4947 in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7db72dd7e63fa9aff80ffb4da71a4cea060f1c76 needs to be ported to the opentsdb interface https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7db72dd7e63fa9aff80ffb4da71a4cea060f1c76/app/vminsert/opentsdbhttp/request_handler.go#L37

**Comment by Amper** [comment]
Hey @ysh7.

Fixed in #5063.

**Comment by valyala** [comment]
FYI, the bug has been introduced in [v1.93.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.2) when fixing the https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4910 .

The bugfix will be included in the next release.

**Comment by valyala** [comment]
FYI, see also the follow-up commit 15645c8a94885f319902fb8fa28f7a49aaa59745 , which fixes the multitenant url handler at [vmagent](https://docs.victoriametrics.com/vmagent.html).

**Comment by valyala** [comment]
Starting from [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html), [multitenant urls](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy-via-labels) should work properly in `vminsert` and `vmagent`. Closing the issue as fixed.

**Comment by valyala** [comment]
FYI, the bugfix has been included also in [v1.87.10](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.10).

**Comment by valyala** [comment]
FYI, the bugfix has been back-ported to [v1.93.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.6)
