### ISSUE TITLE
Data was prematurely deleted due to bug in 1.93.0 version

### ISSUE THREAD

**Issue by ivankovnatsky** [VictoriaMetrics/VictoriaMetrics#5062]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Basically we have all of our prod metrics lost except for the last 2 days.

<img width="1340" alt="Untitled" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/75213/6dea7d18-9e7e-421e-a24c-a19adc4c238c">

Version: 1.93.0.
Retention: 30 days.

We deploy vm in terraform, like this:

```terraform
resource "helm_release" "vmsingle_v0" {
  repository   = "https://victoriametrics.github.io/helm-charts/"
  name         = "vmsingle-v0"
  chart        = "victoria-metrics-single"
  version      = local.victoria_metrics_chart_version
  namespace    = kubernetes_namespace.monitoring.metadata[0].name
  force_update = true

  values = [
    <<-EOT
server:
  resources:
    requests:
      cpu: ${local.vm_resources_cpu}
      memory: ${local.vm_resources_memory}
  # -- Data retention period in month
  retentionPeriod: 1
  persistentVolume:
    storageClass: "${kubectl_manifest.storage_class_gp3.name}"
    # -- Size of the volume
    size: "${var.vm_k8s_disk_size}"
  extraArgs:
    maxLabelsPerTimeseries: "50"
    search.maxUniqueTimeseries: "6000000"
    search.logSlowQueryDuration: "30s"
    selfScrapeInterval: "10s"

  nodeSelector:
    default: "true"
EOT
  ]
}

...
  victoria_metrics_chart_version = "0.9.3"
...
```

We did deploy vm version change on Sep 12, only (_probably_) retention went into action this Friday. Do I understand correctly that 1.93.1 fixes this? https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.1. I was reading this issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4873. But I'm not sure that this 100% related.

Do I understand correctly that we lost metrics because of 1.93.0 misbehaving in one way or another? If not can please help to understand or navigate me how can I debug this.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @ivankovnatsky!

I'm sorry for this issue. It is a known bug of [1.93](https://docs.victoriametrics.com/CHANGELOG.html#v1930) version:
> It is recommended upgrading to [VictoriaMetrics v1.93.1](https://docs.victoriametrics.com/CHANGELOG.html#v1931) because v1.93.0 contains a bug, which can lead to data loss because of incorrect indexdb rotation. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4873) for details.

We published this notification to the CHANGELOG, and also notified our telegram and slack channels about the issue. I'm very sorry it happened to you. I'd recommend joining our communication channels to get such notifications. I also hope you followed our recommendations for data safety and made a backup - https://docs.victoriametrics.com/Quick-Start.html?#data-safety

**Comment by ivankovnatsky** [comment]
@hagen1778 got it, thanks. No it was my bad upgrading to x.0. It reminded me a bit to harsh 😄
