### ISSUE TITLE
Add additional information in `vlinsert.elasticsearch`

### ISSUE THREAD

**Issue by khanh96le** [VictoriaMetrics/VictoriaMetrics#5065]
### Is your feature request related to a problem? Please describe

When logs cannot ingested by VMlogs, I expected I can find enough helpful information in the logs.
Currently, it seems lacking of information

Example:
```
{"ts":"2023-09-26T09:10:04.316Z","level":"warn","caller":"VictoriaMetrics/app/vlinsert/elasticsearch/elasticsearch.go:96","msg":"cannot decode log message #61 in /_bulk request: cannot read log message, since its size exceeds -insert.maxLineSizeBytes=1000000"}
{"ts":"2023-09-26T09:11:13.238Z","level":"warn","caller":"VictoriaMetrics/app/vlinsert/elasticsearch/elasticsearch.go:96","msg":"cannot decode log message #911 in /_bulk request: cannot parse json-encoded log entry: cannot parse json: cannot parse JSON: cannot parse object: cannot find opening '\"\" for object key; unparsed tail: \"\""}
```

In both cases, it should be much easier for me to debug if the `_stream` caused the error is shown.

### Describe the solution you'd like

I suggest to log the `StreamFields` as well

```
# app/vlinsert/elasticsearch/elasticsearch.go
logger.Warnf("cannot decode log message #%d in /_bulk request: %s, stream fields: %s", n, err, cp.StreamFields)
```

**Comment by hagen1778** [comment]
@zekker6 @valyala could you please take a look?

**Comment by valyala** [comment]
The `_stream_fields` value is logged on the error to parse elasticsearch log entry after the commit 4b7e6b36cec535cd40135262966a24b5461a3744 . This commit will be included in the [next VictoriaLogs release](https://docs.victoriametrics.com/VictoriaLogs/CHANGELOG.html).

**Comment by fukawi2** [comment]
The fix for this issue appears to literally log the names of the stream fields, not the values. I'm quite possibly just a little dense, but it's unclear to me how this is supposed to help identify the source of the problem?

```
VictoriaMetrics/app/vlinsert/elasticsearch/elasticsearch.go:108        cannot decode log message #60843 in /_bulk request: cannot parse json-encoded log entry: cannot parse JSON: cannot parse object: cannot find opening '"" for object key; unparsed tail: "", stream fields: [host process]
```
