### ISSUE TITLE
Transitioning from Thanos to Victoriametrics

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5067]
### Is your question request related to a specific component?

vmselect 

### Describe the question in detail

I'm in the process of evaluating a transition from Prometheus+Thanos to Victoriametrics.   My challenge is that I have up to a year of historical metrics currently stored in a GCS bucket (accessible via Thanos Query+Store) which would still need to be accessible to meet our one year retention guarantee.  Is there anyway I can point vmselect to instances of Thanos Store so that these metrics aren't lost?

Thank you for your help.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @hartfordfive!

>  Is there anyway I can point vmselect to instances of Thanos Store so that these metrics aren't lost?

Unfortunately no, vmselect can't read data form object storage or in Prometheus format. For migration from thanos, one should follow the recommendations below:
https://docs.victoriametrics.com/vmctl.html#migrating-data-from-thanos

**Comment by LH8PPL** [comment]
> Hello @hartfordfive!
> 
> > Is there anyway I can point vmselect to instances of Thanos Store so that these metrics aren't lost?
> 
> Unfortunately no, vmselect can't read data form object storage or in Prometheus format. For migration from thanos, one should follow the recommendations below: https://docs.victoriametrics.com/vmctl.html#migrating-data-from-thanos

If I want to get historical data, 30 days backwards, is the thanos-remote-read an option?

**Comment by hagen1778** [comment]
@LH8PPL remote-read protocol is pretty unoptimized and expensive way to read the data. Its performance mostly depends on the resources dedicated to thanos-remote-read-proxy and other thanos components. So I'd suggest trying it, as I don't have a good answer of how efficient it could be.

**Comment by hartfordfive** [comment]
@hagen1778 , in the documentation it shows an example using vmsingle.   Which port would you specify if you're importing data to an existing vmcluster setup?

**Comment by tiny-pangolin** [comment]
the port for vminsert runs on port 8480 and requires adding `/insert/<tenant_id>/promethues` to the url. The default tenant is zero so the vmctl command from the docs would look like 

```
vmctl prometheus --prom-snapshot thanos-data --vm-addr http://vminsert:8480/insert/0/prometheus
```

**Comment by jiekun** [comment]
Close as answered.
