### ISSUE TITLE
Series appear after short amount of time after deletion

### ISSUE THREAD

**Issue by ilyatrefilov** [VictoriaMetrics/VictoriaMetrics#5069]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Hi!
I do use this handler `/api/v1/admin/tsdb/delete_series` to delete series in case of incorrect labels. Application  deletes these series in standalone VictoriaMetrics via handler mentioned above and from metrics exporter almost simultaneously.

After request to this handler i do `watch -n 1 curl -g 'http://localhost:8084/api/v1/series/?' --data-urlencode 'match[]=myMetric{job="job"}' -d 'nocache=1'` and `watch -n 1 curl http://localhost:2323/metrics -q | grep myMetric`.
There are no series on exporter and no series on requests to `api/v1/series`, but after ~10-20s they appear again in request to `api/v1/series`

As a side note, if i do `query_range` with filter on these series after they were somehow restored, i get no results.

I didn't find any suitable advice on how to troubleshoot this one in troubleshooting guide.

Version: 1.93.5

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @ilyatrefilov!
Do you continue to ingest series which match the filter you used for deleting them?

**Comment by ilyatrefilov** [comment]
No , i do not.

I timed scraping and it does happen after exporter has no series matching the filter. Maybe there is some sort of scraping cache involved in this?

I've also tested this with exporter that was immediately shut down after deletion of series in VictoriaMetrics, and the issue did not reproduce in such scenario.

**Comment by hagen1778** [comment]
To sum up:
1. There was a series ingested into VM
2. The series isn't longer ingested, though
3. You delete it via /api/v1/delete API and can confirm it doesn't return for /api/v1/series or /api/v1/query_range APIs
4. After some time, series start to be returned again for /api/v1/series only, but is still missing for /api/v1/query_range

Is my understanding correct? Could you please [export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) the time series and verify its latest written timestamp - when it was updated: before or after the deletion?

**Comment by hagen1778** [comment]
@ilyatrefilov https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5174 was merged and will be likely included into the next release.

**Comment by hagen1778** [comment]
@ilyatrefilov I'd like to mention that DELETE API is not something you should use on a permanent basis, as it accumulates an overhead of keeping deleted series IDs in the indexdb. The mentioned bug was likely discovered because the deletes were used frequently, that's why I think this warning should be mentioned explicitly.

**Comment by valyala** [comment]
VictoriaMetrics should stop creating new time series when it receives [staleness marker](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers) for new time series, starting from [v1.93.7 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.7).

**Comment by valyala** [comment]
FYI, the bugfix for this issue has been included into [v1.95.0 release](https://docs.victoriametrics.com/CHANGELOG.html).

**Comment by f41gh7** [comment]
FYI, we decided to revert proposed fix due to possible side-effect at cluster version: 
```
- In a cluster configuration the samples for a given time series are
normally sent to the same vmstorage replica. However, wminsert may
reroute the samples to another replica because the original one is down
or is overloaded. In this case the stale NaN may end up on a replica
that has no data for that time series, but we still want to record that
sample.
```

**Comment by ilyatrefilov** [comment]
@f41gh7  Wouldn't you mind mentioning the first build version to include this fix here ?
This behaviour is unacceptable for my use case, so I really need to know the  last possible versions for potential update

**Comment by hagen1778** [comment]
@ilyatrefilov the last version without the revert is https://docs.victoriametrics.com/changelog/#v11030
