### ISSUE TITLE
Why are metrics from node_exporter not appearing on vmagent?

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#5075]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I am using you docker compose file from deployment/docker folder with some slight changes, I have added a node exporter in order for it to send metrics to the existing vmagent. 
![imagem](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/2e3d6370-e360-4cd3-afa3-f7ba2fe962f7)

And did some changes to the prometheus.yml file:
![imagem](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/655322c5-eda1-46d7-8e2a-0839e3fe647f)

The problem is that the metrics from the node exporter are not appearing on the http://127.0.0.1:8428/metrics address neither on http://127.0.0.1:8429/metrics. Am I missing something?

I would also like to ask for some guidance on how to add labels to the node exporters container metadata and how to use service discovery to retrieve those added labels.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @DaRealCapz ! When you define the node exported as a target in the scrape config, `vmagent` will start to scrape node exporter metrics and send them to the configured storage. Please see this part of the documentation about vmagent
https://docs.victoriametrics.com/vmagent.html#vmagent. 

Those address http://127.0.0.1:8428/metrics,  http://127.0.0.1:8429/metrics exposes their own metrics and have nothing to do with node exporter

**Comment by DaRealCapz** [comment]
After using vmui i found the node exporter metrics. Thank you for your help !
