### ISSUE TITLE
InfluxDB v2 support

### ISSUE THREAD

**Issue by maxb** [VictoriaMetrics/VictoriaMetrics#5076]
### Is your feature request related to a problem? Please describe

I would like to send metrics from Traefik to VictoriaMetrics.

The InfluxDB HTTP protocol seems like it would be the easiest way to do this.

VictoriaMetrics supports InfluxDB v1 ... but Traefik v3 is going to drop support for InfluxDB v1, and only support v2!

It looks rather like the changes from v1 to v2 are mostly irrelevant for Victoria Metrics, being focussed on URL query parameters that are only relevant for InfluxDB's cloud service... however the v2 API client comes with a hardcoded requirement that the write URL include `api/v2/`.

### Describe the solution you'd like

Looking through the InfluxDB v2 client code, it seems like it would probably be sufficient for VictoriaMetrics to expose a new endpoint at `/influxdb/api/v2/write`.

I haven't actually tested it, but it looks a lot like all the existing request parsing logic could be used as-is, just at a different URL.

### Describe alternatives you've considered

I could migrate to a different metrics protocol entirely, but none seem quite as convenient as direct HTTP push.

### Additional information

The current VictoriaMetrics documentation is unclear about which version of the InfluxDB API it implements. It would be good to explicitly call out InfluxDB v1 vs. v2 where relevant.

**Comment by maxb** [comment]
I wrote the above based on reading the VictoriaMetrics documentation... but then I looked at the code, and it turns out vmagent already supports `api/v2/write`. This is not mentioned anywhere in https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html

Please convert this issue into a docs bug.

**Comment by zekker6** [comment]
Hello @maxb !

There is now new section in doc which describes InfluxDB v2 API compatibility - https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-send-data-in-influxdb-v2-format

Is this something that would help you in your case?

**Comment by maxb** [comment]
Thanks, I think that is sufficient.
