### ISSUE TITLE
Support for legacy DataDog agent was incorrectly copy/pasted from vminsert to vmagent

### ISSUE THREAD

**Issue by maxb** [VictoriaMetrics/VictoriaMetrics#5078]
### Describe the bug

Whilst reading the code, I spotted a conditional that will always evaluate to false:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/af5379933210fc09311ea74f234c44732d81c0a3/app/vmagent/main.go#L254-L258

This is testing an URL-path, which necessarily always starts with a slash - so it can never have the prefix `datadog/`.

Digging in to the Git history, the relevant check was originally introduced in vminsert in #2670 - and there, it is correct.

However, in immediate follow-up commit 638ba4614acdc8a67bb60c96cacf3f6b024f3b7e (whose message implies it was just a changelog update, but it wasn't) the code was copy/pasted to vmagent, but a critical leading slash was dropped from the copied version.

### To Reproduce

This is an issue I just noticed reading the code, but you could test it by seeing what happens with an HTTP request to `/datadog/api/v1/series/` on a vmagent.

### Version

Git master at time of writing

**Comment by dmitryk-dk** [comment]
Hi @maxb ! What version of the datadog agent do you use? Can you share the log what you see when running agent?

**Comment by dmitryk-dk** [comment]
I have checked datadog requests, and all API has the prefix `datadog/`, for example
`"/datadog/api/v1/series"`
`"/datadog/api/v1/validate"`
`"/datadog/api/v1/check_run"`
So when you make curl or use datadog you shouldn't see any errors.

If it is possible can you share the error log?

**Comment by maxb** [comment]
As I said, this is not an error I experienced at run-time - but a bug I noticed when reading the code. I do not use datadog agent. I have no logs. But I can see that the code is incorrect, as when processing an URL-path that always starts with `/`, a test for a prefix of `datadog/` will always return false, because it does **not** start with a `/`.

**Comment by valyala** [comment]
@maxb , thanks for the bugreport! The issue should be fixed in the commit 34961dd4b8636064187d746dc1b924e6ab0acf86 , which will be included in the next release.

**Comment by maxb** [comment]
The fix referenced above has fixed one instance of the incorrect code, but there is a second copy/paste of the same further down in the same file, that also needs the same fix.

**Comment by valyala** [comment]
> The fix referenced above has fixed one instance of the incorrect code, but there is a second copy/paste of the same further down in the same file, that also needs the same fix.

The [second one instance of the code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f13a96f42c9b6ac87ed04f620a880a1c74425fc3/app/vmagent/main.go#L458) doesn't need this fix, since `p.Suffix` doesn't start from `/`.

The bugfix has been included in [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.

**Comment by valyala** [comment]
FYI, the bugfix has been included also in [v1.87.10](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.10).

**Comment by valyala** [comment]
FYI, the bugfix has been back-ported to [v1.93.6 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.6).
