### ISSUE TITLE
Ability for Victorialogs to perform aggregation queries on specific log entry fields

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5079]
### Is your feature request related to a problem? Please describe

Feature request for Victorialogs

### Describe the solution you'd like

In Elasticsearch, it's possible to run [aggregation queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html) on specified fields.  This type of feature is important where users want to calculate statistics such as the sum/min/max/mean/stddev of a specific field over all documents in the index.   

For example, given an index that stores documents such as this one:
```json
{
  "app": "payment_processor",
  "data": {
     "payment_amount": 72.00,
    "total_items": 2,
    "currency": "USD",
    "processing_time_ms": 2100
  },
  "description": "transaction description here"
}
```

One might want to calculate the mean value of `data.payment_amount` as well as the max value of `data.processing_time_ms` of all requests over the period of the last 30 days.   They might also want to obtain distinct count ([cardinality aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html) in Elasticsearch) of all the possible values in the `data.currency` field.

**Comment by valyala** [comment]
VictoriaLogs supports calculating various stats starting from [v0.6.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). See [these docs](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe). For example, the following query calculates the average of `data.payment_amount` field and the max of the `data.processing_time_ms` field across logs for the last 30 days:

```logsql
_time:30d | stats
  avg(data.payment_amount),
  max(data.processing_time_ms)
```

Closing the feature request as done.
