### ISSUE TITLE
vmagent: promscrape.config check only mode

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#508]
We using `promtool check config` to validate prometheus config by its commit hook. Due to the fact that vmagent do not support 100% of prometheus config options (#503), this check will not be representative for vmagent promscrape configuration file.

My suggestion is to add to vmagent config check mode: just check config file for errors, and terminate immediately with corresponding exit code: 0 if no errors, any other - if there are errors.

**Comment by valyala** [comment]
Currently `vmagent` supports `-promscrape.config.strictParse` option, which returns errors if it sees unsupported options in the config. What about adding `-promscrape.config.dryRun` option for config check only mode?

This looks like a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/362 .

**Comment by valyala** [comment]
Closing this feature request as a duplicate for #362 .

**Comment by valyala** [comment]
FYI, `vmagent` includes `-dryRun` option starting from the [v1.35.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) release.

**Comment by wf1nder** [comment]
Thank you!
