### ISSUE TITLE
Improve JSON import/export documentation

### ISSUE THREAD

**Issue by yatskevich** [VictoriaMetrics/VictoriaMetrics#5083]
### Is your feature request related to a problem? Please describe

From a user perspective it was not obvious what is the JSON format for importing data.

[How to import data in JSON line format](https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format) refers to an example from [How to export data in JSON line format](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format), but it's not clear enough that you need to follow the link in
> Example for importing data obtained via [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format):

### Describe the solution you'd like

It would be great to list json format explicitly in the import section or reword the docs to clearly state the JSON Line format and explicitly give a link to it.

**Comment by hagen1778** [comment]
@yatskevich @Amper please see update here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/612ec2df6be45ab6f410fff9bed42a70f8b146e2

**Comment by yatskevich** [comment]
@hagen1778 thank you for the update!

**Comment by valyala** [comment]
@yatskevich , please see an additional update at 2dd9b69101402d0929db4a7fe8df1b214b0e379f . It creates a dedicated chapter for [JSON line format](https://docs.victoriametrics.com/#json-line-format), which can be used for direct linking.

Closing the feature request as done.
