### ISSUE TITLE
Ability to accept logs via syslog protocol in Victorialogs

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5089]
### Describe the solution you'd like

Network devices (including routers, switches, etc) typically have the ability to output logs directly to a destination via syslog protocol.   Having Victorialogs expose a listener to allow for this would be greatly beneficial in allowing network management teams to start centralizing logs with very little work and effort.

**Comment by zekker6** [comment]
Hello @hartfordfive 

There is an existing feature request for this here - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4619

I'll close this issue to remove duplicate, please follow the issue mentioned above to get updates about this.
