### ISSUE TITLE
Support Datadog sketches API

### ISSUE THREAD

**Issue by AndrewChubatiuk** [VictoriaMetrics/VictoriaMetrics#5093]
### Is your feature request related to a problem? Please describe

Our team uses AWS Lambda a lot and we're using Datadog with their extension for monitoring. Though it's convenient, it's expensive

### Describe the solution you'd like

Would like to add support of undocumented yet /api/beta/sketches API to be able to use Datadog extension together with Victoria Metrics

**Comment by valyala** [comment]
This is a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3091
