### ISSUE TITLE
vmui: time interval retention from Top Queries

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/VictoriaMetrics#5097]
### Is your feature request related to a problem? Please describe

On the `Top Queries` page, there is an option to execute a selected query. When a user selects a query for execution and navigates to the `Query` page, the specified time interval is not carried over.

### Describe the solution you'd like

It would be very useful if the specified `query time interval` from the `Top Queries` table was considered when executing the selected query.

**Comment by valyala** [comment]
This feature has been implemented in [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request then.
