### ISSUE TITLE
Not human readable order in VM documentation menu

### ISSUE THREAD

**Issue by samaelua** [VictoriaMetrics/VictoriaMetrics#5108]
### Describe the bug

![Screenshot 2023-10-02 at 18-44-27 VictoriaMetrics · The High Performance Open Source Time Series Database   Monitoring Solution](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/102154089/5fa11878-7ba3-4749-aadd-7b9c7cd915b1)
There is cunfused order for CHANGELOGs at VM documentation menu. IMHO the correct order should start from 2020 and end with the latest one from 2023. I've made a PR  https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5107 to fix this issue. Please take a look.

### To Reproduce

Open https://docs.victoriametrics.com/ and check a menu on the left side.

### Version

master branch

**Comment by hagen1778** [comment]
Hello @samaelua!

> There is cunfused order for CHANGELOGs at VM documentation menu. IMHO the correct order should start from 2020 and end with the latest one from 2023. I've made a PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5107 to fix this issue. Please take a look.

I do not agree wit this. The order should be descending, as it shows the most recent changes first. I consider this as a common practice for other software vendors too. For example, check https://clickhouse.com/docs/category/changelog
