### ISSUE TITLE
Lag in vmagent

### ISSUE THREAD

**Issue by ctunr2022** [VictoriaMetrics/VictoriaMetrics#5115]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I am running vmagent on kubernetes having almost 70+ pods running. When i started the vmagent it was doing its job as expected but later on after 1 hour i saw some lags as per `vmagent_remotewrite_pending_data_bytes` metric. And this lag keeps on increasing. Even `vmagent_remotewrite_errors_total` & `vmagent_remotewrite_conn_write_errors_total` are 0.  I'm using v1.91.3 version.

I'm not sure what is wrong here.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hi @ctunr2022!
Could you please share screenshots/snapshots of vmagent's Grafana dashboard?

**Comment by ctunr2022** [comment]
Hey @hagen1778 I'm not using Grafana dashboard, instead i'm pushing it to different application which is ultimately indexing into opensearch. I will show you the metrics.
