### ISSUE TITLE
lib/backup: support permanent deletion of objects with versioning enabled

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5121]
### Is your feature request related to a problem? Please describe

Some implementations of ObjectStorages (like S3) support [versioning](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html) of stored objects. That means that one object could have multiple different versions. Each change to the object, like delete operation, creates a new version of this object, while the previous version remains to exist. Until evicted by lifecycle policy.

For vmbackup/vmbackupmanager it would mean that DELETE calls to objects in S3 only mark them for deletion. Such objects remain in S3 and occupy the disk space. 

### Describe the solution you'd like

If it is supported by specific ObjectStorage SDK, would be great if vmbackup/vmbackupmanager could permanently delete the object even if versioning is enabled. This behavior should be disabled by default, as objects versioning was created specifically to prevent permanent data loss and it is up to system administrator to decide on lifecycle policy or whether vmbackup should permanently delete backups.

### Describe alternatives you've considered

Configure lifecycle policy for removing outdated versions of the objects.

**Comment by valyala** [comment]
The `-deleteAllObjectVersions` command-line flag is available in [vmbackup](https://docs.victoriametrics.com/vmbackup.html) starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
