### ISSUE TITLE
vmbackup: Full backup broken in 1.94.0

### ISSUE THREAD

**Issue by a26nine** [VictoriaMetrics/VictoriaMetrics#5144]
### Describe the bug

When trying to create a full backup on a custom S3 endpoint with the command:
```
/vmbackup-prod \
        -storageDataPath="/storage" \
        -snapshot.createURL="http://localhost:8482/snapshot/create" \
        -customS3Endpoint="${AWS_ENDPOINT}" \
        -dst="${DIR}/${current_date}" \
        -origin="${DIR}/latest"
```

It fails with
```
cannot perform server-side copying from fslocal "/storage/snapshots/20231008000034-178B1F56CAB19C04" to S3{bucket: "xxx", dir: "xxx/"}: both of them must be S3
```

The incremental backup — without `origin` — still works fine.

This was not an issue till `v1.93.5`. It seems `v1.94.0` added server-side copying feature for `vmbackup` which has identical tags to the full backup:
```
FEATURE: vmbackup: add support for server-side copy of existing backups. See these docs for details.
```

### To Reproduce

Run `vmbackup` with:
```
/vmbackup-prod \
        -storageDataPath="/storage" \
        -snapshot.createURL="http://localhost:8482/snapshot/create" \
        -customS3Endpoint="${AWS_ENDPOINT}" \
        -dst="${DIR}/${current_date}" \
        -origin="${DIR}/latest"
```

### Version

vmbackup-20231002-215223-tags-v1.94.0-0-gf13a96f42

### Logs

2023-10-08T00:00:36.083Z	fatal	VictoriaMetrics/app/vmbackup/main.go:102	cannot create backup: cannot server-side copy origin parts to dst: cannot copy part{path: "indexdb/178471C64B26973E/178B1F56D66133DE/items.bin", file_size: 3608768, offset: 0, size: 3608768} from fslocal "/storage/snapshots/20231008000034-178B1F56CAB19C04" to S3{bucket: ..231008/"}: cannot perform server-side copying from fslocal "/storage/snapshots/20231008000034-178B1F56CAB19C04" to S3{bucket: "monitoring-victoriametrics-dev", dir: "vmstorage/victoria-metrics-cluster-vmstorage-2/20231008/"}: both of them must be S3

**Comment by a26nine** [comment]
It works fine after reverting to `v1.93.5`.

**Comment by Amper** [comment]
Hey, @a26nine.
What format/prefix of `${DIR}` for `-dst` and `-origin` do you use in you cases?
I've only managed to reproduce this error if I use `fs://` for `-origin` and `s3://` for `-dst`. But that doesn't seem like a valid scenario.

**Comment by a26nine** [comment]
> Hey, @a26nine. What format/prefix of `${DIR}` for `-dst` and `-origin` do you use in you cases? I've only managed to reproduce this error if I use `fs://` for `-origin` and `s3://` for `-dst`. But that doesn't seem like a valid scenario.

No, I am using `s3` for both. Here's the full command:
```
/vmbackup-prod \
        -storageDataPath="/storage" \
        -snapshot.createURL="http://localhost:8482/snapshot/create" \
        -customS3Endpoint="https://xxx.com/" \
        -dst="s3://monitoring-victoriametrics-prod/vmstorage/${POD_NAME}/${current_date}" \
        -origin="s3://monitoring-victoriametrics-prod/vmstorage/${POD_NAME}/latest"
```

**Comment by Amper** [comment]
It's weird.
I haven't been able to reproduce the problem yet - it works fine for me:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/31a4188b-0871-4e86-bda1-26afba1f280b)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/d6054701-0b76-48c0-bf7c-8d304174ee07)

I'll try to understand from the code how this can happen.

**Comment by valyala** [comment]
@Amper , the provided screenshot contains the following log line: `server-side copied 0 bytes`. This means that the provided `-origin` didn't contain any files from the source snapshot at `-storageDataPath`. You need to upload a backup to some s3 folder, then write additional data to VictoriaMetrics and then to make a new backup to another s3 folder, while specifying the previous s3 folder in the `-origin` command-line flag. In this case `vmbackup` should notice that there are common files in the local snapshot and in the `-origin` backup, so it should perform server-side copy for these files from the `-origin` to `-dst` instead of re-uploading them from the local snapshot to `-dst`.

**Comment by valyala** [comment]
@a26nine , could you build `vmbackup` from the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b248413a078a456bed9689e35898e90071f86ce8 according to [these docs](https://docs.victoriametrics.com/vmbackup.html#how-to-build-from-sources) and verify whether it properly makes backups when the `-origin` command-line flag is set?

**Comment by a26nine** [comment]
> @a26nine , could you build `vmbackup` from the commit [b248413](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b248413a078a456bed9689e35898e90071f86ce8) according to [these docs](https://docs.victoriametrics.com/vmbackup.html#how-to-build-from-sources) and verify whether it properly makes backups when the `-origin` command-line flag is set?

That would be difficult for me as I have my setup in k8s. For this, I will have to build a custom Docker image.

**Comment by valyala** [comment]
FYI, [vmbackup](https://docs.victoriametrics.com/vmbackup.html) should properly make backups when the `-origin` command-line flag is set, starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.

**Comment by a26nine** [comment]
> FYI, [vmbackup](https://docs.victoriametrics.com/vmbackup.html) should properly make backups when the `-origin` command-line flag is set, starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.

Thanks, @valyala!
