### ISSUE TITLE
 Is there any strategy when the vminsert node selects the vmstorage node?

### ISSUE THREAD

**Issue by tianshimoyi** [VictoriaMetrics/VictoriaMetrics#5146]
### Is your question request related to a specific component?

vminsert vmstorage

### Describe the question in detail

The current cluster contains 5 vmstorage nodes, and the vminsert replicationFactor parameter is configured as 2. When the vminsert node selects the vmstorage node, will the cpu, memory, and disk/Io of the storage node be considered?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @tianshimoyi. 

> When the vminsert node selects the vmstorage node, will the cpu, memory, and disk/Io of the storage node be considered?

No, all nodes are assumed to be equal

**Comment by tianshimoyi** [comment]
@Amper Thank you very much for your help. I also want to ask a question. Where is the storageNode parameter loaded in the code? I searched the entire project and did not find this parameter. Can you tell me? Thank you very much.

**Comment by Amper** [comment]
@tianshimoyi, i guess you didn't find it, because you used wrong branch. 
Source code for cluster version of VM is in branch `cluster`: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a41c2aeafba56356c46902a0e480b115c0ced8a7/app/vminsert/main.go#L117

**Comment by tianshimoyi** [comment]
@Amper Thank you very much for your help.
