### ISSUE TITLE
Add labels_equal(q, label1, label2, ...) function

### ISSUE THREAD

**Issue by itssvet** [VictoriaMetrics/VictoriaMetrics#5148]
### Is your feature request related to a problem? Please describe

Sometimes I need to compare labels between themselves, not as any certain values. The purpose of my task is to find any redundancy in my labels, to clean up them, or just to optimize my dashboard set to remove duplicates that use different labels with the same values.

### Describe the solution you'd like

Please add a new label manipulation function `labels_equal(q, label1, label2, ...)` to return only those rows from q that have the equal label1 and label2

### Describe alternatives you've considered

Aliaksandr Valialkin [advised me](https://t.me/VictoriaMetrics_ru1/51458) the following temp solution: `q and on(host) label_copy(q, "http_host", "host")`, but implementing this would be better :)

**Comment by valyala** [comment]
@itssvet , thanks for filing this feature request! The [labels_equal(q, "label1", "label2", ...)](https://docs.victoriametrics.com/MetricsQL.html#labels_equal) function has been implemented in the commit da77f4deeb40c5526ced54dcdcb041bc0630ba9c , which will be included in the next release of VictoriaMetrics.

In the mean time it is possible to test this function by running VictoriaMetrics built from this commit according to the following instructions:

- [How to build single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-build-from-sources). It must be built from the commit da77f4deeb40c5526ced54dcdcb041bc0630ba9c
- [How to build VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources). It must be built from the commit 627a4e93308f8a6f8e1d60bccf1ad417e6d26cd1

**Comment by valyala** [comment]
The [labels_equal](https://docs.victoriametrics.com/MetricsQL.html#labels_equal) function is available in VictoriaMetrics since the release [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as fixed.
