### ISSUE TITLE
High CPU usage observed with VictoriaMetrics storage

### ISSUE THREAD

**Issue by qiu-peng20** [VictoriaMetrics/VictoriaMetrics#5149]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Problem Description :
Hello, I've been observing unusually high CPU usage with my VictoriaMetrics storage instance. I would appreciate any insights or advice on this matter.

environment:
VictoriaMetrics version:  v1.75.0-cluster
Deployment method:  Kubernetes 
OS: Linux
CPU/Memory:  8 CPU cores and 16G memory

Phenomenon:
1、Noticed that github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*inmemoryBlock).UnmarshalData function has significant accumulated time, indicating that a lot of CPU time is spent reading and decompressing data.
      ![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/e49455a3-d5b5-4954-930d-e17b34ba6632)  
      
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/412a19c4-fa80-40a7-b9bd-62c78829fbca)
     

2、Write metrics vm_vminsert_metrics_read_total is around 160K.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/71b32b44-e1dd-4555-bfb8-fe74ab5c43cc)

3、The rate for vm_rows_merged_total showed the following:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/10d40f91-2c0a-4e75-9aa5-aab9c0b53fd8)

Solutions to try:
I've considered expanding the storage and also reducing the metrics insertion rate as potential solutions.

Further information:
I used the following query to fetch pending datapoints and found:
sum(max_over_time(vm_pending_rows{job=~"$job_storage", instance=~"$instance", type="storage"}[$__rate_interval]))
Results:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/17ab553f-84a7-4b5d-a3c6-2967ae34cb6e)

storage hard drive：2000GiB SSD

From the pprof data, these functions showed significant CPU consumption:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/074e4f3a-f27a-4672-b532-9b3d5b5f3023)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/19a3e7d2-539b-4457-8e48-1e66628fc047)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55682965/2130ee81-3850-4dcd-a596-a0fd41c1b980)

     
question:
1、Is this CPU consumption expected for the given metrics rate and storage size?
2、What could be causing this behavior, and how can I optimize it?
3、Would increasing the MaxConcurrentInserts help in this scenario? If so, is it for storage or insert?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @qiu-peng20!

> 1、Is this CPU consumption expected for the given metrics rate and storage size?

Can't say - none of the provided screenshots or stats show the actual CPU usage :)

> 2、What could be causing this behavior, and how can I optimize it?

According to the pprof you attached, reading data from the disk and decompressing it is caused by read queries. Check partSearch.Seek function for references.

> 3、Would increasing the MaxConcurrentInserts help in this scenario? If so, is it for storage or insert?

I don't think so. I believe most of the load is caused by read queries, not ingestion.

**Comment by hagen1778** [comment]
@qiu-peng20 is first graph shows CPU seconds? I'm confused as Y axis shows GB units...

> Is this because my cache setting size is not enough, or because too much data is written?

The Troubleshooting section in Grafana dash should suggest if it is enough of memory. Please use these docs https://docs.victoriametrics.com/Troubleshooting.html#slow-data-ingestion and this dash https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?orgId=1 as a reference.

Please verify that you have low ratio of slow inserts, that your memory usage is <90%, and connection saturation between vminsert and vmstorage is < 80%.

I'd also recommend following https://docs.victoriametrics.com/Troubleshooting.html#general-troubleshooting-checklist

**Comment by jiekun** [comment]
Close as answered.
