### ISSUE TITLE
Improve detection slow/unhealthy vmstorage

### ISSUE THREAD

**Issue by PavelKolobaev** [VictoriaMetrics/VictoriaMetrics#515]
**Problem**
Improve detection slow/unhealthy vmstorage

Example:
I have 2 node vmstorge. vmselect  run with options
```
 --storageNode=10.203.32.6:8401 --storageNode=10.203.32.8:8401 --selectNode=10.203.32.6:8481 --selectNode=10.203.32.8:8481
```
I shutdown one of two vmstorge node and send some request to vmselect. vmselect received a response from first node at 0,1s (example), but the second node is shutdown. vmselect will resend requests for 30 secons (by default) and took nothing. 

**Proposal**
will add some check to vmselect which will allow vmselect send request to problem node or not.
Example:
average vmstorage  query duration last 30 second equal 27 second
vmstorage did not  respond ot the last three checks
If vmstorage check failed, vmselect do not send requests to it.

After normalize vmselect status, vmselect unmark badly status vmstatus and send request to it again

**Comment by valyala** [comment]
This issue should be addressed by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4423 . This pull request adds `-vmstorageUserTimeout` command-line flag for `vmselect`, which can be used for tuning the wait time before `vmselect` detects unavailable `vmstorage` node. By default `vmselect` waits for up to 3 seconds before deciding that the `vmstorage` node is unavailable. This pull request has been included in [v1.94.0](https://docs.victoriametrics.com/CHANGELOG.html).

See also https://github.com/VictoriaMetrics/VictoriaMetrics/issues/711 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3378 .

Closing the feature request as done.
