### ISSUE TITLE
Does the metricql statement have a length limit? If so, is there a parameter to set this length?

### ISSUE THREAD

**Issue by groobyming** [VictoriaMetrics/VictoriaMetrics#5150]
### Describe the question in detail

Does the metricql statement have a length limit? If so, is there a parameter to set this length?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @groobyming! 
Yes, you can control it via the following cmd-line flag:
>   -search.maxQueryLen size
     The maximum search query length in bytes
     Supports the following optional suffixes for size values: KB, MB, GB, TB, KiB, MiB, GiB, TiB (default 16384)
