### ISSUE TITLE
vmalert: add `evaluationDelay` for rule evaluation

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#5155]
### Is your feature request related to a problem? Please describe

When vmalert evaluates group rules, there are three ways to modify the timestamp of raw series queried from database:
1. set `-search.latencyOffset` on vmselect;
2. set `-datasource.lookback` on vmalert;
3. add `latency_offset` in group's params, which will be attached to group's evaluation query requests and override `-search.latencyOffset` if there is.

All of them can be used to solve [data delay](https://docs.victoriametrics.com/vmalert.html#data-delay) problem and will generate [ALERTS/ALERTS_FOR_STATE](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#time-series-to-create) with timestamp `T` using actual raw series from timestamp `T-search.latencyOffset` or `T-datasource.lookback`. 
_Notice if multiple options are set, only the biggest one will work, so normally there is no need to set `datasource.lookback` if `search.latencyOffset` is there since `search.latencyOffset` will modify all the query requests to vmcluster._

But since they won't effect the timestamp in alertmanager notifications and  ALERTS/ALERTS_FOR_STATE metrics, there can be some confusion when users try to retrospect their alerts.
For example, if vmselect has flag`search.latencyOffset=30s`, and there is a rule
```
alert: test
expr: cpu_usage>0.8
for: 0s
``` 
and cpu usage exceed 80% at `T`.
VMAlert will detect this at `T+30s` at least(_**It's allowed when there are query delay since data need to be uploaded by vmagent to vmcluster**_) or `T+30s+other minor factors like evalAlignment/randSleep`. And ALERTS/ALERTS_FOR_STATE will be generated with timestamp `T+30s`. So if you query `ALERTS` and the raw `cpu_usage>0.8`, you will see a gap of 30s.
The same goes for recording rules.

### Describe the solution you'd like

Add `evaluationDelay` flag for VMALERT and for each rule Group, they will fix the timestamp in alertmanager notifications and  ALERTS/ALERTS_FOR_STATE metrics, using `T-datasource.lookback` instead of `T`.

ps. Mimir [implemented](https://github.com/grafana/mimir/pull/1474) this on their prometheus's rule group and have a default [RulerEvaluationDelay](https://github.com/grafana/mimir/blob/c28e59f42a9db144e8442889defb7ffc52a0523a/pkg/util/validation/limits.go#L143C2-L143C39) for 1m.

**Comment by hagen1778** [comment]
The issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c9375cac5e7bc612259e0101b50b4861115cc030 and will be likely included to the next release.

**Comment by valyala** [comment]
`vmalert` gains support for `eval_delay` option at [group level](https://docs.victoriametrics.com/vmalert.html#groups) since [v1.95.0 release](https://docs.victoriametrics.com/CHANGELOG.html). It also supports `-rule.evalDelay` command-line flag.

Closing the feature request as done then.

**Comment by Haleygo** [comment]
To sum up, we found `-datasource.lookback` is not necessary since vm datasource already has `-search.latencyOffset(default 30s)`, which eliminates the risk of getting incomplete data when querying.
Also, `-datasource.lookback` has bad effects on [ALERTS/ALERTS_FOR_STATE's](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#time-series-to-create) timestamps. And `-rule.evalDelay` added in this issue will correct this.

As exampled in description 
>For example, if vmselect has flagsearch.latencyOffset=30s, and there is a rule
alert: test
expr: cpu_usage>0.8
for: 0s
and cpu usage exceed 80% at T.
VMAlert will detect this at T+30s at least(It's allowed when there are query delay since data need to be uploaded by vmagent to vmcluster) or T+30s+other minor factors like evalAlignment/randSleep. And ALERTS/ALERTS_FOR_STATE will be generated with timestamp T+30s. So if you query ALERTS and the raw cpu_usage>0.8, you will see a gap of 30s.
The same goes for recording rules.

Now, vmalert still detect the firing alert at `T+30s`(caused by default -search.latencyOffset in datasource like vmselect), but the timestamp of ALERTS/ALERTS_FOR_STATE will be `T+30s(default -search.latencyOffset)-30s(default -rule.evalDelay) = T`.

If there is rules using metrics that uploading way slower than others, you can add `latency_offset` under [group's](https://docs.victoriametrics.com/vmalert/#groups) `params` which overrides datasource `-search.latencyOffset`, and in this case, you need also specify `eval_delay` equal to `latency_offset` under [group's](https://docs.victoriametrics.com/vmalert/#groups).

**Comment by valyala** [comment]
FYI, the `-datasource.lookback` command-line flag at [vmalert](https://docs.victoriametrics.com/vmalert/) becomes no-op starting from [v1.100.0](https://docs.victoriametrics.com/changelog/). The [`eval_delay` option](https://docs.victoriametrics.com/vmalert/#groups) must be used instead.
