### ISSUE TITLE
VMUI logo link when using pathPrefix

### ISSUE THREAD

**Issue by krakazyabra** [VictoriaMetrics/VictoriaMetrics#5156]
### Describe the bug

when using `http.pathPrefix` command-line flag home link in VMUI logo supposed to equal the argument.

### To Reproduce

run single/cluster version with `http.pathPrefix` option. go to vmui and check link in logo (header):
```
extraArgs: {
  'http.pathPrefix': '/vmsingle'
}
```

in vmui:
```
<a href="/" class="navbar-brand d-flex align-items-center ms-3" title="The High Performance Open Source Time Series Database &amp; Monitoring Solution ">
...
</a>
```

### Version

v1.94.0

### Used command-line flags

`http.pathPrefix`

### Additional information

Probably connected with https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/htmlcomponents/components.qtpl#L14

**Comment by Loori-R** [comment]
@hagen1778, This isn't related to `vmui`. The portion in question is part of `htmlcomponents`, and you can find it in `lib/htmlcomponents/components.qtpl`. Should I tackle this issue?

**Comment by valyala** [comment]
Closing as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5306
