### ISSUE TITLE
Decimal type support?

### ISSUE THREAD

**Issue by sezaru** [VictoriaMetrics/VictoriaMetrics#516]
Do VictoriaMetrics support decimal types to store data without losing precision?

**Is your feature request related to a problem? Please describe.**
I'm trying to evaluate if VictoricMetrics is a good solution to store direct OHLCV and trade data without data precision loss for the financial system I'm developing.

Currently I'm using TimescaleDB for that, which supports decimal type (since Postgres supports it too already).

**Describe alternatives you've considered**
One workaround I already tried was to convert the values to integers, but since the precision I need is very big, The resulted integer easily overflows the int64 type.

Another workaround is to store it as a string and then convert it back to a decimal when I retrieve it. I guess this would work (to be clear I didn't find any info if VictoriaMetrics supports strings too), but it would limit the usage a lot since no internal function would understand the string as a number, (this is not a deal-breaker since I don't have use for then for now, I only want to store and retrieve the data faster).

**Comment by valyala** [comment]
VictoriaMetrics stores all the values as [float64](https://en.m.wikipedia.org/wiki/Double-precision_floating-point_format) numbers. It doesn't support decimal or string types.

Could you share more details on the use case where int64 precision isn't enough for decimal values? Which scale and precision do you use for decimal type declaration in TimescaleDB in this case?

**Comment by sezaru** [comment]
Sure thing, for my system I need to have decimal with 28 precision.
So, for example, if I have this decimal number: 
-1234567890.123456789012345679
I can convert it into a bigint keeping the 28 precision, which results in this number:
-123456789012345678901234567900000000000
Since I know the precision is always 28, I can easily convert this number back to the original decimal number.

The issue is that this number is way bigger than what int64 can store, giving me this error in go: 
`constant -123456789012345678901234567900000000000 overflows int64`

<details>
  <summary>More info</summary>
  
  Just for completeness, I will post the code I use to convert from decimal to number and vice-versa, I'm not sure if this would help to understand what I'm trying to do since it's not written in Go (it's written in Elixir):

```elixir
defmodule Numeric do
  def from_decimal(%Decimal{sign: sign, coef: coef, exp: exp}, precision \\ 28) do
    string_coef = Integer.to_string(coef)

    div = String.length(string_coef) + exp

    new_string_coef =
      string_coef |> add_zeros(precision, div) |> String.to_integer() |> add_sign(sign)
  end

  def to_decimal(coef, precision \\ 28)

  def to_decimal(coef, precision) when coef >= 0,
    do: Decimal.new(1, coef, -precision) |> Decimal.reduce()

  def to_decimal(coef, precision), do: Decimal.new(-1, abs(coef), -precision) |> Decimal.reduce()

  defp add_zeros(coef, precision, div), do: String.pad_trailing(coef, precision + div, "0")

  defp add_sign(coef, -1), do: coef * -1
  defp add_sign(coef, 1), do: coef
end
```
  
</details>

**Comment by valyala** [comment]
@sezaru , thanks for the details! Probably your use case can afford lower number of significant decimal digits, since 28 digits looks like overkill for any practical purpose. 15 digits from float64 numbers is mostly enough even for [NASA's calculations](https://www.jpl.nasa.gov/edu/news/2016/3/16/how-many-decimals-of-pi-do-we-really-need/).

**Comment by denisgolius** [comment]
Closing this issue as resolved.
