### ISSUE TITLE
vmalert: `vmalert_alerting_rules_error` should be a counter

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5160]
### Is your feature request related to a problem? Please describe

vmalert exposes a gauge metric `vmalert_alerting_rules_error` which shows whether the current rule is failing or not. But it seems like a counter `vmalert_alerting_rules_error_total` would be more sufficient here, as it could show not only the state but also rate of failures. And also capture state changes between the scrapes, if any.

### Describe the solution you'd like

Would be great to convert gauge  `vmalert_alerting_rules_error` to counter `vmalert_alerting_rules_error_total`. The change will require not only changes to vmalert, but also to dashboards and recommended alerting rules.

**Comment by valyala** [comment]
`vmalert_alerting_rules_error` and `vmalert_recording_rules_error` [metrics](https://docs.victoriametrics.com/vmalert.html#monitoring) at vmalert are replaced with `vmalert_alerting_rules_errors_total` and `vmalert_recording_rules_errors_total` at the release [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing this feature request as done.
