### ISSUE TITLE
vmalert: `alertname` label attached to `vmalert_alerting_.*` metrics collides with alertmanager

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5161]
### Describe the bug

Mistakenly, vmalert uses `alertname` label to identify the name of alerting rule in metrics. But if someone wants to use these metrics for alerting rule checking vmalert's health, then `alertname` will collide with the same labelname generated for ALERTS and ALERTS_FOR_STATE time series, or notifications sent to Alertmanager.

### To Reproduce

I think it would make sense to change `alertname` label to just `name`. 
It would also make sense to change `recording` label name for recording rules to `name` as well, so both metric families will be consistent.

**Comment by artli** [comment]
To be more specific, one scenario where you would see a collision is:
1. A vmalert is executing some rule, say, `MyAlert`, and exposing metrics about it, e.g. `vmalert_alerting_rules_error{alertname="MyAlert", group="my_group", id="12345678"}=0`
2. Another vmalert (or even the same one) is monitoring this vmalert to make sure none of its rules have errors, e.g. using the `AlertingRulesError` rule from the official [alerting rule list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/alerts-vmalert.yml): `sum(vmalert_alerting_rules_error) by(job, instance, group) > 0`
3. If `MyAlert` experiences an error, `AlertingRulesError` fires and tries to copy all labels from the returned `vmalert_alerting_rules_error` time series and attach them to the alert, including the `alertname="MyAlert"` label.
4. However, the vmalert that is executing `AlertingRulesError` overrides that label and instead attaches `alertname="AlertingRulesError"` to the alert, obscuring the name of the original alerting rule that experienced an error.

As I understand, the suggestion is to change the label name in the metrics produced by vmalert to make them look something like `vmalert_alerting_rules_error{name="MyAlert", group="my_group", id="12345678"}=0` instead. Then `AlertingRulesError` will produce alerts that have both the `alertname="AlertingRulesError"` and `name="MyAlert"` labels in them, which might be slightly confusing but at least allows the user to trace the error back to the original alerting rule.

**Comment by Haleygo** [comment]
>But if someone wants to use these metrics for alerting rule checking vmalert's health, then alertname will collide with the same labelname generated for ALERTS and ALERTS_FOR_STATE time series, or notifications sent to Alertmanager.

@hagen1778 Under this situation, I don't see it as a bug in vmalert, but a rule with wrong expr.

As @artli said above, even if we change the default label from `alertname` to `name`, the results will have both `alertname` and `name` label which is not good as well.
How about we rewrite the `AlertingRulesError` [rule](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e16d3f5639d67ff970975d342aaa276e339e9b0c/deployment/docker/alerts-vmalert.yml#L20) here, using `label_replace` to change the origin `alertname` label to something like `origin_alertname`, I think it will make the result message more clear.

**Comment by hagen1778** [comment]
@Haleygo I agree. Let's keep it as is for the compatibility sake and fix only the alerting rule.

**Comment by valyala** [comment]
FYI, [the pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5398) has been included in [vmalert v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).
