### ISSUE TITLE
Read/Write performance

### ISSUE THREAD

**Issue by DatScript** [VictoriaMetrics/VictoriaMetrics#5163]
### Is your question request related to a specific component?

VictoriaMetrics, VMUI, write, query.

### Describe the question in detail

Hi,
I have 2 problem this this question:

1. _**Read/Write data**_
I do an example to write influx line protocol data to VictoriaMetrics continuously 1ms by C# (each protocol contains 1000 items).
- The execution time to write each data is 1~10ms.
- When I do a query by VMUI, the execution time to write data > 10ms.
As the image below, the time I captured is the time at I do a query.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/37483861/e7703d0d-ca69-4b13-bdad-6e66edf3206e)
The example can be found here: https://github.com/DatScript/Test-VictoriaMetrics
`How can I do a query to not affect to writing time?`

2. **_Query data_**
I want to check the update interval between two data points of Performance_Flux00001, to do so, I make a query to get all of data in 5 minutes then do some time subtraction to get interval. But I cannot get raw data of my inserted data, the query requires `step` parameter for some interpolation. My query is:
`http://[localhost:8428/api/v1/query_range?query=Performance_Flux00001&start=now-30s&step=1ms`
`How can I check the update interval between two data points?`

Thank you!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by DatScript** [comment]
Another problem is that the memory of VictoriaMetrics (monitored by Windows Task Manager) increase by time. Is it the limitation of VM in write data. Should I decrease Metrics number or write frequency? Is the any solution to increase Metrics?

**Comment by zekker6** [comment]
Hello @DatScript 

> How can I do a query to not affect to writing time?

It is not possible because the storage for data is the same for write and read paths, so using both at the same time will be limited by the amount of resources available on the host where VictoriaMetrics is running.

> I want to check the update interval between two data points of Performance_Flux00001, to do so, I make a query to get all of data in 5 minutes then do some time subtraction to get interval. But I cannot get raw data of my inserted data, the query requires step parameter for some interpolation. 


In order to get raw samples you need to use export [API endpoints](https://docs.victoriametrics.com/url-examples.html#apiv1export). Query range endpoint has interpolation based on the given step, you can find more details about this [here](https://docs.victoriametrics.com/keyConcepts.html#range-query).


> Another problem is that the memory of VictoriaMetrics (monitored by Windows Task Manager) increase by time. Is it the limitation of VM in write data. Should I decrease Metrics number or write frequency? Is the any solution to increase Metrics?

The only way to limit memory usage is to use the following flags:
```
 -memory.allowedPercent and -memory.allowedBytes limit the amounts of memory, which may be used for various internal caches at all the cluster components of VictoriaMetrics - vminsert, vmselect and vmstorage. Note that VictoriaMetrics components may use more memory, since these flags don't limit additional memory, which may be needed on a per-query basis.
```
But those flags only limit memory used for caches mainteined by VictoriaMetrics and not the total memory usage. If you need to run clear tests and isolate memory usage it is better to set up a test environment in containers / VMs and limit memory there.

**Comment by DatScript** [comment]
Thank you for your response @zekker6

1. **_Second problem (interval)_**

As my experiment, the execution time to write data < 10ms (most of execution time < 5ms) then start the next write after 1ms delay. So, average interval ~5ms.
From your response, I export the data into Json format.  The data value is not missing but the delay interval between two data points that ~15ms.

`Is it mean that the new data will be insert to queue (stored in physical memory) and VMs need some execution time (~10ms) to write data to hard drive?` I think this might leads to memory increase continuously.

`http://localhost:8428/api/v1/export?match[]=Performance_Flux00001&start=now-15m`
```
1697118305976,15
1697118305991,16
1697118306007,16
1697118306023,15
1697118306038,16
1697118306054,15
1697118306069,16
1697118306085,15
1697118306100,16
1697118306116,15
1697118306131,15
1697118306146,16
1697118306162,16
1697118306178,16
```

2. **_First problem (write/query)_**

`Is it possible to run cluster in the same server?` One task for insert and one task for query?

3. **_Third problem (memory increase)_**

I added `victoria-metrics-windows-amd64-prod.exe -memory.allowedBytes 200000000` to limit 200MB memory. 
Log: ` info    VictoriaMetrics/lib/memory/memory.go:46 limiting caches to 20000000 bytes, leaving 14851420928 bytes to the OS according to -memory.allowedBytes=20000000`
But the memory still increases > 300 MB. And it is still increase.
`Is there any solution for memory issue?`

Thank you so much!

**Comment by zekker6** [comment]
> Is it mean that the new data will be insert to queue (stored in physical memory) and VMs need some execution time (~10ms) to write data to hard drive? I think this might leads to memory increase continuously.

No, timestamp is assigned right after parsing the records.

> Is it possible to run cluster in the same server? One task for insert and one task for query?

It is possible, just not recommended for production use. Note that any case vmstorage component will be used by both read and write paths, so it each path will affect the other one.

>  Is there any solution for memory issue?

As I've mentioned, this flag does not limit the total memory usage. The only option to limit total memory usage is to limit amount of memory available to VictoriaMetrics by using containers/VMs.

**Comment by DatScript** [comment]
Thank you for your support, @zekker6
