### ISSUE TITLE
When using query_range query Rollup functions , are the meanings of lookbehind window conflicting?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5168]
### Is your question request related to a specific component?

vmselelt

### Describe the question in detail

the meanings of lookbehind window:

* Rollup functions (aka range functions or window functions) calculate rollups over raw samples on the given lookbehind window for the [selected time series](https://docs.victoriametrics.com/keyConcepts.html#filtering).
* The lookbehind window can be used as a lookback window when there is no time point near the query time, like this:
<img width="612" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/52991866/d4cb4de1-05a4-4c85-9625-50f67e3bed44">

For rate(node_cpu_seconds_total[30s]), what does  mean?

At this time [30s] has two meanings:
* the meaning of [30s] is to calculate the cpu increase rate per second. The calculation window is 30s. 
* when obtaining the data point of the cpu increase rate per second, if there is no time point near the query time, query the last 30s data points.

My question is when using query_range, when there is no time point near the query time, how far back will vm go to find the data points?

**Comment by zekker6** [comment]
@luzejia `query_range` endpoint can also fall back to the following logic if lookbehind window was not large enough to find the previous sample(described [here](https://docs.victoriametrics.com/keyConcepts.html#range-query)):

> Sometimes, the lookbehind window for locating the datapoint isn't big enough and the graph will contain a gap. For range queries, lookbehind window isn't equal to the step parameter. It is calculated as the median of the intervals between the first 20 raw samples in the requested time range. In this way, VictoriaMetrics automatically adjusts the lookbehind window to fill gaps and detect stale series at the same time.

**Comment by luzejia** [comment]
> @luzejia `query_range` endpoint can also fall back to the following logic if lookbehind window was not large enough to find the previous sample(described [here](https://docs.victoriametrics.com/keyConcepts.html#range-query)):
> 
> > Sometimes, the lookbehind window for locating the datapoint isn't big enough and the graph will contain a gap. For range queries, lookbehind window isn't equal to the step parameter. It is calculated as the median of the intervals between the first 20 raw samples in the requested time range. In this way, VictoriaMetrics automatically adjusts the lookbehind window to fill gaps and detect stale series at the same time.

For query_range:

* rate(node_cpu_seconds_total[30s])
* node_cpu_seconds_total[30s]

For the above two situations, which one of "[30s]" and "It is calculated as the median of the intervals between the first 20 raw samples in the requested time range" will the vm use as the rearview window?

**Comment by zekker6** [comment]
@luzejia This will be applied in both cases. This is because of [implicit query conversions](https://docs.victoriametrics.com/MetricsQL.html#implicit-query-conversions):

> All the [series selectors](https://docs.victoriametrics.com/keyConcepts.html#filtering), which aren't wrapped into [rollup functions](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions), are automatically wrapped into [default_rollup](https://docs.victoriametrics.com/MetricsQL.html#default_rollup) function. Examples:

    foo is transformed to default_rollup(foo[1i])
    foo + bar is transformed to default_rollup(foo[1i]) + default_rollup(bar[1i])
    count(up) is transformed to count(default_rollup(up[1i])), because [count](https://docs.victoriametrics.com/MetricsQL.html#count) isn't a [rollup function](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) - it is [aggregate function](https://docs.victoriametrics.com/MetricsQL.html#aggregate-functions)
    abs(temperature) is transformed to abs(default_rollup(temperature[1i])), because [abs](https://docs.victoriametrics.com/MetricsQL.html#abs) isn't a [rollup function](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) - it is [transform function](https://docs.victoriametrics.com/MetricsQL.html#transform-functions)


And during execution of rollup functions such as `default_rollup` or `rate` window can be increased to median of first 20 samples in order to ensure that there will be sample located withing the window.

**Comment by luzejia** [comment]
> @luzejia这将适用于两种情况。这是因为[隐式查询转换](https://docs.victoriametrics.com/MetricsQL.html#implicit-query-conversions)：
> 
> > 所有未包装到[rollup 函数中的](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions)[系列选择器](https://docs.victoriametrics.com/keyConcepts.html#filtering)都会自动包装到[default_rollup](https://docs.victoriametrics.com/MetricsQL.html#default_rollup)函数中。例子：[](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions)[](https://docs.victoriametrics.com/MetricsQL.html#default_rollup)
> 
> ```
> foo is transformed to default_rollup(foo[1i])
> foo + bar is transformed to default_rollup(foo[1i]) + default_rollup(bar[1i])
> count(up) is transformed to count(default_rollup(up[1i])), because [count](https://docs.victoriametrics.com/MetricsQL.html#count) isn't a [rollup function](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) - it is [aggregate function](https://docs.victoriametrics.com/MetricsQL.html#aggregate-functions)
> abs(temperature) is transformed to abs(default_rollup(temperature[1i])), because [abs](https://docs.victoriametrics.com/MetricsQL.html#abs) isn't a [rollup function](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions) - it is [transform function](https://docs.victoriametrics.com/MetricsQL.html#transform-functions)
> ```
> 
> 并且在执行汇总函数（例如`default_rollup`或窗口）期间`rate`，可以将窗口增加到前 20 个样本的中值，以确保样本位于窗口内。

thanks!
