### ISSUE TITLE
vmalert: GeneratorURL customisation

### ISSUE THREAD

**Issue by phnakarin** [VictoriaMetrics/VictoriaMetrics#517]
**Is your feature request related to a problem? Please describe.**

I'd love to see a built-in option in `vmalert` to be able to customise `GeneratorURL` that sent out to a notifier as an alert's source to another service. It would be helpful for a set up that doesn't want to expose vmalert's service to the world and can share the alerts without any workaround.

Currently, we can do `-external.url` but only a domain name is overwritten. The hardcore path to an alert's status is still there. (`/api/v1/groupID/alertID/status`)

**Describe the solution you'd like**

I don't know this would be good and flexible enough. Maybe a proper flag with an argument to overwrite the status URL and work well with `-external.url`. Also, the flag should be able to read the rules' expressions.

For example;

```
# To Prometheus
-external.url=https://prometheus.testdrive.com/
-external.alert.source="graph?g0.range_input=1h&g0.expr=\"{{$expr|quotesEscape|pathEscape}}\"&g0.tab=1"

# To Grafana Explore
-external.url=https://grafana.testdrive.com/
-external.alert.source="explore?orgId=1&left=[\"now-1h\",\"now\",\"VictoriaMetrics\",{\"expr\": \"{{$expr|quotesEscape|pathEscape}}\"},{\"mode\":\"Metrics\"},{\"ui\":[true,true,true,\"none\"]}]"
```

When clicking an alert's source on the Alert Manager and redirect to;

https://prometheus.testdrive.com/graph?g0.range_input=1h&g0.expr=sum%20by%20(app)%20(up%20%3D%3D%201)&g0.tab=1

https://grafana.testdrive.com/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22VictoriaMetrics%22,%7B%22expr%22:%22sum%20by%20(app)%20(up%3D%3D1)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

**Comment by tenmozes** [comment]
Hi @phnakarin for me idea looks interesting. The new property may be introduced `external.alert.template` where user can define own template with access to all template variables ($labels, $value, $expr) and send evaluated template to alermanager.

@hagen1778 what do you think?

**Comment by hagen1778** [comment]
Sounds good! What's the point of separating `-external.url` and `-external.alert.source`? Backward compatibility probably...

**Comment by tenmozes** [comment]
when user specifies external url (e.g. http://ops.domain.com/prometheus) logic adds correct suffix to it (/api/<groupid>/<alertid>/status) and generates the final url to vmalert API. 
so with new flag don't need to add custom logic and check is it url or template

**Comment by hagen1778** [comment]
Hi @phnakarin! New flag for external URL was added in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7ec6711f069bdfcb39126e520d3d4c77e426182d

You can verify it by [building](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert#how-to-build-from-sources) `vmalert` from sources. The change will be also included in next release.

**Comment by valyala** [comment]
FYI, the `-external.alert.source` command-line flag hass been added in [v1.37.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)

**Comment by hagen1778** [comment]
Closing issue as done. @phnakarin feel free to reopen if it is not working as expected.

**Comment by blakebarnett** [comment]
I'm trying to use this with grafana, and the URLs produced seem correct but grafana always throws out the expression. Has anyone had luck making this work? I've tried using pre-encoded special characters in place of [{}], etc. also but can't seem to make it work. I noticed in the code `quotesEscape` is `queryEscape` also, still didn't work.

```-external.alert.source="explore?orgId=1&left=[\"now-1h\",\"now\",\"VictoriaMetrics\",{\"expr\": \"{{$expr|quotesEscape|pathEscape}}\"},{\"mode\":\"Metrics\"},{\"ui\":[true,true,true,\"none\"]}]"```

**Comment by hagen1778** [comment]
Hi @blakebarnett! Could you pls provide the example of generated URL?

**Comment by blakebarnett** [comment]
Yeah, here's an example: `https://grafana.example.com/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22metrics%22,%7B%22expr%22:%22pg_replication_is_replica%7Bgcp_project%3D%27stage-123%27%2C+cluster%3D%27pgcluster0%27%2C+instance%3D~%27.%2Apgserver-replica.%2A%27%7D+%3C+1%0Aor+absent%28%7Bgcp_project%3D%27stage-123%27%2C+cluster%3D%27pgcluster0%27%2C+instance%3D~%27.%2Apgserver-replica.%2A%27%7D%29%0A%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D`

**Comment by blakebarnett** [comment]
This is what a working explore query looks like: `https://grafana.example.com/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22metrics%22,%7B%22expr%22:%22rate(http_request_total%5B5m%5D)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D`

**Comment by blakebarnett** [comment]
Ah I just noticed the line feeds in there `%0A`, removing those fixed it... I suppose `queryEscape` should do that?

**Comment by laixintao** [comment]
Hi, is it possible to set the `-external.alert.source` with `group_id` and `alert_id`?

I want the `GeneratorUrl` to be `/vmalert/alert?group_id=17290483213180221165&alert_id=7686873860857475156` instead of `/vmalert/api/v1/alert?group_id=&alert_id=`, web UI is better than json.

but if I run with `-external.alert.source="/vmalert/alert?group_id=&alert_id="`, the `group_id` and `alert_id` will not be filled.

**Comment by hagen1778** [comment]
@laixintao see related PRs https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2983 and https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2986

**Comment by laixintao** [comment]
Hi @hagen1778 it's very helpful, thank you very much!

I have another feature request regarding the alert templating, opened another issue with a detailed use case, what do you think about this? https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2999
