### ISSUE TITLE
streamaggr config reload bug

### ISSUE THREAD

**Issue by aluode99** [VictoriaMetrics/VictoriaMetrics#5170]
### Describe the bug

When streamAggr.config is initialized as empty, subsequent configurations cannot be loaded through hot loading
code is as follows:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/eb5cdb1d-f91c-489a-bf68-d58222ff79c2)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/528f997d-715c-411d-9021-5a1b05f33789)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/2876c765-f859-4ad3-9255-714617b3fb1f)

### To Reproduce

1. start vmagent with empty streamAggr.config 
2. add  some Match to streamAggr.config  and call reload

### Version

v1.94.0

**Comment by valyala** [comment]
FYI, the bugfix has been included in [VictoriaMetrics v1.93.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.6).

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5207

**Comment by valyala** [comment]
FYI, the bugfix for this issue has been included in [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html).
