### ISSUE TITLE
cannot parse WatchEvent json response: context canceled

### ISSUE THREAD

**Issue by kubeop** [VictoriaMetrics/VictoriaMetrics#5171]
### Describe the bug

Error reported every time the service is restarted

### To Reproduce

Every time the service is restarted

### Version

# ./vmagent-prod --version
vmagent-20230919-042301-tags-v1.93.5-0-g3efbb0af2b

### Logs

{"ts":"2023-10-13T06:50:06.655Z","level":"error","caller":"VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:775","msg":"error when reading WatchEvent stream from \"https://192.168.0.1:443/api/v1/namespaces/kube-system/services?watch=1&allowWatchBookmarks=true&timeoutSeconds=1620&resourceVersion=2403185\": cannot parse WatchEvent json response: context canceled"}
{"ts":"2023-10-13T06:50:06.655Z","level":"info","caller":"VictoriaMetrics/lib/promscrape/discovery/kubernetes/api_watcher.go:737","msg":"stopped service watcher for \"https://192.168.0.1:443/api/v1/namespaces/kube-system/services\""}

### Used command-line flags

            - --promscrape.config=/config/scrape.yml
            - --promscrape.configCheckInterval=30s
            - --promscrape.maxScrapeSize=20971520
            - --remoteWrite.url=https://vminsert.monitoring.svc.cluster.local:8480/insert/0/prometheus/
            - --remoteWrite.tmpDataPath=/tmpData
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json

**Comment by hagen1778** [comment]
Hello @kubeop! I think this is related to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5048, just fix wasn't correct - see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5048#discussion_r1361960905

From the mentioned PR description, the logged error doesn't affect service discovery. We just need to properly suppress this error.
cc @zekker6

**Comment by lujiajing1126** [comment]
We also suffered this error. And after service discovery is stopped, almost all target are removed.

**Comment by hagen1778** [comment]
@lujiajing1126 could you please try updating vmagent to [1.93.6](https://docs.victoriametrics.com/CHANGELOG.html#v1936)?
>BUGFIX: [vmagent](https://docs.victoriametrics.com/vmagent.html): suppress context canceled error messages in logs when vmagent is reloading service discovery config. This error could appear starting from [v1.93.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.5). See [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5048).

**Comment by lujiajing1126** [comment]
> @lujiajing1126 could you please try updating vmagent to [1.93.6](https://docs.victoriametrics.com/CHANGELOG.html#v1936)?
> 
> > BUGFIX: [vmagent](https://docs.victoriametrics.com/vmagent.html): suppress context canceled error messages in logs when vmagent is reloading service discovery config. This error could appear starting from [v1.93.5](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.5). See [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5048).

I'm currently using 1.93.6.

**Comment by lujiajing1126** [comment]
I've raised a PR to resolve expected service discovery shutdown issue #5196

**Comment by hagen1778** [comment]
@lujiajing1126 was it resolved for you after https://github.com/VictoriaMetrics/VictoriaMetrics/commit/632d788b63bcead6b1afa0ba8d4c2fe1a129ca92 ?

**Comment by lujiajing1126** [comment]
> @lujiajing1126 was it resolved for you after [632d788](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/632d788b63bcead6b1afa0ba8d4c2fe1a129ca92) ?

Yes. I've confirmed that

**Comment by hagen1778** [comment]
Closing this issue as fixed in v1.95.0.
