### ISSUE TITLE
vmalert: alert state can't be replayed correctly with rather big `for`

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#5186]
### Describe the bug

When replay alerting rules with a rather big `for`, it could exceeds the range of single query_range request which controlled by group interval and `maxDatapointsPerQuery`, since the alert states are not persisted, firing state will lose.
It could also happen when the firing stage is divided into two query ranges.

### To Reproduce

1. create an alerting rule with `interval: 1m ; for: 1d`, and have a must triggered expr like `1`;
2. set `maxDatapointsPerQuery=1000`
3. replay rule for 2 days

### Version

any version.

**Comment by valyala** [comment]
This issue has been fixed in [vmalert](https://docs.victoriametrics.com/vmalert.html) starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing it then.
