### ISSUE TITLE
What I can't explain about the step parameter in the query interface

### ISSUE THREAD

**Issue by iayamowner** [VictoriaMetrics/VictoriaMetrics#5187]
### Describe the bug

version: v1.91.0-cluster or v1.94.0-cluster
question: An accidental operation, when i use query instance with two different step parameters, different results are obtained.(later the url and some data was desensitized)

This returns the result normally:
```
# Req
http://xxx.xx.xxx.xx:8481/select/0/prometheus/api/v1/query?time=1697511600&query=vm_http_requests_total{instance="xxx.xx.xxx.xx:8482",path="/metrics"}&step=8s&nocache=1

# Resp
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": [
            {
                "metric": {
                    "__name__": "vm_http_requests_total",
                    "instance": "xxx.xx.xxx.xx:8482",
                    "job": "prometheus",
                    "path": "/metrics"
                },
                "value": [
                    1697511600,
                    "1841019"
                ]
            }
        ]
    },
    "stats": {
        "seriesFetched": "1"
    }
}
```

This one I don't think is returning normal results：
```
# Req
http://xxx.xx.xxx.xx:8481/select/0/prometheus/api/v1/query?time=1697511600&query=vm_http_requests_total{instance="xxx.xx.xxx.xx:8482",path="/metrics"}&step=9s&nocache=1

# Resp
{
    "status": "success",
    "isPartial": false,
    "data": {
        "resultType": "vector",
        "result": []
    },
    "stats": {
        "seriesFetched": "1"
    }
}
```

And this is the raw points:
```
# Req
http://xxx.xx.xxx.xx:8481/select/0/prometheus/api/v1/export?match[]=vm_http_requests_total{instance="xxx.xx.xxx.xx:8482",path="/metrics"}&start=1697511580&end=1697511630&max_rows_per_line=1&reduce_mem_usage=1

# Resp
{
    "metric": {
        "__name__": "vm_http_requests_total",
        "job": "prometheus",
        "instance": "xxx.xx.xxx.xx:8482",
        "path": "/metrics"
    },
    "values": [
        1841019,
        1841022
    ],
    "timestamps": [
        1697511585583,
        1697511600583
    ]
}
{
    "metric": {
        "__name__": "vm_http_requests_total",
        "job": "prometheus",
        "instance": "xxx.xx.xxx.xx:8482",
        "path": "/metrics"
    },
    "values": [
        1841019,
        1841022
    ],
    "timestamps": [
        1697511585583,
        1697511600583
    ]
}
{
    "metric": {
        "__name__": "vm_http_requests_total",
        "job": "prometheus",
        "instance": "xxx.xx.xxx.xx:8482",
        "path": "/metrics"
    },
    "values": [
        1841019,
        1841022
    ],
    "timestamps": [
        1697511585583,
        1697511600583
    ]
}
```

If the documentation is what it says: 
```
What happens here if there is no raw sample at the requested timestamp - VictoriaMetrics will try to locate the closest sample on the left to the requested timestamp
```
When I set step to 9s, I should be able to return the result normally, But now I can't explain it，I hope I can get some help， Thanks!!!

### To Reproduce

Please see the description above.

### Version

version: vmselect-20231002-215516-tags-v1.94.0-cluster-0-gcf93d27bc
run command: /data/victoria-metrics/bin/vmselect-prod --storageNode=xxx:8401 --storageNode=xxx:8401 --storageNode=xxx:8401 --storageNode=xxx:8401 --storageNode=xxx:8401 --storageNode=xxx:8401 --httpListenAddr=xxx:8481 --http.disableResponseCompression=true --cacheExpireDuration=30m0s --search.cacheTimestampOffset=5m0s --search.disableCache=false

**Comment by hagen1778** [comment]
Hi @iayamowner! 
Looks like this is a corner case produced by the following logic for identifying the lookback window
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e16d3f5639d67ff970975d342aaa276e339e9b0c/app/vmselect/promql/rollup.go#L819-L839
, when increase of `step` param by 1s actually results into smaller lookback window.

How this affects you in your use case? Is it synthetic?

**Comment by iayamowner** [comment]
👍👍Thanks a lot!!! Indeed, as you said, So that explains why this sample set gets the correct result even if step is set to 10. I'll learn the code to gain a deeper understanding of the internal logic.
