### ISSUE TITLE
High number of inmemory indexdb parts slow down ingestion on high CPU environment

### ISSUE THREAD

**Issue by misutoth** [VictoriaMetrics/VictoriaMetrics#5190]
### Describe the bug

Upon startup from empty storage (but sometimes during indexdb rotation and sudden increased churn rates too) we observed very slow startup. In itself this is not surprising because there is a very large volume of data. However, the ingestion rate as well as the disk write speed is reduced but the CPU usage is very high. We recognised a strong correlation with very high number of inmemory indexdb parts. Looking at the profiling vmstorage is busy seeking the place to insert new items into the inmemory parts, which operation's magnitude is proportional to the number of parts there.

My expectation would be for inmemory indexdb parts not to grow above a certain hard limit to prevent entering into an inefficient mode of operation and provide backbressure to data ingestion.

We saw there are limits applied but if an inmemory indexdb part is already being merged they are excluded. I guess the logic was that eventually they will get merged. Which is true, but even during merging/persisting it contributes to search linearity.

When looking at [profile.pdf](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12926328/profile.pdf)
one can see that ingestion is taking up the most part of the processing, and we can also see in the code the linearity in TableSearch.Seek() -> partSearch.Seek() propagation.

### To Reproduce

We have a performance test environment to simulate the production load. We simulate about 430 million unique time series, stored with replication factor of 2. The ingestion speed is 6.5 million samples per second. We have about 700 recording rules generating queries quite frequently. For this report we observed the behaviour during startup.

### Version

/ # /vmselect-prod --version
vmselect-20230902-002725-tags-v1.93.3-cluster-0-gf78d8b994d

/ # /vmstorage-prod --version
vmstorage-20230902-002932-tags-v1.93.3-cluster-0-gf78d8b994d

/ # /vminsert-prod --version
vminsert-20230902-002549-tags-v1.93.3-cluster-0-gf78d8b994d

### Logs

not captured, did not seem to add value

### Screenshots

![drilldown](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/adac8a43-3c29-4175-8efb-4cd97f67de89)
![vminsert](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/7e4fca32-0c16-4c95-8535-1500448250a1)
![vmselect](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/3d60c897-cd42-4d59-bf79-e1d8c8e82d46)
![vmstorage](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/8f289190-5891-46d2-a266-d5aedeba3d2f)
![interconnection](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/0e03c690-69a5-43f9-8ba3-997aecff0b7e)
![troubleshooting](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/a56e15f9-9644-499b-8225-103fbf5ec47e)
![resource_usage](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/1cacb047-279d-4e9e-a2a5-8894129ec077)
![stats](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/dc839a4a-9895-4f09-a31c-4506e008ea33)
![inmemory_parts](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7244068/130d1005-f13f-4b3a-86e7-91f56959aad8)
[goroutine.pdf](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12926327/goroutine.pdf)
[profile.pdf](https://github.com/VictoriaMetrics/VictoriaMetrics/files/12926328/profile.pdf)

### Used command-line flags

agent:
promscrape.config=/config/scrape.yml
remoteWrite.tmpDataPath=/tmpData
remoteWrite.url=http://victoria-metrics-cluster-vminsert:8480/insert/0/prometheus
remoteWrite.url=http://streaming-calculator:8399/remote_write
envflag.enable=true
envflag.prefix=VM_
loggerFormat=json
maxConcurrentInserts=20
memory.allowedBytes=4GiB
promscrape.cluster.membersCount=5
promscrape.configCheckInterval=30s
promscrape.httpSDCheckInterval=30s
promscrape.maxScrapeSize=1GiB
promscrape.noStaleMarkers=true
promscrape.streamParse=true
remoteWrite.maxDiskUsagePerURL=1GiB
remoteWrite.showURL=true

vminsert:
dropSamplesOnOverload=true
envflag.enable=true
envflag.prefix=VM_
http.connTimeout=15s
insert.maxQueueDuration=10s
loggerFormat=json
maxConcurrentInserts=10
maxInsertRequestSize=1GiB
maxLabelsPerTimeseries=70
memory.allowedBytes=20GiB
opentsdbhttp.maxInsertRequestSize=512MiB
replicationFactor=2
vmstorageDialTimeout=2s

vmstorage:
retentionPeriod=1
storageDataPath=/storage
envflag.enable=true
envflag.prefix=VM_
http.connTimeout=15s
loggerFormat=json
memory.allowedBytes=220GiB
search.maxUniqueTimeseries=100000000
smallMergeConcurrency=16

vmselect:
dedup.minScrapeInterval=1ms
envflag.enable=true
envflag.prefix=VM_
http.connTimeout=15s
http.maxGracefulShutdownDuration=2m
internStringDisableCache=true
loggerFormat=json
memory.allowedBytes=40GiB
replicationFactor=2
search.maxConcurrentRequests=150
search.maxLookback=6m
search.maxQueryDuration=300s
search.maxSamplesPerQuery=5000000000
search.maxSeries=500000
search.maxStalenessInterval=6m
search.maxUniqueTimeseries=100000000
search.minStalenessInterval=5m
search.skipSlowReplicas=true
vmalert.proxyURL=http://alert-rules:8880
vmstorageDialTimeout=1s

### Additional information

We also checked in some other cases (due to technical difficulties we did not see the metrics for the disks) the disk load on  vmstorages. We saw a spike in the beginning of the accumulation but we are not 100% sure that there was an io exhaustion. There may have been.

We also tried with 40 vmstorages but we experienced similar effect.

**Comment by hagen1778** [comment]
@f41gh7 @valyala would appreciate if you take a look

**Comment by misutoth** [comment]
We have deployed this to production: 1.93.6 + the version based on the pull request above. The startup time was about 6 minutes. Earlier we experienced a prolonged recovery during which the inmemory indexdb parts increased.

I feel that this report focuses too much on the internals and not on the impact and symptoms. Anyway, if you could provide some feedback on:

1. The measurement. What data should we capture and potentially compare with the PR.
2. The direction of the PR. What are your thoughts about it? Do you have some cencerns around it?

@valyala ?

**Comment by valyala** [comment]
@misutoth , the [v1.97.0 release](https://docs.victoriametrics.com/CHANGELOG.html) includes `indexdb` background merge scalability improvements from the pull request https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5212 . Now VictoriaMetrics limits the number of in-memory parts at `indexdb` to 30. See bb7a419cc30afed0a42c431d48cb5f4d1ac29e7b for details.

Closing the issue then as addressed.

**Comment by misutoth** [comment]
Thanks @valyala for taking care of this 👍
