### ISSUE TITLE
vmselect: storage groups/shards awarness

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5197]
### Is your feature request related to a problem? Please describe

One of the approaches for distributed systems is to create bi-level sharding. For example, the following VM topology consists of "shards" represented as a set of vmstorage components:
<img width="472" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/8792512b-053c-4970-8a2d-428cdb9499a4">

Such topology allows to scale each shard independently. For example, user can forward 70% of data to shard-1 and 30% to shard-2, based on some custom criteria (like `dev` and `prod` labels). In this way, shard-1 and shard-2 can be scaled independently and still participate in global queries.

But there is an uncovered problem - replication factor. If user would like to protect himself from partial results, he might set a replicationFactor on vmselect level in order to tolerate cases when one or more vmstorage nodes fail. However, in this topology vmselect won't be able to differentiate between this case:
<img width="485" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/6cafd6b6-3ead-488a-9ee0-207dac22d80a">
// the error should be tolerable, as only 1 storage failed per shard and thanks to RF=2 on vminsert level data remains complete

and this case:
<img width="495" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/484d191c-a2a6-4200-9b27-bc8ded95b8dd">
// the error is critical: the whole shard has failed

### Describe the solution you'd like

The possible resolution to the problem would be introducing group/shard awareness to vmselect config. For example:
```
-storageNode=shard-1/vmstorage1,shard-1/vmstorage2 -storageNode=shard-2/vmstorage3,shard-2/vmstorage3
```
In this way, vmselect can group vmstorage addresses into shards and tolerate failing requests within the shard.

**Comment by valyala** [comment]
The commit e4bb2808f15e2f9404b6dfed5d685122c3f0331a adds support for configuring independent `-replicationFactor` per each `vmstorage` group. This is done by specifying optional `vmstorage` group in `-storageNode` command-line flag via the `-storageNode=group/addr` syntax, where `group` is storage group name and `addr` is the address of `vmstorage` node. See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#vmstorage-groups-at-vmselect) for more details.

This commit will be included in the next release.

**Comment by valyala** [comment]
The [v1.96.0 release](https://docs.victoriametrics.com/CHANGELOG.html) includes the ability to specify storage groups via `-storageNode` command-line flag as described in [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#vmstorage-groups-at-vmselect). Closing the feature request as done.
