### ISSUE TITLE
absent_over_time not work

### ISSUE THREAD

**Issue by no-catcake** [VictoriaMetrics/VictoriaMetrics#5201]
### Describe the bug

when host1 turn off, 
run absent_over_time(node_time_seconds{instance="host1"}), I can get result,
run absent_over_time(node_time_seconds), show no data

### To Reproduce

as describe

### Version

vmstorage-20230519-012137-tags-v1.79.13-cluster-0-g7276d82b1

**Comment by Amper** [comment]
Hey, @no-catcake.
Could you please provide [raw data](https://docs.victoriametrics.com/url-examples.html#apiv1export) for reproducing problem?

**Comment by no-catcake** [comment]
> Hey, @no-catcake. Could you please provide [raw data](https://docs.victoriametrics.com/url-examples.html#apiv1export) for reproducing problem?

This problem can be reproduced using any data
when I use v1.72.0, It's ok

**Comment by Amper** [comment]
@no-catcake, it was updated in [v1.73.0](https://docs.victoriametrics.com/CHANGELOG_2022.html#v1730):

> - BUGFIX: calculate [absent_over_time()](https://docs.victoriametrics.com/MetricsQL.html#absent_over_time) in the same way as Prometheus does. Previously it could return multiple time series instead of at most one time series like Prometheus does. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2130).

See related issues:
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2130
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2415
