### ISSUE TITLE
vmui: "explore prometheus metrics" doesn't show the query errors

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5202]
### Describe the bug

I've tried using [Explore Prometheus Metrics](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/metrics?g0.range_input=30m&g0.end_input=2023-10-19T08%3A32%3A54&g0.relative_time=last_30_minutes&size=small&g0.step_input=5s) tab with [Prometheus as datasource](https://demo.promlabs.com/). It didn't work and it wasn't clear why.
Looking at NetworkTab I found the error message related to Prometheus not supporting some MetricsQL functions.
Would be nice for this error to be propagated to the UI as well.

P.S. would be also great to make it compatible with Prometheus. Maybe we can use queries in pure PromQL. wdyt @valyala ?

### To Reproduce

Visit https://play.victoriametrics.com and configure it with https://demo.promlabs.com/ as data source.

### Version

v1.94

cc @Loori-R

**Comment by valyala** [comment]
[`Explore Prometheus metrics` tab at vmui](https://docs.victoriametrics.com/#metrics-explorer) shows the minimum, maximum and the average values per each graph via a single query, which uses [rollup](https://docs.victoriametrics.com/MetricsQL.html#rollup), [rollup_rate](https://docs.victoriametrics.com/MetricsQL.html#rollup_rate), [alias](https://docs.victoriametrics.com/MetricsQL.html#alias) and [union](https://docs.victoriametrics.com/MetricsQL.html#union) functions, which are available only in [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) only and aren't available in PromQL. See [the corresponding source code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f90d2ec843063fa382e2add5206ecb3ecf6bed53/app/vmui/packages/vmui/src/components/ExploreMetrics/ExploreMetricGraph/ExploreMetricItemGraph.tsx#L64).

I don't know how to get these three lines in a single query by using pure PromQL :(

BTW, which issue does resolve the ability to query Prometheus datasource via vmui?

**Comment by valyala** [comment]
FYI, [vmui](https://docs.victoriametrics.com/#vmui) should display errors at [Explore Prometheus metrics](https://docs.victoriametrics.com/#metrics-explorer) page starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html).
