### ISSUE TITLE
vmui: strip slashes from datasource address 

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5203]
### Describe the bug

I've tried to [Explore Cardinality](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/cardinality?date=2023-10-19) of the [Prometheus instance](https://demo.promlabs.com/) and got the error: failed to fetch.

From the error msg it wasn't clear what is wrong. So after some adjustments I made it work by removing `/` 
from the `https://demo.promlabs.com/`. Would be nice if vmui or VM could do it automatically.

### To Reproduce

Go to https://play.victoriametrics.com and try pointing it to https://demo.promlabs.com/

### Version

v1.94

cc @Loori-R

**Comment by valyala** [comment]
FYI, the bugfix has been included in [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html).
