### ISSUE TITLE
vmagent does not dropInput 

### ISSUE THREAD

**Issue by aluode99** [VictoriaMetrics/VictoriaMetrics#5207]
### Describe the bug

 vmagent does not dropInput when set remoteWrite.streamAggr.keepInput to false and remoteWrite.streamAggr.dropInput to true . In my case, the streamAggrConfig is empty.I expect all input to be discarded, but in fact, no input was discarded. This has resulted in a multiple increase in the write traffic to VM.

### To Reproduce

1.  set streamAggrConfig empty
2. set remoteWrite.streamAggr.dropInput true
3. set remoteWrite.streamAggr.keepInput false 

### Version

v1.93.6

**Comment by hagen1778** [comment]
@aluode99  the issue should have been addressed by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5213 and is likely to be included into the next release of VM.

**Comment by valyala** [comment]
@aluode99 , the bugfix has been included in vmagent [v1.93.7 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.7). Now `vmagent` should properly handle an empty file pointed by `-remoteWrite.streamAggr.config`
