### ISSUE TITLE
VMAlert add ability to disable query validation.

### ISSUE THREAD

**Issue by korjavin** [VictoriaMetrics/VictoriaMetrics#521]
I use loki-promql as datasource for alerts.
For loki query like 
`sum(count_over_time({app="myapp"}[5m]|="NEVER"))`
is valid.

Grafana works with it fine. 

When I add it to vmalert like:
```
      groups:
        - name: myapp
          rules:    
            - alert: import never logs count
              for: 1m
              expr: sum(count_over_time({app="myapp"}[5m]|="NEVER"))>1
              labels:
                app : myapp
                reason : never
```

I am getting:
```
invalid expression for rule "never logs count": cannot recognize "|=\"NEVER\"))>1"; unparsed data: "]|=\"NEVER\"))>1"
```

I'd like to have query validation as optional thing, it will allow me to use loki's promql.

**Comment by hagen1778** [comment]
Hi @korjavin ! Flag for disabling expressions validation was added in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ffa75c423d9b24636ea1048ea655037319becd31

You can verify it by [building](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert#how-to-build-from-sources) `vmalert` from sources. The change will be also included in next release.

**Comment by valyala** [comment]
`vmalert` supports disabling rule expression validation starting from [v1.37.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
