### ISSUE TITLE
vmctl vm-native fails on "the number of matching timeseries exceeds 300000"

### ISSUE THREAD

**Issue by nemobis** [VictoriaMetrics/VictoriaMetrics#5215]
### Describe the bug

When attempting a [migration from one VictoriaMetrics cluster to another](https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics) with `vmctl vm-native`, the import fails immediately with an error:

> the number of matching timeseries exceeds 300000; either narrow down the search or increase -search.max* command-line flag values at vmselect

Increasing the vmselect limits as instructed by the log message, https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4624 doesn't actually help. https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3734#issuecomment-1413145067 should not apply. Could the culprit be on vmstorage as valyala said at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/293#issuecomment-577631226 :

> `-search.maxUniqueTimeseries` flag must be set at `vmstorage`. It doesn't exist at `vmselect`.

? If so, the error message and https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics should be changed to state that vmstorage limits may also need to be increased.

### To Reproduce

1) Deploy the VM clustered helm chart
2) Fill your vmstorage pods with sufficiently high cardinality metrics
3) Attempt https://docs.victoriametrics.com/vmctl.html#migrating-data-from-victoriametrics

### Version

vmstorage-20230518-213137-tags-v1.91.0-cluster-0-g93f934eae

### Logs

```
2023/10/19 14:04:43 Initing import process from "https://<redacted>/select/0/prometheus/api/v1/export/native" to "http://victoriametrics-victoria-metrics-cluster-vminsert.victoriametrics.svc.cluster.local:8480/api/v1/import/native" with filter  
       filter: match[]={__name__!=""} 
       start: 2023-10-19T00:00:00Z 
2023/10/19 14:04:43 Exploring metrics... 
2023/10/19 14:04:43 migration failed: cannot get metrics from source https://<redacted>/select/0/prometheus: series request failed: unexpected response code 422: {"status":"error","errorType":"422","error":"cannot obtain values for label \"__name__\": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage 
victoriametrics-victoria-metrics-cluster-vmstorage-9.victoriametrics-victoria-metrics-cluster-vmstorage.victoriametrics.svc.cluster.local:8401: cannot execute funcName=\"labelValues_v5\" on
vmstorage \"10.236.232.55:8401\": the number of matching timeseries exceeds 300000; either narrow down the search or increase -search.max* command-line flag values at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits"}
```

### Used command-line flags

```
./vmctl-prod vm-native \
    --vm-native-src-addr=https://<redacted>/select/0/prometheus/ \
    --vm-native-dst-addr=http://victoriametrics-victoria-metrics-cluster-vminsert.victoriametrics.svc.cluster.local:8480/insert/0/prometheus/ \
    --vm-native-filter-time-start='2023-07-01T00:00:00Z' \
```

**Comment by dmitryk-dk** [comment]
Hi @nemobis ! Can you try to use this approach?
I can suggest one more option to change flags, limiting the number of series.
`search.maxUniqueTimeseries: ""`
`search.maxQueryDuration: "600s"`
```
-search.maxUniqueTimeseries limits the number of unique time series a single query can find and process. VictoriaMetrics keeps in memory some metainformation about the time series located by each query and spends some CPU time for processing the found time series. This means that the maximum memory usage and CPU usage a single query can use is proportional to -search.maxUniqueTimeseries.
```

```
-search.maxQueryDuration limits the duration of a single query. If the query takes longer than the given duration, then it is canceled. This allows saving CPU and RAM when executing unexpected heavy queries.
```
This flag should help to migrate from big cluster which has a lot of data. When i tested migration process i set
search.maxUniqueTimeseries 
to 25000000, but it was test cluster.

**Comment by nemobis** [comment]
Thank you. Indeed I ended up using `search.maxSeries` of 15M for vmselect and `search.maxUniqueTimeseries` of 10M for vmstorage (on a cluster with little more than 10M active timeseries at the moment, and peaks under 20M).

I've not yet increased the max duration because I've not hit that issue yet. I'm trying to keep concurrency low enough and the individual requests small enough to avoid this kind of error I've now hit:
```
2023-10-20T20:37:20.881Z        error   VictoriaMetrics/app/vmctl/backoff/backoff.go:56 got error: failed to init export pipe: export request failed: unexpected response code 503: remoteAddr: "10.<redacted>:36766", X-Forwarded-For: "10.<redacted>"; requestURI: /select/0/prometheus/api/v1/export/native?end=2023-08-29T00%3A00%3A00Z&match%5B%5D=%7B__name__%3D%22container_network_receive_errors_total%22%7D&start=2023-08-28T00%3A00%3A00Z; couldn't start executing the request in 10.000 seconds, since -search.maxConcurrentRequests=16 concurrent requests are executed. Possible solutions: to reduce query load; to add more compute resources to the server; to increase -search.maxQueueDuration=10s; to increase -search.maxQueryDuration; to increase -search.maxConcurrentRequests
 on attempt: 1; will retry in 2s
2023-10-20T20:37:38.159Z        error   VictoriaMetrics/app/vmctl/vm_native.go:132      error initialize import pipe: import request failed: unexpected response code 400: remoteAddr: "10.236.228.5:51666"; requestURI: /insert/0/prometheus/api/v1/import/native; too big metricName size; got 1919249775; shouldn't exceed 1048576
```

I could increase that limit too but I don't want to increase it by a factor of more than 2000... Hopefully `--vm-native-step-interval=minute` helps. (Should I file a different feature request for vmctl to automatically break down the import requests when it hits this limit?)

**Comment by dmitryk-dk** [comment]
Hi @nemobis ! From what version of vmstorage you try to export, and what version of the vmstorage you import your data?

**Comment by nemobis** [comment]
@dmitryk-dk Thank you! Both sides are on v1.91.0-cluster, would it help to upgrade to 1.93?

I don't know how that metric name could be incorrect, if it's indeed about `container_network_receive_errors_total`. That's a standard kubelet metric which we just scrape with an ordinary prometheus-operator which remote-writes to VictoriaMetrics. How to debug further?

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk Thank you! Both sides are on v1.91.0-cluster, would it help to upgrade to 1.93?
> 
> I don't know how that metric name could be incorrect, if it's indeed about `container_network_receive_errors_total`. That's a standard kubelet metric which we just scrape with an ordinary prometheus-operator which remote-writes to VictoriaMetrics. How to debug further?

This is the correct metrics name, but you can make a request via `api/v1/label/__name__/values` for the period you try to migrate data. And check that there can be wrong metric names.
The version is ok. Could you just try to check the names of the metrics? If you find that all metrics are okay, please export some parts of the data. I will import it and check where there be a problem.

**Comment by nemobis** [comment]
I could import the metrics piecemeal with more specific selectors, but I was hoping to avoid it. Unfortunately I can't share any data as it's bound to contain some confidential information.

**Comment by dmitryk-dk** [comment]
> I could import the metrics piecemeal with more specific selectors, but I was hoping to avoid it. Unfortunately I can't share any data as it's certain to contain some confidential information.

Ok, understand! So, check the metrics names to see if they would be okay. If not, I will check the possible problem with metric names when importing data.

**Comment by dmitryk-dk** [comment]
@nemobis ! About this question
> (Should I file a different feature request for vmctl to automatically break down the import requests when it hits this limit?)

You can create feature requests, of course, but it would be discussed. `vmctl` is just a mediator between two deployments of the VictoriaMetrics, and I think it would be unhelpful because we have step intervals, and you can change search flags to avoid the query problems.

**Comment by dmitryk-dk** [comment]
Hi @nemobis ! I have checked migration from our test cluster and it works well, I can't find any problem with it. 

I want to ask, can we close the issue?

**Comment by nemobis** [comment]
> I want to ask, can we close the issue?

Sure, but my main issue was with the misleading error message. Could that be changed, so that it doesn't hardcode vmselect as being the culprit when the limit may be in vmstorage as well?
