### ISSUE TITLE
Publish Alpine images to Dockerhub

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#522]
**Is your feature request related to a problem? Please describe.**
It is currently difficult to add dynamic parameters to vmbackup (e.g. for the date). It is also difficult to debug issues with the other images because they are based on scratch and you cannot use `kubectl exec` to get a shell.

**Describe the solution you'd like**
In addition to (or in replacement of) the current images based on scratch can you publish images for all the components with Alpine as a base?

**Describe alternatives you've considered**
Build a Docker image locally and push to another registry but it adds some friction when a new version is released.

**Comment by valyala** [comment]
Switching base image from `scratch` to `alpine` increases the resulting image size. This goes in the opposite direction to https://medium.com/@valyala/stripping-dependency-bloat-in-victoriametrics-docker-image-983fb5912b0d :(

If you use Kubernetes 1.18 and newer versions, then it is possible to debug distroless containers with `kubectl alpha debug` - see https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container for details.

This is recurring feature request, so it is likely VictoriaMetrics Docker images will be switched from `scratch` to `alpine` base image in the near future. This should improve the overall user experience at the cost of slightly bigger Docker images.

**Comment by valyala** [comment]
@alexandv , the following commits switch base image for VictoriaMetrics components from `scratch` to `alpine`:

* Single-node version - ff624c9125c45ba00bc6dec57cc5c784e319262b
* Cluster version - 2961e7121776cd7b5e22de81b55116eaf40404f0

These commits will be included in the next release.

**Comment by alexandv** [comment]
That's great. Thanks @valyala for addressing this so quickly

**Comment by valyala** [comment]
FYI, all the VictoriaMetrics components are based on `alpine` docker image starting from [v1.37.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
