### ISSUE TITLE
VMAgent fails to scrape targets

### ISSUE THREAD

**Issue by soniaAr** [VictoriaMetrics/VictoriaMetrics#5220]
### Describe the bug

Hello
i have an issue when i try to scrape an endpoint from a static configuration:

![tempsnip](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70903490/5aaf916b-9f2a-4a1c-9c70-cea4b14a2a25)
this is my configuration knowing that the two targets ( that are on the same machine but differents ports are accessible from the machine where the agent and the victoriametrics is installed.

![tempsnip2](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70903490/971b7d1f-ad91-42ab-808c-24b2f6307256)

this is the systemd:

![tempsnip3](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70903490/533f3252-66ca-41e5-a8f4-ee1710dada49)

thank you in advance.

### To Reproduce

i'm not sure about the steps

### Version

![Capture](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70903490/2e339b66-8926-45ee-ae8e-c05d6aa2cb68)

![Capture2](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70903490/2862e66f-5a84-475b-9630-3d28f518c494)

**Comment by f41gh7** [comment]
Hello, did you check vmagent logs? Is there any error related to the scrape configuration?

 Also, I as far as I see, scrape didn't happen for the configured target. You have 2 minutes scrape interval, vmagent starts it with some offset delay. So you have to wait a bit for the first scrape.

**Comment by f41gh7** [comment]
![Uploading vmagent_scrape.png…]()

**Comment by soniaAr** [comment]
Hello, 
thank you for your answer,
where are the logs located please?
Even if I put 15 sec or less of scarpe_interval, i dont get the scrape done, I had an error before which is about promscrape.maxScrapeSize which is less than 16777216, i have changed it, and now no more errors but no scrapes.
I know that the static endpoint that i'm requesting has too many metrics.

**Comment by soniaAr** [comment]
With Prometheus i'm getting this scrape [duration](url) 
![MicrosoftTeams-image (1)](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70903490/91f93747-ef92-4e84-9758-e0dcf706d2bb)

**Comment by hagen1778** [comment]
> where are the logs located please?

@soniaAr logs are emitted by the vmagent, can you check if there are other errors? Can you show what vmagent UI shows now for this target?

**Comment by Amper** [comment]
@hagen1778 Most of the messages on this issue are here: https://victoriametrics.slack.com/archives/C05UNTPAEDN/p1698051054686819

**Comment by soniaAr** [comment]
Hello, sorry for the delay answer
Yes i was able to have some logs, by starting the vmagent with command line and not with systemd service, so when the agent tries to scrape the target we get a fatal error : OUT OF MEMORY, so i have increased the RAM and now i can see the state of the target as "UP" thank you for your help 👍
