### ISSUE TITLE
How to optimize queries 

### ISSUE THREAD

**Issue by jicki** [VictoriaMetrics/VictoriaMetrics#5225]
### Describe the question in detail

 Grafana panel

```
Status: 500. Message: 422: not enough memory for processing kube_pod_info, which returns 1698176844 data points across 841932 time series with 2017 points in each time series; total available memory for concurrent requests: 20615843020 bytes; requested memory: 28012761504 bytes; possible solutions are: reducing the number of matching time series; increasing `step` query arg (step=300s); switching to node with more RAM; increasing -memory.allowedPercent
```

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/2b7a94bb-9e31-413a-b2eb-a69a70b069d2)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/5cf891a5-fc35-429e-8eac-d294533534ce)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @jicki.
It's worth starting with this guide: https://docs.victoriametrics.com/Troubleshooting.html
Most of the information you need is given to you right in the text of the error.
It clearly states how many datapoints, series you want to select, how much memory you need for this and and what the solutions are:
1. *"reducing the number of matching time series"*:
    - for instance, you can use [aggregate functions](https://docs.victoriametrics.com/MetricsQL.html#aggregate-functions) 
    - or specify series selector
3. reducing the number of datapoints:
    - *"increasing `step` query arg (step=300s)"*
    - reducing query interval
5. increasing memory for query with:
    - *"switching to node with more RAM;"*
    - *"increasing -memory.allowedPercent"*
