### ISSUE TITLE
How to switch influxdb to vm, but there is no int value

### ISSUE THREAD

**Issue by DoLolitingyu** [VictoriaMetrics/VictoriaMetrics#5226]
### Is your question request related to a specific component?

influxdb VictoriaMetrics

### Describe the question in detail

We use influxdb which is more like a time based row database, but vm is more like a time based metric (column) database；
and we now have this kind of data in influxdb:
```
measurement: vm
time: 1698027840000000000

tags:
vmid="382"
vmname="test-vm"
user="ben"

fields:
Manufacturer="intel"
Family="Not Specified"
```

If I want to use it in vm, do I have to turn all fields into tags, and then fix an int even if I don't use it?
**vm_info{vmid="382" vmname="test-vm" user="ben" Manufacturer="intel" Family="Not Specified"} 1**

The only way I can think of is to use it as a row database. Thank you for your answer.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @DoLolitingyu.

Yes, VM only support float fields, and you should convert your string fields to tags and add some artificial value.

Related links:

- Guide about migration from Influx: https://docs.victoriametrics.com/guides/migrate-from-influx.html
- How to send data from InfluxDB-compatible agents: https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/385
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1557
