### ISSUE TITLE
vmagent puppetdb service discovery support

### ISSUE THREAD

**Issue by fzuerkeraguilar** [VictoriaMetrics/VictoriaMetrics#5230]
### Is your feature request related to a problem? Please describe

I'm currently discovering my targets via the puppetdb service discovery of Prometheus and writing the metrics to a vmcluster. I would like to simplify this setup and scrape the targets directly with vmagent.

### Describe the solution you'd like

I would like to see support for the service discovery configs of puppetdb in vmagent.

**Comment by jiekun** [comment]
Hi. Thanks for the feature request. I'm closing this issue. Please track it with #5744 .
