### ISSUE TITLE
Custom proxy "exporter"

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#5237]
### Is your question request related to a specific component?

vmagent, vmalert

### Describe the question in detail

My current goal is to create a monitoring system that surveils a network with millions of nodes pumping metrics from the edge layer of the network to a central storage in this case a VM instance. This system has 2 main goals, allow for the gathering of metrics without network bottlenecking and latency, and also to ensure alerts are detected and propagated as soon as possible. 
After analyzing the vmalert component I was able to verify that it would be limited to verify its rules for alert triggering when observing the metrics in an VM instance. This situation would cause a delay in alert detection due to the fact that the metrics would need to be scraped from the millions of devices and then inserted in the VM instance by the vmagent, the time that this takes is too long.
Is there a possibility of creating a proxy container or "exporter" that posesses the ability of storing aggregated metrics from different node exporters ,for example, in a compatible TSDB in order for the vmalert to interact with said TSDB? Additionaly, could there be a way for this proxy container/exporter to have an endpoint that allows vmagents to scrape the stored aggregated metrics?
Below there is an image of what i am trying to depict:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/3865bae0-4c13-4e05-859d-c327ff9cd834)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @DaRealCapz 

Based on your description it seems like "New proxy container/Exporter" should do just the same what VictoriaMetrics Single does, isn't it?
It should store data and process `/query` read requests from vmalert to evaluate alerts and store new datapoints by using one of existing ingestion protocols.

For this usecase I'd suggest to use the following setup:
![vm-central-leaf](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1367798/6effcbac-6fc4-4f57-97a5-08315ba1e4ec)

Here you can see that each "leaf" location will use:
- vmalert - to evaluate alerts locally
- vmsingle - to store scraped metrics and store with short retention
- vmagent - to scrape metrics and push to local vmsingle and central vmcluster

Here all alerts will be evaluated locally in "leaf" locations, but data will also be tranfserred to a central monitoring platforms.

**Comment by DaRealCapz** [comment]
Thank you for your reply, at the moment the use of a VMSingle is not possible because it does not solve the current issue of detecting and propagating alerts asap. Since the vmagent would send the metrics to a VMSingle that extra step could cause errors to not be detected in due time. Idealy the alerts would be detected before reaching the vmagent and since the vmagent does not have "queryable" interface for the metrics in its cache there is a need for developing a solution that has a small TSDB like VMSingle, can scrape and aggregate metrics exclusively for a vmalert to evaluate its rules and then send those metrics to the vmagent.
The question remains, is there a way that I can incorporate these features in a small proxy that has the ability of scrapping and aggregating metrics in an TSDB for vmalert to evaluate?

**Comment by zekker6** [comment]
@DaRealCapz Delay of sending data between vmsingle and vmagent depend on the bandwidth and delay in network between those components. If both will be hosted locally I'd expect delays to be lower than tens of milliseconds.
Please, note that there is also a delay controlled by `-search.latencyOffset` flag:
```
  -search.latencyOffset duration
     The time when data points become visible in query results after the collection. It can be overridden on per-query basis via latency_offset arg. Too small value can result in incomplete last points for query results (default 30s)
```
Which by default delays ingested datapoint visibility by 30s.

If using vmagent does not work for you, you can scrape metrics with both vmsingle and vmagent. 
vmsingle will scrape metrics directly in order to avoid delays and will be used by vmalert to evaluate alerts. 
vmagent will just forward metrics to central location.

**Comment by DaRealCapz** [comment]
The main purpose for this proxy exporter is to be integrated in a very large network where the vmagents are located close to the edge layer of the network . This proxy would be located at the same level as the vmagent or even below allowing for the vmalert to detect issues in a more timely manner. Given this is it possible to combine storage component of the VMSingle with the aggregation and relabeling features of the vmagent?

**Comment by zekker6** [comment]
@DaRealCapz VMSingle already has suport of [relabeling](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#relabeling) and [streaming aggregation](https://docs.victoriametrics.com/stream-aggregation.html) just the same as vmagent.

**Comment by DaRealCapz** [comment]
Could you point me in the direction of some tutorial or documentation where I can understand how to do it?

**Comment by DaRealCapz** [comment]
Thank you for your assistance, to finalize I am having trouble supplying this new vmsingle directly with metrics from my exporters. Where in the configs does this linking occur?

**Comment by zekker6** [comment]
@DaRealCapz This linking is configured by scrape configuration. Please, give a read to this part of documentation to get a better understanding of configuration - https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-scrape-prometheus-exporters-such-as-node-exporter

**Comment by DaRealCapz** [comment]
One final question, in the image you have sent me can the new VMSingle replace the role of the vmagent by gathering metrics from the exporters and send the gathered metrics to a central node and if so at what cost in terms of resource usage. Also can the VMCluster gather metrics from a VMSingle instance by the means of a Pull or is it only possible through the push/remote_write protocol?

**Comment by zekker6** [comment]
@DaRealCapz 
> One final question, in the image you have sent me can the new VMSingle replace the role of the vmagent by gathering metrics from the exporters and send the gathered metrics to a central node and if so at what cost in terms of resource usage. 

No, VMSingle can't forward gathered metrics. This is the reason I've used VMAgent on the scheme in order to gather metrics and send to separate locations.

> Also can the VMCluster gather metrics from a VMSingle instance by the means of a Pull or is it only possible through the push/remote_write protocol?

VMCluster itself does only store metrics, unlike VMSingle it cant scrape metrics. VMAgent is required to scrape metrics and push to the cluster.

**Comment by zekker6** [comment]
Closing as questions have been answered. Please, reopen if there will be any other related questions.
