### ISSUE TITLE
"SELECT *" for VictoriaLog fields

### ISSUE THREAD

**Issue by rul-hydro** [VictoriaMetrics/VictoriaMetrics#5238]
### Is your feature request related to a problem? Please describe

In some cases, I have many fields for a log line and may not even know beforehand which fields exist. This makes it tiresome to impossible to extract all information associated with a log line.

### Describe the solution you'd like

A selector like `*:word` or even `*:*` would allow selecting all fields. The `*` field would then have to mean "any field that is present".
Maybe, a modifier flag for selecting fields _after_ filtering would be an even better approach, since it would not slow down the search. This might look like this:
Include all fields:
```word ip:ipv4_range(10.0.0.0/8) include_fields(*)```
or
Include all fields with prefix
```word ip:ipv4_range(10.0.0.0/8) include_fields(grafana*)```

The Roadmap states that something like this is planned. Any ETA yet?

**Comment by rul-hydro** [comment]
Especially when selecting from multiple streams with different field sets, getting all fields is tricky:
```error and (ip:* or ip:"")```

**Comment by mr-karan** [comment]
Related: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4918

**Comment by hagen1778** [comment]
VictoriaLogs returns all fields by default in query results starting from [v0.6.0](https://docs.victoriametrics.com/victorialogs/changelog/#v060). See [docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs):
> The response by default contains all the [fields](https://docs.victoriametrics.com/victorialogs/keyconcepts/#data-model) for the selected logs. Use [fields pipe](https://docs.victoriametrics.com/victorialogs/logsql/#fields-pipe) for selecting only the needed fields.

See more details in related ticket [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4918#issuecomment-2222433791).
