### ISSUE TITLE
query_range get "0x04" in response

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#524]
**Describe the bug**
got exception char in label value(**0x04**)

**To Reproduce**
##### a series `cpu.idle` with label
```
"__ns__": "x.y.z"
"host": "host1"
``` 

##### query 1 series, got 2 result
query_range?query=`cpu.idle{__ns__=~"x.x.z",host=~"host1"}`

from `now() - 7d` to `now()`, get correct response
from `now() - 1m` to `now()`, the response is exception:
```
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {
          "__name__": "cpu.idle",
          "__ns__": "x.yz", <<<<<<<<<<<<<<< x.y<0x04>y
          "host": "host1"
        },
        "values": []
      },
      {
        "metric": {
          "__name__": "cpu.idle",
          "__ns__": "x.y.z",
          "host": "host1"
        },
        "values": []
      }
    ]
  }
}

```

other labels is same, except `__ns__` label

**Expected behavior**
always get correct response

**Version**
```
$ ./vmstorage-prod --version
vmstorage-20200520-060954-heads-cluster-0-g8ff28f5b

$ ./vmselect-prod --version
vmselect-20200520-060943-heads-cluster-0-g8ff28f5b

$ ./vminsert-prod --version
vminsert-20200520-060901-heads-cluster-0-g8ff28f5b

```

**Comment by n4mine** [comment]
i thank i know the cause.
regexp meta char **dot** will match char ".", and 0x04
so i got "x.y.z" and "x.y<0x04>z"

but this query will break grafana, it show "Cannot read property 'result' of undefined"

any idea can limit the special characters ingest in vm?

**Comment by valyala** [comment]
It is possible to filter special chars with `action: replace_all` relabeling rules in `vmagent`, which should be put in front of VictoriaMetrics.
For example, the following relabeling rule will replace all the [unsupported chars by Prometheus](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels) in `ns` with `_`:

```yml
- action: "replace_all"
  regex: "[^0-9a-zA-Z:_]"
  replacement: "_"
  source_labels: [ns]
  target_label: ns
```

See [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#relabeling) for details.

Let's repurpose this issue to feature request for adding an option to reject samples with labels containing unsupported in Prometheus chars.
