### ISSUE TITLE
vmauth: support skipTLSInsecure on the user level

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5240]
### Is your feature request related to a problem? Please describe

It could be that backends configured in vmauth are using self-signed certificates. In this case, vmauth will fail to proxy requests to such backends correctly, unless user will add corresponding certificates to the vmauth container. Which significantly complicates the deployment.

### Describe the solution you'd like

Would be nice if vmauth, as other vm components, could have an option to skip TLS certificates verification.
Since each user can have different set of backends configured, it makes sense to add a new param `tls_insecure_skip_verify` on the user level.

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5256 has been merged and will be likely included in the next release

**Comment by valyala** [comment]
Starting from the commit 61594d2bd85cf7bb66f24f36d28cff47db55ee5b , `vmauth` can be configured to skip TLS verification at both global level (via `-backend.tlsInsecureSkipVerify` command-line flag) and at per-user level (via `tls_insecure_skip_verify` option at `user` config). See [these docs](https://docs.victoriametrics.com/vmauth.html#backend-tls-setup) for more details.

See also the commit eded218e8c7478799956db40cb7dfe98a1c359d0 , which properly sets `Host` request header to the backend host and allows http/2.0 requests to backends.

Both commits will be included in the next release

**Comment by valyala** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth.html) gains the ability to skip TLS server verification when requesting the configured backends starting from [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmauth.html#backend-tls-setup) for more detials.

Closing the feature request as done.
