### ISSUE TITLE
vmselect missing data 

### ISSUE THREAD

**Issue by yasvanth** [VictoriaMetrics/VictoriaMetrics#5242]
### Is your question request related to a specific component?

vmselect:v1.93.1-enterprise-cluster

### Describe the question in detail

Versions:

`vmagent:v1.88.1-enterprise`
`victoriametrics/vminsert:v1.93.1-enterprise-cluster`
`victoriametrics/vmselect:v1.93.1-enterprise-cluster`
`victoriametrics/vmstorage:v1.93.1-enterprise-cluster`

There is missing data in the graph (between 14:00 - 20:00 ) when the Grafana timestamp is set to 24hrs  as below.

<img width="741" alt="Screenshot 2023-10-27 at 09 35 30" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/f12f302b-3519-4d96-b8df-92d48187717e">

The data is available by selecting the missing timestamp (14:00 - 20:00). 

<img width="739" alt="Screenshot 2023-10-27 at 09 38 15" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/9b0928fb-e09a-4098-93d5-24857ab44ac8">

`vmagent` configs:

<pre>
      - '--eula'
      - '--promscrape.cluster.name=network-monitor'
      - '--promscrape.cluster.membersCount=3'
      - '--promscrape.cluster.memberNum=2'
      - '--promscrape.cluster.replicationFactor=3'
      - '--remoteWrite.tmpDataPath=/vmagentdata'
      - '--promscrape.config=/etc/vmagent/scrape-config.yml'
      - '--remoteWrite.url=http://vminsert:8480/insert/multitenant/prometheus/'
      - '--promscrape.suppressScrapeErrorsDelay=30s'
      - '--promscrape.maxScrapeSize=56777216'

</pre>

`vminsert` configs:

<pre>
      - '--eula'
      - '--storageNode=vmstorage-01:8401'
      - '--storageNode=vmstorage-02:8401'
      - '--storageNode=vmstorage-03:8401'
</pre>

`vmselect` configs:

<pre>
      - '--eula'
      - '--search.minStalenessInterval=5m'
      - '--dedup.minScrapeInterval=1m'
      - '--storageNode=vmstorage-01:8401'
      - '--storageNode=vmstorage-02:8401'
      - '--storageNode=vmstorage-03:8401'
      - '--replicationFactor=3'
</pre>

`vmstorage` configs 

<pre>
      - '--eula'
      - '--dedup.minScrapeInterval=1m'
      - '--downsampling.period=30d:5m,180d:1h'
      - '--storageDataPath=/storage'
      - '--retentionPeriod=37'
      - '--vminsertAddr=:8400'
      - '--vmselectAddr=:8401'
</pre>

The same setting is used for staging, with no issue whereas production shows the missing data or too many data points. 

The same devices are scrapped with an interval of `1m`. 

Staging:
<img width="2257" alt="Screenshot 2023-10-27 at 09 44 23" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/722a98af-a999-4cf6-9505-85cb21afe41a">

Production:

<img width="2253" alt="Screenshot 2023-10-27 at 09 44 39" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/0d16136e-a2b5-4253-8590-7ebc48799452">

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @yasvanth 

It looks like those entries are either missing in index or there is an issue with caches which are used for fetching metrics.
Could you try resetting cache on each vmselect node and see if it helps?
You can reset cache by running `curl 0.0.0.0:8481/internal/resetRollupResultCache` on each `vmselect` node in cluster.
Alternatively, you can disable caching by passing `-search.disableCache` command-line flag to all the vmselect nodes in cluster.

If that doesn't help, could you please run the same queries with [tracing](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#query-tracing) enabled and share the traces?

**Comment by yasvanth** [comment]
@zekker6  Thanks for your prompt response. No luck with cache disable `-search.disableCache` , will try to get tracing.

**Comment by yasvanth** [comment]
@zekker6  Please find the attached trace results for the query 

timestamp - 24hrs
<img width="2236" alt="Screenshot 2023-10-27 at 11 11 38" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/21e921fd-bd1d-4f8a-ab04-259dc9767ef5">

timestamp - 12hrs
<img width="2251" alt="Screenshot 2023-10-27 at 11 16 56" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/58bf2b33-f43f-433c-bda1-a3ad96bf8201">

**Comment by zekker6** [comment]
@yasvanth Can you please export json conntent of traces and share it?
You can do this by clicking angled brackets sign to on the right side of trace.

**Comment by yasvanth** [comment]
@zekker6 I have attached the trace JSON file for the query (24h) . I have to source with `router_name` in the json. 

`rate(interfaces_interface_state_counters_in_octets{source="$router_name",subscription_name="sub1"}[5m] * on (interface_name) group_left(description) interfaces_interface_state_description{source="$router_name",subscription_name="sub1"})*8 [5m]` 

[vmui-query-trace-export.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/13204112/vmui-query-trace-export.json)

**Comment by yasvanth** [comment]
@zekker6  Any suggestions or updates?

**Comment by zekker6** [comment]
@yasvanth As far as I can see from the trace: 
>  /select/00/prometheus/api/v1/query: query=rate(interfaces_interface_state_counters_in_octets{source="router_name",subscription_name="sub1"}[5m] * on (interface_name) group_left(description) interfaces_interface_state_description{source="router_name",subscription_name="sub1"})*8 [5m], time=1698661994655

This trace is performed by using `/query` endpoint which has different semantics than `/query_range`.

In order to make it easier to reproduce the problem from our side, could you export part of data where this problem is reproducible by using [export API](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-export-time-series) and share it here?
Any sensitive details can be stripped off.

**Comment by yasvanth** [comment]
@zekker6  please find the attached export from prod and staging. Due to size limit in git the file can be downloaded from 

https://filesender2.heanet.ie/?s=download&token=ddb1168e-2122-47f3-bf1d-25f8a342b0c8 

data timestamp : ` -d 'start=2023-10-31T17:00:00' -d 'end=2023-11-01T17:00:00'`
format: `native`

**Comment by yasvanth** [comment]
Thanks @zekker6 , I will enable `-promscrape.noStaleMarkers` on vmagent and run it for a day. Also is there a way to remove all the null values using `metricsQL`?

**Comment by yasvanth** [comment]
@zekker6  Setting `noStaleMarkers` on vmagent fixed the null value. When I exported metric on prod I saw some repeated values. 

timestamp : `-d 'start=2023-11-07T07:50:00' -d 'end=2023-11-07T08:00:00'`
scrape_interval: `1m` 

vmagent HA settings
<pre>
      - '--promscrape.cluster.memberNum=0'
      - '--promscrape.cluster.membersCount=3'
      - '--promscrape.cluster.replicationFactor=3'
 </pre>

`Pro` - has duplicates/repitation
<pre>
{
    "metric": {
        "__name__": "interfaces_interface_state_counters_in_octets",
        "job": "streaming-telemetry",
        "instance": "g",
        "interface_name": "et",
        "source": "core1-pw",
        "subscription_name": "sub1"
    },
    "values": [
        7490505581319902,
        7490880214003752,
        7491138962497483, <----
        7491138962497483, <----
        7491538637056988,
        7491949669726378, <----
        7491949669726378, <----
        7492373543259190,
        7492791376165734, <-----
        7492791376165734 <-----
    ],
    "timestamps": [
        1699354241510,
        1699354301510,
        1699354361510,
        1699354386760,
        1699354481510,
        1699354541510,
        1699354566760,
        1699354661510,
        1699354721510,
        1699354746760
    ]
}
</pre>



`staging` - No repetition
<pre>
{
    "metric": {
        "__name__": "interfaces_interface_state_counters_in_octets",
        "job": "streaming-telemetry",
        "instance": "g",
        "interface_name": "et",
        "source": "core1-pw",
        "subscription_name": "sub1"
    },
    "values": [
        7448151713445856,
        7448182429865091,
        7448213721051082,
        7448246763021913,
        7448282348998274,
        7448317545869166,
        7448357184473145,
        7448396069109588,
        7448438504012523,
        7448480860930021
    ],
    "timestamps": [
        1699343441510,
        1699343501510,
        1699343561510,
        1699343621510,
        1699343681510,
        1699343741510,
        1699343801510,
        1699343861510,
        1699343921510,
        1699343981510
    ]
}
</pre>

**Comment by zekker6** [comment]
@yasvanth For this vmagent configuration it is required to enable deduplication at `vmselect` and `vmstorage`(see [this](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#deduplication) for reference).
It is required to add the following flag to both `vmselect` and `vmstorage`: `-dedup.minScrapeInterval=1ms`

**Comment by jiekun** [comment]
Close as answered.
