### ISSUE TITLE
[VMAlert] How to make VMAlert and Alertmanager resend notification after finished keep_firing_for period?

### ISSUE THREAD

**Issue by tantm3** [VictoriaMetrics/VictoriaMetrics#5247]
### Is your question request related to a specific component?

Component: VMAlert & Alertmanager
Version: v1.93.2

### Describe the question in detail

I am using the VMAlert to monitor the Kubernetes Cluster.
In the alert definitions, I used the `keep_firing_for` option to force VMAlert not to send a `resolved state` because the metric data may be slightly delayed. Here is the configuration:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: vmalert-rules-config
data:
  alert-rules.yaml: |
    groups:
      - interval: 60s
        name: missing-points
        rules:
        - alert: Missing Metric Data (UNDETERMINED)
          annotations:
            message: 'missing datapoint (test_metric_1): {{ $labels.hostname }}'
            summary: 'missing datapoint (test_metric_1): {{ $labels.hostname }}'
          expr: count(test_metric_1 offset 2m) by (hostname) unless count(test_metric_1) by (hostname) > 0
          for: 1m
          labels:
            dev: "undetermined"
          debug: true
      - name: test.rule
        interval: 60s
        rules:
        - alert: 'Alert test firing'
          annotations:
            message: 'Alert test firing > 1 host: {{ $labels.hostname }}'
            summary: 'Alert test firing > 1 host: {{ $labels.hostname }}'
          expr: sum by (hostname)(sum_over_time(test_metric_1[1m])) > 1 
          for: 1m
          labels:
            dev: "true"
          keep_firing_for: 3m
          debug: true
```
The `keep_firing_for` logic has worked fine, but I think it still lacks something.
When the metric data exceed the threshold, the alarm state is changed from `resolved` => to `firing`. In the next evaluation interval, the data is delayed and the alarm state is `keep_firing_for`. It's still fine until the data returns and the value exceeds the alert threshold `(firing state)`. I think the firing state is sent to Alertmanager, but Alertmanager checks that the old state (before keep_firing_for period) is `firing` and now it's also `firing`, so it's flushing the alert and we lose an alert state.

So, Is there a way to implement this logic from the VMAlert component?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
>I think the firing state is sent to Alertmanager, but Alertmanager checks that the old state (before keep_firing_for period) is firing and now it's also firing, so it's flushing the alert and we lose an alert state.

I'm not sure I understand the "losing alert state" here, you mean things like `Value`?
If it is, I don't think we can retrieve that because we don't retry evaluation, `keep_firing_for` only allows alert to stay active until the system truly stabilizes and prevents the alert itself from getting resolved across a bridge of data-less time. 

>In the alert definitions, I used the keep_firing_for option to force VMAlert not to send a resolved state because the metric data may be slightly delayed.

If the data is slightly delayed, are you sure the firing state is keeping because of `keep_firing_for` instead of the evaluation query get the old value? Since query request can fetch data from `[now, now()-5m]` by default, see https://docs.victoriametrics.com/keyConcepts.html#instant-query.
And if the data delay is regular, you can try increasing `-search.latencyOffset`[default is 30s] instead of using `keep_firing_for`, see https://docs.victoriametrics.com/vmalert.html#data-delay.

**Comment by tantm3** [comment]
> I'm not sure I understand the "losing alert state" here, you mean things like Value?

I thought that we missed a notification when VMAlert changes from `keep_firing_for` to a stable `firing state`. But it seems like it's a bad idea because we don't need to duplicate the `firing state`.

Actually, I am trying to understand a scenario here:
- I have two alert rules:
Alert 1. for checking no-data
Alert 2. for normal alert (something like disk usage > 20%) - This one here `using keep_firing_for option` to keep alert not changed to resolved state in case we have no data
- When we enter a no-data period, I will receive `a no-data notification` from Alert 1.
Alert 2 enters the `keep_firing_for state`, and then the data comes back, `I would like to receive again an alert state from Alert 2`.  But, in fact, we have not received any notification message here because the `last state keep_firing_for is firing state` and now `it's also firing` => the Alertmanager not sending notification message.

**Comment by Haleygo** [comment]
Oh, thanks for the explanation!
>I would like to receive again an alert state from Alert 2. But, in fact, we have not received any notification message here because the last state keep_firing_for is firing state and now it's also firing => the Alertmanager not sending notification message.

I don't think alertmanager should resend the firing message here, since alert state is unchanged. 
For now, we use `keep_firing_for` to stabilize alert resolution on vmalert side which reduce resolved messages from alertmanager, and we have this `Stabilizing` mark on vmalert ui.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/e26d5122-17e3-4229-807e-a6e2c1d15de9)

I think we should fix the [startsAt](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/notifier/alertmanager_request.qtpl#L12) in [message](https://prometheus.io/docs/alerting/latest/clients/) that vmalert sends to alertmanager, since it should be updated. But it still won't make alertmanager to resend notification since it use alert's labels to distinguish alerts.

**Comment by Haleygo** [comment]
>I think we should fix the [startsAt](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/notifier/alertmanager_request.qtpl#L12) in [message](https://prometheus.io/docs/alerting/latest/clients/) that vmalert sends to alertmanager, since it should be updated.
Seem like we shouldn't update `startsAt` under this situation too, see https://github.com/prometheus/prometheus/pull/13053#issuecomment-1787931681.

**Comment by buihuudang2000** [comment]
> > I think we should fix the [startsAt](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/notifier/alertmanager_request.qtpl#L12) in [message](https://prometheus.io/docs/alerting/latest/clients/) that vmalert sends to alertmanager, since it should be updated.
> 
> Seem like we shouldn't update `startsAt` under this situation too, see [prometheus/prometheus#13053 (comment)](https://github.com/prometheus/prometheus/pull/13053#issuecomment-1787931681).

I also have similar issue. I want alertmanager to send a message after miss-data whether the message is ok or fired. Is there any way?

**Comment by Haleygo** [comment]
> > > I think we should fix the [startsAt](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/notifier/alertmanager_request.qtpl#L12) in [message](https://prometheus.io/docs/alerting/latest/clients/) that vmalert sends to alertmanager, since it should be updated.
> > 
> > 
> > Seem like we shouldn't update `startsAt` under this situation too, see [prometheus/prometheus#13053 (comment)](https://github.com/prometheus/prometheus/pull/13053#issuecomment-1787931681).
> 
> I also have similar issue. I want alertmanager to send a message after miss-data whether the message is ok or fired. Is there any way?

No, you shouldn't use `keep_firing_for` if you need to know the difference between `real firing` and `stabilizing firing` from alertmanager.

**Comment by tantm3** [comment]
> No, you shouldn't use `keep_firing_for` if you need to know the difference between `real firing` and `stabilizing firing` from alertmanager.

I agree with this comment here, VMAlert uses `keep_firing_for` to not `spam the resolved state`, so it's quite not relevant to do the no-data state logic in the VMAlert component.
Is there any way that we can call the VMAlert component and reset the alert state?
I have an idea that we will trigger directly VMAlert to reset the alert state. Then, the VMAlert will send the new alert message and the Alertmanager will also send a new alert.

**Comment by Haleygo** [comment]
>I have an idea that we will trigger directly VMAlert to reset the alert state. Then, the VMAlert will send the new alert message and the Alertmanager will also send a new alert.

No, as said [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5247#issuecomment-1787114875), alertmanager won't take alert as new alert if they have the same labelset(the labels from rule's expr result). if you changed some label, alertmanager will see them as different alerts and resolve the previous one when `EndAt` comes.

**Comment by tantm3** [comment]
Oh, I see, sorry I did not read it carefully.
I think cheating Alertmanager to send a whole new alert is not possible. So, Could we do something like trigger VMAlert to send an alarm message that makes Alertmanager resend a `firing alarm message` even though the last state in the Alertmanager is `firing` **(all alarm message comes from the alert rule)**?

**Comment by tantm3** [comment]
Thanks for all of your detailed explanations!
It's wrong to apply the resending alert after the keep_firing_for period flow because as you said, the user cannot know whether it's a real alert or a repeated one. 
I will close the discussion here because we have many documents to understand the question.
