### ISSUE TITLE
Why I get this error

### ISSUE THREAD

**Issue by rookie-fpc** [VictoriaMetrics/VictoriaMetrics#5248]
### summary

I deployed a single-node cluster. but seems i cannot get the data

### Describe the question in detail

 My prometheus configuration is below:

remote_write:
\- url: "http://10.62.169.124:8480/insert/1/prometheus/api/v1/write"

start command of vmstorage:
/usr/local/bin/vmstorage -storageDataPath /victoriametrics -httpListenAddr 10.62.169.124:8482 -vminsertAddr 10.62.169.124:8400 -vmselectAddr 10.62.169.124:8401 -dedup.minScrapeInterval 180s

start command of vminsert:
/usr/local/bin/vminsert -httpListenAddr 10.62.169.124:8480 -storageNode 10.62.169.124:8400  -loggerLevel INFO

start aommand of vmselect:
/usr/local/bin/vmselect -httpListenAddr 10.62.169.124:8481 -selectNode 10.62.169.124:8481 -storageNode 10.62.169.124:8400 -dedup.minScrapeInterval 180s

when i access http://10.62.169.124:8481/select/1/vmui
It shown me this: 
503
cannot obtain values for label "job": cannot fetch label values from vmstorage nodes: cannot get label values from vmstorage 10.62.169.124:8400: cannot obtain connection from a pool: cannot perform "vmselect" handshake with server "10.62.169.124:8400": cannot read success response after sending hello: cannot read message with size 2: EOF; read only 0 bytes

Is there something wrong I setup?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by rookie-fpc** [comment]
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/75996252/ef3d1f06-45f5-4710-9ead-f5119c75ade8)

**Comment by Amper** [comment]
Hey, @rookie-fpc.

You should change value of `storageNode` for `vmselect` from `10.62.169.124:8400` to `10.62.169.124:8401`, the value of `vmselectAddr` flag for vmstorage must be specified there:

```
/usr/local/bin/vmselect -httpListenAddr 10.62.169.124:8481 -selectNode 10.62.169.124:8481 -storageNode 10.62.169.124:8401 -dedup.minScrapeInterval 180s
```

**Comment by rookie-fpc** [comment]
Hi @Amper 
Thank you for your answer. I can use VictoriaMecrics Cluster now.
