### ISSUE TITLE
vmalert: add ability to limit the number of decimal digits after the point in recording rules' calculations

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#525]
**Is your feature request related to a problem? Please describe.**
[Recording rules](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule) in [vmalert](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/README.md) 
may generate floating-point values with many decimal digits after the point. For instance, `1/3=0.3333333333333333`. Time series generated by such recording rules have bad compression ratio.

**Describe the solution you'd like**
It is usually enough to have much smaller number of decimal digits after the point for recording rules' results (up to 3 decimal digits after the point in practical cases). Time series with such values have much better compression rate comparing to values with 15 decimal digits after the point (5x better compression for 15 vs 3 decimal points case). So it would be great to have `-decimalDigitsAfterPoint` command-line flag in `vmagent` in order to limit the number of decimal digits in recording rules' results.

**Describe alternatives you've considered**
It is possible to wrap recording rule expressions into [round() function](https://prometheus.io/docs/prometheus/latest/querying/functions/#round) in order to limit the number of decimal digits after the point. But this is user-unfriendly and error-prone approach.

**Comment by valyala** [comment]
This has been implemented in `vmagent` in the release [v1.56.0](https://docs.victoriametrics.com/CHANGELOG.html#v1560) -  `vmagent` now supports `-remoteWrite.roundDigits` command-line flag. Additionally to this, `vmalert` can pass `round_digits=N` query arg to `/api/v1/query` in order to round results to up to N decimal digits after the point.

**Comment by hagen1778** [comment]
This has been implemented and released in https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.60.0

**Comment by valyala** [comment]
Values in responses to alerting and recording rules can be rounded with `-datasource.roundDigits` command-line flag starting from [v1.60.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). For example, `/path/to/vmalert -datasource.roundDigits=2` would round recording rule results to 2 decimal digits after the decimal point. Note that this functionality works only when `-datasource.url` points to VictoriaMetrics, which supports `round_digits` query arg in requests to `/api/v1/query` as described [here](https://docs.victoriametrics.com/#prometheus-querying-api-enhancements).
