### ISSUE TITLE
Change indexdb and data location for vm storage

### ISSUE THREAD

**Issue by waleedabdelwahed89** [VictoriaMetrics/VictoriaMetrics#5255]
### Is your question request related to a specific component?

vmstorage

New path (wrong one):
<img width="1266" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55146056/f454c135-e150-470d-8f58-473f91ecb8fb">
<img width="692" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55146056/f0aec6c3-c3bf-431c-91f9-3bf705d8c380">

Old Path (correct one):
<img width="919" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/55146056/9d6053d1-5771-4373-a40d-06e4b1b58482">

### Describe the question in detail

We have a VM cluster running on multiple nodes, each node has two local file systems

Ideally the data should be written to "/server/victoria-metrics/data" FS according to the configuration

-storageDataPath /server/victoria-metrics/data

For some reason the data has is now being written to a different file system "/home/victoria-metrics" FS

I'm still trying to figure out why this's happening

The question is, how to enforce the write operation to a different storage (keeping in mind the storageDataPath is already pointing to the correct path), and how to merge the data written in the both locations, as we can't afford data loss

Any quick advise or tips will be appreciated before the FS gets full

Thank you

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> The question is, how to enforce the write operation to a different storage (keeping in mind the storageDataPath is already pointing to the correct path)

VictoriaMetrics process isn't aware of filesystem or attached disks. It is relying on interaction with OperatingSystem via SysCalls. If VM was configured to use `/server/victoria-metrics/data` then there is no way it could have tried to use different path instead. It is only a responsibility of OS settings and configuration flags.

>  how to merge the data written in the both locations, as we can't afford data loss

You can try running two separate clusters configured with different storagePath. Then [export](https://docs.victoriametrics.com/#how-to-export-data-in-native-format) data from each cluster and [import](https://docs.victoriametrics.com/#how-to-import-data-in-native-format) it to a new cluster.

**Comment by waleedabdelwahed89** [comment]
Hi @hagen1778 , many thanks for your answer
I've rectified the issue and now the data is being written in the desired path, i'll check the missing data part and see how it goes
Will close this for now

Thanks again
