### ISSUE TITLE
promQL opetrate two metric with same labels, but different label-val combiantions,

### ISSUE THREAD

**Issue by Hello-World-0X** [VictoriaMetrics/VictoriaMetrics#5259]
### Is your question request related to a specific component?

promQL

### Describe the question in detail

English version:

I have to metric one metric is total count, another is error count, they have same labels, but different label-val combination, total count metric's label-vals combinations mush constains error count metric's label-val combination,such as:

total count metric:
```
    method_totalCall{host="h1", dst="a1", src="a2"}@t1 = 24
    method_totalCall{host="h1", dst="b1", src="b2"}@t1 = 30
    method_totalCall{host="h1", dst="c1", src="c2"}@t1 = 3
    method_totalCall{host="h1", dst="d1", src="d2"}@t1 = 6
    method_totalCall{host="h1", dst="e1", src="e2"}@t1 = 21
```
this metric means method call count in $host from $src to $dest

error count metric:
```
    method_totalCall_ERROR{host="h1", dst="c1", src="c2"}@t1 = 1
    method_totalCall_ERROR{host="h1", dst="d1", src="d2"}@t1 = 2
    method_totalCall_ERROR{host="h1", dst="e1", src="e2"}@t1 = 3
```
this metric means method call error count in `$host` from `$src` to `$dest`

i want to get a metric which means method call success count in `$host` from `$src` to `$dest`
so i write a promQL:

   ` method_totalCall{host='h1'} - method_totalCall_ERROR{host='h1'}`

but
if i use promQL :

   ` method_totalCall{host='h1'} - method_totalCall_ERROR{host='h1'}`

I will get a new temporary metric :
```
    methed_succ_count{host="h1", dst="c1", src="c2"}@t1 = 2 
    methed_succ_count{host="h1", dst="d1", src="d2"}@t1 = 4
    methed_succ_count{host="h1", dst="e1", src="e2"}@t1 = 18

    (come from:method_totalCall{host="h1", dst="c1", src="c2"}@t1 - method_totalCall_ERROR{host="h1", dst="c1", src="c2"}@t1)
    (come from:method_totalCall{host="h1", dst="d1", src="d2"}@t1 - method_totalCall_ERROR{host="h1", dst="d1", src="d2"}@t1)
    (come from:method_totalCall{host="h1", dst="e1", src="e2"}@t1 - method_totalCall_ERROR{host="h1", dst="e1", src="e2"}@t1)
```
but for label
```
    {host="h1", dst="a1", src="a2"}
    {host="h1", dst="b1", src="b2"}
```
value missed in new metric. which means i doesn't get the sucess count in host h1 from  from specific `$src(a1, b1)` to specific `$dest(a2,b2)`.how should I modify promQL? i want get val like this:
```
    methed_succ_count{host="h1", dst="a1", src="a2"}@t1 = 24
    methed_succ_count{host="h1", dst="b1", src="b2"}@t1 = 30
    methed_succ_count{host="h1", dst="c1", src="c2"}@t1 = 2 
    methed_succ_count{host="h1", dst="d1", src="d2"}@t1 = 4
    methed_succ_count{host="h1", dst="e1", src="e2"}@t1 = 18
```
which means when no error occur on host h1 from some specific `$src(a1, b1)` to specific `$dst (a2,b2)`， error count is zero from `(a1,b1)` to `(a2, b2)`, success count from `(a1, b1)` to `(a2, b2)` is total count.

the tsdb i used is victoriametrics.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @Hello-World-0X ! When you make `-` operation, it will check all labels in your metrics and will return result where labels will be the same. You can try to add `default 0` after your `method_totalCall_ERROR{host='h1'}` for example to try to use 
https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators

**Comment by Hello-World-0X** [comment]
@dmitryk-dk first of all, thanks a lot, i try your instruction, after modified, my promQL become ```(method_totalCall{host='h1'}) - (method_totalCall_ERROR{host='h1'}) default 0```
default 0 only refill data on those label-label_val combination which both method_totalCall  and method_totalCall_ERROR are exactly same, in my example that is 
```
{host="h1", dst="c1", src="c2"}, 
{host="h1", dst="d1", src="d2"},
{host="h1", dst="e1", src="e2"},
```
method_totalCall and method_totalCall_ERROR are exactly same

finally, I resolve my question with this promQL:
``` metricA - MetricB or MetricA```

**Comment by dmitryk-dk** [comment]
Hi @Hello-World-0X ! Thank you for your question
Close as resolved!
