### ISSUE TITLE
vmalert: add `file` label to alert metrics

### ISSUE THREAD

**Issue by antoinedeschenes** [VictoriaMetrics/VictoriaMetrics#5267]
### Is your feature request related to a problem? Please describe

I'm trying to provide diagnostic information about dead alerting rules in a Grafana dashboard, but I find there are many duplicate rows in the metrics output. The following rules come from VMRule CRDs installed in every namespaces with a namespace filter. Tracing them back to their origin would require parsing the vmalert API rules endpoint, but the Grafana instance doesn't have access to the vmalert instances. 
```
vmalert_alerting_rules_last_evaluation_series_fetched{alertname="KubePodCrashLooping", group="kubernetes-apps", id="11270992714369453245"} 6
vmalert_alerting_rules_last_evaluation_series_fetched{alertname="KubePodCrashLooping", group="kubernetes-apps", id="11403117063922463493"} 2
vmalert_alerting_rules_last_evaluation_series_fetched{alertname="KubePodCrashLooping", group="kubernetes-apps", id="11799760525998906717"} 9
vmalert_alerting_rules_last_evaluation_series_fetched{alertname="KubePodCrashLooping", group="kubernetes-apps", id="12126577122588019062"} 3
```

### Describe the solution you'd like

Add the file label to rule metrics, similarly to `vmalert_iteration_*` metrics, or add `group_id` along `group` in both cases. I'll be able to trace back to the namespace and vmrule name using the file label from there. 

```
vmalert_iteration_total{group="kubernetes-apps", file="/etc/vmalert/config/vm-vmstack-rulefiles-2/ops-kubernetes-alerts.yaml"} 3972
vmalert_iteration_total{group="kubernetes-apps", file="/etc/vmalert/config/vm-vmstack-rulefiles-2/osr-consumer-default-rules.yaml"} 3972
vmalert_iteration_total{group="kubernetes-apps", file="/etc/vmalert/config/vm-vmstack-rulefiles-2/partner-pixel-default-rules.yaml"} 3972
```

### Describe alternatives you've considered

- Prefixing group names with `<namespace>-<vmrule_name>-`
- Write an exporter for vmalert to output alert ids matching group names and filenames.

**Comment by valyala** [comment]
The `file` label is available in `vmalert_recording_rules_error`, `vmalert_recording_rules_last_evaluation_samples`, `vmalert_alerts_pending`, `vmalert_alerts_firing`, `vmalert_alerting_rules_error`, `vmalert_alerting_rules_last_evaluation_samples` and `vmalert_alerting_rules_last_evaluation_series_fetched` metrics [exposed by vmalert](https://docs.victoriametrics.com/vmalert.html#monitoring) since [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the feature request as done.
