### ISSUE TITLE
Enterprise licence for homelab users (hobbysts not making money just using this for fun of it) 

### ISSUE THREAD

**Issue by atropos112** [VictoriaMetrics/VictoriaMetrics#5278]
### Is your question request related to a specific component?

VictoriaMetrics Enterprise

### Describe the question in detail

I am a homelab user and am using VictoriaMetrics for hobby reasons, I make no money of it, no money of the infrastructure I am monitoring it with nor I will ever make money of my k8s cluster at home. 

Obviously when I see something like VictoriaMetrics my eyes light up, I see enterprise features (like vmanomaly) and i want to play with this also, understanding they are behind the licence however.

As a user that makes no money of this (directly or indirectly) I am not going to purchase the enterprise licence. I wonder if for such users (homelab/hobbysts) you offer the licence (without the support obviously). Having such licence 

- If i see a bug I will report it
- If company I work for will look for such solution I would propose VictoriaMetrics (I would propose it regardless if I am given the licence to be honest, I really enjoy your product)

I understand these two points are not "much" but I also don't see you losing anything from this either (how many homelab users would purchase the enterprise edition?).

Please feel free to tell me to go away if your business model doesn't match this and you have no desire pursuing this, I would understand and respect your decision as I realise I am not adding "that" much to the table here, kind of selfishly wanting to play with it is all.

**Comment by hagen1778** [comment]
Hello @atropos112! Have you requested license here https://victoriametrics.com/products/enterprise/trial/ ?
If yes, I believe you'll get in contact soon.

**Comment by tenmozes** [comment]
Hi @atropos112 we would be happy to provide the personal license for free, please email me at artem{@}victoriametrocs.com

**Comment by atropos112** [comment]
> Hello @atropos112! Have you requested license here https://victoriametrics.com/products/enterprise/trial/ ? If yes, I believe you'll be contacted soon.

I think that trial is very generous, more than enough time for me to play around with it and test it. In particular for a company/enterprise prospect this is perfect as the company can test its capabilities and decide if they want to pursue or not.

If I am a homelab user, I will spend a long time playing with it, seeing how it "ticks", eventually once I figure out its capabilities and potential I will probably want to implement this into my home infrastructure (that heavily relies on VictoriaMetrics already), knowing that in few weeks time I have to take it out once my trial runs out. This is a very powerful incentive for a company to invest into enterprise licence, for a homelab user this is the end of that road.
