### ISSUE TITLE
When using /api/v1/import to push json data to vmagent, when the amount of data is large, there are not enough ports.

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5280]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

When I have a lot of series, about 100,000, every time the series has data points, I push data to vmagent by /api/v1/import. This will establish a lot of TCP connections, and the ports will not be enough. 

Are there any recommended practices for using tcp connections similar to streaming mode?
 I want to push the data to vmagent, not the streaming mode of collection.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @luzejia! Each supported ingestion protocol (except Prometheus Remote Write protocol) supports streaming by default. You can batch 100k series in one request and send it via one connection. Actually, this is a recommended way to push the data. See https://docs.victoriametrics.com/#json-line-format

**Comment by luzejia** [comment]
> Hello @luzejia! Each supported ingestion protocol (except Prometheus Remote Write protocol) supports streaming by default. You can batch 100k series in one request and send it via one connection. Actually, this is a recommended way to push the data. See https://docs.victoriametrics.com/#json-line-format

thanks!

**Comment by hagen1778** [comment]
>  Does it mean streaming the same big data to be transmitted or does it mean that the connection can be maintained and data can be written continuously?

I used streaming in the wrong sense here. Streaming means that vminsert will continiously read from the connection, line-by-line, not waiting for payload to end. Hence, the client can start sending 100MiB request payload.

> For example, the scenario is that there are 100k series every 10 seconds.

I'm not sure how can I provide such an example. In your client, define a batch struct which would maintain a buffer to accumulate single write to it. Periodically, make the batch to flush its content to the remote destination. Something like this https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/remotewrite/client.go

**Comment by luzejia** [comment]
> > Does it mean streaming the same big data to be transmitted or does it mean that the connection can be maintained and data can be written continuously?
> 
> I used streaming in the wrong sense here. Streaming means that vminsert will continiously read from the connection, line-by-line, not waiting for payload to be completely transferred. The client can start sending 100MiB request payload, and server will start processing it immediately, with no wait for all 100MiB to be read.
> 
> > For example, the scenario is that there are 100k series every 10 seconds.
> 
> I'm not sure how can I provide such an example. In your client, define a batch struct which would maintain a buffer to accumulate single write to it. Periodically, make the batch to flush its content to the remote destination. Something like this https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmalert/remotewrite/client.go

Thanks!
