### ISSUE TITLE
[VMAgent] Error decompressing zstd-encoded request

### ISSUE THREAD

**Issue by PrarthiJain** [VictoriaMetrics/VictoriaMetrics#5301]
### Describe the bug

Encountering an error with vmagent where it fails to decompress zstd-encoded blocks from the persistent queue leading to a skipping of the data block and subsequent data loss.

Environment
victoriametrics/vmagent:v1.91.0
VictoriaMetrics version: v1.91.0
vminsert version: v1.91.2-cluster
vmstorage version: v1.91.2-cluster
Deployment method: Kubernetes

Configuration
`  
> - args:
>     - -enableTCP6=true
>     - -http.pathPrefix=/vmagent2
>     - -httpListenAddr=:8429
>     - -promscrape.config=/etc/vmagent/config_out/vmagent.env.yaml
>     - -promscrape.streamParse=true
>     - -remoteWrite.label=cluster=cluster-name
>     - -remoteWrite.maxDiskUsagePerURL=0
>     - -remoteWrite.queues=4
>     - -remoteWrite.tmpDataPath=/vmagent_pq/vmagent-remotewrite-data
>     - -remoteWrite.url=http://observability-internal.gcp.dex.ai/insert/0/prometheus/api/v1/write
>     - -remoteWrite.urlRelabelConfig=/etc/vm/relabeling/url_relabeling-0.yaml

    `

### To Reproduce

1. vmagent scrape metrics from services (some services are down) and remote writes to the endpoint.
2. The remote write endpoint becomes unreachable, triggering vmagent to write to the persistent queue.
3. Once the endpoint is back online, vmagent attempts to push the queued data and errors occur.

### Version

victoriametrics/vmagent:v1.91.0
VictoriaMetrics version: v1.91.0
vminsert version: v1.91.2-cluster
vmstorage version: v1.91.2-cluster

### Logs

vmagent 2023-11-06T20:31:06.878Z error VictoriaMetrics/app/vmagent/remotewrite/client.go:400 sending a block with size 398962 bytes to "1:secret-url" was rejected (skipping the block): status code 400; response body: remoteAddr: "10.202.0.12:45134", X-Forwarded-For: "10.1.2.10,10.200.140.202"; requestURI: /insert/0/prometheus/api/v1/write; cannot decompress zstd-encoded request with length 398962: decompression error: Unknown frame descriptor

### Screenshots
<img width="1728" alt="Screenshot 2023-11-07 at 12 59 27 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/46317159/37ef6ae0-f338-4cf8-9702-8c900f6b603b">

<img width="1728" alt="Screenshot 2023-11-07 at 12 56 30 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/46317159/8f6e38b7-6850-4cc6-82f6-f092b4c82cfc">

<img width="1728" alt="Screenshot 2023-11-07 at 12 56 56 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/46317159/1b6bb10b-6321-4cd2-99d8-1122f6060ffc">

<img width="1728" alt="Screenshot 2023-11-07 at 12 57 15 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/46317159/f103b2e4-9d9a-450b-a22e-c8ac4eaa212b">

<img width="1728" alt="Screenshot 2023-11-07 at 12 57 30 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/46317159/3517ff58-273f-482e-bbc6-c4b7c8a028df">

**Comment by f41gh7** [comment]
Issue related to the auto-protocol negotiation mechanics. On start-up vmagent sends http request to the remote target and if it replies correctly, it uses zstd encoding. If no reply was received, it fall backs to the standard snappy.

Main problem with it, encoding applied before data block was written into persistent queue. It makes impossible to correctly process persistent queue content, if vmagent was restarted.

 Current work-around, enable flag - `remoteWrite.forcePromProto=true` for remote write targets.

**Comment by PrarthiJain** [comment]
Thank you @f41gh7 for the workaround.

**Comment by valyala** [comment]
@PrarthiJain , thanks for filing the issue! It has been appeared that VictoriaMetrics and vmagent can gracefully handle this case by switching to Snappy decoding when zstd decoding fails. This has been implemented in the commit 12cd32fd75706969f972a328e8583ca1da9e68c3 . This commit will be included in the next release. In the mean time it is possible to test this fix by building vmselect from this commit according to [these instructions](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by valyala** [comment]
FYI, the bugfix has been included in [v1.93.8 LTS release of vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.8).

**Comment by valyala** [comment]
The bugfix has been included in [v1.95.0 release](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.

**Comment by Haleygo** [comment]
@valyala What if things were reversed? 
1. vmagent successfully performed handshake with the -remoteWrite.url and the remote storage supports zstd-compressed data.
2. remote storage became unavailable or slow to ingest data, vmagent compressed the collected data into blocks with zstd and puts these blocks to persistent queue on disk.
3. vmagent restarts and the remote storage is unavailable during the handshake, then vmagent falls back to Snappy compression.
4. vmagent starts sending zstd-compressed data from persistent queue to the remote storage, while falsely advertizing it sends Snappy-compressed data.
5. The remote storage receives zstd-compressed data and fails unpacking it with Snappy.

Should be fixed with the same way as this one.

**Comment by valyala** [comment]
@Haleygo , yes, this case is also possible! Thanks for providing the fix at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5344 !

**Comment by valyala** [comment]
FYI, the fix for the issue described [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5301#issuecomment-1815871992) has been included in [v1.93.9 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.9).

**Comment by valyala** [comment]
The fix for [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5301#issuecomment-1815871992) has been included in the release [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html).
