### ISSUE TITLE
metric for vmagent like prometheus_target_scrape_pool_targets

### ISSUE THREAD

**Issue by datamuc** [VictoriaMetrics/VictoriaMetrics#5311]
### Is your feature request related to a problem? Please describe

I want to identify scrape jobs that do not discover any targets. I can do that by going to the /targets endpoint and search for "0/0 up". But a metric for that would be great, so I can have an alert rule for that.

It serves to purposes, I can identify scrape_jobs that are probably not needed anymore, and I can detect some  misconfigurations pretty easily.

### Describe the solution you'd like

Implement a metric like prometheus [prometheus_target_scrape_pool_targets](https://prometheus.demo.do.prometheus.io/graph?g0.expr=prometheus_target_scrape_pool_targets&g0.tab=1&g0.stacked=0&g0.range_input=1h)

### Describe alternatives you've considered

I can monitor the /targets endpoint somehow. But that is a manual process. Or I can go through the config and write an alert for each scrape config manually, but that is error prone (everytime I add a new servicescrape for example I need to create a specific alert for that).

**Comment by Haleygo** [comment]
For now, vmagent exposes [vm_promscrape_active_scrapers](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/scraper.go#L329){type="SD type"} and [vm_promscrape_targets](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/ba058a45147042a4fbbb6e6707253703633034ef/lib/promscrape/scraper.go#L335C19-L335C19){type="SD type", status=up/down}, which are overlapped and don't help much for cases like here.
So I think we can remove `vm_promscrape_active_scrapers` and add `job_name` label for `vm_promscrape_targets`.

**Comment by mkilchhofer** [comment]
@valyala thank you for the fast implementation. I handed this info over to my colleagues. My work effort is already over for 2023, my vacation already started 😆.
