### ISSUE TITLE
vmstorage memory consumption increases over time without any changes to the cluster

### ISSUE THREAD

**Issue by a26nine** [VictoriaMetrics/VictoriaMetrics#5314]
### Describe the bug

The vmstorage pods memory usage increases with every passing day. [[Discussion](https://t.me/VictoriaMetrics_en/4602)]

### To Reproduce

Just running Victoria Metrics Cluster as is with arguments:
```
dedup.minScrapeInterval: 1ms
retentionPeriod: 1y
```

### Version

1.94.0

### Screenshots

![Snap-20231113-090925@2x](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/103454930/d4e19b4e-bd1e-4879-bfca-a8aaa71b0ba6)

![Snap-20231113-090825@2x](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/103454930/266617a3-7269-478d-956f-dfbe2dbdf28a)

![Snap-20231113-090405@2x](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/103454930/4f4745be-a8b0-4ab9-ac16-f65acdcc8a19)

### Additional information

Some of the high memory usage pods have regular restarts too.

**Comment by dmitryk-dk** [comment]
Hi @a26nine !
The graph for anonymous memory usage looks OK - it stays stable around 13GB after November 4 till November 12. This suggests that there are no memory leaks in vmstorage. The anonymous memory is the memory allocated by the application itself.

The RSS memory usage shows the amounts of memory, which is recently accessed by the application. It includes anonymous memory. It also includes the operating system page cache memory, which contains data recently read from files. The growth of RSS means that vmstorage accesses more and more data from files. This may point to inefficient queries, which select large volumes of data over long periods of time. This may be some SLO/SLI alerting queries with big lookbehind windows in square brackets. For example, avg_over_time(up[30d]) < 0.99. Another possible case for growing rss memory usage is frequentle refreshed graphs in Grafana over long periods of time.

The solution is to reduce the lookbehind window in square brackets, so vmstorage could read lower amounts of data during the execution of the query. Another solution is to add more specific filters for selecting lower number of time series and reducing the amounts of data, which needs to be read during query execution.

See also https://docs.victoriametrics.com/Troubleshooting.html

**Comment by a26nine** [comment]
> Hi @a26nine ! The graph for anonymous memory usage looks OK - it stays stable around 13GB after November 4 till November 12. This suggests that there are no memory leaks in vmstorage. The anonymous memory is the memory allocated by the application itself.
> 
> The RSS memory usage shows the amounts of memory, which is recently accessed by the application. It includes anonymous memory. It also includes the operating system page cache memory, which contains data recently read from files. The growth of RSS means that vmstorage accesses more and more data from files. This may point to inefficient queries, which select large volumes of data over long periods of time. This may be some SLO/SLI alerting queries with big lookbehind windows in square brackets. For example, avg_over_time(up[30d]) < 0.99. Another possible case for growing rss memory usage is frequentle refreshed graphs in Grafana over long periods of time.
> 
> The solution is to reduce the lookbehind window in square brackets, so vmstorage could read lower amounts of data during the execution of the query. Another solution is to add more specific filters for selecting lower number of time series and reducing the amounts of data, which needs to be read during query execution.
> 
> See also https://docs.victoriametrics.com/Troubleshooting.html

Thanks @dmitryk-dk for sharing insights and confirming that there's no memory leak. @dmitryk-dk, please feel free to close this issue at your discretion.

**Comment by dmitryk-dk** [comment]
Thank you for your question!
Close as resolved!
