### ISSUE TITLE
vmselect: how to get recently written data

### ISSUE THREAD

**Issue by dw130** [VictoriaMetrics/VictoriaMetrics#5315]
### Describe the question in detail

Hi,I hava a question 

write point at 00:00:00 and query out  the point at 00:00:30(read the write points has 30 second delay)
This data cannot be query out within 30 seconds of writing the data.

my vm config is:

-retentionPeriod=90d -storageDataPath=/home/data/vm/data   -dedup.minScrapeInterval 1ms -search.logSlowQueryDuration 10s -search.maxQueryDuration 500s -search.maxConcurrentRequests 5000 -search.maxPointsPerTimeseries 5000000

Can I  write the point and query out the point immediately？
Does any config is not set？

write point code

type MetricPoint struct {
	Metric  string            `json:"metric"`
	TagsMap map[string]string `json:"tags"`  
	Time    int64             `json:"time"`  
	Value   float64           `json:"value"` 
}

func convertOne(item *MetricPoint) (prompb.TimeSeries, error) {

	var newLabel []prompb.Label
	for k, v := range item.TagsMap {
		singleLabel := prompb.Label{}
		singleLabel.Name = k
		singleLabel.Value = v
		newLabel = append(newLabel, singleLabel)
	}

	newLabel = append(newLabel, prompb.Label{Name: “__name__”, Value: “opcai”})

	point := prompb.TimeSeries{}
	point.Labels = newLabel
	point.Samples = append(point.Samples, prompb.Sample{})
	point.Samples[0].Timestamp = item.Time * 1000
	point.Samples[0].Value = item.Value

	return point, nil
}

func buildWriteRequest(samples []prompb.TimeSeries) ([]byte, error) {

	req := &prompb.WriteRequest{
		Timeseries: samples,
	}
	data, err := proto.Marshal(req)
	if err != nil {
		return nil, err
	}
	compressed := snappy.Encode(nil, data)
	return compressed, nil
}

And my query is: max_over_time(opcai1[1s])              step is 1s
This data cannot be found within 30 seconds of writing the data.

Thanks

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @dw130!

The 30s delay on recently written data is explained here https://docs.victoriametrics.com/keyConcepts.html#query-latency
You can remove the delay by setting `-search.latencyOffset=0s` or by passing extra GET param with each query `latency_offset=0s`.

> And my query is: max_over_time(opcai1[1s]) step is 1s

The query seems odd - specifying `[1s]` look-behind makes no sense. Try querying as is `max(opcai)` instead.
Although, what's the purpose of querying the recent data?

**Comment by dw130** [comment]
@hagen1778 thanks very much!
