### ISSUE TITLE
Support of OTEL Protocol

### ISSUE THREAD

**Issue by jakirpatel** [VictoriaMetrics/VictoriaMetrics#5323]
### Is your question request related to a specific component?

Vmagent and OpenTelemetry

### Describe the question in detail

OpenTelemtry adoption is growing and Prometheus is also announced the plan to support Push based mechanism. So Is there any possibility to support OTEL protocol with vmagent? 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @jakirpatel!
OTEL push protocol for metrics is already supported by vmagent/vminsert/single-node starting from [v1.92](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.92.0)
see https://docs.victoriametrics.com/#sending-data-via-opentelemetry

**Comment by valyala** [comment]
Closing as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2424
