### ISSUE TITLE
How to reduce memory usage in storage nodes

### ISSUE THREAD

**Issue by adgarr** [VictoriaMetrics/VictoriaMetrics#5333]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

My storage node has 128G of memory and the usage rate is 80%. However, I don't want to increase the memory or storage node. How can I configure it to reduce memory usage?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by valyala** [comment]
The most common sources of high memory usage at VictoriaMetrics:

- Too big number of [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series)
- [High churn rate](https://docs.victoriametrics.com/FAQ.html#what-is-high-churn-rate)
- Heavy queries, which touch big number of time series and / or samples on long time ranges. Such queries can be monitored via [Top queries](https://docs.victoriametrics.com/#top-queries) tab at [vmui](https://docs.victoriametrics.com/#vmui).

You need to identify the source of high memory usage and then to decide how to fix it. See also https://docs.victoriametrics.com/Troubleshooting.html#out-of-memory-errors and 
https://docs.victoriametrics.com/Troubleshooting.html#monitoring for further investigation.

**Comment by jiekun** [comment]
Close as answered.
