### ISSUE TITLE
【 v1.95.1 】 VMUI autocomplete  metrics 

### ISSUE THREAD

**Issue by jicki** [VictoriaMetrics/VictoriaMetrics#5342]
### Describe the bug

* v1.94.0 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/3df81091-df4c-4d5d-bc7a-52ef57303fbd)

* v1.95.1 

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/14c5eae0-448b-40eb-a044-b81c08cb56ca)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7707585/2c9a91f8-8dcf-41f0-ac21-48f53bbbdebb)

@hagen1778 

### To Reproduce

Update v1.95.1 

VMUI   Query    

autocomplete  metrics 

### Version

vmselect-20231116-195457-tags-v1.95.1-cluster-0-g1a15b0f57

**Comment by Loori-R** [comment]
Such behavior is related to `limit` and `start`/`end`. See #5253. 
The behavior of autocomplete is proposed to be improved in #5348

**Comment by Loori-R** [comment]
This issue has been fixed in vmui starting from [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
