### ISSUE TITLE
Prettify JSON in _msg field in VictoriaLogs UI

### ISSUE THREAD

**Issue by yatskevich** [VictoriaMetrics/VictoriaMetrics#5347]

**Comment by f41gh7** [comment]
Currently, if log message has a `JSON` like field, it's not possible to prettify it's view at UI page. You have to copy it content, paste it into text redactor and prettify it.

 I suggest to introduce toggle - `Wrap JSON`. It'll try to parse and prettify content of message field at UI with some javascript lib. In case of fail, it should display original message.

**Comment by f41gh7** [comment]
Like grafana does for `Explore` page for loki datasource. 
<img width="801" alt="Screenshot 2023-12-01 at 17 20 05" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/18450869/1fb77380-ac6d-4334-ae23-d77cc91e0428">

**Comment by tenmozes** [comment]
not relevant
