### ISSUE TITLE
vmui: auto-completion usability improvements

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#5348]
### Is your feature request related to a problem? Please describe

[vmui](https://docs.victoriametrics.com/#vmui) has improved auto-completion support since [v1.95.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3006) for details. However, it has some usability issues:

1. The list of suggested items may be incomplete. In this case the usefulness of the provided auto-suggestion is negative comparing to missing auto-suggestion, since the user may think that the needed items are missing in VictoriaMetrics.
2. The auto-suggestion adds visible freezes when editing the query input field or when moving cursor in the input field. These freezes are absent when auto-suggestion is disabled.
3. The list of suggested items is updated on every keystroke in the query input field, while in reality the provided list of suggestions is needed in rare cases. All the other suggestions just distract the user who edits the query.

### Describe the solution you'd like

It would be great to resolve these issues with the following solutions:

1. If vmui receives the number of items from VictoriaMetrics, which is equal to the provided `limit` (1000 in v1.95.0), then it is better to not show the incomplete list to the user, since it only confuses the user. Instead, it is better to wait until the user enters additional chars to the query input field and then try requesting items with the updated `match[]` filter and with the same `limit=1000` from VictoriaMetrics again.

   For example, if the user enters a metric name `foo`, then `vmui` sends the request to `/api/v1/label/__name__/values?match[]={__name__=~".*foo.*"}&limit=1000` filter. If VictoriaMetrics returns less than 1000 items, then show them in the auto-suggestion. Otherwise do not show auto-suggestion and wait until the user updates the query. For example, if it adds `bar` to the query, then `vmui` can send the request to `/api/v1/label/__name__/values?match[]={__name__=~".*foobar.*"}` and show the auto-suggestion list if the number of received items is less than 1000. The same logic applies to auto-suggestions for label names and label values.

   It is important to cache auto-suggestion results at `vmui` side in order to reduce load on VictoriaMetrics and to improve auto-suggestion responsiveness while the user continues editing the query. It is important to cache queries, which return `limit=1000` items too, in order to do not send them again to VictoriaMetrics. It is important to do not send additional requests to VictoriaMetrics if `vmui` already has a list of items with the length smaller than 1000, which can be filtered out at `vmui` side without the need to send request to VictoriaMetrics. It is important to cache responses with non-200 HTTP status code. Such responses usually mean that VictoriaMetrics cannot execute the query because some resource usage limit has been exceeded (e.g. query timeout or memory usage limit). There is no sense in re-trying such queries, since they will increase load on VictoriaMetrics and return the same non-200 response.

2. Try eliminating the source of visible freezes when editing the query input field or moving the cursor inside the query input field when auto-suggestion is enabled. For example, queries to VictoriaMetrics, which are needed for auto-suggestion, must be performed in background thread, so they do not interfere with the UI thread. Another improvement, which should reduce load at VictoriaMetrics if it contains large amounts of data, is to execute requests related to auto-suggestion in serial fashion (e.g. to put them in the queue and to execute them one-by-one instead of concurrently).

3. It would be great introducing a delay in 0.5 second after the last edit event or cursor movement event inside query input field before triggering the auto-suggestion. This should reduce the amount of noise and the level of distraction for the user, who edit the query input field.

Also it would be great to be able to manually trigger the popup with suggestions at the current cursor position in the query input field when the auto-suggestion is disabled and when `ctrl+space` or `cmd+space` is pressed.

### Describe alternatives you've considered

To disable auto-suggestion and be happy :)

**Comment by f41gh7** [comment]
maybe related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5342

**Comment by valyala** [comment]
`vmui` autocomplete improvements mentioned [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5348#issue-1999190340) are implemented in [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
