### ISSUE TITLE
Victoria for Traces

### ISSUE THREAD

**Issue by eugene-chernyshenko** [VictoriaMetrics/VictoriaMetrics#5351]
### Describe the question in detail

I am very inspired by Victoria Logs. Please tell me if you plan to create a project for distributed tracing

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by mxssl** [comment]
Victoria for distributed tracing would be fantastic!

**Comment by x-0D** [comment]
+1. Victoria tracer to replace jaeger. It's should be good to be one Victoria ecosystem instead. Use case is to replace Prometheus and jaeger for use with kiali.

**Comment by jiekun** [comment]
Hi. Thanks for asking. We are currently working on Logs. There has been no progress in implementing trace functionality at the moment. However, if we do begin working on Traces, we will definitely announce it on public media. I'm closing this issue for now.

**Comment by archef2000** [comment]
Also like the idea of VictoriaTraces

**Comment by makasim** [comment]
We’re actively working on this. You can track our progress here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8148
