### ISSUE TITLE
vm-storage slow insertion every night resulting in false alerts

### ISSUE THREAD

**Issue by victoramsantos** [VictoriaMetrics/VictoriaMetrics#5359]
### Is your question request related to a specific component?

vm-storage

### Describe the question in detail

Hi, I noticed that in all of our different clusters (more than 20 different cluster), vm-storage increase the `Slow inserts due to date` and during this period, some queries (mainly the one that uses `histogram_quantile`) starts to return values with high spikes which results in false-positive alerts. However, after the metric goes down, the queries are returning the right value which generates uncomfortable alerts saying thresholds that we can't see anymore :/ 

_**In sum, during the period of slow insert, the vm-select answer queries for vm-alert which trigger wrongly some alerts and when this period ends we can see everything okay and the spikes results gonna way**_

When I was investigating I could only see this correlation between 
```
sum(rate(vm_slow_per_day_index_inserts_total{kubernetes_pod_name=~".*vicmetrics-storage.*"}[5m])) by(kubernetes_pod_name)
```
that shows this graph:
![Screenshot 2023-11-20 at 15 02 06](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/6938bc6a-5f9e-4619-87c3-a4b78c3d3a4d)

As you can see the spikes occurs every day between 8pm-9pm. A zoom-in to see better:
![Screenshot 2023-11-20 at 15 05 19](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/23a1c891-21ff-42d2-a9f0-6ab66687334e)

I could only relate this spikes with the metric:
```
sum(rate(vm_cache_entries{type="storage/next_day_metric_ids"}[5m])) by (kubernetes_pod_name)
```
Which has the same behavior:
![Screenshot 2023-11-20 at 15 06 47](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1914482/181d0c90-1733-4ab5-b4a4-317284b118f8)
(PS: I didn't understand right what this `vm_cache_entries` means so I could conclude anything :/ )

I don't know how to investigate deeper, but this is very annoying because it's happening out of our business hour :/ 

**_Is there any way to identify if it's some internal procedure for vm-storage and if we can, at least, change the time it's happening?_** 

PS:
- cluster version: v1.91.0-cluster
- environment: kubernetes 
- timezone: all times are from Brazil UTC-3

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, Also,  I'd recommend to try upgrading for v1.95.1 version, it has performance improvements for daily index creation introduced at 1.92 and 1.93 versions. See full change log at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/CHANGELOG.md

**Comment by victoramsantos** [comment]
Hi @f41gh7 I'm running this on production, do you know if this index improvements are already on LTS version (1.93.x)?
