### ISSUE TITLE
New flag `maxQueryResultSize` for `/query` and `/query_range`

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#5372]
### Describe the solution you'd like

Need to add new flag `maxQueryResultSize` for vmselect/vmsingle, that will limit size of response for query API (`/query` and `/query_range`).

This is necessary to limit tenants for two reasons:
- Saves traffic between clients and server.
- Client failure protection (e.g. Grafana) by OOM.

### Additional information

[Discussion in private slack](https://victoriametrics-rocks.slack.com/archives/C03JQL8NW3E/p1699585007967519)

**Comment by hagen1778** [comment]
Hey @Amper! Would it be more convenient to add `-search.maxPointsPerQuery`, in order to be aligned with `-search.maxPointsPerTimeseries`?

In my opinion, it is a number of data points that matter if we talk about UI (Grafana) to plot them. Not the response size.

**Comment by Amper** [comment]
> Hey @Amper! Would it be more convenient to add `-search.maxPointsPerQuery`, in order to be aligned with `-search.maxPointsPerTimeseries`?
> 
> In my opinion, it is a number of data points that matter if we talk about UI (Grafana) to plot them. Not the response size.

We discussed it on the daily sync, and @valyala suggested this option. Ok, let's discuss it again.

**Comment by hagen1778** [comment]
I think it is important to include reasoning for such feature requests. It could be that the question I asked can be asked by other people, too.

**Comment by valyala** [comment]
The commit 3d3b0e31e09d4a86493f816aacf0272f3870f507 adds `-search.maxResponseSeries` command-line flag, which can be used for limiting the number of time series a single request to to [`/api/v1/query`](https://docs.victoriametrics.com/keyConcepts.html#instant-query) or [`/api/v1/query_range`](https://docs.victoriametrics.com/keyConcepts.html#range-query) can return. This command-line flag is easier to understand and use than the proposed `-search.maxQueryResultSize` and `-search.maxPointsPerQuery`.

This commit will be included in the next release.

**Comment by valyala** [comment]
The `-search.maxResponseSeries` command-line flag is available in single-node VictoriaMetrics and in `vmselect` component of [VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) starting from the release [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
