### ISSUE TITLE
Is it possible to retain data forever?

### ISSUE THREAD

**Issue by yulipumal** [VictoriaMetrics/VictoriaMetrics#5374]
### Is your question request related to a specific component?

victoriametrics

### Describe the question in detail

Dear community,
i want to store datasets that must not be deleted and can not be deduplicated. Does VictoriaMetrics offer no deletion on data, or is it the wrong TSDB for such a task?
thanks for the answer

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by belm0** [comment]
pruning can be effectively disabled by setting `retentionPeriod` to an arbitrarily long value

our instance has about 4 years of data and growing

**Comment by hagen1778** [comment]
> VictoriaMetrics does not support indefinite retention, but you can specify an arbitrarily high duration, e.g. -retentionPeriod=100y.

See https://docs.victoriametrics.com/#retention

> i want to store datasets that must not be deleted and can not be deduplicated.

All ingested data will be stored during the specified retentionPeriod, even duplicates. Unless you explicitly configure [deduplication](https://docs.victoriametrics.com/#deduplication).
