### ISSUE TITLE
allow specifying a server-wide default timezone for `vmui`

### ISSUE THREAD

**Issue by zackelan** [VictoriaMetrics/VictoriaMetrics#5375]
### Is your feature request related to a problem? Please describe

we have a geographically distributed team, and a convention that everything with a timestamp that is shared among the team (logs, screenshots of graphs and dashboards, etc) should be in UTC time to avoid confusion.

since v1.85 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3075 it's possible to set the timezone in VMUI, but this is a user preference. we have multiple VM instances (one per region, and per dev/test/prod environment) and it's cumbersome to have every user set this configuration for each VM instance.

with our Grafana dashboards, we can [set the timezone globally](https://grafana.com/docs/grafana/latest/administration/organization-preferences/#change-the-grafana-default-timezone), so that all dashboards display UTC time automatically, without requiring any per-user configuration. I'd like similar functionality in VMUI.

### Describe the solution you'd like

a command-line argument such as `-vmui.defaultTimezone string`

if specified, it would set the default timezone when viewing VMUI, rather than defaulting to the browser's local timezone

(if it'd be easier to implement, a `-vmui.forcedTimezone string` or `-vmui.alwaysUTC` would also work for my use case - disable the timezone configuration entirely and enforce "you'll use UTC and you'll like it")

related nice-to-have: add UTC to the list of timezones offered by the UI. it's possible to work around its absence by specifying a timezone such as `Atlantic/Reykjavik` or `Africa/Dakar` (because [they follow UTC year-round without daylight-savings time changes](https://en.wikipedia.org/wiki/UTC%2B00:00#As_standard_time_(year-round))) but it's not self-explanatory the way specifying UTC directly would be.

**Comment by valyala** [comment]
The `-vmui.defaultTimezone` command-line flag is supported by single-node VictoriaMetrics and `vmselect` at VictoriaMetrics cluster starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).

Closing the feature request as done.
