### ISSUE TITLE
vmctl: option to execute range steps in reverse order

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#5376]
### Is your feature request related to a problem? Please describe

If we have a migration that will take days or weeks, and would like to use the destination instance during migration, it would be useful to migrate the data roughly from newest to oldest.

### Describe the solution you'd like

Add a `vmctl` option to execute the step interval ranges in reverse order.

### Describe alternatives you've considered

I'm writing a script to call `vmctl` repeatedly with month ranges in reverse order.

(This script is needed anyway due to a bug about heavy names query, https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5369)

**Comment by hagen1778** [comment]
Hey @belm0! https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5444 has been merged and will be likely included into the next release.

**Comment by valyala** [comment]
The ability to migrate data in reverse order has been included in `vmctl` starting from the release [v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/vmctl.html#using-time-based-chunking-of-migration) for details.

Closing the feature request as done.
