### ISSUE TITLE
Can't see any imported metrics in Grafana

### ISSUE THREAD

**Issue by urupaud** [VictoriaMetrics/VictoriaMetrics#5377]
### Is your question request related to a specific component?

Yes, it's related to vmctl.

### Describe the question in detail

Hi Team,

I've imported data from Prometheus (currently using M3DB as longterm storage) remote read protocol to Victorimetrics using vmctl. The migration job completed successfully without any issues, however, I still can't see most of the imported metrics in Grafana, metrics visible only for only for a very few instances.

`
[root@ip-10-110-192-236 ~]# vmctl remote-read --remote-read-src-addr=http://prometheus:9090 --remote-read-filter-time-start=2023-08-14T00:00:00Z --remote-read-filter-time-end=2023-11-10T02:48:00Z --remote-read-step-interval=hour --vm-addr=http://vminsert:8480/ --vm-concurrency=2 --vm-account-id=0
Selected time range "2023-08-14 00:00:00 +0000 UTC" - "2023-11-10 02:48:00 +0000 UTC" will be split into 2115 ranges according to "hour" step. Continue? [Y/n] Y
VM worker 0:↑ 98753 samples/s
VM worker 1:↑ 117068 samples/s
Processing ranges: 2115 / 2115 [███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████] 100.00%
2023/11/22 09:14:32 Import finished!
2023/11/22 09:14:32 VictoriaMetrics importer stats:
  idle duration: 7h19m56.538426499s;
  time spent while importing: 4h4m5.097139497s;
  total samples: 1592762012;
  samples/s: 108757.35;
  total bytes: 34.9 GB;
  bytes/s: 2.4 MB;
  import requests: 7961;
  import requests retries: 0;
2023/11/22 09:14:32 Total time: 4h4m5.103872824s
`

Could you please check and advise on this.

Regards,
Udara

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @urupaud.
Could you please give more details about your setup.
Is the datasource in Grafana configured correctly? Can you try running the query through VMUI?

**Comment by urupaud** [comment]
Hi @Amper ,

I'm using Victoriametrics k8s stack with vmcluster enabled. Yes, datasource is correctly configured, as I can see the metrics pushed in real-time, I can't see only the imported metrics. Btw, I've used labels and imported metrics of a single instance, and it was successful. In the screenshot, there is metrics from 3 instances, as you can see, only one instance has the old metrics I imported from the Prometheus remote read (that was imported specifically by using the instance labels) other servers don't, even though the job was successful. It seems like the vmctl is not importing all the metrics from the Prometheus remote read though the job is completing.

![Screenshot 2023-11-24 at 15 37 46](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/35029043/0f0e2019-3f12-4c50-871d-bc5b21b50ded)

Highly appreciate your assistance on this. 🙏 

Thanks
