### ISSUE TITLE
VictoriaLog web ui

### ISSUE THREAD

**Issue by xiehaitang** [VictoriaMetrics/VictoriaMetrics#5386]
### Is your feature request related to a problem? Please describe

To query logs, i need to enter various keywords

### Describe the solution you'd like

Web UI adds selection dropdown boxes, which contain corresponding labels,Like Grafana Explore
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/74036543/5283a16c-329d-4292-842f-38081aadbe9b)

**Comment by JakeCooper** [comment]
Wait how were you able to get Grafana to speak to VictoriaLogs?

**Comment by hagen1778** [comment]
Duplicates https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4513
