### ISSUE TITLE
Add function "query", "first" and "value" to alert templates function

### ISSUE THREAD

**Issue by PavelKolobaev** [VictoriaMetrics/VictoriaMetrics#539]
**Describe the bug**
Add function "query", "first" and "value" to alert templates function
**To Reproduce**
```
helm install stable/prometheus-operator
for f in `kubectl get prometheusrules.monitoring.coreos.com -o name`; do kubectl -n monitoring get prometheusrules.monitoring.coreos.com `basename $f` -o yaml > `basename $f`.yaml ; done
```
Clean files (delete strings from top to specs)
```
./vmalert-prod -remoteRead.url="http://127.0.0.1:8428" -notifier.url="http://127.0.0.1:9093" -datasource.url="http://127.0.0.1:8428" -rule="./*.yaml"
```

**Expected behavior**

We want replace vmalert in operator-prometheus. For backward compatibility need same behavior

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./vmalert-prod --version
vmalert-20200605-191106-tags-v1.37.0-0-g69a647b0d
```

**Comment by hagen1778** [comment]
@kreedom could you pls take a look?

**Comment by valyala** [comment]
`query`, `first` and `value` functions have been added to alert templates in the commit 6247884057e91a9d750dde36daec16bd6873da42 . @PavelKolobaev , could you build `vmalert` from this commit according to [these instructions](https://victoriametrics.github.io/vmalert.html#how-to-build-from-sources) and verify whether the newly added functionality works as expected?

**Comment by valyala** [comment]
`query`, `first` and `value` template functions have been added to `vmalert` starting from [v1.50.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
