### ISSUE TITLE
resulting series aren't sorted when using `or` operator

### ISSUE THREAD

**Issue by Saigut** [VictoriaMetrics/VictoriaMetrics#5393]
### Describe the bug

VictoriaMetrics returns data in an inconsistent order in different queries, this results in inconsistent colors on the line chart. We expect the order is consistent.

### To Reproduce

query exprression: `irate(node_network_receive_bytes_total{instance=~'<ip>:<port>'}[5m])*8 or irate(node_network_receive_bytes{instance=~'<ip>:<port>'}[5m])*8`

### Version

/ # /vmselect-prod --version
vmselect-20231116-195457-tags-v1.95.1-cluster-0-g1a15b0f57

### Logs

![WechatIMG107](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2455241/64f388df-9590-4afe-9995-4dcccb59b603)
![WechatIMG108](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2455241/30f4148b-47cd-4cf4-8f31-1cc2ddb4f222)
![WechatIMG109](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2455241/289d6c99-9986-440c-b188-2b9c4fd5848f)
![WechatIMG110](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2455241/d46181e0-b579-4e8d-b03e-e2036f95ef88)

We can see the order is inconsistent between two queries, causing inconsistent color. In the mean while the order of prometheus is consistent.

**Comment by hagen1778** [comment]
I believe this is related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4763
Will have a closer look tomorrow

**Comment by Saigut** [comment]
> I believe this is related to #4763 Will have a closer look tomorrow

Hello, this problem may not relate to `or` operator. Bacause I got same problem when I use query exprression `node_network_receive_bytes_total{instance=~'$node'}`

**Comment by hagen1778** [comment]
> Will have a closer look tomorrow

Ha-ha, took me a while) 
So it looks like to satisfy requirement [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4763#issuecomment-1674285608) the sorting was disabled if query contains `or` operator. And you'd probably won't notice any issues if you were using single-node VictoriaMetrics.

But in cluster version, the query results are received in arbitrary order from vmstorage nodes. Not sorting results would mean the order would never be consistent between consequent query executions. I think, we should revert the change [here](https://github.com/AndrewChubatiuk/VictoriaMetrics/commit/9e1823b60a3d7551b48fe81f1c4742c487bc01cb).
@valyala wdyt?

**Comment by hagen1778** [comment]
Or, which should be better, we need to sort results of `a` and `b` expressions independently. This would satisfy this and mentioned case.

**Comment by valyala** [comment]
The issue has been fixed in the commit 190a6565ae93a30c0b98c42e794c092eba476238 according to the suggestion from [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5393#issuecomment-1884817219). This commit will be included in the next release of VictoriaMetrics. In the mean time it is possible to test the fix by running VictoriaMetrics built from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources).

**Comment by valyala** [comment]
FYI, VictoriaMetrics should consistently sort `a or b` query results across multiple requests starting from [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html).
