### ISSUE TITLE
vmstorage API: list of accountid and projectid

### ISSUE THREAD

**Issue by radumar1001** [VictoriaMetrics/VictoriaMetrics#540]
We need a way to identify the tenants (accountid and projectid) that exist on a vmstorage node.

I would expect to have the possibility to make an **API call** on the **vmstorage** node querying the **list of available accountids**. Similarly, I would expect to be able to make a query through API for the **list of projectids** corresponding to a given accountid.

So far I didn't find anything similar in the API of vmstorage. I found something that is somehow helpful in the metrics of vminsert, namely:

```
# curl -s http://192.168.161.3:8480/metrics | grep vm_rows_inserted_total
vm_rows_inserted_total{type="promremotewrite",accountID="1155",projectID="11"} 72055
vm_rows_inserted_total{type="promremotewrite",accountID="1155",projectID="3"} 72260
vm_rows_inserted_total{type="promremotewrite",accountID="1155",projectID="5"} 72055
vm_rows_inserted_total{type="promremotewrite",accountID="1155",projectID="7"} 73460
vm_rows_inserted_total{type="promremotewrite",accountID="1337",projectID="0"} 73060
vm_rows_inserted_total{type="promremotewrite",accountID="1337",projectID="17"} 76604
vm_rows_inserted_total{type="promremotewrite",accountID="1337",projectID="23"} 76199
vm_rows_inserted_total{type="promremotewrite",accountID="35",projectID="5"} 73060
vm_rows_inserted_total{type="promremotewrite",accountID="35",projectID="7"} 72455
```
  but this has a few drawback:
- the information is only about that specific vminsert, not about the vmstorage node(s) behind the vminsert
- the information is volatile: if the vminsert node is restarted, it "forgets" about the tenants until fresh datapoints arrive

**Comment by valyala** [comment]
Closing this feature request as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2929
