### ISSUE TITLE
vmselect incorrectly applies concurrency limits for API requests. 

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#5415]
### Describe the bug

 
 Currently, vmselect applies concurrency limit for each request and returns `search.maxConcurrentRequests=` error, even if request was made not for `search` API. Such as `vmui`, `active queries`, `vmalert`, etc.
 
 It confuses users, makes impossible to understand which search query consumes all server requests. May block actual search requests from execution. 

 This concurrency limiter must be applied only for search API requests.

### To Reproduce

 Try to debug heavy queries with 300-500 qps rate.

### Version

 any version

**Comment by f41gh7** [comment]
FYI @valyala

**Comment by valyala** [comment]
This issue should be fixed by f62e03b3d2b408d8e06de8407251bd3146949870 . This commit has been included in [v1.96.0](https://docs.victoriametrics.com/changelog/). Closing the issue as fixed.
