### ISSUE TITLE
Expected performance of the log tailing feature of Victorialogs?

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5424]
### Is your question request related to a specific component?

Victorialogs

### Describe the question in detail

I'm looking to test the log tailing functionality of Victorialogs (once available) as a potential substitute for tailing kubernetes logs with `kubectl logs`.  Im curious to know if you've done any benchmarks to see how many concurrent clients could run the tail, each on different streams?  Could this be scaled up to easily handle over a hundred (or more) clients simultaneously?  Thank you for your help.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @hartfordfive.
No, as far as I know, there is no such benchmark yet. We would appreciate it if someone outside the company performed such a benchmark and we could reference it.
Maybe @valyala or @zekker6 can get more about that.

**Comment by hartfordfive** [comment]
I would be interested in running a benchmark for this although do you have an estimate as to when the tail feature will be available?

**Comment by hartfordfive** [comment]
Is there a development branch in which the feature  is at least partially present and could be used?

**Comment by valyala** [comment]
> Is there a development branch in which the feature is at least partially present and could be used?

There is no a branch for live tailing yet.

As for the performance, VictoriaLogs should be able to handle hundreds concurrent `tail` requests with arbitrary complex [LogsQL filters](https://docs.victoriametrics.com/VictoriaLogs/LogsQL.html#filters). The basic idea is to filter out the needed log lines for every `tail` request during data ingestion before the ingested logs are written to petsistent storage.

**Comment by valyala** [comment]
Live tailing feature is available in VictoriaLogs starting from [v0.24.0-victorialogs release](https://docs.victoriametrics.com/victorialogs/changelog/). See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#live-tailing) for details on how to use live tailing in VictoriaLogs.

Closing this feature request as done.
