### ISSUE TITLE
Problem with retention files

### ISSUE THREAD

**Issue by hajdukr** [VictoriaMetrics/VictoriaMetrics#543]
Hello,
I have VictoriaMetrics version victoria-metrics-20200516-065828-tags-v1.35.5-0-g4e850cd6a. I have retention set on 2. My metrics from March are not visible, but files are still on disk. I have also instance with 1 month retention and there is everything ok. Data is currently deleted. Could you tell me where is the problem? What should I do? Can I remove this files safetly with no risk of data?

**Comment by rafal815** [comment]
Hello,
thanks for the answer. I checked the configuration, and retention is set to 2, and storageDataPath is set to /data/victoriametrics from the beginning, and has not been changed. In logs, the only thing besides "merge" are single errors "missing metricName by metricID xxxx; this could be the case after unclean shutdown; deleting the metricID".
I have also instances with retention set to 1 and there are no problems with old data.

**Comment by ulikl** [comment]
hello,
I see the problem also with retentionPeriod=1 in Version victoria-metrics-20200427-220723-tags-v1.35.0-0-g3bfa41a9
But only in the largest of 3 instances, which run with the same version and configuration . In the logs apart from error   "net/http/server.go:3059 http: TLS handshake error from 160.50.174.86:38412: EOF"  there are only info messages.
Also after a restart the files remain. 
The snapshots (taken hourly) are correct. I.e. they do not include the files out of retention.

Would it be a workaround to add a retry of the retention deletions in the startup.

**Comment by valyala** [comment]
> Would it be a workaround to add a retry of the retention deletions in the startup.

VictoriaMetrics checks for monthly partitions outside the retention every minute. So it must delete such partitions from `data/big` and `data/small` directories as soon as it notices them. See [the corresponding code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9a2ba5b6d1bf462efee205982494d384a3e1fcef/lib/storage/table.go#L378) for details. If it cannot delete these folders, then VictoriaMetrics exits with `FATAL: cannot remove ...` error. The only exception if the data stored on NFS-like storage. In this case it increments `vm_nfs_dir_remove_failed_attempts_total` metric on every unsuccessful attempt to delete the folder. See [these docs](https://victoriametrics.github.io/#monitoring) on how to collect this metric.

**Comment by ulikl** [comment]
Thank you very much for the explanation.
We are using SAN-Storage on all three instances and the metric constantly 0.

We wanted to upgrade to an newer version anyway, maybe this helps.

**Comment by valyala** [comment]
@ulikl , @rafal815 , do you experience this issue in [latest VictoriaMetrics releases](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by ulikl** [comment]
Hi @valyala,
sorry, I forgot to update the issue:
After upgrading from v1.35 to v1.42.0 immediately the files/directories for the old month have been deleted.
So no more issue from my side.

**Comment by dan-sel** [comment]
> It is safe to delete subfolders with names `YYYY_MM` (for example, `2020_03`) inside `<-storageDataPath>/data/small` and `<-storageDataPath>/data/big` when VictoriaMetrics is stopped via graceful shutdown

@valyala Is that documented anywhere? Will it still hold true when downsampling has been implemented?

We are running VM on an embedded device with little disk space. Since we cannot anticipate how much disk space VM will occupy with our data, we need to monitor disk usage and remove old VM partitions as an emergency measure to prevent the disk from filling up. It would be great if we could remove the partitions manually instead of having to calculate a retention period, restart VM and wait for it to eventually delete the old partitions.

However, I'm hesitant to implement this unless it is documented that deleting the folders is safe.

**Comment by valyala** [comment]
> Is that documented anywhere? Will it still hold true when downsampling has been implemented?

@dan-sel , deleting folders under `<-storageDataPath>/data/{small,big}` is safe and will remain safe after downsampling is implemented. Note that folders must be deleted when VictoriaMetrics isn't running. It is documented at [troubleshooting section](https://victoriametrics.github.io/#troubleshooting). Note that VictoriaMetrics supports retentions smaller than one month starting from [v1.45.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
Closing this issue as solved after the confirmation at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/543#issuecomment-712780242
