### ISSUE TITLE
`<` character is printed as `\u003c` in `/federate` result, but that is invalid according to Prometheus golang client

### ISSUE THREAD

**Issue by DanielLeone** [VictoriaMetrics/VictoriaMetrics#5431]
### Describe the bug

When calling the `/federate` endpoint of VictoriaMetrics, if there's a `<` character in a label value, it's printed as `\u003c`. However, this is invalid according to [TextToMetricFamilies](https://github.com/prometheus/common/blob/main/expfmt/text_parse.go#L100C22-L100C42).

The line producing the `\u0003c`:
https://github.com/valyala/quicktemplate/blob/v1.5.1/jsonstring.go#L58

The line in Prometheus which errors when seeing that escape sequence:
https://github.com/prometheus/common/blob/c59927ec74c04c0c17891bf27784fe7c484ae97f/expfmt/text_parse.go#L587

This only appears to happen when calling the `/federate` endpoint, in all other cases, the `<` character is printed as `<,` not the escape sequence.

I'm not sure if VicotriaMetrics is doing it wrong, or if Prometheus golang client should be able to parse this, but according to the documentation on the Exposition Format, it seems that only `\\`, `\"`, and `\n` need escaping.

Exposition format documentation on the matter:
https://github.com/prometheus/docs/blob/995743836ec508e7ca714ba758ab71b6ae102f3e/content/docs/instrumenting/exposition_formats.md?plain=1#L90

Comment in the Prometheus client explaining that only `\\` and `\n` are valid escape sequences, so not sure about `"` in this case either?:
https://github.com/prometheus/common/blob/c59927ec74c04c0c17891bf27784fe7c484ae97f/expfmt/text_parse.go#L573

### To Reproduce

* Start up victoria metrics
* Get it to scrape itself - on any source with a `<` in a label value
* Call the federate endpoint matching the metric with the `<`, eg: `http://127.0.0.1:8428/federate?match[]=vm_http_requests_total`
* See the `\u003c` code in the output

### Version

master branch

### Screenshots

instance of the issue when scraping victoria metrics itself, the `<` character is used in a few label values, including `vm_http_requests_total` as seen here:

http://127.0.0.1:8428/federate?match[]=vm_http_requests_total{path=~%22.*func_name.*%22}

<img width="886" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8600684/e3f50503-7f63-43b1-bbf8-1e3ffb4c1ede">

---
however, when looking at the raw response from the metric source, the `<` character appears literally:

<img width="585" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8600684/d0d09d4e-3af2-4a5f-b443-50e48d8ec190">

**Comment by valyala** [comment]
FYI, the bugfix has been backported to [v1.87.12 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.12). It will be included in the latest release as well.

**Comment by DanielLeone** [comment]
Appreciate the super quick fix! 👍 please close this issue as required

**Comment by valyala** [comment]
The bugfix has been back-ported to [v1.93.9 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.9).

> please close this issue as required

The issue will be closed after publishing the latest release, which includes the bugfix.

**Comment by valyala** [comment]
The bugfix has been included in [the release v1.96.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed then.
