### ISSUE TITLE
WITH Expression, How can i use variable as duration in with expression

### ISSUE THREAD

**Issue by Hello-World-0X** [VictoriaMetrics/VictoriaMetrics#5432]
### Is your question request related to a specific component?

vm select

### Describe the question in detail

i have a promQL use WITH expression
```    
WITH (
    over_threshold(metric, filters, threshold) = sum_over_time(metric{filters}[5m]) > threshold
)
over_threshold(metric_name, {env!="xxxx", region!="xxxx"}, 100)
```
this promQL is ok, but if i want make duration as an variables llike :

```
WITH (
    over_threshold(metric, filters, threshold, duration) = sum_over_time(metric{filters}[duration]) > threshold
)
over_threshold(metric_name, {env!="xxxx", region!="xxxx"}, 100, 6m)
```

this promQL will execute failed when use query range api, the resp error is parse failed, but in with play ground ,it can be expanded correctly

if i want use variables as duration, how should i correct my promQL?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Hello-World-0X** [comment]
i got it, because the vm select i used is 1.90-0-cluster, but this feature of use duration variables in with expression was finished in 1.92.0.

**Comment by dmitryk-dk** [comment]
Hi @Hello-World-0X ! Can we close the issue as solved?

**Comment by Hello-World-0X** [comment]
@dmitryk-dk yes, thank you.
