### ISSUE TITLE
Rollout process with metrics gap

### ISSUE THREAD

**Issue by juliocleal13** [VictoriaMetrics/VictoriaMetrics#5434]
### Is your question request related to a specific component?

vmstorage and vminsert

### Describe the question in detail

Hi folks,

We have deployed in production a Victoria Metrics as cluster installation mode.

We scrape and send metrics from RW by prometheus-agent

This prometheus agent has a wal file with 10 minutes of metrics.

We currently have vmstorage with: 52 replicas, 4vCPU, 170Gi of RAM and 200Gi of disk

So, every time we need to rollout the victoria metrics we have faced a gaps in our metrics.
We are using a [no downtime rollout](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#no-downtime-strategy) strategy because we don't want to have unavailability in our metrics.

To try resolve this, I've tried configure `vmstorageUserTimeout` and `vmstorageDialTimeout` in the vminsert configured in 2 seconds
I updated the VMStorage to 1.95.1 to use the `vminsertConnsShutdownDuration` configured in 25 seconds but in any configuration the problem was not solved.

Is there some solution or tip to resolve this?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by ericholt** [comment]
Hi, I am having the same issue. Can the solution be shared here as the Slack conversation is not available to those with a free version of Slack. Thanks in advance!

**Comment by dmitryk-dk** [comment]
> Yes, after we change the configuration the problem was solved. Thanks a lot for help

Hi @juliocleal14 could you please describe what you did to solve your problem?

**Comment by juliocleal14** [comment]
Hi everyone! Of course!
This configuration: `vminsertConnsShutdownDuration` helps a lot in this proccess and we have increase its value until find a good gracefull interval, but only this was not enough.

After a several days of test we identified that the CPU usage in the VMStorage is the most responsible for delay in sending delay.
In our tests, increase 10% of CPU was enough to not have gaps in the metrics during rollout.


But in the end of the day, increase 10% of CPU only to be used in the rollout moments seems like a waste of money and after some more investigation we realized some tests making rollou in out of business hours (in our case, after 10pm) and, when we are not in the business ours, with vmstorage using less CPU, the rollout works without delay and gaps.

So, my advice is, increase the `vminsertConnsShutdownDuration` (in our configuration we configured in 200s) (the rollout time increase a lot), and increase 10% of CPU in the VMStorage (if increase this is not a problem for you, this is the best solution)

**Comment by ericholt** [comment]
> increase 10% of CPU in the VMStorage

@juliocleal14 what was your average vmstorage cpu usage % before the increase?

**Comment by juliocleal14** [comment]
It was around 70%, look the prints I made in the tests
Without increase CPU
<img width="620" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/48995318/ef7b5841-98a1-44cb-85e3-4e7c2f9321a4">

After increase CPU
<img width="615" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/48995318/5ce4d2d8-60a8-49fe-a322-480bd6514cdf">

Look that I increased a lot to make sure I wouldn't have a problem
