### ISSUE TITLE
After update cluster version 1.75.0 to 1.87.11, every time a vmstorage node's GC time increases, it will be accompanied by a certain number of handshake timeouts

### ISSUE THREAD

**Issue by tydhot** [VictoriaMetrics/VictoriaMetrics#5443]
### Describe the bug

After update cluster version 1.75.0 to 1.87.11, every time a vmstorage node's GC time increases, it will be accompanied by a certain number of handshake timeouts

### To Reproduce

Update cluster version 1.75.0 to 1.87.11, and vmstorage node's GC time increased.
<img width="1020" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/605b6d83-d945-475c-8a6d-fa0f6bce28ea">
And the gc time is always low before we updated it.And every time a vmstorage node's GC time increases, it will be accompanied by a certain number of handshake timeouts .This will result in a certain number of alarm queries failing.
<img width="1430" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/8a405bc5-e2f1-4542-96ae-80592995a0c7">
<img width="1027" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/ea977dcb-d365-4128-bb92-8f97b7bc19db">

### Version

1.87.11-cluster

### Logs

<img width="1439" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/8ffe50c3-5e72-4fdb-bc4c-6bf8ae935999">

error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage :8401: cannot obtain connection from a pool: cannot perform \"vmselect\" handshake with server \":8401\": cannot read success response after sending hello: cannot read message with size 2: read tcp4 :55770->:8401: i/o timeout; read only 0 bytes"}

Dec  8 20:50:47 [37107]: 2023-12-08T12:50:47.971Z#011error#011VictoriaMetrics/lib/vmselectapi/server.go:201#011cannot perform vmselect handshake with client ":40672": cannot read isCompressed flag: cannot read message with size 1: EOF; read only 0 bytes

### Used command-line flags

vmstorage: 
./vmstorage-prod -storageDataPath /data/docker/vm -search.maxTagKeys=10000 -search.maxTagValues=10000 -search.maxUniqueTimeseries=3000000 -retentionPeriod=15d -dedup.minScrapeInterval=10s
vmselect:
"-search.logSlowQueryDuration=30s",
    "-search.maxConcurrentRequests=32",
    "-search.maxQueueDuration=20s",
    "-search.maxUniqueTimeseries=3000000",
    "-search.maxQueryDuration=1m",
    "-dedup.minScrapeInterval=10s",
    "-search.maxQueryLen=64KB",
    "-search.denyPartialResponse=true",
    "-cacheDataPath=/data/log"

### Additional information

maybe i can find some way to reduce the memory usage? I don't know why the GC time increases after upgrading the version. Or maybe I can make the handshake read timeout bigger than 1s?

Before the upgrade, the GC of vmstorage did not experience significant time consumption, and there was no handshake timeout during queries in vmselect.  However, the memory usage of vmstroage is not significantly different from before the upgrade, which is very puzzling to me

**Comment by tydhot** [comment]
I have found the reason for the instability of GC, which is because the default value of upgraded GOGC has been adjusted from 50 to 30. After further adjustments, my application's GC situation has become stable, but I am still curious why my application's memory drops significantly every day at 0 o'clock in the standard time zone

**Comment by zekker6** [comment]
Hello @tydhot 

> I have found the reason for the instability of GC, which is because the default value of upgraded GOGC has been adjusted from 50 to 30. After further adjustments, my application's GC situation has become stable, but I am still curious why my application's memory drops significantly every day at 0 o'clock in the standard time zone

It is very likely that this is related to the reset in one of caches. In order to check this could you check the following metric across the storage nodes: `vm_cache_size_bytes`?
It shows amount of memory used per each cache type, I'd expect it's value to drop at the same time as overall memory usage daily.

**Comment by tydhot** [comment]
> Hello @tydhot
> 
> > I have found the reason for the instability of GC, which is because the default value of upgraded GOGC has been adjusted from 50 to 30. After further adjustments, my application's GC situation has become stable, but I am still curious why my application's memory drops significantly every day at 0 o'clock in the standard time zone
> 
> It is very likely that this is related to the reset in one of caches. In order to check this could you check the following metric across the storage nodes: `vm_cache_size_bytes`? It shows amount of memory used per each cache type, I'd expect its value to drop at the same time as overall memory usage daily.

hi @zekker6 
I have already observed around cache, but the preliminary results did not meet my expectations. Take the following two statements as examples
sum(vm_cache_size_bytes{instance=""}) by (instance) / 1024 / 1024 / 1024 
process_resident_memory_anon_bytes{instance="instance"}  /1024 / 1024 / 1024 
<img width="1364" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/1ad4350e-4d3f-430e-890b-8ffe77c89b73">
When the memory drops by more than 10G at 0:00 in the standard time zone, there is no significant change in the total cache size, which make me temporarily excludes the possibility of cache

**Comment by zekker6** [comment]
@tydhot Could you check the ingestion rate around the same time?
Also, could you also check series and datapoints read panels in the [official Grafana dashboard](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/)? ("vmselect" row -> scroll to the last panels)

**Comment by tydhot** [comment]
hi @zekker6 thanks for reply 
<img width="686" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/f885d1d8-6d4d-437b-a695-6fb081ca6ff1">
<img width="692" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/27889201/c88e080f-9c21-436d-918b-d6bb87ab8293">
 
At 8 o'clock this morning (which is zero in the standard time zone), all storage memory experienced a decline, but the Datapoints ingestion rate did not show any significant changes at this time point.
There seems to be some problem with the metrics of vmselect that I have collected so far, but moving forward from this time point for 7 to 8 hours is not our working time. Apart from periodic alert queries, there should be no human queries for the first two to three hours before and after this period.
If there is no good solution on your end, I may not delve into it for now. Thanks anyway.
