### ISSUE TITLE
vmui: "Statistic inaccuracy explanation" is broken

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5460]
### Describe the bug

The following link [Statistic inaccuracy explanation](https://docs.victoriametrics.com/#cardinality-explorer-statistic-inaccurancy) on the Cardinality Explorer page is broken
<img width="365" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/23538b58-8a30-4137-ad8e-28b29bb3088a">

### To Reproduce

Visit the cardianility explorer page for clustered version of VM.

### Version

v1.96.0

**Comment by valyala** [comment]
The commit 105c6b2eb7ca10ee750e633247aca549db735104 fixes the broken link. This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
The broken link to static inaccuracy explanation at vmui has been updated in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing the issue as fixed.
