### ISSUE TITLE
 vmstorage memory copy is extended horizontally

### ISSUE THREAD

**Issue by pwangyangyang** [VictoriaMetrics/VictoriaMetrics#5464]
### Is your question request related to a specific component?

The vmstorage memory is insufficient. The VMstorage memory does not change after the number of copies is increased
When additional copies are added for horizontal capacity expansion, replicationFactor is configured as 2xN-1 in the document

### Describe the question in detail

<img width="1686" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/140464695/18cb0b17-bb08-4b65-aa43-764457948e9c">

I have 19 instances of vmagent, replicationFactor: 10, conforming to 2*N-1 
<img width="1149" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/140464695/0b982f96-d7f0-493e-92e8-9574fc418f86">

Sometimes I come across vmstorage OOM

Then we receive Too many errors served for path /insert/{}/prometheus/ (instance vminsert-vmcluster-xxx-xxx)

Could you tell me how to reduce the vmstorage memory in this case

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @pwangyangyang
It seems like `vmstorage` nodes memory usage is close to the limits. It is [recommended](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#capacity-planning) to keep more spare RAM available to avoid OOM kills of `vmstorage` nodes (see also: https://docs.victoriametrics.com/Troubleshooting.html#cluster-instability, https://docs.victoriametrics.com/Troubleshooting.html#out-of-memory-errors).

>  When additional copies are added for horizontal capacity expansion, replicationFactor is configured as 2xN-1 in the document
> I have 19 instances of vmagent, replicationFactor: 10, conforming to 2*N-1

It is important to understand the difference in replication mechanism in [VictoriaMetrics cluster](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety) and [vmagent](https://docs.victoriametrics.com/vmagent.html#high-availability) itself.

VictoriaMetrics cluster replication is configured by setting `-replicationFactor=N` command-line flag for `vminsert` nodes. `vminsert` than distributes every sample to `N` different storage nodes in cluster. 

`vmagent` replication is achieved by using multiple `vmagent` instances to scrape the same targets. 

Could you elaborate on your requirements to data availability?
Having `replicationFactor` set to 10 might be an overkill, leading to higher memory, cpu and storage usage than it is actually required. Using `replicationFactor=10` allows cluster to tolerate outage of 9 `vmstorage` nodes without loosing access to data, is that intended?

**Comment by pwangyangyang** [comment]
replicationFactor=2 starts.  If one vmstorage OOM is faulty, data is abnormal

See the documentation recommended is 2*N-1, so I set it, I don't know how much I should set, but I want to hang an instance without affecting my data

**Comment by pwangyangyang** [comment]
I would like to know how much replicationFactor should be set to in general

**Comment by zekker6** [comment]
> replicationFactor=2 starts. If one vmstorage OOM is faulty, data is abnormal

Is `replicationFactor=2` set at `vminsert`?
Also, note that enabling `replicationFactor` affects only data ingested after change. Data which was previously ingested will not be replicated. Could you clarify if abnormal data is in the past(before changing `replicationFactor`) or it is newly ingested samples?

> See the documentation recommended is 2*N-1, so I set it, I don't know how much I should set, but I want to hang an instance without affecting my data

Could you point to documentation with this recommendation?
Most likely it is the following [reference](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#replication-and-data-safety):

> The cluster must contain at least `2*N-1` `vmstorage` nodes, where `N` is replication factor, in order to maintain the given replication factor for newly ingested data when `N-1` of storage nodes are unavailable.

Which defines minimal number of nodes to ensure data availability. It is not required to keep `replicationFactor` to values higher than this if it is not required for higher availability.

**Comment by pwangyangyang** [comment]
I was wondering if I could set replicationFactor to a smaller value to reduce the memory usage of vmstorage

**Comment by zekker6** [comment]
> I was wondering if I could set replicationFactor to a smaller value to reduce the memory usage of vmstorage

Yes, it will reduce memory storage across vmstorage nodes. 

As I've mentioned before, `replicationFactor=N` creates `N` copied for each datapoint on different storage nodes. Reducing `replicationFactor` means that there will be fewer copies of data and thus less load on `vmstorage` nodes.

**Comment by pwangyangyang** [comment]
Thank you.  I changed replicationFactor=10 and reduced replicationFactor=5 ， Memory does go down a bit

**Comment by pwangyangyang** [comment]
There are now 20 vmstorage instances and 5 shards, if I want to reduce the number of instances by 15, will it affect the data

**Comment by zekker6** [comment]
@pwangyangyang Yes, it is possible that this will affect the data.

Data is distributed by picking a node based on consistent hashing. In case one of storage nodes is not available data is re-routed to another storage nodes (see [this](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) doc).
Based on this there are 2 possible states of data:
- rerouting never happened - in this case `replicationFactor=5` guarantees that data was written to 5 different storage nodes consistently. It is possible to remove `replicationFactor-1 => 4` storage nodes without risk of loosing data. Note that this can affect number of copies of data in cluster because there is no background replication. If 4 nodes will be removed there is a chance that some datapoints will only be available at 1 other storage node.
- there was a rerouting - in this case removing nodes is not safe because series where rerouted, and it is impossible to select node to safely remove.

Also, in case the goal of removing storage nodes is to reduce resource allocation(CPU/RAM) it is safer/easier to lower amount of resources allocated to each storage node.

**Comment by zekker6** [comment]
Closing as questions here have been answered. Feel free to reopen if further questions will arise.
