### ISSUE TITLE
Rules are complex, and we want aggregation and real-time computation rules to support logical operations

### ISSUE THREAD

**Issue by wego-xc** [VictoriaMetrics/VictoriaMetrics#5465]
### Is your feature request related to a problem? Please describe

Rules are complex, and we want aggregation and real-time computation rules to support logical operations

We want the logical operation to refer to if... else or support for scripting language engines can complement this if...else problem.
Or just use a lua script, which is great

### Describe the solution you'd like

Rules are complex, and we want aggregation and real-time computation rules to support logical operations

We want the logical operation to refer to if... else or support for scripting language engines can complement this if...else problem.
Or just use a lua script, which is great

**Comment by zekker6** [comment]
Hello @wego-xuchang, could you elaborate on why you need `if..else` conditions for rules?
There are operators like `if`, `ifnot` and `default` already [supported](https://docs.victoriametrics.com/MetricsQL.html#metricsql-features):
- `default` binary operator. q1 default q2 fills gaps in q1 with the corresponding values from q2. See also [drop_empty_series](https://docs.victoriametrics.com/MetricsQL.html#drop_empty_series).
- `if` binary operator. q1 if q2 removes values from q1 for missing values from q2.
- `ifnot` binary operator. q1 ifnot q2 removes values from q1 for existing values from q2.

Does it help in your case?

**Comment by zekker6** [comment]
Closing as there was no feedback provided.
