### ISSUE TITLE
vmagent: support stream aggregation before splitting data streams

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5467]
### Is your feature request related to a problem? Please describe

[Streaming aggregation](https://docs.victoriametrics.com/stream-aggregation.html) is specified individually per each `-remoteWrite.url`. This allows writing different aggregates to different remote storage destinations.

But it doesn't allow to fan-out once aggregated data stream to multiple destinations. Like to make streaming aggregation to happen only once before replicating data.

### Describe the solution you'd like

Would be great to support a new cmd-line flag `-remoteWrite.streamAggr.globalConfig` of type "string" which could be specified only once. When the flag is set, the specified aggregation should happen before data is replicated to specified  `-remoteWrite.url`.

### Describe alternatives you've considered

An alternative is to chain vmagents:
1. 1st vmagent should perform aggregation and forward results to 2nd vmagent
2. 2nd vmagent will replicate data stream to multiple destinations.

**Comment by hagen1778** [comment]
@AndrewChubatiuk would you mind taking a look at this enhancement?

**Comment by rparvizian-rbx** [comment]
@AndrewChubatiuk any updates on this?

**Comment by hagen1778** [comment]
The PR is here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6268

**Comment by valyala** [comment]
[vmagent](https://docs.victoriametrics.com/vmagent/) supports global stream aggregation before splitting data streams starting from [v1.102.0-rc1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1). See [these docs](https://docs.victoriametrics.com/stream-aggregation/#routing) for details.
