### ISSUE TITLE
Why does the data on VMUI have numbers greater than 100%

### ISSUE THREAD

**Issue by LeonYanghaha** [VictoriaMetrics/VictoriaMetrics#5473]
### Describe the bug

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/23301914/aeeb4853-7826-4a06-a805-48aac50bc0c7)

From the screenshot, why are there numbers greater than 100% in the data here。

### To Reproduce

```dc```, ```job``` will exist in each time series. But I don't understand if it's greater than 100%.

### Version

1.79.8

**Comment by zekker6** [comment]
Hello @LeonYanghaha , it is possible because of the following:

> In [cluster version of VictoriaMetrics](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html) each vmstorage tracks the stored time series individually. vmselect requests stats via [/api/v1/status/tsdb](https://docs.victoriametrics.com/#tsdb-stats) API from each vmstorage node and merges the results by summing per-series stats. This may lead to inflated values when samples for the same time series are spread across multiple vmstorage nodes due to [replication](https://docs.victoriametrics.com/#replication) or [rerouting](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html?highlight=re-routes#cluster-availability).

**Comment by LeonYanghaha** [comment]
This still cannot explain my doubts：
* Replication: All of my cluster data is on the local disk of vmstorage and has not been backup or migrated. Can I assume that this will not cause data duplication.
* Rerouting: If a vmstorage node is unavailable and vminsert fails to write data, why is there data duplication when routing to other nodes? I don't understand

**Comment by zekker6** [comment]
> Rerouting: If a vmstorage node is unavailable and vminsert fails to write data, why is there data duplication when routing to other nodes? I don't understand

As an example, let assume cluster has 3 `vmstorage` nodes and there are three metrics written: `foo`, `bar`, `baz`. For example purposes let's assume that each metric is written to its own `vmstorage` node(e.g. `foo` -> `vmstorage1`, `bar` -> `vmstorage2`, `baz` -> `vmstorage3`).

In case of rerouting one of series will be routed to another storage node, for example:
- `vmstorage1` now stores `foo` and `bar` samples
- `vmstorage2` stores `bar` samples
- `vmstorage3` stores `baz` samples

When `/api/v1/status/tsdb` results will be merged from each storage node number of series for `bar` will be taken from both `vmstorage1` and `vmstorage2` and might result in inconsistent results.
