### ISSUE TITLE
Regarding the problem that the bool operator cannot obtain complete data when performing an or operation.

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5474]
### Is your question request related to a specific component?

MetricsQL

### Describe the question in detail

exec：(0 > bool 1) 
result：{} 0

exec：(1 > bool 0) 
result：{} 1

exec：(0 > bool 1) or (1 > bool 0)
result：{} 0
Why not get {} 0 and {} 1 at the same time？

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @luzejia, this happens because `or` operator per [PromQL spec ](https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators) works like this:
> vector1 or vector2 results in a vector that contains all original elements (label sets + values) of vector1 and additionally all elements of vector2 which do not have matching label sets in vector1.

In this case both queries on the right and left side of `or` produce equal set of labels - `{}` (empty set) and all datapoints are taken from the left part.

**Comment by luzejia** [comment]
> Hello @luzejia, this happens because `or` operator per [PromQL spec ](https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators) works like this:
> 
> > vector1 or vector2 results in a vector that contains all original elements (label sets + values) of vector1 and additionally all elements of vector2 which do not have matching label sets in vector1.
> 
> In this case both queries on the right and left side of `or` produce equal set of labels - `{}` (empty set) and all datapoints are taken from the left part.


Thank you, this situation brings me some questions:

There are two metrics, they have the same set of labels, I do the following OR operation:

 (linux_disk_read_bps{} > bool 5000) or (linux_disk_write_bps{}  > bool 5000)
 
 At this point I will never get the one on the right, even if the left is 0 and the right is 1, only the series of 0 on the left will be returned. But I hope it will be returned as long as the conditions are met.

**Comment by zekker6** [comment]
> (linux_disk_read_bps{} > bool 5000) or (linux_disk_write_bps{} > bool 5000)

This query result is: for each data point in `linux_disk_read_bps` return 1 if value `is > 5000` and `0` otherwise  (see Prometheus docs [here](https://prometheus.io/docs/prometheus/latest/querying/operators/#comparison-binary-operators)). After that when `or` is executed each timestamp has a value of `0` or `1` on the left side, so right side is never used.

In order to get values from both series `bool` filter is not needed, query should be similar to this: `(linux_disk_read_bps{} > 5000) or (linux_disk_write_bps{} > 5000)`.
This query will out datapoints with values `< 5000`. In this case left part of query will only have values greater than 5000 and the rest will be filled by the right part.

**Comment by luzejia** [comment]
> > (linux_disk_read_bps{} > bool 5000) or (linux_disk_write_bps{} > bool 5000)
> 
> This query result is: for each data point in `linux_disk_read_bps` return 1 if value `is > 5000` and `0` otherwise (see Prometheus docs [here](https://prometheus.io/docs/prometheus/latest/querying/operators/#comparison-binary-operators)). After that when `or` is executed each timestamp has a value of `0` or `1` on the left side, so right side is never used.
> 
> In order to get values from both series `bool` filter is not needed, query should be similar to this: `(linux_disk_read_bps{} > 5000) or (linux_disk_write_bps{} > 5000)`. This query will out datapoints with values `< 5000`. In this case left part of query will only have values greater than 5000 and the rest will be filled by the right part.

If I have linux_disk_read_bps{instance="192.168.0.1"}=6000 and linux_disk_write_bps{instance="192.168.0.1"}=8000, I hope to get both at the same time through `(linux_disk_read_bps{} > 5000) or (linux_disk_write_bps{} > 5000)`.
But in this case, only linux_disk_read_bps{instance="192.168.0.1"}=6000 can be obtained.

Is there any good way to achieve this?

**Comment by zekker6** [comment]
> If I have linux_disk_read_bps{instance="192.168.0.1"}=6000 and linux_disk_write_bps{instance="192.168.0.1"}=8000, I hope to get both at the same time through (linux_disk_read_bps{} > 5000) or (linux_disk_write_bps{} > 5000).
But in this case, only linux_disk_read_bps{instance="192.168.0.1"}=6000 can be obtained.
> Is there any good way to achieve this?

You can use the following query: `{__name__=~"linux_disk_read_bps|linux_disk_write_bps"} > 5000`
It will use meta label `__name__` to filter metric by its name and `> 5000` will filter the value. As the result both metrics will be present.

**Comment by luzejia** [comment]
> > If I have linux_disk_read_bps{instance="192.168.0.1"}=6000 and linux_disk_write_bps{instance="192.168.0.1"}=8000, I hope to get both at the same time through (linux_disk_read_bps{} > 5000) or (linux_disk_write_bps{} > 5000).
> > But in this case, only linux_disk_read_bps{instance="192.168.0.1"}=6000 can be obtained.
> > Is there any good way to achieve this?
> 
> You can use the following query: `{__name__=~"linux_disk_read_bps|linux_disk_write_bps"} > 5000` It will use meta label `__name__` to filter metric by its name and `> 5000` will filter the value. As the result both metrics will be present.

Thank you so much!
