### ISSUE TITLE
vmui: move input focus to the query input field after the initial load

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#5479]
### Is your feature request related to a problem? Please describe

The most frequent action after opening `vmui` is editing the query. Currently the user needs to click the query input field before editing the query.

### Describe the solution you'd like

It would be great if the query input field is automatically focused just after opening the `vmui`. The cursor should be moved to the end of the query on automatic focus. The same applies to all the other views at `vmui`, which contain main input field - it would be great if `vmui` would automatically focus this field when switching to the corresponding view.

The automatic focus shouldn't trigger auto-suggestion, since this isn't what most users expect. The auto-suggestion can be triggered after the user starts editing the input field contents.

The automatic focus shouldn't be triggered when opening VMUI from appliances with touch screens (such as smartphones and tablets), since this usually opens a keyboard widget, which occupies half of the visible space. This isn't what most users expect.

**Comment by Loori-R** [comment]
Auto-focus for query input field added to `vmui` views starting from version [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing feature request as completed.
