### ISSUE TITLE
Questions on importing csv data

### ISSUE THREAD

**Issue by pavinil** [VictoriaMetrics/VictoriaMetrics#548]
1. As per documentation, "Each request to /api/v1/import/csv may contain arbitrary number of CSV lines.". Can you please give me an example on how to implement this? Should the distinct lines be separated by a new line character? The documentation has an example only for a single line.
2. How can I specify custom timestamp format if the first csv column contains time in this format - 2020/06/09 04:24:32.016
I tried ?format=1:time:custom:2006/01/02 15:04:05.000, but I am getting a 400 response

**Comment by valyala** [comment]
@pavinil , see answers below:

>  Can you please give me an example on how to implement this? Should the distinct lines be separated by a new line character?

Distinct lines must be separated by a new line character. For example,
```csv
foo,bar,123
baz,aaa,345
```

> How can I specify custom timestamp format if the first csv column contains time in this format - 2020/06/09 04:24:32.016

Note that the `format` value must be properly encoded with [percent encoding](https://en.wikipedia.org/wiki/Percent-encoding). For example:
```
?format=1%3Atime%3Acustom%3A2006%2F01%2F02%2015%3A04%3A05.000
```

**Comment by berghauz** [comment]
During swappnig from influxdb (with prometheus incompatible metric names with "-") faced with problem, 
`remoteAddr: "10.7.8.136:37726"; error in "/insert/0/prometheus/api/v1/import/csv": cannot read csv data: too long line: more than 262144 bytes
== Info: we are done reading and this is set to close, stop send
== Info: Closing connection 0
`
Is there any way import csv other than read&insert line by line in case of large csv files? Looks like vminsert or vmagent haven't any options for line size tuning.

**Comment by berghauz** [comment]
Well, curl with -d concatenate lines from file in one big line, so solution is simple - use --data-binary instead.

**Comment by denisgolius** [comment]
Closing this issue as resolved.
