### ISSUE TITLE
VictoriaMetrics dashboard: add vm_merge_need_free_disk_space panel

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#5484]
### Is your feature request related to a problem? Please describe

We had a case where merges were blocked for several weeks and didn't realize it.

### Describe the solution you'd like

Add a panel for `vm_merge_need_free_disk_space` to the Troubleshooting or Storage section.

It seems like an important metric, since a low disk situation may block merges, causing the storage to fill even faster (and maybe slower queries).

**Comment by hagen1778** [comment]
Hi @belm0! This metric isn't exposed anymore starting from 1.94. See why [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/686#issuecomment-1733844128).

I'd suggest sticking to a [traditional way](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/326a77c6974454f1585ac662b762138727fa41f4/deployment/docker/alerts.yml#L35-L50) of identifying disk space issues.
