### ISSUE TITLE
Can't store `int64` (> 2^53) values with zero precision loss

### ISSUE THREAD

**Issue by Kaushal28** [VictoriaMetrics/VictoriaMetrics#5485]
### Describe the bug

I am storing nano second field values in Victoria metrics. But that results in the precision loss as mentioned here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/213

The fix for the above issue just improves the precision but it still results in precision loss. Since I am storing time (nano seconds) I will need the exact precision.

I am migrating from influxDb, where I was able to store nano seconds precisely.

### To Reproduce

`curl -d 'measurement,tag1=value1,tag2=value2 field1=1702878157125929618,field2=1702878157125929618' -X POST http://10.111.229.225:8480/insert/0/influx/write`

Then do

`curl 'http://<vm-select-ip>:8481/select/0/prometheus/api/v1/query' --data-urlencode 'query={__name__=~".+"}[1h]'`

This will return field value which are slightly different from what provided in the insert query: `1702878157125929472`

### Version

vminsert pod version: `vminsert-20231002-215600-tags-v1.94.0-cluster-0-gcf93d27bc`
vmselect pod version: `vmselect-20231002-215651-tags-v1.94.0-cluster-0-gcf93d27bc`
vmstorage pod version: `vmstorage-20231002-215726-tags-v1.94.0-cluster-0-gcf93d27bc`

**Comment by dmitryk-dk** [comment]
Hi @Kaushal28 ! In the documentation we mentioned that 
https://docs.victoriametrics.com/guides/migrate-from-influx.html#data-model-differences

```
timestamps are stored with nanosecond resolution in InfluxDB, while in VictoriaMetrics it is milliseconds;
```

**Comment by dmitryk-dk** [comment]
Hi @Kaushal28 ! VictoriaMetrics stores all values in `float64` format. So, these values can lose precision when the value contains more than 12-15 decimal digits.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/163b3fb3-4dd7-403f-bf88-68db03512375)

The 53-bit significand precision gives from 15 to 17 significant decimal digits precision (2−53 ≈ 1.11 × 10−16).

The format is written with the significand having an implicit integer bit of value 1 (except for special data, see the exponent encoding below). With the 52 bits of the fraction (F) significand appearing in the memory format, the total precision is therefore 53 bits (approximately 16 decimal digits, 53 log10(2) ≈ 15.955). 
So in that case the fix you mentioned https://github.com/VictoriaMetrics/VictoriaMetrics/issues/213 explains all information about your bug. 

We will update the documentation with this information about `float64` values in the Key Concept part of the documentation.

**Comment by valyala** [comment]
Closing this question as answered.
