### ISSUE TITLE
Label name and label value are ''=1 / ''

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#5487]
### Describe the bug

When I deploy vm-cluster, I found strange label name and label value.
I don't known why:

my local vm-select address is: http://127.0.0.1:28481/select/0/vmui/#/cardinality?date=2023-12-19

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4198375/5e4034ad-92ef-415b-867e-64e05cf36904)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4198375/0be00701-74a3-449c-b419-2ea52af088ff)

### To Reproduce

N/A

### Version

1.96.0-cluster

**Comment by dmitryk-dk** [comment]
Hi @ahfuzhang ! Could you try to call api [/api/v1/labels](https://prometheus.io/docs/prometheus/latest/querying/api/#getting-label-names). What it return for the same period of time? Can you call [/api/v1/status/tsdb](https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-stats) and check does this labels present into the response?

**Comment by dmitryk-dk** [comment]
Hi @ahfuzhang ! Can you downgrade vmselect to v1.95.1 and check is this issue reproducible?

**Comment by ahfuzhang** [comment]
http://127.0.0.1:8481/select/0/prometheus/api/v1/labels
at this path, every data is good.

http://127.0.0.1:8481/select/0/prometheus/api/v1/status/tsdb
at this path, I saw error datas like this:

```
"seriesCountByLabelValuePair": [
{
"name": "env=test",
"value": 34687
},
{
"name": "job=file",
"value": 34687
},
{
"name": "region=HK",
"value": 34687
},
{
"name": "from=vm-agent",
"value": 27294
},
{
"name": "''=1",
"value": 21324
},
{
"name": "cluster=realtime-cluster",
"value": 15376
},
{
"name": "''=0",
"value": 13354
},
{
"name": "cluster=self-monitor-cluster",
"value": 9850
},
{
"name": "cluster=alert-cluster",
"value": 9304
},
{
"name": "is_set=false",
"value": 8521
}
],
```

**Comment by ahfuzhang** [comment]
I find the reason:

at vm-agent command line, I set:
```
-promscrape.cluster.memberLabel=''
-remoteWrite.label=''
```

When I comment those two, problems fixed.

I think we'd better add a check on vm-agent.

@dmitryk-dk dmitryk-dk

**Comment by dmitryk-dk** [comment]
> I find the reason:
> 
> at vm-agent command line, I set:
> 
> ```
> -promscrape.cluster.memberLabel=''
> -remoteWrite.label=''
> ```
> 
> When I comment those two, problems fixed.
> 
> I think we'd better add a check on vm-agent.
> 
> @dmitryk-dk dmitryk-dk

Hi ! I think vmstorage shouldn't store the empty labels. I will check it on vmstorage side and if it has this problem we will fix it
