### ISSUE TITLE
docs  about `-maxConcurrentInserts`  have been outdated

### ISSUE THREAD

**Issue by FOWind** [VictoriaMetrics/VictoriaMetrics#5488]
### Describe the bug

currently  `-maxConcurrentInserts` is desribed as below in doc
```sh
-maxConcurrentInserts int
     The maximum number of concurrent insert requests. Default value should work for most cases, since it minimizes the memory usage. The default value can be increased when clients send data over slow networks. See also -insert.maxQueueDuration (default 32)
```
but in code is 
```golang
maxConcurrentInserts = flag.Int("maxConcurrentInserts", 2*cgroup.AvailableCPUs(), "The maximum number of concurrent insert requests. "+
		"Default value should work for most cases, since it minimizes the memory usage. The default value can be increased when clients send data over slow networks. "+
		"See also -insert.maxQueueDuration")
```

to match the code should change the doc

### To Reproduce

https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html?highlight=KISS#list-of-command-line-flags-for-vminsert
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html?highlight=KISS#list-of-command-line-flags-for-vmstorage

### Version

master

**Comment by dmitryk-dk** [comment]
Hi @FOWind ! What confuses you in the description of the documentation?

**Comment by FOWind** [comment]
The default value of `-maxConcurrentInserts`.

I found it was generated  at compile time.  So the document will show `32`, but actually on my server environment it's 64 .

**Comment by dmitryk-dk** [comment]
I think we can remove default value. Thank you!

**Comment by dmitryk-dk** [comment]
Hi @FOWind ! Docs were updated. Close the issue. If you need to discuss anything or have another question, feel free to reopen
