### ISSUE TITLE
FIPS compliant build for vmagent

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#5489]
### Is your feature request related to a problem? Please describe

vmagent uses a static linker for the Kafka library. We need to make sure that we use an FIPS-compliant version of OpenSSL for Kafka

- modify the existing build for vmagent and include a FIPS-complaint OpenSSL for Kafka
or 
- release separate vmagent build, which is FIPS-complaint

**Comment by f41gh7** [comment]
vmagent is already FIPS complaint as any other VM components.

 But it may be required to configure system for openssl usage:

https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/fips/README.md#enabling-fips-provider
