### ISSUE TITLE
VictoriaMetrics returns too many points

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#549]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3659110/84353121-2554bd80-abf1-11ea-9810-9c4363e8bcc3.png)
Metric looks to be 40 all day on June 9.
When I turn down the timerange, I see only two dots.
![image](https://user-images.githubusercontent.com/3659110/84353475-d0fe0d80-abf1-11ea-8655-ebadbd821dab.png)
![image](https://user-images.githubusercontent.com/3659110/84353509-e1ae8380-abf1-11ea-855e-53e8917142cf.png)

It looks like VM has returned too many points. I'm not sure if the query expression is wrong or if vm's behavior is wrong.
```
/api/v1/query_range?query={__name__="lavie",__lavie_g1__="build",__lavie_g2__="zae",__lavie_g3__="master",__lavie_g4__="lavie04",__lavie_g5__="post-build",__lavie_g6__="duration",__lavie_g7__="max"}&start=1591591920&end=1591790432&step=10
```
![image](https://user-images.githubusercontent.com/3659110/84353907-90eb5a80-abf2-11ea-8ed6-3cad78117811.png)

**Expected behavior**
VM only returns two points, and I can control how the graph is rendered through grafana's options.
![image](https://user-images.githubusercontent.com/3659110/84354150-f5a6b500-abf2-11ea-9f91-5974f32a04ea.png)

**Version**
vmstorage-20200605-193050-tags-v1.37.0-cluster-0-g9f55dea16
vmselect-20200605-193046-tags-v1.37.0-cluster-0-g9f55dea16
vminsert-20200605-193042-tags-v1.37.0-cluster-0-g9f55dea16

**Comment by valyala** [comment]
@faceair , could you downgrade to v1.36.3 and verify whether the issue is reproduced there?

Note that `/api/v1/query_range` returns calculated data points instead of raw data points. The interval between each returned data point equals to `step` arg.

Could you query raw data points from `/api/v1/export` according to [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-export-time-series)?

**Comment by faceair** [comment]
I know that `/api/v1/query_range` returns calculated data points instead of raw data points. And I can change the behavior of the calculation with functions such as `sum_over_range` `max_over_range` `min_over_range`. 
By name the calculation only takes place between the range(step), if the interval exceeds the range(step), it is not calculated.
I don't know if prometheus is behaving this way, but this is how I understand it now.

If the interval between return values is always equal to step, then it won't return null, grafana's option looks like it's hardly going to work.
![image](https://user-images.githubusercontent.com/3659110/84558505-e300bd00-ad65-11ea-96cf-b3b7c9828fa8.png)

**Comment by faceair** [comment]
I tried downgrading vmselect & vmstorage to v1.36.3, but the behavior is the same.

**Comment by faceair** [comment]
I've read the rollup code and I see that I've misunderstood something.
I thought rollup was calculated with step as the window, but it is actually calculated with scrape interval as the window.
I can overrides this window size by using max_lookback in the query or the search.minStalenessInterval command line argument.

**Comment by valyala** [comment]
@faceair , note that you can expicitly set the window by passing it in square brackets inside `sum_over_time` or any other rollup function. For example, `sum_over_time(metric{foo="bar"}[1h])` - would return the sum of all the `metric{foo="bar"}` values for the last hour. The window may be based on the `step` value: `[1i]` means one step, while `[10i]` means 10 `step` values. See more details at [MetricsQL page](https://victoriametrics.github.io/MetricsQL.html).

**Comment by faceair** [comment]
![image](https://user-images.githubusercontent.com/3659110/86492488-e30e3e80-bda0-11ea-94cd-da67da20a561.png)

But the window will be overwritten by the scrape interval, so I have to overwrite the scrape interval with max_lookback first.

**Comment by valyala** [comment]
The `window` is overwritten by scrape interval only if the following conditions are met:
* The used rollup function isn't included in the [rollupFuncsCannotAdjustWindow list](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9a2ba5b6d1bf462efee205982494d384a3e1fcef/app/vmselect/promql/rollup.go#L126)
* The provided `window` is smaller than the scrape interval

If at least a single condition isn't met, then the provided `window` value in square brackets is used. For instance, `sum_over_time` is included in the `rollupFuncsCannotAdjustWindow` list, so the `window` value is respected. If you feel that the `rollupFuncsCannotAdjustWindow` list should contain more rollup functions, then feel free opening an issue or sending a PR with  the justification.

**Comment by erkexzcx** [comment]
Looks like I am having the same issue. I have a script on my phone that pushes a single point at a random intervals to VictoriaMetrics, like every 30mins to 3 hours...

I expect to see that point only, but VictoriaMetrics just shows a line (multiiple points).:
![image](https://user-images.githubusercontent.com/5955795/205630514-4243e64e-f52a-4c4c-8793-cbcdbf38a576.png)

If I change `min step` duration in Grafana to e.g., 1s from 1minute, then points are shown accordingly (every 1s).

The same behaviour is on both standalone server and a cluster (of 1x select/insert/storage nodes). There is nothing to deduplicate in cluster mode...

If I use `sum_over_time` function, it shows properly:
![image](https://user-images.githubusercontent.com/5955795/205630777-1866c72e-3d1f-411e-8234-39edfe8c0170.png)


Is this intended behavior, or am I just used too much to InfluxQL?

**Comment by hagen1778** [comment]
It could be intended. Have you read https://docs.victoriametrics.com/guides/migrate-from-influx.html#basic-concepts ?
