### ISSUE TITLE
How to access VMUI

### ISSUE THREAD

**Issue by waleedabdelwahed89** [VictoriaMetrics/VictoriaMetrics#5490]
### Is your question request related to a specific component?

VMUI

### Describe the question in detail

Hello, 

I've deployed a small VM cluster, but i'm unable to access VMUI via http://vmselect:8481/select/accountID/vmui/

The question is, what do i need to do in order to enable the VMUI ? 
Do i need to configure vmauth as a prerequisites ? and how to get the accountID 
Any advise will be appreciated. Thank you

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @waleedabdelwahed89 ! If you don't configure any tenants, you should be able to see vmui over the next link
```URL with basic Web UI: http://<vmselect>:8481/select/<accountID>/vmui/``` where account id by default is 0
Please check this art of the documentation
https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format

**Comment by dmitryk-dk** [comment]
> Hi @dmitryk-dk, thanks a lot for your response indeed i haven't configured any tenants, but when i try to access this url it gives me this error "unsupported path" Not sure if there's extra configuration needed
> 
> curl http://localhost:8481/vmselect/0/vmui/ remoteAddr: "127.0.0.1:58592"; requestURI: /vmselect/0/vmui/; unsupported path requested: "/vmselect/0/vmui/"

you are using /vmselect/ into the path request, but should use /select/

`http://localhost:8481/select/0/vmui`

**Comment by waleedabdelwahed89** [comment]
Ohh, my bad, thanks again, should be ok now 🙏
