### ISSUE TITLE
why two function for default_roll_up and last_over_time

### ISSUE THREAD

**Issue by changshun-shi** [VictoriaMetrics/VictoriaMetrics#5499]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

According to this issue(https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526), 
The code became as follows. but I don't know the difference between them, they looks the same.
```
func rollupDefault(rfa *rollupFuncArg) float64 {
	values := rfa.values
	if len(values) == 0 {
		// Do not take into account rfa.prevValue, since it may lead
		// to inconsistent results comparing to Prometheus on broken time series
		// with irregular data points.
		return nan
	}
	// Intentionally do not skip the possible last Prometheus staleness mark.
	// See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1526 .
	return values[len(values)-1]
}

func rollupLast(rfa *rollupFuncArg) float64 {
	values := rfa.values
	if len(values) == 0 {
		// Do not take into account rfa.prevValue, since it may lead
		// to inconsistent results comparing to Prometheus on broken time series
		// with irregular data points.
		return nan
	}
	return values[len(values)-1]
}
```
So why two same functions instead of one before the commit for the 1526 issue

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> So why two same functions instead of one before the commit for the 1526 issue

I don't know answer to this. I've created a [PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5502) and mentioned the author of this change.

**Comment by changshun-shi** [comment]
👍

**Comment by hagen1778** [comment]
@changshun-shi the duplicate was removed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5502. Thanks for reporting!
