### ISSUE TITLE
TLS Support for Cluster Components

### ISSUE THREAD

**Issue by zbindenren** [VictoriaMetrics/VictoriaMetrics#550]
**Is your feature request related to a problem? Please describe.**
Our company has the policy that all communication has to be encrypted.

**Describe the solution you'd like**
In the single binary solution it is possible to configure TLS. It would be great to add the possibility to configure TLS for all cluster components.

**Describe alternatives you've considered**
Put a proxy in front of every component. This solution is a little cumbersome.

**Comment by zbindenren** [comment]
Am I right that I have to use vmauth for this purpose? But TLS within cluster is not possible?

**Comment by valyala** [comment]
It is expected that all the components in a single cluster are located in a protected private network. TLS layer adds unnecessary overhead in this case.

TLS may be necessary for data ingestion into `vminsert` and querying from `vmselect` components. Any http proxy or load balancer with TLS support may be used for this case. For example, nginx or [vmauth](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmauth/README.md).

We are ready to add TLS layer for internal communications between cluster components (i.e. `vminsert -> vmstorage` and `vmselect <-> vmstorage`) on enterprise subscription. Contact us at info@victoriametrics.com for details.

**Comment by mvpnitesh** [comment]
Hi Valyala,

From this link https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#security can we say TLS is supported for all Victoria Metric componenets?

**Comment by valyala** [comment]
> From this link https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#security can we say TLS is supported for all Victoria Metric componenets?

VictoriaMetrics cluster components - vminsert, vmselect and vmstorage - communicate with each other via custom protocol over plain TCP connections. It is expected that all the cluster component run in the same isolated private network. These connections don't support TLS. VictoriaMetrics components support TLS only for HTTP handlers enumerated [here](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format).

There are plans to add TLS support for connections between cluster components of VictoriaMetrics in [enterprise package](https://victoriametrics.com/products/enterprise/).

**Comment by valyala** [comment]
[Enterprise version of VictoriaMetrics cluster](https://victoriametrics.com/products/enterprise/) supports mTLS connections between vminsert <-> vmstorage and vmselect <-> vmstorage components starting from [v1.75.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#mtls-protection) for details. Closing this feature request as done.
