### ISSUE TITLE
The same series of data are sent to different vmserts, and whether different vminserts send this same series to the same vmstorage?

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5501]
### Is your question request related to a specific component?

vminsert

### Describe the question in detail

My vmagent uses k8s service to load balance data to different vminserts. Can different vminserts put the data of the same series into the same vmstorage?

Under the vm cluster architecture, and regardless of rerouting, is it guaranteed that the same series will always be sent to the same vmstorage?

like this:

metrics1 ------> vminsert1 -------> vmstorage2
metrics1 ------> vminsert2-------> vmstorage2
metrics1 ------> vminsert3-------> vmstorage2

metrics2 ------> vminsert1 -------> vmstorage4
metrics2 ------> vminsert2-------> vmstorage4
metrics2 ------> vminsert3-------> vmstorage4

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @luzejia !

> Can different vminserts put the data of the same series into the same vmstorage?

Yes, it is guaranteed - see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview
> vminsert - accepts the ingested data and spreads it among vmstorage nodes according to consistent hashing over metric name and all its labels

Time series received by vminsert [are consistently sharded](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview) among configured vmstorage nodes. As a sharding key vminsert is using time series name and labels, respecting their order. If the order of labels in time series is constantly changing, this could cause wrong sharding calculation and result in un-even and sub-optimal time series distribution across available vmstorages. It is expected that metrics pushing client is responsible for consistent labels order (like Prometheus or vmagent during scraping). If this can't be guaranteed, set -sortLabels=true cmd-line flag to vminsert. Please note, sorting may increase CPU usage for vminsert.

**Comment by luzejia** [comment]
> Hello @luzejia !
> 
> > Can different vminserts put the data of the same series into the same vmstorage?
> 
> Yes, it is guaranteed - see https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview
> 
> > vminsert - accepts the ingested data and spreads it among vmstorage nodes according to consistent hashing over metric name and all its labels
> 
> Time series received by vminsert [are consistently sharded](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#architecture-overview) among configured vmstorage nodes. As a sharding key vminsert is using time series name and labels, respecting their order. If the order of labels in time series is constantly changing, this could cause wrong sharding calculation and result in un-even and sub-optimal time series distribution across available vmstorages. It is expected that metrics pushing client is responsible for consistent labels order (like Prometheus or vmagent during scraping). If this can't be guaranteed, set -sortLabels=true cmd-line flag to vminsert. Please note, sorting may increase CPU usage for vminsert.

I understand, and thank you very much for reminding me about the label order.
