### ISSUE TITLE
What will happen if I insert the history data with the same timestamp?

### ISSUE THREAD

**Issue by christianxiao** [VictoriaMetrics/VictoriaMetrics#5504]
### Is your question request related to a specific component?

vminsert

### Describe the question in detail

We are using the VictoriaMetrics as a time series DB, and we are also migrating some services from TSDB.
We have some ETL tools which will backfill history data into the DB, and if the ETL tools have some bugs, we need to run the ETL tool again and insert the **UPDATED data** into the VM again, with the API  http://localhost:8480/insert/0/prometheus/api/v1/write. 
This won't be a problem with TSDB because it will override the old value with the new value if exists. But for VM, I am not sure what will happen if we insert the data again.
For example, my original data is  
```
2023-12-01 01:01:01 product_pv{url='/home'} 300
```
then I insert the newer data like
```
2023-12-01 01:01:01 product_pv{url='/home'} 310
```
So will my newer data be dropped? or both of them will be saved? and if I query product_pv, which value, 300 or 310 will be returned?
Thank you, VM team!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @christianxiao!

> So will my newer data be dropped? 

No. It will be stored. You can verify it by [exporting](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) the raw data.

>  if I query product_pv, which value, 300 or 310 will be returned?

Depends on the query. For aggregation queries both datapoints will be aggregated. For select queries - the random data point will be picked.

If you enable [deduplication](https://docs.victoriametrics.com/#deduplication), then its logic will kick-in:
> If multiple raw samples have the same timestamp on the given -dedup.minScrapeInterval discrete interval, then the sample with the biggest value is kept.

**Comment by christianxiao** [comment]
Hi, Hagen, thank you for your clear explanation! I also checked that there is a doc showing how to update the metric data in a Delete-Then-Import way. https://docs.victoriametrics.com/guides/guide-delete-or-replace-metrics.html
I guess I have two solutions now:
1. Delete-Then-Import way
2. Add a version label in the metrics, then query with the latest version value, for example: ``` 2023-12-01 01:01:01 product_pv{url='/home', version='3'} 310```

**Comment by hagen1778** [comment]
> Delete-Then-Import way

Be aware, deletes aren't meant to be used frequently as they are "soft deletes" - data is marked as deleted, not actually removed (for indexdb). So each delete actually has a small performance impact.

**Comment by christianxiao** [comment]
Hi, Hagen, thank you for your help, I will close this question.
