### ISSUE TITLE
Datapoints pannel in the VM Dashboard seems wrong

### ISSUE THREAD

**Issue by xunleii** [VictoriaMetrics/VictoriaMetrics#551]
**Describe the bug**
Currently, when we use the available Grafana dashboard for VM provided in this repo, the panel "Datapoints" seems wrong; on https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/victoriametrics.json#L1352, the number of data-points is divided by the amount of used storage (`datapoints-per-byte`), but the value name is `bytes-per-datapoint`. Is a mistake or I have misunderstood something ?

If it is a mistake, it is easy to fix: 
```diff
-              "expr": "sum(vm_rows{job=\"$job\", type != \"indexdb\"}) / sum(vm_data_size_bytes{job=\"$job\", type!=\"indexdb\"})",
+              "expr": "sum(vm_data_size_bytes{job=\"$job\", type!=\"indexdb\"}) / sum(vm_rows{job=\"$job\", type != \"indexdb\"})",
```

**To Reproduce**
Import the dashboard https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/victoriametrics.json on Grafana

**Expected behavior**
I expect to see the graph of `bytes-per-datapoint` and not `datapoints-per-byte`

**Screenshots**
_No screenshot_

**Version**
_Not applicable_

**Used command-line flags**
_Not applicable_

**Additional context**
_Not applicable_

**Comment by hagen1778** [comment]
Thanks for report @xunleii! See linked PRs for a fix.

**Comment by xunleii** [comment]
This dashboard is fixed in the latest (and older too) release, so I close this issue.
