### ISSUE TITLE
metricsql: increase calculates the value of counter to be zero

### ISSUE THREAD

**Issue by fyuan1316** [VictoriaMetrics/VictoriaMetrics#5510]
### Is your question request related to a specific component?

vmui

### Describe the question in detail

When using `increase` in vmui to calculate the change in value of the counter metric over time, I'm finding that some data is being calculated correctly and some data is being calculated as 0. I'm wondering if I'm not using it in the right way?
```
istio_request_duration_milliseconds_count{destination_msname="service-api-l1"}
```

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42265657/b975e6d9-f993-4994-853f-4ee14712193a)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42265657/e8c580a0-895e-41ca-aebc-2a77680c1557)

- First calculate the change in data for the first two hours from now (the change value should be 0)
```
increase(istio_request_duration_milliseconds_count{destination_msname="service-api-l1"}[2h])
```
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42265657/fc7614c9-2a8e-4a61-836f-837b7a75b252)

- Then calculate the change in data for the 4 hours prior to now, i.e., the start time is before 4:00 (the change value of counter should not be 0)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/42265657/33332dab-b3ae-4b38-a06e-f179e1e05aa8)

I've found two data points that are calculated to be zero, which is not as expected.
- /delay/{arg}
- /get
---
May I ask if there is something I am thinking about incorrectly in this process? Thanks in advance!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by fyuan1316** [comment]
By the way, during this period counter did not reset

**Comment by hagen1778** [comment]
Hello @fyuan1316! Could you please provide [/api/v1/export](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) for these series on this time interval? And queries you used for all experiments (including time ranges).

**Comment by fyuan1316** [comment]
@hagen1778 Thanks for your quick reply.  Here is the exported data
start: 1703144441
end: 1703214041
[data.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/13748077/data.txt)

**Comment by hagen1778** [comment]
Thanks for provided data!

You're facing a corner case when selected time series starts from a non-zero value. For example, the series `{request_operation_path="/delay/{arg}", source_msname=""}` starts from `3` in your example. To calculate increase for this time series we need 2 datapoints: last datapoint on [interval], and first datapoint on [interval]. But the interval you use in your example exceeds the lifetime of this series. In other words, at now()-4h that time series didn't exist, it is null.

When previous data point doesn't exist, VM can assume two things:
1. It could be that previous datapoint should be 0, we just don't have that sample recorded. So increase()=3-0=3
2. It could be that this metric started with `3` right away. So increase()=3-3=0. There are many default metrics exposed by exporters which start from non-zero values. Like OS-level counters for CPU or network.

To learn more about this problem check this ticket https://github.com/VictoriaMetrics/VictoriaMetrics/issues/962

The current logic is here https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7575f5c501c8860da97d31969dfa8e72d50fec14/app/vmselect/promql/rollup.go#L1701-L1721

If you want to avoid using this heuristic - try using `increase_pure` function. It assumes first datapoint is always 0.

**Comment by fyuan1316** [comment]
@hagen1778 Thank you very much for your detailed instructions and the advice given to use `increase_pure`, it solved the problem I was experiencing perfectly.

Also, after taking a deeper look at the code implementation, I was wondering if we could make some minor adjustments so that the metrics calculations in this scenario reflect a consistent behavior.

The current heuristic judgment logic, in scenarios where the value of the indicator does not change, degenerates into a judgment on the value of the indicator.
- if math.Abs(values[0]) < 10  then result= values[last]-0;
- If math.Abs(values[0]) >= 10 then result= values[last]-values[0];

This results in metrics with the same data characteristics showing different results after an "increase" calculation, simply because the values are different. (As the screenshot shows)

I'm trying to keep the "increase" behavior consistent in pr. What are your thoughts on this idea? ：）

**Comment by fyuan1316** [comment]
@hagen1778 
I was wondering if you've had a chance to take a look at PR and what your thoughts are on this tweak that enhances the consistency of the behavior of data query results?

**Comment by jiekun** [comment]
Close per https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5524#discussion_r1447353679
