### ISSUE TITLE
Support for `username_file` in scrape config (basic_auth) similar to prometheus

### ISSUE THREAD

**Issue by wasim-nihal** [VictoriaMetrics/VictoriaMetrics#5511]
### Is your feature request related to a problem? Please describe

The prometheus version https://github.com/prometheus/common/releases/tag/v0.45.0 , added the support to configure the basic auth username using a file, by introducing a new field  `username_file`.

The same is currently not supported in Victoria Metrics and it fails to startup with any scrape config that has the `username_file` field for basic auth.

https://github.com/prometheus/common/blob/686da346a82cffad41db9e713b7283789eed8c1b/config/http_config.go#L130

### Describe the solution you'd like

It is good to align Victoria Metrics as per Prometheus' config and add the support for `username_file` in Victoria Metrics' BasicAuthConfig under promauth.

### Additional information

I'd like to submit a pull request for this if it's acceptable.

**Comment by hagen1778** [comment]
> I'd like to submit a pull request for this if it's acceptable.

Hello! Sounds good for config compatibility between Prometheus and VictoriaMetrics. Would appreciate the pull request for this!

**Comment by kevinmingtarja** [comment]
Hi, I'd like to contribute to this!

**Comment by wasim-nihal** [comment]
Hi @kevinmingtarja , thank you for your willingness to contribute. However, I have already started working on the ticket and will raise a PR for this. Appreciate your interest here.

**Comment by valyala** [comment]
`vmagent` gained support for `username_file` option inside `basic_auth` section at [`scrape_configs`](https://docs.victoriametrics.com/sd_configs/#http-api-client-options) starting from [v1.97.1](https://docs.victoriametrics.com/CHANGELOG.html). Closing the feature request as done.
