### ISSUE TITLE
Getting a token via AWS IMDSv1 is disabled on the VM in Yandex Cloud

### ISSUE THREAD

**Issue by vmazgo** [VictoriaMetrics/VictoriaMetrics#5513]
### Describe the bug

Amazon EC2 Instance Metadata Service version 1 (IMDSv1) has a number of drawbacks. The most critical of them is that there is a risk of compromising a service account token via the metadata service using a Server-Side Request Forgery (SSRF) attack. Yandex Cloud had disabled getting a service account token via Amazon EC2 IMDSv1.
As a result when function getInstanceCreds in https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/discovery/yandexcloud/api.go is trying to reach   http://169.254.169.254/latest/meta-data/iam/security-credentials/default it is getting an error:

```
Token is disabled for <VM-ID>
```

It is necessary to use Google Compute Engine instead of Amazon EC2 IMDSv1 : change "http://169.254.169.254/latest/meta-data/iam/security-credentials/default" to "Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token" and refactor code of `getInstanceCreds()` to handle answer.

### To Reproduce

1. Create VM with internal service account following https://cloud.yandex.com/en-ru/docs/compute/operations/vm-connect/auth-inside-vm#link-with-exist-instance
2. Use yandexcloud_sd from that VM

### Version

latest

**Comment by hagen1778** [comment]
I'm afraid I'm not familiar with YC to triage this ticket.
Tagging the author of the YC SD @ITD27M01. And @f41gh7 as a subject expert.

**Comment by ITD27M01** [comment]
Hi guys. The metadata URL is managed by switches on virtual machine settings and users could enable them for VM cluster vms as a workaround:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3703483/8d6a1373-caab-4ff3-a93e-f9026f1913b0)

I agree that there should be support for both methods and I have a question here, what should be by default? The obsoleted AWS (IMDSv1) is disabled by default now, but setting the default to Google Compute Engine format in configs will broke the existing installation during upgrades.

**Comment by AndrewChubatiuk** [comment]
Reopening till it's released

**Comment by valyala** [comment]
The commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/43049503917686e881fe854c04e0b6447b805419 has been included in [v1.102.0 release](https://docs.victoriametrics.com/changelog/). Closing the issue as fixed.

@vmazgo , @ITD27M01 , please re-open the issue if it isn't fixed yet, since we do not have Yandex Cloud account for the verification.
