### ISSUE TITLE
rules error but the reload interface returns 200

### ISSUE THREAD

**Issue by SRE-Rick** [VictoriaMetrics/VictoriaMetrics#5517]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

When my rules were incorrect, vmalert reported an error, but my curl reload interface returned 200, preventing me from finding the problem with my rules in time.I want the reload interface not to return 200 when my rules are wrong
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/86993048/f737949e-ad72-464e-a08c-25da9e150095)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/86993048/3e922f87-04de-4787-82d3-1c1c8cc8eacf)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by denisgolius** [comment]
Hey @SRE-Rick , could you please check your files via `vmalert` and `-dryRun` flag? The error from the latest screenshot said that there is an error in syntax.

```bash
  -dryRun
     Whether to check only config files without running vmalert. The rules file are validated. The -rule flag must be specified.
```
