### ISSUE TITLE
or operator not working as expected on query_range

### ISSUE THREAD

**Issue by xunleii** [VictoriaMetrics/VictoriaMetrics#552]
**Describe the bug**
When I use `or` on a query_range (`count(up == 0) or vector(0)`), VM doesn't return the second value (right operand) if the first one is `null` (left operand), as Prometheus did. The second operand is only returned if all returned values of the first operand are `null`.

**To Reproduce**
It can be easily reproducible by using requests with "future" values (because it returns null values):
- Victoria Metrics: [http://play-grafana.victoriametrics.com](http://play-grafana.victoriametrics.com:3000/explore?orgId=1&left=%5B%22now-50m%22,%22now%2B50m%22,%22VictoriaMetrics_demo%22,%7B%22expr%22:%22count(up)%20or%20vector(0)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) (works when [we use only "future" values](http://play-grafana.victoriametrics.com:3000/explore?orgId=1&left=%5B%22now%2B10m%22,%22now%2B50m%22,%22VictoriaMetrics_demo%22,%7B%22expr%22:%22count(up)%20or%20vector(0)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D))
- Prometheus: [https://play.grafana.org](https://play.grafana.org/explore?orgId=1&left=%5B%22now-50m%22,%22now%2B50m%22,%22demo.robustperception.io%22,%7B%22expr%22:%22count(up)%20or%20vector(0)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

**Expected behavior**
I expect a response with second values if the first one is `null`.

**Version**
The same used on your [playground](http://play-grafana.victoriametrics.com:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22VictoriaMetrics_demo%22,%7B%22expr%22:%22count(vm_app_version)%20by%20(version)%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Bfalse,true,true,%22none%22%5D%7D%5D):
- `vmselect-20200605-210748-heads-master-0-gf10124612`
- `vmstorage-20200605-210906-heads-master-0-gf10124612`
- `vminsert-20200605-210832-heads-master-0-gf10124612`

**Comment by valyala** [comment]
@xunleii , thanks for the bug report!

The issue should be fixed in the following commits:

* single-node version - 88e1b7d144e87c632765ce4c2f8f9abd7596efa8
* cluster version - 6939e36fdda5d81f36301eb46730b3293415ad98

These commits will be included in the next release. In the mean time you can build VictoriaMetrics from the commits mentioned above according to [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#building-from-sources) and verify whether the issue is fixed there

**Comment by valyala** [comment]
FYI, the bugfix has been included in VictoriaMetrics [v1.37.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by xunleii** [comment]
@valyala, thanks a lot for this fix. I close this issue because it already released.

**Comment by valyala** [comment]
Thanks for closing the issue! I forgot closing it after v1.37.1 release.
