### ISSUE TITLE
How to install with docker compose

### ISSUE THREAD

**Issue by VibeEly** [VictoriaMetrics/VictoriaMetrics#5525]
### Is your question request related to a specific component?

VictoriaMetrics,Docker,Docker Compose,Portainer

### Describe the question in detail

I would like to install VictoriaMetrics in a docker container via docker compose in Portainer.

I would also like to install the following packages in containers:

- vmagent  
- vmalert  
- victorialogs  
- alertmanager  
- grafana  
- fluentbit  

These components are all included in the docker compose file found at source VictoriaMetrics/deployment/docker/docker-compose.yml.

I've spent a few days reading the VM documentation and source code. I see that the included docker-compose.yml expects additional yml files to be included. It also has configuration files for other packages located in the main VictoriaMetrics folder that it depends on. It expects all this to be ran with a docker command line, from the root directory of the downloaded VM package.

Install instructions: `make docker-single-up` from the root of the VictoriaMetrics repository.

Can I install it with Portainer with docker compose instead of the command line? Normally I have Portainer download the images and manage docker containers in a central place. I know this is kind of a 'noob' question but I really appreciate any help <3.

The [Quick Start](https://docs.victoriametrics.com/Quick-Start.html) guide says one way to install VictoriaMetrics via docker is:

```docker pull victoriametrics/victoria-metrics:latest  
docker run -it --rm -v 'pwd'/victoria-metrics-data:/victoria-metrics-data -p 8428:8428 victoriametrics/victoria-metrics:latest
```

I use Portainer and docker compose to launch containers, so I wrote the above command as a compose yml file:

```version: "3"
name: victoria-metrics
services:
    victoria-metrics:
        stdin_open: true
        tty: true
        volumes:
            - /home/XXX/apps/victoria-metrics/data2:/victoria-metrics-data
        ports:
            - 8428:8428
        image: victoriametrics/victoria-metrics:latest
```

That successfully launches the base VictoriaMetrics service. I can visit it at IP:8428. To launch the other packages above, I need to configure them also. I see the instructions for that in the documentation. 

I imagine the final result looks something like below, but with the dependencies all included. I've never launched a container with multiple yml files and config files in other directories, although I see why that's beneficial. 

Is launching VictoriaMetrics with docker compose and Portainer doable?

Thank you.

VictoriaMetrics/deployment/docker/docker-compose.yml:

```version: "3.5"
services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.96.0
    depends_on:
      - "victoriametrics"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    networks:
      - vm_net
    restart: always
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.96.0
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    networks:
      - vm_net
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
      - ./../../dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./../../dashboards/victorialogs.json:/var/lib/grafana/dashboards/vl.json
      - ./../../dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./../../dashboards/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
    networks:
      - vm_net
    restart: always
  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert:v1.96.0
    depends_on:
      - "victoriametrics"
      - "alertmanager"
    ports:
      - 8880:8880
    volumes:
      - ./alerts.yml:/etc/alerts/alerts.yml
      - ./alerts-health.yml:/etc/alerts/alerts-health.yml
      - ./alerts-vmagent.yml:/etc/alerts/alerts-vmagent.yml
      - ./alerts-vmalert.yml:/etc/alerts/alerts-vmalert.yml
    command:
      - "--datasource.url=http://victoriametrics:8428/"
      - "--remoteRead.url=http://victoriametrics:8428/"
      - "--remoteWrite.url=http://victoriametrics:8428/"
      - "--notifier.url=http://alertmanager:9093/"
      - "--rule=/etc/alerts/*.yml"
      # display source of alerts in grafana
      - "--external.url=http://127.0.0.1:3000" #grafana outside container
      # when copypaste the line be aware of '$$' for escaping in '$expr'
      - '--external.alert.source=explore?orgId=1&left={"datasource":"VictoriaMetrics","queries":[{"expr":{{$$expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"now-1h","to":"now"}}'
    networks:
      - vm_net
    restart: always
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./alertmanager.yml:/config/alertmanager.yml
    command:
      - "--config.file=/config/alertmanager.yml"
    ports:
      - 9093:9093
    networks:
      - vm_net
    restart: always
  fluentbit:
    container_name: fluentbit
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on: [victorialogs]
    ports:
      - "5140:5140"
    networks:
      - vm_net
  victorialogs:
    container_name: victorialogs
    image: docker.io/victoriametrics/victoria-logs:v0.4.2-victorialogs
    command:
      - "--storageDataPath=/vlogs"
      - "--httpListenAddr=:9428"
    volumes:
      - victorialogs-fluentbit:/vlogs
    ports:
      - "9428:9428"
    networks:
      - vm_net
volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}
  victorialogs-fluentbit: {}
networks:
  vm_net:
```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by ahfuzhang** [comment]
you can use my code: 
https://github.com/ahfuzhang/deploy_VictoriaMetrics_cluster

**Comment by hagen1778** [comment]
Closing as answered.
