### ISSUE TITLE
Can't return the total number of points in a series, despite it being present in the error message?

### ISSUE THREAD

**Issue by dandv** [VictoriaMetrics/VictoriaMetrics#5530]
### Describe the bug

Apologies for the dumb question, but how do you *count* how many points there are in a series that might have "too many points"?

If I send `count_over_time(metric_name{label_selector}[1y])` to the `/query` HTTP API endpoint, I get

> `error when executing query="count(...)" on the time range (start=..., end=..., step=300000): too many points for the given start=..., end=... and step=300000: 840961; the maximum number of points is 30000; (see -search.maxPointsPerTimeseries command-line flag)`

I just want the NUMBER of points, not the actual points or an average or anything, and the error message seems to already return the number of points ("840961"). This is [another](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2467) perplexing difference vs. InfluxDB or any other database that never complains about returning **counts**. What am I missing?

### To Reproduce

`count_over_time(metric_name{label_selector}[10y])`

### Version

victoria-metrics-20231212-224437-tags-v1.96.0-0-g304fe0565

### Used command-line flags

-retentionPeriod=100y

**Comment by hagen1778** [comment]
Hello @dandv!

The `search.maxPointsPerTimeseries` purpose is to prevent the client (which is usually a Grafana or vmui) from getting overloaded with response. Usually, such clients try to plot response visually as a time series line. It makes no point to plot a time series which has more than 30k samples in it. The frontend script which will try to do this will likely fail or crash the browser.

Hence, I have the question to your question. The " to the /query HTTP API endpoint" API is called instant. This API doesn't return more than 1 data point per series, it can't hit the limit you provided. Please see [example on the playground ](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=count_over_time%28vm_cache_entries%5B1y%5D%29&g0.range_input=30m&g0.end_input=2024-01-16T09%3A08%3A19&g0.tab=1&g0.relative_time=last_30_minutes)where 1y query doesn't hit any default limits. 

I assume, you're using range query for the mentioned request and this is why you hit the limit you mentioned. If I am right, then such a query tries to execute `count_over_time(metric_name{label_selector}[1y])` with default step of 5min, which means it will return you `525600 minutes in a year / 5 default step = 105K samples per series`.

**Comment by jiekun** [comment]
Close as answered.
