### ISSUE TITLE
aggr_over_time query missing data

### ISSUE THREAD

**Issue by aluode99** [VictoriaMetrics/VictoriaMetrics#5534]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

Changing the step in sum_over_time and avg_over_time results in partial data loss.

(1) count(sum_over_time(as_pv_count{url=~"abc"}[$__interval])),window=step=__interval=2m，the query results are as follows.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/b8d67637-e2bc-4260-b748-e7b6036a0a47)

(2) count(sum_over_time(as_pv_count{url=~"abc"}[$__interval])),window=step=__interval=1m, the query results are as follows.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/d3affe25-ea40-4b32-b317-f51b1864bfde)

The query results with step=1m are more than 10 times the results with step=2m. With step=2m, some series are missing.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15179646/3e3d5653-9a97-423f-abab-cb5b7d79a630)

I tried setting deny_partial_response=1 and nocache=true, but there was no change in the query results. Is there something wrong with how I am using it?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
@aluode99 could you please provide [traces](https://docs.victoriametrics.com/#query-tracing) for query 1 and 2? It would be nice to determine a specific series or two which is present and not depending on the look-behind window in rollup function. And attach raw samples for these series to the ticket.

**Comment by jiekun** [comment]
Close as answered.
