### ISSUE TITLE
Accidentally performed curl -s' http://vmselect:8481/delete/0/prometheus/api/v1/admin/tsdb/delete_series? match[]=process_cpu_cores_available' How do I recover the data?

### ISSUE THREAD

**Issue by SRE-Rick** [VictoriaMetrics/VictoriaMetrics#5538]
### Is your question request related to a specific component?

Accidentally performed curl -s' http://vmselect:8481/delete/0/prometheus/api/v1/admin/tsdb/delete_series? match[]=process_cpu_cores_available' How do I recover the data?

### Describe the question in detail

Accidentally performed curl -s' http://vmselect:8481/delete/0/prometheus/api/v1/admin/tsdb/delete_series? match[]=process_cpu_cores_available' How do I recover the data?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @SRE-Rick, it is not possible to revert deleting the data. You need to restore the data from a [backup](https://docs.victoriametrics.com/vmbackup.html).

**Comment by zekker6** [comment]
Closing this as the answer have been provided and no follow-up questions were posted.
