### ISSUE TITLE
Unable to write data to victoriametrics - cannot read prompb.WriteRequest:

### ISSUE THREAD

**Issue by dennisbnym** [VictoriaMetrics/VictoriaMetrics#554]
**Describe the bug**
After starting Victoriametrics, when trying to hit the remote write url, getting the below error.

ERROR:
error in "/api/v1/write": cannot read prompb.WriteRequest: cannot decompress request with length 0: snappy: corrupt input

**To Reproduce**
Started victoriametrics container with version 1.36.3
The endpoint displays default metrics (http://victoriametircs.8428/metrics)
When trying to hit the remote write url in browser, getting the below error msg.

**error in "/api/v1/write": cannot read prompb.WriteRequest: cannot decompress request with length 0: snappy: corrupt input**

**Screenshots**
attached screenshot
![image](https://user-images.githubusercontent.com/66824342/84487385-4cc48c80-acbc-11ea-9f2c-51c0a2b30a32.png)

![image](https://user-images.githubusercontent.com/66824342/84487498-7382c300-acbc-11ea-9bb3-233814160504.png)

**Version**
Version 1.36.3
```

**Comment by dennisbnym** [comment]
Can someone please suggest a solution for this issue ?

**Comment by hagen1778** [comment]
Hello @dennisbnym! Remote write URL expects to receive data in Prometheus [remote_write](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) protocol and throws an error on getting unexpected input. What is your use case for using VM?

**Comment by dennisbnym** [comment]
Hello @hagen1778 

We are trying to use Victoriametrics as a centralized metric storage for Prometheus with increased data retention.

I have configured prometheus with the remote_write properties as below,
remote_write:
  - url: http://hostname:8428/api/v1/write

When i tried to configure the VM to Grafana datasource, im getting badgateway error. When i checked into the VM remote write url(http://hostname:8428/api/v1/write), got the above mentioned error.

**Comment by hagen1778** [comment]
As I mentioned before `/api/v1/write` path is for remote_write only, so Prometheus is configured correctly. But for Grafana datasource you need to specify just `http://hostname:8428` as address, or `http://r00jfrp0c:8428` like in your example. You can check [docker-compose](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker) setup for VM which is already bundled with [Prometheus](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/prometheus.yml) and [Grafana](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/provisioning/datasources/datasource.yml) configurations.

**Comment by dennisbnym** [comment]
Hi @hagen1778 

Sorry for not being clear, i followed the correct address for Grafana datasoure

Datasource: prometheus
url: http://hostname:8428

Getting the below error

![image](https://user-images.githubusercontent.com/66824342/84882737-529be280-b0ad-11ea-966a-831ab9414730.png)

**Comment by hagen1778** [comment]
Would be very helpful if you can fetch error message. You can get it by checking the Network tab in browser's [developer tools](https://developers.google.com/web/tools/chrome-devtools/network) or by checking VM logs for errors. So far it is hard to help without details. You can check docker-compose env from my prev response to verify that VM datasource in Grafana is working.

**Comment by valyala** [comment]
It looks like the issue has been resolved. Then closing it.

@dennisbnym , feel free re-opening it if it still bothers you.
