### ISSUE TITLE
How to set custom promscrape config files from vmagent installed from victoriametrics-k8s-stack? 

### ISSUE THREAD

**Issue by cyony95** [VictoriaMetrics/VictoriaMetrics#5540]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

How to set custom promscrape config files from vmagent installed from victoriametrics-k8s-stack in the case I dont want to add them as secrets or configmaps(as described in the helm chart readme). I want to add an extra container to the vmagent(which is a Custom resource in the k8s-stack helm-chart) that mounts an extra volume that the vmagent can read from. There is no way to change the CRD or deployment of the VMagent to do that in the k8s-stack. I know it can be done with a separate vmagent helm-chart, but I was wondering if it s possible from the vmagent inside the victoriametrics-k8s-stack.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @cyony95 

`victoria-metrics-k8s-stack` chart uses VictoriaMetrics operator to deploy its resources.
You can check API documentation for VMAgent CRD here - https://docs.victoriametrics.com/operator/api.html#vmagentspec
Operator based deployment configuration is dynamically updated by operator based on k8s resources and I don't think it is possible to include a reference to static file at the moment.

@Haleygo @Amper @f41gh7 Could you please correct me if I'm missing something here?

**Comment by Haleygo** [comment]
Hey @cyony95 ,
There is `containers` field under [vmagentSpec](https://docs.victoriametrics.com/operator/api.html#vmagentspec) to inject additions sidecar to vmagent pod, so you can have extra container to do things you want.

**Comment by cyony95** [comment]
Hi, @zekker6 , @Haleygo ,

Thank you so much for your answers. 
I actually did add a container under the vmagentspec, but it didn't want to create the deployment afterwards(even though the CRD  instance had it), maybe there is a mistake I made with that so I'll try it again. 
Additionally, I also need a shared volume between them, is that possible? (it s just an emptyDir so they can exchange some config files.

**Comment by Haleygo** [comment]
Yeah, the volume defined in pod can be shared by multiple containers as long as it's mounted to the container, see https://kubernetes.io/docs/concepts/storage/volumes/.

**Comment by zekker6** [comment]
@Haleygo I've also found an option with using `containers` but couldn't find an option to include custom config files afterwards, am I missing something?

**Comment by Haleygo** [comment]
> @Haleygo I've also found an option with using `containers` but couldn't find an option to include custom config files afterwards, am I missing something?

@zekker6 I think that should be two separate questions. `containers` here is only for adding extra container, you can use it to generate or download config file for vmagent container to use.
The config file is usually provided by secret, configmap or other local file that defined under `vmagentSpec.volumes`, and mounted by containers to use.

**Comment by jiekun** [comment]
close as answered.
