### ISSUE TITLE
Implement Extra Filters in VMLogs for Enhanced Log Query Customization

### ISSUE THREAD

**Issue by AlexisDucastel** [VictoriaMetrics/VictoriaMetrics#5542]
### Is your feature request related to a problem? Please describe

Currently, VictoriaMetrics supports the use of `extra_labels` as query parameters for customizing queries in a multi-tenancy environment. However, this feature is not available in VMLogs, particularly in vmauth. This limitation restricts the ability to apply fine-grained control over log data exposure and customization in environments where using tenants may not be feasible or desired. For instance, in a scenario where we wish to sandbox logs for security or organizational reasons without resorting to full multi-tenancy, the lack of this feature becomes a significant constraint.

### Describe the solution you'd like

I propose the implementation of `extra_filters` as query parameters in VMLogs, so that we can set it within the vmauth component. This feature would mirror the functionality currently available in VictoriaMetrics (with `extra_labels`), allowing users to apply additional filters to their log queries. For example, the use of a query parameter like `extra_filters=_stream:{cluster="dev"}` would enable users to add extra filters to their queries, thereby enhancing the granularity and precision of log data retrieval and exposure control.

### Describe alternatives you've considered

An alternative to this feature would be to continue using the existing multi-tenancy model, but this approach lacks the flexibility and granularity that `extra_filters` would provide. Another option would be to implement a custom proxy or middleware to handle these filters, but this would add unnecessary complexity and potential performance overhead to the system.

### Additional information

Given its potential impact and the fact that a similar functionality already exists in VictoriaMetrics, it seems like a valuable and feasible addition to VMLogs.

Lastly, I want to extend a heartfelt thank you to the entire VictoriaMetrics team for your exceptional work and dedication. Your efforts in continually improving and evolving the platform bring immense value to users like myself. Keep up the fantastic work – it’s truly appreciated!

**Comment by valyala** [comment]
Support for extra_filters has been added in [v0.40.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#extra-filters) for details.

Closing this feature request as done.

**Comment by valyala** [comment]
> That makes this makes the currently implemented feature quite limited and (imo) doesn't really solve what's described in this feature request.

@tumd , agreed. How about adding an ability to specify a list of values per each field name in the `extra_filters` and `extra_stream_filters` JSON objects? This should cover your case for extra stream filter for `{cluster=~"(dev|staging)"}`. It could be represented as the following `extra_stream_filters` value:

```json
{
  "cluster": ["dev", "staging"]
}
```

Historical note: these args accept `{fieldName1="value1", ... fieldNameN="valueN"}` JSON object instead of arbitrary [LogsQL filter](https://docs.victoriametrics.com/victorialogs/logsql/#filters) in order to satisfy [the initial idea on how to improve VictoriaLogs web UI](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7365#issuecomment-2447964259). It is much easier to construct properly a JSON object at web browser than an arbitrary LogsQL filter. This mostly concerns proper escaping of the used field values and field names, and, to the least extent, proper construction of regexps for stream filters.

Re-opening this feature request until `extra_filters` and `extra_stream_filters` query args support more flexible configuration.

**Comment by valyala** [comment]
FYI, the commit e6b7d25ab44a3c8b975943ffa2b08efb91698b01 adds ability to pass arbitrary [LogsQL filters](https://docs.victoriametrics.com/victorialogs/logsql/#filters) to `extra_filters` and `extra_stream_filters` query args as described in [these docs](https://docs.victoriametrics.com/victorialogs/querying/#extra-filters). This commit also allows passing an array of string values per each JSON entry as described in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5542#issuecomment-2536139341). This simplifies creating faceted search in [VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) according to [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7365#issuecomment-2447964259), when multiple values for the same field must be selected in filters.

This commit will be included in the next release of VictoriaLogs. In the mean time it is possible to verify this functionality by building VictoriaLogs from this commit according to [these docs](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code).

**Comment by valyala** [comment]
[VictoriaLogs querying APIs](https://docs.victoriametrics.com/victorialogs/querying/#http-api) support arbitrary [LogsQL filters](https://docs.victoriametrics.com/victorialogs/logsql/#filters) at `extra_filters` and `extra_stream_filters` query args starting from [v1.4.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#extra-filters) for details.

Closing the feature request as done.
