### ISSUE TITLE
vmstorage: panic when graceful shutdown caused by push metrics

### ISSUE THREAD

**Issue by zhdd99** [VictoriaMetrics/VictoriaMetrics#5548]
### Describe the bug

![showdown](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7420848/5a8568d5-8df8-4b0b-8951-458bae435659)
![panic](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/7420848/20281a8c-3f48-4499-a7aa-9daaa93b58c3)

I found that during the graceful shutdown of a vmstorage node, a panic was caused by pushing metrics。I can fix this bug. I will submit a Merge Request later to help VictoriaMetrics resolve this issue.

### To Reproduce

None

### Version

vmstorage-20231101-230002-tags-v1.93.7-cluster-0-g1415cd7cd

### Logs

No response

### Screenshots

No response

### Used command-line flags

No response

### Additional information

No response

**Comment by hagen1778** [comment]
Thanks for the ticket! The https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5549 has been merged and will be included into the next release.

**Comment by valyala** [comment]
FYI, while the https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5549 stops background push process from reading the metrics from the destroyed `server.Server` instance, it is better fixing the issue in another way - by de-registering server metrics before destroying the server itself. This makes unnecessary to stop background push process before destroying the server. This has been implemented in the commit 51060450488e955a07b904145ff56976a3069eaf . This commit will be included in the next release.

**Comment by valyala** [comment]
FYI, the fix for this issue has been included in [v1.87.13 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.13). The fix will be included also into the latest release.

**Comment by valyala** [comment]
FYI, the fix for this issue has been included in [v1.93.10 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.10).

**Comment by valyala** [comment]
This issue has been addressed in [v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing it as fixed then.
