### ISSUE TITLE
tfirst_over_time returns "duplicate output timeseries" when the series selector matches more than one series

### ISSUE THREAD

**Issue by dandv** [VictoriaMetrics/VictoriaMetrics#5554]
### Describe the bug

The [documentation for `tfirst_over_time`](https://docs.victoriametrics.com/MetricsQL.html#tfirst_over_time) says that it,

> returns the timestamp in seconds for the first raw sample on the given lookbehind window `d` per each time series returned from the given [series_selector](https://docs.victoriametrics.com/keyConcepts.html#filtering).

But if the series selector matches more than one series, I get this error:

> error when executing query=\"tfirst_over_time(..." for (...): duplicate output timeseries: {}

### To Reproduce

```sh
curl http://localhost:8428/api/v1/import/prometheus -d 'series1 123
series2 456'

curl http://localhost:8428/api/v1/query -d 'query={__name__=~"series.*"}' | jq  # validate seeing 2 series

curl http://localhost:8428/api/v1/query -d 'query=tfirst_over_time({__name__=~"series.*"})'  # the error

curl http://localhost:8428/api/v1/query -d 'query=tfirst_over_time({__name__=~"series1"})'   # succeeds
```

### Version

victoria-metrics-20231212-224437-tags-v1.96.0-0-g304fe0565

### Logs

The error above,

```
error in "/api/v1/query?query=tfirst_over_time%28%7B__name__%3D~%22series.%2A%22%7D%29": error when executing
query="tfirst_over_time({__name__=~\"series.*\"})" for (time=1703885975314, step=300000):
duplicate output timeseries: {}
```

### Used command-line flags

-retentionPeriod=100y -search.maxPointsPerTimeseries=10000000

### Additional information

If I suffix the query with `keep_metric_names`, it succeeds, and shows the time series were different rather than duplicate.

**Comment by jiekun** [comment]
Close due to inactivity.
