### ISSUE TITLE
Recently written data isn't immediately visible

### ISSUE THREAD

**Issue by dandv** [VictoriaMetrics/VictoriaMetrics#5555]
### Describe the bug

In a completely empty TSDB, I insert one data point, then run `count_over_time`. It takes more than 30 seconds for the result to be 1. This was surprising until I read about the `-search.latencyOffset=1s` flag, but the name of that flag, `search.`, didn't make me think it would affect *counts*.

### To Reproduce

```sh
rm -rf vicmetest && ./victoria-metrics-prod-1.96.0 -storageDataPath ./vicmetest

# In new shell
curl http://localhost:8428/api/v1/import/prometheus -d 'series1 10'
curl http://localhost:8428/api/v1/query -d 'query=count_over_time(series1)'
# run the above command repeatedly until you get 1 `seriesFetched`
```

### Version

victoria-metrics-20231212-224437-tags-v1.96.0-0-g304fe0565

### Logs

No warnings or errors.

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/33569/fe47bafe-16d7-4e90-a91c-47fe1491bded)

### Additional information

This behavior should be documented, but I don't see any mention of `search.latencyOffset` at https://docs.victoriametrics.com/MetricsQL.html.

**Comment by hagen1778** [comment]
Hello @dandv !

> but the name of that flag, search., didn't make me think it would affect counts.

`search.` prefix is relevant to all read API exposed by vmselects/single-node.

> This behavior should be documented, but I don't see any mention of search.latencyOffset at https://docs.victoriametrics.com/MetricsQL.html.

This behavior isn't related to MetricsQL as a query language. You can read more about it [here](https://docs.victoriametrics.com/keyConcepts.html#query-latency). I also added this question to [Troubleshooting docs](https://docs.victoriametrics.com/Troubleshooting.html#unexpected-query-results) in this [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/8040bdc1d61d020b58592d17da523b0c4b16b87d).

**Comment by valyala** [comment]
There is also `/internal/force_flush` http handler, which can be used during debugging and/or testing. I documented it in the commit b7ffee2644991b75d5d0572c5ef51dd3029b818f .

Closing the question as answered.

**Comment by dandv** [comment]
Thanks. I used /internal_force_flush and most of the time it worked, though in about 5% of the cases, running a `count_over_time` for several series at a time (with `{__name__=~"..."}` right after the flush revealed that not all points had been flushed.
