### ISSUE TITLE
When vmselect calls vmstorage, vmstorage has many "i/o timeout "errors

### ISSUE THREAD

**Issue by whc9527** [VictoriaMetrics/VictoriaMetrics#5559]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Deploy with helm mode, The deployment command is helm upgrade --install algo vm/victoria-metrics-cluster -n hawkeye-algo --version 0.11.8 -f victoriaMetrics/aws_vg_algo.yaml
vmSelect options in  aws_vg_algo.yaml:
```
extraArgs:
envflag.enable: "true"
envflag.prefix: VM_
loggerFormat: json
replicationFactor: 3
dedup.minScrapeInterval: 240s
search.maxUniqueTimeseries: "300000000"
search.maxSamplesPerSeries: "300000000"
search.maxSamplesPerQuery: "300000000"
search.maxPointsPerTimeseries: "300000000"
search.maxPointsSubqueryPerTimeseries: "300000000"
search.maxSeriesPerAggrFunc: "300000000"
search.maxSeries: "300000000"
search.maxGraphiteSeries: "300000000"
search.maxQueueDuration: 10m
search.maxQueryDuration: 10m
search.maxConcurrentRequests: 2000
search.maxLookback: 10m
storageNode: "base-victoria-metrics-cluster-vmstorage-0.base-victoria-metrics-cluster-vmstorage.hawkeye-base.svc.cluster.local:8401,base-victoria-metrics-cluster-vmstorage-1.base-victoria-metrics-cluster-vmstorage.hawkeye-base.svc.cluster.local:8401,base-victoria-metrics-cluster-vmstorage-2.base-victoria-metrics-cluster-vmstorage.hawkeye-base.svc.cluster.local:8401"
http.connTimeout: 10m
http.idleConnTimeout: 10m
search.logSlowQueryDuration: 30s
```

vmStorage options in  aws_vg_algo.yaml:
```
extraArgs:
envflag.enable: "true"
envflag.prefix: VM_
loggerFormat: json
# https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability
dedup.minScrapeInterval: 4m
search.maxConcurrentRequests: 2000
http.connTimeout: 10m
http.idleConnTimeout: 10m
```

vmSelect Grafana Panel:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/f7aad769-3534-47a2-a9cf-57ea67180627)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/d1ef53c5-1642-41cb-b752-d9b14e6deef1)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/ec3cdbcd-2c8d-4a3a-9b3a-b58bc93f7962)
vmStorage Grafana Panel:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/e717917c-78ab-4612-9011-64f02861a0f4)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/a8de9ff7-29df-42f7-963d-0ab0e5f4a5e2)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/1bdb5688-35dc-40f3-aa3c-f6f334fe94d2)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/f141f162-d393-4845-a51f-b37a07f08171)

vmSelect pod stdout logs:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/bc0d83f3-0af1-478e-bf6f-e8c7fe1e1e98)

vmStorage pod stdout logs:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/ef9ad91f-0780-4520-b3f8-3bdb0db82bfd)

vmstorage keeps reporting the same error like 
`{" ts" : "the 2024-01-01 T05: for the 319 z", "level" : "error", the "caller" : "VictoriaMetrics/lib/vmselectapi/server go: 203", "MSG" : "always perform vmselect handshake with client \"172.31.178.121:48570\": cannot read hello: cannot read message with size 11: read tcp4 172.31.182.196:8401-&gt; 172.31.178.121:48570: i/o timeout; read only 0 bytes "} `
The server where vmstorage is located has a very low cpu and disk io load. i don't quite understand why the above 'i/o timeout' error occurs

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/b2b1a1c2-84e3-4705-b799-51d0787cd5e1)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17898805/5ba3a3d7-c4f0-4393-acfc-b6167cf80ca7)

**Comment by whc9527** [comment]
Can anyone help me with this? Thank you very much

**Comment by whc9527** [comment]
我刚又看了一下，i/o timeout指的应该是网络io，然后我手动看了下vmselect所在的node节点的情况，看到node的cpu总是突然增加到100%，但是这种情况在aws和prometheus侧都没有看到这种突刺，之后我升级了vmselect的node节点，从8C16G，改为了16C128G的机型，目前已经没有这个报错信息了

**Comment by f41gh7** [comment]
Hello, it looks like network issue. Something between vmstorage and vmselect intercepts and terminates connections. I'd suspect  kubernetes service mech or CNI plugins.

**Comment by whc9527** [comment]
@f41gh7 感谢你的解答，我升级后vmselect的机器规格后就好了，应该是vmselect的cpu导致的网络i/o阻塞。
