### ISSUE TITLE
How to build victoriametrics/vmselect from sources

### ISSUE THREAD

**Issue by aruicoding** [VictoriaMetrics/VictoriaMetrics#5561]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

Oh, my God.I will developing additional features specific to my needs.It seems like only build "app/victoria-metrics" from “deployment/",please help for me.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Hello, first of all, you have to checkout to the cluster branch. 
- Next step make sure, that you have build tools installed - `cmake`, `git` are necessary. 
- To be able compile vmselect for local run, you need `go` compiler. Execute `make vmselect` command.
- if only docker image is needed, you have to install docker.  Execute `make package-vmselect`. 

 Check docs for details https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#how-to-build-from-sources

**Comment by aruicoding** [comment]
> * step
Oh Good! I see,thank you very much.
