### ISSUE TITLE
Query about remoteWrite.oauth2.clientSecretFile parameter

### ISSUE THREAD

**Issue by AshrithaSB** [VictoriaMetrics/VictoriaMetrics#5562]
### Is your question request related to a specific component?

All the components

### Describe the question in detail

It is mentioned in the documentation that **remoteWrite.bearerTokenFile** and **remoteWrite.basicAuth.passwordFile** are re-read every second. Similarly, is the **remoteWrite.oauth2.clientSecretFile** parameter also re-read on specific intervals?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
Yes, that's correct.  Content of the `remoteWrite.oauth2.clientSecretFile` cached for 1 second.

**Comment by AshrithaSB** [comment]
Thank you
