### ISSUE TITLE
vmagent exceeds -promscrape.maxScrapeSize=16777216

### ISSUE THREAD

**Issue by rotarur** [VictoriaMetrics/VictoriaMetrics#5567]
### Describe the bug

I have some backends which export lots of metrics, around 200MB in total. The vmagent can't handle so big response size throwing this error:
```
{"ts":"2024-01-04T10:12:23.638Z","level":"warn","caller":"VictoriaMetrics/lib/promscrape/scrapework.go:387","msg":"cannot scrape target \"http://10.4.3.22:8040/metrics\" ({app=\"index-no
de\",controller_revision_hash=\"index-node-community-864b7bdf5d\",instance=\"10.4.3.22:8040\",job=\"kubernetes-pods\",kubernetes_namespace=\"default\",kubernetes_pod_name=\"index-node-co
mmunity-7\",network=\"all\",node_set=\"common\",quarantine=\"disabled\",statefulset_kubernetes_io_pod_name=\"index-node-community-7\"}) 1 out of 1 times during -promscrape.suppressScrape
ErrorsDelay=0s; the last error: cannot read stream body in 0 seconds: the response from \"http://10.4.3.22:8040/metrics\" exceeds -promscrape.maxScrapeSize=16777216; either reduce the re
sponse size for the target or increase -promscrape.maxScrapeSize"}
```

This is what my backend exports in terms of metrics:

```
root@myhost:/# curl -I localhost:8040/metrics
HTTP/1.1 200 OK
content-type: text/plain; version=0.0.4
access-control-allow-origin: *
content-length: 286975060
date: Thu, 04 Jan 2024 10:18:45 GMT
```

This one exports 286.9751 MB of metrics and I can't reduce the number of those metrics due to the nature of the backend.

I'm using these scrape configurations which don't seem to help anything:

```
            - job_name: "kubernetes-pods"
              scrape_interval: 120s
              scrape_timeout: 120s
              disable_compression: true
              stream_parse: true
```

If I increase the `promscrape.maxScrapeSize` it starts to consume more resources, which is understandable, and in this case the prometheus exporters work better with less memory footprint. It's not acceptable for me to accommodate so large  `promscrape.maxScrapeSize` in vmagent if it starts to consume much more memory and CPU than my existing prometheus setup which I'm trying to migrate to VM.

Is there a way to make the stream read body higher because from my log above it's complaining about `cannot read stream body in 0 seconds` as well

### To Reproduce

create a backend which exports 40MB of metrics

### Version

victoriametrics/vmagent:v1.95.1

**Comment by rotarur** [comment]
Adding more to this bug. In order to scrape 259MB or metrics from within vmagent it takes 39s:

```
real    0m 39.36s
user    0m 0.01s
sys     0m 3.49s
```

```/ # curl -I http://10.4.14.23:8040/metrics
HTTP/1.1 200 OK
content-type: text/plain; version=0.0.4
access-control-allow-origin: *
content-length: 259733347
date: Thu, 04 Jan 2024 10:36:37 GMT
```

but vmagent can't handle it even with larger timeout

**Comment by rotarur** [comment]
by increasing the `promscrape.maxScrapeSize: "450000000"` then it's not throwing the error anymore. I still have to disable the scrape compression to decrease the resource footprint, otherwise it's constantly killed with OOM in a dedicated node with 16GB of RAM. The network usage will increase within the cluster but it's OK if it stays there.

nonetheless I think the stream parser is under-performing or it's not working at all if I still have to increase the maxScrapeSize to accommodate the metrics size

**Comment by Haleygo** [comment]
Hello!
The error log is correct even with `stream_parse: true`, since `stream_parse` is only used to save memory by doing relabel and pushing for each chunk of the response in order. So target response will always be limited by `promscrape.maxScrapeSize`.

>but vmagent can't handle it even with larger timeout

Did you get timeout error for this? Have you tried to increase `scrape_timeout` for this job? (Please be aware `scrape_timeout` can't be bigger than job `scrape_interval`)

>otherwise it's constantly killed with OOM in a dedicated node with 16GB of RAM.

Weird, I tested one job with 400M response and the memory usage is about 1.5G, could you share the [memory profile](https://new.docs.victoriametrics.com/vmagent/#profiling)?

**Comment by rotarur** [comment]
from my tests I got these memory / CPU usages:

promscrape.maxScrapeSize: "950000000" (950MB) 2093m        3449Mi
promscrape.maxScrapeSize: "750000000"  (750MB) 1835m        2728Mi
promscrape.maxScrapeSize: "650000000" (650MB) 2515m        2682Mi
promscrape.maxScrapeSize: "450000000" (450MB) 2191m        1277Mi 
promscrape.maxScrapeSize: "450000000" (350MB) doesn't work

Those are pretty stable and low if I disable the compression. The CPU decreases but the memory increases a little bit, but it's acceptable.

I've increased the timeouts as I shared in this issue

```
scrape_interval: 120s
scrape_timeout: 120s
```

only these configurations work for me.

It makes sense now as you explained it, I thought that stream parse will solve the issue and I won't needed to increase the maxScrapeSize

**Comment by Haleygo** [comment]
> from my tests I got these memory / CPU usages:
> 
> promscrape.maxScrapeSize: "950000000" (950MB) 2093m 3449Mi promscrape.maxScrapeSize: "750000000" (750MB) 1835m 2728Mi promscrape.maxScrapeSize: "650000000" (650MB) 2515m 2682Mi promscrape.maxScrapeSize: "450000000" (450MB) 2191m 1277Mi promscrape.maxScrapeSize: "450000000" (350MB) doesn't work
> 
> Those are pretty stable and low if I disable the compression. The CPU decreases but the memory increases a little bit, but it's acceptable.
> 
> I've increased the timeouts as I shared in this issue
> 
> ```
> scrape_interval: 120s
> scrape_timeout: 120s
> ```
> 
> only these configurations work for me.
> 
> It makes sense now as you explained it, I thought that stream parse will solve the issue and I won't needed to increase the maxScrapeSize

The numbers looks good to me.
I'm not sure about this point though, since I don't see `disable_compression: true` has much effects on memory usage in my test, can you share the memory profile if that's still a problem for you?
>I still have to disable the scrape compression to decrease the resource footprint, otherwise it's constantly killed with OOM in a dedicated node with 16GB of RAM.

**Comment by valyala** [comment]
@rotarur , the commit bc7cf4950b5ff1072a33fe58c6bae1184d01068b may help reducing `vmagent` memory usage for scrape targets, which return huge responses like in your case. The memory usage reduction should be visible for both regular scraping mode and for [stream parsing mode](https://docs.victoriametrics.com/vmagent/#stream-parsing-mode). Additionally, this commit should reduce the probability of scrape timeout errors when scraping huge responses.

Could you try building `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent/#how-to-build-from-sources) and verify whether the built `vmagent` uses lower amounts of memory on your workload?

**Comment by valyala** [comment]
As for the respect of `-promscrape.maxScrapeSize` command-line flag in stream parsing mode, this is made on purpose - see [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1331) for details.

@Haleygo , what do you think about adding `max_scrape_size` option at [scrape_configs](https://docs.victoriametrics.com/sd_configs/#scrape_configs) level, which could be used for more fine-grained control of scrape response sizes.

**Comment by valyala** [comment]
@rotarur , could you try running [vmagent v1.97.0](https://docs.victoriametrics.com/CHANGELOG.html) on your workload and see whether it uses less memory than the previous version of vmagent?

**Comment by jiekun** [comment]
Close due to inactivity.
