### ISSUE TITLE
Trying to do metric aggregation on a vmagent

### ISSUE THREAD

**Issue by DaRealCapz** [VictoriaMetrics/VictoriaMetrics#5580]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

![Configuracao 1](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/71236784/22cc064b-8ee3-400b-96c4-f368701b3f55)

I was trying to implement the system above and in order to make it more efficient I need to setup some sort of metric aggregation in order to reduce the resource usage of the system, for instance the metrics reaching the VM storage are the average values between the 3 Node Exporters below.
What type of file do I need to create and what is the syntax I should use to achieve the previous mentioned objective?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @DaRealCapz.
You can try [Streaming aggregation](https://docs.victoriametrics.com/stream-aggregation.html) for it.

**Comment by DaRealCapz** [comment]
I have created a yaml file but I am still having issues coming up with the configuration to aggregate the metrics from the 3 node exporters in which of writting the same metric 3 times in the VM, one per node exporter, I want to store the average value from each metric from each node exporter. 
Is that something that can be done?

**Comment by hagen1778** [comment]
> I want to store the average value from each metric from each node exporter

Try the following stream aggregation config:
```
- match:  '{job="nodeexporter"}'     # match metrics that belong to nodeexporter
  interval: "5m"                          # aggregate on 5m interval, so 1 datapoint per series once in 5m
  outputs: ["avg"]                      # aggregate to avg value on 5m interval
```
This aggreation rule will calculate the `avg` between samples of each time series on 5m interval. Effectively, it will reduce the number of samples ingested into VictoriaMetrics. But it will not reduce cardinality. To reduce cardinality you'd need to add (`by`) or exclude (`without`) labels from aggregation. See more here https://docs.victoriametrics.com/stream-aggregation/#reducing-the-number-of-stored-series
