### ISSUE TITLE
stream aggregation: `streamAggr.dedupInterval` significantly increases the memory consumption of vmagent

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5586]
### Is your feature request related to a problem? Please describe

When `streamAggr.dedupInterval` is enabled, vmagent starts to track time series in memory for proper deduplication.
This could significantly increase memory consumption and is hard to predict/control from user perspective.

### Describe the solution you'd like

Would be great to revise the deduplication logic in case if it can be optimized for lower memory usage.

**Comment by nemobis** [comment]
Indeed, stream aggregation is a nice feature but I had to give up on using it in v1.99 because of the memory usage. With 2 vmagent pods handling an ingestion of about 100k samples per second, memory usage went from 200 MB to 3 GB (initially they all died of OOM before I realised I had to significantly increase the limits).

I expected memory usage to decrease when I switched dedupInterval from 30 seconds to 15 seconds, but it didn't.

**Comment by nemobis** [comment]
![Screenshot_20240316_202921](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/901528/a98e7ae4-d599-46ef-aa54-7230667df78e)

**Comment by hagen1778** [comment]
> I expected memory usage to decrease when I switched dedupInterval from 30 seconds to 15 seconds, but it didn't.

Memory usage depends on number of unique series vmagent deduplicates, not on the interval.

> With 2 vmagent pods handling an ingestion of about 100k samples per second, memory usage went from 200 MB to 3 GB

There is a cost for vmagent to track unqiue time series and deduplicate the values. This cost will be paid anyway, either at vmagent side or at vmstorage/vmselect side.

**Comment by hagen1778** [comment]
> FEATURE: [stream aggregation](https://docs.victoriametrics.com/stream-aggregation/): reduce memory usage by up to 5x when aggregating over big number of unique [time series](https://docs.victoriametrics.com/keyconcepts/#time-series). The memory usage reduction is most visible when [stream deduplication](https://docs.victoriametrics.com/stream-aggregation/#deduplication) is enabled.

from version [v1.100](https://docs.victoriametrics.com/changelog/#v11000)

Closing as done.
