### ISSUE TITLE
vmctl influx is only importing the last 30 days of data?

### ISSUE THREAD

**Issue by deviantintegral** [VictoriaMetrics/VictoriaMetrics#5596]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I'm trialing VictoriaMetrics and testing out the influx migration. While I can run the migration, it's only importing the last 30 days of my data. There should be 13 months of data available.

Here's a simple query, with the cache disabled:

<img width="1211" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/255023/0db45502-db1a-476e-b5fc-f3c72213b89b">

There's no errors while importing (though it's odd that the output at the end has missing characters). As well, while total bytes says `7.6 GB`, the whole container is only using `1.10 GB` of uncompressed space:

```
$ zfs get logicalused,referenced,compressratio rpool/vmdata/subvol-106-disk-0
NAME                            PROPERTY       VALUE  SOURCE
rpool/vmdata/subvol-106-disk-0  logicalused    1.52G  -
rpool/vmdata/subvol-106-disk-0  referenced     970M   -
rpool/vmdata/subvol-106-disk-0  compressratio  1.59x  -
```

Here's the import command I ran:

```
$ docker run --network docker_vm_net \
  --rm -it \
  victoriametrics/vmctl:v1.96.0 \
  influx \
  --influx-addr http://influxdb.lan:8086 \
  --influx-user USER \
  --influx-password PASSWORD \
  --influx-database home_assistant \
  --vm-addr http://victoriametrics:8428 \
  --vm-extra-label db=home_assistant \
  --vm-disable-progress-bar \
  --vm-concurrency 4
InfluxDB import mode
2024/01/10 02:33:57 Exploring scheme for database "home_assistant"
2024/01/10 02:33:57 fetching fields: command: "show field keys"; database: "home_assistant"; retention: "autogen"
2024/01/10 02:33:59 found 5812 fields; skipped 6624 non-numeric fields
2024/01/10 02:33:59 fetching series: command: "show series"; database: "home_assistant"; retention: "autogen"
2024/01/10 02:33:59 found 4081 series
Found 29737 timeseries to import. Continue? [Y/n] Y

2024/01/10 03:10:21 Import finished!
2024/01/10 03:10:21 VictoriaMetrics importer stats:
  le duration: 2h16m50.243477032s;
  me spent while importing: 36m21.111806277s;
  tal samples: 374340295;
  mples/s: 171628.20;
  tal bytes: 7.6 GB;
  tes/s: 3.5 MB;
  port requests: 1858;
import requests retries: 0;
2024/01/10 03:10:21 Total time: 36m23.66551076s
```

Any suggestions? `skipped 6624 non-numeric fields` seems like it may be a hint, but I would have expected the series to be entirely missing, not just truncated in the recent past.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @deviantintegral.
By default VM has retention = one month (more details: https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#retention / ), do you set `-retentionPeriod` flag on VM?

**Comment by deviantintegral** [comment]
That was it! Thank you.

One bit of confusion was that the docs show single dashes (`-retentionPeriod`) yet that errored out, and I had to do double-dash-with-equals style (`--retentionPeriod=13`).

It would also be a nice improvement if vmctl imports could detect if you were importing data beyond the configured retention period, and show a warning.
