### ISSUE TITLE
Extended PromQL library?

### ISSUE THREAD

**Issue by jacksontj** [VictoriaMetrics/VictoriaMetrics#56]
Hello, the author of [Promxy](https://github.com/jacksontj/promxy) here. First off, this definitely looks like an interesting project and I'm excited to see where it goes. Also, I do appreciate the link over to promxy -- I'm glad I can be of help.

While reading through the docs for VictoriaMetrics I see mention of this Extended PromQL functionality. I did a quick search through the code and didn't see a replacement promql engine (TBH I spent about 5m-- so it might be there and I missed it). If there is a library for usage I could look into optionally adding support for this promql Extenstion into Promxy.

**Comment by valyala** [comment]
I'm glad you are eager to add extended PromQL support to Promxy!

The extended PromQL library code is located at [app/vmselect/promql](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/fb140eda33ccbe8fdea366c90cbcd0fef145b121/app/vmselect/promql). It has a few dependencies on other bits of VictoriaMetrics, so it cannot be used as is in external projects. But it should be quite easy to fork the library and remove these dependencies there.

While you are here, could you help with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/52 ?

**Comment by jacksontj** [comment]
I'll take a look at the promql thing likely this weekend. I'm not sure how
tightly coupled it is, but assuming I can pull it out into something
standalone would you be interested in that?

**Comment by valyala** [comment]
> I'm not sure how
tightly coupled it is, but assuming I can pull it out into something
standalone would you be interested in that?

Yes! That would be great! The lib is almost self-contained with a few exceptions like integration with VictoriaMetrics storage. This part may be abstracted out in the standalone version. Other dependencies on VictioraMetrics code may be just removed from standalone version.

**Comment by jeromegn** [comment]
We've started using VictoriaMetrics and need a HA setup. We've chosen promxy, but we lost the extended query language support which I'd love to be able to use.

I haven't looked at how promxy parses queries, but I would assume since VM's parser is prometheus-compatible, it could use it (if it's easily extractable, which seems to be the case).

Anyway, this comment is more like a :+1: than anything. Hope to see this soon!

**Comment by valyala** [comment]
@jacksontj , MetricsQL parser (new name for Extended PromQL) has been extracted into a standalone library with the minimum number of external dependencies - `github.com/VictoriaMetrics/VictoriaMetrics/lib/metricsql`. See [source code](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/6f67e0b56bfa546309df88de156a4f82d21b574e/lib/metricsql) and [documentation](https://godoc.org/github.com/VictoriaMetrics/VictoriaMetrics/lib/metricsql) for `lib/metricsql`.

Closing this feature request.
