### ISSUE TITLE
Questions about victoriametrics indexdb

### ISSUE THREAD

**Issue by luzejia** [VictoriaMetrics/VictoriaMetrics#5600]
### Is your question request related to a specific component?

vmstorage-1.39.9

### Describe the question in detail

I have some performance questions about indexdb in vcitoriametrics：

* If metrics fail to hit the cache in the memory during the insertion and query process, do you need to check the indexDB data on the disk? If the indexDB is large and fail to hit the cache, disk IO is required. Will the performance be poor?

* Assume that by default, all indexDB will be cached in memory and flushed back to disk regularly. If so, it will prevent disk read IO, but there is a risk of memory OOM. I don’t know how this vm is processed.

* If the cache fails to be hit and the data needs to be read from the disk, will the data be added to the cache after reading?

* I don’t quite understand what "maybeCreateIndexes" does.

 lib/storage/index_db.go
```
// maybeCreateIndexes probabilistically creates global and per-day indexes for the given (tsid, metricNameRaw, date) at db.
//
// The probability increases from 0 to 100% during the first hour since db rotation.
//
// It returns true if new index entry was created, and false if it was skipped.
func (is *indexSearch) maybeCreateIndexes(tsid *TSID, metricNameRaw []byte, date uint64) (bool, error) {
	pMin := float64(fasttime.UnixTimestamp()-is.db.rotationTimestamp) / 3600
	if pMin < 1 {
		p := float64(uint32(fastHashUint64(tsid.MetricID))) / (1 << 32)
		if p > pMin {
			// Fast path: there is no need creating indexes for metricNameRaw yet.
			return false, nil
		}
	}
	// Slow path: create indexes for (tsid, metricNameRaw) at db.
	mn := GetMetricName()
	if err := mn.UnmarshalRaw(metricNameRaw); err != nil {
		return false, fmt.Errorf("cannot unmarshal metricNameRaw %q: %w", metricNameRaw, err)
	}
	mn.sortTags()
	is.createGlobalIndexes(tsid, mn)
	is.createPerDayIndexes(date, tsid.MetricID, mn)
	PutMetricName(mn)
	atomic.AddUint64(&is.db.timeseriesRepopulated, 1)
	return true, nil
}
```

I hope to get a detailed answer. It would be best if there is a detailed analysis.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by xiaozongyang** [comment]
> If metrics fail to hit the cache in the memory during the insertion and query process, do you need to check the indexDB data on the disk? If the indexDB is large and fail to hit the cache, disk IO is required. Will the performance be poor?

1. In the inserting flow, VM will generate a TSID by metric name and all labels. At first it wil bel checked in memory cache, if miss checked in on-disk indexDb, if missed create a new entry in indexDb. The main process is in `Storage.add` [source code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/storage.go#L1696C22-L1696C22).
2. The source code about main process of query flow is at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/index_db.go#L1680.
3. Data will be divided into fixed-sized blocks which is represented by an entry in IndexDb, each entry will point to 8 * 1024 samples, so index db size will be `raw_data_size / 8196` which consumes little memory to cache them. 
4. In theory when your memory is insufficient and do a full scan query, the indexDb should be read from disk, the latency will be increasing. But in real-word performance is usaually enough, if you want get exact latency information, you can build a query can run it!

**Comment by luzejia** [comment]
> > 如果插入和查询过程中metrics未能命中内存中的缓存，是否需要检查磁盘上的indexDB数据？如果indexDB较大，无法命中缓存，则需要进行磁盘IO。性能会不会很差？
> 
> 1. 在插入流程中，VM将通过metric名称和所有标签生成TSID。首先，它将在内存缓存中进行检查，如果未在磁盘上的indexDb中进行检查，如果未命中，则在indexDb中创建一个新条目。主要流程在`Storage.add` [源代码](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/storage.go#L1696C22-L1696C22)中。
> 2. 查询流程主要流程的源代码位于https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/storage/index_db.go#L1680。
> 3. 数据将被分成固定大小的块，由 IndexDb 中的一个条目表示，每个条目将指向 8 * 1024 个样本，因此索引数据库大小将`raw_data_size / 8196`消耗很少的内存来缓存它们。
> 4. 理论上当你的内存不足并且进行全扫描查询时，indexDb应该从磁盘读取，延迟会增加。但在实际情况下，性能通常就足够了，如果您想获得准确的延迟信息，您可以构建一个可以运行它的查询！

Thanks!
