### ISSUE TITLE
feat: calculate scrape size for each target 

### ISSUE THREAD

**Issue by IvanZenger** [VictoriaMetrics/VictoriaMetrics#5612]
### Is your feature request related to a problem? Please describe

We have the need to determine the scrape size for each Endpoint. Currently, we are only able to calculate the response size for each vmagent. This enhancement would assist us in making informed decisions regarding our infrastructure.

### Describe the solution you'd like

Enhance the target status by appending a metric such as scrapeSize. https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/targetstatus.qtpl

### Describe alternatives you've considered

- vm_promscrape_scrape_response_size_bytes_bucket and flag{is_set="true", name="promscrape.maxScrapeSize"} (vmagent)

**Comment by AndrewChubatiuk** [comment]
hey @IvanZenger
ability to set `max_scrape_size` for each job and see targets scrape size on both VMAgent ui and in metrics was [merged](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6434) already and will be available since upcoming release.

**Comment by IvanZenger** [comment]
Great! I'm excited to try it. Thank you, everyone! 😊

**Comment by valyala** [comment]
See the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6429
