### ISSUE TITLE
Can retention period be lower than 1d?

### ISSUE THREAD

**Issue by FFparad0x** [VictoriaMetrics/VictoriaMetrics#5615]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

why the minimal retention period is 1 day, can it be set to 1 hour?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> why the minimal retention period is 1 day, can it be set to 1 hour?

Nope, it can't. One day is the minimum retention due to internal implementation details like per-day indexes and caches. You can't go below that and there are not many use cases when this is needed.

**Comment by whh32** [comment]
> > why the minimal retention period is 1 day, can it be set to 1 hour?
> 
> Nope, it can't. One day is the minimum retention due to internal implementation details like per-day indexes and caches. You can't go below that and there are not many use cases when this is needed.

For a short reserved log, such as one week, it can save a lot of disks on the hour. At present, the minimum particle size is one day. If the log with a large traffic, the largest part may reach hundreds of GB
