### ISSUE TITLE
Is it possible to restore data deleted due to retention period?

### ISSUE THREAD

**Issue by nerdbaggy** [VictoriaMetrics/VictoriaMetrics#5617]
### Describe the question in detail

Hello,
I need some data that was recently deleted by a retention period. Because it isn't the 1st of the month it sounds like the data is still there on the disk. Is there any way I can export this data or restore it?

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Is there any way I can export this data or restore it?

Unfortunately, no. The data deletion is an unrecoverable operation unless you made a backup or snapshot before this.

**Comment by nerdbaggy** [comment]
So I was actually able to get the data restored.

I was querying for data from Dec 10-15 2023 on January 15 2024. When querying it via vmui there was no data, but I was able to export the data and reimport it and then the data was back.

Based on [this](https://docs.victoriametrics.com/#retention) it seems to be expected because the data wouldn't actually be deleted until Feb 1st
