### ISSUE TITLE
vmalert how to escape comma in -notifier.basicAuth.password?

### ISSUE THREAD

**Issue by dchiaramello** [VictoriaMetrics/VictoriaMetrics#5626]
### Is your question request related to a specific component?

vmalert, but not only

### Describe the question in detail

vmalert has to target an existing AlertManager server using Basic authentication, but the password is (for example) "MyPass,toto"

So, I'm using -notifier.basicAuth.password='MyPass,toto' parameter - but unfortunately, that parameter is described as an array, with "Supports an array of values separated by comma or specified via multiple flags".

As a consequence, vmalert considers that parameter as 2 different passwords separated by a comma, and uses "MyPass" alone as BasicAuth password, instead of "MyPass,toto"...

How can I solve that problem?

Thanks for your attention!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dchiaramello** [comment]
Hello.

By checking `lib/flagutil/array.go` project source code, I found the solution:
`-notifier.basicAuth.password='"MyPass,toto"'`

That's this comment which helped me:

> // Each flag value may contain commas inside single quotes, double quotes, [], () or {} braces.
> // For example, -foo=[a,b,c] defines a single command-line flag with `[a,b,c]` value.
> //
> // Flag values may be quoted. For instance, the following arg creates an array of ("a", "b,c") items:
> //
> //	-foo='a,"b,c"'

**Comment by Haleygo** [comment]
Hello!
`./vmalert   -notifier.basicAuth.username="\"MyPass,toto\""`  should work here)
```
➜  vmalert git:(fix-watcher-start-order) ✗ ./vmalert   -notifier.basicAuth.username="\"MyPass,toto\""                                                                                                                            
2024-01-17T14:33:44.062Z        info    lib/logger/flag.go:12   build version: 
2024-01-17T14:33:44.063Z        info    lib/logger/flag.go:13   command-line flags
2024-01-17T14:33:44.063Z        info    lib/logger/flag.go:20     -notifier.basicAuth.username="\"MyPass,toto\""
```

**Comment by hagen1778** [comment]
@Haleygo wdyt about adding this hint to the flag type description so it would be easier for users to find?
