### ISSUE TITLE
vmtool-alert unittest expects incorrect values when applying an aggregator with _over_time on top of another aggregator

### ISSUE THREAD

**Issue by cooltea713705** [VictoriaMetrics/VictoriaMetrics#5642]
### Describe the bug

`vmtool-alert unittest` expects incorrect values for a record when applying an aggregator `_over_time` on top of another aggregator.

In a simple example where the order in which the aggregations are applied should not be relevant, `vmtool-alert unittest` will have correct expectations for `agg1 by (label) (agg2_over_time(metric))` but those expectations will seemingly be incorrect for `agg2_over_time(agg1 by label) (metric))`.

### To Reproduce

Example provided [here](https://gist.github.com/cooltea713705/55569ad75e9d0be19ad740f8fa34a3cb)

The expectations for the 2 records `test:metric:avg_by_site_avg_over_time` and `test:metric:avg_over_time_avg_by_site` would be the same but, if set as such, the test fails for the second record with expected values that would be 0, 10 and 20:

```
❯ vmalert-tool unittest --files="rules_test.yaml"

Unit Testing:  rules_test.yaml
evaluation_interval set to 1m by default
  FAILED

failed to run unit test for file "rules_test.yaml":
[
    expr: "test:metric:avg_over_time_avg_by_site", time: 1m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1E+00
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 0E+00
    expr: "test:metric:avg_over_time_avg_by_site", time: 2m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 3E+00
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 0E+00
    expr: "test:metric:avg_over_time_avg_by_site", time: 3m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 5E+00
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 0E+00
    expr: "test:metric:avg_over_time_avg_by_site", time: 4m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 7E+00
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 0E+00
    expr: "test:metric:avg_over_time_avg_by_site", time: 5m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 9E+00
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1E+01
    expr: "test:metric:avg_over_time_avg_by_site", time: 6m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1.1E+01
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1E+01
    expr: "test:metric:avg_over_time_avg_by_site", time: 7m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1.3E+01
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1E+01
    expr: "test:metric:avg_over_time_avg_by_site", time: 8m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1.5E+01
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1E+01
    expr: "test:metric:avg_over_time_avg_by_site", time: 9m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1.7E+01
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1E+01
    expr: "test:metric:avg_over_time_avg_by_site", time: 10m0s,
        exp: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 1.9E+01
        got: {__name__="test:metric:avg_over_time_avg_by_site", site="site"} 2E+01]2024/01/18 15:11:18 unittest failed
```

### Version

```
❯ vmalert-tool --version
vmalert-tool version vmalert-tool-20231221-162934-heads-master-0-g8c1dcf474
2024/01/18 15:16:31 Total time: 92.541µs
```

### Additional information

`vmtool-alert` built from cloning https://github.com/VictoriaMetrics/VictoriaMetrics and `make vmalert-tool` on
`23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64`

**Comment by Haleygo** [comment]
Hello!
>In a simple example where the order in which the aggregations are applied should not be relevant, vmtool-alert unittest will have correct expectations for agg1 by (label) (agg2_over_time(metric)) but those expectations will seemingly be incorrect for agg2_over_time(agg1 by label) (metric))

Acctually not true, if you apply agg func like `avg` first, the inner result will be a scalar, so the outside `agg2_over_time` won't get the right inputs and the output is likely not what you expected.
Like your example:
```
 avg_over_time(
            avg by (site) (
                metric
            )
          [2m])
```
prometheus treats it as a wrong expr and gives error "parse error: ranges only allowed for vector selectors", but [MetricsQL](https://new.docs.victoriametrics.com/metricsql/) implements some functions differently compared to PromQL to improves user experience, one of them is
>MetricsQL treats scalar type the same as instant vector without labels, since subtle differences between these types usually confuse users.

But it still doesn't give the right inputs to the outside `avg_over_time`, since the inner result is still a scalar.
To make it right, you can use [subqueries](https://new.docs.victoriametrics.com/metricsql/#subqueries), it allows you to do a range query within a query. Since your input data is with 1m interval, the expr can be
```
 avg_over_time(
            avg by (site) (
                metric
            )
          [2m:1m])
```

**Comment by cooltea713705** [comment]
Thanks for looking into it!

> prometheus treats it as a wrong expr and gives error "parse error: ranges only allowed for vector selectors"

Thanks for pointing out this difference between Prometheus and MetricsQL: I was not aware of it.

> if you apply `agg` func like avg first, the inner result will be a scalar

Sorry but I don't understand this statement: according to the [documentation](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators), `avg` should be an aggregation operator converting "the elements of a single instant vector, resulting in a new vector of fewer elements with aggregated values": I expect `avg` to return a new time series by aggregating data from (possibly) multiple time series. I have updated the [gist example that was provided](https://gist.github.com/cooltea713705/55569ad75e9d0be19ad740f8fa34a3cb) to demonstrate this (`test:metric:avg_by_site` + associated test). Could you please clarify what you meant and help determine why this is not a bug?

**Comment by Haleygo** [comment]
Sure!
```
      - record: test:metric:avg_over_time_avg_by_site
        expr: >
          avg_over_time(
            avg by (site) (
              metric
            )
          [2m])
```
The problem with record `test:metric:avg_over_time_avg_by_site` is the outside `avg_over_time` also need a range vector as it's input, but the result of `avg by (site) (metric)` is a instant vector. That's why prometheus gives "parse error: ranges only allowed for vector selectors".
MetricsQL supports it and will automatically do range query for `avg by (site) (metric)` but with `step: 5m(default)`, so the results will be  `0m:0 5m:10 10m:20...`, then the result of outside `avg_over_time` will be `0m:0 1m:0 2m:0 3m:0 4m:0 5m:10...`, and that's not you want.
In order to pass the right `step` to inner func, there comes subquery, see this [doc](https://prometheus.io/blog/2019/01/28/subquery-support) for more details.
>a subquery is a part of a query, and allows you to do a range query within a query, which was not possible before.

**Comment by cooltea713705** [comment]
Thanks for the input! I'll close the question as you have provided the information that we were looking for (`step: 5m(default)`). This has indeed solved what we were seeing as an issue.
