### ISSUE TITLE
stream aggregation: deduplication should keep the sample with biggest timestamp on interval

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5643]
### Is your feature request related to a problem? Please describe

Currently, `--remoteWrite.streamAggr.dedupInterval` option in vmagent reuses [last](https://docs.victoriametrics.com/stream-aggregation.html#last) aggregation output for deduplication. But this differs from how VictoriaMetrics deduplicates samples and may result into incorrect output.

### Describe the solution you'd like

It would be better not to keep the last received value on deduplication interval, but keep the sample with the biggest timestamp on the interval or the biggest value on timestamp conflicts - see https://docs.victoriametrics.com/#deduplication

This should prevent from improper deduplication results when there are more than metrics source producing duplicates. For example, if there is an HA pair of clients pushing data to vmagent then there is a chance that the pushed values will differ. This is extremely important for counters calculation, because it may result in counter to behave more like gauge if clientA will send value lower than clientB.

**Comment by valyala** [comment]
Re-opening the issue until the new release is published with this feature.

**Comment by valyala** [comment]
[stream de-duplication](https://docs.victoriametrics.com/stream-aggregation/#deduplication) uses the same logic as the [regular de-duplication](https://docs.victoriametrics.com/#deduplication) starting from [v1.100.0](https://docs.victoriametrics.com/changelog/).

Closing the feature request as done.
