### ISSUE TITLE
vmalert: ALERTS_FOR_STATE omitted for immediate alerts

### ISSUE THREAD

**Issue by trearcul** [VictoriaMetrics/VictoriaMetrics#5648]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

Hi, 
I'd like to inquire if there is any specific reason for [omitting](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/7e374c227fe079a6f30fc98e80fe32e04d3c2c3b/app/vmalert/rule/alerting.go#L581) the `ALERTS_FOR_STATE` metric for immediate alerts (when `for == 0`). I'm aware that the `ALERTS_FOR_STATE` metric is more or less internal metric, but we would greatly appreciate having it even for immediate alerts.

Additionally, I would be happy to try and create potential PR.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by trearcul** [comment]
Hi @Amper, thank you for looking at my question.

The `ALERTS` metric doesn't say anything about alert age, on the other hand the `ALERTS_FOR_STATE` metric does as it holds a timestamp of alert start in its value. The alert age is useful for further monitoring of fired alerts, for example for elevation to more severe alerts if the age exceeds some threshold, dynamic `for` interval and surely some more cases.

Getting the age of immediate alerts is quite complicated right now and must be done using recording rules, which takes some resources. Other methods can take even more resources, because you may need to query extensive time intervals in every rule eval round. So I thought it would be a lot easier to create the `ALERTS_FOR_STATE` metric for every alert without considering the `for` interval.

**Comment by Amper** [comment]
But alerts without `"for"` doesn't have age, because the're one-shot events, they only have firing date. You can calculate firing date for them with [`timestamp` MetricsQL function](https://docs.victoriametrics.com/MetricsQL.html#timestamp).
Or did I misunderstand something?

@hagen1778, wdyt?

**Comment by trearcul** [comment]
I appreciate your point about calculating the firing date, and you are correct. However, as mentioned earlier, this operation can be resource-demanding, because you **may need to query extensive time windows** compared to storing "a few more" (it depends) series of `ALERTS_FOR_STATE` and then querying its value.

I personally don't see a reason for treating immediate alerts differently. IMHO even immediate alert can have age as it starts to fire at certain moment and since then it should have its age until it got resolved. Of course valid reasons may exists for treating immediate alerts differently and that brings me back to my original question. Do you know about any?

BTW, I've always thought that the `for` interval is for purposes like defining minimal duration before firing an alert to minimize alerts flapping.

**Comment by trearcul** [comment]
Additionally, I've just tested immediate alerts in Prometheus and the `ALERTS_FOR_STATE` metric exists even for immediate alerts there. I know it's different project, but it may also be taken into consideration.

**Comment by hagen1778** [comment]
Hi @trearcul! Thanks for pointing this out! I didn't expect Prometheus generates those for rules with `for: 0`, as it was mentioned the `ALERTS_FOR_STATE` series are used for state restore purposes. But I find your arguments and use case valid and the fact that Prometheus also does this only contributes more in your point of view.
The behavior of vmalert supposed to be changed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5680

**Comment by trearcul** [comment]
Hi @hagen1778, that was super fast, thank you! 🙂

**Comment by hagen1778** [comment]
@trearcul the fix was included in https://docs.victoriametrics.com/changelog/#v1970
Closing this request as done
