### ISSUE TITLE
labels are ignored when maxLabelsPerTimeseries (default = 30) is reached

### ISSUE THREAD

**Issue by fsperling** [VictoriaMetrics/VictoriaMetrics#565]
**Describe the bug**
If a timeseries has more than 30 labels the additional ones are ignored without any warning/log msg.

**To Reproduce**
Create a timeseries with more than 30 labels and view it after scraping.

**Expected behavior**
A log message for every time a timeseries with more than 30 labels might not be practical. However it would be good to get some kind of feedback that labels are ignored. Maybe one message per scrape interval.

Also the parameter maxLabelsPerTimeseries and the described behavior seem to be missing from the documentation.

The relevant places in the source are:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/432187ac3b3372eea2a92885a0a8a0e99bd05b0c/app/vminsert/main.go#L36
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0686ac52c39eba6731be26797fb6f72b0af128a2/lib/storage/metric_name.go#L444

**Version**
v1.37.0

**Comment by valyala** [comment]
I think the best approach would be to export a metric for the number of skipped labels, so alerts could be created on top of this metric. Such a metric - `vm_metrics_with_dropped_labels_total` - has been added in the commit b542e5068078f4e01892f44af65345c4102f1194 . This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
FYI, the `vm_metrics_with_dropped_labels_total` metric is available in VictoriaMetrics starting from [v1.37.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by fsperling** [comment]
Thanks! That's a good solution.

**Comment by valyala** [comment]
@fsperling , I think VictoriaMetrics could log a sample of metrics with with too big number of labels. This could help the operator identifying and fixing the source of metrics with too big number of labels. Feel free creating new feature request for this task.
