### ISSUE TITLE
code problem about index merge

### ISSUE THREAD

**Issue by ahfuzhang** [VictoriaMetrics/VictoriaMetrics#5651]
### Is your feature request related to a problem? Please describe

index merge can be faster

### Describe the solution you'd like

see: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/41d6c8a7dd521fa30786db715205db2cbb42ca00/lib/mergeset/merge.go#L130

when read data from part dir 1 and part dir 2, part1's every index will compare with part2's current item.

if we compare the lastItem of part1 and the firstitem of part2, index merge might be faster.
```go
// example code
  lastItem := items[len(items)-1].Bytes(data)
  if string(lastItem)<= nextItem{
        // merge current block with out compare each index
}
```

**Comment by valyala** [comment]
@ahfuzhang , thanks for the suggestion! It has been implemented in the commit 980338861fe552253fd843fa150a1d58b80bc544 . This commit will be included in the next release (`v1.97.0`). Closing the issue as done then.
