### ISSUE TITLE
avg(metric) -avg(metric) not zero

### ISSUE THREAD

**Issue by Hello-World-0X** [VictoriaMetrics/VictoriaMetrics#5654]
### Is your question request related to a specific component?

vmselect 

### Describe the question in detail

<img width="2491" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/25972398/6d622cc6-2c07-4c77-9f58-d6a504557a0a">
I have a metric is avg(ww_1020_2), but when i use avg(ww_1020_2) - avg(ww_1020_2) ,the result is not 0

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @Hello-World-0X.
VictoriaMetrics stores all the values as [float64](https://en.wikipedia.org/wiki/Double-precision_floating-point_format, so you can get some [accuracy problems](https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems) like that on arithmetic operations.
There are two workarounds for that:
- You can use [MetricsQL round function](https://docs.victoriametrics.com/MetricsQL.html#round)
- You can add [`round_digits` query parameter](https://docs.victoriametrics.com/#prometheus-querying-api-enhancements) to your http requests.

**Comment by valyala** [comment]
See also https://docs.victoriametrics.com/keyConcepts.html#raw-samples

**Comment by Hello-World-0X** [comment]
I can understand float will lost some accuracy, but for two not accurate value , which is the same, the result after minus， will be zero， Is it not so? I  want to simplify my question, for the query avg(ww_1020_2), why the result at the same timestamp 1705909860 is not same?

<img width="2301" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/25972398/bf7964b0-7c21-45dd-811d-46a7b1096e4f">

<img width="2302" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/25972398/4fbd98de-3125-4646-a9f9-9f07dd36bbff">
