### ISSUE TITLE
Does vmstorage lose data during graceful shutdown?

### ISSUE THREAD

**Issue by bleedfish** [VictoriaMetrics/VictoriaMetrics#5662]
### Describe the bug

When the vmstorage receives a stop signal and the merge worker is actively working, there are two scenarios:

Case 1: If the merge worker's pending writes (pws) include an in-memory part and it receives a stop signal (stopch), the loop exits abruptly. This leads to an incomplete directory structure in the generated file. The directory will be missing the metadata.json file, and the parent directory (parts.json) will also lack reference to this directory. Upon restarting vmstorage, the process will delete this incomplete directory, resulting in permanent data loss.

Case 2: If the merge worker's pending writes (pws) only include data from small parts or big parts, and the directory is incomplete without a metadata.json file due to the abrupt exit, it is considered okay. This is because the pws before the merge still exist in the directory.

### To Reproduce

Add some log in  lib/storage/partition.go
lib/storage/partition.go: function: mergeParts,
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3396080/3d4004ab-5646-448e-b558-ad8f8078e012)
 ----(This is to print which pending writes (pws) need to be merged.)
and  
lib/storage/partition.go: mergeWorker
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3396080/4caa8a3a-956c-41e2-b397-828ed55395d0)
----(This is to print that the merge process has received a stop signal (stopch), forcing it to terminate.)
and 
lib/storage/partition.go: mustOpenParts
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3396080/ec580321-9c54-4ecd-9ace-91641708af62)
---- (This is to print that the incomplete directories are deleted upon restarting.)

### Version

v1.96

### Logs

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3396080/2fd4d318-6c49-43a3-86ac-c776fddbd585)

**Comment by dmitryk-dk** [comment]
Hi @bleedfish ! But can you explain how you stoped the VM storage? Did it shoot down gracefully? 
Can you try to use this flag
```
-inmemoryDataFlushInterval duration
     The interval for guaranteed saving of in-memory data to disk. The saved data survives unclean shutdowns such as OOM crash, hardware reset, SIGKILL, etc. Bigger intervals may help increase the lifetime of flash storage with limited write cycles (e.g. Raspberry PI). Smaller intervals increase disk IO load. Minimum supported value is 1s (default 5s)
```

**Comment by bleedfish** [comment]
I use the "kill" command with the process name to send a signal and stop the process. The inmemoryDataFlushInterval parameter is not configured, so it should be using the default value of 5 seconds.

when I stop VM storage，this is log :
2024-01-24T10:26:26.621+0800    info    app/vmstorage/main.go:138       service received signal terminated
2024-01-24T10:26:26.621+0800    info    app/vmstorage/main.go:140       gracefully shutting down http service at ":8482"
2024-01-24T10:26:26.621+0800    info    app/vmstorage/main.go:145       successfully shut down http service in 0.000 seconds
2024-01-24T10:26:26.621+0800    info    app/vmstorage/main.go:147       gracefully shutting down the service
2024-01-24T10:26:26.621+0800    info    app/vmstorage/main.go:153       successfully shut down the service in 0.000 seconds
2024-01-24T10:26:26.621+0800    info    app/vmstorage/main.go:155       gracefully closing the storage at /data1/vm

**Comment by bleedfish** [comment]
The scenario should occur when the merge worker's pending writes (pws)  include both  in-memory parts and the pending writes from the small part.

**Comment by dmitryk-dk** [comment]
Hi @bleedfish ! I will try to reproduce it. Thank you for your information

**Comment by hagen1778** [comment]
@zekker6 would you mind taking a look at this issue? From the description it looks like only unfinished merges are lost, which is ok.

**Comment by zekker6** [comment]
@bleedfish The point @hagen1778 posted above is correct: when storage is stopped only unfinished partition is left on disk. Original partitions are not deleted until the merge will be completed.
Code wise partitions will be swapped [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5320cc3198bfe25aacd92c050d26dbd3ce27dc54/lib/storage/partition.go#L1460), this code path is only reachable in case merge will not return an `err` which [happens in case DB is shutting down](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a1baf25c2e2b936031d7f35998f1e7291a9afd3d/lib/storage/merge.go#L51).
When storage is [stopping](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5320cc3198bfe25aacd92c050d26dbd3ce27dc54/lib/storage/partition.go#L888-L927) it first cancels all running background merges/merge workers and then flushes inmemory partitions to disk to prevent any data loss. There is also additional check that there are no inmemory parts left before stopping the storage to make sure there is no bug which could lead to unnoticeable data loss.

**Comment by bleedfish** [comment]
@zekker6 
Yes, I've tried several times to reproduce this error over the past few day, but I haven't been able to make it happen again。

When storage is [stopping](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5320cc3198bfe25aacd92c050d26dbd3ce27dc54/lib/storage/partition.go#L888-L927) it first cancels all running background merges/merge workers and then flushes inmemory partitions to disk to prevent any data loss. There is also additional check that there are no inmemory parts left before stopping the storage to make sure there is no bug which could lead to unnoticeable data loss.

The process behaves as described above.

**Comment by jiekun** [comment]
I think the original question has been answered. Please reopen it if you still encounter issue.
