### ISSUE TITLE
vmagent does not update consul service meta

### ISSUE THREAD

**Issue by vyacheslav-skvortsov** [VictoriaMetrics/VictoriaMetrics#5665]
### Describe the bug

vmagent does not update consul service metadata without restart

### To Reproduce

1. Register service in consul with any metadata foo=1
I can see endpoint label __meta_consul_service_metadata_foo="1"
2. Update service meta to foo=2 (or add the new one)
label keep the same value __meta_consul_service_metadata_foo="1"
3. Restart vmagent updates all metadata values

### Version

vmagent-20231212-224644-tags-v1.96.0-0-g304fe0565

### Used command-line flags

-httpListenAddr="xx.xxx.x.xx:xxxxx"
-promscrape.cluster.name="1"
-promscrape.config="/etc/prometheus/prometheus.yml"
-promscrape.consulSDCheckInterval="1m0s"
-remoteWrite.url="secret"

**Comment by dmitryk-dk** [comment]
Hi! @vyacheslav-skvortsov i tried to reproduce your bug, but i can't reproduce it. Could you please share reproducible example? 

My steps

```
./vmagent  --remoteWrite.flushInterval=5s --httpListenAddr=:8430 --promscrape.disableKeepAlive=false --remoteWrite.url=http://127.0.0.1:8431/api/v1/write -promscrape.config=consul.yml -promscrape.consulSDCheckInterval=5s
```

```yaml
scrape_configs:
  - job_name: consul
    consul_sd_configs:
      - server: "127.0.0.1:8500"
    relabel_configs:
      - action: keep
        source_labels: [__meta_consul_service_metadata_env]
        regex: "prod"
```
In this config we tries to keep all metrics with env meta label
but in the consul config we are started service without this label

```json
{
      "name": "vmselect",
      "port": 8481,
      "tags": [
        "vmselect"
      ]
    },
```

And checked the vmagent targets they will be dropped
<img width="1677" alt="Screenshot 2024-01-23 at 16 00 14" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/6353d50d-fcdd-4d46-b6a5-6744c94b4aab">

after I have updated the concul config and added meta label

```json
{
      "name": "vmselect",
      "port": 8481,
      "tags": [
        "vmselect"
      ],
      "meta": {
        "env": "prod",
     }
    },
```

and ran `consul reload`

After checked the targets
<img width="1670" alt="Screenshot 2024-01-23 at 16 02 52" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/d3471ab6-008e-41f9-b68d-d32871ef2fcc">

It shows the discovered target with the new metric `__meta_consul_service_metadata_env="prod"`
So the `vmagent` works as expected.

**Comment by vyacheslav-skvortsov** [comment]
Hi @dmitryk-dk!
Thank you for your reply and your time.
Actually I can`t reproduce this behaviour on my side anymore. I think it was a problem with local consul agent which was not getting updates from the cluster.
Sorry for the false alarm)
