### ISSUE TITLE
`-bigMergeConcurrency` and `-smallMergeConcurrency` flags do not really take effect

### ISSUE THREAD

**Issue by foobar** [VictoriaMetrics/VictoriaMetrics#567]

**Comment by valyala** [comment]
Re-opening this issue until new release with the bugfix is out.

**Comment by valyala** [comment]
The bugfix has been included in VictoriaMetrics [v1.37.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
