### ISSUE TITLE
Incorrect log output while there're unsupported metrics

### ISSUE THREAD

**Issue by drTr0jan** [VictoriaMetrics/VictoriaMetrics#5670]
### Describe the bug

`vmagent` (or possible other services) outputs incorrect log message while compiled by Go120 (or older) runtime after https://github.com/VictoriaMetrics/metrics/issues/54.

```
root@boris:/usr/local/etc/rc.d# vmagent  -promscrape.config="/usr/local/etc/prometheus/prometheus.yml" -dryRun
2024/01/23 17:21:01 github.com/VictoriaMetrics/metrics: do not expose go_memlimit_bytes metric, since the corresponding metric /gc/gomemlimit:bytes isn't supported in the current Go runtime
2024-01-23T14:21:01.044Z  info  VictoriaMetrics/lib/logger/flag.go:12  build version: vmagent-20240117-010526-d277977
2024-01-23T14:21:01.044Z  info  VictoriaMetrics/lib/logger/flag.go:13  command-line flags
2024-01-23T14:21:01.044Z  info  VictoriaMetrics/lib/logger/flag.go:20    -dryRun="true"
2024-01-23T14:21:01.044Z  info  VictoriaMetrics/lib/logger/flag.go:20    -promscrape.config="/usr/local/etc/prometheus/prometheus.yml"
2024-01-23T14:21:01.045Z  info  VictoriaMetrics/app/vmagent/main.go:116  all the configs are ok; exiting with 0 status code
```
The first message is differ from other lines. It would be good to rewrite it as other lines with log level (warn, ex.).

### To Reproduce

Build vm with go1.20 and run: `vmagent  -promscrape.config="/usr/local/etc/prometheus/prometheus.yml" -dryRun`

### Version

```
root@boris:/usr/ports/www/grafana# vmagent -version
vmagent-20240117-010526-d277977
```

LTS v1.93.10

**Comment by drTr0jan** [comment]
@dmitryk-dk, the message appears in vmutils builded by go1.20.12 from 1.93.10.

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk, the message appears in vmutils builded by go1.20.12 from 1.93.10.

I have checked the package which is used to generate metrics and metrics like `go_memlimit_bytes` were added in the 
https://pkg.go.dev/runtime/metrics@go1.21.0
```
/gc/gomemlimit:bytes
	Go runtime memory limit configured by the user, otherwise
	math.MaxInt64. This value is set by the GOMEMLIMIT environment
	variable, and the runtime/debug.SetMemoryLimit function.
```
And checked the code 
```golang
{"/gc/gomemlimit:bytes", "go_memlimit_bytes"},
```

and in the function 

```golang
var supportedRuntimeMetrics = initSupportedRuntimeMetrics(runtimeMetrics)

func initSupportedRuntimeMetrics(rms [][2]string) [][2]string {
	exposedMetrics := make(map[string]struct{})
	for _, d := range runtimemetrics.All() {
		exposedMetrics[d.Name] = struct{}{}
	}
	var supportedMetrics [][2]string
	for _, rm := range rms {
		metricName := rm[0]
		if _, ok := exposedMetrics[metricName]; ok {
			supportedMetrics = append(supportedMetrics, rm)
		} else {
			log.Printf("github.com/VictoriaMetrics/metrics: do not expose %s metric, since the corresponding metric %s isn't supported in the current Go runtime", rm[1], metricName)
		}
	}
	return supportedMetrics
}
```
it shows that the metric doesn't supported by the runtime, so that it is expected behavior.

**Comment by drTr0jan** [comment]
Yep, it's right. But...

> it is expected behavior.

vm logger outputs messages to stderr as:
```2024-01-23T14:21:01.044Z  info  VictoriaMetrics/lib/logger/flag.go:12  build version: vmagent-20240117-010526-d277977```
or (with `-loggerDisableTimestamps` flag):
```info  VictoriaMetrics/lib/logger/flag.go:12  build version: vmagent-20240117-010526-d277977```

But metrics logger output the message in different format (different time format, absent priority):
```2024/01/23 17:21:01 github.com/VictoriaMetrics/metrics: do not expose go_memlimit_bytes metric, since the corresponding metric /gc/gomemlimit:bytes isn't supported in the current Go runtime```

It would be great to bring the format in line.

**Comment by dmitryk-dk** [comment]
> Yep, it's right. But...
> 
> > it is expected behavior.
> 
> vm logger outputs messages to stderr as: `2024-01-23T14:21:01.044Z info VictoriaMetrics/lib/logger/flag.go:12 build version: vmagent-20240117-010526-d277977` or (with `-loggerDisableTimestamps` flag): `info VictoriaMetrics/lib/logger/flag.go:12 build version: vmagent-20240117-010526-d277977`
> 
> But metrics logger output the message in different format (different time format, absent priority): `2024/01/23 17:21:01 github.com/VictoriaMetrics/metrics: do not expose go_memlimit_bytes metric, since the corresponding metric /gc/gomemlimit:bytes isn't supported in the current Go runtime`
> 
> It would be great to bring the format in line.

You are right. I suppose it should be fixed

**Comment by dmitryk-dk** [comment]
Hi @drTr0jan ! We discussed that issue and decided not to fix it because it needs changes in the metrics library to enable the same logger as VictoriaMetrics. Nad this functionality adds only complexity into the library instead of solve problem

**Comment by drTr0jan** [comment]
Thx for quick answer.
