### ISSUE TITLE
Timepicker in vmui for logs

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#5673]
### Is your feature request related to a problem? Please describe

It takes quite a long time to manually write the time interval and this process is often error-prone.

### Describe the solution you'd like

We need a time picker to select the time in the UI like timepicker in vmui for metrics:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/63a1d97d-32e8-44f8-a16d-dbaa27cc3e23)

### Additional information

Most likely the time interval in the time picker should be sent implicitly in the request, not as part of the query - this will help avoid a lot of problems.

**Comment by Loori-R** [comment]
This feature request has been implemented in [v0.5.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.5.0-victorialogs).
