### ISSUE TITLE
Ability to set the maximum number of displayed records in vmui for logs

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#5674]
### Is your feature request related to a problem? Please describe

Now the number of records displayed is limited to a fixed value (1000) which cannot be changed, there are scenarios where more records need to be displayed.

### Describe the solution you'd like

Need to add a field in vmui for logs where you can set the maximum number of records that can be displayed. 
I think the best place for this is the settings window.

**Comment by valyala** [comment]
This feature has been implemented in [VictoriaLogs v0.5.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.5.0-victorialogs).
