### ISSUE TITLE
Please tell me how to get the real series in /api/v1/series/count

### ISSUE THREAD

**Issue by aruicoding** [VictoriaMetrics/VictoriaMetrics#5675]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

Gosh, I'm confused, although vmui/#/cardinality gives me the total sequence, I'm finding that it's showing the active sequence when I want the true total, and when I use /api/v1/series/count I specify start times of -1d and -2d, and also find that the difference between those two points is much smaller than the true difference.
<img width="432" alt="截屏2024-01-24 19 18 49" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/97781337/bc246d5d-4e2d-4335-9245-5d3438e04693">

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @aruicoding ! What of the type of VictoriaMetrics do you use? I mean single version or cluster?
 
 If you are using the cluster version you should see the [documentation](https://docs.victoriametrics.com/#cardinality-explorer-statistic-inaccuracy).
 
 But overall all cardinality statistic is built on top of [/api/v1/status/tsdb](https://docs.victoriametrics.com/#tsdb-stats).

**Comment by aruicoding** [comment]
Hi @dmitryk-dk !we are using the cluster version.I want to get the amount of samples collected in a day (TotalSeries), aka rawSample, but I don't know which api to use, please help me, note that it's not the number of active TotalSeries, but the number of full TotalSeries.

**Comment by aruicoding** [comment]
Hi @dmitryk-dk ! Does totalseries refer to the amount of data for the whole day in local time or utc time? 00:00:00 to 23:59:59 in 2024-01-25? in  /api/v1/status/tsdb?topN=100000&date=2024-01-25

**Comment by aruicoding** [comment]
Hi @dmitryk-dk ! Thank you so much for helping me.What if I want to know the total raw samples at a certain point in time for a certain __name__?

**Comment by dmitryk-dk** [comment]
> Hi @dmitryk-dk ! Does totalseries refer to the amount of data for the whole day in local time or utc time? 00:00:00 to 23:59:59 in 2024-01-25? in /api/v1/status/tsdb?topN=100000&date=2024-01-25

Hi! You can check the information about tsdb in this part of the [documentation](https://docs.victoriametrics.com/#tsdb-stats).
For the query, it calculates 
```golang
start := int64(date*secsPerDay) * 1000
end := int64((date+1)*secsPerDay)*1000 - 1
```
and collects the series from DB

**Comment by dmitryk-dk** [comment]
> Hi @dmitryk-dk ! Thank you so much for helping me.What if I want to know the total raw samples at a certain point in time for a certain **name**?

If I understand correctly you can to query data with [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) via [/api/v1/query](https://docs.victoriametrics.com/keyConcepts.html#instant-query) HTTP APIs.

If you need querying raw samples for some [time series](https://docs.victoriametrics.com/keyConcepts.html#time-series) matching the given [series selectors](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors) on a specified time range (t-d ... t], then the following query to /api/v1/query HTTP API can be issued:

curl 'http://prometheus-host:9090/api/v1/query?query=some_series_selector[d]&time=t`
For example, [http://demo.robustperception.io:9090/api/v1/query?query=up[5m]](http://demo.robustperception.io:9090/api/v1/query?query=up%5B5m%5D)

See [this article](https://valyala.medium.com/analyzing-prometheus-data-with-external-tools-5f3e5e147639) for details.
