### ISSUE TITLE
Release feature `exposeMetadata` to expose TYPE and HELP metadata at the /metrics page

### ISSUE THREAD

**Issue by chenfeilee** [VictoriaMetrics/VictoriaMetrics#5683]
### Is your question request related to a specific component?

Victoria Metrics

### Describe the question in detail

Hi there,

Was looking around and found this commit merged into master a month ago https://github.com/VictoriaMetrics/VictoriaMetrics/commit/326a77c6974454f1585ac662b762138727fa41f4. Seems like it hasn't been released yet. Just wondering if this could make it into the next release and if so, when the next release would be?  :)

This feature would be super helpful as with this, we could start collecting metrics about our Victoria Metrics cluster and start monitoring it in Datadog. 

Thank you :bow

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello! Exposing of metadata at /metrics page by VM components is available starting from [v1.97.0](https://docs.victoriametrics.com/changelog/#v1970):
> FEATURE: all VictoriaMetrics components: add `-metrics.exposeMetadata` command-line flag, which allows displaying `TYPE` and `HELP` metadata at `/metrics` page exposed at `-httpListenAddr`. This may be needed when the `/metrics` page is scraped by collector, which requires the `TYPE` and `HELP` metadata such as [Google Cloud Managed Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus/troubleshooting#missing-metric-type).
