### ISSUE TITLE
how to send data from one vm to another

### ISSUE THREAD

**Issue by denniedeng** [VictoriaMetrics/VictoriaMetrics#5684]
### Is your question request related to a specific component?

vm cluster

### Describe the question in detail

by myself agent, i had remote write metrics to my vm cluster. but how can i send the metrics to another vm cluster?
btw, myself agent is written in java, so i do not want to use it to remote write to another vm cluster also, it's not a good way.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @denniedeng!
You can try using [vmagent](https://docs.victoriametrics.com/vmagent.html) - it supports sending data to multiple destinations configured with distinct - see https://docs.victoriametrics.com/vmagent.html#replication-and-high-availability
In your case, you can run vmagent with two `-remoteWrite.url`: `./vmagent -remoteWrite.url=http://clusterA -remoteWrite.url=clusterB`. With this config vmagent will send all received or scraped metrics to two destinations: clusterA and clusterB.

**Comment by denniedeng** [comment]
Thanks. because i have another agent to deal with business logic, so using vmagent is not a good choice. 
now, i use prometheus to pull data. then remote write to two vm.
