### ISSUE TITLE
vmalert 告警问题

### ISSUE THREAD

**Issue by zcspk** [VictoriaMetrics/VictoriaMetrics#5687]
### Is your question request related to a specific component?

我手动上传指标到 VictoriaMetrics ， 可以查看， 但是vmalert 告警发出后alertmanger 看不到信息。 那些prometheus 采集的指标写到VictoriaMetrics 的 指标， vmalert 告警发出可以查看

### Describe the question in detail

我手动上传指标到 VictoriaMetrics ， 可以查看（VictoriaMetrics，grafana）,   但是vmalert 告警发出后alertmanger 看不到信息。 
那些prometheus 采集的指标写到VictoriaMetrics ， vmalert 告警发出，早alertmanger上可以查看

谢谢大佬解答，十分感谢

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @zcspk! 
VictoriaMetrics community is using English as common language for issues, comments and documentation. I'd appreciate translating your question into English so everyone in the community could benefit from our communication. Thanks!

**Comment by zcspk** [comment]
I manually uploaded the metrics to VictoriaMetrics, which can be viewed, but alertmanger can't see the information after the vmalert alarm is issued.    Those metrics collected by prometheus are written to VictoriaMetrics' vmalert alert alert emitted alertmanger can be viewed. For example: curl -d 'metric_name{foo="bar"} 123' -X POST http://172.25.25.26:8888/insert/0/prometheus/api/v1/import/prometheus. vmalert configuration. expr: metric_name{foo="bar"} > 1 。 The status is firing. But alertmanger doesn't see the message

**Comment by hagen1778** [comment]
@zcspk have you gone through https://docs.victoriametrics.com/vmalert.html#troubleshooting ?
Does it send alert notifications for other cases? Have you checked vmalert logs? Have you tried[ this setup](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker#docker-compose-environment-for-victoriametrics) which already contains all components configured together?

**Comment by jiekun** [comment]
Close due to inactivity.
