### ISSUE TITLE
Grafana: fill template variable with values from selected time range only

### ISSUE THREAD

**Issue by CoreMoni** [VictoriaMetrics/VictoriaMetrics#5695]
### Is your question request related to a specific component?

Victoria Metrics, Grafana 10

### Describe the question in detail

Hello,

For my variable dropdowns I used `label_values(...)` to fill the template variables with the labels that existed in the timerange of my dashboard (so the panels can use them as filter).

Then we switched from Prometheus to Victoria Metrics, and I got values from outside the selected time range (which is intentional according to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3107 )

But this was a problem, because I got complaints that when filtering for some values, the panel suddenly had no data anymore (because the labels didn't exist in the dashboard's time range)
So I replaced `label_values(...)` with `query_result(last_over_time(...[$__range]))` and the dropdowns were correct again.

But now we will be going from Grafana 9 to Grafana 10, and during tests I found that in Grafana 10 (v10.2.3), `query_result(last_over_time(...[$__range]))` returns values from before the selected time range.

I thought maybe `query_result` used to be an instant query, and with Grafana 10, it is now executed as a range query. But when I remove the `last_over_time` part, I only get results from the last point in time, so it's not a range query.

My question is, how can I get exactly the labels that exist within the dashboard's time range, not more and not less, with Grafana 10?

Thanks.

**Comment by hagen1778** [comment]
Grafana docs saying the following:
> Make sure to set the variable’s refresh trigger to be On Time Range Change to get the correct instances when changing the time range on the dashboard.
https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/#use-interval-and-range-variables

Do you have this setting enabled?

**Comment by hagen1778** [comment]
>I thought maybe query_result used to be an instant query, and with Grafana 10, it is now executed as a range query. But when I remove the last_over_time part, I only get results from the last point in time, so it's not a range query.

So I just installed `grafana-v10.3.1` and tried it against VM single node which should log all queries taking longer than 1ns (all queries :) ). Here's what I get for my variable
<img width="527" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/cbd264a4-d2bb-4e71-9f2f-975982a89dc2">


Last 30min:
```
2024-01-26T13:01:59.890Z        warn    VictoriaMetrics/app/vmselect/main.go:167        slow query according to -search.logSlowQueryDuration=1ns: remoteAddr="127.0.0.1:63800, X-Forwarded-For: ::1", duration=0.001 seconds; requestURI: "/api/v1/query?query=last_over_time%28vm_app_version%5B1800s%5D%29+&time=1706274120"
```

Last 5min:
```
2024-01-26T13:02:31.029Z        warn    VictoriaMetrics/app/vmselect/main.go:167        slow query according to -search.logSlowQueryDuration=1ns: remoteAddr="127.0.0.1:63800, X-Forwarded-For: ::1", duration=0.001 seconds; requestURI: "/api/v1/query?query=last_over_time%28vm_app_version%5B300s%5D%29+&time=1706274151"
```

In both cases, it is as instant query with correct `[window]` in the query. The `time` param is also correct - it is current time when I make a query. So it looks like it should work correctly.

**Comment by CoreMoni** [comment]
Not sure if I understand your example...

Anyway, I created a test dashboard that fills variables with pod names (the filter is just so we don't get too many).

VarLV is filled via label_values, VarQR via query_result, and VarSQ via a third method I found, which is Series Query

![Issue5695_1](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/4e044950-af7a-4340-836a-8ee79767e284)

The dashboard has three Text panels showing the content of each variable, and a TimeSeries panel showing the pods of the selected time range with the following query:

![Issue5695_2](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/a100c0ef-bd53-406e-b592-5661b14408ea)

Here are the pods from the last two days:

![Issue5695_3](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/a8305dfd-2dc2-4777-adfd-a85b60c760f1)

With the time range being full days, all three methods to fill the variable work as expected.

If I zoom in now, and set the time range to 2024-01-25 16:00:00 to 21:59:59, there are only two pods in that time range left: 8vnz8 and dvbhw.

However, the variables contain more values.
Label Values and Series Query contain 3 pods - these are all the pods from the entire day 2024-01-25
Query Result contains even more pods. The additional pods are pods that were started the next day.

![Issue5695_4](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/8126b6df-ca9a-4323-a487-989c37bb7411)

(Btw, if I change the query result query from last_over_time to first_over_time, the result doesn't change at all...)

Here's the dashboard json: 
[Variable_Fill_Test.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/14066760/Variable_Fill_Test.json)

**Comment by CoreMoni** [comment]
We are now on Grafana 10.3.1, Victoria Metrics 1.96.0, and query_result seems to work now:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/111497946/3a51abe0-0f2d-443e-bd65-071c1a7400c7)
