### ISSUE TITLE
how max_lookback works?

### ISSUE THREAD

**Issue by n4mine** [VictoriaMetrics/VictoriaMetrics#570]
**Describe the bug**
got redundant sample from vm

**To Reproduce**
1. write 1 sample to vm use /write api
```
v=$(date +%s) ; echo $v; curl 127.0.0.1:8428/write -d "$(echo  m v=${v} ${v}000000000)"
```
get ```1592491293```

2. query 
```
curl -sG  "127.0.0.1:8428/api/v1/query_range?query=m&start=$(date +%s -d '10 minutes ago')&end=$(date +%s)&step=10s&max_lookback=7s" | jq '.data.result[].values[]' -r
[
  1592491300,
  "1592491293"
]
[
  1592491310,
  "1592491293"
]
```

**Expected behavior**
```
[
  1592491310,
  "1592491293"
]
```
should **not** be return

the following image, is what do i understand about max_lookback, it's corrent?
![111](https://user-images.githubusercontent.com/3345153/85037136-8a8f4c80-b1b7-11ea-992f-b2e4ab138a6d.jpg)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./bin/victoria-metrics --version
victoria-metrics-20200618-144056-heads-master-0-ge91d7588
```

**Comment by valyala** [comment]
The image is correct, but VictoriaMetrics may duplicate the last data point if it has a timestamp closer than `-search.latencyOffset` to the current time. See [adjustLastPoints](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0afd48d2ee30c42220efb8b98574822617abb83a/app/vmselect/prometheus/prometheus.go#L840) function for details.
