### ISSUE TITLE
Disable vmalert notifier

### ISSUE THREAD

**Issue by Sin4wd** [VictoriaMetrics/VictoriaMetrics#5703]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

Is it possible to completely disable vmalert notifier?
We have multiple vmalerts for calculating recording rules and pointing notifier to a wrong address generates many error logs. Moreover, these errors prevent us from tracking error metrics.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> We have multiple vmalerts for calculating recording rules and pointing notifier to a wrong address generates many error logs. Moreover, these errors prevent us from tracking error metrics.

It is allowed to omit notifier.url if you don't have alerting rules in your config:
> -notifier.url is optional and is needed only if you have alerting rules.
https://docs.victoriametrics.com/vmalert/#topology-examples

If you do have alerting rules but don't want notifications to be sent, then you can set `-notifier.blackhole` cmd-line flag:
> -notifier.blackhole
   Whether to blackhole alerting notifications. Enable this flag if you want vmalert to evaluate alerting rules without sending any notifications to external receivers (eg. alertmanager). -notifier.url, -notifier.config and -notifier.blackhole are mutually exclusive.
