### ISSUE TITLE
vmauth: support dns domain as route destination

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#5707]
### Is your feature request related to a problem? Please describe

vmauth can balance load among multiple HTTP backends defined under `url_prefix` with different mode. 
In Kubernetes, if users want to perform loadbalance on workload's pods, they need to list all the pods' subdomain[since address is normally changed after pod recreate] under `url_prefix`, and for now it's only possible for statefulset since they can have [fixed subdomain](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/).
But sometimes user can't give the entire server list or the server addresses can change dynamically, and this list is already maintained by other dns server. Like for deployment, we can also use a [Headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) to control the domain of pods.
> 

### Describe the solution you'd like
It will be great if we can config this domain in vmauth directly, and vmauth will periodically re‑resolve the domain names into IP addresses and load balancing across the set of addresses.

**Comment by valyala** [comment]
DNS-based discovering of backend IPs is available in [vmauth](https://docs.victoriametrics.com/vmauth/) starting from [v1.100.0](https://docs.victoriametrics.com/changelog/). See [these docs](https://docs.victoriametrics.com/vmauth/#discovering-backend-ips) for details.

Closing the feature request as done.
