### ISSUE TITLE
Vmbackup:  Provide client-side TLS configuration to create/delete snapshot

### ISSUE THREAD

**Issue by khushijain21** [VictoriaMetrics/VictoriaMetrics#5724]
### Is your feature request related to a problem? Please describe

Currently, vmbackup does not give provision for TLS connection. It connects to snapshot url via HTTP scheme only.
 

### Describe the solution you'd like

Provide additional CLI flags for client side TLS configuration in vmbackup 

### Additional information

If the community feels this is a required feature I would like to contribute here. Also please do share if there are any better approaches for the same.

**Comment by Haleygo** [comment]
Hi @khushijain21 ,
Thanks for the issue and the offer to contribute, I think it's a good feature since vmsingle/vmstorage could enable TLS.
Please correct me if I'm wrong or there is another way @zekker6 @dmitryk-dk

**Comment by zekker6** [comment]
That seems to be a good feature to me as well. Currently vmbackup should accept any types of URLs, but it won't allow customizing TLS configuration options for this(for example use custom CA in case vmstorage is configured with self-signed certs).
@khushijain21 I will assign you to this feature to indicate that you are working on it. If you will need any help with the contribution please let us know.

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5738 has been merged and will be available in the next release.

**Comment by valyala** [comment]
The following `-snapshot.tls*` command-line flags are available in [vmrestore](https://docs.victoriametrics.com/vmrestore.html) and [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager/) starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html):

- `-snapshot.tlsInsecureSkipVerify`
- `-snapshot.tlsCertFile`
- `-snapshot.tlsKeyFile`
- `-snapshot.tlsCAFile`
- `-snapshot.tlsServerName`

Closing the feature request as done.
