### ISSUE TITLE
vmalert: new metrics for firing and pending alerts count.

### ISSUE THREAD

**Issue by Allineer** [VictoriaMetrics/VictoriaMetrics#573]
How about two new vmalert's metrics for:

1. for firing alerts (gauge)
```
count(ALERTS{alertstate="firing"})
```

2. for pending alerts (gauge)
```
count(ALERTS{alertstate="pending"})
```

Maybe, with alertname label.
For those, who uses `-remoteWrite.url` database only for vmalert instance and with a minimal retention.

**Comment by chaets** [comment]
How about ALERTS_FOR_STATE as well?

**Comment by Allineer** [comment]
@chaets 

> For those, who uses -remoteWrite.url database only for vmalert instance and with a minimal retention.

**Comment by valyala** [comment]
@hagen1778 , the commit that extends metrics exported by `vmalert` has been included in [v1.39.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Should we close this issue as fixed?

**Comment by Allineer** [comment]
Wow!

Give me sime hours fir testing it and i'll close this issue

**Comment by Allineer** [comment]
@hagen1778, @valyala, it's working, thanks!

**Comment by Allineer** [comment]
But...
Why `ID` label is used? Why not simply sum() values over alertname and group labels?
This label not in any way indicate a specific rule of several with the same name, i.e. this label is useless to the user, right?

**Comment by valyala** [comment]
> Why ID label is used? Why not simply sum() values over alertname and group labels?

See the answer at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/654#issuecomment-667696586 .

> This label not in any way indicate a specific rule of several with the same name, i.e. this label is useless to the user, right?

The `alertID` is used in `http://<vmalert-addr>/api/v1/<groupName>/<alertID>/status`

**Comment by Allineer** [comment]
Understand. Thanks.
