### ISSUE TITLE
docs: broken links to particular releases at changelog after switching to new docs

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#5731]
### Describe the bug

Links to changelog of a particular release are broken after switching to new docs.

### To Reproduce

Try opening https://docs.victoriametrics.com/CHANGELOG.html#v1930 . It should show changelog for v1.93.0 release. In reality it opens https://docs.victoriametrics.com/changelog/#v1930 , but doesn't scroll to `v1.93.0` release changelogs. The same applies to changelogs from the previous years. For example, https://docs.victoriametrics.com/changelog_2023/#v1937 must scroll to `v1.93.7` changelog.

### Version

The latest `master` branch

**Comment by tenmozes** [comment]
Hugo and Goldmark (which Hugo uses by default for markdown rendering) don't strip tags from headings by default. I changed the default generation of `id` for headings
