### ISSUE TITLE
How to debug premature alert resolution?

### ISSUE THREAD

**Issue by Homulvas** [VictoriaMetrics/VictoriaMetrics#5741]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

We have several alerts that get resolved in Opsgenie even though the alert is still firing in vmalert.
Opsgenie log displays messages like:
```
system  System
Alert closed via Prometheus[Prometheus-Close Alert] with incomingDataId[da459e90-b2d3-4d75-8861-81d9984f3e13] with customSource[https://vmalertmanagerurl/#/alerts?receiver=monitoring-alertmanager-config-opsgenie-default]
```
However, even after enabling debug logs for specific alerts the vmalert logs don't show any resolution events at the time when Opsgenie reports a resolved alert. Evaluation logs also shows that the series consistently returns a value over a long period of time..

I'm running out of ideas on how to debug this better. Any advice would be greatly appreciated.

P.S. the alert query in question is an average over a 5min window so it should be resistant to the issues of data delay.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/Troubleshooting.html
- [x] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @Homulvas 

Based on your description it seems like vmalert is behaving as expected here, but it is actually Alertmanager sending alert `firing`/`resolved` events to external notify configs. It is better to check the Alertmanager logs and metrics to understand why the alert went to `resolved` state. Using `--log.level=debug` and checking for incoming and outgoing events might contain useful information.
Also, if using a clustered setup of Alertmanagers it worth checking if there were any cluster connections issues as well as ensuring that `vmalert` is provided with list of all Alertmanager instances(see [this](https://docs.victoriametrics.com/vmalert/#ha-vmalert) doc for example deployment configuration of `vmalert` and Alertmanager in HA mode).

**Comment by Homulvas** [comment]
I got some more logs from alertmanager:
```
DEFAULT 2024-02-01T16:32:45.924029764Z [resource.labels.podName: vmalertmanager-vmalertmanager-1] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:32:45.923Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=SomeName[9da5035][active]
DEFAULT 2024-02-01T16:32:45.926752976Z [resource.labels.podName: vmalertmanager-vmalertmanager-0] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:32:45.926Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=SomeName[9da5035][active]
DEFAULT 2024-02-01T16:33:00.807320889Z [resource.labels.podName: vmalertmanager-vmalertmanager-0] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.806Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{}/{}:{alertname=\"SomeName\", env=\"prod\", instance_id=\"someId\", namespace=\"monitoring\", severity=\"critical\"}" msg=flushing alerts=[SomeName[9da5035][resolved]]
DEFAULT 2024-02-01T16:33:00.807430251Z [resource.labels.podName: vmalertmanager-vmalertmanager-0] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.806Z caller=opsgenie.go:139 level=debug integration=opsgenie alert="{}/{}/{}:{alertname=\"SomeName\", env=\"prod\", instance_id=\"someId\", namespace=\"monitoring\", severity=\"critical\"}"
DEFAULT 2024-02-01T16:33:00.807449912Z [resource.labels.podName: vmalertmanager-vmalertmanager-0] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.806Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{}/{env=\"prod\"}:{alertname=\"SomeName\", env=\"prod\", instance_id=\"someId\", namespace=\"monitoring\", severity=\"critical\"}" msg=flushing alerts=[SomeName[9da5035][resolved]]
DEFAULT 2024-02-01T16:33:00.808359548Z [resource.labels.podName: vmalertmanager-vmalertmanager-1] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.808Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{}/{}:{alertname=\"SomeName\", env=\"prod\", instance_id=\"someId\", namespace=\"monitoring\", severity=\"critical\"}" msg=flushing alerts=[SomeName[9da5035][resolved]]
DEFAULT 2024-02-01T16:33:00.808515452Z [resource.labels.podName: vmalertmanager-vmalertmanager-1] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.808Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{}/{env=\"prod\"}:{alertname=\"SomeName\", env=\"prod\", instance_id=\"someId\", namespace=\"monitoring\", severity=\"critical\"}" msg=flushing alerts=[SomeName[9da5035][resolved]]
DEFAULT 2024-02-01T16:33:00.826194288Z [resource.labels.podName: vmalertmanager-vmalertmanager-1] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.825Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=SomeName[9da5035][active]
DEFAULT 2024-02-01T16:33:00.826497350Z [resource.labels.podName: vmalertmanager-vmalertmanager-0] [resource.labels.containerName: alertmanager] ts=2024-02-01T16:33:00.826Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert=SomeName[9da5035][active]
```
It appears that it's receiving the alert update but then decides to flush it anyway.
The alerttmanager parameters are:
```
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 24h
```
Is this related to the group interval in some way (as it seems that it resolves at exactly 5 minutes or increments of it). Any suggestions for parameters to tune here?

**Comment by zekker6** [comment]
Hello @Homulvas 

`group_interval` defines a period to wait between sending alerts states update in a single group. You can give a read to [this article](https://www.robustperception.io/whats-the-difference-between-group_interval-group_wait-and-repeat_interval/) to get a better understanding.
This means that somewhere in between these 5 minutes alert have become "resolved" for Alertmanager and than it flushed it "resolved" state.

In order to confirm that alert is always firing on vmalert side could you check values of `ALERTS` and `ALERTS_FOR_STATE` generated by vmalert and confirm that alert state was always firing? You can also find more information about troubleshooting alert state for vmalert here - https://docs.victoriametrics.com/vmalert/#alerts-state

Could you also share the alert definition which triggers this behaviour? (with any sensitive information removed)

**Comment by zekker6** [comment]
@Homulvas I would suggest to open an issue in [Alertmanager repo](https://github.com/prometheus/alertmanager) with the details you've gathered as I can't see what can be further investigated from vmalert side and I do not have deep knowledge of Alertmanager internals to help debugging it further.

**Comment by Homulvas** [comment]
After a break I got some more information. Our `evaluationInterval` is set at `15s` and `evalDelay` is default at `30s`. Looking at vmalert code it seems that this results in `endsAt` set at `now()-evalDelay+4*evaluationInterval` which is `30s` in the future.
curl'ing `/api/v1/alerts` from alertmanager reveals that some of the alerts have their `endsAt` very close to expiration before they get updated. This is a bit hard to track as you can only look at a current snapshot but I would assume it's not that far fetched that an update doesn't arrive in time.

My question is there a good suggestion to adjust our config? It seems that with an `evaluationInterval` that is lower than default `evalDelay` becomes much more important in the automatic resolution calculation. Which one of these should we try to adjust?

**Comment by hagen1778** [comment]
Hello @Homulvas! 

>  Our evaluationInterval is set at 15s and evalDelay is default at 30s. Looking at vmalert code it seems that this results in endsAt set at now()-evalDelay+4*evaluationInterval which is 30s in the future.

It should be simply ` now()+4*evaluationInterval`. Could you point me to the code where evalDelay is subtracted? Could you please share version of your vmalert?

**Comment by Homulvas** [comment]
> It should be simply ` now()+4*evaluationInterval`. Could you point me to the code where evalDelay is subtracted? Could you please share version of your vmalert?

If I'm reading things right before https://github.com/VictoriaMetrics/VictoriaMetrics/commit/d7224b2d1cecdef881793e1675bb2f1090e1d864 happened the current timestamp was adjusted first https://github.com/VictoriaMetrics/VictoriaMetrics/blob/453988e244a174c39ccf02675169793007a63939/app/vmalert/rule/group.go#L597
We are currently running `v1.97.1` so we definitely don't have that fix yet.

**Comment by Homulvas** [comment]
> Do you consider updating to newer version of vmalert with the fix included?

I see the operator helm chart was updated today. So definitely will try to upgrade sometime soon.

**Comment by Homulvas** [comment]
The `endsAt` are now greater than it was before. Another thing that has also changed is that it's no longer rounded to the next `evaluationInterval` but I guess it's not an issue for us.
