### ISSUE TITLE
vmctl: Provide TLS configurations for import/export endpoints

### ISSUE THREAD

**Issue by khushijain21** [VictoriaMetrics/VictoriaMetrics#5748]
### Is your feature request related to a problem? Please describe

Currently, vmctl does not provide ability to configure TLS connections to import/export endpoints

### Describe the solution you'd like

Create CLI flags for various datasources vmctl supports

### Additional information

If the community feels this is a required feature I would like to contribute here. Also please do share if there are any better approaches for the same.

**Comment by khushijain21** [comment]
sure @zekker6. Could you please assign this to me tho?

**Comment by valyala** [comment]
[vmctl](https://docs.victoriametrics.com/vmctl/) gained support for TLS config options for the supported datasources starting from [v1.99.0 release](https://docs.victoriametrics.com/changelog/). The following command-line flags are responsible for these configs:

[VictoriaMetrics native protocol](https://docs.victoriametrics.com/vmctl/#migrating-data-from-victoriametrics):
* `vm-native-src-cert-file`
* `vm-native-src-key-file`
* `vm-native-src-ca-file`
* `vm-native-src-server-name`
* `vm-native-src-insecure-skip-verify`

* `vm-native-dst-cert-file`
* `vm-native-dst-key-file`
* `vm-native-dst-ca-file`
* `vm-native-dst-server-name`
* `vm-native-dst-insecure-skip-verify`

[InfluxDB protocol](https://docs.victoriametrics.com/vmctl/#migrating-data-from-influxdb-1x):
* `influx-cert-file`
* `influx-key-file`
* `influx-CA-file`
* `influx-server-name`
* `influx-insecure-skip-verify`

[OpenTSDB protocol](https://docs.victoriametrics.com/vmctl/#migrating-data-from-opentsdb):
* `otsdb-cert-file`
* `otsdb-key-file`
* `otsdb-CA-file`
* `otsdb-server-name`
* `otsdb-insecure-skip-verify`

[Prometheus remote read protocol](https://docs.victoriametrics.com/vmctl/#migrating-data-by-remote-read-protocol):
* `remote-read-cert-file`
* `remote-read-key-file`
* `remote-read-CA-file`
* `remote-read-server-name`
* `remote-read-insecure-skip-verify`

Closing the feature request as done.

**Comment by valyala** [comment]
Re-opening the feature request, since [the support for TLS configs at VictoriaMetrics native protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5824) isn't merged yet.

**Comment by hagen1778** [comment]
@khushijain21 https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5824 has been merged. Thanks for your contribution! The change will be available in the next release.

**Comment by valyala** [comment]
[`vmctl`](https://docs.victoriametrics.com/vmctl.html) supports the ability to configure TLS options for import/export endpoints in [VictoriaMetrics native protocol](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5824) starting from [v1.100.0](https://docs.victoriametrics.com/changelog/) release. The following command-line options are supported by `vmctl` now:

* `vm-native-src-cert-file`
* `vm-native-src-key-file`
* `vm-native-src-ca-file`
* `vm-native-src-server-name`

* `vm-native-dst-cert-file`
* `vm-native-dst-key-file`
* `vm-native-dst-ca-file`
* `vm-native-dst-server-name`


Closing the feature request as done.
