### ISSUE TITLE
Gaps in metrics collected from cadvisor

### ISSUE THREAD

**Issue by qiqingkai1** [VictoriaMetrics/VictoriaMetrics#5760]
### Describe the bug

When the vmagent collects advisors, the metrics always show gaps.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/0053d7c9-db44-4910-8729-aa2a871e7f36)
scrape_interval:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/f6107df6-767f-4979-a5e8-6b106aba59bc)

### To Reproduce

vmgent:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/b472819f-5b33-454e-8c25-0f39ac0175a6)
vmstorage:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/dca15fbe-e941-4c07-a043-1bd6cbc382f5)
vmselect:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/4303f954-e25a-4142-a0e3-fab743671556)
scrape_interval:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/7a12f954-4ff0-403b-971f-177d012e8712)

I have two replicas, and both VMagents will collect the same target. Therefore, it can lead to irregular scraper intervals

### Version

vmagnt:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/101e0996-266e-4889-8085-f776643b88d0)
vmstorage, vmselect, vminsert:
![B198677142063219E63EA2AC5CD8B3CF](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/139681413/ae2202fa-17a9-4f34-bca3-4069e93be709)

**Comment by qiqingkai1** [comment]
Previously, many people had raised this issue and the gap could be resolved by using the - search. minStalessInterval parameter. However, no matter how I set the parameter size, I was unable to successfully eliminate the gap



This problem has been bothering me for over a month now. I hope the official can help me take a look. Thank you here

**Comment by qiqingkai1** [comment]
Previously, many people had raised this issue and the gap could be resolved by using the - search. minStalessInterval parameter. However, no matter how I set the parameter size, I was unable to successfully eliminate the gap



This problem has been bothering me for over a month now. I hope the official can help me take a look. Thank you here

**Comment by hagen1778** [comment]
Hi @qiqingkai1! Since you mentioned cadvisor and 1.87.1 vmagent version, I think your problem is related to the following issue
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697
And specifically to this comment https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1654144380

In short, you can do two things to mitigate the issue:
1.  Ignore cadvisor timestamps by setting `honor_timestamps: false` in promscrape config for this target on vmagent side.
2. Update vmagent to 1.93 or higher. Starting from this version, vmagent ignores target's timestamps by default.

**Comment by qiqingkai1** [comment]
@hagen1778 Thanks，I have reviewed this issue and set honor_timesamples: false and - search MinStalessInterval=2m, but gaps still appear. According to the description, if search is set MinStalessInterval=2m should eliminate gaps, but obviously not. What I cannot understand is why VM's staleness detection is so radical.

**Comment by qiqingkai1** [comment]
@hagen1778 Thanks，I have reviewed this issue and set honor_timesamples: false and - search MinStalessInterval=2m, but gaps still appear. According to the description, if search is set MinStalessInterval=2m should eliminate gaps, but obviously not. What I cannot understand is why VM's staleness detection is so radical.

**Comment by qiqingkai1** [comment]
@hagen1778 The collection frequency of the cadvisor is **10** seconds, as two vmagents collect the same job. Therefore, the value of **scraper_interval** is approximately 5 seconds. What I cannot understand is that when **scraper_interval** is 12 seconds, gaps will appear. And I set **- search MinStalessInterval=2m** surprisingly cannot eliminate this gap.

**Comment by hagen1778** [comment]
> What I cannot understand is why VM's staleness detection is so radical. If I reload my collection frequency, it will cause a few minutes of gaps in the VM.

It could cause gaps only if collector reload took significant time which exceeded the scrape_interval, or if you reduce scrape_interval. Usually, vmagent restarts in matter of seconds, and scrape interval changes infrequently. 

I don't see anything radical here. Using time series history allows VM to properly caclulate staleness for scraped or pushed metrics, regardless for their resolution. 

Moreover, the fact that your experience this gaps rather highlights there is an issue. If VM just used a static staleness interval, this could be overlooked.

So first time reading the issue I missed you have 2 vmagent replicas. If it is so, then you need to change vmselect and vmstorage param -dedup.minScrapeInterval to 10s. See https://docs.victoriametrics.com/#deduplication
> The recommended value for -dedup.minScrapeInterval must equal to scrape_interval config from Prometheus configs. It is recommended to have a single scrape_interval across all the scrape targets. See [this article](https://www.robustperception.io/keep-it-simple-scrape_interval-id) for details.

**Comment by qiqingkai1** [comment]
> > What I cannot understand is why VM's staleness detection is so radical. If I reload my collection frequency, it will cause a few minutes of gaps in the VM.
> 
> It could cause gaps only if collector reload took significant time which exceeded the scrape_interval, or if you reduce scrape_interval. Usually, vmagent restarts in matter of seconds, and scrape interval changes infrequently.
> 
> I don't see anything radical here. Using time series history allows VM to properly caclulate staleness for scraped or pushed metrics, regardless for their resolution.
> 
> Moreover, the fact that your experience this gaps rather highlights there is an issue. If VM just used a static staleness interval, this could be overlooked.
> 
> So first time reading the issue I missed you have 2 vmagent replicas. If it is so, then you need to change vmselect and vmstorage param -dedup.minScrapeInterval to 10s. See https://docs.victoriametrics.com/#deduplication
> 
> > The recommended value for -dedup.minScrapeInterval must equal to scrape_interval config from Prometheus configs. It is recommended to have a single scrape_interval across all the scrape targets. See [this article](https://www.robustperception.io/keep-it-simple-scrape_interval-id) for details.
Today is the Chinese New Year, first of all, happy Chinese New Year.

I previously set **- dedup. minScrapeInterval=1ms** on vmselect, and I will set it to 10s in the future I only have one final question left, why did the setting **- search MinStalessInterval=2m** not take effect. I have looked at many issues, and most of them can eliminate gaps by setting the - search MinStalessInterval parameter. But no matter how large the value I set, I cannot eliminate gaps. I want to know why?

**Comment by qiqingkai1** [comment]
> > What I cannot understand is why VM's staleness detection is so radical. If I reload my collection frequency, it will cause a few minutes of gaps in the VM.
> 
> It could cause gaps only if collector reload took significant time which exceeded the scrape_interval, or if you reduce scrape_interval. Usually, vmagent restarts in matter of seconds, and scrape interval changes infrequently.
> 
> I don't see anything radical here. Using time series history allows VM to properly caclulate staleness for scraped or pushed metrics, regardless for their resolution.
> 
> Moreover, the fact that your experience this gaps rather highlights there is an issue. If VM just used a static staleness interval, this could be overlooked.
> 
> So first time reading the issue I missed you have 2 vmagent replicas. If it is so, then you need to change vmselect and vmstorage param -dedup.minScrapeInterval to 10s. See https://docs.victoriametrics.com/#deduplication
> 
> > The recommended value for -dedup.minScrapeInterval must equal to scrape_interval config from Prometheus configs. It is recommended to have a single scrape_interval across all the scrape targets. See [this article](https://www.robustperception.io/keep-it-simple-scrape_interval-id) for details.

Today is the Chinese New Year, first of all, happy Chinese New Year.

I previously set **- dedup. minScrapeInterval=1ms** on vmselect, and I will set it to 10s in the future I only have one final question left, why did the setting **- search MinStalessInterval=2m** not take effect. I have looked at many issues, and most of them can eliminate gaps by setting the - search MinStalessInterval parameter. But no matter how large the value I set, I cannot eliminate gaps. I want to know why?

**Comment by qiqingkai1** [comment]
> > What I cannot understand is why VM's staleness detection is so radical. If I reload my collection frequency, it will cause a few minutes of gaps in the VM.
> 
> It could cause gaps only if collector reload took significant time which exceeded the scrape_interval, or if you reduce scrape_interval. Usually, vmagent restarts in matter of seconds, and scrape interval changes infrequently.
> 
> I don't see anything radical here. Using time series history allows VM to properly caclulate staleness for scraped or pushed metrics, regardless for their resolution.
> 
> Moreover, the fact that your experience this gaps rather highlights there is an issue. If VM just used a static staleness interval, this could be overlooked.
> 
> So first time reading the issue I missed you have 2 vmagent replicas. If it is so, then you need to change vmselect and vmstorage param -dedup.minScrapeInterval to 10s. See https://docs.victoriametrics.com/#deduplication
> 
> > The recommended value for -dedup.minScrapeInterval must equal to scrape_interval config from Prometheus configs. It is recommended to have a single scrape_interval across all the scrape targets. See [this article](https://www.robustperception.io/keep-it-simple-scrape_interval-id) for details.

Today is the Chinese New Year, first of all, happy Chinese New Year.

I previously set **- dedup. minScrapeInterval=1ms** on vmselect, and I will set it to 10s in the future. I only have one final question left, why did the setting **- search MinStalessInterval=2m** not take effect. I have looked at many issues, and most of them can eliminate gaps by setting the - search MinStalessInterval parameter. But no matter how large the value I set, I cannot eliminate gaps. I want to know why?
