### ISSUE TITLE
vmui: dragging the graph with the mouse does not work

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/VictoriaMetrics#5764]
### Describe the bug

In Firefox and Safari, dragging the graph using `ctrl/cmd + mouse movement` does not work.

### To Reproduce

1) Open [vmui](https://play.victoriametrics.com) in Firefox or Safari.
2) Execute any query to display the graph.
3) Try dragging the graph using `ctrl/cmd + mouse left/right`.

It is expected that the graph will shift right/left. Instead, an area on the graph is highlighted for zooming in.

### Version

victoria-metrics: v1.96.0
firefox: v122.0
safari: v17.3

### Screenshots

<img width="600" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/29711459/d64341c0-500f-4a1b-9c61-d4595167098e"/>

**Comment by valyala** [comment]
This bug has been fixed in vmui starting from [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html).
