### ISSUE TITLE
docs: links with back-ticked text must differ from regular back-ticked text

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#5768]
### Describe the bug

https://docs.victoriametrics.com/ contains links with back-ticked text. Such links must differ from regular back-ticked text, since it is unclear whether the given back-ticked text contains a link.

### To Reproduce

1. Open https://docs.victoriametrics.com/scrape_config_examples/
2. Search for `The target address is used as` on the opened page and hover the cursor overt the next word after this text - `instance`.
3. Notice that the `instance` is a hyperlink, but it looks like a regular back-ticked text. This should be fixed

### Version

The latest one

**Comment by marshalova** [comment]
Hi! 
I suggest to always use `rgba(24, 144, 255, 1)` for all links (text, tags). 
In both modes: dark and light.

**Comment by tenmozes** [comment]
Fixed for tags which contain links
