### ISSUE TITLE
vmsingle: Inconsistent HTTP Response code for -/reload handler in vmagent and vmsingle

### ISSUE THREAD

**Issue by wasim-nihal** [VictoriaMetrics/VictoriaMetrics#5774]
### Is your feature request related to a problem? Please describe

I observed discrepancies in the behavior of the -/reload handler between vmagent and vmsingle while investigating issues related to reloading in our backend systems.

The -/reload handler in vmagent returns an HTTP 200 response code, whereas vmsingle returns an HTTP 204 response code. Considering that both handlers perform the same functionality, it seems appropriate for the response codes to be consistent across the components. Please clarify if my understanding is incorrect in this regard.

Additionally, I noticed that the landing page of vmagent (http://127.0.0.1:8429/) includes a href for -/reload to trigger a reload. However, this is missing from the landing page of vmsingle (http://127.0.0.1:8428/).

### Describe the solution you'd like

- Change response code of vmsingle's request handler for -/reload to return 200
- Add href of -/reload in vmsingle's landing page

### Additional information

If the community feels this is a required change, I would like to open a PR with the change.

**Comment by valyala** [comment]
Changes related to this feature request have been included in [v1.98.0](https://docs.victoriametrics.com/CHANGELOG.html). Closing it as fixed then.
