### ISSUE TITLE
How do you use the latency_offset query arg?

### ISSUE THREAD

**Issue by OmegaZero** [VictoriaMetrics/VictoriaMetrics#5786]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

How do you use the latency_offset query arg?  For instance I want to change it for a particular query to only be 5 seconds but if I do

`windows_cpu_time_total{latency_offset="5s"}`

it returns no data. Forgive my ignorance on how this works! :)  Thanks!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
This param can be used via http request [query arg](https://en.wikipedia.org/wiki/Query_string):
```sh
curl localhost:8428/api/v1/query -g -d 'latency_offset=5s' -d 'query=windows_cpu_time_total'
```

**Comment by OmegaZero** [comment]
But can it be used inside the query (like I had mentioned before?). Specifically, how can I use it from Grafana?
