### ISSUE TITLE
"step=0ms is out of allowed range [0 ..."

### ISSUE THREAD

**Issue by dandv** [VictoriaMetrics/VictoriaMetrics#5795]
### Describe the bug

When passing `step=0h` to a query, the following error is returned:

    "\"step\"=0ms is out of allowed range [0 ... 3153600000000]

0ms is technically not out of that range. It would be out of [the] allowed range [1 ... 3153600000000]

### To Reproduce

curl .../api/v1/query -d 'query=...' -d 'step=0h'

### Version

victoria-metrics-20240130-205929-tags-v1.97.0-0-gfcc8b14f8

### Logs

warn    VictoriaMetrics/app/vmselect/main.go:213

### Used command-line flags

-retentionPeriod=100y -search.maxPointsPerTimeseries=10000000 -search.latencyOffset=1s

**Comment by Amper** [comment]
error message will be fixed here: #5812

**Comment by hagen1778** [comment]
@dandv https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5812 has been merged! Thanks for reporting!

**Comment by valyala** [comment]
FYI, the fix for this issue has been included in [v1.93.13 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.13).

**Comment by valyala** [comment]
FYI, the fix for this issue has been included also in [v1.97.3 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.3).

**Comment by valyala** [comment]
The fix for this issue has been included in [v1.99.0 release](https://docs.victoriametrics.com/changelog/). Closing it as fixed.
