### ISSUE TITLE
Deploy victoria-metrics-k8s-stack in parallel with prometheus stack

### ISSUE THREAD

**Issue by Angel0r** [VictoriaMetrics/VictoriaMetrics#5807]
### Is your question request related to a specific component?

VictoriaMetrics, victoria-metrics-k8s-stack

### Describe the question in detail

Hey!
We are about to deploy victoria-metrics-k8s-stack in production as a replacement for prometheus-stack. Since we want to minimize downtime we are considering deploying it in the same cluster but in a different namespace.
Will I have any problem with global CRD's that are used from both? 
Should I enable Prometheus converter(`disable_prometheus_converter`) or not or it doesn't matter?

Thank you!
/Angelos

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @Angel0r.
The working principles of the prometheus converter in vmoperator are described in detail here: https://docs.victoriametrics.com/operator/migration/

> Will I have any problem with global CRD's that are used from both?

No, I don't think so, vm-operator does not change prometheus objects in any way.

> Should I enable Prometheus converter(disable_prometheus_converter) or not or it doesn't matter?

If you want to use VM as replacement for prometheus and want to use the same monitor objects, 
you need to set `disable_prometheus_converter: true`.

I think in brief the plan should be as follows:

1. Run victoria-metrics-k8s-stack
2. As a result, the vm-operator and its objects will be deployed
3. Based on the objects, the vm-operator will do the following:
    - Run required victoria metrics components
    - Based on scrape objects prometheus will generate the same VM objects
    - The vmagent will start collecting metrics and writing them to the VM instance
5. At this point prometheus and vm will be running simultaneously
6. if you need to migrate old data from pormetheus to VM, use vmctl: https://docs.victoriametrics.com/vmctl/#migrating-data-from-prometheus
7. After you make sure everything works as you need it to, you can remove prometheus (but don't remove its CRD)

**Comment by Angel0r** [comment]
Hey Amper,

Thank you so much for your elaborate answer!

/Angelos
