### ISSUE TITLE
Getting query results not corresponding to docs about implicit query conversions

### ISSUE THREAD

**Issue by Muxa1L** [VictoriaMetrics/VictoriaMetrics#5816]
### Describe the bug

When I execute the same query with [1i] and without the lookbehind window I'm receiving different results.
The [documentation](https://docs.victoriametrics.com/metricsql/#implicit-query-conversions) states that 
<details><summary>Implicit query conversions</summary>
<p>
If lookbehind window in square brackets is missing inside [rollup function](https://docs.victoriametrics.com/metricsql/#rollup-functions), then [1i] is automatically added there. The [1i] means one step value, which is passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyconcepts/#range-query). It is also known as $__interval in Grafana. For example, rate(http_requests_count) is automatically transformed to rate(http_requests_count[1i]).
</p>
</details> 
but observed results differ from this.

### To Reproduce

Get some metric, which have rare scrape time (e.g 30m)
Set in grafana 15s as min step
Then simply execute something like
default_rollup(<metrics>)
default_rollup(<metrics>[1i])
and observe different results

### Version

starting from (and including) vmselect-20221220-230852-tags-v1.85.3-cluster-0-g30b15111a and up to last version

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9287490/d9bbab32-53a6-4b8a-9e47-831e82af674a)

**Comment by valyala** [comment]
See the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3483

**Comment by valyala** [comment]
The commit 149d83e596e43d4d38a2765664cb5b0118ad99b7 updates docs accordingly to the updated logic for `rate(m)` and `default_rollup(m)` calculations starting from `v1.85.3`, which has been changed in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3483 .

The logic is the following: when lookbehind window is missing in [rollup functions](https://docs.victoriametrics.com/metricsql/#rollup-functions), then it is automatically set to the following values:

- To `step` value passed to [/api/v1/query_range](https://docs.victoriametrics.com/keyConcepts.html#range-query) or [/api/v1/query](https://docs.victoriametrics.com/keyconcepts/#instant-query) for all the [rollup functions](https://docs.victoriametrics.com/metricsql#rollup-functions) except of [default_rollup](https://docs.victoriametrics.com/metricsql#default_rollup) and [rate](https://docs.victoriametrics.com/metricsql#rate). This value is known as `$__interval` in Grafana or `1i` in MetricsQL. For example, `avg_over_time(temperature)` is automatically transformed to `avg_over_time(temperature[1i])`.
- To the `max(step, scrape_interval)`, where `scrape_interval` is the interval between [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) for [default_rollup](https://docs.victoriametrics.com/metricsql#default_rollup) and [rate](https://docs.victoriametrics.com/metricsql#rate) functions. This allows avoiding unexpected gaps on the graph when `step` is smaller than `scrape_interval`.

Closing the issue as addressed.
