### ISSUE TITLE
docs: missing anchor link for v1.97.2 release at https://docs.victoriametrics.com/changelog/

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#5818]
### Describe the bug

The 1.97.2 release is already documented at https://docs.victoriametrics.com/changelog/ , but there is no a link to it in the right-hand menu. The following link also work incorrectly - https://docs.victoriametrics.com/changelog/#v1972 - it scrolls to the middle of the description of v1.97.2 release instead of the top of the description.

### To Reproduce

Go to https://docs.victoriametrics.com/changelog/ and note missing link to the `v1.97.2` release in the right-hand menu.

### Version

The lastest commit in `master` branch.

**Comment by tenmozes** [comment]
fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7332431b9031f89a967117addfba507131e86bf1
