### ISSUE TITLE
vminsert relabelConfig configuration fails to run

### ISSUE THREAD

**Issue by whc9527** [VictoriaMetrics/VictoriaMetrics#5820]
### Is your question request related to a specific component?

vminsert

### Describe the question in detail

cluster version: 0.11.8

```
- source_labels: [__name__]
  regex: (container_blkio_device_usage_total|container_tasks_state|container_memory_failures_total|container_network_receive_packets_dropped_total|container_network_transmit_packets_dropped_total|container_network_transmit_errors_total|container_network_receive_errors_total)
  action: drop
```

After vminsert was configured with the above relabelConfig, all indicators (except the masked indicators) on vmui could not be found after the time point of vminsert restart. Later, after removing relabelConfig on vminsert side, it returned to normal. Do I have a problem with this relabelConfig?

**Comment by dmitryk-dk** [comment]
Hi @whc9527 ! This relabel config will drop all metrics with names 
```
container_blkio_device_usage_total|container_tasks_state|container_memory_failures_total|container_network_receive_packets_dropped_total|container_network_transmit_packets_dropped_total|container_network_transmit_errors_total|container_network_receive_errors_total
```
So when you add this config to your system those metrics are dropped (they are not inserted in the database). That is why you do not see those metrics

**Comment by whc9527** [comment]
@dmitryk-dk Yes, but after I added this strategy, in addition to these blocked indicators, other indicators are also invisible

**Comment by dmitryk-dk** [comment]
> @dmitryk-dk Yes, but after I added this strategy, in addition to these blocked indicators, other indicators are also invisible

Could you please share how you run your installation and where you specify relabelConfig? I want to reproduce the issue Can you check some errors into cluster components?
