### ISSUE TITLE
vmalert: avoid sending resolves notification to alertmanager

### ISSUE THREAD

**Issue by Terrynech** [VictoriaMetrics/VictoriaMetrics#5828]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

I have a type of VM alarm that repeatedly fires and becomes inactive in a short period of time, causing the alertmanager to be unable to aggregate it into one alarm and instead send out multiple alarms, resulting in an alarm storm.

Is there any way for vmalert to prohibit sending recovery notifications to alertmanager?

**Comment by hagen1778** [comment]
> Is there any way for vmalert to prohibit sending recovery notifications to alertmanager?

There is no such way and I don't see the real need for it to be.

> I have a type of VM alarm that repeatedly fires and becomes inactive in a short period of time, causing the alertmanager to be unable to aggregate it into one alarm and instead send out multiple alarms, resulting in an alarm storm.

It looks like you're having a "flappy alert". There are two ways how you can try fixing this:
1. Update your alert expression to be resilient for short periods of inactivity. For example, `memory_usage_bytes > 1Gi` could be indeed flappy, as memory usage constantly changes. But if you write `max_over_time(memory_usage_bytes[5m]) > 1Gi` then this expression will be resilient to memory usage drops on 5min interval.
2. Use `keep_firing_for` param in [alert config](https://docs.victoriametrics.com/vmalert/#alerting-rules):
>  Alert will continue firing for this long even when the alerting expression no longer has results.
 This allows you to delay alert resolution.
[ keep_firing_for: <duration> | default = 0s ]
