### ISSUE TITLE
Multiple scrape intervals

### ISSUE THREAD

**Issue by yasvanth** [VictoriaMetrics/VictoriaMetrics#5830]
### Is your question request related to a specific component?

vmstorage - enterprise
vmselect - enterprise

### Describe the question in detail

Hi Team,

I have an instance that scrapes metrics from network devices using SNMP and StreamingTelemetry at different scrape intervals, the scraped data is stored to a single vmstorage (clustered) and exported using vmselect. The VM document suggests to have the same scrape interval for all targets. Could we use the same storage and use multiple vmselect to avoid duplicate data?

Also when I restart the docker swarm nodes that run vm instances in replicas, there is a gap between the plots. 

The complete details of my setup.

VMagnet : 

> 3 instances
> Scrapes SNMP every 30s and Streaming Telemetry every 15s

VMInsets
> 3 instances

VMstroage:

> 3 instances
> de-duplication: 15s

VMselect:

> 3 instances
> de-duplication: 15s

![Screenshot 2024-02-20 at 08 45 34](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13409183/a540ad81-12ae-4d77-8bea-4013b99dc160)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Could we use the same storage and use multiple vmselect to avoid duplicate data?

You can have different vmselects with different `dedup.minScrapeInterval` setting. But it is not recommended doing so for vmstorages. Also, remember that vmstorages permanently deduplicate data.

Btw, do you actually write duplicates to the cluster?

> Also when I restart the docker swarm nodes that run vm instances in replicas, there is a gap between the plots.

Have you checked https://docs.victoriametrics.com/cluster-victoriametrics/#cluster-availability ? Does cluster behave differently in your case?

**Comment by yasvanth** [comment]
@hagen1778  Thanks for your response. I will deploy a separate stack for snmp and streaming telemetry. 
Regarding cluster availability, I have 3 replicas for all the instances (storage, select, insert), when a node is drained it should move the replicas to another probably `stop-first` should do the trick instead of `start-first`.
