### ISSUE TITLE
Cluster performance drop due to writes throttling on a single node.

### ISSUE THREAD

**Issue by just1900** [VictoriaMetrics/VictoriaMetrics#5836]
### Is your question request related to a specific component?

vmstorage

## Problem
We have 44 nodes of vmstorage, each with 2 cores and 16GB of memory, version is v1.82.1

The pod `vmstorage-9` have the issue of write throttling due to a big merge
![img_v3_0289_f26a3b44-d18a-4f64-99f8-55180526b56g](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16233178/6c19807b-d43c-4bd0-a41f-63ef87593e1c)
 
![img_v3_0289_ffce5d65-75ba-40f9-a0e7-387c2b72021g](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16233178/d4a9cb06-eacf-44e1-bb7b-20fa917271d4)

which causes data ingestion to be throttled and the persistent queue to grow on the vmagent side.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/16233178/7c9b77d0-8dda-4249-82bd-117531c829a9)

## Question
1. AFAICT, the vminsert does have the ability to reroute writes to other nodes if write is blocked. It appears that no rerouting occurred in the case mentioned above. Is this expected?
2. How can one slove the problem, say for example is it possible to control the merge via API?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by f41gh7** [comment]
If you have enough cluster capacity, you can enable rerouting at vminsert with flag `-disableRerouting=false`. 

By default, rerouting is disabled due to possible rerouting storms.

 See this issues for details
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4922
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/791

**Comment by just1900** [comment]
Thank you. After reading #791, it appears that rerouting also has limitations.
Regarding question 2, what should I do if a single node experiences write throttling? Does this indicate uneven distribution of the write load?
Currently, the only solution I can think of is to scale out the vmstorage in order to alleviate the write load on that node.

**Comment by jiekun** [comment]
I will close this one as answered.

>  what should I do if a single node experiences write throttling? Does this indicate uneven distribution of the write load?

@just1900 I think the answer is yes. And you may need to evaluate your resource usage to prevent it.
