### ISSUE TITLE
CSV export in RFC3339 format loses millisecond precision

### ISSUE THREAD

**Issue by dandv** [VictoriaMetrics/VictoriaMetrics#5837]
### Describe the bug

When [exporting in CSV format](https://docs.victoriametrics.com/#how-to-export-csv-data), using the human-readable RFC3339 time format, milliseconds are lost.

The RFC3339 standard support fractional seconds. In fact, the first example in section 5.8 of [the RFC](https://www.ietf.org/rfc/rfc3339.txt) shows a fractional timestamp.

### To Reproduce

1. Create a series with two points 100ms apart:

       curl http://localhost:8428/api/v1/import/prometheus -d 'rfcms{label="foo"} 10 1707123456700
rfcms{label="foo"} 20 1707123456800'

2. Export the series with UNIX millisecond precision

       curl http://localhost:8428/api/v1/export/csv -d 'format=__name__,__value__,__timestamp__:unix_ms' -d 'match[]=rfcms'

3. Export the series in RFC3339 format

       curl http://localhost:8428/api/v1/export/csv -d 'format=__name__,__value__,__timestamp__:rfc3339' -d 'match[]=rfcms'

Notice the identical timesmps:

> rfcms,10,2024-02-05T02:57:36-xx:yy
> rfcms,20,2024-02-05T02:57:36-xx:yy

### Version

victoria-metrics-20240130-205929-tags-v1.97.0-0-gfcc8b14f8

**Comment by f41gh7** [comment]
Hello, it's possible to define custom layout:

```
curl http://localhost:8428/api/v1/export/csv -d 'format=__name__,__value__,__timestamp__:custom:2006-01-02T15:04:05.999Z07:00' -d 'match[]=rfcms'
```

I think, we should alter current behavior and return millis fraction as minimal supported precision for timestamps.

**Comment by hagen1778** [comment]
Thanks for reporting @dandv!
Looks like [golang's rfc3339](https://pkg.go.dev/time#pkg-constants) format has seconds precision. With merge of  https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5853 export in CSV format will respect milliseconds when rfc3339 is specified.

**Comment by dandv** [comment]
How can the time be output in UTC (as Influx does)?

I tried,
* `TZ=UTC curl -s http://localhost:8428/api/v1/export/csv -d 'format=__timestamp__:rfc3339,__value__' -d 'match[]={...}'` but that still outputs times in the local timezone, e.g. `2024-06-19T10:03:15-04:00`
* `curl -s http://localhost:8428/api/v1/export/csv -d 'format=__timestamp__:2006-01-02T15:04:05,__value__' -d 'match[]={...}'` but that still outputs `Unsupported timeFormat=2006-01-02T15:04:05`
* `curl -s http://localhost:8428/api/v1/export/csv -d 'format=__timestamp__:2006-01-02T15:04:05z,__value__' -d 'match[]={...}'` - same, `Unsupported timeFormat=2006-01-02T15:04:05z`
* Same for format=__timestamp__: `2006-01-02T15:04:05Z`, `2006-01-02T15:04:05z07:00`, `2006-01-02T15:04:05Z07:00`, `2006-01-02T15:04:05z07`, `2006-01-02T15:04:05Z07`
