### ISSUE TITLE
vmalert: support multiple notification urls

### ISSUE THREAD

**Issue by datamuc** [VictoriaMetrics/VictoriaMetrics#584]
**Is your feature request related to a problem? Please describe.**

We are running alertmanager as a cluster, in this case the client must send the alerts to all alertmanagers in the cluster in parallel.

Here is the relevant prometheus documentation:
https://github.com/prometheus/alertmanager#high-availability

But vmalert can currently only handle one notification.Url.

**Describe the solution you'd like**

For example if vmalert can handle the notification.Url option multiple times would solve that for me. Of course vmalert must send the alerts to all supplied urls.

**Comment by valyala** [comment]
Support for multiple notifier urls has been added in [v1.37.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.
