### ISSUE TITLE
[vmselect] Query results are empty when the query time is between 01-31 00:00 - 01-31 23:59, but data exists for 01-31 when the query time is between 01-31 00:00 - 02-01 23:59

### ISSUE THREAD

**Issue by Buddruggy** [VictoriaMetrics/VictoriaMetrics#5840]
### Describe the bug

Query results are empty when the query time is between 01-31 00:00 - 01-31 23:59, but data exists for 01-31 when the query time is between 01-31 00:00 - 02-01 23:59

### To Reproduce

1. Query with a time range of 01-31 00:00 - 01-31 23:59
<img width="2549" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/32037815/6b48c270-fdcc-41a3-8acf-59cf9877b295">
2. Query with a time range of 01-31 00:00 - 02-01 23:59
<img width="2539" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/32037815/de01bca5-7018-4f29-a1ad-9e7d5e0148da">

### Version

vmselect-prod --version
vmselect-20230728-102546-tags-v1.92.1-cluster-0-gc5c539f97

**Comment by f41gh7** [comment]
Hello, it looks like an issue with index records search. It may be related to this issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4972.

First of all, I'd recommend to upgrade for v1.97.1 release as the lastest LTS version.

Second, can you provide at trace out for the query, that doesn't return any result?

**Comment by Buddruggy** [comment]
> Hello, it looks like an issue with index records search. It may be related to this issue #4972.
> 
> First of all, I'd recommend to upgrade for v1.97.1 release as the lastest LTS version.
> 
> Second, can you provide at trace out for the query, that doesn't return any result?

OK, I will upgrade cluster later.

**Comment by Buddruggy** [comment]
[no_result_trace.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/14368229/no_result_trace.json)
 
This is empty result trace.

**Comment by Buddruggy** [comment]
[normal_result_trace.json](https://github.com/VictoriaMetrics/VictoriaMetrics/files/14368246/normal_result_trace.json)

This is normal result trace.

**Comment by f41gh7** [comment]
Thanks for the traces!

 It looks like, indexdb entries are missing at vmstorage nodes, one record exists only at previous indexdb. 

 Most likely, it caused by rollback from 1.91+ version to the any previous version. 

 See this comment for details https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4972#issuecomment-1720977747

**Comment by Buddruggy** [comment]
> Hello, it looks like an issue with index records search. It may be related to this issue #4972.
> 
> First of all, I'd recommend to upgrade for v1.97.1 release as the lastest LTS version.
> 
> Second, can you provide at trace out for the query, that doesn't return any result?

Hi, I upgraded cluster version to 1.97.1, but this problem still exist.

**Comment by hagen1778** [comment]
@f41gh7 do you think the data loss is permanent?

**Comment by f41gh7** [comment]
It's better to assume that those data loss is permanent. 


There is a workaround for it https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4972#issuecomment-1731240476

But I don't recommend it.
