### ISSUE TITLE
Add count_values_over_time function

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#5847]
### Is your feature request related to a problem? Please describe

That would be awesome to have count values over time function
it should return the number of distinct values over time 

### Describe the solution you'd like

for example, for set if [1,2,3,4,4,4] and metric name foo it can return

count_values_over_time(foo, "bar"}[10m])

- foo{"bar"="1} 1 
- foo{"bar"="2} 1 
- foo{"bar"="3} 1 
- foo{"bar"="4} 3

**Comment by valyala** [comment]
The [count_values_over_time](https://docs.victoriametrics.com/MetricsQL.html#count_values_over_time) function has been added in the commit f7c3dee1c3808ea298fa3ff621069432e0717d83 . This commit will be included in the next release. In the mean time it is possible to test this functionality by building VictoriaMetrics from this commit according to [these docs](https://docs.victoriametrics.com/#how-to-build-from-sources) and checking the `count_values_over_time` MetricsQL function there.

**Comment by valyala** [comment]
[`count_values_over_time`](https://docs.victoriametrics.com/MetricsQL.html#count_values_over_time) function has been added in [VictoriaMetrics v1.99.0 release](https://docs.victoriametrics.com/changelog/). Closing the feature request as done.
