### ISSUE TITLE
vmalert - add basicAuth option to notifier.alertmanager.url for external alertmanager

### ISSUE THREAD

**Issue by ssh2n** [VictoriaMetrics/VictoriaMetrics#585]
**Is your feature request related to a problem? Please describe.**
No, ...just cosmetics 

**Describe the solution you'd like**
options/flags for that
for k8s / helm maybe the option to pull the passwd from secret

**Describe alternatives you've considered**
workarround:
you can put the basicAuth credentials in the url like http://usr:passwd@url-to-your-doma.in

**Additional context**
should I open an additional issue on "helm-charts" for the mentioned improvements?

**Comment by hagen1778** [comment]
Hi @ssh2n! Missing flags were added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/590 and available in https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.37.4 now. Closing this issue as done.
