### ISSUE TITLE
Difference in PVC volume data after migration from vmsingle to vmcluster

### ISSUE THREAD

**Issue by shivtej-opsverse** [VictoriaMetrics/VictoriaMetrics#5856]
### Is your question request related to a specific component?

vmctl

### Describe the question in detail

I migrated 4 months of metrics data from from a vmsingle which has around 12 months of metric data (close to 4.8 TB of data attached the output of same below)
```
➜  ~ kubectl exec --tty --stdin vmsingle-podname -- df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  45.0G     19.1G     26.0G  42% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.7G         0     15.7G   0% /sys/fs/cgroup
/dev/sdh                  6.2T      4.8T      1.4T  77% /victoria-metrics-data
/dev/sda1                45.0G     19.1G     26.0G  42% /etc/hosts
/dev/sda1                45.0G     19.1G     26.0G  42% /dev/termination-log
/dev/sda1                45.0G     19.1G     26.0G  42% /etc/hostname
/dev/sda1                45.0G     19.1G     26.0G  42% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    27.7G     12.0K     27.7G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.7G         0     15.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    15.7G         0     15.7G   0% /proc/scsi
tmpfs                    15.7G         0     15.7G   0% /sys/firmware
```

The migration seems to be successful without any error logs. We anticipate roughly uniform migration ingestion for 12 months in the vmsingle instance we have. Hence we expect the metric data of 4 months which was migrated to be atleast  `1 TB`

But when we see the PVC in vmstorage  only around `221 Gigs` of space is use (attaching results for reference)

```
➜  ~ kubectl exec --tty --stdin vmstorage-pod-name -- df -h            
Filesystem                Size      Used Available Use% Mounted on
overlay                  45.0G     19.4G     25.6G  43% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.7G         0     15.7G   0% /sys/fs/cgroup
/dev/sdg                  2.9T    221.7G      2.7T   8% /vm-data
/dev/sda1                45.0G     19.4G     25.6G  43% /etc/hosts
/dev/sda1                45.0G     19.4G     25.6G  43% /dev/termination-log
/dev/sda1                45.0G     19.4G     25.6G  43% /etc/hostname
/dev/sda1                45.0G     19.4G     25.6G  43% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.5G     12.0K      1.5G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.7G         0     15.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    15.7G         0     15.7G   0% /proc/scsi
tmpfs                    15.7G         0     15.7G   0% /sys/firmware
```

I am confused about this massive difference in the PVC volumes.

Can anyone explain the reason for this difference?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @shivtej-opsverse, could you clarify the following:
- how many vmstorage nodes are used for the cluster setup?
  Note that data will be evenly distributed across all storage nodes, so it is possible that disk usage on a single storage node can be around 200G in case there are 8 vmstorage nodes used: `4.8Tb / 3 = 1.6Tb` data for 4 month, `1.6Tb / 200G = 8`. 
- what is the value of `-retentionPeriod` flag used at vmstorage nodes?

**Comment by shivtej-opsverse** [comment]
Hey there are 2 vm-storage nodes. Even if we add both the pvc volume data it doesn't add up. Attaching the output below.
```
➜  ~ kubectl exec --tty --stdin vmstorage-opsverse-two-observe-backend-1 -- df -h              
Filesystem                Size      Used Available Use% Mounted on
overlay                  45.0G     19.3G     25.8G  43% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    15.7G         0     15.7G   0% /sys/fs/cgroup
/dev/sdg                  2.9T    221.7G      2.7T   8% /vm-data
/dev/sda1                45.0G     19.3G     25.8G  43% /etc/hosts
/dev/sda1                45.0G     19.3G     25.8G  43% /dev/termination-log
/dev/sda1                45.0G     19.3G     25.8G  43% /etc/hostname
/dev/sda1                45.0G     19.3G     25.8G  43% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.5G     12.0K      1.5G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                    15.7G         0     15.7G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    15.7G         0     15.7G   0% /proc/scsi
tmpfs                    15.7G         0     15.7G   0% /sys/firmware

➜  ~ kubectl exec --tty --stdin vmstorage-opsverse-two-observe-backend-0 -- df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  25.4G      8.9G     16.4G  35% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     7.8G         0      7.8G   0% /sys/fs/cgroup
/dev/sde                  2.9T    221.7G      2.7T   8% /vm-data
/dev/sda1                25.4G      8.9G     16.4G  35% /etc/hosts
/dev/sda1                25.4G      8.9G     16.4G  35% /dev/termination-log
/dev/sda1                25.4G      8.9G     16.4G  35% /etc/hostname
/dev/sda1                25.4G      8.9G     16.4G  35% /etc/resolv.conf
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.5G     12.0K      1.5G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     7.8G         0      7.8G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                     7.8G         0      7.8G   0% /proc/scsi
tmpfs                     7.8G         0      7.8G   0% /sys/firmware

```



> what is the value of -retentionPeriod flag used at vmstorage nodes?

the retention period is `6`
 

>  what is the value of -replicationFactor flag used at vminsert nodes?

replicationFactor = 1

**Comment by zekker6** [comment]
@shivtej-opsverse If you have [monitoring](https://docs.victoriametrics.com/single-server-victoriametrics/#monitoring) for the source vmsingle in place could you please share the result of the following queries?
- `sum(vm_data_size_bytes{type=~"indexdb.*"}) by(job, instance)`
- `sum(vm_data_size_bytes{type=~"storage.*"}) by(job, instance)`

This will allow to the distribution of disk usage between IndexDB and samples storage itself. 

Such large disk usage reduction can be caused by the fact that source vmsingle stored metrics with [high cardinality](https://docs.victoriametrics.com/faq/#what-is-high-cardinality). This will cause IndexDB grow much faster and use much more disk space.
After migration IndexDB is populated from by using only relevant samples which can significantly reduce amount of storage required for new IndexDB.

**Comment by shivtej-opsverse** [comment]
@zekker6, Sure here is the data requested

> sum(vm_data_size_bytes{type=~"indexdb.*"}) by(job, instance)

<img width="1424" alt="1index" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/98976553/54619dab-b69b-4762-9dbd-2fd13b9bb3dc">


> sum(vm_data_size_bytes{type=~"storage.*"}) by(job, instance)

<img width="1424" alt="Screenshot 2024-02-27 at 10 28 41 PM" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/98976553/dff14542-73f3-4b68-b724-64976db865ec">

**Comment by zekker6** [comment]
@shivtej-opsverse These metrics show that there is 1.2Tb of data used by storage and around 60Gb for index. This means that if there is data migrated for 4 mounts out of 12 total it should be(1/3 of data split across 2 storage nodes): `1200 / 3 / 2 = 200` so this matches the real data size on disk. 

Could you try following [this troubleshooting guide](https://docs.victoriametrics.com/troubleshooting/#too-much-disk-space-used) to understand why 4.8Tb of disk space is used for old Single Node installation?

**Comment by jiekun** [comment]
Close due to inactivity.
