### ISSUE TITLE
vmbackupmanager should check health status of the vmstorage

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#5859]
### Is your feature request related to a problem? Please describe

In some cases, when vmstorages has a lot of data, it can start later than vmbackupmanager pod. This may lead to many restarts for vmbackupmnager pod if it starts with the flag `runOnStart`. 
Here is the log message when it happens
```
{"ts":"2024-02-22T07:19:58.790Z","level":"fatal","caller":"VictoriaMetrics/app/vmbackupmanager/main.go:348","msg":"error creating backup: error creating snapshot: Post \"http://localhost:8482/snapshot/create\": dial tcp 127.0.0.1:8482: connect: connection refused"}
```

### Describe the solution you'd like

The vmbackaupmanager should check the vmstorage pod's health and create a snapshot only when vmstorage is healthy.

**Comment by valyala** [comment]
[vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html) waits for up to 30 seconds before requesting a snapshot from VictoriaMetrics if it is temporarily unavailable, starting from the [release v1.99.0](https://docs.victoriametrics.com/changelog/). Closing the feature request as done.
