### ISSUE TITLE
docs: vmstorage API docs in k8s operator seem to contain typos in component name

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#5865]
### Describe the bug

The vmstorage related doc [here](https://docs.victoriametrics.com/operator/api/#vmstorage) contains many mentions of vmselect, which is likely a typo after doc generation. Would be great to get it fixed and check other components as well.

### To Reproduce

See this [doc](https://docs.victoriametrics.com/operator/api/#vmstorage) and look for `vmselect` mentions.

**Comment by hagen1778** [comment]
cc @Haleygo @Amper

**Comment by Haleygo** [comment]
Fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6022.
