### ISSUE TITLE
vmui: do not trigger auto-suggestion after whitespace char

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#5866]
### Describe the bug

Currently [vmui](https://docs.victoriametrics.com/#vmui) incorrectly triggers auto-suggestion after any whitespace char in the following cases:

- `some_metric<whitespace>`. The auto-suggestion shouldn't be triggered in this context, since the resulting query after selecting some value from the auto-suggestion list will become incorrect: `some_metric<whitespace>another_metric`.
- `some_metric{some_label<whitespace>`
- `some_metric{some_label=~"some_value<whitespace>`
- `some_metric{some_label="value"}<whitespace>`

The auto-suggestion should continue triggering after whitespace char if any of `)`, `,` `+`, `-`, `*`, `/` or `^` chars or any of the following strings - (`or`, `and`, `unless`, `default`, `if`, `ifnot`, `group_left`, `group_right`) - are located in front of the whitespace. For example, `some_metric+<whitespace>` or `some_metric{some_label="some_value",<whitespace>` or `some_metric + on(foo)<whitespace>` or `(some_metric,<whitespace>`.

### To Reproduce

Open https://play.victoriametrics.com/ and enter queries above

### Version

The latest commit in master branch.

**Comment by hagen1778** [comment]
@valyala @Loori-R looks like at least 3 fixes related to this issue were included into [v.100.0](https://docs.victoriametrics.com/changelog/#v11000) release. Do you think we can close this issue or is there something left unfinished?

**Comment by valyala** [comment]
@Loori-R , thanks for the fixes! Could you also handle the following issues?

- Auto-completion mustn't be triggered after `"`, `'` and backtick char. For example, `up{job="analytic-exporter"<cursor_here>`
- Auto-completion for metric name must be triggered after `or`, `and`, `unless`, `default`, `if`, `ifnot`, `group_left` and `group_right` tokens written in any case followed by whitespace. For example, `up OR <cursor_here>` or `up And v<cursor_here>`.
- Auto-completion from label names (they are obtained from [`/api/v1/labels`](https://docs.victoriametrics.com/url-examples/#apiv1labels)) must be triggered after `(` char if there is `by`, `without`, `on` and `ignoring` word in any case in front of this char. There may be a whitespace between the word and the `(` char. For example, `sum(up) by (<cursor_here>` or `avg WithOut(<cursor_here>`. Note that the chosen label name must be put as is without putting it in quotes. For example, `sum(up) by(job)`.
- It would be great triggering auto-completion for label names after `,` char if it is located after `(` char after the words mentioned in the previous case. For example, `sum(up) by (job,<cursor_here>` or `sum(up) by (job, instance, <cursor_here`.

**Comment by valyala** [comment]
@Loori-R , are there any updates on [these comments](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5866#issuecomment-2065273421) and [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6153)?

**Comment by Loori-R** [comment]
@valyala there are no updates at the moment; I've just started working on this issue.

**Comment by hagen1778** [comment]
hey @valyala 

> Auto-completion for metric name must be triggered just after +, -, /, * and ^ chars even if there is no whitespace after these chars. For example, up+<cursor_here>
> Auto-completion for metric name must be triggered after or, and, unless, default, if, ifnot, group_left and group_right tokens written in any case followed by whitespace. For example, up OR <cursor_here> or up And v<cursor_here>.

but what's the point in triggering autocompletion if there were no user input yet?

**Comment by hagen1778** [comment]
Hey @Loori-R @valyala is this issue still relevant?

**Comment by valyala** [comment]
> but what's the point in triggering autocompletion if there were no user input yet? Should it trigger if user typed at least one character, so autocomplete got at least something to filter by?

The point is that this simplifies editing the query. For example, when you edit `a + b` query and the cursor is located at `a + <cursor_here>b`, then I'd like to see all the possible metric names, which could be used for replacing the `b` metric name in this context. I'm not sure this type of suggestion works good when the auto-complete pop-up appears automatically, but this type of suggestion is very useful when the pop-up appears after pressing `ctrl+space`. Probably, it is time to disallow automatic popup and leaving only on-demand popup with suggestions relevant for the current cursor position after pressing `ctrl+space`?

> Hey @Loori-R @valyala is this issue still relevant?

There are a few bugs with incorrect auto-suggestion, which should be narrowed down, reported and fixed then. Let's close this issue and hunt the remaining bugs in separate issues.
