### ISSUE TITLE
VictoriaMetrics, and related components, should be cgroup aware

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/VictoriaMetrics#5867]
### Describe the bug

It doesn't appear that VictoriaMetrics or its related components (vmagent, etc.) are cgroup aware, because [Go is not cgroup aware](https://github.com/golang/go/issues/33803). This means the applications are prone to throttling and degraded performance in containers environments with CPU limits.

[automaxprocs](https://github.com/uber-go/automaxprocs) can use cgroups automatically.

### To Reproduce

Run VictoriaMetrics, or the agent, on a Kubernetes node with a lot of threads and limit the container to just 1 cpu. Observe the application throttle under normal workloads.

### Version

v1.98.0

### Screenshots

The below screenshots are split into two parts. The first part is with a 13600k (20 threads), and the second with an EPYC 7763 (128 threads). The agent clearly shows an increased throttle rate, about 90ms instead of 15ms on average. The single victoria metrics node initially showed a dramatic increase in CPU throttling, but I gave it an extra CPU and it seems to have cleared (not that it means this is not an issue).

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/b03994fa-b746-4521-8625-d921b1e837f4)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/3424c64e-8814-4cc7-aeaa-002e361731ab)

### Additional information

The use of [automaxprocs](https://github.com/uber-go/automaxprocs) to use Linux container CPU quotas has been mentioned before.

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/685#issuecomment-672070638

**Comment by zekker6** [comment]
Hello @uhthomas, VictoriaMetrics does not rely only on default `GOMAXPROCS` value and sets it based on cgroups configuration. Please, take a look at [`cgroup` package](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/9f94c295ab4b87696c8574488213cb1a340ef32d/lib/cgroup), more specifically this part of code does update `GOMAXPROCS` based on cgrups limits:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9f94c295ab4b87696c8574488213cb1a340ef32d/lib/cgroup/cpu.go#L20-L63

**Comment by uhthomas** [comment]
> Hello @uhthomas, VictoriaMetrics does not rely only on default `GOMAXPROCS` value and sets it based on cgroups configuration. Please, take a look at [`cgroup` package](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/9f94c295ab4b87696c8574488213cb1a340ef32d/lib/cgroup), more specifically this part of code does update `GOMAXPROCS` based on cgrups limits:
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9f94c295ab4b87696c8574488213cb1a340ef32d/lib/cgroup/cpu.go#L20-L63

I was not aware of this, thank you so much. VM in general admittedly does not throttle nearly as badly as other applications, so I wonder if this is just because of the lower single thread performance? Is there anyway to observe the calculated value of GOMAXPROCS?

**Comment by zekker6** [comment]
> I was not aware of this, thank you so much. VM in general admittedly does not throttle nearly as badly as other applications, so I wonder if this is just because of the lower single thread performance?

Most likely it is related to the fact that there is a `GOMAXPROCS` adjustment in place, plus processes which are executed concurrently are using value of `GOMAXPROCS` to limit amount of concurrently running goroutines. This helps to avoid CPU throttling while optimizing the performance.

> Is there anyway to observe the calculated value of GOMAXPROCS?

It is exposed as `go_gomaxprocs` in VictoriaMetrics' metrics.

**Comment by uhthomas** [comment]
Looks good, sorry for the trouble.

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/97459e92-b43b-42e6-aceb-729b50e8d12f)
