### ISSUE TITLE
vmsingle dashboard should allow all instances to be selected

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/VictoriaMetrics#5869]
### Describe the bug

The [vmsingle dashboard](https://grafana.com/grafana/dashboards/10229-victoriametrics-single-node/) only allows once instance to be selected at a time. This is problematic when the pod is recreated as it will be assigned a new IP address and considered as a new instance. This essentially means all pod restarts reset the metrics for the dashboard - which is not helpful. A simple fix would be to allow all instances to be selected, rather than just one.

Current:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/b063b7d9-c908-45fe-8776-94f4c6396e8d)

With change to 'instance' variable:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/9749173/b1be6686-2328-4708-ba6f-141ccc23c9ae)

### To Reproduce

Observe the [vmsingle dashboard](https://grafana.com/grafana/dashboards/10229-victoriametrics-single-node/) does not show data for pods when they are restarted.

### Version

N/A

### Logs

N/A

### Screenshots

N/A

### Used command-line flags

N/A

### Additional information

N/A

**Comment by hagen1778** [comment]
It is possible to select multiple VM instance on Single-Server dashboard. You can find the updated version at https://grafana.com/orgs/victoriametrics/dashboards or https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/dashboards.
