### ISSUE TITLE
frequent "has a timestamp older than"

### ISSUE THREAD

**Issue by fchelinski** [VictoriaMetrics/VictoriaMetrics#5873]
### Is your question request related to a specific component?

vmagent, vmsingle-persistent

### Describe the question in detail

Hi, lately i have problem that i get alerts about kubeapi, kubelet and nginx-ingress disappearing from target directory. I did some digging and found in vmsingle-persistent warnings eg. `has a timestamp older than -search.cacheTimestampOffset=5m0s by 789.266s`. If i restart vmagent problem stops for while. 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @fchelinski 
This warning is triggered whenever a sample with timestamp older than `5m0s` is pushed to VictoriaMetrics.
Usually, this is caused either by backfilling the data or in case data ingestion pipeline can't keep up and buffers data for too long. Could you try to follow [this troubleshooting guide](https://docs.victoriametrics.com/troubleshooting/#slow-data-ingestion) to ensure that the latter is not the case?

**Comment by jiekun** [comment]
Close due to inactivity.
