### ISSUE TITLE
grafana query VictoriaMetrics error too long 

### ISSUE THREAD

**Issue by lvbaiquan12** [VictoriaMetrics/VictoriaMetrics#5875]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

Hi, lately i have problem that an error occurred while granfana querying vmselect.How to fix it

422: too long query; got 27614 bytes; mustn't exceed `-search.maxQueryLen=16384` bytes

 too long query; got 27574 bytes; mustn't exceed `-search.maxQueryLen=16384` bytes

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @lvbaiquan12 
You need to adjust value of `search.maxQueryLen` command-line flag to be at least `27614` or higher.
This error is caused by sending too long MetricsQL query to vmselect. If this happens frequently it might also make sense to check the query in Grafana to make it shorter.
