### ISSUE TITLE
v1.93 providing inconsistent result for sort() query

### ISSUE THREAD

**Issue by sachinjangle** [VictoriaMetrics/VictoriaMetrics#5896]
### Describe the bug

I am using Grafana with VictoriaMetrics (VM). I was using VM v1.48 and everything was working fine. Then I upgraded to latest version of VM i.e. v1.93 and after upgrade `sort()` API giving inconsistent result which was working correctly in v1.48.

API - `sort(scoring_cro{ data-points }[30s])`

I also had tested without Grafana and found out above VictoriaMetrics API itself is giving inconsistent result. So posting bug here. Please let me know if more information is required.

### To Reproduce

Add data in VictoriaMetrics and run query - `sort(scoring_cro{ data-points }[30s])`. Sometimes it gives result and sometimes empty array.

### Version

1.93

**Comment by hagen1778** [comment]
Hello @sachinjangle! 
Are using the latest LTS version of 1.93? If not, I'd recommend swithcing to the latest upstream or LTS release and try again.

I wasn't able to reproduce the described behavior. Can you reproduce it on our [public environment](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=sort%28vl_http_requests_total%5B1m%5D%29&g0.range_input=30m&g0.end_input=2024-03-01T08%3A17%3A00&g0.tab=1&g0.relative_time=last_30_minutes)?

**Comment by sachinjangle** [comment]
@hagen1778 Found out the bug. It was related to query I was using. I was using [30s] which was working fine with 1.48 but not with latest v1.93. Now updated to [1m] and query is working correctly. I got idea from you query only which was there in public environment. Thank you so much for your help!!!
