### ISSUE TITLE
grafana: autocomplete query fails with "unparsed data" error

### ISSUE THREAD

**Issue by mheffner** [VictoriaMetrics/VictoriaMetrics#5904]
### Describe the bug

When using Grafana 9.4 connected to Victoria Metrics via the Prometheus data source, I often receive errors when autocompleting metrics in the panel editor. If I look at the VM logs, I see errors from parsing the request to `/prometheus/api/v1/label/__name__/values`. Grafana appears to send an empty element in the list of labels that trips up VM.

This seems like it could also be a bug in what Grafana is sending as a query. However, is Prom more accepting of empty label elements? I wonder if VM should relax its parsing requirements here.

### To Reproduce

1. Go to a dashboard in Grafana 9.4 (in this case, AWS Managed Grafana)
2. Duplicate a panel that has some label filters (e.g, `env=staging` + `organization_id=12345`)
3. On the new panel, attempt to search for a new metric name.
4. See errors pop up in Grafana due to parsing errors
5. To search metric names: delete the label filters in the panel, find the metric name, re-add label filters.

### Version

```victoria-metrics-20240214-141427-tags-v1.98.0-0-gbaaa88001```

### Logs

```
2024-03-01T15:39:00.657Z	warn	VictoriaMetrics/app/vmselect/main.go:190	error in "/prometheus/api/v1/label/__name__/values?end=1709307541&match%5B%5D=%7B__name__%3D~%22.%2Asource_in.%2A%22%2Cenv%3D%22staging%22%2C%2Corganization_id%3D%2212345%22%7D&start=1709303941": cannot parse matches[]={__name__=~".*source_in.*",env="staging",,organization_id="12345"}: labelFilterExpr: unexpected token ","; want "ident"; unparsed data: ",organization_id=\"12345\"}"
```

Notice the empty element in the query list between `env` and `organization_id`:
```
ng",,org
```

**Comment by hagen1778** [comment]
Hello @mheffner! It still looks like Grafana issue to me. The query in the error message will fail in both: Prom and VM
1. [Example in Prom](http://demo.robustperception.io:9090/graph?g0.expr=%7B__name__%3D~%22.*source_in.*%22%2Cenv%3D%22staging%22%2C%2Corganization_id%3D%2212345%22%7D&g0.tab=1&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h)
2. [Example in VM](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=%7B__name__%3D%7E%22.*source_in.*%22%2Cenv%3D%22staging%22%2C%2Corganization_id%3D%2212345%22%7D&g0.range_input=30m&g0.end_input=2024-03-18T17%3A20%3A27&g0.tab=0&g0.relative_time=last_30_minutes)

**Comment by hagen1778** [comment]
Btw, how do you set `organization_id`? Is it extra_label in datasource setting or some filter on the dashboard?

**Comment by mheffner** [comment]
> Btw, how do you set `organization_id`? Is it extra_label in datasource setting or some filter on the dashboard?

It's a label filter on the panel query. In my case it's using dashboard variables, but I think it happened on static values too.

**Comment by hagen1778** [comment]
I see. Just to want make sure that `{__name__=~".*source_in.*",env="staging",,organization_id="12345"}` is actually what Grafana sends. If it is the actual query (I think you can check it via Network tab in browser), then this is bug in Grafana.
If it sends something like `?match[]={__name__=~".*source_in.*",env="staging",}&extra_label=organization_id="12345"` and VictoriaMetrics incorrectly merges extra_label into the query - then bug is on VM side.

**Comment by mheffner** [comment]
> Just to want make sure that `{__name__=~".*source_in.*",env="staging",,organization_id="12345"}` is actually what Grafana sends. If it is the actual query (I think you can check it via Network tab in browser), then this is bug in Grafana.

@hagen1778 Yeah, it does look like this is a bug on Grafana's side. I looked further and it appears that the version 9.4.x on AWS Managed Grafana must be impacted, but if I test on the Grafana Playground version 11.x.x it doesn't seem to behave the same.

I'll close this since it seems Prom and VM behave the same with respect to the bug on Grafana's side.

**Comment by mheffner** [comment]
Closing since this is not a VM issue.
