### ISSUE TITLE
Query metrics as table will return all series

### ISSUE THREAD

**Issue by kevinmatthe** [VictoriaMetrics/VictoriaMetrics#5909]
### Describe the bug

Querying metrics with type `table` will fail in large series.

### To Reproduce

Using grafana `table` or prometheus `table` to query a metric like qbittorrent_torrent_info, only the `ExecutionTime`(mostly latest) data will be calculated and return(which is always fast).

However, after switching datasource to victoriaMetrics, grafana `table` panel will still display latest metric but victoria tried to return all series during time range. When series become large, this will throw an error:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/36391318/a78f5336-a742-463a-ac98-3c17ee4810e7)

```
search error after reading 0 data blocks: error when searching for tagFilters=[{__name__="qbittorrent_torrent_info",instance="qbit_exporter:17871"}] on the time range [2024-03-02T21:52:24.604Z..2024-03-02T22:02:24.604Z]: error when searching for metricIDs in the current indexdb: the number of matching timeseries exceeds 300000; either narrow down the search or increase -search.max* command-line flag values at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits
```

At the same time, using prometheus webui to query `graph` will be slow, but `table` is really quick.

It seems like the behavior between prometheus and victoriaMetrics in table querying is completely different.

### Version

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/36391318/bcde0f6b-7ad7-42f5-8e0c-1af6003ff9bb)
victoria-metrics-20240301-013626-tags-v1.99.0-0-g9cd4b0537

### Logs

Grafana simply throws error from VictoriaMetrics.

VictoriaMetrics Webui throws the same error.

### Used command-line flags

none

**Comment by f41gh7** [comment]
VictoriaMetrics and prometheus uses the same API calls for table and graph requests. It's `/api/v1/query` and `/api/v1/query_range`. 

 An error already has an explanation how to fix it - increase value for corresponding flag ( i believe it's search.maxUniqueTimeseries).  And additional CPU may be required to reduce latency for those requests.

 I assume, you have a metric with high cardinality. Which needs extra resources for request processing.  I'd recommend to check the following doc with troubleshooting section https://docs.victoriametrics.com/troubleshooting/#slow-queries

**Comment by kevinmatthe** [comment]
> VictoriaMetrics and prometheus uses the same API calls for table and graph requests. It's `/api/v1/query` and `/api/v1/query_range`.
> 
> An error already has an explanation how to fix it - increase value for corresponding flag ( i believe it's search.maxUniqueTimeseries). And additional CPU may be required to reduce latency for those requests.
> 
> I assume, you have a metric with high cardinality. Which needs extra resources for request processing. I'd recommend to check the following doc with troubleshooting section [docs.victoriametrics.com/troubleshooting/#slow-queries](https://docs.victoriametrics.com/troubleshooting/#slow-queries)

Sorry for marking it as a bug, but is it expected to show such error when query "latest" metrics? Since the number at "Execution time" doesn't meet the limit of search.maxUniqueTimeseries, in fact there's only like 20 series at that moment(or second I assume), should this Limit be checked using `time_range series number` or `execution_time series number` when query metrics as a table?
