### ISSUE TITLE
vmselect fetches merged data from Multi-level cluster 

### ISSUE THREAD

**Issue by evanzhang87** [VictoriaMetrics/VictoriaMetrics#5913]
### Is your feature request related to a problem? Please describe

When I fetch metrics from Multi-level cluster, top-level `vmselect` will fetch raw data from second-level `vmselect`, and merge data in top-level `vmselect`, it will spend a lot of network traffic.

### Describe the solution you'd like

I want to fetch merged data from second-level `vmselect`, and merge twice in top-level `vmselect`.

**Comment by Haleygo** [comment]
Hello!
Have you changed the  `-clusternative.disableCompression(default false)` in vmselect?
```
  -clusternative.disableCompression
     Whether to disable compression of the data sent to vmselect via -clusternativeListenAddr. This reduces CPU usage at the cost of higher network bandwidth usage
```

**Comment by hagen1778** [comment]
Closing as won't implemented.
