### ISSUE TITLE
VictoriaMetrics Enterprise license check via -eula command-line flag is deprecated.

### ISSUE THREAD

**Issue by electrofloat** [VictoriaMetrics/VictoriaMetrics#5919]
### Is your question request related to a specific component?

No

### Describe the question in detail

I've just noticed this in the logs:
```
warn	VictoriaMetrics/lib/license/copyrights.go:27	VictoriaMetrics Enterprise license check via -eula command-line flag is deprecated. Please obtain VictoriaMetrics Enterprise license at https://victoriametrics.com/products/enterprise/trial/ and pass it via either -license or -licenseFile command-line flags. See https://docs.victoriametrics.com/enterprise/
```

since when is this deprecated and why? I need features that are only in the enterprise version that is why I'm using that one.

Why is the trial license only 2 month valid?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by electrofloat** [comment]
Yeah.. but... I cannot find it anymore, since it seems you rewrote the docs too, but for personal use I remember it was stated that we can use the `-eula` flag and that is all.

And I am using it for personal use I`m not an enterprise, but I need features that are only in the "enterprise" version.

I don't mind using the license flags instead of -eula as long as it is still unlimited time.

**Comment by hagen1778** [comment]
Hello @electrofloat! To request a personal license key, please send us an email at info@victoriametrics.com or use the ContactUs button at https://victoriametrics.com/. Please note that the license key can't be unlimited.
