### ISSUE TITLE
vminsert perform to much read syscalls. Is this normal ?

### ISSUE THREAD

**Issue by vnStrawHat** [VictoriaMetrics/VictoriaMetrics#5922]
### Is your question request related to a specific component?

vminsert

### Describe the question in detail

Hello everyone,

Chart of "Disk write/read calls (All)" in our Victoria Metrics cluster show the result that vminsert perform to many disk read syscalls.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4435695/c8428ed7-ce04-4ec2-ae46-7608fee6ec19)

Is this normal behavior ? 

bellow is Victoria Metric cluster stats:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4435695/d06a5d0c-1c86-4499-a728-885a6722049e)

Thanks

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Haleygo** [comment]
Hello!
It's normal, see our [playground](https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?orgId=1&from=1706742097000&to=1706770406000) for reference.
[read](https://man7.org/linux/man-pages/man2/read.2.html) exposed by `process_io_read_syscalls_total` is a system call in Linux used to read data from an open file descriptor into a buffer. It's not only include reading data from files, but also from sockets, pipes, and other input sources.

**Comment by Haleygo** [comment]
>In our environment, vminsert performs x20 read syscalls compared to vmstorage. This is big difference with [playground](https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?orgId=1&from=1706742097000&to=1706770406000)

I think it's fine, it will vary in different vmclusters, for different number of components, different number/size of write requests, etc.
