### ISSUE TITLE
VMUI: VMalert link inside Tools block

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#5924]
### Is your feature request related to a problem? Please describe

VMselect supports feature proxy to VMalert and you can check VMalert via VMUI
- https://docs.victoriametrics.com/cluster-victoriametrics/?highlight=vmalertproxyurl#vmalert

Example link https://play.victoriametrics.com/select/0/prometheus/vmalert/
It's difficult to remember the address or create a separate DNS entry for this endpoint

### Describe the solution you'd like

It would be nice if you added button or link to VMalrt when proxy is enabled and displayed on VMUI
For example include button into `Tools` or add a seperate button
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70581130/fc344a4c-aab5-4fec-b6bf-029b1ec8f70a)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/70581130/a6a3499a-d21c-423c-9740-7df9304cd7e6)

**Comment by hagen1778** [comment]
@Loori-R wdyt?

**Comment by Loori-R** [comment]
Sure, that seems useful. I think it's best to add the link as a separate item

**Comment by hagen1778** [comment]
The change from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7088 was included into [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040).
But I can't close this ticket because of discovered issues in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7088#issuecomment-2391360368

**Comment by yuriydzobak** [comment]
Yep, i'm using cluster version, and button doesn't show up like you described in that comment

**Comment by Loori-R** [comment]
The bug has been resolved with the fix from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7380, which was included in [v1.106.0](https://docs.victoriametrics.com/changelog/#v11060).
