### ISSUE TITLE
API requests for /api/v1/series is broken with search.ignoreExtraFiltersAtLabelsAPI enabled

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#5930]
### Describe the bug

 VictoriaMetrics ignores match[] request param with this enabled flag. It breaks API requests for cluster and returns empty result for single node. 

### To Reproduce

start VictoriaMetrics with flag -search.ignoreExtraFiltersAtLabelsAPI   and try request for /api/v1/series

### Version

v1.99.0

**Comment by hagen1778** [comment]
Related commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b33b620af66f1199b93dc63324b3a32f0a16c402

**Comment by hagen1778** [comment]
The issue was addressed in [v.100.0](https://docs.victoriametrics.com/changelog/#v11000). Closing this issue as completed.
