### ISSUE TITLE
Vmstorage pod unexpectedly getting into "Complted" state and can not be redeployed 

### ISSUE THREAD

**Issue by RNDM-01** [VictoriaMetrics/VictoriaMetrics#5943]
### Describe the bug

We have vmcluster installation where "vmstorage" component has 6 replicas set up by param "replicaCount". After several hours of work, any pods can fall down to "Completed" state. If we looked into state of Completed pod we can see - Exit Code 0
`    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 07 Mar 2024 10:33:42 +0000
      Finished:     Thu, 07 Mar 2024 12:21:09 +0000`
      Completed pods cannot be recreated again. After fallen down several pods we start to lose metrics
     Version:  vmstorage:v1.94.0-cluster

### To Reproduce

Set up vmcluster with several copies of each component

### Version

vmstorage:v1.94.0-cluster

### Logs

Impossible to get any logs from Completed pod.

**Comment by zekker6** [comment]
Hello @RNDM-01 
Pod enters completed state when it was gracefully shut down by request from k8s and containers exited with successful status code(exit code - `0`).
You need to identify the reason k8s decided to stop this pod and why pod in completed state was not deleted(k8s GC is expected to remove such pods).

**Comment by jiekun** [comment]
Close due to inactivity.
