### ISSUE TITLE
vmagent: resources usage increased since v1.97.0

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#5952]
### Describe the bug

Since this [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/09c388a8e419b9d84380f157d0f1fe34420e153c), vmagent start to using more memory when scraping big targets with streamParse.

### To Reproduce

Set up vmagent using v1.96.0, v1.97.1, v1.99.0 without resource limits, scrape same targets with streamParse enabled.
`process_resident_memory_bytes: v1.99.0 > v1.97.1 > v1.96.0`, but from memory profiles, there are no big differences.
<img width="2497" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/6fc9a8f8-5f4b-47fd-a04a-172b430727a0">

https://snapshots.raintank.io/dashboard/snapshot/t3LYeQ0whGjIDcifdSYWtMgIzRA5iYzI

profiles:
[vmagent1971.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/14575485/vmagent1971.pb.gz)
[vmagent1990.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/14575486/vmagent1990.pb.gz)
[vmagent1960.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/14575487/vmagent1960.pb.gz)

### Version

\>= 1.97.0

**Comment by hagen1778** [comment]
@Haleygo, is it possible to try the same test with a bigger number of targets and with a bigger response size? I'd like to see how big is the difference for workload which makes vmagent to consume about 10GiB of mem.
