### ISSUE TITLE
VictoriaLogs: add API to get all values for a label/field

### ISSUE THREAD

**Issue by obitoquilt** [VictoriaMetrics/VictoriaMetrics#5953]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

the same as title. Thanks for any reply.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @obitoquilt 
VictoriaLogs returns all fields stored as `_stream` by default. See this doc for details about querying - https://docs.victoriametrics.com/victorialogs/querying/#http-api

**Comment by zekker6** [comment]
Hi @obitoquilt, release [v0.9.0](https://docs.victoriametrics.com/victorialogs/changelog/#v090) added an API to get a list of streams:
> FEATURE: add /select/logsql/streams HTTP endpoint for returning [streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) from results of the given query. See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-streams) for details.

This release also added API endpoints to fetch all stream fields names and values:
> FEATURE: add /select/logsql/stream_label_names HTTP endpoint for returning [stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) label names from results of the given query. See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-stream-label-names) for details.
> FEATURE: add /select/logsql/stream_label_values HTTP endpoint for returning [stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) label values for the given label from results of the given query. See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-stream-label-values) for details.

See [HTTP querying docs](https://docs.victoriametrics.com/victorialogs/querying/#http-api) for the details regarding data format.

Closing this feature request as completed.
