### ISSUE TITLE
Transferring alerting conditions from Prometheus to vmalert

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#5957]
### Is your question request related to a specific component?

vmalert

### Describe the question in detail

What is the advised method to use to import a large list of alerting conditions from Prometheus to vmalert?  Is there any type of script that exists which could make this transition simpler?  For reference, I'm deploying vmalert with the helm chart.

Thanks for your help.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by zekker6** [comment]
Hello @hartfordfive 
vmalert [supports the same format](https://docs.victoriametrics.com/vmalert/#features) of alert rules definition, so it is only required to copy and paste the alerts into vmalert chart values.
More specifically, you need to copy rules to [`.Values.server.config.alerts.groups`](https://github.com/VictoriaMetrics/helm-charts/blob/619b872768f4f5ceddb291ba2ceaf01801cf2fd3/charts/victoria-metrics-alert/values.yaml#L273) or to create a configmap with rules and use [`.Values.server.configMap`](https://github.com/VictoriaMetrics/helm-charts/blob/619b872768f4f5ceddb291ba2ceaf01801cf2fd3/charts/victoria-metrics-alert/values.yaml#L270) to point to the configmap.

**Comment by hartfordfive** [comment]
How can i specify for it to use multiple existing configmaps for the alerting conditions?  I have quite a few so having the ability to simply use all of these existing configs would make things much easier.

**Comment by hartfordfive** [comment]
I've attempting to define multiple alert rules files using the `server.extraVolumes` [parameter](https://github.com/VictoriaMetrics/helm-charts/blob/497c33e84b7f8efca2fe6a1a4134ccd882a84c69/charts/victoria-metrics-alert/values.yaml#L167) along with `server.extraArgs` [parameter](https://github.com/VictoriaMetrics/helm-charts/blob/497c33e84b7f8efca2fe6a1a4134ccd882a84c69/charts/victoria-metrics-alert/values.yaml#L152) although the problem seems the later parameter only supports setting one additional rule file as it's a map (see [code](https://github.com/VictoriaMetrics/helm-charts/blob/497c33e84b7f8efca2fe6a1a4134ccd882a84c69/charts/victoria-metrics-alert/templates/server-deployment.yaml#L111C1-L117C21)):
```
          {{- range $key, $value := .Values.server.extraArgs }}
              {{- if eq $key "rule" }}
            - -{{ $key }}={{ $value | quote}}
              {{- else }}
            - -{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
```
Could this be updated in the helm chart to allow for this or is there anything simpler method of accomplishing this?   Keep in mind I'm aware you can also specifying alerting conditions via the `server.config.alerts.groups` parameter although considering a configmap can only hold up to 1MB of data (see [docs](https://kubernetes.io/docs/concepts/configuration/configmap/#motivation)), my high number of alerting conditions will likely be quite close to this number (if not over) if I combine everything into a single configmap.   For the sake of clarity and cleanliness, it would also be a more appropriate to have individual configmap items for each alerting condition group.

**Comment by zekker6** [comment]
@hartfordfive You can use the following format for `extraArgs`:
```
  extraArgs:
    envflag.enable: "true"
    envflag.prefix: VM_
    loggerFormat: json
    rule: "/path/to/file/a.yaml,/path/to/file/b.yaml"
```

Helm template in this case will ensure that there are quoutes passed to vmalert command and the value will be interpreted correctly.
