### ISSUE TITLE
Stream field empty using vector and victorialogs on kubernetes

### ISSUE THREAD

**Issue by didlawowo** [VictoriaMetrics/VictoriaMetrics#5961]
### Describe the bug

I have setup victorialogs and vector on my kubernetes cluster to get logs.
it works, almost...
i don't have the stream field with value 
in json mode

  {
    "_msg": "error: unrecognized subcommand 'install'",
    "_stream": "{}",
    "_time": "2024-03-12T12:32:02.979838263Z"
  },
  {
    "_msg": "error: unrecognized subcommand 'install'",
    "_stream": "{}",
    "_time": "2024-03-12T12:32:23.91378648Z"
  },
  {
    "_msg": "error: unrecognized subcommand 'install'",
    "_stream": "{}",
    "_time": "2024-03-12T12:33:11.817714677Z"
  },
  {
    "_msg": "time=\"2024-03-12T12:33:17Z\" level=warning msg=\"Failed to get filesystem device type of /var/lib/longhorn/\" func=\"controller.(*ClusterInfo).collectNodeDiskCount\" file=\"setting_controller.go:1853\" controller=longhorn-setting error=\"lstat /sys/class/block/ubuntu--vg-ubuntu--lv: no such file or directory\" node=nvidia",
    "_stream": "{}",
    "_time": "2024-03-12T12:33:17.621516825Z"
  },

### To Reproduce

lookup into /select/vmui/?#/?query=_time%3A1h+AND+error&page=1&view=json

### Version

latest helm chart for victoria logs

  source:
    chart: victoria-logs-single
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.3.5
    helm:

### Logs

no logs with error about this

### Screenshots

value for vector

      values: |
        role: Agent
        customConfig:
          data_dir: /vector-data-dir
          api:
            enabled: true
            address: 127.0.0.1:8686
            playground: false

          sources:
            k8s:
              type: kubernetes_logs
              auto_partial_merge: true
              delay_deletion_ms: 60000
              # exclude_paths_glob_patterns:
              # - "**/exclude/**"
              # extra_field_selector: metadata.name!=pod-name-to-exclude
              # extra_label_selector: my_custom_label!=my_value
              # extra_namespace_label_selector: app!=monitoring
              # fingerprint_lines: 1
              glob_minimum_cooldown_ms: 60000
              ignore_older_secs: 600
              ingestion_timestamp_field: .ingest_timestamp
              # max_line_bytes: 32768
              max_read_bytes: 2048
              oldest_first: true
              read_from: beginning
              self_node_name: ${VECTOR_SELF_NODE_NAME}
              # timezone: local

          transforms:
            filter_severity:
              type: filter
              inputs:
              - k8s
              condition: '!includes(["info", "debug"], .severity)'

          sinks:
            vlogs:
              inputs:
              - "k8s" # only take sampled data
              type: "elasticsearch"
              endpoints:
              - "http://victoria-logs-single-server.kube-monitoring.svc.cluster.local:9428/insert/elasticsearch/"
              bulk:
                index: "vector-%Y-%m-%d" # daily indices
              mode: "bulk"
              api_version: "v8"
              healthcheck:
                enabled: false
              compression: "gzip"
              query:
                _msg_field: "message"
                _time_field: "timestamp"
                _stream_fields: "container_name"
                ignore_fields: "log.offset,event.original"
                #debug: "1"
              batch:
                max_events: 1000

value for victorialogs

      values: |
        vector:
          enabled: true

### Additional information

i have tryed different vector configuration but always same problem.

**Comment by hagen1778** [comment]
Hello @didlawowo !

I believe, k8s logs from vector just don't have field `container_name` in them. Usually, k8s logs contain the following field `kubernetes.container.name`. Could you try updating your `_stream_fields` setting accordingly?

**Comment by didlawowo** [comment]
it sworks with    _stream_fields: "kubernetes.pod_namespace,kubernetes.container_name"
