### ISSUE TITLE
vmbackupmanager: extend backup scheduling flexibility

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#5966]
### Is your feature request related to a problem? Please describe

Currently, the user can specify a type of backup to create: `hourly`, `daily`, `weekly` or `monthly`.
Scheduling of the backup execution is based on the backup types chosen and uses the lowest time unit among the enabled backups.
With this scheduling logic it is not possible to *only* update the backup without creating a copy in the respective folder.
E.g. I'd like to have daily backups updated every hour. To achieve this it is required to enable hourly backups but set `keepHourly=0` to force removal of every hourly backup.

### Describe the solution you'd like

It would be great to implement implement one of the following:
- skip creation of backup if `keep*` is set to `0` - this seems to be the most straighforward approach, but it might be counterintuitive that it is required to enable this backup but set `keep*` to zero.
- to allow customizing frequency of backups creation - this will allow creating each enabled backup type on user-defined frequency basis

### Describe alternatives you've considered

Using `keep*` set to `0` with the backup type enabled. The problem is that increases amount of operations required to perform the backup which affects backup time and costs.

**Comment by zekker6** [comment]
This was implemented in [v1.100.1](https://docs.victoriametrics.com/changelog/#v11001), closing as done.

**Comment by valyala** [comment]
Custom backup interval can be specified via `-backupInterval` command-line flag at [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager/) starting from [v1.100.1 release](https://docs.victoriametrics.com/changelog/):

> -backupInterval duration
>     Interval between backups. If set to 0 interval is set to 1h if hourly backups are enabled and 24h otherwise (default 0)
