### ISSUE TITLE
How to increase search.maxUniqueTimeseries 

### ISSUE THREAD

**Issue by kengan** [VictoriaMetrics/VictoriaMetrics#597]
I use promxy  to search data from victoriametrics and get following errro

Error executing query: 422: error when executing query="node_cpu_seconds_total{mode="user"}" for (time=1593595540736, step=30000): cannot evaluate "node_cpu_seconds_total{mode="user"}": search error after reading 0 data blocks: error when searching tsids for tfss ["{name="node_cpu_seconds_total", mode="user"}"]: more than 300001 time series found on the time range [2020-07-01 09:20:10.736 +0000 UTC - 2020-07-01 09:25:40.736 +0000 UTC]; either increase -search.maxUniqueTimeseries or shrink the time range

can you tell me how to increase search.maxUniqueTimeseries. Thank you

**Comment by valyala** [comment]
Just pass `-search.maxUniqueTimeseries` command-line flag to VictoriaMetrics during startup. For example, the following line will increase the limit on unique time series during querying to 1M :
```
/path/to/victoria-metrics -search.maxUniqueTimeseries=1000000
```

**Comment by angryman9** [comment]
` /victoria-metrics-prod -version
victoria-metrics-20210611-102507-tags-v1.61.1-0-g2ef2e3d6f`

setting value to 1000000 or more returns an error like:
`invalid value "1e+06" for flag -search.maxUniqueTimeseries: parse error`

maximum accepted value is 999999
but I need more:
`wget -O- -q 'https://victoria-metrics-prod.host/api/v1/series/count' | jq '.data[0]'
12334050`

please help with it

**Comment by valyala** [comment]
Try wrapping the value in quotes. E.g. `-search.maxUniqueTimeseries="1000000"`

**Comment by angryman9** [comment]
setting the value in quotes works. thx

**Comment by PritomAhmed** [comment]
When I am passing this argument, I am seeing the following error message
`flag provided but not defined: -search.maxUniqueTimeseries`
