### ISSUE TITLE
irate function aggregation is abnormally high

### ISSUE THREAD

**Issue by hichenxinyu** [VictoriaMetrics/VictoriaMetrics#5986]
### Describe the bug

When we query the pod CPU usage, we found that the irate data will be distorted and appear to be abnormally high. It is normal to directly query the original data without using irate.
Here is the normal query
metricql：container_cpu_usage_seconds_total{pod="core-api-9fb8bb4c7-ctsf5"}
![uKKIDjgMD8](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/ec7ed89e-0487-4ec4-b2e4-6cfcdaf9827f)
Here is the exception query
metricql: irate(container_cpu_usage_seconds_total{pod="core-api-9fb8bb4c7-ctsf5"}[1m])
![img_v3_0294_1af0044e-8700-4fc5-993b-1890c245240g](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/09ac3b13-a553-48a5-8d84-75c70c914fc9)

The deployment method is vm-operator，cluster version:1.91.3

### To Reproduce

 irate(container_cpu_usage_seconds_total[1m])

### Version

vmselect-20230630-163028-tags-v1.91.3-cluster-0-g12f262c331

### Logs

grafana

**Comment by hagen1778** [comment]
@hichenxinyu please follow https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results
In order to understand whether this bug or not, we need to get raw data from p.2.

**Comment by hichenxinyu** [comment]
1. raw data
container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/fc3739a5-e2a7-4661-8982-d549ff72922a)

2. rate
rate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/c50ecdf1-3b64-4e5f-9623-62d20cc31a59)

3. irate
irate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/ebece103-1155-48bc-bf7e-5673a2fc7ae1)

**Comment by hagen1778** [comment]
Hi @hichenxinyu !

> In order to understand whether this bug or not, we need to get raw data from p.2.

p.2 in the link https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results implies exporting the data samples to a file and sharing it here. Plotting metrics in VMUI is never about raw data - see why here https://docs.victoriametrics.com/keyconcepts/#query-data

**Comment by hichenxinyu** [comment]
1. container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}
{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"__name__":"container_cpu_usage_seconds_total","container":"gs-gf-canary","cpu":"total","instance":"cn-shanghai.172.19.7.190","job":"kubernetes-nodes-cadvisor","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","namespace":"ak-prod","pod":"gs-gf-canary-4lttq","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[[1716404400,"1443676.51202676"],[1716404460,"1443848.5479921638"],[1716404520,"1443994.8102552183"],[1716404580,"1444156.7245255953"],[1716404640,"1444287.695845293"],[1716404700,"1444468.40684718"],[1716404760,"1444621.314398774"],[1716404820,"1444771.59092836"],[1716404880,"1444952.65794684"],[1716404940,"1445075.290480883"],[1716405000,"1445240.985099765"]]}]},"stats":{"seriesFetched": "1"}}%

2. rate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"container":"gs-gf-canary","cpu":"total","instance":"cn-shanghai.172.19.7.190","job":"kubernetes-nodes-cadvisor","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","namespace":"ak-prod","pod":"gs-gf-canary-4lttq","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[[1716404400,"2.7881266340302924"],[1716404460,"2.8672660900629126"],[1716404520,"2.4377043842415635"],[1716404580,"2.6985711729503237"],[1716404640,"2.1828553282966214"],[1716404700,"3.01185003144977"],[1716404760,"2.548459193230762"],[1716404820,"2.504608826432377"],[1716404880,"3.017783641334002"],[1716404940,"2.043875567386082"],[1716405000,"2.761576981365215"]]}]},"stats":{"seriesFetched": "1"}}%

3. irate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"container":"gs-gf-canary","cpu":"total","instance":"cn-shanghai.172.19.7.190","job":"kubernetes-nodes-cadvisor","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","namespace":"ak-prod","pod":"gs-gf-canary-4lttq","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[[1716404400,"0"],[1716404460,"0"],[1716404520,"0"],[1716404580,"0"],[1716404640,"0"],[1716404700,"0"],[1716404760,"0"],[1716404820,"0"],[1716404880,"0"],[1716404940,"0"],[1716405000,"0"]]}]},"stats":{"seriesFetched": "1"}}%

**Comment by hichenxinyu** [comment]
container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}
```
{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"__name__":"container_cpu_usage_seconds_total","container":"gs-gf-canary","cpu":"total","instance":"cn-shanghai.172.19.7.190","job":"kubernetes-nodes-cadvisor","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","namespace":"ak-prod","pod":"gs-gf-canary-4lttq","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[[1716404400,"1443676.51202676"],[1716404460,"1443848.5479921638"],[1716404520,"1443994.8102552183"],[1716404580,"1444156.7245255953"],[1716404640,"1444287.695845293"],[1716404700,"1444468.40684718"],[1716404760,"1444621.314398774"],[1716404820,"1444771.59092836"],[1716404880,"1444952.65794684"],[1716404940,"1445075.290480883"],[1716405000,"1445240.985099765"]]}]},"stats":{"seriesFetched": "1"}}%
```

rate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
```
{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"container":"gs-gf-canary","cpu":"total","instance":"cn-shanghai.172.19.7.190","job":"kubernetes-nodes-cadvisor","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","namespace":"ak-prod","pod":"gs-gf-canary-4lttq","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[[1716404400,"2.7881266340302924"],[1716404460,"2.8672660900629126"],[1716404520,"2.4377043842415635"],[1716404580,"2.6985711729503237"],[1716404640,"2.1828553282966214"],[1716404700,"3.01185003144977"],[1716404760,"2.548459193230762"],[1716404820,"2.504608826432377"],[1716404880,"3.017783641334002"],[1716404940,"2.043875567386082"],[1716405000,"2.761576981365215"]]}]},"stats":{"seriesFetched": "1"}}%
```

irate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
```
{"status":"success","isPartial":false,"data":{"resultType":"matrix","result":[{"metric":{"container":"gs-gf-canary","cpu":"total","instance":"cn-shanghai.172.19.7.190","job":"kubernetes-nodes-cadvisor","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","namespace":"ak-prod","pod":"gs-gf-canary-4lttq","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[[1716404400,"0"],[1716404460,"0"],[1716404520,"0"],[1716404580,"0"],[1716404640,"0"],[1716404700,"0"],[1716404760,"0"],[1716404820,"0"],[1716404880,"0"],[1716404940,"0"],[1716405000,"0"]]}]},"stats":{"seriesFetched": "1"}}%
```

**Comment by hichenxinyu** [comment]
I see, I didn't get it before, thanks for explaining.
Here's the raw data from the report.
```
{"metric":{"__name__":"container_cpu_usage_seconds_total","namespace":"ak-prod","job":"kubernetes-nodes-cadvisor","instance":"cn-shanghai.172.19.7.190","pod":"gs-gf-canary-4lttq","container":"gs-gf-canary","cpu":"total","k8s_cluster_name":"hg-online","kubernetes_io_hostname":"cn-shanghai.172.19.7.190","prometheus":"monitoring/hg-vmagent-statefulset","replica":"hg-online"},"values":[1212390.3812399947,1212390.3812399947,1212493.33686736,1212493.33686736,1212587.101170926,1212587.101170926,1212701.10749039,1212701.10749039,1212843.188067887,1212843.188067887,1212938.3254454522,1212938.3254454522,1213086.468988257,1213086.468988257,1213210.415540035,1213210.415540035,1213335.9272663617,1213335.9272663617,1213471.4552453223,1213471.4552453223,1213576.732523764,1213576.732523764,1213691.23498833,1213691.23498833,1213813.319380004,1213813.319380004,1213902.9747765083,1213902.9747765083,1213991.962749983,1213991.962749983,1214172.27581144,1214172.27581144,1214172.27581144,1214172.27581144,1214303.641534594,1214303.641534594,1214451.3881284131,1214451.3881284131,1214565.14053214,1214565.14053214,1214715.9681382782,1214715.9681382782,1214817.4242046068,1214817.4242046068,1214907.8230600383,1214907.8230600383,1215006.0168317717,1215006.0168317717,1215142.40508536,1215142.40508536,1215252.1433278932,1215252.1433278932,1215359.869907173,1215453.67000135,1215553.34472523,1215553.34472523,1215657.335538057,1215657.335538057,1215777.9315142916,1215777.9315142916,1215876.537563044,1215876.537563044,1216004.107424711,1216004.107424711,1216126.6123412743,1216126.6123412743,1216248.2152623262,1216248.2152623262,1216248.2152623262,1216248.2152623262,1216388.7522693428,1216388.7522693428,1216521.067737017,1216521.067737017,1216615.0180150825,1216615.0180150825,1216734.52251706,1216734.52251706,1216896.70017353,1216896.70017353],"timestamps":[1716375613193,1716375613212,1716375628193,1716375628212,1716375643193,1716375643212,1716375658193,1716375658212,1716375673193,1716375673212,1716375688193,1716375688212,1716375703193,1716375703212,1716375718193,1716375718212,1716375733193,1716375733212,1716375748193,1716375748212,1716375763193,1716375763212,1716375778193,1716375778212,1716375793193,1716375793212,1716375808193,1716375808212,1716375823193,1716375823212,1716375838193,1716375838212,1716375853193,1716375853212,1716375868193,1716375868212,1716375883193,1716375883212,1716375898193,1716375898212,1716375913193,1716375913212,1716375928193,1716375928212,1716375943193,1716375943212,1716375958193,1716375958212,1716375973193,1716375973212,1716375988193,1716375988212,1716376003193,1716376003212,1716376018193,1716376018212,1716376033193,1716376033212,1716376048193,1716376048212,1716376063193,1716376063212,1716376078193,1716376078212,1716376093193,1716376093212,1716376108193,1716376108212,1716376123193,1716376123212,1716376138193,1716376138212,1716376153193,1716376153212,1716376168193,1716376168212,1716376183193,1716376183212,1716376198193,1716376198212]}
```

**Comment by hagen1778** [comment]
Thanks for the data!
It helped me to see that you have sample duplicates:
```
  "values": [
    1212390.3812399947,
    1212390.3812399947, # duplicate
    1212493.33686736,
    1212493.33686736, # duplicate
```
Apparently, you double-scrape your targets. In this case, to get correct query results you need to de-duplicate the data on query time and on storage side. Please read more here https://docs.victoriametrics.com/#deduplication

Based on the provided timestamps, the scrape interval of the samples is about `15s`. So this is what you want to set as `-dedup.minScrapeInterval=15s`.
