### ISSUE TITLE
[vmalert] Why is the execution time of the vmalert rule inconsistent with the time in the request ？

### ISSUE THREAD

**Issue by zxl181212** [VictoriaMetrics/VictoriaMetrics#5994]
### Is your question request related to a specific component?

rule file:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157791461/a5d939e9-db59-41b2-9136-98daef757816)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157791461/e9bb5cdf-a95c-4928-8793-1aa42a178387)

The rule executed at 2024-03-20T19:50:04+08:00 , but the request url is: 
curl -X POST -H 'Content-Type: application/json' 'http://vmpf.tsdb.qihoo.net:8481/select/0/prometheus/api/v1/query?query=xxx&step=10800s&time=1710925200'

Why is this time parameter not the rule execution time and the difference from the current time so large ?

### Describe the question in detail

The other 20 are also like this.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @zxl181212 ! What version of the vmalert do you use? I have checked the latest version of the VM alert, and it shows time in RFC339 format. 
<img width="1680" alt="Screenshot 2024-03-21 at 13 21 43" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/493ae51f-1c40-4b9a-9d3d-5d42892ae979">

**Comment by zxl181212** [comment]
@dmitryk-dk  ./vmalert-prod -version
vmalert-20230201-230025-tags-v1.87.0-enterprise-0-gcb25ddccf

**Comment by dmitryk-dk** [comment]
Hi @zxl181212 ! I have checked your question. The difference is because the `time` param is in UTC format always, and the `Executed At` was formatted to RFC339, which shows to you in local time. 
If you upgrade your version to newset I think you will see the same time in RFC339 format as I mentioned before

**Comment by zxl181212** [comment]
> Hi @zxl181212 ! I have checked your question. The difference is because the `time` param is in UTC format always, and the `Executed At` was formatted to RFC339, which shows to you in local time. If you upgrade your version to newset I think you will see the same time in RFC339 format as I mentioned before

Okay, I'll give it a try. Thank you very much
