### ISSUE TITLE
Extended vmstorage unreachability after replicaCount change

### ISSUE THREAD

**Issue by nemobis** [VictoriaMetrics/VictoriaMetrics#5997]
### Describe the bug

After increasing `replicaCount` for vmstorage pods with the VictoriaMetrics helm chart, some vmstorage pods remained in unreachable state for over 1 hour. During this time, potential data loss was observed on samples which were ostensibly remote-written to vmagent without failures by Prometheus instances. (Most metrics were ingested and retrieved correctly, but some metrics from one source appeared missing for over 1 hour and never came back.)

All pods returned to a reachable state after restarting the vminsert and vmselect pods.

### To Reproduce

Increase vmstorage `replicaCount` without restarting the vminsert/vmselect pods?

### Version

```
/ # ./vmstorage-prod --version
vmstorage-20240301-014102-tags-v1.99.0-cluster-0-gd66680fc4
```

### Logs

No relevant logs found.

### Screenshots

![Screenshot_20240319_163755](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/901528/6d110ee8-70ef-4bc9-bb6b-15fb71e2d25d)

### Used command-line flags

```
Containers:
  victoria-metrics-cluster-vmstorage:
    Container ID:  containerd://2e64047b8fb30c5f90a5a7dbc6d74f3a165b7ee5b5ff9f59957325b61052bcda
    Image:         victoriametrics/vmstorage:v1.99.0-cluster
    Image ID:      docker.io/victoriametrics/vmstorage@sha256:368ad068a7e1b0cb57cf031d0d9f72bba81f243e59fe52b2cf792458f3dbb6a9
    Ports:         8482/TCP, 8400/TCP, 8401/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Args:
      --retentionPeriod=12
      --storageDataPath=/storage
      --dedup.minScrapeInterval=30s
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
      --search.maxConcurrentRequests=2
      --search.maxUniqueTimeseries=1000000
      --storage.minFreeDiskSpaceBytes=64GB
```

and
```
  victoria-metrics-cluster-vminsert:
    Container ID:  containerd://a59f5bc82ae0e36cba202aec3269a78b5e3bb10c51b6d1789762a0164616238f
    Image:         victoriametrics/vminsert:v1.99.0-cluster
    Image ID:      docker.io/victoriametrics/vminsert@sha256:141b33bf9914f34b10477039a27a88ec117615207d046a8716aa84c7e6236acd
    Port:          8480/TCP
    Host Port:     0/TCP
    Args:
      --storageNode=victoriametrics-victoria-metrics-cluster-vmstorage-0.victoriametrics-victoria-metrics-cluster-vmstorage.victoriametrics.svc.cluster.local:8400
[...]
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
```

**Comment by nemobis** [comment]
I wonder if there might have been some silent errors due to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5441

**Comment by hagen1778** [comment]
Hey @nemobis! Do you have any details on why vmstorages were unavailable during this hour? Is it because they were overloaded or because k8s deployment got stuck?
Please follow https://docs.victoriametrics.com/troubleshooting/#cluster-instability

**Comment by nemobis** [comment]
@hagen1778 Thanks for the link; I don't think any of [those](https://docs.victoriametrics.com/troubleshooting/#cluster-instability) reasons apply. As the issue was fixed instantly after restarting the vminsert deployment, I suspect it may have something to do with orchestration, for example the pods may have changed their IP address and for some reason the `cluster.local` connections may have been temporarily broken.

Also, at the same time I increased `storage.minFreeDiskSpaceBytes`, so several pods went read-only. Not sure whether they're marked as unreachable too.

**Comment by hagen1778** [comment]
>  Not sure whether they're marked as unreachable too.

If they became RO, then vminsert will stop writing into them. But this doesn't align with what you said about restarting vminsert.

Anyway, [monitoring](https://docs.victoriametrics.com/troubleshooting/#monitoring) should help to see what exactly happened during the incident. On dashboard, you should be able to see whether vminserts were able to write to all vmstorage pods.

**Comment by nemobis** [comment]
There wasn't anything at all in logs and I couldn't notice anything unusual in the dashboards. None of the suggested alerts would have fired either.

I can't reproduce this bug so I'll close the report now, I can reopen if/when I find how to reproduce it.
