### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6]
Feature request:
- add import/export of all metrics or by given query

**Comment by valyala** [comment]
It is possible to export time series matching the given selector starting from [v1.7.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
See also https://github.com/prometheus/prometheus/issues/535

**Comment by valyala** [comment]
The priority for `/api/v1/import` feature should be increased, since users frequently ask for it. The `/api/v1/import` handler must accept data generated by `/api/v1/export`.

**Comment by valyala** [comment]
Added `/api/v1/import` in [v1.30.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

Closing the issue.
