### ISSUE TITLE
VM ignore some metrics, received from influxdb clients

### ISSUE THREAD

**Issue by 0xBF** [VictoriaMetrics/VictoriaMetrics#60]
Some influxdb clients (at least ruby client) send metrics without trailing newline. If there is only one metric in request, it ignored. In some cases can be ignored the last metric in batch requests.

example request:
```
curl -sd "mymetric test=10i 1559933640" 'http://172.17.0.3:8428/write?db=qq&precision=s'
```

check metrics:
```
curl -s 'http://172.17.0.3:8428/metrics' |grep influx
vm_http_request_errors_total{path="/write", protocol="influx"} 0
vm_http_requests_total{path="/query", protocol="influx"} 0
vm_http_requests_total{path="/write", protocol="influx"} 1
vm_read_calls_total{name="influx"} 1
vm_read_errors_total{name="influx"} 0
vm_rows_inserted_total{type="influx"} 0
vm_unmarshal_errors_total{name="influx"} 0
```

It can be fixed by commenting this line:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vminsert/influx/request_handler.go#L135

**Comment by valyala** [comment]
The issue has been fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/e1c45b314a11957645729fdd1fc3dd3008978cd1 .  The bugfix will be available in the next release. In the mean time you can build VictoriaMetrics with the bugfix from sources.

**Comment by 0xBF** [comment]
thank you! it was really fast!
