### ISSUE TITLE
victoriaMetrics single node indexdb occupy high disk

### ISSUE THREAD

**Issue by GlqEason** [VictoriaMetrics/VictoriaMetrics#6000]
### Describe the question in detail

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/36256450/96f822ae-6207-442f-9ca2-252d4441fd07)
indexdb has outdate data with retentionPeriod=15d, 2024-02 data has remain in it and fouce_flush is not working.
force_flush is alse not work.
How do I troubleshoot this?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by GlqEason** [comment]
additionally disk usage is up to 91% so that victoriaMetris doesn’t merge parts.
so how can i deal with the data which outside the configured retention
@valyala

**Comment by GlqEason** [comment]
> Hey @GlqEason, it works according to this doc: https://docs.victoriametrics.com/#retention:
> 
> > Data is split in per-month partitions inside `<-storageDataPath>/data/{small,big}` folders.
> > **Data partitions** outside the configured retention are deleted **on the first day of the new month**.
> > Each partition consists of one or more **data parts**. Data parts outside the configured retention
> > are **eventually deleted** during [background merge](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282).
> > The time range covered by data part is **not limited by retention period unit**. One data part can cover hours or days of
> > data. Hence, a data part can be deleted only **when fully outside the configured retention**.
> > See more about partitions and parts [here](#storage).
> > **The maximum disk space usage for a given `-retentionPeriod` is going to be (`-retentionPeriod` + 1) months.**
> > **For example, if `-retentionPeriod` is set to 1, data for January is deleted on March 1st.**

How can expired data be deleted immediately without having to wait until the first day of the next month?

**Comment by Amper** [comment]
> How can expired data be deleted immediately without having to wait until the first day of the next month?

AFAIK, there is no standard way to do it.
