### ISSUE TITLE
VMsingle: Burp scan reported SQL injection attack

### ISSUE THREAD

**Issue by VeenaThimmegowda** [VictoriaMetrics/VictoriaMetrics#6008]
### Is your question request related to a specific component?

vmsingle

### Describe the question in detail

Burp scan reported SQL injection attack in vmsingle component for the path **/vmsingle/target-relabel-debug**

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/38758323/5b8ebf6d-49e4-4e45-8de6-bd3a878474cd)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
Hello @VeenaThimmegowda ! 
vmsingle, or any other VM component, has no SQL query engine or processor. Hence, they can't be vulnerable to SQL injections, as injected commands can't be executed.
The provided vulnerability report is red herring.
