### ISSUE TITLE
How to query VictoriaMetrics raw data

### ISSUE THREAD

**Issue by wzh2136927** [VictoriaMetrics/VictoriaMetrics#6013]
### Is your question request related to a specific component?

 VictoriaMetrics

### Describe the question in detail

Now I want to take out the data from VictoriaMetrics for profiling analysis. I tried the query_range api in https://docs.victoriametrics.com/url-examples/. I wrote a scheduled task and executed it once every minute. I called this api to obtain VictoriaMetrics data, the start set for each run is the current time -1m, and the end is the current time.
step is 15s,
I have been running this scheduled task for a long time, but no data is returned. What is this question?,  

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by hagen1778** [comment]
> Now I want to take out the data from VictoriaMetrics for profiling analysis. 

Please try using the [Export API](https://docs.victoriametrics.com/#how-to-export-time-series).

> I have been running this scheduled task for a long time, but no data is returned. What is this question?,

I believe [Export API](https://docs.victoriametrics.com/#how-to-export-time-series) will suit you better. But if not, and you still have issues with query API - please go through https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results.

**Comment by wzh2136927** [comment]
i try the query_range api this morning again, and set the params not change,  but  it works this morning ,   and i change my strategy to get data from VictoriaMetrics,   when the schedule task running , try to get the same timestamp of lastday and the same timestamp -1m of lastday ,  is this ok?

**Comment by wzh2136927** [comment]
i've try the export api,but the same result returned,     
An interesting phenomenon is that when I called this API yesterday about 17:00 and today's morning, the parameters did not change, but the results were different 。
curl http://10.0.1.138:8428/api/v1/export -d 'match[]=mem_used_percent' -d 'start=2024-03-26T16:16:00.000Z' -d 'end=2024-03-26T16:17:00.000Z' 
 
how to explain this?

**Comment by wzh2136927** [comment]
and another question,  when i use query_range api and returns empty data,  but when i use the query api  to query the instant data, it always returns data

**Comment by hagen1778** [comment]
@wzh2136927 could you provide a scenario with steps to reproduce? Without this I can't help, as I don't know which data, when and where you write. As well as which queries you use to get it back.
Would appreicate if you can reproduce it on the [playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/top-queries?topN=10&maxLifetime=10m) or in [docker-compose env](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker#docker-compose-environment-for-victoriametrics) and list steps you took in this issue.

**Comment by wzh2136927** [comment]
I would like to query the data for the 'mem_used_percent' metric from 1 minute ago until now.  It's surprising that I couldn't retrieve the data at the current time, but when I execute the same API tomorrow without changing any parameters, I can retrieve the data again. This really puzzles me.  I don’t know how VetricMetirc stores data and what processing is done when querying the data. Please help me translate it.

**Comment by hagen1778** [comment]
> It's surprising that I couldn't retrieve the data at the current time, but when I execute the same API tomorrow without changing any parameters, I can retrieve the data again. This really puzzles me. I don’t know how VetricMetirc stores data and what processing is done when querying the data. Please help me translate it.

I can recommend reading https://docs.victoriametrics.com/keyconcepts/#query-data, especially https://docs.victoriametrics.com/keyconcepts/#query-latency. Let me know if you'd still have questions after reading the docs.
