### ISSUE TITLE
vmgateway: add an ability to log invalid auth tokens

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#6029]
### Is your feature request related to a problem? Please describe

When setting up an external SSO it is hard to understand why exactly the token can be rejected by vmgateway.
Currently, vmgateway exposes several metrics which are representing different types of problems which can be used as a first step to see why the token is rejected, but it doesn't help to debug token formatting issues.

### Describe the solution you'd like

To add support of flag similar to vmauth's `logInvalidAuthTokens`:
>   -logInvalidAuthTokens
     Whether to log requests with invalid auth tokens. Such requests are always counted at vmauth_http_request_errors_total{reason="invalid_auth_token"} metric, which is exposed at /metrics page

This allows to enable invalid tokens logging during the setup to see the token value. This allows to use debugging tools like https://jwt.io to see the token contents and take action based on specific formatting issues.

**Comment by valyala** [comment]
[`vmgateway`](https://docs.victoriametrics.com/vmgateway/) gains the ability to log invalid auth tokens if `-logInvalidAuthTokens` command-line flag is passed to it starting from [v1.100.0 release](https://docs.victoriametrics.com/changelog/).

Closing the feature request as done.
