### ISSUE TITLE
Adds firehose http endpoint protocol integration for opentelemetry ingestion.

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#6037]
### Is your feature request related to a problem? Please describe

It's possible to forward AWS CloudWatch metrics to the VictoriaMetrics with Firehose http endpoint opentelemetry format. https://aws.amazon.com/blogs/aws/cloudwatch-metric-streams-send-aws-metrics-to-partners-and-to-your-apps-in-real-time/

 But it has the following issues:
- Firehose expects strict format for HTTP responses https://docs.aws.amazon.com/firehose/latest/dev/httpdeliveryrequestresponse.html#responseformat
- metric names has prometheus incompatible format
- 1.0 opentemetry format parses incorrectly (attributes have nested maps).  https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-formats-opentelemetry-100.html 

### Describe the solution you'd like

* Fix compatibility with firehose.
* Introduce new flag for metric name conversion into prometheus compatible format. 
* properly parse nested maps for attributes.

**Comment by valyala** [comment]
FYI, the compatibility with AWS Firehose should be fixed in the commit 509df44d03631a863fab00e202a6449c19d784e1

**Comment by valyala** [comment]
FYI, the `-opentelemetry.usePrometheusNaming` flag has been introduced in the commit fb42380ef374c394053b4cc4f2b083ed4afc7d09 . If this flag is set, then VictoriaMetrics automatically converts metric names and label names into Prometheus-compatible names for samples ingested via [OpenTelemetry format](https://docs.victoriametrics.com/#sending-data-via-opentelemetry).

**Comment by valyala** [comment]
FYI, [vmagent](https://docs.victoriametrics.com/vmagent/) and [single-node VictoriaMetrics](https://docs.victoriametrics.com/) properly return responses to Amazon Firehose starting from [v1.100.0](https://docs.victoriametrics.com/changelog/). They also support the `-opentelemetry.usePrometheusNaming` command-line flag starting from `v1.100.0` release.

**Comment by AndrewChubatiuk** [comment]
@f41gh7 
we're [converting](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0dda3978a59c529597bada50d81009df14f71070/lib/protoparser/opentelemetry/pb/helpers.go#L23) otel metrics in the same manner as it's done in [collector](https://github.com/open-telemetry/opentelemetry-collector/blob/2ff9795371c0972cf1c7ffc3b753de07cbfd00db/pdata/pcommon/value.go#L385), they are also storing array and map attributes as JSON
