### ISSUE TITLE
Add Vultr to service discovery

### ISSUE THREAD

**Issue by Lusitaniae** [VictoriaMetrics/VictoriaMetrics#6041]
### Is your feature request related to a problem? Please describe

I want Vultr as a service discovery 

https://docs.victoriametrics.com/sd_configs/

### Describe the solution you'd like

Prometheus have support for Vultr's service discovery and would be great to have the same thing in Victoria Metrics

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#vultr_sd_config

### Describe alternatives you've considered

Built and host a simple API to fetch the required data from Vultr API

> http_sd_configs is for discovering and scraping targets provided by external http-based service discovery. See [these docs](https://docs.victoriametrics.com/sd_configs/#http_sd_configs).

**Comment by jiekun** [comment]
I am interested in implementing this enhancement if the maintainer deems it worthwhile and no one else is currently working on it.

**Comment by valyala** [comment]
Support for Vultr service discovery is available in [single-node VictoriaMetrics](https://docs.victoriametrics.com/#how-to-scrape-prometheus-exporters-such-as-node-exporter) and in [vmagent](https://docs.victoriametrics.com/vmagent/) starting from [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).
