### ISSUE TITLE
How to remove/shrink storage node quantity in vm cluster?

### ISSUE THREAD

**Issue by naughtyGitCat** [VictoriaMetrics/VictoriaMetrics#6043]
### Is your question request related to a specific component?

vm-cluster and the vm-storage management

### Describe the question in detail

In the documents, only expand storage node quantity is mentioned, but how can we shrink/remove storage node numbers from X to X-N ？

for example:
we have a cluster with 6 storage nodes(replication factor=1),  we shorten the retention period from 4 years to 2year, and the total size of storage decreases to half， then we do not need 6 storage nodes anymore, and we want to cut off some machine costs, how can we shrink from 6 storage nodes to 3 storage nodes and keep the data integrity？ if we simply remove storage nodes urls from vm-select nodes, and shut down the machine, the cluster will be lost half of the data.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

ref 
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4524

**Comment by zekker6** [comment]
Hello @naughtyGitCat 

There are a few ways to achieve this:

1. Separate read and write paths to use different sets of storage nodes.
You can change vminsert configuration to write data to 3 nodes out of 6 existing nodes. vmselects should still read the data from all 6 nodes. Once retention period removes all data from excessive storage nodes it's possible to remove those storage nodes and update vmselect configuration.
This option works well for short retention periods as it requires all storage nodes to be available until retention will remove the data.

2. Re-import data to be distributed across 3 storage nodes.
The idea is to update vminsert configuration to only write data to 3 storage nodes which will be left in cluster.
After this you can export data from cluster and import back.
Please, make sure that [deduplication](https://docs.victoriametrics.com/cluster-victoriametrics/#deduplication) is enabled before importing data. You can use `dedup.minScrapeIntervals=1ms` for this case.
In this case data will be distributed across 3 storage nodes used in vminsert configuration, deduplication will remove the duplicate samples created by import operations in the background.
After import is finished it is possible to remove unneeded storage nodes as the data for these storage nodes is already present in cluster.

3. Create new cluster with the desired configuration and migrate the data.
This option is the most straightforward and simple to implement. It works unless it is required to update an existing cluster.

**Comment by naughtyGitCat** [comment]
thanks, your suggestion is very meticulous
