### ISSUE TITLE
vmagent/vmalert: support SRV records to discover remote-write targets

### ISSUE THREAD

**Issue by plangdale-roblox** [VictoriaMetrics/VictoriaMetrics#6053]
### Is your feature request related to a problem? Please describe

Today, we rely on DNS A records + static ports to allow vmagents and vmalert to discover their write targets. We'd like to reduce our dependency on static port assignments throughout our infrastructure, which means needing another way to communicate port numbers. 

### Describe the solution you'd like

We would like vmagent and vmalert to support doing SRV lookups for remote-write URLs to get port number information dynamically. This would allow us to freely redeploy the target services without having to worry about port numbers changing, or communicating changed port numbers.

### Describe alternatives you've considered

* Implementing #2628 would provide a way to reload configuration, which we could then use with additional code on our side that is able to respond to a change in target port number by updating and reloading configuration. But this would require that additional code to be provided, which is more moving parts. Native SRV support avoids the need for it.
* Running a discovery aware load balancer in front of the targets would isolate changes of port numbers, but the load balancer itself needs a static port, so we've just moved the problem one hop, and we'd also need to do non-trivial resource provisioning for the load balancer given our traffic volumes.

### Additional information

There should be a way to configure whether SRV lookups fall back to TCP (from UDP) if the response is truncated. In some situations, it is sufficient to receive at least one record, and not the complete set - and it is better not to generate unnecessary traffic from large TCP responses.

**Comment by hagen1778** [comment]
@f41gh7 could you please take a look?

**Comment by valyala** [comment]
The commit dc326f70b4026a802ba0db0c891b856d56b08c0d adds an ability to specify DNS SRV address inside `-remoteWrite.url` in the form `-remoteWrite.url=http://srv+some-addr/api/v1/write`. In this case the `some-addr` DNS SRV address is automatically resolved to TCP address (e.g. hostname with TCP port) and used instead of `srv+some-addr` in the `-remoteWrite.url`.

The DNS SRV resolution is performed each time `vmagent` establishes connection to the remote storage.
If the are multiple TCP addresses behind the DNS SRV record, then random TCP address is chosen every time new connection is established to the remote storage. See [these docs](https://docs.victoriametrics.com/vmagent/#srv-urls) for more details.

This commit will be included in the next release. In the mean time it is possible to verify this feature by building `vmagent` from this commit according to [these docs](https://docs.victoriametrics.com/vmagent/#how-to-build-from-sources).

@hagen1778 , @Haleygo , please add support for DNS SRV urls at `vmalert`.

**Comment by plangdale-roblox** [comment]
Thank you for making this change. With respect to DNS specifics, how does the querying handle large responses? Does it use EDNS or TCP fallback? We don't need complete responses for our use-case so we'd like to avoid TCP fallback happening unnecessarily.

**Comment by hagen1778** [comment]
Hello @plangdale-roblox!
In this implementation, vmagent and other tools rely on Go [stdlib for DNS resolve](https://go.dev/src/net/lookup.go).

> how does the querying handle large responses?

stdlib respects limits and considerations described here https://www.dnsflagday.net/2020/. From my understanding, it will be  able to parse responses with max size of 1232 bytes. For bigger responses it will return an error.

> Does it use EDNS or TCP fallback?

It uses EDNS and respects https://man7.org/linux/man-pages/man5/resolv.conf.5.html settings - see https://go.dev/src/net/dnsconfig_unix.go

**Comment by lapo-luchini** [comment]
> If the are multiple TCP addresses behind the DNS SRV record, then random TCP address is chosen every time new connection is established to the remote storage.

So this only makes sense if those addresses are different `vminsert` nodes of the same cluster, is that right?
(redundant single-node clusters would still need multiple `-remoteWrite.url` in order to write to each and all of the nodes, each with its own queue and everything)

**Comment by hagen1778** [comment]
> So this only makes sense if those addresses are different vminsert nodes of the same cluster, is that right?

Yes. The purpose of this feature is to avoid vmagent process restart if the host address (balancer before vminserts) changes frequently.

**Comment by plangdale-roblox** [comment]
> @hagen1778 , @Haleygo , please add support for DNS SRV urls at `vmalert`.

Can I get an update on the vmalert implementation? Thanks!

**Comment by Haleygo** [comment]
> > @hagen1778 , @Haleygo , please add support for DNS SRV urls at `vmalert`.
> 
> Can I get an update on the vmalert implementation? Thanks!

Hi, it should be included in the next release.

**Comment by valyala** [comment]
[vmalert](https://docs.victoriametrics.com/vmalert.html) supports [DNS SRV](https://en.wikipedia.org/wiki/SRV_record) addresses in `-datasource.url`, `-remoteWrite.url` and `-remoteRead.url` command-line flags starting from [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1). For example, `-remoteWrite.url=http://src+some-addr/foo/bar` . In this case `some-addr` is resolved into a random address under the corresponding DNS SRV record and is used for establishing connection to `-remoteWrite.url`.

Closing the feature request as done.
