### ISSUE TITLE
High requests and churn rate when writing metrics for /api/v1/import/prometheus in Pushgateway format

### ISSUE THREAD

**Issue by urupaud** [VictoriaMetrics/VictoriaMetrics#6059]
### Is your question request related to a specific component?

vminsert
vmstorage

### Describe the question in detail

Hi Team,

We have been using pushgateway to write application level metrics to prometheus. As we are currently migrating from Prometheus to Victoriametrics, we have started to write these metrics to /api/v1/import/prometheus in Pushgateway format as mentioned in [here](https://github.com/VictoriaMetrics/VictoriaMetrics?tab=readme-ov-file#how-to-import-time-series-data). However, after sometime, we've noticed that vmstorage have started to run out of space frequently (1TB would only last for a couple of weeks 😱 ) and when checked, we've noticed high requests and churn rate (new series over 24h) for /insert/{}/prometheus/api/v1/import/prometheus. This kinda behaviour was not there when we were using Pushgateway with Prometheus/M3DB. Could you please advise on this?

Thanks
![Screenshot 2024-04-03 at 16 03 35](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/35029043/80330d2f-c464-4374-b8f8-bf30264acc4a)
![Screenshot 2024-04-03 at 16 04 01](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/35029043/ed03fcc6-f62d-4697-9e4f-8151e77a86e2)
![Screenshot 2024-04-03 at 16 04 36](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/35029043/7451cd2d-f5f1-4c39-a83c-2dc1aede41c0)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/Troubleshooting.html
- [X] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey, @urupaud.
Did you check data in [Cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer), can you investigate with it what leads high churn rate?
Maybe you had some relabelings on Prometheus side and didn't setup them on VM.

**Comment by urupaud** [comment]
Hey @Amper 

Thanks for the info, I will check it.

Also, during the investigation, I've found out that Prometheus was scraping metrics from Pushgateway with an interval of 30secs, but I was unable to find a way to set some kind of interval for /insert/{}/prometheus/api/v1/import/prometheus [in the docs](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-import-time-series-data). Is this not possible with vminsert? 

[Prometheus-net libarary](https://github.com/prometheus-net/prometheus-net/blob/60e9106a83ff1274fec0022c37366f04822b1d1b/Prometheus/MetricPusherOptions.cs#L10) is writing metrics with an interval of 1 second, so I guess now the applications that use this library write to vminsert every second instead of with an interval of 30 seconds just like with Prometheus.

Thanks

**Comment by urupaud** [comment]
we can try to override the interval in [Prometheus-net libarary](https://github.com/prometheus-net/prometheus-net/blob/60e9106a83ff1274fec0022c37366f04822b1d1b/Prometheus/MetricPusherOptions.cs#L10), but just wanted to check with you guys before going with it

**Comment by Amper** [comment]
> Also, during the investigation, I've found out that Prometheus was scraping metrics from Pushgateway with an interval of 30secs, but I was unable to find a way to set some kind of interval for /insert/{}/prometheus/api/v1/import/prometheus [in the docs](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-import-time-series-data). Is this not possible with vminsert?

You are a bit confusing push/pull approaches in this case, you should read this docs about difference between [push model](https://docs.victoriametrics.com/keyconcepts/#push-model) and [pull model](https://docs.victoriametrics.com/keyconcepts/#pull-model): https://docs.victoriametrics.com/keyconcepts/#write-data

## In brief

There are two models of data collection for monitoring:
1. push model - when the application sends data to the monitoring system on its own with the frequency it requires
2. pull model - when the monitoring system polls (scrape) applications at a specified interval, writing data to DB

Prometheus supports pull model, but Pushgateway can adapt push model to pull model for prometheus:

```mermaid
graph LR;
    app1["App 1 with /metrics endpoint"]
    app2["App 2 with /metrics endpoint"]
    app3["App 3 with push"]
    app4["App 2 with push"]
    prom[(Prometheus)]
    pgw[[Pushgateway]]
    prom-- scrape app1 metrics -->app1;
    prom-- scrape app2 metrics -->app2;
    prom-- scrape app1 and app2 metrics -->pgw;
    app3-- push app3 metrics -->pgw;
    app4-- push app4 metrics -->pgw;
```

VictoriaMetrics (single or cluster) supports push model, but vmagent can adapt push model to pull model for VM:

```mermaid
---
title: First option
---
graph LR;
    app1["App 1 with /metrics endpoint"]
    app2["App 2 with /metrics endpoint"]
    app3["App 3 with push"]
    app4["App 2 with push"]
    vmdb[(VMDB)]
    vmagent[[vmagent]]
    vmagent-- scrape app1 metrics -->app1;
    vmagent-- scrape app2 metrics -->app2;
    app3-- push app3 metrics -->vmdb;
    app4-- push app4 metrics -->vmdb;
    vmagent -- push app1 and app2 metrics -->vmdb;
```

```mermaid
---
title: Second option
---
graph LR;
    app1["App 1 with /metrics endpoint"]
    app2["App 2 with /metrics endpoint"]
    app3["App 3 with push"]
    app4["App 2 with push"]
    vmdb[(VMDB)]
    vmagent[[vmagent]]
    vmagent-- scrape app1 metrics -->app1;
    vmagent-- scrape app2 metrics -->app2;
    app3-- push app3 metrics -->vmagent;
    app4-- push app4 metrics -->vmagent;
    vmagent -- push all metrics -->vmdb;
```

As you can see, vminsert (VMDB on scheme) does not control how often data is sent to it, this is done on the application side - as you wrote it should be done in the application/library parameters.

**Comment by urupaud** [comment]
Thanks a lot for the detailed explanation @Amper 🙏
