### ISSUE TITLE
After upgrade VictoriaMetrics to newest release observed 100% CPU usage

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#6069]
### Describe the bug

When upgrading the VictoriaMetrics cluster to v1.100 vmstorage starts to use 100% CPU 
<img width="829" alt="Screenshot 2024-04-05 at 12 12 31" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/dfbef91c-305e-481e-8355-5b41324aafb6">

The possible reason is that small merges start with a high number of active merges, but the speed of the merge stays the same.
<img width="1666" alt="Screenshot 2024-04-05 at 12 14 37" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/32d7ca6c-ab7c-436e-940c-4859738bb4c5">

tsid cache miss grow to 100%
<img width="844" alt="Screenshot 2024-04-05 at 12 15 44" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/12189570/aa69bd21-73cb-4c0f-9c55-beee3505a0af">

### To Reproduce

Upgrade the VictoriaMetrics cluster from version 1.99.0 to 1.100.0

### Version

[v1.100.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.100.0)

**Comment by f41gh7** [comment]
Most probably caused by https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5959

**Comment by hagen1778** [comment]
@dmitryk-dk @f41gh7 the issue should be addressed starting from [v1.101.0](https://docs.victoriametrics.com/changelog/#v11010) release. See related changes below:
> BUGFIX: [downsampling](https://docs.victoriametrics.com/#downsampling): skip unnecessary index lookups if downsampling wasn’t set for ENT versions of VictoriaMetrics. Before, users of VictoriaMetrics ENT could have experience elevated CPU usage even if no downsampling was configured. The issue was introduced in [v1.100.0](https://docs.victoriametrics.com/changelog/#v11000).

> BUGFIX: [downsampling](https://docs.victoriametrics.com/#downsampling): properly populate downsampling metadata for data parts created by VictoriaMetrics ENT versions lower than v1.100.0. The bug could trigger the downsampling actions for parts that were downsampled already. This bug doesn’t have any negative effect apart from spending extra CPU resources on the repeated downsampling. The issue was introduced in [v1.100.0](https://docs.victoriametrics.com/changelog/#v11000).
