### ISSUE TITLE
vmagent: service discovery support for OVH dedicated server and vps

### ISSUE THREAD

**Issue by jiekun** [VictoriaMetrics/VictoriaMetrics#6071]
### Is your feature request related to a problem? Please describe
[OVH](https://www.ovhcloud.com/en/) is a French cloud computing company which offers VPS, dedicated servers and other web services.

Currently, VictoriaMetrics does not support [service discovery](https://docs.victoriametrics.com/sd_configs/) of OVH resources.

### Describe the solution you'd like
Please consider adding support for service discovery of OVH. Here are some useful links:
1. API doc of OVH: https://api.ovh.com/
2. OVH go SDK: https://github.com/ovh/go-ovh
3. Prometheus provides SD support, including label defination: [<ovhcloud_sd_config>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ovhcloud_sd_config)

### Additional information

I am willing to implement this feature and submit a Pull Request. However, considering that there might be other newcomers interested, the following Pull Request can be referenced to see how to add a new service discovery:
1. https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5550
2. https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3840

**Comment by jiekun** [comment]
Please assign it to me If the maintainers consider that this feature is needed ^_^
(The previous pull request of SD is still in the review phase, so I believe the new SD support may not have high priority, tho.)

**Comment by hagen1778** [comment]
VictoriaMetrics now support [OVH Cloud service discovery](https://docs.victoriametrics.com/sd_configs/#ovhcloud_sd_configs) starting from [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040). Thanks to @jiekun for contributing this functionality!
