### ISSUE TITLE
VictoriaLogs often has too many active merges when OOM occurs.

### ISSUE THREAD

**Issue by kk-kwok** [VictoriaMetrics/VictoriaMetrics#6084]
### Describe the bug

same as this issue #5409 
VictoriaLogs often has too many active merges when OOM occurs.

### To Reproduce

always oom

### Version

The problem is the same when running v0.5.0-victorialogs and v0.5.1-victorialogs

### Logs

# pod logs:
{"ts":"2024-04-10T08:10:14.154Z","level":"info","caller":"VictoriaMetrics/lib/logstorage/datadb.go:487","msg":"merged (4 parts, 100453 rows, 250 blocks, 7747477 bytes) into (1 part, 100453 rows, 106 blocks, 7046140 bytes) in 35.096 seconds at 2862 rows/sec to \"/storage/partitions/20240410/datadb/17C4DCCA29195F5B\""}

{"ts":"2024-04-10T08:10:17.070Z","level":"info","caller":"VictoriaMetrics/lib/logstorage/datadb.go:487","msg":"merged (5 parts, 109434 rows, 281 blocks, 8551669 bytes) into (1 part, 109434 rows, 112 blocks, 7603337 bytes) in 35.937 seconds at 3045 rows/sec to \"/storage/partitions/20240410/datadb/17C4DCCA29195F64\""}

 {"ts":"2024-04-10T08:10:19.799Z","level":"info","caller":"VictoriaMetrics/lib/logstorage/datadb.go:487","msg":"merged (15 parts, 249121 rows, 696 blocks, 19369558 bytes) into (1 part, 249121 rows, 174 blocks, 16666908 bytes) in 62.125 seconds at 4009 rows/sec to \"\""}

# describe pod
(combined from similar events): System OOM encountered, victim process: systemd-udevd, pid: 3550

### Screenshots

![vl_active_merges](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/279eac84-0c0f-4c6f-b27b-c397198b9eb1)
![vl_memory](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/37f06289-0f78-4e6f-816b-55fd3b39ac99)

### Used command-line flags

      --retentionPeriod=1
      --storageDataPath=/storage
      --envflag.enable=true
      --envflag.prefix=VM_
      --loggerFormat=json
      --insert.maxFieldsPerLine=2000

### Additional information

pod resources:
    Limits:
      cpu:     16
      memory:  32Gi
    Requests:
      cpu:        16
      memory:     32Gi

**Comment by Haleygo** [comment]
Hello,
Can descreasing `cpu.request` or adding env `GOMAXPROCS` with smaller value in VictoriaLogs help to reduce the OOM?

**Comment by Haleygo** [comment]
Could you please share memroy profile when active merges happening? You can use [this](https://docs.victoriametrics.com/#profiling)doc as a reference, but substitude port for port of your VictoriaLogs instance.

**Comment by kk-kwok** [comment]
> Hello, Can descreasing `cpu.request` or adding env `GOMAXPROCS` with smaller value in VictoriaLogs help to reduce the OOM?

After reducing cpu.request and vector configuration batch.max_events, OOM no longer occurs. It works for me.
```yaml
    Limits:
      cpu:     16
      memory:  32Gi
    Requests:
      cpu:        8
      memory:     32Gi
```
![vl_active_merges](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/0c6d2ea5-5737-4b2a-bd27-7766e05f0a67)
![pod_resources](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/91448402-0224-412b-8ee1-ddd2ff678dea)

**Comment by kk-kwok** [comment]
> Hello, Can descreasing `cpu.request` or adding env `GOMAXPROCS` with smaller value in VictoriaLogs help to reduce the OOM?

After reducing cpu.request and vector configuration batch.max_events, OOM no longer occurs. It works for me.
```yaml
    Limits:
      cpu:     16
      memory:  32Gi
    Requests:
      cpu:        8
      memory:     32Gi
```
![vl_active_merges](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/0c6d2ea5-5737-4b2a-bd27-7766e05f0a67)
![pod_resources](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/91448402-0224-412b-8ee1-ddd2ff678dea)

**Comment by kk-kwok** [comment]
> Hello, Can descreasing `cpu.request` or adding env `GOMAXPROCS` with smaller value in VictoriaLogs help to reduce the OOM?

After reducing cpu.request and vector configuration batch.max_events, OOM no longer occurs. It works for me.
```yaml
    Limits:
      cpu:     16
      memory:  32Gi
    Requests:
      cpu:        8
      memory:     32Gi
```
![vl_active_merges](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/0c6d2ea5-5737-4b2a-bd27-7766e05f0a67)
![pod_resources](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4901238/91448402-0224-412b-8ee1-ddd2ff678dea)

**Comment by valyala** [comment]
FYI, it is recommended upgrading VictoriaLogs to the [latest available release](https://docs.victoriametrics.com/victorialogs/changelog/).
