### ISSUE TITLE
VictoriaLogs: Is there a good way to export logs of several hundred MB

### ISSUE THREAD

**Issue by dw130** [VictoriaMetrics/VictoriaMetrics#6108]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

Hi：
    My scence is export log for hundred MB
    use http function means server return  500 MB contents
    Is there a good way to do this？

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by Amper** [comment]
Hey @dw130.
AFAIK, right now there is no way to export data from VMLogs except using [http API](https://docs.victoriametrics.com/victorialogs/querying/#http-api).
