### ISSUE TITLE
automagically add group as a label in vmalert

### ISSUE THREAD

**Issue by cskinfill** [VictoriaMetrics/VictoriaMetrics#611]
**Is your feature request related to a problem? Please describe.**
I would like to be able to select something like `ALERTS{alertstate="firing", group="apps"} == 1` to get just those alerts related to the "apps" group.

**Describe the solution you'd like**
Each alert fired and sent to alertmanager or recorded back to the metric store includes a "group=<group>" label

**Describe alternatives you've considered**
Explicitly adding this to each alert by hand, but this seems like needless duplication.

**Comment by hagen1778** [comment]
Hi @cskinfill! Group name is now added as label to generated alerts and time series. Pls see https://github.com/VictoriaMetrics/VictoriaMetrics/commit/6ad6480400302e736886431d04b0626ef4afa213
You can verify it by [building](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert#how-to-build-from-sources) `vmalert` from sources. The change will be also included in next release.

**Comment by valyala** [comment]
FYI, the commit mentioned by @hagen1778  has been included in vmalert [v1.41.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
