### ISSUE TITLE
feat: vmagent: auto metrics for the size of scraped body

### ISSUE THREAD

**Issue by umezawatakeshi** [VictoriaMetrics/VictoriaMetrics#6123]
### Is your feature request related to a problem? Please describe

I want a way to detect oversized metrics before being rejected by `-promscrape.maxScrapeSize` limit. It is too late to detect it by `vm_promscrape_max_scrape_size_exceeded_errors_total` since the oversized metrics are already dropped at the moment.

### Describe the solution you'd like

I want a automatically generated metrics that represents the size of scraped body. The name of the metrics should preferably be `scrape_body_size_bytes`, same as that of Prometheus's extra scrape metrics https://prometheus.io/docs/prometheus/latest/feature_flags/#extra-scrape-metrics .

I already have a very rough implementation https://github.com/cybozu-go/VictoriaMetrics/commit/5d7c78dcf0a55e43fb1dabe396a29ce617f8b819 .
However,
- I'm not sure that it is complete,
- It doesn't have tests, and
- It would be nice if the body size is also reported on `/targets` and `/api/v1/targets` endpoint response.

**Comment by AndrewChubatiuk** [comment]
hey @umezawatakeshi 
Merged [PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6434) which ability to set max_scrape_size in scrape config for each job and also added autometric, which tracks amount of scraped data in bytes

**Comment by hagen1778** [comment]
Starting from [v1.102.0-rc2](https://docs.victoriametrics.com/changelog/#v11020-rc2) vmagent [generates](https://docs.victoriametrics.com/vmagent/#automatically-generated-metrics) `scrape_response_size_bytes` for each scraped target.

**Comment by umezawatakeshi** [comment]
@AndrewChubatiuk 
Thank you very much 👍

**Comment by valyala** [comment]
See the related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6429
