### ISSUE TITLE
No -cluster tag for v1.97.3 LTS release

### ISSUE THREAD

**Issue by miljank** [VictoriaMetrics/VictoriaMetrics#6125]
### Describe the question in detail

Hi,

I've already found issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5811 and I'm wondering if that impacts cluster LTS releases as well? I see that `v1.97.1-cluster` tag is present in Github repository, but `v1.97.3-cluster` is missing.

Thanks
Miljan

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
HI @miljank ! Related to this [comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5811#issuecomment-1946065612) all LTS releases will be published as enterprise.

You can find cluster enterprise version in this [release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.3)

**Comment by miljank** [comment]
Any chance that you can tag the repo as well?

**Comment by dmitryk-dk** [comment]
> Any chance that you can tag the repo as well?

This is that version https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.93.7 not v1.97.3. 
The last LTS release is v1.93.7 and another release will be enterprise.

```
P.S. The v1.93.x LTS release will receive updates for both open-source and enterprise versions until July 2024.
```

**Comment by miljank** [comment]
Thanks, all clear.
