### ISSUE TITLE
"go back" button in browser doesn't work properly with VMUI

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/VictoriaMetrics#6126]
### Describe the bug

The browser "go back" button doesn't work properly after time range change.

### To Reproduce

1. Open [play.victoriametrics.com](https://play.victoriametrics.com/select/0/vmui/#/?g0.expr=sum%28up%29&g0.range_input=30m&g0.end_input=2024-04-17T07%3A45%3A32&g0.tab=0&g0.relative_time=last_30_minutes&g0.tenantID=0)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/6b91fb64-7838-43ea-a5a5-6dc8e212f663)

2. Change the interval to `` -> `` and click "Apply":

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/7038acbd-a9f0-40cf-9e66-d45b2c6ee14c)

3. Click "Go back" in your browser:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/495795/f2c28ca7-bf42-4351-990b-a70ea77983c2)

*We don't see the previous screen*.

The same result with "Zoom in".

### Version

any

**Comment by hagen1778** [comment]
@Loori-R I think this issue is also related to this problem described in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5516#issuecomment-1867507232).

**Comment by valyala** [comment]
The issue has been fixed in [v1.97.5 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.97.5) and in [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).
