### ISSUE TITLE
VictoriaLogs: how to get all fields name, how to get log rows count, how to know get storage usage and disk compress ratio? 

### ISSUE THREAD

**Issue by shuaiyy** [VictoriaMetrics/VictoriaMetrics#6128]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

Q1:  how to get all fields name ?

I need to know the exact file name before writing a search query,

Q2: how to count log rows ?

just want to konw how many logs  are ingested into vlogs.

Q3: how to get storage usage and disk compress ratio ?  

is vlogs provide some system stats info, this is very helpful for us in selecting the log system architecture.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/Troubleshooting.html
- [ ] vmagent - https://docs.victoriametrics.com/vmagent.html#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert.html#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @shuaiyy !

1. there is an issue for that improvement https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4918 please follow it
2. you can count it via the request `curl http://localhost:9428/select/logsql/query -d 'query=*' -d 'limit=10000' | wc -l`
 or use metrics `sum(vl_storage_rows{job=~"$job", instance=~"$instance"})`
3. I think you can calculate disk usage via `du -sh file_path` where `file_path` the storage file path
but that would be copressed size
```
 sum(vl_uncompressed_data_size_bytes{job=~"$job", instance=~"$instance"})  - uncompressed sum(vl_compressed_data_size_bytes{job=~"$job", instance=~"$instance"}) - compressed
 ```

**Comment by dmitryk-dk** [comment]
Hi @shuaiyy ! Can we close an issue as resolved?
