### ISSUE TITLE
vmauth doesn't help spreading loads for vminsert instances

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#6136]
### Is your feature request related to a problem? Please describe

It's recommended to [put vmauth in front of vminsert nodes in vmcluster,](https://docs.victoriametrics.com/vmauth/#load-balancer-for-victoriametrics-cluster) to spread requests among the instances using `least-loaded` round-robin policy.
Compare to k8s service, vmauth should perform better because it doesn't just using `round-robin` between backend pods, but also take into account the load of each backend instance through the current ongoing requests, eg, one backend instance needs more time to process one big request, while another instance got small requests and returned quick, then the next request will still go to the second instance.

But it doesn't work well now from the test:

1. use k8s service
<img width="1402" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/24b97ea5-f99d-44c2-8907-3f53aa00ac08">

2. set up vmauth with 2 replicas
<img width="1414" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/b71d47c9-36ab-423b-aa6d-f88f07c824fd">

3. reduce vmauth replicas from 2 to 1
<img width="1404" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/b8ea989b-2352-41eb-92bb-d3a3c28313ea">

ps. 90% of the requests cause about the same load
<img width="1416" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/abc03aa6-562f-44be-9dba-7bf7ca8fb5e6">

Compare 1&2, no such difference between using k8s service and vmauth, cpu usage between vminsert instances still uneven;
Compare 2&3, using only one vmauth reduces the time to re-balance the usage( usage gap last longer when having multiple vmauth), as vmauth instances could do things differently cause they don't know about each other.

### Describe the solution you'd like

vmauth help balancing the loads for vminsert instances better.

**Comment by hagen1778** [comment]
@Haleygo, according to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6144, the balancing policy works as expected. Do you have ideas why it doesn't show itself useful in your experiment?
