### ISSUE TITLE
vmagateway: ingestion stops if qps limit reached 

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6148]
### Describe the bug

 ingestion stops if qps limit reached 

### To Reproduce

setup low ingestion rate and qps for vmgateway rate limiting, reach qps limit see ingestion 

### Version

100.1

**Comment by radociech** [comment]
The same occurs in reverse: if the ingestion limit is reached, the query is restricted. Please refer to the log from vmalert below.

`2024-04-22T10:20:49.395Z        error   VictoriaMetrics/app/vmalert/group.go:298        group "nodeexporter": rule "HostClockNotSynchronising": failed to execute: failed to execute query "min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16": unexpected response code 429 for http://vmgateway-victoria-metrics-gateway.vm.svc.cluster.local:8431/select/0/prometheus/api/v1/query?query=min_over_time%28node_timex_sync_status%5B1m%5D%29+%3D%3D+0+and+node_timex_maxerror_seconds+%3E%3D+16&step=300s&time=1713781200. Response body request was rate limited by: "inserted rows limit reached"`

**Comment by tenmozes** [comment]
should be fixed in the next ENT release (102 or 103)

**Comment by valyala** [comment]
The bugfix for this issue has been included in [v1.102.0 release](https://docs.victoriametrics.com/changelog/). Closing it then.
