### ISSUE TITLE
vmui: auto-complete doesn't work properly after `{` if there is no metric name in front of `{`

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#6153]
### Describe the bug

Auto-complete should show the list of label names across all the time series if the cursor is located just after `{` and there is no metric name in front of `{`. For example, `{<cursor_here>`, `{ins<cursor_here>` or `{job="foo", ins<cursor_here>`.

It also queries incorrect information form VictoriaMetrics for the auto-completion of label values if there is no metric name in front of `{`. For example, `{job="<cursor_here>`. It should return the list of jobs across all the time series in this case, e.g. it should send the request to `/api/v1/label/job/values?start=...&end=...` without specifying `match[]` query arg. Note that the `match[]` query arg must be set to label filters specified between `{` and the current cursor position. For example, if the query input field contains `{job="foo", instance="<cursor_here>`, then `vmui` should request `/api/v1/label/instance/values?start=...&end=...&match[]={job="foo"}`.

### To Reproduce

1. Go to https://play.victoriametrics.com/
2. Enable auto-complete mode
3. Type `{` in the query input

It is expected that auto-complete shows the list of all the labels across all the time series on the selected time range, e.g. `vmui` must send the request to `/api/v1/labels?start=...&end=...` without `match[]` query arg in this case.

Now it mistakenly sets the `match[]` query arg to `__name__="label_name_prefix"` where `label_name_prefix` is the prefix written after `{`. For example, it sets `match[]` query arg to `{__name__="ins"}` if the query input field contains `{ins<cursor_here>`.

### Version

The latest available commit in the `master` branch

### Additional information

Related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5866

**Comment by hagen1778** [comment]
@valyala auto-complete enhancements were added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6566 and will be included into the next release.

**Comment by f41gh7** [comment]
this bug should be fixed in [v1.102.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.1).

feel free to reopen if you still observe issue
