### ISSUE TITLE
[vmagent] flushInterval and other options doesnt work for individual remoteWriteURL

### ISSUE THREAD

**Issue by k1rk** [VictoriaMetrics/VictoriaMetrics#616]
**Describe the bug**
When you try to specify options like `-remoteWrite.flushInterval`,`-remoteWrite.maxBlockSize`, `-remoteWrite.maxDiskUsagePerURL`, `-remoteWrite.queues`, `-remoteWrite.sendTimeout`, `-remoteWrite.showURL`, `-remoteWrite.tmpDataPath` for multiple `remoteWrite.url` its doesn't work

if you specify them separately like 
```
vmagent -remoteWrite.url=http://vm2:8429/api/v1/write -remoteWrite.queues=2 -remoteWrite.url=http://vm3:8430/api/v1/write -remoteWrite.queues=3
```
only last one will be used

if you specify them in one flag divided by coma 
```
vmagent -remoteWrite.url=http://vm2:8429,http://vm3:8430 -remoteWrite.queues=1,2
```
it fails with `invalid value "1,2" for flag -remoteWrite.queues: parse error`

while for `basicAuth`, `bearerToken`, `urlRelabelConfig` everything works as expected

and for labels situation a bit different. all the labels applied to all urls

**To Reproduce**
```
vmagent -remoteWrite.url=http://vm2:8429/api/v1/write -remoteWrite.queues=2 -remoteWrite.url=http://vm3:8430/api/v1/write -remoteWrite.queues=3
```
or 
```
vmagent -remoteWrite.url=http://vm2:8429,http://vm3:8430 -remoteWrite.queues=1,2
```

**Expected behavior**
flags parsed correctly and different configuration applied for different urls

**Version**
```
$ ./vmagent--version
vmagent-20200605-194106-tags-v1.37.0-cluster-0-g9f55dea16
```
and 
```
$ ./vmagent--version
vmagent-20200708-180352-tags-v1.38.0-cluster-0-g418f0e46c
```

**Comment by hagen1778** [comment]
Hi @k1rk! Looks like it is by design, since listed flags are `global` and applied to every configured remotewrite.url. I agree, that it is unclear from flags description whether they support array of values or not. Pls see this inconvenience addressed here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/620

**Comment by k1rk** [comment]
oh, you right. 
my bad, missed this
