### ISSUE TITLE
Enhancement to search.maxUniqueTimeseries and indexdb population for long interval time series

### ISSUE THREAD

**Issue by jduncan0000** [VictoriaMetrics/VictoriaMetrics#6170]
### Is your feature request related to a problem? Please describe

I have several metrics that are created by recording rules that run on an interval of 3 hours. The interval is long since these metrics do not change often and I did not want to duplicate the samples unnecessarily. I noticed that after some time, queries to search for these metrics over long time ranges began failing due to exceeding the `-search.maxUniqueTimeseries` value (using the default of `300000`) even though the actual cardinality of the labels on each metric amounts to less than `5000` unique series.

After some research, I believe I understand why this is happening and would like to outline my scenario and see if there is a solution that would reduce the seemingly artificial growth I am seeing on metricIDs for these metrics.

The reason for this behavior seems to be the code that is pre-populating the next day's per-day inverted index:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5f487c7090e99654a55fc8429ffd9dc514c5bc46/lib/storage/storage.go#L2167-L2187

This code has two aspects that are important here:

1. It only pre-populates the next day index during the last hour of the UTC day (meaning time series' that are not recorded in this hour time frame are not carried forward and presumably are assigned a new metricID each day).
2. The pre-population appears to only be done if the metricID being recorded is found in the current hour cache (fast-path). Meaning ( I believe) that time series' have to be recorded at least twice in this hour to be carried forward.

Hence, most time series with a > `30m` interval will be assigned a new metricID each day, each counting against the `-search.maxUniqueTimeseries` limit.

While I can temporarily resolve this issue by increasing the `-search.maxUniqueTimeseries` limit, I have a long (5+ year) retention on this data and am seeing the count of metricIDs in the indexdb continue to grow daily, even though the actual unique time series count/cardinality is not increasing. 

### Describe the solution you'd like

From my analysis of the code, I see a few potential opportunities that could help with my use case (admittedly, I may be missing some important aspects of the design so please let me know if these solutions are not viable or if any of my analysis is incorrect.)

1. One idea would be to introduce a new configuration flag that would allow users to adjust the window of time in which we pre-populate the next day indexdb. With this solution, in instances with many long interval time series, the window of time could be extended a bit (for example, to 3 hours in my case) and these longer interval series could maintain a single metricID over multiple days.
2. Update the code to ensure that all metric samples that are ingested during this window are pre-populated to the next day index, not just those that are found in the current hour cache/using fast path. This would ensure that metrics do not have to be seen twice in the time window in order to be pre-populated.

I am hoping the VictoriaMetrics team may have other ideas to improve upon these; this is simply a user's analysis of the scenario. Thank you for your time. 

### Describe alternatives you've considered

I considered the following alternatives:

- Decreasing the interval of recording these metrics. 
  - This is possible, but given that these metric values do not change often and that we view them over long periods of time (years), we can run into other limits such as exceeding the maximum sample limit.
  - Additionally, some of these metrics are sourced from a batch process that does not run more often than every few hours.
- Increasing the `-search.maxUniqueTimeseries` limit
   - This tactically resolved my issue but may not be viable in the long term, as I will need to increase this to well over 2.5 million given the current growth rate I see and can run into other limits such as query duration limit.
- Changing the recording rules to run on an offset that would ensure they run in the final hour of the day
  - This did not change the behavior since the metrics were still not being recorded twice within the hour

**Comment by jduncan0000** [comment]
Anyone have a chance to look at this one? I was hopeful for a response. Thank you!

**Comment by hagen1778** [comment]
Thanks for the detailed description and analysis. 

I think we're hitting a corner case here, because VictoriaMetrics is usually used for telemetry that is updated at least once in interval between 1s and 5m. Everything below or above this interval is a corner case.

> One idea would be to introduce a new configuration flag that would allow users to adjust the window of time in which we pre-populate the next day indexdb.

While this would be the simplest solution, I don't really like it because the chances are you'll be the only user of this new flag. While we're in a constant fight with increasing complexity of the project, I'm taking the position of resisting any changes that aren't essential or can't have a workaround.

> Update the code to ensure that all metric samples that are ingested during this window

The logic is based on premise that we want to migrate to new day only those metrics which were recently active. This is important because usually in infra monitoring or APM metrics have [high churn rate](https://docs.victoriametrics.com/faq/#what-is-high-churn-rate). Moving all metrics from this day to a new day will have very negative snowballing effect, bloating the indexes more and more with every day. And this would be a negative change for 99% of users, according to my understanding of end users.

> This is possible, but given that these metric values do not change often and that we view them over long periods of time (years), we can run into other limits such as exceeding the maximum sample limit.

That might be the easiest solution, to be fair. The default limit to max samples is 1Bil. So 5k series updated every 3h will generate you 40k samples a day, 14.4Mil samples a year, 72mil samples per 5y. 
If you change RRs to update every 30min, then it will be 86Mil samples per year, 430Mil samples per 5y. Still below the default limit of 1Bil samples per query.

**Comment by jduncan0000** [comment]
Thank you for the detailed response. Understood about being a corner case - we will try proceeding with more frequent intervals.

**Comment by kpaschen** [comment]
Just for the record in case anyone's keeping count: I would also like to be able to use VictoriaMetrics with a large number of infrequently-updated time series.

If there's enough interest, would it be possible to plan support for a configuration flag such as was suggested above?

**Comment by hagen1778** [comment]
Hello @kpaschen! Thanks for bringing it up!

>  I would also like to be able to use VictoriaMetrics with a large number of infrequently-updated time series.

I think this already should be possible with https://docs.victoriametrics.com/#index-tuning-for-low-churn-rate:
> if your use case assumes low or no churn rate, then you might benefit from disabling the per-day index by setting the flag -disablePerDayIndex. This will improve the time series ingestion speed and decrease disk space usage, since no time or disk space is spent maintaining the per-day index.

However, this setting is global. It can't be applied for a subset of series. And it is ideal for low-churn rate metrics.
