### ISSUE TITLE
Slow inserts remain high, although the churn rate and the number of active series have decreased

### ISSUE THREAD

**Issue by escapekyg** [VictoriaMetrics/VictoriaMetrics#6176]
### Is your question request related to a specific component?

vmstorage, slow insert

### Describe the question in detail

Previously, our vmstorage experienced high levels of churn rate, active timeseries, and slow inserts, which often led to out-of-memory (OOM) issues. Recently, we did the following to improve:
1.upgraded our machine's memory from 64GB to 128GB 
2.stopped ingesting some metrics with frequently changing label values. 
3.added commanline flag -storage.maxDailySeries=1500000

Now, we observed the cardinality explorer, we have many series, as well as labels with a high number of values that are indeed necessary to ingest. Puzzlingly, although the churn rate and active timeseries have decreased, the slow inserts remain high. Is there a way to more accurately identify which series are causing the slow inserts to remain high, or if there are other underlying reasons? Thank you!
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/50529145-c87e-47d6-b01b-43b8b5bcf3f0)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/9a3f63f7-a9e1-40b3-b4e2-a6f12b4d0615)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/983417c3-f8de-4288-bf5c-bb34c8c97c78)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/f583589f-548f-4705-88e9-81a579665f7c)

we use version 1.100.1
we deploy a cluster with 3 machines, each machine has vminsert/vmselect/vmstorage, commanline for each machine:
./vmstorage -storageDataPath=/data/victoriaMetrics -httpListenAddr=10.0.0.1:18000 -vminsertAddr=10.0.0.1:18001 -vmselectAddr=10.0.0.1:18002 -storage.cacheSizeStorageTSID=1GB -storage.cacheSizeIndexDBDataBlocks=1GB -storage.cacheSizeIndexDBIndexBlocks=1GB -bigMergeConcurrency=8 -storage.maxDailySeries=1500000 -search.maxUniqueTimeseries=2000000 -retentionPeriod=1y
./vminsert -replicationFactor=2 -httpListenAddr=10.0.0.1:18004 -storageNode=10.0.0.1,10.0.0.2,10.0.0.3
./vmselect -replicationFactor=2 -cacheDataPath=/vm/tmp -httpListenAddr=10.0.0.1:18003 -dedup.minScrapInterval=15s -storageNode=10.0.0.1,10.0.0.2,10.0.0.3

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
Hello @escapekyg!

> Puzzlingly, although the churn rate and active timeseries have decreased, the slow inserts remain high

Slow inserts aren't always a sign of churn rate, it could be a sign of insufficient tsid cache size. See also SlowInserts panel description:
> The percentage of slow inserts comparing to total insertion rate during the last 5 minutes.
The less value is better. If percentage remains high (>10%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of [active time series](https://docs.victoriametrics.com/faq/#what-is-an-active-time-series).
In general, VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to capacity planning docs. But the resulting number may be far from the real number because the required amounts of memory depends on many other factors such as the number of labels per time series and the length of label values. See also [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3976#issuecomment-1476883183) for details.

> Is there a way to more accurately identify which series are causing the slow inserts to remain high

New series can be detected via the following flag:
>  -logNewSeries
     Whether to log new series. This option is for debug purposes only. It can lead to performance issues when big number of new series are ingested into VictoriaMetrics

Or by comparing days in Cardinality explorer (the green number shows change of series for a metric name comparing to prev day):
<img width="197" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/76073522-578f-49ee-b0e6-334e1e72c82b">

> 1.upgraded our machine's memory from 64GB to 128GB

As I said in previous issue, I find it very disturbing that you need 3 vmstorages with 128GiB of mem each to handle 1Mil of Active Time series. Normally, this won't require more than 10GiB in total.
I'd start investigating why the memory usage is so high. I remember you shared memory profile in previous issue, but I didn't have time to check it yet. I'll let you know once I have any updates.

**Comment by escapekyg** [comment]
Hello @hagen1778 ! Thanks for reply !

> vmstorage CPU and memory usage
> vmstorage Active merges and Merge speed
> vmstorage Disk space usage % and usage by type %
> vmstorage LSM parts by type

The following are the respective screenshots of one node of the cluster, along with other important panels. After we added -storage.maxDailySeries=1500000, the size of the indexdb file seems to have stopped increasing; it has stayed at 30GB in recent days.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/9b80da8e-2654-4d92-a062-4284e527c4a9)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/582147d9-d0ec-4762-a7d4-4d643255e07a)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/0a481a13-571d-4579-8f05-08b30e246d64)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/182b5893-629d-411e-8701-1e4c1505f180)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/51df0d8a-251c-47bc-bc6c-809f43bbcd78)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/9416eadb-d670-4713-a1ba-86ae5e40f6a4)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/f2a60d8e-9b5c-4730-88f3-6a29407326b7)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/56d51299-9a32-4098-81c9-ce220146c35b)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/4f358f99-3372-4859-8bb7-40057b60067f)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/157368221/30c5a737-87bc-4488-ae87-75e61c3a5014)

**Comment by perederyaev** [comment]
Hi, this looks similar to my issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6198 .
When VM gets new timeseries with null values - it doesn't insert them and shows them like slow inserts and cache misses.

**Comment by hagen1778** [comment]
@escapekyg can I ask you to execute the following cmd for one of the vmstorage data folders?
```
ls -hs vmstorage-data/indexdb/*/* | grep metaindex.bin
```

**Comment by escapekyg** [comment]
Hello @hagen1778 ! thanks for your reply again!

**Comment by escapekyg** [comment]
Hello @hagen1778 ! Thanks for your reply again!

> Would be great if you could try writing the same info to the new VM installation, just for test. You could even try running VM single, for your workload it seems like one VM single with 4vCPU and 16GiB of mem will do.
> If the new installation will show the same level of mem usage - please, show me the example data you write into it.

The data is in our customer's environment, we can't frequently access it, and it's hard to simulate the data like customer's. 

> can I ask you to execute the following cmd for one of the vmstorage data folders?

[metaindex.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/15272220/metaindex.txt)
The cmd result is in attachment file, thank you!

**Comment by f41gh7** [comment]
I think an issue related to the design of metaindex. In case, when index records have large entities ( > 20k bytes). VictoriaMetrics may consume extra memory for storing metaindex.

 Usually, the size of metrics are relatively small. But if there are a lot of metrics with huge label values size, it increases chance of bloat metaindex size. 

it also give a chance, that during indexdb merge process it ll require x2 memory and cause immediate OOM.

**Comment by hagen1778** [comment]
In other words, you experience so high mem usage because of labels with big size. In order to reduce memory usage, one shouldn't have very long labels. If you avoid having that, the memory usage will drop significantly for your cluster. The best way would be to get rid of time series with too wide labels and re-ingest data again in a fresh cluster to cleanup the indexes.

We'll try to patch VM to avoid this problem in future. Maybe by limiting the max label size, or by re-thinking the metaindex.bin structure. But the fastest way to mitigate the issue would be as described above.

**Comment by escapekyg** [comment]
@hagen1778 @f41gh7 Thank you! It's collecting metrics from a container environment, the labels, such as pod, id, name, image, etc., are quite long.
Also, I am still trying to figure out why the rate of slow inserts remains high. I added the -logNewSeries=true flag to the command line, but the number of new series over 15 minutes is only several hundred, significantly lower than what vm_slow_row_inserts_total indicates. Could this issue be related to the excessively long labels? Is it possible to increase the memory allocated to the TSID index to reduce cache misses?

**Comment by hagen1778** [comment]
> It's collecting metrics from a container environment, the labels, such as pod, id, name, image, etc., are quite long.

Could you provide an example of too long labels, because what you say is normal labels. The labels that could be a concern are more than 1KB size or if one time series has many labels of that size.

**Comment by hagen1778** [comment]
> Also, I am still trying to figure out why the rate of slow inserts remains high. I added the -logNewSeries=true flag to the command line, but the number of new series over 15 minutes is only several hundred, significantly lower than what vm_slow_row_inserts_total indicates. 

This could be related to this comment https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6176#issuecomment-2080069779

Do you collect metrics via vmagent?

**Comment by escapekyg** [comment]
@hagen1778 
> Could you provide an example of too long labels, because what you say is normal labels. The labels that could be a concern are more than 1KB size or if one time series has many labels of that size.

I check some of them, I think it's possbile to have some metrics which are over 1kb, for example, the lable value of image is sha256 hash value, and they have multi labels with long length

> This could be related to this comment https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6176#issuecomment-2080069779

ok, I will check this next week in customer's environment.

> Do you collect metrics via vmagent?
No, we don't

**Comment by escapekyg** [comment]
@hagen1778 @perederyaev is there any way to find out the specific series cause slow inserts?

**Comment by escapekyg** [comment]
> > Also, I am still trying to figure out why the rate of slow inserts remains high. I added the -logNewSeries=true flag to the command line, but the number of new series over 15 minutes is only several hundred, significantly lower than what vm_slow_row_inserts_total indicates.
> 
> This could be related to this comment [#6176 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6176#issuecomment-2080069779)
> 
> Do you collect metrics via vmagent?

Hello @hagen1778 ! Today, I reviewed the customer's metric data and found that there were no metrics with null values. I used -logNewSeries to log the new series, but they represent a very small percentage of the total number of inserts. Could it be possible that many inserts miss the TSID cache?

Now the machines still have sufficient free memory, I haven't configured -storage.cacheSizeStorageTSID, so theoretically, there should be no limit on the TSID cache size?

**Comment by f41gh7** [comment]
Recommended settings to minimize memory footprint:
```
-maxLabelValueLen=512
-maxLabelsPerTimeseries=30
```
 After applying changes, it requires full indexdb rotation to decrease memory usage. Basically it's a value of retentionPeriod flag.

Current indexdb architecture stores all sparse indexes in-memory. It may use a lot of memory, if metrics have huge label values. Potentially, it could be solved by migration to the partitioned indexdb (monthly,daily). But there is no such plans for now.

**Comment by escapekyg** [comment]
> Recommended settings to minimize memory footprint:
> 
> ```
> -maxLabelValueLen=512
> -maxLabelsPerTimeseries=30
> ```
> 
> After applying changes, it requires full indexdb rotation to decrease memory usage. Basically it's a value of retentionPeriod flag.
> 
> Current indexdb architecture stores all sparse indexes in-memory. It may use a lot of memory, if metrics have huge label values. Potentially, it could be solved by migration to the partitioned indexdb (monthly,daily). But there is no such plans for now.

Thanks @f41gh7 ! We will consider your advice. But now the memory is sufficient, and the churn rate is low, but the slow inserts is still above 30%,  is this also related to the long label?

**Comment by f41gh7** [comment]
> > Recommended settings to minimize memory footprint:
> > ```
> > -maxLabelValueLen=512
> > -maxLabelsPerTimeseries=30
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After applying changes, it requires full indexdb rotation to decrease memory usage. Basically it's a value of retentionPeriod flag.
> > Current indexdb architecture stores all sparse indexes in-memory. It may use a lot of memory, if metrics have huge label values. Potentially, it could be solved by migration to the partitioned indexdb (monthly,daily). But there is no such plans for now.
> 
> Thanks @f41gh7 ! We will consider your advice. But now the memory is sufficient, and the churn rate is low, but the slow inserts is still above 30%, is this also related to the long label?
 

 Regarding slow inserts. You changed value for `-storage.cacheSizeStorageTSID=1GB`. It may trigger slow insert, if current size of TSID cache isn't enough for your ingestion rate. I'd recommend to use default value or adjust it for your needs. Check Troubleshooting grafana panel for insights.

**Comment by escapekyg** [comment]
> > > Recommended settings to minimize memory footprint:
> > > ```
> > > -maxLabelValueLen=512
> > > -maxLabelsPerTimeseries=30
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > After applying changes, it requires full indexdb rotation to decrease memory usage. Basically it's a value of retentionPeriod flag.
> > > Current indexdb architecture stores all sparse indexes in-memory. It may use a lot of memory, if metrics have huge label values. Potentially, it could be solved by migration to the partitioned indexdb (monthly,daily). But there is no such plans for now.
> > 
> > 
> > Thanks @f41gh7 ! We will consider your advice. But now the memory is sufficient, and the churn rate is low, but the slow inserts is still above 30%, is this also related to the long label?
> 
> Regarding slow inserts. You changed value for `-storage.cacheSizeStorageTSID=1GB`. It may trigger slow insert, if current size of TSID cache isn't enough for your ingestion rate. I'd recommend to use default value or adjust it for your needs. Check Troubleshooting grafana panel for insights.
> 
> Also, unsorted labels may trigger slow insert. It could happen, if client doesn't follow requirement for metric sorting. You can enforce sorting with flag `sortLabels` at vminsert.

Thank you! We had already removed `-storage.cacheSizeStorageTSID` before, but it didn't work. Now we use `sortLabels`, and the slow inserts have significantly decreased.

**Comment by valyala** [comment]
FYI, the default value for `-maxLabelValueLen` command-line flag has been reduced from 16KB to 1KB starting from [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).

**Comment by valyala** [comment]
FYI, the default value for `-maxLabelValueLen` command-line flag has been increased from 1KiB to 4KiB in the commit e3d5714f6fd4e0eb7767258b3d8deffa1dda82fc , since it has been appeared that Kubernetes monitoring can generate labels longer than 1KiB by default.

**Comment by alirezaghey** [comment]
On a vmsingle instance with about 10 million active time series, an ingestion rate of about 300k/s, with 80Gi memory (memory.allowedPercent set to 90) and 7vCPU, we had consistent slow inserts around 20 to 30 percent. We were considering dropping metrics and/or reduce cardinality by removing labels, etc.

Setting `sortLabels` to true, reduced the slow inserts rate to much below 1% consistently and reduced memory and cpu usage. tsid cache misses are almost none existent.

It may be helpful to have this setting as a default or at least document it somewhere prominently.

**Comment by makasim** [comment]
@alirezaghey, thanks for highlighting this. I’ve added a note about `sortLabels` to the [Troubleshooting](https://docs.victoriametrics.com/victoriametrics/troubleshooting/#slow-data-ingestion)  section in commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ebad7e5496882ec59e6b74a3ee7c648a126f886e
