### ISSUE TITLE
vmui: query trace fails to expand on mouse click

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6186]
### Describe the bug

The first generated query trace in VMUI can't be expanded on mouse click.

### To Reproduce

1. Open https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=sum%28http_total%5B1m%5D%29&g0.range_input=30m&g0.end_input=2024-04-25T08%3A17%3A39&g0.tab=0&g0.relative_time=last_30_minutes
2. Execute the query
3. Enable QueryTrace option
4. Execute the query again
5. Try expanding the received query trace by clicking on it

### Version

v1.100.1

**Comment by valyala** [comment]
The bug has been fixed in [v1.102.0-rc1 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).
