### ISSUE TITLE
VMUI search indexes exception

### ISSUE THREAD

**Issue by luweijun1992** [VictoriaMetrics/VictoriaMetrics#6193]
### Describe the bug

For some metrics, I need to delete all characters and re-enter them before vmui will display them.

### To Reproduce

For some metrics, I need to delete all characters and re-enter them before vmui will display them.
---
![vmui](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/58923704/d4816f5a-f1ea-4516-9dcf-346f12ace71b)
---
![prometheus](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/58923704/55525fc6-dcc0-4943-abc7-96f83f56ce69)

### Version

victoria-metrics-20240425-145715-tags-v1.101.0-0-g5334f0c2c

**Comment by luweijun1992** [comment]
When will the bug be fixed?

**Comment by luweijun1992** [comment]
@Loori-R

**Comment by Loori-R** [comment]
Hi @luweijun1992

Thanks for reporting the bug. We're currently focused on other high-priority tasks, so we can't give an exact timeline for the fix, but we'll try to get to it as soon as possible.

We'll keep you updated!
