### ISSUE TITLE
Problem with null values

### ISSUE THREAD

**Issue by perederyaev** [VictoriaMetrics/VictoriaMetrics#6198]
### Describe the bug

Hi,
VictoriaMetrics v1.93.14 processes samples with null values in way.
When VM receives metrics like
```
{"metric":{"__name__":"namedprocess_namegroup_thread_context_switches_total","job":"process_exporter","instance":"srv82","ctxswitchtype":"nonvoluntary","groupname":"mtpro - php  -dmemory_limit=640M run.php --controller=TimeSpent\\RawLowConsumer --action=default --useSwoole=1 --pid=1858 --maxWorkTime=3600 --timeout=5000 --partition=278","threadname":"grpc_global_tim"},"values":[null,null,null,null,null,null,null,null],"timestamps":[1714159866695,1714159926695,1714159986694,1714160046694,1714160106695,1714160166694,1714160226695,1714160286695]}
{"metric":{"__name__":"namedprocess_namegroup_thread_context_switches_total","job":"process_exporter","instance":"srv82","ctxswitchtype":"voluntary","groupname":"mtpro - php  -dmemory_limit=640M run.php --controller=TimeSpent\\RawLowConsumer --action=default --useSwoole=1 --pid=1858 --maxWorkTime=3600 --timeout=5000 --partition=335","threadname":"rdk:broker11111"},"values":[null,null,null,null,null,null,null,null],"timestamps":[1714159866695,1714159926695,1714159986694,1714160046694,1714160106695,1714160166694,1714160226695,1714160286695]}
```
it doesn't insert them (can't see them in export or cardinality explorer in VMUI), doesn't count them in active series but counts them as 'slow inserts' and 'cache misses' (storage/tsid).
This is critical issue because it affects performance of the whole ingesting.

Same metrics are processed correctly in v1.87.14 - they are counted in active series, we can access them and no strange 'slow inserts', 'cache misses' and so on.

### To Reproduce

Try to insert null values in clean database (so no metrics exists before) to VM v1.93.14

### Version

victoria-metrics-20240419-095826-tags-v1.93.14-0-g345a53d8b0

**Comment by Haleygo** [comment]
Hello,
Yes, VictoriaMetrics will drop "null" value from `/api/v1/import` when store
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5e8c087d4244a4d82e11c1428e9699d2a00b6cb7/lib/storage/storage.go#L1811-L1816

But as I can see, this behavior hasn't changed since `/api/v1/import` added support to ingest value like `null` in [v1.82.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.82.0).
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5e8c087d4244a4d82e11c1428e9699d2a00b6cb7/lib/protoparser/vmimport/parser.go#L142-L143

So if you import timeseries with all "null" values like your example above, the whole timeseries will be dropped and they won't be counted in `vm_slow_row_inserts_total` since they're not inserted.
But if you import timeseries with part of "null" values like `"values":[3,null,13]`, the timeseries will be registered and not be marked as slow_insert next time.

>Same metrics are processed correctly in v1.87.14 - they are counted in active series, we can access them and no strange 'slow inserts', 'cache misses' and so on.

Did you ingest the same values to v1.87.14, set all the values to "null"?

**Comment by perederyaev** [comment]
Hi Haleygo,
We are using vmagent for sending metrics to VM. In this case /api/v1/write is used but not /api/v1/import.

**Comment by Haleygo** [comment]
Ok, that's not expected.
What the version of vmagent here? Did you test with target that down for a while and didn't see NaN values only in v1.93.14?
I did a quick test with vmsingle v1.93.14(vmsingle shares same code with vmagent and vmcluster storage) and the NaN works. My test steps are:
1. set up vmsingle v1.93.14 to scrape a target for few minutes;
2. stop the target for a while;
3. check the results.
<img width="1503" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/39937150/293891b3-bf04-4431-a7e1-8847c8fc62ce">

>Only v1.93.14 has the issue with registering new timeserries if they have nulls value and hadn't existed before.

You mean the new timeseries start with null values, like the target expose metrics with null values?
In my test, the NaN value is attached automatically by vmagent as stale marker.

**Comment by perederyaev** [comment]
I'm not sure how to reproduce issue from the scratch.
Please check this tcpdump [vm_bug.pcap.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/15152494/vm_bug.pcap.zip)
first tcp stream is to v1.93.14 (127.0.0.1) and it's not inserted with 'slow insert' and 'cache miss' every minute
second stream to 1.87.14 (10.111.150.2) and it's inserted and has no 'slow insert' and 'cache miss' every minute

**Comment by perederyaev** [comment]
Managed to reproduce it with [promremotecli](https://github.com/m3dbx/prometheus_remote_client_golang/tree/master/cmd/promremotecli) - just modify it for sending "staleNaNBits uint64 = 0x7ff0000000000002" and you will get the same behavior.

**Comment by Haleygo** [comment]
Should related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5069.
>VictoriaMetrics should stop creating new time series when it receives [staleness marker](https://docs.victoriametrics.com/vmagent.html#prometheus-staleness-markers) for new time series

But this won't happen if time series has "real" values, only has staless marker from time to time.
Could you please elaborate your use case here, why store time series only with NaN values?
