### ISSUE TITLE
Rate as a Streaming Aggregation

### ISSUE THREAD

**Issue by rbizos** [VictoriaMetrics/VictoriaMetrics#6202]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

I'm trying to replicate our current Prometheus recording rules with vmagent to make a cheaper drop-in replacement of our Prometheus. So far I have great results (the total is absolutely a game changer).
I've seen that the documentation indicates to use increase and divide by the time window at query time. I'm not sure to understand why its unsafe to aggregate afterwards as the only difference is a common factor.

Would it be acceptable to implement the rate ? I'm willing to do it as well.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Haleygo** [comment]
dup with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5641

**Comment by rbizos** [comment]
Oh sorry, I missed it thanks !

**Comment by AndrewChubatiuk** [comment]
hey @rbizos
[rate_sum](https://docs.victoriametrics.com/stream-aggregation/#rate_sum) and [rate_avg](https://docs.victoriametrics.com/stream-aggregation/#rate_avg) outputs are available in v1.102.0-rc1

**Comment by rbizos** [comment]
I'm playing with that as soon as possible :)
