### ISSUE TITLE
vmstorage custom build crashes for versions 1.87.3, 1.87.5, 1.87.14

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#6208]
### crash snapshot
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2275120/9df0cf92-778b-4b72-98ad-895407e4590e)

### main crash info
runtime: marked free object in span 0x7fce6fa713e8, elemsize=320 freeindex=0 (bad use of unsafe.Pointer? try -d=checkptr)

### some context
1. This problem occurs in the version we compiled ourselves. 
2. There is no any code change
3. This problem does not occur when using the community version binary directly
4. Our build environment（use self docker image）：
    * golang versoin： FROM golang:1.21-alpine as builder
    * system version：debian-stretch
    * others：`RUN apt-get update && apt-get install -y make rsync gcc g++ pkg-config cmake build-essential bzip2 nasm \
 zlib1g-dev libelf-dev libelf1 libglib2.0-dev autoconf automake libtool libmagickwand-dev python-dev libcrypto++-dev clang curl libssl-dev libpq-dev \
 openssl default-libmysqlclient-dev && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*`

### To Reproduce

random crash 

### Version

vmstorage-20240428-135734-heads-cluster_1.87.14-0-g7e9bc13f8

base: cluster_1.87.14
there is no any code change

**Comment by hagen1778** [comment]
@jinlongwang I'm removing the `bug` label because you said official pre-compiled binaries are Ok.

@f41gh7 @zekker6 do you any opinion on why this problem could happen?

**Comment by zekker6** [comment]
@jinlongwang Could you also provide a `go build` command which you're using to create a build?

As far as I can see based on the shared command, you're using gcc to perform the build while official binaries are using musl. This can cause some issues in code which is using CGO.
Is it possible to either use musl or switch to [official build scripts](https://docs.victoriametrics.com/single-server-victoriametrics/#how-to-build-from-sources) to produce a binary?

**Comment by f41gh7** [comment]
given error related to the case when object was marked as free by garbage collector. But at the next GC cycle a pointer for it is still in-use.


 It could happen in the following cases:
1) incorrect usage of raw pointers. It's a trivial case, most linters could catch it. And we follow unsafe rules. So it's most unlikely. 
2) missing runtime.KeepAlive call for object created by unsafe code. Potentially, when you create some object from bytes unsafely converted from string, garbage collector may mark original string as free for garbage collection. It relies on compiler escape analysis and  could cause a problem if compiler incorrectly handles `noinline` marker.

 Both cases are possible if you have an issue with golang compiler. I'd recommend to pin minor version number for build image, e.g. `golang:1.22.2-alpine` instead of `golang:1.22-alpine`.

**Comment by jinlongwang** [comment]
This looks like it's most likely an issue with the gcc version. The gcc in the VM compilation image is 13.2.1, while the version with which we previously had issues was 6.x. I have now recompiled a version using gcc12 and am currently monitoring it. Due to company environment constraints, I cant used gcc 13.2.1

**Comment by jinlongwang** [comment]
update
In the version of gcc12, it still crashed. so, we looked into the build script. and We added code specifying the use of musl to compile, and this problem is no longer happening

the script is like:

# cd ${ROOT_PATH}/${APP_PATH}
CC=musl-gcc go build -trimpath -buildvcs=false \
         -ldflags "-extldflags '-static' \
             -X '${PKG_PREFIX}/lib/buildinfo.Version=${APP_NAME}-${DATEINFO_TAG}-${BUILDINFO_TAG}' " \
         -tags 'netgo osusergo nethttpomithttp2 musl' \
         -o ${OUTPUT_PATH}/bin/${RUN_NAME} ${PKG_PREFIX}/${APP_PATH}

**Comment by hagen1778** [comment]
@AndrewChubatiuk @f41gh7 do you think we should make changes to our build commands?

**Comment by AndrewChubatiuk** [comment]
@jinlongwang which arch are you running on?

**Comment by hagen1778** [comment]
> 
@hagen1778 build scripts in 1.87 and master differ. in master build for arm64 and amd64 already uses musl. do you want to update scripts in 1.87?

No, if we already switched to musl in the upstream then we can close this issue.
