### ISSUE TITLE
vmalert: speed up rules reload from object storage

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6210]
### Is your feature request related to a problem? Please describe

When [loading rule files from object storage](https://docs.victoriametrics.com/vmalert/#reading-rules-from-object-storage) vmalert performs to subsequent actions:
1. List all files in configured bucket. Having the list allows prefix matching by file name, to select only specific files to load.
2. Read files that match filters from the p1.

The most time consuming stage is p2, as it loads each individual file and parses it. Would be great, if vmalert could speed up this stage by checking whether file's update time has changed or whether there were any changes to the bucket at all. In this way, vmalert could detect if something needs to be downloaded from object storage much faster.

### Describe the solution you'd like

vmalert should remember file versions or update time of rules loaded from object storage. On next config reload call, vmalert should list all available files in the bucket and download only those which were updated since the last config reload.

**Comment by valyala** [comment]
[Enterprise version](https://docs.victoriametrics.com/enterprise.html) of [vmalert](https://docs.victoriametrics.com/vmalert.html) should reload rules from object storage at faster speed starting from [v1.102.0-rc1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc1).
