### ISSUE TITLE
Triplicated metrics in Grafana

### ISSUE THREAD

**Issue by jdsanclemente** [VictoriaMetrics/VictoriaMetrics#6215]
### Is your question request related to a specific component?

VictoriaMetrics, Grafana

### Describe the question in detail

I'm encountering this problem when using VictoriaMetrics as a datasource in graphana: The same metric is being triplicated, showing almost the same values:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/168703539/24267a2c-c823-4877-89fb-ea22d5668829)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/168703539/452180a0-3790-4282-8a44-379197dc11b3)

This is the JSON code:

```
{
  "id": 4,
  "gridPos": {
    "h": 6,
    "w": 8,
    "x": 0,
    "y": 26
  },
  "type": "timeseries",
  "title": "RA04 WS sessions ",
  "datasource": {
    "uid": "pz0kQ7OVk",
    "type": "prometheus"
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 4,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "axisColorMode": "text",
        "scaleDistribution": {
          "type": "linear"
        },
        "axisCenteredZero": false,
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        },
        "lineStyle": {
          "fill": "solid"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      }
    },
    "overrides": []
  },
  "options": {
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "showLegend": true,
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "datasource": {
        "type": "prometheus",
        "uid": "pz0kQ7OVk"
      },
      "editorMode": "code",
      "expr": "ra_server_sessions_active{job=~\"raejob04\"}",
      "legendFormat": "{{__name__}}",
      "range": true,
      "refId": "A"
    }
  ]
}
```

Any idea on how to fix this? Any help would be greatly appreciated, thank you.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by xiaozongyang** [comment]
hi @jdsanclemente what's your original data in http network response? you may find it by your browser development tools

**Comment by zekker6** [comment]
Hello @jdsanclemente 
Could you elaborate on what is your write path configuration?
It seems like these metrics can either be scraped by mulitiple vmagent instances (for example running in [HA mode](https://docs.victoriametrics.com/vmagent/#high-availability)) or it metrics could be pushed by different application instances without `instance` label attached.
The fix in the first case is to enable [deduplication](https://docs.victoriametrics.com/single-server-victoriametrics/#deduplication). In the second case it is needed to ensure that `instance` label will be present for ingested series to distinguish the source of metrics.

**Comment by jdsanclemente** [comment]
> Hello @jdsanclemente Could you elaborate on what is your write path configuration? It seems like these metrics can either be scraped by mulitiple vmagent instances (for example running in [HA mode](https://docs.victoriametrics.com/vmagent/#high-availability)) or it metrics could be pushed by different application instances without `instance` label attached. The fix in the first case is to enable [deduplication](https://docs.victoriametrics.com/single-server-victoriametrics/#deduplication). In the second case it is needed to ensure that `instance` label will be present for ingested series to distinguish the source of metrics.

The query inspector tells me that these metrics are coming from three diferrent pods:

{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
  "response": {
    "results": {
      "A": {
        "frames": [
          {

                  "name": "Value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64"
                  },
                  "labels": {
                    "__name__": "ra_server_sessions_active",
                    "container": "rastatus",
                    "endpoint": "http",
                    "instance": "10.75.22.45:80",
                    "job": "rae02",
                    "namespace": "raestatus",
                    "pod": "raestatus-64d757659f-4l4zw",
                    "prometheus": "monitoring/kube-prometheus-stack-prometheus",
                    "prometheus_replica": "prometheus-kube-prometheus-stack-prometheus-0",
                    "service": "raestatus"
                  },
                  "config": {
                    "displayNameFromDS": "rae_server_sessions_active"
                  }
                }
              ]
 
                  },
                  "labels": {
                    "__name__": "ra_server_sessions_active",
                    "container": "rastatus",
                    "endpoint": "http",
                    "instance": "10.75.22.45:80",
                    "job": "rae02",
                    "namespace": "raestatus",
                    "pod": "raestatus-64d757659f-4l4zw",
                    "prometheus": "monitoring/kube-prometheus-stack-prometheus",
                    "prometheus_replica": "prometheus-kube-prometheus-stack-prometheus-1",
                    "service": "raestatus"
                  },
                  "config": {
                    "displayNameFromDS": "rae_server_sessions_active"
                  }

                  },
                  "labels": {
                    "__name__": "ra_server_sessions_active",
                    "container": "rastatus",
                    "endpoint": "http",
                    "instance": "10.75.22.45:80",
                    "job": "rae02",
                    "namespace": "raestatus",
                    "pod": "raestatus-64d757659f-4l4zw",
                    "prometheus": "monitoring/kube-prometheus-stack-prometheus",
                    "prometheus_replica": "prometheus-kube-prometheus-stack-prometheus-2",
                    "service": "raestatus"
                  },
                  "config": {
                    "displayNameFromDS": "rae_server_sessions_active"
                  }
                }

This is certainly the reason, but how to fix it?

**Comment by zekker6** [comment]
@jdsanclemente In order to fix that you need to:
1. Remove `prometheus_replica` label by using [relabeling](https://docs.victoriametrics.com/relabeling/)
2. Enable [deduplication](https://docs.victoriametrics.com/single-server-victoriametrics/#deduplication) to enforce storing of 1 copy of each sample scraped by Prometheus.

**Comment by zekker6** [comment]
Closing as original question have been answered. Feel free to reopen if additional questions will appear.
