### ISSUE TITLE
Strangeness with `timestamp()`

### ISSUE THREAD

**Issue by lapo-luchini** [VictoriaMetrics/VictoriaMetrics#6219]
### Describe the bug

If I use this I get all the results:

`vm_app_version{job="vmagent"}`

but when I do this I get a varying amount of records:

`timestamp(vm_app_version{job="vmagent"})`

I use this kind of rule to detect when a remote `vmagent` stopped responding, but I am now getting false positives.

I noticed that this happened when I upgraded vmagent from 1.93.x to 1.100.1, and not when (previously) I upgraded victoria-metrics di 1.100.1.

### To Reproduce

![timestamp](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/420454/b120e188-b7d6-416f-aeb3-3b7dc9d7ce31)

### Version

victoria-metrics-20240411-091522-tags-v1.100.1-0-g9ee51e3

**Comment by lapo-luchini** [comment]
Seems to be fixed in [v1.101.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.101.0)… ?

**Comment by lapo-luchini** [comment]
> Grafana Explore probably doesn't send `step` param, so it defaults to `5m` when omitted. Does it make sense?

It does! Originally I noticed the problem in vmalert rules, tough, not using vmui.
It had a lot of false negatives in latest updates that didn't happen before.
Might have been a change… but explanation makes sense, I'll add an explicit look-behind window to the rule.

**Comment by jiekun** [comment]
@lapo-luchini Hi. Based on previous comment, I think this issue could be closed now. But please don't hesitate to re-open it if you encounter more trouble.
