### ISSUE TITLE
VMUI static files are missing in  v1.101.0

### ISSUE THREAD

**Issue by lapo-luchini** [VictoriaMetrics/VictoriaMetrics#6224]
### Describe the bug

When I access `/vmui/` I get `404` on generated files.

### To Reproduce

http://localhost:8428/vmui/

### Version

victoria-metrics-20240426-090403-tags-v1.101.0-0-g5334f0c

### Logs

```
HTTP 404 GET http://localhost:8428/vmui/static/css/main.d0b400e3.css
HTTP 404 GET http://localhost:8428//vmui/static/js/main.59c17910.js
```

**Comment by dantangfan** [comment]
face the same problem

<img width="1273" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/4002837/abebd496-22b5-4afd-bfb2-d97b028e8d6b">

**Comment by hagen1778** [comment]
Hello @dantangfan @lapo-luchini! Do you use official builds provided here https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.101.0 ?

**Comment by dantangfan** [comment]
> Hello @dantangfan @lapo-luchini! Do you use official builds provided here https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.101.0 ?

oh no. I build by myself for test purpose. I run `make all` cmd in the root dir, and the vminsert app in `./bin/` dir got vmui 404 error.

**Comment by lapo-luchini** [comment]
I'm using a locally modified FreeBSD Port that I personally updated to v1.100.1 (and it was working fine, except for #6192) and then to v1.101.0 (and it gives this error).
Using the file from the release page it works fine, but while I can use that release personally (or for testing purposes), the official FreeBSD package (built from the Ports) needs to be locally compiled, so I'll need to fix that anyways in order to have it as a supported package.
PS: I'm not the official maintainer of the port, just a user interested in using a more recent release and advocating for it to be upgraded, so I'd like to send a patch in order to facilitate the process.

**Comment by lapo-luchini** [comment]
I noticed that [diff v1.100.1...v1.101.0](https://github.com/VictoriaMetrics/VictoriaMetrics/compare/v1.100.1...v1.101.0) shows this:
```patch
  "entrypoints": [
    "static/css/main.bc07cc78.css",
-   "static/js/main.034044a7.js"
+   "static/js/main.8e7757ef.js"
  ]
```
but then the `/vmui/` searches for `main.59c17910.js`.

**Comment by lapo-luchini** [comment]
I managed to reproduce on a pristine Linux virtual machine (no relation to FreeBSD):
```sh
$ git clone https://github.com/VictoriaMetrics/VictoriaMetrics.git --branch v1.101.0 --depth=1
$ cd VictoriaMetrics
$ make victoria-metrics
APP_NAME=victoria-metrics make app-local
make[1]: Entering directory '/root/VictoriaMetrics'
CGO_ENABLED=1 go build  -ldflags "-X 'github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=victoria-metrics-20240507-112209-tags-v1.101.0-0-g5334f0c'" -o bin/victoria-metrics github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics
make[1]: Leaving directory '/root/VictoriaMetrics'
$ bin/victoria-metrics -httpListenAddr '[::]:18428' &
$ wget -qO - http://localhost:18428/vmui/ | egrep -o 'static/js/main[^"]+'
static/js/main.59c17910.js
$ wget http://localhost:18428/vmui/static/js/main.59c17910.js
--2024-05-07 11:26:45--  http://localhost:18428/vmui/static/js/main.59c17910.js
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:18428... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:18428... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-05-07 11:26:45 ERROR 404: Not Found.
```

**Comment by hagen1778** [comment]
The issue with missing static files should be solved starting from https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0.
