### ISSUE TITLE
Scrape CRD's support by single-node VictoriaMetrics

### ISSUE THREAD

**Issue by stepan-vardanyan** [VictoriaMetrics/VictoriaMetrics#6257]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Hi all.

Not sure if this was answered somewhere, but does single-node VictoriaMetrics (without vmagent or cluster at all) somehow support scrape config generate and update by VMOperator CRD's like ServiceMonitor, VMPodScrape, VMServiceScrape, etc.?
It was working for us in VM cluster + VMOperator setup, before we migrated to single-node setup for sake of simplicity and cost optimization, but apparently we lost this useful feature of generating scrape config from CRD's which is convenient way to manage it by developers, most of helm charts provide servicemonitor resource out of box, automatically feeding them to monitoring. Otherwise it's much harder, you have to manually update scrape config dealing with the complex relabeling and so on.

Thanks in advance.

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @stepan-vardanyan 
Currently, the only way to configure scrape via CRD objects is to use operator and vmagent.

>  It was working for us in VM cluster + VMOperator setup, before we migrated to single-node setup for sake of simplicity and cost optimization, but apparently we lost this useful feature of generating scrape config from CRD's which is convenient way to manage it by developers, most of helm charts provide servicemonitor resource out of box, automatically feeding them to monitoring. Otherwise it's much harder, you have to manually update scrape config dealing with the complex relabeling and so on.

Seems to me like you should have had vmagent there as well, so you could replace `VMCluster` definition with `VMSingle` object to switch to single-node setup.

**Comment by stepan-vardanyan** [comment]
Okey, I was thinking the same, but thanks for clarification.
So along with single-node VM vmagent have to be deployed and it has it's own scrape configmap, it should be provided to VM using [server.scrape.configMap](https://artifacthub.io/packages/helm/victoriametrics/victoria-metrics-single/0.9.14?modal=values&path=server.scrape.configMap) option in victoria-metrics-single chart? Can vmagent's ConfigMap be appended somehow instead? [server.scrape.extraScrapeConfigs](https://artifacthub.io/packages/helm/victoriametrics/victoria-metrics-single/0.9.14?modal=values&path=server.scrape.extraScrapeConfigs) seems accept pure config instead of ConfigMap name. Our intention is that we provide both pure scrape config in victoria-metrics-single values.yaml and append vmagent's one which generated from CRD objects.
