### ISSUE TITLE
Influx-to-Prometheus names conversion: "field" name as time series name without the "{measurement}{separator}" prefix

### ISSUE THREAD

**Issue by vpedosyuk** [VictoriaMetrics/VictoriaMetrics#626]
**Is your feature request related to a problem? Please describe.**
I use Telegraf for ingesting data into VictoriaMetrics. I'm trying to configure the following flow: `Prometheus-node-exporter -> Telegraf -> Kafka -> Telegraf -> VictoriaMetrics`

This works fine but all the ingested metrics have a measurement name prefix and [this name is required to be a non-empty string](https://github.com/influxdata/telegraf/issues/5849#issuecomment-491977936) in Telegraf.

For example, I've got `prometheus_node_cpu_seconds_total` instead of original `node_cpu_seconds_total`. This breaks the node-exporter Grafana dashboard, etc.

**Describe the solution you'd like**
It'd be great if we had an option in VictoriaMetrics to use only the "field" name as time series name omitting the "measurement" prefix.

**Describe alternatives you've considered**
1. I've considered vmagent as an alternative but it can't act as a Kafka producer/consumer.
2. I've considered relabeling in v1.38.0 but I'm unsure how to mount a file with a list of `relabel_config` entries using the VM Helm chart (cluster version).

**Comment by valyala** [comment]
The next release of VictoriaMetrics will support `-influxSkipMeasurement` command-line flag, which could be set for using field names from Influx lines as metric names. See the corresponding commit - 4081e2295e4f5dd1fb35b0ed7a36390e95faf8b1 . In the mean time you can test this functionality by building VictoriaMetrics from this commit according to [these instructions](https://victoriametrics.github.io/#how-to-build-from-sources).

**Comment by valyala** [comment]
The `-influxSkipMeasurement` command-line flag has been added in VictoriaMetrics [v1.38.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
