### ISSUE TITLE
vmui requests are not automatically quoted

### ISSUE THREAD

**Issue by luweijun1992** [VictoriaMetrics/VictoriaMetrics#6260]
### Describe the bug

vmui requests are not automatically quoted

### To Reproduce

As follows, there is no automatic
When selecting the drop-down selection, the quotation marks are automatically added in front, but not after them.
---
![Animation](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/58923704/00829145-64b0-476a-989a-54dae63277b4)

### Version

victoria-metrics-20240425-145715-tags-v1.101.0-0-g5334f0c2c

**Comment by zekker6** [comment]
@Loori-R Could you please take a look?

**Comment by luweijun1992** [comment]
When will the bug be fixed?

**Comment by luweijun1992** [comment]
@Loori-R

**Comment by Loori-R** [comment]
Hi @luweijun1992

Thanks for reporting the bug. We're currently focused on other high-priority tasks, so we can't give an exact timeline for the fix, but we'll try to get to it as soon as possible.

We'll keep you updated!

**Comment by hagen1778** [comment]
@luweijun1992 the automatic quoting of options selected from auto-suggestion list was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6566 and will be included into the next release.

**Comment by f41gh7** [comment]
this bug should be fixed in [v1.102.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.1).

feel free to reopen if you still observe issue
