### ISSUE TITLE
add aggregate(downsampling) function to vm

### ISSUE THREAD

**Issue by flashmouse** [VictoriaMetrics/VictoriaMetrics#627]
**Is your feature request related to a problem? Please describe.**
Downsampling should decrease cpu usage & improve performance or stability when do long term query, and it should reduce disk usage in some situation.

**Describe the solution you'd like**
we now add "aggrType" to each metric, this attribute decide the behavior when doing aggregate. 

"aggrType" has 4 value: max, min, sum and gauge. it not support avg, we could use 2 metrics to implement that. 

 this attribute would add into BlockHeader, and aggregate would happen during merge. when merge executed, it will check whether aggregate is triggered.

**Describe alternatives you've considered**
some tsdbs such as influxdb, opentsdb, allow user write sql to do downsampling, it looks liitle bother, the way above may be more simple.

**Additional context**
we want to know whether this a reachable way to do downsampling? or whether official is doing this function?

and for now we have try implement the code and face some problems:
- the data structure for storage seems hard to do upgrade, beacuse this way will add a new attribute to BlockHeader and no easy way to check whether this Block has this attribute.
- for now vm support replication, vmselect will get all data from all vmstorages then remove duplicate data, right? do downsampling will change point's timestamp, we not sure whether vmselect could do right behavior.

thx!

**Comment by valyala** [comment]
> the data structure for storage seems hard to do upgrade, beacuse this way will add a new attribute to BlockHeader and no easy way to check whether this Block has this attribute.

This may be hard to implement without breaking backwards compatibility. Probably, another file may be added to each part alongside values.bin, timestamps.bin, index.bin and metaindex.bin - extra_info.bin. This file could contain extra information for all the blocks in the part. The file format should support adding new info in the future in order to save backwards compatibility.

> for now vm support replication, vmselect will get all data from all vmstorages then remove duplicate data, right? do downsampling will change point's timestamp, we not sure whether vmselect could do right behavior.

Correct - `vmselect` removes duplicate (replicated) datapoints according to `-dedup.minScrapeInterval=1ms` command-line flag. Downsampling should be deterministic across `vmstorage` nodes in order to work properly with the deduplication - i.e. it should generate identical samples for the same time series.

**Comment by flashmouse** [comment]
thx for reply!

add another file seems a good idea, we'll go on based this.

downsampling will change timestamp & value. although it should provide the same qurey result eventually, but we couldn't make them start & complete merge job at the same time. when one node merge done but another not, there may have different result.

**Comment by iamhritikkumar** [comment]
any updates on other downsampling strategies apart from deduplication?

**Comment by iamhritikkumar** [comment]
now we can use stream_aggregation feature directly to achieve downsampling in VM

**Comment by valyala** [comment]
VictoriaMetrics supports downsampling starting from [v1.71.0](https://docs.victoriametrics.com/CHANGELOG.html). See [these docs](https://docs.victoriametrics.com/#downsampling) and [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/36).

There is also [streaming aggregation](https://docs.victoriametrics.com/stream-aggregation.html) supported by [recent versions](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest) of [vmagent](https://docs.victoriametrics.com/vmagent.html). It can be used for arbitrary downsampling tasks - see [this example](https://docs.victoriametrics.com/stream-aggregation/#reducing-the-number-of-stored-samples).

Closing this feature request as done.
