### ISSUE TITLE
How to search log as quickly as possible while writing log  in client side

### ISSUE THREAD

**Issue by dw130** [VictoriaMetrics/VictoriaMetrics#6275]
### Is your question request related to a specific component?

victoriaLogs

### Describe the question in detail

Hi:
   I have been testing writing some content in client side and collect to victoriaLogs via filebeat
   But I can search out the log by some key words was already around 12 seconds later,some times even more longer

   Is there any configuration that can help me more quickly search for the written logs？ thanks

victoria-logs config（use the lastest version）

victoria-logs
-inmemoryDataFlushInterval=1s 
-maxConcurrentInserts=1000 
-retentionPeriod=7d 
-search.maxQueryDuration 500s 
-search.maxConcurrentRequests 5000 
-httpListenAddr=0.0.0.0:9200 
-storageDataPath=/home/data/log/victoria-logs-data 
-maxConcurrentInserts=10000 
-memory.allowedPercent=75

filebeat:
filebeat.inputs:
- type: filestream
  id: debug
  enabled: true
  backoff.max: 2s
  backoff.init: 1s

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
please take a look at filebeat in-memory queue configuration
https://www.elastic.co/guide/en/beats/filebeat/current/configuring-internal-queue.html#_configuration_options_32
try to switch filebeat to synchronous mode using `flush.timeout` or `flush.min_events`

**Comment by dw130** [comment]
@AndrewChubatiuk , Thanks a lot
