### ISSUE TITLE
Maximum advised storage capacity for a vmstorage instance?

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/VictoriaMetrics#6277]
I would like to know if there is an advised max storage capacity size suggested for vmstorage nodes?  Is it reasonable to have instances with up to 10TBs of storage?  Are there any other implications or guidelines with regards to scaling storage on vmstorage nodes?   

Thanks for your help.

**Comment by AndrewChubatiuk** [comment]
hey @hartfordfive
It's possible to run VM cluster with terabytes of data, but vertical vmstorage scaling is limited by disk I/O. Its preferable to scale storage horizontally to not depend on disk throughput. General recommendations for cluster setup you can find [here](https://docs.victoriametrics.com/cluster-victoriametrics/#cluster-setup)
