### ISSUE TITLE
VictoriaMetrics Datadog APM/Trace Agent URL integration

### ISSUE THREAD

**Issue by michalgoldys** [VictoriaMetrics/VictoriaMetrics#6278]
### Describe the question in detail

Hey there!

As described here:
https://docs.victoriametrics.com/single-server-victoriametrics/#how-to-send-data-from-datadog-agent
https://docs.victoriametrics.com/url-examples/#datadog

VictoriaMetrics supports Datadog Agent metrics collection for specific endpoints.

I'm wondering, if VictoriaMetrics supports, or will support collecting data from Datadog Trace Agents.
You could easily achieve this by changing the proper environment variable - which I did:

https://github.com/DataDog/datadog-agent/blob/878600ef7a55c5ef0efb41ed0915f020cf7e3bd0/pkg/config/config_template.yaml#L1242

I've tried to tide up the Datadog Trace Agent data forwarding to the VictoriaMetrics URL. I changed the ```apm_dd_url``` to match my VictoriaMetrics setup, but unfortunately looks like the given path for VictoriaMetrics seems to be unknown:

```
{"ts":"XX-XX-XX:XX:XX.XX","level":"warn","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:419","msg":"remoteAddr: \"XX.XX.XX.XX:XX, X-Forwarded-For: XX.XX.XX.XX\"; requestURI: /datadog/api/v0.2/stats; unsupported path requested: \"/datadog/api/v0.2/stats\""}
{"ts":"XX-XX-XX:XX:XX","level":"warn","caller":"VictoriaMetrics/lib/httpserver/httpserver.go:419","msg":"remoteAddr: \"XX.XX.XX.XX:XX, X-Forwarded-For: XX.XX.XX.XX\"; requestURI: /datadog/api/v0.2/traces; unsupported path requested: \"/datadog/api/v0.2/traces\""}
```

It is more related to Application Performance Monitoring (https://docs.datadoghq.com/tracing/) instead of typical "metrics". 
I'm not sure if such a solution is supported. 
Do I do something wrong, or just Traces/APM is not supported? 

I am using ```victoria-metrics-single``` helm chart in version ```0.9.17``` with app running on ```image v1.99.0```

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @michalgoldys
Currently VictoriaMetrics doesn't support traces, but we're planning to add it in a future

**Comment by michalgoldys** [comment]
Hey @AndrewChubatiuk thanks for the reply.

Could you reveal any potential assumptions when traces are planned to be supported?
I mean, is it more like a couple of weeks or more like a mid/long-term goal?

**Comment by AndrewChubatiuk** [comment]
Suppose it's a mid/long-term goal, but anyway will let you know in case of any updates

**Comment by michalgoldys** [comment]
I suppose that traces aren't yet supported? 😅

**Comment by jiekun** [comment]
@michalgoldys Hi. Yes. We are not going to support it now. Just like VictoriaLogs, if Trace is going to be supported in the future, it will be as a standalone product. We will proceed according to internal planning, so I have closed this question/feature request as not planned.
