### ISSUE TITLE
MetricsQL: Document stalness marker differences between `default_rollup` and `last_over_time`

### ISSUE THREAD

**Issue by michalhosna** [VictoriaMetrics/VictoriaMetrics#6279]
From the current(2024-05-15) MetricsQL documentation, it seems that the `default_rollup` and `last_over_time` functions are effectivly the same. 

Even looking into the code, those functions seem the same https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5e8c087d4244a4d82e11c1428e9699d2a00b6cb7/app/vmselect/promql/rollup.go#L2328

But there are somewhat hidden differences at minimum with staleness marker handling, which are non-obvious
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5e8c087d4244a4d82e11c1428e9699d2a00b6cb7/app/vmselect/promql/eval.go#L1972

Those differences, as well as any other differences, should be documented in the MetricsQL documentation.

**Comment by AndrewChubatiuk** [comment]
hey @michalhosna
thanks for a finding
added PR with a note about difference between these functions

**Comment by hagen1778** [comment]
Thanks for reporting @michalhosna!
The issue should be addressed in this commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/ce3cfd720e81affe2222df57b0b24e537c8a2ae5
