### ISSUE TITLE
incorrect and unstable output when using `limit` request parameter

### ISSUE THREAD

**Issue by eduardbareev** [VictoriaMetrics/VictoriaMetrics#6298]
### Describe the bug

this is about `limit` request parameter, not the pipe one

```
curl --no-progress-meter 'http://rck9thr.test:9428/select/logsql/query' \
    --data-urlencode query='_time:[0, now] | sort by (_time desc)  ' \
    --data-urlencode limit=1000 \
    | wc -l
45

curl --no-progress-meter 'http://rck9thr.test:9428/select/logsql/query' \
    --data-urlencode query='_time:[0, now] | sort by (_time desc)  ' \
    --data-urlencode limit=1000 \
    | wc -l
44

curl --no-progress-meter 'http://rck9thr.test:9428/select/logsql/query' \
    --data-urlencode query='_time:[0, now] | sort by (_time desc)  ' \
    --data-urlencode limit=1000 \
    | wc -l
45

curl --no-progress-meter 'http://rck9thr.test:9428/select/logsql/query' \
    --data-urlencode query='_time:[0, now] | sort by (_time desc)  ' \
    --data-urlencode limit=1000 \
    | wc -l
55


curl --no-progress-meter 'http://rck9thr.test:9428/select/logsql/query' \
    --data-urlencode query='_time:[0, now] | sort by (_time desc)  ' \
    --data-urlencode limit=1000 \
    | wc -l
45
```

### To Reproduce

maybe datadir can help [vicloglimitrequstparam.tag.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/15357522/vicloglimitrequstparam.tag.gz)

### Version

`victoria-logs-20240515-025846-tags-v0.7.0-victorialogs-0-g6fdba8599d`

**Comment by hagen1778** [comment]
Could be related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6785

**Comment by valyala** [comment]
Closing as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6785 .

**Comment by jiekun** [comment]
@eduardbareev Hello. Could you provide your dataset? It could be the `victoria-logs-data` folder. The appendix `vicloglimitrequstparam.tag.gz` seems incorrect.

**Comment by eduardbareev** [comment]
> @eduardbareev Hello. Could you provide your dataset? It could be the `victoria-logs-data` folder. The appendix `vicloglimitrequstparam.tag.gz` seems incorrect.

That's typo, extract it as if it's `tar.gz`. There is should 56 rows in it.
