### ISSUE TITLE
Add possibility to choose between increase() function native Prometheus or VictoriaMetrics

### ISSUE THREAD

**Issue by guliangsi** [VictoriaMetrics/VictoriaMetrics#630]
**Is your feature request related to a problem? Please describe.**
See issue #603 

**Describe the solution you'd like**
It is a bit confusing to observe different results between Prometheus and VicotriaMetrics in this case. It would be nice to have the possibility to choose between the increase() function native to Prometheus or that of VictoriaMetrics as both have their advantages / disadvantages.

Thanks

**Comment by valyala** [comment]
This may be implemented as a part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8

**Comment by hagen1778** [comment]
Functions `changes_prometheus` `delta_prometheus` `increase_prometheus` were added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1972
