### ISSUE TITLE
Grafana shows metrics value after removal in victoria metrics

### ISSUE THREAD

**Issue by tonus01** [VictoriaMetrics/VictoriaMetrics#6300]
### Is your question request related to a specific component?

VictroiaMetrics with grafana

### Describe the question in detail

Hi. I use victoria metrics with promethues scrape config. After I changed job name(from servs to hosts) grafana started showing 2 jobs(old and new).
![jobs](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/91814425/85e74eea-8ae1-4db6-ad39-5e1375f7952a)
Then I deleted the time series for the servs job.
`http://victoria-metrics:8428/api/v1/admin/tsdb/delete_series?match[]={job="servs"}`
And victoria metrics explorer return me only 1 job(hosts). But grafana still return 2 jobs(hosts and servs).  Why does grafana return something that doesn't exist?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tonus01** [comment]
This issue is rise when i choose prometheus version >= 2.24.x When i choose 2.23.x my grafana work fine and not show removed time series.

**Comment by hagen1778** [comment]
> Why does grafana return something that doesn't exist?

It is likely Grafana caches the previous response. Will it show the old job value if you create a new datasource with identical settings?

**Comment by hagen1778** [comment]
Hey @tonus01! Starting from https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0 VM shouldn't return deleted label values.
