### ISSUE TITLE
VictoriaLogs feature request: please add limit_with_ties

### ISSUE THREAD

**Issue by eduardbareev** [VictoriaMetrics/VictoriaMetrics#6301]
Hi. Please add a new pipe to VictoriaLogs query language. The pipe I request is similar to `limit`, but would look ahead (beyond N records) for tie items which, when found, are also included into result.

It would be also nice to have some kind of configurable threshold for extra rows upon reaching which `limit_with_ties` would yield error.

When consuming VictoriaLogs API, one might want to retrieve contiguous records split in pages and ordered chronologically.
A reasonable approach to this is to query records defining pages as exclusive timestamp bound and limit.
However, multiple records might have same timestamp (ties) and a naive limit can place page boundary between ties.

There are two consequences of this

1) There are going to be some records that would not be included to either page, i.e. they are lost from overall retrieval
2) The set of records related to a page became non-deterministic

A possible solution is to have a version of limit different in that it is aware of a field that makes records ties and is allowed to return more items than requested.

Here is a demo of this problem in VictoriaLogs:

```
# note that "blue" and "cyan" records are ties in following dataset 

curl --json '
{ "_msg": "red",    "_time":"2024-05-12T00:00:06+00:00" }
{ "_msg": "green",  "_time":"2024-05-12T00:00:05+00:00" }
{ "_msg": "blue",   "_time":"2024-05-12T00:00:04+00:00" }
{ "_msg": "cyan",   "_time":"2024-05-12T00:00:04+00:00" }
{ "_msg": "magenta","_time":"2024-05-12T00:00:03+00:00" }
{ "_msg": "yellow", "_time":"2024-05-12T00:00:02+00:00" }
{ "_msg": "black",  "_time":"2024-05-12T00:00:01+00:00" }
' 'http://localhost:9428/insert/jsonline'

sleep 3

# for initial page we query 3 newest records, ordered new to old
curl 'http://localhost:9428/select/logsql/query' --data-urlencode \
    'query=_time:[0, now] | sort by (_time desc) limit 3'
{"_time":"2024-05-12T00:00:06Z","_stream":"{}","_msg":"red"}
{"_time":"2024-05-12T00:00:05Z","_stream":"{}","_msg":"green"}
{"_time":"2024-05-12T00:00:04Z","_stream":"{}","_msg":"cyan"}

# for "previous>" page 
# we ask 3 records preceeding 2024-05-12T00:00:04+00:00 (exclusively)
curl 'http://localhost:9428/select/logsql/query' --data-urlencode \
    'query=_time:[0, 2024-05-12T00:00:04+00:00) | sort by (_time desc) limit 3'
{"_time":"2024-05-12T00:00:03Z","_stream":"{}","_msg":"magenta"}
{"_time":"2024-05-12T00:00:02Z","_stream":"{}","_msg":"yellow"}
{"_time":"2024-05-12T00:00:01Z","_stream":"{}","_msg":"black"}

# you can see that "blue" record is missing from either page
```

What follows is how this handled by `WITH TIES` option of `FETCH` clause in standard SQL.

```
-- for initial page we query 3 newest records, ordered new to old
select ts, color 
from records
where ts <= now()
order by ts desc
fetch first 3 rows with ties;
┌────────────────────────┬───────┐
│           ts           │ color │
├────────────────────────┼───────┤
│ 2024-05-12 00:00:06+00 │ red   │
│ 2024-05-12 00:00:05+00 │ green │
│ 2024-05-12 00:00:04+00 │ blue  │
│ 2024-05-12 00:00:04+00 │ cyan  │
└────────────────────────┴───────┘
(4 rows)

-- for "previous>" page                                         
-- we ask 3 records preceeding 2024-05-12T00:00:04+00:00 (exclusively)
select ts, color 
from records
where ts < '2024-05-12T00:00:04+00:00'
order by ts desc
fetch first 3 rows with ties
;
┌────────────────────────┬─────────┐
│           ts           │  color  │
├────────────────────────┼─────────┤
│ 2024-05-12 00:00:03+00 │ magenta │
│ 2024-05-12 00:00:02+00 │ yellow  │
│ 2024-05-12 00:00:01+00 │ black   │
└────────────────────────┴─────────┘
(3 rows)
```
Note that in SQL, `with ties` option requires presence of `order by` clause.

**Comment by eduardbareev** [comment]
I'm just wondering, is there any chance of this being ever added?

**Comment by valyala** [comment]
VictoriaLogs querying engine is designed in a way, which allows efficient streaming arbitrary number of the found results - see [these docs](https://docs.victoriametrics.com/victorialogs/querying/#command-line). Just execute the query and read results from the response stream in pages whenever you need the next page.

Adding `lit_with_ties` pipe will encourage mis-using [VictoriaLogs querying API](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs) in less efficient way. So it is unlikely this functionality will be added, since it will bring more confusion and troubles than it solves.

Closing this feature request as "won't implemented".

P.S. Probably, it would be a good idea adding am ability to stream query results via Websocket. Then such results could be consumed by web browsers on demand when user navigates to the next page. Please file a separate feature request for this feature if you think it will be useful.
