### ISSUE TITLE
Grafana dashboard shows error: AnnotationQueryRunner failed

### ISSUE THREAD

**Issue by pko-trackunit** [VictoriaMetrics/VictoriaMetrics#6309]
### Describe the bug

When I open VM cluster dasboard I see error popup in top-right.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/6b236841-bdf0-40da-834a-ebea797d34f9)

### To Reproduce

1. Import VM cluster dashboard from https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/?tab=revisions (revision 36 at the time of reporting the bug)
2. Open the dashboard.
3. You should see the error in top-right.

### Version

```
$ ./vmselect-prod --version
vmselect-20240419-100910-tags-v1.93.14-cluster-0-g8249acc69a

$ ./vmstorage-prod --version
vmstorage-20240419-100935-tags-v1.93.14-cluster-0-g8249acc69a

$ ./vminsert-prod --version
vminsert-20240419-100837-tags-v1.93.14-cluster-0-g8249acc69a

$ ./vmagent-prod --version
vmagent-20240419-100504-tags-v1.93.14-0-g345a53d8b0
```

### Logs

`POST` request to `.../grafana/api/ds/query`:
```
{"from":"1716191089000","to":"1716212689000","queries":[{"expr":"sum(changes(vm_app_start_timestamp{job=~\"(vminsert-blah-blah|vmselect-blah-blah|vmstorage-blah-blah)\", instance=~\".*\"})) by(job)","range":true,"instant":false,"exemplar":false,"interval":"60s","refId":"X","datasource":{"type":"prometheus","uid":"AN_UID_HERE"},"legendFormat":""}]}
```

Response:
```
{"results":{"X":{"error":"ReadObject: expect { or , or } or n, but found c, error found in #10 byte of ...|unction \"changes\", g|..., bigger context ...| expected type range vector in call to function \"changes\", got instant vector\"}|...","errorSource":"","status":400,"frames":[{"schema":{"refId":"X","meta":{"typeVersion":[0,0],"executedQueryString":"Expr: sum(changes(vm_app_start_timestamp{job=~\"(vminsert-1a|vminsert-1b|vminsert-1c|vmselect-vmselect|vmstorage-1a|vmstorage-1b|vmstorage-1c)\", instance=~\".*\"})) by(job)\nStep: 5m0s"},"fields":[]},"data":{"values":[]}}]}}}
```

### Screenshots

Anonymized query executed in Prometheus:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/5d694f34-d440-4496-9668-6909523bf191)

**Comment by f41gh7** [comment]
Could you please specify version of grafana? 

Looks like, grafana enforces lookbehind window for vectors.

**Comment by pko-trackunit** [comment]
We're using Grafana v10.4.2 (701c851be7)

**Comment by hagen1778** [comment]
Thanks for reporting @pko-trackunit !
The issue should be addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c746ba154d4efbbd1a25cc98428f63092cd6659a
Dashboard versions at https://grafana.com/orgs/victoriametrics/dashboards were updated as well.

**Comment by pko-trackunit** [comment]
Thanks for the fix @hagen1778 !

It no longer shows the alert, but I doesn't seem to work as intended.

`sum(changes(vm_app_start_timestamp[5m])) by (job)` is just a flat line:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/0fd46cb1-6397-4f0e-bf52-7fe1c8565715)

But there are definitely changes in the metric - `vm_app_start_timestamp`:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/f060c508-97c9-4022-b741-0dd0fbae4541)

There seem to be 7-minute gap in the metric. `vm_app_start_timestamp{pod="vmstorage-1a-0"}`:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/ebf36555-de9a-414a-9a09-6da6c88ee543)

Also: not sure if this is specific to our deployment, but `job` label is not unique in our case. We have `job="vmstorage-1a"` that has 2 pods - `pod="vmstorage-1a-0"` and `pod="vmstorage-1a-1"`. And I think it makes sense to see their restarts separately.

I played a bit with it and eventually I came to:
```
changes(max(vm_app_start_timestamp or last_over_time(vm_app_start_timestamp [1h])) by(pod)[5m:])
```

or for Grafana:

```
changes(max(vm_app_start_timestamp{job=~"$job", instance=~"$instance"} or last_over_time(vm_app_start_timestamp{job=~"$job", instance=~"$instance"} [1h])) by(pod)[15m:])
```

but that creates wide (and overlapping) annotations:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/daefc2ed-7a72-4872-90ad-8f40375e3d24)

Although when zoomed out it's okay:
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/131138290/8fd3603a-2c30-4bee-a25b-173e377de587)

**Comment by hagen1778** [comment]
> But there are definitely changes in the metric - vm_app_start_timestamp:

It is likely the change isn't visible because `change` is calculated individually per time series. And in your case the app restart is actually a pod restart, with a new pod name, and new pod name is a new time series. This is why changes `by (pod)` worked for you. But it won't work for users who run VM not in k8s.

> Also: not sure if this is specific to our deployment, but job label is not unique in our case. We have job="vmstorage-1a" that has 2 pods - pod="vmstorage-1a-0" and pod="vmstorage-1a-1". And I think it makes sense to see their restarts separately.

The purpose of the annotation is just to show that there were a restart, so user can start the investigation or correlate the change of metrics with a restart. Showing restarts for each instance or pod could be overwhelming for installations with hundreds of pods. The dashboard should remain usable for all clusters: small and big.

**Comment by hagen1778** [comment]
I'm closing this issue because the bug mentioned in the first post was fixed. Feel free to open a new ticket if you have suggestions regarding annotation queries improvements.
