### ISSUE TITLE
vmagent -  documentation on stream aggregations

### ISSUE THREAD

**Issue by arnoldyahad** [VictoriaMetrics/VictoriaMetrics#6317]
### Describe the bug

Hey VM team!
i'm trying to use stream aggregation on vmagent, and reading the docs here:
https://docs.victoriametrics.com/stream-aggregation/#rate_sum

i've tried to use rate_sum as the documentation shows but it looks like this parameter doesnt exist: 

```
{"ts":"2024-05-21T09:49:03.063Z","level":"fatal","caller":"VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:872","msg":"cannot initialize stream aggregators from -remoteWrite.streamAggr.config=\"/config/stream.yml\": cannot initialize aggregators from \"/config/stream.yml\": cannot initialize aggregator #0: unsupported output=\"rate_sum\"; supported values: [total total_prometheus increase increase_prometheus count_series count_samples unique_samples sum_samples last min max avg stddev stdvar histogram_bucket quantiles(phi1, ..., phiN)]; see https://docs.victoriametrics.com/stream-aggregation/; see https://docs.victoriametrics.com/stream-aggregation/#stream-aggregation-config"}
Stream closed EOF for kube-system/vmagent-victoria-metrics-agent-74c9c6d87-2vmkf (victoria-metrics-agent)
```

also, 
the documentation specified there are 2 variables that can be chosen to use stream aggregations: 
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/18227724/be4c641c-d5f4-45c4-b9b9-c6efc686e34b)
(same page: https://docs.victoriametrics.com/stream-aggregation/index.html)

but it looks like only the second option works (remoteWrite.streamAggr.config) although it says both of them should work on vmagent. 

so there are 2 questions here:
1. does `streamAggr.config` should work on vmagent? or is it documentation mistake?
2. does `rate_sum` should work?

thanks a lot!

### To Reproduce

use vmagent helm chart:
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-agent
deploy version 1.101.0 
and try to set `-streamAggr.config=/path/to/your/config.yml` 
(this will fail) 
try setting:  `-remoteWrite.streamAggr.config=/path/to/your/config.yml` (this will work)
and for the config of the stream aggregation, try to use `rate_sum`

### Version

```
/ # ./vmagent-prod --version
vmagent-20240425-145801-tags-v1.101.0-0-g5334f0c2c
```

**Comment by hagen1778** [comment]
Hello @arnoldyahad! 
The mentioned features were merged to `master` but weren't released yet - they're listed under the `tip` section in changelog https://docs.victoriametrics.com/changelog/#tip

But documentation is built from `master` branch. So you see features that will be available only in the next release.
