### ISSUE TITLE
v1.97 OSS images are no longer published to docker hub

### ISSUE THREAD

**Issue by ptimofee** [VictoriaMetrics/VictoriaMetrics#6320]
### Describe the bug

The latest OSS version from v1.97 LTS branch available in dockerhub is v1.97.1.
However, it's been released 3 more minor version since then. But no images were published.

### To Reproduce

Try pulling any OSS image of v1.97 LTS branch that is  v1.97.1+ from dockerhub
For example:
```
docker pull victoriametrics/vmauth:v1.97.4
docker pull victoriametrics/vmagent:v1.97.4
docker pull victoriametrics/vmalert:v1.97.4
docker pull victoriametrics/vmselect:v1.97.4-cluster
docker pull victoriametrics/vminsert:v1.97.4-cluster
docker pull victoriametrics/vmstorage:v1.97.4-cluster
```

### Version

 v1.97.1+

**Comment by Haleygo** [comment]
Please check https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5811 for details, close as duplicated.
