### ISSUE TITLE
vmagent - aggregation based on metric type

### ISSUE THREAD

**Issue by arnoldyahad** [VictoriaMetrics/VictoriaMetrics#6325]
### Is your question request related to a specific component?

vmagent
stream aggregations

### Describe the question in detail

Hello, 

We have several questions regarding stream aggregations (https://docs.victoriametrics.com/stream-aggregation/index.html#stream-aggregation-config) 

we want to aggregate based on the metric type(gauge/counter) while dropping a label and keeping the original name for the new aggregated metric for example:

```
- match: '{__name__=~".+"}'
  interval: 5m
  drop_input_labels: [kubernetes_pod_name]
  type:  gauge # doesn't exist yet
  outputs: [avg]
```

or: 
```
- match: '{__name__=~".+_"}'
  interval: 5m
  drop_input_labels: [kubernetes_pod_name]
  type: counter  # doesn't exist yet
  outputs: [total]
```

the result we want to get is, for example `http_requests_total`, which is aggregated and without the `kubernetes_pod_name` label.

thanks a lot!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Haleygo** [comment]
Hello!
>we want to aggregate based on the metric type(gauge/counter)

I'm afraid it's not possible, since metric samples don't contain information like metadata for vmagent to tell the type. And metrics exposer can name their metrics freely.
If you know all your metrics which have `_total` suffix is counter, you can pass specific filter to the match
```
- match: '{__name__=~".*_total"}'
  interval: 5m
  drop_input_labels: [kubernetes_pod_name]
  outputs: [total]
```

**Comment by dudicoco** [comment]
Hi @Haleygo,

Target endpoints do contain metadata on the metric types, see example:
![Screenshot_2019-10-18_13-27-36](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/51051860/4b3145ae-e055-4bd1-a97f-78c2a5bcae11)

Can we use the TYPE field to correlate the metrics to their appropriate rule accordingly?

**Comment by hagen1778** [comment]
Hey @dudicoco!
If exporters you collect metrics from satisfy [Prometheus naming convention ](https://prometheus.io/docs/practices/naming/), then there is no need in reading metadata to distinguish between metric types:
1. Everything that ends on `_total` or `_bucket` is a cumulative counter and should be aggregated with `total` output
2. Everything else is a gauge, and should be aggregated with appropriate aggregation output of your choice (max, min, avg, etc.)
