### ISSUE TITLE
-reloadAuthKey for vmauth/vmagent/vmalert should override -httpAuth.{username,password}

### ISSUE THREAD

**Issue by ptimofee** [VictoriaMetrics/VictoriaMetrics#6329]
### Describe the bug

If vmauth/vmagent/vmalert have defined -httpAuth.username and -httpAuth.password values then http requests to these services should provide basic authentication.
There are multiple http endpoints (urls) for these service that handle reload, metrics, flags, etc.
Each of those urls have their own settings for a separate auth if needed, for example:
- reloadAuthKey
- metricsAuthKey
- flagsAuthKey
- pprofAuthKey
- etc.

All of them override basic authentication set in  -httpAuth.username and -httpAuth.password. Except for reloadAuthKey.

reloadAuthKey set to some value still needs a http request to provide basic auth set in -httpAuth.* AND AuthKey set in -reloadAuthKey.

This seems wrong and reloadAuthKey probably should override what is set in -httpAuth.username and -httpAuth.password. Just like other *AuthKey options listed above.

**NOTE** if this is expected behavior then k8s victoria-metrics-operator should handle it properly (it does handle reloadAuthKey properly, but not -httpAuth.{username,password})

### To Reproduce

1. Take vmauth or vmagent or vmalert
2. Set  -httpAuth.username and -httpAuth.password
3. Also set -reloadAuthKey
4. Try trigger reload via http. It will work only if both basic auth and AuthKey provided.

### Version

```
~ $ /vmalert-prod --version
vmalert-20240425-145844-tags-v1.101.0-0-g5334f0c2c
```

**Comment by Haleygo** [comment]
Hi,
I believe it's intentional to protect endpoints like `/-/reload` or `/config`.
>NOTE if this is expected behavior then k8s victoria-metrics-operator should handle it properly (it does handle reloadAuthKey properly, but not -httpAuth.{username,password})

Thanks for reporting, I will fix that.

**Comment by ptimofee** [comment]
This is how I tested it in the vmalert reloader container:
```
wget -O- http://<USER>:<PASSWD>@<IP>:8080/-/reload?authKey=<KEY>
```

**Comment by Haleygo** [comment]
Thanks @ptimofee ,
after discussion, we will make `reloadAuthKey`, `configAuthKey`, `flagsAuthKey`, `pprofAuthKey` behavior the same way,
but keys like `-snapshotAuthKey`, `-forceMergeAuthKey` are still protected by httpAuth.*.

**Comment by ptimofee** [comment]
@Haleygo  thanks for the link. I don't see **vmauth** in the list of software being changed. Is it going to be change in a separate PR?

**Comment by Haleygo** [comment]
> @Haleygo thanks for the link. I don't see **vmauth** in the list of software being changed. Is it going to be change in a separate PR?

The handlerWrapper is shared by all the components including vmauth, but I missed some flag descriptions, added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6338/commits/7a5950d9eb841ed4f0574338b8e56593b156e424, thanks for notice)

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6338 has been merged and will be included into the next release.

**Comment by hagen1778** [comment]
@ptimofee starting from [v1.102.0-rc2](https://docs.victoriametrics.com/changelog/#v11020-rc2) all VM components will prioritize `-configAuthKey` and `-reloadAuthKey` over `-httpAuth.*` settings.
