### ISSUE TITLE
Help need to debug ~ possible issue data from vmstorage cluster  A/A not exactly 1

### ISSUE THREAD

**Issue by renchili** [VictoriaMetrics/VictoriaMetrics#6331]
### Is your feature request related to a problem? Please describe

We wounder if the below is correct or not:
Some time  in cluster mode vmstorages return unsynchronized metrics-A and metrics-B due to each vmstorage may in different delay condition.

What we expected is that possible to log which vmstorage the data comes from, the query made to tsdb and the exact time/ time range and step.

### Describe the solution you'd like

we want to have jaeger tracing system that can mark query from client side till vmstorage tsdb query, and logging all to a log system
is the same as https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1629

and Thanos / prometheus support this https://thanos.io/v0.30/thanos/tracing.md/#tracing

### Additional information

we have some times got  by /query?query=metrics_a/metrics_b  result != 1  but  few minute afterwards by query_range?query=metrics_a/metric_b then we got all values =1

for example: min(sum(increase(mesh_permissionService_server_request_path_counter{upstream_service="PermissionService",status="200"}[1m])) by (path) /sum(increase(mesh_permissionService_server_request_path_counter{ upstream_service="PermissionService",status!~"^4.*"}[1m])) by (path)) <=  0.995, result: 1716421740,"0.9709897610921502"

but few minute later  on grafana it show No data.

**Comment by jiekun** [comment]
I would like to offer a few input here if you don't mind~
1. in webui you could use [query tracing](https://docs.victoriametrics.com/#query-tracing). It will offer some informations that you might interested in:

<img width="939" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/30280396/dc320d76-89fb-459c-a0bd-28e588ef675d">

2. External distributed tracing is great. But it's hard for me to seek for the information I need when I was using Thanos with distributed tracing. It reports 10k+ spans for a query.

I think VictoriaMetrics does a better job in this scenario. Perhaps you could start by trying query tracing. If it doesn't meet our requirements, we can optimize it or consider other external tracing solutions.
