### ISSUE TITLE
How does drop_uneeded_labels work with stream aggregation?

### ISSUE THREAD

**Issue by dudicoco** [VictoriaMetrics/VictoriaMetrics#6340]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

According to https://docs.victoriametrics.com/stream-aggregation/#dropping-unneeded-labels a typical use case is to drop the replica label before aggregation.
How would this work exactly? If I have 10 different time series which are only unique by their replica label how does vmagent knows which samples to keep after dropping the replica label?

The Prometheus docs state that this should not be done as metrics need to be uniquely labeled: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config:~:text=Care%20must%20be%20taken%20with%20labeldrop%20and%20labelkeep%20to%20ensure%20that%20metrics%20are%20still%20uniquely%20labeled%20once%20the%20labels%20are%20removed.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
@dudicoco The core idea of streaming aggregation is to apply [aggregation functions](https://docs.victoriametrics.com/stream-aggregation/#aggregation-outputs) to the input timeseries and save the result as a new timeseries.

As per Prometheus documentation, it is not possible to drop labels as series must be uniquely labeled. With streaming aggregation only new series must be uniquely labeled.

For example, incoming series are:
```
my_metric{replica="1"} 21
my_metric{replica="2"} 32
my_metric{replica="3"} 10
```

When applying the following streaming aggregation rule:
```
- match: my_metric
  interval: 1m
  without: [replica]
  outputs: [avg]
  keep_metric_names: true
```

The output will contain(see naming rules documentation [here](https://docs.victoriametrics.com/stream-aggregation/#output-metric-names)):
```
my_metric:1m_without_repilca_avg 21
```

**Comment by dudicoco** [comment]
Hi @zekker6,

The example you've provided removes the label during the aggregation: https://docs.victoriametrics.com/stream-aggregation/#aggregating-by-labels

In the docs that i've linked to it explicitly states that it drops the labels before aggregation, this is by using the `drop_input_labels` field.

**Comment by zekker6** [comment]
@dudicoco Sorry for the confusion. The idea of `drop_input_labels` is to help [de-duplication](https://docs.victoriametrics.com/stream-aggregation/#deduplication) to remove duplicate samples which were scraped by different instances of scraping agent which is running in HA mode.
Usually, it is needed to use `drop_input_labels` together with `-streamAggr.dedupInterval`  command-line flag or `dedup_interval` parameter to make sure that only 1 sample will be processed by streaming aggregation.

**Comment by dudicoco** [comment]
thanks for the clarification @zekker6
