### ISSUE TITLE
irate function aggregation is abnormally high

### ISSUE THREAD

**Issue by hichenxinyu** [VictoriaMetrics/VictoriaMetrics#6350]
### Describe the bug

When we query the pod CPU usage, we found that the irate data will be distorted and appear to be abnormally high. It is normal to directly query the original data without using irate.

The deployment method is vm-operator，cluster version:1.91.3

1. raw data
container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/bc9b11de-0c4d-4fa5-9b57-ac50670a4450)

2. rate
rate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/2480ba09-865d-45da-8e58-2ee62ae10de3)

3. irate
irate(container_cpu_usage_seconds_total{container!="POD",container!="",pod="gs-gf-canary-4lttq"}[60s])
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/17958216/40a412eb-a3e9-47de-82e1-d513a1b6d958)

### To Reproduce

irate(container_cpu_usage_seconds_total{container!="POD",container!=""}[60s])

### Version

vmstorage-20230630-163052-tags-v1.91.3-cluster-0-g12f262c331

**Comment by AndrewChubatiuk** [comment]
closing as it duplicates https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5986
