### ISSUE TITLE
How to access and view indexdb in vmstorage ? 

### ISSUE THREAD

**Issue by buzzlightyear2k** [VictoriaMetrics/VictoriaMetrics#6352]
### Is your question request related to a specific component?

vmstorage, indexdb

### Describe the question in detail

- Im running Vicrotia Metrics cluster mode in a Kubernetes cluster. How can i access and view indexdb in vmstorage node?

**Comment by trong11** [comment]
Help me

**Comment by jiekun** [comment]
Hi. I think indexdb does not expose access to the user. What's the scenario for viewing data in it?
