### ISSUE TITLE
Question when `vmselect` query data 

### ISSUE THREAD

**Issue by buzzlightyear2k** [VictoriaMetrics/VictoriaMetrics#6355]
### Is your question request related to a specific component?

vmselect, vmstorage

### Describe the question in detail

I have 2 `vmstorage` nodes, when `vmselect` query data, does it select data from 1 `vmstorage` or both ?

**Comment by jiekun** [comment]
Hi @trong11 

vmselect query necessary data blocks from all configured **vmstorage** nodes.

You can find detailed architecture and description here: https://docs.victoriametrics.com/cluster-victoriametrics/#architecture-overview

**Comment by trong11** [comment]
> Hi @trong11
> 
> vmselect query necessary data blocks from all configured **vmstorage** nodes.
> 
> You can find detailed architecture and description here: https://docs.victoriametrics.com/cluster-victoriametrics/#architecture-overview

Thank you @jiekun , I have one more question: Each `vmstorage` has 1 `indexdb` or they share the same `indexdb`

**Comment by jiekun** [comment]
> Each vmstorage has 1 indexdb or they share the same indexdb?

By "share the same indexdb" I assume you mean they are mirrored of each other?

From my understanding,  `vminsert` decides which `vmstorage` they should send data to. And each `vmstorage` holds different data without overlap in this context. So `vmstorage` does not share or store the same `indexdb`.

**Comment by trong11** [comment]
> > Each vmstorage has 1 indexdb or they share the same indexdb?
> 
> By "share the same indexdb" I assume you mean they are mirrored of each other?
> 
> From my understanding, `vminsert` decides which `vmstorage` they should send data to. And each `vmstorage` holds different data without overlap in this context. So `vmstorage` does not share or store the same `indexdb`.

So that means each `vmstorage` node holds different data, i thought they replicate data of each other

**Comment by jiekun** [comment]
While data is **sharded** in different N instances, vmstorage is **also** capable of **replicating** data for M copies (You need to deploy N * M instances). For more information on replication and data safety in vmstorage, please refer to the documentation: 
https://docs.victoriametrics.com/cluster-victoriametrics/#replication-and-data-safety.

It's very flexible and depends on the available resources and the needs of the user.

**Comment by trong11** [comment]
> While data is **sharded** in different N instances, vmstorage is **also** capable of **replicating** data for M copies (You need to deploy N * M instances). For more information on replication and data safety in vmstorage, please refer to the documentation: https://docs.victoriametrics.com/cluster-victoriametrics/#replication-and-data-safety.
> 
> It's very flexible and depends on the available resources and the needs of the user.

If i replicate data to 2 `vmstorage` node, so what `indexdb` will look like because from my understanding `indexdb` will map canonical_metric_name -> tsid? Does that means each `vmstorage` node have its own `indexdb`

**Comment by jiekun** [comment]
> each vmstorage node have its own indexdb
Yes
