### ISSUE TITLE
Merge snaps

### ISSUE THREAD

**Issue by hidakafinzelz** [VictoriaMetrics/VictoriaMetrics#6356]
### Is your question request related to a specific component?

How to merge snaps

### Describe the question in detail

I have many snaps like snap_01, snap_02...., 
Diffrent snaps with diffent timeline,
snap_01 20240501
snap_02 20240502
snap_03 20240503

I want merge then to a laert snap call snap_202405

when i vmrestore, i can use the large snap

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hidakafinzelz** [comment]
> Hey @hidakafinzelz There's no ability to merge independent snapshots. Please consider using [incremental backups](https://docs.victoriametrics.com/vmbackup/#incremental-backups).

Thanks. I'll try it.

**Comment by hidakafinzelz** [comment]
> Hey @hidakafinzelz There's no ability to merge independent snapshots. Please consider using [incremental backups](https://docs.victoriametrics.com/vmbackup/#incremental-backups).

It's a pity that this plan is not suitable for me.

The memory of my device is very low, only 100MB. What I hope is that after I complete the data backup, I can delete the old historical data and then restart victoriametrics. At this time, its memory usage will be very low.When I use `restore` to restore data, I can restore it all at once instead of restoring each backup one by one.

The method you provided can be used for incremental backup, but when I clear the data and back up again, it will overwrite the data I have backed up, instead of just backing up according to the timeline as I expected.

**Comment by AndrewChubatiuk** [comment]
for your case it's possible to use external storage for backup
https://docs.victoriametrics.com/vmbackup/#supported-storage-types

**Comment by hidakafinzelz** [comment]
ok, thank u
