### ISSUE TITLE
vmagent Retry mechanism

### ISSUE THREAD

**Issue by SRE-Rick** [VictoriaMetrics/VictoriaMetrics#6357]
### Is your question request related to a specific component?

vmagent   vminsert  vmstorage

### Describe the question in detail

There may be network fluctuations between vmagent and vmstorage, which can lead to data loss. If the write fails, Can vmagent retry? How should I configure it?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
Hey @SRE-Rick 
Looks like you can find an answer in [this](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5486) issue

**Comment by SRE-Rick** [comment]
> Hey @SRE-Rick Looks like you can find an answer in [this](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5486) issue
Hey @AndrewChubatiuk  
That answer doesn't seem to have been accepted in the official version?

**Comment by hagen1778** [comment]
Hello @SRE-Rick !

> There may be network fluctuations between vmagent and vmstorage, which can lead to data loss. If the write fails, Can vmagent retry? 

vmagent will automatically retry write attempts with exponential backoff. The retries will continue happening until one of two conditions are met:
1. Remote URL restored its availability and is able process requests from vmagents
2. On-disk queue for unsent data exceeds configured `--remoteWrite.maxDiskUsagePerURL` limit. In this case, data will start dropping.

> How should I configure it?

You don't need to configure retry policy. But you should be aware of the queue for pending data - see https://docs.victoriametrics.com/vmagent/#calculating-disk-space-for-persistence-queue
