### ISSUE TITLE
can not get some value from categraf

### ISSUE THREAD

**Issue by zhangchi2217** [VictoriaMetrics/VictoriaMetrics#6359]
### Describe the question in detail

categraf is data source ,  i  can get two value in categraf,like:
`08:11:05 snmp_optical_hwEntityOpticalVendorSn agent_hostname=Nightingale ip=172.20.189.5 name=AC6508 region=sohu role=ac AE230600016906`
`08:11:05 snmp_optical_hwEntityOpticalVendorSn agent_hostname=Nightingale ip=172.20.189.5 name=AC6508 region=sohu role=ac 2000198390607`

but in vm,  just get one value, like :
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/110875942/b8e9bb2f-bf3e-497f-bfb3-2b69bade7b7d)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/110875942/3e916f3d-e8ed-4d77-9b88-4b42eead1c96)

Is it because of the length or type of the text?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zhangchi2217** [comment]
> hey @zhangchi2217 is `AE230600016906` a hex value or a string?

it is a string~

**Comment by AndrewChubatiuk** [comment]
VictoriaMetrics doesn't support strings as values

**Comment by zhangchi2217** [comment]
VictoriaMetrics doesn't support strings as values
