### ISSUE TITLE
vmstorage sets different data retention periods based on different metrics

### ISSUE THREAD

**Issue by SRE-Rick** [VictoriaMetrics/VictoriaMetrics#6360]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Can I set different data retention periods for Vmstorage based on different indicators?  I have two collection tools: node_exporter and grok_exporter.  I want to keep the data of node_exporter for only 30 days.  The data of grok_exporter is kept for 1 year

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
Hey @SRE-Rick
Suppose you're looking for [retention filters](https://docs.victoriametrics.com/#retention-filters)
Note: it's supported by enterprise version of VictoriaMetrics only

**Comment by SRE-Rick** [comment]
> Hey @SRE-Rick Suppose you're looking for [retention filters](https://docs.victoriametrics.com/#retention-filters) Note: it's supported by enterprise version of VictoriaMetrics only

Are there other ways to achieve the same goal besides the enterprise version?

**Comment by AndrewChubatiuk** [comment]
it's possible to [delete metrics completely](https://docs.victoriametrics.com/url-examples/#apiv1admintsdbdelete_series) for a match expression, but for custom retention rules you should use retention filters

**Comment by SRE-Rick** [comment]
> it's possible to [delete metrics completely](https://docs.victoriametrics.com/url-examples/#apiv1admintsdbdelete_series) for a match expression, but for custom retention rules you should use retention filters

Hey @AndrewChubatiuk 
According to your guidance, I call the  curl -v http://<vmselect>:8481/delete/0/prometheus/api/v1/admin/tsdb/delete_series -d 'match[]=rest_client_request_duration_seconds_bucket' -d 'start=1701388800.0' -d 'end=1701389100.0'  Specifies the time range. But he made a mistake. Is there something wrong with my usage
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/86993048/40e80978-6031-4d0e-adc0-601353e738d4)

**Comment by AndrewChubatiuk** [comment]
this api call doesn't support custom time ranges
there's also another approach. you can have multiple VM clusters with different retention periods and vmselect in front of all of them to be able to query all metrics

**Comment by SRE-Rick** [comment]
> this api call doesn't support custom time ranges there's also another approach. you can have multiple VM clusters with different retention periods and vmselect in front of all of them to be able to query all metrics
prometheus supports deletion within specified time ranges, is victoriametrics not compatible with this api?
https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series

**Comment by SRE-Rick** [comment]
> this api call doesn't support custom time ranges there's also another approach. you can have multiple VM clusters with different retention periods and vmselect in front of all of them to be able to query all metrics

prometheus supports deletion within specified time ranges, is victoriametrics not compatible with this api?

**Comment by AndrewChubatiuk** [comment]
These query params are not yet supported
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0a71bad72285a5072fa56dc57103b59b9a74c030/app/vmselect/prometheus/prometheus.go#L479

**Comment by jiekun** [comment]
Close as answered.
