### ISSUE TITLE
How `indexdb` works ?

### ISSUE THREAD

**Issue by trong11** [VictoriaMetrics/VictoriaMetrics#6363]
### Is your question request related to a specific component?

indexdb

### Describe the question in detail

![dasda](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/86591649/cd6d7b77-a21d-4476-92d1-54818bfcab15)

I deep into `indexdb` and see files, can someone explain what do those files mean and how can i see the data inside them

**Comment by Amper** [comment]
Hey @trong11, i've answered here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3268#issuecomment-2138044760
