### ISSUE TITLE
vmbackup data compression

### ISSUE THREAD

**Issue by hidakafinzelz** [VictoriaMetrics/VictoriaMetrics#6364]
### Is your question request related to a specific component?

vmbackup

### Describe the question in detail

I use vmbackup to backup data to filesystem
`
vmbackup-prod -storageDataPath=/data/victoria-metrics/data/  -snapshotName=20240524104905-17D266615E0E73DD -dst=fs:///data/victoria-metrics/backup
`

But the file is too large. I have to use `zip -r backup.zip backup` to compress the data.

Is there any method to compose data is vmbackup-prod gracefully?

Thanks!!!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Amper** [comment]
Hey @hidakafinzelz.

> Is there any method to compose data is vmbackup-prod gracefully?

No, there is not. Could you please clarify what you mean by "compose data gracefully"? Compression?

**Comment by hidakafinzelz** [comment]
> Hey @hidakafinzelz.
> 
> > Is there any method to compose data is vmbackup-prod gracefully?
> 
> No, there is not. Could you please clarify what you mean by "compose data gracefully"? Compression?
Thanks.

 "compose data gracefully"
  means that I can use a flag like `--zip` to backup data to a zipfile but not a dir , for the dir is so large.

**Comment by Amper** [comment]
We have no plans to implement zip compression: it can be done by the separate command you provided above + is unlikely to significantly reduce the amount of data.

**Comment by hidakafinzelz** [comment]
ok, thank u
