### ISSUE TITLE
vmctl `--vm-disable-progress-bar` flag does not actually disable the progress bar

### ISSUE THREAD

**Issue by IsQiao** [VictoriaMetrics/VictoriaMetrics#6367]
### Describe the bug

when i set `--vm-disable-progress-bar=true`, the progress bar still display.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8536046/263701bd-9d0f-4a4b-aecb-3d424684cb43)

### To Reproduce

1. run `vmctl prometheus -s --verbose=false --vm-disable-progress-bar=false --vm-addr="http://127.0.0.1:9090" --prom-snapshot="/home/orion/prometheus"`
2. run `vmctl prometheus -s --verbose=false --vm-disable-progress-bar=true --vm-addr="http://127.0.0.1:9090" --prom-snapshot="/home/orion/prometheus"`
3. compare the different. found the progress-bar still display.

### Version

``` shell
$ vmctl -v
vmctl version vmctl-20240425-150251-tags-v1.101.0-0-g5334f0c2c
```

**Comment by IsQiao** [comment]
related issue(#4432), because the progress bar need to config user terminal properties in no terminal environment.

**Comment by hagen1778** [comment]
@IsQiao https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6385 should address the issue with disabling progress bar. Additionally, this PR deprecates `--vm-disable-progress-bar` in favour of `--disable-progress-bar` flag, which should consistently disable progress bar for all migration modes.

This change will be included into the next release. Meanwhile, you can [build vmctl from sources](https://docs.victoriametrics.com/vmctl/#how-to-build).

**Comment by IsQiao** [comment]
thanks a lot! 😊

**Comment by hagen1778** [comment]
I'll re-open the issue. It will be closed once the new release is published.

**Comment by valyala** [comment]
The `--disable-progress-bar` command-line flag is available in [vmctl](https://docs.victoriametrics.com/vmctl/) starting from [v1.102.0-rc2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.102.0-rc2).
