### ISSUE TITLE
what is more efficient way to keep metrics

### ISSUE THREAD

**Issue by teror4uks** [VictoriaMetrics/VictoriaMetrics#6368]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

hello everyone, 

Could you help me understand what is a better way to keep metrics?

For example, I have a function that can return either an error or success on an IO operation.

```golang
func Send() error {
     err := send()
     if err != nil {
         metrics.CountM("send", Label{Name: "failure", "on_send"})
     }
     metrics.CountM("send", Label{Name: "success", "on_send})
     return nil
}
```

so now I can visualize my counter in Grafana dashboard like this: 

```
sum(increase(send)) by (failure, success) 
```

for me, it looks fine, but it has another approach where I split one metric to two:

```golang
func Send() error {
     err := send()
     if err != nil {
         metrics.count("send_failed")
     }
     metrics.count("send_success")
     return nil
}
```

So what is better for VM search engine and space consumption? Keep two metrics or use one with different labels?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Amper** [comment]
Hey @teror4uks.
For VM in both cases (with labels and metrics) these are two different time series with different identifiers (TSID), so the only thing that matters in this case is usability - if you really need statuses in your queries, it seems right to put them in a separate label.

**Comment by teror4uks** [comment]
thanks @Amper it explains a lot :+1:
