### ISSUE TITLE
How `indexdb` store data? 

### ISSUE THREAD

**Issue by trong11** [VictoriaMetrics/VictoriaMetrics#6371]
### Is your question request related to a specific component?

vmstorage, indexdb

### Describe the question in detail

I just want to know how `indexdb` store data, anyone know how can i check it ?

**Comment by trong11** [comment]
I have searched inside indexdb looks like this:

```
|-- indexdb
        |-- 166E885A1EDE6CFB # table, unix nano seconds timestamp in hex
        |       |-- 1196553400_4504368_16805658E302A9F3 # part <- blocks <- items/[]byte
        |       |    |-- index.bin
        |       |    |-- items.bin
        |       |    |-- lens.bin
        |       |    |-- metadata.json
        |       |    `-- metaindex.bin
        |       |-- 122079861_288959_168B127D038EED7B # itemCount_blocksCount_garbage
        |      |     |-- index.bin
        |      |     |-- items.bin
        |      |     |-- lens.bin
        |      |     |-- metadata.json
        |      |     `-- metaindex.bin
        |      |-- flock.lock
        |      |-- tmp
        |      `-- txn
       `-- snapshots
```

Can someone explain what line `1196553400_4504368_16805658E302A9F3` means ?

**Comment by Amper** [comment]
Hey @trong11, i've answered here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3268#issuecomment-2138044760

**Comment by trong11** [comment]
> Hey @trong11, i've answered here: [#3268 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3268#issuecomment-2138044760)

Thank you very much bro <3
