### ISSUE TITLE
Fix crashloops - Improve documentation by listing which components flags apply

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/VictoriaMetrics#6375]
### Is your feature request related to a problem? Please describe

Crashlooping when using using the wrong flags on the wrong cluster component.

```
flag provided but not defined: -search.maxTSDBStatusSeries

vmstorage stores time series data obtained from vminsert and returns the requested data to vmselect.

See the docs at https://docs.victoriametrics.com/cluster-victoriametrics/ .

Run "/vmstorage-prod -help" in order to see the description for all the available flags
```

### Describe the solution you'd like

The online [documentation](https://docs.victoriametrics.com/#list-of-command-line-flags) does not appear to break down which component flag apply to. Please break down the flags by component.

Given the API errors also do not correctly list the problem component:
```
"cannot obtain tsdb stats: cannot fetch tsdb status from vmstorage nodes: cannot obtain tsdb status 
from vmstorage vmstorage-vmcluster-0.vmstorage-vmcluster.monitoring:8401: cannot execute 
funcName=\"tsdbStatus_v5\" on vmstorage \"10.36.2.31:8401\": the number of matching timeseries 
exceeds 10000000; either narrow down the search or increase -search.max* command-line flag values 
at vmselect; see https://docs.victoriametrics.com/#resource-usage-limits"
```

Everything in that error message points to `vmstorage` and a limit on TSDB  status. However, this is a `vmselect` error and apparently its not `vmstorage` that is the issue.

**Comment by Amper** [comment]
Hey, @mbrancato.
You've read the vmsingle documentation, in the cluster documentation the flags are separated by component: https://docs.victoriametrics.com/cluster-victoriametrics/#list-of-command-line-flags-for-vmselect

**Comment by mbrancato** [comment]
Ahh, thanks - I've struggled to find some thing since the doc site changed.
