### ISSUE TITLE
How Victoria Metrics stores data ?

### ISSUE THREAD

**Issue by buzzlightyear2k** [VictoriaMetrics/VictoriaMetrics#6377]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

I dived into Victoria Metrics and found this structure:
```
data
|-- big
|    `-- 2021_08 # rowsCount_blocksCount_minTime_maxTime_garbage
|       `-- 10037958883_4913358_20210812025654.031_20210813004004.028_169705A5DBF810F2
|                |-- index.bin
|                |-- metaindex.bin
|                |-- timestamps.bin
|                `-- values.bin
`-- small
          |-- 2021_08
               `-- 100794256_4270757_20210824023530.636_20210824024140.896_169705A5DBFB1074
                    |-- index.bin
                    |-- metaindex.bin
                    |-- timestamps.bin
                    `-- values.bin
```

Can someone please explain :

- Why it has `big` and `small` directory

- What do those number  `2021_08 ` and `10037958883_4913358_20210812025654.031_20210813004004.028_169705A5DBF810F2` means ?

- What do those .bin file do 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by dmitryk-dk** [comment]
Hi @trong11 ! 
`big` - it is a big parts of the data
`small` - it is a small parts of the data

```
In-memory parts are persisted to disk into part directories under the <-storageDataPath>/data/small/YYYY_MM/ folder, where YYYY_MM is the month partition for the stored data. For example, 2022_11 is the partition for parts with [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) from November 2022. Each partition directory contains parts.json file with the actual list of parts in the partition.
```

You can find a lot of information in this part of the [documentation](https://docs.victoriametrics.com/?highlight=parts#storage)

**Comment by jiekun** [comment]
Hi. I think you could refer to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3268.
