### ISSUE TITLE
vmagent: incorrect reporting of number of dropped targets

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#6381]
### Describe the bug

vmagent reports incorrect amount of dropped targets, the number constantly grows and does not help to understand a real number of dropped targets.

### To Reproduce

The reason for this is [the following code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c81a633b025e3cb051a0a4baa31fe245b06f359e/lib/promscrape/targetstatus.go#L359-L385): 
```
 func (dt *droppedTargets) Register(originalLabels *promutils.Labels, relabelConfigs *promrelabel.ParsedConfigs, reason targetDropReason, clusterMemberNums []int) { 
 	if originalLabels == nil { 
 		// Do not register target without originalLabels. This is the case when *dropOriginalLabels is set to true. 
 		return 
 	} 
 	// It is better to have hash collisions instead of spending additional CPU on originalLabels.String() call. 
 	key := labelsHash(originalLabels) 
 	dt.mu.Lock() 
        // Step 1 - check if item is not present in list of targets and increment the counter
 	if _, ok := dt.m[key]; !ok { 
 		dt.totalTargets++ 
 	} 
 	dt.m[key] = droppedTarget{ 
 		originalLabels:    originalLabels, 
 		relabelConfigs:    relabelConfigs, 
 		dropReason:        reason, 
 		clusterMemberNums: clusterMemberNums, 
 	} 
 	if len(dt.m) > *maxDroppedTargets { 
 		for k := range dt.m {
                        // Step 2 - Delete targets until number of targets is lower than *maxDroppedTargets
 			delete(dt.m, k) 
 			if len(dt.m) <= *maxDroppedTargets { 
 				break 
 			} 
 		} 
 	} 
 	dt.mu.Unlock() 
 } 
```

Once number of targets stored in `dt.m` will reach `*maxDroppedTargets` and will be cleared `dt.totalTargets` will grow infinity since target will be evicted over and over for the subsequent `Register` calls.

I would suggest to use [`lib/bloomfilter`](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/bloomfilter/filter.go) to replace existing counter with a bloom filter. The logic can be updated to:
- save the target both in bloom filter and `dt.m`
- use bloom filter in order to check that target was already registered.

This will slightly increase resource usage but will give much better understanding of real amount of targets exceeding `*maxDroppedTargets`.

### Version

v1.101.0

**Comment by valyala** [comment]
How about an easier solution - stop registering dropped targets in `dt.m` and stop incrementing `dt.totalTargets` after `len(dt.m) reaches `*maxDroppedTargets`?

**Comment by valyala** [comment]
It looks like [the default value for `-promscrape.maxDroppedTargets` command-line flag](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8f254232bb2216d6355ca7d1c2e06b1590cceaf0/lib/promscrape/targetstatus.go#L23) can be increased significantly without significant increase in memory usage after [this commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/4513893ead4ecb4a6dd6b8d0ed7b2bd6bc0cafe5). This should help debugging issues related to improperly dropped targets. Let's increase it from 1000 to 10000. If the original length of labels per each target is 1000, then 10K targets will need 10K*1000=10MB of memory at the `droppedTargets` struct. This is pretty small number compared to additional memory vmagent needs for scraping thousands of targets.

**Comment by hagen1778** [comment]
@zekker6 starting from [v1.102.0-rc2](https://docs.victoriametrics.com/changelog/#v11020-rc2) vmagent tracks up to 10K of dropped targets instead of 1K. This should significantly reduce probability of false numbers when reporting dropped target. I'll close this issue for now, feel free to re-open if it still remains significant.
