### ISSUE TITLE
victoria-metrics: mitigate timing attacks for basic auth and authkey comparisions

### ISSUE THREAD

**Issue by wasim-nihal** [VictoriaMetrics/VictoriaMetrics#6392]
### Describe the bug

Currently, the comparison of basic auth credentials and authKeys in Victoria Metrics happens in linear time. This might be vulnerable to timing attacks where the attacker can approximate the credentials from the TCP timestamps.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/b97916276f51fd3857e2d529cba3875c18842f24/lib/httpserver/httpserver.go#L450

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/b97916276f51fd3857e2d529cba3875c18842f24/lib/httpserver/httpserver.go#L433

The proposal is to compare these in constant time using `crypto/subtle`'s `ConstantTimeCompare` method as below.

**For AuthKeys:**
```
if subtle.ConstantTimeCompare([]byte(r.FormValue("authKey")), []byte(flagValue)) != 1 {
		authKeyRequestErrors.Inc()
		http.Error(w, fmt.Sprintf("The provided authKey doesn't match -%s", flagName), http.StatusUnauthorized)
		return false
	}
```

**For Basic Auth Credentials:**
```
username, password, ok := r.BasicAuth()
	if ok {
		if subtle.ConstantTimeCompare([]byte(username), []byte(*httpAuthUsername)) == 1 && subtle.ConstantTimeCompare([]byte(password), []byte(httpAuthPassword.Get())) == 1 {
			return true
		}
		authBasicRequestErrors.Inc()
	}

	w.Header().Set("WWW-Authenticate", `Basic realm="VictoriaMetrics"`)
	http.Error(w, "", http.StatusUnauthorized)
	return false
```

**More info on timing-attacks**: https://en.wikipedia.org/wiki/Timing_attack

Please do share your thoughts on this.

### To Reproduce

nil

### Version

Latest build from source

### Additional information

**I would like to open a PR for this if it's is accepted by the community**

**Comment by Haleygo** [comment]
@zekker6 @f41gh7 @hagen1778  Could you share some thoughts here?

**Comment by zekker6** [comment]
From the security POV this seems to be a very good suggestion, thanks @wasim-nihal!
It would be important to make sure that all credentials comparison functions will be converted to constant time comparison.

**Comment by hagen1778** [comment]
I like this proposal as well!

**Comment by wasim-nihal** [comment]
Thanks, @zekker6 , @hagen1778 for accepting the proposal!! 

> It would be important to make sure that all credentials comparison functions will be converted to constant time comparison.

As of now, I have taken note of only authkey and basic auth credential comparison. I will explore the codebase a bit more and see where such similar comparisons are made and open the PRs (maybe in stages). Any heads-up would be helpful 🚀

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6423 was merged and will be available in the next release.

**Comment by valyala** [comment]
FYI, I reverted the commit 9b7e532172eea7ea516bd0323fa73db5d473876d in  82d639411d9b236eb3cbeed8d4e87854b94e3e9a . See commit description for the reasons of the revert.

**Comment by valyala** [comment]
Additional notes regarding this issue additionally to comments at https://github.com/VictoriaMetrics/VictoriaMetrics/commit/82d639411d9b236eb3cbeed8d4e87854b94e3e9a : it is expected that all the VictoriaMetrics components run in protected private networks. The only component, which can be exposed to the public Internet is [vmauth](https://docs.victoriametrics.com/vmauth.html). If we are going to fix real security issues (if they really exist), then they must be fixed at [vmauth](https://docs.victoriametrics.com/vmauth.html) at first.
