### ISSUE TITLE
VictoriaLogs: query api just return raw logs

### ISSUE THREAD

**Issue by dw130** [VictoriaMetrics/VictoriaMetrics#6400]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

hi,is there way to use curl http://localhost:9428/select/logsql/query -d 'query=error'
just return the raw logs?

I find fields pipe returns json in lines
Is there way to return the raw logs in every lines?

Thanks 

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Haleygo** [comment]
Hi,
do you need export api or returning raw logs using query api?
