### ISSUE TITLE
VictoriaLogsUI: Add Bar Chart

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6404]
### Describe the solution you'd like

Please add a bar chart with 20 items after the query execution 
You can choose time range on it by selecting the area
barchart should provide information about the amount of log entries - see https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6461 has been merged and will be included into the next release.

**Comment by valyala** [comment]
Bar chart is available in VictoriaLogs starting from [v0.21.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.21.0-victorialogs). Closing the feature request as done.
