### ISSUE TITLE
VictoriaLogs UI: show the log entries for the last 5m be defualt

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6405]
### Describe the solution you'd like

Show the logs for the lastest 5 minutes by default when user opens the UI

**Comment by valyala** [comment]
[Web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) shows entries for the last 5 minutes by default starting from [v0.18.0-victorialogs release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.18.0-victorialogs).
