### ISSUE TITLE
VictoriaLogs UI: Group by tab - show only stream in header

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6406]
### Describe the solution you'd like

Need to show only streams in headers all other fields, please move to the body 
If no stream fields don't use grouping

**Comment by valyala** [comment]
This feature has been implemented in [v0.18.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.18.0-victorialogs).
