### ISSUE TITLE
VictoriaLogs UI: show all fields in log message

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6407]
### Describe the solution you'd like

Show all fields after the message (please keep in mind that the message can contain many fields, 10-100)

**Comment by valyala** [comment]
[VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) shows all the log fields by default starting from [v0.18.0-victorialogs release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.18.0-victorialogs).
