### ISSUE TITLE
VictoriaLogs UI: set the default log entries limit to 50 (current 1000)

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6408]
### Describe the solution you'd like

Switch the default limit to 50

**Comment by valyala** [comment]
[Web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) has the limit of 50 entries starting from [v0.18.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.18.0-victorialogs).
