### ISSUE TITLE
vmstorage: high memory used after expanding disk size

### ISSUE THREAD

**Issue by tripitakav** [VictoriaMetrics/VictoriaMetrics#6411]
### Is your question request related to a specific component?

vmstorage oom killed

### Describe the question in detail

We expand the storage disk,vmstorage memory used more than 40% vs before. Due to the OOM, we start a new Victoriaemetrics clusters and suspended the old cluster ingestion data . There is old cluster monitor dashboard，can you help me investigate the cause of high memory?

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73687556/4cb9625c-8960-4099-83fa-1dcc1d3061e3)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73687556/c35d21a2-25ed-40e5-abd0-14002ef927a9)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73687556/cca3e4a9-5ee5-4005-aa10-c7031d0059fb)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @tripitakav 
This is usually a caused by vmstorage starting background merges. Before the disk expansion vmstorage could postpone merges as there was not enough free disk space to perform a merge. After the disk resize vmstorage detected that there is enough disk space to perform background merge and started merging the data.
You can confirm if that's the case by checking "Active merges" and "Merge" speed panels. If that is the case you will see than number of merges and their speed was lower before the disk resize.

**Comment by tripitakav** [comment]
@zekker6
Yes, there is indeed a backend merge. Name is indexdb/file.
So is there any way to reduce memory usage？
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/73687556/5308079e-47b9-4259-8288-3f19fd62c3ec)

**Comment by zekker6** [comment]
@tripitakav Usually, 3-5Mil merge speed should not use that much memory. Could you gather memory profile from the storage nodes as per [this instruction](https://docs.victoriametrics.com/cluster-victoriametrics/#profiling) and share the profiles here?

**Comment by hagen1778** [comment]
@tripitakav could you please share screenshots of the Troubleshooting and Interconnection section of the Grafana dashboard?

Btw, I see you have a plenty of restart annotations on the screenshots. Why it is so?

**Comment by tripitakav** [comment]
@zekker6 @hagen1778 
Sorry, I took a leave last week and the old cluster has been deleted by my colleagues, so I cannot see any information. I will temporarily close this issue for now
