### ISSUE TITLE
Discrepancy with Prometheus in query_range result with step param

### ISSUE THREAD

**Issue by sweatybridge** [VictoriaMetrics/VictoriaMetrics#642]
**Describe the bug**
When there are "gaps" in time series data points (scraping failed or sample label doesn't exist), query_range with `step` param on Prometheus returns results with missing range filled with NaNs. For example, with step=181, Prometheus returns

```json
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[
  [1594281790,"NaN"],[1594281971,"NaN"],[1594282152,"NaN"],[1594282333,"NaN"],
  [1594282514,"NaN"],[1594282695,"NaN"],[1594282876,"NaN"],[1594283057,"NaN"],
  [1594283238,"0.013750015624934896"],[1594283419,"0.0060641560696879735"]
]}]}}
```

The same query, when ran against VM, removes all NaNs to return results with inconsistent step interval.
```json
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[
  [1594265738,"0.0075"],[1594269177,"0.0075"],[1594271530,"0.0075"],[1594271892,"0.0075"],[1594283295,"0.01375"]
]}]}}
```

**To Reproduce**
Difficult to reproduce because Prometheus doesn't support import.

**Expected behavior**
VM query response should be consistent with Prometheus response according to documentation https://victoriametrics.github.io/MetricsQL.html.

**Comment by valyala** [comment]
VictoriaMetrics treats NaNs in the same way as missing values. So it removes them from the output of `/api/v1/query_range`. Previously VictoriaMetrics was returning missing values from `/api/v1/query_range` as NaNs, but this wasn't consistent with Prometheus behavior - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/153 for details.

@sweatybridge , could you give more details on your use case where NaN values are required in `/api/v1/query_range` response?

**Comment by sweatybridge** [comment]
Thank you for referencing the related ticket. I just checked my query again and it appears that the inconsistency applies specifically to `histogram_quantile` function. As documented in Prometheus,

> If b has 0 observations, NaN is returned. If b contains fewer than two buckets, NaN is returned. For φ < 0, -Inf is returned. For φ > 1, +Inf is returned.

https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile

Here's the PromQL I ran:
```bash
curl 'http://localhost:9091/api/v1/query_range?query=histogram_quantile(0.5%2C%20sum(increase(traefik_backend_request_duration_seconds_bucket%7Bbackend%3D%22snowy-queen-1285.playground.bdrk.ai%22%7D%5B2m%5D))%20by%20(backend%2C%20le))&start=1594878300&end=1594899900&step=181&_=1595425827966'
```

And the response json containing nans:
```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"backend":"snowy-queen-1285.playground.bdrk.ai"},"values":[[1594881558,"0.0058771641684665895"],[1594881739,"0.00451570499515705"],[1594881920,"NaN"],[1594882101,"NaN"],[1594882282,"NaN"],[1594882463,"NaN"],[1594882644,"NaN"],[1594882825,"NaN"],[1594883006,"NaN"],[1594883187,"NaN"],[1594883368,"NaN"],[1594883549,"NaN"],[1594883730,"NaN"],[1594883911,"NaN"],[1594884092,"NaN"],[1594884273,"NaN"],[1594884454,"NaN"],[1594884635,"NaN"],[1594884816,"NaN"],[1594884997,"NaN"],[1594885178,"NaN"],[1594885359,"NaN"],[1594885540,"NaN"],[1594885721,"NaN"],[1594885902,"NaN"],[1594886083,"NaN"],[1594886264,"NaN"],[1594886445,"NaN"],[1594886626,"NaN"],[1594886807,"0.004637651546110884"],[1594886988,"0.004885422615648201"],[1594887169,"NaN"],[1594887350,"NaN"],[1594887531,"NaN"],[1594887712,"NaN"],[1594887893,"NaN"],[1594888074,"NaN"],[1594888255,"NaN"],[1594888436,"NaN"],[1594888617,"NaN"],[1594888798,"NaN"],[1594888979,"NaN"],[1594889160,"0.006087792127921279"],[1594889341,"0.0060497329773030704"],[1594890065,"0.00483215405644448"],[1594890246,"0.0049226367104705385"],[1594890427,"NaN"],[1594890608,"NaN"],[1594890789,"NaN"],[1594890970,"NaN"],[1594891151,"NaN"],[1594891332,"NaN"],[1594891513,"NaN"],[1594891694,"NaN"],[1594891875,"NaN"],[1594892056,"NaN"],[1594892237,"NaN"],[1594892418,"NaN"],[1594892599,"NaN"],[1594892780,"NaN"],[1594892961,"NaN"],[1594893142,"NaN"],[1594893323,"NaN"],[1594893504,"NaN"],[1594893685,"NaN"],[1594893866,"NaN"],[1594894047,"NaN"],[1594894228,"NaN"],[1594894409,"NaN"],[1594894590,"NaN"],[1594894771,"NaN"],[1594894952,"NaN"],[1594895133,"NaN"],[1594895314,"NaN"],[1594895495,"NaN"],[1594895676,"NaN"],[1594895857,"NaN"],[1594896038,"NaN"],[1594896219,"NaN"],[1594896400,"NaN"],[1594896581,"NaN"],[1594896762,"NaN"],[1594896943,"NaN"],[1594897124,"NaN"],[1594897305,"NaN"],[1594897486,"NaN"],[1594897667,"NaN"],[1594897848,"NaN"],[1594898029,"NaN"],[1594898210,"NaN"]]}]}}
```

If I query the metric directly without applying `histogram_quantile`, nans are indeed removed from the response.

**Comment by sweatybridge** [comment]
Regarding our use case, we are plotting time series graphs of p50 latency and the frontend tries to connect neighbouring points to fill up any gaps. I don't think it's a hard requirement to have NaNs returned in `/api/v1/query_range` as we can update the frontend code to show gaps instead. We were just a little surprised that some graphs went from bumpy to flat line after switching to VM.

<img width="608" alt="Screenshot 2020-07-09 at 4 49 42 PM" src="https://user-images.githubusercontent.com/1639722/88191247-cfeae200-cc6d-11ea-8bae-fa3c127efe3f.png">

**Comment by valyala** [comment]
VictoriaMetrics isn't going to return `NaN` values, since many users rely on the behavior that [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) never returns `NaN` values.

Closing this issue then as won't resolve.
