### ISSUE TITLE
vmui: `copy row` button in Table view produces unexpected result

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6421]
### Describe the bug

Value copied from the table view in vmui isn't what it is expected to be.

### To Reproduce

Go to [playground](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.expr=100+-+%28avg+by+%28instance%29+%28rate%28node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B1m%5D%29%29+*+100%29&g0.range_input=30m&g0.end_input=2024-06-05T10%3A54%3A48&g0.tab=1&g0.relative_time=last_30_minutes) and press on `Copy row` button next to one of the rows in response:
<img width="1338" alt="image" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2902918/855bb44b-3998-4f2b-b27f-c571a57adf51">

The value copied to the buffer will be the following:
> undefined {"instance":"10.142.0.85:9100"}

^ The copied value contains unexpected `undefined` word (metric name, I suppose) and doesn't have value.

### Version

:latest

**Comment by valyala** [comment]
FYI, this bug must be fixed in [v1.102.0-rc2 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
