### ISSUE TITLE
indexdb data not being deleted in vmstorage pods

### ISSUE THREAD

**Issue by surekha3** [VictoriaMetrics/VictoriaMetrics#6426]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

We've deployed victoriametrics cluster into AWS EKS. For vmstorage pod, we have set -retentionPeriod: 3. It's working fine with /data folder where data before 3 months is properly cleaning up but in /indexdb folder, old data is not cleaning up. Due to this disk space is consuming too much. Please help with this request. Attaching folder structure of /indexdb in pod
<img width="767" alt="indexdb" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/49813610/330b3ab7-3add-49b5-a9fd-342199f530e2">

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @surekha3 
Was `retentionPeriod` set to 3 initially or this was changed after the initial deployment?

**Comment by surekha3** [comment]
Hi @zekker6 ,

Initially it was set to 183 as we thought default is in days. But later we realized if we wont specify anything, it's in months. So just few days back, I changed it to 3. Then immediately old data in /data folder got removed. But not in /indexdb as shown in screenshot attached

**Comment by zekker6** [comment]
@surekha3 IndexDB is rotated once per retention period, unlike the data folder which is constantly running background merges which can remove previous partitions. The only way to force shrink the index size is to migrate the data in a new cluster with `retentionPeriod=3` so that unnecessary index entries will be removed in a new cluster.

**Comment by surekha3** [comment]
Hi @zekker6, It's not possible for us to have new cluster. So you mean as it set to 3 months now, after 3 months, old folders of indexdb gets deleted? Please clarify

**Comment by zekker6** [comment]
> So you mean as it set to 3 months now, after 3 months, old folders of indexdb gets deleted?
@surekha3 Yes, that is correct.

**Comment by surekha3** [comment]
Okay understood. Thankyou so much @zekker6 for the quick help

**Comment by zekker6** [comment]
Closing as answered.
