### ISSUE TITLE
How to config the Prometheus can achieve read the data from the Victoria metrics?

### ISSUE THREAD

**Issue by Sleepatnoon** [VictoriaMetrics/VictoriaMetrics#6431]
### Is your question request related to a specific component?

Victoria metrics, Prometheus

### Describe the question in detail

I set the Prometheus store the latest 1 month data, and strore the last six monthes data into the Victoria metrics. 
I want to know can I use any configuration to let the Prometheus query data from the Victoria metrics? 
Because sometimes I need  to use the Prometheus to see the last six monthes data and make alert.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @Sleepatnoon 
prometheus has [federation](https://prometheus.io/docs/prometheus/latest/federation/) to scrape data from other prometheus compatible endpoints. VM has federation endpoint [available](https://docs.victoriametrics.com/url-examples/?highlight=federation#federate) in both single and cluster modes. Alerting can be configured in VM as well

**Comment by jiekun** [comment]
Close as answered.
