### ISSUE TITLE
Alerting rule `RecordingRulesNoData`'s annotations use missing `recording` label

### ISSUE THREAD

**Issue by evevseev** [VictoriaMetrics/VictoriaMetrics#6439]
### Describe the bug

`RecordingRulesNoData` of `vmalert` group uses `recording` label in summary and description which is thrown away by `without(recording, id)` in expr.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/a9448f372b140fea3873199e1c2dc860384d66be/deployment/docker/alerts-vmalert.yml#L42-L52

### To Reproduce

Have a look :)

### Version

NA

### Additional information

Found using pint

**Comment by hagen1778** [comment]
Thanks @evevseev @AndrewChubatiuk for fixing this!
