### ISSUE TITLE
vmauth: a way to stop proxying Host header

### ISSUE THREAD

**Issue by ptimofee** [VictoriaMetrics/VictoriaMetrics#6453]
### Is your feature request related to a problem? Please describe

I tried to put VM stack into istio.
Istio is a service mesh that's intended for HTTP traffic mostly. It relies on `Host` header in HTTP requests to figure out what traffic policy/routing/etc to apply.

As of v1.101.0 version vmauth proxies `Host` header received from downstream to upstream services as-is.
This breaks istio because `Host` header vmauth sends to upstream is not upstream fqdn/dns name, but downstream entrypoint fqdn instead.

### Describe the solution you'd like

There are configuration options for deleting and adding headers on vmauth side. But `Host` header is a special case. Looking at the vmauth code I see that this header is protected when proxying request to upstream.
The only case when it's changed is TLS usage.

It would be nice to have a command line option, for example, that would tell vmauth to stop proxying `Host` header and use the upstream fqdn in this header instead.

### Describe alternatives you've considered

The only thing that worked for me was to tell istio to handle the traffic from vmauth to upstream svc as plain tcp (i. e. not http, so 90% of istio features become unavailable):
- create a separate k8s svc for upstream svc that has `tcp` word in ports name (or with appProtocol set to tcp)
- reconfigure vmauth to use this new svc as upstream

### Additional information

Istio is just an example. I believe other service mesh may be affected as well.
Other thing that comes to my mind is Autopilot service available in Google Cloud Platform (GCP).
I've never used it to be honest, but as far as I know they use istio under the hood.

**Comment by Amper** [comment]
Hey, @ptimofee.
See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4825) and [this doc](https://docs.victoriametrics.com/vmauth/#modifying-http-headers).
Since [v1.94.0](https://docs.victoriametrics.com/changelog_2023/#v1940) you can remove, set or add any header with vmauth config.

**Comment by AndrewChubatiuk** [comment]
hey @ptimofee
vmauth has`response_headers` section in auth config, if header's value is empty, it will not be included into response
https://docs.victoriametrics.com/vmauth/#auth-config

**Comment by ptimofee** [comment]
Response has nothing to do here, request does

**Comment by AndrewChubatiuk** [comment]
Reopening as it's not released yet

**Comment by valyala** [comment]
@ptimofee , please read [these docs](https://docs.victoriametrics.com/vmauth/#modifying-http-headers) on how to use backend host header in requests to backend (just specify an empty `Host` header there). This functionality will be available in the next release. In the mean time you can build `vmauth` from the commit e666d64f1de7f018ac84499bbbe435bba39ac27b according to [these docs](https://docs.victoriametrics.com/vmauth/#how-to-build-from-sources) and verify whether this works as intended.

**Comment by hagen1778** [comment]
[vmauth](https://docs.victoriametrics.com/vmauth/) allows overriding `Host` header with backend host before sending the request to the configured backend starting from [v1.102.0](https://docs.victoriametrics.com/changelog/#v11020).

**Comment by ptimofee** [comment]
Thank you!
I can confirm it works as expected and I don't have any problems with running vmstack under istio anymore!
