### ISSUE TITLE
large queries cause vmselect occupy lots of memory usage

### ISSUE THREAD

**Issue by dxtrzhang** [VictoriaMetrics/VictoriaMetrics#646]
**Describe the bug**
a large query(contains lots of metrics data) causes vmselect memory climbing rapidly, and recover very slowly even if the high memory usage causes OOM.

**To Reproduce**
big queries with large amount of metric data(may be with too many different labels in one metric)

**Version**
vmselect-20200714-150152-tags-v1.38.1-cluster-0-gc2b4b9138

**Additional context**
before the instance OOM, I fortunately got a peak at the pprof top heap of the instance, it shown `WriteBlock(mb *storage.MetricBlock)` use the top of the memory:
![image](https://user-images.githubusercontent.com/13900390/88128290-376e4680-cc08-11ea-97a6-a4b79909870b.png)
[pprof.vmselect-prod.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4957552/pprof.vmselect-prod.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

and some other instances gets the same situation, so I get the metric data exposed by another vmselect instance, large amount of memory was occupied by `go_memstats_heap_idle_bytes` and few was released or in use, eg:
```
go_memstats_heap_idle_bytes 76784279552                   (71.51G)
go_memstats_heap_inuse_bytes 1390010368                   (1.29G)
go_memstats_heap_released_bytes 19746603008               (18.39G)
```
all exported metrics data from vmselect and the associated heap pprof file: 
[metrics.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4958213/metrics.txt)
[pprof.vmselect-prod.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4957565/pprof.vmselect-prod.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz)

I guess this may caused by `sync.Pool` in `WriteBLock`, When larger amount of data comes in, pool alloc large amount of memories, all cached in memory, and takes a long time to recover.
```go
func (tbfw *tmpBlocksFileWrapper) WriteBlock(mb *storage.MetricBlock) error {
	bb := tmpBufPool.Get()
	bb.B = storage.MarshalBlock(bb.B[:0], &mb.Block)
	tbfw.mu.Lock()
	addr, err := tbfw.tbf.WriteBlockData(bb.B)
	tmpBufPool.Put(bb)
	if err == nil {
		metricName := mb.MetricName
		addrs := tbfw.m[string(metricName)]
		if len(addrs) == 0 {
			tbfw.orderedMetricNames = append(tbfw.orderedMetricNames, string(metricName))
		}
		tbfw.m[string(metricName)] = append(addrs, addr)
	}
	tbfw.mu.Unlock()
	return err
}
```

**Comment by dxtrzhang** [comment]
all exported metrics data from vmselect: 
[metrics.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/4957492/metrics.txt)
[pprof heap svg file](https://imgbed-dex.oss-cn-hangzhou.aliyuncs.com/profile001.svg)

**Comment by valyala** [comment]
@dxtrzhang , thanks for the provided memory profile and for the analysis.

The profile shows that the majority of memory is allocated at `tbfw.m[string(metricName)] = append(addrs, addr)` line (run `go tool pprof` with `--alloc_space` command-line flag):

```
(pprof) list tmpBlocksFileWrapper..WriteBlock
Total: 6.62TB
ROUTINE ======================== github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage.(*tmpBlocksFileWrapper).WriteBlock in github.com/VictoriaMetrics/VictoriaMetrics/app/vmselect/netstorage/netstorage.go
    2.71TB     2.72TB (flat, cum) 41.07% of Total
         .          .    836:	m                  map[string][]tmpBlockAddr
         .          .    837:	orderedMetricNames []string
         .          .    838:}
         .          .    839:
         .          .    840:func (tbfw *tmpBlocksFileWrapper) WriteBlock(mb *storage.MetricBlock) error {
         .    50.33MB    841:	bb := tmpBufPool.Get()
         .     8.07GB    842:	bb.B = storage.MarshalBlock(bb.B[:0], &mb.Block)
         .    83.01MB    843:	tbfw.mu.Lock()
         .     2.50MB    844:	addr, err := tbfw.tbf.WriteBlockData(bb.B)
         .   429.75MB    845:	tmpBufPool.Put(bb)
         .          .    846:	if err == nil {
         .          .    847:		metricName := mb.MetricName
         .          .    848:		addrs := tbfw.m[string(metricName)]
         .          .    849:		if len(addrs) == 0 {
  739.11GB   739.11GB    850:			tbfw.orderedMetricNames = append(tbfw.orderedMetricNames, string(metricName))
         .          .    851:		}
    1.99TB     1.99TB    852:		tbfw.m[string(metricName)] = append(addrs, addr)
         .          .    853:	}
         .          .    854:	tbfw.mu.Unlock()
         .          .    855:	return err
         .          .    856:}
         .          .    857:
```

This may be the case when the query selects big number of distinct time series with long names and/or labels. I have no idea how to reduce memory usage for `tbfw.m` in this case :(

**Comment by valyala** [comment]
It is possible to track the estimated memory usage for `tbfw.m` and `tbfw.orderedMetricNames` and abort queries which would require too big amounts of memory.

**Comment by dxtrzhang** [comment]
> This may be the case when the query selects big number of distinct time series with long names and/or labels (they are encoded in `metricName`).
Exactly! But the question here is:
1. Why after the big query completed, the memory usage still kept the way it was and recovered very slowly(maybe other big queries came in and caused the OOM)
2. Why the memory stuck in idle stat(I check the idle bytes, inuse bytes and released bytes, large memories stuck in idle stat for a long time)

**Comment by valyala** [comment]
> Why after the big query completed, the memory usage still kept the way it was and recovered very slowly(maybe other big queries came in and caused the OOM)
> Why the memory stuck in idle stat(I check the idle bytes, inuse bytes and released bytes, large memories stuck in idle stat for a long time)

I think this is how Go garbage collector works. Try setting lower value for [GOGC environment variable](https://dave.cheney.net/tag/gogc) - probably this will trigger quicker memory releases in Go runtime. By default GOGC equals to 100, which means that Go may hold up to 2x of actually used memory. Try reducing it to 50 or something like that.

BTW, I figured out how to reduce memory usage for the case above. Try VictoriaMetrics from the following commits:
* Single-node version - 34563916f7d0c1670f82a7e233897339e09d8e41
* Cluster version - 7aa5b485086e76d5faccd365eff10b374f12020e

**Comment by valyala** [comment]
oops, these commits contained a typo, which prevented from memory usage optimization. It has been fixed in the following commits:

* Single-node version: e79de9774b6da46985fc1cf3a2f06cfecca3ba9b
* Cluster version: 55ed07add16297a78264f59617bf92588e78696e

**Comment by valyala** [comment]
@dxtrzhang , the release [v1.39.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) includes memory usage improvements referenced above.  Could you compare memory usage for `v1.39.0` release vs `v1.38.1` release for your workload?

**Comment by dxtrzhang** [comment]
It seems like the new release v1.39.0 change the communication protocol between vmselect and vmstorage and not mentioned in the change log. Could you please add this change to change log since it causes all the select rejected by vmstorage.
Thanks~

**Comment by valyala** [comment]
Added the following text to release notes for [v1.39.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.39.0):

> this change modifies communication protocol between vmselect and vmstorage in cluster version of VictoriaMetrics in incompatible way. This is needed for propagating the deadline from vmselect to vmstorage. So vmselect prior v1.39.0 cannot talk to vmstorage v1.39.0 and higher. The same applies for vmselect v1.39.0 or higher and vmstorage prior to v1.39.0 - they also cannot communicate with each other. So all the vmselect and vmstorage nodes must be updated to v1.39.0 or higher in order to work properly.

**Comment by dxtrzhang** [comment]
Thanks for the additional upgrade info @valyala 

As for the high memory RSS, Go use `MADV_FREE` on Linux since v1.11, see [runtime: use MADV_FREE on linux as well](https://github.com/golang/go/issues/23687) and [madvise(2)](https://man7.org/linux/man-pages/man2/madvise.2.html).
>  The application no longer requires the pages. The kernel can thus free these pages, but the freeing could be delayed until memory pressure occurs.

`MADV_FREE` frees the  pages until memory pressure occurs, and our machine open the swap, some how the system may confuse about the "memory pressure", the pages occupied by vmselect can't be released properly and caused the OOM problem. After we turn off the swap, everything seems to be normal again.
