### ISSUE TITLE
GetRowsDiff func takes a lot of time when vmagent pushes kube-state-metrics data

### ISSUE THREAD

**Issue by MajLuu** [VictoriaMetrics/VictoriaMetrics#6479]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

In our cluster, we use the vmagent component to scrape the metrics of the kube-state-metrics component every 30 seconds, with a data volume of about 600MB each time. At the same time, the vmagent component also scrapes a large number of other non-stream mode metrics. We found that it takes about 1 minute to scrape and push the metrics of kube-state-metrics component on a machine with a CentOS7 operating system, 64-core CPU, and 256GB memory. We did some logs in the codes and found that the GetRowsDiff function takes about 50 seconds when we scrape and push metrics of kube-state-metrics, but it is normal with other non-stream mode metrics.  How should we deal with this situation?

ps: We have tried to deploy only vmagent on a single machine, and the vmagent only scrape the metrics of the kube-state-metrics component. At this time, it takes about 20 seconds each time, which matches our expectations.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
have you tried VMAgent in a cluster mode to spread the scrape jobs out over multiple instances of VMAgent?

There are instructions in the [docs for running in cluster mode](https://docs.victoriametrics.com/operator/resources/vmagent/#high-availability) on k8s and a [blog post](https://victoriametrics.com/blog/vmagent-high-availability-examples/) explaining how cluster mode works.

**Comment by f41gh7** [comment]
600MB is really huge metrics response. And It'll take a lot of time to process it. 

I can suggest to disable staleMarkers detection `no_stale_markers: true`  for this job (or for all jobs with flag -promscrape.noStaleMarkers").
job config example:

```yaml
scrape_configs:
- job_name: kube-state-metrics
  no_stale_markers: true
  # make sure that series limit is not set or has default 0 value
  series_limit: 0
  static_configs:
  - targets: ["kube-state-url:1234"]
```

 It must skip GetRowsDiff function execution.

**Comment by MajLuu** [comment]
> 600MB is really huge metrics response. And It'll take a lot of time to process it.
> 
> I can suggest to disable staleMarkers detection `no_stale_markers: true` for this job (or for all jobs with flag -promscrape.noStaleMarkers"). job config example:
> 
> ```yaml
> scrape_configs:
> - job_name: kube-state-metrics
>   no_stale_markers: true
>   # make sure that series limit is not set or has default 0 value
>   series_limit: 0
>   static_configs:
>   - targets: ["kube-state-url:1234"]
> ```
> 
> It must skip GetRowsDiff function execution.

Good idea, but I want to know if there are other problems? And although setting `no_stale_markers: true`,  I consider it also run  GetRowsDiff func once [ref](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/eea361defb50eec7590389ea6131449fb6888130/lib/promscrape/scrapework.go#L578).  If we could optimize the GetRowsDiff func? Or we shard kube-state-metrics component.
Thanks for replies.
