### ISSUE TITLE
Allow VMAlert to replay alerts till the current time

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#6492]
### Is your feature request related to a problem? Please describe

I was replaying recording rules to import data and wanted the data to replay till the current time but had to use type out the time myself which would be tedious if I had numerous rule files.

### Describe the solution you'd like

* not specifying replay.rtimeTo will replay rules till the current time
* having an alias like now that would substitute the current time automatically for the user

### Describe alternatives you've considered

using command substitution to place in the current timestamp

**Comment by hagen1778** [comment]
@Haleygo wdyt?

**Comment by Haleygo** [comment]
> @Haleygo wdyt?

I think we can have the default `replay.timeTo` as time.Now().
And add option like `replayFor: 30d`(replay for last 30days) like proposed [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6328).

**Comment by valyala** [comment]
The `-replay.timeTo` command-line flag is optional starting from [vmalert v1.102.0](https://docs.victoriametrics.com/changelog/). Closing the feature request as completed.
