### ISSUE TITLE
IndexDB data consuming more space after pod restarts

### ISSUE THREAD

**Issue by surekha3** [VictoriaMetrics/VictoriaMetrics#6496]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

We have deployed victoriametrics as cluster into AWS EKS. For vmstorage pods, we have created persistent volumes as ebs storage for storing the data. Recently these ebs volumes disk utilization reached 100% so we cleaned the old data manually and did pod restarts. From that time, indexdb data is increasing. I'm suspecting it might be due to new time series data getting added up. Will it reduce over time?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @surekha3 
> I'm suspecting it might be due to new time series data getting added up. 

This is correct. IndexDB holds a mapping between time series and location of the data on disk. If IndexDB size grows it can only mean that there are new entries appearing in IndexDB.

> Will it reduce over time?

IndexDB is rotated once per retention period. During rotation entries which are no longer needed are removed so disk space is reclaimed.

**Comment by surekha3** [comment]
okay thankyou. Means under /indexdb folder, will it delete all the old folders and files with old timestamps following retention period

**Comment by zekker6** [comment]
@surekha3 

> Means under /indexdb folder, will it delete all the old folders and files with old timestamps following retention period

Yes, it will remove old files and copy entries which are still relevant to current version of IndexDB into a new instance of IndexDB.

**Comment by zekker6** [comment]
Closing as answered.
