### ISSUE TITLE
victorialogs vmui: unresponsive after query execution

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#6510]
### Describe the bug

Looks like VMUI crashes after executing a query with `stats` pipe.
![1718793431](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/1367798/24ea22b6-bc2a-4fc7-9179-74b0e13e4930)

### To Reproduce

1. Go to https://play-vmlogs.victoriametrics.com/select/vmui/
2. Increase time range to 12h and use the following query: `* | stats by (channel_id) count()`

### Version

victoria-logs-20240617-222505-tags-v0.20.2-victorialogs-0-g3eda4617c0

**Comment by Loori-R** [comment]
Should be fixed in fd809eb601c3da45ab19d9bdee48b6070e06729b, and the fix is included from [v0.21.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.21.0-victorialogs).
Close as completed, feel free to reopen if there is still problem.
