### ISSUE TITLE
Random inconsistent results in query operations from the same instance and exporter

### ISSUE THREAD

**Issue by fmadrids** [VictoriaMetrics/VictoriaMetrics#6511]
### Describe the bug

Every now and then some metrics coming from the same exporter shows updated values while others don't. This results in inconsistent queries and recording rules.

To illustrate the issue, we are trying to calculate how much delay is there between a redis slave and it's master. We calculate it substracting both offsets and in the best case scenario both should be equal so that the slave is up to date. Both values come from the same exporter in the same server, so I would expect both to be scraped exactly at the same time as they both come from the same request to the exporter endpoint. The query we run is:

```
(sum(redis_master_repl_offset) by (cluster, instance)
-
sum(redis_slave_repl_offset) by (cluster, instance)) != 0
```

But, every now and then this query reports lag (even a negative one, meaning that the slave has overtaken the master!), and investigating I've seen in the VMUI that one of them reports an additional metric. In other words, even though both have been scraped at the same time, one offset shows an updated metric while the other still shows the previous one (see attached screenshot). Therefore, the query results in inexistent lag.

To do this I ran these three queries at the same time in the VMUI:
```
(sum(redis_master_repl_offset) by (cluster, instance)
-
sum(redis_slave_repl_offset) by (cluster, instance)) != 0
```
```
redis_master_repl_offset[5m]
```
```
redis_slave_repl_offset[5m]
```

I've uploaded a screenshot of the result of these queries when it happened a little ago.

If we rerun the same query just a second afterwards everything comes again to normal and lag resets again to zero, but it has happened that an alert has triggered because the slave is apparently lagging behind the master.

### To Reproduce

Not been able to reproduce, happens randomly.

### Version

"victoria-metrics-k8s-stack" helm chart version 0.23.1

### Screenshots

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15650406/61152217-76e7-47a2-bf91-81a65f701b42)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15650406/83f87585-ba75-4187-8645-3970a87e8263)

**Comment by Haleygo** [comment]
Hello!
>Both values come from the same exporter in the same server, so I would expect both to be scraped exactly at the same time as they both come from the same request to the exporter endpoint. 

Yes, both of the metrics should be scraped at the same time with same timestamp, but it can't ensure both of them becoming queryable at the same time, since each series is stored separately and might be flushed to searchable parts with few seconds delay, check [this doc](https://docs.victoriametrics.com/keyconcepts/#query-latency) for more details.
I believe that's why there are occasionally one more samples when you query `redis_master_repl_offset[5m]`.
And to eliminate the false-positive alerts, try add some [offset](https://docs.victoriametrics.com/metricsql/#metricsql-features) to the expr like 
```
(sum(redis_master_repl_offset offset 5s) by (cluster, instance)
-
sum(redis_slave_repl_offset offset 5s) by (cluster, instance)) != 0
```

You can also check their real-time ingestion latency by querying `lag(redis_master_repl_offset[1m])`.

**Comment by fmadrids** [comment]
Hi @Haleygo , thanks for your answer!

I've just checked that the lag reported by one of the metrics is slightly higher than the other and perhaps, just as you said, from time to time the query evaluation coincides with the lag in the metrics deriving in these weird results.

I'll try adding a small offset as you suggested. Thanks again!

**Comment by fmadrids** [comment]
Hi @Haleygo ,

I just read the link you posted and there's something that is not clear for me. According [to documentation](https://docs.victoriametrics.com/keyconcepts/#query-latency), by default the `search.latencyOffset` is set to 30 seconds. If I have understood correctly, then only metrics scraped prior to 30 seconds are to be evaluated.

Does this mean that 30 seconds aren't enough for flushing the metrics and making them searchable? Should we then increase the `search.latencyOffset` and the `rule.evalDelay`?

**Comment by Haleygo** [comment]
>According [to documentation](https://docs.victoriametrics.com/keyconcepts/#query-latency), by default the search.latencyOffset is set to 30 seconds. If I have understood correctly, then only metrics scraped prior to 30 seconds are to be evaluated.

That's right. But not for query like `redis_master_repl_offset[5m]`, it returns all the latest samples.
>Does this mean that 30 seconds aren't enough for flushing the metrics and making them searchable?

What's the maximum value you can see for `lag(redis_master_repl_offset[1m])` or `lag(redis_slave_repl_offset[1m])`?

**Comment by fmadrids** [comment]
> What's the maximum value you can see for `lag(redis_master_repl_offset[1m])` or `lag(redis_slave_repl_offset[1m])`?

It's 44.xx secs for both, which fits in our `scrapeInterval` (which is 45 secs).

**Comment by Haleygo** [comment]
>It's 44.xx secs for both, which fits in our scrapeInterval (which is 45 secs).

That's good number, indicates no big delay on ingestion, so there is no need to`search.latencyOffset`.
Do all the `redis_master_repl_offset` and `redis_slave_repl_offset` samples come from a single exporter instance?
Could you add `now()` and `lag()` to query list in VMUI and share results when issue happens? Want to understand the delay for missing point in `redis_master_repl_offset` at that moment.
```
(sum(redis_master_repl_offset) by (cluster, instance)
-
sum(redis_slave_repl_offset) by (cluster, instance)) != 0

redis_master_repl_offset[5m]

redis_slave_repl_offset[5m]

now()

lag(redis_master_repl_offset[1m])
```

**Comment by fmadrids** [comment]
Yes, every pair of master/slave metrics come from the same exporter as it's the slave that reports the offset metrics.

I'm not able to run 5 concurrent queries in VMUI, just four, so I've run the following:
```
(sum(redis_master_repl_offset) by (cluster, instance)
-
sum(redis_slave_repl_offset) by (cluster, instance)) != 0

lag(redis_master_repl_offset[1m])

redis_master_repl_offset[5m]

redis_slave_repl_offset[5m]
```

I'll now try to run the `now()` query instead of the `lag(...)` one.

Two samples are:

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15650406/80600058-4ec7-4df8-96a0-b71dce311b18)

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15650406/f61e87fe-77e1-46be-b87f-ded05298ae86)

**Comment by fmadrids** [comment]
Here's a sample with the `now()` query.

<img width="381" alt="Captura de pantalla 2024-06-27 a las 9 32 00" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15650406/73d3fd6b-129b-411e-8314-c300c67b6ec3">

<img width="393" alt="Captura de pantalla 2024-06-27 a las 9 32 39" src="https://github.com/VictoriaMetrics/VictoriaMetrics/assets/15650406/fcc34f4a-2375-4be0-b3dc-31a3b58f7731">

**Comment by Haleygo** [comment]
> Here's a sample with the `now()` query.
> 
> <img alt="Captura de pantalla 2024-06-27 a las 9 32 00" width="381" src="https://private-user-images.githubusercontent.com/15650406/343675426-73d3fd6b-129b-411e-8314-c300c67b6ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Nzk3NzgsIm5iZiI6MTcxOTQ3OTQ3OCwicGF0aCI6Ii8xNTY1MDQwNi8zNDM2NzU0MjYtNzNkM2ZkNmItMTI5Yi00MTFlLTgzMTQtYzMwMGM2N2I2ZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMzY1MGEzNWJjN2Q3NDZjNmUwYzgxMzUyNmJkNmRhOTNmMDg2ODcyYTBiMzI4OTZhNWUxMmUzMjk1MzIzM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MJMhUg6guT9k9Zzx35QOyzrEWBKPyB_dmoeOHBO86-Y"> <img alt="Captura de pantalla 2024-06-27 a las 9 32 39" width="393" src="https://private-user-images.githubusercontent.com/15650406/343675872-fcc34f4a-2375-4be0-b3dc-31a3b58f7731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0Nzk3NzgsIm5iZiI6MTcxOTQ3OTQ3OCwicGF0aCI6Ii8xNTY1MDQwNi8zNDM2NzU4NzItZmNjMzRmNGEtMjM3NS00YmUwLWIzZGMtMzFhM2I1OGY3NzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA5MTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNzA1ODdjNGQxNDMxNGM1NmM2NGQ0ZDc2ZWE4MDZiMDUwNDdiZWIyNWM5ODdjZmRjYTA5ZTZkMGI5OTFkNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.elzlvmKC2Jg0epWL-OgsWpGcF1uXO6VW-fHaz_Ymvf8">

Thanks for the data! 
So the offset result is non-zero and calculated from these two samples:
```
redis_master_repl_offset: 46704583367809@1719473369.667
redis_slave_repl_offset:  46705581449861@1719473414.667
```
And the query timestamp is `1719473417`, indicating the query shouldn't fetch samples newer than `1719473417-30s=1719473387`, but it does not apply to `redis_slave_repl_offset` here.
Have you disabled the cache for these queries? If so, the `search.latencyOffset` will be omitted, resulting in this output.
Can you reproduce this issue with cache enabled?

**Comment by fmadrids** [comment]
Hi @Haleygo ,

Yes, I had disabled the query cache thinking having no cache would be more like a "raw" vmalert query. I didn't know it had to do the `search.latencyOffset` :-(

Now I'm not being able to reproduce the strange behaviour I had before, though I still don't know why the alerts triggered then (?).

Either way, if it now works it's all right. Thank you so much!
