### ISSUE TITLE
Feature request: show link to VM query UI from vmalert

### ISSUE THREAD

**Issue by bduffany** [VictoriaMetrics/VictoriaMetrics#6536]
### Is your feature request related to a problem? Please describe

The vmalert UI is pretty bare-bones - it shows the alert query but doesn't show a chart.

It is helpful to see a chart so that we can visualize the severity of the alert. One of our team members mentioned that this used to be available with prometheus but is no longer available after switching to VictoriaMetrics.

### Describe the solution you'd like

It would be nice if a chart were shown in this page, but I'm guessing that `vmalert` is probably a minimal application that doesn't include charting functionality in its web UI. So the second-best solution would be to allow configuring a URL template which could be used to render a link to VM UI.

### Describe alternatives you've considered

I see that it's possible to use Grafana Alerting but this seems like a relatively heavyweight solution when all we really need is to see a chart - plus we're already using Grafana dashboards as well as VM UI which are both capable of rendering charts themselves.

The docs also mention that it's possible to use templating to attach an annotation which could in theory have a Grafana URL, but it doesn't seem very straightforward and I think it would require copying the templated URL annotation to all alerting rules (or having more auto-generated YAML which feels a bit overcomplicated).

### Additional information

![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/2414826/ad51013b-f791-4bfe-bbde-292ed6602474)

**Comment by hagen1778** [comment]
Hey @bduffany! Adding a link to Grafana or vmui is already possible by overriding default source link via ` -external.url` and  `-external.alert.source` cmd-line flags. See example below:
```
./bin/vmalert \
    -external.url=http://<vmui-addr> \  # the hostname and port for datasource vmui 
    -external.alert.source='vmui/#/?g0.expr={{.Expr|queryEscape}}' # the path built using alert expr
```

Now, all `source` links will lead to `http://<vmui-addr>/vmui/#/?g0.expr=$expr`, where $expr is an alerting rule
expression.

I've also added other examples here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6561

**Comment by hagen1778** [comment]
Instructions for manipulating the alert's source are available here https://docs.victoriametrics.com/vmalert/#link-to-alert-source 
Closing the request as done.
