### ISSUE TITLE
how can I implement sending metrics to telegram using vmalert

### ISSUE THREAD

**Issue by tim1737** [VictoriaMetrics/VictoriaMetrics#6537]
### Describe the question in detail

please help me how to implement sending metrics to telegram using vmalert

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
Hey @tim1737 
[VMalert](https://docs.victoriametrics.com/vmalert/) sends alerting notifications to Alertmanager there you can configure [telegram receiver](https://prometheus.io/docs/alerting/latest/configuration/#telegram_config)
