### ISSUE TITLE
I have three storage nodes. Why is the data volume of storage nodes not balanced?

### ISSUE THREAD

**Issue by SRE-Rick** [VictoriaMetrics/VictoriaMetrics#6544]
### Is your question request related to a specific component?

Vminsert
Vmstorage

### Describe the question in detail

I have three storage nodes. Why is the data volume of storage nodes not balanced?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by SRE-Rick** [comment]
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/86993048/c7b50574-2edb-456a-a60a-4fa2555b0fe5)

**Comment by tiny-pangolin** [comment]
since replication and distribution of storage is done on a per time series basis and not all time series require the same amount of storage, storage utilization will not be consistent on each storage node. If you want figure which series are consuming the most resources please look at the [cardinality explorer](https://docs.victoriametrics.com/#cardinality-explorer) in [VMUI](https://docs.victoriametrics.com/?highlight=cardinality&highlight=explorer#cardinality-explorer).

**Comment by hagen1778** [comment]
> Why is the data volume of storage nodes not balanced?

Data rebalancing isn't supported by VM - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/188).

In general, if you didn't add or remove vmstorage nodes during ingestion, the disk usage should be balanced among the. See as example playground with VM cluster collecting 1k hosts node-exporter metrics [here](https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?viewPanel=200&var-ds=P38648FE0F8C5BEA2&var-instance=.%2A&from=now-3h&to=now&orgId=1).

Other things leading to unbalanced disk usage could be the following:
1. Frequent [cluster instability](https://docs.victoriametrics.com/troubleshooting/#cluster-instability) causing re-routing of ingested data
2. Outdated old snapshots that weren't removed from the disk
3. Topology changes involving adding or removing storage nodes.
4. Different retention settings on vmstorage nodes

**Comment by jiekun** [comment]
Please see @valyala 's comment here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/188

I'm going to close this issue for now. You can subscribe to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2324 instead.
