### ISSUE TITLE
vmui for VictoriaLogs: show top 5 log streams in the bar chart

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#6545]
### Is your feature request related to a problem? Please describe

Currently [vmui for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) shows a bar chart with the number of matching logs on the selected time range according to [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6404). The matching logs can be distributed across multiple [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields). The first task during logs' exploration is to determine which log streams generate the most of matching logs. The current bar chart view doesn't provide this ability.

### Describe the solution you'd like

It would be great if the bar chart shows up to top 5 [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) with the biggest number of matching logs on the selected time range. The remaining logs streams, which do not fit the top 5, must be grouped into `other` bar. This information can be obtained via [`/select/logsql/hits` HTTP handler](https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats) by passing `field=_stream` or `field=_stream_id` query arg, so it will return hits grouped by the given `field`.

It would be great is the bar chart will contain a legend for top 5 streams with the biggest number of matching logs, so the user could click the corresponding `_stream`, and vmui would add `_stream:{...}` filter to the beginning of the query, and execute the new query. If the old query is `q`, then the new query should become `_stream:{...} AND (q)`. The parenthesis around `q` are mandatory, since `q` may contain `OR`-delimited filters.

### Describe alternatives you've considered

Manually execute `q | top 5 by (_stream)` query in order to determine top 5 log streams with the biggest number of logs for the given query `q`. This isn't convenient. This also doesn't show the distribution of log streams over time (e.g. per separate bar on the bar chart).

### Additional information

Probably, it would be better substituting the bar chart with the usual line graph when displaying top 5 log streams with the biggest number of matching logs. Line graph is easier to read than bar chart when it contains multiple lines (vs multiple small bars per each interval).

**Comment by valyala** [comment]
FYI, the commit e8322147e9966d53130fa7f0fc0ce71ff398f510 adds optional `fields_limit` query arg to [`/select/logsql/hits` endpoint](https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats). This query arg can be used for returning hits stats for top 5 [log streams](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) with the biggest number of matching logs. Hits stats for the remaining log streams is returned in `"fields": {}` group. This commit also adds `"total"` field per each returned `"fields"` group - this field contains the total number of hits for the given `"fields"` group. This information can be displayed at the bar chart legend.

**Comment by valyala** [comment]
IMHO, it would be great from readability PoV replacing bars with staircase lines on the hits chart - up to 5 lines with different colors for top 5 log streams with the biggest number of logs on the selected time range, plus "other" line for the rest of log streams.

Note that the [`/select/LogsQL/hits` API](https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats) returns hits per each `[timestamp ... timestamp+step)` interval. So staircase line value must be equal to the number of hits on the corresponding interval. If some intervals are missing for some line, then the line must contain zero values on these intervals.

@Loori-R , FYI

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6647 was merged and will be included into the next vlogs release.

**Comment by valyala** [comment]
FYI, this feature has been included in [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).

@Loori-R , could you address the following comments in the follow-up pull requests:

1. It would be great to show the time range in the tooltip when hovering staircase graph. Currently only the starting time of the stair is shown. This complicates the understanding of the time range per each stair on the graph.
2. It would be great to use bolder lines for staircase graphs. This should improve the usability of the graph.
3. It would be great increasing the number of stairs on the graph to 100, since currently they are too coarse for typical log investigation tasks.
4. It would be great reducing the maximum width of the tooltip to 1/3 of the screen width, since currently too long `_stream` values result in too wide tooltips, which may overlay lines at the cursor position. This makes hard using the staricase chart efficiently. This can be done by trimming too long `_stream` values to some prefixes of these values, so they fit 1/3 of the screen width.
5. It would be great inserting only the label name under the cursor into the query input field when clicking the line legend with `ctrl`. For example, if clicking `kubernetes_container_name="vmagent"`, then `_stream:{kubernetes_container_name="vmagent"}` must be added to query input field. Currently all the `_stream` labels are added into `_stream:{...}` filter. This makes less convenient the `ctrl`+click on the line legend when the number of `_stream` labels is big (like in typical Kubernetes setup).

**Comment by valyala** [comment]
All the comments from [this message](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6545#issuecomment-2336805237) were addressed in [v0.31.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.31.0-victorialogs) release. Closing the feature request as done.
