### ISSUE TITLE
Something like `min_over_time` that considers `default` operator as well

### ISSUE THREAD

**Issue by vijayaggarwal** [VictoriaMetrics/VictoriaMetrics#6549]
### Is your feature request related to a problem? Please describe

I have a metric `uptime{service="service_name"}` that tracks uptime of my services. The metric is updated once every 30s. The value is 1 if the service is up. Importantly, the value is not pushed if the service is down, i.e., the value is "missing" and not 0 if the service is down. Now, I use the query `uptime{service="service_name"} default 0` to fill missing values with 0s. I use this query to plot graphs. The graphs look fine when the time range is small and hence the `step` is 30s. But if I plot the graph over say 2 days causing the step to become something like 5m, then the range query does not return any 0 values. I also tried `min_over_time` function, but still the query does not return any 0 values. I guess this is because as per documentation, the min_over_time function calculates the minimum value over "raw samples" (and hence does not consider the `default` operator).

If the requirement seems general enough, can it be supported by updating the behavior of min_over_time or through any other way?

### Describe the solution you'd like

Either update `min_over_time` to consider `default` as well, or create a new function or any other way that feels most appropriate.

**Comment by tiny-pangolin** [comment]
I can recreate the problem as well with `min_over_time` and `drop_series` . My best guess is that the default will add 1 value per step. I was able to fix the problem by adjusting the step value in Grafana and VMUI.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13280132/34232bb4-bf5a-418c-8cff-9038389961d0)
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/13280132/a7c7d465-e847-4dcc-94e4-fa99ce7fe40b)

**Comment by vijayaggarwal** [comment]
@tiny-pangolin Thanks for the additional details!

In my case though, changing the step to 1m is not feasible, as the query is executed over a period of 2 days (or even 7 days). Having step of 1m will produce too many data points for the graph to handle.

**Comment by tiny-pangolin** [comment]
are you receiving any errors or experiencing issues when do this if so what are they? Running the query above with out the check_name filter works fine for 30 days of data for me.

**Comment by vijayaggarwal** [comment]
@tiny-pangolin I didn't understand the `check_name` part. Is this some feature of MetricsQL that I am unaware of? Anyway, answering your question below.

The query does not return any errors, but the results are incorrect. Let me explain:

We use the metric `uptime{service="service_name"}` to track uptime of our services. Normally, we run the query `uptime{service="service_name"} default 0` to identify downtimes. This works fine if we plot the graph over a small duration, say 1 hour. However, we often also want to identify downtimes over a longer time interval, say 1 week. However, if we plot the graph over 1 week with this query, it shows no downtimes (our downtimes last only 1-2 minutes).

I guessed that adding `min_over_time` should solve the problem as it would make the query pick the minimum value at every step, so I modified the query to `min_over_time(uptime{service="service_name"} default 0)`. But, to my surprise, the graph was still not showing any downtimes over 1 week duration. To be sure, I selected a 1 hour duration in the past and the graph did show the downtimes now. So, it was clear to me that the output was incorrect only for longer durations.

Multiple people in my team do their analysis independently, and this use-case of plotting graphs over longer time durations comes up often. It is in this context that I said that changing the step to 1m is not feasible for me because (1) we need to often run queries for 1 week time range and 1m step produces too many data points for the graph to properly handle, and (2) multiple people write queries independently and so the 1m step constraint becomes difficult to enforce practically.

Lastly, getting an error would still be better, but presently we incorrectly draw the conclusion that there were no downtimes. This incorrect conclusion can lead us to make wrong decisions, and this is my biggest concern here.

I feel that the query I am writing should give the result I expect, but if we say that the `default` operator is supposed to work this way only, I would be happy to get a suggestion on what query I can use to get the result I expect, i.e., to be able to identify downtimes when plotting graphs over longer time ranges.

**Comment by tiny-pangolin** [comment]
`check_name` isn't a metricsql feature it is a label I add to my blackbox checks so there is a human readable name tied to a URL.

if adjusting the step isn't a viable workaround. Then I would modify whatever is emitting the metric to report 0 if something isn't up since the check for uptime failing is different than no data and it wouldn't involve adding any extra steps. If that isn't possible then you can create a recording rule with `expr: uptime{} default 0` which will create a metric with zero filled in so users don't have to use `default 0` or adjust the step.

The reason I suggest these workarounds instead of changing the behavior of default is I cannot think of a way to have just enough data points appear in the query since spraying 1 data point per minute/second is too many data points and cause other issues but using the step to determine this is causing your issue. I also think it is more accurate to have a way to tell the difference between service is up and data is not being sent to VictoriaMetrics since there are cases were your service is up and sending metrics to VMAgent but VMAgent cannot write the data to VictoriaMetrics.

**Comment by vijayaggarwal** [comment]
@tiny-pangolin Thanks! Using recording rule to fill the gaps with 0 is a great idea. I will implement this at my end.
