### ISSUE TITLE
victorialogs: some queries with logical filter return unexpected results

### ISSUE THREAD

**Issue by francisye19** [VictoriaMetrics/VictoriaMetrics#6554]
### Describe the bug

Here is an example log: `{"A": "a", "B": "b", "_msg": "message"}`. The following queries were expected to return the log but they didn't.

1. `A:=a AND (B:=b OR C:=c)`
2. `A:>=a OR C:=c`
3. `A:=a AND B:=b OR C:=c`

It's reproducible with the latest version (v0.25.0), while older versions (e.g. v0.15.0) return the expected results.

### To Reproduce

**Ingest:**
```shell
echo '{"A": "a", "B": "b", "_msg":"message"}' | curl -XPOST -H 'Content-Type: application/stream+json' --data-binary @- 'http://localhost:9428/insert/jsonline'
```

**Query:**
```shell
curl 'http://localhost:9428/select/logsql/query' --data-urlencode 'query=A:=a AND (B:=b OR C:=c)'
```

### Version

victoria-logs-20240628-172156-tags-v0.25.0-victorialogs-0-g9877c086b9

**Comment by valyala** [comment]
[VictoriaLogs v0.29.0](https://docs.victoriametrics.com/victorialogs/changelog/) should properly execute queries with [`or` filters](https://docs.victoriametrics.com/victorialogs/logsql/#logical-filter) over distinct log fields such as `field1:foo OR field2:bar`. Closing the issue as fixed.

@francisye19 , feel free re-opening the issue if you'll encounter incorrect query results from [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).
