### ISSUE TITLE
API docs: sort table of contents

### ISSUE THREAD

**Issue by bh-tt** [VictoriaMetrics/VictoriaMetrics#6563]
### Is your feature request related to a problem? Please describe

I'm a little frustrated when browsing the API docs for the operator as items are not sorted alphabetically. Sorting them alphabetically helps a lot with searching for a specific type (I can simply scroll instead of searching through the 20+ matches for e.g. VMPodScrape).

### Describe the solution you'd like

Is it possible to alphabetically order that page?

**Comment by AndrewChubatiuk** [comment]
Hey @bh-tt 
operator is in a separate repo and has it's own issues
but anyway there's a PR which updates docs for operator
does it fit your needs?
https://github.com/VictoriaMetrics/operator/blob/docs-cleanup/docs/api.md

**Comment by bh-tt** [comment]
I'm talking about the docs over at https://docs.victoriametrics.com/operator/api/, which are very much not sorted. Thanks for pointing out that page tho, that does help.

**Comment by AndrewChubatiuk** [comment]
These are the same docs, I've sent you a link to how it will look like after [PR](https://github.com/VictoriaMetrics/operator/pull/1004) is merged

**Comment by bh-tt** [comment]
That looks good. Sorry for opening the issue here, was not sure where the source for docs.victoriametrics.com was located so I figured here would be a good start.
