### ISSUE TITLE
vmalert absent() does not trigger alert

### ISSUE THREAD

**Issue by gnulux** [VictoriaMetrics/VictoriaMetrics#657]
**Describe the bug**

Runing Telegraf clients which send data every 5min to Victoriametrics
I configured a vmalert agent  ( in kubernetes) in order to send alert to alertmanager with the following rules

groups:
    - name: System
      interval: 7m
      rules:
      - alert: HighCpuSystem
        expr: cpu_usage_user{cpu="cpu-total"} > 80
        for: 10m
        labels:
          severity: CRITICAL
        annotations:
          summary: High CPU request
          description: " {{ $labels.host }} consumes {{ $value }} of CPU for more than 20m"

      - alert: HostNotAlive
        expr: absent(cpu_usage_system{cpu="cpu-total"}) == 1
        for: 20m
        labels:
          severity: CRITICAL
        annotations:
          summary: Host not reachable
          description: "No metrics received from {{ $labels.host }} for more than 20 mn"

I don't receive alert when a host does not send datapoint. but it works well when cpu reach 80%
the query works well on grafana explorer

**To Reproduce**

**Expected behavior**
To receive an alert in alertmanager when no data is present for a host

**Version**
vmalert-20200724-180921-tags-v1.39.0-cluster-0-gcc735da81

**Used command-line flags**
    "-rule=prod-rules.rules"
      - "-datasource.url=http://victoriametrics:8428"
      - "-notifier.url=http://alertmanager-service:9093"
      - "-evaluationInterval=7m"

**Comment by hagen1778** [comment]
Thanks for report! Will take a look and get back to you!

**Comment by varuzam** [comment]
I  am not sure but, perhaps, this behavior is explained as  you have more than one host and hence there are many metrics like this cpu_usage_system{cpu="cpu-total"}. The alert is triggered  only when all the hosts are down

**Comment by gnulux** [comment]
Hi Varuzam, 

Not sure, when playing the query on Grafana  it shows only the disconnected host. I din't read the code yet but i understand that vmalert generates an alert based on the result of the query.
From my understanding it returns only host which does not have data for cpu_usage_system{cpu="cpu-total"} . My question is on which data retention vmalert  base on in order to see the complete list of host as no data is availbale for 20m for the disconnected host ?
I also tried with this query but same result : absent(cpu_usage_system{cpu="cpu-total"}[30m]) .

Before going in production, I made a test  with little values like evaluationInterval=1m  and metrics gathered every 10s from telegraf and it worked well. I changed to 5m in order the reduced data consumption on 4G line.

**Comment by varuzam** [comment]
What, you described, is Grafana magic. VictoriaMetrics returns empty value. Try this `curl -g 'http://localhost:8428/api/v1/query?query=absent(cpu_usage_system{cpu="cpu-total"})==1' `

**Comment by valyala** [comment]
> I also tried with this query but same result : absent(cpu_usage_system{cpu="cpu-total"}[30m])

Try substituting `absent` with `absent_over_time`: `absent_over_time(cpu_usage_system{cpu="cpu-total"}[30m])`. See docs about `absent_over_time` - https://prometheus.io/docs/prometheus/latest/querying/functions/#absent_over_time .

**Comment by gnulux** [comment]
> absent_over_time(cpu_usage_system{cpu="cpu-total"}[30m])

same result

**Comment by gnulux** [comment]
When removing '==1'  I have a result

curl -s -g 'http://localhost:8428/api/v1/query?query=absent(cpu_usage_system{cpu="cpu-total"})' | jq 
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": [
      {
        "metric": {
          "cpu": "cpu-total",
          "host": "box-demo2"
        },
        "value": [
          1596020916,
          "1"
        ]
      }
    ]
  }
}

**Comment by gnulux** [comment]
Ok  i partially understood what's going on . In fact both queries absent and absent_over_time works but for a weird defined time of five minutes.
This is what i did :
I have restart vmalert with default interval: 1m
then
while true; do sleep 5 ; curl -g 'http://localhost:8428/api/v1/query?query=absent_over_time(cpu_usage_system{cpu="cpu-total"}[10m])==1' ; echo; done

After roughly 5min (again) i t gives me this output after I've stopped telegraf process on the host (box-demo2) 

`{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059102,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059107,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059112,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059117,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059122,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059127,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059132,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059138,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059143,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059148,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059153,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059158,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059163,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059168,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059173,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059178,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059183,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059189,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059194,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059199,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059204,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059209,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059214,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059219,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059224,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059229,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059235,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059240,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059245,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059250,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059255,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059260,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059265,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059270,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059275,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059280,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059286,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059291,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059296,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059301,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059306,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059311,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059316,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059321,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059326,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059331,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059337,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059342,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059347,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059352,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059357,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059362,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059367,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059372,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059377,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059383,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059388,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059393,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"cpu":"cpu-total","host":"box-demo2"},"value":[1596059398,"1"]}]}}
{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[]}}
{"status":"success","data":{"resultType":"vector","result":[]}}`

As you can see after 5 min the query does not return data. I have modified my alerting rule with "for: 1m" (lower than 5mn) and now I have an alert. 
However after 5 minutes vmalert triggers another alert telling that the previous one is resolved whereas telegraf is still stopped. 

Why the result shows data during 5 minutes ? Is it possible change this behaviour ? 
Do you have any suggestion in order  to detect when a host is not sending data ?

**Comment by valyala** [comment]
It looks like the expected behavior for [absent](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent) and [absent_over_time](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent_over_time) functions from PromQL - these functions are mostly needed for detecting time series .

> Do you have any suggestion in order to detect when a host is not sending data ?

Try the following query instead: `lag(cpu_usage_system{cpu="cpu-total"}[24h]) > 5*60` - it will return time series with missing samples for at least 5 last minutes (5*60). It stops returning time series with missing samples for more than `24h`.
