### ISSUE TITLE
Feature Request: Disable Display of Sensitive Headers in Scrape Configs

### ISSUE THREAD

**Issue by IsQiao** [VictoriaMetrics/VictoriaMetrics#6573]
### Is your feature request related to a problem? Please describe

I would like to request a feature to disable the display of header values within scrape_configs in the /config endpoint. Currently, headers contain sensitive information that is exposed when the /config endpoint is accessed. This presents a security risk, as sensitive data can be easily retrieved through this interface.

### Describe the solution you'd like

Introduce a configuration option that allows users to disable the display of headers in the /config endpoint output. When this option is enabled, headers should either be masked or completely omitted from the output to prevent sensitive information from being exposed.

when, I curl the `/config` route, the VM display my token value in browser.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/8536046/35727499-f9f3-422f-b29a-4b6ee6d35736)

**Comment by hagen1778** [comment]
Hello @IsQiao!

You can protect access to /config endpoint via the following cmd-line flag:
> -configAuthKey value
   Authorization key for accessing /config page. It must be passed via authKey query arg. It overrides httpAuth.* settings.
   Flag value can be read from the given file when using -configAuthKey=file:///abs/path/to/file or -configAuthKey=file://./relative/path/to/file . Flag value can be read from the given http/https url when using -configAuthKey=http://host/path or -configAuthKey=https://host/path

Will that help?

**Comment by IsQiao** [comment]
yes, the solution can resolve my problem, thanks. 😊
