### ISSUE TITLE
Underscores in label names result in no results for label_values() in grafana

### ISSUE THREAD

**Issue by blakebarnett** [VictoriaMetrics/VictoriaMetrics#658]
**Describe the bug**
I'm assuming it's a bug in vmselect handling labels with underscores in their name.

**To Reproduce**
label_values(metric_name, label_with_underscore)

**Expected behavior**
Values for the label to be returned

**Screenshots**
Works:
![Screen Shot 2020-07-28 at 7 13 14 PM](https://user-images.githubusercontent.com/19394251/88748661-66a01e80-d106-11ea-83c6-e024f9b35901.png)
Doesn't work:
![Screen Shot 2020-07-28 at 7 14 04 PM](https://user-images.githubusercontent.com/19394251/88748698-833c5680-d106-11ea-996f-2520d33329c0.png)

**Version**
```vmselect-20200620-225258-tags-v1.37.2-cluster-0-g50aa34bcb```

**Comment by valyala** [comment]
@blakebarnett , could you share a graph for the following query on the `last 24 hours` time range?

`count(hermes_web_inflight_connections) by (gcp_project)`

If the graph shows multiple `gcp_project` lines, then try selecting `last 24 hours` time range on the dashboard, then switching to `Dashboard settings->Variables` menu and verifying whether `label_values(hermes_web_inflight_connections, gcp_project)` returns any values.

**Comment by blakebarnett** [comment]
There's only 1 graph line unless I go back 7 days (which is strange because there has always only be 1 gcp_project for this metric, this might be from when prometheus was having trouble keeping up with remote_write, we've since switched to vmagent as of a few days ago.)

**Comment by blakebarnett** [comment]
Unfortunately I can't keep the time range this wide, is there a way to fix this live or is it actually a bug?

**Comment by blakebarnett** [comment]
I tracked this down to an IAM permissions issue on GCP, it just presented very oddly.
