### ISSUE TITLE
After upgrading to v1.101.0-cluster, vmstorage crashes repeatedly

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#6585]
### Describe the bug

Yesterday, I upgraded from version v1.93.5-cluster to v1.101.0-cluster. This morning, around 7 AM (I’m in the GMT+8 timezone), vmstorage started repeatedly crashing. Here is the error stack trace:

```
runtime: pointer 0xc00ece5ffc to unused region of span span.base()=0xc00ecd6000 span.limit=0xc00ece5ffc span.state=1
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

goroutine 125 gp=0xc00a758a80 m=17 mp=0xc0001c9008 [running]:
runtime.throw({0x96df0a?, 0xc00a95d5b8?})
	runtime/panic.go:1023 +0x5c fp=0xc00a95d588 sp=0xc00a95d558 pc=0x43a01c
runtime.badPointer(0x7f7f5ab855d8, 0xc00ece5ffc, 0x0, 0x0)
	runtime/mbitmap.go:286 +0x165 fp=0xc00a95d5d8 sp=0xc00a95d588 pc=0x4150e5
runtime.findObject(0xc00fd1c700?, 0xac?, 0xc00?)
	runtime/mbitmap.go:329 +0xa6 fp=0xc00a95d610 sp=0xc00a95d5d8 pc=0x415266
runtime.checkptrBase(0xc00ece5ffc)
	runtime/checkptr.go:94 +0x3e fp=0xc00a95d638 sp=0xc00a95d610 pc=0x407b3e
runtime.checkptrArithmetic(0xfffc?, {0xc00a95d6b0, 0x1, 0x0?})
	runtime/checkptr.go:58 +0x38 fp=0xc00a95d668 sp=0xc00a95d638 pc=0x407a38
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.Item.String(...)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/encoding.go:39
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*inmemoryBlock).Less(0x200?, 0x17d?, 0xc000213350?)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/encoding.go:54 +0x8e fp=0xc00a95d6c8 sp=0xc00a95d668 pc=0x72b6ce
sort.IsSorted({0xa793f0, 0xc00ab38e00})
	sort/sort.go:108 +0x51 fp=0xc00a95d6f8 sp=0xc00a95d6c8 pc=0x47e3b1
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*inmemoryBlock).isSorted(...)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/encoding.go:206
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*inmemoryBlock).UnmarshalData(0xc00ab38e00, 0xc00ab38f20, {0xc00bab1c86, 0x17d, 0x17d}, {0xc00bab1b07, 0x17d, 0x0?}, 0xac, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/encoding.go:347 +0x6db fp=0xc00a95d980 sp=0xc00a95d6f8 pc=0x72d93b
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamReader).Next(0xc00ab38e00)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/block_stream_reader.go:225 +0x51b fp=0xc00a95dab8 sp=0xc00a95d980 pc=0x72a07b
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*blockStreamMerger).Merge(0xc00a73c500, 0xc000003680, 0xc00aa3a140, 0xc000247c20, 0xc00016c2a8)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/merge.go:149 +0x2a5 fp=0xc00a95db98 sp=0xc00a95dab8 pc=0x730d45
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.mergeBlockStreams(0xc00aa3a140, 0xc000003680, {0xc002eb4150, 0xd, 0xd}, 0x9f8b70, 0xc000247c20, 0xc00016c2a8)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/merge.go:36 +0x10e fp=0xc00a95dc28 sp=0xc00a95db98 pc=0x73058e
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergePartsInternal(0xc00016c280, {0xc00a918000, 0x32}, 0xc000003680, {0xc002eb4150, 0xd, 0xd}, 0x1, 0xc000247c20)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/table.go:1318 +0x17a fp=0xc00a95dce0 sp=0xc00a95dc28 pc=0x73cf3a
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).mergeParts(0xc00016c280, {0xc002eb40e0, 0xd, 0xe}, 0xc000247c20, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/table.go:1217 +0x58c fp=0xc00a95df10 sp=0xc00a95dce0 pc=0x73c48c
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).filePartsMerger(0xc00016c280)
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/table.go:1119 +0x145 fp=0xc00a95dfb8 sp=0xc00a95df10 pc=0x73bba5
github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startFilePartsMergerLocked.func1()
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/table.go:424 +0x1c fp=0xc00a95dfe0 sp=0xc00a95dfb8 pc=0x737d7c
runtime.goexit({})
	runtime/asm_amd64.s:1695 +0x1 fp=0xc00a95dfe8 sp=0xc00a95dfe0 pc=0x474841
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset.(*Table).startFilePartsMergerLocked in goroutine 1
	github.com/VictoriaMetrics/VictoriaMetrics@v1.101.0-cluster/lib/mergeset/table.go:423 +0x85
```

I compared the code between v1.93.5-cluster and v1.101.0-cluster versions and found that the unsafe string conversion code had been changed. I manually patched the previous method using reflection on the v1.101.0-cluster code. After manually building and upgrading, the crashes stopped.
![image](https://github.com/VictoriaMetrics/VictoriaMetrics/assets/3659110/9f70889a-1049-4a48-ac95-98fc1c423221)

In theory, these two pieces of code should be logically equivalent, but could there be some unusual corner cases that were not considered? @valyala 

### To Reproduce

I don’t know. It doesn’t seem to be consistently reproducible. I didn’t encounter it after upgrading other clusters, but in this particular cluster, it repeatedly restarts and crashes.

### Version

v1.101.0-cluster

### Logs

[guancedb-cluster-guance-storage-2.log](https://github.com/user-attachments/files/16104675/guancedb-cluster-guance-storage-2.log)

**Comment by f41gh7** [comment]
According to the go unsafe convention, both versions must be safe to use. 
But non-default compiler may break those rules. Recently we got few reports with memory corruption, when people used own builds with old version of gcc.

**Comment by faceair** [comment]
I used the same Docker setup as VictoriaMetrics to build the image, with gcc 11.2.1 from musl (Snapshot 11-20211120). The CPU model of the server where vmstorage crashes is Intel(R) Xeon(R) Gold 6151 CPU @ 3.00GHz.

As you mentioned, could it be that gcc is not fully compatible with the implementation of unsafe.Slice in certain scenarios? The previous version using reflection might have better compatibility? However, I haven’t found any related feedback in golang's issues.

**Comment by f41gh7** [comment]
And given log was collected after compilation of vmstorage with non-default flag `checkptr` , is it correct? 

> As you mentioned, could it be that gcc is not fully compatible with the implementation of unsafe.Slice in certain scenarios? 

 unsafe.Slice adds only 1 additional safety check for string len. It shouldn't cause problem. 

 Maybe CGO runtime corrupts memory and it may have mixed pointers (initialized at go runtime and uninitialized at cgo). Currently, it's hard to say. There was a fix to gozstd package https://github.com/valyala/gozstd/commit/8e7a79f9d0cc09341fc5b51d3873f34ee0711898 . But I believe it's really rare.

**Comment by faceair** [comment]
Yes, I added a compile flag `-gcflags=all=-d=checkptr`. Should I remove it ?

**Comment by f41gh7** [comment]
> Yes, I added a compile flag `-gcflags=all=-d=checkptr`. Should I remove it ?

 It has performance impact and could prevent a certain functions from inlining, but it shouldn't be related with current issue.

 Also, I noticed that usage of unsafe.SliceData and unsafe.StringData could lead to undefined behavior if input was not validated for corner cases ( empty string, 0 cap byte slice).

https://pkg.go.dev/unsafe#SliceData

**Comment by valyala** [comment]
@faceair , could you build VictoriaMetrics with [Go1.23rc1](https://pkg.go.dev/golang.org/dl/go1.23rc1)? This will help ruling out [potential bug at Go1.22](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6425), which is used for building VictoriaMetrics v1.101.0 .

**Comment by faceair** [comment]
When we tried Go 1.23rc, we discovered some issues caused by the checkptr option. https://github.com/golang/go/issues/68415 https://github.com/golang/go/issues/68511

We now suspect that checkptr was responsible for the problems we encountered earlier. It seems that not many people have enabled this option, so the testing might not have been very thorough. We will disable this option in our production build later.

Next week, we will use Go 1.22 with checkptr disabled in the production environment and Go 1.23 next rc version with checkptr enabled in the testing environment, hoping to resolve this issue in both versions.

**Comment by hagen1778** [comment]
Hello @faceair! Have you had a chance to test it with new Go version?

**Comment by faceair** [comment]
We have verified in the test environment that the 1.23 version of Go, when checkptr is enabled, no longer exhibits this issue.
Similarly, in the production environment, using the 1.22 version with checkptr disabled also does not exhibit this issue.

It appears that this problem is related to the 1.22 version combined with checkptr. Enabling this option does not yield any additional benefits, so we do not plan to turn it back on. With that, we consider this matter resolved. Thank you all for your support!
