### ISSUE TITLE
Pass X-Forwarded-For header from http requests into logs

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#659]
We using http reverse proxy in front of some VM components. As a result, VM writing into logs proxy's address, instead of original client address, which sometimes makes it difficult to debug. Proxy passing original address in standard `X-Forwarded-For` header, but it looks like VM ignores it.

I suggest to support `X-Forwarded-For` header. If it presents in request, use its value in logs as client address, or write it as additional filed in logs.

**Comment by valyala** [comment]
Added `X-Forwarded-For` header in error messages in the following commits:

* Single-node version: 67a64c142dbd44bbd406bb9155865c99e55c90b1
* Cluster version: 1e067401ba6ae52f24ab24470ef5e1dd8a14efc4

These commits will be included in the next release.

**Comment by valyala** [comment]
The `X-Forwarded-For` header has been added to error logs starting from [v1.39.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.

**Comment by valyala** [comment]
FYI, the `X-Forwarded-For` request header is shown at `/api/v1/status/active_queries` page starting from [v1.39.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). This should simplify detecting clients that send heavy queries.
