### ISSUE TITLE
Add docs for installing Single and Cluster from Binaries.

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#6597]
### Is your feature request related to a problem? Please describe

A Quick start guide for VictoriaMetrics Single and VictoriaMetrics Cluster without the use of ansible or conatiners.

### Describe the solution you'd like

docs that walk through downloading binaries from github, placing them on the local filesystem, and creating a systemd unit.

**Comment by jiekun** [comment]
As it's addressed by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6598 (with a few comments left in the follow-up commit by @hagen1778 ,tho), is it OK to close this issue as completed? @tiny-pangolin
