### ISSUE TITLE
Influx protocol skip field value 

### ISSUE THREAD

**Issue by ihard** [VictoriaMetrics/VictoriaMetrics#66]
Please add flag for skip add field value to `__name__` when processing influx protocol.
This will allow to release a transparent collection of exporters' metrics by telegraf and sending them to VictoriaMetrics without changing the names of the metrics.

**Comment by valyala** [comment]
@ihard , this should be fixed in master branch when `-influxSkipSingleField` flag is set.

**Comment by valyala** [comment]
This functionality is available starting from [v1.20.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
