### ISSUE TITLE
Whether the old data can be synchronized to the new storage node？

### ISSUE THREAD

**Issue by menglee37** [VictoriaMetrics/VictoriaMetrics#6602]
### Describe the question in detail

Hi, Thank you for checking my question.

Background: We are prepare to upgrade the all VictoriaMetrics cluster node system one by one. After the node is upgraded, add it to the cluster again, synchronize the old data, and then move on to the next node.

Question1:
Whether a command can be used to synchronize old data to the newly add storage node?  We need to add a storage node to cluster , but the VictoriaMetrics cluster only schdule the new data to new node, i can't find anything in the documentation about synchronizing old data.

Thanks again!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
it looks like there are two questions here 1 is about upgrading an existing storage node and  how to redistribute old data after a node is added to the cluster

if you are upgrading a cluster 1 storage node at a time then you do not need to do anything after the node comes back online. When the list of storage nodes is changed on vminsert  inserts will be routed based on the new topology and your replication factor.  So if a node is unavailable the time series that were being written to it will be written to the remaining nodes in the cluster until it comes back online and you will see increased resource usage unless the  `-disableReroutingOnUnavailable` flag is set to true on vminsert. if it is set then then writes will not be redistributed to and you will have 1 less copy of that while the data while the node is down. 

it might be simpler to shutdown the insert and select nodes in the cluster, upgrade all the storage nodes and turn on vminsert and vmselect after the cluster has been upgraded. This can be done with 0 data loss if data is being sent VMAgent. 

for adding new nodes it possible to configure vminsert favor new nodes until they have the same amount of data as the existing nodes, but I'm unsure if you can replay the data through the cluster to redistribute data.

Please see our [cluster upgrade docs](https://docs.victoriametrics.com/cluster-victoriametrics/#updating--reconfiguring-cluster-nodes) for more details.

**Comment by tiny-pangolin** [comment]
> for adding new nodes it possible to configure vminsert favor new nodes until they have the same amount of data as the existing nodes, but I'm unsure if you can replay the data through the cluster to redistribute data.
you can replay data through the database however this is not recommended

**Comment by menglee37** [comment]
Hi @tiny-pangolin 

"it might be simpler to shutdown the insert and select nodes in the cluster, upgrade all the storage nodes and turn on vminsert and vmselect after the cluster has been upgraded. This can be done with 0 data loss if data is being sent VMAgent."
Got it.
Thanks for your reply!

**Comment by jiekun** [comment]
I assume this question is answered by @tiny-pangolin . I'm closing it now but feel free to open it again if you encounter further issue.
