### ISSUE TITLE
VmAlert Recording performance very low

### ISSUE THREAD

**Issue by weenxin** [VictoriaMetrics/VictoriaMetrics#661]
**Describe the bug**
A same query, I can configure grafana dashboard (use `query_range` inteface), It will show curve in one minite. 

But When I use VmAlert( which use `query` interface ) It will failed because of time limit (5 minites).

**Expected behavior**
Same performance between interface.

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
./vmstorage-prod --version
vmstorage-20200727-210909-tags-v1.39.1-cluster-0-g96bc476e5
```

**Comment by valyala** [comment]
@weenxin , could you provide the query, which times out on `vmalert` and the graph for the query from Grafana dashboard?

**Comment by valyala** [comment]
@weenxin , any updates on this issue?

BTW, it looks something is broken if the query take more than one minute to execute. Probably the query touches too many time series (millions) or too many data points (billions). Or `vmstorage` runs on a server with insufficient amounts of resources (RAM, disk IO bandwidth, CPU, network bandwidth). It is recommended setting up monitoring for the cluster according [to these docs](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#monitoring). This may give insights in cluster health and performance. It is also recommended investigating high cardinality source and/or high churn rate source for time series via `/api/v1/status/tsdb` handler. See https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#url-format for more details.

**Comment by weenxin** [comment]
@valyala  Thanks ， I will check it .

**Comment by hagen1778** [comment]
Closing due to no updates. Feel free to reopen
