### ISSUE TITLE
Add global default labels if none exist

### ISSUE THREAD

**Issue by StellaV** [VictoriaMetrics/VictoriaMetrics#6623]
### Describe the question in detail

Hi!

We have a monitoring setup where we route our alerts based on a label. The infrastructure team should receive all infra alerts and the application teams should receive all application alerts. The latter already have labels in their helm charts that are kept by the scraping and the routing is also configured. But what we're still missing is that "the rest" goes to the infrastructure team.

VM is deployed using the victoria-metrics-k8s-stack helm chart, where you can specify per component what labels to use for scraping, using podTargetLabels. This means we have to ensure all infra applications have the correct labels available and configure Victoria metrics to use those when scraping. 

Is there an option to add a default label instead, just like you can do with external_labels, but allow it to be overwritten by anything else defined in a podscrape, rule, etc.?

Kind regards,
Stella

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
I think this feature is not available now, considering you just want to apply them based on CRD (`vmpodscrape`)

**Comment by ties** [comment]
> There should be some tricky ways to do this, such as naming your job in a specific way and filtering them by job name, etc. However, I assume all your jobs are well-defined and cannot be easily edited.

@StellaV I did not check how we label it - but a regex-based relabel based on the on the job, pod, or namespace name might get us close?

A more native way of providing a default label would definitely be a good enhancement though!

**Comment by StellaV** [comment]
@ties that might work, but not everything is in a pod (think, kubelet monitoring).

@jiekun Thanks for the suggestion, we might try the job name filtering. 

But indeed a one-label-fits-all would be a nice solution for us :)

**Comment by Haleygo** [comment]
Hello @StellaV ,
>We have a monitoring setup where we route our alerts based on a label.

You can use [relabeling](https://docs.victoriametrics.com/vmagent/#relabeling) to add the label to metrics that miss it with `-remoteWrite.relabelConfig` in vmagent.
For instance, the following config set `team="infra"` only for metrics which do not have `team=app` labels.
```
  - if: '{team!="app"}'
    target_label: team
    replacement: infra
```
you can also use this [debug tool](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/relabeling?config=++-+if%3A+%27%7Bteam%21%3D%22app%22%7D%27%0A++++target_label%3A+team%0A++++replacement%3A+infra&labels=%7Bjob%3D%22my-infra-app%22%7D) to test relabel_config.

**Comment by jiekun** [comment]
It sounds the issue could be solved as Haley suggested. I'm closing this enhancement request now. Feel free to open it again if you have more idea to provide.
