### ISSUE TITLE
victorialogs: ability to choose a tenant in VMUI

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#6631]
### Is your feature request related to a problem? Please describe

When using [multi-tenancy](https://docs.victoriametrics.com/victorialogs/#multitenancy) in VictoriaLogs it is not possible to query logs from non-default tenant via VMUI.

### Describe the solution you'd like

I would like to have an option to tweak a tenant to be used to send a request in VMUI settings.

**Comment by zekker6** [comment]
@tenmozes It would be helpful to add just numeric input fields representing `AccountID` and `ProjectID` as it will immediately allow using VMUI in multi-tenant setups. 
Later on we can add `/tenants` API and enhance the UX for this one.

**Comment by hagen1778** [comment]
Ability to configure AccountID and ProjectID in vlogs UI was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6661 and will be available in the next release.

**Comment by valyala** [comment]
VictoriaLogs supports setting [`AccountID` and `ProjectID` values for different tenants](https://docs.victoriametrics.com/victorialogs/#multitenancy) in [web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) starting from [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing this feature request as done.
