### ISSUE TITLE
VictoriaLogs: add ability to receive logs in DataDog format

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6632]
### Is your feature request related to a problem? Please describe

That would be nice to have direct integration with datadog agent.

related pull request https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5536

### Describe the solution you'd like

To add support for Datadog protocol for logs' transfer to VictoriaLogs. 

### Describe alternatives you've considered

One of the supported log shippers is used to forward journal logs to VictoriaLogs.

**Comment by tommysitehost** [comment]
Hey guys, we are looking to use VictoriaLogs with Datadog format in our project so would be happy to contribute to push the process along if needed. Just noticed that the PR is stalled for the past 3 weeks, anything that I can help out?

**Comment by tenmozes** [comment]
@f41gh7 @AndrewChubatiuk could you please take a look? do we need to update the existing PR, do we need any help? 

@tommysitehost thank you for the willing to help!

**Comment by AndrewChubatiuk** [comment]
hey @tommysitehost
I've just updated [PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5536), it requires a review. @f41gh7 or @valyala could you please help?

**Comment by tommysitehost** [comment]
Thanks guys, let me know if you need a hand on anything. Just out of curiosity - not wanting to rush, do we have an ETA for it? Just so I know the timing if its possible :)

**Comment by AndrewChubatiuk** [comment]
Datadog logs ingestion is supported starting from v0.41.0
