### ISSUE TITLE
[vmagent] scraping consul targets differ from prometheus

### ISSUE THREAD

**Issue by nonamef** [VictoriaMetrics/VictoriaMetrics#664]
**Describe the bug**
When trying to replace prometheus with the vmagent, the consul target lists differ. Seems that the service node discovery uses different requests. vmagent uses '/v1/health/service/xxx' and prometheus uses '/v1/catalog/service/xxx'.

Prometheus: https://github.com/prometheus/prometheus/blob/master/discovery/consul/consul.go
Victoria Metrics: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/discovery/consul/service_node.go

**Expected behavior**
Consul target GET requests should be the same as Prometheus  e.g http://consul:8500/v1/catalog/service/xxx

**Version**
v1.39.2

**Comment by valyala** [comment]
Prometheus scrapes [/v1/health/service/xxx](https://www.consul.io/api-docs/health#list-nodes-for-service) endpoint as `vmagent` does - see https://github.com/prometheus/prometheus/blob/98a69b77d1eda71c20836cbebf83b956c68de3a9/discovery/consul/consul.go#L445 . The [/v1/catalog/service/xxx](https://www.consul.io/api-docs/catalog#list-nodes-for-service) response doesn't contain all the information needed for `__meta_*` labels in [consul_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config). For instance, it doesn't contain information for `__meta_consul_health` label.

The only difference between `vmagent` and `Prometheus` implementations is that `vmagent` polls Consul for service updates while `Prometheus` subscribes for service updates in Consul. The polling may be slower than the subscription when monitoring big number of services, so there are plans to switch `vmagent` to the subscription model - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/574 for details.

@nonamef , could you give more details on discrepancies you see between `vmagent` and `Prometheus` when `consul_sd_config` is enabled? It would be great if you could share `consul_sd_config` section and relabeling rules used for the scrape job.

**Comment by nonamef** [comment]
My situation is a bit more specific as I have a proxy in between prometheus/vmagent and Consul. This proxy rewrites "v1/catalog/service/“ responses to get additional data in e@tag, for the service metrics host:port.
When using the vmagent, as all responses come from '/v1/health/service’, the data is missing. I can create a workaround for the time being and will follow the progress of #574.
