### ISSUE TITLE
Recording rules run interval consistency and not missing data in recording rules

### ISSUE THREAD

**Issue by MatthewPierson** [VictoriaMetrics/VictoriaMetrics#6643]
### Is your question request related to a specific component?

~~vmagent~~
vmalert

### Describe the question in detail

Hi, I have a few questions about how consistent recording rules are in relation to when they are run and how we can avoid missing data when recording rules run.

If I have a recording rule which is set to run every 60s, and work on data from the last 60s, how much variance is there in that 60s period between rule runs? How close to every 60s is the rule run? Is there a way to ensure a recording rule picks up all new data since the last rule run, instead of just strictly from the interval specified (in this case the last 60s)?

The main reason we are asking this is that we are looking to use recording rules on aggregated data which gets inserted into VM every 30s, but we are concerned about delays in the running of the recording rule causing data to be missed. If the rule is run at `00:00:00`, `00:01:00` and `00:02:00:60` (60ms after `02:00`), and data is inserted at `00:00:00`, `00:00:30`, `00:01:00:50` (50ms after `01:00`) and `00:01:30`, will the rule run at `00:02:00:60` pickup the data inserted at `00:01:00:50`? My understanding is that the run at `00:00:00` will get nothing, since no data was inserted before the run, the run at `00:01:00`  will get the data inserted at `00:00:00` and `00:00:30` as those were both inserted before the rule was run, and my hope is that run at `00:02:00:60` would pick up the data inserted at 

We just want to avoid a situation where the recording rule misses out on 30s of aggregated data because the data came in 100ms late, or the rule run started 20ms later than it should. Is there anything built into VM which prevents recording rules from missing data in these situations such as having the recording rule grab all data since the last recording rule was run?

Another idea we had was to run the rule offset from the data inserts, sort of like the below. Would this solve this problem in your opinion?

```
Inserts      Rule Runs
00:00:00     ↓  
00:00:30     <-00:00:45
00:01:00     ↓
00:01:30     <-00:01:45
00:02:00     ↓
00:02:30     <-00:02:45
00:03:00     ↓
00:03:30     <-00:03:45
```

I hope all of this makes sense, it was a bit difficult to put into words, so please let me know if I need to expand on anything here!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Amper** [comment]
Hey, @MatthewPierson.
I believe that that answer for you question is described in [this section of the docs](https://docs.victoriametrics.com/vmalert/#data-delay).
