### ISSUE TITLE
How Victoria Metrics stores data for each tenant on Vmstorage when multitenancy is enabled

### ISSUE THREAD

**Issue by Shindek77** [VictoriaMetrics/VictoriaMetrics#6645]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

As we know when multitenancy is enabled we can send data with different tenant_id on vmtstorage, im my case tenant id are as follows:
1:1000
1:2000
1:3000
Now, i want to know how we can find that in vmstorage as per tenant under path /storage as PVC is mounted on it ?
is data in separated as per tenant id on that path as it is Mimir on object storage as well as in mimir as per tenant id...
Because I can data in below structure:
─ big
│   ├── 2024_07
│   │   ├── 17E08243EC8BE7C8
│   │   │   ├── index.bin
│   │   │   ├── metadata.json
│   │   │   ├── metaindex.bin
│   │   │   ├── timestamps.bin
│   │   │   └── values.bin
│   │   ├── 17E08243EC8BEFD0
│   │   │   ├── index.bin
│   │   │   ├── metadata.json
│   │   │   ├── metaindex.bin
│   │   │   ├── timestamps.bin
│   │   │   └── values.bin
│   │   ├── 17E08243EC8C0BFD
│   │   │   ├── index.bin
│   │   │   ├── metadata.json
│   │   │   ├── metaindex.bin
│   │   │   ├── timestamps.bin
│   │   │   └── values.bin
│   │   ├── 17E08243EC8C29E9
│   │   │   ├── index.bin
│   │   │   ├── metadata.json
│   │   │   ├── metaindex.bin
│   │   │   ├── timestamps.bin
│   │   │   └── values.bin
│   │   ├── 17E08243EC8C2D3B
│   │   │   ├── index.bin
│   │   │   ├── metadata.json
│   │   │   ├── metaindex.bin
│   │   │   ├── timestamps.bin
│   │   │   └── values.bin
│   │   ├── 17E08243EC8C311F
│   │   │   ├── index.bin
│   │   │   ├── metadata.json
│   │   │   ├── metaindex.bin
│   │   │   ├── timestamps.bin
│   │   │   └── values.bin
└── small
    ├── 2024_07
    │   ├── 17E08243EC8BC812
    │   │   ├── index.bin
    │   │   ├── metadata.json
    │   │   ├── metaindex.bin
    │   │   ├── timestamps.bin
    │   │   └── values.bin
    │   ├── 17E08243EC8C1952
    │   │   ├── index.bin
    │   │   ├── metadata.json
    │   │   ├── metaindex.bin
    │   │   ├── timestamps.bin
    │   │   └── values.bin
    │   ├── 17E08243EC8C9A1A
    │   │   ├── index.bin
    │   │   ├── metadata.json
    │   │   ├── metaindex.bin
    │   │   ├── timestamps.bin
    │   │   └── values.bin
    │   ├── 17E08243EC8C9A34
    │   │   ├── index.bin
    │   │   ├── metadata.json
    │   │   ├── metaindex.bin
    │   │   ├── timestamps.bin
    │   │   └── values.bin

**Comment by jiekun** [comment]
Hi @Shindek77 sorry for the late reply.

From the file structure, it is easy to guess that all the data of the tenants is stored together.

So you might be more interested in how this data is stored and retrieved. I have done some debugging these past few days, and here are some partial details along with steps you can try for debugging yourself.

## Steps
1. Run `vminsert` + `vmstorage` + `vmselect`.
2. Import data via:
```
curl -d "GOOG,1.23,4.56,NYSE" 'http://127.0.0.1:8480/insert/5/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market'
```
3. Query data on: `http://vmselect:8481/select/5/vmui`.

## Useful Break Points
- write: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/48a5c4cb017ad0ebd449777bc0f7b28237584531/lib/storage/storage.go#L1889
- read: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0cf18a6f636ba46cd8689a38978b8650c6a33454/lib/storage/index_db.go#L1628

## Explanation
1. During write procedure, many `struct`s (e.g. `TSID`, `indexSearch`) are generated with a field of tenant id (`AccountID` in codes). Typically, the `AccountID` will be marshaled into the index key as a prefix. (e.g. `flag | AccountID | ProjectID | MetricsName` -> `TSID`).
2. During read procedure, `vmstorage` will search for data blocks that match query condition and return to `vmselect`. Index will help with filtering data blocks, where `AccountID` will be marshaled into the index search key as one of the prefix.

I believe the Break Point mentioned above can provide you with insights into the entire process. However, if you are not able to debug them, here are some extra code blocks and explanations:
1. Write: [Generate TSID by AccountID, MetricsName and generate a unique MetricsID](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0cf18a6f636ba46cd8689a38978b8650c6a33454/lib/storage/index_db.go#L513)
2. Write: [Create index for it](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0cf18a6f636ba46cd8689a38978b8650c6a33454/lib/storage/index_db.go#L531).
3. Read: [Go through blocks](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/207b4bd91dd1e7b4b6956aef29e2765841b76881/lib/storage/search.go#L240).
4. Read: [Check if a block contains specific metric](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0cf18a6f636ba46cd8689a38978b8650c6a33454/lib/storage/index_db.go#L2044).

Also thank @zekker6 for help me.
