### ISSUE TITLE
vmalert -dryRun doesn't detect label template issues

### ISSUE THREAD

**Issue by antoinedeschenes** [VictoriaMetrics/VictoriaMetrics#6652]
### Describe the bug

`vmalert-prod -dryRun -rule test.yaml` doesn't detect label template issues

### To Reproduce

1. Create a rule file:
```
groups:
  - name: foo-alerts
    rules:
      - alert: FooAlert
        expr: up == 1 
        labels:
          severity: '{{ .foo }}'
```

2. Test rule file 
```
% vmalert-prod -dryRun -rule test.yaml                                                                                                              
2024-07-16T17:19:23.028Z	info	VictoriaMetrics/lib/logger/flag.go:12	build version: vmalert-20240425-145515-tags-v1.101.0-0-g5334f0c2c
2024-07-16T17:19:23.028Z	info	VictoriaMetrics/lib/logger/flag.go:13	command-line flags
2024-07-16T17:19:23.028Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -dryRun="true"
2024-07-16T17:19:23.028Z	info	VictoriaMetrics/lib/logger/flag.go:20	  -rule="test.yaml"
2024-07-16T17:19:23.028Z	info	VictoriaMetrics/app/vmalert/config/log/logger.go:52	found 1 files to read from "Local FS{MatchPattern: \"test.yaml\"}"
2024-07-16T17:19:23.028Z	info	VictoriaMetrics/app/vmalert/config/log/logger.go:52	finished reading 1 files in 92.328µs from "Local FS{MatchPattern: \"test.yaml\"}"
```

3. Run vmalert with above rule deployed

4. Find error in logs:
```
"msg": "group \"foo\": rule \"FooAlert\": failed to execute: failed to expand templates: failed to expand labels: failed to expand labels: errors(1): key \"severity\", template \"{{ .foo }}\": error evaluating annotation template: template: :1:248: executing \"\" at <.foo>: can't evaluate field Values in type notifier.tplData"
```

### Version

vmalert-20240425-145515-tags-v1.101.0-0-g5334f0c2c

### Logs

```
"msg": "group \"foo\": rule \"FooAlert\": failed to execute: failed to expand templates: failed to expand labels: failed to expand labels: errors(1): key \"severity\", template \"{{ .foo }}\": error evaluating annotation template: template: :1:248: executing \"\" at <.foo>: can't evaluate field Values in type notifier.tplData"
```

**Comment by zekker6** [comment]
Hello @antoinedeschenes 

`-dryRun` flag at vmalert only performs the syntax validation of the alerts configuration. It parses `expr` and labels/annotations for correct syntax of MetricsQL and Go templates.
It is not possible to perform a verification of some specific labels/annotations because when running in `-dryRun` mode vmalert does not execute the rules and thus it cannot fetch information about labels which are available in TSDB.

If you need to perform more advanced verification of alerting rules you might want to use vmalert-tool - https://docs.victoriametrics.com/vmalert-tool/
It allows to define artificial data with both values and labels to match against the alert rules.

**Comment by antoinedeschenes** [comment]
Ok, thanks for the answer, I also confirm promtool doesn't detect these issues. 

For reference, it looks like [pint](https://github.com/cloudflare/pint) can detect these issues.

```
% pint lint test.yaml
level=INFO msg="Finding all rules to check" paths=["test.yaml"]
test.yaml:7 Fatal: Template failed to parse with this error: `115: executing "severity" at <.foo>: can't evaluate field foo in type struct { Labels map[string]string; ExternalLabels map[string]string; ExternalURL string; Value interface {} }`. (alerts/template)
 7 |           severity: '{{ .foo }}'

level=INFO msg="Problems found" Fatal=1
level=ERROR msg="Execution completed with error(s)" err="found 1 problem(s) with severity Bug or higher"
```

**Comment by antoinedeschenes** [comment]
Ok, it looks like vmalert supports [additional template fields](https://docs.victoriametrics.com/vmalert/#templating) that Prometheus doesn't support. Would it make sense to consider evaluating annotation and label `<tmpl_string>` fields during alert rule validation as an enhancement?

**Comment by jiekun** [comment]
@antoinedeschenes Hi I assume that should be an enhancement. Please edit the title and description of the issue. And I will add the `enhancement` label for it. 

Also feel free to close and re-open a feature request if you prefer to keep each issue clean.

**Comment by Haleygo** [comment]
Hi @antoinedeschenes ,
It's possible to check annotations and labels during rule validataion, but vmalert also support functions that can't be executed without values (label values or query results), like `{{ slice $labels.job 9 }}`. See [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2514) for details.
So we decided to only parse templates without executing during rule validation.
