### ISSUE TITLE
VMInsert does not support InfluxDB health endpoint

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#6653]
### Describe the bug

When trying to add vminsert as a metric server in Proxmox VE and Proxmox Backup server I receive a 400 error when adding a metric server  to the gui of Proxmox VE, the gui of Proxmox Backup Server, or curling where Proxmox thinks the health endpoint should be `/insert/0/influx/health` or `/insert/0/influx/write/health`. If edit the metric server config manually I am able to send metrics to my VictoriaMetrics Cluster. 

### Curl
```
[root@vicky-test ~]# curl http://localhost:8480/insert/0/influx/write/health
remoteAddr: "127.0.0.1:54514"; requestURI: /insert/0/influx/write/health; unsupported path requested: "/insert/0/influx/write/health"
[root@vicky-test ~]# curl http://localhost:8480/insert/0/influx/health
remoteAddr: "127.0.0.1:54522"; requestURI: /insert/0/influx/health; unsupported path requested: "/insert/0/influx/health"
[root@vicky-test ~]# curl http://localhost:8428/influx/health
remoteAddr: "127.0.0.1:37700"; requestURI: /influx/health; unsupported path requested: "/influx/health"
[root@vicky-test ~]# curl http://localhost:8428/influx/write/health
remoteAddr: "127.0.0.1:37716"; requestURI: /influx/write/health; unsupported path requested: "/influx/write/health"
```
### From the proxmox Gui
1. Follow the documentation listed on the victoriaMetrics for ingesting data from proxmox
2. receive 400 error when I hit ok on the form

Adding the metric server manually on `/etc/pve/status.cfg`  for PVE and `/etc/proxmox-backup/metricserver.cfg` for PBS works fine with or without the token. The validation of the health endpoint does not seem to be checked unless you a specify an api path in PVE or have something after / in the url. because I can set this up successfully on victoriametrics single node

### Version

```
# vminsert-prod --version
vminsert-20240425-151720-tags-v1.101.0-enterprise-cluster-0-gea1c63525
```

### Logs

```
Jul 16 14:59:19 vicky-test vminsert-prod[94]: 2024-07-16T14:59:19.743Z        warn        VictoriaMetrics/lib/httpserver/httpserver.go:449        remoteAddr: "10.0.0.2:58424"; requestURI: /influx/0/write/health; unsupported path requested: "/influx/0/write/health"
Jul 16 14:59:24 vicky-test vminsert-prod[94]: 2024-07-16T14:59:24.147Z        warn        VictoriaMetrics/lib/httpserver/httpserver.go:449        remoteAddr: "10.0.0.2:38706"; requestURI: /influx/0/write/health; unsupported path requested: "/influx/0/write/health"
Jul 16 15:34:57 vicky-test vminsert-prod[94]: 2024-07-16T15:34:57.293Z        warn        VictoriaMetrics/lib/httpserver/httpserver.go:449        remoteAddr: "10.0.0.3:54594"; requestURI: /insert/0/influx//health; unsupported path requested: "/insert/0/influx//health"
Jul 16 15:35:30 vicky-test vminsert-prod[94]: 2024-07-16T15:35:30.698Z        warn        VictoriaMetrics/lib/httpserver/httpserver.go:449        remoteAddr: "10.0.0.2:56652"; requestURI: /insert/0/influx/health; unsupported path requested: "/insert/0/influx/health"
```

### Screenshots

![image](https://github.com/user-attachments/assets/78950ad3-a411-4fd3-affe-ddbb8b37e67d)

**Comment by hagen1778** [comment]
@tiny-pangolin support of `/influx/health` endpoint was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6749 and will be included into the next release.
