### ISSUE TITLE
How to assert the VM cluster is deploy succeed?

### ISSUE THREAD

**Issue by IsQiao** [VictoriaMetrics/VictoriaMetrics#6655]
### Is your question request related to a specific component?

I deployed to two vmstorage instances in cluster, then i want to check the deployment is succeed.

### Describe the question in detail

Is there any API to query all connected storage nodes information? like vmagent service discoverty WebUI.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by IsQiao** [comment]
i found a temp solution, call `vmselect/metrics` route, the 'vm_rpc_vmstorage_is_reachable‘ can assert the storage node is connected.
is there any other way? thanks! 😊

**Comment by jiekun** [comment]
Hi. 
> check the deployment is succeed
I think it's all depends on the reason you need this information.

For example, you could send request to `http://vmstorage:8482/health` to see if it's running. The metrics you mention could help, too.

However, there might be many other things to affect the health status of vmstorage instances. It would be nice to have a Grafana dashboard of VMCluster so that you could visualize some important metrics of vmstorage/other components.

https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/

**Comment by IsQiao** [comment]
Thanks a lot,  request to `http://vmstorage:8482/health` can check vmstorage is ready, But it can't check that all component configurations are successful. like
* Which vmstorage is connected to vminsert? 
* Which vmstorage is connected to vmselect?
* Is vmui connected to a directly connected vmselect or a connected load balancer?

**Comment by jiekun** [comment]
> - Which vmstorage is connected to vminsert?
> - Which vmstorage is connected to vmselect?

AFAIK, those info are not available on UI now. I think you need the dashboard I mentioned above. And the connections between each component are allowed to go down at any time. You cannot assert that the vmcluster is NOT healthy when one of your vmselect/vminsert instances is not available.

> - Is vmui connected to a directly connected vmselect or a connected load balancer?

I don't think vmui should aware info like this.

**Comment by IsQiao** [comment]
The component is currently in a healthy state and cannot be asserted that the cluster is successfully configured. There may be some problems in the cluster. For example, in some network environments, even if the configuration is successful and in a healthy state, there may be cases where other components cannot be connected, such as authentication failure and other reasons.

**Comment by IsQiao** [comment]
> > * Which vmstorage is connected to vminsert?
> > * Which vmstorage is connected to vmselect?
> 
> AFAIK, those info are not available on UI now. I think you need the dashboard I mentioned above. And the connections between each component are allowed to go down at any time. You cannot assert that the vmcluster is NOT healthy when one of your vmselect/vminsert instances is not available.
> 
> > * Is vmui connected to a directly connected vmselect or a connected load balancer?
> 
> I don't think vmui should aware info like this.

In my usage scenario, the software is a SaaS, grafana is not a required component, so the delivery person to deploy grafana to check if the cluster is healthy is not very realistic.

The component is currently in a healthy state and cannot be asserted that the cluster is successfully configured. There may be some problems in the cluster. For example, in some network environments, even if the configuration is successful and in a healthy state, there may be cases where other components cannot be connected, such as authentication failure and other reasons.

Ok, i will to check component connections by metric `vm_rpc_vmstorage_is_reachable`.

**Comment by jiekun** [comment]
> In my usage scenario, the software is a SaaS, grafana is not a required component, so the delivery person to deploy grafana to check if the cluster is healthy is not very realistic.

I agree. I am going to update our docs or blog post to introduce some important metrics, which might be useful for your case.

I'm going to close this issue as complete now. Feel free to re-open it if you have more questions.
