### ISSUE TITLE
[Feature Request] add vmctl binary

### ISSUE THREAD

**Issue by patsevanton** [VictoriaMetrics/VictoriaMetrics#666]
Hello!
Thanks for VictoriaMetrics!
druchoo create issue for vmctl rpm packages.
https://github.com/patsevanton/victoriametrics-rpm/issues/2

Please create/add vmctl binary.

**Comment by valyala** [comment]
The feature request has been moved to https://github.com/VictoriaMetrics/vmctl/issues/20
