### ISSUE TITLE
 Streaming aggregation have concepts similar to event time, ingestion time, and processing time as seen in Apache Flink?

### ISSUE THREAD

**Issue by smallyao** [VictoriaMetrics/VictoriaMetrics#6662]
### Is your question request related to a specific component?

Victorialmetics、vmagent、vmstore

### Describe the question in detail

1 Does VictoriaMetrics' streaming aggregation have concepts similar to event time, ingestion time, and processing time as seen in Apache Flink? 
2 The parameter retentionPeriod  of vmstore is based on which time for data rolling? What if there is a significant difference between event time and the time data is stored?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @smallyao 

> 1 Does VictoriaMetrics' streaming aggregation have concepts similar to event time, ingestion time, and processing time as seen in Apache Flink?

No, VictoriaMetrics only stores one timestamp associated with each sample.
When metrics are gathered via scraping this timestamp will be the time of scrape. In case metrics are being pushed to VictoriaMetrics timestamp is set to ingestion time.

>  2 The parameter retentionPeriod of vmstore is based on which time for data rolling? What if there is a significant difference between event time and the time data is stored?

Since there is only one timestamp representing point in time when sample was created `retentionPeriod` is using this time when enforcing retention.

**Comment by smallyao** [comment]
@zekker6  Got it. Thanks.

**Comment by smallyao** [comment]
Consider a scenario , suppose the metrics reside in Kafka, and a program consumes this data from Kafka, processes it, and subsequently pushes it to VictoriaMetrics, the retention period in vmstore is set to 1 day.

In a situation where, due to some issue such as the consumer program malfunctioning, the data from Kafka is consumed and processed after a delay of 1 day, this data would be considered expired by the time it reaches vmstore?

How VictoriaMetrics would handle such expired data? Discard it? What can i do if i want it to still contribute to streaming aggregation operations?

Thanks in advande @zekker6

**Comment by zekker6** [comment]
> Consider a scenario , suppose the metrics reside in Kafka, and a program consumes this data from Kafka, processes it, and subsequently pushes it to VictoriaMetrics, the retention period in vmstore is set to 1 day.
> In a situation where, due to some issue such as the consumer program malfunctioning, the data from Kafka is consumed and processed after a delay of 1 day, this data would be considered expired by the time it reaches vmstore?

This will depend on timestamps which are set by consumer. If consumer will keep original timestamps which are 1 before now - vmstorage will reject these samples. If a consumer sets timestamps to a current time (which usually happens with a push model) than vmstorage will accept the samples.

> How VictoriaMetrics would handle such expired data? Discard it? What can i do if i want it to still contribute to streaming aggregation operations?

vmstorage does discard such samples. Streaming aggregation however can be configured to keep samples which are outside of retention, see these docs - https://docs.victoriametrics.com/stream-aggregation/#ignoring-old-samples

**Comment by smallyao** [comment]
Thank you for your patient explanation. So, can I understand that expired data is, by default, still aggregated during streaming aggregation, but is then rejected by vmstore when receive it

**Comment by zekker6** [comment]
> So, can I understand that expired data is, by default, still aggregated during streaming aggregation, but is then rejected by vmstore when receive it

By default, the data will be aggregated by streaming aggregation and an aggregated datapoint will use a timestamp of state flush.

**Comment by hagen1778** [comment]
Closing as answered.
