### ISSUE TITLE
VMUI for Logs: improvements in table view

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6668]
### Describe the solution you'd like

We need to add the next features to Table Settings
- select all
- unselect all
- search by field name (frontend only)

https://play-vmlogs.victoriametrics.com/select/vmui/#/?query=*&g0.range_input=1y&g0.end_input=2024-07-18T13%3A20%3A27&g0.relative_time=last_1_year&view=table
<img width="261" alt="Screenshot 2024-07-18 at 15 20 39" src="https://github.com/user-attachments/assets/82ab0633-2d55-461f-809c-699d02ac0314">

**Comment by hagen1778** [comment]
@Loori-R do we have plans to implement search field?

**Comment by Loori-R** [comment]
Yes, I'm currently working on it.

**Comment by hagen1778** [comment]
@tenmozes search functionality for columns in table settings was added in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6804 and will be available in the next vlogs release.

Functionality to select/deselect/filter columns in table settings will be also available in vmui.

**Comment by tenmozes** [comment]
amazing thank you!

**Comment by valyala** [comment]
The functionality to select/deselect and filter columns it table view is available in VictoriaLogs starting from [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) release. Closing the feature request as done.
