### ISSUE TITLE
make possible send VMProto packets to kafka

### ISSUE THREAD

**Issue by proffust** [VictoriaMetrics/VictoriaMetrics#6670]
### Is your feature request related to a problem? Please describe

I can't use VMProto when use kafka, but I read data from kafka with vmagent and write data to kafka with vmagent

### Describe the solution you'd like

change behaviour flag remoteWrite.forceVMProto when as remote write use kafka, now vmproto not enable, if remote write(kafka) not support it

**Comment by jiekun** [comment]
Hi. I'm verifying this enhancement (or it could be a question about an existing feature) in internal discussion. I will get back to you asap.

**Comment by jiekun** [comment]
@proffust Hi. After checking I think this feature is available already.

- For the producer side: set `-remoteWrite.forceVMProto=true`
- For the consumer side: set `-kafka.consumer.topic.format=promremotewrite`

Feel free to provide feedback if you continue to experience any issues.
