### ISSUE TITLE
Why is there a delay of approximately 30 seconds in the data results queried from VMS?

### ISSUE THREAD

**Issue by CoderX-Aaron** [VictoriaMetrics/VictoriaMetrics#6672]
### Is your question request related to a specific component?

vmselect，vmstorage，vminsert

### Describe the question in detail

I am writing the same metrics data to both Prometheus and the write interface of VMinsert through Pushgateway simultaneously for storage. However, when querying, I found that there is a 30-second delay in the results plotted from VMinsert compared to querying from Prometheus using the same PromQL. This 30-second delay is shown as a smooth straight line in the line chart. What could be the reason for this? Below is the PromQL statement：
```
sum(increase(nginx_requests{port='80'}[1m]))/60
```
![image](https://github.com/user-attachments/assets/a6f4cdd1-538d-4968-a9cf-cb069669936b)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi @CoderX-Aaron 

It could be caused by many reason, such as slow insert in victoriametrics side, pending queue in scrape agent side(prom agent / vmagent / ...).

Could you check the health status of those components? For example you could check the slow insert of vm by:
```
max(
    rate(vm_slow_row_inserts_total{job=~"$job_storage"}[$__rate_interval]) 
    / rate(vm_rows_added_to_storage_total{job=~"$job_storage"}[$__rate_interval])
)
```

If you want to visualize those metrics easily, please also consider setting dashboard for vm: https://grafana.com/orgs/victoriametrics/dashboards

On the other hand, checking the (cpu / memory / ...) resource usage of vm components would be helpful.

**Comment by CoderX-Aaron** [comment]
> Hi @CoderX-Aaron
> 
> It could be caused by many reason, such as slow insert in victoriametrics side, pending queue in scrape agent side(prom agent / vmagent / ...).
> 
> Could you check the health status of those components? For example you could check the slow insert of vm by:
> 
> ```
> max(
>     rate(vm_slow_row_inserts_total{job=~"$job_storage"}[$__rate_interval]) 
>     / rate(vm_rows_added_to_storage_total{job=~"$job_storage"}[$__rate_interval])
> )
> ```
> 
> If you want to visualize those metrics easily, please also consider setting dashboard for vm: https://grafana.com/orgs/victoriametrics/dashboards
> 
> On the other hand, checking the (cpu / memory / ...) resource usage of vm components would be helpful.

Hi， @jiekun 
I can now confirm that it is not a performance issue. I directly queried the data for relevant metrics, and the timestamp information in the JSON results did not have any delay. I also compared it with another independent vms cluster, which directly uses vmagent to collect data. The data volume is not large, but there is still a 30-second delay when drawing the graphs. I wonder if this is related to the promql statement. Should I rewrite it using metricsql? I haven't finished reading the metricsql documentation yet, so I'm not sure if this is the problem.

**Comment by jiekun** [comment]
Thank you so much for the extra info.

I tried similar query but can't see flat result for the last min.

There is an `export query` button on VMUI. Could you export your raw data (like `nginx_requests`) and paste it here. I am more than happy to help debugging it.

![image](https://github.com/user-attachments/assets/01e53f7a-8d3a-479f-91cc-a6e69b333fc1)

**Comment by CoderX-Aaron** [comment]
@jiekun here is the report file
[vmui_report_2024-07-19_072708.json](https://github.com/user-attachments/files/16307690/vmui_report_2024-07-19_072708.json)

**Comment by CoderX-Aaron** [comment]
@jiekun There is another question I would like to ask. If the delay in writing data is due to performance issues, then when drawing the graph, if there is no data at certain points, shouldn't the line chart for that area be empty? Why is it showing as a straight line instead?

**Comment by CoderX-Aaron** [comment]
@jiekun I would like to ask, what does the result of this query specifically represent, how is slow_insert determined, is it when the insert component receives data and the delay in inserting it into storage exceeds a certain threshold?
```
max(
    rate(vm_slow_row_inserts_total{job=~"$job_storage"}[$__rate_interval]) 
    / rate(vm_rows_added_to_storage_total{job=~"$job_storage"}[$__rate_interval])
)
```
I have collected monitoring information for the insert component, which shows that the value of slow_insert exceeds 1%, but I don't understand what this specifically means.

![image](https://github.com/user-attachments/assets/d6bac46b-7612-4887-b3ad-7810d1cd8d0d)

**Comment by CoderX-Aaron** [comment]
I have resolved the issue, which was caused by the -search.latencyOffset parameter. The default value of this parameter has now been modified.
