### ISSUE TITLE
The same query shows is different between the VictoriaMetrics UI graph and the Prometheus graph

### ISSUE THREAD

**Issue by YL-Zhang1** [VictoriaMetrics/VictoriaMetrics#6673]
### Describe the question in detail

When I was conducting a data query, I found that the UI display in VictoriaMetrics was inconsistent with Prometheus. I would like to know the reason for this and how I can solve it
<img width="963" alt="VictoriaMetrics" src="https://github.com/user-attachments/assets/042edec7-448c-4077-9f0f-0488f629d51b">
<img width="940" alt="prometheus" src="https://github.com/user-attachments/assets/ca3b7abe-6f69-4f2e-a84c-e7d1fa05535a">

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
@YL-Zhang1 Hi thanks for the question.

Could you switch to the **Table** tab so that you could see the result in timestamp-value table format?

In this way you could better observe the data between prometheus instance and victoriametrics instance. Does data point identical in both instances?

If yes, then it's all about the graph UI. If no, it might be caused by different data ingestion / deduplication / scrape interval / ... and we could discuss about it.

Please add more comments if you found something strange.

**Comment by jiekun** [comment]
BTW I think this comment may help with your case, please check it too:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3018#issuecomment-1227140193

**Comment by YL-Zhang1** [comment]
@jiekun Thank you for yourreply。this question caused by different  scrape interval。
but  scrape interval is not allow edit。
![Uploading 企业微信截图_17216371024869.png…]()

**Comment by YL-Zhang1** [comment]
@jiekun Thank you for yourreply。this question caused by different  scrape interval。
but  scrape interval is not allow edit。
<img width="960" alt="企业微信截图_17216371024869" src="https://github.com/user-attachments/assets/d7afb294-70d0-4326-a23f-b2bbb7aa64d1">

**Comment by jiekun** [comment]
@YL-Zhang1 Hi. I'm not sure about what you're going to express by the screenshot.

> this question caused by different scrape interval

By this you mean the Prometheus and VictoriaMetrics store data that scraped with different intervals? So it would be great if you could align them before doing comparison.

> but scrape interval is not allow edit

I believe the scrape interval is fully configurable. Please let me know how you configure the Scrape Job. Additionally, please refer to [the vmagent document](https://docs.victoriametrics.com/vmagent/) to learn how to modify the scrape interval.

```go
scrape_configs:
- job_name: foo
  scrape_interval: 1m
```
