### ISSUE TITLE
how to drop metris during scrape with specific value

### ISSUE THREAD

**Issue by leiwingqueen** [VictoriaMetrics/VictoriaMetrics#6687]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

how to drop metris during scrape with specific value, for example.
```json
http_requests_total{job="prometheus",group="canary"} with value=100
http_requests_total{job="prometheus",group="canary"} with value=0
```
I need to drop the value<=0 because in most case the metrics value is zero. How can I config. I have already read the docs in victoriametrics and still can not find any answer.

[how to drop metris during scrape](https://docs.victoriametrics.com/relabeling/#how-to-drop-metrics-during-scrape)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Is it possible for you to filter them by query? like:

http_requests_total{job="prometheus",group="canary"} >= 0

I think you cannot do it by relabeling rule on vmagent.🤔

Also, this metric seems to be an counter who could be increased only. Why value<0 is recorded?

**Comment by leiwingqueen** [comment]
> Hi. Is it possible for you to filter them by query? like:
> 
> http_requests_total{job="prometheus",group="canary"} >= 0
> 
> I think you cannot do it by relabeling rule on vmagent.🤔
> 
> Also, this metric seems to be an counter who could be increased only. Why value<0 is recorded?

thanks for reply. I want to drop value==0 and keep the value>0. I need to drop  the metric which value equals zero to speed up query in alert manager(for the reason that I only concern about the metric value bigger than zero)

**Comment by jiekun** [comment]
@leiwingqueen I think it's impossible as relabeling rule is focus on label and label value, not the value of a time series. 🤔

**Comment by leiwingqueen** [comment]
> @leiwingqueen I think it's impossible as relabeling rule is focus on label and label value, not the value of a time series. 🤔

thanks, maybe there is another way to solve this problem.
