### ISSUE TITLE
Cannot decompress request with length: snappy: corrupt input

### ISSUE THREAD

**Issue by Adverg** [VictoriaMetrics/VictoriaMetrics#670]
Running the [docker-compose](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml) you provided with `docker-compose up` and then sending GZip compressed `openstdb` metrics in Prometheus format via API endpoint `api/v1/write` the following error is appeared in the log output:

```
victoriametrics    | 2020-08-04T22:53:19.061Z   warn    VictoriaMetrics/app/vminsert/main.go:95 
remoteAddr: "172.18.0.1:39540"; error in "/api/v1/write": cannot read prompb.WriteRequest: 
cannot decompress request with length 1405: snappy: corrupt input 
```
and therefore no metrics are actually stored.

Do you have any idea about the root cause of the issue? Maybe some extra config option is required or so?

**Comment by valyala** [comment]
The `/api/v1/write` endpoint accepts data in [Prometheus remote_write protocol](https://prometheus.io/docs/prometheus/latest/storage/#remote-storage-integrations). OpenTSDB data must be sent to another endpoint configured with `-opentsdbListenAddr` or `-opentsdbHTTPListenAddr` command-line flags - see the following docs for details:

* [sending OpenTSDB data via telnet put protocol](https://victoriametrics.github.io/#sending-data-via-telnet-put-protocol)
* [sending OpenTSDB data via /api/put endpoint](https://victoriametrics.github.io/#sending-opentsdb-data-via-http-apiput-requests)
