### ISSUE TITLE
set higher vm_allowed_memory_bytes but vmstorage have small vm_cache_size_bytes in type "storage/tsid"

### ISSUE THREAD

**Issue by zhengyingsdu** [VictoriaMetrics/VictoriaMetrics#6701]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

I set a higher cache by using the parameter - "-memory.allowedPercent=60",however the cache vm_cache_size_bytes of the type “storage/tsid” has become smaller. On the contrary, I set a small cache usage -memory.allowedPercent=40 and  vm_cache_size_bytes in type "storage/tsid" became larger, which cause vmstorage with very high memory usage and slow insert and select occur at the same time, i wanna know why?
![image](https://github.com/user-attachments/assets/96ffab95-ddff-4a29-8e20-16f09486e61e)
![image](https://github.com/user-attachments/assets/0e107199-3aa5-4501-8fba-788f4caa6dc8)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Based on the codes, max TSID cache size could be configured by flag `storage.cacheSizeStorageTSID`. If it's NOT set by flag, it will use 37% of allowed memory (which is controlled by your total memory and `memory.allowedPercent`).

Could you provide more information, like:
- How many memory you are using in total?
- Does 3TB memory of TSID Cache match the expected amount of memory (e.g. `total memory * 40% * 37%`)?
- Any other flags you are using that affects the memory/cache?

**Comment by zhengyingsdu** [comment]
> Hi. Based on the codes, max TSID cache size could be configured by flag `storage.cacheSizeStorageTSID`. If it's NOT set by flag, it will use 37% of allowed memory (which is controlled by your total memory and `memory.allowedPercent`).
> 
> Could you provide more information, like:
> 
> * How many memory you are using in total?
> * Does 3TB memory of TSID Cache match the expected amount of memory (e.g. `total memory * 40% * 37%`)?
> * Any other flags you are using that affects the memory/cache?

thank you for the reply!

**Comment by zhengyingsdu** [comment]
> Hi. Based on the codes, max TSID cache size could be configured by flag `storage.cacheSizeStorageTSID`. If it's NOT set by flag, it will use 37% of allowed memory (which is controlled by your total memory and `memory.allowedPercent`).
> 
> Could you provide more information, like:
> 
> * How many memory you are using in total?
> * Does 3TB memory of TSID Cache match the expected amount of memory (e.g. `total memory * 40% * 37%`)?
> * Any other flags you are using that affects the memory/cache?

thank you for the reply!
1.we are setting 522GB memory per instance, and we set the "memory.allowedPercent=40",which means the the allowed memory(vm_allowed_memory_bytes) of every instance is about 209GB.
2.Now the total TSID Cache of 10 instances is 719GB,  as you say,  the expected amount of TSID Cache can be calculated by 522 * 10 * 40% * 37% = 772.5GB, which is similar to the actual value 719GB. But when we set "memory.allowedPercent=60",the  expected amount of TSID Cache should be  522 * 10 * 60% * 37% = 1.13TB，however the actual value from the monitoring dashboard is 663GB, which is lower than we set memory.allowedPercent=40, i think if we don't set other flags, then the TSID cache should be proportional to the allowed memory, right? if the allowed memory increased, the TSID cache should increased too. In our case, it's actually the reverse.
3.no, for the component vmstorage, we only set the flags as below.
  - "-retentionPeriod=31d"
  - "-storageDataPath=/data"
  - "-memory.allowedPercent=40" 
![image](https://github.com/user-attachments/assets/855b8e5b-dbe7-4f75-ba98-ded1a77c365f)

**Comment by zhengyingsdu** [comment]
> Hi. Based on the codes, max TSID cache size could be configured by flag `storage.cacheSizeStorageTSID`. If it's NOT set by flag, it will use 37% of allowed memory (which is controlled by your total memory and `memory.allowedPercent`).
> 
> Could you provide more information, like:
> 
> * How many memory you are using in total?
> * Does 3TB memory of TSID Cache match the expected amount of memory (e.g. `total memory * 40% * 37%`)?
> * Any other flags you are using that affects the memory/cache?

and can we speak Chinese ~

**Comment by jiekun** [comment]
Could you also share the `Cache Usage %` graph, which should be available on Grafana dashboard as well, or using the following MetricsQL:
```
max(
    vm_cache_size_bytes{job=~"$job", instance=~"$instance"} 
    /
    vm_cache_size_max_bytes{job=~"$job", instance=~"$instance"}
) by(type)
```

> the expected amount of TSID Cache can be calculated by 522 * 10 * 40% * 37% = 772.5GB, which is similar to the actual value 719GB.

So when setting cache to `40%`, the resource usage is close to the expectation. I think we should try to figure out what happen when setting cache to `60%`. For example, does `storage/tsid` is 100% used? What's the value of `vm_cache_size_max_bytes` and `vm_cache_size_bytes`  for `storage/tsid`?

**Comment by zhengyingsdu** [comment]
> Could you also share the `Cache Usage %` graph, which should be available on Grafana dashboard as well, or using the following MetricsQL:
> 
> ```
> max(
>     vm_cache_size_bytes{job=~"$job", instance=~"$instance"} 
>     /
>     vm_cache_size_max_bytes{job=~"$job", instance=~"$instance"}
> ) by(type)
> ```
> 
![image](https://github.com/user-attachments/assets/f3eef6f8-9898-404e-9a98-a41b937159ea)
![image](https://github.com/user-attachments/assets/bd7039d8-ff90-4502-9010-578111067aa3)
sure, here is the graph, we can see the usage of TSID Cache  is almost 10%.
> 
> So when setting cache to `40%`, the resource usage is close to the expectation. I think we should try to figure out what happen when setting cache to `60%`. For example, does `storage/tsid` is 100% used? What's the value of `vm_cache_size_max_bytes` and `vm_cache_size_bytes` for `storage/tsid`?
> 
The `storage/tsid` is not 100% used, but our active series is almost steady, i don't know why the usage of storage/tsid  cache reduced.
![image](https://github.com/user-attachments/assets/df669b74-ef2e-4ecc-b4a7-eb827238fad7)
> 
As for the value of `vm_cache_size_max_bytes` and `vm_cache_size_bytes` for `storage/tsid`?
when set the  cache to `40%`,the value of `vm_cache_size_max_bytes` and `vm_cache_size_bytes` are both 719GB , indicate that `storage/tsid` is 100% used. when set the  cache to `60%`,the value of `vm_cache_size_max_bytes` is 1.05T, but the vm_cache_size_bytes is below 100GB.
![image](https://github.com/user-attachments/assets/56d9413f-e7c2-45b1-ac49-a5d9d13047ef)

**Comment by jiekun** [comment]
Hi it will take me some times to validate. I'm not sure if it's related, but there is a `mode` field for the cache. See: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d845edc24b0eae5d24466ce1d30d09c3b6fb0b37/lib/workingsetcache/cache.go#L46

Please expect my response in up-comming days. At the same time, it would be great if you could try other `allowedPercent` setting with your setup and see what will be different.

**Comment by jiekun** [comment]
@zhengyingsdu Here's one possibility.

The cache could work in different `mode`: `split` mode and `whole` mode.

For `split` mode, cache has chance to expire, swap and memory could be released. See: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d845edc24b0eae5d24466ce1d30d09c3b6fb0b37/lib/workingsetcache/cache.go#L135
For `whole` mode, cache use all space and never release them. See: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d845edc24b0eae5d24466ce1d30d09c3b6fb0b37/lib/workingsetcache/cache.go#L218

The mode switching happens when cache is using more than 50% of space (of `allowPercent`). If you set `allowedPercent` to 40%, and somehow experience a churn rate spike, the memory usage exceed 50% of it cap, it will transit to `whole` mode and use 100% of space (719GB in your case)

And when you set the `allowPercent` to 60% (e.g. 600G of 1000G), if the actual cache size never exceed 50% of it (300G), it will stay at `split` mode. Once churn rate spike happens again, it may transit to `whole` mode and use all memory (600G).

**Comment by zhengyingsdu** [comment]
> @zhengyingsdu Here's one possibility.
> 
> The cache could work in different `mode`: `split` mode and `whole` mode.
> 
> For `split` mode, cache has chance to expire, swap and memory could be released. See:
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d845edc24b0eae5d24466ce1d30d09c3b6fb0b37/lib/workingsetcache/cache.go#L135
> 
> 
> For `whole` mode, cache use all space and never release them. See:
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d845edc24b0eae5d24466ce1d30d09c3b6fb0b37/lib/workingsetcache/cache.go#L218
> 
> The mode switching happens when cache is using more than 50% of space (of `allowPercent`). If you set `allowedPercent` to 40%, and somehow experience a churn rate spike, the memory usage exceed 50% of it cap, it will transit to `whole` mode and use 100% of space (719GB in your case)
> 
> And when you set the `allowPercent` to 60% (e.g. 600G of 1000G), if the actual cache size never exceed 50% of it (300G), it will stay at `split` mode. Once churn rate spike happens again, it may transit to `whole` mode and use all memory (600G).

Thanks a lot, this gave me some inspiration, I'll verify it. Is there any prometheus metric that can capture the mode switch, I can't find it in the code.

**Comment by jiekun** [comment]
I don't think the `Cache` provides related metrics. You could add one and build the image from source.

**Comment by jiekun** [comment]
Hi. Has this issue resolved?

**Comment by zhengyingsdu** [comment]
> Hi. Has this issue resolved?

Yep, we have resolved this issue, thanks~
