### ISSUE TITLE
Add Alerting and recording rules to Victorialogs

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#6704]
### Is your feature request related to a problem? Please describe

I would like the ability to generate metrics from logs like the number of errored requrests from an access log and alert on certain logs messages like windows defender detected a virus.  

### Describe the solution you'd like

I would like the ability in vmalert or a similar utility to generate metrics and alerts from logsql queries from victorialogs.

### Describe alternatives you've considered

I believe this can be achieved using the logsql api and the ingestion protocols in victoriametrics but I think this feature should be apart of victoriametrics and not something users have to write for themselves.

**Comment by Haleygo** [comment]
Closing this as dup, please follow https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6706.
