### ISSUE TITLE
vmalert: add support for alerting on LogsQL queries for VictoriaLogs

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#6706]
### Is your feature request related to a problem? Please describe

[VictoriaLogs](https://docs.victoriametrics.com/victorialogs/) provides [HTTP API](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs) for querying the ingested logs with [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/). Sometimes it is convenient building alerts on logs. For example, alerting when the percentage of per-[stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) logs with the `error` level over the last 5 minutes exceeds 1%. This can be done with the LogsQL query:

```logsql
_time:5m
  | stats by (_stream)
      count() if (level:error) as errors,
      count() as total
  | math errors / total as errors_percentage
  | filter errors_percentage :> 0.01
```

### Describe the solution you'd like

It would be great if [vmalert](https://docs.victoriametrics.com/vmalert/) will support executing the configured [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) alerting rules at the configured [VictoriaLogs](https://docs.victoriametrics.com/victorialogs/) data source.

### Describe alternatives you've considered

To use custom cron jobs with bash scripts, which use curl for periodic execution of alerting queries at VictoriaLogs.

### Additional information

We need figuring out the most simple yet convenient way to configure alerts for VictoriaLogs data source in vmalert.

This feature request has high priority because it is essential for VictoriaLogs adoption. See [VictoriaLogs roadmap](https://docs.victoriametrics.com/victorialogs/roadmap/).

**Comment by jiekun** [comment]
Similar enhancement issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6704

**Comment by Haleygo** [comment]
I think we can also put recording rule into consideration here. Expr like
```
_time:5m
  | stats by (_stream)
    count() if (level:error) as errors,
    count() as total
  | math errors / total as errors_percentage
  | filter errors_percentage > 0.01

## reponse
{
    "_stream": "{path=\"/var/lib/docker/containers/1d683ee6d58fdfedbef-json.log\",stream=\"stdout\"}",
    "path": "/var/lib/docker/containers/fedbef-json.log",
    "errors": "121",
    "total": "191",
    "errors_percentage": "0.6335078534031413"
}
``` 
can serve as either an alerting or recording rule.
As alerting rule, it should use fields `_stream, path, errors, total` as alert’s properties to allow [templating](https://docs.victoriametrics.com/vmalert/#templating) in rule’s annotations, and `errors_percentage` as the [alert state value](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d53dd6ecf3a68e3120f44bb7d4574682cd171807/app/vmalert/notifier/alert.go#L44).
As recording rule, it should use fields `_stream, path, errors, total` as result's properties to generate timeseries as `error_percentage{fields _stream="xx", path="xx", errors="121", total="191"} 0.633507` and store it to remote storage.

However, there are two questions need to be address first:
1. **Rule validation**: Both alerting and recording rules require the query to return numerical results, so the expr must generates at least one numerical result with the [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe).
2. **Extract value from the response**:
2.1. **For alerting rule**: The generated alert message must contain a single value to indicate the current stats, but vmalert can’t understand the results now as there could be multiple filters and the response returns all the fields together. e.g
```
   ## with expr with two filters, which value should be the alert state
_time:5m
  | stats by (_stream,path)
    count() if (level=error) as errors,
    count() as total
  | math errors / total as errors_percentage
  | filter errors_percentage :>0
  | filter total :>100

## response
{
...
    "errors": "121",
    "total": "191",
    "errors_percentage": "0.6335078534031413"
}
```
   2.2. **For recording rule**: LogsQL also supports computing multiple stats in single query, e.g

```
_time:5m  
| stats by (_stream,path)  
  count() if (level=error) as errors,  
  count() as total  
```
Should we allow generating two timeseries for this rule, or we will only allow one series per rule?

----
I think adding those validations in vmalert makes the code complicated and detracts from its main purpose. 
How about introducing an additional [query API ](https://docs.victoriametrics.com/victorialogs/querying/#http-api)in VictoriaLogs like `/select/logsql/query/metric` to validate queries and translate responses to VictoriaMetrics style with explicit properties and values?
cc @valyala @hagen1778

**Comment by Haleygo** [comment]
>Probably, the new API handler at VictoriaLogs should accept an optional query arg - metric_fields - with the list of fields, which must be returned as metric values. If multiple fields are specified, then multiple metrics with the same set of labels will be returned by this handler .

Sounds good. 
It can ensure vmalert knows which value to use as rule state. Even if `metric_fields` is not specified by users, VictoriaLogs should pick fileld from the `query` as default `metric_fields`.

>Any returned field may have arbitrary number of unique values. This may result in high cardinality issues if such fields will be stored as metric labels into VictoriaMetrics.

VictoriaMetrics faces the same issue when the query matches too many series, we can have limits on both VictoriaLogs API and rule [group](https://docs.victoriametrics.com/vmalert/#groups) side.
```
# Limit limits the number of alerts or recording results the rule within this group can produce.
# On exceeding the limit, rule will be marked with an error and all its results will be discarded.
# 0 is no limit.
[ limit: <integer> | default 0]
```

**Comment by hagen1778** [comment]
@valyala @Haleygo why can't we use existing https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats API instead? It looks very similar to /query API in VM/Prometheus - returns numeric values and list of related fields. From vmalert perspective we only need to make sure to receive one timestamp-value pair per each unique fields combination, to make it look like [instant query](https://docs.victoriametrics.com/keyconcepts/#instant-query).

**Comment by Haleygo** [comment]
> @valyala @Haleygo why can't we use existing https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats API instead? It looks very similar to /query_range API in VM/Prometheus: it returns numeric values and list of related fields. From vmalert perspective we only need to make sure to receive one timestamp-value pair per each unique fields combination, to make it look like [instant query](https://docs.victoriametrics.com/keyconcepts/#instant-query).

[Hits stats API](https://docs.victoriametrics.com/victorialogs/querying/#querying-hits-stats) only returns the number of matching log entries, but drops all the pipes. So if you query
```
_time:5m
  | stats by (_stream)
      count() if (level:error) as errors,
      count() as total
  | math errors / total as errors_percentage
  | filter errors_percentage :> 0.01
```
the result is the same as `_time:5m`.

**Comment by hagen1778** [comment]
> I'd name this new API handler as /select/logsql/stats_query, in order to signify the need to use [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe) in the query passed to this handler.

Looks like eventually we should add `/select/logsql/stats_query_range` with support of `start`, `end` and `step` params. It will serve the same purpose as  `/select/logsql/stats_query` but will mimic /query_range behavior. Such endpoint will be useful for integrating with Grafana datasource (to support time series panel) and for backfilling recording rules via vmalert.

**Comment by hagen1778** [comment]
@Haleygo please see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6942 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6943

**Comment by valyala** [comment]
FYI, the `/select/logsql/stats_query` endpoint for VictoriaLogs has been added in the commit c9bb4ddeed6f6e8463bab9854b4565d7f788719a . See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-stats) for details.

So, it is time to implement alerting and recording rules at [vmalert](https://docs.victoriametrics.com/vmalert/) side on top of this endpoint.

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7255 was merged and will be added to the next VictoriaMetrics release.

**Comment by zekker6** [comment]
Support of VictoriaLogs datasource was added in release [v1.106.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.106.0), closing feature request as completed.
