### ISSUE TITLE
label_replace() does not fail for invalid target labels

### ISSUE THREAD

**Issue by juliusv** [VictoriaMetrics/VictoriaMetrics#672]
**Describe the bug**
Native PromQL notices invalid target labels in queries like `label_replace(foo, "~invalid", "", "src", "(.*)")` and returns a query error. VictoriaMetrics does not fail for this.

**To Reproduce**
Run `label_replace()` as described above.

**Expected behavior**
The query should fail with an error.

**Version**

```
$ ./victoria-metrics-prod --version
victoria-metrics-20200727-204526-tags-v1.39.1-0-g5b81bdde3
```

**Comment by valyala** [comment]
VictoriaMetrics supports arbitrary chars in label names and label values, so this looks like valid query. Note that VictoriaMetrics supports escaping special chars with backslashes. See more details at [MetricsQL docs](https://victoriametrics.github.io/MetricsQL.html). For instance, query may contain a filter on label name `~invalid`: `foo{\~invalid="bar"}`.

Note that VictoriaMetrics accepts data from various sources via [various data ingestion protocols](https://victoriametrics.github.io/#how-to-import-time-series-data) - Influx line protocol, OpenTSDB, Graphite, CSV, JSON lines, Prometheus text exposition format, etc. Some of these systems and/or protocols support arbitrary chars in label names.

**Comment by juliusv** [comment]
Thanks for the explanation! I was suspecting already that this could be intentional, since MetricsQL does more than PromQL.

**Comment by juliusv** [comment]
I'll close this for now. It's still unclear to me how to handle this kind of case in correctness checker tests. If e.g. it was an implementation that just tried to 100% replicate PromQL and not extend it, then it would be important to catch this kind of error (as otherwise you could produce illegal label values that can cause problems in further processing). Perhaps it would make sense to add a flag to a given test case to indicate that a case is not passing due to an extension of the language, rather than a bug, and then list that kind of thing separately somehow.
