### ISSUE TITLE
vminsert upgraded to v1.101.0-cluster, CPU usage increased from 35%  to 100%

### ISSUE THREAD

**Issue by aluode99** [VictoriaMetrics/VictoriaMetrics#6733]
### Describe the bug

after upgrading vminsert to version v1.101.0-cluster, under the same conditions, the CPU usage has increased from 35% to 100%.

before the upgrade, the CPU usage was as follows:
<img width="630" alt="image" src="https://github.com/user-attachments/assets/352d5c36-06fc-4a2d-b2d6-4f50a4392254">

<img width="711" alt="image" src="https://github.com/user-attachments/assets/0f55a4dd-1569-46fa-9fb8-a4d5cdda5cda">

after upgrading to v1.101.0-cluster version, the CPU usage is as follows:
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/020e8e47-4d5e-4aac-b798-1c0c06c6f675">

<img width="713" alt="image" src="https://github.com/user-attachments/assets/95bed385-9562-4758-9d03-790602110b31">

by analyzing pprof, it is suspected that insert_ctx_pool is the cause. Roll insert_ctx_pool back to v1.100.0-cluster, recompile vminsert(v1.101.0-cluster), and CPU usage returns to normal.
<img width="647" alt="image" src="https://github.com/user-attachments/assets/78f4b862-8abd-400d-ac94-215209677158">
<img width="719" alt="image" src="https://github.com/user-attachments/assets/a550d973-99df-45e3-9f25-9253e5e45cc0">
 repeated testing many times, the CPU usage will increase after upgrading to v1.101.0. Only rolling insert_ctx_pool back to v1.100.0 solves the problem.
  should insert_ctx_pool be rolled back to v1.100.0 ?

### To Reproduce

 upgrading vminsert to version v1.101.0-cluster and observe changes in cpu usage.

### Version

 v1.101.0-cluster

**Comment by Sinketsu** [comment]
On `1.102.0` we have the same issue

**Comment by jiekun** [comment]
I'm linking the related commit as it's not mentioned in CHANGELOG.

https://github.com/VictoriaMetrics/VictoriaMetrics/commit/498fe1cfa523be5bfecaa372293c3cded85e75ab

@aluode99 could you provide the pprof result?

**Comment by hagen1778** [comment]
@aluode99 would be also great if you could provide resource requests/limits for your vminsert components.

**Comment by jiekun** [comment]
Trying to reproduce it locally with very simple setup. And here's my profile for `v1.100.0`/`v1.100.0-without-ch`/`v1.101.0`.
[profile.zip](https://github.com/user-attachments/files/16450356/profile.zip)

I did not observe a significant difference in CPU usage (I did not scrape the precise metrics), but I noticed some differences in these profiles in terms of **Total Samples**, which may indicate the difference of CPU usage:
- v1.100.0: ~100%
- v1.101.0 / v1.100.0-without-ch: ~200%

I may need to setup a test env and re-test it again.

**Comment by Sinketsu** [comment]
Hello!
Tell me, please, what is the status of issue now? This blocks us from updating to the latest version. Is there anything I can do to help?
Thanks!

**Comment by jiekun** [comment]
@Sinketsu @aluode99  Hi. I'm running the related version of `vminsert` in our internal cluster to reproduce the issue.

It would be helpful if you could provide the monitor dashboard under `vminsert` (including: Requests rate, Concurrent inserts, CPU usage, Memory usage, Storage connection saturation, Storage reachability, Network usage: clients, Network usage: vmstorage, Row per insert) when running v1.101.0 (or 1.102.0).

Also, please try to capture the [cpu profile](https://docs.victoriametrics.com/cluster-victoriametrics/#profiling).

**Comment by Sinketsu** [comment]
Hello!
We have independent clusters of `vminsert` in different AZ. Different AZ have exactly the same load. So, I deploy `1.97.3` to one AZ and `1.102.0` to another to compare in real time.

Graphs **per one instance of each cluster** (all other instances are similiar):

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/bc0d206e-aef8-45e2-b6c7-b9b17cd6cdda">
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/42b282fe-537e-46ec-9a11-50c8f977c0d8">
<img width="1415" alt="image" src="https://github.com/user-attachments/assets/817e5f59-32bf-46f3-88d0-4f2403c2d346">
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/f8464297-8f0e-4b7f-a49b-4ccc3b40d8b4">
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/9699e780-7ebd-41b5-b296-dab64967d4f5">

pprofs: [pprof.zip](https://github.com/user-attachments/files/16559113/pprof.zip)

**Comment by jiekun** [comment]
@Sinketsu Thank you for the support and feedback. I've also observed similar issues during testing. We are discussing internally and will continue to update progress on this issue.

**Comment by f41gh7** [comment]
Hello, can you please try to provide GOGC=100 env variable to vminsert? 

By default, VictoriaMetrics uses GOGC=30 and it seems, that It could make sync.Pool inefficient for some cases.

**Comment by Sinketsu** [comment]
I set `GOGC=100` on `1.102.0` version.
There are CPU/Mem metrics
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/10e61125-1eca-4e63-b6a4-f91484cd4474">

Cpu has become better (I think it is similiar with 1.97.3). But now memory was increase)

**Comment by hagen1778** [comment]
The change was reverted to the state before v1.101.0 in this PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6794

**Comment by hagen1778** [comment]
This bugfix was included into [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030) and [v1.102.2](https://docs.victoriametrics.com/changelog/#v11022) releases.
