### ISSUE TITLE
vmagent: increased mem usage when scraping big targets since v1.97

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6759]
### Describe the bug

vmagent started to consume more memory when scraping targets with big response body (usually federation) after upgrading to v1.97 or higher.
It is likely related to this [ticket](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5567) and this [change](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/bc7cf4950b5ff1072a33fe58c6bae1184d01068b).

### To Reproduce

Create a target with big response body (try avalanche or big Prometheus server to federate from) and run two instances of vmagent: before v1.97 and after. Observe the difference in memory usage. 
Users report the following observations:
![image](https://github.com/user-attachments/assets/ba6cd95a-10c6-49f8-b822-29170444f69a)

### Version

v1.97+

**Comment by hagen1778** [comment]
Change from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6761 was merged and will be included into the next release. According to tests on [playground](https://play-grafana.victoriametrics.com/) and tests conducted by users this change should produce memory usage reduction when scraping targets with big response body.

**Comment by hagen1778** [comment]
The change was included into [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030) release.

**Comment by just1900** [comment]
@hagen1778 will this fix be back port to the previous lts version like v1.97 or v1.102?
