### ISSUE TITLE
There are alot of " read only 0 bytes" in vmstorage logs per 30 sec

### ISSUE THREAD

**Issue by saclive** [VictoriaMetrics/VictoriaMetrics#676]
**Describe the bug**
There are alot of " read only 0 bytes" in vmstorage logs, as the describe in log file:
Aug  6 14:32:13 vm-24-centos vmstorage-prod: 2020-08-06T06:32:13.047Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:41996": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
Aug  6 14:32:43 vm-24-centos vmstorage-prod: 2020-08-06T06:32:43.769Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:43126": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
Aug  6 14:33:13 vm-24-centos vmstorage-prod: 2020-08-06T06:33:13.991Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:44312": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
Aug  6 14:33:43 vm-24-centos vmstorage-prod: 2020-08-06T06:33:43.397Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:45354": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
Aug  6 14:34:13 vm-24-centos vmstorage-prod: 2020-08-06T06:34:13.785Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:46522": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
Aug  6 14:34:43 vm-24-centos vmstorage-prod: 2020-08-06T06:34:43.337Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:47624": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes
Aug  6 14:35:14 vm-24-centos vmstorage-prod: 2020-08-06T06:35:14.011Z#011error#011VictoriaMetrics/app/vmstorage/transport/server.go:155#011cannot perform vminsert handshake with client "10.1.1.24:48796": cannot read hello: cannot read message with size 11: EOF; read only 0 bytes

**To Reproduce**
There are five vmstorage node which have vminsert and vmselect program. 
each vminsert/vmselect connect with all of the vmstorage.

**Expected behavior**
I found error infomation per 30 seconds in vmstoragelogs  as the above discription

**Screenshots**
![image](https://user-images.githubusercontent.com/69297441/89511399-70134000-d804-11ea-8e07-0a86b7cfc765.png)

**Version**
[root@vm-10-52-centos victoria]# ./vmstorage-prod -version
vmstorage-20200727-210909-tags-v1.39.1-cluster-0-g96bc476e5
[root@vm-10-52-centos victoria]# ./vminsert-prod -version
vminsert-20200727-210856-tags-v1.39.1-cluster-0-g96bc476e5

**need help**
what's the meaning of this log ?Does it mean tcp connection reset?  And can i change tcp keepalive parameter to 15s to avoid this error log?

**Comment by valyala** [comment]
The error message `cannot read hello: cannot read message with size 11: EOF; read only 0 bytes` usually means that somebody other than `vminsert` is trying to connect to `vmstorage` at port 8400 every 30 seconds. The error message contains source IP address for this `somebody` - `10.1.1.24`. This looks like incorrectly set up health checker or something like this. Note that HTTP health checker must connect to port `8482` at `vmstorage` nodes instead of port `8400`. The port `8400` must be used only by `vminsert` nodes. See [these docs](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#monitoring) for details.

**Comment by saclive** [comment]
yes,i think it is the reason.thanks a lot

> The error message cannot read hello: cannot read message with size 11: EOF; read only 0 bytes usually means that somebody other than vminsert is trying to connect to vmstorage at port 8400 every 30 seconds. The error message contains source IP address for this somebody - 10.1.1.24. This looks like incorrectly set up health checker or something like this. Note that HTTP health checker must connect to port 8482 at vmstorage nodes instead of port 8400. The port 8400 must be used only by vminsert nodes. See these docs for details.

**Comment by valyala** [comment]
Then closing the issue.
