### ISSUE TITLE
vmui: UI for vlogs tries to load `dashboards/index.js`

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6764]
### Describe the bug

vmui for VictoriaLogs tries to load `vmui/dashboards/index.js:1` when opened. It throws the error: `Failed to load resource: the server responded with a status of 404 ()`

### To Reproduce

Open https://play-vmlogs.victoriametrics.com/ and check browser console.

### Version

https://docs.victoriametrics.com/victorialogs/changelog/#v0280

**Comment by hagen1778** [comment]
Issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6770 and will be available in the next release.

**Comment by valyala** [comment]
The bugfix for this issue has been included in [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the issue as fixed.
