### ISSUE TITLE
vmagent: allow specifying `-remoteWrite.streamAggr.dropInputLabels` individually per each `-remoteWrite.url`

### ISSUE THREAD

**Issue by Haleygo** [VictoriaMetrics/VictoriaMetrics#6780]
### Describe the bug

[The doc](https://docs.victoriametrics.com/stream-aggregation/#dropping-unneeded-labels) says:
>To specify comma-separated list of label names to drop in -streamAggr.dropInputLabels command-line flag or via -remoteWrite.streamAggr.dropInputLabels individually per each -remoteWrite.url.

But flag `-remoteWrite.streamAggr.dropInputLabels` is a one-dimensional array, there is no way to specify multiple lables for multiple remoteWriteURL.

### To Reproduce

`vmagent -remotewrite.url=a,b -remoteWrite.streamAggr.dropInputLabels=foo1,bar1 ...`

### Version

All the version

**Comment by Haleygo** [comment]
We can change the type of flag `-streamAggr.dropInputLabels` to string, and allow using specific delimiter like `^^` to specify multiple labels like `-streamAggr.dropInputLabels=instance^^job`. [vmalert](https://docs.victoriametrics.com/vmalert/) has the same usage on flags `-datasource.headers`, `-remoteRead.headers`.
In this way, flag `-remoteWrite.streamAggr.dropInputLabels` can still be an array, and the value would be `-remoteWrite.streamAggr.dropInputLabels=instance^^job,cluster`.

**Comment by hagen1778** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6780#issuecomment-2274987553 looks valid to me. Would you like to contribute the fix?

**Comment by hagen1778** [comment]
The bugfix was included in [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040) and [v1.102.4](https://docs.victoriametrics.com/changelog/#v11024). Thanks @Haleygo for fixing it!
