### ISSUE TITLE
Unable to decompress vmutils tar.gz file for the v1.102.1 release inside an LXC container as the uid and gid is too high

### ISSUE THREAD

**Issue by kennethso168** [VictoriaMetrics/VictoriaMetrics#6788]
### Describe the bug

Decompression fails for the vmutils tar.gz v1.102.1 release archive fails on an lxc container as the user and group used is `nik_victoriametrics_com` with id `1029054284`, which is too high for an lxc container (by default with max uid and gid 60000).

```
# tar -tvf vmutils-linux-amd64-v1.102.1.tar.gz --numeric-owner
-rwxr-xr-x 1029054284/1029054284 17159112 2024-08-01 20:55 vmagent-prod
-rwxr-xr-x 1029054284/1029054284 16598312 2024-08-01 20:55 vmalert-prod
-rwxr-xr-x 1029054284/1029054284 24759392 2024-08-01 20:55 vmalert-tool-prod
-rwxr-xr-x 1029054284/1029054284 10701287 2024-08-01 20:55 vmauth-prod
-rwxr-xr-x 1029054284/1029054284 37398320 2024-08-01 20:55 vmbackup-prod
-rwxr-xr-x 1029054284/1029054284 36462353 2024-08-01 20:55 vmrestore-prod
-rwxr-xr-x 1029054284/1029054284 35196600 2024-08-01 20:56 vmctl-prod
```

For the previous version v1.102.0, the id used is `1000` which can be successfully decompressed

```
# tar -tvf vmutils-linux-amd64-v1.102.0.tar.gz --numeric-owner
-rwxr-xr-x 1000/1000  17154632 2024-07-18 02:51 vmagent-prod
-rwxr-xr-x 1000/1000  16597776 2024-07-18 02:52 vmalert-prod
-rwxr-xr-x 1000/1000  24750560 2024-07-18 02:52 vmalert-tool-prod
-rwxr-xr-x 1000/1000  10694382 2024-07-18 02:52 vmauth-prod
-rwxr-xr-x 1000/1000  37384304 2024-07-18 02:52 vmbackup-prod
-rwxr-xr-x 1000/1000  36438819 2024-07-18 02:52 vmrestore-prod
-rwxr-xr-x 1000/1000  35167504 2024-07-18 02:52 vmctl-prod
```

### To Reproduce

```
# wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.102.1/vmutils-linux-amd64-v1.102.1.tar.gz
# tar -xvzf vmutils-linux-amd64-v1.102.1.tar.gz -C /tmp                
vmagent-prod
tar: vmagent-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
vmalert-prod
tar: vmalert-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
vmalert-tool-prod
tar: vmalert-tool-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
vmauth-prod
tar: vmauth-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
vmbackup-prod
tar: vmbackup-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
vmrestore-prod
tar: vmrestore-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
vmctl-prod
tar: vmctl-prod: Cannot change ownership to uid 1029054284, gid 1029054284: Invalid argument
tar: Exiting with failure status due to previous errors
```

Such errors do not exist for the previous v1.102.0 release version
```
# wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.102.0/vmutils-linux-amd64-v1.102.0.tar.gz
# tar -xvzf vmutils-linux-amd64-v1.102.0.tar.gz -C /tmp
vmagent-prod
vmalert-prod
vmalert-tool-prod
vmauth-prod
vmbackup-prod
vmrestore-prod
vmctl-prod
```

The workaround is to add the `--no-same-owner` option to `tar`, which discards the owner and group for the files inside the archive
```
# tar -xvzf vmutils-linux-amd64-v1.102.1.tar.gz -C /tmp --no-same-owner
vmagent-prod
vmalert-prod
vmalert-tool-prod
vmauth-prod
vmbackup-prod
vmrestore-prod
vmctl-prod
```

### Version

v1.102.1

### Additional information

I'm not sure why there is need for the change in owner and group. I suggest to change and user and group id inside the release archive to something not that high to ensure compatibility.

There is a workaround for extracting such archive successfully though (see the "to reproduce" section). If you think it is better to keep the same uid and gid, you should adapt the workaround to the roles inside your [ansible collections](https://github.com/VictoriaMetrics/ansible-playbooks).

**Comment by denisgolius** [comment]
Hey @kennethso168m have you tried to change the owner and chmod for executable files for your own user?

**Comment by zekker6** [comment]
@kennethso168 Thank you for the details, this fix was included in ansible collections release [v0.62.0](https://github.com/VictoriaMetrics/ansible-playbooks/releases/tag/v0.62.0).

**Comment by hagen1778** [comment]
@zekker6 @kennethso168 should we close the issue?

**Comment by zekker6** [comment]
@hagen1778 We've discussed this briefly with @f41gh7. It might worth it to also modify make files to reset permissions when packing the build results to avoid such issues in future. 
Seems like using `1000:1000` would be a good default option as most linux distros currently use these as uid/gid for the first created user.

**Comment by hagen1778** [comment]
Thanks @zekker6! Would you or @f41gh7 make a corresponding PR then?

**Comment by hagen1778** [comment]
The problem should fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6846. New releases of VM components will be packed with 1000:1000 owner/group.

**Comment by hagen1778** [comment]
Releases [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030), [v1.102.2](https://docs.victoriametrics.com/changelog/#v11022) and [v1.97.7](https://docs.victoriametrics.com/changelog/#v1977) were built with change from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6846.
