### ISSUE TITLE
offset in WITH templates does not work

### ISSUE THREAD

**Issue by simonDeHero** [VictoriaMetrics/VictoriaMetrics#679]
hi there!

i would like to use `offset` in my template like this:
```
WITH (
    fn(o) = up o
)
fn("offset 1w")
```

i tried it out on https://play.victoriametrics.com/promql/expand-with-exprs but got this error:
```
Cannot expand query:withExpr: unexpected token "o"; want ",", ")"; unparsed data: "o\r\n)\r\nfn(\"offset 1w\")"
```

any idea, what could be wrong?

thx for looking into it!

**Comment by valyala** [comment]
Currently it is impossible to pass offset as a parameter to template function. The workaround is to write `offset X` after the template function call:

```metricsql
WITH (
   fn(a, b) = ...
)
fn(a, b) offset 1w
```

Let's keep this issue open in order to find the best approach on how to parameterize offsets in `WITH templates`.

**Comment by valyala** [comment]
There is another approach, which supports `offset` in [`WITH` templates](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/expand-with-exprs):

```metricsql
WITH (
  fn(d) = up offset d
)
fn(1w)
```

See https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/expand-with-exprs?query=WITH+%28%0D%0A++fn%28d%29+%3D+up+offset+d%0D%0A%29%0D%0Afn%281w%29 .

Closing this feature request as resolved then.
