### ISSUE TITLE
Victorial metrics is showing data for nodes, that don't have label in filter

### ISSUE THREAD

**Issue by hennadii2012** [VictoriaMetrics/VictoriaMetrics#6791]
### Describe the bug

When I filter data for containers on host based on host label, I am getting some amount of data for containers, that not part of that host. I suppose that this is linked with the situation, that different service are using the same IP for node from time to time (nodes are creating and deleted dynamically)
![image](https://github.com/user-attachments/assets/0378be86-5946-4776-959d-2fff633a61ae)

Metric is `container_cpu_usage_seconds_total`

I am expecting to exclude such metrics in the filter, because they are not really part of existing node( red line on screenhot )

### To Reproduce

Create host with label=1 and container_1 on board, wait for data for this host in monitoring. Delete host and immediately recreate it with the same ip and label=2 and container_2 on board. Filter `container_cpu_usage_seconds_total{label='2'}`. 
You will see the small amount of data with container_1 for host, where we have container_2 only

### Version

1.102.0

### Screenshots

![image](https://github.com/user-attachments/assets/14a4c15d-5ebb-4201-9e45-510689fb2ae7)

**Comment by jiekun** [comment]
Hello. I assume you are scraping metrics with vmagent. Have you checked the service discovery page of vmagent and see what targets and labels are available?

> You will see the small amount of data with container_1 for host

CMIIW, the metrics `container_cpu_usage_seconds_total` is provided by Kubernetes. As described [here](https://kubernetes.io/docs/reference/instrumentation/metrics/), the `container` label is attached and not generated by relabeling in vmagent. So it think it's not a bug of vmagent or VictoriaMetrics.

I recommand checking the metrics API of Kubernetes and see what it's provided in the original response.

**Comment by hennadii2012** [comment]
We are not using kubernetes for such type of services. There are GCP labels on the hosts.  Yes we are scraping metrics with vmagent. The metrics is provided by cadvisor_exporter. 
On vmagent side we are having correct list of aims during the time, when we are looking on them. Also we don't an issue for the regions, where dynamic of adding and deleting hosts smaller. Only for the region, where the big amount of instances can be added or deleted during the 24 hours

**Comment by jiekun** [comment]
May I ask how `label=2` is attached to the metrics? Is it attached by service discovery or by cadvisor_exporter?

> You will see the small amount of data with container_1 for host, where we have container_2

It's likely that the labels have changed for service discovery, but incorrect container metrics still exist on cadvisor_exporter, which vmagent seems unable to handle.

**Comment by hennadii2012** [comment]
We have `gce_sd_configs`, that looks for `__meta_gce_metadata_label` and using `relabel_configs` it creates the label for victoria with key `label`, and value, that it contains. In our case it is `label=2`

**Comment by jiekun** [comment]
This sounds a bit strange, please see if my understanding is correct:

1. cAdvisor is running as a daemon and provides information about the containers that are running on this node.
2. A node is deleted and immediately recreated with the same IP but different labels.
3. vmagent scrape metrics from it.

As you mentioned, metadata labels are from service discovery, and container name information is from cAdvisor. How can cAdvisor provide metrics with a `container_name` that is not running on this node? Have you checked the metrics API of cAdvisor to see if `container_name=container_1` exists on it after recreating the node?

**Comment by hennadii2012** [comment]
Yes you understand correct all 3 items

_How can cAdvisor provide metrics with a container_name that is not running on this node?_ - is a my question. This is the main issue. I suppose, that it don't, and I am thinking about the way, how victoria clean the old data (we have prometheus in parallel, that doesn't have this issue with the same conditions)

_Have you checked the metrics API of cAdvisor to see if container_name=container_1 exists on it after recreating the node?_ - I don't see this container on newly created node, only small part of data in victoria. Nothing else is pointing to this container

**Comment by jiekun** [comment]
> how victoria clean the old data

vmagent only collect data that exporter (in your case, cAdvisor) provides. I would recommend you to check the scrape result of vmagent and see if `container_1` exists.

> I don't see this container on newly created node, only small part of data in victoria.

By this I mean: have you checked if cAdvisor still providing metrics that contains `container_1`? If not, vmagent won't be able to collect it.

> only small part of data in victoria

Can I ask for clarification on the term "small part"? Does it mean that this data only exists for a brief period and then disappear?

**Comment by hennadii2012** [comment]
> Can I ask for clarification on the term "small part"? Does it mean that this data only exists for a brief period and then disappear?
They are not. They are exists during the whole retention period

> By this I mean: have you checked if cAdvisor still providing metrics that contains container_1? If not, vmagent won't be able to collect it.

Based on time of issue on the graph I don't see problem data in cAdvisor api

**Comment by jiekun** [comment]
> I don't see problem data in cAdvisor api

If cAdvisor does not provide data for container_1, vmagent should not be able to collect it, and it should not be queried either. 

You can query the metrics for `container_1` to see which job is collecting them, and then check the status of this job on the vmagent web UI to see if it is collecting data really includes `container_1`.

Also, please provide the query you are using. I can't get information from your screenshot above.

**Comment by hennadii2012** [comment]
`container_cpu_usage_seconds_total{label=~'1',name=~'container_1|container_2'}`

**Comment by hennadii2012** [comment]
I do see in in `Discovered targets` unhealthy target with ip `10.10.10.45` with `label=1` and healthy with the same ip and `lable=2`. When this happened, I see the date on graph, as on screenhot. After some time unhealthy target is removed from  `Discovered targets`, but data left on grapth. So I suppose faster removing of unhealthy targets may solve an issue, but I don't know how to enforce victoria to do this

**Comment by jiekun** [comment]
I think you cannot do it manually. And adjusting `-promscrape.gceSDCheckInterval` (default 1 minute) may help checking for change in GCE more frequently. See: https://docs.victoriametrics.com/sd_configs/#gce_sd_configs

**Comment by hennadii2012** [comment]
I tried this as the first step. Even change to 10s doesn't change the result behaviour

**Comment by hennadii2012** [comment]
I see that the host with label=1 down and removed from monitoring but data are stopping gathering only after couple minutes

**Comment by jiekun** [comment]
It is worth mentioning that VictoriaMetrics Single-Node or vmselect will process and fill missing data point in the query response. Sometimes you may observe more data points than those collected, which is also related to the query step. However, vmagent does not actually collect additional data. 

If you want to confirm this behavior, you need to use the [export API](https://docs.victoriametrics.com/url-examples/#apiv1export) to export the raw data for verification.

**Comment by hennadii2012** [comment]
Hello! I have got raw data
Here is how they are looking like:
`{"metric":{"__name__":"container_cpu_usage_seconds_total","job":"gce_scrape_container_zone","instance":"instance1","name":"container1","label":"1","cpu":"cpu06","image":"image:release","region":"region","replica":"victoria-replica-name","zone":"zone"},"values":[167.603841375,175.706060462,182.936656153,190.8486385289,197.783027475,205.8690625569,212.783846699,220.388763544,228.535343379,236.296237689,244.150878504,251.6939918319,258.6975347149],"timestamps":[1724095071245,1724095091245,1724095111245,1724095131245,1724095151245,1724095171245,1724095191245,1724095211245,1724095231245,1724095251245,1724095271245,1724095291245,1724095311245]}
{"metric":{"__name__":"container_cpu_usage_seconds_total","job":"gce_scrape_container_zone","instance":"instance1","name":"container1","label":"1","cpu":"cpu22","image":"image:release","region":"region","replica":"victoria-replica-name","zone":"zone"},"values":[169.4308011289,177.3473585309,184.600044238,192.578870661,199.6215379659,207.697751689,214.5786195969,222.2900711519,230.317091484,237.949230279,246.001456265,253.37618802,260.398678764],"timestamps":[1724095071245,1724095091245,1724095111245,1724095131245,1724095151245,1724095171245,1724095191245,1724095211245,1724095231245,1724095251245,1724095271245,1724095291245,1724095311245]}
{"metric":{"__name__":"container_cpu_usage_seconds_total","job":"gce_scrape_container_zone","instance":"instance1","name":"container2","label":"1","container_label_org_label_schema_build_date":"2023-07-18T22:35:33+00:00","container_label_org_label_schema_license":"App licence","container_label_org_label_schema_name":"app_name","container_label_org_label_schema_schema_version":"1.0","container_label_org_label_schema_url":"https://app.url","container_label_org_label_schema_vcs_url":"https://app-github.url","container_label_org_label_schema_vendor":"Vendor","container_label_org_label_schema_version":"0.0.0","container_label_org_opencontainers_image_created":"2023-07-18T22:35:33+00:00","container_label_org_opencontainers_image_description":"app_name description","container_label_org_opencontainers_image_licenses":"App licence","container_label_org_opencontainers_image_ref_name":"os_name","container_label_org_opencontainers_image_title":"app_name","container_label_org_opencontainers_image_vendor":"Vendor","container_label_org_opencontainers_image_version":"0.0.0","cpu":"cpu06","image":"image:release","region":"region","replica":"victoria-replica-name","zone":"zone"},"values":[75.949792262,83.709961564,88.589946574,97.304280226,110.232822297,123.07096419,127.977721419],"timestamps":[1724094933295,1724094953295,1724094973295,1724094993295,1724095013295,1724095033295,1724095053295]}
{"metric":{"__name__":"container_cpu_usage_seconds_total","job":"gce_scrape_container_zone","instance":"instance1","name":"container2","label":"1","container_label_org_label_schema_build_date":"2023-07-18T22:35:33+00:00","container_label_org_label_schema_license":"App licence","container_label_org_label_schema_name":"app_name","container_label_org_label_schema_schema_version":"1.0","container_label_org_label_schema_url":"https://app.url","container_label_org_label_schema_vcs_url":"https://app-github.url","container_label_org_label_schema_vendor":"Vendor","container_label_org_label_schema_version":"0.0.0","container_label_org_opencontainers_image_created":"2023-07-18T22:35:33+00:00","container_label_org_opencontainers_image_description":"app_name description","container_label_org_opencontainers_image_licenses":"App licence","container_label_org_opencontainers_image_ref_name":"os_name","container_label_org_opencontainers_image_title":"app_name","container_label_org_opencontainers_image_vendor":"Vendor","container_label_org_opencontainers_image_version":"0.0.0","cpu":"cpu22","image":"image:release","region":"region","replica":"victoria-replica-name","zone":"zone"},"values":[81.124938745,88.868949098,99.488066294,110.890724822,125.663638901,138.178785416,144.6917475129],"timestamps":[1724094933295,1724094953295,1724094973295,1724094993295,1724095013295,1724095033295,1724095053295]}
{"metric":{"__name__":"container_cpu_usage_seconds_total","job":"gce_scrape_container_zone","instance":"instance1","name":"container2","label":"1","container_label_org_label_schema_build_date":"2023-07-18T22:35:33+00:00","container_label_org_label_schema_license":"App licence","container_label_org_label_schema_name":"app_name","container_label_org_label_schema_schema_version":"1.0","container_label_org_label_schema_url":"https://app.url","container_label_org_label_schema_vcs_url":"https://app-github.url","container_label_org_label_schema_vendor":"Vendor","container_label_org_label_schema_version":"0.0.0","container_label_org_opencontainers_image_created":"2023-07-18T22:35:33+00:00","container_label_org_opencontainers_image_description":"app_name description","container_label_org_opencontainers_image_licenses":"App licence","container_label_org_opencontainers_image_ref_name":"os_name","container_label_org_opencontainers_image_title":"app_name","container_label_org_opencontainers_image_vendor":"Vendor","container_label_org_opencontainers_image_version":"0.0.0","cpu":"cpu38","image":"image:release","region":"region","replica":"victoria-replica-name","zone":"zone"},"values":[73.894113881,83.705311964,92.813412485,101.213555188,113.122011824,124.720823497,131.5274267809],"timestamps":[1724094933295,1724094953295,1724094973295,1724094993295,1724095013295,1724095033295,1724095053295]}
`

**Comment by hagen1778** [comment]
@hennadii2012  do you observe such issues with cadvisor exporter only? Can you try setting `honor_timestamps: true` in vmagent's scrape config? Can you check Prometheus logs when scraping this target - are there any errors in logs?

**Comment by hennadii2012** [comment]
@hagen1778 , thank you, I will check this options. I don't have prometheus on board in this setup, only victoria metrics. No errors in vmagent and vicrotria metrics containers

**Comment by hennadii2012** [comment]
@hagen1778  `honor_timestamps: true` did not help

**Comment by jiekun** [comment]
@hennadii2012 Hi, since I haven't received a reply from you for 2w, this issue will be removed from the tracking list. If you have any questions, please feel free to reopen it anytime.
