### ISSUE TITLE
How to use VM on bare metal within public network?

### ISSUE THREAD

**Issue by meteozond** [VictoriaMetrics/VictoriaMetrics#6795]
### Describe the question in detail

If vminsert, vmselect, vmagent doesn't support basic auth, what is correct way using VM cluster within public network without build private network between hosts? Is there any way implementing Authorisation for each of components?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. I think one possible way is to deploy [vmauth](https://docs.victoriametrics.com/vmauth/) in the same machine. vmauth could be used as **HTTP proxy** to provide basic auth. 

And for TCP connection between vminsert/vmselect and vmstorage, you could try to whitelist the IP address of vminsert/vmselect on the machine running vmstorage.

**Comment by meteozond** [comment]
@jiekun When you are talking about using vmauth, do you mean using schema like this?

```mermaid
graph TD;
vmagent-A-->vmauth-A;
vmauth-A --basic--> nginx-B;
nginx-B --> vminsert-B; 
vminsert-B --> vm_storage-B;

vmauth-A --basic--> nginx-C;
nginx-C --> vminsert-C; 
vminsert-C --> vm_storage-C;

```
```mermaid
graph TD;
vm_storage.B --> select.B;
select.B --> nginx.B;
nginx.B --basic--> Grafana;

vm_storage.A --> select.A;
select.A --> nginx.A;
nginx.A --basic--> Grafana;
```

**Comment by jiekun** [comment]
By using vmauth, you don't need Nginx. For example you could setup vmauth with following config:
```yaml
users:
  - username: foo
    password: bar
    url_map:
      - src_paths:
          - "/insert/.*"
        url_prefix:
          - "http://<vminsert-1>:8480/"
          - "http://<vminsert-2>:8480/"
```

In this case, you need to config the remote write in vmagent like:
```yaml
-remoteWrite.url=http://<vmauth>:8427/insert/0/prometheus/api/v1/write
-remoteWrite.basicAuth.password=bar
-remoteWrite.basicAuth.username=foo
...
``` 
```mermaid
graph TD;
vmagent-A--basic-->vmauth-A;
vmauth-A --> vminsert-B;
vminsert-B --> vm_storage-B;

vmauth-A --> vminsert-C; 
vminsert-C --> vm_storage-C;
```

**Comment by meteozond** [comment]
@jiekun Ok I've got it about nginx vmauth replacement, but I don't understand how vminsert is authorized to write both C and B storages. Through vmauth too?

**Comment by jiekun** [comment]
`vminsert` sends data to `vmstorage` via a TCP connection. `vmauth` is an HTTP proxy, so we cannot use `vmauth` here. `vmstorage` should whitelist the IP address of `vminsert` and block other public access.

And typically, data needs to be sharded across multiple vmstorage instances. Therefore, each vminsert instance should be able to access **all** vmstorage instances and distribute data among them.

**Comment by meteozond** [comment]
Thank again, I've got your idea, but still don't like white list aproach. What do you think about vminsert traffic nginx tuneling? (Not sure that vauth could do so).

```mermaid

graph TD;

vinsert-A --> storage-A;

vmagent-A-->vinsert-A;
vinsert-A --> nginx-A-127.0.0.2;
nginx-A-127.0.0.2--basic-->nginx-B;
nginx-B-->storage-B;

vinsert-B --> storage-B;

vmagent-B-->vinsert-B;
vinsert-B --> nginx-B-127.0.0.3;
nginx-B-127.0.0.3--basic-->nginx-A;
nginx-A-->storage-A;

```

**Comment by jiekun** [comment]
I cannot agree with this kind of network architecture design, and I don't understand why accessing `vmstorage-A` from `vminsert-A` does not require authentication, while accessing `vmstorage-B` does. 

In fact, all `vmstorage` instances should be treated equally for any `vminsert`. `A` and `B` do not necessarily imply that they are on the same physical machine. 

Moreover, the design of a two-layer Nginx makes the entire architecture unnecessarily complex. 

`vmstorage` does not need authentication because its communications with `vminsert` and `vmselect` are internal, while `vminsert` and `vmselect` are services exposed externally, hence they might need authentication for protection. Therefore, I cannot understand why authentication is being set up between `vminsert` and `vmstorage`.

**Comment by meteozond** [comment]
Mermaid made some mistake assumption, the key idea is something like this.
![image](https://github.com/user-attachments/assets/dbf4d42e-97af-4b6e-90fc-deb1d4b3bfe3)

**Comment by jiekun** [comment]
Yes, you need to use `vmauth` to protect the HTTP ports exposed to the public network, instead of placing authentication methods in front of `vmstorage`.

**Comment by tiny-pangolin** [comment]
VictoriaMetrics enterprise offers mtls for communication between vmselect, vminsert, and vmstorage. 

Placing vmselect, vminsert, and vmstorage nodes on a VPN like wireguard would also solve this problem, but that would be creating an internal network which you are trying to avoid.

**Comment by meteozond** [comment]
I guess it is possible to do something with `nginx` `content_by_lua_block` waiting/sending sequence/password before upstreaming tcp ) 
It will defenetly reduce passthrough a bit, but I'll give this idea a try soon )

**Comment by jiekun** [comment]
I'm closing this issue as answered. Please reopen it if you have more question on this topic.
