### ISSUE TITLE
Trigger browser authorization dialog in vmauth

### ISSUE THREAD

**Issue by ofen** [VictoriaMetrics/VictoriaMetrics#680]
**Describe the solution you'd like**
1. Add user in config.yaml
2. Navigate browser to instance (e.g. http://vmauth:80)
3. Browser prompt for username and password
4. Enter correct credential
5. vmauth route to configured endpoint

**Current implementation**
1. Add user in config.yaml
2. Pass additional args (should be same as in config.yaml):
    - -httpAuth.username=admin
    - -httpAuth.password=12345678
3. Navigate browser to instance (e.g. http://vmauth:80)
4. Browser prompt for username and password
5. Enter correct credential
6. vmauth route **only** to configured endpoint with credentials from **-httpAuth.username** and **-httpAuth.password** (other routes will result 401 HTTP error code)

**Comment by ofen** [comment]
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/681

**Comment by valyala** [comment]
The commit that adds browser authorization dialog to `vmauth` has been included in [v1.39.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.

**Comment by ofen** [comment]
still need to remove **-httpAuth.username** and **-httpAuth.password** flags from **vmauth** because it's leading to only one acceptable basic auth header

**Comment by valyala** [comment]
> still need to remove -httpAuth.username and -httpAuth.password flags from vmauth because it's leading to only one acceptable basic auth header

Yeah. The temporary workaround is just don't set these flags when running `vmauth` :)
