### ISSUE TITLE
[vmagent]: How env flags are enumarted ?

### ISSUE THREAD

**Issue by divinesecret** [VictoriaMetrics/VictoriaMetrics#6800]
### Describe the question in detail

for `vmagent` systemd unit file i can use:
```
Environment="remoteWrite_basicAuth_username=user"
Environment="remoteWrite_basicAuth_password=password"
```
But if i have several URLs, how to enumerate env variables ?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by f41gh7** [comment]
Hello,  it's possible to use comma - `,` as separator:

 With given example there are 4 remote write urls. If basic auth is not needed for some url, it must be set to empty value
```
Environment="remoteWrite.url=url,url-1,url-2,url-3"
Environment="remoteWrite_basicAuth_username=user,user2,,user3"
Environment="remoteWrite_basicAuth_password=password,password2,,password3"
```
