### ISSUE TITLE
Prometheus remote write failed, status:400 or 404, msg: 'unsupported path requested: \"/insert/0/prometheus'

### ISSUE THREAD

**Issue by adgarr** [VictoriaMetrics/VictoriaMetrics#6810]
### Describe the bug
Occasionally receive error logs from Prometheus, as follows：
Aug 14 16:19:47 xxxxxx prometheus: ts=2024-08-14T08:19:47.134Z caller=dedupe.go:112 component=remote level=error remote_name=1c0693 url=http://victoria-metrics-insert.cn/insert/0/prometheus msg="non-recoverable error" count=10000 exemplarCount=0 err="server returned HTTP status 404 Not Found: "
Aug 14 16:30:33 xxxxxx prometheus: ts=2024-08-14T08:30:33.479Z caller=dedupe.go:112 component=remote level=error remote_name=1c0693 url=http://victoria-metrics-insert.cn/insert/0/prometheus msg="non-recoverable error" count=10000 exemplarCount=0 err="server returned HTTP status 400 Bad Request: remoteAddr: \"xx.xx.xx.xx:62402, X-Forwarded-For: 10.19.xx.xx\"; requestURI: /insert/0/prometheus; unsupported path requested: \"/insert/0/prometheus\""
Aug 14 17:46:20 xxxxxx prometheus: ts=2024-08-14T09:46:20.441Z caller=dedupe.go:112 component=remote level=error remote_name=1c0693 url=http://victoria-metrics-insert.cn/insert/0/prometheus msg="non-recoverable error" count=10000 exemplarCount=0 err="server returned HTTP status 400 Bad Request: remoteAddr: \"xxxx:19412, X-Forwarded-For: 10.19.xx.xx\"; requestURI: /insert/0/prometheus; unsupported path requested: \"/insert/0/prometheus\""

prometheus, version 2.53.1
The configuration for remote write is as follows：
remote_write:
  - url: "http://victoria-metrics-insert.cn/insert/0/prometheus"
    remote_timeout: 120s
    queue_config:
      capacity: 30000
      max_shards: 15000
      max_samples_per_send: 10000
      min_backoff: 300ms
      max_backoff: 10s
      batch_send_deadline: 3s

### To Reproduce

Occasionally occurs, cannot reproduce.

### Version

prometheus  --version
prometheus, version 2.53.1 (branch: HEAD, revision: 14cfec3f6048b735e08c1e9c64c8d4211d32bab4)

vminsert-prod --version
vminsert-20240201-152243-tags-v1.93.11-cluster-0-g891a9f951

### Screenshots

no err log

**Comment by jiekun** [comment]
Hi. May I ask if you can check the logs in `vminsert`, could you find similar logs like:
```
2024-08-15T07:57:02.092Z        warn    lib/httpserver/httpserver.go:348        remoteAddr: "127.0.0.1:51630"; requestURI: *****; unsupported path requested: "*****"
```

**Comment by adgarr** [comment]
"The request was routed to a specific insert node, but no error logs were found on that insert node."

**Comment by adgarr** [comment]
> "The request was routed to a specific insert node, but no error logs were found on that insert node."



> Hi. May I ask if you can check the logs in `vminsert`, could you find similar logs like:
> 
> ```
> 2024-08-15T07:57:02.092Z        warn    lib/httpserver/httpserver.go:348        remoteAddr: "127.0.0.1:51630"; requestURI: *****; unsupported path requested: "*****"
> ```
> 
> The URL you are using appears to be correct. I think it's worth investigating whether the request is being incorrectly routed by the load balancer, as this issue does not occur consistently.

"The request was routed to a specific insert node, but no error logs were found on that insert node."

**Comment by jiekun** [comment]
That's weird, because the error message is likely to be responded from a VictoriaMetrics component:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9c4b0334f21eab6156445ca874db7e2f0de980b1/lib/httpserver/httpserver.go#L422

And vminsert will log a warning if the request path is not available. If you can't see the warning log, the error request may not have reached the vminsert node and could have been routed to an incorrect node.

I would suggest double-checking DNS and routing settings, as well as trying to find warning logs on other VM components. If a similar warning log can be found in another component (such as `vmselect`), it indicates that the error request is being routed to that particular component.

**Comment by adgarr** [comment]
> the request path is not available.

Sorry, it's my mistake！ I exec cmd: "egrep unsupported vmselect-prod.log" in select node, found log: "requestURI: /insert/0/prometheus; unsupported path requested: "/insert/0/prometheus"

but why?  the domain 'victoria-metrics-insert.cn' is routed to my all insert nodes in my lb config. And the insert node and select node are located on different hosts.

**Comment by adgarr** [comment]
> That's weird, because the error message is likely to be responded from a VictoriaMetrics component:
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9c4b0334f21eab6156445ca874db7e2f0de980b1/lib/httpserver/httpserver.go#L422
> 
> And vminsert will log a warning if the request path is not available. If you can't see the warning log, the error request may not have reached the vminsert node and could have been routed to an incorrect node.
> 
> I would suggest double-checking DNS and routing settings, as well as trying to find warning logs on other VM components. If a similar warning log can be found in another component (such as `vmselect`), it indicates that the error request is being routed to that particular component.

Most likely it's a DNS issue. Thanks!
