### ISSUE TITLE
How to calculate the QPS of logs in victorialog

### ISSUE THREAD

**Issue by CoderX-Aaron** [VictoriaMetrics/VictoriaMetrics#6811]
### Is your question request related to a specific component?

VictoriaLogs

### Describe the question in detail

I have collected a lot of Nginx logs (json format) from victorialogs, but I don't know how to use logsQL to achieve real-time statistics of the number of QPS of each specific interface in the nginx log within 1 minute, and draw graphs in Grafana. Can you give me some guidance on how to implement this logsQL?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
> and draw graphs in Grafana

I'm not sure if the query API could be used to draw QPS graph. But There's a `/hit` API for VictoriaLogs, which is used to draw histogram on VMUI. And maybe you could try HTTP request like this:
```
curl 'http://<victoria-logs>/select/logsql/hits' \
  --data-raw 'query=*&step=1000ms&start=2024-08-15T02%3A29%3A34.698Z&end=2024-08-15T08%3A29%3A34.698Z'
```
