### ISSUE TITLE
How to setup VMAgent remotewrite to different targets with different authority method

### ISSUE THREAD

**Issue by JingangLi** [VictoriaMetrics/VictoriaMetrics#6812]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hi,

Can I get help to know how to setup vmagent parameter to two remotewrite targets?
One of them use Token access, and one of them use TSL cert .

Many thanks.

Rgds,
Jingang Li

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Here's the example configuring multiple remote write targets with different basic auth params:
```bash
./bin/vmagent \
    -promscrape.config=./bin/vmagent-scrape-config.yaml \
    -remoteWrite.url=http://127.0.0.1:8480/insert/0/prometheus \
    -remoteWrite.url=http://127.0.0.1:8480/insert/2/prometheus \
    -remoteWrite.basicAuth.username=user, \
    -remoteWrite.basicAuth.password=password, \
    -remoteWrite.tlsCertFile=,/opt/cert.pem \
    -remoteWrite.tlsKeyFile=,/opt/key.pem \
```

You could use **comma** to seperate the values. vmagent will extra the correct value by `idx`. 

In this example, for remote write `0`:
- url: `http://127.0.0.1:8480/insert/0/prometheus`
- basicAuth.username: `user`
- basicAuth.password: `password`
- tlsCertFile: empty
- tlsKeyFile: empty

For remote write `1`:
- url: `http://127.0.0.1:8480/insert/2/prometheus`
- basicAuth.username: empty
- basicAuth.password: empty
- tlsCertFile: `/opt/cert.pem`
- tlsKeyFile: `/opt/key.pem`

And for the flags that you may want to use, please refer to vmagent doc: https://docs.victoriametrics.com/vmagent/
```bash
# Those might be the flags you are looking for. But please read the doc before using them.
    -remoteWrite.tlsCAFile
    -remoteWrite.tlsCertFile
    -remoteWrite.tlsKeyFile
    -remoteWrite.bearerToken
```

**Comment by JingangLi** [comment]
Hi @jiekun ,

Many thanks you for support. It works to me!

Have a nice day!

Rgds,
Jingang Li
