### ISSUE TITLE
allow configuration of dedup on same timestamp behavior

### ISSUE THREAD

**Issue by WolfEYc** [VictoriaMetrics/VictoriaMetrics#6819]
### Is your feature request related to a problem? Please describe

Dedup on the same time chooses the MAX value.

### Describe the solution you'd like

Dedup on the same value chooses the most recently inserted value, either by default or by config.

### Describe alternatives you've considered

I've tried just deleting and reinserting the entire stream, but for my use case, this data can be updated without any event of knowing what series changed, and so i end up having the delete and reinsert ALL of the series, causing performance impact.

The data im working with can only be updated up to 6 months in the past. and overall there are years of data, dating back 5+ years. flushing and filling 5 years worth of data just to do an update on stuff within the last 6 months causes issues. 

The data is daily data (one point per day per series at midnight) 

If this feature existed, i would be able to just have a job that will import the last 6 months into the instance twice a week (which is the acceptable frequency) this would eliminate downtime during the insert (instead of flushing and filling)
and would also eliminate the need to create new streams constantly which seems to make the indexes super unperformant, due to high churn rate.

**Comment by zekker6** [comment]
@WolfEYc Deduplication actually applies two rules for samples within `-dedup.minScrapeInterval`: 
1. it takes the sample with the highest timestamp
2. if multiple samples have the same timestamp - it picks a sample with the highest value

For your use-case you might configure deduplication with `-dedup.minScrapeInterval=10ms` which will give 10 "slots" to store an updated value. You can increase this to `100ms` to have more "slots" if it is needed.
Will that help in your case?

**Comment by WolfEYc** [comment]
This workaround is not viable, as i do not know when/if the data is updated, so i would only have the capability to run the job 100 times before it breaks, not a very stable automation if you ask me.

Being able to configure the default behavior from max to latest upload TS would be a much more viable option.

**Comment by hagen1778** [comment]
Hey @WolfEYc! Looks like you're trying to use VictoriaMetrics for cases it wasn't designed for. Specifically, to perform regular data updates. VictoriaMetrics is append-only database, it wasn't designed to sustain updates or provide APIs for it. It is likely you need to look at different solution for your use case.

**Comment by WolfEYc** [comment]
@hagen1778 all good, ill stick to using the sql db for this use case, which is OK because its only daily values, not high frequency.
