### ISSUE TITLE
 use VictoriaMetrics could reduce how much cpu and memory?

### ISSUE THREAD

**Issue by zdyj3170101136** [VictoriaMetrics/VictoriaMetrics#6850]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Compared with prometheus, use VictoriaMetrics could reduce how much cpu and memory?

i need convince our team to use VictoriaMetrics.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by Amper** [comment]
Hello, @zdyj3170101136.
I believe you can find answer in [this section](https://docs.victoriametrics.com/articles/?highlight=benchmark#benchmarks), especially in [this article](https://valyala.medium.com/prometheus-vs-victoriametrics-benchmark-on-node-exporter-metrics-4ca29c75590f).
You can also find more fresh and independent benchmarks, i.e. (first results for me in google for "VictoriaMetrics vs prometheus"):
- https://last9.io/blog/prometheus-vs-victoriametrics/
- https://zetablogs.medium.com/prometheus-vs-victoria-metrics-load-testing-3fa0cc782912
- https://www.dbi-services.com/blog/prometheus-vs-victoriametrics/

In addition, you can take a look into Case studies [here](https://docs.victoriametrics.com/casestudies/) or [here](https://victoriametrics.com/case-studies/).

**Comment by changshun-shi** [comment]
If choose prometheus, you will find you must choose a distribute time series database when you has mount of service and data someday because of the stability, and you will find `VictoriaMetrics` is the best choice throught the open source world.
And maybe benchmark with your real data is better than believe in other test.

**Comment by zdyj3170101136** [comment]
> this article

that article is four years old.

and the result shows that prometheus and VictoriaMetrics have same cpu usage.

i want to know if VictoriaMetrics have huge enhancement after four years old.

Otherwise we cannot reduce the instance specifications of the machine.

**Comment by hagen1778** [comment]
Hi @zdyj3170101136 !

> that article is four years old.

Try checking newer article here https://victoriametrics.com/blog/reducing-costs-p1/ (available as video and slides as well).

> i want to know if VictoriaMetrics have huge enhancement after four years old.

In terms of CPU usage, Prometheus and VictoriaMetrics are pretty similar. But you can get much more from switching to VM:
1. Reduced mem usage
2. Faster query processing
3. Stream aggregation
4. Enhanced query language and relabeling
5. Ability to scale horizontally

I'd also recommend to not rely on other articles. Comparing VM and Prometheus, especially when they're just single binaries, should be super straightforward. Just test it for yourself on your own data and see whether it worth it. Try referring to the articles only if you need to know techniques for comparing these two products.

**Comment by jiekun** [comment]
I'm closing this issue as answered. Please comment if you have more question on this topic.
