### ISSUE TITLE
vmstorage: some IndexDB's metrics are incorrectly reported 

### ISSUE THREAD

**Issue by fxrlv** [VictoriaMetrics/VictoriaMetrics#6868]
### Describe the bug

vmstorage reports metrics for current IndexDB only
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f599f3ad8648c65201c7ee3fb2d0bb41b13b9b25/lib/storage/storage.go#L657

while some counters are incremented for previous IndexDB only
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/336406e2e13344e246b199cbb0151d44819c3c38/lib/storage/index_db.go#L1812

that causes some metrics are always zero

### To Reproduce

```sh
curl http://vmstorage:8482/metrics
```

### Version

v1.102.1-cluster

### Additional information

cc @f41gh7

**Comment by hagen1778** [comment]
Starting from [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030) VictoriaMetrics should properly update IndexDB metrics using data from the previous index:
> BUGFIX: [Single-node VictoriaMetrics](https://docs.victoriametrics.com/) and vmstorage in [VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/): properly register index metrics for previous index part. See this [issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6868) for details.
