### ISSUE TITLE
Saving metrics in vmagent persisten queue after improper power-off and restart 

### ISSUE THREAD

**Issue by alpi-ua** [VictoriaMetrics/VictoriaMetrics#687]
**Is your feature request related to a problem? Please describe.**
Metrics which are stored at the vmagent persistent queue while there is no connection with the server, are lost if the host powered off or vmagent process has been killed.

**Describe the solution you'd like**
After restart vmagent keeps all metrics that were in a queue before power-off or vmagent killed.

**Describe alternatives you've considered**
A precision may not be ideal, but it will be good if just a few minutes of metrics history are lost after the incident. 

**Additional context**
We want to use vmagent as a part of fail-safe pipeline on POS Terminals, Scales and other Linux devices which are using in retail and may have no connection with Data Center and get powered off by unqualified personnel.

**Comment by valyala** [comment]
@alpi-ua , could you build `vmagent` from the commit d455764a6f0351645803f630e51122b900a6051d according to [these docs](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources) and verify whether it helps preserving pending data after unclean shutdown? It is expected that this commit should significantly reduce the risk of losing pending data after unclean shutdown. Note that the commit permits to lose up to 5 seconds of recently collected data.

**Comment by valyala** [comment]
There was an additional issue in the previous commits, which could prevent from proper persistence for pending data. This should be fixed in the commit 70c721c01b2771f45877ca377c7ae856420d35b6

**Comment by alpi-ua** [comment]
I will try it next week. It will take some time.
Thank you!

**Comment by valyala** [comment]
FYI, persistent queues in vmagent must become more durable starting from [v1.41.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as done.

@alpi-ua , feel free re-opening it if you still see significant data loss after unclean shutdown for `vmagent` v1.41.1 or newer.
