### ISSUE TITLE
Metrics are getting dropped which are sent from Opentelemetry at VMinsert.

### ISSUE THREAD

**Issue by Shindek77** [VictoriaMetrics/VictoriaMetrics#6873]
### Describe the question in detail

Hello, We are sending the Metrics from Opentelemetry to VictoriaMetrics...But few metrics are getting dropped with error              {"ts":"2024-08-22T12:43:53.557Z","level":"warn","caller":"VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:89","msg":"unsupported type for metric \"http_client_duration_milliseconds\"""unsupported type for metric \"http_server_response_size_bytes\""}..{"ts":"2024-08-22T13:36:51.522Z","level":"warn","caller":"VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:89","msg":"unsupported type for metric \"dns_lookup_duration_seconds\""}
2024-08-22T19:06:51+05:30 {"ts":"2024-08-22T13:36:51.522Z","level":"warn","caller":"VictoriaMetrics/lib/protoparser/opentelemetry/stream/streamparser.go:89","msg":"unsupported type for metric \"kestrel_connection_duration_seconds\""}.....................................
Can you please help me on this what must be reason...FYI few metrics are Exponential Histogram but not all of them

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello, this issue is being discussed in Slack. For others who are interested, please check: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1724649677775059

I will update the conclusion here once it's solved.

**Comment by jiekun** [comment]
This issue is discussed in Slack.

> There are some [limitation](https://docs.victoriametrics.com/guides/getting-started-with-opentelemetry/#limitations) for OTel metrics support:
> - VictoriaMetrics doesn’t support experimental JSON encoding format.
> - VictoriaMetrics supports only AggregationTemporalityCumulative type for histogram and summary.

**Comment by chenlujjj** [comment]
hi @jiekun are there any blockers prevent this PR: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6354 to be merged?

**Comment by Shindek77** [comment]
yes..we want it as soon as possible as it already there with some other metrics backend with on config parameter if we set...

**Comment by Shindek77** [comment]
yes..we want it as soon as possible as it already there with some other metrics backend with on config parameter if we set...
