### ISSUE TITLE
Publish VictoriaLogs dashboard to Grafana

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6886]
### Describe the solution you'd like

i want to have VictoroaLogs dashboard in Grafana with an option to download it by id

**Comment by valyala** [comment]
Grafana dashboard for VictoriaLogs has been published - see https://grafana.com/grafana/dashboards/22084-victorialogs/ . The source of the dashboard is available [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/dashboards/victorialogs.json).

Closing the feature request as done.
