### ISSUE TITLE
Provide the list of predefined Alerts for VictoriaLogs

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#6887]
### Describe the solution you'd like

I want to have an official list of alerts for VictoriaLogs like you have for other components in https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/deployment/docker

**Comment by valyala** [comment]
The list of pre-defined alerts for VictoriaLogs is available starting from the commit 3538869942f816f0e64ee0d508f66bbb7e31280c (see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7252 ). See [the list of alerts for VictoriaLogs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/rules/alerts-vlogs.yml).

Closing the feature request as done.
