### ISSUE TITLE
vmagent allocate too many memory when startup

### ISSUE THREAD

**Issue by dxtrzhang** [VictoriaMetrics/VictoriaMetrics#689]
**Describe the bug**
vmagent allocate a lot of memory to heap when startup. And all the extra allocated memory will be set as idle and wait for OS to be freed right after, finally the inuse will be stable.
![image](https://user-images.githubusercontent.com/13900390/89855116-378ab200-dbc8-11ea-91e7-b1f8d467f969.png)
sometime, if the vmagent have tons of targets to scrape, vmagent will get OOM.

**Expected behavior**
memory usage to be stable at startup.

**Version**
v1.38.1-cluster

**Comment by dxtrzhang** [comment]
When scrape job start, it create a `scrapeWork` which contains all the scraped data.
```
type scrapeWork struct {
	// Config for the scrape.
	Config ScrapeWork

	// ReadData is called for reading the data.
	ReadData func(dst []byte) ([]byte, error)

	// PushData is called for pushing collected data.
	PushData func(wr *prompbmarshal.WriteRequest)

	// ScrapeGroup is name of ScrapeGroup that
	// scrapeWork belongs to
	ScrapeGroup string

	rows   parser.Rows
	tmpRow parser.Row

	writeRequest prompbmarshal.WriteRequest
	labels       []prompbmarshal.Label
	samples      []prompbmarshal.Sample

	// the prevSeriesMap and lh are used for fast calculation of `scrape_series_added` metric.
	prevSeriesMap map[uint64]struct{}
	labelsHashBuf []byte
}
```
the number of the targets' metric rows may be large, and all the data filed(especially labels) is a nil slice, when append all  the labels to this field, numerous append cause various slice resize, when slice resize happens, golang copy the value from old array to new array, this operation, causes the inuse memory so high and set as idle right after.
```
func appendLabels(dst []prompbmarshal.Label, metric string, src []parser.Tag, extraLabels []prompbmarshal.Label, honorLabels bool) []prompbmarshal.Label {
	...
	dst = append(dst, prompbmarshal.Label{
		Name:  "__name__",
		Value: metric,
	})
	for i := range src {
		tag := &src[i]
		dst = append(dst, prompbmarshal.Label{
			Name:  tag.Key,
			Value: tag.Value,
		})
	}
	dst = append(dst, extraLabels...)
	...
}
```

**Comment by dxtrzhang** [comment]
This happens when every new scrape job created, more obvious when startup which even causes agent OOM.

**Comment by dxtrzhang** [comment]
after the fix( pre allocate space for the slice), it saves more than 1/2 of the memory usage when startup in our cases.
![image](https://user-images.githubusercontent.com/13900390/89856594-44110980-dbcc-11ea-9e4e-9fdc60b40c63.png)

**Comment by dxtrzhang** [comment]
There are still some gap between, I guess it's the same reason, see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/5492edcc6ca04f432c068b7763e66a7a7e87c384/lib/protoparser/prometheus/parser.go#L152
It's hard to predict the row counts without iter the scraped data, so I kept it unchanged.

**Comment by valyala** [comment]
@dxtrzhang , thanks for the original idea about reducing memory usage at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/688 ! It has been extended in the commit 4628deecd13e9c95b9a1701188079ea3bde18271 . Could you try building `vmagent` from this commit and verifying whether it requires lower amounts of memory for your case?

**Comment by valyala** [comment]
Oops, the previous commit contained a bug, which could lead to high memory usage. The bug has been fixed in e646674b23ebb3204a63566d4a9cd78913c51861 .

**Comment by dxtrzhang** [comment]
works fine from commit `e646674`.

**Comment by valyala** [comment]
Thanks for the confirmation! The enhancement will be included into the next release. After that the issue will be closed.

**Comment by valyala** [comment]
`vmagent` should use lower amounts of memory when scraping big number of targets starting from [v1.40.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as done.
