### ISSUE TITLE
RetentionFilters don't respected deleted metricIDs

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#6891]
### Describe the bug

 Enterprise version of VictoriaMetrics has https://docs.victoriametrics.com/#retention-filters feature.

 It performs `searchMetricNameWithCache` call for `bh.TSID.MetricID` obtained during storage background merge.

But it doesn't perform check if metricID was deleted. It may trigger unexpected path for tsid cache reset.

### To Reproduce

 Delete metricID, wait for background merge to remove it from index. Check `missingMetricNamesForMetricID` counter. 

### Version

 Any version with retentionFilters

**Comment by hagen1778** [comment]
The bugfix was included into [v1.103.0](https://docs.victoriametrics.com/changelog/#v11030) and [v1.102.2](https://docs.victoriametrics.com/changelog/#v11022).
