### ISSUE TITLE
Remove unnecessary HTML files from the build

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/VictoriaMetrics#6900]
### Is your feature request related to a problem? Please describe

The current build process generates several HTML files for different variants of the application, each corresponding to a specific configuration. However, all of these HTML files are included in the final build, even if they are not used, resulting in unnecessary files being added to the build.

### Describe the solution you'd like

Only the `index.html` file should be retained in the build. All other HTML files should be removed.

### Describe alternatives you've considered

The current implementation does not affect the application's functionality, but it includes unnecessary files in the build.

### Additional information

It is also necessary to modify the metadata in the HTML files according to each build configuration.
Related issue: #6764 and related PR: #6770.

**Comment by valyala** [comment]
@Loori-R , is there any progress on this issue? The `make vmui-logs-update` and `make vmui-update` commands create a `app/vmui/packages/vmui/public/index.html` file after the merge of https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6770 , and it is unclear whether this file should be added to git repository on not.

**Comment by Loori-R** [comment]
@valyala, I’ve opened [pull request #6972](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6972), which addresses this issue and slightly reduces the build size. Additionally, I added `index.html` to `.gitignore`, as I believe it shouldn’t be deleted because it is needed during the development process.

**Comment by hagen1778** [comment]
I've updated vm and vl assets after merging https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6972 - see this commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c00b64726c290a52c3d5ca533a52cd975d4399aa. Closing this ticket as done, as it doesn't require release.
