### ISSUE TITLE
Cast to int limiting the cache size to MaxInt32

### ISSUE THREAD

**Issue by mkrysiak** [VictoriaMetrics/VictoriaMetrics#6902]
### Describe the bug

Caches are limited to Go's max `int` size of 2147483647 bytes because the allowed memory calculation is cast to an `int` (https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/memory/memory.go#L40).

### To Reproduce

Start VictoriaMetrics with `-memory.allowedBytes` greater than 2GB.  On startup, VM will log `VictoraMetircs/lib/memory/memory.go:46 limiting caches to 2147483647 bytes, ...`.

### Version

victoria-metrics-20240425-145433-tags-v1.101.0-0-g5334f0c2c

**Comment by jiekun** [comment]
Hello, are you using a 32-bit operation system?

When I tried ` -memory.allowedBytes=4GiB`, it logs:
```
// 4GiB
2024-08-29T07:11:19.500Z        info    lib/memory/memory.go:46 limiting caches to 4294967296 bytes, leaving 29225709568 bytes to the OS according to -memory.allowedBytes=4GiB
```
And when this flag is not set:
```
// 18.7GiB, which is about 60% of my 31.9GiB memory.
2024-08-29T07:15:40.051Z        info    lib/memory/memory.go:42 limiting caches to 20112406118 bytes, leaving 13408270746 bytes to the OS according to -memory.allowedPercent=60
```

They seems to be correct on 64 Bit OS. And there are memory limitation on 32 bit OS so I doubt this bug should be fixed.

**Comment by mkrysiak** [comment]
Thanks for helping, it pointed me in the right direction.  We were using a 64-bit system but accidentally had a 32-bit binary in our repository.  I downloaded the appropriate amd64 package and now it's working as expected.

Sorry for the erroneous bug report.
