### ISSUE TITLE
The "match[]" parameter filtering of the http label values ​​interface does not work

### ISSUE THREAD

**Issue by groobyming** [VictoriaMetrics/VictoriaMetrics#6903]
### Describe the bug

When using the [vm labelvalues ​​api](https://docs.victoriametrics.com/url-examples/#apiv1labelvalues) to get label values, the match[] parameter filtering does not work. All values ​​that do not meet the filter criteria are returned.

Http Request:
```
 curl -XGET http://localhost:8888/api/v1/label/__name__/values \
 -d 'match[]={__name__="http_request_count"}''
```

Expected:
http_request_count

Actual:
Returns all metric names

### To Reproduce

step 1: Prepare some test data, including metricA, metricB and metric

step 2: 
```
 curl -XGET http://localhost:8888/api/v1/label/__name__/values \
 -d 'match[]={__name__="metricA"}''
```

step 3:
return metricA，metricB and metricC

### Version

v1.93.1-cluster

**Comment by jiekun** [comment]
Hello. Have you tried to put the filter in query params like:
```
curl --location -g --request GET 'http://<vm>:<port>/api/v1/label/__name__/values?match[]={__name__="http_request_count"}'
```

Also you could try POST request like:
```
curl --location --request POST 'http://<vm>:<port>/api/v1/label/__name__/values' \
--form 'match[]="{__name__=\"vm_promscrape_targets\"}"'
```

Docs FYI:
- https://docs.victoriametrics.com/url-examples/#apiv1labelvalues
- https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values

**Comment by jiekun** [comment]
Close as answered. Please reopen it if you have more question on this topic.

**Comment by groobyming** [comment]
> Hello. Have you tried to put the filter in query params like:
> 
> ```
> curl --location -g --request GET 'http://<vm>:<port>/api/v1/label/__name__/values?match[]={__name__="http_request_count"}'
> ```
> 
> Also you could try POST request like:
> 
> ```
> curl --location --request POST 'http://<vm>:<port>/api/v1/label/__name__/values' \
> --form 'match[]="{__name__=\"vm_promscrape_targets\"}"'
> ```
> 
> Docs FYI:
> 
> * https://docs.victoriametrics.com/url-examples/#apiv1labelvalues
> * https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values

Thanks, but why doesn't it work the following way? ."curl -XGET http://localhost:8888/api/v1/label/__name__/values \
 -d 'match[]={__name__="metricA"}''"

**Comment by jiekun** [comment]
> The HTTP/1.1 specification (RFC 7230) does allow for the inclusion of a request body in GET requests, although it is generally not recommended.

So it's simply not parsed into the correct request params.

**Comment by groobyming** [comment]
> The HTTP/1.1 specification (RFC 7230) does allow for the inclusion of a request body in GET requests, although it is generally not recommended.

Got it, thanks
