### ISSUE TITLE
Find the way show how many instances are pushing to vm cluster

### ISSUE THREAD

**Issue by jimmy-bro** [VictoriaMetrics/VictoriaMetrics#6919]
### Describe the question in detail

Hi all， I have a problem when using vm cluster.  While using the VM cluster, I initially ran some tests by pushing data from various sources to the cluster. However, I forgot how many instances I tested. Now that the VM cluster is ready to go into production, I want to remove the test data sources, but I can't remember which sources have not been removed. Is there a way to display the all of the IPs of the data sources? 

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Please re-open it if you have more question.
