### ISSUE TITLE
multi-tenancy in standalone version

### ISSUE THREAD

**Issue by varuzam** [VictoriaMetrics/VictoriaMetrics#692]
nice to have multi-tenancy in the standalone version

**Comment by hagen1778** [comment]
Single-node doesn't have multi-tenancy support. But cluster version does - https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multitenancy

The workaround for single-node version is to use `extra_labels`:
```
VictoriaMetrics accepts optional extra_label=<label_name>=<label_value> query arg, which can be used for enforcing additional label filters for queries. For example, /api/v1/query_range?extra_label=user_id=123&extra_label=group_id=456&query=<query> would automatically add {user_id="123",group_id="456"} label filters to the given <query>. This functionality can be used for limiting the scope of time series visible to the given tenant. It is expected that the extra_label query args are automatically set by auth proxy sitting in front of VictoriaMetrics. 
```

See more details here https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html?highlight=external_label#prometheus-querying-api-enhancements
