### ISSUE TITLE
same query works for today data but failed for yesterday data with error "cannot process MetricBlock #1: cannot select more than -search.maxSamplesPerQuery=2000000000 samples"

### ISSUE THREAD

**Issue by vanliu-tx** [VictoriaMetrics/VictoriaMetrics#6941]
### Is your question request related to a specific component?

vmselect

### Describe the question in detail

We have a cluster with 12 insert/2 select/6 storage nodes. The ingesting rate is ~600k/s, and active series is ~20Mil. 

We have a query below which queries and calculates histogram_quantile for data in 30 minutes, it works well for today, but failed for history data in yesterday or before.
```
histogram_quantile(0.9, sum by(le, target_svc) (rate({namespace=~"^(prod|pg)$", result_table_id=~"100147_bcs_custom_metric_result_table_41001|100147_bcs_custom_metric_result_table_40359", __name__="kh_grpc_request_latency_bucket_bucket_value"}[1m] offset -59s999ms)))
```

Here is trace query output for query today data: 
[query_success.json](https://github.com/user-attachments/files/16885699/query_success.json)

![image](https://github.com/user-attachments/assets/c7d677f2-4e79-419b-86b9-8ff4d507617b)

Here is the error response for query yesterday data:
```
422 error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage monitor-vmstorage-3.monitor-kihan-vmstorage.vm.svc.cluster.local:8401: cannot execute funcName="search_v7" on vmstorage "xx.xx.xx.xx:8401": cannot process MetricBlock #1: cannot select more than -search.maxSamplesPerQuery=2000000000 samples; possible solutions: to increase the -search.maxSamplesPerQuery; to reduce time range for the query; to use more specific label filters in order to select lower number of series
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello, are the sample counts of these metrics today the same as yesterday? Have there been any changes in the scrape targets? And are there any differences if you query results from other time ranges?

**Comment by vanliu-tx** [comment]
![image](https://github.com/user-attachments/assets/1ee7d923-5235-4ba8-bc6b-dbf215e99a99)

**Comment by vanliu-tx** [comment]
> Hello, are the sample counts of these metrics today the same as yesterday? Have there been any changes in the scrape targets? And are there any differences if you query results from other time ranges?

the series is almost the same. Tomorrow(2024/09/06) when I query data on today(2024/09/05), the same error message will show up.

**Comment by jiekun** [comment]
Do you know roughly how many samples are involved in these metrics? Are they also around the threshold?
- If yes, you may need to adjust `-search.maxSamplesPerQuery`.
- If not, perhaps this is a bug that needs to be investigated.

You could also use the export API to retrieve the raw data: https://docs.victoriametrics.com/#how-to-export-time-series

**Comment by vanliu-tx** [comment]
> Do you know roughly how many samples are involved in these metrics? Are they also around the threshold?
> 
> * If yes, you may need to adjust `-search.maxSamplesPerQuery`.
> * If not, perhaps this is a bug that needs to be investigated.
> 
> You could also use the export API to retrieve the raw data: https://docs.victoriametrics.com/#how-to-export-time-series

you can refer to the query trace https://github.com/user-attachments/files/16885699/query_success.json file, this query matches ~ 1.8Mil(300k * 6) series, total data points in 30 minutes is around 1.8Mil * 30 * 2 = 108Mil (sample every 30s). This value is much less than the configured -search.maxSamplesPerQuery=2000000000 samples.

Another question is even if I changed the time range from 30 minutes to 2 minutes, this query still failed for yesterday data.

I think this issue may related to the merge in background in storage node.

![image](https://github.com/user-attachments/assets/38118b3a-6654-4c98-b5a8-9b46ad8bae70)

**Comment by Haleygo** [comment]
@vanliu-tx 
>this query matches ~ 1.8Mil(300k * 6) series, total data points in 30 minutes is around 1.8Mil * 30 * 2 = 108Mil (sample every 30s). This value is much less than the configured -search.maxSamplesPerQuery=2000000000 samples.

`-search.maxSamplesPerQuery` not only counts samples that match the query time range, as the samples could be highly compressed in one data part and vmselect needs to unpack the entire part.
see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5851#issuecomment-2187727458 for details.

**Comment by vanliu-tx** [comment]
> @vanliu-tx
> 
> > this query matches ~ 1.8Mil(300k * 6) series, total data points in 30 minutes is around 1.8Mil * 30 * 2 = 108Mil (sample every 30s). This value is much less than the configured -search.maxSamplesPerQuery=2000000000 samples.
> 
> `-search.maxSamplesPerQuery` not only counts samples that match the query time range, as the samples could be highly compressed in one data part and vmselect needs to unpack the entire part. see [#5851 (comment)](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5851#issuecomment-2187727458) for details.

Thanks for explain. Is there a way to config how many datapoints could be merged into one block? Some times a user only want to query data in half one hour (30 ~ 60 points per series), but VM select reads 8192 points (one block), which is 100x data points than needed, and this limit the unique series could be read in one query to a few hundred thousands. 

This also cause another problem, one query may success but the same query with same duration different start time may fail, as the failed one matches two data blocks which requires more data points to read and exceeds the limit. This is very wired from user's view.

**Comment by vanliu-tx** [comment]
@Haleygo Is there a way to configure the max data point count in a block?

**Comment by Haleygo** [comment]
> @Haleygo Is there a way to configure the max data point count in a block?

I'm afraid it's not configurable, each block contains up to 8K [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) for better compression performance.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8bc30b68cd181d5880a62da1ba5ed4696b4c58cc/lib/storage/block.go#L14-L15

**Comment by vanliu-tx** [comment]
> > @Haleygo Is there a way to configure the max data point count in a block?
> 
> I'm afraid it's not configurable, each block contains up to 8K [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) for better compression performance.
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8bc30b68cd181d5880a62da1ba5ed4696b4c58cc/lib/storage/block.go#L14-L15

In my opinion, this should be a configurable args for the user to better trade off storage cost and query cost.

**Comment by Haleygo** [comment]
>In my opinion, this should be a configurable args for the user to better trade off storage cost and query cost.

If the `maxRowsPerBlock` can be changed, it will be applied to only new blocks, so it can't help users to query historical data. And compare to the query cost of changing `-search.maxSamplesPerQuery`, the storage cost of changing `maxRowsPerBlock` is much harder to understand and evaluate.

**Comment by xiaozongyang** [comment]
I met same issue, and my vmstorage version is `vmstorage-20230910-140729-tags-v1.93.4-cluster-0-ge8164968e`.

In my case, when I query all node cpus of the whole cluster in past two hours, vmselect will return normal result. But when I run the same query and the time range size but on the day before yesterday data, I meet the same error. Here is the error message  `422 error occured during search: cannot fetch query results from vmstorage nodes: cannot perform search on vmstorage 10.1.10.205:8401: cannot execute funcName="search_v7" on vmstorage "10.1.10.205:8401": cannot process MetricBlock #1: cannot select more than -search.maxSamplesPerQuery=1000000000 samples; possible solutions: to increase the -search.maxSamplesPerQuery; to reduce time range for the query; to use more specific label filters in order to select lower number of series `.

**Comment by xiaozongyang** [comment]
@valyala @hagen1778 Do you have some suggestions about this issue?

**Comment by xiaozongyang** [comment]
In my case, I found out limited my query is `1 - sum(rate(node_cpu_seconds_total{mode="idle"}[1m]) / sum(rate(node_cpu_seconds_total[1m]))`, the cardinarity of `node_cpu_seconds_total` is 106272, query range is 1h, scrape interval is 15s, so the scanned samples should be `106272 * 60 * 60 / 15 = 25505280`, when we do rate with 1m, we scan 4x samples which is `25505280 * 4 = 102021120 > 1e8`.

I hope to provide you with some ideas, @vanliu-tx

**Comment by xiaozongyang** [comment]
more feedback tody.

Today(2024-09-27) query return reuslt, the actual query range is `2024-09-27 11:21:01 - 2024-09-27 11:51:02, step=30s`
![Clipboard_Screenshot_1727409272](https://github.com/user-attachments/assets/4ad7eaff-315c-4045-8615-fc3cafba00ce)

Yesterday query reach the limit 
![Clipboard_Screenshot_1727409301](https://github.com/user-attachments/assets/053f02dc-a6ea-4c9e-8689-1ee5863b4412)

**Comment by xiaozongyang** [comment]
![Clipboard_Screenshot_1727411437](https://github.com/user-attachments/assets/6742894f-20e5-4d11-9bb6-084f0889f860)
I see this code in `netstorage.go:1692`, how do I ensure the matched samples number in the block and the blockCount?

cc @valyala @hagen1778

**Comment by xiaozongyang** [comment]
Thanks for your exaplaining! @hagen1778
