### ISSUE TITLE
victorialogs: introduce new API /select/logsql/stats_query

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6942]
Introduce an additional [query API ](https://docs.victoriametrics.com/victorialogs/querying/#http-api)in VictoriaLogs like `/select/logsql/stats_query`.
The new API should signify the need to use [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe) in the query passed to this handler. And validate queries and translate responses to VictoriaMetrics style with explicit properties and values.

The new HTTP API handler must accept the following query args:
* query - [LogsQL query](https://docs.victoriametrics.com/victorialogs/logsql/) with [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe)
* time - query evaluation timestamp

The new API will be utilized by vmalert for alerting and recording rules. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6706

**Comment by valyala** [comment]
FYI, the `/select/logsql/stats_query` endpoint for VictoriaLogs has been added in the commit c9bb4ddeed6f6e8463bab9854b4565d7f788719a . See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-stats) for details.

**Comment by valyala** [comment]
The [`/select/logsql/stats_query` endpoint](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-stats) is available in VictoriaLogs starting from [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the feature request as done.
