### ISSUE TITLE
victorialogs: introduce new API /select/logsql/stats_query_range

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#6943]
Introduce an additional [query API ](https://docs.victoriametrics.com/victorialogs/querying/#http-api) in VictoriaLogs `/select/logsql/stats_query_range`.
The new API should signify the need to use [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe) in the query passed to this handler. And validate queries and translate responses to VictoriaMetrics style with explicit properties and values.

The new HTTP API handler is very similar to [/stats_query](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6942) must accept the following query args:
* query - [LogsQL query](https://docs.victoriametrics.com/victorialogs/logsql/) with [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe)
* start - query start evaluation timestamp
* end - query end evaluation timestamp
* step - aggregation step for results

The new API will be utilized by VictoriaLogs Datasource for time series panel, and by vmalert for alerting and recording rules backfilling. See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6706 and https://github.com/VictoriaMetrics/victorialogs-datasource/issues/61

**Comment by valyala** [comment]
The `/select/logsql/stats_query_range` endpoint is implemented in the commit 0a40064a6fa64f9d3e3ae60f6f12a9584dce459d . See [these docs](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats) for details.

**Comment by valyala** [comment]
The [`/select/logsql/stats_query_range` endpoint](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats) is available in VictoriaLogs starting from [v0.29.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the feature request as done.
