### ISSUE TITLE
Updating 1 of 5 VMSTORAGE nodes (/downtime) can cause that node to have only a partial data for customers.

### ISSUE THREAD

**Issue by vhajdukd** [VictoriaMetrics/VictoriaMetrics#6953]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Imagine a situation you have to patch one vmstorage (for example migrating it to bigger vm instance type), it goes down for ~5 min, as vmselect picks for queries a random storage node, for some customers the data retrieved can be partial.

Is that expected behaviour of running VM in cluster mode ? How can I minimize or completely eliminate the possibility of partial data being returned from nodes that go through maintenance ?

More or less - How can I ensure completeness of the data returned by queries in case one of multiple vmstorage nodes goes down for some time ? lets assume my replicationFactor is N (N=number of vmstorage nodes)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

ps This is a question in regards to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/188#issuecomment-534464347, coz Im not sure whether this design decision was changed later or not (google doesnt help).

**Comment by tiny-pangolin** [comment]
the way to solve this is to set `-replicationFactor=2` on vmselect and vminsert. vmselect will aggregate and de-duplicate results from all storage nodes and return the result to the user. So a replication factor of 2 will provide full results if any 1 storage node is unavailable, but this means you will  storing each sample twice. If you need to tolerate more storage node failures replication factor can be set higher.

**Comment by vhajdukd** [comment]
Please consider this case:

- vminsert writes to two vmstorage nodes (replicationFactor=2)
- vmstorage#1 goes down for one hour
- vminsert writes to the same two vmstorage nodes, but one of them is down
- vmstorage#1 goes online again, but has no data for the past 1 hour due to the lack of replication between nodes (no data consistency is kept in "cluster")
- vmselect is configured to read from both vmstorages

How will vmselect know which de-duplicated data to choose ? This is the part I'm missing. It's not specified in the documentation.

**Comment by vhajdukd** [comment]
Where can I read about vmselect de-duplication from multi vmstores ?

**Comment by vhajdukd** [comment]
Seems the issue is somehow mitigated Ill test locally to confirm.
