### ISSUE TITLE
Doubts about the disableRerouting parameter

### ISSUE THREAD

**Issue by snakorse** [VictoriaMetrics/VictoriaMetrics#6962]
### Is your question request related to a specific component?

vminsert of the cluster version

### Describe the question in detail

I have some doubts about the impact of the disableRerouting parameter on vminsert writing data. As I understand it, when disableRerouting=false, if a certain vmstorage node (hereinafter referred to as node1) writes slowly (that is, the buffer of the corresponding node is full), each series in the currently written data packet will be rerouted. The rerouting logic is as follows:
1. Exclude nodes in the not ready state and the current node (node1), and recalculate the jump consistent hash for the remaining storage nodes to obtain a new node (hereinafter referred to as node2).
2. Try to send the current series to the buffer of the newly selected storage node (node2).
3. If the buffer of the newly selected storage node (node2) is also full, return to step 1.
 My question is: regarding the situation in step 3 above, if the new node (node2) is also slow, then in the next round of the loop, shouldn't node2 be further excluded in order to further try other nodes? That is, the location of the following code segment https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cad236003b05c1b2a3470b735c17db1587045628/app/vminsert/netstorage/netstorage.go#L722 
It seems that for the same piece of data, each time in a loop, it will always only be rerouted to node2. Is this a bug or is there some other consideration that I didn't notice?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
> shouldn't node2 be further excluded in order to further try other nodes

I think this description is not correct.

The following line will re-generate `idxsExclude` list.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/353766061bf1fe5d394530f769a0964c0bf0527b/app/vminsert/netstorage/netstorage.go#L726

**Comment by snakorse** [comment]
@jiekun Thank you for your response. I agree when the newly selected nodw(node2) is not in a ready state, it will enter the code branch you mentioned to further exclude that node (node2). However, if the new node(node2) is just a bit slow(buffer full) but still in a ready state, I think the recalculation of excludeIds will not be performed, so in the next round, that node (node2) will still be the target node for rerouting, and this is where my doubt arises.

**Comment by snakorse** [comment]
I think I have found the design consideration behind this code: in order to reduce the scope of rerouting-storm, [the related issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1054#issuecomment-1031545916)
