### ISSUE TITLE
VictoriaLogs 0.29 and VictoriaMetrics 1.103.0 version components don't work on Windows 10/11

### ISSUE THREAD

**Issue by the-goodies** [VictoriaMetrics/VictoriaMetrics#6973]
### Describe the bug

When I start VictoriaLogs, it prints the following and immediately exits:
```
C:\Users\User\Desktop\victoria-logs-windows-amd64-v0.29.0-victorialogs>victoria-logs-windows-amd64-prod.exe
2024-09-10T09:08:56.525Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version: victoria-logs-20240908-191531-tags-v0.29.0-victorialogs-0-gfb339d7574
2024-09-10T09:08:56.525Z        info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2024-09-10T09:08:56.525Z        info    VictoriaMetrics/app/victoria-logs/main.go:42    starting VictoriaLogs at "[:9428]"...
2024-09-10T09:08:56.525Z        info    VictoriaMetrics/app/vlstorage/main.go:62        opening storage at -storageDataPath=victoria-logs-data
2024-09-10T09:08:56.526Z        info    VictoriaMetrics/lib/memory/memory.go:42 limiting caches to 20514648883 bytes, leaving 13676432589 bytes to the OS according to -memory.allowedPercent=60

C:\Users\User\Desktop\victoria-logs-windows-amd64-v0.29.0-victorialogs>
```
Version 0.28 works fine.

### To Reproduce

Download [victoria-logs-windows-amd64-v0.29.0-victorialogs.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v0.29.0-victorialogs/victoria-logs-windows-amd64-v0.29.0-victorialogs.zip) on Windows machine, extract and run the binary.

### Version

victoria-logs-20240908-191531-tags-v0.29.0-victorialogs-0-gfb339d7574

**Comment by f41gh7** [comment]
It could be related to the golang runtime 1.23 upgrade.

**Comment by f41gh7** [comment]
Other components (1.103.0 version) are also broken with golang 1.23.

**Comment by the-goodies** [comment]
Now works well. Thank you.

**Comment by Munsio** [comment]
@f41gh7 I can see that the `victoria-metrics` assets got updated but I am still missing the `vmutils` assets for windows on 1.103
As we are using the github assets for the Chocolatey Windows package this is now crashing for us.

Could you be so kind to upload those too again!?

**Comment by f41gh7** [comment]
> @f41gh7 I can see that the `victoria-metrics` assets got updated but I am still missing the `vmutils` assets for windows on 1.103 As we are using the github assets for the Chocolatey Windows package this is now crashing for us.
> 
> Could you be so kind to upload those too again!?

 Fix will be included into the v1.104 release. We expect it soon. 

Meanwhile, it's possible to build `vmutils` from source https://docs.victoriametrics.com/#how-to-build-from-sources

**Comment by valyala** [comment]
FYI, VictoriaLogs build for Windows should work without issues starting from [v0.30.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) release.

**Comment by hagen1778** [comment]
VictoriaMetrics builds for Windows should work without issues starting from [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040), [LTS v1.102.3](https://docs.victoriametrics.com/changelog/#v11023) and [LTS v1.97.8](https://docs.victoriametrics.com/changelog/#v1978) releases.
