### ISSUE TITLE
VictoraLogs will support logs to metric ?

### ISSUE THREAD

**Issue by homerzhou** [VictoriaMetrics/VictoriaMetrics#6974]
### Describe the solution you'd like

convert log to metric
like fluentbit log_to_metrics: https://docs.fluentbit.io/manual/pipeline/filters/log_to_metrics
like logstash Metrics filter plugin: https://www.elastic.co/guide/en/logstash/current/plugins-filters-metrics.html

**Comment by tiny-pangolin** [comment]
We are working on adding logsql support to vmalert so logsql query results can be stored as metrics. Please look at #6706 for details.

**Comment by Haleygo** [comment]
@homerzhou 
Please check [/select/logsql/stats_query](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-stats) and [/select/logsql/stats_query_range](https://docs.victoriametrics.com/victorialogs/querying/#querying-log-range-stats) APIs, both of them return log stats for the given [query](https://docs.victoriametrics.com/victorialogs/logsql/) in the format compatible with [Prometheus querying API](https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries).
