### ISSUE TITLE
Flaky test: TestStorageRotateIndexDB

### ISSUE THREAD

**Issue by rtm0** [VictoriaMetrics/VictoriaMetrics#6977]
### Describe the bug

The `TestStorageRotateIndexDB` unit test located in `lib/storage/storage_test.go` fails from time to time. The failure is mainly noticed when the PR is submitted for review and the test actions are run. Examples:

- https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/9897475061/job/27342086170
- https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/10540667325/job/29205599007

Failures like this make the results of the test actions less reliable and may lead to less attention to be paid to them.

### To Reproduce

Locally:

```shell
while true; do go test ./lib/storage -run TestStorageRotateIndexDB -count 1; done
```

It will fail eventually.

### Version

`master` branch

### Logs

See example links from the description.

**Comment by hagen1778** [comment]
Since https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7267 was merged I'm closing this ticket. Thanks!
