### ISSUE TITLE
vmagent: support trimming trailing \n in `-remoteWrite.bearerTokenFile`

### ISSUE THREAD

**Issue by meysam81** [VictoriaMetrics/VictoriaMetrics#6986]
Now, the title of this issue may be a bit click baity but I promise you I'm not trying to deceive the feed algorithms :sweat_smile: 

I have spent a full day trying to understand why my `vmagent` was acting differently in the following scenarios:

1. `vmagent -remoteWrite.bearerTokenFile=/path/to/token` will NOT work if the `/path/to/token` includes a trailing `\n` character. :x: 
2. `vmagent -remoteWrite.bearerToken="$(cat /path/to/token)"` WILL work because it's already trimming the trailing `\n` character anyway.

I know the cause of this because I built the `vmagent` using `make vmagent-linux-amd64` command and upon printing the `token` to the screen, I realized the trailing `\n` in the case of `-remoteWrite.bearerTokenFile` is NOT removed.

This is the offending line:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/e92f347336f9cbe23c5b5fd622bc69ccafb83242/lib/promauth/config.go#L802

The fix is quite simple really and I would happily contribute if you confirm this issue is indeed an issue.

Adding the following line will make it work like a charm.

```go
token = strings.TrimSpace(token)
```

P.S. Thanks for the great product BTW. I love it. And I even wrote about it [here](https://developer-friendly.blog/blog/2024/06/17/unlocking-the-power-of-victoriametrics-a-prometheus-alternative/).

**Comment by jiekun** [comment]
I appreciate your report and would like to label it as an `enhancement`. Your code guide should be sufficient for newcomers to improve it, making it a `good first issue`.

Additionally, thank you for the excellent article you wrote introducing the VictoriaMetrics ecosystem.

**Comment by f41gh7** [comment]
VictoriaMetrics reads secret values from files as is. It's expected behavior. Previously, it did trim of trailing spaces and it had a lot of confusion for users.

 See this PR with detailed explanation: 

https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6503

**Comment by meysam81** [comment]
@f41gh7


Here's a more fluent and polished version of your text:

---

I understand that I’m not your only user and that you have other community members and paying customers to assist. However, handling the bearer token file and trimming spaces is quite a basic behavior. Don’t just take my word for it—have a look at the `promtail` code here:

https://github.com/grafana/loki/blob/2bde071872fd08c138e03535b520ff7ae32dd336/pkg/logcli/client/client.go#L414

I use Promtail for logging and VictoriaMetrics for my metrics. It was surprising to see that Promtail handles the same bearer-token-file without issue, while I’m encountering an `invalid header for "Authorization"` error in the `net/http` package when used in `vmagent`.

**Comment by f41gh7** [comment]
Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6947

**Comment by f41gh7** [comment]
I understand that, thanks for your input. We'll discuss it and maybe revert related Pull request.

**Comment by meysam81** [comment]
To help with the final decision-making, here's the RFC 7230 explicitly indicating that newline characters in header field values are not allowed<sup>[1]</sup>:

> A sender MUST NOT generate a message that includes
   line folding (i.e., that has any field-value that contains a match to
   the obs-fold rule) unless the message is intended for packaging
   within the message/http media type.

That is to say, no header value can have `\n` in its value, and both `-remoteWrite.bearerTokenFile` and the `-remoteWrite.basicAuth.passwordFile` are ultimately included in the HTTP header `Authorization: Basic/Bearer ${value}` and that is, as specified by the mentioned RFC, not allowed to have breaklines in them.

[1]: https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.4

**Comment by f41gh7** [comment]
Update from our side, behavior will be reverted to the previous state. We also will add a new flag to switch to the current behavior.  cc @zekker6

**Comment by valyala** [comment]
FYI, the commit 3bbb2aed7255666da611a91fc9e03915acea9d78 returns back trimming trailing whitespace in password files, which are read by `vmagent` and other VictoriaMetrics components. This commit will be included in the next release.

**Comment by hagen1778** [comment]
This change was included into [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040).
