### ISSUE TITLE
`v1.97.x` docker image is perhaps needed.

### ISSUE THREAD

**Issue by changshun-shi** [VictoriaMetrics/VictoriaMetrics#6991]
### Is your question request related to a specific component?

image since 1.97.x LTS.

### Describe the question in detail

Hello, everyone. I'd like to update my VictoriaMetrics version from 1.93.x to 1.97.x. Unfortunately, I found the image is not supported since v1.97.1-cluster. I found some reason from https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6005 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5811. I don't think it's a perfect decision. It breaks the **_`LTS`_** agreement and it prevented me upgrade my version to `1.97.x` .
As mentioned, I can still use 1.93.x. But i can not use the new feature even more without self maintained version because I don't know which version is stable.
So keep building image for LTS is really needed, Thank you.

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi.

Please see: https://github.com/VictoriaMetrics/VictoriaMetrics/commit/45f53748fff231a22e52db4f040f9feb7fe4eecc
and discussion here: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1725017520503779

**Comment by changshun-shi** [comment]
Thank for reply. However, noting at changlog in LTS version that which `latest available releases` is equals to this LTS version in bugfix is better.
