### ISSUE TITLE
operator: no matches for kind "PodDisruptionBudget"

### ISSUE THREAD

**Issue by emreberber** [VictoriaMetrics/VictoriaMetrics#6994]
### Describe the bug

 
```
 Warning  ReconcilationError  <unknown>  victoria-metrics-operator  no matches for kind "PodDisruptionBudget" in version "policy/v1"
```
Sometimes I get this error. Why is this happening even though PDP `enabled: false` in Values?

Kubernetes version may not match, but it does not always give this error

### To Reproduce

Helm Upgrade vmagent.

### Version

v1.102.1

**Comment by f41gh7** [comment]
It could happen at kubernetes clusters before 1.21 version during CRD objects delete operations.

 We should add fix for that by suppressing this error.

**Comment by emreberber** [comment]
Thanks for your support,

I have `cleanupCRD false`, are you talking about deleting another / which CRD ?

Also, does this prevent the Pod from occurring or is it really a warning message?

**Comment by f41gh7** [comment]
It shouldn't block pod creation. Could you please check the following:
1) was vmagent deployment created?
2) is there anything at `kubectl -n NS get events` output? 
3) Which is kubernetes and operator versions?

**Comment by emreberber** [comment]
In my scenario there is no problem with a new installation but whenever I want to update VMAgent with Helm it seems to delete the StatefulSet but not create a new one.

**Events**

```
❯ kubectl get events -n monitoring
4m11s       Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
2m11s       Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
3m47s       Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
4m14s       Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
4m3s        Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
4m12s       Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
3m15s       Warning   ReconcilationError   vmagent/victoria-metrics-agent         no matches for kind "PodDisruptionBudget" in version "policy/v1"
```

VMAgent Deployment

```
❯ kubectl get vmagent -A -o wide                                                                                                                                                                                        13:41:40 kubernetes-admin@d-platform-p1-1mars/default
NAMESPACE    NAME                     SHARDS COUNT   REPLICA COUNT   STATUS
monitoring   victoria-metrics-agent   1              1               operational
```


- Kubernetes Cluster Version is **1.20**
- VMAgent Operator Version is **v0.47.0**


Kube Controller Manager

```
stateful_set.go:419] StatefulSet has been deleted monitoring/vmagent-victoria-metrics-agent
```


When I remove VMAgent's finalizers, the automatic vmagent deployment is deleted and after sync operation it's running along with the new vmagent.

**Comment by Dentrax** [comment]
It seems there should be a [check here](https://github.com/VictoriaMetrics/operator/blob/fe90f57a10f30cd5fcdfe6c35099cb41cae99db9/internal/controller/operator/factory/finalize/vmalertmanager.go#L40-L42) if `cr.Spec.VMSelect.PodDisruptionBudget != nil`, on all finalizers. Since `apps.victoriametrics.com/finalizer` is set.

**Comment by f41gh7** [comment]
That correct, on object deletion, operator removes finalizers and free all possibly created child objects. Such as hpa, service, pdb and other. At 1.20 version pdb is still beta and there is no v1 API for it. 

 At the next operator release there will be check for missing API and it should resolve this error.

**Comment by Dentrax** [comment]
Thanks Nikolay, we've worked on a fix and submitted a PR here: https://github.com/VictoriaMetrics/operator/pull/1109 (Tested on our clusters and can confirm it works!)
