### ISSUE TITLE
Add support for metrics' insertion via Graphite protocol

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#7]
### The issue

Many users want switching from Graphite to Prometheus, since Prometheus has better [query language](https://prometheus.io/docs/prometheus/latest/querying/basics/), has better support for [metric labels](https://prometheus.io/docs/concepts/data_model/) and has better storage for high metric volumes. But these users don't want switching from Graphite-compatible agents to Prometheus exporters.

### The solution

Add support to VictoriaMetrics for metrics' insertion via [Graphite protocols](https://graphite.readthedocs.io/en/latest/feeding-carbon.html), so the Graphite data stored in VictoriaMetrics could be queried via PromQL.

**Comment by valyala** [comment]
Single-server VictoriaMetrics [v1.6.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.6.0)+ accepts Graphite plaintext protocol messages if `-graphiteListenAddr` flag is set.

It is unclear how to add support for Graphite protocol in the SaaS version, since the protocol has no authorization fields :(

**Comment by tenmozes** [comment]
implemented
