### ISSUE TITLE
Does vmStorage support data aggregation?

### ISSUE THREAD

**Issue by yudelin** [VictoriaMetrics/VictoriaMetrics#7010]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

Does vmstorage Support Aggregate Processing of Data Beyond the Retention Period? For example, if the CPU usage exceeds 1 week or more, 60 pieces of data will be generated every hour, but now 3 pieces of data will be generated after aggregation, which are the average, max, and min of this metric, which can reduce disk usage as much as possible and save the data for a longer period

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Basically vmstorage only responsible for storing raw data (blocks). Data aggregation are done by vmselect during query, or vmagent during data ingestion pipeline. And for your case, it sounds stream aggregation could help. See: https://docs.victoriametrics.com/stream-aggregation/

**Comment by hagen1778** [comment]
> Does vmstorage Support Aggregate Processing of Data Beyond the Retention Period? For example, if the CPU usage exceeds 1 week or more, 60 pieces of data will be generated every hour, but now 3 pieces of data will be generated after aggregation, which are the average, max, and min of this metric, which can reduce disk usage as much as possible and save the data for a longer period

The vmstorage itself supports only downsampling - see https://docs.victoriametrics.com/#downsampling
It allows to reduce number of datapoints per series after specified time interval. But it doesn't support any aggregations.

The aggregation can be achieved only on ingestion time via [recording rules](https://docs.victoriametrics.com/vmalert/#downsampling-and-aggregation-via-vmalert) or via [stream aggregation](https://docs.victoriametrics.com/stream-aggregation.html), as @jiekun mentioned.

See also https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2739 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/627

**Comment by yudelin** [comment]
Stream-aggregation doesn't seem to meet my needs. My needs are:
1. There is no need to set aggregation rules, for example, there are 20,000 indicators in Prometheus, and I need to set all 20,000 indicators to avg, max, and min
2. I need to save the original data for 1 month, and the data for more than 1 month is aggregated, and this aggregation does not need to be configured.
My current scenario is:
1. Use the VictoriaMetrics cluster to directly connect to the remote_write of prometheus to save one month's raw data
2. The second remote_rewrite of Prometheus is to aggregate min, max, and avg to a self-developed VMagent-like program every hour (this custom aggregation cycle). and set the label of the corresponding aggregate function to be added to the time series database. Write data to another VictoriaMetrics cluster, and the secondary cluster retains the data for 2 years
3. The promsql query distinguishes between the original data and the trend data, and corresponds to the aggregate function in the second step
I would like to ask, is the above solution feasible? If feasible, how can retentionPeriod distinguish between the retention period of the two parts of the data, the original data is stored for 1 month, and the aggregated data is stored for 2 years. Can this only be achieved by deploying two VictoriaMetrics clusters?
