### ISSUE TITLE
VictoriaLogs: add auto refresh in UI

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#7017]
### Is your feature request related to a problem? Please describe

Hi,
Thanks for a great product

It would be very nice if you added auto refresh in UI for Vlogs as sometimes you need to check or like live stream logs aka tail and each time press button or refresh page it's bad user experience

### Describe the solution you'd like

VMUI has already this feature
![screenshot-000339@2x](https://github.com/user-attachments/assets/19a26f26-9c3c-4ccc-8dd1-5a67f8ff3851)

**Comment by hagen1778** [comment]
@Loori-R, if you ever after this, it is likely VictoriaLogs supports more efficient way to show newer logs - [live tailing](https://docs.victoriametrics.com/victorialogs/querying/#live-tailing). Can we use it in vmui?

**Comment by valyala** [comment]
Live tailing is good for looking for the stream of logs. It isn't good for showing a bar chart of matching logs at the top of the list of logs. Live tailing also doesn't work for [stats pipe](https://docs.victoriametrics.com/victorialogs/logsql/#stats-pipe). So it is better to re-execute the same query for sliding window time range based on the selected refresh interval.

As for [the live tailing](https://docs.victoriametrics.com/victorialogs/querying/#live-tailing), it would be great to have an additional tab view for live tailing in [web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui). If the user selects live tailing tab, then logs must be streamed there.

**Comment by hagen1778** [comment]
@yuriydzobak https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7038 has been merged and will be available in the next release. This ticket will be closed once the release is published.

**Comment by hagen1778** [comment]
> As for [the live tailing](https://docs.victoriametrics.com/victorialogs/querying/#live-tailing), it would be great to have an additional tab view for live tailing in [web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui). If the user selects live tailing tab, then logs must be streamed there.

@valyala @Loori-R I moved this to a separate feature request https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7046

**Comment by valyala** [comment]
VictoriaLogs web UI gained support for auto-refresh starting from [v0.30.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) release. Closing the feature request as done.
