### ISSUE TITLE
VIctoriaLogs Retention Period by streams 

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#7020]
### Is your feature request related to a problem? Please describe

Hi,
Thanks for a great product!

It would be nice if Vlogs has extra parameter to configure retentions period by streams and some API, etc to remove logs what you want

For example if you have single Vlogs  but some streams you don't need to keep the general retantion Period 1 year and what to have only keeps streams with source:foo 7 days 
How it could be remove old logs manually, like i want remove all logs with stream or stream_id in Vlogs

It would be nice if Vlogs had an additional parameter to configure retention periods for streams, as well as an API to remove specific logs because create each time seperate Vlogs isn't good solution

### Describe the solution you'd like

- Add an extra flag for Vlogs to configure the retention period by stream label.
- Create the ability to remove old logs in Vlogs via API or provide documentation on how to do

**Comment by valyala** [comment]
Closing this feature request as duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6709
