### ISSUE TITLE
delete series API leads to OOM kill on cluster version

### ISSUE THREAD

**Issue by dmitryk-dk** [VictoriaMetrics/VictoriaMetrics#7027]
### Describe the bug

After calling the delete series API (api/v1/admin/tsdb/delete_series), one storage node was killed by OOM.
There are some graphs describing the bug 

<img width="887" alt="Screenshot 2024-09-17 at 11 46 14" src="https://github.com/user-attachments/assets/85de4d4c-eeca-4397-ab3f-d1615f096d1f">

<img width="886" alt="Screenshot 2024-09-17 at 11 48 39" src="https://github.com/user-attachments/assets/4cb56613-dc7b-451b-aaae-448467d6f558">

<img width="877" alt="Screenshot 2024-09-17 at 11 50 36" src="https://github.com/user-attachments/assets/79f1615d-ead9-47ac-b5f3-7606c15769b1">

### To Reproduce

Ingest high cardinality metrics and try to delete that metric by using the `api/v1/admin/tsdb/delete_series`. 
After the usage of this API endpoint, the memory usage increased from 3.08GB to 4.27GB, which led to OOM kill.

### Version

All components has v1.101.0-enterprise-cluster

### Logs

[WARN]  slow query according to -search.logSlowQueryDuration=5s: remoteAddr="addr_1:53608", duration=5.441 seconds; requestURI: "/delete/1/prometheus/api/v1/admin/tsdb/delete_series?match%5B%5D=my_test_metric"

2024-09-16T19:44:31.137Z  [WARN]  remoteAddr: "addr_1:53608"; requestURI: /delete/1/prometheus/api/v1/admin/tsdb/delete_series?match%5B%5D=my_test_metric; cannot delete time series: cannot delete time series on all the vmstorage nodes: cannot obtain connection from a pool: cannot dial vmstorage-storage-1-blue-2.vmstorage-storage-1-blue:8401: dial tcp4 addr1:8401: connect: connection refused

**Comment by rtm0** [comment]
Also was able to reproduce in single-node in `master` branch. To fix that, I am going to introduce a command line flag that limits the number of time series to delete at once.

**Comment by hagen1778** [comment]
This change was released in [v1.104.0](https://docs.victoriametrics.com/changelog/#v11040).
