### ISSUE TITLE
Are vmbackup/vmrestore tools really needed for fs:// storage?

### ISSUE THREAD

**Issue by Monstrofil** [VictoriaMetrics/VictoriaMetrics#703]
Hi, I just wanna make sure that I'm not missing something in my thoughts.

There are tools written specially for backup/restore of victoriametrics:
- https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/vmbackup
- https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/vmrestore

Both of them support local filesystem folder as target, but what I found is that result of these two commands:
```
# ./vmbackup-prod -storageDataPath /mnt/vmstorage -snapshotName HERE_IS_SNAPSHOT_NAME -dst fs:///root/backup_vmbackup
# ./vmrestore-prod -src fs:///root/backup_vmbackup/ -storageDataPath /root/backup_restored
```

is identical to simple rsync:
```
# rsync -L -r  /mnt/vmstorage/snapshots/HERE_IS_SNAPSHOT_NAME/ /root/backup_rsync
```
Here is diff result:
```
# diff -qr /root/backup_vmrestored/ /root/backup_rsync/
Only in /root/backup_rsync/data: big
Only in /root/backup_vmrestored/: flock.lock
```

Does that mean that for local fs I can get rid of vmbackup and vmrestore tools and just use rsync to copy snapshots instead? Am I right that vmbackup/vmrestore main purpose is copying data to s3/gcs, not local fs?

**Comment by anjakefala** [comment]
My understanding is that the `rsync --delete` flag is important! MergeTree structures may delete files over time, and you do not want those to stick around in your backup.
