### ISSUE TITLE
VictoriaLogs: Missing otel resource.attributes and attributes in otel formatted logs

### ISSUE THREAD

**Issue by nickytd** [VictoriaMetrics/VictoriaMetrics#7032]
### Describe the bug

A sample [docker compose - gist](https://gist.github.com/nickytd/af87954b5216f5e4d32bfe82bc3e8c36) environment demonstrates an issue with missing otel `Resource.Attributes` and `Attributes` in victorialogs backend.
The docker compose starts a fluent-bit, otel-collector and victorialogs and expects the victoria logs to contain in addition to the message in otel Body, the respective metadata such as `Resource.Attributes` and `Attributes`

### To Reproduce

To reproduce download locally the configuration files from [gist](https://gist.github.com/nickytd/af87954b5216f5e4d32bfe82bc3e8c36) 
docker-compose.yaml
collector.yaml
fluent-bit.yaml 

and execute 
```bash
docker compose up
```

The console shall contain the correct output from the otel-collector
```text
collector-1     | Resource SchemaURL:
collector-1     | Resource attributes:
collector-1     |      -> host.name: Str(b6a036ffa3a4)
collector-1     | ScopeLogs #0
collector-1     | ScopeLogs SchemaURL:
collector-1     | InstrumentationScope
collector-1     | LogRecord #0
collector-1     | ObservedTimestamp: 1970-01-01 00:00:00 +0000 UTC
collector-1     | Timestamp: 2024-09-17 15:40:20.718563921 +0000 UTC
collector-1     | SeverityText:
collector-1     | SeverityNumber: Unspecified(0)
collector-1     | Body: Str(dummy)
collector-1     | Attributes:
collector-1     |      -> origin: Str(localhost)
collector-1     | Trace ID:
collector-1     | Span ID:
collector-1     | Flags: 0
collector-1     | 	{"kind": "exporter", "data_type": "logs", "name": "debug"}
```

where the `Resource.Attributes` and `Attributes` are present

While the querying `victorialogs` backend does not show those fields
```bash
curl -sN http://localhost:9428/select/logsql/tail --data-urlencode 'query=(*)' | jq
```
...
```json
{
  "_time": "2024-09-17T15:42:51.713698213Z",
  "_stream_id": "0000000000000000ac79bb572cd666a6528b5f705d9b2982",
  "_stream": "{host.name=\"b6a036ffa3a4\",origin=\"localhost\"}",
  "_msg": "dummy",
  "host.name": "b6a036ffa3a4",
  "origin": "localhost",
  "severity": "Unspecified"
}
```

Here `_msg` field is correct but `resource.attributes` and `attributes` are missing.

### Version

fluent-bit: docker.io/fluent/fluent-bit:3.1.7
otel-collector: docker.io/otel/opentelemetry-collector:0.109.0
victorialogs: docker.io/victoriametrics/victoria-logs:v0.29.0-victorialogs

### Logs

No errors are present in the vicotrialogs output.

### Additional information

Thanks, pls let me know if anything else is needed.

**Comment by hagen1778** [comment]
@AndrewChubatiuk could you please take a look?

**Comment by f41gh7** [comment]
Looks like resource attributes:
```
 collector-1     | Resource attributes:
collector-1     |      -> host.name: Str(b6a036ffa3a4)
```
and  sample attributes:
```
collector-1     | Attributes:
collector-1     |      -> origin: Str(localhost)
```

 are the part of the stream field - ` "_stream": "{host.name=\"b6a036ffa3a4\",origin=\"localhost\"}",`

 According to the stream fields configuration https://gist.github.com/nickytd/af87954b5216f5e4d32bfe82bc3e8c36#file-collector-yaml-L13

**Comment by nickytd** [comment]
Thanks
A conceptual question, if we remove the 
```yaml
headers:
     VL-Stream-Fields: "origin,host.name"
```
then the we have `_stream:{}` and all logs will share the same `_stream_id`,
Will it be correct behaviour to add `Resource.Attributes` as stream fields by default (or by configuration)?
Usually the resource attributes will be used to filter the streams and logs with the same set of resource.attribute wshall naturally share the same `_stream_id`

**Comment by zekker6** [comment]
> Will it be correct behaviour to add Resource.Attributes as stream fields by default (or by configuration)?
Usually the resource attributes will be used to filter the streams and logs with the same set of resource.attribute shall naturally share the same _stream_id.

If I understood that correctly, a single logs source will have a unique set of `resource.attribute` during the lifetime of an application. If that is correct it matches with the suggestion for stream fields in the [documentation](https://docs.victoriametrics.com/victorialogs/keyconcepts/#how-to-determine-which-fields-must-be-associated-with-log-streams) and should be correct to use.

**Comment by nickytd** [comment]
Thanks Much appriciated.
