### ISSUE TITLE
vmselect: add support of SRV discovery for `-selectNode` flag

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/VictoriaMetrics#7040]
### Is your feature request related to a problem? Please describe

Currently it is not possible to automatically discover a list of vmselect nodes for `-selectNode` flag. Maintaining all nodes manually makes it fragile and more error prone.

### Describe the solution you'd like

It would be great if `-selectNode` supported SRV discovery similar to [discovery for `-storageNode` flag](https://docs.victoriametrics.com/cluster-victoriametrics/#automatic-vmstorage-discovery).

**Comment by f41gh7** [comment]
Hello, we decided to deprecate `selectNode` flag. 

 Instead new component `vmcache` will be introduced for caching query results. It will expose HTTP API for vmselect. It should eliminate need of vmselect awareness for each replica and simplify cache resets.

**Comment by hagen1778** [comment]
Closing as won't implement.
