### ISSUE TITLE
maxUniqueTimeseries error persists after using delete_series

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#706]
**Describe the bug**
We created a histogram metric with a high cardinality. When querying this series it returned the error: `the number of matching unique timeseries exceeds 300000; either narrow down the search or increase -search.maxUniqueTimeseries `

We have now lowered the cardinality for this histogram but it still returns the same error. I tried to delete the series (_bucket, _sum and _count) using `delete_series` API but it doesn't work. I also tried to purge the cache directory and call `/internal/resetRollupResultCache`, same result.

I tried to narrow down the time range and that didn't help either.

I would prefer to avoid increasing `-search.maxUniqueTimeseries`

The doc says that the delete happens asynchronously until the parts are merged. Could it be the reason? Is there any way to force a merge similar to the optimize call in Clickhouse?

**To Reproduce**
- Create a time series with high cardinality (more than `-search.maxUniqueTimeseries`)
- Delete this time series using the `delete_series` API 
- Query the time series using `query_range`

**Expected behavior**
- `-search.maxUniqueTimeseries` should take into account the time range when calculating the number of time series that will be returned.
- Deleted time series should not count towards the total number of unique time series that would be returned

**Version**
1.38.1

**Used command-line flags**
```
"bigMergeConcurrency" = "0"
"csvTrimTimestamp" = "1ms"
"dedup.minScrapeInterval" = "0s"
"deleteAuthKey" = "secret"
"denyQueriesOutsideRetention" = "false"
"enableTCP6" = "false"
"envflag.enable" = "false"
"envflag.prefix" = ""
"fs.disableMmap" = "false"
"graphiteListenAddr" = ""
"graphiteTrimTimestamp" = "1s"
"http.disableResponseCompression" = "false"
"http.maxGracefulShutdownDuration" = "7s"
"http.pathPrefix" = ""
"http.shutdownDelay" = "0s"
"httpAuth.password" = "secret"
"httpAuth.username" = ""
"httpListenAddr" = ":8428"
"import.maxLineLen" = "104857600"
"influxListenAddr" = ""
"influxMeasurementFieldSeparator" = "_"
"influxSkipMeasurement" = "false"
"influxSkipSingleField" = "false"
"influxTrimTimestamp" = "1ms"
"insert.maxQueueDuration" = "1m0s"
"loggerErrorsPerSecondLimit" = "10"
"loggerFormat" = "default"
"loggerLevel" = "INFO"
"loggerOutput" = "stderr"
"maxConcurrentInserts" = "64"
"maxInsertRequestSize" = "33554432"
"maxLabelsPerTimeseries" = "30"
"memory.allowedPercent" = "60"
"metricsAuthKey" = "secret"
"opentsdbHTTPListenAddr" = ""
"opentsdbListenAddr" = ""
"opentsdbTrimTimestamp" = "1s"
"opentsdbhttp.maxInsertRequestSize" = "33554432"
"opentsdbhttpTrimTimestamp" = "1ms"
"pprofAuthKey" = "secret"
"precisionBits" = "64"
"promscrape.config" = ""
"promscrape.config.dryRun" = "false"
"promscrape.config.strictParse" = "false"
"promscrape.configCheckInterval" = "0s"
"promscrape.consulSDCheckInterval" = "30s"
"promscrape.disableCompression" = "false"
"promscrape.disableKeepAlive" = "false"
"promscrape.discovery.concurrency" = "100"
"promscrape.discovery.concurrentWaitTime" = "1m0s"
"promscrape.dnsSDCheckInterval" = "30s"
"promscrape.ec2SDCheckInterval" = "1m0s"
"promscrape.fileSDCheckInterval" = "30s"
"promscrape.gceSDCheckInterval" = "1m0s"
"promscrape.kubernetesSDCheckInterval" = "30s"
"promscrape.maxScrapeSize" = "16777216"
"promscrape.suppressScrapeErrors" = "false"
"relabelConfig" = ""
"retentionPeriod" = "12"
"search.cacheTimestampOffset" = "5m0s"
"search.disableCache" = "false"
"search.latencyOffset" = "30s"
"search.logSlowQueryDuration" = "5s"
"search.maxConcurrentRequests" = "16"
"search.maxExportDuration" = "720h0m0s"
"search.maxLookback" = "0s"
"search.maxPointsPerTimeseries" = "30000"
"search.maxQueryDuration" = "30s"
"search.maxQueryLen" = "16384"
"search.maxQueueDuration" = "10s"
"search.maxStalenessInterval" = "0s"
"search.maxTagKeys" = "secret"
"search.maxTagValues" = "100000"
"search.maxUniqueTimeseries" = "300000"
"search.minStalenessInterval" = "0s"
"search.resetCacheAuthKey" = "secret"
"selfScrapeInstance" = "self"
"selfScrapeInterval" = "10s"
"selfScrapeJob" = "victoria-metrics"
"smallMergeConcurrency" = "0"
"snapshotAuthKey" = "secret"
"storageDataPath" = "/storage"
"tls" = "false"
"tlsCertFile" = ""
"tlsKeyFile" = "secret"
"version" = "false"
```

**Comment by valyala** [comment]
VictoriaMetrics maintains an index for fast searching of time series by the given label filters. The `-search.maxUniqueTimeseries` command-line flag is applied during search in this index. Index entries aren't removed after deleting time series via [delete API](https://victoriametrics.github.io/#how-to-delete-time-series) - they persist for at least `-retentionPeriod` months.

So, the workaround for your case is to increase `-search.maxUniqueTimeseries` in order to remove unneeded time series. After the deletion is complete the `-search.maxUniqueTimeseries` may be returned back to default values.

Let's keep this feature request open until better solution arises. For instance, creating separate limit for the maximum number of time series that could be removed via `delete API` at once.

**Comment by valyala** [comment]
Closing this issue as answered
