### ISSUE TITLE
vmalert: recording rules results aren't visible in database

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#7060]
### Describe the bug

After calculating metrics using recording, some metric data is displayed incorrectly and then is missing.

### To Reproduce

```
-datasource.lookback="1m0s"
-datasource.url="secret"
-remoteWrite.concurrency="8"
-remoteWrite.flushInterval="1m0s"
-remoteWrite.maxBatchSize="10000"
-remoteWrite.maxQueueSize="10000000"
-remoteWrite.url="secret"
-rule="/usr/local/vmagent/rules/*.yaml"
```
This is the startup parameter for vmalert, I use prometheus to collect data and write it to the vm cluster with a collection interval of 2 minutes, then read the data from the cluster, calculate it, and then write it to the cluster.

### Version

vmalert-20240214-141153-tags-v1.98.0-0-gbaaa88001

### Logs

[vmui_report_2024-09-20_075037.json](https://github.com/user-attachments/files/17072447/vmui_report_2024-09-20_075037.json)

![image](https://github.com/user-attachments/assets/43e8bd58-3373-4ee6-8400-1d44c01edfe4)

The data in red is the data for the calculated indicator, and the data in blue is the data queried directly using the calculated statement.

**Comment by AndrewChubatiuk** [comment]
hey @FengZh61 
Can you share recording rule you're using?

**Comment by FengZh61** [comment]
> hey @FengZh61 Can you share recording rule you're using?

```
(1-(sum(irate(node_cpu_seconds_total{mode='idle'}[5m]))by(ip,job,business_name,business_id,location_name,location_num,note,hostname,instance))/(sum(irate(node_cpu_seconds_total[5m]))by(ip,job,business_name,business_id,location_name,location_num,note,hostname,instance)))*100
```

**Comment by AndrewChubatiuk** [comment]
could you please share a whole rule section, which contains this expression from vmalert config?

**Comment by AndrewChubatiuk** [comment]
also could you clarify why there is one line per each set of labels, when your expression has multiple labels in by expr?

**Comment by FengZh61** [comment]
> could you please share a whole rule section, which contains this expression from vmalert config?

[node.recording.txt](https://github.com/user-attachments/files/17095324/node.recording.txt)

**Comment by FengZh61** [comment]
> also could you clarify why there is one line per each set of labels, when your expression has multiple labels in by expr?

I'm sorry I didn't understand what you meant.

**Comment by AndrewChubatiuk** [comment]
have you checked a alert state like it's described [here](https://docs.victoriametrics.com/vmalert/#alerts-state)?

**Comment by FengZh61** [comment]
> have you checked a alert state like it's described [here](https://docs.victoriametrics.com/vmalert/#alerts-state)? also please share vmalert logs

[alert.log](https://github.com/user-attachments/files/17106531/alert.log)
![rules](https://github.com/user-attachments/assets/94b42cb2-39e2-407b-beb5-cff51c8a8e7f)

**Comment by FengZh61** [comment]
> Reference in

![RW](https://github.com/user-attachments/assets/6f77bfb9-2310-4377-b8c6-86083c7f75d9)

**Comment by FengZh61** [comment]
> Hey @FengZh61 ! According to the screenshot, vmalert fetches 250k samples on each evaluation for the mentioned recording rule. Can you verify vmalert's logs or Grafana dash in RemoteWrite section to see if it sends results succesfully?

![RW](https://github.com/user-attachments/assets/f35c9280-c212-4399-923e-85454624abd3)

**Comment by FengZh61** [comment]
> Hey @FengZh61 ! According to the screenshot, vmalert fetches 250k samples on each evaluation for the mentioned recording rule. Can you verify vmalert's logs or Grafana dash in RemoteWrite section to see if it sends results succesfully?

How to see more detailed log content, I see the parameter -loggerLevel minimum level is info.

**Comment by FengZh61** [comment]
> If you don't see panel `Datapoints drop rate` showing drops, then all that data should be delivered and queryable at VictoriaMetrics side. Could you try exporting the raw data and check if it exists like suggested here https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results ?
> 
> Btw, I noticed that in your first message you query `node_cpu_idle_pct` record name. While on the [screenshot here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7060#issuecomment-2369912004) the record name is different `node_cpu_busy_pct`. Are you sure we're looking at the correct record?

Sorry, wrong screenshot.
![idel](https://github.com/user-attachments/assets/43576c42-de4e-4206-8a28-1340addc26dc)

I followed the documentation to troubleshoot the raw data

**Comment by hagen1778** [comment]
> I followed the documentation to troubleshoot the raw data

Did it show something. Or you're saying that you're going to do this?

>If you don't see panel Datapoints drop rate showing drops, then all that data should be delivered and queryable at VictoriaMetrics side

What about this?

**Comment by FengZh61** [comment]
> > I followed the documentation to troubleshoot the raw data
> 
> Did it show something. Or you're saying that you're going to do this?
> 
> > If you don't see panel Datapoints drop rate showing drops, then all that data should be delivered and queryable at VictoriaMetrics side
> 
> What about this?

[vmex.json](https://github.com/user-attachments/files/17127628/vmex.json)

This is the data I found from /api/v1/export, from the results returned to see, from 1726453860000 to start behind the data is not continuous, before the data is continuous, 2 minutes a data point, but these data, not accurate, on the line I posted above screenshots like, for the calculation of the promql and the calculation of the indicator after the data is a lot of difference.

**Comment by hagen1778** [comment]
> This is the data I found from /api/v1/export, from the results returned to see, from 1726453860000 to start behind the data is not continuous

Yes, data looks irregular. 

> If you don't see panel Datapoints drop rate showing drops, then all that data should be delivered and queryable at VictoriaMetrics side

What about this?

**Comment by FengZh61** [comment]
> > This is the data I found from /api/v1/export, from the results returned to see, from 1726453860000 to start behind the data is not continuous
> 
> Yes, data looks irregular.
> 
> > If you don't see panel Datapoints drop rate showing drops, then all that data should be delivered and queryable at VictoriaMetrics side
> 
> What about this? Do you observe drops on that panel on vmalert dashboard? Are any other recording rules behave similarly?

![drop](https://github.com/user-attachments/assets/e7e21bbc-8dd3-425e-8ad3-d1916a5a5587)

No data loss observed on vmalert panel.

In the node.cpu group, only the ```node_cpu_num record``` rule is normal, the others have problems. The recording rules for the other groups are also normal.

**Comment by hagen1778** [comment]
> In the node.cpu group, only the node_cpu_num record rule is normal, the others have problems. The recording rules for the other groups are also normal.

This is weird. I don't know what could be happening.
If vmalert reports it receives the samples and pushes them forward - those samples should be in database. Could you check if `vmalert_recording_rules_last_evaluation_samples` metric is stable for mentioned problematic rules?
Apart of that, have you tried restarting vmalert? Could you try updating to newer versions of vmalert?

**Comment by FengZh61** [comment]
> > In the node.cpu group, only the node_cpu_num record rule is normal, the others have problems. The recording rules for the other groups are also normal.
> 
> This is weird. I don't know what could be happening. If vmalert reports it receives the samples and pushes them forward - those samples should be in database. Could you check if `vmalert_recording_rules_last_evaluation_samples` metric is stable for mentioned problematic rules? Apart of that, have you tried restarting vmalert? Could you try updating to newer versions of vmalert?

[vmui_report_2024-09-26_083140.json](https://github.com/user-attachments/files/17145467/vmui_report_2024-09-26_083140.json)


The vmalert_recording_rules_last_evaluation_samples indicator is not stable, I have restarted vmalert and did not use the new version.

**Comment by hagen1778** [comment]
Did you observe any changes after restart? Could you try updating to newer version?
Apart of that I don't have other suggestions. Unless you can provide an example where this problem can be reproduced.

**Comment by FengZh61** [comment]
> Did you observe any changes after restart? Could you try updating to newer version? Apart of that I don't have other suggestions. Unless you can provide an example where this problem can be reproduced.

No change after reboot, I'll try a new version of vmalert.

**Comment by FengZh61** [comment]
> Did you observe any changes after restart? Could you try updating to newer version? Apart of that I don't have other suggestions. Unless you can provide an example where this problem can be reproduced.

I'm using 1.82 and 1.103 versions of vmalert and the data is fine, there may be some bugs in this version 1.98.

**Comment by hagen1778** [comment]
Okay, thanks. I'm closing this ticket then. Please, re-open if the issue will repeat.

**Comment by FengZh61** [comment]
> Okay, thanks. I'm closing this ticket then. Please, re-open if the issue will repeat.
Hi
Please reopen this issue,I'm having a similar problem.

**Comment by FengZh61** [comment]
> Okay, thanks. I'm closing this ticket then. Please, re-open if the issue will repeat.

Please reopen this issue,I'm having a similar problem.

**Comment by tiny-pangolin** [comment]
can you recreate the issue on the latest (v1.106.1) or a supported (LTS 1.102.6 or v1.97.11)?

**Comment by FengZh61** [comment]
> can you recreate the issue on the latest (v1.106.1) or a supported (LTS 1.102.6 or v1.97.11)?

Using version v1.106.1, same problem.
