### ISSUE TITLE
VMagent panics when high queues value is set but ulimit is default

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/VictoriaMetrics#707]
**Describe the bug**
VMagent panics when high queues value is set but ulimit is default

panic: runtime error: integer divide by zero

goroutine 5954 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.(*remoteWriteCtx).Push(0xc0001640c0, 0xc004cec000, 0x35, 0x400)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:240 +0x44a
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite.Push(0xc0007ad770)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:160 +0x1e7
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/graphite.insertRows(0xc01ff1e000, 0x35, 0x492, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/graphite/request_handler.go:61 +0x728
github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/graphite.ParseStream(0x7fd2a8d56160, 0xc001678040, 0xafb620, 0x0, 0x0)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/protoparser/graphite/streamparser.go:34 +0xad
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/graphite.InsertHandler.func1(0xc0005ea000, 0xc0008a6e20)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/graphite/request_handler.go:24 +0x3f
github.com/VictoriaMetrics/VictoriaMetrics/lib/writeconcurrencylimiter.Do(0xc0008a6f00, 0x40b5f5, 0xa4f120)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/writeconcurrencylimiter/concurrencylimiter.go:37 +0x2fc
github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/graphite.InsertHandler(0x7fd2a8d56160, 0xc001678040, 0xc001678040, 0x7fd2a8d56160)
	github.com/VictoriaMetrics/VictoriaMetrics/app/vmagent/graphite/request_handler.go:23 +0x5c
github.com/VictoriaMetrics/VictoriaMetrics/lib/ingestserver/graphite.serveTCP.func1(0xafb618, 0xba0980, 0xc001678040)
	github.com/VictoriaMetrics/VictoriaMetrics/lib/ingestserver/graphite/server.go:106 +0x8a
created by github.com/VictoriaMetrics/VictoriaMetrics/lib/ingestserver/graphite.serveTCP
	github.com/VictoriaMetrics/VictoriaMetrics/lib/ingestserver/graphite/server.go:104 +0x91

**Comment by valyala** [comment]
This panic is possible only if `-remoteWrite.queues` command-line flag is set to 0. I think it would be great to add a check for inappropriate values for this flag in order to generate more user-friendly error message in this case.

**Comment by valyala** [comment]
The issue must be fixed in the commit 2149733bd2489333ee202e069c66a46e50591bea - now `vmagent` automatically adjusts `-remoteWrite.queues` value if it exceeds sane limits, i.e. if it is smaller than 1 or if it is bigger than `GOMAXPROCS*4`.

**Comment by valyala** [comment]
The bugfix has been included in [v1.40.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as resolved.
