### ISSUE TITLE
how can i push customer timestamp with series？

### ISSUE THREAD

**Issue by lddlww** [VictoriaMetrics/VictoriaMetrics#7100]
### Is your question request related to a specific component?

victoriaMetrics

### Describe the question in detail

i want to use my custom timestmap with values， and write directly to VM， how can i do？

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. 

I think the easiest way is to use import API. You could send request with data in JSON format like:

```javascript
{
  // metric contans metric name plus labels for a particular time series
  "metric":{
    "__name__": "metric_name",  // <- this is metric name

    // Other labels for the time series

    "label1": "value1",
    "label2": "value2",
    ...
    "labelN": "valueN"
  },

  // values contains raw sample values for the given time series
  "values": [1, 2.345, -678],

  // timestamps contains raw sample UNIX timestamps in milliseconds for the given time series
  // every timestamp is associated with the value at the corresponding position
  "timestamps": [1549891472010,1549891487724,1549891503438]
}
```
Please ref this doc for more format details: https://docs.victoriametrics.com/#json-line-format 

And ref this doc for the import API: https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format
```bash
# Import gzipped data to <destination-victoriametrics>:
curl -X POST -H 'Content-Encoding: gzip' http://destination-victoriametrics:8428/api/v1/import -T exported_data.jsonl.gz
```

Also, there are many other import API (csv, native, ...) that you could try. Please see the doc above.

**Comment by lddlww** [comment]
thanks for such a detailed reply， i got it
