### ISSUE TITLE
vmagent: set up a timeout for tcp connection establishment during k8s discovery

### ISSUE THREAD

**Issue by tIGO** [VictoriaMetrics/VictoriaMetrics#7127]
### Is your feature request related to a problem? Please describe

In our k8s-installation we use DNS balancing – kube-api server has multiple DNS-records, that could be partially unavailable.
Default golang HTTP client traverses all IPs until it successfully connects. Currently, HTTP client for discovery does not set timeout [explicitly](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/discovery/kubernetes/api_watcher.go#L252), while scraping HTTP client [does](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/client.go#L87) so. 

In this case, we wait for 120+ seconds (allegedly, some OS timeout) per each request (kube-api hostname has 3 DNS records, one is off).

### Describe the solution you'd like

Explicitly set up dialer for k8s discovery client (e.g. use `netutil.Dialer`).

**Comment by dennisme** [comment]
Anyone working on this can I pick it up? Would you like the value to be configurable via cli args to vmagent?

**Comment by tIGO** [comment]
Not really, we patch it with oneliner – add `DialContext: netutil.Dialer.DialContext,` to client [creating](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/v1.103.0-cluster/lib/promscrape/discovery/kubernetes/api_watcher.go#L253)

I could create PR if maintainers think this is an appropriate fix.

**Comment by f41gh7** [comment]
The bugfix was included into [v1.107.0](https://docs.victoriametrics.com/changelog/#v11070), [v1.102.8](https://docs.victoriametrics.com/changelog/#v11028) and [v1.97.13](https://docs.victoriametrics.com/changelog/#v19713).
