### ISSUE TITLE
minScrapeInterval confusion

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#714]
**Describe the bug**
documentation of `minScrapeInterval`:
> For example, -dedup.minScrapeInterval=60s would de-duplicate data points on the same time series if they are located closer than 60s to each other

My reading was that if a duration between any two points A and B < 60, point B will be discarded.

That is not the case-- the implementation appears to use quantized time buckets, and only one point will be accepted per bucket.  From the unit tests:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d7c1ff8b0c6df29a65b1331af5df463401e6575a/lib/storage/dedup_test.go#L55

From my reading of the docs I expected the point at time 300 to be discarded, since the previous point was 95 ms earlier (< 100ms).

**Expected behavior**
The semantics of `minScrapeInterval` should be documented clearly.

**Version**

**Comment by valyala** [comment]
@belm0 , agreed with this point. Could you suggest more clear and correct description for `-dedup.minScrapeInterval`?
