### ISSUE TITLE
Protocol links in README.md do not work

### ISSUE THREAD

**Issue by mactyr** [VictoriaMetrics/VictoriaMetrics#7155]
### Describe the bug

In the [prominent features](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#prominent-features) section of README.md, none of the links beginning with "#" (under the "various protocols" bullet) work. It looks like they may just need to be prefixed with "https://docs.victoriametrics.com/". 

### To Reproduce

Try to click a protocol link in the readme file.

### Version

N/A

**Comment by jiekun** [comment]
Thank you for reporting!

**Comment by hagen1778** [comment]
@jiekun @mactyr I'm unable to reproduce this. Both links below work for me:
* https://docs.victoriametrics.com/#how-to-import-data-in-json-line-format 
* https://docs.victoriametrics.com/single-server-victoriametrics/#how-to-import-data-in-json-line-format

I clicked on that link from mentioned section on https://docs.victoriametrics.com/ and https://docs.victoriametrics.com pages. 

What browser do you use? What happens to URL when you click on the link?

**Comment by mactyr** [comment]
@hagen1778 I'm talking about clicking the links from within github (or, presumably, anywhere else that isn't https://docs.victoriametrics.com/, like a local markdown preview if I have the repo cloned). When I click the protocol links from github, nothing happens (or, more accurately, the fragment string in the link gets added to the github url at the top of the browser, but that doesn't take me to the correct documentation, I'm still looking at the readme within github). If you follow the "prominent features" link in my original issue description and try to click the protocol links from there, I think you'll see the problem.

**Comment by hagen1778** [comment]
Got it! Thanks for the explanation!
