### ISSUE TITLE
VictoriaLogs sort by time in UI for group

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#7184]
### Describe the bug

When you check the logs in the UI under the `Group` block, they are sorted in ascending order. However, if you open the `table`, the sorting works correctly, allowing for manipulation. It would be great if the sorting in the Group block defaulted to show new logs at the top instead of at the bottom. Since there is usually a limit, it can be hard to read or check the latest logs in the group block.

### To Reproduce

Open UI, [for example](https://play-vmlogs.victoriametrics.com/select/vmui/#/?query=*&g0.range_input=24h&g0.end_input=2024-10-05T09%3A27%3A41&g0.relative_time=last_24_hours)
And check how logs sorted in group block
![screenshot-000458](https://github.com/user-attachments/assets/88757412-2974-4db9-91e8-4044bf2237d3)
as you see the older logs in the top, but must be the newest logs

if we check `table` field then you are able to sort by time in desc or asc way
![screenshot-000460](https://github.com/user-attachments/assets/2985a3b1-231f-4609-b7e0-b702daceb60a)

### Version

0.33.0

**Comment by hagen1778** [comment]
Probably related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7045 
> The returned lines aren’t sorted by default, since sorting disables the ability to send matching log entries to response stream as soon as they are found. Query results can be sorted in the following ways

from https://docs.victoriametrics.com/victorialogs/querying/

@Loori-R can we sort on frontend?

**Comment by valyala** [comment]
Sorting by time is available in [VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) starting from [v0.41.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the feature request as done.
