### ISSUE TITLE
Support additional labels on prometheus import API

### ISSUE THREAD

**Issue by ledmonster** [VictoriaMetrics/VictoriaMetrics#719]
**Is your feature request related to a problem? Please describe.**

When I try to substitute VictoriaMetrics for Prometheus+Pushgateway, lack of additional labels feature on prometheus import API (`/api/v1/import/prometheus`) makes work harder. Pushgateway does support additional labels on API, and I want to use it in the import API, too.

**Describe the solution you'd like**

One idea is to support same API as [Pushgateway](https://github.com/prometheus/pushgateway#url).

```
/api/v1/import/prometheus{/<LABEL_NAME>/<LABEL_VALUE>}
```

or some query strings (e.g. `labels`) may also work.

```
/api/v1/import/prometheus?labels={<LABEL_NAME>%3D<LABEL_VALUE>,}
```

**Describe alternatives you've considered**

Now I'm using `remote_write` API instead. I parse Prometheus exposition format to `WriteRequest` and post it to the API with following code.

* https://gist.github.com/ledmonster/7d0de61a788b164a510c0359465a41f4

**Comment by valyala** [comment]
@ledmonster , this sounds like very useful feature request! I think it would be great adding `labels={<LABEL_NAME>:<LABEL_VALUE>,...}` query arg to all the [supported data ingestion protocols](https://victoriametrics.github.io/#how-to-import-time-series-data) that work over http.

**Comment by valyala** [comment]
In the mean time you may try adding labels via relabeling with `-relabelConfig` command-line flag - see [these docs](https://victoriametrics.github.io/#relabeling) for details.

**Comment by ledmonster** [comment]
> I think it would be great adding labels={<LABEL_NAME>:<LABEL_VALUE>,...} query arg to all the supported data ingestion protocols that work over http.

That's great!!

I'm also using reliable feature, thank you.

**Comment by valyala** [comment]
The commit f41b36bb9a162e5cc184da5e0236e3c441776c85 adds ability to add extra labels to data imported via the following http endpoints:

* [/api/v1/import](https://victoriametrics.github.io/#how-to-import-time-series-data)
* [/api/v1/import/csv](https://victoriametrics.github.io/#how-to-import-csv-data)
* [/api/v1/import/prometheus](https://victoriametrics.github.io/#how-to-import-data-in-prometheus-exposition-format)

Extra labels must be enumerated in `extra_label=name=value` query args. Multiple query args are supported. For example, `{foo="bar"}` and `{baz="aaa"}` labels must be added to all the imported metrics via `/api/v1/import/prometheus?extra_label=foo=bar&extra_label=baz=aaa`.

@ledmonster , could you build VictoriaMetrics from the commit f41b36bb9a162e5cc184da5e0236e3c441776c85 and verify whether the functionality for adding extra labels works as expected? See [build instructions](https://victoriametrics.github.io/#how-to-build-from-sources).

**Comment by ledmonster** [comment]
@valyala I'll try it later, thank you!!

**Comment by valyala** [comment]
The ability to add extra labels has been added into [v1.40.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing feature request as done.
