### ISSUE TITLE
tests: lib/storage/TestStorageRotateIndexDB periodically fails

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#7196]
### Describe the bug

Failed run in CI: https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/11231503513/job/31221149172?pr=7114
```
2024-10-08T08:27:57.918Z	panic	VictoriaMetrics/lib/mergeset/table.go:518	BUG: raw items must be empty at this stage; got 7 items
panic: BUG: raw items must be empty at this stage; got 7 items
```

### To Reproduce

Can't reproduce it locally

### Version

Upstream

**Comment by rtm0** [comment]
@hagen1778 There is a bug for this already: #6977
