### ISSUE TITLE
Are PromQL compatibility is tested?

### ISSUE THREAD

**Issue by ctrlok** [VictoriaMetrics/VictoriaMetrics#72]
I found that predict_linear function didn't work. Do you have any tests for other functions? Are you sure that they will work the same way as in Prometheus? Thanks!

**Comment by ctrlok** [comment]
I'm trying to do Prometheus compatible test manually and I started to get wired results:
```
[root@instance-0 ~]$ QUERY="api/v1/query_range?query=node_filesystem_free_bytes%7Bjob%3D%22node%22%2Cmountpoint%3D%22%2Fdata%22%2Cname%3D%22instance-0%22%2Crole%3D%22Monitoring%22%7D&start=1561101500&end=1561101930&step=10"
[root@instance-0 ~]$ wdiff -3n <(curl "localhost:9090/$QUERY" 2>/dev/null| jq .) <(curl "localhost:8481/select/1/prometheus/$QUERY" 2>/dev/null| jq . | grep -v "env") | colordiff

======================================================================
# That's mean a data are the same
# Let's try to do changes(node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0", role="Monitoring"}[20s])


[root@instance-0 ~]$ QUERY="api/v1/query_range?query=changes(node_filesystem_free_bytes%7Bjob%3D%22node%22%2C%20mountpoint%3D%22%2Fdata%22%2C%20name%3D%22instance-0%22%2C%20role%3D%22Monitoring%22%7D%5B20s%5D)&start=1561101500&end=1561101930&step=10"
[root@instance-0 ~]$ wdiff -3n <(curl "localhost:9090/$QUERY" 2>/dev/null| jq .) <(curl "localhost:8481/select/1/prometheus/$QUERY" 2>/dev/null| jq . | grep -v "env") | colordiff

======================================================================

            [-"1"-]
            {+"2"+}
======================================================================

            [-"1"-]
            {+"2"+}
======================================================================

            [-"1"-]
            {+"2"+}
======================================================================

            [-"1"-]
            {+"2"+}
```
It look like this in Grafana:

![2019-06-21 11 00 08](https://user-images.githubusercontent.com/3265316/59907461-cad8b500-9413-11e9-974a-e4782009a49c.gif)

**Comment by ctrlok** [comment]
I got different data for delta(node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0", role="Monitoring"}[1m]) as well.

**Comment by ctrlok** [comment]
In some functions (like idelta) data are the same, but moved to 10s before. In others like delta or holt_winters returned data are different. And I dound difference only in range-vector functions.

**Comment by ctrlok** [comment]
Hm... After reading https://github.com/prometheus/prometheus/issues/3806 and @valyala comment to this issue I found that metrics in VM for holt-winters is equal to metrics in prometheus with +10s time range. 
As example: 
```
# For VM is 30s range
holt_winters(node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0", role="Monitoring"}[30s], 0.1, 0.1)

# Values:
          "values": [
            [
              1561104780,
              "104597386391.552"
            ],
            [
              1561104790,
              "104597433491.45602"
            ],
            [
              1561104800,
              "104597520932.86401"
            ],
            [
              1561104810,
              "104597166067.71202"
            ],
            [
              1561104820,
              "104597089050.62401"
            ],
            [
              1561104830,
              "104597051723.77602"
            ],
            [
              1561104840,
              "104597156745.21602"
            ]
          ]

# For Prometheus is 40s range:
holt_winters(node_filesystem_free_bytes{job="node", mountpoint="/data", name="instance-0", role="Monitoring"}[40s], 0.1, 0.1)

# Values:
          "values": [
            [
              1561104780,
              "104597464268.8"
            ],
            [
              1561104790,
              "104597386391.552"
            ],
            [
              1561104800,
              "104597433491.45602"
            ],
            [
              1561104810,
              "104597520932.86401"
            ],
            [
              1561104820,
              "104597166067.71202"
            ],
            [
              1561104830,
              "104597089050.62401"
            ],
            [
              1561104840,
              "104597051723.77602"
            ]
          ]
```

**Comment by valyala** [comment]
The majority of functions are covered with tests at [app/vmselect/promql](https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmselect/promql). There are two rarely used functions - `holt_winters` and `predict_linear` - which weren't tested properly.

As for the small discrepancies you noticed above, they are related to slightly different data model between Prometheus and VictoriaMetrics outlined [here](https://github.com/prometheus/prometheus/issues/3806). This allows using steps smaller than the scrape interval. Prometheus stops showing graph in this case.

**Comment by ctrlok** [comment]
Hm. I'm not sure that I understand. Are you mean for changes() I should always use -10s because of it?

**Comment by ctrlok** [comment]
>This allows using steps smaller than the scrape interval. Prometheus stops showing graph in this case.

**Comment by valyala** [comment]
> Hm. I'm not sure that I understand. Are you mean for changes() I should always use 10s instead of 20s and 50s instead of 1m because of it?

The time shift between Prometheus and VictoriaMetrics depends on the `step` arg passed to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries). This arg is dynamically calculated by Grafana and is usually close to the distance between adjanced pixels on your monitor.

**Comment by ctrlok** [comment]
I have data with 10s resolution. I created a graph with function: 
```
changes(node_filesystem_free_bytes{}[19s])
```
How many changes should be? One
In VictoriaMetrics it's two.

**Comment by tenmozes** [comment]
let me a bit rephrase:
- on interval [1,2] "changes" function must be 1, VM shows 2
- idelta show one additional point too
looks like VM always includes one more interval

**Comment by valyala** [comment]
@ctrlok , I adjusted data model in VictoriaMetrics - now it is closer to Prometheus' one. This should remove small discrepancies. Could you build VictoriaMetrics form the latest commit and verify this?

**Comment by ctrlok** [comment]
VM still show 2 changes instead of 1 on [19s] range

**Comment by ctrlok** [comment]
![Capto_Capture 2019-06-22_12-12-44_AM](https://user-images.githubusercontent.com/3265316/59951732-7ddff780-9482-11e9-97dc-a032df12d5d5.png)
It's how it looks. VM for changes(metric[19s]) is equal for PROM  changes(metric[30s])

**Comment by valyala** [comment]
> VM still show 2 changes instead of 1 on [19s] range

This is correct behavior if the metric is scraped with `10s` interval, since in the majority of cases `[19s]` time range would contain two data points instead of a single data point. Example timestamps for data points on the `19s` time range: `[0, 10]`, `[5, 15]`, `[9, 19]`. The time range may contain a single data point only in the presence of scrape jitter: `[-0.1, 10, 19.1]`. In this case `-0.1` and `19.1` data points are outside the `19s` time range. So I'd say that Prometheus' results are incorrect in this case.

There is another issue in VM I'm going to fix soon: it sets the time range `d` in square brackets of `changes(m[d])` to `~2x(scrape_interval)` if `d` is smaller than `2x(scrape_interval)` for the given metric. This would result in inflated values.

**Comment by valyala** [comment]
@ctrlok , try [v1.20.4](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). It should calculations for range functions such as `changes` with intervals in square brackets smaller than `2 x scrape_interval`.

**Comment by valyala** [comment]
@ctrlok , ping :)

**Comment by hagen1778** [comment]
Closing the issue due to inactivity. @ctrlok feel free to open if there are any questions
