### ISSUE TITLE
Inconsistent description about active time series definition

### ISSUE THREAD

**Issue by snakorse** [VictoriaMetrics/VictoriaMetrics#7212]
### Is your feature request related to a problem? Please describe

I found the definition about "active time series" were inconsistent at the following two documents:
1.  https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/889b990d-618b-4c60-85ca-810536a22939">

2.  https://docs.victoriametrics.com/faq/#what-is-an-active-time-series
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/285f8a9e-3e9f-4eb0-9894-31060e507b1e">

as my understanding, the second one is more accurate.

### Describe the solution you'd like

the description of "active time series" should be consistent in these two places.

**Comment by jiekun** [comment]
Thank you. I'd like to update the doc to make them all consistent.

**Comment by snakorse** [comment]
@jiekun I notice that you choose the statement [at here](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy) as the correct one in your [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7242), but I wonder does this statement matchs the meaning of "vm_tenant_active_timeseries" metric?

**Comment by jiekun** [comment]
Hi. From code perspective, active time series is actually the metrics ID (or the unique ID for each time series) stored in in-memory cache. For each time series, it could be added to the cache when:
1. a sample is ingested.
2. queried.

So `vm_tenant_active_timeseries` represent metrics contains at least a sample or touched by queried during the last hour.
