### ISSUE TITLE
maxUniqueTimeseries should be separate for instant and range queries?

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#722]
**Is your feature request related to a problem? Please describe.**
Queries related to metrics stats like `count({__name__=~".*"})` by job, etc. are useful, yet will easily exceed the typical `search.maxUniqueTimeseries` limit.  But these queries should be OK if they are instant rather than range. 

**Describe the solution you'd like**
Separate limits for instant and range queries.  Or perhaps only apply limits to range queries.

**Comment by valyala** [comment]
The `-search.maxUniqueTimeseries` command-line flag limits the number of time series a single query may match. This prevents from high memory usage (up to OOM), high CPU usage and high disk IO usage for extended periods of time when processing heavy query like `count({__name__=~".*"})`. Both instant and range queries use the same code for finding time series that match the given query. So there is no sense in using distinct config options for them.

**Comment by belm0** [comment]
I think the problem is that high `maxUniqueTimeseries` does not necessarily imply high mem / CPU / IO.  It depends on the query.  An instant query of one point in time will be orders of magnitude more efficient than a range query.

I would like queries that are efficient to be allowed even if they return a large number of time series.

**Comment by valyala** [comment]
>  An instant query of one point in time will be orders of magnitude more efficient than a range query.

Unfortunately VictoriaMetrics doesn't work in this way. Every query - range and instant - is executed in the following steps:

1. Locating time series that match the given filters from the query.
2. Fetching and processing the data for the found time series.

The `-search.maxUniqueTimeseries` limit is applied at step 1 for both instant and range queries. This step may take significant amount of resources (CPU, RAM, disk IO) during extended periods of time when the database contains big number of time series. So `-search.maxUniqueTimeseries` allows limiting resource usage at this step.

As for the second step, its' resource usage is limited mostly with `-search.maxQueryDuration` command-line flag.

**Comment by belm0** [comment]
Thank you for clarifying-- agreed this feature request is not viable then.
