### ISSUE TITLE
Calculating the percentage of dropped metrics in VMagent

### ISSUE THREAD

**Issue by ankitdh7** [VictoriaMetrics/VictoriaMetrics#7226]
### Is your question request related to a specific component?

VictoriaMetrics, VMagent

### Describe the question in detail

**Use case**
I want to calculate the percentage of dropped metrics during the shipping phase, which is the interval between a successful scrape and remote ingestion. The goal is to capture scenarios where the remote write endpoint is either down or too slow to ingest data, enabling us to set an SLO on dropped metrics.

**Attempt**
- I used below query to get the number of scraped samples
```
sum(scrape_samples_scraped)
``` 
- Below query to get the dropped bytes per seconds from VMAgent
```
sum(rate(vm_persistentqueue_bytes_dropped_total{job=~"$job"}[$__rate_interval])) by (namespace)
```
- Below query to find the avg bytes per sample on disk
```
sum(vm_data_size_bytes{job=~".*vmstorage.*"}) / sum(vm_rows{job=~".*vmstorage.*", type!~"indexdb.*"})
``` 
- Below query to convert the dropped bytes into the dropped samples per sec
```
sum(rate(vm_persistentqueue_bytes_dropped_total{job=~"$job",environment!=""}[$__rate_interval])) by (environment) / (sum(vm_data_size_bytes{job=~".*vmstorage.*",environment!=""}) by (environment) / sum(vm_rows{job=~".*vmstorage.*", type!~"indexdb.*",environment!=""}) by (environment))
```

**Result**

![image](https://github.com/user-attachments/assets/ab7f219b-d1da-4732-8f81-41deed100658)

As seen in the snapshot above, there is a noticeable difference between the scraped samples (top) and the dropped samples(bottom).

I believe the issue stems from the fact that scraping statistics are in number_of_samples, whereas dropping statistics are in bytes. The average sample size is taken from VMstorage, but it's actually VMagent that writes the samples locally before dropping them, and they may use a different compression mechanism.

Could you please advise if there are existing metrics that I may have missed, which would allow me to avoid converting between number_of_samples <-> bytes? If not, do you see any issues with my current approach, or would you suggest a different method?

Thanks in advance! 

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by zekker6** [comment]
Hello @ankitdh7 

> Could you please advise if there are existing metrics that I may have missed, which would allow me to avoid converting between number_of_samples <-> bytes?

As you have correctly pointed out vmagent and vmstorage are using different data storage and data compression formats, this makes calculation results skewed.

> If not, do you see any issues with my current approach, or would you suggest a different method?

It seems like you're looking for this metric: `vmagent_remotewrite_samples_dropped_total`:
> The number of dropped samples because of overloaded remote storage can be monitored via `vmagent_remotewrite_samples_dropped_total` metric.

**Comment by ankitdh7** [comment]
Hi @zekker6 Thank you for your response. I checked the metric `vmagent_remotewrite_samples_dropped_total` but for some reason, this metric doesn't register any data for me.
<img width="1653" alt="image" src="https://github.com/user-attachments/assets/062fb646-4523-4ffb-afbe-4d4a0ba00ba8">

Where as during the same time other metrics like `vm_persistentqueue_bytes_dropped_total` clearly shows that there is some data dropped from the persistent queue.
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/58d840f1-d4a4-40a6-a19b-41ab50424150">

The VMagent version is `v1.93.4`. It sends same metrics to 2 remoteWriteUrl. I tested this scenario by intentionally providing one incorrect remoteWriteURL to the VMagent. This caused the agent to write data to the persistent queue, and eventually, the data was dropped. Any idea why the `vmagent_remotewrite_samples_dropped_total` didn't register any data in this case?

**Attempt 2**
Also, i was looking at the other metrics to find the dropped % in bytes as follows:
```
Total amount of metrics collected by VMagent (bytes) = vmagent_remotewrite_conn_bytes_written_total + vm_persistentqueue_bytes_dropped_total + vmagent_remotewrite_pending_data_bytes
```
```
% of dropped metrics = (vm_persistentqueue_bytes_dropped_total) / (vmagent_remotewrite_conn_bytes_written_total + vm_persistentqueue_bytes_dropped_total + vmagent_remotewrite_pending_data_bytes )
```

Below is the actual query i tried
```
(sum(rate(vm_persistentqueue_bytes_dropped_total{job=~".*vmagent.*"}[$__rate_interval])) by (job))/
(sum(rate(vmagent_remotewrite_conn_bytes_written_total{job=~".*vmagent.*"}[$__rate_interval])) by(job) + sum(rate(vm_persistentqueue_bytes_dropped_total{job=~".*vmagent.*"}[$__rate_interval])) by (job) + sum(rate(vmagent_remotewrite_pending_data_bytes[$__rate_interval])) by (job))
```

**Output:**

![image](https://github.com/user-attachments/assets/4da71071-fd5b-4ecf-8478-baf7505add93)

We are sending the same metrics to two remoteWriteURL endpoints. When one of the URLs is completely down, I expected the data loss percentage to be around 50%. However, as shown in the graph above, it is closer to 80%. Could there be an issue with this approach?

**Comment by zekker6** [comment]
@ankitdh7 Sorry for the confision, I've checked the source for this metric and it turned out that it will only be incremented if vmagent is explicitly configured to drop samles when vmstorage is overloaded with the following command-line flag:
```
  -remoteWrite.dropSamplesOnOverload
     Whether to drop samples when -remoteWrite.disableOnDiskQueue is set and if the samples cannot be pushed into the configured -remoteWrite.url systems in a timely manner. See https://docs.victoriametrics.com/vmagent#disabling-on-disk-persistence
```

Could you try the following query:
```
sum(rate(vm_persistentqueue_bytes_dropped_total)) by (job, instance) / sum(rate(vm_persistentqueue_bytes_written_total)) by (job, instance)
```

It calculates the ratio between number of written and dropped bytes in vmagent's queue, so that should be much more accurate.

**Comment by ankitdh7** [comment]
Hi @zekker6 Thank you for your ans. I configured the `-remoteWrite.dropSamplesOnOverload` and the metric was coming but it didn't show any data even when persistent queue in VMagent was dropping the data.

I tried the below query your shared and it works fine for my use-case.
```
sum(rate(vm_persistentqueue_bytes_dropped_total)) by (job, instance) / sum(rate(vm_persistentqueue_bytes_written_total)) by (job, instance)
```

I would like to share the updated query below that i used to capture an additional scenario when metrics pipeline is down and these metrics are absent.

```
((sum(rate(vm_persistentqueue_bytes_dropped_total{cluster=~"$Cluster"}[$__rate_interval])) or vector(1)) 
/
(sum(rate(vm_persistentqueue_bytes_written_total{cluster=~"$Cluster"}[$__rate_interval])) or vector(1))) or vector(0)
```

We can close this and once again, thank you for the amazing support.
