### ISSUE TITLE
TagFiltersToMetricIDsCache leaks, not expired regularly

### ISSUE THREAD

**Issue by DavidYuYu** [VictoriaMetrics/VictoriaMetrics#7230]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

Hi, I'm using VictoriaMetrics-singleNode v1.97.0 and found some strange things to ask
It's mainly about tagFiltersToMetricIDsCache not expired

What i observed is the maxSize of the cache will be expanded very early（In my case, it's usually 40 minutes）. As a result, the cache will not be expired .And the cache kept increasing to the maximum value

I observed it through vm_cache_size_max_bytes{type="indexdb/tagFiltersToMetricIDs"} and vm_cache_size_bytes{type="indexdb/tagFiltersToMetricIDs"}/1024/1024

By reading the source code, I found that the cache has curr and prev two block address, the initialization, the size of the curr is --storage.CacheSizeIndexDBTagFilters half, while the prev size is a small fixed value.So in general curr maxSize will be much larger than prev maxSize

And there are two other goroutine:
ExpirationWatcher goroutine is executed every 30 minutes to Reset prev cache and swap it with the curr cache.**It will exchage curr's MaxSize and prev's MaxSize.**
CacheSizeWatcher goroutine is executed every 1.5 seconds to determine if curr has exceeded 90% maxSize,and if over 90%,the mode will change to whole.This will cause expirationWatcher to stop working, and the cache will continue to grow

**So after each CacheSizeWatcher, if at this time the maxSize of the curr is swapped to the maxSize of the initial prev. Then it is easy for CacheSizeWatcher to trigger the scaling logic in the next 30 minutes because the maxSize of the initial prev is very small**
In the end, the cache is not expired

Is it my misunderstanding, or is the design so

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. In VictoriaMetrics, the in-memory caches have two `mode`: `split` mode and `whole` mode. For `whole` mode, cache use all space and never release them.

Also see my comment in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6701#issuecomment-2257439138
