### ISSUE TITLE
VictoriaLogs Documentation - Retention mistake

### ISSUE THREAD

**Issue by lukeod** [VictoriaMetrics/VictoriaMetrics#7231]
### Describe the bug

The documentation here:

https://docs.victoriametrics.com/victorialogs/#retention-by-disk-space-usage

Has the example:
"/path/to/victoria-logs -retention.maxDiskSpaceUsageBytes=10TiB -**retention**=100y"

This doesn't seem to be valid - it should be:

"/path/to/victoria-logs -retention.maxDiskSpaceUsageBytes=10TiB -**retentionPeriod**=100y"

-retention doesn't seem to be a valid command line flag

### To Reproduce

N/A

### Version

N/A

**Comment by zekker6** [comment]
Hello @lukeod, thank you for noticing!
Will be fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7245
