### ISSUE TITLE
Does the api/v1/query_range of VictoriaMetrics support unless between instant vectors?

### ISSUE THREAD

**Issue by imquanke** [VictoriaMetrics/VictoriaMetrics#7240]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail
```
query={region="2022_guizhou_siyouyun2",uuid="4415b3c0-d29a-4ae3-a327-4cea834c2da5",__name__=~".*disk_space_on.*"} unless {region="2022_guizhou_siyouyun2",uuid="4415b3c0-d29a-4ae3-a327-4cea834c2da5",__name__="free_disk_space_on_var_lib_mysql"}
```
when use `api/v1/query_range` query metrics, param query like above, the result is wrong(Excluded label `__name__="free_disk_space_on"` which should not be excluded)

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. 

I tried some similar query in our VictoriaMetrics playground, and it works fine.
[Playground](https://play.victoriametrics.com/select/0/vmui/?#/?g0.range_input=1h&g0.end_input=2024-10-15T08%3A38%3A20&g0.relative_time=last_1_hour&g0.tab=0&g0.tenantID=0&g0.expr=%7B__name__%3D%7E%22.*up%22%2Cinstance%3D%2210.71.13.6%3A9093%22%2Cpod%3D%22vmalertmanager-main-0%22%7D+unless+%7B__name__%3D%22up%22%2Cinstance%3D%2210.71.13.6%3A9093%22%2Cpod%3D%22vmalertmanager-main-0%22%7D)

[Screen Recording](https://github.com/user-attachments/assets/a9366478-a2c8-4bc4-94f3-620263993f78)

Could you provide more info about your `free_disk_space_on` metrics? For example, what labels does it has? It would be even better if you could export those related metrics (which is excluded/not excluded) and upload them here. See: https://docs.victoriametrics.com/#how-to-export-time-series

**Comment by imquanke** [comment]
![企业微信截图_17290470603318](https://github.com/user-attachments/assets/878be7c4-d430-41fc-8e8b-40f54276e31e)

**Comment by jiekun** [comment]
Looks weird to me. Could you help exporting those (6) metrics so that I can try to reproduce it locally? You can use the export API I mentioned above.

**Comment by imquanke** [comment]
[
[data.txt](https://github.com/user-attachments/files/17407797/data.txt)
](url)

**Comment by jiekun** [comment]
Thanks I'm checking.

**Comment by jiekun** [comment]
Thank you. This is not a bug as declared here:
https://docs.victoriametrics.com/metricsql/#keep_metric_names

> By default, metric names are dropped after applying functions or [binary operators](https://prometheus.io/docs/prometheus/latest/querying/operators/#binary-operators)

Basically, during `unless` operation, the `__name__` label will be **ignored**. In your case, the unless query:
```
{
  device_type="vm",
  __name__="used_disk_space_on",
  region="2022_guizhou_siyouyun2",
  uuid="1790ed97-28c5-48be-83ff-c76861b8dc87"
}
```
will be treat as:
```
{
  device_type="vm",
  region="2022_guizhou_siyouyun2",
  uuid="1790ed97-28c5-48be-83ff-c76861b8dc87"
}
```

Since the following time series match this filter, it's dropped as expected:
```
{
                    "__name__": "used_disk_space_on_root_ljs",
                    "device_type": "vm",
                    "exported_job": "zabbix-exporter",
                    "instance": "10.63.143.58:48100",
                    "job": "zabbix-exporter-siyouyun2",
                    "name": "Used disk space on $1",
                    "region": "2022_guizhou_siyouyun2",
                    "uuid": "1790ed97-28c5-48be-83ff-c76861b8dc87"
}
```

As clarified in doc, adding a `keep_metric_names` at the end of the MetricsQL could help:
```
{<MetricsQL-1>} unless {<MetricsQL-2>} keep_metric_names
```

And it should return **5** time series instead of **4**. Please try and comment if you still encounter issues.
