### ISSUE TITLE
victoriametrics dosn't apply max_scrape_size changes after reload

### ISSUE THREAD

**Issue by jawm111** [VictoriaMetrics/VictoriaMetrics#7260]
### Describe the bug

When i do reload victoriametrics i expect to apply max_scrape_size changes in scrape config. Changes applying only after restarting victoriametrics

### To Reproduce

Add max_scrape_size to scrape config

### Version

./victoria-metrics-prod --version
victoria-metrics-20241002-113036-tags-v1.104.0-0-g0d4f4b8f7d

### Used command-line flags

-search.maxSeries=2000000 
-search.maxUniqueTimeseries=2000000 
-storageDataPath=/victoriametrics/data 
-retentionPeriod=36
-promscrape.config=/victoriametrics/config/prometheus.yml 
-selfScrapeInterval=10s 
-httpListenAddr=127.0.0.1:8428 
-promscrape.streamParse=true

**Comment by dennisme** [comment]
You have a running vm process with an existing scrape config, you edit the config adjusting max_scrape_size, and reload it (systemctl reload?) and the change isn't reflected unless you do a full restart?

**Comment by jawm111** [comment]
> You have a running vm process with an existing scrape config, you edit the config adjusting max_scrape_size, and reload it (systemctl reload?) and the change isn't reflected unless you do a full restart?

I do reload with curl 127.0.0.1:8428/-/reload.
Yes, the change isn't reflected unless you do a full restart.

**Comment by dennisme** [comment]
Is it just that option in the prom config is are other changes respected?

**Comment by jawm111** [comment]
> Is it just that option in the prom config is are other changes respected?

Only the max_scrape_size option requires a full restart; other changes are respected after a reload.

**Comment by hagen1778** [comment]
@AndrewChubatiuk would you mind checking this? I believe it is related to the recent change https://github.com/VictoriaMetrics/VictoriaMetrics/commit/1e83598be330b844b58041966129ce9a728027ac

**Comment by AndrewChubatiuk** [comment]
hey @jawm111
which were old and a new max_scrape_size values?

**Comment by jiekun** [comment]
I was able to reproduce it. 

The `/config` page does show the latest config after reloading, because it simply read and print the config file. 

However, the scrape HTTP client is not updated because the new config is considered **identical** to the old config. 

It use the following function to determine whether the scrape configs are identical.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/eefae854500e742b4788c16cedd883e20f335a3d/lib/promscrape/scrapework.go#L162

And the following modification is tested and seems working.
```go
// key returns unique identifier for the given sw.
//
// It can be used for comparing for equality for two ScrapeWork objects.
func (sw *ScrapeWork) key() string {
	// Do not take into account OriginalLabels, since they can be changed with relabeling.
	// Do not take into account RelabelConfigs, since it is already applied to Labels.
	// Take into account JobNameOriginal in order to capture the case when the original job_name is changed via relabeling.
	key := fmt.Sprintf("JobNameOriginal=%s, ScrapeURL=%s, ScrapeInterval=%s, ScrapeTimeout=%s, HonorLabels=%v, HonorTimestamps=%v, DenyRedirects=%v, Labels=%s, "+
		"ExternalLabels=%s, "+
		"ProxyURL=%s, ProxyAuthConfig=%s, AuthConfig=%s, MetricRelabelConfigs=%q, "+
		"SampleLimit=%d, DisableCompression=%v, DisableKeepAlive=%v, StreamParse=%v, "+
		"ScrapeAlignInterval=%s, ScrapeOffset=%s, SeriesLimit=%d, NoStaleMarkers=%v, MaxScrapeSize=%v",
		sw.jobNameOriginal, sw.ScrapeURL, sw.ScrapeInterval, sw.ScrapeTimeout, sw.HonorLabels, sw.HonorTimestamps, sw.DenyRedirects, sw.Labels.String(),
		sw.ExternalLabels.String(),
		sw.ProxyURL.String(), sw.ProxyAuthConfig.String(), sw.AuthConfig.String(), sw.MetricRelabelConfigs.String(),
		sw.SampleLimit, sw.DisableCompression, sw.DisableKeepAlive, sw.StreamParse,
		sw.ScrapeAlignInterval, sw.ScrapeOffset, sw.SeriesLimit, sw.NoStaleMarkers, sw.MaxScrapeSize)
	return key
}
```

**Comment by AndrewChubatiuk** [comment]
I've tested with `1Mib` and changed it to `2Mib` and it works as expected and after sending `kill -1` to a process

**Comment by jiekun** [comment]
I just confirm it again. And here's my recording.
1. Start with a scrape with 1KiB `max_scrape_size`.
2. vmagent logs scrape error.
3. edit limit to 10MiB.
4. reload (or sending kill -1). vmagent logs reload.
5. vmagent logs scrape error again.
6. restart vmagent.
7. vmagent scrape successfully.

[Screencast from 2024年10月17日 13时43分21秒.webm](https://github.com/user-attachments/assets/fa7c038f-88db-4d41-96a5-06f924b2ff65)

Please note, the result of `/config` page could be misleading. As it simply print the yaml which does not reflect the real status of the running scrape client.

**Comment by hagen1778** [comment]
@jawm111 https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7282 was merged and will be available in the next release.

**Comment by vlasiuk-everstake** [comment]
> @jawm111 #7282 was merged and will be available in the next release.

Thank you for the update and for fixing the issue!

**Comment by jawm111** [comment]
> @jawm111 #7282 was merged and will be available in the next release.

Thank you for the update and for fixing the issue!
