### ISSUE TITLE
VictoriaLogs web UI: query results and hits panels sometimes fail to refresh after executing new query

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#7279]
### Describe the bug

[VictoriaLogs web UI](https://docs.victoriametrics.com/victorialogs/querying/#web-ui) fails updating query results and hits panels after executing new queries

### To Reproduce

1. Go to https://vmlogs.sandbox.victoriametrics.com/select/vmui/
2. Enter the the `*` in the query input field and press `enter. Note the state of query results and hits panels.
3. Enter `info` in the query input field and press `enter`. Note that query results and hits panels aren't updated for the `info` query - it looks like they remain the same as for the previous query - `*`.
4. Press `enter` again in the query input field. Note that query results and hits panels are properly updated for the `info` query.

### Version

[v0.36.0-victorialogs](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v0.36.0-victorialogs).

### Additional information

It looks like this bug has been introduced after the change at 6c9772b10186b44619a5ce386669650a7651338b ( https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7204 ). See the corresponding issue at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7097 .

**Comment by yuriydzobak** [comment]
Hi,
Also, it has bugs
1. it doesn't keep table, it jumps to previous tabs
2. it remove last symbol in limit
3. doesn't work query need to run twices
Please check, video https://youtu.be/0UrbKF7qd8c?si=SAl2xpKq0DfbxPrk

**Comment by hagen1778** [comment]
I don't observe mentioned issues in VM UI, though.

**Comment by yuriydzobak** [comment]
> I don't observe mentioned issues in VM UI, though.

hm, checked  Safari and Chrome in incognito mode, it has the problem like in Video in this [VL play ](https://play-vmlogs.victoriametrics.com/select/vmui/)

**Comment by hagen1778** [comment]
@yuriydzobak sorry if I not was clear. I meant VictoriaMetrics vmui behavior. 
vmui in VictoriaLogs and VictoriaMetrics share many common components, and request cancellation is one of them. So I was expecting it to be buggy as well.

**Comment by hasanbal** [comment]
+1

**Comment by hagen1778** [comment]
This issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7294 and will be included into the next release of VictoriaLogs.

**Comment by valyala** [comment]
These bugs should be addressed in [v0.38.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the issue as fixed then.
