### ISSUE TITLE
vmagent : data loss when network outage

### ISSUE THREAD

**Issue by macjl** [VictoriaMetrics/VictoriaMetrics#7280]
### Is your question request related to a specific component?

Vmagent remote write to Prometheus

### Describe the question in detail

Hello, here is my config : 
I have an application, SignalK, in a boat, which produce Prometheus metrics. The network may have pretty long period (10th of hours) without internet access, when far from coasts. I want to put all the metrics into a remote Prometheus Server, in my home. I can’t use a local Prometheus server, because consume too much power. 

To do it, I have installed vmagent to collect and cache the SignalK data, and send it to Prometheus through remote write protocol when internet is available. Here is the Vmagent command I use : 

``` 
/data/vmutils/vmagent-prod \
 -remoteWrite.url=https://prometheus.xxx.xxx.xxx/api/v1/write \
 -remoteWrite.basicAuth.username=xxxx \
 -remoteWrite.basicAuth.password=xxxx \
 -promscrape.config=/data/vmagent-launcher/prometheus.yml \
 -remoteWrite.label='signalk=venus' \
 -remoteWrite.tmpDataPath=/data/vmagent-launcher/vmagent-remotewrite-data \
 -remoteWrite.maxDiskUsagePerURL=5GB \
 -remoteWrite.queues=1
```

The problem is that it doesn’t support network outage longer than a few tenth of minutes. When the network is cut for 1 hour or more, I have datas that are not pushed to Prometheus. And I find theses messages in Vmagent logs : 

`2024-10-16T03:39:23.265Z        error   VictoriaMetrics/app/vmagent/remotewrite/client.go:453   sending a block with size 22002 bytes to "1:secret-url" was rejected (skipping the block): status code 400; response body: out of bounds`

What can I do to avoid such data loss ?

### Troubleshooting docs

- [x] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
> What can I do to avoid such data loss ?

The easiest solution would be to replace Prometheus with VictoriaMetrics.

Now to details. Prometheus has a fixed time window at which it can receive out-of-order samples, samples that aren't sorted by time stamp. For example, if client sends sample with timestamp: 10, and later it sends sample with timestamp: 5 - then this will be out-of-order sample. See more about this here https://promlabs.com/blog/2022/12/15/understanding-duplicate-samples-and-out-of-order-timestamp-errors-in-prometheus/

So when outage happens, vmagent will start to buffer to data. When connection restored - vmagents backfills data to the remote destination. It prefers sending fresh new data first, and then drain the queue when it has time. In result, data will arrive unsorted to Prometheus and it may reject it.

You can replace Prometheus with VictoriaMetrics which doesn't have this limitation.

You can try adjusting time window when Prometheus accepts such samples https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb
Please also see https://github.com/prometheus/prometheus/issues/12016.

**Comment by hagen1778** [comment]
> A last question : Could you consider adding an option to Vmagent to send data only in an ordered manner? By storing on disk the newer data, until the old data aren’t pushed ?

I don't think that this would solve the problem completely, because Prometheus would reject samples older than l [out_of_order_time_window](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb). If I am reading this right https://promlabs.com/blog/2022/12/15/understanding-duplicate-samples-and-out-of-order-timestamp-errors-in-prometheus/#remote-write-sending-bad-data

**Comment by macjl** [comment]
Ok, thanks. 

For the moment, I just set the out_of_order_time_window to 10 days. I will see if it cause issues. 

I’m also studying a way to migrate to VictoriaMetrics, and merging an InfluxDB and a Prometheus DB in just one VictoriaMetrics instance. 

Thanks for your help !

**Comment by tiny-pangolin** [comment]
You can use vmctl to migrate data from InfluxDB and Prometheus to VictoriaMetrics.

https://docs.victoriametrics.com/vmctl/
