### ISSUE TITLE
VictoriaLogs web UI: hits chart not keep state

### ISSUE THREAD

**Issue by yuriydzobak** [VictoriaMetrics/VictoriaMetrics#7290]
### Describe the bug

HI,
VL UI has added new feature https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7117
I believe this is a bug and not expected behavior. 
It doesn't disable the hits chart when you re-run a query and that feature doesn't improve user experience, in my opinion. It's easier to scroll down instead of clicking a button to disable hit charts when you re-run LogsQL query each time :) .

### To Reproduce

Open [VL play](https://play-vmlogs.victoriametrics.com/select/vmui/#/)
1. use any query and run it
2. disable chart
![screenshot-000527](https://github.com/user-attachments/assets/e51cc95a-abb2-44b2-bd13-241ff514e848)
3. run again query with disabled hits charts, and it show again
![screenshot-000528](https://github.com/user-attachments/assets/aeb09476-4b78-42fe-80b1-763d3ea552c8)

### Version

0.37.0

**Comment by yuriydzobak** [comment]
https://github.com/user-attachments/assets/e86a6393-24ee-40a9-a945-aebd81a6036c

**Comment by Loori-R** [comment]
This issue is related to #7279. It will be fixed in PR #7294.

**Comment by hagen1778** [comment]
This issue was addressed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7294 and will be included into the next release of VictoriaLogs.

**Comment by valyala** [comment]
This bug has been fixed in [v0.38.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the issue as fixed then.
