### ISSUE TITLE
Pending datapoints increase up to 6x-7x after vmstorage upgrade to v1.104.0-cluster from v1.93.4-cluster

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#7293]
### Is your question request related to a specific component?

vmstorage

### Describe the question in detail

When I upgrade one vmstorage instance from `v1.93.4-cluster` to `v1.104.0-cluster`, the VM dashboard shows that the value of `pending datapoints` increased up to 6x-7x (500K -> 3-3.4M)as shown in following screenshot.

<img width="1892" alt="Clipboard_Screenshot_1729239907" src="https://github.com/user-attachments/assets/c8ca6f8b-7834-4a85-a650-b623868c9a37">

In this picture, we have two vmstorage instances:
- 10.1.10.205: version is `vmstorage-20230910-140729-tags-v1.93.4-cluster-0-ge8164968e`, this instance keep running without any change  as the green line shown
- 10.1.3.232: version is `vmstorage-20241002-113649-tags-v1.104.0-cluster-0-gdfb2ad4ab4`, this instance upgraded at 15:49:00 as the yellow line shown

Since the number of active series didn't have big change, so
1. The pending datapoints  metric of instance`10.1.10.205` is stable, which matches expectation
2. The pending datapoints metric of instance `10.1.3.232` had an obvious change after upgrading, but why?

**My questions are**
1. Why the pending datapoints metrics increased so much after upgrading?
2. What's meaning of this increasing? Does it mean that latency wo data points increased after upgrading?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by xiaozongyang** [comment]
I also found out
1. the `process_num_threads` changed from 75 to 39
2. the memory usage changed from 55.9GB to 35.9GB, which is 10GB reduced
3. the cpu usage changed increased nearly 0.5-1 core, our hosts is 16c

**Comment by jiekun** [comment]
Hi. Could you also provide your ingestion rate?

**Comment by xiaozongyang** [comment]
@jiekun the ingestion rate of all cluster is 17.1Mil
<img width="946" alt="Clipboard_Screenshot_1729245284" src="https://github.com/user-attachments/assets/dd26caef-d0e3-4a7e-8815-192739c1069b">

**Comment by xiaozongyang** [comment]
ping @jiekun

**Comment by jiekun** [comment]
Hi. I would like to know about the ingestion rate of the instance which pending data point increased by 6x.

**Comment by xiaozongyang** [comment]
Hi @jiekun, ingestion rate of the instance is here
<img width="946" alt="Clipboard_Screenshot_1729565342" src="https://github.com/user-attachments/assets/9192d04a-8b82-4c17-9a06-b5a16f0571ec">

**Comment by xiaozongyang** [comment]
Does it mean that there is a abouot 3-second(3Mil / 1Mil) delay when writing datapoints?

**Comment by jiekun** [comment]
@xiaozongyang Hi.

Based on your ingestion rate, the pending data points is still within a reasonable range (0 - 3 * ingestion rate). 

In VictoriaMetrics, `rawItems` contains recently added items that haven't been converted to `parts` yet. `rawItems` are converted to `inmemoryParts` (which are visible for search) at least every `pendingItemsFlushInterval` or when `rawItems` becomes full. `rawItems` aren't visible for search due to performance reasons.

**Comment by xiaozongyang** [comment]
@jiekun 
1. When I change the timerange to past 2d, the mean pending datapooints is 3.7M, and max is 4.45M and the ingestion rate is always 1.02M, is that reasonable?
<img width="1893" alt="Clipboard_Screenshot_1729596673" src="https://github.com/user-attachments/assets/aaf7795b-0c1a-4bb2-bd6a-afb005e86ce2">
2. Also, why the pending datapoints increases by up to 6x?  Are there refactoring works? And the old version seems working well on this traffic pattern.

cc @valyala @hagen1778

**Comment by xiaozongyang** [comment]
I try to dump to profile svg, hope that helpful

- [profile-10 1 3 232](https://github.com/user-attachments/assets/a919cb29-1c97-4a75-9c21-522cfbb9da84)
- [profile-10 1 12 164](https://github.com/user-attachments/assets/0e990050-ef85-4e8c-8c04-d67781f93240)

**Comment by xiaozongyang** [comment]
![Clipboard_Screenshot_1729598984](https://github.com/user-attachments/assets/c7975958-7c22-41c0-9d00-21fd0229fd18)
It seems that, at version 1.104.0 in function `storage.(*blockStreamWriter).WriterExternalBlock` do an extra `zstd.Decompress` which increases about 5% CPU usage in profile

**Comment by xiaozongyang** [comment]
<img width="1914" alt="Clipboard_Screenshot_1729599596" src="https://github.com/user-attachments/assets/f04eb314-8690-4bc6-aa70-2fec02e4a5ac">
Antoher difference I found in the flume chart is `runtime.memmove` caused by `bytesutil.(*ByteBuffer).Write`

**Comment by jiekun** [comment]
> When I change the timerange to past 2d, the mean pending data pooints is 3.7M, and max is 4.45M and the ingestion rate is always 1.02M, is that reasonable?

**Again**, it's **reasonable** since pending data point is flushed every 2 seconds. You can find more info on the dashboard
![image](https://github.com/user-attachments/assets/c33d66be-e9a3-4a25-ac9e-cffa0eb394e3)

> why the pending datapoints increases by up to 6x?

Here's an example: 
![image](https://github.com/user-attachments/assets/422fc11a-7474-43f6-a6e8-e2e6410f6a1d)

The ingestion rate is slight below 2 Million, and pending data point is flushed every 2 seconds, which means it will accumulate and become 0 after flushing.

While the metrics is scraped in a fixed interval, what you can see on the dashboard will highly depends on **when** does the scraper scrape the pending data points metrics. For example:
- If we scrape at: [0s, 2s, 4s], we will get: [0, 0, 0].
- If we scrape at: [1s, 3s, 5s], we will get: [1.9M, 1.9M, 1.9M].
- If we scrape at: [1.999s, 3.999s, 5.999s], we will get: [3.9M, 3.9M, 3.9M], which is about 3x of the ingestion rate.

Please note, this is an example, not a real world case. So those number value might be incorrect. But it still demonstrate how pending data point dashboard work.

**Comment by xiaozongyang** [comment]
@jiekun jie
Thanks a lot! I found that there is a new flag `-inmemoryDataFlushInterval` when I diff code tag v1.1.04.0-cluster with v1.93.4, and the default value of this flag is 5, which will set DataFlushInterval in mergeset to 5s. But in v1.93.4 there is no code calling SetFlushInterval, so the flush interval is 1s.

This issue will be closed!

## v1.104.0-cluster
```go
// flushInterval in v1.104.0-cluster
func SetDataFlushInterval(d time.Duration) {
    if d < pendingItemsFlushInterval {
        // There is no sense in setting dataFlushInterval to values smaller than pendingItemsFlushInterval,
        // since pending rows unconditionally remain in memory for up to pendingItemsFlushInterval.
        d = pendingItemsFlushInterval
    }

    dataFlushInterval = d
}
```

## v1.93-4-cluster
```go
// The interval for flushing buffered data to parts, so it becomes visible to search.
const pendingItemsFlushInterval = time.Second

// The interval for guaranteed flush of recently ingested data from memory to on-disk parts,
// so they survive process crash.
var dataFlushInterval = 5 * time.Second

// SetDataFlushInterval sets the interval for guaranteed flush of recently ingested data from memory to disk.
//
// The data can be flushed from memory to disk more frequently if it doesn't fit the memory limit.
//
// This function must be called before initializing the indexdb.
func SetDataFlushInterval(d time.Duration) {
    if d > pendingItemsFlushInterval {
        dataFlushInterval = d
    }
}
```
