### ISSUE TITLE
grafana graphs should set ymin

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#731]
**Describe the bug**
Most of the graphs are using auto ymin, which can be very misleading for stats like CPU, request rate, etc.

**Expected behavior**
use ymin of 0 for gauges unless there is a good reason not to

**Screenshots**
![Screen Shot 2020-08-31 at 3 10 40 PM](https://user-images.githubusercontent.com/1708631/91688274-98405580-eb9c-11ea-873d-0a797157c1ef.png)

rather, it should look like this:
![Screen Shot 2020-08-31 at 3 16 15 PM](https://user-images.githubusercontent.com/1708631/91688481-0b49cc00-eb9d-11ea-9a14-691a205d0f28.png)

**Comment by belm0** [comment]
I'll make another PR for cluster dashboards.

**Comment by valyala** [comment]
FYI, all the changes mentioned above have been integrated into [v1.40.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by hagen1778** [comment]
@belm0 it is in `cluster` branch - https://github.com/VictoriaMetrics/VictoriaMetrics/tree/cluster/dashboards

jfyi, dashboards https://grafana.com/orgs/victoriametrics/dashboards were updated as well.

**Comment by belm0** [comment]
it seems to have been addressed in both files x both branches
