### ISSUE TITLE
vmselect caches incomplete data and does not expire

### ISSUE THREAD

**Issue by letian0805** [VictoriaMetrics/VictoriaMetrics#7332]
### Describe the bug

I deployed a VictoriaMetrics cluster using 2 shards(vmstorage, vminsert, and vmselect all have two replicas), and used the default cache expiration time of 30 minutes. I shut down a vmstorage, and then queried data through vmselect. Then I started up the shut down shard, and queried data from vmselect again. I found that the data was incomplete, even after 30 minutes. After restarting vmselect, the data returned to normal. I expect vmselect to return the correct data after vmstorage is restored.

### To Reproduce

1. Stop vmstorage-1 and wait for a few minutes.
2. Check the monitoring dashboard on grafana. Some indicators can only get part of the data (the data collected during the waiting period is stored on vmstorage-2).
3. Wait for a few minutes, start vmstorage-1, and wait for a few minutes.
4. Check the monitoring dashboard on grafana. Some indicators are still incomplete (no data from vmstorage-1 is obtained).
5. Wait 30 minutes and check the monitoring dashboard on grafana again. Some indicators are still incomplete.
6. Restart vmselect, check grafana, and the data returns to normal.

### Version

vmselect-20241021-133148-tags-v1.105.0-cluster-0-g7ba360adad

### Screenshots

Since vmselect has two nodes, sometimes complete data can be obtained, and sometimes only incomplete data can be obtained.
![image](https://github.com/user-attachments/assets/00023a01-426c-427a-8681-e019dbc60f41)
![image](https://github.com/user-attachments/assets/e8cb00a6-887e-43ec-847c-b1c04c7c6870)
![image](https://github.com/user-attachments/assets/818eebe0-7b1f-46ae-92ab-4fc981a63744)

**Comment by jiekun** [comment]
I'm testing it right now. 

At the mean time, could you please check if it works without cache:
- By passing `-search.disableCache` command-line flag to a single-node VictoriaMetrics or to all the vmselect components if cluster version of VictoriaMetrics is used.
- By passing `nocache=1` query arg to every request to `/api/v1/query` and `/api/v1/query_range`. If you use Grafana, then this query arg can be specified in Custom Query Parameters field at Prometheus datasource settings.
https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results

**Comment by letian0805** [comment]
> I'm testing it right now.
> 
> At the mean time, could you please check if it works without cache:
> 
> * By passing `-search.disableCache` command-line flag to a single-node VictoriaMetrics or to all the vmselect components if cluster version of VictoriaMetrics is used.
> * By passing `nocache=1` query arg to every request to `/api/v1/query` and `/api/v1/query_range`. If you use Grafana, then this query arg can be specified in Custom Query Parameters field at Prometheus datasource settings.
>   https://docs.victoriametrics.com/troubleshooting/#unexpected-query-results

I found that the reason why it had not expired before was because I had been querying all the time. Today, I tried not to query for 30 minutes, and the data expired. I got the complete data. Can it be optimized like this: If the vmstorage shard is abnormal when querying the indicator, mark the obtained data as incomplete data, and wait until the vmstorage shard returns to normal, and vmselect gets the latest data from vmstorage to update the cache.

**Comment by letian0805** [comment]
I have another question, how ```rollupResultCache.GetSeries```  covers these cases?
	//cache:....................|-------------------|
	//case1:..........................|-----------|
	//case2:..............|------------------------| 
	//case3:.......|----------------|
	//case4:..................................|--------------|
	//case5: |-------|
	//case6: ..........................................................|-------|

**Comment by jiekun** [comment]
> Can it be optimized like this: If the vmstorage shard is abnormal when querying the indicator, mark the obtained data as incomplete data, and wait until the vmstorage shard returns to normal, and vmselect gets the latest data from vmstorage to update the cache.

vmselect already has a `isPartial` field in response.
```json
{
    "status": "success",
    "isPartial": true,  # here
    "data": {
        ...
}
```

If you are using Grafana, this feature might be helpful for you: https://github.com/VictoriaMetrics/victoriametrics-datasource/issues/142

So I'm afraid there won't be any optimization for this.

**Comment by jiekun** [comment]
I have another question, how rollupResultCache.GetSeries covers these cases?


//cache:....................|-------------------|
//node1:..........................|-----------|
//node2:..............|------------------------|
//node3:.......|----------------|
//node4:..................................|--------------|
//node5: |-------|
//node6: ..........................................................|-------|
//time  :t0.................t1........................t2....................t3

I assume by this you mean:
1. cache exist in vmselect.
2. vmstorage node1-node6 contains some data in different time range.

1. typically, vmselect look for cache result by `GetSeries` and it return the cache data in your graph (let's say it can cover `[t1, t2]`).
2. and then vmselect send RPC request to vmstorage node1-node6 and ask for the data in `[t0, t1]` and `[t2, t3]` and then do the rollup calculation.

**Comment by jiekun** [comment]
I'm closing this as answered. Please feel free to reopen it if you have more question on this topic.

**Comment by letian0805** [comment]
> > I have another question, how rollupResultCache.GetSeries covers these cases?
> 
> > //cache:....................|-------------------|
> > //node1:..........................|-----------|
> > //node2:..............|------------------------|
> > //node3:.......|----------------|
> > //node4:..................................|--------------|
> > //node5: |-------|
> > //node6: ..........................................................|-------|
> > //time  :t0...................t1....................t2.....................t3
> 
> I assume by this you mean:
> 
> 1. cache exist in vmselect.
> 2. vmstorage node1-node6 contains some data in different time range.
> 
> For this case:
> 
> 1. typically, vmselect look for cache result by `GetSeries` and it return the cache data in your graph (let's say it can cover `[t1, t2]`).
> 2. and then vmselect send RPC request to vmstorage node1-node6 and ask for the data in `[t0, t1]` and `[t2, t3]` and then do the rollup calculation.

No! The cases I listed refer to multiple indicators, not multiple vmstorages. The root cause of the problem is that when updating the cache, multiple indicators are updated as a whole. See https://github.com/VictoriaMetrics/VictoriaMetrics/blob/4e50d6eed360bba101a9592a5b60cc577985c94c/app/vmselect/promql/rollup_result_cache.go#L447

If some of these indicators are rerouted to vmstorage-2 due to the failure of vmstorage-1, their data will be incomplete. After vmstorage-1 is restored, vmselect should go to vmstorage-1 to get data to complete the data in the cache.

**Comment by jiekun** [comment]
> multiple indicators are updated as a whole

I'm not sure about this. The rollup result cache is the aggregated result of a MetricsQL, not the cache of some metrics.

> If some of these indicators are rerouted to vmstorage-2 due to the failure of vmstorage-1, their data will be incomplete.

This is incorrect. If vmstorage-1 is down, vminsert (not vmselect) will re-route the metrics to vmstorage-n. And while querying, vmselect will send request to all vmstorage nodes. So the query result should be correct for latest data.

As for the existing data, you can also try `-search.denyPartialResponse` on vmselect, to make the response consistent.

> After vmstorage-1 is restored, vmselect should go to vmstorage-1 to get data to complete the data in the cache.

vmselect only look for the data out of rollup result cache range. In my case, vmselect will look for data in range `[t0, t1]` and `[t2, t3]` from ALL nodes. And the cached result won't be affected. Please consider `-search.denyPartialResponse` if you have strong consistency requirement.

**Comment by letian0805** [comment]
> > multiple indicators are updated as a whole
> 
> I'm not sure about this. The rollup result cache is the aggregated result of a MetricsQL, not the cache of some metrics.
> 
> > If some of these indicators are rerouted to vmstorage-2 due to the failure of vmstorage-1, their data will be incomplete.
> 
> This is incorrect. If vmstorage-1 is down, vminsert (not vmselect) will re-route the metrics to vmstorage-n. And while querying, vmselect will send request to all vmstorage nodes. So the query result should be correct for latest data.
> 
> As for the existing data, you can also try `-search.denyPartialResponse` on vmselect, to make the response consistent.
> 
> > After vmstorage-1 is restored, vmselect should go to vmstorage-1 to get data to complete the data in the cache.
> 
> vmselect only look for the data out of rollup result cache range. In my case, vmselect will look for data in range `[t0, t1]` and `[t2, t3]` from ALL nodes. And the cached result won't be affected. Please consider `-search.denyPartialResponse` if you have strong consistency requirement.

As you said, for a single-copy deployment, only the latest data is complete, and the historical data before the failure of vmstorage-1 cannot be obtained. This is not friendly to some analysis systems that use historical data, and it is easy to calculate wrong results. `-search.denyPartialResponse` sacrifices availability.

**Comment by jiekun** [comment]
In a distributed system, you cannot achieve CAP at the same time; you have to strike a balance between them. If you prioritize strong consistency, you will not be able to have high availability. 

If vmselect need to remove the cache every time a vmstorage node recovered, the cache is not useful. In this case, you can simply disable the rollup result cache by `-search.disableCache`. WDYT of this option?

**Comment by letian0805** [comment]
For distributed storage, in addition to considering availability and data consistency, deployment costs also need to be considered. Considering that short-term data inconsistency is allowed (for example, within 5 minutes), I will deploy vmstorage as a single copy with multiple shards. When using container deployment, vmstorage may be rescheduled due to OOM due to full memory, or due to a k8s worker node crash. In these cases, vmstorage will not stop for a long time (about 5 minutes). Storage failure is not a high-probability problem. If vmselect supports refreshing the cache, it will have no effect in most cases. `-search.disableCache` can avoid cache problems, but it will increase the burden on vmstorage and may cause avalanches.

**Comment by jiekun** [comment]
Then how about the `/internal/resetRollupResultCache` api to reset rollup result cache? See: https://docs.victoriametrics.com/url-examples/?highlight=rollup#internalresetrollupresultcache

**Comment by letian0805** [comment]
`/internal/resetRollupResultCache` is used for data backfilling scenarios, and is not very suitable for vmstorage shard failure recovery. The nocache=1 you provided before may be more suitable, but it is also very expensive (may cause vmstorage avalanche).

Therefore, the more elegant way I can think of is: each `timeseries` carries the node ID and status of vmstorage, so that after vmstorage is restored, in subsequent vmselect requests, the node ID and status of `timeseries` in the cache are used to obtain historical data from the restored vmstorage node, complete the `timeseries` in the cache, and refresh the status.

**Comment by jiekun** [comment]
@letian0805 Hi. I'd like to open a new feature request regarding auto expiring cache for partial response, when all vmstorage node back to work (or under some other condition). 

It should solve the issue you mentioned if implemented. But we would like to have more discussion before changing the current behaviour. WDYT?

**Comment by letian0805** [comment]
@jiekun That's great!

**Comment by jiekun** [comment]
@letian0805 Hi. Sorry for the confusion. But I found that vmselect does not cache result when `isPartial` is `true`. See: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/4114301955d6e60ae047613afaee8e235f9394ba/app/vmselect/promql/eval.go#L1703

**Comment by letian0805** [comment]
@jiekun This problem does not occur when the node crashes, but after the node recovers. For example, there are two nodes, vmstorage-1 and vmstorage-2. After 1 crashes, 2 takes on all the traffic. Therefore, 2 will save the data that should have been routed to 1 after 1 crashes. Therefore, vmselect will still cache 2's data (because it has been rerouted).

However, the data cached by vmselect is missing the historical data of 1. After 1 recovers, vmselect does not complete the historical data in 1 into the cache, causing subsequent continuous access to miss the historical data before 1 crashes.

**Comment by jiekun** [comment]
> Therefore, vmselect will still cache 2's data (because it has been rerouted).

Hi! By default, you shouldn't see `vmselect` caching the data from `vmstorage-2` when `vmstorage-1` is down. This is because `vmselect` should not know which `vmstorage` node a particular time series should be stored on, so it queries **all** `vmstorage` nodes. When `vmselect` only receives responses from some `vmstorage` nodes, it marks the query as `isPartial: True`, and at this point, the query results are **not cached**.

Once `vmstorage-1` is back up, `vmselect` will continue to query all `vmstorage` nodes. If it successfully receives a response (regardless of whether receiving data from `vmstorage-1`), `isPartial` will be `False`, and the query results will then be cached by `vmselect`.
