### ISSUE TITLE
Query performance problem consultation

### ISSUE THREAD

**Issue by iayamowner** [VictoriaMetrics/VictoriaMetrics#7333]
### victoria-metrics bin

victoria-metrics-linux-amd64-v1.101.0-cluster.tar.gz

### storage

node num: 3 (48 cores, 256GB mem, disk space enough)
config: --search.maxConcurrentRequests=128

### select
node num: 5 (48cores, 256GB mem, disk space enough)
config: --search.cacheTimestampOffset=15m --dedup.minScrapeInterval=1s --search.maxConcurrentRequests=32

### test host

test client host: 1 (32 cores, 24GB mem, disk space enough).

## Test Examples:
I did the stress test by randomly requesting data for the last hour in a different Time series：

|Concurrent num|time range|test time range|
|--|--|--|
|32|last hour|15:40 ~ 16:07|
|200|last hour|16:10 ~ 16:27|

## Test Result

On the monitoring chart, 15:40 to 16:07 indicates that the number of concurrent applications is 32，16:10 to 16:27 indicates that the number of concurrent applications is 200：

![图片](https://github.com/user-attachments/assets/c87dab92-48c8-41a5-863c-3caac30b8b11)
![图片](https://github.com/user-attachments/assets/7fbb61a6-856f-42d6-8e54-d8d70617ac74)

## My problem

Why does qps plummet to around 5.5k after a request period when the concurrency is 200 (exceeding the configured maximum concurrency)? At this time, it seems that the cpu and memory resource usage is not too high。I ran several more tests, and this phenomenon always occurred whenever the number of concurrent requests exceeded a certain limit。And I am confident that the test tools are problem-free and perform adequately。

Can someone please give me a reasonable explanation, I really don't see what the problem is. Thank you very much.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
I am confused with issue description.

> Why does qps plummet to around 5.5k after a request period when the concurrency is 200 (exceeding the configured maximum concurrency)?

On the graphs I see QPS ~40K queries/s from 15:40 to 16:07. And ~80K queries/s from 16:10 to 16:27.
I have no idea what the number `5.5k` you mentioned and how the `concurrency` param you mentioned results in QPS.

I'd also add that setting --search.maxConcurrentRequests=32 on vmselect effectively limits the max efficient concurrency by 32*5 = 160 QPS. The rest of requests generated by your bench suite will be put in queue, waiting for their time. So it makes not much sense in generating more than 160 concurrent requests/s.

**Comment by hagen1778** [comment]
Closing this ticket due to inactivity.
