### ISSUE TITLE
Storage full ETA dashboard panel should use free space - free space limit

### ISSUE THREAD

**Issue by eserte** [VictoriaMetrics/VictoriaMetrics#7334]
### Is your question request related to a specific component?

grafana dashboards

### Describe the question in detail

Regarding the "Storage full ETA" panel in dashboards/victoriametrics.json and dashboards/victoriametrics-cluster.json: shouldn't the query take vm_free_disk_space_limit_bytes into account? That is, make the numerator
```
(vm_free_disk_space_bytes{job=~...} - vm_free_disk_space_limit_bytes{job=~...})
```
instead of just
```
vm_free_disk_space_bytes{job=~...}
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
quickly glanced over the code, and this looks sensible to me。
