### ISSUE TITLE
Multi-arch docker images

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/VictoriaMetrics#734]
**Is your feature request related to a problem? Please describe.**

   All VM applications docker images should support Multi-arch builds, it allows end user do not care about arch version for docker image and use one image for all platforms.

**Describe the solution you'd like**
 
  Build docker images with [buildx](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

**Describe alternatives you've considered**

 Or use docker manifests.

**Additional context**

 Parent issue [link](https://github.com/VictoriaMetrics/operator/issues/71)

**Comment by valyala** [comment]
Docker images for VictoriaMetrics should already support multiple architectures - see https://hub.docker.com/r/victoriametrics/victoria-metrics/tags . The following architectures should be supported at the moment:
* amd64
* arm
* arm64
* 386
* ppc64le

See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/258 for details.

**Comment by f41gh7** [comment]
Already done!
