### ISSUE TITLE
docs: broken css for LogsQL examples

### ISSUE THREAD

**Issue by erikschul** [VictoriaMetrics/VictoriaMetrics#7341]
### Describe the bug

https://docs.victoriametrics.com/victorialogs/logsql-examples/

some examples are not visible in "light mode".

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/9c810211-af7d-49d5-91ab-b70883fe0b69">

### To Reproduce

.

### Version

.

**Comment by hagen1778** [comment]
Hey @erikschul ! Thanks for reporting the bug!
It was fixed by @AndrewChubatiuk in our docs repo and was already re-deployed to docs.victoriametrics.com.
