### ISSUE TITLE
vminsert: Add configurable label priority for -maxLabelsPerTimeseries limit

### ISSUE THREAD

**Issue by timurbabs** [VictoriaMetrics/VictoriaMetrics#7357]
### Is your feature request related to a problem? Please describe

The -maxLabelsPerTimeseries option enforces a maximum label count for each time series. If the label count exceeds this limit, labels are automatically dropped. Currently, the order in which labels are removed is not configurable, which can lead to the unintended loss of higher-priority labels.

From the documentation:

```
-maxLabelsPerTimeseries int
   The maximum number of labels accepted per time series. Extra labels are dropped, and the vm_metrics_with_dropped_labels_total metric at the /metrics endpoint is incremented (default 30).
```

### Describe the solution you'd like

Introduce a way to specify the priority of labels, allowing users to define which labels should be dropped first if the label count exceeds the configured limit. This feature would help ensure that essential labels are retained when limits are reached, providing greater control over data management.

**Comment by AndrewChubatiuk** [comment]
hey @timurbabs 
soon a meaning of this flag will be changed
timeseries instead of labels will be dropped
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6928
