### ISSUE TITLE
add fresh logs to the very top of the list

### ISSUE THREAD

**Issue by Nello-Angelo** [VictoriaMetrics/VictoriaMetrics#7366]
### Describe the solution you'd like

Is it possible to make sure that the latest logs are added to the very top of the list and not to the very bottom?

<img width="992" alt="Screenshot at Oct 25 23-37-07" src="https://github.com/user-attachments/assets/ed30895f-2132-48df-8705-d8f6bf23feb0">

**Comment by valyala** [comment]
This feature request concerns [web UI for VictoriaLogs](https://docs.victoriametrics.com/victorialogs/querying/#web-ui). It may also concern [VictoriaLogs plugin for Grafana](https://docs.victoriametrics.com/victorialogs/victorialogs-datasource/). @Loori-R , please take a look!

**Comment by Loori-R** [comment]
Duplicate of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7184. 
Will be fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7344
