### ISSUE TITLE
Timestamps before 1970

### ISSUE THREAD

**Issue by aapeliv** [VictoriaMetrics/VictoriaMetrics#7370]
### Is your question request related to a specific component?

VictoriaMetrics

### Describe the question in detail

I would like to store some historical timeseries data in VictoriaMetrics, including data that predates 1970 (unix epoch, timestamp 0).

Is this possible? I had a sniff around the codebase and it seems there may be some limitations (e.g. importing does not import past 1970), but does e.g. the storage engine support this? If not, is there a workaround?

Thanks!

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Currently we do not support ingesting data with timestamp smaller than `0`.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8551fbe9f38872fee829a9a821911ae9307ec2e7/lib/storage/table.go#L372

May I ask about the scenario for this? 

As for the workaround, it would be possible to add an offset to the timestamp. You may need to subtract the offset when viewing the data from dashboard. Also be careful with the `-retentionPeriod` flag, and make ensure data can be cleaned up as expected.

**Comment by aapeliv** [comment]
I’m trying to ingest some historical data from https://fred.stlouisfed.org/. If I recall correctly, the max retention period is 100y? So that imposes a limit?

**Comment by jiekun** [comment]
`-retentionPeriod` and `timestamp>=0` are the limits here, and cannot be overrided.
