### ISSUE TITLE
vmui hang with auto-refresh enabled

### ISSUE THREAD

**Issue by xiaozongyang** [VictoriaMetrics/VictoriaMetrics#7382]
### Describe the bug

When I query last 30 minutes data with vmui, set auto_refresh to 2s, the UI hang after refresh about 1-3 times
<img width="1890" alt="Clipboard_Screenshot_1730172943" src="https://github.com/user-attachments/assets/982cbefb-97d5-474d-8af5-d22070bc2b44">

### To Reproduce

1. visit vmui and run some query to select data
2. turn on `auto_refresh` and set it to 2s
3. Wait the browser to show the popup of `Page Unresponsive`

### Version

vmselect-20241002-113721-tags-v1.104.0-cluster-0-gdfb2ad4ab4

**Comment by jiekun** [comment]
@xiaozongyang Hi. May I ask if this bug is still bothering you?

**Comment by xiaozongyang** [comment]
@jiekun No, I can use grafana instead. You can close this issue if you can't reproduce it.

More information, my browser version is `Google Chrome, Version 127.0.6533.89 (Official Build) (arm64)`
