### ISSUE TITLE
VictoriaMetrics cannot be updated after upgrading Kubernetes version

### ISSUE THREAD

**Issue by hichenxinyu** [VictoriaMetrics/VictoriaMetrics#7389]
### Is your question request related to a specific component?

Victoriametrics in Kubernetes

### Describe the question in detail

I use VictoriaMetrics cluster version in kubernetes, using the operator method. After upgrading Kubernetes version from 1.22 to 1.26, the vmagent configuration cannot be updated because the Kubernetes podsecurity policy has been deprecated in versions after 1.25. The error is as follows. What should I do? I can no longer query the podsecurity policy in the cluster.

```
"level":"error","ts":1730183556.7510633,"msg":"Reconciler error","controller":"vmcluster","controllerGroup":"operator.victoriametrics.com","controllerKind":"VMCluster","VMCluster":{"name":"sre-vmcluster","namespace":"monitoring"},"namespace":"monitoring","name":"sre-vmcluster","reconcileID":"3208afa5-275e-4be0-9a7f-c008b9446fe0","error":"failed create or update vmcluster: cannot create podsecurity policy for vmsingle, err=failed check policy: the server could not find the requested resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
```

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @hichenxinyu 
which operator version are you using?

**Comment by hichenxinyu** [comment]
victoriametrics/operator:v0.35.1
after  I set env   to disable psp , problem solved,thanks
---
Environment:
      WATCH_NAMESPACE:
      VM_PSPAUTOCREATEENABLED:  false
