### ISSUE TITLE
VictoriaLogs: Sorting of same-timestamp logs unstable

### ISSUE THREAD

**Issue by Fusl** [VictoriaMetrics/VictoriaMetrics#7397]
### Describe the bug

When feeding multiple logs with the same timestamp into VictoriaLogs and then querying the same logs, the sorting of the logs is unstable and randomized. This causes messages in VMUI to constantly reshuffle when using the auto-refresh option.

### To Reproduce

Generate and feed 10 same-timestamp different-message logs into VictoriaLogs:
```
~ ❯ timestamp=$(date +%s)
~ ❯ for i in $(seq 1 10); do
        message=$(printf "$((i-1))%.0s" {1..${i}})
        echo '{"_msg":"'${message}'","_time":"'${timestamp}'"}' | curl -s -XPOST -T /dev/stdin "http://127.0.0.1:9428/insert/jsonline"
done
```

Query VictoriaLogs and observe the order of messages changing:
```
~ ❯ curl -s "http://127.0.0.1:9428/select/logsql/query?query=*" | jq -r ._msg | xargs
888888888 9999999999 0 77777777 6666666 555555 44444 3333 222 11
~ ❯ curl -s "http://127.0.0.1:9428/select/logsql/query?query=*" | jq -r ._msg | xargs
0 77777777 6666666 555555 44444 3333 222 11 888888888 9999999999
~ ❯ curl -s "http://127.0.0.1:9428/select/logsql/query?query=*" | jq -r ._msg | xargs
888888888 9999999999 0 77777777 6666666 555555 44444 3333 222 11
~ ❯ curl -s "http://127.0.0.1:9428/select/logsql/query?query=*" | jq -r ._msg | xargs
888888888 9999999999 0 77777777 6666666 555555 44444 3333 222 11
~ ❯ curl -s "http://127.0.0.1:9428/select/logsql/query?query=*" | jq -r ._msg | xargs
0 77777777 6666666 555555 44444 3333 222 11 888888888 9999999999
~ ❯ curl -s "http://127.0.0.1:9428/select/logsql/query?query=*" | jq -r ._msg | xargs
888888888 9999999999 0 77777777 6666666 555555 44444 3333 222 11
```

### Version

victoria-logs-20241030-140647-tags-v0.39.0-victorialogs-0-g13822f6d11

**Comment by valyala** [comment]
Unfortunately this behavior cannot be fixed because of the way VictoriaLogs performs logs' search. This is explained in [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7045#issuecomment-2448284268).

Closing the issue as answered.

**Comment by valyala** [comment]
The workaround is to assign unique [`_time`](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) value per each log entry in a single [log stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields). VictoriaLogs supports `_time` field values with nanosecond precision, so it shouldn't be too hard performing this workaround.

It is OK to have identical `_time` values across different log streams.

Another workaround is to assign automatically generated timestamps to `_time` field during logs' ingestion, and to store the original timestamp in other than `_time` field. See [these docs](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) for details.

**Comment by unlightable** [comment]
> The workaround is to assign unique [`_time`](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) value per each log entry in a single [log stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields). VictoriaLogs supports `_time` field values with nanosecond precision, so it shouldn't be too hard performing this workaround.
> 
> It is OK to have identical `_time` values across different log streams.
> 
> Another workaround is to assign automatically generated timestamps to `_time` field during logs' ingestion, and to store the original timestamp in other than `_time` field. See [these docs](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) for details.


This workaround looks promising if millisecond precision is fine enough.
I think I will try to shove a dumb counter into micro/nano parts of the time during log collection.

Although maybe similar logic could be implemented on ingest side of VL? It tracks the stream anyways, could it have flag-driven option to nudge every log entry some nanoseconds forward if it matches previous timestamp up to some fidelity?

(coming originally from https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6669#issuecomment-2457344144)
