### ISSUE TITLE
What is -maxConcurrentInserts, vm_concurrent_insert_capacity and vm_concurrent_insert_current?

### ISSUE THREAD

**Issue by timurbabs** [VictoriaMetrics/VictoriaMetrics#7404]
### Is your question request related to a specific component?

vminsert, vmagent.

### Describe the question in detail

In our setup we are using VM Cluster. We have vmagents in separate VPCs and they send data to the VM Cluster, also we have one vmagent in the same VPC with VM Cluster. Why vmagents in other VPCs constantly have zero `vm_concurrent_insert_current`, but vmagent in VM Cluster VPC and vminsert always have different `vm_concurrent_insert_current` values, but all of them have same amount of metrics and slightly same amount of load? What is the difference between `vm_concurrent_insert_current` and `-remoteWrite.queues`? How `vm_concurrent_insert_capacity` or `-maxConcurrentInserts` and `vm_concurrent_insert_current` is calculated and what they mean?
Please help, thank you!

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi @timurbabs,

vmagent and vminsert can receive remote write as well as other protocols (such as the InfluxDB line protocol) write request. Therefore, both of them have these metrics (`vm_concurrent_insert_capacity`, `vm_concurrent_insert_current`), which represent the concurrency of **handing write requests**. The limit of this capacity is controlled by `-maxConcurrentInserts`.

As for `-remoteWrite.queues`, it is only available on vmagent to manage the concurrency of writing data to external targets. Therefore, it is not relevant to the metrics mentioned above.

**Comment by timurbabs** [comment]
Can I check somehow why only one of my vmagents have more than 0 `vm_concurrent_insert_current `?

**Comment by jiekun** [comment]
You can check `vmagent_http_requests_total` metrics. It will tell you what request vmagent handled.

**Comment by timurbabs** [comment]
Thank you a lot!

**Comment by timurbabs** [comment]
In `vmagent_http_requests_total` I see 62 requests for `/-/reload` last 1 hour. How to check who is sending requests to it?

**Comment by jiekun** [comment]
`/-/reload` is for config reloading. It could be triggered by a configReloader. Do you have any other requests that look like data ingestion?

**Comment by timurbabs** [comment]
No, other paths have 0

**Comment by jiekun** [comment]
Could you show the query result for `vm_concurrent_insert_current` metrics and `vmagent_http_requests_total` **for this vmagent**?

**Comment by timurbabs** [comment]
![5271741459130869052](https://github.com/user-attachments/assets/538e12cd-8fe4-49d4-b0bc-28be888e0aa6)
![5271741459130869047](https://github.com/user-attachments/assets/c203d010-b2cd-4c6f-9551-c9b3c4c10ae6)
```
vmagent_http_requests_total{cluster="infra-cluster",container="vmagent",endpoint="http",group="infra",instance="192.168.1.44:8429",job="vmagent-vmagent-victoria-metrics-k8s-stack",namespace="monitoring",path="/-/reload",pod="vmagent-vmagent-victoria-metrics-k8s-stack-5ccdb68467-s2pcf",prometheus="monitoring/vmagent-victoria-metrics-k8s-stack",service="vmagent-vmagent-victoria-metrics-k8s-stack",workload="vmagent-vmagent-victoria-metrics"} 62

vmagent_http_requests_total{cluster="infra-cluster",container="vmagent",endpoint="http",group="infra",instance="192.168.1.44:8429",job="vmagent-vmagent-victoria-metrics-k8s-stack",namespace="monitoring",path="/service-discovery",pod="vmagent-vmagent-victoria-metrics-k8s-stack-5ccdb68467-s2pcf",prometheus="monitoring/vmagent-victoria-metrics-k8s-stack",service="vmagent-vmagent-victoria-metrics-k8s-stack",workload="vmagent-vmagent-victoria-metrics"} 1

vmagent_http_requests_total{cluster="infra-cluster",container="vmagent",endpoint="http",group="infra",instance="192.168.1.44:8429",job="vmagent-vmagent-victoria-metrics-k8s-stack",namespace="monitoring",path="/target-relabel-debug",pod="vmagent-vmagent-victoria-metrics-k8s-stack-5ccdb68467-s2pcf",prometheus="monitoring/vmagent-victoria-metrics-k8s-stack",service="vmagent-vmagent-victoria-metrics-k8s-stack",workload="vmagent-vmagent-victoria-metrics"} 1

vmagent_http_requests_total{cluster="infra-cluster",container="vmagent",endpoint="http",group="infra",instance="192.168.1.44:8429",job="vmagent-vmagent-victoria-metrics-k8s-stack",namespace="monitoring",path="/target_response",pod="vmagent-vmagent-victoria-metrics-k8s-stack-5ccdb68467-s2pcf",prometheus="monitoring/vmagent-victoria-metrics-k8s-stack",service="vmagent-vmagent-victoria-metrics-k8s-stack",workload="vmagent-vmagent-victoria-metrics"} 3

vmagent_http_requests_total{cluster="infra-cluster",container="vmagent",endpoint="http",group="infra",instance="192.168.1.44:8429",job="vmagent-vmagent-victoria-metrics-k8s-stack",namespace="monitoring",path="/targets",pod="vmagent-vmagent-victoria-metrics-k8s-stack-5ccdb68467-s2pcf",prometheus="monitoring/vmagent-victoria-metrics-k8s-stack",service="vmagent-vmagent-victoria-metrics-k8s-stack",workload="vmagent-vmagent-victoria-metrics"} 3
```

**Comment by timurbabs** [comment]
Resending the images:
![5271741459130869052](https://github.com/user-attachments/assets/2417ed01-945a-4e54-9e12-ed9c711d749f)
![5271741459130869047](https://github.com/user-attachments/assets/34fe84b1-75b7-4f74-896f-b434de9c4f4d)

**Comment by timurbabs** [comment]
@jiekun,
I checked this vmagent using tcpdump but I don't see any requests for `/-/reload` path. How vmagent_http_requests_total for it can be 62?
