### ISSUE TITLE
Unable to Install vmagent from the Helm chart

### ISSUE THREAD

**Issue by anamika-nih** [VictoriaMetrics/VictoriaMetrics#7406]
### Is your question request related to a specific component?

vmagent

### Describe the question in detail

Hello, I am following the documentation to do the step3 - Install vmagent from the Helm chart
https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-cluster/

`helm install vmagent vm/victoria-metrics-agent -f https://docs.victoriametrics.com/guides/examples/guide-vmcluster-vmagent-values.yaml`

However, I am encountering this error:

`Error: INSTALLATION FAILED: execution error at (victoria-metrics-agent/templates/deployment.yaml:51:19): Please define at least one remoteWrite`

Can you please explain what needs to be done to resolve the issue?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by AndrewChubatiuk** [comment]
hey @anamika-nih 
victoria-metrics-agent helm chart configures an agent for, which collects metrics. Besides it you need to have a database, where all these collected metrics should be stored. It can be either victoria metrics single or cluster setup. victoria-metrics-agent chart fails deployment if url to a database is not set. You can pass it like this:
```
remoteWrite:
  - url: <vmsingle-or-vmcluster-url>
```

**Comment by AndrewChubatiuk** [comment]
@anamika-nih 
Thanks for an issue, fixed a guide in PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7411/files

**Comment by anamika-nih** [comment]
@AndrewChubatiuk can you please fix the yaml files in the official docs too? 
YAML file https://docs.victoriametrics.com/guides/examples/guide-vmcluster-vmagent-values.yaml
Official doc - https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-cluster/#3-install-vmagent-from-the-helm-chart

**Comment by AndrewChubatiuk** [comment]
@anamika-nih fixes are already available in docs
