### ISSUE TITLE
VictoriaLogs: Support for `_time:step` buckets in `uniq by (...)` pipe

### ISSUE THREAD

**Issue by Fusl** [VictoriaMetrics/VictoriaMetrics#7407]
### Describe the solution you'd like

VictoriaLogs supports the `_time:step` syntax for `stats by (...)` pipes but not for `uniq by (...)` pipes. This would make it useful to, for example, deduplicate multiple field values within a certain time period.

Raw samples:
```
{"field":"foo","_time":"2024-10-31T15:31:00Z"}
{"field":"foo","_time":"2024-10-31T15:34:00Z"}
{"field":"bar","_time":"2024-10-31T15:36:00Z"}
{"field":"foo","_time":"2024-10-31T15:39:00Z"}
{"field":"bar","_time":"2024-10-31T15:41:00Z"}
{"field":"bar","_time":"2024-10-31T15:43:00Z"}
{"field":"foo","_time":"2024-10-31T15:44:00Z"}
{"field":"foo","_time":"2024-10-31T15:46:00Z"}
```

Expected result after applying `| uniq by (field,_time:5m)`:
```
{"field":"foo","_time":"2024-10-31T15:30:00Z"}
{"field":"bar","_time":"2024-10-31T15:35:00Z"}
{"field":"foo","_time":"2024-10-31T15:35:00Z"}
{"field":"bar","_time":"2024-10-31T15:40:00Z"}
{"field":"foo","_time":"2024-10-31T15:40:00Z"}
{"field":"foo","_time":"2024-10-31T15:45:00Z"}
```

### Describe alternatives you've considered

`stats by (field,_time:step) count() count | drop count` works as an interim solution but the syntax isn't as nice to use as an equivalent shorthand `uniq by (field,_time:step)` would be and probably has some computational overhead.

**Comment by valyala** [comment]
@Fusl , try [`uniq_values` stats function](https://docs.victoriametrics.com/victorialogs/logsql/#uniq_values-stats). For example, the following query will return unique values for the field `user_id` per every 5 minutes over logs for the last hour:

```logsql
_time:1h | stats by (_time:5m) uniq_values(user_id)
```

**Comment by Fusl** [comment]
Unfortunately this syntax doesn't provide the format in a way that's useful for further aggregation with chained pipes. It returns the individual field values collapsed and aggregated into a single line for each time step:
```
{"_time":"2024-10-31T15:30:00Z","uniq_values(field)":"[\"foo\"]"}
{"_time":"2024-10-31T15:35:00Z","uniq_values(field)":"[\"bar\",\"foo\"]"}
{"_time":"2024-10-31T15:40:00Z","uniq_values(field)":"[\"bar\",\"foo\"]"}
{"_time":"2024-10-31T15:45:00Z","uniq_values(field)":"[\"foo\"]"}
```

**Comment by valyala** [comment]
Then just pass the returned values into [`unroll` pipe](https://docs.victoriametrics.com/victorialogs/logsql/#unroll-pipe) as documented in [`unique_values` pipe docs](https://docs.victoriametrics.com/victorialogs/logsql/#uniq_values-stats):

```logsql
_time:1h
  | stats by (_time:5m) uniq_values(user_id)
  | unroll by (user_id)
```

**Comment by valyala** [comment]
Closing the question as answered.

@Fusl , feel free opening a new issue if `uniq_values` followed by `unroll` pipes do not resolve your use case.
