### ISSUE TITLE
VictoriaLogs # LogsQL rate function 

### ISSUE THREAD

**Issue by top1ing** [VictoriaMetrics/VictoriaMetrics#7415]
### Describe the solution you'd like

Add **rate** function to LogsQL for calculate the number of entries per second.

**Comment by valyala** [comment]
FYI, in the mean time it is possible emulating `rate()` function in LogsQL according to [this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7646#issuecomment-2502085991).

**Comment by valyala** [comment]
The [`rate`](https://docs.victoriametrics.com/victorialogs/logsql/#rate-stats) and [`rate_sum`](https://docs.victoriametrics.com/victorialogs/logsql/#rate_sum-stats) functions are available starting from [v1.2.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) release. Closing the feature request as done.
