### ISSUE TITLE
VictoriaLogs: vector v0.42.0 attach loki metadata, result in errors during ingestion

### ISSUE THREAD

**Issue by jiekun** [VictoriaMetrics/VictoriaMetrics#7431]
#### Source
https://victoriametrics.slack.com/archives/C05UNTPAEDN/p1730754569831629

#### Log
```
{"ts":"2024-11-04T20:43:42.688Z","level":"warn","caller":"VictoriaMetrics/app/vlinsert/loki/loki_json.go:59","msg":"remoteAddr: \"172.18.0.3:37444, X-Forwarded-For: 35.160.204.137, 10.1.6.210\"; requestURI: ...; cannot parse Loki json request: unexpected number of values in `values` item array "..."; got 3 want 2"}
```

#### Cause
Since Vector [v0.42.0](https://vector.dev/releases/0.42.0/):
> The Loki sink now has support for sending structured metadata when using the JSON API (the default). Thanks to [maxboone](https://github.com/maxboone) for contributing this change!

It can now append metadata at the end of each `values` array item correctly.

Example of the request body for v0.42.0 and previous version:
```json
{
    "streams": [
        {
            "stream": {
                "source": "vector"
            },
            "values": [
                [
                    "1730790583903710090",
                    "{\"host\":\"jiekun\",\"message\":\"hello world!\",\"source_type\":\"stdin\"}",
                    {
                    }
                ]
            ]
        }
    ]
}
```

```json
{
    "streams": [
        {
            "stream": {
                "source": "vector"
            },
            "values": [
                [
                    "1730790630875982731",
                    "{\"host\":\"jiekun\",\"message\":\"hello world!\",\"source_type\":\"stdin\"}"
                ]
            ]
        }
    ]
}
```

Currently VictoriaLogs has hardcoded validation for `values`:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/478468e6cd8f98dbce14e68a3cb3751239ff07c9/app/vlinsert/loki/loki_json.go#L143-L145

According to loki's [doc](https://grafana.com/docs/loki/latest/reference/loki-http-api/#ingest-logs):
> You can optionally attach [structured metadata](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/) to each log line by adding a JSON object to the end of the log line array.

So this validation is incorrect when metadata is attached.

### To Reproduce

1. Download vector v0.42.0 from: https://github.com/vectordotdev/vector/releases and extract the binary.
2. create a `vector-config.yaml` with following content:
```yaml
sources:
  in:
    type: "stdin"

sinks:
  vlogs:
    type: "loki"
    endpoint: "http://localhost:9428/insert/loki/"
    inputs:
      - in
    compression: gzip
    path: /api/v1/push?_msg_field=message.message&_time_field=timestamp&_stream_fields=source
    encoding:
      codec: json
    labels:
      source: vector
```
3. start VictoriaLogs.
4. run `echo 'hello world!' | ./vector -c ./vector.yaml`

expect: error log like this:
```
2024-11-05T07:00:41.496Z        warn    app/vlinsert/loki/loki_json.go:59       remoteAddr: "127.0.0.1:49098"; requestURI: /insert/loki/api/v1/push?_msg_field=message.message&_time_field=timestamp&_stream_fields=source; cannot parse Loki json request: unexpected number of values in `values` item array "[\"1730789774113558713\",\"{\\\"host\\\":\\\"jiekun\\\",\\\"message\\\":\\\"hello world!\\\",\\\"source_type\\\":\\\"stdin\\\"}\",{}]"; got 3 want 2
```

5. Download vector v0.41.1 and test again. It should works fine.

### Version

Since: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4482

**Comment by valyala** [comment]
VictoriaLogs supports [structured metadata](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/) in [JSON-based loki data ingestion protocol](https://docs.victoriametrics.com/victorialogs/data-ingestion/#loki-json-api) starting from [v0.41.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).
