### ISSUE TITLE
Strange inconsistency between vmui and grafana instant query

### ISSUE THREAD

**Issue by FlorianVielhauer** [VictoriaMetrics/VictoriaMetrics#7436]
### Describe the question in detail

Hi,

We are using VictoriaMetrics v1.105 and are experiencing a strange behaviour in Grafana when using "instant" queries.

When executing the attached query, we are getting the following results in VMUI:

[vmui_report_2024-11-05_114359.json](https://github.com/user-attachments/files/17631868/vmui_report_2024-11-05_114359.json)

![image](https://github.com/user-attachments/assets/e959d03f-57ad-4650-b797-c30b6a3f1c90)

![image](https://github.com/user-attachments/assets/140be9bd-ca03-4f80-bb42-ec3a2786ce97)

The goal of the query is to count the number of times a state changes to a certain value. In this example we want to count how many times the status metric changed to value "1" in a certain time frame. 

The results in vmui look correct to me. The graph looks fine and under "table" we can see value "24" which corresponds to the last point in the graph.

In Grafana we get the same graph as in vmui. The graph also ends with value "24" but as "instant value", we get "4":

![image](https://github.com/user-attachments/assets/52d1fcd1-7364-4968-a070-571f33d1d44d)

We are using Grafana v10.0.2.

Do you have an explanation for this? Shouldn't the "instant" value in Grafana always show the last value in the graph? Or is there some kind of misunderstanding on our side?

We also experienced that sometimes the displayed "instant" value is correct for other queries - the behaviour looks quite random to us and we are completely confused how and when this can happen.

Any help is highly appreciated. :-)

BR,
Florian

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
> increases_over_time((kiosk_status{hostname="easykiosk-8",instance="10.0.1.127:8080"} ==bool 1)[12h])

This expression uses [subquery](https://docs.victoriametrics.com/metricsql/#subqueries). You can check it in attached trace. Subquery syntax expects user to specify time interval and step `[interval:step]`. However, `step` can be omitted and then VM will try to use `step` from GET params of the request. Grafana and vmui could have different `step` param sent with instant queries. You can check it by opening a NetworkTab in your browser and checking what is actually sent by browser in payload. This could result into difference in responses, as it would be different queries.

The query also looks weird to me, as it filters `kiosk_status` metric by value. And value is exactly what is used to calculate `increases_over_time`. Maybe if you could explain what you want to achieve with this expression I could recommend a better way to do this?

**Comment by FlorianVielhauer** [comment]
Thank you very much for explanation!

> Subquery syntax expects user to specify time interval and step [interval:step]

When I change the query to

`increases_over_time((kiosk_status{hostname="easykiosk-8",instance="10.0.1.100:8080"} ==bool 1)[12h:30s])` 

I get the expected results in Grafana. :-) This solves my issue, thanks!

For deeper investigation:

When I send the query without `:step`, Grafana sends this POST request:

![image](https://github.com/user-attachments/assets/85876562-a8f9-4d2d-89ce-3e85947d6357)

I don't see a `step` parameter somewhere but maybe you can see something?

> The query also looks weird to me, as it filters kiosk_status metric by value. And value is exactly what is used to calculate increases_over_time. Maybe if you could explain what you want to achieve with this expression I could recommend a better way to do this?

I tried to explain it in the original post:

> The goal of the query is to count the number of times a state changes to a certain value. In this example we want to count how many times the status metric changed to value "1" in a certain time frame.

We have a metric `kiosk_status` which reflects the current state of a client. It is a gauge which can have values from 0 to 7 - each value represents a certain state. Value `1` for example means "ErrorState". With the query we want to count how many times the client has switched to error state in a certain time range. We are not interested in how long the client was in this state, we only want to know how often it switches to this state.

Therefore we had the idea to convert all values to bool (1 = true, all other values = false) and then use `increase_over_time` to count how many times there is a switch from false to true. 

Is there a better or more correct approach to achieve this?

**Comment by hagen1778** [comment]
> I don't see a step parameter somewhere but maybe you can see something?

If Grafana doesn't send, then it is likely set to some default value on vmselect. And it is likely vmui is sending the `step`, and this is why queries from it don't get this default value for step.

> Is there a better or more correct approach to achieve this?

Seems like a good approach. Thanks!

I'm closing this ticket as answered.
