### ISSUE TITLE
Changing the stream fields in Victoria logs when ingesting through syslog. 

### ISSUE THREAD

**Issue by deepanshu-yadav** [VictoriaMetrics/VictoriaMetrics#7480]
### Is your question request related to a specific component?

Victoria Logs

### Describe the question in detail

Hi! I was trying out Victoria logs and ingesting some logs through syslog.
and found out that the number of streams created were quite huge.

 vl_streams_created_total   **1646059** 
And also found out that the rate of growth remains at **150** per second.
So my first question is that a problem ? I suspect it will reduce query time later.

If yes These were my stream fields
`streamFields= {app_name="foo-bar",hostname="blah",proc_id="1"}`
Out of that main culprit is I think is `proc_id` and I don’t want it as well.

I tried specifying fields when I start the application.  `-journald.streamFields=:app_name,:hostname -logNewStreams=true`
But that did not work I still see the issue. And getting the same rate of growth. 
The only solution I could think is changing the format of ingestion to something like
`template(name="WithoutProcId" type="string" string="<%PRI%>%TIMESTAMP% %HOSTNAME% %app-name% - %msg%\n")`
But that is not easy to do as they are coming from source.
So my second question is there a way for Victoria logs to neglect the stream field `proc_id` and consider only `app_name` and `hostname` when ingesting the logs through syslog?

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by amabilee** [comment]
Hey there!

> And also found out that the rate of growth remains at 150 per second.
> So my first question is that a problem ?

Having a large number of streams can impact query performance and complicate log management. It's generally a good idea to reduce the number of streams if possible.

> So my second question is there a way for Victoria logs to neglect the stream field proc_id and consider only app_name and hostname when ingesting the logs through syslog?

You can configure Victoria Logs to ignore specific fields during data ingestion by using the ignore_fields parameter:
`ignore_fields: proc_id`

**Comment by deepanshu-yadav** [comment]
Hi Thank you for your answer I tried your solution using the following  `-journald.streamFields=:app_name,:hostname  -journald.ignoreFields=:proc_id  -logNewStreams=true` . I suspect this should work but unfortunately it didn't I still see streams with proc_id. 
<img width="674" alt="Screenshot 2024-11-07 at 14 48 17" src="https://github.com/user-attachments/assets/a0640a98-bd98-4f5a-9013-f73993182d88">

**Comment by AndrewChubatiuk** [comment]
hey @deepanshu-yadav 
if you want to see benefits from using `-journald.streamFields` you need to ingest data to [journald](https://docs.victoriametrics.com/victorialogs/data-ingestion/journald/) endpoint instead

**Comment by deepanshu-yadav** [comment]
Thanks @AndrewChubatiuk  Will close this issue in lieu of this pull request later.

**Comment by deepanshu-yadav** [comment]
Also @AndrewChubatiuk @valyala Do you guys know about what will happen to to all those streams that were created before  once I will rerun victoria logs that contains this feature? Do I have delete my directory that contained previous logs?

**Comment by valyala** [comment]
> Do you guys know about what will happen to to all those streams that were created before once I will rerun victoria logs that contains this feature? Do I have delete my directory that contained previous logs?

All the previously created log streams will remain available for querying. VictoriaLogs stores log streams independently per each day, so old log streams shouldn't affect performance of queries over time ranges, which do not cover dates when logs with big number of streams were ingested into VictoriaLogs. It is also possible dropping the ingested data on per-day basis by using the following steps:

1. Stop VictoriaLogs
2. Drop folders for the needed days from the `<-storageDataPath>/partitions/` folder, where `-storageDataPath` is the corresponding command-line flag value. This folder contains per-day data in folders named as `YYYYMMDD` format, where `YYYY` is the year, `MM` is the month number [`01` .. `12`] and `DD` is the day of month by UTC time. For example, `20241105` corresponds to logs with [`_time` field](https://docs.victoriametrics.com/victorialogs/keyconcepts/#time-field) belonging to November 5, 2024 UTC.
3. Start VictoriaLogs.

**Comment by valyala** [comment]
The commit 4f0bec6f036b868171f4c5484bd9f3ac7c59fa7c adds support for overriding the default set of [log stream](https://docs.victoriametrics.com/victorialogs/keyconcepts/#stream-fields) fields for logs ingested via Syslog protocol. See [these docs](https://docs.victoriametrics.com/victorialogs/data-ingestion/syslog/#stream-fields) for details.

This commit will be included in the next release. In the mean time it is possible to build VictoriaLogs from this commit according to [these docs](https://docs.victoriametrics.com/victorialogs/quickstart/#building-from-source-code) and verifying whether this feature works as expected.

**Comment by valyala** [comment]
VictoriaLogs supports overriding log stream fields via `-syslog.streamFields.tcp` and `-syslog.streamFields.udp` command-line flags starting from [v0.42.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/) - see [these docs](https://docs.victoriametrics.com/victorialogs/data-ingestion/syslog/#stream-fields).

Closing the feature request as done.
