### ISSUE TITLE
vmselect conn vmstorage timeout

### ISSUE THREAD

**Issue by wgb1990** [VictoriaMetrics/VictoriaMetrics#7481]
### Is your question request related to a specific component?

vmselect/vmstorage version 1.91.2

### Describe the question in detail

I have 44 vmstorage nodes, and this morning one node suddenly became unstable. The vmselect query timeout is relatively high, resulting in many query failures, but there is no delay during the writing process, so it can be confirmed that this is not a network issue.

this is vmstorage error log
![image](https://github.com/user-attachments/assets/248c7b9a-42b1-4a8e-a603-bba60cc8e62b)
this is vmselect error log 
![image](https://github.com/user-attachments/assets/454ec470-4456-4a72-b9e6-cb7ebc9454fc)

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [x] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [x] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. 
> one node suddenly became unstable

Have you checked the "TCP connections" and "TCP connections rate" of this vmstorage (and vmselect)? Those metrics are available on our [Grafana dashboard](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/), or via the following MetricsQL:
```
sum(max_over_time(vm_tcplistener_conns{job=~"$job", instance=~"$instance"}[$__interval])) by(job)

sum(rate(vm_tcplistener_accepts_total{job=~"$job", instance=~"$instance"}[$__rate_interval])) by(job)
```

Did you observe any other abnormalities (e.g. spikes) on other dashboards?

**Comment by wgb1990** [comment]
> Hi.
> 
> > one node suddenly became unstable
> 
> Have you checked the "TCP connections" and "TCP connections rate" of this vmstorage (and vmselect)? Those metrics are available on our [Grafana dashboard](https://grafana.com/grafana/dashboards/11176-victoriametrics-cluster/), or via the following MetricsQL:
> 
> ```
> sum(max_over_time(vm_tcplistener_conns{job=~"$job", instance=~"$instance"}[$__interval])) by(job)
> 
> sum(rate(vm_tcplistener_accepts_total{job=~"$job", instance=~"$instance"}[$__rate_interval])) by(job)
> ```
> 
> Did you observe any other abnormalities (e.g. spikes) on other dashboards?

thank you  reply !
confirm it is a bug in the linux kernel, after restarting the machine, vmstorage returned to normal ！(https://lore.kernel.org/lkml/20210927170235.589030577 )
