### ISSUE TITLE
Loki JSON parsing: show which logs were parsed

### ISSUE THREAD

**Issue by vrutkovs** [VictoriaMetrics/VictoriaMetrics#7490]
### Describe the bug

When Loki client sends requests without `streams` arg the warning is printed in VL logs:
```
VictoriaMetrics/app/vlinsert/loki/loki_json.go:60        remoteAddr: "192.168.1.165:1406"; requestURI: /insert/loki/api/v1/push; cannot parse Loki json request: `streams` item in the parsed JSON must contain an array; got "null"
```

However it does not print other parsed labels or request headers so it may not be easy to find the offending client

### To Reproduce

Not trivial probably, I managed to make it happen by pointing https://github.com/unpoller/unpoller to VL instead of Loki

### Version
```
victoria-logs-20241106-191052-tags-v0.41.0-victorialogs-0-ga4ce80b4ea
```

### Logs

```
victorialogs[1200866]: 2024-11-08T10:04:23.533Z        warn        VictoriaMetrics/app/vlinsert/loki/loki_json.go:60        remoteAddr: "192.168.1.165:1406"; requestURI: /insert/loki/api/v1/push; cannot parse Loki json request: `streams` item in the parsed JSON must contain an array; got "null"
```

**Comment by valyala** [comment]
VictoriaLogs will print the original request body on parse errors for [JSON-based Loki data ingestion protocol](https://docs.victoriametrics.com/victorialogs/data-ingestion/#loki-json-api) starting from the commit 342f84c5693bff17778f9c972bc584b4a53d854a . This commit will be included in the next release.

**Comment by valyala** [comment]
VictoriaLogs prints the original request body on parse errors for [JSON-based Loki data ingestion protocol](https://docs.victoriametrics.com/victorialogs/data-ingestion/#loki-json-api) starting from [v0.42.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/). Closing the feature request as done.
