### ISSUE TITLE
Vmauth - Features Configuration Validation

### ISSUE THREAD

**Issue by nulldoot2k** [VictoriaMetrics/VictoriaMetrics#7505]
### Is your feature request related to a problem? Please describe

Add Nginx-Like Features and Configuration Validation to Vmauth
How can I check the configuration status vmauth before it is initialized or running?

### Describe the solution you'd like

I would like to request the addition of Nginx-like features to Vmauth. Specifically, I am interested in having the ability to validate the configuration of Vmauth in a manner similar to the nginx -t command for Nginx.

For Nginx we need the command line: nginx -t --> check config
For Vmauth currently in the Flag document I see we are missing a flag for checking the configuration before being deployed and running.

I think we need a **subcmd** like
**vmauth-prod -t vmauth.conf**
and **vmauth-prod -s** for sending signals to the Vmauth process to perform actions like reloading the configuration

### Additional information

Thank you for your attention to this request. Looking forward to the possibility of seeing this feature added to Vmauth.

**Comment by f41gh7** [comment]
It'd be great to have `--dryRun` flag that only validates configuration file and exists immediately.
