### ISSUE TITLE
[DOC] mind slip about `vlogscli` vs. `vlogsql`

### ISSUE THREAD

**Issue by grinapo** [VictoriaMetrics/VictoriaMetrics#7512]
### Describe the bug

https://docs.victoriametrics.com/victorialogs/querying/vlogscli/ consistently thinks they are `vlogsql`, except in a few places. But the start of the docs thinks `vlogscli` while the rest calls it `vlogsql`.

(And the code seems to be vlogscli anyway.)

### To Reproduce

:-)

### Version

Actual web version.

### Screenshots

Configuration [#](https://docs.victoriametrics.com/victorialogs/querying/vlogscli/#configuration)

By default **vlogscli** sends queries to [http://localhost:8429/select/logsql/query](https://docs.victoriametrics.com/victorialogs/querying/#querying-logs). The url to query can be changed via -datasource.url command-line flag. For example, the following command instructs **vlogsql** sending queries to https://victoria-logs.some-domain.com/select/logsql/query:

**Comment by valyala** [comment]
@grinapo , thanks for the pointer to the issue with [`vlogscli`](https://docs.victoriametrics.com/victorialogs/querying/vlogscli/) docs! The issue has been fixed in the commit 4837dc6e09539f4eba18b32d707d780c7029baf2 . Closing the issue as fixed.
