### ISSUE TITLE
Prometheus Data Migration to VictoriaMetrics Using vmctl Not Successful

### ISSUE THREAD

**Issue by abolfazlyarian** [VictoriaMetrics/VictoriaMetrics#7530]
### Is your question request related to a specific component?

it is related to `vmctl` for data migration. 

### Describe the question in detail

I have a Prometheus instance that has been running since 2019, and I need to migrate its data to a new VictoriaMetrics cluster using vmctl. Initially, I tried the Prometheus migration mode. After creating a snapshot in Prometheus, I ran the following command to begin the migration:
```
sudo docker run --net host -v /mnt/disk1:/mnt/disk1 -it victoriametrics/vmctl:v1.106.0 prometheus --prom-snapshot=/mnt/disk1/prometheusTSDB/snapshots/20241111T110846Z-1160fe94faffa216/ --vm-addr=http://10.244.211.35:8480 --vm-account-id 0 --verbose --prom-concurrency=10 --vm-concurrency=5
```
Note: "10.244.211.35:8480" address of the vminsert but the vmagent using the 10.244.211.35:8480/insert/0/prometheus to inserting data.
The migration process ran for approximately 36 hours. However, when I checked VictoriaMetrics to verify the data (using the query up), the data from Prometheus was not present. In other words, vmctl completed without errors, but the data did not appear in VictoriaMetrics.

To troubleshoot, I added a time filter to limit the migration to just one month (November 2022) to reduce the dataset and test the process, but this also did not work.

Expected Behavior: Data from Prometheus should appear in VictoriaMetrics after a successful migration with vmctl.

### Troubleshooting docs

- [ ] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Could you provide the logs from vmctl and vminsert?

Also, it seems you are using a wrong value for `--vm-addr` flag. In your case it should be: 
```
http://10.244.211.35:8480/insert/<accountID>/prometheus
```

**Comment by abolfazlyarian** [comment]
I resolved the initial issue, which was related to the `retentionPeriod` being set shorter than the time range I wanted to migrate from Prometheus. However, I’ve encountered another issue with vmctl. I attempted to migrate data from the past two years, but when I query the result (e.g., using the up PromQL query), the data appears incomplete—the graph is not continuous.

Additionally, when the vmctl migration command completed, I didn’t receive the detailed "VictoriaMetrics importer stats" output that typically provides information such as "import requests". Instead, the output was limited to the following:

VictoriaMetrics importer stats:
  idle duration: 36m40.68162561s;
  time spent while importing: 23h13m13.69401492s

How can I ensure a safe and complete migration of data?

**Comment by jiekun** [comment]
Hello. This log seems incorrect base on v1.106.0 codes [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d5c180e6800c5e7a5cc39f3456e1a811f43e7a7e/app/vmctl/vm/stats.go#L34). Could you try again on a smaller time range so that it can finish quickly and check the log output? Also, is this issue reproducible consistently?

**Comment by jiekun** [comment]
Hello. I'd like to close this issue as inactive. Please feel free to reopen it if you still encounter the same issue and require assistance from us.
