### ISSUE TITLE
vmselect: prevent panics

### ISSUE THREAD

**Issue by tIGO** [VictoriaMetrics/VictoriaMetrics#7549]
### Describe the bug

1. `vmselect` panics on multitenant selects if there are no tenants yet
2. If `populateSqTenantTokensIfNeeded` fails netstorage [wraps](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/netstorage/netstorage.go#L1058) it in `[]*nodeResult`. Later it will fail on [typecast](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/netstorage/netstorage.go#L1080) to `[]any`. Look at the [playground](https://go.dev/play/p/XnKdOy6heNn).  Currently, it is impossible since `populateSqTenantTokensIfNeeded` always returns `nil` error.
3. There is no need to call `populateSqTenantTokensIfNeeded` multiple times from different goroutines and modify the shared variable `sq` (a potential source of bugs)

### To Reproduce

Run fresh cluster with vmselect and vmstorage. Query arbitrary data in multitenant mode (e.g. `{a="b"}`)
<img width="387" alt="Screenshot 2024-11-15 at 12 51 26" src="https://github.com/user-attachments/assets/a907aa32-7272-4742-86b9-c0ff8ddeae6f">
<img width="918" alt="Screenshot 2024-11-15 at 12 51 48" src="https://github.com/user-attachments/assets/d515e9bb-d322-40c7-ac21-4b4eac5b30f2">

### Version

1.104.0-cluster+

**Comment by f41gh7** [comment]
The bugfix was included into [v1.106.1](https://docs.victoriametrics.com/changelog/#v11061)

**Comment by f41gh7** [comment]
The bugfix was included into [v1.107.0](https://docs.victoriametrics.com/changelog/#v11070)
