### ISSUE TITLE
vmagent: generate different IDs for persistent queues if the same URL is multiple times in remoteWrite.url

### ISSUE THREAD

**Issue by aval13** [VictoriaMetrics/VictoriaMetrics#755]
**Describe the bug**
When using the same URL twice in -remoteWrite.url parameter, the fast persistent queue IDs (used as subfolders in the remoteWrite.tmpDataPath folder) are the same.
Use case: vmagent scrapes exporters and sends the metrics to the same vmauth (using using 2 sets of credentials), each set of credentials in vmauth sends its metrics stream to a different Victoria Metrics Cluster insert node.
CREDS 1
vmagent ====> vmauth | ---> vminsert cluster 1
CREDS 2                            | ---> vminsert cluster 2

**To Reproduce**
Start vmagent with the remoteWrite parameters: -remoteWrite.url https://auth.service,https://auth.service -remoteWrite.basicAuth.username USER1,USER2 -remoteWrite.basicAuth.password PASS1,PASS2
The logs will tell something like this (2 identical lines):
info    VictoriaMetrics/lib/persistentqueue/fastqueue.go:46     opened fast persistent queue at "/var/lib/vmagent-remotewrite-data/persistent-queue/738A2745C2BB25E0" with maxInmemoryBlocks=200
...
info    VictoriaMetrics/lib/persistentqueue/fastqueue.go:46     opened fast persistent queue at "/var/lib/vmagent-remotewrite-data/persistent-queue/738A2745C2BB25E0" with maxInmemoryBlocks=200

**Expected behavior**
vmagent should use different IDs for the queues of the 2 remoteWrite.url URLs, something like:
info    VictoriaMetrics/lib/persistentqueue/fastqueue.go:46     opened fast persistent queue at "/var/lib/vmagent-remotewrite-data/persistent-queue/SOME_QUEUE_ID" with maxInmemoryBlocks=200
info    VictoriaMetrics/lib/persistentqueue/fastqueue.go:46     opened fast persistent queue at "/var/lib/vmagent-remotewrite-data/persistent-queue/SOME_OTHER_QUEUE_ID" with maxInmemoryBlocks=200
I am not sure if vmagent can handle 2 streams of metrics buffered in the same subfolder, by the looks of the files in the queue ID subfolder it does not.

**Screenshots**
N/A

**Version**
vmagent-20200903-232636-tags-v1.40.1-cluster-0-gd2f6f96e4

**Used command-line flags**
-memory.allowedPercent X -remoteWrite.tmpDataPath /var/lib/vmagent-remotewrite-data -httpListenAddr=''
-promscrape.config /prometheus.yml -promscrape.discovery.concurrency X
-remoteWrite.url https://auth.service,https://auth.service -remoteWrite.tlsCAFile /SOMECA.crt
-remoteWrite.basicAuth.username USER1,USER2 -remoteWrite.basicAuth.password PASS1,PASS2
(yes, it's run as a container via docker)

**Additional context**
Will add more details and/or logs if asked in the comments.
I would suggest a solution in order to maintain predictability in case the vmagent-remotewrite-data folder has useful data in it when restarting vmagent: when computing the "hash" for the queue ID, prefix what you are "hashing" with the positional index in the "array" for the urls, in my case above, instead of "hashing" let's say https://auth.service twice and coming up with the same hash, has "0https://auth.service" and "1https://auth.service". As long as the URLs order does not change, the hash will be consistent between service restarts.
Disclaimer: I did not look at the source code yet, so I'm guesstimating some of the stuff above.

**Comment by valyala** [comment]
@aval13 , could you build `vmagent` from the commit ca856284e4ab55e163b837fbe9f573ca0cfa226b and verify whether it works as expected when multiple identical `-remoteWrite.url` command-line flags are passed to it? See [build instructions for vmagent](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources)

**Comment by valyala** [comment]
The feature has been added to [v1.41.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as done.

@aval13 , feel free re-opening it if it doesn't work as expected.
