### ISSUE TITLE
[Document] Vector does not support OpenTelemetry as sink

### ISSUE THREAD

**Issue by windware-ono** [VictoriaMetrics/VictoriaMetrics#7557]
### Describe the bug

In the document,
https://docs.victoriametrics.com/victorialogs/data-ingestion/#log-collectors-and-data-ingestion-formats
it mentions Vector supporting OpenTelemetry but Vector only supports OpenTelemetry as a source but not as a sink.

https://vector.dev/docs/reference/configuration/sources/
https://vector.dev/docs/reference/configuration/sinks/

### To Reproduce

Reading the document.

### Version

As of 2024/Nov/17th.

**Comment by jiekun** [comment]
This looks like a mistake in doc, as it's still in their roadmap: https://github.com/vectordotdev/vector/issues/13622

Thanks for pointing it out. Would you like to raise a pull request to fix it?

**Comment by AndrewChubatiuk** [comment]
closed as fix is available in documentation
