### ISSUE TITLE
Grafana dashboard: API path variable

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#756]
**Is your feature request related to a problem? Please describe.**
query request rate / duration / error rate panels are mixing series with very different value ranges-- often we want to see stats for a specific API path like query_range.  But selecting the specific time series in all 3 panels is cumbersome (especially for duration, which has multiple series per path).

and for duration, using linear scale is not ideal when mixing 50 and 99.9 percentiles, since the 50% will likely be negligible

**Describe the solution you'd like**
  * Add API path variable to the dashboard (multi-select + All).
  * change query duration scale to log

![Screen Shot 2020-09-09 at 11 04 19 AM](https://user-images.githubusercontent.com/1708631/92545944-48444b80-f28c-11ea-9c28-d417723d1f60.png)

**Comment by belm0** [comment]
if it sounds reasonable, I'll submit a PR

**Comment by valyala** [comment]
This sounds reasonable to me. @hagen1778 , what do you think?

**Comment by hagen1778** [comment]
I don't have strong opinion about this. The thing that stopped me for voting up is that `path` is related to specific panels only, while other vars are global and affect every panel. The second thing is that `path` is specific for every component in cluster: 
* vminsert serves `insert/.*` requests
* vmselect serves `select/.*` requests
So it is unclear to me which `path` options var should contain.

**Comment by valyala** [comment]
Then how about changing query duration scale to log? This looks OK

**Comment by belm0** [comment]
>  The thing that stopped me for voting up is that path is related to specific panels only, while other vars are global and affect every panel.

This is not unusual at all for grafana dashboards.  Grafana has enough limitations on its own, so I'm not sure why you'd want to self-impose an additional constraint that dashboard variables need to be used in every panel.  Examples:  a variable for percentile that applies to histogram queries, a variable for interval that the user can use to smooth out graphs, etc.

> The second thing is that path is specific for every component in cluster:

In my prototype (please see screenshot), the variable is actually "API path" and is constrained to `/api/.*` paths.

**Comment by hagen1778** [comment]
This sounds reasonable. Thanks!

> if it sounds reasonable, I'll submit a PR

I'd appreciate your help.

**Comment by hagen1778** [comment]
Closing as inactive.
