### ISSUE TITLE
How dose vm handle NaN?

### ISSUE THREAD

**Issue by XMingG99** [VictoriaMetrics/VictoriaMetrics#7572]
### Describe the question in detail

Three questions:
1. Can vmalter aggregate NaN values
2. How do various components of VM handle NaN values?
3 Will vminsert ignore NaN values? Will vmstorage delete the nan value? How does vmselect observe the NaN value of an indicator?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [ ] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by hagen1778** [comment]
> Can vmalter aggregate NaN values

Could you please elaborate on this?

> How do various components of VM handle NaN values?

vmselect doesn't return NaNs to user requests via /query and /query_range API. But does return NaNs for /export API

> Will vminsert ignore NaN values?

No, it will send them as is.

> Will vmstorage delete the nan value?

Yes, it deletes NaNs other than [staleness markers](https://docs.victoriametrics.com/vmagent/#prometheus-staleness-markers)

> How does vmselect observe the NaN value of an indicator?

It marks series as stale immediately as it sees [staleness marker.](https://docs.victoriametrics.com/vmagent/#prometheus-staleness-markers)

**Comment by hagen1778** [comment]
Closing as answered.
