### ISSUE TITLE
Hide hostname and ip addresses from errors in Grafana

### ISSUE THREAD

**Issue by tiny-pangolin** [VictoriaMetrics/VictoriaMetrics#7588]
### Is your feature request related to a problem? Please describe

Users are able to see the URLs and IP addresses when there are errors when querying Victoriametrics from Grafana. When providing Victoriametrics as a solution for customers this information should be hidden from the end user.

### Describe the solution you'd like

Provide the ability for errors in Victoriametrics to have the URLs, hostnames, and IP addresses hidden, similar to how passwords are hidden in log messages for command line flags.

![image](https://github.com/user-attachments/assets/4cd47a32-a438-488b-9332-097b5390b11d)

**Comment by hagen1778** [comment]
AFAIK, Grafana could still report IP addresses on its own. For example, if I configure it with a bad datasource URL I'll get the following error message:
> Post "http://demo.robustperception.io:9090/api/v1/query_range": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Here ^ Grafana discloses the datasource URL to the users. Should that be hidden as well?

**Comment by hagen1778** [comment]
@tiny-pangolin closing this ticket in favour of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7625
