### ISSUE TITLE
vmalert: recording rules results aren't visible in database

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#7610]
### Describe the bug

This is a continuation of issue #7060 

After calculating metrics using recording, some metric data is displayed incorrectly and then is missing.

The recodring runs for a while and then an exception occurs, generating abnormal data and then not generating data.

### To Reproduce
```
-datasource.lookback="1m0s"
-datasource.url="secret"
-remoteWrite.concurrency="8"
-remoteWrite.flushInterval="1m0s"
-remoteWrite.maxBatchSize="10000"
-remoteWrite.maxQueueSize="10000000"
-remoteWrite.url="secret"
-rule="/usr/local/vmagent/rules/*.yaml"
```
### Version

1.104

### Logs

[vmui_report_2024-11-20_023635.json](https://github.com/user-attachments/files/17838541/vmui_report_2024-11-20_023635.json)

```node_memory_MemUse_py_bytes``` is the metrics generated by recoding, ```node_memory_MemTotal_bytes-node_memory_MemFree_bytes``` is the promql calculated by recoding.

**Comment by Haleygo** [comment]
Hi,
Could you please post the screenshot of query results on vmui directly or export the data via `/api/v1/export` [api](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) with reduce_mem_usage=1 param set?

Is this recording rule the only one missing in VictoriaMetrics? Have you noticed any ingestion errors from the VictoriaMetrics side?

Could you also provide the definition of recording rule `node_memory_MemUse_py_bytes` and the query results of below expressions:
```
vmalert_recording_rules_last_evaluation_samples{recording=<your-rule-name>}
sum(rate(vmalert_remotewrite_sent_rows_total{job=<vmalert-jobname>}[1m])) by(job)
sum(rate(vmalert_remotewrite_dropped_rows_total{job=<vmalert-jobname>}[1m])) by(job) > 0
```

**Comment by FengZh61** [comment]
> Hi, Could you please post the screenshot of query results on vmui directly or export the data via `/api/v1/export` [api](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) with reduce_mem_usage=1 param set?
> 
> Is this recording rule the only one missing in VictoriaMetrics? Have you noticed any ingestion errors from the VictoriaMetrics side?
> 
> Could you also provide the definition of recording rule `node_memory_MemUse_py_bytes` and the query results of below expressions:
> 
> ```
> vmalert_recording_rules_last_evaluation_samples{recording=<your-rule-name>}
> sum(rate(vmalert_remotewrite_sent_rows_total{job=<vmalert-jobname>}[1m])) by(job)
> sum(rate(vmalert_remotewrite_dropped_rows_total{job=<vmalert-jobname>}[1m])) by(job) > 0
> ```

![捕获2](https://github.com/user-attachments/assets/ed2033be-9832-46de-82e8-e4d55e774c50)
![捕获1](https://github.com/user-attachments/assets/f622fecf-0e76-4993-b205-fcfcab282583)
![捕获3](https://github.com/user-attachments/assets/e8c22a1f-7608-4e58-b606-b535beb0867c)

Here's a screenshot of the results of the 3 queries

```
https://github.com/user-attachments/files/17838541/vmui_report_2024-11-20_023635.json
```

this is node_memory_MemUse_py_bytes  query results file.

**Comment by Haleygo** [comment]
>Could you please post the screenshot of query results(`node_memory_MemUse_py_bytes` and `node_memory_MemTotal_bytes-node_memory_MemFree_bytes`) on vmui directly or export the data via /api/v1/export [api](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) with reduce_mem_usage=1 param set?

>Is this recording rule the only one missing in VictoriaMetrics? Have you noticed any ingestion errors from the VictoriaMetrics side?

What about those?

**Comment by FengZh61** [comment]
> > Could you please post the screenshot of query results(`node_memory_MemUse_py_bytes` and `node_memory_MemTotal_bytes-node_memory_MemFree_bytes`) on vmui directly or export the data via /api/v1/export [api](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format) with reduce_mem_usage=1 param set?
> 
> > Is this recording rule the only one missing in VictoriaMetrics? Have you noticed any ingestion errors from the VictoriaMetrics side?
> 
> What about those?

this file is ```reduce_mem_usage!=1```
[reduce!_1.json](https://github.com/user-attachments/files/17896331/reduce._1.json)
this file is ```reduce_mem_usage=1```
[reduce_1.json](https://github.com/user-attachments/files/17896335/reduce_1.json)

No error logs found on select node.

My storage node has 6 nodes where A1A2A3 is 3 copies storing the same data and B1B2B3 is 3 copies storing the same data.
The parameter to start my select is replicationFactor=3,storageNode=A1,A2,A3,B1,B2,B3, is there a problem with this parameter configuration?

**Comment by FengZh61** [comment]
@Haleygo Are you still following up on this issue?

**Comment by Haleygo** [comment]
@FengZh61 
As I can see, both attached json files are the same, for metric `node_memory_MemUse_py_bytes`. And the exported samples show valid values from the recording rules(means recording rule is working), but there are also many `null` values which indicates the original `node_memory_MemTotal_bytes` have null values, and those null values can effect the visualization on vmui or grafana.
To confirm that, please attach the exported samples for `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes` separately in the same time range with `node_memory_MemUse_py_bytes`. 
Also, please share the screenshot of two query results(node_memory_MemUse_py_bytes and node_memory_MemTotal_bytes-node_memory_MemFree_bytes) on vmui or grafana directly(please include timerange and step params you choose), so I can identify the differences you want to address.

**Comment by FengZh61** [comment]
> @FengZh61 As I can see, both attached json files are the same, for metric `node_memory_MemUse_py_bytes`. And the exported samples show valid values from the recording rules(means recording rule is working), but there are also many `null` values which indicates the original `node_memory_MemTotal_bytes` have null values, and those null values can effect the visualization on vmui or grafana. To confirm that, please attach the exported samples for `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes` separately in the same time range with `node_memory_MemUse_py_bytes`. Also, please share the screenshot of two query results(node_memory_MemUse_py_bytes and node_memory_MemTotal_bytes-node_memory_MemFree_bytes) on vmui or grafana directly(please include timerange and step params you choose), so I can identify the differences you want to address.

![me](https://github.com/user-attachments/assets/ced39b6e-36b3-4d16-99de-c16dcaccc954)

Here's a screenshot of the query, the blue line is ```node_memory_MemTotal_bytes-node_memory_MemFree_bytes``` ,and the red line is ```node_memory_MemUse_py_bytes```.

Data began to appear partially missing on Nov. 15, then completely missing.

There's some sensitive information that I've obscured, so please forgive me.

```node_memory_MemTotal_bytes```
[total.json](https://github.com/user-attachments/files/17916328/total.json)
```node_memory_MemFree_bytes```
[free.json](https://github.com/user-attachments/files/17916330/free.json)
```node_memory_MemUse_py_bytes```
[pyte.json](https://github.com/user-attachments/files/17916331/pyte.json)

These three files are the data queried via /api/v1/export

**Comment by Haleygo** [comment]
Did you specify the `start` and `end` args in above export requests?
All samples are within the range of ~[2024-11-14 17:00:26, 2024-11-15 16:58:00 UTC], and `node_memory_MemUse_py_bytes` is available during this period.
What about afterwards, when you say `node_memory_MemUse_py_bytes` is missing?

**Comment by Haleygo** [comment]
>My storage node has 6 nodes where A1A2A3 is 3 copies storing the same data and B1B2B3 is 3 copies storing the same data.
The parameter to start my select is replicationFactor=3,storageNode=A1,A2,A3,B1,B2,B3

And could you describe your topology here, do you have one or two vmclusters? Are vmalert and vmui using the same vmselect endpoint as the datasource?
Was there any setup change on 2024-11-15?

**Comment by FengZh61** [comment]
> > My storage node has 6 nodes where A1A2A3 is 3 copies storing the same data and B1B2B3 is 3 copies storing the same data.
> > The parameter to start my select is replicationFactor=3,storageNode=A1,A2,A3,B1,B2,B3
> 
> And could you describe your topology here, do you have one or two vmclusters? Are vmalert and vmui using the same vmselect endpoint as the datasource? Was there any setup change on 2024-11-15?


![image](https://github.com/user-attachments/assets/24678220-9279-46e8-a9a2-65867a858bc6)

No changes were made, and when it became clear that the indicator data was not there, it was time to start troubleshooting the problem

**Comment by Haleygo** [comment]
Do both prometheus instances scrape the same targets(both collect `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes`) and write to both vminsert?
What are your storageNode and replicationFactor flags on vmselect?

**Comment by FengZh61** [comment]
> Do both prometheus instances scrape the same targets(both collect `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes`) and write to both vminsert? What are your storageNode and replicationFactor flags on vmselect?

No, no, no, the two promtheus are independent, because of network security rules, there is no way to write data to an insert.

vmselect param is replicationFactor=3,storageNode=A1,A2,A3,B1,B2,B3

**Comment by Haleygo** [comment]
> > Did you specify the `start` and `end` args in above export requests? All samples are within the range of ~[2024-11-14 17:00:26, 2024-11-15 16:58:00 UTC], and `node_memory_MemUse_py_bytes` is available during this period. What about afterwards, when you say `node_memory_MemUse_py_bytes` is missing?
> 
> From the view, there is no data for `node_memory_MemUse_py_bytes` after 2024-11-15 01:30:00 UTC

I know that, I mean there are also no data for `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes` since somewhere 2024-11-15 UTC from the json you exported [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7610#issuecomment-2500002719).

> No, no, no, the two promtheus are independent, because of network security rules, there is no way to write data to an insert.

Then which prometheus is collecting `node_memory_MemTotal_bytes`? Or two prometheus instances are collecting `node_memory_MemTotal_bytes` for different instances?

**Comment by FengZh61** [comment]
> > > Did you specify the `start` and `end` args in above export requests? All samples are within the range of ~[2024-11-14 17:00:26, 2024-11-15 16:58:00 UTC], and `node_memory_MemUse_py_bytes` is available during this period. What about afterwards, when you say `node_memory_MemUse_py_bytes` is missing?
> > 
> > 
> > From the view, there is no data for `node_memory_MemUse_py_bytes` after 2024-11-15 01:30:00 UTC
> 
> I know that, I mean there are also no data for `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes` since somewhere 2024-11-15 UTC from the json you exported [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7610#issuecomment-2500002719).
> 
> > No, no, no, the two promtheus are independent, because of network security rules, there is no way to write data to an insert.
> 
> Then which prometheus is collecting `node_memory_MemTotal_bytes`? Or two prometheus instances are collecting `node_memory_MemTotal_bytes` for different instances?

I looked at the TOTAL and FREE files and the time max is 1731689906788 converted to UTC time is Oct 16, 2024 13:25:06 UTC.

two prometheus instances are collecting `node_memory_MemTotal_bytes` for different instances

**Comment by FengZh61** [comment]
> > > My storage node has 6 nodes where A1A2A3 is 3 copies storing the same data and B1B2B3 is 3 copies storing the same data.
> > > The parameter to start my select is replicationFactor=3,storageNode=A1,A2,A3,B1,B2,B3
> > 
> > 
> > And could you describe your topology here, do you have one or two vmclusters? Are vmalert and vmui using the same vmselect endpoint as the datasource? Was there any setup change on 2024-11-15?
> 
> ![image](https://private-user-images.githubusercontent.com/98309003/389878305-24678220-9279-46e8-a9a2-65867a858bc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzkwNzQsIm5iZiI6MTczMjY3ODc3NCwicGF0aCI6Ii85ODMwOTAwMy8zODk4NzgzMDUtMjQ2NzgyMjAtOTI3OS00NmU4LWE5YTItNjU4NjdhODU4YmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDAzMzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MWQxMjZkMGQ2ZDg4NzM2ZTFiZjM2YzVmZmEwYjkxN2UyOGI5N2YzZTQ5ZjcyZDgyMTBmYjUzMjJlMWYwOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.u8g18UfXOgpIyTpPNrxS-yCSX8NWSAwHhNE0evmiRdM)
> 
> No changes were made, and when it became clear that the indicator data was not there, it was time to start troubleshooting the problem

I made some changes, recording is no longer centralized calculation, respectively, from a single cluster to calculate, so that the data is normal, missing data can be queried, I do not know whether it is because of the number of instances of the problem, I have a total of nearly 3000 nodes, a single cluster is only a few hundred, a difference of several times.

**Comment by FengZh61** [comment]
> > > Did you specify the `start` and `end` args in above export requests? All samples are within the range of ~[2024-11-14 17:00:26, 2024-11-15 16:58:00 UTC], and `node_memory_MemUse_py_bytes` is available during this period. What about afterwards, when you say `node_memory_MemUse_py_bytes` is missing?
> > 
> > 
> > From the view, there is no data for `node_memory_MemUse_py_bytes` after 2024-11-15 01:30:00 UTC
> 
> I know that, I mean there are also no data for `node_memory_MemTotal_bytes` and `node_memory_MemFree_bytes` since somewhere 2024-11-15 UTC from the json you exported [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7610#issuecomment-2500002719).
> 
> > No, no, no, the two promtheus are independent, because of network security rules, there is no way to write data to an insert.
> 
> Then which prometheus is collecting `node_memory_MemTotal_bytes`? Or two prometheus instances are collecting `node_memory_MemTotal_bytes` for different instances?

![memcount](https://github.com/user-attachments/assets/c9b475c9-e9fc-4a2c-b40d-2a7938d69fc0)

I counted the number of instances, and the number of total, free, and total-free is 2810, but the calculated number of py_bytes becomes 2528, and there is nothing equal to 0 for total and free, so theoretically the number of py_bytes should also be 2810.

**Comment by FengZh61** [comment]
> > I looked at the TOTAL and FREE files and the time max is 1731689906788 converted to UTC time is Oct 16, 2024 13:25:06 UTC.
> 
> No, `1731689906788` is `2024-11-15 16:58:26 UTC`, see https://www.timestamp-converter.com/.
> 
> I'd recommend to use [multi-level vmselect](https://docs.victoriametrics.com/cluster-victoriametrics/#multi-level-cluster-setup) instead of one, since your data is only complete when both vmstorage clusters return results. <img alt="image" width="1127" src="https://private-user-images.githubusercontent.com/39937150/390311380-a9c24dd4-f64a-4d6e-81da-55591a653505.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTczMzgsIm5iZiI6MTczMjc1NzAzOCwicGF0aCI6Ii8zOTkzNzE1MC8zOTAzMTEzODAtYTljMjRkZDQtZjY0YS00ZDZlLTgxZGEtNTU1OTFhNjUzNTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDAxMjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMmU0ZDM1ZWY5ZTA1MmVmODM5ZDFjMWM3MzczYWU4ZmUyMTlhM2Q3MjJmOTkzN2MzZTQ5MDAyMWZiNGE3Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PxBZQQ7LfyXHFGqq77WAsq8tsvuesH95crqUEAVBOM4">

After using multi-level vmselect, data is still missing after recording

**Comment by FengZh61** [comment]
@Haleygo Any more thoughts on this issue? If can't locate the problem, I plan to break up the RECORDING RULES and not do the centralized calculations, which should solve the problem with the missing data.

**Comment by Haleygo** [comment]
>After using multi-level vmselect, data is still missing after recording

What are your flag settings on the two-level vmselect now? Which vmselect is vmalert using as a data source? It would be helpful if you could share more information(the flags, the query screenshot...), so I can help checking the setup.

After redeploy, is the recording rule result missing consistently, or does it go missing after some time as you described earlier?
Could you export the data from your current topology (the top-level vmselect)?

**Comment by FengZh61** [comment]
> > After using multi-level vmselect, data is still missing after recording
> 
> What are your flag settings on the two-level vmselect now? Which vmselect is vmalert using as a data source? It would be helpful if you could share more information(the flags, the query screenshot...), so I can help checking the setup.
> 
> After redeploy, is the recording rule result missing consistently, or does it go missing after some time as you described earlier? Could you export the data from your current topology (the top-level vmselect)?

The configuration of my multi-level vmselect is as follows
```
./ vmselect-prod -httpListenAddr :8491 \
-replicationFactor=1 \
-storageNode=g1/host1,g1/host2,g1/host3 \
-storageNode=g2/host4,g2/host5,g2/host6
```

I use this select as the data source for vmalert,After redeploy, is the recording rule result missing consistently


This is the latest data, exported from top-level select, where node_memory_MemUse_py_bytes has a portion of the data, which I calculated from a single cluster, not using top-level select as the data source

`total`
[total.json](https://github.com/user-attachments/files/17946225/total.json)
`free`
[free.json](https://github.com/user-attachments/files/17946228/free.json)
`byte`
[byte.json](https://github.com/user-attachments/files/17946227/byte.json)

**Comment by Haleygo** [comment]
>I use this select as the data source for vmalert,After redeploy, is the recording rule result missing consistently

>This is the latest data, exported from top-level select, where node_memory_MemUse_py_bytes has a portion of the data, which I calculated from a single cluster, not using top-level select as the data source

So, you're saying: with two level vmselect setup, `node_memory_MemUse_py_bytes` is visible when vmalert uses L1 vmselect(the one directly connects to vmstorge nodes) as the datasource, but disappears when vmalert uses L2(top-level) vmselect as the datasource.
Could you confirm this with a simple test?
Here’s the test setup:
1. create two vmalert instances: 
  `vmalertA` use L1 vmselect as the datasource and with `-external.label=test=vmalertA`
  `vmalertB` uses L2 vmselect as the datasource and with `-external.label=test=vmalertB`
   All other configurations, including `-remoteWrite.url`, should be the same.
2. create a rule file with just the rule `node_memory_MemUse_py_bytes=node_memory_MemTotal_bytes-node_memory_MemFree_bytes`;
3. check if `node_memory_MemUse_py_bytes` are present for both vmalert instances (they should have different labels as vmalertX).
4. if the result from `vmalertB` is still missing, check `vmalert_remotewrite_sent_rows_total, vmalert_remotewrite_dropped_rows_total, vmalert_recording_rules_last_evaluation_samples`

**Comment by FengZh61** [comment]
@Haleygo I have localized the problem, the vm components are fine, my Prometheus write to storage latency is too high caused by 01 minutes of collected data in the vm storage 10 minutes to check, and my vmalert parameter lookback is set to 1 minute, thus the problem of missing data, this has a lot to do with my architecture and network links, again! Thanks for your answer.
