### ISSUE TITLE
vmagent: Add ability to work with multi-tenancy

### ISSUE THREAD

**Issue by dxtrzhang** [VictoriaMetrics/VictoriaMetrics#762]
**Is your feature request related to a problem? Please describe.**
Same reason for adding ability to work with multi-tenancy , See #740 

**Describe the solution you'd like**
maybe similar solution with how vmalert implement(#754 ), but vmagent is much more complex than vmalert, so it's better that we discuss first.

**Comment by valyala** [comment]
[Recent versions of vmagent](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest) already support the ability to accept data from multiple [tenants](https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy) and to write it to multiple tenants. See [these docs](https://docs.victoriametrics.com/vmagent/#multitenancy).

Closing this feature request as done.
