### ISSUE TITLE
feat: vmui release artifact

### ISSUE THREAD

**Issue by k0ste** [VictoriaMetrics/VictoriaMetrics#7631]
### Is your feature request related to a problem? Please describe

Currently I'm didn't see `vmui` artifact. Is 'thing' that produces with `npm`

The provided, in Makefile, variant of build (docker only) is hardly to implement for [mock](https://github.com/rpm-software-management/mock) builds, where
`mock` runs in docker (gitlab), and `rpmbuild` runs in `podman` (by `mock`)

### Describe the solution you'd like

The Prometheus project provide `prometheus-web-ui-${pkgver}.tar.gz` artifact for each github release. When we make Prometheus package we download this artifact and put it do `/usr/share/prometheus`

```
install -Dm0755 -d "%{buildroot}%{_datadir}/%{name}/web/ui"
cp -r "web/ui/static" "%{buildroot}%{_datadir}/%{name}/web/ui"
```

### Describe alternatives you've considered

<img width="779" alt="Screenshot 2024-11-22 at 15 02 41" src="https://github.com/user-attachments/assets/76e634e1-4346-4251-9a2c-f2fbfd5f6ff2">

### Additional information

It will be nice to have `vmui` artifact for each VictoriaMetrics release

**Comment by hagen1778** [comment]
Hi @k0ste! vmui is baked-in in VictoriaMetrics single node and vmselect binaries. The same is for VictoriaLogs.
We don't produce vmui separately, as it has no sense. 
Why would you need it separately?

**Comment by k0ste** [comment]
> Hi @k0ste! vmui is baked-in in VictoriaMetrics single node and vmselect binaries. The same is for VictoriaLogs. We don't produce vmui separately, as it has no sense. Why would you need it separately?

I'm just joining VM, at the moment I'm packaging for internal use. It wasn't obvious to me that `vmui` is builtin into `vmselect`. Now I've opened the directory with this project, it's clearly written there (README.md). But in the documentation, at least in the section about the cluster version - no. At this moment, everything has become clear to me - the statics available in the tarball are enough for build, npm is not needed. Thank you!

**Comment by hagen1778** [comment]
Added note about vmui in cluster docs here https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c9837de9cdddb36da84833571219d42ff51f7993.

Closing as answered.
