### ISSUE TITLE
How can I directly push data to VictoriaMetrics instead of promtheus

### ISSUE THREAD

**Issue by jinlongwang** [VictoriaMetrics/VictoriaMetrics#764]
hi
I want to directly push the data of Prometheus structure to VictoriaMetrics instead of remote_write_api, what should I do?

**Comment by hagen1778** [comment]
Hi @jinlongwang! Have you checked https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-import-data-in-prometheus-exposition-format ?

**Comment by jinlongwang** [comment]
hi
I am using the cluster version of vm 
![image](https://user-images.githubusercontent.com/2275120/92916469-1f74af80-f460-11ea-97bb-19f824860edb.png)


and I want to design my architecture like this, I want to ask you if this is OK? thx
![image](https://user-images.githubusercontent.com/2275120/92916314-f81de280-f45f-11ea-8dc6-a54b2280b7d8.png)

**Comment by valyala** [comment]
@jinlongwang , Prometheus exposition format data should be pushed to `/insert/<accountID>/prometheus/api/v1/import/prometheus` in VictoriaMetrics cluster - see https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#url-format .

The proposed architecture looks OK. Not that the `data adapter` may be unnecessary if `push mode monitor agent` already can push data to VictoriaMetrics via [supported protocols](https://victoriametrics.github.io/#how-to-import-time-series-data):

* Influx line protocol
* Graphite protocol
* OpentTSDB protocol
* CSV
* JSON line
* Prometheus text exposition format

**Comment by jinlongwang** [comment]
@valyala thank you very much ! i got it

**Comment by valyala** [comment]
Closing the question as answered. @jinlongwang , feel free re-opening it if you have additional questions related to this one.

**Comment by richlv** [comment]
> Hi [@jinlongwang](https://github.com/jinlongwang)! Have you checked https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-import-data-in-prometheus-exposition-format ?

This content now at https://docs.victoriametrics.com/victoriametrics/single-server-victoriametrics/#how-to-import-data-in-prometheus-exposition-format .
