### ISSUE TITLE
increase `maxLabelsPerTimeseries` default limit from 30 to 40

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#7661]
### Is your feature request related to a problem? Please describe

`maxLabelsPerTimeseries` was set to 30 by default a few years ago, when having 30 labels per time series was **a lot**. But looks like nowadays default k8s monitoring can easily exceed this limit. And user will have to change the default limit, which defeats the purpose of meaningful defaults.

### Describe the solution you'd like

I think it is time to bump the limit to 40 or higher, depending on what are the current requirements for k8s metrics exposed by popular exporters.

### Describe alternatives you've considered

Set the limit manually.

### Additional information

Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6928

**Comment by f41gh7** [comment]
The feature was included into [v1.108.0](https://docs.victoriametrics.com/changelog/#v11080) release
