### ISSUE TITLE
add more details for "clipboard not supported" error in vmui

### ISSUE THREAD

**Issue by zystem** [VictoriaMetrics/VictoriaMetrics#7677]
### Describe the bug

Then I clicked on the field in VictoriaLogs vmui stream I got "clipboard not supported".

### To Reproduce

Click on stream in vmui

### Expected behavior

Enhance the UI to provide more detailed information about the “clipboard not supported” error. Include common reasons why the Clipboard API might be unavailable and add a link to relevant documentation.

### Version

victoria-logs-20241112-180853-tags-v1.0.0-victorialogs-0-g99607e2f3b

### Screenshots

![image](https://github.com/user-attachments/assets/b35387d5-03c6-4ff1-bf7a-dadfbdcc4f39)

### Additional information

Linux Mint 22
Firefox 132.0.1 (64-bit)
same on
Chrome 131.0.6778.69

**Comment by Loori-R** [comment]
The error `"clipboard not supported"` indicates that the Clipboard API is unavailable on this page in your browser. The most common reasons for this are:

1. The page is running over an insecure HTTP protocol instead of HTTPS.
2. The browser or its version does not support the Clipboard API.
3. Access to the clipboard is restricted by the browser's security policies.

For more information: [Clipboard API documentation](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API?utm_source=chatgpt.com#security_considerations).

**Comment by zystem** [comment]
You're right. I use HTTP. In this case, a check should be added. If a browser does not support Clipboard API, disable it. I can not select and copy a string because this feature drops my selection.

**Comment by Loori-R** [comment]
> You're right. I use HTTP. In this case, a check should be added. If a browser does not support Clipboard API, disable it. I can not select and copy a string because this feature drops my selection.

Could you please provide more details on how to reproduce the issue?

I tested in Chrome, Safari, and Firefox and didn't find any issues with copying when the Clipboard API is unavailable. Below is a video demonstrating the test in Safari: 

https://github.com/user-attachments/assets/be3ceb8a-7b4b-44d4-bb9f-5bb7fc7454bc

**Comment by zystem** [comment]
I'm sorry that my problem description was not accurate. The problem appears when I try to select several fields at once. I can not copy at once `kubernetes_container_name="fluent-bit" kubernetes_namespace_name="monitoring"`

**Comment by Loori-R** [comment]
> I'm sorry that my problem description was not accurate. The problem appears when I try to select several fields at once. I can not copy at once `kubernetes_container_name="fluent-bit" kubernetes_namespace_name="monitoring"`

Did I understand correctly that the issue is that when you select multiple fields, the group collapses, and the selection resets?

**Comment by zystem** [comment]
yes. group collapses and selection resets.

https://github.com/user-attachments/assets/d2a9c1b9-0498-4f37-a93e-76f061e19881
