### ISSUE TITLE
vmalert - reload api is not consistent

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#768]
**Describe the bug**
I am deploying vmalert with helm charts, and I am changing the configmap that vmalert uses to include new or update existing alerts. After changing the configmap I then call reload on vmalert but it works inconsistent, many times nothing will happen and sometimes the reload will work instantly. This is a huge problem because I always get 200 response from the reload call but I do not know if the new/updates rules are updated in vmalert.

**To Reproduce**
Have a simple rule in the configmap like: 

> groups:
> - name: TestGroup1
>   rules:
>   - alert: TestALERT1
>     expr: sum(up == 1) by(job)

Change the alert name to TestALERT2 inside the configmap, and call reload api.
This will sometimes have no effect and the name will still be TestALERT1, and sometimes will work.

(There are cases when changing the name(lets say its now TestALERT3) will have no effect at all, then changing the name again(to TestALERT4) and calling reload will update the name to the previous updated name (will now show TestALERT3))

**Expected behavior**
Reload should always update the alerts, and if there is some problem that will make the reload not to work it should not return status 200.

**Screenshots**
The name is TestALERT1 in configmap and inside vmalert
<img width="545" alt="Screen Shot 2020-09-14 at 12 37 49" src="https://user-images.githubusercontent.com/7746785/93070702-def77a80-f687-11ea-8489-aea227d0a5f1.png">

<img width="1220" alt="Screen Shot 2020-09-14 at 12 40 07" src="https://user-images.githubusercontent.com/7746785/93070778-fafb1c00-f687-11ea-8187-f5b50cfebacd.png">

Updated in configmap to TestALERT2 and called reload
<img width="564" alt="Screen Shot 2020-09-14 at 12 42 01" src="https://user-images.githubusercontent.com/7746785/93070828-0b12fb80-f688-11ea-8e6d-7394c016c8b5.png">

Still the same name in vmalert after reload TestALERT1
<img width="1223" alt="Screen Shot 2020-09-14 at 12 42 14" src="https://user-images.githubusercontent.com/7746785/93070888-19f9ae00-f688-11ea-96af-f5ab66fbb73e.png">

Here is the weird part I was talking about
Changed the name to TestALERT3 and called reload:
<img width="549" alt="Screen Shot 2020-09-14 at 12 48 14" src="https://user-images.githubusercontent.com/7746785/93071346-b4f28800-f688-11ea-8291-5392a5db847f.png">

Now vmalert will show TestALERT2! and not TestALERT3
<img width="1224" alt="Screen Shot 2020-09-14 at 12 48 24" src="https://user-images.githubusercontent.com/7746785/93071391-c63b9480-f688-11ea-8f25-f2e747fe0ade.png">

What is going on?
Maybe this pr is making this weird behavior? https://github.com/VictoriaMetrics/VictoriaMetrics/pull/759

**Version**
v1.41.0

Thanks!

**Comment by f41gh7** [comment]
Its kubernetes related issue, by default, kubernetes (kubelet) updates configmaps at pods with random time. And you cannot trigger it by sending request to vmalert api.

 There are few workarounds:
 - update vmalert's pod annotation (random one) - it should trigger configmap resync.
 - wait until configmaps will be updated by kubelet and config-reloader will trigger config-reload.

**Comment by Alon-Katz** [comment]
Thanks for the info! Updating the pod annotation worked like a charm!
Closing the issue :)
