### ISSUE TITLE
vmagent doesn't respect /multitenant/ endpoint for ingestion

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#7694]
### Describe the bug

Ingesting data into vmagent via multitenant endpoint fails with the following error:
```
curl  -X POST 'http://localhost:8429/insert/multitenant/prometheus/api/v1/import/write' -d 'http_requests_total{path="/foo",vm_account_id="42"} 12'
remoteAddr: "192.168.65.1:54463"; requestURI: /insert/multitenant/prometheus/api/v1/import/write?http_requests_total%7Bpath=%22%2Ffoo%22%2Cvm_account_id%3D%2242%22%7D+12; cannot obtain auth token: cannot parse accountID from "multitenant": strconv.ParseUint: parsing "multitenant": invalid syntax
```
But it should support it in the same way as vminsert - see https://docs.victoriametrics.com/vmagent/#multitenancy

### To Reproduce

Run vmagent with `--enableMultitenantHandlers` enabled. Execute the following cmd:
```
curl  -X POST 'http://vmagent:8429/insert/multitenant/prometheus/api/v1/import/write' -d 'http_requests_total{path="/foo",vm_account_id="42"} 12'
```

This is likely affects current LTS releases as well.

### Version

v1.106.1

### Additional information

Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4910

**Comment by f41gh7** [comment]
The bugfix was included into [v1.107.0](https://docs.victoriametrics.com/changelog/#v11070) and [v1.102.8](https://docs.victoriametrics.com/changelog/#v11028)
