### ISSUE TITLE
Storage node writes datapending

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#7709]
### Describe the question in detail

![捕获1](https://github.com/user-attachments/assets/ac159ac6-15af-44fa-bc4d-bc10fd05c5db)
I found that there is a delay in data writing, and found that these two indicators are very high, is it possible to reflect that there is a problem with writing, and how can I adjust it?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hello. Have you checked our slow data ingestion troubleshooting guide here: https://docs.victoriametrics.com/troubleshooting/#slow-data-ingestion ?

And how about the **Slow inserts** of your vmstorage node? It could be found on our [Grafana dashboard](https://grafana.com/orgs/victoriametrics/dashboards) or via the following MetricsQL:
```
max(
    rate(vm_slow_row_inserts_total{job=~"$job_storage"}[$__rate_interval]) 
    / rate(vm_rows_added_to_storage_total{job=~"$job_storage"}[$__rate_interval])
)
```

**Comment by FengZh61** [comment]
> Hello. Have you checked our slow data ingestion troubleshooting guide here: https://docs.victoriametrics.com/troubleshooting/#slow-data-ingestion ?
> 
> And how about the **Slow inserts** of your vmstorage node? It could be found on our [Grafana dashboard](https://grafana.com/orgs/victoriametrics/dashboards) or via the following MetricsQL:
> 
> ```
> max(
>     rate(vm_slow_row_inserts_total{job=~"$job_storage"}[$__rate_interval]) 
>     / rate(vm_rows_added_to_storage_total{job=~"$job_storage"}[$__rate_interval])
> )
> ```

I read the following in the article, yes, the value of slow insert was higher than 20% and it lasted for a long time, the resource limit of storage caused it, it has been scaled up, thanks a lot for the answer.

`
The [official Grafana dashboards for VictoriaMetrics](https://docs.victoriametrics.com/#monitoring) contain Slow inserts graph, which shows the cache miss percentage for storage/tsid cache during data ingestion. If slow inserts graph shows values greater than 5% for more than 10 minutes, then it is likely the current number of [active time series](https://docs.victoriametrics.com/faq/#what-is-an-active-time-series) cannot fit the storage/tsid cache.
`

**Comment by jiekun** [comment]
Great. I recommend to go through the [capacity planning section](https://docs.victoriametrics.com/cluster-victoriametrics/#capacity-planning) in our doc. And please don't hesitate to reopen the issue if you come across additional problem.
