### ISSUE TITLE
Three vmstorage nodes occupy different disk space

### ISSUE THREAD

**Issue by saclive** [VictoriaMetrics/VictoriaMetrics#774]
In July and Aug, There are 5 vmstorage  nodes ,they take up the same disk space about 60G. There are 2 vminsert nodes connect with each vmstorage.
In Aug 27 ,I offlined  these 5 nodes and onlined other 3 nodes. Old nodes are 192.50,192.51,192.52,192.24,192.25. New nodes are 192.27,192.36,192.37. Vminsert nodes connect to these 3 new nodes. 
But some days later, I find the three nodes take up diffrent disk space.

****************************

There are three changes in that period:
    Create a snap in192.50 and restored in 192.27  in Aug 27. The same optation from 192.51 to 192.36. The 192.37 is a new node without restore operation.
    Expand memory from 12G to 24G in every nodes in Sep 3.
    Promxy Rule was updated on September 7. Promxy only read datapoint from vm and won't write datapoint to vm.

*****************************
The disk usage before i create snap in Aug 25 as following pic:
![image](https://user-images.githubusercontent.com/69297441/93438713-428bdd00-f900-11ea-844e-49b4f4e35e45.png)
![image](https://user-images.githubusercontent.com/69297441/93439522-40764e00-f901-11ea-9b25-c76f62b7bec4.png)

Now the disk usage is as following pic:
192.37 big folder:
![image](https://user-images.githubusercontent.com/69297441/93439738-7ddadb80-f901-11ea-9bc9-5f2cb4528f37.png)
![image](https://user-images.githubusercontent.com/69297441/93439977-c7c3c180-f901-11ea-8042-bd1b9b515d09.png)

192.36 big folder:
![image](https://user-images.githubusercontent.com/69297441/93439872-a7940280-f901-11ea-9412-ab30ac044810.png)
![image](https://user-images.githubusercontent.com/69297441/93439946-bd092c80-f901-11ea-87c8-b8cea16aa10b.png)
![image](https://user-images.githubusercontent.com/69297441/93441668-651ef580-f902-11ea-877e-7c0975a9cefb.png)

As the red box in the pic, The number of rows is not much different in 192.36 and 192.37 ,but why they take up diffrent disk space,especially timestamp.bin in big folder

new datapoint: compared with 192.37, the datapoint to 192.36 seems doubled  :
![image](https://user-images.githubusercontent.com/69297441/93446926-5fc2aa80-f904-11ea-97c0-9b3f1aaa2bb4.png)
 
I wonder:
1.From folder name  we can get the rownum ,why 192.36 and 192.37 have same datapoint but take up diffrent disk space.
2.Why data ingestion is not same in 3 storage nodes

**Comment by saclive** [comment]
In addition ,

**Comment by valyala** [comment]
Which version of VictoriaMetrics cluster do you run? If you run [v1.41.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) or newer version, then the difference in `timestamps.bin` size may be related to an optimization added in this version, which allows reducing `timestamps.bin` sizes in certain cases. The size of `timestamps.bin` file is usually reduced after [background merge process](https://medium.com/@valyala/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282) (aka compaction) merges multiple such files into bigger one. According to file creation dates, the smaller one file has been created on September 14, while the bigger one has been created on September 11. Probably, the cluster was running on version prior to `v1.41.0` on September 11. If this is the case, then just wait until compaction is performed on the file from September 11 - this should reduce the resulting size of stored data.

**Comment by saclive** [comment]
Thanks valyala .
We will upgrade to v1.41.0 today.
But we are confused about the active time series of the storage nodes.

We do some test :
1.Before stop storagenode in 192.27 and 192.36 . The number of active time series is twice as much 192.27 as 192.37  
![image](https://user-images.githubusercontent.com/69297441/93726499-f59e5400-fbe8-11ea-8002-bd24af74048d.png)
2.Stop 192.27 and 192.36 and start them 20 minutes later . the number of active time series changed as the following pic:
![image](https://user-images.githubusercontent.com/69297441/93726733-3480d980-fbea-11ea-88a6-6b9ea563d821.png)
![image](https://user-images.githubusercontent.com/69297441/93726743-482c4000-fbea-11ea-8bc8-3ac2257c7ae2.png)
3.After 80 minutes , We found that the number of active time series  returned to before restarting.
![image](https://user-images.githubusercontent.com/69297441/93726763-5aa67980-fbea-11ea-8a27-7985861943ba.png)

we are confused about the change of active time series. We doubt it is the root cause of the diffrent disk space using.
1. since the datapoint number did'nt change, why the time series sum of the four nodes increased?
2.Why the num of active time series are not the same 

We tried to find it out  from your source code ,but there meet some questions :
1.vminsert just use hash to decide which vmstorage node to be sent. then why the active time series is not average in vmstorage node?
2. we cant find in the source code where the metrics update such as the bellowing gauge.  
![image](https://user-images.githubusercontent.com/69297441/93727262-f802ad00-fbec-11ea-9fb8-9215eb58f834.png)
we find a function named updatemetrics() but it is never be called
![image](https://user-images.githubusercontent.com/69297441/93727254-ecaf8180-fbec-11ea-8485-be663d9f9362.png)

Thank you very much for your help and look forward to your reply

**Comment by saclive** [comment]
In addition , there are data of Aug and Sep in 27 and 36 nodes. but only Sep in 37 and 50 nodes.
Is it the reason that active time series not the same?

**Comment by valyala** [comment]
@saclive , could you verify that all the `vminsert` nodes in the cluster have the same set of `-storageNode` command-line flags and these flags have identical order? If this isn't the case, then the data distribution among `vmstorage` nodes may become uneven.

> we find a function named updatemetrics() but it is never be called

This function is called inside `registerStorageMetrics()` function in `app/vmstorage/main.go` file in `cluster` branch - see https://github.com/VictoriaMetrics/VictoriaMetrics/blob/8cd89cb8477dc7fcf003292bcba107bce4208ba7/app/vmstorage/main.go#L222

**Comment by saclive** [comment]
yes, i am sure that three vminsert node having the same storage node . just the order of nodes in param is not the same
192.25:
![image](https://user-images.githubusercontent.com/69297441/93834157-6dce4d80-fcad-11ea-906e-904a26c25814.png)
192.48:
![image](https://user-images.githubusercontent.com/69297441/93834196-935b5700-fcad-11ea-9a00-c3d4dc3adac4.png)
192.49:
![image](https://user-images.githubusercontent.com/69297441/93834222-ae2dcb80-fcad-11ea-8a2b-f44b06d1fb57.png)

and the netstat status  in storage nodes shows us the three vminsert nodes connect with every storage nodes:
192.37:
![image](https://user-images.githubusercontent.com/69297441/93834411-63f91a00-fcae-11ea-868f-a2ba74af3ebc.png)
192.27:
![image](https://user-images.githubusercontent.com/69297441/93834428-7bd09e00-fcae-11ea-8f40-dd3ea107f782.png)
192.36:
![image](https://user-images.githubusercontent.com/69297441/93834451-8db24100-fcae-11ea-9d41-75aad184af23.png)
***********
There is only once call of this registerStorageMetrics() function  in main function. How can it change the value in runtime?
![image](https://user-images.githubusercontent.com/69297441/93834605-07e2c580-fcaf-11ea-9eb5-fca83e8567b2.png)

**Comment by saclive** [comment]
@valyala Hi valyala,i think i find the root cause.

**Comment by saclive** [comment]
@valyala Hi valyala,i think maybe i find the root cause.
In Aug 31, i change 3 storagenodes from HD to ssd, at that time, the start parametre of vminserts were changed.
   25 insertnode start with "-storageNode=1.1.1.36:8400 -storageNode=1.1.1.27:8400 -storageNode=1.1.1.37:8400 -storageNode=1.1.1.50:8400	"
   48 and 49 insertnode start with "-storageNode=1.1.1.27:8400 -storageNode=1.1.1.36:8400 -storageNode=1.1.1.37:8400 -storageNode=1.1.1.50:8400	"

The choose of storagenodes idx  in vminsert "func (ctx *InsertCtx) GetStorageNodeIdx(at *auth.Token, labels []prompb.Label) int {" 
	h := xxhash.Sum64(buf)
	ctx.labelsBuf = buf
	idx := int(jump.Hash(h, int32(len(storageNodes))))
	return idx

Then ,one timeseries were sent to 27 storagenode by 25insert node, but be sent to 36 storagenode by 48 insert node.
That is why timeseries in 27 and 36 node are twice as many as 37and 50 node .


I think the count of timestamps have much to do with the count of timeseries .
And the disk space has much to do with the count of timestamps in storage versin 1.40.0.



Now i need your help because my disk space will be full immediatly.
The retentionperiod is 1.Can i delete  Aug data to free diskspace? How can i do?

**Comment by valyala** [comment]
> Can i delete Aug data to free diskspace? How can i do?

You need to stop the corresponding `vmstorage` node and then delete the following folders under `-storageDataPath`:
* `/data/big/2020_08`
* `/data/small/2020_08`

Then just start `vmstorage` node.

Note that VictoriaMetrics gained support for retention periods smaller than one month starting from [v1.45.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). For example, `-retentionPeriod=7d` would set retention to 7 days.

**Comment by hagen1778** [comment]
Closing the issue as inactive. Feel free to reopen if the problem still exists.
