### ISSUE TITLE
Copying text from accordion header resets text selection

### ISSUE THREAD

**Issue by Loori-R** [VictoriaMetrics/VictoriaMetrics#7742]
### Describe the bug

When attempting to select text from the header of an accordion, the accordion unexpectedly toggles. This behavior interrupts the selection process, resetting the user’s text selection.

### To Reproduce: 

https://github.com/user-attachments/assets/d2a9c1b9-0498-4f37-a93e-76f061e19881

### Expected behavior:
The accordion should remain in its current state while the user is selecting text.

_Originally posted by @zystem in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7677#issuecomment-2517674704_

**Comment by f41gh7** [comment]
The bugfix was included into [v1.108.0](https://docs.victoriametrics.com/changelog/#v11080), [v1.102.9](https://docs.victoriametrics.com/changelog/#v11029) and [v1.97.14](https://docs.victoriametrics.com/changelog/#v19714).
