### ISSUE TITLE
Missing label normalization

### ISSUE THREAD

**Issue by flokli** [VictoriaMetrics/VictoriaMetrics#7744]
### Describe the bug

I use Grafana Alloy to collect metrics from an application sending them in OTLP format (using https://opentelemetry.io/docs/specs/semconv/http/http-metrics/)

Exploring labels in Grafana, with both Mimir and VictoriaMetrics configured, I see that VictoriaMetrics keeps them as-is, while mimir does do some normailzation, replacing dots with underscores:

Mimir:
![image](https://github.com/user-attachments/assets/486e1cca-dca2-435e-8c0b-f38dda3f8bad)

VictoriaMetrics:
![image](https://github.com/user-attachments/assets/63c78446-be6b-4009-800c-f725f957d474)

This subsequently causes issues with dashboards using the "Label Values" feature to show all values for a label - it breaks with a

```
victoria-metrics[648185]: 2024-12-04T18:08:30.367Zwarn	VictoriaMetrics/app/vmselect/main.go:231	error in "/api/v1/series?match%5B%5D=label_values(http.request.method)&start=1733333911&end=1733335711": cannot parse matches[]=label_values(http.request.method): unsupported function "label_values"
```

I think it'd be best if VictoriaMetrics would do the same kind of normalization, maybe configurable.

### To Reproduce

The alloy config looks like this:

```yaml
otelcol.receiver.otlp "main" {
  grpc {
    endpoint = "[::1]:4317"
  }

  http {
    endpoint = "[::1]:4318"
  }

  output {
    metrics = [
      otelcol.exporter.otlphttp.victoriametrics.input,
      otelcol.exporter.otlphttp.mimir.input,
    ]
    traces = [otelcol.exporter.otlp.tempo.input]
  }
}

// We push to Tempo over otlp-grpc.
otelcol.exporter.otlp "tempo" {
  client {
    endpoint = "127.0.0.1:4319"
    tls {
      insecure = true
    }
  }
}

// We push to VictoriaMetrics over otlp-http.
otelcol.exporter.otlphttp "victoriametrics" {
  client {
    endpoint = "http://localhost:8428/opentelemetry"
  }
}
// We push to Mimir over otlp-http.
otelcol.exporter.otlphttp "mimir" {
  client {
    endpoint = "http://localhost:9009/otlp"
  }
}
```

Run a service pushing metrics via OTLP in this format, for example https://github.com/francoposa/tower-otel-http-metrics/tree/main/examples/axum-http-service (and hit the endpoints)

### Version

1.105.0

**Comment by Haleygo** [comment]
Hello,
could you share the raw request from grafana?
>victoria-metrics[648185]: 2024-12-04T18:08:30.367Zwarn	VictoriaMetrics/app/vmselect/main.go:231	error in "/api/v1/series?match%5B%5D=label_values(http.request.method)&start=1733333911&end=1733335711": cannot parse matches[]=label_values(http.request.method): unsupported function "label_values"

From the error message, it's not about the metric `http.request.method`, but VictoriaMetrics doesn't support function `label_values()`.

**Comment by flokli** [comment]
> Hello, could you share the raw request from grafana?

Where do I get this in more detail, other than the log below? 

This was produced in the dashboard settings, variables tab, using label values and selecting one of these labels. The request failed to list the label values, and I saw the log below from VictoriaMetrics.

> > victoria-metrics[648185]: 2024-12-04T18:08:30.367Zwarn	VictoriaMetrics/app/vmselect/main.go:231	error in "/api/v1/series?match%5B%5D=label_values(http.request.method)&start=1733333911&end=1733335711": cannot parse matches[]=label_values(http.request.method): unsupported function "label_values"
> 
> From the error message, it's not about the metric `http.request.method`, but VictoriaMetrics doesn't support function `label_values()`.

I don't know what exact API calls grafana is doing, but it seems to work with other labels (without dots).

**Comment by Haleygo** [comment]
>Where do I get this in more detail, other than the log below?

I couldn't find the place where grafana sends `/api/v1/series?match=label_values()` request.
You can use the browser development tools, for example, in chrome:
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/5d67a977-cfb5-493b-984a-717fad0af8d4">

**Comment by flokli** [comment]
I'm talking about this view:

![image](https://github.com/user-attachments/assets/a2310a48-ae5f-4fbc-ac79-78a9f67d229f)

(that's screenshot is with mimir and the normalized values)

You should be able to trigger this by importing https://grafana.com/grafana/dashboards/18860-http-metrics-opentelemetry/ and trying to update the dashboard variable value selection to use the `http.route` labels present in VictoriaMetrics.

I can try to reproduce your screenshot later today, though I'd assume what I see in the Web Console might not be the exact same request anyways, as Grafana uses that proxy mechanism, so it's not the client querying directly.

**Comment by hagen1778** [comment]
@flokli @Haleygo VictoriaMetrics doesn't perform normalization by defaul - it accepts data as is. This is mostly due to the fact that VM could be used as a storage for many various ingestion protocols, that don't have to follow Prometheus naming convention.

You can enable conversion via `-opentelemetry.usePrometheusNaming`:
> -opentelemetry.usePrometheusNaming
   Whether to convert metric names and labels into Prometheus-compatible format for the metrics ingested via OpenTelemetry protocol; see https://docs.victoriametrics.com/#sending-data-via-opentelemetry

This is also outlined in docs:
> VictoriaMetrics stores the ingested OpenTelemetry [raw samples](https://docs.victoriametrics.com/keyconcepts/#raw-samples) as is without any transformations. Pass -opentelemetry.usePrometheusNaming command-line flag to VictoriaMetrics for automatic conversion of metric names and labels into Prometheus-compatible format. OpenTelemetry [exponential histogram](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exponentialhistogram) is automatically converted to [VictoriaMetrics histogram format](https://valyala.medium.com/improving-histogram-usability-for-prometheus-and-grafana-bc7e5df0e350).

You can aslo switch Alloy to send data in [PrometheusRemoteWrite](https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.remote_write/) format. This should do the conversion on the collector side and will send identical data to both destinations.

**Comment by flokli** [comment]
Yeah, I think that's what's been going on. Thanks, and sorry for the noise!
