### ISSUE TITLE
Simplify access to the version number(s)

### ISSUE THREAD

**Issue by bartbutenaers** [VictoriaMetrics/VictoriaMetrics#7746]
### Is your feature request related to a problem? Please describe

I am developing an integration of VictoriaMetrics for Node-RED (open-source IOT dataflow platform), and I am struggling to find the version number(s) of the currently installed db.  In my case a single node db.

Other people (e.g. [here](https://github.com/VictoriaMetrics/operator/issues/675)) seem to use `vm_app_version`.  I have tried to _**query**_ that in all kinds of formats in vmui, but I don't get a match unfortunately:

> WARNING: No match! This query hasn't selected any time series from database. Either the requested metrics are missing in the database, or there is a typo in series selector.

When I try to _**export**_ that same selector, I always get an empty array. 

### Describe the solution you'd like

1. It would be nice if the version number(s) would be somehow visible in the vmui.  Because that is the place where most (frontend) users will expect to find it.
2. It would perhaps also be nice to make these version numbers available via e.g. `api/v1/version_info`, so we can easily fetch them at the backend size.
3. Or if somebody could tell me how I can easily get the version numbers via a query, then point 2 might be rejected (because I can execute that query also via `api/v1`).  

### Describe alternatives you've considered

Queries and exports, but failed to get a result.

**Comment by hagen1778** [comment]
Hey @bartbutenaers!

The version of each VM component is exposed via its metrics on /metrics page. So you can get it like the following:
```
curl https://play.victoriametrics.com/metrics | grep 'vm_app_version'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 86754    0 86754    0     0   142k      0 --:--:-- --:--:-- --:--:--  142k
vm_app_version{version="vmselect-20241129-172603-tags-v1.107.0-enterprise-cluster-0-gda8a84854b", short_version="v1.107.0-enterprise-cluster"} 1
```

You can use query API for that,  but only if the datasource has those metrics (they're scraped and stored as suggested in [monitoring](https://docs.victoriametrics.com/#monitoring)). See example [here](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.range_input=30m&g0.end_input=2024-12-05T08%3A02%3A31&g0.relative_time=last_30_minutes&g0.tab=1&g0.expr=vm_app_version).

> It would be nice if the version number(s) would be somehow visible in the vmui. Because that is the place where most (frontend) users will expect to find it.

That's possible, for sure. But VictoriaMetrics cluster consists of 3 components (insert, select and storage), and each of them could have a different version. So printing only vmui version will be misleading. Also, vmselect doesn't "know" about vminserts and can't get their versions. 

> It would perhaps also be nice to make these version numbers available via e.g. api/v1/version_info, so we can easily fetch them at the backend size.

Visiting `http://vm-component/metrics` page would display metrics it exposes, and one of those metrics is `vm_app_version`.

**Comment by bartbutenaers** [comment]
@hagen1778 ,
Thanks for your fast response!
That is just what I needed, so I will close this issue.
Hope you have a nice day!
