### ISSUE TITLE
Option to disable timestamp in logs

### ISSUE THREAD

**Issue by varuzam** [VictoriaMetrics/VictoriaMetrics#778]
**Is your feature request related to a problem? Please describe.**
When victoria-metrics runs on kubernetes it is redundant to put timestamp into log records because kubernetes does this as well.
The same happens in case of VM runs as a systemd unit. Journald already adds timestamp in logs.

**Describe the solution you'd like**
it would be nice to have an argument for command  line which disables timestamp in log records

**Comment by valyala** [comment]
The `-loggerDisableTimestamps` command-line flag has been added in the following commits:
* Single-node version: 29108cc53e42d29a41bc3ff6e70b36a8c5788db2
* Cluster version: d32c3f747c383dcc12ce303ad1c5b18a72a8917b

@varuzam , could you build VictoriaMetrics from these commits and verify whether it works as expected? See [build instructions for single-node VictoriaMetrics](https://victoriametrics.github.io/#how-to-build-from-sources) and [build instructions for cluster version](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#building-from-sources).

**Comment by valyala** [comment]
FYI, the `-loggerDisableTimestamps` command-line flag has been added in [v1.41.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.
