### ISSUE TITLE
VictoriaMetrics Cluster not use func "alias" in Grafana

### ISSUE THREAD

**Issue by vipsql** [VictoriaMetrics/VictoriaMetrics#78]
Hi, VictoriaMetrics is a very good project,thank to developer, i use the soft missing some problem want to help,
env：
VictoriaMetrics  V1.20.5(Cluster 2node->vminsert 2node->vmselect 2node->vmstorage )
Prometheus 2.8.0
Grafana 6.1.6

arch:
prometheus_remote->vminsert->vmstorage->vmselect->grafana
then,i use vmselect as source,some query can not execute,the error is
“cannot execute "count(node_exporter_build_info{instance=~"xxxx.com:9100"}) by(alias,env,instance,version)": cannot expand WITH expressions: cannot use func "alias" instead of "alias" in [alias env instance version]”

but i use prometheus as source,the is woking!

**Comment by valyala** [comment]
@vipsql , thanks for the bug report. The bug will be fixed in the next release.

**Comment by valyala** [comment]
@vipsql , could you confirm that the bug has been fixed in [v1.20.6](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by vipsql** [comment]
@valyala  thanks,i will confirm it as soon as possible
