### ISSUE TITLE
Packaging for OpenBSD

### ISSUE THREAD

**Issue by dohnuts** [VictoriaMetrics/VictoriaMetrics#785]
preparing env
```
# ftp https://github.com/VictoriaMetrics/VictoriaMetrics/archive/v1.41.0.tar.gz
# tar xzvf ./v1.41.0.tar.gz
# go version
go version go1.13.9 openbsd/amd64
# pkg_add gmake
```
testing basic build : 
```
# gmake victoria-metrics-pure
CGO_ENABLED=0 GO111MODULE=on go build  -mod=vendor -ldflags "-X 'github.com/VictoriaMetrics/VictoriaMetrics/lib/buildinfo.Version=victoria-metrics-20200922-141958--dirty-da39a3ee'"
-o bin/victoria-metrics-pure github.com/VictoriaMetrics/VictoriaMetrics/app/victoria-metrics
# github.com/VictoriaMetrics/VictoriaMetrics/lib/filestream
lib/filestream/filestream.go:96:16: r.st.close undefined (type streamTracker has no field or method close)
lib/filestream/filestream.go:126:16: r.st.adviseDontNeed undefined (type streamTracker has no field or method adviseDontNeed)
lib/filestream/filestream.go:223:16: w.st.close undefined (type streamTracker has no field or method close)
lib/filestream/filestream.go:250:16: w.st.adviseDontNeed undefined (type streamTracker has no field or method adviseDontNeed)
gmake[1]: *** [Makefile:134: app-local-pure] Error 2
gmake[1]: Leaving directory '/home/VictoriaMetrics-1.41.0'
gmake: *** [app/victoria-metrics/Makefile:77: victoria-metrics-pure] Error 2
```

I was hopping the GO language would help the code at being easily rebuild elsewhere.

**Comment by f41gh7** [comment]
Yep, openbsd is not supported, atm. There are OS specific syscalls, which might be different. So we are using different implementation for each OS. And, we don't handle case for GOOS=openbsd. Need to investigate it.

**Comment by dohnuts** [comment]
hw.physmem is available on OpenBSD

I used `GOOS=freebsd gmake victoria-metrics-pure`

and it builded something

I search for freebsd in the repo and only found the sysctl case.

Nerverthess the binary ( looks like elf ) is complaining about a parenthesis ??!? 

```
# file /usr/local/test/victoria-metrics-pure
/usr/local/test/victoria-metrics-pure: ELF 64-bit LSB executable, x86-64, version 1
```
but running does
/usr/local/test/victoria-metrics-pure[2]: syntax error: `)' unexpected


Probably because of : ./vendor/golang.org/x/sys/unix/zsyscall_freebsd_arm64.go
?

As most of those exist for OpenBSD would it possible for you to add the target so i can test the software ?

I must say unless i m mistaken, isn't that a bit strange to embed third party libs like that ?

https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/vendor/cloud.google.com/go

On master current: 
```
# GOOS=freebsd go run -mod=vendor ./app/victoria-metrics
fork/exec /tmp/go-build427578221/b001/exe/victoria-metrics: exec format error
```

The program looks really nice on paper,  would be nice to have a build system like other go program with dependencies and no docker.

**Comment by f41gh7** [comment]
I've made quick fix with openbsd specific implementations . Can you try to build binary from this branch https://github.com/VictoriaMetrics/VictoriaMetrics/tree/openbsd-build

 Freebsd wouldn't work in this case.

**Comment by dohnuts** [comment]
``` 
# github.com/valyala/gozstd
ld: error: undefined symbol: ZDICT_isError
>>> referenced by cgo-gcc-prolog:53
>>>               $WORK/b076/_x002.o:(_cgo_180ec9577e43_Cfunc_ZDICT_isError)
```

https://github.com/valyala/gozstd yeah this does not have openbsd support

is that libz ? seems standard

# objdump -T /usr/lib/libz.so.5.0 | tail
0000000000013aa0 g    DF .text  0000000000000050 gzputc
000000000000bf70 g    DF .text  00000000000001e0 inflateCopy


https://golang.org/pkg/compress/zlib/ <= is that too big ?

**Comment by f41gh7** [comment]
gozstd shouldn't be used with pure build. Thats strange.

 I've tested it at ```OpenBSD  6.7 GENERIC#179 amd64```

 With go version: 
```go version go1.13.9 openbsd/amd64```

 Build command: 
```bash
# at openbsd GOOS can be omitted.

GOOS=openbsd gmake victoria-metrics-pure

# run
./bin/victoria-metrics-pure
```

**Comment by dohnuts** [comment]
YEs it works

I did `GOOS=openbsd go run -mod=vendor ./app/victoria-metrics` and that used the  gozstd

**Comment by dohnuts** [comment]
# ./bin/victoria-metrics-pure --version
victoria-metrics-20200923-173735-heads-openbsd-build-0-ge3286ce7

**Comment by dohnuts** [comment]
If this is merge/released I will try to package it.

**Comment by valyala** [comment]
> I must say unless i m mistaken, isn't that a bit strange to embed third party libs like that ?https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/vendor/cloud.google.com/go

This is called [vendoring](https://blog.gopheracademy.com/advent-2015/vendor-folder/) in Go. VictoriaMetrics uses third-party libraries (aka Go packages). All the source code for these packages is placed under `vendor` directory. This provides the following benefits:
* This makes possible to build VictoriaMetrics from sources in an environment without access to Internet and without the need to manually install dependencies before building VictoriaMetrics, since `vendor` folder contains all the source code for all third-party dependencies.
* This makes easy grep'ing across all the source code including all thrid-party dependencies.
* This makes easy investigating changes to third-party dependencies via git history.

Go provides simple mechanism for determining why the given third-party dependency is needed. For example:

```
$ go mod why cloud.google.com/go
# cloud.google.com/go
github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/gcsremote
cloud.google.com/go/storage
cloud.google.com/go
```

The output for `go mod why` says that `cloud.google.com/go` is transitively used by  `github.com/VictoriaMetrics/VictoriaMetrics/lib/backup/gcsremote`.

**Comment by dohnuts** [comment]
> > I must say unless i m mistaken, isn't that a bit strange to embed third party libs like that ?https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/vendor/cloud.google.com/go
> 
> This is called [vendoring](https://blog.gopheracademy.com/advent-2015/vendor-folder/) in Go. VictoriaMetrics uses third-party libraries (aka Go packages). All the source code for these packages is placed under `vendor` directory. This provides the following benefits:
> 

Ok I can see the benefits for releasing software, I would expect some external reference to depot in this case, but it makes sense.

For a packaging point of view it creates questions : 

use the vendor/golang.org/x/sys at the release version 
or (probably better) use the OS release version `DISTNAME =      go-sys-20190904` ?
which is the go-sys package in OpenBSD

..and how the build system can choose one or another ?
Rafael Sadowski ended up repacking the release of Inf*uxDB
regarding this apparently. `# selfhosted because we bundle go deps`

Would be nice to avoid that.

**Comment by GhioRodolphe** [comment]
Hi everyone, 
I am using OpenBSD 6.7 and it work well !
I also connected my Prometheus and VictoriaMetrics to retrieve my Prometheus data on VictoriaMetrics

Steps done: 
1. _`pkg_add go git gmake`_
2. `cd /bin`
3. `git clone https://github.com/VictoriaMetrics/VictoriaMetrics.git`
4. `cd VictoriaMetrics/`
5. `git checkout openbsd-build`
6. `GOOS=openbsd gmake victoria-metrics-pure`
7. Add this into /etc/prometheus.yml
 `remote_write:
              - url: "http://127.0.0.1:8428/api/v1/write"`
8.  ./bin/victoria-metrics-pure
9. Test ` curl -XGET -sS -m2 http://<VictoriaMetrics_ip>:<VictoriaMetrics_port>/api/v1/label/job/values` by default VictoriaMetrics port is 8428, this should return all prometheus job.

Thanks a lot !

**Comment by valyala** [comment]
> use the vendor/golang.org/x/sys at the release version or (probably better) use the OS release version DISTNAME = go-sys-20190904 ? which is the go-sys package in OpenBSD

I'm unsure that using OS release version of `golang.org/x/sys` or other third-party Go packages is better than using vendored packages from `vendor` folder. This requires setting up thrid-party dependencies before building VictoriaMetrics. Currently VictoriaMetrics can be built without the need to configure any third-party dependencies except of Go itself. It would be better upstreaming OpenBSD-related changes to from OS release versions to [golang.org/x/sys](https://github.com/golang/sys/), so they can be incorporated into `vendor` directory with `make vendor-update` command.

FYI, support for OpenBSD has been added in the following commits:

* single-node version - cc90a548b1822f536988cf4cfc3f4f52c34afcf5
* cluster version - 658a05ef0f6d93ab00b68194ee3e71e134caa776

The following line must be used for building VictoriaMetrics binary for OpenBSD: `GOOS=openbsd gmake victoria-metrics-pure`, as @GhioRodolphe  mentioned above. `victoria-metrics-pure` can be substituted with `vmagent-pure`, `vmalert-pure`, etc. for building other `vm*` binaries.

These commits will be included in the next release.

**Comment by dohnuts** [comment]
There is no special change to go-sys in OpenBSD ports tree

COMMENT =       Go package for low-level operating system interaction
DISTNAME =      go-sys-20190904
GH_ACCOUNT =    golang
GH_PROJECT =    sys
GH_COMMIT =     43c01164e93111c754a278ab423ba01063c44917
CATEGORIES =    devel

The purpose of the ports compared to a windows like setup system is to avoid installing multiple time the same software,
with a different set of version etc.. probably a never ending story between `working` and `better`
Usually it is better to rely on existing package, or the all devel category would probably be almost empty.

After creating a working makefile/package I will ask the `porters` how they want this done.
I will need two of them to show interest and saying OK.
Thank you for pushing the diff to master.

**Comment by valyala** [comment]
> The purpose of the ports compared to a windows like setup system is to avoid installing multiple time the same software,
with a different set of version etc..

I see the reason behind using dependencies provided by the OS. But this reason doesn't apply to VictoriaMetrics and any other Go application which is built into a static binary and doesn't need any external dependencies (shared libraries) when it runs.

FYI, OpenBSD support has been included in VictoriaMetrics starting from release [v1.42.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
Closing this feature request as done. Feel free sending additional pull requests or filing new issues related to OpenBSD support for VictoriaMetrics.
