### ISSUE TITLE
Grafana Instant query with table don't work correctly

### ISSUE THREAD

**Issue by raags** [VictoriaMetrics/VictoriaMetrics#786]
**Describe the bug**
When using Grafana Instant queries and plot them as a table (for e.g. to plot label values), the table shows multiple series, instead of a single series. This keeps changing on refresh (more clear in screenshots below)

**To Reproduce**
Plot labels of two queries onto a Grafana Table by using `instant` queries. Only happens with there are two queries that are bing plotted.

**Expected behavior**
This is the expected output:

![expected output](https://user-images.githubusercontent.com/697714/93985769-23c79380-fda3-11ea-9a1d-36c495a2b8ae.png)

But on refresh it'll change to:

![actual-output](https://user-images.githubusercontent.com/697714/93985930-52456e80-fda3-11ea-8fc4-af2dd5208c82.png)

**Version**
```
$ ./victoria-metrics-prod --version
victoriametrics02 : victoria-metrics-20200911-214525-tags-v1.41.0-0-gba74d0c14
```

**Used command-line flags**
```
--retentionPeriod=3 --memory.allowedPercent=60
```

**Additional Context**
- Metrics are scraped via VMagent (1min scrape interval)
- Parallel Prometheus cluster doesn't exhibit this issue (same interval as VMagent)
- Seems to be related to the Timestamps that don't match between the two queries, but why does that not happen in Prometheus

**Comment by valyala** [comment]
This looks like a duplicate for https://github.com/VictoriaMetrics/VictoriaMetrics/issues/720 .

**Comment by valyala** [comment]
Closing the issue as duplicate for #720 .
