### ISSUE TITLE
Question about vminsert's parameters.

### ISSUE THREAD

**Issue by FengZh61** [VictoriaMetrics/VictoriaMetrics#7873]
### Describe the question in detail

I have 6 machines with vmstorage deployed, I want 3 of them to be a shard and the other 3 to be a shard, how do I configure the parameters for vminsert?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by tiny-pangolin** [comment]
The correct way to do this is to set up two 1 set of vminserts per vmstorage shard and configure each set of vminserts to forward writes 1 shard of vmstorage. Then deploy vmagent and configure it to [shard data by URL](https://docs.victoriametrics.com/vmagent/index.html#sharding-among-remote-storages) The reason for using this approach instead of making vminsert aware of shards is explained in #6504

**Comment by FengZh61** [comment]
> The correct way to do this is to set up two 1 set of vminserts per vmstorage shard and configure each set of vminserts to forward writes 1 shard of vmstorage. Then deploy vmagent and configure it to [shard data by URL](https://docs.victoriametrics.com/vmagent/index.html#sharding-among-remote-storages) The reason for using this approach instead of making vminsert aware of shards is explained in #6504

Can I add Load Balancer to the two vminserts and write through polling to achieve data fragmentation?

**Comment by tiny-pangolin** [comment]
I'm not sure and I'm not familar with write through polling but I believe you can use a load balancer with mirroring [like Traefik](https://doc.traefik.io/traefik/routing/services/#mirroring-service) to forward requests to separate sets of vminsert

**Comment by FengZh61** [comment]
> I'm not sure and I'm not familiar with write through polling, but I believe you can use a load balancer with mirroring [like Traefik](https://doc.traefik.io/traefik/routing/services/#mirroring-service) to forward requests to separate sets of vminsert. The downside of this approach is you would lose out the buffer capabilities of vmagent. This will likely cause data to be from 1 shard when that shard is unavailable due to maintenance or other outages since the load balancer cannot buffer and back fill it after the shard available like vmagent can

Thanks, I see, thanks for the answer!
