### ISSUE TITLE
please add CHANGELOG.md to repo

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#788]
**Is your feature request related to a problem? Please describe.**
Currently, the project change history seems to only be held in github metadata on the `/releases` page.

The change log should also be represented as a file in the git repo.  Reasons:
  * it's important for a git repo to be self-describing
  * it allows contributors to make PR's against the changelog file for typos, omissions, etc.
  * novice github users don't know how to discover releases page on their own (multiple clicks, Tags --> Releases)

**Describe the solution you'd like**
Include a `CHANGELOG.md` or equivalent file.

**Comment by valyala** [comment]
FYI, [CHANGELOG.md](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/CHANGELOG.md) has been started in e59de98384481d7873c8eca35be8d0ad9d598bb6 .

**Comment by valyala** [comment]
Closing this feature request as done after [v1.42.0 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), which includes the `CHANGELOG.md` file.
