### ISSUE TITLE
release 1.41.1 description did not mention Inf storage

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#789]
**Describe the bug**
https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.41.1 did not mention feature of supporting storage and query of `Inf`/`-Inf` (commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/26115891dba851ff8c98a222ef528b56a116ab20).

I could not make a PR myself, due to #788

**Comment by valyala** [comment]
Let's join this issue with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/752 .
