### ISSUE TITLE
scrape minio return code 400

### ISSUE THREAD

**Issue by dxg0716** [VictoriaMetrics/VictoriaMetrics#7907]
### Is your question request related to a specific component?

vmagent:v1.89.1

### Describe the question in detail

when i use vmagent scrape minio tenant that return code 400
![image](https://github.com/user-attachments/assets/67312db8-27cb-43d5-abf9-70400c0c7a3e)
i found that not always return code 400，sometime return 200，sometime return 400
i do not know why，vmagent log
![image](https://github.com/user-attachments/assets/087b7a12-7957-4bea-9c5a-35034bdb6dbc)

please help me，how can i debug this

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [X] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by dxg0716** [comment]
someone know how to debug this？

**Comment by jiekun** [comment]
Hello. Have you tried to make the request manually in vmagent or other container/instance? For example, `curl` to the `/minio/metrics/v3/cluster` endpoint.

**Comment by dxg0716** [comment]
> Hello. Have you tried to make the request manually in vmagent or other container/instance? For example, `curl` to the `/minio/metrics/v3/cluster` endpoint.

yes i try netshoot container curl，this return ok
![image](https://github.com/user-attachments/assets/874dc531-0f17-407c-b7d3-8ef3a7c34ce2)

**Comment by jiekun** [comment]
I quickly went through the code of vmagent. There isn't much you can do on the vmagent side. Do you have any proxy/gateway in front of Minio with access control/rate limiting? Did Minio log this error with reason?

**Comment by dxg0716** [comment]
> I quickly went through the code of vmagent. There isn't much you can do on the vmagent side. Do you have any proxy/gateway in front of Minio with access control/rate limiting? Did Minio log this error with reason?

![image](https://github.com/user-attachments/assets/519f9c9f-3e49-46a1-afff-96f38310d8c9)
https://172.16.0.204:9000/minio/metrics/v3/cluster  this address is pod ip，do not have proxy/gateway，and minio log can not found anything，so i do konw how to debug

**Comment by dxg0716** [comment]
> I quickly went through the code of vmagent. There isn't much you can do on the vmagent side. Do you have any proxy/gateway in front of Minio with access control/rate limiting? Did Minio log this error with reason?

i see vmagent loggerLevel is info，can i change loggerLevel？for example debug？

**Comment by jiekun** [comment]
I don't think it's a client error if you could have success response from minio. You could try to change the logger level by `-loggerLevel` flag. But it's less likely to have more info from vmagent side since it won't log the request.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/476bf400ac4c19660edaad41caf1d2d7035e0430/lib/promscrape/discoveryutils/client.go#L226

But it should be easy to add some log and build your own image for testing. Please let me know if you need any help on this.

**Comment by dxg0716** [comment]
> I don't think it's a client error if you could have success response from minio. You could try to change the logger level by `-loggerLevel` flag. But it's less likely to have more info from vmagent side since it won't log the request.
> 
> https://github.com/VictoriaMetrics/VictoriaMetrics/blob/476bf400ac4c19660edaad41caf1d2d7035e0430/lib/promscrape/discoveryutils/client.go#L226
> 
> But it should be easy to add some log and build your own image for testing. Please let me know if you need any help on this.

if i change loggerLevel, i need change VMAgent crd？
![image](https://github.com/user-attachments/assets/81f283a2-f748-446d-adac-4a371c37b79e)

but i saw vmagent args loglevel no have debug
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/9f7ba16f-092a-49a2-84f5-06562c85e698" />

Please help me, Thanks

**Comment by jiekun** [comment]
There is no `DEBUG` level log in VictoriaMetrics. Let me build a customized image for you. The following image will log an error if the scrape HTTP status code != 200:
```
victoriametrics/vmagent:heads-debug-error-log-scrape-req-0-g005068ea5
```
It will log the request URL, request headers and response headers.

**Comment by dxg0716** [comment]
> There is no `DEBUG` level log in VictoriaMetrics. Let me build a customized image for you. The following image will log an error if the scrape HTTP status code != 200:
> 
> ```
> victoriametrics/vmagent:heads-debug-error-log-scrape-req-0-g005068ea5
> ```
> 
> It will log the request URL, request headers and response headers.

**Comment by dxg0716** [comment]
> There is no `DEBUG` level log in VictoriaMetrics. Let me build a customized image for you. The following image will log an error if the scrape HTTP status code != 200:
> 
> ```
> victoriametrics/vmagent:heads-debug-error-log-scrape-req-0-g005068ea5
> ```
> 
> It will log the request URL, request headers and response headers.

ok， let me try it

**Comment by dxg0716** [comment]
> There is no `DEBUG` level log in VictoriaMetrics. Let me build a customized image for you. The following image will log an error if the scrape HTTP status code != 200:
> 
> ```
> victoriametrics/vmagent:heads-debug-error-log-scrape-req-0-g005068ea5
> ```
> 
> It will log the request URL, request headers and response headers.

i try it,then i saw vmagent log，invalid header field value for "Authorization"
![image](https://github.com/user-attachments/assets/049d9981-6306-453e-961b-c482348652bc)


but i use curl test，it is ok
![image](https://github.com/user-attachments/assets/3803112e-10f0-498e-ad63-27f5e55325d6)

then i saw vmagent configmap，bearer_token is ok
![image](https://github.com/user-attachments/assets/03318076-af5b-4b6b-82dd-0773f5b53906)

so i do know where is err，please help me，thanks.

**Comment by jiekun** [comment]
This is not the debug log I added in test image. Please check and provide the log with request header.

**Comment by dxg0716** [comment]
> This is not the debug log I added in test image. Please check and provide the log with request header.

i do know how to see request header, can you tell me how to see?
i only see vmagent log
![image](https://github.com/user-attachments/assets/4b5acfed-c949-4775-b987-019cd244e7d3)

**Comment by dxg0716** [comment]
why closed？

**Comment by jiekun** [comment]
Hello! Please see my commit of the debug branch here:
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/005068ea5a816cf0a754c14efd889604ee302ff1

If you received a non-200 response, this should log the request header and response header. Also, you can try to add more debug log, and build your own image by running `make package-vmagent`. Please try and comment if you observed more detail about the error.

**Comment by dxg0716** [comment]
> Hello! Please see my commit of the debug branch here: [005068e](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/005068ea5a816cf0a754c14efd889604ee302ff1)
> 
> If you received a non-200 response, this should log the request header and response header. Also, you can try to add more debug log, and build your own image by running `make package-vmagent`. Please try and comment if you observed more detail about the error.

thanks，i know where is wrong，because my token secret has trailing whitespaces，the same as https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7089

**Comment by dxg0716** [comment]
I suggestion  vmagent image loggerLevel have debug level，if user have problem，them can debug。
![image](https://github.com/user-attachments/assets/b699601a-7899-4cb4-85f9-381d47b33744)
