### ISSUE TITLE
How to configure VM to return data points where the timestamp is 5s apart in range queries?

### ISSUE THREAD

**Issue by mnachmia31** [VictoriaMetrics/VictoriaMetrics#792]
### Description
I'm trying to configure VM to fit our use case where we expect metrics to be ingested every 5 seconds. I've been able to work around the issue of being able to query for the latest data point when our application does not write duplicate data points to VM by tuning the `-search.maxLookback` flag to overcome the staleness configuration. However, I am unable to figure out how to retrieve all data points that have timestamps 5 seconds apart using a range query. I assume it is related to a scrape configuration that I am not aware of how to tune.

### Example
Given the following metric data points:
```
{"metric":{"__name__":"m0_v0","db":"stress","tag0":"value0"},"values":[2000,3000,4000,5000],"timestamps":[1601152381682,1601152386692,1601152441682,1601152541682]}
```

Value      Timestamp
2000       20:33:01.682 UTC
3000       20:33:06.692 UTC
4000       20:34:01.682 UTC
5000       20:35:41.682 UTC

Running the following range query:
```
curl -g 'http://localhost:8428/api/v1/query_range?query={__name__=~"m0_v0"}&start=2020-09-26T20:25:00.000Z&end=2020-09-26T20:46:00.000Z'
```

I get the following results:
```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"m0_v0","db":"stress","tag0":"value0"},"values":[[1601152500,"4000"],[1601152800,"5000"]]}]}}
```

Value      Timestamp
4000       20:35:00.000 UTC
5000       20:40:00.000 UTC

It's only returning a subset of the data points with a 5 minute difference between them. I assume I can configure this but haven't had any luck up to this point.

### Additional Details:
- build version: victoria-metrics-20200911-214603-tags-v1.41.0-0-gba74d0c14
- Tried setting `search.minStalenessInterval` and `search.maxStalenessInterval` to 3s each (together and separately) with the same results
- Command used to run VM: `docker run -it --rm -v /tmp/victoria-metrics-data:/victoria-metrics-data -p 8428:8428 victoriametrics/victoria-metrics -search.maxLookback=2h`

**Comment by dxtrzhang** [comment]
What about adding a url param like`step=5s`?

**Comment by mnachmia31** [comment]
> What about adding a url param like`step=5s`?

@dxtrzhang Yes it appears having `step=5s` works when I also update the global scraping interval through the flag `-promscrape.config`. The config file I pointed it to had the following settings:

```
# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s
```

Posting here in case anyone else runs into supporting a similar use case.
