### ISSUE TITLE
VictoriaLogs: `_msg` mapping ignored VL-Msg-Field

### ISSUE THREAD

**Issue by bxy4543** [VictoriaMetrics/VictoriaMetrics#7932]
### Is your feature request related to a problem? Please describe

The `_msg` queried in victorialog always contains the complete container log:
```
_msg:
{"time":"2024-12-25T16:42:01.473532247+08:00","logtag":"F","message":"xxx"}
```
Includes the three cri parser fields of time, logtag, and message, but I hope that `_msg` only corresponds to the content of the message

### Describe the solution you'd like

I am not sure whether this result is caused by some configuration errors on my part or whether Victoria logs does not support direct correspondence to the message field.

### Describe alternatives you've considered

I tried to set:
```
uri /insert/loki/api/v1/push?_stream_fields=xxx&_msg=message
```
and set:
```
header VL-Msg-Field message
```
It didn't work

### Additional information

fluent bit config:
```
   [OUTPUT]
        Name loki
        Match kube.*
        host xxx
        uri /insert/loki/api/v1/push?_stream_fields=namespace,pod,container
        #header     VL-Msg-Field message
        compress gzip
        port 9428
        label_map_path /fluent-bit/etc/conf/labelmap.json
        labels job="fluent-bit", namespace=$kubernetes['namespace_name'], pod=$kubernetes['pod'], container=$kubernetes['container']
        remove_keys kubernetes,stream
        auto_kubernetes_labels false
        line_format json
```
```
  labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "release": "release"
        },
        "namespace_name": "namespace",
        "pod_name": "pod"
      },
      "stream": "stream"
    }
```
```
        [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
```

victoria logs image: `victoriametrics/victoria-logs:v1.3.2-victorialogs` & Installed by helm, using the default installation configuration.

**Comment by AndrewChubatiuk** [comment]
@bxy4543. victorialogs doesn't parse JSON from Loki message field as validating each message will impact ingestion performance.
if you want to extract message field consider using [`nest`](https://docs.fluentbit.io/manual/pipeline/filters/nest) filter to move nested values from `log` object to a top level with `log_` prefix and then use [`modify`](https://docs.fluentbit.io/manual/pipeline/filters/modify) filter to rename `log_message` to `log`

**Comment by bxy4543** [comment]
@jiekun @AndrewChubatiuk 
Thank for your reply, I understand, I will try the `nest` & `modify` filter to get the message field.

**Comment by bxy4543** [comment]
In my case, just set loki output
`remove_keys time,logtag` 
&
`drop_single_key on`:
```
    [OUTPUT]
        Name loki
        xxx
        remove_keys kubernetes,stream,time,logtag
        drop_single_key on
```
