### ISSUE TITLE
ClickHouse integration

### ISSUE THREAD

**Issue by coding-hui** [VictoriaMetrics/VictoriaMetrics#7939]
### Is your question request related to a specific component?

VictoriaMetrics、vmagent

### Describe the question in detail

Can vmagent read metrics from clickhouse and push them to a remote influxdb?

### Troubleshooting docs

- [X] General - https://docs.victoriametrics.com/troubleshooting/
- [X] vmagent - https://docs.victoriametrics.com/vmagent/#troubleshooting
- [ ] vmalert - https://docs.victoriametrics.com/vmalert/#troubleshooting

**Comment by jiekun** [comment]
Hi. Currently vmagent can only send data to any remote write compatible target. Also it does not support reading data from clickhouse directly.

**Comment by coding-hui** [comment]
> Hi. Currently vmagent can only send data to any remote write compatible target. Also it does not support reading data from clickhouse directly.

Ok.thanks, we currently have some metrics in ck and want to use VictoriaMetrics for unified management. Let me think again. What do I do.

**Comment by jiekun** [comment]
I am not sure if I have misunderstood your question. Are you looking to migrate data from ClickHouse to InfluxDB, not ClickHouse to VictoriaMetrics? If that's the case, perhaps you should explore some of the solutions provided by InfluxDB.

But if you want to migrate data from ClickHouse to VictoriaMetrics, you can try the [import API](https://docs.victoriametrics.com/#how-to-import-time-series-data). VictoriaMetrics supports JSON, CSV and more data format.

**Comment by coding-hui** [comment]
> I am not sure if I have misunderstood your question. Are you looking to migrate data from ClickHouse to InfluxDB, not ClickHouse to VictoriaMetrics? If that's the case, perhaps you should explore some of the solutions provided by InfluxDB.
> 
> But if you want to migrate data from ClickHouse to VictoriaMetrics, you can try the [import API](https://docs.victoriametrics.com/#how-to-import-time-series-data). VictoriaMetrics supports JSON, CSV and more data format.

ok,thanks.
