### ISSUE TITLE
[QUESTION] Monitoring VM with another VM

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#799]
Hey,

I was looking for a good way to monitor VM (cluster version) and I thought about monitoring production VM with another instance of VM. Is it a recommended approach? 

Looking at vmagent it requires a storage component like prometheus or vm and if my use case is just monitoring vm then vmagent seems like not the best alternative (because then I will need to use the same vm I am monitoring for storage or add another component to maintain).

Thanks!

**Comment by dxtrzhang** [comment]
> I thought about monitoring production VM with another instance of VM. Is it a recommended approach?

That's what we do now.

You can use single node version of vm(victoria-metrics) for the self monitoring, it packets all the components you want(vmstorage, vmagent, vmselect and vminsert) into one single instance.

**Comment by Alon-Katz** [comment]
Awesome! Thanks.
