### ISSUE TITLE
Add an ability to disable PromQL extensions

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#8]
### The issue

Sometimes users want using plain [PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/) without [PromQL extensions](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL), so their queries may be used with both Prometheus and VictoriaMetrics.

### The solution

Add an ability to disable `PromQL extensions` on a per-project basis.

**Comment by belm0** [comment]
argument for the feature from duplicate issue:

> Do we agree that MetricsQL is a superset of PQL? Except for some small semantic differences noted in the docs, it must be so-- since easy migration of Prometheus query workloads is listed as a Victoria Metrics feature.
>
> So for a PQL user, features outside of the intersection can said to be extensions of PQL. We can take an example from compilers like gcc, where flags are offered to limit extensions, gate experimental features, etc. These are desirable for various reasons, including users wanting to avoid vendor lock-in (whether intentional or unintentional) and maintain flexibility to chose different implementations in the future.

Possible workaround:
> You could put something like promxy in front of your VictoriaMetrics instance. That would limit users to only PromQL queries. Bit of a hack, but it would work.

**Comment by valyala** [comment]
Closing this feature request, since it isn't going to be implemented because [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) outgrew PromQL in many aspects.
