### ISSUE TITLE
Understanding multitenancy

### ISSUE THREAD

**Issue by pepjo** [VictoriaMetrics/VictoriaMetrics#804]
Hi,

If this is not the best place to ask this, **please feel free to redirect me to where this question would be appropriate**.

I am trying to understand the multitenancy feature from VM, however, I can only see it mentioned [here](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html).

I would like to understand why is it only available on the cluster version, what limitations does it have, and how does it work. The following are some questions that I have but I could not find the answer to:

- Does it use different `vmstorage` for each tenant? If so, do I have to scale the pods to match the number of tenants?
- If I would like to connect grafana, would I have to create a different connection for each tenant?
- When using alerts, will they apply to all tenants? If not, how do you configure the alerts for each tenant?

Thanks in advance for your help!

**Comment by pepjo** [comment]
Closing this, I just found the section where it says: `Join our Slack or contact us with consulting and support questions`

**Comment by valyala** [comment]
FYI, some of these questions are already answered at https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#multitenancy 

> Does it use different vmstorage for each tenant? If so, do I have to scale the pods to match the number of tenants?

No, each tenant's data is evenly spread among available `vmstorage` nodes. This guarantees even load among `vmstorage` nodes when serving tenants with different number of samples and time series.

> If I would like to connect grafana, would I have to create a different connection for each tenant?

Yes - tenant id is encoded in url, so you should use distinct datasource urls in Grafana for each tenant. See https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#url-format for more details.

> When using alerts, will they apply to all tenants? If not, how do you configure the alerts for each tenant?

Alerts are applied individually to each tenant. There is a feature request for multi-tenant alerts - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/740
