### ISSUE TITLE
range_* functions only emit points at input timestamps

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#806]
**Describe the bug**
The range_*() functions like `range_max()` only emit data points where there is a corresponding data point in the input.

**Expected behavior**
The global value computed by these functions should exist throughout the range.

**Screenshots**
![Screen Shot 2020-10-02 at 5 17 01 PM](https://user-images.githubusercontent.com/1708631/94902727-9d622e80-04d3-11eb-8f35-5ca353ed44ef.png)

**Version**
victoria-metrics-20200929-211927-tags-v1.42.0-0-ge59de9838

**Comment by valyala** [comment]
The issue should be addressed in the commit 59c26feefa1be18865803a42f87620151828c465

**Comment by valyala** [comment]
The bugfix has been included in [v1.43.0 release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

**Comment by belm0** [comment]
@valyala Please consider addressing test coverage deficiencies for MetricsQL functions 🙏
