### ISSUE TITLE
 cannot read influx line protocol data: too long line - caused by const maxLineSize

### ISSUE THREAD

**Issue by rskuza** [VictoriaMetrics/VictoriaMetrics#807]
**Describe the bug**
Unable to ingest datapoints in influx format using influx line protocol when line is longer than 256KiB. Issue is caused by fixed maxLineSize in lib/protoparser/common/lines_reader.go

**To Reproduce**
Try to write datapoint in influx format when line is longer than 256KiB

**Expected behavior**
Configurable parameter like -maxLineSize, or even better configurable parameter per protocol used like -maxInfluxLineSize, -maxGraphiteLineSize and so on

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
victoria-metrics-20200929-211855-tags-v1.42.0-0-ge59de9838
```

**Used command-line flags**
none

**Comment by valyala** [comment]
The `-influx.maxLineSize` command-line flag has been added in the commit bbeac0ba4610a0c91969d923d448e64ae2cd4d73 :

```
$ bin/victoria-metrics -help | grep -A 2 influx.maxLineSize
  -influx.maxLineSize value
    	The maximum size in bytes for a single Influx line during parsing
    	Supports the following optional suffixes for values: KB, MB, GB, KiB, MiB, GiB (default 262144)
```

@rskuza , could you verify whether it works as expected for your case?

**Comment by valyala** [comment]
The `-influx.maxLineSize` command-line flag has been added in [release v1.43.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
