### ISSUE TITLE
Support time shift!?

### ISSUE THREAD

**Issue by plajjan** [VictoriaMetrics/VictoriaMetrics#808]
When comparing metrics it can be very useful to compare them at different times. In order to get them aligned in the presentation, we would need to shift one metric series in time.

For example, you want to compare the current day metrics with what it looked like 1 week ago to easily spot weekly differences. Or the same for monthly & yearly.

When doing CI testing, you ran multiple test suites at any time of the day. To compare two of them, you want to timeshift one series by an arbitrary duration.

I haven't found a mention of time shift in Victoria. Is it supported but called something else? Or can some more generic functionality be used to cover this use case?

**Comment by f41gh7** [comment]
Probably, `offset` modifier is what you are looking for  https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier

**Comment by plajjan** [comment]
@f41gh7 yes indeed, I'm probably colored by influxdb which calls it timeshift, but yes, same same different name. Does VictoriaMetrics support it?

**Comment by f41gh7** [comment]
Yep, VictoriaMetrics supports promQL and provides additional features with metricsQL.

 You can readme more at following articles:
- https://medium.com/@valyala/promql-tutorial-for-beginners-9ab455142085
- https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/MetricsQL
