### ISSUE TITLE
Where can i see the ingestion buffer? There after flushed in 1s to disk?

### ISSUE THREAD

**Issue by gitmko0** [VictoriaMetrics/VictoriaMetrics#813]
Sorry to ask this question, but I would like to adjust the flush time rate. Where is the code buffered data ingestion?

Is it inside here?
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/workingsetcache/cache.go

**Comment by valyala** [comment]
Take a look at the following places:

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/bec9b31b815583627b4e76bb9b0f62118081aa06/lib/storage/partition.go#L108

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/bec9b31b815583627b4e76bb9b0f62118081aa06/lib/storage/partition.go#L104

**Comment by gitmko0** [comment]
Great work once again. Thanks. Appreciate it.
