### ISSUE TITLE
Using VM with EKS fargate

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#815]
Hey,

I was wandering if VM can work on EKS with fargate? 

The first issue is that fargate only supports EFS and not EBS, will it make VM less performant? or is it even supported?
Then the second issue is that every vmselect and vminsert should know all the instances of vmstorage and it might be a problem with fargate?

Thanks!

**Comment by f41gh7** [comment]
Hello, 

 1) Yep, it works and EFS storage is supported. Performance should be the same. But you cannot use the same folder for multiple vmstorage instances.

 2) As far as i understand AWS Fargate docs, you can launch one vmstorage instance per task and bind service discovery to it.

**Comment by Alon-Katz** [comment]
Thanks for the quick response!

That sounds great, that the performance should be the same. I will look into the service discovery to find out how to do it.

Thanks for the help!
