### ISSUE TITLE
Proposal: vmstorage support more data types

### ISSUE THREAD

**Issue by faceair** [VictoriaMetrics/VictoriaMetrics#819]
**Is your feature request related to a problem? Please describe.**
Difficult to support VictoriaLogs requirements on existing code https://github.com/VictoriaMetrics/VictoriaMetrics/issues/816

**Describe the solution you'd like**
Right now vmstorage only supports storing float64 type data. I would like vmstorage to support richer data formats so that we can store more logs, tracing and other types of data in vmstorage. We can try to support all the observable data stores on one storage.

https://docs.influxdata.com/influxdb/v2.0/reference/syntax/line-protocol/#float-field-value-examples
We can introduce field & field type design like influxdb so that we can optimize the compression algorithm for different data types.

**Comment by belm0** [comment]
Prometheus is decidedly not intended as a logging / event database (giving it's sampled nature), so this seems like a significant departure.

**Comment by faceair** [comment]
Overly broad requirements are not conducive to building a high-performance, specialized database. Optimizations should be targeted for specific scenarios, such as VictoriaLogs or VictoriaTraces, etc.
