### ISSUE TITLE
vm retention seems to lose part of data

### ISSUE THREAD

**Issue by davidsome** [VictoriaMetrics/VictoriaMetrics#823]
**Describe the bug**
vm retention seems to lose part of data. this following picture shows when vm retention at 8.00 clock am，part of data in last month has been lost. I think it is related to indexdb，I am confused what is the bug and how I can fix it. And it seems happened many times when retention.

![image](https://user-images.githubusercontent.com/6347394/95554350-9fcc0780-0a42-11eb-911a-776b1fcc57dc.png)

**Version**
```
I use vm cluster version,  the version is v1.28.0
```

**Comment by f41gh7** [comment]
Hello, version v1.28.0 is very old, can you upgrade to the latest release?

**Comment by valyala** [comment]
Closing as duplicate for #248

**Comment by davidsome** [comment]
@valyala when I upgrade cluster-v1.28.0 to cluster-v1.31.5 , I found old data will be lost. do you know why? And I can fix it ?

**Comment by valyala** [comment]
@davidsome , old data should become visible after a day after the upgrade from v1.28.0 to v1.31.5 - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/290 for details.
