### ISSUE TITLE
Influx protocol insertion issue - VMAgent and  VictoriaMetrics

### ISSUE THREAD

**Issue by syepes** [VictoriaMetrics/VictoriaMetrics#829]
### Describe the bug
I have recently noticed a strange behavior when ingesting metrics with the influx protocol.

if the metric (measurements) is named 'proc_cpu_cur' I can see and query the data without any issues.
if we change the metric (measurements) name to 'proc-cpu-cur', we can no longer see nor query* the metrics from grafana.

Having a deeper look the metric data is actually getting stored, but its not returned by the standard query. If I use the query '{__name__=~"proc-mem-cur"}' it returns values but not using the standard name.

 **Does not work**
curl -H 'Content-Type: application/json'  'http://localhost:8428/api/v1/query_range?query=proc_cpu_cur&start=1602459660&end=1602502860&step=30'
{"status":"success","data":{"resultType":"matrix","result":[]}}
**Works**
curl -H 'Content-Type: application/json'  'http://localhost:8428/api/v1/query_range?query=%7B__name__%3D~%22proc-mem-cur%22%7D&start=1602459660&end=1602502860&step=30'
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"proc-mem-cur","db":....}}}}

### To Reproduce
I have noticed this on VMAgent  or VictoriaMetrics running with 'influxSkipSingleField'

**Does not work**
Metrics inserted like this are not queryable unless using '{__name__=~"proc-mem-cur"}' 
curl -d "proc-mem-cur,host=test value=$(($RANDOM % 10 + 1)) `date +%s%N`" -X POST 'http://localhost:8428/write'

**Works as expected**
curl -d "proc_mem_cur,host=test value=$(($RANDOM % 10 + 1)) `date +%s%N`" -X POST 'http://localhost:8428/write' (edited) 

### Expected behavior
Metrics (measurements) inserted with characters '_' or '-' should behave in the same way and be equally queryable

### Version
```
vmagent-20201006-120534-tags-v1.43.0-cluster-0-g1602f5579
victoria-metrics-20201006-113105-tags-v1.43.0-0-g2a6fa5395

```

**Comment by syepes** [comment]
The '-' are not support :-)
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

**Comment by valyala** [comment]
VictoriaMetrics supports arbitrary chars in metric names, label names and label values. Certain chars such as `-` may clash with [MetricsQL syntax](https://victoriametrics.github.io/MetricsQL.html). For instance, `foo-bar-baz` metric is interpreted into `foo - bar -baz` expression by MetricsQL parser. Such special chars can be escaped with backslashes in queries: `foo\-bar\-baz`.
