### ISSUE TITLE
vmalert: Does it maintain state of alerts after restart

### ISSUE THREAD

**Issue by sagor999** [VictoriaMetrics/VictoriaMetrics#830]
Hello,

I couldn't find an answer to that question in docs.
Currently using promxy for alerting, and each time it restarts, all alerts get reset, because it is stateless.

Does vmalert save the state of alerts? So that when it is restarted, does it read alert state from previous run and resumes from there? And if yes, is there anything specific with setup to make it work? Or just remote-write and remote-read is all it needs?

Thank you!

**Comment by f41gh7** [comment]
Hello, yes, a state of alerts are restored during restart. Nothing specific is needed. You are right, flags  `-remoteRead.url` and `remoteWrite.url` must be provided with the same url address of VictoriaMetrics database.

**Comment by hagen1778** [comment]
Thanks for question! I changed the README to highlight some details and requirements for state restore process in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/833

**Comment by sagor999** [comment]
Excellent! Thank you!
