### ISSUE TITLE
Group by time and aggregate in MetricsQL

### ISSUE THREAD

**Issue by chaymankala** [VictoriaMetrics/VictoriaMetrics#831]
I have a metric say x, of type gauge, And the values are reported every 5m.

Now I want to make a query such that, I get sum of values in each hour in a day.

Exmaple: from 3PM to 5PM, the gauge values are 1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2,1,1,1,1,1,2,2,2,2,2 reported every 5 minutes - total 60 values

The result of my query should be 3PM-4PM -> 45 and 4PM-5PM -> 45 (sum of all values in the hour)

**Comment by valyala** [comment]
This can be done with `sum_over_time(x[1h])` query sent to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) with `step=1h` and the desired `start` and `end`  args.
See [documentation for PromQL functions](https://prometheus.io/docs/prometheus/latest/querying/functions/) and [documentation for MetricsQL functions](https://victoriametrics.github.io/MetricsQL.html).
