### ISSUE TITLE
option to clear rollup cache on server start

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#834]
**Is your feature request related to a problem? Please describe.**
For our use of VM (single-node), to avoid confusion we'd prefer that the cache is cleared each time the server starts.  Especially since VM is in rapid development, there are often bug fixes, etc.  We'd like to always have query output that is consistent with the current server version.

**Describe the solution you'd like**
add an option like `-search.resetRollupResultCache`

**Describe alternatives you've considered**
  * `-search.disableCache` option exists, but we only want to clear the cache, not disable it
  * `/internal/resetRollupResultCache` endpoint exists, but we would have to set up a wrapper script or something to trigger it, and I'd like to avoid adding some fragile layers

**Comment by valyala** [comment]
There is another workaround - to manually delete `<-storageDataPath>/cache` directory between restarts.

**Comment by valyala** [comment]
FYI, there is another option to reset cache on startup - to put `reset_cache_on_startup` file at `<-storageDataPath>/cache` directory before restarting VictoriaMetrics. See [these docs](https://docs.victoriametrics.com/#cache-removal) for more details. This option has been appeared starting from [v1.63.0](https://docs.victoriametrics.com/CHANGELOG.html) - see [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1447).

**Comment by valyala** [comment]
@belm0 , the commit 61d9df4c36dfea7e0fe873d2e220bb39efd58a81 adds `-search.resetRollupResultCacheOnStartup` command-line flag to single-node VictoriaMetrics and to `vmselect` at [VictoriaMetrics cluster](https://docs.victoriametrics.com/cluster-victoriametrics/). This allows resetting [rollup result cache](https://docs.victoriametrics.com/#rollup-result-cache) on VictoriaMetrics startup.

This commit will be included in the next release.

**Comment by valyala** [comment]
The `-search.resetRollupResultCacheOnStartup` command-line flag is available in single-node VictoriaMetrics and in `vmselect` component at VictoriaMetrics cluster starting from [v1.98.0 release](https://docs.victoriametrics.com/CHANGELOG.html). 

Closing the feature request as done.
