### ISSUE TITLE
vmalert analyse past data on request

### ISSUE THREAD

**Issue by pepjo** [VictoriaMetrics/VictoriaMetrics#836]
**Is your feature request related to a problem? Please describe.**
Our current use-case for VictoriaMetrics is a bit different than most. As a satellite operator, we have limited connection time to our remote systems. Connections might last just several minutes and might only occur every few hours. This use-case is similar to some IoT devices, where `vmagent` can be used to safely relay metrics when the connection is available.

The main problem that we face is during the usage of `vmalert`. We are able to use it to detect alerts that occur during the minutes that we have a connection with the remote satellite, however, we are unable to analyse past data to see if a problem occurred but it later resolved.

**Describe the solution you'd like**
We would like a way to tell `vmalert` to scan for a group of alerts during a period of time, for example: `Scan alerts for group 123456789 between 10am and 14pm`. We believe that an HTTP endpoint would be a good way to implement it. Furthermore, it would be ideal if the alerts have the correct timestamps from the time they occurred, not from the time they were detected (in this example, the time we used the HTTP endpoint). It would also be great to be able to specify an alert group, as we also use VictoriaMetrics for other conventional server and we would not like to detect again the same alerts.

**Describe alternatives you've considered**
We could manually implement a feature that queries `vmstore` over a period of time to get the same result, but we believe this would mostly duplicate `vmalert`.

We could implement a different alerting solution that scans data points as they are ingested, similar to a proxy before VictoriaMetrics. But we believe using the current `vmalert` will be faster to implement and require less maintenance.

**Comment by valyala** [comment]
FYI, Prometheus is going to implement similar feature - see https://github.com/prometheus/prometheus/pull/8674/files

**Comment by pepjo** [comment]
Thanks for sharing, that is great! It is also implemented as a comand in an executable, similar to what we discussed.

**Comment by valyala** [comment]
The backfilling for recording rules and alerting rules is available starting from [v1.61.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://docs.victoriametrics.com/vmalert.html#rules-backfilling). Closing the feature request as done.
