### ISSUE TITLE
vmstorage CrashLoopBackOff with data corrupt

### ISSUE THREAD

**Issue by lcfang** [VictoriaMetrics/VictoriaMetrics#838]
**Describe the bug**
one of my vmstorages CrashLoopBackOff with data corrupt

**To Reproduce**
helm install the VM using [this chart](https://github.com/VictoriaMetrics/helm-charts), there are two replicas default, after one day, I scale the vminsert and vmselect to 0, and scale vmstorage to 3, after that add arg `-replicationFactor=3` to vminsert and `-dedup.minScrapeInterval=1ms` to vmselect and add vmstorage-2 info to all, then scale vminset and vmselect to 3, but I think these are no relation with my error.

**Expected behavior**
all the pods are running.

**Screenshots**
![image](https://user-images.githubusercontent.com/30678878/96207701-66dde680-0f9e-11eb-9417-2717f51a8982.png)

![image](https://user-images.githubusercontent.com/30678878/96207729-7fe69780-0f9e-11eb-8445-c744ba896fab.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ /vmselect-prod --version
vmselect-20201006-115713-tags-v1.43.0-cluster-0-g1602f5579
$ /vmselect-prod --version
vmselect-20201006-115713-tags-v1.43.0-cluster-0-g1602f5579
$ /vmstorage-prod --version
vmstorage-20201006-120126-tags-v1.43.0-cluster-0-g1602f5579
```

**Used command-line flags**
Command-line flags are listed as `flag{name="httpListenAddr", value=":443"} 1` lines at `/metrics` page.
See the following docs for details:

* [monitoring for single-node VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring)
* [montioring for VictoriaMetrics cluster](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#monitoring)

**Additional context**
Add any other context about the problem here such as error logs from VictoriaMetrics and Prometheus,
`/metrics` output, screenshots from the official Grafana dashboards for VictoriaMetrics:

* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

**Comment by f41gh7** [comment]
@valyala  probably, we can add flag `--allow-unclean-shutdown` to skip broken files, WDYT?

**Comment by valyala** [comment]
> probably, we can add flag --allow-unclean-shutdown to skip broken files, WDYT?

This isn't good solution, since it may skip detected broken files on startup, but it cannot skip broken files when VictoriaMetrics already runs and detects broken file during querying or during background merge of smaller files into bigger files. It is better just manually removing directories with broken files under `<-storageDataPath>/data/{big,small}` directories before starting VictoriaMetrics.

**Comment by lcfang** [comment]
Hi, @valyala , I agree this issue is about `longhorn`, the performance of longhorn in my virtualmachine env maybe not enough, I deploy vm on servers running a long time and don't get this issue again, I think the performance of volume itself is very important.
so this issue can be closed.

**Comment by lcfang** [comment]
close
