### ISSUE TITLE
Running VictoriaMetrics in background OpenBSD

### ISSUE THREAD

**Issue by GhioRodolphe** [VictoriaMetrics/VictoriaMetrics#839]
**Is your feature request related to a problem? Please describe.**
I'm tryning to run VM as background but I didn't find any flags or anythings in the documentation that allow me to run VM in backgroup on OpenBSD 6.7

**Describe the solution you'd like**
It would be great if a -deamonize flag is added so we can run VM in background easly

**Comment by f41gh7** [comment]
Maybe it helps to run with nohup command?

```bash
 nohup ./victoria-metrics > /var/log/victoria-metrics .log &
```

**Comment by valyala** [comment]
@GhioRodolphe , I believe VictoriaMetrics can run as a daemon under OpenBSD in the same way as Prometheus does. See, for example, https://www.findelabs.com/post/grafana-prometheus-monitoring-openbsd/ . It looks like Prometheus doesn't provide command-line flag similar to `-daemonize` - see http://demo.robustperception.io:9090/flags .

**Comment by dohnuts** [comment]
> @GhioRodolphe , I believe VictoriaMetrics can run as a daemon under OpenBSD in the same way as Prometheus does. See, for example, https://www.findelabs.com/post/grafana-prometheus-monitoring-openbsd/ . It looks like Prometheus doesn't provide command-line flag similar to `-daemonize` - see http://demo.robustperception.io:9090/flags .

Yes ,
```
rc_start() {
        ${rcexec} "${daemon} ${daemon_flags} < /dev/null 2>&1 | \
                logger -p daemon.info -t prometheus"
}
```

Nevertheless all of that is losing log level, Prometheus is using Heroku like message and system-d SD_ are leveled with a prefix like <5> , i ve been looking into that and it s kind of sad how 'new' tech is trying to avoid syslog for zero reason.

It s super easy to format syslog message with the level for an analysis platform , but on a remote system parsing log level that does not event use a unified naming scheme for the level is crazy.

Moreover with this kind of pipe ( recommended by many like runit or god - do daemon ) if you kill the logger process ,
I am not even sure what is happening after.

The Victoria code is clean enough to support syslog easily in the case statement , using `csh -f programe &` is ok, but i hope a syslog patch could be done or accepted.

**Comment by dohnuts** [comment]
> @GhioRodolphe , if this feature request is still relevant, then we are happy to accept a patch, which adds `-daemonize` command-line flag for running VictoriaMetrics components in background mode under OpenBSD.

It is not, the openbsd rc system handle the 'daemonize ation' , --syslog would be more helpful ( mariadb does it for example ).
You can close this. @valyala
