### ISSUE TITLE
vm_request_duration_seconds in /metrics always empty

### ISSUE THREAD

**Issue by rumanzo** [VictoriaMetrics/VictoriaMetrics#85]
Hi! At least in version 1.20.7 I have emty result for vm_request_duration_seconds in /metrics, and some values with vm_http_request_duration_seconds. What difference between them?
Should I have some metrics with vm_request_duration_seconds?

**Comment by valyala** [comment]
The following metric should increase when querying VictoriaMetrics with Grafana: `vm_request_duration_seconds{path="/api/v1/query_range"}`

`vm_http_request_duration_seconds` must be renamed to `vm_request_duration_seconds`. This is a typo.

**Comment by rumanzo** [comment]
I'm querying VictoriaMetrics with Grafana throw promxy, and still missing any metrics with vm_request_duration_seconds

**Comment by valyala** [comment]
Try building from the latest commit. It has fixes to `Summary` metrics. Previously these metrics could be missing during the first call to `/metrics`. Now this should be fixed.

**Comment by rumanzo** [comment]
I build latest version (victoria-metrics-20190628-114426-heads-master-0-g7354f10), several times curl metrics, refresh dashboard in grafana. Still vm_request_duration_seconds is missing parameter in metrics

**Comment by valyala** [comment]
This looks strange. Could you post output for the given commands?
```
curl -s http://localhost:8428/api/v1/query_range?query=up > /dev/null
curl -s http://localhost:8428/api/v1/query_range?query=foobar > /dev/null
curl -s http://localhost:8428/metrics | grep vm_request_duration_seconds
```

The last line should return non-empty output like the following:
```
vm_request_duration_seconds{path="/api/v1/query_range",quantile="0.5"} 0.000191568
vm_request_duration_seconds{path="/api/v1/query_range",quantile="0.9"} 0.001096796
vm_request_duration_seconds{path="/api/v1/query_range",quantile="0.97"} 0.001096796
vm_request_duration_seconds{path="/api/v1/query_range",quantile="0.99"} 0.001096796
vm_request_duration_seconds{path="/api/v1/query_range",quantile="1"} 0.001096796
vm_request_duration_seconds_sum{path="/api/v1/query_range"} 0.001604217
vm_request_duration_seconds_count{path="/api/v1/query_range"} 2
```

**Comment by rumanzo** [comment]
> Could you post output for the given commands?

[root@akostin-prometheus-1 ~]# victoriametrics -version
victoria-metrics-20190628-114426-heads-master-0-g7354f10
[root@akostin-prometheus-1 ~]# curl http://localhost:8428/query=up > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    40  100    40    0     0   5914      0 --:--:-- --:--:-- --:--:--  5714
[root@akostin-prometheus-1 ~]# curl http://localhost:8428/query=foobar > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    44  100    44    0     0   5823      0 --:--:-- --:--:-- --:--:--  6285
[root@akostin-prometheus-1 ~]# curl http://localhost:8428/metrics | grep vm_request_duration_seconds
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12755    0 12755    0     0  1916k      0 --:--:-- --:--:-- --:--:-- 2076k
[root@akostin-prometheus-1 ~]#

**Comment by valyala** [comment]
You use invalid paths for [Prometheus query API](https://prometheus.io/docs/prometheus/latest/querying/api/). Use `/api/v1/query_range?query=up` instead of `/query=up`. Just copy-n-paste commands from the previous message.

**Comment by rumanzo** [comment]
> You use invalid paths for [Prometheus query API](https://prometheus.io/docs/prometheus/latest/querying/api/). Use `/api/v1/query_range?query=up` instead of `/query=up`. Just copy-n-paste commands from the previous message.

I'm sorry, my fault.
I retry, and get results.
And I found something else. If I manually curl VictoriaMetrics, I got metrics vm_request_duration_seconds, if I do source in grafana directly to VictoriaMetrics - i got metrics, but if I use promxy - I do not. Checked twice

**Comment by valyala** [comment]
Make sure that `promxy` sends queries to VictoriaMetrics. Check its' config. Probably it sends queries to another upstream datasource such as Prometheus.

Probably `promxy` or another proxy such as [trickster](https://github.com/Comcast/trickster) caches results, so subsequent queries don't reach  VictoriaMetrics. Try modifying queries that are sent to `promxy`. Try modifying `step`, `start` and `stop` args in [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) in order to skip possible caches.

Try using `promxy` url in Prometheus datasource in Grafana.

**Comment by rumanzo** [comment]
You are right and I am very ashamed.
I'm confused in Puppet module, and put the wrong port to promxy config

**Comment by valyala** [comment]
:) Then closing the issue
