### ISSUE TITLE
*_over_time() output is incorrect

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#850]
**Describe the bug**
query `count(max_over_time(my_metric[5d]))` is giving incorrect output.  It is related to ending of individual data series, because the problem is especially noticeable across a 12 hour outage of our metrics ingestion.

See attached screenshots of VM vs. prometheus (thanos).  Notably:
  * steady state value before the outage is 2730 vs. 3325
  * during the outage there is an abnormal floor value 2391 on VM only
  * after outage also has a large discrepancy
 
**Expected behavior**
output should reasonably match query executed on Prometheus

**Screenshots**
![Screen Shot 2020-10-22 at 11 31 58 AM](https://user-images.githubusercontent.com/1708631/96817499-6d66d500-145a-11eb-9c77-8614d1d8f454.png)
![Screen Shot 2020-10-22 at 11 32 18 AM](https://user-images.githubusercontent.com/1708631/96817497-6b9d1180-145a-11eb-96fb-c7c7b48363ca.png)

**Version**
```
v1.44.0
```

**Comment by valyala** [comment]
@belm0 , could you try adding more specific label filters to the query, i.e. `count(max_over_time(my_metric{label="value"}[5d]))`, so  it returns lower values? Then try removing outer `count()` from the query and leaving only `max_over_time(my_metric{label="value"}[5d])`, so the remaining time series on graphs could be compared and investigated between Prometheus and VictoriaMetrics?

**Comment by belm0** [comment]
Why does 66de02f mention this issue in the PR description, but a different issue in the comments?  I don't know if it's really related.

**Comment by belm0** [comment]
> could you try adding more specific label filters to the query

@valyala not sure if this is the main problem case, but following is the first discrepancy I hit.  I'm using stacked display so we can see both the count and continuity of individual series.

raw series - basically Prometheus and VM are the same except for the range end point:
![Screen Shot 2020-11-02 at 5 58 45 PM](https://user-images.githubusercontent.com/1708631/97854008-3a66f000-1d3c-11eb-9070-1bb7364874ce.png)
![Screen Shot 2020-11-02 at 5 58 37 PM](https://user-images.githubusercontent.com/1708631/97854020-3e930d80-1d3c-11eb-8ce2-d19e441fa6bd.png)

`count_over_time([5d])` - very different, and I don't know what VM is doing:
![Screen Shot 2020-11-02 at 6 00 14 PM](https://user-images.githubusercontent.com/1708631/97854244-8ade4d80-1d3c-11eb-996d-2f53db94eb42.png)
![Screen Shot 2020-11-02 at 6 00 05 PM](https://user-images.githubusercontent.com/1708631/97854359-af3a2a00-1d3c-11eb-9507-85c60c545b03.png)

interestingly, `[1h]` interval mostly match.  As the interval increases to `[2d]` and then `[5d]` VM has an increasing number of dropped series.

`[1h]`:
![Screen Shot 2020-11-02 at 7 00 15 PM](https://user-images.githubusercontent.com/1708631/97856196-515b1180-1d3f-11eb-84d3-4cc49d018502.png)
![Screen Shot 2020-11-02 at 7 00 04 PM](https://user-images.githubusercontent.com/1708631/97856601-d9d9b200-1d3f-11eb-9c1e-2f224fa4667e.png)


`[2d]`:
![Screen Shot 2020-11-02 at 7 10 27 PM](https://user-images.githubusercontent.com/1708631/97856315-7780b180-1d3f-11eb-9e76-afec4d54f98e.png)
![Screen Shot 2020-11-02 at 7 10 35 PM](https://user-images.githubusercontent.com/1708631/97856338-7cddfc00-1d3f-11eb-970d-8139259742c6.png)

**Comment by belm0** [comment]
here is another comparison with a different set of series, raw vs 6h interval

I've highlighted a point where VM drops a series where it clearly should not have.

raw:
![Screen Shot 2020-11-02 at 7 44 24 PM](https://user-images.githubusercontent.com/1708631/97859520-114a5d80-1d44-11eb-9962-65ca16135bdc.png)
![Screen Shot 2020-11-02 at 7 43 48 PM](https://user-images.githubusercontent.com/1708631/97859510-0d1e4000-1d44-11eb-8437-d8b16acedac4.png)

max_over_time([6h]):
![Screen Shot 2020-11-02 at 7 43 16 PM](https://user-images.githubusercontent.com/1708631/97859465-fd9ef700-1d43-11eb-9a2f-2a2b9bfea7d6.png)
![Screen Shot 2020-11-02 at 7 42 44 PM](https://user-images.githubusercontent.com/1708631/97860285-3d1a1300-1d45-11eb-995a-2c89bb057830.png)

**Comment by belm0** [comment]
regarding DATA2 example:  in fact, it seems that the 6h interval is not applied to the end of the range at all

![Screen Shot 2020-11-02 at 8 31 58 PM](https://user-images.githubusercontent.com/1708631/97863720-c54ee700-1d4a-11eb-8d30-36c35da05c80.png)

**Comment by valyala** [comment]
@belm0 , could you verify whether this behavior remains in [v1.45.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)? Please [drop response caches](https://victoriametrics.github.io/#backfilling) before verifying this in v1.45.0 .

**Comment by belm0** [comment]
it seems resolved in 1.45.0, thank you
