### ISSUE TITLE
when will victoria support eureka_sd_config?

### ISSUE THREAD

**Issue by w6m6** [VictoriaMetrics/VictoriaMetrics#851]
**Is your feature request related to a problem? Please describe.**
In lastest prometheus(v2.22), new scrape_config for eureka was introduced,  and we are wondering when victoria support it? 
thx a lot.

**Comment by valyala** [comment]
`eureka_sd_config` looks promising! VictoriaMetrics will add support for `eureka_sd_config` as soon as we'll see high demand in this service discovery.

**Comment by w6m6** [comment]
@valyala thx a lot.

**Comment by valyala** [comment]
@w6m6 , Prometheus-compatible [Eureka](https://github.com/Netflix/eureka) service discovery has been added in the commits eec76718e9bddd6ce1903449e6b1844252734133 and d7932775cc42a1c41f870d16d5c16c7cadab748a . Could you build VictoriaMetrics (or [vmagent](https://victoriametrics.github.io/vmagent.html)) from the commit d7932775cc42a1c41f870d16d5c16c7cadab748a and verify whether it works as expected? See [build instructions for VictoriaMetrics](https://victoriametrics.github.io/#how-to-build-from-sources) and [build instructions for vmagent](https://victoriametrics.github.io/vmagent.html#how-to-build-from-sources).

These commits will be included in the next release if they work OK.

**Comment by valyala** [comment]
VictoriaMetrics supports Eureka service discovery aka eureka_sd_config starting from [v1.48.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this feature request as done.

@w6m6 , could you verify whether eureka_sd_config works in the same way as in Prometheus starting from v1.48.0? Feel free re-opening the issue if something doesn't work for Eureka service discovery.
