### ISSUE TITLE
topk to return sum of all series which aren't in top K elements

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/VictoriaMetrics#854]
**Is your feature request related to a problem? Please describe.**
The common case when plotting `topk` series is to show sum of all series which aren't in the selected top K of elements. 

**Describe the solution you'd like**
`topk` could return the sum as extra time series with name `other` or similar.

**Describe alternatives you've considered**
Using `ifnot` to exclude series returned from topk: `sum(metric) by (label) ifnot topk(3, sum(metric) by (label))`. But it doesn't seem to be working.

**Comment by belm0** [comment]
> topk could return the sum as extra time series with name `other` or similar

it may break existing queries which aren't expecting the additional series, so perhaps this needs to be a separate function

The use case seems somewhat specialized.  In many cases sum of "not top k" would be orders of magnitude larger than the top k series, so it wouldn't make sense to display them together.

**Comment by valyala** [comment]
This has been implemented in [v1.45.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). For example, `topk_max(3, process_resident_memory_bytes, "remaining_sum")` would return top 3 time series with the maximum value plus a sum of all the remaining time series in a time series with label `remaining_sum="remaining_sum"`. See `topk_*` and `bottomk_*` docs at [MetricsQL](https://victoriametrics.github.io/MetricsQL.html) for details.
