### ISSUE TITLE
Add support "Content-encoding: deflate" for vmagent

### ISSUE THREAD

**Issue by ofen** [VictoriaMetrics/VictoriaMetrics#857]
**Describe the solution you'd like**
Please add support for "deflate" decoding and add appropriate request header "Accept-Encoding: deflate, gzip" (https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/lib/promscrape/client.go#L90-L92) when scrapping targets.

**Additional context**
This feature required in case if HTTP endpoint returns "deflate" encoded response instead of "gzip" one.

**Comment by valyala** [comment]
It looks like `deflate` encoding for http responses isn't widely used in real world according to https://zlib.net/zlib_faq.html#faq39 :

> there have been reports of servers and browsers that incorrectly produce or expect raw deflate data per the deflate specification in RFC 1951, most notably Microsoft. So even though the "deflate" transfer encoding using the zlib format would be the more efficient approach (and in fact exactly what the zlib format was designed for), using the "gzip" transfer encoding is probably more reliable due to an unfortunate choice of name on the part of the HTTP 1.1 authors.
> Bottom line: use the gzip format for HTTP 1.1 encoding.

@ofen , could you provide more details on the use case where `Accept-Encoding: deflate` is needed? Could you also check whether Prometheus supports this encoding during targets' scraping?

**Comment by valyala** [comment]
Closing this feature request because of inactivity.

@ofen , feel free re-opening it and providing more details on the use case for `Accept-Encoding: deflate`.
