### ISSUE TITLE
Vmagent (remote write) + Thanos Receiver Results in 100% Dropped Samples

### ISSUE THREAD

**Issue by rickdonato** [VictoriaMetrics/VictoriaMetrics#873]
**Describe the bug**
When using the vmagent and sending samples to Thanos receiver via a remote write, there are situations where the Thanos receiver will send an HTTP 4XX back to the sender if it is unable to ingest the sample. This is to prevent the sender sending incorrect data and avoiding retry loops (https://github.com/thanos-io/thanos/issues/1509).
After the VMagent gets the 4XX response, it stops sending any samples upstream to the Thanos receiver.

From looking at the metrics on the vmagent I can see the 409 responses increase and also the queue.
```
...
vmagent_remotewrite_errors_total{url="1:http://thanos-receive:10908/api/v1/receive"} 0
vmagent_remotewrite_global_relabel_metrics_dropped_total 0
vmagent_remotewrite_pending_data_bytes{path="/tmp/persistent-queue/1_E2292CB6C0038D5F", url="1:http://thanos-receive:10908/api/v1/receive"} 18467
vmagent_remotewrite_pending_inmemory_blocks{path="/tmp/persistent-queue/1_E2292CB6C0038D5F", url="1:http://thanos-receive:10908/api/v1/receive"} 4
vmagent_remotewrite_relabel_metrics_dropped_total{path="/tmp/persistent-queue/1_E2292CB6C0038D5F", url="1:http://thanos-receive:10908/api/v1/receive"} 0
vmagent_remotewrite_requests_total{url="1:http://thanos-receive:10908/api/v1/receive", status_code="2XX"} 146
vmagent_remotewrite_requests_total{url="1:http://thanos-receive:10908/api/v1/receive", status_code="409"} 5158
vmagent_remotewrite_retries_count_total{url="1:http://thanos-receive:10908/api/v1/receive"} 5154
...
```

**To Reproduce**
* Setup/run up telegraf to send to vmagent via `outputs.influxdb`
* Setup/run VMagent to remote write to Thanos receiver
* Setup/run Thanos receiver
* Setup/run Thanos gateway and querier
* Connect Grafana to the Thanos querier
At the point you see any out of order samples on the Thanos receiver, you will see the Vmagent logs the fact it is seeing 409 back off messages from the Thanos receiver. 
Grafana dashboards then allow you to observe the lack of samples within the TSDB.

**Expected behavior**
The expected behavior is that only the single sample will not be resent and all other samples would continue to be sent upstream.

**Screenshots**
Everything starts off fine. then the Metrics straighten out, then eventually stop.
![image](https://user-images.githubusercontent.com/4304301/97694121-0e2c4480-1a9a-11eb-9e19-27caabe47ba9.png)

**Version**
VMagent - v1.44.0

**Used command-line flags**
    command:
      - -remoteWrite.url=http://thanos-receive:10908/api/v1/receive
      - -remoteWrite.showURL
      - -remoteWrite.maxDiskUsagePerURL=5
      - -remoteWrite.tmpDataPath=/tmp
      - -remoteWrite.queues=4

**Comment by f41gh7** [comment]
It's interesting. Is it happens only with metrics ingested from telegraph? Or vmagent scrape config produces the same errors? How prometheus handles this case? Simply drops unordered metrics? 

 For vmagent, it is expected behavior to retry non-200 responses.

**Comment by valyala** [comment]
@rickdonato , try using `-remoteWrite.queues=1` command-line option as a temporary workaround. By default `vmagent` sends data to `-remoteWrite.url` via 4 parallel queues (aka `-remoteWrite.queues=4`). Certain samples for the same time series can be sent in parallel, so remote storage could receive them in out of order. Using a single queue (i.e. `-remoteWrite.queues=1`) should prevent from sending out of order samples to remote storage.

[The commit](0b35da159c92759c2a75fd4e08a87eeba2263caa) adds behavior similar to Prometheus to `vmagent` - it drops packets if remote storage returns `4xx` status code. Note that `vmagent` drops the whole packet with all the samples in it if remote storage returns `4xx` status code.

**Comment by valyala** [comment]
`vmagent` should drop packets if remote storage returns `4xx` status code starting from [v1.45.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the feature request as done.
