### ISSUE TITLE
add support for minTime/maxTime on promql API

### ISSUE THREAD

**Issue by jacksontj** [VictoriaMetrics/VictoriaMetrics#88]
I had an issue reported on promxy (https://github.com/jacksontj/promxy/issues/186) which lead me to a server-side prometheus issue (https://github.com/prometheus/client_golang/issues/614 and https://github.com/prometheus/prometheus/pull/5734). 

TLDR; go's stdlib time can't parse the minTime/maxTime that prometheus uses as default times. In this case when promxy gets a query without a timestamp (such as `/api/v1/series` calls) it will send the min/max time -- which go's stdlib can't parse. The workaround on prometheus was to add special-case handling of the time parsing for those 2 special times, so I'd like to see if we could get the same fix in here :)

**Comment by valyala** [comment]
I guess these times are always passed from Promxy in `UTC` time zone?

**Comment by valyala** [comment]
Added a workaround for `UTC` times.

**Comment by valyala** [comment]
The fix is available in [v1.22.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).
