### ISSUE TITLE
Starting around v1.42 the query_range end point do not return result even if i see the data with the export end point

### ISSUE THREAD

**Issue by ydastous** [VictoriaMetrics/VictoriaMetrics#881]
**Describe the bug**
Starting around v1.42 the query_range end point do not return result even if i see the data with the export end point
my data is a simple  metric name with 3 or 4 labels and 1 label have a large number of possible value, insert by the graphite  endpoint

**To Reproduce**
I am  running v1.41.0:
upgrade to anything to 1.42 ( or greater > ) and more and try to curl the query_range this give me a null result.
even if the data query were  ingested with the 1.41 version,

`curl -G  'http://127.0.0.1:8428/api/v1/query_range?query=sum(statsite_counts_rtb_gateway_flights_targeting_rate)&start=-1h&end=-30m&step=30'
{"status":"success","data":{"resultType":"matrix","result":[]}}

**Expected behavior**
`curl -G  'http://127.0.0.1:8428/api/v1/query_range?query=sum(statsite_counts_rtb_gateway_flights_targeting_rate)&start=-1h&end=-30m&step=30'
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1604518380,"108663.33789800659"],[1604518410,"83078.00412200333"],[1604518440,"84536.67046400365"],[1604518470,"123060.67057500684"],[1604518500,"128533.33784700811"],[1604518530,"94741.3373770048"],[1604518560,"123048.67151800863"],[1604518590,"92971.33780000522"],[1604518620,"92234.67088500477"],[1604518650,"89156.00419500441"],[1604518680,"101800.0042990057"],[1604518710,"71208.67054300028"],[1604518740,"80321.33729400285"],[1604518770,"90881.33738700478"],[1604518800,"71558.67063500031"],[1604518830,"97868.00435600564"],[1604518860,"119033.3379430081"],[1604518890,"100134.00471700617"],[1604518920,"108366.00435200639"],[1604518950,"150219.33825500275"],[1604518980,"174538.004644997"],[1604519010,"188471.33790499435"],[1604519040,"136540.67092200596"],[1604519070,"121480.00471500824"],[1604519100,"133338.00443600703"],[1604519130,"106622.67108000655"],[1604519160,"119041.33794300775"],[1604519190,"102407.33784700606"],[1604519220,"109919.3375770061"],[1604519250,"90922.00422200459"],[1604519280,"128603.33769600761"],[1604519310,"99373.33767000563"],[1604519340,"92516.00439100541"],[1604519370,"81856.67096200325"],[1604519400,"96327.33767500521"],[1604519430,"92065.33751000476"],[1604519460,"142642.67142400407"],[1604519490,"133453.33779000663"],[1604519520,"124822.00441700769"],[1604519550,"112627.33792500716"],[1604519580,"127161.33815000836"],[1604519610,"127318.67132700814"],[1604519640,"125892.0047280082"],[1604519670,"169250.00446099817"],[1604519700,"182946.00420299606"],[1604519730,"125823.33741400711"],[1604519760,"103859.33750400595"],[1604519790,"136994.004554006"],[1604519820,"116548.67105200728"],[1604519850,"128018.00449800768"],[1604519880,"121907.33801300834"],[1604519910,"150629.33830900147"],[1604519940,"155317.33817000064"],[1604519970,"149623.33799500234"],[1604520000,"142446.0049510044"],[1604520030,"134510.6712550068"],[1604520060,"116136.00453500747"],[1604520090,"96790.67070600504"],[1604520120,"104112.00436400608"],[1604520150,"192312.00412399435"],[1604520180,"147239.33704800226"]]}]}}`

**Screenshots**
NA

**Version**
version working: 
victoria-metrics-20200911-214525-tags-v1.41.0-0-gba74d0c14
all versions 1.42 and more does not work,

**Used command-line flags**
`/usr/bin/victoria-metrics-prod -storageDataPath=/var/lib/victoria-metrics-data-EBS -graphiteListenAddr=:2003 -retentionPeriod 12 -selfScrapeInterval=10s -search.maxUniqueTimeseries 3000000 -search.maxStalenessInterval=9s -dedup.minScrapeInterval=1s -search.maxPointsPerTimeseries 10000000 -search.maxQueryDuration 60s -search.maxConcurrentRequests 8`

i think i can create a small ( 30 minutes) data working set which show the issue this should a tar  around 1-2 gig 
not sure how to attached it.

**Comment by ydastous** [comment]
More info on my bug, it look related to the time range choose on the query_range call ( with version > 1.41) 

```curl -G 'http://127.0.0.1:8428/api/v1/query_range?query=sum(statsite_counts_rtb_gateway_flights_targeting_rate)&start=1604957410&end=1604958400&step=30'   
{"status":"success","data":{"resultType":"matrix","result":[]}}```

but same query with a start time10 sec  early give good results:
```
curl -G 'http://127.0.0.1:8428/api/v1/query_range?query=sum(statsite_counts_rtb_gateway_flights_targeting_rate)&start=1604957400&end=1604958400&step=30'  
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1604957400,"124709.33774499815"],[1604957430,"94638.00397599934"],[1604957460,"81904.00404300005"],[1604957490,"116750.00447299807"],[1604957520,"99052.6708669989"],[1604957550,"97757.33775899925"],[1604957580,"114528.67104199834"],[1604957610,"139846.00403699954"],[1604957640,"128640.67096099802"],[1604957670,"100931.33758399909"],[1604957700,"131594.67094499868"],[1604957730,"68565.33745300186"],[1604957760,"98868.67059699925"],[1604957790,"132504.00379999893"],[1604957820,"101876.67092699901"],[1604957850,"154214.00451800163"],[1604957880,"99824.67059399915"],[1604957910,"100494.00415899897"],[1604957940,"122823.33784399823"],[1604957970,"122768.6706429984"],[1604958000,"140532.6710959995"],[1604958030,"92151.33737899944"],[1604958060,"127190.67078299828"],[1604958090,"94122.00425499945"],[1604958120,"112157.33764699871"],[1604958150,"156540.67125400167"],[1604958180,"161782.0039800021"],[1604958210,"99344.00436699903"],[1604958240,"120292.67108299807"],[1604958270,"92153.33717499951"],[1604958300,"103240.67079299908"],[1604958330,"105529.3373359991"],[1604958360,"135849.33741799925"],[1604958390,"48270.00176200071"]]}]}}```

**Comment by valyala** [comment]
The `-search.maxStalenessInterval` command-line values must be bigger than the real interval between samples stored in the database. Otherwise VictoriaMetrics could return empty results or graphs with gaps. So either increase `-search.maxStalenessInterval` or decrease the interval between samples ingested in VictoriaMetrics.

**Comment by ydastous** [comment]
Thanks we can close this :-)
