### ISSUE TITLE
percentile_of() function

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#882]
**Is your feature request related to a problem? Please describe.**
Use case:  I'd like to know percentage of devices which e.g. have 1d counter increase of > 10

**Describe the solution you'd like**
`percentile_of(10, increase(my_counter[1d]))`

**Comment by valyala** [comment]
Probably you need `histogram_share` function:

> histogram_share(le, buckets) - returns share (in the range 0..1) for buckets that fall below le. Useful for calculating SLI and SLO. For instance, the following query returns the share of requests which are performed under 1.5 seconds during the last 5 minutes: histogram_share(1.5, sum(rate(request_duration_seconds_bucket[5m])) by (le))

Addtionally take a look at `share_le_over_time` and `share_gt_over_time` functions from [MetricsQL](https://victoriametrics.github.io/MetricsQL.html):

> share_gt_over_time(m[d], gt) - returns share (in the range 0..1) of values in m over d, which are bigger than gt. Useful for calculating SLI and SLO. Example: share_gt_over_time(up[24h], 0) - returns service availability for the last 24 hours.

**Comment by belm0** [comment]
> Probably you need histogram_share function:

in my case, there is no histogram involved

> Additionally take a look at share_le_over_time and share_gt_over_time

These look OK for an "over_time" context, but that isn't my case.  I'd like to know the percentage of series that are greater than a value for each individual point in time.

(I couldn't find these because I was searching for "percent".  The "share" naming is a little unusual.)

**Comment by valyala** [comment]
> I'd like to know the percentage of series that are greater than a value for each individual point in time.

Then probably you need the following query - `with (q=increase(my_counter[1d])) count(q > threshold) / count(q)`. This query would return the share of series `q` that exceeds the given `threshold` for each each point on the graph.

**Comment by valyala** [comment]
Closing the feature request, since [the proposed solution](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/882#issuecomment-723459586) should cover `percentile_of(n, q)` case.
