### ISSUE TITLE
Tool to detect high cardinality metrics

### ISSUE THREAD

**Issue by alexandv** [VictoriaMetrics/VictoriaMetrics#889]
**Is your feature request related to a problem? Please describe.**
When receiving many time series from multiple Prometheus instances it is often difficult to pinpoint which Prometheus and metric names might be generating too many time series.
With Prometheus I would use `count({__name__=~".+"}) by (__name__)` but that can be pretty expensive with a high number of series and VictoriaMetrics also has `maxUniqueTimeseries ` parameter to prevent impacting the server with a costly query.

**Describe the solution you'd like**
Mechanism to get the metric names currently generating the most time series and the most data points in the last x minutes.
Ideally we would have a dashboard with the top metric names in terms of time series and/or datapoints.
This could also maybe be added as a feature to the CLI that would directly read the index?

**Describe alternatives you've considered**
- Increase `maxUniqueTimeseries` to use `count({__name__=~".+"}) by (__name__)`. Not sure how safe it is to increase or disable the `maxUniqueTimeseries` check completely.
- Use the same query on the Prometheus instance sending the metrics but that requires first identifying the Prometheus server that could be sending too many metrics.

**Comment by valyala** [comment]
@alexandv  , could you verify whether the [/api/v1/status/tsdb](https://prometheus.io/docs/prometheus/latest/querying/api/#tsdb-stats) page contains the required information?

It is also useful to perform the following query in order to determine scrape targets exporting the maximum number of metrics:

```metricsql
topk_max(5, max_over_time(scrape_samples_scraped[1h]))
```

Additionally to that the following query could be useful for determining scrape targets that introduce the most of time series churn rate:

```metricsql
topk_max(5, max_over_time(scrape_series_added[1h]))
```

**Comment by alexandv** [comment]
Thanks @valyala ! Those are useful.

It would be nice if we could specify a time range for `/api/v1/status/tsdb`. Please correct me if I'm wrong but it seems that the metrics are for the whole database. So previous cardinality issues might overshadow the current one.

**Comment by valyala** [comment]
> It would be nice if we could specify a time range for /api/v1/status/tsdb

This endpoint accepts optional `topN=N` and `date=YYYY-MM-DD` args, where `topN` is the number of top entries to show, while `date` is the date to stats on. By default `topN=10` and `date=current_day` - see [these docs](https://victoriametrics.github.io/#prometheus-querying-api-usage) for more details.

**Comment by alexandv** [comment]
Great! Thanks. 

I think we can close this issue.
