### ISSUE TITLE
vmalert source URL broken for grafana

### ISSUE THREAD

**Issue by blakebarnett** [VictoriaMetrics/VictoriaMetrics#890]
**Describe the bug**
For all but the simplest prometheus queries the expression gets thrown out when generated from vmalert. I believe this is because grafana expects strict encoding like RFC 3986. This breaks clicking on the alert source in alertmanager, our users got very used to using these links with prometheus.

**To Reproduce**
Set `-external.alert.source="graph?g0.range_input=1h&g0.expr=\"{{$expr|quotesEscape|pathEscape}}\"&g0.tab=1"` and attempt to view an alert with a complex query (multiline, or using various special characters

**Expected behavior**
RFC3986 strict URI encoding for expressions in the URI, I believe something like this would work:
https://gist.github.com/czyang/7ae30f4f625fee14cfc40c143e1b78bf

**Screenshots**

**Version**
1.37.3+

Related to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/560/files

**Comment by f41gh7** [comment]
There is working example at https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/deployment/docker/docker-compose.yml#L73
 
 Can you try it?

**Comment by blakebarnett** [comment]
Yeah I've done quite a bit of experimenting with it, that's what led me to making this. https://github.com/VictoriaMetrics/VictoriaMetrics/issues/517#issuecomment-701097473

I think I might be able to make it work with an incredibly hairy `reReplaceAll` but it seems like it may be better added in the code as a simpler helper method...

**Comment by blakebarnett** [comment]
It's not just newlines, I believe it's all the special character replacements done in that gist I linked.

**Comment by Muxa1L** [comment]
@valyala It looks more like a bug. For example this expression for alert results in query for grafana's _explore_ reset if you try to open it clicking "Source" in alertmanager's alert. 
```
(sum(rate(rest_client_requests_total{code=~"5..", system_id="Система ниппель"}[5m])) by (instance, job)
  /
sum(rate(rest_client_requests_total{system_id="Система ниппель"}[5m])) by (instance, job))
* 100 > 1
```
external_alert_source=explore?orgId=1&left=["now-1h","now","VictoriaMetrics",{"expr":"{{$expr|quotesEscape|pathEscape}}"},{"mode":"Metrics"},{"ui":[true,true,true,"none"]}]

For simple expressions it work, but for multiline as @blakebarnett  said it did not.

Such query in grafana's query params looks like 
`{"expr":"(sum(rate(rest_client_requests_total{code=~\"5..\", system_id=\"Система ниппель\"}[5m])) by (instance, job)**\r\n**  /**\r\n**sum(rate(rest_client_requests_total{system_id=\"Система ниппель\"}[5m])) by (instance, job))**\r\n*** 100 > 1"}`

**Comment by valyala** [comment]
@f41gh7 , @hagen1778 , could you look into this?

**Comment by f41gh7** [comment]
Was able to reproduce it with:
```yaml
groups:
- name: groupTest
  rules:
  - alert: VMRows
    for: 1s
    expr: |
      go_memstats_alloc_bytes
        >
         0
```

 Suggest to add new function `crlfEscape` at PR https://github.com/VictoriaMetrics/VictoriaMetrics/commit/403886af18418d2178bfeb0d0e1b76c4f6d125be

**Comment by blakebarnett** [comment]
I believe it applies to other characters as well, please see the link in the description.

**Comment by f41gh7** [comment]
> I believe it applies to other characters as well, please see the link in the description.

 Thanks, i'll investigate it deeper and i guess, that we should introduce new function for grafana url encoding instead of 3 functions chain.

**Comment by valyala** [comment]
The bugfix for multi-line queries has been added into vmalert [v1.51.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)

**Comment by ablackmon** [comment]
> Thanks, i'll investigate it deeper and i guess, that we should introduce new function for grafana url encoding instead of 3 functions chain.

That would be a nice addition.  For now I can confirm it does fix the new line issue.

**Comment by valyala** [comment]
FYI, the commit a018b1d75ea638df62b53b331140a368c4071860 implements proper encoding of JSON string contents by the `quotesEscape` function, so its output can be safely embedded into JSON string. This makes obsolete the `crlfEscape` function, since it is no longer needed for results returned by `*Escape` functions. So it advised to remove the `crlfEscape` function from all the templates and do not use it after the next release of `vmalert` will be published.

**Comment by valyala** [comment]
The related issue - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3139

**Comment by valyala** [comment]
FYI, the `quotesEscape` function properly escapes any strings, so they could be put into JSON string, starting from [vmalert v1.83.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by valyala** [comment]
FYI, the `quotesEscape` function properly escapes any strings starting from [v1.79.5 LTS release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.79.5).
