### ISSUE TITLE
Uninformative error message from vmselect

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#891]
Sometimes users make terrible requests, to which vmselect fairly answers something like:

```Error executing query: 422: error when executing query="<...>" for (time=1605021999513, step=300000): cannot evaluate "<...>": error occured during search: cannot perform search on vmstorage <...>: cannot execute rpcName="search_v4" on vmstorage "<...>" with timeout 30.000 seconds; the timeout can be adjusted with `-search.maxQueryDuration` command-line flag: error when searching for tagFilters=[AccountID=0, ProjectID=0 {__name__=<...>] on the time range [2020-11-10 15:16:39.513 +0000 UTC - 2020-11-10 15:26:39.513 +0000 UTC]: error when searching tsids: the number of matching unique timeseries exceeds 300000; either narrow down the search or increase -search.maxUniqueTimeseries```

But this is only if there is only one vmstorage under vmselect. If we have more than 1 vmstorage in cluster (which is typically for cluster VM version), vmselect responds with uninformative error message:

```Error executing query: 422: error when executing query="<...>" for (time=1605022379023, step=300000): cannot evaluate "<...>": cannot return full response, since some of vmstorage nodes are unavailable```

I think it's worth to fix this and pass to user error message from vmstorage.

**Comment by valyala** [comment]
@wf1nder , could you build `vmselect` from commit 2ac5f00d987ad1a12031ecf06dc547ae03436910 and verify whether it returns more informative error message in query responses in your case?

**Comment by wf1nder** [comment]
Builded and checked vmselect from master, and now seems everything fine: clients getting proper error messages in grafana, and have no questions to OPs :)
Thank you!

**Comment by valyala** [comment]
The commit mentioned above has been included in [v1.47.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing this issue as resolved.
