### ISSUE TITLE
Is it possible to store future data

### ISSUE THREAD

**Issue by thomashusa** [VictoriaMetrics/VictoriaMetrics#892]
Hi, I'm currently evaluating VictoriaMetrics as a general-purpose time-series database. Some of our data is weather forecast data. In our current data store I'm storing this data with the forecasted time as the time of the data points. In other words, the time series contains data for the future.

**Question:** Is this possible to do with VictoriaMetrics?

When migrating our data I ran into the following error message:
```
victoriametrics    | 2020-11-10T16:29:46.105Z	error	VictoriaMetrics/lib/storage/storage.go:1242	warn occurred during rows addition: cannot insert row with too big timestamp 1605200400000 exceeding the current time; maximum allowd timestamp is 1605198585000; propbably you need updating -retentionPeriod command-line flag
```

Our `-retentionPeriod` is set to `0`

**Version:**
`victoria-metrics-20201102-004452-tags-v1.45.0-0-gd396c265a`

**Comment by f41gh7** [comment]
Hello, duplicates of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/827

 Atm, VictoriaMetrics supports maxTimestamp value +2 days from now.

**Comment by tedpearson** [comment]
Following up on this question, I noticed that storage/table.go has a hard coded +2 days limit. I am also doing some work with forecast data, so I recompiled VM with a larger maxTimestamp. Newer data seems to import fine. Can anyone tell me if I'll cause any issues by increasing maxTimestamp (I would guess at cache issues) or is it just an arbitrary number?

Thanks in advance.

**Comment by pavanmallepudi** [comment]
how can I pass this config in values.yaml as we are installing victoria using helm
