### ISSUE TITLE
increase() artifacts whenever series reappears

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#894]
**Describe the bug**
increase() output becomes non-zero whenever a counter series reappears, even when the counter is 0

**Expected behavior**
increase() should reflect the input series

**Screenshots**

![Screen Shot 2020-11-12 at 1 33 02 PM](https://user-images.githubusercontent.com/1708631/98896124-9f180c80-24eb-11eb-9af2-35ff8c7ae4ad.png)

**Version**
victoria-metrics-20201107-155516-tags-v1.46.0-0-g41813eb87

**Comment by belm0** [comment]
remove_resets() has a similar artifact

![Screen Shot 2020-11-12 at 1 37 04 PM](https://user-images.githubusercontent.com/1708631/98896414-38dfb980-24ec-11eb-8057-e123f89aa89e.png)

**Comment by belm0** [comment]
why bug is significant problem:

When we have an aggregate query over many series (in our case, corresponding to 1000's of devices with imperfect connectivity), it's normal for series to come and go.  This bug will produce anomalous counts.

**Comment by valyala** [comment]
@belm0 , could you build VictoriaMetrics from the commit 1f19c167a49eb1116d2e94e3bd2fef874600a99c and verify whether this fixes unexpected spikes for `increase()` at the end of time series gaps?

**Comment by valyala** [comment]
As for `remove_resets()` issue, I cannot reproduce it. Could you provide full query used when `remove_resets()` produces unexpected results?

**Comment by valyala** [comment]
Added [yet another fix](d9d01f976bc51a44bda46e16c53a22b3e08dec9a), which should prevent from returning spikes from `increase()` on time series with spare irregular data points.

**Comment by valyala** [comment]
@belm0, could you verify whether the issue is fixed in [v1.47.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by belm0** [comment]
`increase()` issue seems to be resolved

I'll open a new issue for `remove_resets()`
