### ISSUE TITLE
query and query_range returns empty list

### ISSUE THREAD

**Issue by strangeman** [VictoriaMetrics/VictoriaMetrics#895]
**Describe the bug**
I try to use VictoriaMetrics as long-term storage for Prometheus. As I see, data successfully ingested, but I cannot query it from Grafana.

I can get time series by /export endpoint:
```
curl http://localhost:8428/api/v1/export?match[]=org_graylog2_throughput_input

{
  "metric": {
    "__name__": "org_graylog2_throughput_input",
    "application": "graylog",
    "level": "infrastructure"
  },
  "values": [
    3733222616,
    3733761780,
    3734352052,
    3734897480,
    3735431731,
    3736008782,
    3736536536,
    3737061401,
    3737319094,
    3738819326
  ],
  "timestamps": [
    1605184474914,
    1605184504914,
    1605184534914,
    1605184564914,
    1605184594914,
    1605184624914,
    1605184654914,
    1605184684914,
    1605184714914,
    1605184804916
  ]
}
```

But /query_range and /query returns nothing:
```
curl "http://localhost:8428/api/v1/query_range?query=org_graylog2_throughput_input&start=1605184474&end=1605184804&step=15"
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": []
  }
}

curl "http://localhost:8428/api/v1/query_range?query=org_graylog2_throughput_input"
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": []
  }
}

curl "http://localhost:8428/api/v1/query?query=org_graylog2_throughput_input"
{
  "status": "success",
  "data": {
    "resultType": "vector",
    "result": []
  }
}
```

Prometheus, BTW, shows result of query correctly:
```
curl "http://localhost:9090/api/v1/query_range?query=org_graylog2_throughput_input&start=1605184474&end=1605184804&step=15"

{
    "status": "success",
    "data": {
        "resultType": "matrix",
        "result": [
            {
                "metric": {
                    "__name__": "org_graylog2_throughput_input",
                    "application": "graylog",
                    "level": "infrastructure"
                },
                "values": [
                    [
                        1605184474,
                        "3732683911"
                    ],
                    <omitted>
                ]
            }
        ]
    }
}
```

Grafana `Explore` page shows nothing too.

**Expected behavior**
I expected identical behavior of Prometheus and VictoriaMetrics datasources for Grafana.

**Version**
```
$ ./victoria-metrics-prod --version
victoria-metrics-20201107-155439-tags-v1.46.0-0-g41813eb87
```
Also tried 1.41 - same problem.

**Used command-line flags**
`./victoria-metrics-prod -storageDataPath=/var/lib/victoriametrics -retentionPeriod=6`

**Comment by f41gh7** [comment]
Hello, for me it works.
   Can you try to disable cache with flag `-search.disableCache=true` and try to test it with lower value for step:
```curl "http://localhost:8428/api/v1/query_range?query=org_graylog2_throughput_input&start=1605184474&end=1605184804&step=5"```

 And what is the way you ingest metrics to VictoriaMetrics?

**Comment by strangeman** [comment]
Hmm, after calling the `/internal/resetRollupResultCache` endpoint all seems working. Strange behaviour.

I ingest metrics via remote write API:
```
remote_write:
  - url: http://VM-ip:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      max_shards: 30
```

**Comment by strangeman** [comment]
I think it was a strange bug caused by a big leap through VM versions (I got this problem when updated from 1.28.0 to 1.46.0).

What I did:

- I moved old data to another folder
- Started a new instance from scratch
- Ran `/internal/resetRollupResultCache` to reset caches 
- Checked than all graphs with new data seems correct
- Exported data from the old instance and imported it to the new instance
- Ran `/internal/resetRollupResultCache`  again

After that, all graphs working correctly with old and new data

**Comment by valyala** [comment]
@strangeman , thanks for the update! Then closing the issue as resolved. Feel free re-opening it if this issue will be encountered again.

**Comment by valyala** [comment]
FYI, single-node VictoriaMetrics automatically resets response cache when it sees new sample with too old timestamp. This behavior is enabled starting from `v1.50.0` - see [the changelog](https://victoriametrics.github.io/CHANGELOG.html) for details.
