### ISSUE TITLE
feature: query stats endpoint

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#907]
**Is your feature request related to a problem? Please describe.**
It would be useful to have query stats that represent where the majority of search compute resources are going.  So it's based on frequency and duration.   And it would need to collate similar queries somehow.

Use case is when we want to find disproportionate use of query compute resources.  It can't be captured by aggregate duration or rate independently.  With the appropriate information we can clearly see opportunities to lower resource usage (by rewriting a certain query for speed, limiting the rate of a certain query, adjusting caching, etc.).

**Describe the solution you'd like**
Server tracks count and cumulative duration of all queries.  In order to combine similar queries, they are keyed by the query text with certain labels removed (configured by the user).

The server provides an endpoint to list top N queries by one of:
  * cumulative duration (roughly reflecting compute resources)
  * count
  * average duration

**Comment by valyala** [comment]
@belm0 , victoriametrics exposes query stats at `/api/v1/status/top_queries` page starting from the commit ad4e6a92837409122d76ba91bdd7ac3c4abc0fa3 .

**Comment by valyala** [comment]
VictoriaMetrics exposes query stats at `/api/v1/status/top_queries` page starting from [release v1.51.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). See [these docs](https://victoriametrics.github.io/#prometheus-querying-api-enhancements) for more details.

Closing this feature request as done.
