### ISSUE TITLE
vm_rows_added_to_storage_total does not incorporate dedup

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/VictoriaMetrics#916]
**Describe the bug**
We observed that `vm_rows_added_to_storage_total` appears to be before application of `dedup.minScrapeInterval`.

**Expected behavior**
Since `vm_rows_added_to_storage_total` is important for disk storage estimation, ideally it would include the effects of dedup.

**Version**
victoria-metrics-20201116-192030-tags-v1.47.0-0-g1c477bc2f

**Comment by valyala** [comment]
The de-duplication is applied lazily during background merges of smaller data files into bigger ones (see [this article](https://valyala.medium.com/how-victoriametrics-makes-instant-snapshots-for-multi-terabyte-time-series-data-e1f3fb0e0282) for more details about background merges). This means that it is impossible to account for de-duplicated samples in `vm_rows_added_to_storage_total` metric, which is incremented when new sample arrives to storage layer. Note that this metric is reset to 0 when `vmstorage` is reset, so it cannot be used for determining disk storage estimation. It can be used only for estimating the ingestion rate via `rate(vm_rows_added_to_storage_total)`.

`vmstorage` exports the following metrics, which could be useful for you:

* `vm_deduplicated_samples_total` - it shows the number of de-duplicated samples during background merges.
* `vm_rows` - it shows the number of rows in the storage.

**Comment by belm0** [comment]
> Note that this metric is reset to 0 when vmstorage is reset, so it cannot be used for determining disk storage estimation. It can be used only for estimating the ingestion rate via rate(vm_rows_added_to_storage_total)

ingestion rate is a component of the storage estimation, as we've already implemented on the VM dashboard

> vm_deduplicated_samples_total - it shows the number of de-duplicated samples during background merges

OK, the storage estimation query is going to get more complex:

`vm_free_disk_space_bytes / ignoring(path) ((sum(rate(vm_rows_added_to_storage_total[1d])) - sum without(type) (rate(vm_deduplicated_samples_total[1d]))) * (sum(vm_data_size_bytes{type!="indexdb"}) / sum(vm_rows{type != "indexdb"})))`

**Comment by valyala** [comment]
See the related pull request - https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5747

**Comment by valyala** [comment]
Closing this issue, since it became obsolete after merging https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5747 .
