### ISSUE TITLE
vmbackup should support Basic Auth for Snapshot urls

### ISSUE THREAD

**Issue by dwin** [VictoriaMetrics/VictoriaMetrics#917]
**Is your feature request related to a problem? Please describe.**

vmbackup does not appear to support inline Basic Auth credentials using the Snapshots flags.

ex. `vmbackup ... -snapshot.createURL http://user:pass@localhost:8428/snapshot/create`

**Describe the solution you'd like**

Support inline Basic Auth credentials

**Describe alternatives you've considered**

- Disabling Victoria Metrics Basic Auth and using separate reverse proxy

**Additional context**

none

**Comment by valyala** [comment]
vmbackup should support Basic Auth credentials in url. Probably you hit [shell escaping](https://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-when-using-bash) issues. Try quoting the url when passing it to `-snapshot.createURL`:
```bash
vmbackup ... -snapshot.createURL='http://user:pass@localhost:8428/snapshot/create'
```

**Comment by denisgolius** [comment]
Hi @dwin !
Have you resolved your issue ?
