### ISSUE TITLE
Feed data to AWS Kinesis

### ISSUE THREAD

**Issue by chaets** [VictoriaMetrics/VictoriaMetrics#918]
**Is your feature request related to a problem? Please describe.**
Is there any way, we create VictoriaMetrics Scrape data to feed in AWS Kinesis

**Describe the solution you'd like**
Is there any way, we create VictoriaMetrics Scrape data to feed in AWS Kinesis, This will help data storage in AWS S3 Bucket for long duration and do analytics on that

**Describe alternatives you've considered**
I don't see any alternates for now

**Additional context**
convert the data in the kind of format like csv, Parquet, etc to store in S3 Bucket and to do analytics from that

**Comment by valyala** [comment]
It is possible to send metrics scraped by [vmagent](https://victoriametrics.github.io/vmagent.html) or by [single-node VictoriaMetrics](https://victoriametrics.github.io/#how-to-scrape-prometheus-exporters-such-as-node-exporter) to Amazon Kinesis via [prometheus_remote_kinesis](https://github.com/shirou/prometheus_remote_kinesis). The scheme will look like:

`targets <- vmagent -> prometheus_remote_kinesis -> aws kinesis`

**Comment by denisgolius** [comment]
Hi @chaets !
Have you solve your issue ?

**Comment by denisgolius** [comment]
Closing this issue as resolved.
