### ISSUE TITLE
Question about CSV export 

### ISSUE THREAD

**Issue by BeardedShamrock** [VictoriaMetrics/VictoriaMetrics#919]
Good day. My question is likely to be very simple, but I'm stuck on it and need help.

victoria-metrics-20190531-150038-tags-v1.18.9-0-gf2cf5d8e

I need to make a CSV export, for this I use (metrics for example) - http://x.x.x.x:8428/api/v1/export/csv?format=node_network_net_dev_group{interface="ens192"}&match=http_requests_total{job="srv-clickhouse-04"}[5m] 

as a result, I get the answer - unsupported path requested: "/api/v1/export/csv" 

I'm just beginning to understand services of this kind, the task at first glance is simple, but what am I doing wrong?

p.s. 
And one more small request, can you show an example of how the query should look correctly.

Thank you so much for your help!

**Comment by valyala** [comment]
The [/api/v1/export/csv](https://victoriametrics.github.io/#how-to-export-csv-data) endpoint has been added in [v1.44.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.44.0). It is likely you have older VictoriaMetrics release.

> I need to make a CSV export, for this I use (metrics for example) - http://x.x.x.x:8428/api/v1/export/csv?format=node_network_net_dev_group{interface="ens192"}&match=http_requests_total{job="srv-clickhouse-04"}[5m]

This url has incorrect `format` and `match` arg values. The `format` must contain comma-separated column descriptions for the output CSV. For example, `format=__timestamp__:rfc3339,interface,__value__` would return CSV with three columns:
* timestamp in [RFC3339 format](https://www.ietf.org/rfc/rfc3339.txt)
* `interface` label value for the given metric
* metric value at the given timestamp

`match` arg must contain label filters (aka [time series selector](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-series-selectors)) for time series to return. For example, `match=node_network_net_dev_group{job="foobar"}` would select all the time series with `node_network_net_dev_group` name and `job="foobar"` label.

The `/api/v1/export/csv` accepts optional `start` and `end` args for limiting the time range for the returned data. By default it returns all the data.

See more details about query args for `/api/v1/export/csv` at https://victoriametrics.github.io/#how-to-export-csv-data

Note also that you may hit escaping issues when constructing the url in shell. These may be [shell escaping](https://stackoverflow.com/questions/15783701/which-characters-need-to-be-escaped-when-using-bash) issues and [query arg escaping](https://en.wikipedia.org/wiki/Percent-encoding) issues.

**Comment by BeardedShamrock** [comment]
Done! Ty!

**Comment by Davidrjx** [comment]
hi, @valyala, JSON export by /api/v1/export with start and end query args didn't work as expected, nothing returned. is there an working example about url endpoint? my operation in base shell looks like
```
curl http://<vm_ip>:8428/api/v1/export?match=op:cpu_usage%7Bsource=%22op-rl%22,container_name=%22nginx%22%7D -d 'max_rows_per_line=100&start=1632215162762&end=1632217502762'
```

**Comment by dandv** [comment]
@valyala Any plans to support exporting labels in the CSV, i.e. all the time series in a metric?
