### ISSUE TITLE
Add the prometheus process collector to be able to monitor CPU metrics

### ISSUE THREAD

**Issue by krasi-georgiev** [VictoriaMetrics/VictoriaMetrics#92]
https://godoc.org/github.com/prometheus/client_golang/prometheus#NewProcessCollector

Would you consider adding this?

**Comment by valyala** [comment]
Sure, it will be added to [VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) package in the near future.

**Comment by krasi-georgiev** [comment]
CPU usage metric is a must have metric for most application no?
Thanos,Cortex, Prometheus all expose that. Probably Grafana M3 as well.

**Comment by valyala** [comment]
OK, I'll look into lightweight exporting basic CPU usage metrics via [github.com/VictoriaMetrics/metrics](https://github.com/VictoriaMetrics/metrics) package.

**Comment by krasi-georgiev** [comment]
Thanks. 
It was more of a question really. I am not in operations, but would imagine many alerting rules are built around that.
Maybe @superq can comment for that.

**Comment by SuperQ** [comment]
Yes, `process_cpu_seconds_total` is a must for direct instrumentation.

**Comment by valyala** [comment]
FYI, there is also [process_exporter](https://github.com/ncabatoff/process-exporter) that allows monitoring CPU usage, RAM usage, etc. for the selected processes via `/proc`.

**Comment by SuperQ** [comment]
The process exporter is generally discouraged when direct instrumentation is possible. This is why the official Prometheus client_golang includes all of the process_, go_, etc metrics by default.

**Comment by valyala** [comment]
`process_*` metrics have been added in the commit 998525999c4ebf44c5e39d0ace6091b4ed12e58f . They will be available in the next VictoriaMetrics release.

**Comment by krasi-georgiev** [comment]
Thanks

**Comment by valyala** [comment]
FYI, the release [v1.22.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) exposes `process_*` metrics on the `/metrics` page.

**Comment by krasi-georgiev** [comment]
Thanks!
it might be worth adding another version of the grafana dashboard that includes these.
https://grafana.com/grafana/dashboards/10229

I think @bbrazil's dashboard use few of these so can borrow it from there.
https://grafana.com/grafana/dashboards/9761

**Comment by valyala** [comment]
@hagen1778 , could you add cpu usage graph based on `process_cpu_seconds_total` to the official VictoriaMetrics dashboard?

**Comment by krasi-georgiev** [comment]
From what I see the grafana dashboards should be versioned so that people with VM versions prior to v1.22.2  don't see empty graphs.

**Comment by hagen1778** [comment]
Hi @krasi-georgiev! I've added CPU panel to our [Grafana dashboard](https://grafana.com/grafana/dashboards/10229) and put version into description so revisions contain required version now. Thanks for the hint!
