### ISSUE TITLE
Support S3 bucket as vmalert rules source

### ISSUE THREAD

**Issue by shedimonG** [VictoriaMetrics/VictoriaMetrics#926]
**Is your feature request related to a problem? Please describe.**
Configuring single source fo truth for a fleet of vmalerts require sidecars that acquire yaml files from the source of truth and reload configuration

**Describe the solution you'd like**
An ability to configure rule as a remote destination, such as an S3 bucket, for example `-rule s3://<BUCKET_NAME>/**/*.yml`

**Describe alternatives you've considered**

**Additional context**

**Comment by hagen1778** [comment]
vmalert now can read and reload rules from s3 and gcs in ENT version starting from [1.88.0](https://docs.victoriametrics.com/CHANGELOG.html#v1880)
