### ISSUE TITLE
vmbackup: buggy error message

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#929]
When creating a backup using a wrong auth token like
```
 vmbackup --loggerLevel=INFO --snapshot.createURL='http://localhost:8428/snapshot/create?authKey=wrong+password+not+escaped'
```
vmbackup answer with non.sense like `fatal	VictoriaMetrics/app/vmbackup/main.go:58	invalid character 'r' looking for beginning of value`. It seems, that it expects a json formatted http response body, but the error gets returned a plain text like `remoteAddr: "127.0.0.1:53948"; invalid authKey "wrong password not escaped" ...`.

**Comment by valyala** [comment]
@jelmd , thanks for the bug report! The error message has been improved in the commit b35b3dc043e118ab552401e8040b0c937cd2c4b2 . Now it contains request url and response body. The commit will be included in the next release. In the mean time you can build `vmbackup` from this commit [according to these docs](https://victoriametrics.github.io/vmbackup.html#how-to-build-from-sources).

**Comment by jelmd** [comment]
That will fix it. However, it is a little bit misleading, because the real problem is not really JSON parsing but a different error. So kind of "not really clean" error handling. Perhaps it is possible to use something like in https://tools.ietf.org/html/rfc8555#section-6.7 ?

**Comment by valyala** [comment]
@jelmd , thanks for the suggestion!

The commit ca091bade3e101af80c430bbc76cb175c7482135 adds status code verification for responses from snapshot API. Now the error message should be more clear.
