### ISSUE TITLE
Export per-tenant stats in cluster version

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#932]
**Is your feature request related to a problem? Please describe.**

[Cluster version of VictoriaMetrics](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html) supports [multitenancy](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#multitenancy). Unfortunately it doesn't provide per-tenant metrics, which could be useful for per-tenant accounting and usage limits.

**Describe the solution you'd like**
It would be great if cluster version of VictoriaMetrics could provide the following per-tenant metrics:
* The number of ingested samples (this metric already exists - `vm_rows_inserted_total` )
* The number of active time series
* Time series churn rate
* Storage space used
* CPU time spent on query processing
* Ingress and egress network bandwidth used

**Describe alternatives you've considered**
Some of these metrics can be collected by a custom proxy sitting between users and vminsert / vmselect components of the cluster.

**Additional context**
It would be great also if per-tenant usage limits could be enforced according to these metrics. For example, if more than N active time series is ingested for the given tenant, then reject samples for time series exceeding the limit N.

Per-tenant accounting stats must be supported in [enterprise version of VictoriaMetrics](https://victoriametrics.com/enterprise.html).

**Comment by valyala** [comment]
The per-tenant metrics `vm_vmselect_http_requests_total` and `vm_vmselect_http_requests_duration_ms_total` are available in VictoriaMetrics cluster starting from [v1.54.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Other per-tenant metrics will be available in [enterprise package](https://victoriametrics.com/enterprise.html).

**Comment by valyala** [comment]
FYI, per-tenant metrics have been renamed starting from [v1.57.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases):

* `vm_rows_inserted_total` -> `vm_tenant_inserted_rows_total`
* `vm_vmselect_http_requests_total` -> `vm_tenant_select_requests_total`
* `vm_vmselect_http_requests_duration_ms_total` -> `vm_tenant_select_requests_duration_ms_total`

The following additional per-tenant metrics are available in [enterprise package](https://victoriametrics.com/enterprise.html) starting from `v1.57.0`:

* `vm_tenant_timeseries_created_total` - per-tenant series churn rate.
* `vm_tenant_active_timeseries` - per-tenant number of active time series.

**Comment by syepes** [comment]
@valyala One thing that would have been interesting and that was useful was to keep the **type** label on (vm_rows_inserted_total -> vm_tenant_inserted_rows_total), it permitted to know the distribution by protocol

**Comment by valyala** [comment]
> One thing that would have been interesting and that was useful was to keep the type label on (vm_rows_inserted_total -> vm_tenant_inserted_rows_total), it permitted to know the distribution by protocol

Agreed. The `vm_tenant_inserted_rows_total` metric will gain `type` label in the next release.

**Comment by valyala** [comment]
The `type` label has been added to `vm_tenant_inserted_rows_total` metric starting from [v1.57.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by guinguo** [comment]
Does `vm_tenant_timeseries_created_total` can use in Cluster version?  
Because i want to see how many timeseries in different account

**Comment by valyala** [comment]
> Does vm_tenant_timeseries_created_total can use in Cluster version?

The `vm_tenant_timeseries_created_total` metric is available in [enteprise version of VictoriaMetrics cluster](https://docs.victoriametrics.com/enterprise/). See also [vmgateway](https://docs.victoriametrics.com/vmgateway/), which uses these metrics for rate limiting.

Closing this feature request as complete.
