### ISSUE TITLE
Active time series suddenly drops to 0 while data points ingestion rate keeps working

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/VictoriaMetrics#935]
**Describe the bug**
I dont think its actually a bug so this is more of a question. I have a prometheus that uses remote_write into VM - cluster.
Everything worked fine then suddenly the active time series dropped to 0 and all the queries return empty data. The vmstorage barley used any resources from its allocated capacity and no pods have stopped working (vminsert and vmstorage are all showing status running in EKS). I can query the data in the prometheus that does the remote write just fine, so the data itself is ok.

**To Reproduce**
I just sent a lot of data from prometheus (around 2m active time series) with 2 vmstorage machines that are 16GB of RAM and 2 CPU cores, and 7 vminserts machines with 1GB of RAM and 0.5 CPU cores

**Expected behavior**
I would expect to see VM continue working great as it was before, or at least show errors somehow to make me understand what is going on

**Screenshots**
Here is the sudden drop of active time series to 0
<img width="1360" alt="Screen Shot 2020-12-01 at 20 27 45" src="https://user-images.githubusercontent.com/7746785/100781485-c6d80180-3413-11eb-89b5-aa540d2570e7.png">

Nothing special with vm resources usage
<img width="1363" alt="Screen Shot 2020-12-01 at 20 28 17" src="https://user-images.githubusercontent.com/7746785/100781544-d7887780-3413-11eb-852b-128fb8f936f7.png">

**Version**
v1.46.0 

Any idea what could cause this behaviour or what should I do to resolve this?
Thanks!

**Comment by valyala** [comment]
@Alon-Katz , could you share other graphs from [Grafana dashboard for VictoriaMetrics cluster](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#monitoring)? Could you also check for errors in logs for `vminsert` and `vmstorage` components?

cc'ing @hagen1778 , the author of Grafana dashboards for VictoriaMetrics, in the hope he could help debugging this issue.

**Comment by hagen1778** [comment]
The query for panel "Active time series" is the following:
```
sum(vm_cache_entries{job=~"$job", instance=~"$instance.*", type="storage/hour_metric_ids"})
```
I wonder if it is connected somehow with per-hour index for series @valyala.
@Alon-Katz could you pls provide screenshot for the following query `vm_cache_entries` in Grafana's Explore mode for the same time period?

**Comment by Alon-Katz** [comment]
Hey, sorry for the delay.
I wanted to let you know that I managed to solve this issue by following the queue_config you provided for promethues:
```
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30
```
But I still dont understand why when the prometheus had the default config then VM would have 0 active time series

@hagen1778 here is the results for vm_cache_entries for the same time period:
<img width="1365" alt="Screen Shot 2020-12-03 at 19 50 56" src="https://user-images.githubusercontent.com/7746785/101068067-f8320800-35a0-11eb-9202-b23c15ec2a56.png">

@valyala Here is a full view of the graphs in grafana for the same time period (if I missed anything or you require more information let me know):
<img width="1357" alt="Screen Shot 2020-12-03 at 19 52 43" src="https://user-images.githubusercontent.com/7746785/101068405-61198000-35a1-11eb-8f81-ccb19caa56a8.png">
<img width="1366" alt="Screen Shot 2020-12-03 at 19 53 04" src="https://user-images.githubusercontent.com/7746785/101068421-64ad0700-35a1-11eb-96c1-9ffccc5c77bf.png">
<img width="1368" alt="Screen Shot 2020-12-03 at 19 53 20" src="https://user-images.githubusercontent.com/7746785/101068424-65459d80-35a1-11eb-9178-0fe722ae5939.png">
<img width="1366" alt="Screen Shot 2020-12-03 at 19 53 53" src="https://user-images.githubusercontent.com/7746785/101068426-65de3400-35a1-11eb-8d4f-0b6c7f0727f8.png">
<img width="1364" alt="Screen Shot 2020-12-03 at 19 54 05" src="https://user-images.githubusercontent.com/7746785/101068427-6676ca80-35a1-11eb-84f3-47ab632c07a4.png">
<img width="1369" alt="Screen Shot 2020-12-03 at 19 54 12" src="https://user-images.githubusercontent.com/7746785/101068430-670f6100-35a1-11eb-9247-94b9a66912f8.png">
<img width="1369" alt="Screen Shot 2020-12-03 at 19 54 26" src="https://user-images.githubusercontent.com/7746785/101068432-67a7f780-35a1-11eb-9706-311d1c5060ed.png">

**Comment by valyala** [comment]
The `logging rate` graph looks suspicious - it should contain lines with values close to zero. In your case there are more than 1K info messages per second. @Alon-Katz , could you look into logs for VictoriaMetrics components and share a sample of these logs here?

**Comment by Alon-Katz** [comment]
Sure here are the top logs of each vm resource (vmstorage,vminsert,vmselect) (its from now but the dashboard in grafana is still showing around 1k message each second):

**VMSTORAGE:** (Looks like all of the 1k logs are coming from vmstorage)

> {"ts":"2020-12-06T18:37:44.771Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42750"}
> {"ts":"2020-12-06T18:37:44.771Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41022"}
> {"ts":"2020-12-06T18:37:44.772Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42754"}
> {"ts":"2020-12-06T18:37:44.773Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41026"}
> {"ts":"2020-12-06T18:37:44.773Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42758"}
> {"ts":"2020-12-06T18:37:44.774Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41030"}
> {"ts":"2020-12-06T18:37:44.774Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42764"}
> {"ts":"2020-12-06T18:37:44.775Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41036"}
> {"ts":"2020-12-06T18:37:44.775Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42768"}
> {"ts":"2020-12-06T18:37:44.775Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41040"}
> {"ts":"2020-12-06T18:37:44.776Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42772"}
> {"ts":"2020-12-06T18:37:44.776Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41044"}
> {"ts":"2020-12-06T18:37:44.776Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42776"}
> {"ts":"2020-12-06T18:37:44.777Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41048"}
> {"ts":"2020-12-06T18:37:44.777Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:133","msg":"accepted vminsert conn from 10.0.169.211:42780"}
> {"ts":"2020-12-06T18:37:44.777Z","level":"info","caller":"VictoriaMetrics/app/vmstorage/transport/server.go:200","msg":"accepted vmselect conn from 10.0.169.211:41052"}

**VMINSERT** (last log is from 15/11 so I think there was no issue here):

> {"ts":"2020-11-15T13:13:51.459Z","level":"warn","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:205","msg":"cannot dial storageNode \"vm-victoria-metrics-cluster-vmstorage-0.vm-victoria-metrics-cluster-vmstorage.vm.svc.cluster.local:8400\": dial tcp4: i/o timeout"}
> {"ts":"2020-11-15T13:13:51.459Z","level":"warn","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:205","msg":"cannot dial storageNode \"vm-victoria-metrics-cluster-vmstorage-1.vm-victoria-metrics-cluster-vmstorage.vm.svc.cluster.local:8400\": dial tcp4: i/o timeout"}
> {"ts":"2020-11-15T13:14:14.555Z","level":"info","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:209","msg":"successfully dialed -storageNode=\"vm-victoria-metrics-cluster-vmstorage-0.vm-victoria-metrics-cluster-vmstorage.vm.svc.cluster.local:8400\""}
> {"ts":"2020-11-15T13:14:15.151Z","level":"info","caller":"VictoriaMetrics/app/vminsert/netstorage/netstorage.go:209","msg":"successfully dialed -storageNode=\"vm-victoria-metrics-cluster-vmstorage-1.vm-victoria-metrics-cluster-vmstorage.vm.svc.cluster.local:8400\""}

**VMSELECT**

> {"ts":"2020-12-02T10:57:50.125Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/promql/exec.go:29","msg":"slow query according to -search.logSlowQueryDuration=5s: duration=19.568 seconds, start=1606816800, end=1606903200, step=3600, accountID=3979676418, projectID=0, query=\"topk(5, container_cpu_usage_seconds_total)\""}
> {"ts":"2020-12-02T10:57:54.791Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/promql/exec.go:29","msg":"slow query according to -search.logSlowQueryDuration=5s: duration=11.466 seconds, start=1606820220, end=1606906620, step=60, accountID=3979676418, projectID=0, query=\"topk(5, container_cpu_usage_seconds_total)\""}
> {"ts":"2020-12-02T10:57:54.791Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:379","msg":"error in \"/select/3979676418/prometheus/api/v1/query_range?query=topk(5%2C%20container_cpu_usage_seconds_total)&start=1606820220&end=1606906620&step=60\": error when executing query=\"topk(5, container_cpu_usage_seconds_total)\" on the time range (start=1606820220000, end=1606906620000, step=60000): cannot execute query: cannot evaluate \"container_cpu_usage_seconds_total\": not enough memory for processing 96832318 data points across 67198 time series with 1441 points in each time series; total available memory for concurrent requests: 161061273 bytes; possible solutions are: reducing the number of matching time series; switching to node with more RAM; increasing -memory.allowedPercent; increasing `step` query arg (60s)"}
> {"ts":"2020-12-02T10:58:10.334Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/promql/exec.go:29","msg":"slow query according to -search.logSlowQueryDuration=5s: duration=19.519 seconds, start=1606816800, end=1606903200, step=3600, accountID=3979676418, projectID=0, query=\"topk(5, container_cpu_usage_seconds_total)\""}

Let me know if I can provide more details.

**Comment by hagen1778** [comment]
The logs looks ok. @Alon-Katz do you still observer the behavior you mentioned in the issue?

**Comment by hagen1778** [comment]
Closing the issue as stale.
