### ISSUE TITLE
Feature: add `pure Go` build mode

### ISSUE THREAD

**Issue by valyala** [VictoriaMetrics/VictoriaMetrics#94]
### The issue

VictoriaMetrics build requires `cgo`, since it uses [valyala/gozstd](https://github.com/valyala/gozstd) wrapper for the [upstream zstd library](https://github.com/facebook/zstd) written in C. This complicates build process, especially for cross-compliation - it requires C compiler toolchain for the target architecture additionally to Go.

### The solution

To add ability to use pure Go implementation for zstd - [github.com/klauspost/compress/tree/master/zstd](https://github.com/klauspost/compress/tree/master/zstd). This will simplify cross-compilation builds for various GOOS/GOARCH combinations.

See [this thread on golang-nuts](https://groups.google.com/d/msg/golang-nuts/onlD1GIG00g/MZA0tLgJCQAJ) for more details.

**Comment by valyala** [comment]
`pure Go` build mode with https://github.com/klauspost/compress/tree/master/zstd has been implemented. It provides slightly lower compression ratio and slightly lower decompression performance comparing to `cgo`. See [instructions on how to create GCO_ENABED=0 builds for VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#pure-go-cgo_enabled0).

The `pure Go` mode may become default in the future when it will gain better compression ratio comparable to the [gozstd](https://github.com/valyala/gozstd).

**Comment by valyala** [comment]
@klauspost, is it possible to remove the allocation [here](https://github.com/klauspost/compress/blob/415e5345507ece8609410be3d156d0e37e70b3b6/zstd/decoder.go#L292)? It looks like this allocation reduces the decompression speed for small blocks.

**Comment by klauspost** [comment]
@valyala 40 bytes per block? ok - I will take a look.

**Comment by klauspost** [comment]
@valyala Added here: https://github.com/klauspost/compress/pull/142

Seems quite harmless so I will probably merge it later today.
