### ISSUE TITLE
Using VictoriaMetrics as complete Prometheus replacement?

### ISSUE THREAD

**Issue by n9** [VictoriaMetrics/VictoriaMetrics#947]
Especially after hitting https://github.com/prometheus/prometheus/issues/3746, I am tempted to completely replace Prometheus with VictoriaMetrics. I need **exact** metrics. It seems to be a supported use case, however does not seem to be much promoted yet.

Is it reasonable to get rid of Prometheus? Or are there some missing important parts? What are the reasons to use VictoriaMetrics just as long term storage for metrics collected by Prometheus?

**Comment by valyala** [comment]
VictoriaMetrics components can be used as a complete Prometheus replacement:

* VictoriaMetrics itself replaces Prometheus data storage and [querying engine](https://victoriametrics.github.io/#prometheus-querying-api-usage).
* [vmagent](https://victoriametrics.github.io/vmagent.html) can be used for scraping Prometheus-compatible targets and sending them to VictoriaMetrics (either to a single-node or to [cluster version](https://victoriametrics.github.io/Cluster-VictoriaMetrics.html)) . Single-node VictoriaMetrics has built-in scraper for Prometheus-compatible targets - see [these docs](https://victoriametrics.github.io/#how-to-scrape-prometheus-exporters-such-as-node-exporter).
* [vmalert](https://victoriametrics.github.io/vmalert.html) can be used for processing Prometheus-compatible alerting and recording rules.

**Comment by n9** [comment]
Thank you for your answer. Are there known advantages of using Prometheus/VM combo over VM only?

**Comment by valyala** [comment]
The advantage of using Prometheus + VM combo is that alerting and recording rules are evaluated closer to scraped targets, i.e. at Prometheus side. When using vmagent + vm + vmalert combo, then alerting and recording rules are evaluated at vm side, which is located at one network hop farther than the Prometheus. This may mean reduced reliability when calculating alerting and recording rules.

**Comment by n9** [comment]
Ok, thank you.
