### ISSUE TITLE
Data ingested using the OpenTSDB protocol shows up in export but not in query

### ISSUE THREAD

**Issue by GreatSnoopy** [VictoriaMetrics/VictoriaMetrics#953]
**Describe the bug**
Using VM with the opentsdb protocol, sending batches of data.
When querying the data in grafana or with the query_range api, an empty dataset is obtained.
However, querying either the /series/ shows the metrics that were previously sent
So does using export, we can see series with data that was previously ingested.

**To Reproduce**
Send a batch of metrics in opentsdb format, we use large batches, often 2M
use the query_range, series and export APIs to observe the difference in results

**Expected behavior**
Be able to query the data that was inserted.

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
victoria-metrics-20201205-115122-tags-v1.49.0-0-gae1db8fa0
```

**Used command-line flags**
Command-line flags are listed as `flag{name="httpListenAddr", value=":443"} 1` lines at `/metrics` page.
See the following docs for details:
```
victoria-metrics-prod -storageDataPath=/victoriametrics/data -retentionPeriod=1 -loggerLevel=INFO -promscrape.config=/victoriametrics/config/ps.yaml -search.maxPointsPerTimeseries=200000000 -search.disableCache -opentsdbListenAddr=:4242 -selfScrapeInterval=15s
```

* [monitoring for single-node VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring)
* [montioring for VictoriaMetrics cluster](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/README.md#monitoring)

**Additional context**
Add any other context about the problem here such as error logs from VictoriaMetrics and Prometheus,
`/metrics` output, screenshots from the official Grafana dashboards for VictoriaMetrics:

* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)
* [Grafana dashboard for VictoriaMetrics cluster](https://grafana.com/grafana/dashboards/11176)

**Comment by GreatSnoopy** [comment]
Ok, looks like the issue was that metricsql operates assuming the data follows the prometheus schema and treats dashes in metric name as the minus operator. However, other tsdbs (opentsdb and likely others) consider the dash as a legit character in metric name. So there is a slight ambiguity here as it was not immediately obvious  why the query would not work.
Maybe the "series" api call should return the metrics escaped? Since grafana uses exactly that same api when populating the drop down list with available metrics...

**Comment by valyala** [comment]
The `/api/v1/series` handler cannot return escaped metric names, since this may break other users of this API, who expect plain metric names without escaping. There are other solutions:
* To perform metrics' escaping escaping at Grafana side (at [Prometheus datasource](https://grafana.com/docs/grafana/latest/datasources/prometheus/) level).
* To pass `escape_metric_names=1` query arg to `/api/v1/series` in order to escape metric names returned from `/api/v1/series`.

There are also `/api/v1/labels` and `/api/v1/label/__name__/values` handlers, which also should be aware of metric names' escaping and label names' escaping.

**Comment by valyala** [comment]
The issue is related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/424#issuecomment-616240171 .

**Comment by valyala** [comment]
Another option is to replace dashes with underscores in metric names and label names during data ingestion. This can be done via [relabeling](https://victoriametrics.github.io/#relabeling) when using the following `-relabelConfig` file:

```yml
- action: replace_all
  source_labels: [__name__]
  target_label: __name__
  regex: "-"
  replacement: "_"
- action: labelmap_all
  regex: "-"
  replacement: "_"
```

See more details about relabeling tricks at https://valyala.medium.com/how-to-use-relabeling-in-prometheus-and-victoriametrics-8b90fc22c4b2 .
