### ISSUE TITLE
vminsert export metric always be 0 

### ISSUE THREAD

**Issue by xemxx** [VictoriaMetrics/VictoriaMetrics#955]
**Describe the bug**
In the spreadReroutedBufToStorageNodesBlocking func of app/vm insert/netstorage package, the  metric vm_rpc_rerouted_rows_processed_total is exposed, but the defer of golang is used wrong, the variable rowsProcessed will always use the current value of 0  transfer to reroutedRowsProcessed.Add() func。

**Screenshots**
![image](https://user-images.githubusercontent.com/26523062/101858443-937c3c00-3ba4-11eb-8e5c-d1683ec7e818.png)

**Version**

vminsert  run command line with flag --version have nothing return, but commit-id is 4804e004f31a27989946bf88779560685684516c

**Comment by valyala** [comment]
@xemxx , thanks for the bug report! The issue should be fixed in the commit 9e79fc27c80326e6a009b70f737c562337612483 . This commit will be included in the next release of VictoriaMetrics.

**Comment by valyala** [comment]
The bugfix has been included in [v1.50.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.
