### ISSUE TITLE
labels lost when use remote_write

### ISSUE THREAD

**Issue by wangqiongkaka** [VictoriaMetrics/VictoriaMetrics#957]
**Describe the bug**
query from prometheus
kube_node_labels{cluster="wuxi-buss",instance="10.211.14.78:8080",job="kube-state-metrics",label_CPU_CAP="24",label_MEM_CAP="128GB",label_NIC_CAP="10000M",label_PREENV="HOSTENVTYPE",label_PRODENV="HOSTENVTYPE",label_ROOM_ID="12472",label_SERVER_ID="23635",label_TESTENV="HOSTENVTYPE",label_beta_kubernetes_io_arch="amd64",label_beta_kubernetes_io_os="linux",label_biz_type="storage",label_hostname="wuxi-buss-v1-4.3-10.26.134.176",label_ingress_role="internal",label_ip="10.26.134.176",label_kubernetes_io_arch="amd64",label_kubernetes_io_hostname="wuxi-buss-v1-4.3-10-26-134-176",label_kubernetes_io_os="linux",label_node_role_kubernetes_io_CPU_24="true",label_node_role_kubernetes_io_DISK_845G="true",label_node_role_kubernetes_io_MEM_128_GB="true",label_node_role_kubernetes_io_NIC_10000M="true",label_node_role_kubernetes_io_WorkerNode="true",label_node_role_kubernetes_io_ingress="true",label_node_role_kubernetes_io_storage="true",label_retention_base_dir="data",label_room="wuxi-buss",label_type="v1-4.3",namespace="arms-prom",node="wuxi-buss-v1-4.3-10-26-134-176",pod="kube-state-metrics-6c6d79f8c8-gtxxn",pod_name="kube-state-metrics-6c6d79f8c8-gtxxn",prometheus="default/prometheus"}

query from victoriametrics
kube_node_labels{cluster="wuxi-buss", instance="10.211.14.78:8080", job="kube-state-metrics", label_CPU_CAP="24", label_MEM_CAP="128GB", label_NIC_CAP="10000M", label_PREENV="HOSTENVTYPE", label_PRODENV="HOSTENVTYPE", label_ROOM_ID="12472", label_SERVER_ID="23635", label_TESTENV="HOSTENVTYPE", label_beta_kubernetes_io_arch="amd64", label_beta_kubernetes_io_os="linux", label_biz_type="storage", label_hostname="wuxi-buss-v1-4.3-10.26.134.176", label_ingress_role="internal", label_ip="10.26.134.176", label_kubernetes_io_arch="amd64", label_kubernetes_io_hostname="wuxi-buss-v1-4.3-10-26-134-176", label_kubernetes_io_os="linux", label_node_role_kubernetes_io_CPU_24="true", label_node_role_kubernetes_io_DISK_845G="true", label_node_role_kubernetes_io_MEM_128_GB="true", label_node_role_kubernetes_io_NIC_10000M="true", label_node_role_kubernetes_io_WorkerNode="true", label_node_role_kubernetes_io_ingress="true", label_node_role_kubernetes_io_storage="true", label_retention_base_dir="data", label_room="wuxi-buss"}

some labels lost such as node pod and so on

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
victoria-metrics-20201205-115122-tags-v1.49.0-0-gae1db8fa0
```

**Used command-line flags**
Command-line flags are listed as `flag{name="httpListenAddr", value=":443"} 1` lines at `/metrics` page.
See the following docs for details:

* [monitoring for single-node VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#monitoring)

**Additional context**
Add any other context about the problem here such as error logs from VictoriaMetrics and Prometheus,
`/metrics` output, screenshots from the official Grafana dashboards for VictoriaMetrics:

* [Grafana dashboard for single-node VictoriaMetrics](https://grafana.com/dashboards/10229)

**Comment by valyala** [comment]
It looks like you hit the limit on the number of labels per metric. It is set to 30 by default. The limit can be changed via `-maxLabelsPerTimeseries` command-line flag. See https://victoriametrics.github.io/#troubleshooting for more details.

BTW, could you share more details for your use case on why it needs so many labels per metric?

**Comment by wangqiongkaka** [comment]
> 
> 
> It looks like you hit the limit on the number of labels per metric. It is set to 30 by default. The limit can be changed via `-maxLabelsPerTimeseries` command-line flag. See https://victoriametrics.github.io/#troubleshooting for more details.
> 
> BTW, could you share more details for your use case on why it needs so many labels per metric?

Problem solved, we don't necessarily need so many labels, I just need the node labels, but this one is at the end, thanks very much
