### ISSUE TITLE
Question: Trying to export data via /export/csv

### ISSUE THREAD

**Issue by rkelltel** [VictoriaMetrics/VictoriaMetrics#969]
I've got the following issue with version victoria-metrics-20201205-115036-tags-v1.49.0-0-gae1db8fa0:
Importing successful data:

`curl -v -X POST --data 'power{vpsz="49",aid="CH-1-1-N"} 1.0 1608033794793' localhost:8428/api/v1/import/prometheus`

Executing:
`curl -G --data-urlencode 'format=1:time:rfc3339,2:metric:power,3:label:vpsz,4:label:aid' --data-urlencode 'match[]={__name__!=""}' localhost:8428/api/v1/export/csv`
And only receiving `,,,,`
When i am exporting it as JSON it works:
`curl http://localhost:8428/api/v1/export -d match[]={__name__!=""}`
Result:
`{
    "metric": {
        "__name__": "power",
        "aid": "CH-1-1-N",
        "vpsz": "49"
    },
    "values": [
        1
    ],
    "timestamps": [
        1608033794793
    ]
}`

Please help to find my issue with the csv export. Thanks in advance!

**Comment by valyala** [comment]
The `format` query arg must contain the following value: `__timestamp__:rfc3339,__value__,vpsz,aid` according to [the docs on CSV export](https://victoriametrics.github.io/#how-to-export-csv-data):

```
curl http://localhost:8428/api/v1/export/csv -d 'match[]=power' -d 'format=__timestamp__:rfc3339,__value__,vpsz,aid'
2020-12-15T14:03:14+02:00,1,49,CH-1-1-N
```

**Comment by rkelltel** [comment]
Thank you for the very fast reply. It was an obvious mistake...sorry
