### ISSUE TITLE
Latest vmutils build (1.50.1) contains an old build of vmagent-prod

### ISSUE THREAD

**Issue by opensourcebear** [VictoriaMetrics/VictoriaMetrics#973]
After downloading and verifying the checksum for vmutils-v1.50.1.tar.gz
When I unpack the file, the date on the vmagent-prod file is Dec 3, not Dec 15 the release data.

I have deleted all files and re-downloaded and re untarred to verify I didn't make a mistake.

Running this binary with -version gives this output:
`./vmagent-prod -version`
`vmagent-20201203-094637-heads-adds-query-stats-0-gff3fd46c1`

I was looking forward to the html view in vmagent, but I guess I'll wait ;)

**Comment by f41gh7** [comment]
Sorry, local copy of vmagent broke make script during release. I've rebuilt it and upload new version.

**Comment by opensourcebear** [comment]
I grabbed the update and it looks good now.  Thank you
