### ISSUE TITLE
Discrepancy between export-confirmed data and query_range output

### ISSUE THREAD

**Issue by akira-kurogane** [VictoriaMetrics/VictoriaMetrics#977]
**Description**
/api/v1/query_range returns results with gaps at random times. Data is confirmed to exist in victoriametrics when checked with /api/v1/export.

**Reproduction**
I have imported some metrics where, in pre-processing, I removed intermediate duplicate values.

I import
`{"metric":{"__name__":"nongodb_oplog_stats_avgObjSize","job":"mongodb","instance":"mongoqa-sa03:27018","cl_role":"shardsvr","rs_nm":"mongoqa-s03","rs_state":"1"},"values":[131,264,264,250,250,238,238,228,228,220,220,213],"timestamps":[1584028482000,1584028483000,1584028497000,1584028498000,1584028507000,1584028508000,1584028517000,1584028518000,1584028527000,1584028528000,1584028537000,1584028538000]}`

Using the /api/v1/export endpoint I confirm the data comes out (in jsonline format) exactly the same as imported, but when using /api/v1/query_range I find random gaps in the output.

**Expected behavior**
I expect that if I run /api/v1/query_range with a step=1s argument that I can get continuous data samples through this time.

Eg. [1584028482, 131], [1584028483, 264],  [1584028484, 264],  [1584028485, 264], .... <continuous per-second data points> ...   [1584028497, 264], [1584028498, 250], ...

What is happening instead is that some times the datapoints are absent. E.g. in the range of time where 264 is the value for the nongodb_oplog_stats_avgObjSize{...,"instance":"mongoqa-sa03:27018",...,"rs_state":"1"} metric I get results for seconds 1584028483 to 1584028492; seconds 1584028493 to 1584028497 are missing, then second 1584028498 is set.

Another error is that datapoint for 1584028498 should be the next value (250) but it is 264. Only from 1584028499 does the value become 250.

**Differential test case**
If I import the data show below, i.e. with every second included, the gap issue does not occur in the /api/v1/query_range output.

I.e. if I import this:
`{"metric":{"__name__":"qongodb_oplog_stats_avgObjSize","job":"mongodb","instance":"mongoqa-sa03:27018","cl_role":"shardsvr","rs_nm":"mongoqa-s03","rs_state":"1"},"values":[131,131,131,264,264,264,264,264,264,264,264,264,264,264,264,264,264,264,250,250,250,250,250,250,250,250,250,250,238,238,238,238,238,238,238,238,238,238,228,228,228,228,228,228,228,228,228,228,220,220,220,220,220,220,220,220,220,220,213,213,213],"timestamps":[1584028480000,1584028481000,1584028482000,1584028483000,1584028484000,1584028485000,1584028486000,1584028487000,1584028488000,1584028489000,1584028490000,1584028491000,1584028492000,1584028493000,1584028494000,1584028495000,1584028496000,1584028497000,1584028498000,1584028499000,1584028500000,1584028501000,1584028502000,1584028503000,1584028504000,1584028505000,1584028506000,1584028507000,1584028508000,1584028509000,1584028510000,1584028511000,1584028512000,1584028513000,1584028514000,1584028515000,1584028516000,1584028517000,1584028518000,1584028519000,1584028520000,1584028521000,1584028522000,1584028523000,1584028524000,1584028525000,1584028526000,1584028527000,1584028528000,1584028529000,1584028530000,1584028531000,1584028532000,1584028533000,1584028534000,1584028535000,1584028536000,1584028537000,1584028538000,1584028539000,1584028540000]}`

Then query_range?step=1s will return the value 264 for every second from 1584028483 - 1584028497, and from 1584028498 it is value 250.

**Version**
victoria-metrics-20201126-161316-pmm-6401-v1.48.0

**Used command-line flags**
`promscrape.config=/etc/victoriametrics-promscrape.yml --retentionPeriod=366d --storageDataPath=/srv/victoriametrics/data --httpListenAddr=127.0.0.1:9090 --search.disableCache=true --search.maxQueryLen=72KB --search.maxUniqueTimeseries=1500000 --prometheusDataPath=/srv/prometheus/data --http.pathPrefix=/prometheus`

**Comment by akira-kurogane** [comment]
To demonstrate visually this is what you can see after graphing in grafana. The `*ongodb_oplog_stats_avgObjSize` metric data shown above is the green graph. The left hand side is when I import the data with duplicates; the right hand is when I remove duplicates.
![nongo_qongo_gaps](https://user-images.githubusercontent.com/2595590/102839110-1cb42e00-4443-11eb-83ad-3df0c6a926ee.png)

Data served from /api/vi/export.
"nongodb_*" name was used for data with intermediate duplicates removed before importing.
```
{"metric":{"__name__":"nongodb_oplog_stats_avgObjSize","job":"mongodb","instance":"mongoqa-sa03:27018","cl_role":"shardsvr","rs_nm":"mongoqa-s03","rs_state":"1"},"values":[131,264,264,250,250,238,238,228,228,220,220,213],"timestamps":[1584028482000,1584028483000,1584028497000,1584028498000,1584028507000,1584028508000,1584028517000,1584028518000,1584028527000,1584028528000,1584028537000,1584028538000]}
```
"qongodb_*" name was used for data imported with no removal of intermediate duplicates.
```
{"metric":{"__name__":"qongodb_oplog_stats_avgObjSize","job":"mongodb","instance":"mongoqa-sa03:27018","cl_role":"shardsvr","rs_nm":"mongoqa-s03","rs_state":"1"},"values":[131,131,131,264,264,264,264,264,264,264,264,264,264,264,264,264,264,264,250,250,250,250,250,250,250,250,250,250,238,238,238,238,238,238,238,238,238,238,228,228,228,228,228,228,228,228,228,228,220,220,220,220,220,220,220,220,220,220,213,213,213],"timestamps":[1584028480000,1584028481000,1584028482000,1584028483000,1584028484000,1584028485000,1584028486000,1584028487000,1584028488000,1584028489000,1584028490000,1584028491000,1584028492000,1584028493000,1584028494000,1584028495000,1584028496000,1584028497000,1584028498000,1584028499000,1584028500000,1584028501000,1584028502000,1584028503000,1584028504000,1584028505000,1584028506000,1584028507000,1584028508000,1584028509000,1584028510000,1584028511000,1584028512000,1584028513000,1584028514000,1584028515000,1584028516000,1584028517000,1584028518000,1584028519000,1584028520000,1584028521000,1584028522000,1584028523000,1584028524000,1584028525000,1584028526000,1584028527000,1584028528000,1584028529000,1584028530000,1584028531000,1584028532000,1584028533000,1584028534000,1584028535000,1584028536000,1584028537000,1584028538000,1584028539000,1584028540000]}
```

**Comment by valyala** [comment]
VictoriaMetrics detects the median interval between data points in a time series and then fills gaps with the duration up to 2x of the detected interval. This detection works the best when the duration between data points is close to constant. It is named [scrape_interval](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file) in Prometheus world. It looks like VictoriaMetrics couldn't detect the expected scrape interval for the imported time series, since it is irregular:

> {"metric":{"__name__":"nongodb_oplog_stats_avgObjSize","job":"mongodb","instance":"mongoqa-sa03:27018","cl_role":"shardsvr","rs_nm":"mongoqa-s03","rs_state":"1"},"values":[131,264,264,250,250,238,238,228,228,220,220,213],"timestamps":[1584028482000,1584028483000,1584028497000,1584028498000,1584028507000,1584028508000,1584028517000,1584028518000,1584028527000,1584028528000,1584028537000,1584028538000]}

For instance, the interval between the first two data points is `1584028483000ms - 1584028482000ms = 1s`, while the interval between the second and the third data point is `1584028497000ms - 1584028483000ms = 14s`. There are the following workarounds for this issue:

* To fix data source, so it sends samples to VictoriaMetrics at regular intervals.
* To pass `-dedup.minScrapeInterval=<the_largest_interval_between_samples>` command-line flag to VictoriaMetrics, so it leaves only a sample per interval. See [these docs](https://victoriametrics.github.io/#deduplication) for details.
* To pass `-search.minStalenessInterval=<the_largest_interval_between_samples>` command-line flag to VictoriaMetrics, so it fills gaps smaller than the configured value. See [these docs](https://victoriametrics.github.io/#troubleshooting) for details.

**Comment by akira-kurogane** [comment]
Thanks for explanation Aliaksandr.

> VictoriaMetrics detects the median interval between data points in a time series and then fills gaps with the duration up to 2x of the detected interval.

The scrape and staleness interval options workarounds sound as though they can't be useful here, due to the variability of interval when intermediate duplicates are removed. In the metrics of a single file being uploaded some are effectively constants (i.e. constant for weeks or months); some change once per minute; some of them vary every second.

If the /api/v1/import's function had a mode where I could specify what the gap-fill interval should be (rather than it being estimated) I could upload my deliberately-deduplicated jsonlines data without suffering the side effects of the median-interval-guess issue.

Eg. as a per-metric-line option:
`{"metric":{"name":....},"values":[...],"timestamps":[],"extrapolate_duplicates_interval":1000/*ms*/}`

or file-level option:
`/api/v1/import?.....&extrapolate_duplicates_interval=1s`

Or maybe the jsonline object could be datapoints with optional repeat and interval values eg.
`{"metric":{"name":.... other-labels...},"datapoints":[[1584028482000,131],[1584028483000,264,9/*extra repeats*/,1000/*ms interval of repeats*/],[1584028498000,250,9,1000],[1584028507,238,11,1000],...,...]}`

For me, now, all of this is only to achieve one thing. That is to make upload files smaller, and thus A) avoid running out of disk space on your laptop/desktop and B) reduce the number of curl post commands my end users would have to do to upload the mongodb diagnostic info. The reason "A" happens is because the original diagnostic data source file I generate the jsonlines file from has a very good, lossless compression format. Typically 150MB of those files are available for the average mongod server, and they become ~x100 times larger if expanded into a full representation (c struct style). And JSON format makes it about twice as large again, i.e. 150MB becomes 30GB.

I can workaround this. I could program my conversion tool to interact with the /api/v1/import endpoint directly in HTTP requests, but what I'll probably do is just tell my users to dump the intermediate jsonline file to a disk drive with a lot of space, plus show them a script that cuts the files up into small enough pieces and submits them via curl -X post commands.

So I wouldn't argue this should be top priority feature request.

**Comment by akira-kurogane** [comment]
A new thought: can I trick victoriametrics, as it currently is, into thinking the interval is 1s if I write, say, the first 10s of each line at full resolution then deduplicate after that?

Eg. in my samples above write datapoints for every second 1584028482 to 1584028491, then from 1584028492 onwards remove intermediate duplicates as I already experimented with.

**Comment by valyala** [comment]
> can I trick victoriametrics, as it currently is, into thinking the interval is 1s if I write, say, the first 10 seconds of each line at 1s resolution and only do deduplication for timestamps after that?

I don't think this is good idea, since it is too custom for a particular use case and it may complicate the understanding of data import in VictoriaMetrics. It is better performing the needed transformations (e.g. adding missing samples on the fly by an intermediate script) before importing the data into VictoriaMetrics.

There is yet another workaround - to wrap the selected metric name into `last_over_time()` function. For example, `last_over_time(nongodb_oplog_stats_avgObjSize[10s])`. The `[10s]` means that for each point on the graph VictoriaMetrics will return the last raw sample value on 10s time window ending at the given point.
