### ISSUE TITLE
prometheus high availability when use cluster version

### ISSUE THREAD

**Issue by overstep123** [VictoriaMetrics/VictoriaMetrics#981]
When I use the cluster version VM,I can set up multi vminsert and multi vmselect,so that they are high available.I can also use data replication,so that I can get correct data when a vmstorage node down.But the problem is how I make prometheus high available? When the prometheus node down,how can I make data available? I just want to use two HA pairs,but it seems like that I have to set up two VM cluster or use different account of one VM cluster(this means the cluster will have at least four(2*2) replication of data!). Is there any other way？

**Comment by f41gh7** [comment]
You can enable data deduplication with flags for vmselect and vmstorage `-dedup.minScrapeInterval=30s` according to your scrape interval at prometheus side. Then setup two prometheus instances with **the same external labels** and provide same url for remote write setting. It must point to vminsert instance. 

 Check more at this docs https://victoriametrics.github.io/Single-server-VictoriaMetrics.html#deduplication

**Comment by overstep123** [comment]
> You can enable data deduplication with flags for vmselect and vmstorage `-dedup.minScrapeInterval=30s` according to your scrape interval at prometheus side. Then setup two prometheus instances with **the same external labels** and provide same url for remote write setting. It must point to vminsert instance.
> 
> Check more at this docs https://victoriametrics.github.io/Single-server-VictoriaMetrics.html#deduplication

It doesn't resolve the problem. There are still at least four replication of data in this way(I can't ensure that the data of two prometheus instance is insert into  distinct vmstorage node,so enable replication in vminsert is still necessary).

**Comment by overstep123** [comment]
Maybe I can config distinct vminsert with distinct vmstorage node for prometheus instance. But it looks like not a cluster in this way. I need to add two vmstorage node at once if I want to resize.

**Comment by denisgolius** [comment]
Closing the issue due to inactivity. @overstep123 , feel free re-opening it or creating new one with additional details if you feel that the issue isn't resolved yet.
