### ISSUE TITLE
Question: Continuous Aggregates

### ISSUE THREAD

**Issue by stefan-fast** [VictoriaMetrics/VictoriaMetrics#988]
**Question**
Is it possible to configure and use Continuous Aggregates like in InfluxDB and TimescaleDB?
If not, are there any plans on adding such a feature?

**Use case**
So far I've used InfluxDB to achieve aggregation of application statistics by creating different retention policies that the aggregates are stored to. There are two continuous aggregations, one for summing values per hour and one for summing values per day (using the per hour values). The per hour values have a retention of two weeks while the per day values have an infinite retention (for now). This is used to have minimal disk storage requirements while still being able to store and lookup aggregated application statistics of days from months or even years ago.
I'd like to do something similar with VictoriaMetrics if possible :)

**Comment by f41gh7** [comment]
You should check `recording rules` at vmalert docs, https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmalert#rules , https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/   it should cover your needs in case of aggregation.

  But atm its not possible  to apply custom retention per metric, only for whole database.  As a workaround, you can setup multiple vmdb instances and apply chain recording rule.  Something like : vmdb1 <- vmalert1 record 1 hour -> vmdb2 <- vmalert 2 record 1 day -> vmdb3

 And maybe you don't need it, because VictoriaMetrics has good compression rate and it stores data very efficient.

**Comment by stefan-fast** [comment]
Thank you for the input! I'll check it out and see what I can do, it seems to be promising :)
As for retention: I think this use case would also profit from #289 .

**Comment by stefan-fast** [comment]
@f41gh7 I've looked into this and your suggested solution by using recording rules. While the recording rules seemed to be promising at first, they may not have the ability to do what I need and other time-series databases like InfluxDB and TimescaleDB are able to do (e.g. https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates ). I need to aggregate metrics by full hour (and full day) time buckets just like those two mentioned platforms can do.

Example: 
- Given: There is a counter metric "download_count_total".
- Needed: There should be an aggregated metric that sums the number of downloads per full hour (and a second one per day but I'll just go with the hour one for the sake of this example).

So, for the time between 10:00 and 11:00 o'clock on some day there should be a single value inside that aggregated metric for the timestamp at 11:00 o'clock that sums the number of downloads in the hour between 10:00 and 11:00 o'clock.
If I'd go about doing this with a recording rule it'd probably look something like this: 
```
sum by (some_label) (increase(download_count_total[60m]))
```
But as far as I could see, there is no way to strictly and reliably execute recording rules every full hour to get those aggregated time buckets. With every execution of the recording rule, I'll just get a data point of "1h ago to now", while "now" is the execution time of the rule.
Also, if for some reason an aggregation is lost or the underlying data changed, it'll never be recalculated (e.g. TimescaleDB will refresh/recalculate aggregates in a configurable time interval if there have been changes to the dataset).

Am I missing something here? Is this kind of data analysis out of scope of VictoriaMetrics or is there any chance it'll receive a feature like that?

If it is out of scope, I guess I could still write the data to TimescaleDB and do it there or write an own little tool that'll query VictoriaMetrics and create those fixed aggeregated time buckets and store them to VictoriaMetrics again :)

**Comment by valyala** [comment]
@hagen1778 , what do you think about adding options to `vmalert` configs similar to `scrape_offset` and `scrape_align_interval` options from `vmagent`? See [vmagent troubleshooting docs](https://victoriametrics.github.io/vmagent.html#troubleshooting) for more details about these options.

**Comment by valyala** [comment]
Closing this issue, since [stream aggregation](https://docs.victoriametrics.com/stream-aggregation/) can be used for this case.
