### ISSUE TITLE
Metrics prefixed with non literals (% € °C) can't be queried

### ISSUE THREAD

**Issue by azhiltsov** [VictoriaMetrics/VictoriaMetrics#990]
**Version:**
victoria-metrics-20201227-122315-tags-v1.51.0-0-g70df5f497

**Started:**
/victoria-metrics-prod --graphiteListenAddr :2003 --retentionPeriod 36 --influxSkipSingleField

**Feeded with influx protocol** from "home assistant" (drop-in replacement for influxdb)

Home assistant sends a fair amount of metrics prefixed with non literals (% € °C)
They are saved in VictoriaMetrics fine, but can't be queried straight away from Grafana.

**Here is the example:**

**Query in Grafana returns error**
`%_Uptime`

**Query inspector:**
```
url:"api/datasources/proxy/1/api/v1/query_range?query=%25_Uptime&start=1609762755&end=1609773555&step=15"
method:"GET"

"error when executing query=\"%_Uptime\" on the time range (start=1609762755000, end=1609773555000, step=15000): cannot execute query: singleExpr: unexpected token \"%\"; want \"(\", \"{\", \"-\", \"+\"; unparsed data: \"%_Uptime\""
```

**The same query from Grafana in different format returns fine.**
`{__name__="%_Uptime"}`

**Query inspector:**
```
url:"api/datasources/proxy/1/api/v1/query_range?query=%7B__name__%3D%22%25_Uptime%22%7D&start=1609762830&end=1609773630&step=15"
method:"GET"
```

**Comment by f41gh7** [comment]
For now, there is workaround with querying metrics by label name, like `{__name__=" %_Uptime"}` 

 Need to think how to better change query lexer, to support additional literals.

**Comment by davidsome** [comment]
if tags name prefixed with non literals (% € °C), how can i query it?

**Comment by f41gh7** [comment]
> if tags name prefixed with non literals (% € °C), how can i query it? @f41gh7 @valyala

  For example, use following query expression  ```rate({__name__="%_Uptime"})``` instead of ```rate(%_Uptime)```

**Comment by davidsome** [comment]
> > if tags name prefixed with non literals (% € °C), how can i query it? @f41gh7 @valyala
> 
> For example, use following query expression `rate({__name__="%_Uptime"})` instead of `rate(%_Uptime)`

I mean  label name， not the metric name

**Comment by f41gh7** [comment]
Atm, its not possible, need to think how to implement it better. There is also feature request for Chinese chars support https://github.com/VictoriaMetrics/metricsql/issues/1
 
 Probably allow quoted label names? Something like: `sum_over_time("%_Uptime"{"host-name%"="host-1"}) ` @valyala  what do you think?

**Comment by valyala** [comment]
I think MetricsQL can allow quoted label names inside label filters, i.e. `{"label"="value"}`. I'm unsure about quoted metric names though, since they may clash with string literals.

**Comment by valyala** [comment]
Added ability to escape any unicode char with backslash in the commit acf1a2c72b05e94668523c84eb7ae70fa03e4297

**Comment by valyala** [comment]
VictoriaMetrics supports escaping any unicode char in metric names, label names and function names with backslash starting from [v1.52.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). For example, the following query is valid now:
```metricsql
\€_price{temperature_\°C="123"}
```
