### ISSUE TITLE
Question:  VMStorage node downtime and impact on replication

### ISSUE THREAD

**Issue by vvutharkar** [VictoriaMetrics/VictoriaMetrics#991]
This issue is more of a question as I could not get the answer in any docs I read so far.

Consider scenario where vmstorage node goes down. Underlying storage volume is highly replicated and there is no data loss. Just the vmstorage node is down and not accepting any incoming inserts. 

What I read is that vminsert nodes will tolerate such failures and redirect the requests to the good vmstorage nodes. Which is good.  Does it mean all the replicated data (say nth copy of data in a N-way replication setup), that was meant to go into the bad/unreachable vmstorage node ends up redirected to one of the other surviving vmstorage nodes.  Now consider after a long downtime, the vmstorage node comes back up, will there be any rebalancing happens to redistrubute the data ?   If not, then over time, due to such downtime of single or a few vmstorage nodes, the replicated data gets distributed in a unbalanced way across the cluster of vmstorage nodes, right?   

Also where/who keeps track of where the 'N' replicas of inserted data are spread out ?  And how is that mapping kept up to date when storage nodes go down and replication gets routed to different set of storage nodes ?  Over time and several down times, that *replication map* could get messy, right?

**Comment by f41gh7** [comment]
>  Now consider after a long downtime, the vmstorage node comes back up, will there be any rebalancing happens to redistrubute the data ? If not, then over time, due to such downtime of single or a few vmstorage nodes, the replicated data gets distributed in a unbalanced way across the cluster of vmstorage nodes, right?

 No, atm there is no rebalancing.  And its possible, that data will be distributed in an unbalanced way. There is feature request for rebalancing and an open issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/188

 

> Also where/who keeps track of where the 'N' replicas of inserted data are spread out ? And how is that mapping kept up to date when storage nodes go down and replication gets routed to different set of storage nodes ? Over time and several down times, that _replication map_ could get messy, right?

 There is no 'N' replicas tracking. Each vminsert is responsible for data distribution, it calculates jump consistent hashing and routes traffic to corresponding vmstorage node. If vmstorage become unhealthy, vminsert writes data to the `next` vmstorage from configured vmstorage addresses array. If vmstorage goes down and there is no enough healthy vmstorage nodes to write data, replicated data will be discarded.

**Comment by valyala** [comment]
>  Over time and several down times, that replication map could get messy, right?
Small addition - there is no replication map. As @f41gh7 already said, every vminsert calculates a set of N vmstorage nodes to write (replicate) every incoming data point to. The set is determined using consistent hashing over metric name and all its labels. This means that data for the same metric with the same set of labels is usually routed to the same set of vmstorage nodes (provided all the destination vmstorage nodes are healthy). If certain vmstorage nodes become unhealthy, then vminsert tries maintaining replication factor by writing data to the remaining healthy vmstorage nodes. This may result in messy data distribution. But this is usually OK in practical cases where the probability of vmstorage downtime is quite low.
