### ISSUE TITLE
sort_by_label: support more than a single label

### ISSUE THREAD

**Issue by jelmd** [VictoriaMetrics/VictoriaMetrics#992]
Wanna have the returned TS in a stable order.

Unfortunately, sorting by a single label [value] does not guarantee a stable order (unless label values are unique for each TS, which is rarely the case). So MetricsQL should allow something like `sort_by_label(q, name0 [, nameN]*)` and sort returned TS by $name0, if both are equal compare $name1 of TS in question and so on ...

**Comment by jelmd** [comment]
Actually found, that if one nests sort_by_label, it seems to do, what is needed - e.g. `sort_by_label(sort_by_label(q, name1), name0)`. But wrt. to the syntax I did not expect this and documentation is silent about it ...

**Comment by valyala** [comment]
@jelmd , VictoriaMetrics gained ability to pass multiple labels to `sort_by_label` function in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/1051d8aa2d6fc0883824d0a84be679d4c1898c81 . This commit will be included in the next release.

**Comment by valyala** [comment]
[VictoriaMetrics v1.52.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) supports passing multiple labels to `sort_by_label()` and `sort_by_label_desc()` functions. Closing this feature request as done.

**Comment by jelmd** [comment]
Very cool! Thanx a lot!
