### ISSUE TITLE
Failed to query VM from grafana

### ISSUE THREAD

**Issue by vuxuanlai** [VictoriaMetrics/VictoriaMetrics#994]
**Describe the bug**
```
{"ts":"2021-01-06T10:49:09.393Z","level":"warn","caller":"VictoriaMetrics/app/vmselect/main.go:106","msg":"remoteAddr: \"10.42.141.0:20221\", X-Forwarded-For: \"10.30.11.11, 10.30.11.11\"; cannot handle more than 2 concurrent search requests during 10s; possible solutions: increase `-search.maxQueueDuration`; increase `-search.maxQueryDuration`; increase `-search.maxConcurrentRequests`; increase server capacity"}

```

**Version**

```
$ ./victoria-metrics-prod --version
victoria-metrics-20201227-122315-tags-v1.51.0-0-g70df5f497
```

I used `vmagent` and `vmsingle` (helm chart) to scrape metrics from k8s cluster. `vmsingle` used to store tsdb and also datasource for grafana. I also use prometheus for scrape metrics on one k8s cluster. From grafana, I query sample via prometheus, it's very fast. However, I can't query anything when datasource is switched to VM.

About my tsdb: 

![Screenshot from 2021-01-06 20-19-40](https://user-images.githubusercontent.com/1458400/103772880-cb1fbc00-505c-11eb-8529-695504be357e.png)

**Comment by hagen1778** [comment]
Hi @vuxuanlai! Could you pls provide more info:
1. What are resources dedicated to VM?
2. Do you use service discovery?
3. What is the ingestion and query rate?
4. What is the latency of served queries?
 
The default Grafana dashboard (from which you made a screenshot) contains panels to answer last two questions. It also contains some hints and troubleshooting panels. I'd appreciate if you can attach screenshots of all the panels.
Pls also take a look at the following link to understand possible resource usage https://github.com/VictoriaMetrics/VictoriaMetrics#capacity-planning

**Comment by vuxuanlai** [comment]
Hi @hagen1778 ,
`1. What are resources dedicated to VM?
`
Resource is configured in helm chart value:
```
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 256m
      memory: 512Mi
```
`2. Do you use service discovery?`
Yes. I used kubernetes_sd_config

`3. What is the ingestion and query rate?`
![Screenshot from 2021-01-07 09-10-18](https://user-images.githubusercontent.com/1458400/103842314-394d9880-50c8-11eb-92cf-97a815ba9402.png)
![Screenshot from 2021-01-07 09-09-50](https://user-images.githubusercontent.com/1458400/103842318-3a7ec580-50c8-11eb-8083-12e7b542cb41.png)

`4. What is the latency of served queries?`
![Screenshot from 2021-01-07 09-12-33](https://user-images.githubusercontent.com/1458400/103842446-86ca0580-50c8-11eb-98ef-0206dffe5af2.png)

**Comment by hagen1778** [comment]
Thanks for the info! Would you mind to share also a query you send to VM/Prometheus which results in that error? Can you also check the CPU/Mem usage on the dashboard and would appreciate a screenshot of `Troubleshooting` row. Btw, are resources (1vCPU and 2GB RAM) dedicated to Prometheus the same as for VM ?

**Comment by vuxuanlai** [comment]
I query k8s resource as pod's RAM, CPU, network,.. usage.
I updated RAM request from 2Gi to 4Gi and it can query tsdb normally. However, resource consumption is quite much. You can see the following screenshot
![Screenshot from 2021-01-08 10-08-42](https://user-images.githubusercontent.com/1458400/103969876-80f02500-5199-11eb-9414-3d32272fdab1.png)

And, I also screenshot about resource usage between Prometheus and VMagent +VMsingle via `kubectl top` command

![Screenshot from 2021-01-08 10-10-43](https://user-images.githubusercontent.com/1458400/103970069-f0661480-5199-11eb-8380-38edffb9bcc1.png)

VM is consuming quite much resource.
Could you plz explain or recommend for configuring VM?

**Comment by hagen1778** [comment]
> I updated RAM request from 2Gi to 4Gi and it can query tsdb normally. However, resource consumption is quite much

Memory consumption is tightly connected to amount of **active series** processed by VM. The more active series you have, the higher usage will be. The math is well explained [here](https://github.com/VictoriaMetrics/VictoriaMetrics#capacity-planning).

> VM is consuming quite much resource.

I find the linked screenshot not informative enough, since it shows the short-term metrics. I'd prefer to see CPU usage over some noticeable period of more than 1h which can be found on the Grafana dashboard. But even so, I don't find it "too high" comparing to Prometheus which seems to consume twice more resources according to that metric. 

I'd recommend to re-check the https://github.com/VictoriaMetrics/VictoriaMetrics#capacity-planning for VM capacity planning. And I'd be happy to give better answer to your question but I still require additional info which was ignored to be provided. Such as: 
* "are resources (1vCPU and 2GB RAM) dedicated to Prometheus the same as for VM ?"
* "I'd appreciate if you can attach screenshots of **all the panels**"  
* or at least "would appreciate a screenshot of Troubleshooting row"

So far, I could recommend to investigate Grafana dashboards for [vmsingle](https://grafana.com/grafana/dashboards/10229) and [vmagent](https://grafana.com/grafana/dashboards/12683) more thoroughly. They should contain most of the metrics and hints which explain resource usage and health state.

**Comment by susmitaganguli** [comment]
Hi,
I face a similar issue. This is message and grafana dashboards cannot connect to VM datasource:

2021-02-17T09:37:52.079Z	warn	VictoriaMetrics/app/vmselect/main.go:106	remoteAddr: "10.116.200.98:49548", X-Forwarded-For: "10.114.10.14, 10.116.208.1, 127.0.0.1, 127.0.0.1"; cannot handle more than 4 concurrent search requests during 10s; possible solutions: increase `-search.maxQueueDuration`; increase `-search.maxQueryDuration`; increase `-search.maxConcurrentRequests`; increase server capacity

flag{name="search.maxConcurrentRequests", value="4"} after increasing the cpu and memory requests:
resources:
    limits:
      cpu: 2000m
      memory: 5120Mi
    requests:
      cpu: 500m
      memory: 4096Mi

vmsingle dashboard doesn't have any data only the above error.

Value for vm_cache_entries{type="storage/hour_metric_ids"} from /metrics page:
vm_cache_entries{type="storage/hour_metric_ids"} 2290235

**Comment by valyala** [comment]
@susmitaganguli , try allocating more CPU for VictoriaMetrics. Take a look also at disk IO activity on the node with VictoriaMetrics - if disk IO activity is high, then it is likely VictoriaMetrics needs more memory for the given workload. It is recommended setting up  [monitoring for VictoriaMetrics](https://victoriametrics.github.io/#monitoring).

**Comment by susmitaganguli** [comment]
Thank you @valyala Will check

**Comment by valyala** [comment]
Closing the issue because of inactivity.

@susmitaganguli , please check whether the issue persists at [the latest release of VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest), and then re-open the issue or create new one if this is the case.
